// Chapter 2〜4（ヒノデ台・オウライ街道・イチバ通り）。完全オリジナルStory。
// learningItemIds は各AreaのN3単元 primary語彙（n3UnitSpecs実測 2026-07-31）のみ。
// grammar questionIds は foundationUnit2/5/6 の実在ID（choice系のみ・matching/fill_blank/orderは使わない）。
// authored_by_ai。human_review_candidate（approvedへは昇格しない）。
import type { ChapterDef } from './chapterRegistry';

/** ─────────── 第2章 ヒノデ台「朝の止まった部屋」 ─────────── */
const CHAPTER_2: ChapterDef = {
  chapterId: 'ch2-hinode-no-asa', order: 2, areaId: 'area02-hinode',
  titleJa: '朝の止まった部屋', titleZh: '早晨停摆的房间',
  incidentJa: '引っ越し初日。部屋の時計は止まり、生活のリズムがまだ何もない',
  incidentZh: '搬家第一天。房间的钟停了，生活的节奏还一片空白',
  openingJa: '切符ひとつで着いた丘の町。借りた部屋の時計は止まったまま。大家のミドリさんが鍵を持って待っている。',
  openingZh: '凭一张车票来到丘上的小镇。租下的房间里，钟停着不走。房东绿婆婆拿着钥匙在等你。',
  startLocationId: 'c2-apartment',
  nextChapterId: 'ch3-hantai-yuki',
  locations: [
    { locationId: 'c2-apartment', nameJa: 'アパートの部屋', nameZh: 'アパートの部屋（公寓房间）', x: 20, y: 74 },
    { locationId: 'c2-morning-market', nameJa: '朝市', nameZh: '朝市（早市）', x: 44, y: 56 },
    { locationId: 'c2-clock-shop', nameJa: '時計店', nameZh: '時計店（钟表店）', x: 64, y: 38 },
    { locationId: 'c2-hill-top', nameJa: '丘の上', nameZh: '丘の上（山丘顶）', x: 84, y: 20 },
  ],
  npcs: [
    { npcId: 'c2-npc-midori', nameJa: '大家のミドリさん', nameZh: '房东绿婆婆', roleJa: 'アパートの大家',
      locationId: 'c2-apartment',
      foggyLineJa: '（鍵を持った人が、部屋の説明をしているようだ……）',
      greetingJa: 'この部屋、朝日がよく入るのよ。いい暮らしになるといいわね。',
      greetingZh: '这个房间早上阳光很好。希望你在这里生活愉快。' },
    { npcId: 'c2-npc-setsu', nameJa: '豆腐屋のセツさん', nameZh: '豆腐店的雪婆婆', roleJa: '朝市の豆腐屋',
      locationId: 'c2-morning-market',
      foggyLineJa: '（湯気の向こうで、店の人が何か勧めている……）',
      greetingJa: '朝ごはん、まだでしょう。あったかいの、あるよ。',
      greetingZh: '还没吃早饭吧？这里有热乎的哦。' },
    { npcId: 'c2-npc-fuuka', nameJa: '時計店のフウカさん', nameZh: '钟表店的风花', roleJa: '時計職人',
      locationId: 'c2-clock-shop',
      foggyLineJa: '（小さな作業台で、誰かが歯車を磨いている……）',
      greetingJa: '止まった時計ね。動かすには、毎日の音がいるの。',
      greetingZh: '停摆的钟啊。想让它走起来，需要每天生活的声音。' },
  ],
  storyBeats: [
    { beatId: 'c2-beat-key',
      textJa: '鍵を受け取ると、部屋の窓から丘の町が見えた。ただ、机の上の時計は止まったままだ。',
      textZh: '接过钥匙，从房间的窗户能望见丘上的小镇。只是，桌上的钟依然停着。' },
    { beatId: 'c2-beat-market-smell',
      textJa: '朝市の湯気とだしの匂い。「食べる」「飲む」が言えると、朝がひとつ動き出した。',
      textZh: '早市升起热气，飘着高汤的香味。会说「吃」和「喝」之后，早晨开始转动了。' },
    { beatId: 'c2-beat-clock-tick',
      textJa: 'フウカさんが時計に耳を当てる。「あなたの一日が決まれば、この子も動きます」',
      textZh: '风花把耳朵贴在钟上。「等你的一天定下来，这孩子也会走起来。」' },
    { beatId: 'c2-beat-rooms',
      textJa: '大きい部屋と小さい部屋、新しい棚と古い棚。比べる言葉で、暮らしの形が見えてきた。',
      textZh: '大房间和小房间，新柜子和旧柜子。会比较之后，生活的样子清晰起来。' },
    { beatId: 'c2-beat-clock-moves',
      textJa: 'カチ、と音がした。止まっていた針が、ゆっくり動き始めた。',
      textZh: '咔哒一声。停着的指针，缓缓走动了起来。' },
    { beatId: 'c2-beat-hill-morning',
      textJa: '丘の上から見る朝の町。あなたの一日は、もうここにある。',
      textZh: '从丘顶眺望清晨的小镇。你的一天，已经在这里了。' },
  ],
  quests: [
    { questId: 'c2q1-receive-key', order: 1, siteLocationId: 'c2-apartment',
      titleJa: '部屋の鍵を受け取る', titleZh: '领取房间的钥匙',
      learnGoalJa: '「起きる」「寝る」の2語で一日の始まりと終わりを言う', learnGoalZh: '用「起きる」「寝る」说出一天的开始和结束',
      estimatedMinutes: 3,
      completionConditionJa: '2語のチェックに正解する', completionConditionZh: '答对2个词的确认题',
      storyIntroJa: 'ミドリさんが尋ねた。「朝は何時ごろ起きるの？」……まだ、うまく答えられない。',
      storyIntroZh: '绿婆婆问：「早上大概几点起床？」……你还答不上来。',
      storyOutcomeJa: '起きる時間と寝る時間を伝えられた。ミドリさんが笑って鍵を渡してくれた。',
      storyOutcomeZh: '你说出了起床和睡觉的时间。绿婆婆笑着把钥匙交给了你。',
      learningItemIds: ['fi-okiru', 'fi-neru'],
      unlocks: { locationIds: ['c2-morning-market'], npcIds: ['c2-npc-midori'], storyBeatIds: ['c2-beat-key'] },
      isChapterFinale: false, adventureXpReward: 20 },
    { questId: 'c2q2-morning-market', order: 2, siteLocationId: 'c2-morning-market',
      titleJa: '朝市で朝ごはん', titleZh: '在早市吃早饭',
      learnGoalJa: '語彙3語（食べる・飲む・買う）＋文法「ます形」で毎日の動作を言う',
      learnGoalZh: '3个词（食べる・飲む・買う）＋语法「ます形」，说出每天的动作',
      estimatedMinutes: 6,
      completionConditionJa: '3語のチェックと文法問題2問・産出1問に正解する',
      completionConditionZh: '答对3个词、2道语法题和1道造句题',
      storyIntroJa: 'セツさんの店から湯気が上がる。頼み方が分かれば、朝ごはんにありつける。',
      storyIntroZh: '雪婆婆的店里升起热气。只要会点单，就能吃上早饭。',
      storyOutcomeJa: '温かい朝ごはんを食べた。朝市の人たちが、あなたの顔を覚えてくれた。',
      storyOutcomeZh: '你吃上了热乎的早饭。早市的人们记住了你的脸。',
      learningItemIds: ['fi-taberu', 'fi-nomu', 'fi-kau'],
      grammarRequirements: [
        { ruleId: 'fr-masu-form', unitFile: 2, questionIds: ['f2q-f2', 'f2q-f3'],
          production: { promptJa: '朝市で、毎朝すること（食べる）を伝える文を組み立ててください。',
            promptZh: '在早市，把「每天早上吃」的句子排好。',
            tokens: ['毎朝', 'パン', 'を', '食べます'] } },
      ],
      unlocks: { locationIds: ['c2-clock-shop'], npcIds: ['c2-npc-setsu'], storyBeatIds: ['c2-beat-market-smell'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c2q3-make-a-day', order: 3, siteLocationId: 'c2-clock-shop',
      titleJa: '一日の形を作る', titleZh: '定下一天的形状',
      learnGoalJa: '語彙3語（する・使う・作る）＋文法「ない形」で「しない」も言えるようにする',
      learnGoalZh: '3个词（する・使う・作る）＋语法「ない形」，也要会说「不做」',
      estimatedMinutes: 6,
      completionConditionJa: '3語のチェックと文法問題2問・産出1問に正解する',
      completionConditionZh: '答对3个词、2道语法题和1道造句题',
      storyIntroJa: 'フウカさんが言う。「時計は、する事としない事が決まると動くんです」',
      storyIntroZh: '风花说：「做什么、不做什么定下来，钟就会走。」',
      storyOutcomeJa: '一日の予定表ができた。時計店の棚の時計が、一斉に時を刻み始めた。',
      storyOutcomeZh: '一天的时间表做好了。钟表店架上的钟，一齐开始了走动。',
      learningItemIds: ['fi-suru', 'fi-tsukau', 'fi-tsukuru'],
      grammarRequirements: [
        { ruleId: 'fr-nai-form', unitFile: 2, questionIds: ['f2q-f4', 'f2q-f5'],
          production: { promptJa: '夜はテレビを見ない、と伝える文を組み立ててください。',
            promptZh: '把「晚上不看电视」的句子排好。',
            tokens: ['夜', 'は', 'テレビ', 'を', '見ません'] } },
      ],
      unlocks: { locationIds: [], npcIds: ['c2-npc-fuuka'], storyBeatIds: ['c2-beat-clock-tick', 'c2-beat-clock-moves'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c2q4-compare-rooms', order: 4, siteLocationId: 'c2-apartment',
      titleJa: '部屋くらべ', titleZh: '比较房间',
      learnGoalJa: '対の形容詞4語（大きい・小さい・新しい・古い）でものの様子を言う',
      learnGoalZh: '4个成对的形容词（大・小・新・旧），描述事物的样子',
      estimatedMinutes: 5,
      completionConditionJa: '4語のチェックに正解する', completionConditionZh: '答对4个词的确认题',
      storyIntroJa: 'ミドリさんが物置の整理を手伝ってほしいと言う。「大きい棚と小さい棚、どっちを部屋に置く？」',
      storyIntroZh: '绿婆婆想请你帮忙整理储物间。「大柜子和小柜子，哪个放你房间？」',
      storyOutcomeJa: '棚を選び、部屋が片づいた。窓からの朝日が、床までまっすぐ届くようになった。',
      storyOutcomeZh: '选好了柜子，房间也收拾干净了。清晨的阳光能一直照到地板上了。',
      learningItemIds: ['fi-ookii', 'fi-chiisai', 'fi-atarashii', 'fi-furui'],
      unlocks: { locationIds: ['c2-hill-top'], npcIds: [], storyBeatIds: ['c2-beat-rooms'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c2q5-explain-my-day', order: 5, siteLocationId: 'c2-hill-top',
      titleJa: '章末：丘の上で一日の流れを話す', titleZh: '章末：在丘顶讲述一天的安排',
      learnGoalJa: '「分かる」「帰る」を加え、一日の流れ（起きる→食べる→する→帰る→寝る）を通しで話す',
      learnGoalZh: '加上「分かる」「帰る」，完整说一遍一天的安排（起床→吃饭→做事→回家→睡觉）',
      estimatedMinutes: 6,
      completionConditionJa: '2語のチェックと4ステップの場面会話をすべて成立させる',
      completionConditionZh: '答对2个词并完成4步场景对话',
      storyIntroJa: '丘の上でミドリさんとセツさんが待っている。「あなたの一日、聞かせて」',
      storyIntroZh: '绿婆婆和雪婆婆在丘顶等着。「说说你的一天吧。」',
      storyOutcomeJa: '一日の流れを最後まで話せた。第2章完了。部屋の時計は、もう止まらない。',
      storyOutcomeZh: '你完整讲述了一天的安排。第二章完成。房间的钟，再也不会停了。',
      learningItemIds: ['fi-wakaru', 'fi-kaeru'],
      unlocks: { locationIds: [], npcIds: [], storyBeatIds: ['c2-beat-hill-morning'] },
      isChapterFinale: true, adventureXpReward: 40 },
  ],
  finaleSteps: [
    { stepId: 'c2f-morning', npcLineJa: '朝、何をしますか。', npcLineZh: '早上做什么？',
      correctJa: '7時に起きます。', usesItemId: 'fi-okiru',
      optionsJa: ['7時に起きます。', '7時に買います。', '7時に作ります。'] },
    { stepId: 'c2f-breakfast', npcLineJa: '朝ごはんは？', npcLineZh: '早饭呢？',
      correctJa: 'パンを食べます。', usesItemId: 'fi-taberu',
      optionsJa: ['パンを食べます。', 'パンを起きます。', 'パンを帰ります。'] },
    { stepId: 'c2f-evening', npcLineJa: '夜は何時に家へ帰りますか。', npcLineZh: '晚上几点回家？',
      correctJa: '6時に帰ります。', usesItemId: 'fi-kaeru',
      optionsJa: ['6時に帰ります。', '6時に食べません。', '6時に大きいです。'] },
    { stepId: 'c2f-night', npcLineJa: '寝る前に何かしますか。', npcLineZh: '睡前做点什么吗？',
      correctJa: 'いいえ、テレビは見ません。すぐ寝ます。', usesItemId: 'fi-neru',
      optionsJa: ['いいえ、テレビは見ません。すぐ寝ます。', 'いいえ、朝ごはんを食べます。', 'いいえ、鍵を受け取ります。'] },
  ],
  reviewReunion: {
    questId: 'c2r-reunion-tofu',
    titleJa: '再会：セツさんの豆腐', titleZh: '重逢：雪婆婆的豆腐',
    letterJa: '朝市に来なくなって、少し心配しています。あのとき覚えたことば、まだ言えますか？　温かいの、用意して待っています。——セツ',
    letterZh: '好久没在早市见到你，有点担心。那时学的词，还会说吗？我备着热乎的，等你来。——雪',
    outcomeJa: '思い出したことばと一緒に、朝市の湯気の匂いも戻ってきた。',
    outcomeZh: '想起了那些词，早市的热气和香味也一起回来了。',
    adventureXpReward: 15,
  },
};

/** ─────────── 第3章 オウライ街道「反対行きの急行」 ─────────── */
const CHAPTER_3: ChapterDef = {
  chapterId: 'ch3-hantai-yuki', order: 3, areaId: 'area03-toorimichi',
  titleJa: '反対行きの急行', titleZh: '坐反方向的快车',
  incidentJa: '急行に乗り間違えて反対方向へ。しかも網棚にカバンを忘れた',
  incidentZh: '搭错了快车，坐去了反方向。而且还把包忘在了行李架上',
  openingJa: '気づいたときには、車窓の景色が逆に流れていた。知らない駅で降りたあなたの手に、カバンはない。',
  openingZh: '回过神来，车窗外的风景在往反方向流动。你在陌生的车站下了车，手里没有包。',
  startLocationId: 'c3-ticket-gate',
  nextChapterId: 'ch4-hajimete-no-otsukai',
  locations: [
    { locationId: 'c3-ticket-gate', nameJa: '改札口', nameZh: '改札口（检票口）', x: 18, y: 76 },
    { locationId: 'c3-platform', nameJa: '2番ホーム', nameZh: '2番ホーム（2号站台）', x: 42, y: 56 },
    { locationId: 'c3-lost-found', nameJa: '忘れ物センター', nameZh: '忘れ物センター（失物招领处）', x: 66, y: 40 },
    { locationId: 'c3-bus-stop', nameJa: 'バス停', nameZh: 'バス停（公交车站）', x: 84, y: 22 },
  ],
  npcs: [
    { npcId: 'c3-npc-kaito', nameJa: '駅員のカイトさん', nameZh: '车站的海斗', roleJa: '改札口の駅員',
      locationId: 'c3-ticket-gate',
      foggyLineJa: '（改札の向こうで、駅員が路線図を指している……）',
      greetingJa: '落ち着いて。ここから戻れますよ。まず行き先を教えてください。',
      greetingZh: '别慌。从这里能回去的。先告诉我你要去哪里。' },
    { npcId: 'c3-npc-nana', nameJa: '忘れ物係のナナさん', nameZh: '失物招领的奈奈', roleJa: '忘れ物センターの係員',
      locationId: 'c3-lost-found',
      foggyLineJa: '（カウンターの奥に、届いた荷物がたくさん並んでいる……）',
      greetingJa: 'どんなカバンですか？　いつ、どの電車で？',
      greetingZh: '是什么样的包？什么时候、哪趟车上丢的？' },
    { npcId: 'c3-npc-goro', nameJa: '運転手のゴロウさん', nameZh: '公交司机五郎', roleJa: 'バスの運転手',
      locationId: 'c3-bus-stop',
      foggyLineJa: '（バスの運転席から、誰かがこちらに声をかけている……）',
      greetingJa: 'この便は丘の町行き。乗るなら前のドアからどうぞ。',
      greetingZh: '这班车开往丘上的小镇。要坐的话请从前门上车。' },
  ],
  storyBeats: [
    { beatId: 'c3-beat-wrong-train',
      textJa: '「駅」と「電車」。この2語が言えた瞬間、駅員さんの説明が急に聞き取れるようになった。',
      textZh: '「车站」和「电车」。会说这两个词的瞬间，站务员的说明忽然能听懂了。' },
    { beatId: 'c3-beat-right-platform',
      textJa: '「乗る」と「降りる」を間違えなければ、もう反対行きには乗らない。2番ホームの案内が読めた。',
      textZh: '只要不弄错「上车」和「下车」，就不会再坐反方向。2号站台的指示牌，你读懂了。' },
    { beatId: 'c3-beat-bag-found',
      textJa: '奥の棚から、見覚えのあるカバンが出てきた。「入る」「出る」まで言えたあなたに、ナナさんが拍手した。',
      textZh: '里面的架子上，出现了那个熟悉的包。连「进」「出」都会说了，奈奈为你鼓掌。' },
    { beatId: 'c3-beat-bus-window',
      textJa: 'バスの窓から、来た道が見える。間違えた道も、戻り方が分かれば怖くない。',
      textZh: '从公交车窗能看到来时的路。就算走错了，只要知道怎么回去，就不可怕。' },
    { beatId: 'c3-beat-map-in-hand',
      textJa: '手の中の路線図に、行ける場所が増えていく。',
      textZh: '手里的线路图上，能去的地方越来越多。' },
    { beatId: 'c3-beat-guide-others',
      textJa: '帰り道、今度はあなたが道を聞かれた。説明できた。もう、迷う側ではない。',
      textZh: '回去的路上，这次轮到别人向你问路。你讲明白了。你已经不再是迷路的那一个。' },
  ],
  quests: [
    { questId: 'c3q1-ask-at-gate', order: 1, siteLocationId: 'c3-ticket-gate',
      titleJa: '改札で尋ねる', titleZh: '在检票口询问',
      learnGoalJa: '「駅」「電車」の2語で今いる場所と乗る物を確認する', learnGoalZh: '用「車站」「電車」确认自己在哪、要坐什么',
      estimatedMinutes: 3,
      completionConditionJa: '2語のチェックに正解する', completionConditionZh: '答对2个词的确认题',
      storyIntroJa: '知らない駅名。まずは駅員さんに、ここがどこか聞くしかない。',
      storyIntroZh: '陌生的站名。只能先问站务员，这里是哪里。',
      storyOutcomeJa: 'ここが「反対行きの終点のひとつ手前」だと分かった。戻る電車はある。',
      storyOutcomeZh: '弄清了这里是「反方向终点站的前一站」。有回去的电车。',
      learningItemIds: ['fi-eki', 'fi-densha'],
      unlocks: { locationIds: ['c3-platform'], npcIds: ['c3-npc-kaito'], storyBeatIds: ['c3-beat-wrong-train'] },
      isChapterFinale: false, adventureXpReward: 20 },
    { questId: 'c3q2-right-platform', order: 2, siteLocationId: 'c3-platform',
      titleJa: '正しいホームに立つ', titleZh: '站上正确的站台',
      learnGoalJa: '語彙2語（乗る・降りる）＋文法「移動先の に/へ」で行き先を言う',
      learnGoalZh: '2个词（乗る・降りる）＋语法「表示目的地的 に/へ」，说出要去的地方',
      estimatedMinutes: 6,
      completionConditionJa: '2語のチェックと文法問題2問・産出1問に正解する',
      completionConditionZh: '答对2个词、2道语法题和1道造句题',
      storyIntroJa: '1番と2番、どちらのホームか。「〜に乗る」「〜で降りる」が言えれば間違えない。',
      storyIntroZh: '1号还是2号站台？只要会说「坐〜」「在〜下车」，就不会再错。',
      storyOutcomeJa: '2番ホームの電車に乗り、忘れ物センターのある駅で降りられた。',
      storyOutcomeZh: '你坐上了2号站台的电车，在有失物招领处的车站下了车。',
      learningItemIds: ['fi-noru', 'fi-oriru'],
      grammarRequirements: [
        { ruleId: 'fr-ni-e-destination', unitFile: 5, questionIds: ['f5q-p2', 'f5q-p3'],
          production: { promptJa: '駅員さんに行き先を伝える文を組み立ててください。',
            promptZh: '把告诉站务员目的地的句子排好。',
            tokens: ['ミナトの', '駅', 'に', '行きます'] } },
      ],
      unlocks: { locationIds: ['c3-lost-found'], npcIds: [], storyBeatIds: ['c3-beat-right-platform'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c3q3-lost-and-found', order: 3, siteLocationId: 'c3-lost-found',
      titleJa: '忘れ物センターで説明する', titleZh: '在失物招领处说明情况',
      learnGoalJa: '語彙2語（入る・出る）＋文法「場所・手段の で」でカバンの状況を説明する',
      learnGoalZh: '2个词（入る・出る）＋语法「表示地点・手段的 で」，说明包的情况',
      estimatedMinutes: 6,
      completionConditionJa: '2語のチェックと文法問題2問・産出1問に正解する',
      completionConditionZh: '答对2个词、2道语法题和1道造句题',
      storyIntroJa: 'ナナさんが台帳を開く。「電車で忘れましたか？　バスで？」……手段の「で」が鍵になる。',
      storyIntroZh: '奈奈翻开登记本。「是在电车上忘的？还是公交上？」……表示手段的「で」是关键。',
      storyOutcomeJa: 'カバンが戻ってきた。中身もそのまま。説明できたから、見つかった。',
      storyOutcomeZh: '包回来了，东西一样不少。因为你说清楚了，所以找到了。',
      learningItemIds: ['fi-hairu', 'fi-deru'],
      grammarRequirements: [
        { ruleId: 'fr-de-place-means', unitFile: 5, questionIds: ['f5q-p4', 'f5q-p5'],
          production: { promptJa: '「電車の中でカバンを忘れた」と伝える文を組み立ててください。',
            promptZh: '把「把包忘在了电车里」的句子排好。',
            tokens: ['電車', 'で', 'カバン', 'を', '忘れました'] } },
      ],
      unlocks: { locationIds: ['c3-bus-stop'], npcIds: ['c3-npc-nana'], storyBeatIds: ['c3-beat-bag-found'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c3q4-bus-home', order: 4, siteLocationId: 'c3-bus-stop',
      titleJa: 'バスで帰る', titleZh: '坐公交回去',
      learnGoalJa: '「バス」「家」の2語で帰り道の乗り物と行き先を言う', learnGoalZh: '用「公交」「家」说出回程的交通工具和目的地',
      estimatedMinutes: 3,
      completionConditionJa: '2語のチェックに正解する', completionConditionZh: '答对2个词的确认题',
      storyIntroJa: '最終の電車はもう出たあと。でも、ゴロウさんのバスがまだ残っている。',
      storyIntroZh: '末班电车已经开走了。不过，五郎的公交车还在。',
      storyOutcomeJa: 'バスに乗れた。窓の外、来た道が逆向きに流れていく。今度は正しい方向だ。',
      storyOutcomeZh: '你坐上了公交。窗外，来时的路反向流过。这次，方向是对的。',
      learningItemIds: ['fi-basu', 'fi-ie'],
      unlocks: { locationIds: [], npcIds: ['c3-npc-goro'], storyBeatIds: ['c3-beat-bus-window', 'c3-beat-map-in-hand'] },
      isChapterFinale: false, adventureXpReward: 20 },
    { questId: 'c3q5-guide-someone', order: 5, siteLocationId: 'c3-ticket-gate',
      titleJa: '章末：今度はあなたが道案内', titleZh: '章末：这次由你来指路',
      learnGoalJa: '「学校」「病院」を加え、行き方を尋ねられて説明する側に回る',
      learnGoalZh: '加上「学校」「医院」，轮到你被问路并做出说明',
      estimatedMinutes: 6,
      completionConditionJa: '2語のチェックと4ステップの場面会話をすべて成立させる',
      completionConditionZh: '答对2个词并完成4步场景对话',
      storyIntroJa: '改札前で、地図を持った人に声をかけられた。「すみません、病院はどこですか？」',
      storyIntroZh: '检票口前，拿着地图的人向你搭话：「不好意思，医院在哪里？」',
      storyOutcomeJa: '道案内が最後まで通じた。第3章完了。もう、この街道で迷わない。',
      storyOutcomeZh: '你把路指到了最后。第三章完成。在这条街道上，你不会再迷路了。',
      learningItemIds: ['fi-gakkou', 'fi-byouin'],
      unlocks: { locationIds: [], npcIds: [], storyBeatIds: ['c3-beat-guide-others'] },
      isChapterFinale: true, adventureXpReward: 40 },
  ],
  finaleSteps: [
    { stepId: 'c3f-where', npcLineJa: 'すみません、病院はどこですか。', npcLineZh: '不好意思，医院在哪里？',
      correctJa: '駅の前です。', usesItemId: 'fi-eki',
      optionsJa: ['駅の前です。', '電車の中です。', 'カバンの中です。'] },
    { stepId: 'c3f-how', npcLineJa: '何で行きますか。', npcLineZh: '怎么去呢？',
      correctJa: 'バスで行きます。', usesItemId: 'fi-basu',
      optionsJa: ['バスで行きます。', 'バスを降ります。', 'バスに忘れます。'] },
    { stepId: 'c3f-board', npcLineJa: 'どこで乗りますか。', npcLineZh: '在哪里上车？',
      correctJa: 'あのバス停で乗ります。', usesItemId: 'fi-noru',
      optionsJa: ['あのバス停で乗ります。', 'あのバス停で出ます。', 'あのバス停で入ります。'] },
    { stepId: 'c3f-get-off', npcLineJa: 'どこで降りますか。', npcLineZh: '在哪里下车？',
      correctJa: '病院の前で降ります。', usesItemId: 'fi-oriru',
      optionsJa: ['病院の前で降ります。', '病院の前で乗ります。', '病院の前で寝ます。'] },
  ],
  reviewReunion: {
    questId: 'c3r-reunion-timetable',
    titleJa: '再会：カイトさんの新しい時刻表', titleZh: '重逢：海斗的新时刻表',
    letterJa: 'ダイヤが新しくなりました。前に覚えた乗り方のことば、思い出しながら確かめに来ませんか。——カイト',
    letterZh: '时刻表更新了。要不要一边回想之前学的乘车用语，一边来确认一下？——海斗',
    outcomeJa: '新しい時刻表も、もう読める。ことばは、使うたびに濃くなる。',
    outcomeZh: '新的时刻表你也能读懂了。语言，越用越清晰。',
    adventureXpReward: 15,
  },
};

/** ─────────── 第4章 イチバ通り「はじめてのおつかい」 ─────────── */
const CHAPTER_4: ChapterDef = {
  chapterId: 'ch4-hajimete-no-otsukai', order: 4, areaId: 'area04-ichiba',
  titleJa: 'はじめてのおつかい', titleZh: '第一次跑腿购物',
  incidentJa: '風邪をひいた隣人に頼まれた買い物。値段と数と頼み方が分からないと何も買えない',
  incidentZh: '受感冒的邻居之托去买东西。不懂价格、数量和请求的说法，就什么也买不成',
  openingJa: 'ドアの隙間から、隣人がメモを差し出した。「ごめん、熱があって……市場で、これを買ってきてくれない？」',
  openingZh: '门缝里，邻居递出一张便条。「抱歉，我发烧了……能帮我去市场买这些吗？」',
  startLocationId: 'c4-veg-stand',
  nextChapterId: 'ch5-ame-no-shotaijo',
  locations: [
    { locationId: 'c4-veg-stand', nameJa: '八百屋', nameZh: '八百屋（蔬果店）', x: 20, y: 72 },
    { locationId: 'c4-counting-table', nameJa: '勘定台', nameZh: '勘定台（结账台）', x: 44, y: 56 },
    { locationId: 'c4-pharmacy', nameJa: '薬屋', nameZh: '薬屋（药店）', x: 66, y: 38 },
    { locationId: 'c4-cat-alley', nameJa: '猫の路地', nameZh: '猫の路地（猫咪小巷）', x: 84, y: 20 },
  ],
  npcs: [
    { npcId: 'c4-npc-masu', nameJa: '八百屋のマスさん', nameZh: '蔬果店的阿升', roleJa: '市場の八百屋の店主',
      locationId: 'c4-veg-stand',
      foggyLineJa: '（威勢のいい声が、値段を叫んでいるようだ……）',
      greetingJa: 'いらっしゃい！　今日はトマトが安いよ！',
      greetingZh: '欢迎欢迎！今天西红柿便宜哦！' },
    { npcId: 'c4-npc-rin', nameJa: '薬屋のリンさん', nameZh: '药店的小凛', roleJa: '薬屋の店主',
      locationId: 'c4-pharmacy',
      foggyLineJa: '（白い棚の前で、店主が瓶のラベルを確かめている……）',
      greetingJa: 'お薬ですか？　どなたが、どんな具合です？',
      greetingZh: '要买药吗？是谁不舒服，什么症状？' },
    { npcId: 'c4-npc-daifuku', nameJa: '市場の猫ダイフク', nameZh: '市场的猫咪大福', roleJa: '市場の看板猫',
      locationId: 'c4-cat-alley',
      foggyLineJa: '（路地の奥で、何かが「にゃあ」と鳴いた……）',
      greetingJa: 'にゃあ。（膝の上が定位置らしい）',
      greetingZh: '喵。（看来你的膝盖成了它的专座）' },
  ],
  storyBeats: [
    { beatId: 'c4-beat-price-heard',
      textJa: '「いくらですか」。たった一言で、市場の値段の霧が晴れた。数字が耳に入ってくる。',
      textZh: '「多少钱？」就这一句话，市场里价格的迷雾散开了。数字开始进入你的耳朵。' },
    { beatId: 'c4-beat-counted',
      textJa: 'ひとつ、ふたつ、みっつ。数えられれば、買いすぎも買い忘れもない。',
      textZh: '一个、两个、三个。会数数，就不会买多，也不会漏买。' },
    { beatId: 'c4-beat-medicine',
      textJa: '「これをください」。リンさんがうなずいて、薬を包んでくれた。頼み方は、優しさの形をしている。',
      textZh: '「请给我这个。」小凛点点头，把药包好递给你。请求的说法，本身就是一种温柔。' },
    { beatId: 'c4-beat-cat-follows',
      textJa: '水を買った帰り、ダイフクがついてきた。猫がいる。水がある。「いる」と「ある」の違いが、路地でストンと腑に落ちた。',
      textZh: '买完水回来的路上，大福跟了上来。有猫（いる），有水（ある）。「いる」和「ある」的区别，在小巷里一下子想通了。' },
    { beatId: 'c4-beat-delivery',
      textJa: '袋いっぱいの買い物を隣人に届けた。「全部ある……！　ありがとう」熱のある顔が、少しゆるんだ。',
      textZh: '你把满满一袋东西送到邻居手上。「全都买齐了……！谢谢你。」发烧的脸上，露出一点笑意。' },
    { beatId: 'c4-beat-market-friend',
      textJa: '市場のみんなが、あなたの名前を覚えた。「また来てね」の声に、送り出される。',
      textZh: '市场里的大家记住了你的名字。「下次再来哦」的声音，送你离开。' },
  ],
  quests: [
    { questId: 'c4q1-ask-price', order: 1, siteLocationId: 'c4-veg-stand',
      titleJa: '値段を聞く', titleZh: '询问价格',
      learnGoalJa: '「いくら」「円」「お金」の3語で値段のやり取りを聞き取る', learnGoalZh: '用「いくら」「円」「お金」听懂价格的往来',
      estimatedMinutes: 4,
      completionConditionJa: '3語のチェックに正解する', completionConditionZh: '答对3个词的确认题',
      storyIntroJa: 'メモの1行目は「トマト」。でも値札が読めない。まず値段を聞くことばから。',
      storyIntroZh: '便条第一行写着「西红柿」。可你看不懂价签。先从询问价格的说法开始。',
      storyOutcomeJa: 'マスさんの「200円！」が聞き取れた。財布の中身と相談できるようになった。',
      storyOutcomeZh: '你听懂了阿升喊的「200日元！」。可以和钱包里的钱商量着买了。',
      learningItemIds: ['fi-ikura', 'fi-en', 'fi-okane'],
      unlocks: { locationIds: ['c4-counting-table'], npcIds: ['c4-npc-masu'], storyBeatIds: ['c4-beat-price-heard'] },
      isChapterFinale: false, adventureXpReward: 20 },
    { questId: 'c4q2-count-and-buy', order: 2, siteLocationId: 'c4-counting-table',
      titleJa: '数えて買う', titleZh: '数着数量买',
      learnGoalJa: '語彙2語（いくつ・これ）＋文法（〜つ/〜人・値段と「いくら」）で数と値段を扱う',
      learnGoalZh: '2个词（いくつ・これ）＋语法（〜つ/〜人・价格与「いくら」），处理数量和价格',
      estimatedMinutes: 6,
      completionConditionJa: '2語のチェックと文法問題2問・産出1問に正解する',
      completionConditionZh: '答对2个词、2道语法题和1道造句题',
      storyIntroJa: 'メモには「みっつ」。指をさして「これ」、数えて「みっつ」。それで買い物は成立する。',
      storyIntroZh: '便条上写着「三个」。手一指说「这个」，数一数说「三个」。这样就能买成东西。',
      storyOutcomeJa: 'トマトを3つ、ちょうどのお金で買えた。おまけに1つ増えていたのは、マスさんの気前だ。',
      storyOutcomeZh: '你用刚好的钱买到了3个西红柿。袋里多出来的那1个，是阿升的心意。',
      learningItemIds: ['fi-ikutsu', 'fi-kore'],
      grammarRequirements: [
        { ruleId: 'fr-counters', unitFile: 6, questionIds: ['f6q-m1', 'f6q-c1'],
          production: { promptJa: 'トマトを3つ買う、と伝える文を組み立ててください。',
            promptZh: '把「买3个西红柿」的句子排好。',
            tokens: ['トマト', 'を', 'みっつ', 'ください'] } },
      ],
      unlocks: { locationIds: ['c4-pharmacy'], npcIds: [], storyBeatIds: ['c4-beat-counted'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c4q3-pharmacy-request', order: 3, siteLocationId: 'c4-pharmacy',
      titleJa: '薬屋でお願いする', titleZh: '在药店提出请求',
      learnGoalJa: '語彙2語（薬・ください）＋文法「買い物の基本表現」で丁寧に頼む',
      learnGoalZh: '2个词（薬・ください）＋语法「购物基本表达」，礼貌地提出请求',
      estimatedMinutes: 6,
      completionConditionJa: '2語のチェックと文法問題2問・産出1問に正解する',
      completionConditionZh: '答对2个词、2道语法题和1道造句题',
      storyIntroJa: 'メモの最後は薬の名前。リンさんは優しいが、何が要るかはあなたが言うしかない。',
      storyIntroZh: '便条最后写的是药名。小凛人很好，但需要什么，只能由你来说。',
      storyOutcomeJa: '薬を受け取れた。「お大事に、と伝えてくださいね」とリンさんが言った。',
      storyOutcomeZh: '你拿到了药。小凛说：「请转告他，好好保重。」',
      learningItemIds: ['fi-kusuri', 'fi-kudasai'],
      grammarRequirements: [
        { ruleId: 'fr-shopping', unitFile: 6, questionIds: ['f6q-u1', 'f6q-u3'],
          production: { promptJa: '薬屋で、この薬をください、と頼む文を組み立ててください。',
            promptZh: '把在药店「请给我这个药」的句子排好。',
            tokens: ['この', '薬', 'を', 'ください'] } },
      ],
      unlocks: { locationIds: ['c4-cat-alley'], npcIds: ['c4-npc-rin'], storyBeatIds: ['c4-beat-medicine'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c4q4-cat-alley', order: 4, siteLocationId: 'c4-cat-alley',
      titleJa: '猫の路地と「ある・いる」', titleZh: '猫咪小巷与「ある・いる」',
      learnGoalJa: '4語（水・猫・ある・いる）で「物のある」と「生き物のいる」を使い分ける',
      learnGoalZh: '用4个词（水・猫・ある・いる）区分「物的ある」和「生物的いる」',
      estimatedMinutes: 5,
      completionConditionJa: '4語のチェックに正解する', completionConditionZh: '答对4个词的确认题',
      storyIntroJa: '水を1本買い足した帰り道、路地の奥で「にゃあ」。……これは「ある」？「いる」？',
      storyIntroZh: '多买了一瓶水回来的路上，小巷深处传来「喵」。……这该用「ある」还是「いる」？',
      storyOutcomeJa: '「猫がいる。水がある」。ダイフクが膝に乗ってきた。合格、ということらしい。',
      storyOutcomeZh: '「有猫（いる），有水（ある）。」大福跳上了你的膝盖。看来这是给你打了及格分。',
      learningItemIds: ['fi-mizu', 'fi-neko', 'fi-aru', 'fi-iru-exist'],
      unlocks: { locationIds: [], npcIds: ['c4-npc-daifuku'], storyBeatIds: ['c4-beat-cat-follows'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c4q5-deliver', order: 5, siteLocationId: 'c4-veg-stand',
      titleJa: '章末：おつかいを届ける', titleZh: '章末：把东西送到',
      learnGoalJa: '「何時」を再確認し、買い物の場面会話（値段→数→お願い→時間）を通す',
      learnGoalZh: '再次确认「几点」，完整走一遍购物场景对话（价格→数量→请求→时间）',
      estimatedMinutes: 6,
      completionConditionJa: '1語のチェックと4ステップの場面会話をすべて成立させる',
      completionConditionZh: '答对1个词并完成4步场景对话',
      storyIntroJa: '帰る前に、マスさんが「おさらいだ」と笑う。「明日も来るかい？　店は何時からか、知ってる？」',
      storyIntroZh: '临走前，阿升笑着说「来复习一下」。「明天还来吗？知道店几点开门吗？」',
      storyOutcomeJa: '買い物の会話が全部通じた。第4章完了。袋の中身は、ひとつも間違っていない。',
      storyOutcomeZh: '购物对话全部顺利完成。第四章完成。袋子里的东西，一样都没买错。',
      learningItemIds: ['fi-nanji'],
      unlocks: { locationIds: [], npcIds: [], storyBeatIds: ['c4-beat-delivery', 'c4-beat-market-friend'] },
      isChapterFinale: true, adventureXpReward: 40 },
  ],
  finaleSteps: [
    { stepId: 'c4f-price', npcLineJa: 'トマト、今日は安いよ。いくらか聞いてみて。', npcLineZh: '西红柿今天便宜哦。问问多少钱吧。',
      correctJa: 'これはいくらですか。', usesItemId: 'fi-ikura',
      optionsJa: ['これはいくらですか。', 'これはいくつですか。', 'これは何時ですか。'] },
    { stepId: 'c4f-count', npcLineJa: '200円だよ。何個いる？', npcLineZh: '200日元。要几个？',
      correctJa: 'みっつください。', usesItemId: 'fi-kudasai',
      optionsJa: ['みっつください。', 'みっつあります。', 'みっつです、猫が。'] },
    { stepId: 'c4f-medicine', npcLineJa: '他に要るものは？', npcLineZh: '还需要别的吗？',
      correctJa: 'この薬をください。', usesItemId: 'fi-kusuri',
      optionsJa: ['この薬をください。', 'この薬がいます。', 'この薬はいくつですか。'] },
    { stepId: 'c4f-time', npcLineJa: '明日も来るかい？　店は9時からだよ。今、何時？', npcLineZh: '明天还来吗？店9点开门。现在几点？',
      correctJa: '今、4時です。また明日来ます。', usesItemId: 'fi-nanji',
      optionsJa: ['今、4時です。また明日来ます。', '今、400円です。また明日買います。', '今、よっつです。また明日数えます。'] },
  ],
  reviewReunion: {
    questId: 'c4r-reunion-daifuku',
    titleJa: '再会：ダイフクの見回り', titleZh: '重逢：大福的巡逻',
    letterJa: 'ダイフクが最近、あなたの部屋の方を見に行くんです。市場のことば、忘れていないか確かめに来ませんか。——リン',
    letterZh: '大福最近总往你住的方向跑。要不要来确认一下，市场的那些词还记不记得？——凛',
    outcomeJa: '値札も看板も、まだちゃんと読める。ダイフクが満足そうに目を細めた。',
    outcomeZh: '价签和招牌，你都还读得懂。大福满意地眯起了眼睛。',
    adventureXpReward: 15,
  },
};

export const CHAPTERS_2_TO_4: ChapterDef[] = [CHAPTER_2, CHAPTER_3, CHAPTER_4];
