// Chapter 5〜7（ユカリの森・ハタラキ街・カタチの遺跡）。完全オリジナルStory。
// learningItemIds は各AreaのN3単元 primary語彙のみ。grammar questionIds は
// foundationUnit3/4 の実在ID（choice系のみ）。authored_by_ai・human_review_candidate。
import type { ChapterDef } from './chapterRegistry';

/** ─────────── 第5章 ユカリの森「雨の日の招待状」 ─────────── */
const CHAPTER_5: ChapterDef = {
  chapterId: 'ch5-ame-no-shotaijo', order: 5, areaId: 'area05-yukari',
  titleJa: '雨の日の招待状', titleZh: '雨天的邀请函',
  incidentJa: '森のお茶会に招かれたが、気持ちを伝える言葉が足りない。しかも当日は雨の予報',
  incidentZh: '受邀参加森林茶会，但表达心情的词还不够用。而且当天预报有雨',
  openingJa: 'ポストに緑色の封筒。「森のお茶会にどうぞ。——ゲン」。嬉しい。でも「嬉しい」って、どう言うんだっけ。',
  openingZh: '信箱里有个绿色的信封。「请来参加森林茶会。——阿源」。你很开心。可是「开心」该怎么说来着？',
  startLocationId: 'c5-forest-path',
  nextChapterId: 'ch6-dengon-memo',
  locations: [
    { locationId: 'c5-forest-path', nameJa: '森の小道', nameZh: '森の小道（森林小路）', x: 20, y: 74 },
    { locationId: 'c5-cafe', nameJa: '森のカフェ', nameZh: '森のカフェ（森林咖啡馆）', x: 44, y: 56 },
    { locationId: 'c5-workshop', nameJa: '木工の工房', nameZh: '木工の工房（木工坊）', x: 66, y: 38 },
    { locationId: 'c5-lakeside', nameJa: '湖のほとり', nameZh: '湖のほとり（湖畔）', x: 84, y: 20 },
  ],
  npcs: [
    { npcId: 'c5-npc-gen', nameJa: '隣人のゲンさん', nameZh: '邻居阿源', roleJa: 'お茶会の主催者',
      locationId: 'c5-forest-path',
      foggyLineJa: '（森の入口で、誰かが傘を数えている……）',
      greetingJa: '来てくれたんだね。雨でも、森はいいものだよ。',
      greetingZh: '你来啦。就算下雨，森林也很美。' },
    { npcId: 'c5-npc-yui', nameJa: 'カフェのユイさん', nameZh: '咖啡馆的结衣', roleJa: '森のカフェの店主',
      locationId: 'c5-cafe',
      foggyLineJa: '（カップの湯気の向こうで、店主が何か尋ねている……）',
      greetingJa: 'お茶、どうだった？　味の感想、聞かせてほしいな。',
      greetingZh: '茶怎么样？想听听你的感想。' },
    { npcId: 'c5-npc-takumi', nameJa: '木工職人のタクミさん', nameZh: '木匠拓海', roleJa: '工房の職人',
      locationId: 'c5-workshop',
      foggyLineJa: '（削りたての木の匂い。職人が手を止めてこちらを見た……）',
      greetingJa: '木工は難しいよ。でも、難しいから面白い。',
      greetingZh: '木工很难哦。但正因为难，才有意思。' },
  ],
  storyBeats: [
    { beatId: 'c5-beat-letter',
      textJa: '「嬉しい」「楽しみ」。気持ちのことばを覚えた分だけ、返事が書けるようになる。',
      textZh: '「开心」「期待」。学会多少表达心情的词，就能写出多少回信。' },
    { beatId: 'c5-beat-tea-taste',
      textJa: '「おいしいです。この味、好きです」。ユイさんの顔が、ぱっと明るくなった。感想は、人を照らす。',
      textZh: '「很好喝。我喜欢这个味道。」结衣的脸一下子亮了起来。感想，能照亮别人。' },
    { beatId: 'c5-beat-carving',
      textJa: '木のスプーン作りは難しい。でも「難しいです、でも楽しいです」と言えたとき、タクミさんは弟子を見る目になった。',
      textZh: '做木勺很难。但当你说出「很难，但是很开心」时，拓海看你的眼神变得像看徒弟一样。' },
    { beatId: 'c5-beat-rain-starts',
      textJa: '雨が降り出した。悲しい？　寂しい？　いや——雨の森の音は、静かで、少し嬉しい。',
      textZh: '雨下起来了。难过吗？寂寞吗？不——雨中森林的声音，很安静，甚至让人有点开心。' },
    { beatId: 'c5-beat-family-talk',
      textJa: '焚き火を囲んで、家族の話になった。国の家族、ここでの友達。話すほど、森は近くなる。',
      textZh: '围着篝火，话题聊到了家人。故乡的家人，这里的朋友。越聊，森林越亲近。' },
    { beatId: 'c5-beat-lake-clear',
      textJa: '雨上がりの湖に、みんなの顔が映っている。気持ちを伝えたら、景色まで澄んだ。',
      textZh: '雨后的湖面，映着大家的脸。把心情说出来之后，连风景都清澈了。' },
  ],
  quests: [
    { questId: 'c5q1-read-invitation', order: 1, siteLocationId: 'c5-forest-path',
      titleJa: '招待状に返事を書く', titleZh: '给邀请函写回信',
      learnGoalJa: '「嬉しい」「楽しい」の2語で招待への気持ちを言う', learnGoalZh: '用「嬉しい」「楽しい」表达对邀请的心情',
      estimatedMinutes: 3,
      completionConditionJa: '2語のチェックに正解する', completionConditionZh: '答对2个词的确认题',
      storyIntroJa: '緑の封筒に、返事を書きたい。まず、この「気持ち」の名前を知ろう。',
      storyIntroZh: '想给绿色的信封回信。先弄清这份「心情」叫什么名字。',
      storyOutcomeJa: '「嬉しいです。楽しみにしています」。返事を出せた。森の小道が開いた。',
      storyOutcomeZh: '「我很开心，很期待。」回信寄出去了。森林的小路打开了。',
      learningItemIds: ['fi-ureshii', 'fi-tanoshii'],
      unlocks: { locationIds: ['c5-cafe'], npcIds: ['c5-npc-gen'], storyBeatIds: ['c5-beat-letter'] },
      isChapterFinale: false, adventureXpReward: 20 },
    { questId: 'c5q2-cafe-impressions', order: 2, siteLocationId: 'c5-cafe',
      titleJa: 'カフェで感想を伝える', titleZh: '在咖啡馆表达感想',
      learnGoalJa: '語彙3語（おいしい・好き・上手）＋文法「は」と「が」で感想文を作る',
      learnGoalZh: '3个词（おいしい・好き・上手）＋语法「は」和「が」，说出感想',
      estimatedMinutes: 6,
      completionConditionJa: '3語のチェックと文法問題2問・産出1問に正解する',
      completionConditionZh: '答对3个词、2道语法题和1道造句题',
      storyIntroJa: 'ユイさんが自家製のお茶を出してくれた。「感想、聞かせて」——それが、この店の会計らしい。',
      storyIntroZh: '结衣端出自家做的茶。「说说感想吧」——这似乎就是这家店的「结账方式」。',
      storyOutcomeJa: '感想が伝わった。ユイさんが「常連さん」と呼んでくれるようになった。',
      storyOutcomeZh: '感想传达到了。结衣开始叫你「常客」了。',
      learningItemIds: ['fi-oishii', 'fi-suki', 'fi-jouzu'],
      grammarRequirements: [
        { ruleId: 'fr-wa-topic', unitFile: 4, questionIds: ['f4q-p1', 'f4q-p2'],
          production: { promptJa: 'このお茶が好きだ、と伝える文を組み立ててください。',
            promptZh: '把「我喜欢这个茶」的句子排好。',
            tokens: ['この', 'お茶', 'が', '好きです'] } },
      ],
      unlocks: { locationIds: ['c5-workshop'], npcIds: ['c5-npc-yui'], storyBeatIds: ['c5-beat-tea-taste'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c5q3-workshop-difficulty', order: 3, siteLocationId: 'c5-workshop',
      titleJa: '工房で「難しい」を言う', titleZh: '在木工坊说出「难」',
      learnGoalJa: '「難しい」「簡単」「便利」の3語で できる・できないの感想を言う',
      learnGoalZh: '用「難しい」「簡単」「便利」3个词，说出会与不会的感受',
      estimatedMinutes: 4,
      completionConditionJa: '3語のチェックに正解する', completionConditionZh: '答对3个词的确认题',
      storyIntroJa: 'お茶会の席で使う木のスプーンを、自分で削ることになった。見るのとやるのは大違いだ。',
      storyIntroZh: '茶会上要用的木勺，居然要自己削。看着容易做着难。',
      storyOutcomeJa: '不格好だが、自分のスプーンができた。「難しい」と言える人は、続けられる人だ。',
      storyOutcomeZh: '虽然样子笨拙，但你做出了自己的木勺。说得出「难」的人，才是能坚持下去的人。',
      learningItemIds: ['fi-muzukashii', 'fi-kantan', 'fi-benri'],
      unlocks: { locationIds: [], npcIds: ['c5-npc-takumi'], storyBeatIds: ['c5-beat-carving'] },
      isChapterFinale: false, adventureXpReward: 20 },
    { questId: 'c5q4-rain-feelings', order: 4, siteLocationId: 'c5-forest-path',
      titleJa: '雨と気持ちのことば', titleZh: '雨与心情的词',
      learnGoalJa: '4語（悲しい・寂しい・恥ずかしい・気持ち）で複雑な気持ちに名前をつける',
      learnGoalZh: '用4个词（悲しい・寂しい・恥ずかしい・気持ち）给复杂的心情命名',
      estimatedMinutes: 5,
      completionConditionJa: '4語のチェックに正解する', completionConditionZh: '答对4个词的确认题',
      storyIntroJa: '雨が降ってきた。お茶会は中止？　みんなの顔が曇る。この空気に、なんて声をかけよう。',
      storyIntroZh: '下雨了。茶会要取消吗？大家的脸都阴了下来。这种时候，该说点什么好呢。',
      storyOutcomeJa: '「雨の森も、いい気持ちですね」。その一言で、お茶会は屋根の下で続くことになった。',
      storyOutcomeZh: '「雨中的森林，感觉也很好啊。」就这一句话，茶会改在屋檐下继续了。',
      learningItemIds: ['fi-kanashii', 'fi-sabishii', 'fi-hazukashii', 'fi-kimochi'],
      unlocks: { locationIds: [], npcIds: [], storyBeatIds: ['c5-beat-rain-starts'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c5q5-family-and-friends', order: 5, siteLocationId: 'c5-cafe',
      titleJa: '家族と友達の話', titleZh: '聊家人和朋友',
      learnGoalJa: '語彙3語（家族・友達・興味）＋文法「を」で身近な人の話をする',
      learnGoalZh: '3个词（家族・友達・興味）＋语法「を」，聊聊身边的人',
      estimatedMinutes: 6,
      completionConditionJa: '3語のチェックと文法問題1問・産出1問に正解する',
      completionConditionZh: '答对3个词、1道语法题和1道造句题',
      storyIntroJa: '焚き火を囲むと、なぜか家族の話になる。国のこと、聞かれたら話せるだろうか。',
      storyIntroZh: '围着篝火，话题不知不觉聊到了家人。要是被问起故乡的事，你能聊起来吗？',
      storyOutcomeJa: '家族の写真を見せながら話せた。ゲンさんも、昔の話をしてくれた。',
      storyOutcomeZh: '你看着家人的照片聊了起来。阿源也讲了他过去的故事。',
      learningItemIds: ['fi-kazoku', 'fi-tomodachi', 'fi-kyoumi'],
      grammarRequirements: [
        { ruleId: 'fr-wo-object', unitFile: 4, questionIds: ['f4q-p3'],
          production: { promptJa: '家族の写真を見せる、と伝える文を組み立ててください。',
            promptZh: '把「给你看家人的照片」的句子排好。',
            tokens: ['家族', 'の', '写真', 'を', '見せます'] } },
      ],
      unlocks: { locationIds: ['c5-lakeside'], npcIds: [], storyBeatIds: ['c5-beat-family-talk'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c5q6-lakeside-finale', order: 6, siteLocationId: 'c5-lakeside',
      titleJa: '章末：湖のほとりで気持ちを伝え合う', titleZh: '章末：在湖畔互诉心情',
      learnGoalJa: '「気分」「関係」を加え、気持ちの場面会話（感想→好み→気分→関係）を通す',
      learnGoalZh: '加上「気分」「関係」，完整走一遍心情场景对话（感想→喜好→心情→关系）',
      estimatedMinutes: 6,
      completionConditionJa: '2語のチェックと4ステップの場面会話をすべて成立させる',
      completionConditionZh: '答对2个词并完成4步场景对话',
      storyIntroJa: '雨上がり。湖のほとりで、ゲンさんが尋ねた。「今日は、どうだった？」',
      storyIntroZh: '雨停了。湖畔，阿源问你：「今天过得怎么样？」',
      storyOutcomeJa: '気持ちを最後まで伝え合えた。第5章完了。この森に、あなたの居場所ができた。',
      storyOutcomeZh: '你们把心情聊到了最后。第五章完成。这片森林里，有了属于你的位置。',
      learningItemIds: ['fi-kibun', 'fi-kankei'],
      unlocks: { locationIds: [], npcIds: [], storyBeatIds: ['c5-beat-lake-clear'] },
      isChapterFinale: true, adventureXpReward: 40 },
  ],
  finaleSteps: [
    { stepId: 'c5f-today', npcLineJa: '今日は、どうだった？', npcLineZh: '今天过得怎么样？',
      correctJa: 'とても楽しかったです。', usesItemId: 'fi-tanoshii',
      optionsJa: ['とても楽しかったです。', 'とても便利でした。', 'とても大きかったです。'] },
    { stepId: 'c5f-tea', npcLineJa: 'ユイのお茶は？', npcLineZh: '结衣的茶怎么样？',
      correctJa: 'おいしかったです。あの味が好きです。', usesItemId: 'fi-oishii',
      optionsJa: ['おいしかったです。あの味が好きです。', '難しかったです。あの味は上手です。', '寂しかったです。あの味は簡単です。'] },
    { stepId: 'c5f-spoon', npcLineJa: 'スプーン作りはどうだった？', npcLineZh: '做木勺感觉如何？',
      correctJa: '難しかったです。でも、楽しかったです。', usesItemId: 'fi-muzukashii',
      optionsJa: ['難しかったです。でも、楽しかったです。', '悲しかったです。でも、便利でした。', '恥ずかしかったです。でも、簡単でした。'] },
    { stepId: 'c5f-mood', npcLineJa: '今の気分は？', npcLineZh: '现在的心情呢？',
      correctJa: 'いい気分です。また来たいです。', usesItemId: 'fi-kibun',
      optionsJa: ['いい気分です。また来たいです。', 'いい関係です。また削りたいです。', 'いい家族です。また雨です。'] },
  ],
  reviewReunion: {
    questId: 'c5r-reunion-recipe',
    titleJa: '再会：ユイさんの新作のお茶', titleZh: '重逢：结衣的新茶',
    letterJa: '新しいお茶ができました。前に覚えた気持ちのことば、まだ言えますか？　感想を聞かせに来てください。——ユイ',
    letterZh: '新茶做好了。之前学的表达心情的词，还会说吗？来跟我说说感想吧。——结衣',
    outcomeJa: '気持ちのことばが戻ってきた。新作の味の感想も、ちゃんと言えた。',
    outcomeZh: '表达心情的词回来了。新茶的感想，你也好好说出来了。',
    adventureXpReward: 15,
  },
};

/** ─────────── 第6章 ハタラキ街「読めない伝言メモ」 ─────────── */
const CHAPTER_6: ChapterDef = {
  chapterId: 'ch6-dengon-memo', order: 6, areaId: 'area06-hataraki',
  titleJa: '読めない伝言メモ', titleZh: '看不懂的留言便条',
  incidentJa: '初出勤の日、机に前任者の伝言メモが残っていた。読めないと今日の仕事が始まらない',
  incidentZh: '第一天上班，桌上留着前任的留言便条。读不懂它，今天的工作就无法开始',
  openingJa: '初出勤。自分の机に、走り書きのメモが一枚。「10時に―――へ連絡。※要確認」。肝心なところが、読めない。',
  openingZh: '第一天上班。自己的桌上有一张潦草的便条：「10点联系———。※需确认」。最关键的地方，你读不懂。',
  startLocationId: 'c6-entrance',
  nextChapterId: 'ch7-ugokidasu-sekiban',
  locations: [
    { locationId: 'c6-entrance', nameJa: '会社の受付', nameZh: '会社の受付（公司前台）', x: 20, y: 74 },
    { locationId: 'c6-desk', nameJa: '自分の机', nameZh: '自分の机（自己的办公桌）', x: 44, y: 56 },
    { locationId: 'c6-meeting-room', nameJa: '会議室', nameZh: '会議室（会议室）', x: 66, y: 38 },
    { locationId: 'c6-rooftop', nameJa: '屋上', nameZh: '屋上（天台）', x: 84, y: 20 },
  ],
  npcs: [
    { npcId: 'c6-npc-aoi', nameJa: '先輩のアオイさん', nameZh: '前辈葵', roleJa: '教育係の先輩',
      locationId: 'c6-desk',
      foggyLineJa: '（隣の席から、先輩が何か説明している……）',
      greetingJa: '分からないことは、分からないって言っていいからね。それが一番早いから。',
      greetingZh: '不懂的就说不懂，没关系的。那样反而最快。' },
    { npcId: 'c6-npc-jun', nameJa: '受付のジュンさん', nameZh: '前台的小纯', roleJa: '受付担当',
      locationId: 'c6-entrance',
      foggyLineJa: '（受付で、来客の名前を確認しているようだ……）',
      greetingJa: 'おはようございます。今日から来る人ですね。伺っています。',
      greetingZh: '早上好。你就是今天报到的人吧，我这边有登记。' },
    { npcId: 'c6-npc-sora', nameJa: '配達員のソラさん', nameZh: '快递员小空', roleJa: '街の配達員',
      locationId: 'c6-rooftop',
      foggyLineJa: '（荷物を抱えた誰かが、宛先を探している……）',
      greetingJa: 'この荷物、この階でいいんですよね？　確認お願いします。',
      greetingZh: '这个包裹是这层楼的没错吧？麻烦确认一下。' },
  ],
  storyBeats: [
    { beatId: 'c6-beat-first-day',
      textJa: '「確認します」「連絡します」。この2語だけで、職場の朝の霧が半分晴れた。',
      textZh: '「我确认一下」「我来联系」。只这两个词，职场清晨的雾就散了一半。' },
    { beatId: 'c6-beat-memo-read',
      textJa: 'アオイさんと一緒にメモを解読した。「10時に倉庫へ連絡。在庫を要確認」——読めれば、動ける。',
      textZh: '你和葵一起破解了便条：「10点联系仓库。库存需确认」——读懂了，就能行动。' },
    { beatId: 'c6-beat-meeting',
      textJa: '会議で初めて手を挙げた。「私は、こう思います。理由は――」。声は小さかったが、全員が振り向いた。',
      textZh: '会议上你第一次举手：「我是这样想的。理由是——」。声音虽小，但所有人都回过了头。' },
    { beatId: 'c6-beat-schedule',
      textJa: '「都合」と「約束」が使えると、予定は絡まらない。ホワイトボードの予定表が、きれいに埋まった。',
      textZh: '会用「方便与否」和「约定」之后，日程就不会打结。白板上的日程表，整齐地填满了。' },
    { beatId: 'c6-beat-delivery-check',
      textJa: '屋上でソラさんの荷物を一緒に確認した。「確認お願いします」が、今日いちばん役に立ったことばだ。',
      textZh: '在天台你帮小空一起核对了包裹。「麻烦确认一下」，是今天最有用的一句话。' },
    { beatId: 'c6-beat-first-report',
      textJa: '終業前、アオイさんに今日の報告をした。「完璧」と言って、先輩は明日のメモを――今度は読める字で――残してくれた。',
      textZh: '下班前，你向葵做了今天的汇报。前辈说了句「完美」，然后给你留了明天的便条——这次，是你读得懂的字。' },
  ],
  quests: [
    { questId: 'c6q1-reception', order: 1, siteLocationId: 'c6-entrance',
      titleJa: '受付で確認と連絡', titleZh: '在前台确认与联系',
      learnGoalJa: '「確認」「連絡」の2語で職場の基本動作を言う', learnGoalZh: '用「確認」「連絡」说出职场的基本动作',
      estimatedMinutes: 3,
      completionConditionJa: '2語のチェックに正解する', completionConditionZh: '答对2个词的确认题',
      storyIntroJa: '受付のジュンさんが内線を指す。「着いたら、先輩に連絡してくださいね」',
      storyIntroZh: '前台的小纯指着内线电话：「到了之后，请联系你的前辈。」',
      storyOutcomeJa: '内線でアオイさんに連絡できた。「じゃあ、机まで案内するね」',
      storyOutcomeZh: '你用内线联系上了葵。「那我带你去你的座位吧。」',
      learningItemIds: ['fi-kakunin', 'fi-renraku'],
      unlocks: { locationIds: ['c6-desk'], npcIds: ['c6-npc-jun'], storyBeatIds: ['c6-beat-first-day'] },
      isChapterFinale: false, adventureXpReward: 20 },
    { questId: 'c6q2-decode-memo', order: 2, siteLocationId: 'c6-desk',
      titleJa: '伝言メモを解読する', titleZh: '破解留言便条',
      learnGoalJa: '語彙3語（伝える・説明・情報）＋文法「〜てください」で依頼の形を知る',
      learnGoalZh: '3个词（伝える・説明・情報）＋语法「〜てください」，学会请求的形式',
      estimatedMinutes: 6,
      completionConditionJa: '3語のチェックと文法問題2問・産出1問に正解する',
      completionConditionZh: '答对3个词、2道语法题和1道造句题',
      storyIntroJa: 'メモの字は癖が強い。アオイさんが言う。「分からない字は、分からないと伝えて」',
      storyIntroZh: '便条上的字迹很难认。葵说：「不认识的字，就直说不认识。」',
      storyOutcomeJa: 'メモの全文が分かった。「10時に倉庫へ連絡。在庫を要確認」。最初の仕事が動き出す。',
      storyOutcomeZh: '便条全文弄明白了：「10点联系仓库。库存需确认」。你的第一项工作开始运转。',
      learningItemIds: ['fi-tsutaeru', 'fi-setsumei', 'fi-jouhou'],
      grammarRequirements: [
        { ruleId: 'fr-te-kudasai', unitFile: 3, questionIds: ['f3q-f1', 'f3q-f2'],
          production: { promptJa: '「もう一度説明してください」とお願いする文を組み立ててください。',
            promptZh: '把「请再说明一次」的请求句排好。',
            tokens: ['もう一度', '説明', 'して', 'ください'] } },
      ],
      unlocks: { locationIds: ['c6-meeting-room'], npcIds: ['c6-npc-aoi'], storyBeatIds: ['c6-beat-memo-read'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c6q3-first-meeting', order: 3, siteLocationId: 'c6-meeting-room',
      titleJa: '会議で意見を言う', titleZh: '在会议上发表意见',
      learnGoalJa: '4語（意見・理由・思う・考える）で「こう思います。理由は〜」の形を作る',
      learnGoalZh: '用4个词（意見・理由・思う・考える）搭出「我这样想，理由是〜」的句式',
      estimatedMinutes: 5,
      completionConditionJa: '4語のチェックに正解する', completionConditionZh: '答对4个词的确认题',
      storyIntroJa: '午後の定例会議。「新しい人の目で、何か気づいたことは？」と司会が振ってきた。',
      storyIntroZh: '下午的例会上，主持人把话题抛给了你：「以新人的眼光，有没有注意到什么？」',
      storyOutcomeJa: '意見と理由をセットで言えた。会議室のホワイトボードに、あなたの提案が書き残された。',
      storyOutcomeZh: '你把意见和理由一起说了出来。会议室的白板上，留下了你的提案。',
      learningItemIds: ['fi-iken', 'fi-riyuu', 'fi-omou', 'fi-kangaeru'],
      unlocks: { locationIds: [], npcIds: [], storyBeatIds: ['c6-beat-meeting'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c6q4-adjust-schedule', order: 4, siteLocationId: 'c6-meeting-room',
      titleJa: '予定を調整する', titleZh: '调整日程',
      learnGoalJa: '語彙4語（予定・都合・約束・予約）＋文法「て形」で段取りを組む',
      learnGoalZh: '4个词（予定・都合・約束・予約）＋语法「て形」，安排好流程',
      estimatedMinutes: 7,
      completionConditionJa: '4語のチェックと文法問題2問・産出1問に正解する',
      completionConditionZh: '答对4个词、2道语法题和1道造句题',
      storyIntroJa: '来週の打ち合わせ、3人の都合が合わない。カレンダーとにらめっこが始まった。',
      storyIntroZh: '下周的碰头会，三个人的时间凑不到一起。你开始和日历大眼瞪小眼。',
      storyOutcomeJa: '全員の都合が合う日を見つけ、会議室も予約できた。約束は、ことばで組み立てる。',
      storyOutcomeZh: '你找到了所有人都方便的日子，还订好了会议室。约定，是用语言搭起来的。',
      learningItemIds: ['fi-yotei', 'fi-tsugou', 'fi-yakusoku', 'fi-yoyaku'],
      grammarRequirements: [
        { ruleId: 'fr-te-g1a', unitFile: 3, questionIds: ['f3q-f4', 'f3q-f5'],
          production: { promptJa: '「予定を確認して、連絡します」と伝える文を組み立ててください。',
            promptZh: '把「确认好日程后联系你」的句子排好。',
            tokens: ['予定', 'を', '確認して', '連絡します'] } },
      ],
      unlocks: { locationIds: ['c6-rooftop'], npcIds: [], storyBeatIds: ['c6-beat-schedule'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c6q5-report-to-aoi', order: 5, siteLocationId: 'c6-rooftop',
      titleJa: '章末：先輩に一日を報告する', titleZh: '章末：向前辈汇报这一天',
      learnGoalJa: '「相談」「方法」を加え、報告の場面会話（確認→意見→調整→相談）を通す',
      learnGoalZh: '加上「相談」「方法」，完整走一遍汇报场景对话（确认→意见→调整→商量）',
      estimatedMinutes: 6,
      completionConditionJa: '2語のチェックと4ステップの場面会話をすべて成立させる',
      completionConditionZh: '答对2个词并完成4步场景对话',
      storyIntroJa: '終業前。屋上でアオイさんが缶コーヒーを差し出した。「で、今日はどうだった？」',
      storyIntroZh: '快下班时，葵在天台递给你一罐咖啡：「那么，今天怎么样？」',
      storyOutcomeJa: '報告・連絡・相談が一日で全部できた。第6章完了。明日のメモは、もう怖くない。',
      storyOutcomeZh: '报告、联系、商量，一天里你全做到了。第六章完成。明天的便条，再也不可怕了。',
      learningItemIds: ['fi-soudan', 'fi-houhou'],
      unlocks: { locationIds: [], npcIds: ['c6-npc-sora'], storyBeatIds: ['c6-beat-delivery-check', 'c6-beat-first-report'] },
      isChapterFinale: true, adventureXpReward: 40 },
  ],
  finaleSteps: [
    { stepId: 'c6f-memo', npcLineJa: '朝のメモの件、どうなった？', npcLineZh: '早上便条那件事，办得怎么样了？',
      correctJa: '倉庫に連絡して、在庫を確認しました。', usesItemId: 'fi-kakunin',
      optionsJa: ['倉庫に連絡して、在庫を確認しました。', '倉庫を説明して、在庫を約束しました。', '倉庫と相談して、在庫を予約しました。'] },
    { stepId: 'c6f-opinion', npcLineJa: '会議では、どんな話をしたの？', npcLineZh: '会议上你说了什么？',
      correctJa: '意見を言いました。理由も説明しました。', usesItemId: 'fi-iken',
      optionsJa: ['意見を言いました。理由も説明しました。', '都合を言いました。予定も予約しました。', '方法を言いました。情報も確認しました。'] },
    { stepId: 'c6f-schedule', npcLineJa: '来週の打ち合わせは？', npcLineZh: '下周的碰头会呢？',
      correctJa: 'みんなの都合を聞いて、決めました。', usesItemId: 'fi-tsugou',
      optionsJa: ['みんなの都合を聞いて、決めました。', 'みんなの気分を聞いて、忘れました。', 'みんなの理由を聞いて、寝ました。'] },
    { stepId: 'c6f-consult', npcLineJa: '困ったことがあったら？', npcLineZh: '要是遇到困难了怎么办？',
      correctJa: 'すぐ相談します。', usesItemId: 'fi-soudan',
      optionsJa: ['すぐ相談します。', 'すぐ予約します。', 'すぐ説明を忘れます。'] },
  ],
  reviewReunion: {
    questId: 'c6r-reunion-newmemo',
    titleJa: '再会：アオイさんの抜き打ちメモ', titleZh: '重逢：葵的突击便条',
    letterJa: '机に新しいメモを置きました。前のことば、まだ読めるか試してみて。読めたら、屋上でコーヒーをおごります。——アオイ',
    letterZh: '我在你桌上放了张新便条。试试之前学的词还认不认得。认得的话，天台的咖啡我请。——葵',
    outcomeJa: 'メモは全部読めた。屋上のコーヒーは、達成の味がした。',
    outcomeZh: '便条全都读懂了。天台的咖啡，是达成目标的味道。',
    adventureXpReward: 15,
  },
};

/** ─────────── 第7章 カタチの遺跡「動き出す石版」 ─────────── */
const CHAPTER_7: ChapterDef = {
  chapterId: 'ch7-ugokidasu-sekiban', order: 7, areaId: 'area07-katachi',
  titleJa: '動き出す石版', titleZh: '开始变化的石板',
  incidentJa: '遺跡の石版の文字が毎晩少しずつ変わっていく。変化を記録できる人が必要だ',
  incidentZh: '遗迹石板上的文字每晚都在一点点变化。需要有人能把变化记录下来',
  openingJa: '「石版の文字が、昨日と違う」。案内人のシオリさんは困っていた。変化を言葉にできる人を、遺跡は待っていた。',
  openingZh: '「石板上的文字，和昨天不一样了。」向导诗织很困扰。遗迹在等待一个能把变化说成语言的人。',
  startLocationId: 'c7-ruins-gate',
  nextChapterId: 'ch8-kotoba-no-tou',
  locations: [
    { locationId: 'c7-ruins-gate', nameJa: '遺跡の入口', nameZh: '遺跡の入口（遗迹入口）', x: 20, y: 74 },
    { locationId: 'c7-stone-hall', nameJa: '石版の間', nameZh: '石版の間（石板之间）', x: 44, y: 56 },
    { locationId: 'c7-research-tent', nameJa: '調査テント', nameZh: '調査テント（调查帐篷）', x: 66, y: 38 },
    { locationId: 'c7-observatory', nameJa: '見晴らし台', nameZh: '見晴らし台（瞭望台）', x: 84, y: 20 },
  ],
  npcs: [
    { npcId: 'c7-npc-shiori', nameJa: '案内人のシオリさん', nameZh: '向导诗织', roleJa: '遺跡の案内人',
      locationId: 'c7-ruins-gate',
      foggyLineJa: '（入口で、案内人が石版の拓本を広げている……）',
      greetingJa: 'よく来てくれました。この遺跡、今ちょっと大変なんです。',
      greetingZh: '你来得正好。这处遗迹，现在有点不太平。' },
    { npcId: 'c7-npc-hakase', nameJa: '研究者のミナカタ先生', nameZh: '研究员南方老师', roleJa: '文字の研究者',
      locationId: 'c7-research-tent',
      foggyLineJa: '（テントの中で、誰かが書類の山と格闘している……）',
      greetingJa: '記録は、変化を言葉にすることです。あなた、向いていますよ。',
      greetingZh: '所谓记录，就是把变化变成语言。你很有这方面的天分。' },
    { npcId: 'c7-npc-iwao', nameJa: '石工のイワオさん', nameZh: '石匠岩夫', roleJa: '石版の修復職人',
      locationId: 'c7-stone-hall',
      foggyLineJa: '（ノミの音が、一定のリズムで響いている……）',
      greetingJa: '石は正直だ。続けた分だけ、形になる。',
      greetingZh: '石头最诚实。坚持多少，就成形多少。' },
  ],
  storyBeats: [
    { beatId: 'c7-beat-gate',
      textJa: '「状況」と「問題」。この2語が言えると、シオリさんの説明が一枚の地図のように整理されて聞こえた。',
      textZh: '「状况」和「问题」。会说这两个词之后，诗织的说明听起来就像一张整理好的地图。' },
    { beatId: 'c7-beat-first-record',
      textJa: '「文字が変わりました。線が増えました」。あなたの最初の記録が、調査ノートの1ページ目になった。',
      textZh: '「文字变了。线条增加了。」你的第一条记录，成了调查笔记的第一页。' },
    { beatId: 'c7-beat-pattern',
      textJa: '始まるもの、終わるもの、続くもの。石版の変化には、順番があった。',
      textZh: '有开始的，有结束的，有持续的。石板的变化，是有顺序的。' },
    { beatId: 'c7-beat-connect',
      textJa: '「最近」「つまり」「それで」。つなぎ言葉を置くと、バラバラだった記録が一本の物語になった。',
      textZh: '「最近」「也就是说」「所以」。放上连接词，零散的记录就连成了一个故事。' },
    { beatId: 'c7-beat-habit',
      textJa: '毎晩同じ時刻に記録する。それが習慣になったころ、石版の変化の規則が見えてきた。',
      textZh: '每晚在同一时刻记录。当这成为习惯时，石板变化的规律浮现了出来。' },
    { beatId: 'c7-beat-summit',
      textJa: '見晴らし台から、歩いてきた島々が全部見えた。石版の最後の文字は、こう読めた——「ことばは、旅をする」。',
      textZh: '从瞭望台上，能看到你一路走来的所有岛屿。石板最后的文字，是这样读的——「语言，在旅行」。' },
  ],
  quests: [
    { questId: 'c7q1-hear-situation', order: 1, siteLocationId: 'c7-ruins-gate',
      titleJa: '入口で状況を聞く', titleZh: '在入口了解状况',
      learnGoalJa: '「状況」「問題」の2語で何が起きているかを整理する', learnGoalZh: '用「状況」「問題」梳理发生了什么',
      estimatedMinutes: 3,
      completionConditionJa: '2語のチェックに正解する', completionConditionZh: '答对2个词的确认题',
      storyIntroJa: 'シオリさんの説明は早口だ。要点は2つ——今の状況と、何が問題か。',
      storyIntroZh: '诗织说话很快。要点有两个——现在的状况，和问题出在哪。',
      storyOutcomeJa: '状況が飲み込めた。石版は「生きて」いて、記録者を待っている。',
      storyOutcomeZh: '你搞清了状况。石板是「活的」，正在等待记录它的人。',
      learningItemIds: ['fi-joukyou', 'fi-mondai'],
      unlocks: { locationIds: ['c7-stone-hall'], npcIds: ['c7-npc-shiori'], storyBeatIds: ['c7-beat-gate'] },
      isChapterFinale: false, adventureXpReward: 20 },
    { questId: 'c7q2-record-changes', order: 2, siteLocationId: 'c7-stone-hall',
      titleJa: '変化を記録する', titleZh: '记录变化',
      learnGoalJa: '語彙3語（変わる・増える・減る）＋文法「ない形」で「変わらない」も記録する',
      learnGoalZh: '3个词（変わる・増える・減る）＋语法「ない形」，连「没变」也要记录',
      estimatedMinutes: 6,
      completionConditionJa: '3語のチェックと文法問題1問・産出1問に正解する',
      completionConditionZh: '答对3个词、1道语法题和1道造句题',
      storyIntroJa: '石版の前に立つ。昨日の拓本と見比べる。増えた線、減った線、変わらない線。',
      storyIntroZh: '你站在石板前，对照昨天的拓本。增加的线，减少的线，没变的线。',
      storyOutcomeJa: '最初の記録ができた。ミナカタ先生が「これは大発見の予感」とつぶやいた。',
      storyOutcomeZh: '第一条记录完成了。南方老师喃喃道：「这有大发现的预感。」',
      learningItemIds: ['fi-kawaru', 'fi-fueru', 'fi-heru'],
      grammarRequirements: [
        { ruleId: 'fr-masu-nai-choice', unitFile: 2, questionIds: ['f2q-c1'],
          production: { promptJa: '「この線は変わりません」と記録する文を組み立ててください。',
            promptZh: '把「这条线没有变化」的记录句排好。',
            tokens: ['この', '線', 'は', '変わりません'] } },
      ],
      unlocks: { locationIds: ['c7-research-tent'], npcIds: ['c7-npc-iwao'], storyBeatIds: ['c7-beat-first-record'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c7q3-begin-end-continue', order: 3, siteLocationId: 'c7-research-tent',
      titleJa: '始まり・終わり・続き', titleZh: '开始・结束・持续',
      learnGoalJa: '4語（始める・終わる・続く・続ける）で変化の段階に名前をつける',
      learnGoalZh: '用4个词（始める・終わる・続く・続ける）给变化的阶段命名',
      estimatedMinutes: 5,
      completionConditionJa: '4語のチェックに正解する', completionConditionZh: '答对4个词的确认题',
      storyIntroJa: 'ミナカタ先生が過去の記録を広げた。「変化には種類があります。始まる変化、終わる変化、続く変化」',
      storyIntroZh: '南方老师摊开过去的记录：「变化是分种类的。开始的变化，结束的变化，持续的变化。」',
      storyOutcomeJa: '変化を4種類に分類できた。記録ノートに、初めて「規則性あり」と書けた。',
      storyOutcomeZh: '你把变化分成了4类。调查笔记上，第一次写下了「存在规律」。',
      learningItemIds: ['fi-hajimeru', 'fi-owaru', 'fi-tsuzuku', 'fi-tsuzukeru'],
      unlocks: { locationIds: [], npcIds: ['c7-npc-hakase'], storyBeatIds: ['c7-beat-pattern'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c7q4-connecting-words', order: 4, siteLocationId: 'c7-research-tent',
      titleJa: 'つなぎ言葉で報告書を書く', titleZh: '用连接词写报告',
      learnGoalJa: '4語（最近・つまり・それで・多分）で記録を一本の説明につなぐ',
      learnGoalZh: '用4个词（最近・つまり・それで・多分）把记录连成一段说明',
      estimatedMinutes: 5,
      completionConditionJa: '4語のチェックに正解する', completionConditionZh: '答对4个词的确认题',
      storyIntroJa: '記録は溜まった。でもバラバラだ。「最近〜。つまり〜。それで〜」の形に組み直そう。',
      storyIntroZh: '记录攒了不少，但很零散。用「最近〜。也就是说〜。所以〜」的形式重新组织吧。',
      storyOutcomeJa: '報告書が一本の筋になった。シオリさんが読んで、「これなら村のみんなにも説明できる」。',
      storyOutcomeZh: '报告连成了一条线。诗织读完说：「这样就能向村里的大家说明了。」',
      learningItemIds: ['fi-saikin', 'fi-tsumari', 'fi-sorede', 'fi-tabun'],
      unlocks: { locationIds: [], npcIds: [], storyBeatIds: ['c7-beat-connect'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c7q5-habit-decides', order: 5, siteLocationId: 'c7-stone-hall',
      titleJa: '決めて、慣れて、習慣にする', titleZh: '决定、习惯、成为日常',
      learnGoalJa: '語彙4語（決める・決まる・慣れる・習慣）＋文法「て形」で記録の段取りを言う',
      learnGoalZh: '4个词（決める・決まる・慣れる・習慣）＋语法「て形」，说出记录的流程',
      estimatedMinutes: 7,
      completionConditionJa: '4語のチェックと文法問題1問・産出1問に正解する',
      completionConditionZh: '答对4个词、1道语法题和1道造句题',
      storyIntroJa: 'イワオさんが言う。「記録は一晩じゃ意味がない。毎晩やる。決めて、慣れて、習慣にする」',
      storyIntroZh: '岩夫说：「记录一晚上没有意义。要每晚做。先决定，再习惯，最后成为日常。」',
      storyOutcomeJa: '記録が習慣になった。7日目の夜、石版の変化がぴたりと予測と一致した。',
      storyOutcomeZh: '记录成了习惯。第七天夜里，石板的变化和你的预测完全一致。',
      learningItemIds: ['fi-kimeru', 'fi-kimaru', 'fi-nareru', 'fi-shuukan'],
      grammarRequirements: [
        { ruleId: 'fr-te-g1b', unitFile: 3, questionIds: ['f3q-c1'],
          production: { promptJa: '「毎晩記録を書いて、寝ます」と伝える文を組み立ててください。',
            promptZh: '把「每晚写完记录再睡」的句子排好。',
            tokens: ['毎晩', '記録', 'を', '書いて', '寝ます'] } },
      ],
      unlocks: { locationIds: ['c7-observatory'], npcIds: [], storyBeatIds: ['c7-beat-habit'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c7q6-ask-for-help', order: 6, siteLocationId: 'c7-observatory',
      titleJa: '章末：見晴らし台で助けを求める', titleZh: '章末：在瞭望台请求帮助',
      learnGoalJa: '「大変」「必要」を加え、困った状況の場面会話（状況→問題→依頼→理由）を通す',
      learnGoalZh: '加上「大変」「必要」，完整走一遍求助场景对话（状况→问题→请求→理由）',
      estimatedMinutes: 6,
      completionConditionJa: '2語のチェックと4ステップの場面会話をすべて成立させる',
      completionConditionZh: '答对2个词并完成4步场景对话',
      storyIntroJa: '嵐の予報。石版を守る覆いを一晩で作るには、人手が足りない。村へ助けを求めに行こう。',
      storyIntroZh: '预报有暴风雨。要在一夜之间做好保护石板的罩子，人手不够。去村里求助吧。',
      storyOutcomeJa: '説明が通じ、村の人たちが集まってくれた。第7章完了。石版は、嵐を越えた。',
      storyOutcomeZh: '你的说明起了作用，村里的人都来帮忙了。第七章完成。石板，挺过了暴风雨。',
      learningItemIds: ['fi-taihen', 'fi-hitsuyou'],
      unlocks: { locationIds: [], npcIds: [], storyBeatIds: ['c7-beat-summit'] },
      isChapterFinale: true, adventureXpReward: 40 },
  ],
  finaleSteps: [
    { stepId: 'c7f-situation', npcLineJa: 'どうしました？　何かあったんですか。', npcLineZh: '怎么了？发生什么事了？',
      correctJa: '大変な状況です。嵐が来ます。', usesItemId: 'fi-taihen',
      optionsJa: ['大変な状況です。嵐が来ます。', '便利な状況です。嵐が減ります。', '簡単な問題です。嵐が慣れます。'] },
    { stepId: 'c7f-problem', npcLineJa: '何が問題なんですか。', npcLineZh: '问题出在哪里？',
      correctJa: '石版を守る覆いが必要です。', usesItemId: 'fi-hitsuyou',
      optionsJa: ['石版を守る覆いが必要です。', '石版を守る覆いが習慣です。', '石版を守る覆いが最近です。'] },
    { stepId: 'c7f-request', npcLineJa: '私たちに、何ができますか。', npcLineZh: '我们能做点什么？',
      correctJa: '手伝ってください。人手が足りません。', usesItemId: 'fi-mondai',
      optionsJa: ['手伝ってください。人手が足りません。', '寝てください。人手が増えました。', '慣れてください。問題が終わりました。'] },
    { stepId: 'c7f-reason', npcLineJa: 'どうして今夜なんですか。', npcLineZh: '为什么必须是今晚？',
      correctJa: '状況が変わるからです。朝には嵐が来ます。', usesItemId: 'fi-kawaru',
      optionsJa: ['状況が変わるからです。朝には嵐が来ます。', '習慣が減るからです。朝には記録が寝ます。', '理由が増えるからです。朝には石版が帰ります。'] },
  ],
  reviewReunion: {
    questId: 'c7r-reunion-newlines',
    titleJa: '再会：石版の新しい線', titleZh: '重逢：石板上的新线条',
    letterJa: '石版にまた新しい線が現れました。前に覚えた「変化のことば」で、一緒に記録しませんか。——シオリ',
    letterZh: '石板上又出现了新的线条。要不要用之前学的「变化之词」，一起来记录？——诗织',
    outcomeJa: '記録のことばは、まだ手の中にあった。新しい線も、ちゃんと言葉にできた。',
    outcomeZh: '记录用的词，还好好握在你手里。新的线条，也被你好好写成了语言。',
    adventureXpReward: 15,
  },
};

export const CHAPTERS_5_TO_7: ChapterDef[] = [CHAPTER_5, CHAPTER_6, CHAPTER_7];
