// Chapter 8〜10（ソラノ塔・カタリ港・オモイデ庭園=常設施設の導入章）。完全オリジナルStory。
// 施設エリアの章は「その施設を使う意味」を物語にする。恒久ロックなし・施設本体の機能は変更しない。
// learningItemIds は実在fi-*のみ（再遭遇語は復習として意味を持たせる）。authored_by_ai。
import type { ChapterDef } from './chapterRegistry';

/** 第8章 ソラノ塔「書き言葉の入館証」— N2文法178項目への導入 */
const CHAPTER_8: ChapterDef = {
  chapterId: 'ch8-kotoba-no-tou', order: 8, areaId: 'area08-sorano',
  titleJa: '書き言葉の入館証', titleZh: '书面语的入馆证',
  incidentJa: '塔の書庫は「書き言葉」で試す入館証がないと入れない。基礎のしくみだけでは足りない',
  incidentZh: '塔中书库需要用「书面语」考取的入馆证才能进入。只靠基础的语法还不够',
  openingJa: 'island一番高い塔。司書が言う。「上の階ほど、ことばは硬く、正確になります。まず入館証を」',
  openingZh: '岛上最高的塔。司书说：「越往上，语言越正式、越精确。请先考入馆证。」',
  startLocationId: 'c8-tou-gate',
  nextChapterId: 'ch9-katari-minato',
  locations: [
    { locationId: 'c8-tou-gate', nameJa: '塔の受付', nameZh: '塔の受付（塔的前台）', x: 20, y: 74 },
    { locationId: 'c8-reading-room', nameJa: '閲覧室', nameZh: '閲覧室（阅览室）', x: 44, y: 56 },
    { locationId: 'c8-shelf-178', nameJa: '178の書架', nameZh: '178の書架（178书架）', x: 66, y: 38 },
    { locationId: 'c8-observation', nameJa: '塔の展望室', nameZh: '塔の展望室（塔顶展望室）', x: 84, y: 20 },
  ],
  npcs: [
    { npcId: 'c8-npc-fumi', nameJa: '司書のフミさん', nameZh: '司书芙美', roleJa: '塔の司書',
      locationId: 'c8-tou-gate',
      foggyLineJa: '（受付で、司書が分厚い台帳をめくっている……）',
      greetingJa: 'ようこそ。ここは急がない場所です。読んで、書いて、確かめて。',
      greetingZh: '欢迎。这里是不用着急的地方。读一读，写一写，再确认。' },
    { npcId: 'c8-npc-roka', nameJa: '写本係のロカさん', nameZh: '抄写员洛卡', roleJa: '閲覧室の写本係',
      locationId: 'c8-reading-room',
      foggyLineJa: '（ペン先の音だけが、静かに続いている……）',
      greetingJa: '声のことばと、紙のことばは少し違う。それが分かれば大丈夫。',
      greetingZh: '口头的语言和纸上的语言有点不一样。明白这一点就没问题。' },
    { npcId: 'c8-npc-tobira', nameJa: '書架の番人トビラさん', nameZh: '书架守卫户扉', roleJa: '178の書架の番人',
      locationId: 'c8-shelf-178',
      foggyLineJa: '（178の棚の奥から、鍵の束の音がする……）',
      greetingJa: 'この棚は178ある。全部でなくていい。今日の1つを選びなさい。',
      greetingZh: '这里有178个书架。不必全部读完。选出今天的那一个就好。' },
  ],
  storyBeats: [
    { beatId: 'c8-beat-gate', textJa: '「読む」と「書く」。塔ではこの2語が、歩くことと同じ意味を持つ。',
      textZh: '「读」和「写」。在塔里，这两个词就等于走路。' },
    { beatId: 'c8-beat-groups', textJa: '動詞の3グループが分かると、写本の文字が急に整列して見えた。しくみは、塔の階段でもあった。',
      textZh: '弄懂动词的3个类别后，抄本上的文字忽然变得整齐。语法结构，原来就是塔的阶梯。' },
    { beatId: 'c8-beat-shelf', textJa: '178の書架は、上から読む必要はない。覚えたい棚から開けていい——番人はそう言って鍵を渡した。',
      textZh: '178个书架，不必从上往下读。想记住哪一格，就从哪一格打开——守卫这么说着，把钥匙交给了你。' },
    { beatId: 'c8-beat-compare', textJa: '二つの言い方を選んで比べる。どちらが硬いか、どちらが話し言葉か。比べた分だけ、棚に灯りがつく。',
      textZh: '选出两种说法来比较。哪个更书面，哪个更口语。比较多少，书架上就亮起多少灯。' },
    { beatId: 'c8-beat-pass', textJa: '入館証に、あなたの名前が刻まれた。塔は今日から、いつ来てもいい場所になった。',
      textZh: '入馆证上刻下了你的名字。从今天起，这座塔成了你随时可以来的地方。' },
    { beatId: 'c8-beat-view', textJa: '展望室から見ると、歩いてきた島々のことばが、全部この塔へ続いていた。',
      textZh: '从展望室望去，一路走来的岛屿上的语言，全都通向这座塔。' },
  ],
  quests: [
    { questId: 'c8q1-gate-pass', order: 1, siteLocationId: 'c8-tou-gate',
      titleJa: '受付で「読む・書く」', titleZh: '在前台掌握「读・写」',
      learnGoalJa: '「読む」「書く」の2語で塔での学び方を知る', learnGoalZh: '用「読む」「書く」了解塔中的学习方式',
      estimatedMinutes: 3,
      completionConditionJa: '2語のチェックに正解する', completionConditionZh: '答对2个词的确认题',
      storyIntroJa: 'フミさんが台帳を開いた。「入館証の試験は簡単。読めること、書けること」',
      storyIntroZh: '芙美翻开台账：「入馆证的考试很简单。会读，会写。」',
      storyOutcomeJa: '試験の申込みができた。閲覧室への扉が開いた。',
      storyOutcomeZh: '你报上了名。通往阅览室的门开了。',
      learningItemIds: ['fi-yomu', 'fi-kaku'],
      unlocks: { locationIds: ['c8-reading-room'], npcIds: ['c8-npc-fumi'], storyBeatIds: ['c8-beat-gate'] },
      isChapterFinale: false, adventureXpReward: 20 },
    { questId: 'c8q2-scribe-test', order: 2, siteLocationId: 'c8-reading-room',
      titleJa: '写本係の基礎試験', titleZh: '抄写员的基础考试',
      learnGoalJa: '語彙2語（勉強・調べる）＋文法「動詞の3グループ」で書き言葉の土台を確かめる',
      learnGoalZh: '2个词（勉強・調べる）＋语法「动词的3个类别」，确认书面语的基础',
      estimatedMinutes: 6,
      completionConditionJa: '2語のチェックと文法問題1問・産出1問に正解する',
      completionConditionZh: '答对2个词、1道语法题和1道造句题',
      storyIntroJa: 'ロカさんが問題用紙を差し出す。「基礎のしくみが身についているか、見せてください」',
      storyIntroZh: '洛卡递来考卷：「让我看看，基础的语法结构你掌握了没有。」',
      storyOutcomeJa: '基礎試験に合格。「塔の上の階は、この土台の続きですよ」とロカさんが言った。',
      storyOutcomeZh: '基础考试通过了。洛卡说：「塔上层的内容，就是这个基础的延伸。」',
      learningItemIds: ['fi-benkyo', 'fi-shiraberu'],
      grammarRequirements: [
        { ruleId: 'fr-verb-groups', unitFile: 2, questionIds: ['f2q-f1'],
          production: { promptJa: '「毎日、日本語を勉強します」と書く文を組み立ててください。',
            promptZh: '把「每天学习日语」的句子排好。',
            tokens: ['毎日', '日本語', 'を', '勉強します'] } },
      ],
      unlocks: { locationIds: ['c8-shelf-178'], npcIds: ['c8-npc-roka'], storyBeatIds: ['c8-beat-groups'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c8q3-shelf-keys', order: 3, siteLocationId: 'c8-shelf-178',
      titleJa: '178の書架の鍵', titleZh: '178书架的钥匙',
      learnGoalJa: '「覚える」「有名」の2語で、塔の使い方（好きな棚から・順序自由）を知る',
      learnGoalZh: '用「覚える」「有名」了解塔的用法（想读哪格读哪格・不限顺序）',
      estimatedMinutes: 4,
      completionConditionJa: '2語のチェックに正解する', completionConditionZh: '答对2个词的确认题',
      storyIntroJa: 'トビラさんが言う。「基礎を終えていなくても、この棚は開けていい。ただし、開けた棚は覚えること」',
      storyIntroZh: '户扉说：「就算基础还没学完，也可以打开这些书架。但打开过的，要记住。」',
      storyOutcomeJa: '最初の棚の鍵をもらった。N2の文型は、もう遠い場所のことばではない。',
      storyOutcomeZh: '你拿到了第一格书架的钥匙。N2的句型，不再是遥远的语言了。',
      learningItemIds: ['fi-oboeru', 'fi-yuumei'],
      unlocks: { locationIds: ['c8-observation'], npcIds: ['c8-npc-tobira'], storyBeatIds: ['c8-beat-shelf'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c8q4-choose-compare', order: 4, siteLocationId: 'c8-observation',
      titleJa: '章末：選んで、比べて、入館証', titleZh: '章末：选择、比较、领取入馆证',
      learnGoalJa: '「選ぶ」「比べる」を加え、書き言葉の場面会話（読む→書く→選ぶ→比べる）を通す',
      learnGoalZh: '加上「選ぶ」「比べる」，完整走一遍书面语场景对话（读→写→选→比）',
      estimatedMinutes: 6,
      completionConditionJa: '2語のチェックと4ステップの場面会話をすべて成立させる',
      completionConditionZh: '答对2个词并完成4步场景对话',
      storyIntroJa: '展望室で最終試験。フミさんが二枚の紙を並べた。「どちらが書き言葉か、選んで、理由を」',
      storyIntroZh: '展望室里的最终考试。芙美摆出两张纸：「哪张是书面语？选出来，并说明理由。」',
      storyOutcomeJa: '入館証を受け取った。第8章完了。ソラノ塔の178の棚が、あなたの学習計画に加わった。',
      storyOutcomeZh: '你领到了入馆证。第八章完成。空之塔的178个书架，加入了你的学习计划。',
      learningItemIds: ['fi-erabu', 'fi-kuraberu'],
      unlocks: { locationIds: [], npcIds: [], storyBeatIds: ['c8-beat-compare', 'c8-beat-pass', 'c8-beat-view'] },
      isChapterFinale: true, adventureXpReward: 40 },
  ],
  finaleSteps: [
    { stepId: 'c8f-read', npcLineJa: '塔では、まず何をしますか。', npcLineZh: '在塔里，首先要做什么？',
      correctJa: '文型の説明を読みます。', usesItemId: 'fi-yomu',
      optionsJa: ['文型の説明を読みます。', '文型の説明を寝ます。', '文型の説明を降ります。'] },
    { stepId: 'c8f-write', npcLineJa: '読んだあとは？', npcLineZh: '读完之后呢？',
      correctJa: '例文を書きます。', usesItemId: 'fi-kaku',
      optionsJa: ['例文を書きます。', '例文を買います。', '例文を数えます。'] },
    { stepId: 'c8f-choose', npcLineJa: '178もあります。全部やりますか。', npcLineZh: '有178个。要全部做完吗？',
      correctJa: 'いいえ、今日の1つを選びます。', usesItemId: 'fi-erabu',
      optionsJa: ['いいえ、今日の1つを選びます。', 'いいえ、今日の1つを忘れます。', 'いいえ、今日の1つを閉めます。'] },
    { stepId: 'c8f-compare', npcLineJa: '似た文型が二つあったら？', npcLineZh: '遇到两个相似的句型怎么办？',
      correctJa: '例文を比べて、違いを確かめます。', usesItemId: 'fi-kuraberu',
      optionsJa: ['例文を比べて、違いを確かめます。', '例文を捨てて、塔を出ます。', '例文を歌って、覚えません。'] },
  ],
  reviewReunion: {
    questId: 'c8r-reunion-shelf',
    titleJa: '再会：フミさんの返却棚', titleZh: '重逢：芙美的还书架',
    letterJa: '返却棚に、あなたが前に開けた棚の本が戻っています。中のことば、まだ覚えていますか。——フミ',
    letterZh: '还书架上，放着你之前打开过的那格书。里面的词，还记得吗？——芙美',
    outcomeJa: '棚の灯りが、もう一度点いた。覚え直したことばは、前より消えにくい。',
    outcomeZh: '书架的灯又亮了。重新记住的词，比之前更不容易消失。',
    adventureXpReward: 15 },
};

/** 第9章 カタリ港「声に出す日」— AI会話への導入 */
const CHAPTER_9: ChapterDef = {
  chapterId: 'ch9-katari-minato', order: 9, areaId: 'area09-katari',
  titleJa: '声に出す日', titleZh: '开口说话的日子',
  incidentJa: '覚えたことばが、声に出すと出てこない。港の人たちは「使った分しか残らない」と言う',
  incidentZh: '记住的词，一开口就想不起来。港口的人说：「只有用过的才会留下。」',
  openingJa: '船の汽笛が聞こえる港。ここは読む場所ではなく、話す場所だ。今日、初めて声に出す。',
  openingZh: '能听到汽笛声的港口。这里不是用来读的地方，而是用来说的地方。今天，你要第一次开口。',
  startLocationId: 'c9-pier',
  nextChapterId: 'ch10-omoide-no-akari',
  locations: [
    { locationId: 'c9-pier', nameJa: '桟橋', nameZh: '桟橋（栈桥）', x: 20, y: 74 },
    { locationId: 'c9-waiting-room', nameJa: '待合室', nameZh: '待合室（候船室）', x: 44, y: 56 },
    { locationId: 'c9-lighthouse', nameJa: '灯台', nameZh: '灯台（灯塔）', x: 66, y: 38 },
    { locationId: 'c9-deck', nameJa: '船のデッキ', nameZh: '船のデッキ（甲板）', x: 84, y: 20 },
  ],
  npcs: [
    { npcId: 'c9-npc-umi', nameJa: '船長のウミさん', nameZh: '船长阿海', roleJa: '連絡船の船長',
      locationId: 'c9-pier',
      foggyLineJa: '（桟橋の先で、船長が出航の準備をしている……）',
      greetingJa: 'ことばは荷物と同じ。積んだら、降ろして使わないとな。',
      greetingZh: '语言和货物一样。装上了船，就得卸下来用。' },
    { npcId: 'c9-npc-lee', nameJa: '旅人のリーさん', nameZh: '旅人小李', roleJa: '外から来た旅人',
      locationId: 'c9-waiting-room',
      foggyLineJa: '（待合室で、誰かが地図を広げて困っている……）',
      greetingJa: '私も日本語を勉強中です。お互い、間違えながら行きましょう。',
      greetingZh: '我也在学日语。咱们就一边出错一边前进吧。' },
    { npcId: 'c9-npc-touka', nameJa: '灯台守のトウカさん', nameZh: '灯塔看守灯花', roleJa: '灯台の記録係',
      locationId: 'c9-lighthouse',
      foggyLineJa: '（灯台の上から、望遠鏡がこちらを向いた……）',
      greetingJa: '話した会話は、この灯台が全部記録しています。あとで読み直せますよ。',
      greetingZh: '你说过的对话，这座灯塔都记录着。之后可以重新读。' },
  ],
  storyBeats: [
    { beatId: 'c9-beat-first-voice', textJa: '「聞く」と「見る」。会話は、話す前の二つから始まっていた。',
      textZh: '「听」和「看」。对话在开口之前，就已经从这两件事开始了。' },
    { beatId: 'c9-beat-lee', textJa: 'リーさんに出身を聞かれ、答えた。覚えた語彙が、初めて会話の中で仕事をした。',
      textZh: '小李问起你的家乡，你回答了。记住的词汇，第一次在对话里派上了用场。' },
    { beatId: 'c9-beat-record', textJa: '灯台の記録を読み返す。言えなかった言い回しに、トウカさんが印をつけてくれた。「次はここを言い直しましょう」',
      textZh: '重读灯塔的记录。没说出来的表达，灯花帮你做了记号：「下次就从这里重说吧。」' },
    { beatId: 'c9-beat-feeling', textJa: '「話せた」という経験は、単語帳のどのページにも書いていない感覚だった。',
      textZh: '「我说出来了」这种经验，是单词本的任何一页都没写过的感觉。' },
    { beatId: 'c9-beat-habit-voice', textJa: '船長が笑う。「毎日3分でいい。声は、筋肉と同じだ」',
      textZh: '船长笑着说：「每天3分钟就够。声音和肌肉是一样的。」' },
    { beatId: 'c9-beat-deck', textJa: 'デッキの上、風の中で今日の会話を思い返す。港は、明日もここにある。',
      textZh: '甲板上，你在风里回想今天的对话。港口，明天也会在这里。' },
  ],
  quests: [
    { questId: 'c9q1-listen-first', order: 1, siteLocationId: 'c9-pier',
      titleJa: '桟橋で耳をならす', titleZh: '在栈桥练耳朵',
      learnGoalJa: '「聞く」「見る」の2語で、会話の前にすることを知る', learnGoalZh: '用「聞く」「見る」了解开口前要做的事',
      estimatedMinutes: 3,
      completionConditionJa: '2語のチェックに正解する', completionConditionZh: '答对2个词的确认题',
      storyIntroJa: 'ウミさんが言う。「いきなり話すな。まず相手の顔を見て、最後まで聞く」',
      storyIntroZh: '阿海说：「别一上来就说。先看着对方，把话听完。」',
      storyOutcomeJa: '港の会話の型が分かった。待合室のリーさんが手を振っている。',
      storyOutcomeZh: '你明白了港口对话的路数。候船室的小李在向你招手。',
      learningItemIds: ['fi-kiku', 'fi-miru'],
      unlocks: { locationIds: ['c9-waiting-room'], npcIds: ['c9-npc-umi'], storyBeatIds: ['c9-beat-first-voice'] },
      isChapterFinale: false, adventureXpReward: 20 },
    { questId: 'c9q2-talk-with-lee', order: 2, siteLocationId: 'c9-waiting-room',
      titleJa: 'リーさんと出身の話', titleZh: '和小李聊家乡',
      learnGoalJa: '「出身」「日本語」の2語で、学んだ語彙を会話で使う意味を知る',
      learnGoalZh: '用「出身」「日本語」体会「学过的词要在对话里用」',
      estimatedMinutes: 4,
      completionConditionJa: '2語のチェックに正解する', completionConditionZh: '答对2个词的确认题',
      storyIntroJa: 'リーさんが尋ねた。「ご出身は？」——第1章で覚えたことばの出番だ。',
      storyIntroZh: '小李问：「你是哪里人？」——第一章学过的词，该出场了。',
      storyOutcomeJa: '会話が3往復続いた。使ったことばは、確かに手に残る感じがした。',
      storyOutcomeZh: '对话来回了三轮。用过的词，确实有种握在手里的感觉。',
      learningItemIds: ['fi-shusshin', 'fi-nihongo'],
      unlocks: { locationIds: ['c9-lighthouse'], npcIds: ['c9-npc-lee'], storyBeatIds: ['c9-beat-lee'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c9q3-lighthouse-log', order: 3, siteLocationId: 'c9-lighthouse',
      titleJa: '灯台の記録と言い直し', titleZh: '灯塔的记录与重说',
      learnGoalJa: '「感じる」「経験」の2語で、会話→レポート→言い直し→復習の流れを知る',
      learnGoalZh: '用「感じる」「経験」了解 对话→报告→重说→复习 的循环',
      estimatedMinutes: 4,
      completionConditionJa: '2語のチェックに正解する', completionConditionZh: '答对2个词的确认题',
      storyIntroJa: 'トウカさんが記録簿を開く。「話しっぱなしはもったいない。読み返して、言い直すんです」',
      storyIntroZh: '灯花翻开记录簿：「说完就丢太可惜了。要重读，再重说一遍。」',
      storyOutcomeJa: '言えなかった一文を言い直せた。記録簿に「再会予定」の日付が入った。',
      storyOutcomeZh: '没说出来的那句话，你重新说出来了。记录簿上写下了「重逢预定」的日期。',
      learningItemIds: ['fi-kanjiru', 'fi-keiken'],
      unlocks: { locationIds: ['c9-deck'], npcIds: ['c9-npc-touka'], storyBeatIds: ['c9-beat-record', 'c9-beat-feeling'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c9q4-deck-promise', order: 4, siteLocationId: 'c9-deck',
      titleJa: '章末：デッキで毎日の約束', titleZh: '章末：在甲板上定下每天的约定',
      learnGoalJa: '「頑張る」「自由」を加え、会話の場面（聞く→答える→感想→続ける宣言）を通す',
      learnGoalZh: '加上「頑張る」「自由」，完整走一遍对话场景（听→答→感想→坚持宣言）',
      estimatedMinutes: 6,
      completionConditionJa: '2語のチェックと4ステップの場面会話をすべて成立させる',
      completionConditionZh: '答对2个词并完成4步场景对话',
      storyIntroJa: '出航前のデッキで、ウミさんが聞いた。「で、明日からどうする？」',
      storyIntroZh: '起航前的甲板上，阿海问：「那，明天开始怎么办？」',
      storyOutcomeJa: '毎日3分の約束をした。第9章完了。カタリ港は「毎日来る場所」になった。',
      storyOutcomeZh: '你许下了每天3分钟的约定。第九章完成。语之港成了「每天都来的地方」。',
      learningItemIds: ['fi-ganbaru', 'fi-jiyuu'],
      unlocks: { locationIds: [], npcIds: [], storyBeatIds: ['c9-beat-habit-voice', 'c9-beat-deck'] },
      isChapterFinale: true, adventureXpReward: 40 },
  ],
  finaleSteps: [
    { stepId: 'c9f-listen', npcLineJa: '会話で一番大事なことは？', npcLineZh: '对话里最重要的是什么？',
      correctJa: '最後まで聞くことです。', usesItemId: 'fi-kiku',
      optionsJa: ['最後まで聞くことです。', '最後まで書くことです。', '最後まで比べることです。'] },
    { stepId: 'c9f-origin', npcLineJa: '（リーさん）ご出身はどちらですか。', npcLineZh: '（小李）你是哪里人？',
      correctJa: '出身は中国です。', usesItemId: 'fi-shusshin',
      optionsJa: ['出身は中国です。', '出身は日本語です。', '出身は経験です。'] },
    { stepId: 'c9f-feel', npcLineJa: '今日、初めて声に出してみて、どうでしたか。', npcLineZh: '今天第一次开口，感觉怎么样？',
      correctJa: '緊張しましたが、話せたと感じました。', usesItemId: 'fi-kanjiru',
      optionsJa: ['緊張しましたが、話せたと感じました。', '緊張しましたが、読めたと数えました。', '緊張しましたが、選べたと閉めました。'] },
    { stepId: 'c9f-continue', npcLineJa: 'で、明日からどうする？', npcLineZh: '那，明天开始怎么办？',
      correctJa: '毎日3分、頑張ります。', usesItemId: 'fi-ganbaru',
      optionsJa: ['毎日3分、頑張ります。', '毎日3分、忘れます。', '毎日3分、降ります。'] },
  ],
  reviewReunion: {
    questId: 'c9r-reunion-log',
    titleJa: '再会：トウカさんの記録簿', titleZh: '重逢：灯花的记录簿',
    letterJa: '記録簿の「再会予定」の日が来ました。あのとき言い直した一文、まだ言えますか。——トウカ',
    letterZh: '记录簿上「重逢预定」的日子到了。那句你重说过的话，现在还说得出来吗？——灯花',
    outcomeJa: '声に出したことばが、また一段深く残った。灯台の光が一度、大きく回った。',
    outcomeZh: '说出口的那句话，又深深留下了一层。灯塔的光，大大地转了一圈。',
    adventureXpReward: 15 },
};

/** 第10章 オモイデ庭園「灯りの消えた花壇」— 間隔反復・復習への導入 */
const CHAPTER_10: ChapterDef = {
  chapterId: 'ch10-omoide-no-akari', order: 10, areaId: 'area10-omoide',
  titleJa: '灯りの消えた花壇', titleZh: '熄了灯的花坛',
  incidentJa: '庭園の花壇は「思い出したことば」で灯る。放っておくと、灯りはひとつずつ消えていく',
  incidentZh: '庭园的花坛靠「想起来的词」点亮。放着不管，灯就会一盏一盏熄灭',
  openingJa: '夕方の庭園。手入れ人が、消えかけた花壇の灯りを見つめていた。「消える前に、会いに来てくれますか」',
  openingZh: '傍晚的庭园。园丁望着花坛里将熄的灯。「在熄灭之前，能来见见它们吗？」',
  startLocationId: 'c10-garden-gate',
  nextChapterId: null,
  locations: [
    { locationId: 'c10-garden-gate', nameJa: '庭園の門', nameZh: '庭園の門（庭园之门）', x: 20, y: 74 },
    { locationId: 'c10-flowerbed', nameJa: '再会の花壇', nameZh: '再会の花壇（重逢花坛）', x: 44, y: 56 },
    { locationId: 'c10-bench', nameJa: '静かなベンチ', nameZh: '静かなベンチ（安静的长椅）', x: 66, y: 38 },
    { locationId: 'c10-hilltop-lantern', nameJa: '丘の大灯籠', nameZh: '丘の大灯籠（山丘大灯笼）', x: 84, y: 20 },
  ],
  npcs: [
    { npcId: 'c10-npc-niwa', nameJa: '手入れ人のニワさん', nameZh: '园丁庭婆婆', roleJa: '庭園の手入れ人',
      locationId: 'c10-garden-gate',
      foggyLineJa: '（じょうろの水音と、小さな鼻歌が聞こえる……）',
      greetingJa: '忘れるのは、悪いことじゃないの。会いに来る理由ができるから。',
      greetingZh: '忘记不是坏事。因为这样才有了再来相见的理由。' },
    { npcId: 'c10-npc-hotaru', nameJa: '灯り係のホタルさん', nameZh: '掌灯人小萤', roleJa: '花壇の灯り係',
      locationId: 'c10-flowerbed',
      foggyLineJa: '（花壇の間で、小さな灯りがひとつ、ふっと消えた……）',
      greetingJa: '翌日、3日後、7日後。灯りが弱る日は、だいたい決まっているんです。',
      greetingZh: '第二天、3天后、7天后。灯变弱的日子，其实是有规律的。' },
    { npcId: 'c10-npc-shion', nameJa: '記憶園芸家のシオンさん', nameZh: '记忆园艺家紫苑', roleJa: '定着の研究家',
      locationId: 'c10-bench',
      foggyLineJa: '（ベンチで、誰かが押し花のノートをめくっている……）',
      greetingJa: '思い出せた回数だけ、根が深くなる。植物と同じですよ。',
      greetingZh: '想起来的次数越多，根就扎得越深。和植物一样。' },
  ],
  storyBeats: [
    { beatId: 'c10-beat-gate', textJa: '静かな庭に、忘れかけの灯りが並ぶ。「忘れる」は、ここでは再会の合図だった。',
      textZh: '安静的庭园里，排着将被遗忘的灯。「忘记」在这里，是重逢的信号。' },
    { beatId: 'c10-beat-relight', textJa: '思い出せたことばの花壇に、灯りが戻った。準備はいらない。来るだけでいい。',
      textZh: '想起来的词的花坛里，灯又亮了。不需要准备。来了就好。' },
    { beatId: 'c10-beat-bench', textJa: '忙しい日ほど、この庭の3分が効く——シオンさんのノートには、そう書いてあった。',
      textZh: '越是忙碌的日子，这庭园里的3分钟越有用——紫苑的笔记本上这么写着。' },
    { beatId: 'c10-beat-cycle', textJa: '翌日・3日・7日。灯り係の帳面は、あなたの復習予定表と同じものだった。',
      textZh: '次日・3天・7天。掌灯人的账本，和你的复习计划表是同一样东西。' },
    { beatId: 'c10-beat-lantern', textJa: '丘の大灯籠に火が入った。island中で覚えたことばの灯りが、ここから一望できる。',
      textZh: '山丘上的大灯笼点亮了。在群岛各处记住的词的灯光，从这里一览无余。' },
    { beatId: 'c10-beat-end', textJa: '旅は続く。でも、どこまで行っても、この庭はことばの帰る場所だ。',
      textZh: '旅程还在继续。但无论走多远，这座庭园都是语言回家的地方。' },
  ],
  quests: [
    { questId: 'c10q1-quiet-gate', order: 1, siteLocationId: 'c10-garden-gate',
      titleJa: '門で「忘れる」に出会う', titleZh: '在门口遇见「忘记」',
      learnGoalJa: '「静か」「忘れる」の2語で、庭園の役割（忘れる前に再会する）を知る',
      learnGoalZh: '用「静か」「忘れる」了解庭园的作用（在忘记之前重逢）',
      estimatedMinutes: 3,
      completionConditionJa: '2語のチェックに正解する', completionConditionZh: '答对2个词的确认题',
      storyIntroJa: 'ニワさんが門を開けた。「ここは静かでしょう。忘れかけたことばの声が、聞こえるくらいに」',
      storyIntroZh: '庭婆婆打开了门：「这里很安静吧。安静到能听见那些快被忘记的词的声音。」',
      storyOutcomeJa: '庭園の意味が分かった。花壇の方から、小さな灯りがひとつ揺れた。',
      storyOutcomeZh: '你明白了庭园的意义。花坛那边，一盏小灯轻轻晃了晃。',
      learningItemIds: ['fi-shizuka', 'fi-wasureru'],
      unlocks: { locationIds: ['c10-flowerbed'], npcIds: ['c10-npc-niwa'], storyBeatIds: ['c10-beat-gate'] },
      isChapterFinale: false, adventureXpReward: 20 },
    { questId: 'c10q2-relight', order: 2, siteLocationId: 'c10-flowerbed',
      titleJa: '花壇の灯りを戻す', titleZh: '点回花坛的灯',
      learnGoalJa: '「準備」「利用」の2語で、復習の使い方（準備不要・すき間時間で利用）を知る',
      learnGoalZh: '用「準備」「利用」了解复习的用法（不用准备・利用碎片时间）',
      estimatedMinutes: 4,
      completionConditionJa: '2語のチェックに正解する', completionConditionZh: '答对2个词的确认题',
      storyIntroJa: 'ホタルさんが弱った灯りを指す。「これ、あなたが前に覚えたことばです。思い出せますか」',
      storyIntroZh: '小萤指着一盏变弱的灯：「这是你以前记住的词。还想得起来吗？」',
      storyOutcomeJa: '思い出したことばの灯りが戻った。復習に準備はいらないと、体で分かった。',
      storyOutcomeZh: '想起来的词，灯亮回来了。复习不需要准备——这一点，你用身体记住了。',
      learningItemIds: ['fi-junbi', 'fi-riyou'],
      unlocks: { locationIds: ['c10-bench'], npcIds: ['c10-npc-hotaru'], storyBeatIds: ['c10-beat-relight'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c10q3-busy-days', order: 3, siteLocationId: 'c10-bench',
      titleJa: 'ベンチで「忙しい」と向き合う', titleZh: '在长椅上面对「忙碌」',
      learnGoalJa: '「忙しい」「複雑」の2語で、続かない日の対処（短く・簡単に）を知る',
      learnGoalZh: '用「忙しい」「複雑」了解坚持不下去的日子怎么办（短一点・简单一点）',
      estimatedMinutes: 4,
      completionConditionJa: '2語のチェックに正解する', completionConditionZh: '答对2个词的确认题',
      storyIntroJa: 'シオンさんがノートを見せた。「忙しい日は、複雑なことをしなくていい。3分の再会だけで根は残ります」',
      storyIntroZh: '紫苑给你看笔记：「忙的日子，不用做复杂的事。3分钟的重逢，根就能留住。」',
      storyOutcomeJa: '「続ける」のハードルが下がった。ベンチの横の花が、ひとつ開いた。',
      storyOutcomeZh: '「坚持」的门槛降低了。长椅旁的花，开了一朵。',
      learningItemIds: ['fi-isogashii', 'fi-fukuzatsu'],
      unlocks: { locationIds: ['c10-hilltop-lantern'], npcIds: ['c10-npc-shion'], storyBeatIds: ['c10-beat-bench', 'c10-beat-cycle'] },
      isChapterFinale: false, adventureXpReward: 25 },
    { questId: 'c10q4-lantern-night', order: 4, siteLocationId: 'c10-hilltop-lantern',
      titleJa: '章末：大灯籠に火を入れる', titleZh: '章末：点亮大灯笼',
      learnGoalJa: '「困る」「多い」を加え、復習の場面会話（忘却→再会→予定→続け方）を通す',
      learnGoalZh: '加上「困る」「多い」，完整走一遍复习场景对话（遗忘→重逢→计划→坚持法）',
      estimatedMinutes: 6,
      completionConditionJa: '2語のチェックと4ステップの場面会話をすべて成立させる',
      completionConditionZh: '答对2个词并完成4步场景对话',
      storyIntroJa: '日が沈む。ニワさんが大灯籠の前で待っていた。「最後の質問に答えたら、火を入れましょう」',
      storyIntroZh: '太阳落山了。庭婆婆在大灯笼前等着：「答完最后的问题，我们就点火。」',
      storyOutcomeJa: '大灯籠が灯った。第10章完了。ミナモ列島の全部の章が、あなたの物語になった。',
      storyOutcomeZh: '大灯笼亮了。第十章完成。水面群岛的所有章节，都成了你的故事。',
      learningItemIds: ['fi-komaru', 'fi-ooi'],
      unlocks: { locationIds: [], npcIds: [], storyBeatIds: ['c10-beat-lantern', 'c10-beat-end'] },
      isChapterFinale: true, adventureXpReward: 40 },
  ],
  finaleSteps: [
    { stepId: 'c10f-forget', npcLineJa: 'ことばを忘れたら、どうしますか。', npcLineZh: '要是忘了词，怎么办？',
      correctJa: '困りません。庭園で再会します。', usesItemId: 'fi-komaru',
      optionsJa: ['困りません。庭園で再会します。', '困ります。勉強をやめます。', '困りません。全部書き直します。'] },
    { stepId: 'c10f-when', npcLineJa: '灯りが弱るのは、いつ頃でしたか。', npcLineZh: '灯是什么时候开始变弱的来着？',
      correctJa: '翌日、3日後、7日後です。', usesItemId: 'fi-wasureru',
      optionsJa: ['翌日、3日後、7日後です。', '毎年1回です。', '忘れた日の朝だけです。'] },
    { stepId: 'c10f-busy', npcLineJa: '忙しい日は、どうしますか。', npcLineZh: '忙的日子怎么办？',
      correctJa: '短くていいので、3分だけ利用します。', usesItemId: 'fi-isogashii',
      optionsJa: ['短くていいので、3分だけ利用します。', '複雑なので、全部やめます。', '静かなので、寝ます。'] },
    { stepId: 'c10f-many', npcLineJa: '思い出が増えたら、大変では？', npcLineZh: '回忆越来越多，不会很累吗？',
      correctJa: '多いほど、この庭は明るくなります。', usesItemId: 'fi-ooi',
      optionsJa: ['多いほど、この庭は明るくなります。', '多いほど、門は閉まります。', '多いほど、準備が複雑になります。'] },
  ],
  reviewReunion: {
    questId: 'c10r-reunion-lantern',
    titleJa: '再会：小さな灯りの手紙', titleZh: '重逢：小灯的来信',
    letterJa: '花壇の隅で、灯りがひとつ弱っています。名前は言いません。会えば、きっと思い出すから。——ニワ',
    letterZh: '花坛角落里，有一盏灯弱了下去。名字我不说。因为只要见了面，你一定会想起来。——庭婆婆',
    outcomeJa: '会いに行ったら、やっぱり思い出せた。庭の灯りが、またひとつ強くなった。',
    outcomeZh: '去见了它，果然想起来了。庭园的灯，又亮了一分。',
    adventureXpReward: 15 },
};

export const CHAPTERS_8_TO_10: ChapterDef[] = [CHAPTER_8, CHAPTER_9, CHAPTER_10];
