// N3 Unit Coverage Spec（§14）。全語彙をどの単元で扱うかの契約。
// 生成: scripts経由（全140語の重複0・欠落0を機械検証）。要件はunitCoverage.tsが評価する。
// reviewStatusは全件 human_review_candidate（CEO承認前）。
import type { UnitCoverageSpec } from './unitCoverage';

export const N3_UNIT_SPECS: UnitCoverageSpec[] = [
  { unitId: 'n3u-01-self', titleJa: '自己紹介と身分', titleZh: '自我介绍与身份',
    targetVocabularyIds: ['fi-namae', 'fi-shusshin', 'fi-chugoku', 'fi-nihon', 'fi-gakusei', 'fi-kaishain', 'fi-kaisha', 'fi-nihongo', 'fi-sumu', 'fi-hataraku', 'fi-benkyo', 'fi-sensei'],
    requiredVocabularyIds: ['fi-namae', 'fi-shusshin', 'fi-chugoku', 'fi-nihon', 'fi-gakusei', 'fi-kaishain', 'fi-kaisha', 'fi-nihongo', 'fi-sumu', 'fi-hataraku', 'fi-benkyo', 'fi-sensei'],
    highRiskCognateIds: ['fi-benkyo', 'fi-sensei'],
    practicalMission: { missionId: 'n3m-01', titleJa: '初対面の人に自己紹介する', titleZh: '向初次见面的人做自我介绍',
      usesItemIds: ['fi-namae', 'fi-shusshin', 'fi-hataraku', 'fi-sensei'],
      situationJa: '会社の懇親会で、名前・出身・仕事を伝える', goalJa: '相手の質問に3往復で答えられる' },
    minimumAccuracy: 0.8, reviewPolicy: 'spaced_default', reviewStatus: 'human_review_candidate' },
  { unitId: 'n3u-02-daily', titleJa: '毎日の動作', titleZh: '日常动作',
    targetVocabularyIds: ['fi-iku', 'fi-kuru', 'fi-suru', 'fi-taberu', 'fi-miru', 'fi-hanasu', 'fi-kiku', 'fi-kaku', 'fi-yomu', 'fi-kau', 'fi-kaeru', 'fi-wakaru', 'fi-nomu', 'fi-tsukau', 'fi-tsukuru', 'fi-au', 'fi-neru', 'fi-okiru'],
    requiredVocabularyIds: ['fi-iku', 'fi-kuru', 'fi-suru', 'fi-taberu', 'fi-miru', 'fi-hanasu', 'fi-kiku', 'fi-kaku', 'fi-yomu', 'fi-kau', 'fi-kaeru', 'fi-wakaru', 'fi-nomu', 'fi-tsukau', 'fi-tsukuru', 'fi-au', 'fi-neru', 'fi-okiru'],
    highRiskCognateIds: [],
    practicalMission: { missionId: 'n3m-02', titleJa: '一日の流れを説明する', titleZh: '说明一天的流程',
      usesItemIds: ['fi-okiru', 'fi-taberu', 'fi-neru', 'fi-iku'],
      situationJa: '同僚に週末の過ごし方を聞かれる', goalJa: '起床から就寝まで順番に話せる' },
    minimumAccuracy: 0.8, reviewPolicy: 'spaced_default', reviewStatus: 'human_review_candidate' },
  { unitId: 'n3u-03-move', titleJa: '移動と場所', titleZh: '移动与场所',
    targetVocabularyIds: ['fi-hairu', 'fi-deru', 'fi-noru', 'fi-oriru', 'fi-eki', 'fi-ie', 'fi-gakkou', 'fi-byouin', 'fi-densha', 'fi-basu'],
    requiredVocabularyIds: ['fi-hairu', 'fi-deru', 'fi-noru', 'fi-oriru', 'fi-eki', 'fi-ie', 'fi-gakkou', 'fi-byouin', 'fi-densha', 'fi-basu'],
    highRiskCognateIds: [],
    practicalMission: { missionId: 'n3m-03', titleJa: '行き方を尋ねる・説明する', titleZh: '询问并说明路线',
      usesItemIds: ['fi-eki', 'fi-noru', 'fi-oriru', 'fi-densha'],
      situationJa: '駅で目的地への行き方を聞く', goalJa: '乗る・降りる・駅名を使って道順を言える' },
    minimumAccuracy: 0.8, reviewPolicy: 'spaced_default', reviewStatus: 'human_review_candidate' },
  { unitId: 'n3u-04-things', titleJa: 'ものと数', titleZh: '物品与数量',
    targetVocabularyIds: ['fi-aru', 'fi-iru-exist', 'fi-neko', 'fi-en', 'fi-ikura', 'fi-ikutsu', 'fi-nanji', 'fi-kore', 'fi-kudasai', 'fi-mizu', 'fi-kusuri', 'fi-okane'],
    requiredVocabularyIds: ['fi-aru', 'fi-iru-exist', 'fi-neko', 'fi-en', 'fi-ikura', 'fi-ikutsu', 'fi-nanji', 'fi-kore', 'fi-kudasai', 'fi-mizu', 'fi-kusuri', 'fi-okane'],
    highRiskCognateIds: [],
    practicalMission: { missionId: 'n3m-04', titleJa: '店で買い物をする', titleZh: '在店里买东西',
      usesItemIds: ['fi-ikura', 'fi-kore', 'fi-kudasai', 'fi-kusuri'],
      situationJa: '薬局で必要なものを買う', goalJa: '値段と個数を確認して購入できる' },
    minimumAccuracy: 0.8, reviewPolicy: 'spaced_default', reviewStatus: 'human_review_candidate' },
  { unitId: 'n3u-05-adjpair', titleJa: '対になる形容詞', titleZh: '成对的形容词',
    targetVocabularyIds: ['fi-ookii', 'fi-chiisai', 'fi-takai', 'fi-yasui', 'fi-atarashii', 'fi-furui', 'fi-atsui', 'fi-samui', 'fi-chikai', 'fi-tooi', 'fi-ooi', 'fi-sukunai'],
    requiredVocabularyIds: ['fi-ookii', 'fi-chiisai', 'fi-takai', 'fi-yasui', 'fi-atarashii', 'fi-furui', 'fi-atsui', 'fi-samui', 'fi-chikai', 'fi-tooi', 'fi-ooi', 'fi-sukunai'],
    highRiskCognateIds: ['fi-takai', 'fi-yasui'],
    practicalMission: { missionId: 'n3m-05', titleJa: '二つの部屋を比べて選ぶ', titleZh: '比较两个房间并做选择',
      usesItemIds: ['fi-takai', 'fi-yasui', 'fi-chikai', 'fi-tooi'],
      situationJa: '不動産屋で条件を比べる', goalJa: '広さ・値段・距離を比べて希望を言える' },
    minimumAccuracy: 0.8, reviewPolicy: 'spaced_default', reviewStatus: 'human_review_candidate' },
  { unitId: 'n3u-06-feeling', titleJa: '気持ちと様子', titleZh: '心情与状态',
    targetVocabularyIds: ['fi-isogashii', 'fi-tanoshii', 'fi-muzukashii', 'fi-oishii', 'fi-suki', 'fi-genki', 'fi-shizuka', 'fi-benri', 'fi-kantan', 'fi-yuumei', 'fi-jouzu', 'fi-ureshii', 'fi-kanashii', 'fi-sabishii', 'fi-hazukashii', 'fi-kibishii'],
    requiredVocabularyIds: ['fi-isogashii', 'fi-tanoshii', 'fi-muzukashii', 'fi-oishii', 'fi-suki', 'fi-genki', 'fi-shizuka', 'fi-benri', 'fi-kantan', 'fi-yuumei', 'fi-jouzu', 'fi-ureshii', 'fi-kanashii', 'fi-sabishii', 'fi-hazukashii', 'fi-kibishii'],
    highRiskCognateIds: ['fi-jouzu'],
    practicalMission: { missionId: 'n3m-06', titleJa: '感想を伝える', titleZh: '表达感想',
      usesItemIds: ['fi-oishii', 'fi-tanoshii', 'fi-jouzu', 'fi-genki'],
      situationJa: '食事のあとに感想を言う', goalJa: '味・雰囲気・気持ちを2文以上で言える' },
    minimumAccuracy: 0.8, reviewPolicy: 'spaced_default', reviewStatus: 'human_review_candidate' },
  { unitId: 'n3u-07-people', titleJa: '人と関係', titleZh: '人与关系',
    targetVocabularyIds: ['fi-tomodachi', 'fi-kazoku', 'fi-shigoto', 'fi-kimochi', 'fi-kibun', 'fi-kankei', 'fi-kyoumi'],
    requiredVocabularyIds: ['fi-tomodachi', 'fi-kazoku', 'fi-shigoto', 'fi-kimochi', 'fi-kibun', 'fi-kankei', 'fi-kyoumi'],
    highRiskCognateIds: ['fi-kazoku'],
    practicalMission: { missionId: 'n3m-07', titleJa: '家族と友人について話す', titleZh: '谈论家人和朋友',
      usesItemIds: ['fi-kazoku', 'fi-tomodachi', 'fi-kyoumi'],
      situationJa: '週末の予定を聞かれて答える', goalJa: 'だれと何をするかを説明できる' },
    minimumAccuracy: 0.8, reviewPolicy: 'spaced_default', reviewStatus: 'human_review_candidate' },
  { unitId: 'n3u-08-change', titleJa: '変化と継続', titleZh: '变化与持续',
    targetVocabularyIds: ['fi-kawaru', 'fi-kaeru-change', 'fi-fueru', 'fi-heru', 'fi-hajimeru', 'fi-owaru', 'fi-tsuzukeru', 'fi-tsuzuku', 'fi-kimeru', 'fi-kimaru', 'fi-nareru', 'fi-shuukan'],
    requiredVocabularyIds: ['fi-kawaru', 'fi-kaeru-change', 'fi-fueru', 'fi-heru', 'fi-hajimeru', 'fi-owaru', 'fi-tsuzukeru', 'fi-tsuzuku', 'fi-kimeru', 'fi-kimaru', 'fi-nareru', 'fi-shuukan'],
    highRiskCognateIds: [],
    practicalMission: { missionId: 'n3m-08', titleJa: 'before/afterを説明する', titleZh: '说明变化前后',
      usesItemIds: ['fi-kawaru', 'fi-fueru', 'fi-nareru', 'fi-shuukan'],
      situationJa: '面談で「以前と今」を報告する', goalJa: '増えた・減った・慣れたを使い分けて言える' },
    minimumAccuracy: 0.8, reviewPolicy: 'spaced_default', reviewStatus: 'human_review_candidate' },
  { unitId: 'n3u-09-think', titleJa: '考えと伝達', titleZh: '思考与传达',
    targetVocabularyIds: ['fi-omou', 'fi-kangaeru', 'fi-kanjiru', 'fi-tsutaeru', 'fi-setsumei', 'fi-soudan', 'fi-renraku', 'fi-kakunin', 'fi-iken', 'fi-riyuu', 'fi-jouhou', 'fi-houhou'],
    requiredVocabularyIds: ['fi-omou', 'fi-kangaeru', 'fi-kanjiru', 'fi-tsutaeru', 'fi-setsumei', 'fi-soudan', 'fi-renraku', 'fi-kakunin', 'fi-iken', 'fi-riyuu', 'fi-jouhou', 'fi-houhou'],
    highRiskCognateIds: [],
    practicalMission: { missionId: 'n3m-09', titleJa: '意見と理由を述べる', titleZh: '陈述意见和理由',
      usesItemIds: ['fi-iken', 'fi-riyuu', 'fi-setsumei', 'fi-kakunin'],
      situationJa: '会議で自分の案を説明する', goalJa: '意見→理由→確認の順で話せる' },
    minimumAccuracy: 0.8, reviewPolicy: 'spaced_default', reviewStatus: 'human_review_candidate' },
  { unitId: 'n3u-10-arrange', titleJa: '手続きと段取り', titleZh: '手续与安排',
    targetVocabularyIds: ['fi-junbi', 'fi-yoyaku', 'fi-riyou', 'fi-erabu', 'fi-shiraberu', 'fi-oboeru', 'fi-wasureru', 'fi-kuraberu', 'fi-komaru', 'fi-ganbaru', 'fi-yotei', 'fi-tsugou', 'fi-yakusoku'],
    requiredVocabularyIds: ['fi-junbi', 'fi-yoyaku', 'fi-riyou', 'fi-erabu', 'fi-shiraberu', 'fi-oboeru', 'fi-wasureru', 'fi-kuraberu', 'fi-komaru', 'fi-ganbaru', 'fi-yotei', 'fi-tsugou', 'fi-yakusoku'],
    highRiskCognateIds: ['fi-komaru', 'fi-yotei', 'fi-yakusoku'],
    practicalMission: { missionId: 'n3m-10', titleJa: '予定を調整する', titleZh: '协调日程',
      usesItemIds: ['fi-yoyaku', 'fi-tsugou', 'fi-yakusoku', 'fi-yotei'],
      situationJa: '都合を聞いて約束を決める', goalJa: '予約・都合・約束を使って日程を決められる' },
    minimumAccuracy: 0.8, reviewPolicy: 'spaced_default', reviewStatus: 'human_review_candidate' },
  { unitId: 'n3u-11-situation', titleJa: '状況と評価', titleZh: '状况与评价',
    targetVocabularyIds: ['fi-keiken', 'fi-mondai', 'fi-joukyou', 'fi-taihen', 'fi-hitsuyou', 'fi-muri', 'fi-fukuzatsu', 'fi-jiyuu'],
    requiredVocabularyIds: ['fi-keiken', 'fi-mondai', 'fi-joukyou', 'fi-taihen', 'fi-hitsuyou', 'fi-muri', 'fi-fukuzatsu', 'fi-jiyuu'],
    highRiskCognateIds: ['fi-taihen', 'fi-muri'],
    practicalMission: { missionId: 'n3m-11', titleJa: '困った状況を説明して助けを求める', titleZh: '说明困难情况并求助',
      usesItemIds: ['fi-mondai', 'fi-joukyou', 'fi-muri', 'fi-hitsuyou'],
      situationJa: 'トラブルを上司に報告する', goalJa: '状況・問題・必要なことを順に説明できる' },
    minimumAccuracy: 0.8, reviewPolicy: 'spaced_default', reviewStatus: 'human_review_candidate' },
  { unitId: 'n3u-12-adverb', titleJa: '副詞とつなぎ言葉', titleZh: '副词与连接词',
    targetVocabularyIds: ['fi-tabun', 'fi-kanarazu', 'fi-saikin', 'fi-zenzen', 'fi-nakanaka', 'fi-yatto', 'fi-tsumari', 'fi-sorede'],
    requiredVocabularyIds: ['fi-tabun', 'fi-kanarazu', 'fi-saikin', 'fi-zenzen', 'fi-nakanaka', 'fi-yatto', 'fi-tsumari', 'fi-sorede'],
    highRiskCognateIds: ['fi-zenzen'],
    practicalMission: { missionId: 'n3m-12', titleJa: '話を自然につなげる', titleZh: '自然地衔接话题',
      usesItemIds: ['fi-saikin', 'fi-tsumari', 'fi-sorede', 'fi-zenzen'],
      situationJa: '近況を2〜3文で話す', goalJa: '最近・つまり・それでを使って話をつなげる' },
    minimumAccuracy: 0.8, reviewPolicy: 'spaced_default', reviewStatus: 'human_review_candidate' },
];
