// Phase B-4 バッチ2: 生活動作・思考／伝達の動詞。
// 語ごとに「場所・持っている物・体の向き」を変え、同じ構図の使い回しを作らない。
import type { VocabSceneSpec } from './VocabScene';

const s = (spec: VocabSceneSpec): VocabSceneSpec => spec;

export const SCENES_BATCH2: VocabSceneSpec[] = [
  s({ itemId: 'fi-sumu', place: 'home',
    figures: [{ x: 78, dir: 'left', pose: 'stand', mood: 'happy' }],
    props: [{ kind: 'heart', x: 62, y: 34, scale: 0.9 }],
    altJa: '人が自分の住まいの前に立っている場面', altZh: '人站在自己居住的房子前面的场景' }),
  s({ itemId: 'fi-hataraku', place: 'office',
    figures: [{ x: 44, dir: 'right', pose: 'write' }],
    props: [{ kind: 'desk', x: 60, y: 66 }, { kind: 'screen', x: 62, y: 60, scale: 0.8 }],
    altJa: '人が机に向かって仕事をしている場面', altZh: '人对着办公桌工作的场景' }),
  s({ itemId: 'fi-benkyo', place: 'room',
    figures: [{ x: 44, dir: 'right', pose: 'read' }],
    props: [{ kind: 'desk', x: 62, y: 66 }, { kind: 'book', x: 62, y: 62, scale: 1.1 }, { kind: 'bulb', x: 92, y: 30, scale: 0.9 }],
    altJa: '人が机で本を開いて学んでいる場面', altZh: '人在桌前翻开书学习的场景' }),
  // ✓記号のみ→「正しい」に誤読されていた（両評価者REPLACE）。実際に手を動かす場面へ
  s({ itemId: 'fi-suru', place: 'room',
    figures: [{ x: 44, dir: 'right', pose: 'hold' }],
    props: [
      { kind: 'box', x: 62, y: 58, scale: 1.1 },
      { kind: 'smallBox', x: 88, y: 66, scale: 1.2 }, { kind: 'smallBox', x: 100, y: 66, scale: 1.2 },
    ],
    arrows: [{ x: 78, y: 46, dir: 'right', length: 14 }],
    altJa: '人が箱を運んで作業を進めている場面', altZh: '人搬着箱子、正在做事情的场景' }),
  s({ itemId: 'fi-taberu', place: 'restaurant',
    figures: [{ x: 34, dir: 'right', pose: 'eat', mood: 'happy' }],
    props: [{ kind: 'plate', x: 62, y: 53 }],
    altJa: '人が皿の料理を口へ運んでいる場面', altZh: '人把盘子里的食物送到嘴边的场景' }),
  s({ itemId: 'fi-nomu', place: 'restaurant',
    figures: [{ x: 34, dir: 'right', pose: 'drink', mood: 'happy' }],
    props: [{ kind: 'cup', x: 58, y: 54, scale: 1.2 }],
    altJa: '人がカップを持って飲んでいる場面', altZh: '人拿着杯子在喝东西的场景' }),
  s({ itemId: 'fi-miru', place: 'room',
    figures: [{ x: 32, dir: 'right', pose: 'stand', mood: 'surprised' }],
    props: [{ kind: 'screen', x: 80, y: 52, scale: 1.3 }],
    arrows: [{ x: 56, y: 46, dir: 'right', length: 18 }],
    altJa: '人が画面のほうへ視線を向けている場面', altZh: '人把视线投向屏幕的场景' }),
  s({ itemId: 'fi-kiku', place: 'room',
    figures: [{ x: 74, dir: 'left', pose: 'listen' }],
    props: [{ kind: 'speechPair', x: 34, y: 40, scale: 1.2 }],
    arrows: [{ x: 54, y: 44, dir: 'right', length: 16 }],
    altJa: '人が相手の声のほうへ耳を向けている場面', altZh: '人把耳朵朝向对方声音的场景' }),
  s({ itemId: 'fi-hanasu', place: 'plain',
    figures: [{ x: 38, dir: 'right', pose: 'talk' }, { x: 82, dir: 'left', pose: 'listen', color: '#f2a08c' }],
    bubble: { x: 60, y: 26, kind: 'speech' },
    altJa: '人が相手に向かって言葉を出している場面', altZh: '人朝着对方说话的场景' }),
  s({ itemId: 'fi-kaku', place: 'office',
    figures: [{ x: 38, dir: 'right', pose: 'write' }],
    props: [{ kind: 'desk', x: 58, y: 66 }, { kind: 'note', x: 58, y: 60, scale: 1.1 }],
    altJa: '人が紙に文字を書き入れている場面', altZh: '人在纸上写字的场景' }),
  s({ itemId: 'fi-yomu', place: 'park',
    figures: [{ x: 46, dir: 'right', pose: 'read' }],
    props: [{ kind: 'book', x: 66, y: 52, scale: 1.4 }],
    altJa: '人が開いた本に目を通している場面', altZh: '人在看摊开的书的场景' }),
  s({ itemId: 'fi-kau', place: 'shop',
    figures: [{ x: 58, dir: 'right', pose: 'hold' }],
    props: [{ kind: 'coin', x: 82, y: 46, scale: 0.9 }, { kind: 'bag', x: 96, y: 66, scale: 1.1 }],
    arrows: [{ x: 82, y: 60, dir: 'right', length: 16 }],
    altJa: '店でお金を渡して品物を受け取る場面', altZh: '在店里付钱换取商品的场景' }),
  s({ itemId: 'fi-wakaru', place: 'plain',
    figures: [{ x: 44, dir: 'right', pose: 'raise', mood: 'happy' }],
    props: [{ kind: 'bulb', x: 78, y: 34, scale: 1.4 }],
    altJa: '人の頭の上に明かりがともり、意味がつかめた場面', altZh: '人的头顶亮起灯、表示明白了的场景' }),
  s({ itemId: 'fi-aru', place: 'room',
    props: [{ kind: 'desk', x: 60, y: 68 }, { kind: 'book', x: 60, y: 62, scale: 1.2 }],
    arrows: [{ x: 60, y: 34, dir: 'down', length: 16 }],
    altJa: '机の上に物だけが置かれている図（人はいない）', altZh: '桌上只放着东西的图（没有人）' }),
  s({ itemId: 'fi-iru-exist', place: 'room',
    figures: [{ x: 60, dir: 'right', pose: 'stand' }],
    props: [{ kind: 'cat', x: 88, y: 70, scale: 0.9 }],
    arrows: [{ x: 60, y: 32, dir: 'down', length: 16 }],
    altJa: '部屋に人と動物がいる図（動くもの）', altZh: '房间里有人和动物的图（会动的存在）' }),
  s({ itemId: 'fi-tsukau', place: 'office',
    figures: [{ x: 38, dir: 'right', pose: 'hold' }],
    props: [{ kind: 'phone', x: 58, y: 56, scale: 1.2 }],
    arrows: [{ x: 78, y: 50, dir: 'right', length: 16 }],
    altJa: '人が道具を手に取って役立てている場面', altZh: '人拿起工具加以使用的场景' }),
  s({ itemId: 'fi-tsukuru', place: 'restaurant',
    figures: [{ x: 36, dir: 'right', pose: 'hold' }],
    props: [{ kind: 'box', x: 60, y: 56, scale: 1.1 }, { kind: 'plate', x: 88, y: 54 }],
    arrows: [{ x: 74, y: 44, dir: 'right', length: 16 }],
    altJa: '材料から新しい物ができあがっていく場面', altZh: '用材料做出新东西的场景' }),
  s({ itemId: 'fi-omou', place: 'plain',
    figures: [{ x: 40, dir: 'right', pose: 'think' }],
    bubble: { x: 82, y: 30, kind: 'think', prop: 'heart' },
    altJa: '人の頭に、心に浮かんだ気持ちの吹き出しが出ている場面', altZh: '人的头上出现表示心中想法的气泡的场景' }),
  s({ itemId: 'fi-kangaeru', place: 'office',
    figures: [{ x: 40, dir: 'right', pose: 'think', mood: 'stern' }],
    bubble: { x: 82, y: 30, kind: 'think', prop: 'question' },
    props: [{ kind: 'desk', x: 60, y: 68 }],
    altJa: '人が机の前で、答えを探して筋道を追っている場面', altZh: '人在桌前寻找答案、一步步思考的场景' }),
  s({ itemId: 'fi-kanjiru', place: 'park',
    figures: [{ x: 46, dir: 'right', pose: 'stand', mood: 'happy' }],
    props: [{ kind: 'heart', x: 46, y: 32, scale: 1.1 }],
    arrows: [{ x: 76, y: 46, dir: 'left', length: 18 }],
    altJa: '外からの何かが人の心に届いている図', altZh: '外界的某种东西传到人心里的图' }),
  s({ itemId: 'fi-tsutaeru', place: 'office',
    figures: [{ x: 30, dir: 'right', pose: 'talk' }, { x: 92, dir: 'left', pose: 'listen', color: '#f2a08c' }],
    props: [{ kind: 'letter', x: 61, y: 42, scale: 1.1 }],
    arrows: [{ x: 61, y: 58, dir: 'right', length: 20 }],
    altJa: '人から人へ内容が受け渡されている場面', altZh: '内容从一个人传递到另一个人的场景' }),
  s({ itemId: 'fi-setsumei', place: 'school',
    figures: [{ x: 30, dir: 'right', pose: 'point' }, { x: 90, dir: 'left', pose: 'listen', color: '#f2a08c' }],
    props: [{ kind: 'sign', x: 62, y: 66, scale: 0.9 }],
    altJa: '人が図を指さして、相手に筋道を示している場面', altZh: '人指着图向对方说明的场景' }),
  s({ itemId: 'fi-soudan', place: 'counter',
    figures: [{ x: 40, dir: 'right', pose: 'talk', mood: 'sad' }, { x: 80, dir: 'left', pose: 'listen', color: '#f2a08c', mood: 'happy' }],
    bubble: { x: 60, y: 26, kind: 'speech', prop: 'question' },
    altJa: '困っている人が向かい合った相手に打ち明けている場面', altZh: '有困扰的人向面对面的对方倾诉的场景' }),
  s({ itemId: 'fi-renraku', place: 'street',
    figures: [{ x: 34, dir: 'right', pose: 'hold' }],
    props: [{ kind: 'phone', x: 52, y: 56, scale: 1.2 }, { kind: 'phone', x: 96, y: 56, scale: 1.2, dir: 'left' }],
    arrows: [{ x: 74, y: 38, dir: 'right', length: 22 }],
    altJa: '離れた相手へ知らせが飛んでいく図', altZh: '消息传向远处对方的图' }),
  s({ itemId: 'fi-kakunin', place: 'office',
    figures: [{ x: 38, dir: 'right', pose: 'point', mood: 'stern' }],
    props: [{ kind: 'note', x: 66, y: 56, scale: 1.3 }, { kind: 'check', x: 94, y: 40, scale: 0.9 }],
    altJa: '人が書かれた内容を一つずつ指して照らし合わせている場面', altZh: '人逐条指着写下的内容进行核对的场景' }),
  s({ itemId: 'fi-junbi', place: 'room',
    figures: [{ x: 34, dir: 'right', pose: 'hold' }],
    props: [{ kind: 'bag', x: 60, y: 68, scale: 1.3 }, { kind: 'smallBox', x: 82, y: 66 }, { kind: 'ticket', x: 96, y: 52 }],
    arrows: [{ x: 76, y: 40, dir: 'left', length: 16 }],
    altJa: '出かける前に持ち物をかばんへそろえている場面', altZh: '出门前把要带的东西装进包里的场景' }),
  s({ itemId: 'fi-yoyaku', place: 'counter',
    figures: [{ x: 34, dir: 'right', pose: 'point' }],
    props: [{ kind: 'calendar', x: 66, y: 50, scale: 1.3 }, { kind: 'clock', x: 96, y: 40, scale: 0.9 }],
    altJa: '先の日と時間を押さえて席を取っている場面', altZh: '事先定下日期和时间、把位子留下来的场景' }),
  s({ itemId: 'fi-riyou', place: 'station',
    figures: [{ x: 34, dir: 'right', pose: 'hold' }],
    props: [{ kind: 'ticket', x: 56, y: 52, scale: 1.1 }, { kind: 'train', x: 92, y: 68 }],
    arrows: [{ x: 72, y: 44, dir: 'right', length: 16 }],
    altJa: '切符を使って乗り物のサービスを受ける場面', altZh: '使用车票乘坐交通工具的场景' }),
  s({ itemId: 'fi-erabu', place: 'shop',
    figures: [{ x: 44, dir: 'right', pose: 'point', mood: 'stern' }],
    props: [{ kind: 'smallBox', x: 70, y: 60, scale: 1.4 }, { kind: 'smallBox', x: 92, y: 60, scale: 1.4 }, { kind: 'check', x: 70, y: 38, scale: 0.8 }],
    altJa: '並んだ二つのうち片方を指さして取る場面', altZh: '在并排的两个中指着其中一个拿走的场景' }),
  s({ itemId: 'fi-shiraberu', place: 'office',
    figures: [{ x: 36, dir: 'right', pose: 'read', mood: 'stern' }],
    props: [{ kind: 'screen', x: 72, y: 54, scale: 1.2 }, { kind: 'question', x: 98, y: 30, scale: 0.8 }],
    altJa: '人が資料をたどって分からないことを探している場面', altZh: '人查阅资料寻找不明白之处的场景' }),
  s({ itemId: 'fi-kuraberu', place: 'plain',
    figures: [{ x: 24, dir: 'right', pose: 'point' }],
    sizePair: { x: 74, y: 70, big: 'left' },
    props: [{ kind: 'question', x: 74, y: 26, scale: 0.8 }],
    altJa: '人が大きさのちがう二つを並べて見ている場面', altZh: '人把大小不同的两个东西并排查看的场景' }),
  // 緑線+✓が「簡単」と同型で衝突（両評価者REPLACE）。同一人物の前後2段階で表す
  s({ itemId: 'fi-nareru', place: 'office',
    figures: [
      { x: 26, dir: 'right', pose: 'hold', mood: 'tired', scale: 0.9 },
      { x: 88, dir: 'right', pose: 'hold', mood: 'happy', scale: 0.9 },
    ],
    props: [
      { kind: 'phone', x: 38, y: 58, scale: 0.9 }, { kind: 'sweat', x: 32, y: 32, scale: 1.1 },
      { kind: 'phone', x: 100, y: 58, scale: 0.9 },
    ],
    arrows: [{ x: 58, y: 48, dir: 'right', length: 18 }],
    altJa: '最初は緊張していた人が、繰り返すうちに同じことを楽にできるようになった前後の場面',
    altZh: '起初很紧张的人，反复练习后能轻松做同一件事的前后对比场景' }),
  s({ itemId: 'fi-komaru', place: 'street',
    figures: [{ x: 46, dir: 'right', pose: 'shrug', mood: 'sad' }],
    props: [{ kind: 'tangle', x: 84, y: 44, scale: 1.2 }],
    altJa: '人が困り顔で、もつれた状況の前に立っている場面', altZh: '人一脸为难地站在纠缠不清的情况前的场景' }),
  s({ itemId: 'fi-ganbaru', place: 'park',
    figures: [{ x: 46, dir: 'right', pose: 'run', mood: 'stern' }],
    props: [{ kind: 'tapeGoal', x: 98, y: 72 }, { kind: 'starMark', x: 30, y: 26, scale: 0.9 }],
    altJa: '人が汗をかきながらゴールへ向かって走り続ける場面', altZh: '人一边流汗一边朝着终点坚持跑下去的场景' }),
];
