// Phase B-4 バッチ3: 人・場所・物の名詞と、基礎の表現。
// 名詞は「その物が置かれた場面」で描く。物だけを並べた図鑑にしない。
import type { VocabSceneSpec } from './VocabScene';

const s = (spec: VocabSceneSpec): VocabSceneSpec => spec;

export const SCENES_BATCH3: VocabSceneSpec[] = [
  // ── 自己紹介まわり ──
  s({ itemId: 'fi-namae', place: 'plain',
    figures: [{ x: 40, dir: 'right', pose: 'point', mood: 'happy' }],
    props: [{ kind: 'note', x: 80, y: 46, scale: 1.5 }],
    altJa: '人が自分を指しながら、名札を示している場面', altZh: '人指着自己、同时出示名牌的场景' }),
  s({ itemId: 'fi-shusshin', place: 'plain',
    figures: [{ x: 84, dir: 'left', pose: 'stand' }],
    props: [{ kind: 'sign', x: 26, y: 68 }],
    arrows: [{ x: 56, y: 48, dir: 'right', length: 24 }],
    altJa: '生まれた土地から今いる場所へ矢印が伸びている図', altZh: '箭头从出生的地方指向现在所在地的图' }),
  // 地図表現は廃止（不正確な国境線は政治的リスク・UX-011）。生活場面で表す
  s({ itemId: 'fi-chugoku', place: 'street',
    props: [
      { kind: 'gateRoof', x: 38, y: 46, scale: 1.3 },
      { kind: 'lantern', x: 24, y: 60, scale: 1.1 }, { kind: 'lantern', x: 52, y: 60, scale: 1.1 },
    ],
    figures: [{ x: 84, dir: 'left', pose: 'walk', mood: 'happy' }],
    altJa: '赤い提灯と反り屋根の門がある通りを人が歩いている場面', altZh: '人走在挂着红灯笼、有翘檐门楼的街道上的场景' }),
  s({ itemId: 'fi-nihon', place: 'plain',
    props: [{ kind: 'islandChain', x: 66, y: 52, scale: 1.8 }, { kind: 'cloudHot', x: 30, y: 28, scale: 1 }],
    altJa: '海に浮かぶ細長い島の連なりに日の印がある地図の図', altZh: '海上细长的岛链上带有太阳记号的地图' }),
  s({ itemId: 'fi-gakusei', place: 'school',
    figures: [{ x: 66, dir: 'right', pose: 'hold' }],
    props: [{ kind: 'book', x: 86, y: 56, scale: 1.1 }, { kind: 'bag', x: 96, y: 70 }],
    altJa: '学校で本とかばんを持っている人の場面', altZh: '在学校里拿着书和书包的人的场景' }),
  s({ itemId: 'fi-kaishain', place: 'office',
    figures: [{ x: 34, dir: 'right', pose: 'hold' }],
    props: [{ kind: 'bag', x: 52, y: 62 }, { kind: 'letter', x: 24, y: 40, scale: 0.8 }],
    altJa: '会社で働く服装の人がかばんを持って立つ場面', altZh: '在公司工作打扮的人拿着公文包站立的场景' }),
  s({ itemId: 'fi-kaisha', place: 'office',
    props: [{ kind: 'screen', x: 34, y: 60, scale: 1.2 }, { kind: 'desk', x: 34, y: 68 }, { kind: 'desk', x: 84, y: 68 }],
    figures: [{ x: 84, dir: 'left', pose: 'write', scale: 0.85 }],
    altJa: '机が並んだ働く場所の建物の中の図', altZh: '摆着办公桌的工作场所内部的图' }),
  s({ itemId: 'fi-nihongo', place: 'school',
    figures: [{ x: 34, dir: 'right', pose: 'talk' }],
    props: [{ kind: 'speechPair', x: 84, y: 44, scale: 1.4 }],
    altJa: '二つのことばの吹き出しが並び、片方で話している場面', altZh: '两个语言的气泡并排、用其中一个说话的场景' }),

  // ── 身のまわりの物・生き物 ──
  s({ itemId: 'fi-neko', place: 'park',
    props: [{ kind: 'cat', x: 58, y: 70, scale: 1.9 }],
    altJa: '外で耳としっぽのある小さな動物がいる場面', altZh: '外面有一只有耳朵和尾巴的小动物的场景' }),
  s({ itemId: 'fi-densha', place: 'station',
    props: [{ kind: 'train', x: 60, y: 66, scale: 1.6 }],
    altJa: '駅のホームに止まっている長い乗り物の場面', altZh: '停在站台边的长条形交通工具的场景' }),
  s({ itemId: 'fi-basu', place: 'street',
    props: [{ kind: 'bus', x: 58, y: 68, scale: 1.5 }, { kind: 'sign', x: 100, y: 72, scale: 0.8 }],
    altJa: '道の停留所に止まっている大きな車の場面', altZh: '停在路边站牌处的大型车辆的场景' }),
  s({ itemId: 'fi-kore', place: 'plain',
    figures: [{ x: 34, dir: 'right', pose: 'point' }],
    props: [{ kind: 'smallBox', x: 62, y: 60, scale: 1.6 }, { kind: 'smallBox', x: 100, y: 66, scale: 0.9 }],
    altJa: '人がすぐ手元にある物を指さしている場面', altZh: '人指着就在手边的东西的场景' }),
  s({ itemId: 'fi-en', place: 'shop',
    props: [{ kind: 'coin', x: 62, y: 46, scale: 2.2 }, { kind: 'priceLow', x: 96, y: 62 }],
    altJa: '値札のそばに硬貨が置かれている図', altZh: '价签旁边放着硬币的图' }),
  s({ itemId: 'fi-okane', place: 'plain',
    props: [{ kind: 'coin', x: 44, y: 56, scale: 1.6 }, { kind: 'coin', x: 66, y: 62, scale: 1.6 }, { kind: 'letter', x: 90, y: 60, scale: 1.1 }],
    altJa: '硬貨とお札がまとまって置かれている図', altZh: '硬币和纸币放在一起的图' }),
  s({ itemId: 'fi-kusuri', place: 'hospital',
    props: [{ kind: 'pill', x: 50, y: 54, scale: 1.6 }, { kind: 'pill', x: 70, y: 62, scale: 1.3 }, { kind: 'waterGlass', x: 34, y: 70 }],
    altJa: '病院で水と一緒に置かれた粒の図', altZh: '医院里和水放在一起的药粒的图' }),
  s({ itemId: 'fi-mizu', place: 'restaurant',
    props: [{ kind: 'waterGlass', x: 60, y: 56, scale: 2 }],
    altJa: '透明な液体が入ったコップの図', altZh: '装着透明液体的杯子的图' }),

  // ── 場所 ──
  s({ itemId: 'fi-ie', place: 'home',
    props: [{ kind: 'heart', x: 92, y: 40, scale: 1.1 }],
    figures: [{ x: 84, dir: 'left', pose: 'stand', scale: 0.8 }],
    altJa: '屋根と戸のある建物と、その前の人の場面', altZh: '有屋顶和门的房子以及站在前面的人的场景' }),
  s({ itemId: 'fi-eki', place: 'station',
    props: [{ kind: 'train', x: 92, y: 66, scale: 0.9 }, { kind: 'sign', x: 30, y: 66 }, { kind: 'ticket', x: 58, y: 60 }],
    altJa: '案内板と改札のある乗り物の乗り場の場面', altZh: '有指示牌和检票口的乘车场所的场景' }),
  s({ itemId: 'fi-gakkou', place: 'school',
    figures: [{ x: 74, dir: 'left', pose: 'walk', scale: 0.8 }, { x: 92, dir: 'left', pose: 'walk', scale: 0.8, color: '#f2a08c' }],
    props: [{ kind: 'book', x: 60, y: 68, scale: 0.9 }],
    altJa: '黒板のある建物へ子どもたちが向かう場面', altZh: '孩子们朝有黑板的建筑走去的场景' }),
  s({ itemId: 'fi-byouin', place: 'hospital',
    figures: [{ x: 46, dir: 'right', pose: 'stand', color: '#f2a08c' }],
    props: [{ kind: 'pill', x: 68, y: 62, scale: 0.9 }],
    altJa: '十字の印がある建物と、そこにいる人の場面', altZh: '有十字标记的建筑和在那里的人的场景' }),

  // ── 人・関係 ──
  s({ itemId: 'fi-tomodachi', place: 'park',
    figures: [{ x: 44, dir: 'right', pose: 'raise', mood: 'happy' }, { x: 74, dir: 'left', pose: 'raise', mood: 'happy', color: '#f2a08c' }],
    altJa: '同じくらいの背丈の二人が並んで笑っている場面', altZh: '身高相仿的两个人并排微笑的场景' }),
  s({ itemId: 'fi-kazoku', place: 'home',
    figures: [{ x: 66, dir: 'right', pose: 'stand', mood: 'happy' }, { x: 82, dir: 'left', pose: 'stand', mood: 'happy', color: '#f2a08c' }, { x: 74, dir: 'right', pose: 'stand', mood: 'happy', scale: 0.65, color: '#9ed9a6' }],
    altJa: '家の前に大人二人と小さい人が並ぶ場面', altZh: '房子前面站着两个大人和一个小孩的场景' }),
  s({ itemId: 'fi-sensei', place: 'school',
    figures: [{ x: 70, dir: 'left', pose: 'point', color: '#f2a08c' }, { x: 96, dir: 'left', pose: 'sit', scale: 0.8 }],
    props: [{ kind: 'chair', x: 100, y: 72, scale: 0.9 }],
    altJa: '黒板の前に立つ人が、座っている人へ教えている場面', altZh: '站在黑板前的人向坐着的人讲课的场景' }),
  s({ itemId: 'fi-shigoto', place: 'office',
    figures: [{ x: 36, dir: 'right', pose: 'write' }],
    props: [{ kind: 'desk', x: 54, y: 66 }, { kind: 'stack', x: 90, y: 66, scale: 1.4 }],
    altJa: '机の上に積まれた書類と、それに向かう人の場面', altZh: '桌上堆着文件、有人正在处理的场景' }),

  // ── 基礎の表現 ──
  s({ itemId: 'fi-ikura', place: 'shop',
    figures: [{ x: 50, dir: 'right', pose: 'point' }],
    props: [{ kind: 'priceHigh', x: 82, y: 58, scale: 1.2 }, { kind: 'question', x: 102, y: 34, scale: 0.9 }],
    altJa: '人が値札を指して、金額をたずねている場面', altZh: '人指着价签询问金额的场景' }),
  s({ itemId: 'fi-ikutsu', place: 'shop',
    figures: [{ x: 30, dir: 'right', pose: 'point' }],
    props: [{ kind: 'manyDots', x: 74, y: 50, scale: 1.1 }, { kind: 'question', x: 104, y: 34, scale: 0.9 }],
    altJa: '人が並んだ品物の数をたずねている場面', altZh: '人询问排列着的物品数量的场景' }),
  s({ itemId: 'fi-nanji', place: 'station',
    figures: [{ x: 30, dir: 'right', pose: 'point' }],
    props: [{ kind: 'clock', x: 74, y: 40, scale: 2 }, { kind: 'question', x: 104, y: 34, scale: 0.9 }],
    altJa: '人が時計を見て、時刻をたずねている場面', altZh: '人看着钟询问时间的场景' }),
  s({ itemId: 'fi-kudasai', place: 'counter',
    figures: [{ x: 34, dir: 'right', pose: 'point' }, { x: 90, dir: 'left', pose: 'hold', color: '#f2a08c' }],
    props: [{ kind: 'smallBox', x: 70, y: 50, scale: 1.2 }],
    arrows: [{ x: 62, y: 66, dir: 'left', length: 18 }],
    altJa: '相手に品物を差し出してもらうよう頼んでいる場面', altZh: '请对方把物品递过来的场景' }),
];
