// Phase B-4 バッチ4: 形容詞・感情・状態。
// 対義の組（大小・高安・新旧・暑寒・遠近・多少）は同じ場所・同じ画角にして、
// 変えるのは比べている物の側だけにする。感情は表情と姿勢で描き分ける。
import type { VocabSceneSpec } from './VocabScene';

const s = (spec: VocabSceneSpec): VocabSceneSpec => spec;

export const SCENES_BATCH4: VocabSceneSpec[] = [
  // ── 大きい / 小さい ──
  s({ itemId: 'fi-ookii', place: 'plain',
    sizePair: { x: 62, y: 70, big: 'left' },
    figures: [{ x: 20, dir: 'right', pose: 'point', scale: 0.8 }],
    altJa: '二つ並んだ箱のうち、左の大きいほうを指している図', altZh: '并排的两个箱子中指着左边大的那个的图' }),
  s({ itemId: 'fi-chiisai', place: 'plain',
    sizePair: { x: 62, y: 70, big: 'left' },
    figures: [{ x: 20, dir: 'right', pose: 'crouch', scale: 0.8 }],
    props: [{ kind: 'check', x: 74, y: 44, scale: 0.7 }],
    altJa: '二つ並んだ箱のうち、右の小さいほうに印がある図', altZh: '并排的两个箱子中右边小的那个被标记的图' }),

  // ── 高い / 安い（値段）──
  s({ itemId: 'fi-takai', place: 'shop',
    props: [{ kind: 'priceHigh', x: 66, y: 60, scale: 1.8 }],
    figures: [{ x: 34, dir: 'right', pose: 'shrug', mood: 'surprised' }],
    altJa: '店の値札を見て人が驚いている場面', altZh: '看到店里的价签、人很吃惊的场景' }),
  s({ itemId: 'fi-yasui', place: 'shop',
    props: [{ kind: 'priceLow', x: 66, y: 60, scale: 1.8 }],
    figures: [{ x: 34, dir: 'right', pose: 'raise', mood: 'happy' }],
    altJa: '店の値札を見て人が喜んでいる場面', altZh: '看到店里的价签、人很高兴的场景' }),

  // ── 新しい / 古い ──
  s({ itemId: 'fi-atarashii', place: 'room',
    props: [{ kind: 'box', x: 60, y: 64, scale: 1.6 }, { kind: 'newTag', x: 92, y: 34, scale: 1.2 }],
    altJa: 'つやのある箱に新しさの印が付いている図', altZh: '崭新的箱子上带着表示新的记号的图' }),
  s({ itemId: 'fi-furui', place: 'room',
    props: [{ kind: 'box', x: 60, y: 64, scale: 1.6 }, { kind: 'oldTag', x: 92, y: 34, scale: 1.2 }],
    altJa: '同じ箱に、時間が経ったことを表す印が付いている図', altZh: '同样的箱子上带着表示时间久了的记号的图' }),

  // ── 暑い / 寒い ──
  s({ itemId: 'fi-atsui', place: 'park',
    figures: [{ x: 44, dir: 'right', pose: 'slump', mood: 'tired' }],
    props: [{ kind: 'cloudHot', x: 88, y: 26, scale: 1.5 }],
    altJa: '強い日ざしの下で人がぐったりしている場面', altZh: '在强烈阳光下人无精打采的场景' }),
  s({ itemId: 'fi-samui', place: 'park',
    figures: [{ x: 44, dir: 'right', pose: 'crouch', mood: 'tired' }],
    props: [{ kind: 'snow', x: 88, y: 30, scale: 1.5 }],
    altJa: '雪の下で人が体を縮めている場面', altZh: '在雪中人缩着身体的场景' }),

  // ── 近い / 遠い ──
  s({ itemId: 'fi-chikai', place: 'street',
    figures: [{ x: 48, dir: 'right', pose: 'stand' }],
    props: [{ kind: 'sign', x: 68, y: 72 }],
    arrows: [{ x: 58, y: 52, dir: 'right', length: 12 }],
    altJa: '人と目印がすぐ隣にある図', altZh: '人和目标就在旁边的图' }),
  s({ itemId: 'fi-tooi', place: 'street',
    figures: [{ x: 24, dir: 'right', pose: 'stand' }],
    props: [{ kind: 'sign', x: 108, y: 72, scale: 0.6 }],
    arrows: [{ x: 66, y: 52, dir: 'right', length: 44 }],
    altJa: '人と目印が長い距離で離れている図', altZh: '人和目标之间隔着很长距离的图' }),

  // ── 多い / 少ない ──
  s({ itemId: 'fi-ooi', place: 'plain',
    props: [{ kind: 'manyDots', x: 62, y: 46, scale: 1.7 }],
    altJa: '同じ形の粒がたくさん並んでいる図', altZh: '很多同样形状的点排列在一起的图' }),
  s({ itemId: 'fi-sukunai', place: 'plain',
    props: [{ kind: 'fewDots', x: 62, y: 46, scale: 1.7 }],
    altJa: '同じ形の粒が二つだけ置かれている図', altZh: '只放着两个同样形状的点的图' }),

  // ── その他のい形容詞 ──
  s({ itemId: 'fi-isogashii', place: 'office',
    figures: [{ x: 40, dir: 'right', pose: 'run', mood: 'tired' }],
    props: [{ kind: 'stack', x: 74, y: 66, scale: 1.5 }, { kind: 'clock', x: 100, y: 30, scale: 1.1 }],
    altJa: '書類と時計に追われて人が走っている場面', altZh: '被文件和时间追赶、人在奔跑的场景' }),
  s({ itemId: 'fi-tanoshii', place: 'park',
    figures: [{ x: 42, dir: 'right', pose: 'cheer', mood: 'happy' }, { x: 76, dir: 'left', pose: 'cheer', mood: 'happy', color: '#f2a08c' }],
    props: [{ kind: 'starMark', x: 60, y: 24, scale: 1.1 }],
    altJa: '何人かで長く続く時間を楽しんでいる場面', altZh: '几个人一起享受持续一段时间的活动的场景' }),
  s({ itemId: 'fi-muzukashii', place: 'school',
    figures: [{ x: 44, dir: 'right', pose: 'think', mood: 'sad' }],
    props: [{ kind: 'tangle', x: 84, y: 44, scale: 1.4 }],
    altJa: '入り組んだ問題の前で人が頭をかかえる場面', altZh: '在错综复杂的问题前人抱头苦思的场景' }),
  s({ itemId: 'fi-oishii', place: 'restaurant',
    figures: [{ x: 36, dir: 'right', pose: 'eat', mood: 'happy' }],
    props: [{ kind: 'plate', x: 62, y: 53 }, { kind: 'heart', x: 88, y: 36, scale: 1.1 }],
    altJa: '料理を口にした人の横に心の印が出ている場面', altZh: '人吃到菜时旁边出现心形记号的场景' }),

  // ── な形容詞（基礎）──
  s({ itemId: 'fi-suki', place: 'plain',
    figures: [{ x: 38, dir: 'right', pose: 'hold', mood: 'happy' }],
    props: [{ kind: 'book', x: 58, y: 56, scale: 1.2 }, { kind: 'heart', x: 84, y: 40, scale: 1.4 }],
    altJa: '人が物を胸に抱えて、心の印が出ている場面', altZh: '人把东西抱在胸前、出现心形记号的场景' }),
  s({ itemId: 'fi-genki', place: 'park',
    figures: [{ x: 54, dir: 'right', pose: 'cheer', mood: 'happy' }],
    props: [{ kind: 'cloudHot', x: 92, y: 24, scale: 1.1 }],
    altJa: '人が両手を上げて元気よく立っている場面', altZh: '人举起双手精神饱满地站着的场景' }),
  s({ itemId: 'fi-shizuka', place: 'room',
    figures: [{ x: 40, dir: 'right', pose: 'read' }],
    props: [{ kind: 'quietMark', x: 84, y: 40, scale: 1.4 }],
    altJa: '音のしるしが消してある静かな部屋の場面', altZh: '声音记号被划掉、安静的房间的场景' }),
  s({ itemId: 'fi-benri', place: 'street',
    figures: [{ x: 32, dir: 'right', pose: 'hold', mood: 'happy' }],
    props: [{ kind: 'phone', x: 50, y: 56, scale: 1.2 }, { kind: 'check', x: 86, y: 42, scale: 1.2 }],
    altJa: '道具ひとつで用が足りている場面', altZh: '用一件工具就能把事情办好的场景' }),
  s({ itemId: 'fi-kantan', place: 'plain',
    props: [{ kind: 'freePath', x: 60, y: 50, scale: 2 }, { kind: 'check', x: 100, y: 34, scale: 1 }],
    altJa: 'まっすぐで分かれ道のない一本道の図', altZh: '笔直、没有岔路的一条路的图' }),
  s({ itemId: 'fi-yuumei', place: 'street',
    figures: [{ x: 34, dir: 'right', pose: 'raise' }, { x: 74, dir: 'left', pose: 'stand', scale: 0.8, color: '#f2a08c' }, { x: 92, dir: 'left', pose: 'stand', scale: 0.8, color: '#9ed9a6' }],
    props: [{ kind: 'starMark', x: 34, y: 30, scale: 1.2 }],
    altJa: '一人に印が付き、まわりの人がそちらを見ている場面', altZh: '一个人被标上记号、周围的人都看向他的场景' }),
  s({ itemId: 'fi-jouzu', place: 'school',
    figures: [{ x: 42, dir: 'right', pose: 'write', mood: 'happy' }],
    props: [{ kind: 'note', x: 66, y: 58, scale: 1.2 }, { kind: 'check', x: 94, y: 36, scale: 1.2 }],
    altJa: '人の仕上げた物にまるが付いている場面', altZh: '人完成的作品上被画了圈的场景' }),

  // ── N3 感情（同じ部屋・同じ立ち位置で表情と姿勢だけを変える）──
  s({ itemId: 'fi-ureshii', place: 'room',
    figures: [{ x: 54, dir: 'right', pose: 'cheer', mood: 'happy' }],
    props: [{ kind: 'bang', x: 88, y: 34, scale: 1.1 }],
    altJa: 'よい知らせを受けた瞬間に人が両手を上げる場面', altZh: '收到好消息的瞬间、人举起双手的场景' }),
  s({ itemId: 'fi-kanashii', place: 'room',
    figures: [{ x: 54, dir: 'right', pose: 'slump', mood: 'sad' }],
    props: [{ kind: 'snow', x: 88, y: 40, scale: 0.9 }],
    altJa: '人がうつむいて肩を落としている場面', altZh: '人低着头、肩膀垂下来的场景' }),
  s({ itemId: 'fi-sabishii', place: 'night',
    figures: [{ x: 54, dir: 'right', pose: 'sit', mood: 'sad' }],
    props: [{ kind: 'chair', x: 54, y: 72 }],
    altJa: '広い場所に人がひとりだけ座っている場面', altZh: '宽敞的地方只有一个人坐着的场景' }),
  s({ itemId: 'fi-hazukashii', place: 'plain',
    figures: [{ x: 46, dir: 'right', pose: 'shrug', mood: 'shy' }, { x: 84, dir: 'left', pose: 'stand', scale: 0.85, color: '#f2a08c' }],
    altJa: '人に見られて頬が赤くなり、身を縮めている場面', altZh: '被人看到后脸变红、缩起身子的场景' }),
  s({ itemId: 'fi-kibishii', place: 'office',
    figures: [{ x: 40, dir: 'right', pose: 'point', mood: 'stern', color: '#f2a08c' }, { x: 84, dir: 'left', pose: 'slump', mood: 'sad', scale: 0.9 }],
    props: [{ kind: 'cross', x: 62, y: 32, scale: 0.9 }],
    altJa: '一方が厳しい顔で指し、もう一方が縮こまる場面', altZh: '一方板着脸指出问题、另一方缩起来的场景' }),

  // ── N3 な形容詞 ──
  s({ itemId: 'fi-taihen', place: 'street',
    figures: [{ x: 40, dir: 'right', pose: 'hold', mood: 'tired' }],
    props: [{ kind: 'bigBox', x: 66, y: 62, scale: 0.9 }, { kind: 'stack', x: 98, y: 70, scale: 1.2 }],
    altJa: '人が重そうな荷物をいくつも運んでいる場面', altZh: '人搬运好几件看起来很重的行李的场景' }),
  s({ itemId: 'fi-hitsuyou', place: 'counter',
    figures: [{ x: 34, dir: 'right', pose: 'point' }],
    props: [{ kind: 'key', x: 68, y: 48, scale: 1.6 }, { kind: 'lock', x: 96, y: 56, scale: 1.4 }],
    arrows: [{ x: 82, y: 66, dir: 'right', length: 16 }],
    altJa: '鍵がなければ開かない錠を指している場面', altZh: '指着没有钥匙就打不开的锁的场景' }),
  s({ itemId: 'fi-muri', place: 'plain',
    figures: [{ x: 40, dir: 'right', pose: 'shrug', mood: 'tired' }],
    props: [{ kind: 'bigBox', x: 80, y: 68, scale: 1.3 }, { kind: 'cross', x: 80, y: 30, scale: 1.2 }],
    altJa: '大きすぎる荷物の前で人が手を広げ、ばつ印が出る場面', altZh: '在过大的行李前人摊开手、出现叉号的场景' }),
  s({ itemId: 'fi-fukuzatsu', place: 'office',
    props: [{ kind: 'tangle', x: 62, y: 48, scale: 2.2 }],
    altJa: '線が何重にも絡まり合っている図', altZh: '线条层层缠绕在一起的图' }),
  s({ itemId: 'fi-jiyuu', place: 'park',
    figures: [{ x: 40, dir: 'right', pose: 'cheer', mood: 'happy' }],
    props: [{ kind: 'freePath', x: 84, y: 46, scale: 1.6 }],
    altJa: '開けた場所で人が両手を広げ、行き先が何通りもある図', altZh: '在开阔的地方人张开双手、去向有很多条的图' }),
];
