// 自動生成（scripts/ai-course/generate-mission-index.mts）。**手で編集しない。**
//
// 会話カリキュラムの目次。本文フィールドは意図的に空（''/[]）で、
// レッスン開始時に /api/ai-course/activity/start {activity:'conversation'} が
// 現在ミッションの本文だけを返す（P0: 教材のclient bundle除去）。
// 目次の同期は courseMissionIndex.test.ts が検査する。
import type { CourseWeek, Mission } from './types';

export const COURSE_WEEKS: CourseWeek[] = [
  {
    "week": 1,
    "themeJa": "自己紹介・現在の生活",
    "themeZh": "自我介绍・现在的生活"
  },
  {
    "week": 2,
    "themeJa": "過去の経験",
    "themeZh": "过去的经历"
  },
  {
    "week": 3,
    "themeJa": "変化・成長",
    "themeZh": "变化・成长"
  },
  {
    "week": 4,
    "themeJa": "習慣・継続",
    "themeZh": "习惯・坚持"
  },
  {
    "week": 5,
    "themeJa": "許可・依頼",
    "themeZh": "许可・请求"
  },
  {
    "week": 6,
    "themeJa": "困りごと・相談",
    "themeZh": "困扰・咨询"
  },
  {
    "week": 7,
    "themeJa": "意見・理由",
    "themeZh": "意见・理由"
  },
  {
    "week": 8,
    "themeJa": "比較・選択",
    "themeZh": "比较・选择"
  },
  {
    "week": 9,
    "themeJa": "推測・可能性",
    "themeZh": "推测・可能性"
  },
  {
    "week": 10,
    "themeJa": "仕事・日本での生活",
    "themeZh": "工作・在日本的生活"
  },
  {
    "week": 11,
    "themeJa": "バドミントン・人との交流",
    "themeZh": "羽毛球・与人交流"
  },
  {
    "week": 12,
    "themeJa": "総合会話・弱点克服",
    "themeZh": "综合会话・弱点克服"
  }
];

export const COURSE_MISSIONS: Mission[] = [
  {
    "id": "w01m1",
    "week": 1,
    "order": 1,
    "titleJa": "名前を伝える",
    "titleZh": "介绍名字",
    "category": "selfIntro",
    "difficulty": 1,
    "targetExpression": "〜といいます",
    "targetExpressionReading": "〜といいます",
    "detect": "といいます|と申します",
    "meaningJa": "自分の名前を丁寧に伝える言い方",
    "meaningZh": "礼貌地介绍自己名字的说法",
    "chineseSupport": "rich",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w01m2",
    "week": 1,
    "order": 2,
    "titleJa": "住んでいる場所",
    "titleZh": "居住的地方",
    "category": "selfIntro",
    "difficulty": 1,
    "targetExpression": "〜に住んでいます",
    "targetExpressionReading": "〜にすんでいます",
    "detect": "に住んで|にすんで",
    "meaningJa": "今住んでいる場所を言う",
    "meaningZh": "说明现在居住的地方",
    "chineseSupport": "rich",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w01m3",
    "week": 1,
    "order": 3,
    "titleJa": "仕事・していること",
    "titleZh": "工作・在做的事",
    "category": "selfIntro",
    "difficulty": 1,
    "targetExpression": "〜をしています",
    "targetExpressionReading": "〜をしています",
    "detect": "をしています|の仕事をして",
    "meaningJa": "仕事や普段していることを言う",
    "meaningZh": "说明工作或平时在做的事",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w01m4",
    "week": 1,
    "order": 4,
    "titleJa": "好きなこと",
    "titleZh": "喜欢的事",
    "category": "selfIntro",
    "difficulty": 2,
    "targetExpression": "〜ことが好きです",
    "targetExpressionReading": "〜ことがすきです",
    "detect": "ことが好き|ことがすき",
    "meaningJa": "好きな活動を「〜こと」で名詞化して言う",
    "meaningZh": "把喜欢的活动用「〜こと」名词化来表达",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w01m5",
    "week": 1,
    "order": 5,
    "titleJa": "自己紹介・総合",
    "titleZh": "自我介绍・综合",
    "category": "selfIntro",
    "difficulty": 2,
    "targetExpression": "自己紹介（総合）",
    "targetExpressionReading": "じこしょうかい",
    "detect": "といいます|に住んで|をしています|ことが好き",
    "meaningJa": "今週の4表現を続けて自己紹介にまとめる",
    "meaningZh": "把本周4个表达连起来完成一段自我介绍",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w01m1",
      "w01m2",
      "w01m3",
      "w01m4"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w02m1",
    "week": 2,
    "order": 1,
    "titleJa": "経験を言う",
    "titleZh": "表达经历",
    "category": "experience",
    "difficulty": 2,
    "targetExpression": "〜たことがあります",
    "targetExpressionReading": "〜たことがあります",
    "detect": "たことがあり|たことがある|だことがあり|だことがある",
    "meaningJa": "過去に一度でも経験したことを言う",
    "meaningZh": "表达过去曾经有过的经历",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w02m2",
    "week": 2,
    "order": 2,
    "titleJa": "〜たとき",
    "titleZh": "当〜的时候",
    "category": "experience",
    "difficulty": 2,
    "targetExpression": "〜たとき",
    "targetExpressionReading": "〜たとき",
    "detect": "たとき|だとき",
    "meaningJa": "ある動作が起きた時点を言う",
    "meaningZh": "表达某个动作发生的时间点",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w02m3",
    "week": 2,
    "order": 3,
    "titleJa": "〜てから",
    "titleZh": "〜之后",
    "category": "experience",
    "difficulty": 2,
    "targetExpression": "〜てから",
    "targetExpressionReading": "〜てから",
    "detect": "てから|でから",
    "meaningJa": "ある動作の後で次のことをする",
    "meaningZh": "在某个动作之后再做下一件事",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w02m4",
    "week": 2,
    "order": 4,
    "titleJa": "〜たばかりです",
    "titleZh": "刚〜不久",
    "category": "experience",
    "difficulty": 3,
    "targetExpression": "〜たばかりです",
    "targetExpressionReading": "〜たばかりです",
    "detect": "たばかり|だばかり",
    "meaningJa": "ついさっき／最近その動作を終えた",
    "meaningZh": "刚刚・最近才做完某个动作",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w02m5",
    "week": 2,
    "order": 5,
    "titleJa": "過去の経験・総合",
    "titleZh": "过去经历・综合",
    "category": "experience",
    "difficulty": 3,
    "targetExpression": "過去の経験（総合）",
    "targetExpressionReading": "かこのけいけん",
    "detect": "たことがあり|たとき|てから|たばかり",
    "meaningJa": "今週の経験表現を使ってエピソードを話す",
    "meaningZh": "用本周的经历表达讲一段小故事",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w02m1",
      "w02m2",
      "w02m3",
      "w02m4"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w03m1",
    "week": 3,
    "order": 1,
    "titleJa": "できるようになった",
    "titleZh": "变得会〜了",
    "category": "change",
    "difficulty": 2,
    "targetExpression": "〜ようになりました",
    "targetExpressionReading": "〜ようになりました",
    "detect": "ようになりました|ようになった",
    "meaningJa": "できなかったことができるように変化した",
    "meaningZh": "从不会到会的能力变化",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w03m2",
    "week": 3,
    "order": 2,
    "titleJa": "しなくなった",
    "titleZh": "变得不〜了",
    "category": "change",
    "difficulty": 3,
    "targetExpression": "〜なくなりました",
    "targetExpressionReading": "〜なくなりました",
    "detect": "なくなりました|なくなった",
    "meaningJa": "していたことをしなくなる変化",
    "meaningZh": "从做到不做的变化",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w03m3",
    "week": 3,
    "order": 3,
    "titleJa": "以前は〜でしたが",
    "titleZh": "以前是〜但",
    "category": "change",
    "difficulty": 3,
    "targetExpression": "以前は〜でしたが",
    "targetExpressionReading": "いぜんは〜でしたが",
    "detect": "以前は|昔は|前は",
    "meaningJa": "過去と今を対比して変化を説明する",
    "meaningZh": "把过去和现在对比来说明变化",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w03m4",
    "week": 3,
    "order": 4,
    "titleJa": "だんだん〜てきた",
    "titleZh": "渐渐〜起来了",
    "category": "change",
    "difficulty": 3,
    "targetExpression": "だんだん〜てきました",
    "targetExpressionReading": "だんだん〜てきました",
    "detect": "てきました|できました|てきた",
    "meaningJa": "少しずつ進む変化を表す",
    "meaningZh": "表示逐渐进行的变化",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w03m5",
    "week": 3,
    "order": 5,
    "titleJa": "成長説明・総合",
    "titleZh": "成长说明・综合",
    "category": "change",
    "difficulty": 3,
    "targetExpression": "成長説明（総合）",
    "targetExpressionReading": "せいちょうせつめい",
    "detect": "ようになりました|なくなりました|以前は|てきました",
    "meaningJa": "今週の変化表現で自分の成長を説明する",
    "meaningZh": "用本周的变化表达说明自己的成长",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w03m1",
      "w03m2",
      "w03m3",
      "w03m4"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w04m1",
    "week": 4,
    "order": 1,
    "titleJa": "〜ことにしています",
    "titleZh": "决定〜（并坚持）",
    "category": "habit",
    "difficulty": 3,
    "targetExpression": "〜ことにしています",
    "targetExpressionReading": "〜ことにしています",
    "detect": "ことにしています|ことにして",
    "meaningJa": "自分で決めて続けている習慣を言う",
    "meaningZh": "表达自己决定并持续在做的习惯",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w04m2",
    "week": 4,
    "order": 2,
    "titleJa": "〜ようにしています",
    "titleZh": "尽量〜",
    "category": "habit",
    "difficulty": 3,
    "targetExpression": "〜ようにしています",
    "targetExpressionReading": "〜ようにしています",
    "detect": "ようにしています|ようにして",
    "meaningJa": "努力して心がけていることを言う",
    "meaningZh": "表达努力去做、留意去做的事",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w04m3",
    "week": 4,
    "order": 3,
    "titleJa": "いつも・よく・たまに",
    "titleZh": "总是・经常・偶尔",
    "category": "habit",
    "difficulty": 2,
    "targetExpression": "いつも／よく／たまに",
    "targetExpressionReading": "いつも／よく／たまに",
    "detect": "いつも|よく|たまに|ときどき",
    "meaningJa": "頻度を表す副詞を使い分ける",
    "meaningZh": "区分使用表示频率的副词",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w04m4",
    "week": 4,
    "order": 4,
    "titleJa": "〜続けています",
    "titleZh": "一直坚持〜",
    "category": "habit",
    "difficulty": 3,
    "targetExpression": "〜続けています",
    "targetExpressionReading": "〜つづけています",
    "detect": "続けています|つづけています|続けて",
    "meaningJa": "同じことをずっと続けている",
    "meaningZh": "一直持续做同一件事",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w04m5",
    "week": 4,
    "order": 5,
    "titleJa": "習慣・総合",
    "titleZh": "习惯・综合",
    "category": "habit",
    "difficulty": 3,
    "targetExpression": "習慣（総合）",
    "targetExpressionReading": "しゅうかん",
    "detect": "ことにしています|ようにしています|続けています|いつも|よく|たまに",
    "meaningJa": "今週の習慣表現で自分の生活習慣を話す",
    "meaningZh": "用本周的习惯表达讲自己的生活习惯",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w04m1",
      "w04m2",
      "w04m3",
      "w04m4"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w05m1",
    "week": 5,
    "order": 1,
    "titleJa": "〜てもいいですか",
    "titleZh": "可以〜吗",
    "category": "permission",
    "difficulty": 2,
    "targetExpression": "〜てもいいですか",
    "targetExpressionReading": "〜てもいいですか",
    "detect": "てもいいですか|でもいいですか",
    "meaningJa": "許可を求める丁寧な言い方",
    "meaningZh": "请求许可的礼貌说法",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w05m2",
    "week": 5,
    "order": 2,
    "titleJa": "〜てもらえますか",
    "titleZh": "能帮我〜吗",
    "category": "permission",
    "difficulty": 3,
    "targetExpression": "〜てもらえますか",
    "targetExpressionReading": "〜てもらえますか",
    "detect": "てもらえますか|でもらえますか",
    "meaningJa": "相手に何かをしてもらう依頼",
    "meaningZh": "请求对方帮自己做某事",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w05m3",
    "week": 5,
    "order": 3,
    "titleJa": "〜ていただけませんか",
    "titleZh": "能否请您〜",
    "category": "permission",
    "difficulty": 4,
    "targetExpression": "〜ていただけませんか",
    "targetExpressionReading": "〜ていただけませんか",
    "detect": "ていただけませんか|でいただけませんか|ていただけますか",
    "meaningJa": "より丁寧な依頼（目上・仕事向け）",
    "meaningZh": "更礼貌的请求（对上级・工作场合）",
    "chineseSupport": "rich",
    "correctionPriority": "target",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w05m4",
    "week": 5,
    "order": 4,
    "titleJa": "〜てほしいです",
    "titleZh": "希望（对方）〜",
    "category": "permission",
    "difficulty": 3,
    "targetExpression": "〜てほしいです",
    "targetExpressionReading": "〜てほしいです",
    "detect": "てほしい|でほしい",
    "meaningJa": "相手にしてほしい願望を伝える",
    "meaningZh": "表达希望对方做某事的愿望",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w05m5",
    "week": 5,
    "order": 5,
    "titleJa": "許可・依頼・総合",
    "titleZh": "许可・请求・综合",
    "category": "permission",
    "difficulty": 4,
    "targetExpression": "許可・依頼（総合）",
    "targetExpressionReading": "きょかいらい",
    "detect": "てもいいですか|てもらえますか|ていただけ|てほしい",
    "meaningJa": "場面に合わせて許可・依頼を使い分ける",
    "meaningZh": "根据场合区分使用许可和请求",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w05m1",
      "w05m2",
      "w05m3",
      "w05m4"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w06m1",
    "week": 6,
    "order": 1,
    "titleJa": "〜てしまいました",
    "titleZh": "不小心〜了",
    "category": "trouble",
    "difficulty": 3,
    "targetExpression": "〜てしまいました",
    "targetExpressionReading": "〜てしまいました",
    "detect": "てしまいました|でしまいました|ちゃいました|じゃいました",
    "meaningJa": "失敗・後悔・完了を表す",
    "meaningZh": "表示失误・后悔・完成",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w06m2",
    "week": 6,
    "order": 2,
    "titleJa": "〜なくて困っています",
    "titleZh": "因为不〜而困扰",
    "category": "trouble",
    "difficulty": 3,
    "targetExpression": "〜なくて困っています",
    "targetExpressionReading": "〜なくてこまっています",
    "detect": "なくて困|なくてこまって|困っています",
    "meaningJa": "何かができなくて困っている状況を言う",
    "meaningZh": "表达因为做不到某事而困扰",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w06m3",
    "week": 6,
    "order": 3,
    "titleJa": "どうすればいいですか",
    "titleZh": "该怎么办才好",
    "category": "trouble",
    "difficulty": 3,
    "targetExpression": "どうすればいいですか",
    "targetExpressionReading": "どうすればいいですか",
    "detect": "どうすれば|どうしたらいい",
    "meaningJa": "アドバイスを求める言い方",
    "meaningZh": "寻求建议的说法",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w06m4",
    "week": 6,
    "order": 4,
    "titleJa": "〜ほうがいいですか",
    "titleZh": "〜比较好吗",
    "category": "trouble",
    "difficulty": 3,
    "targetExpression": "〜ほうがいいですか",
    "targetExpressionReading": "〜ほうがいいですか",
    "detect": "ほうがいいですか|方がいいですか",
    "meaningJa": "二択で助言を求める",
    "meaningZh": "在两个选择间寻求建议",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w06m5",
    "week": 6,
    "order": 5,
    "titleJa": "相談・総合",
    "titleZh": "咨询・综合",
    "category": "trouble",
    "difficulty": 3,
    "targetExpression": "相談（総合）",
    "targetExpressionReading": "そうだん",
    "detect": "てしまいました|なくて困|どうすれば|ほうがいいですか",
    "meaningJa": "状況説明→困った→相談、の流れで話す",
    "meaningZh": "按 说明情况→困扰→咨询 的顺序讲",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w06m1",
      "w06m2",
      "w06m3",
      "w06m4"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w07m1",
    "week": 7,
    "order": 1,
    "titleJa": "〜と思います",
    "titleZh": "我认为〜",
    "category": "opinion",
    "difficulty": 2,
    "targetExpression": "〜と思います",
    "targetExpressionReading": "〜とおもいます",
    "detect": "と思います|とおもいます|と思う",
    "meaningJa": "自分の意見・考えを述べる",
    "meaningZh": "陈述自己的意见・想法",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w07m2",
    "week": 7,
    "order": 2,
    "titleJa": "〜からです",
    "titleZh": "因为〜",
    "category": "opinion",
    "difficulty": 2,
    "targetExpression": "〜からです",
    "targetExpressionReading": "〜からです",
    "detect": "からです|からだと思",
    "meaningJa": "理由を説明する言い方",
    "meaningZh": "说明理由的说法",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w07m3",
    "week": 7,
    "order": 3,
    "titleJa": "〜ので",
    "titleZh": "因为〜（所以）",
    "category": "opinion",
    "difficulty": 3,
    "targetExpression": "〜ので",
    "targetExpressionReading": "〜ので",
    "detect": "ので、|のででき|のでした|ので。",
    "meaningJa": "理由を丁寧・柔らかくつなぐ",
    "meaningZh": "礼貌・委婉地连接理由",
    "chineseSupport": "rich",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w07m4",
    "week": 7,
    "order": 4,
    "titleJa": "私の場合は〜",
    "titleZh": "就我而言〜",
    "category": "opinion",
    "difficulty": 4,
    "targetExpression": "私の場合は〜",
    "targetExpressionReading": "わたしのばあいは〜",
    "detect": "私の場合|わたしの場合|場合は",
    "meaningJa": "自分の立場・状況に限定して意見を言う",
    "meaningZh": "限定在自己的立场・情况来陈述意见",
    "chineseSupport": "normal",
    "correctionPriority": "target",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w07m5",
    "week": 7,
    "order": 5,
    "titleJa": "意見説明・総合",
    "titleZh": "意见说明・综合",
    "category": "opinion",
    "difficulty": 4,
    "targetExpression": "意見説明（総合）",
    "targetExpressionReading": "いけんせつめい",
    "detect": "と思います|からです|ので|私の場合",
    "meaningJa": "意見＋理由をセットで述べる",
    "meaningZh": "把意见和理由成套地陈述",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w07m1",
      "w07m2",
      "w07m3",
      "w07m4"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w08m1",
    "week": 8,
    "order": 1,
    "titleJa": "〜より〜のほうが",
    "titleZh": "比起〜，〜更",
    "category": "comparison",
    "difficulty": 2,
    "targetExpression": "〜より〜のほうが",
    "targetExpressionReading": "〜より〜のほうが",
    "detect": "よりも|より.*ほうが|のほうが",
    "meaningJa": "二つを比べてどちらかを選ぶ",
    "meaningZh": "比较两者并选出其一",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w08m2",
    "week": 8,
    "order": 2,
    "titleJa": "〜ほど〜ない",
    "titleZh": "没有〜那么〜",
    "category": "comparison",
    "difficulty": 4,
    "targetExpression": "〜ほど〜ない",
    "targetExpressionReading": "〜ほど〜ない",
    "detect": "ほど.*ない|ほどでは",
    "meaningJa": "程度が及ばないことを表す",
    "meaningZh": "表示程度不及",
    "chineseSupport": "rich",
    "correctionPriority": "target",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w08m3",
    "week": 8,
    "order": 3,
    "titleJa": "どちらかというと",
    "titleZh": "要说的话，比较〜",
    "category": "comparison",
    "difficulty": 4,
    "targetExpression": "どちらかというと",
    "targetExpressionReading": "どちらかというと",
    "detect": "どちらかというと|どっちかというと",
    "meaningJa": "はっきりしないが、あえて選ぶと",
    "meaningZh": "不太确定，但硬要选的话",
    "chineseSupport": "normal",
    "correctionPriority": "target",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w08m4",
    "week": 8,
    "order": 4,
    "titleJa": "〜に比べて",
    "titleZh": "与〜相比",
    "category": "comparison",
    "difficulty": 4,
    "targetExpression": "〜に比べて",
    "targetExpressionReading": "〜にくらべて",
    "detect": "に比べて|にくらべて|と比べて",
    "meaningJa": "基準と比べて違いを述べる",
    "meaningZh": "与基准相比来说明差异",
    "chineseSupport": "normal",
    "correctionPriority": "target",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w08m5",
    "week": 8,
    "order": 5,
    "titleJa": "比較・総合",
    "titleZh": "比较・综合",
    "category": "comparison",
    "difficulty": 4,
    "targetExpression": "比較（総合）",
    "targetExpressionReading": "ひかく",
    "detect": "のほうが|ほど.*ない|どちらかというと|に比べて",
    "meaningJa": "複数の比較表現で自分の好みや変化を話す",
    "meaningZh": "用多种比较表达讲自己的喜好或变化",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w08m1",
      "w08m2",
      "w08m3",
      "w08m4"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w09m1",
    "week": 9,
    "order": 1,
    "titleJa": "〜かもしれません",
    "titleZh": "也许〜",
    "category": "guess",
    "difficulty": 3,
    "targetExpression": "〜かもしれません",
    "targetExpressionReading": "〜かもしれません",
    "detect": "かもしれません|かもしれない|かも。",
    "meaningJa": "可能性がある（確信は低め）",
    "meaningZh": "有可能（把握不大）",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w09m2",
    "week": 9,
    "order": 2,
    "titleJa": "〜そうです（様態）",
    "titleZh": "看起来〜",
    "category": "guess",
    "difficulty": 3,
    "targetExpression": "〜そうです",
    "targetExpressionReading": "〜そうです",
    "detect": "そうです|そうだ|そうな",
    "meaningJa": "見た目からの推測を言う",
    "meaningZh": "根据外观进行推测",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w09m3",
    "week": 9,
    "order": 3,
    "titleJa": "〜ようです",
    "titleZh": "好像〜",
    "category": "guess",
    "difficulty": 4,
    "targetExpression": "〜ようです",
    "targetExpressionReading": "〜ようです",
    "detect": "ようです|ようだ|みたいです",
    "meaningJa": "状況から判断した推測（根拠あり）",
    "meaningZh": "根据情况判断的推测（有依据）",
    "chineseSupport": "normal",
    "correctionPriority": "target",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w09m4",
    "week": 9,
    "order": 4,
    "titleJa": "〜はずです",
    "titleZh": "应该〜",
    "category": "guess",
    "difficulty": 4,
    "targetExpression": "〜はずです",
    "targetExpressionReading": "〜はずです",
    "detect": "はずです|はずだ|はずが",
    "meaningJa": "根拠があって当然そうだと考える",
    "meaningZh": "有依据地认为理应如此",
    "chineseSupport": "normal",
    "correctionPriority": "target",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w09m5",
    "week": 9,
    "order": 5,
    "titleJa": "推測・総合",
    "titleZh": "推测・综合",
    "category": "guess",
    "difficulty": 4,
    "targetExpression": "推測（総合）",
    "targetExpressionReading": "すいそく",
    "detect": "かもしれません|そうです|ようです|はずです",
    "meaningJa": "確信度に応じて推測表現を使い分ける",
    "meaningZh": "根据把握程度区分使用推测表达",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w09m1",
      "w09m2",
      "w09m3",
      "w09m4"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w10m1",
    "week": 10,
    "order": 1,
    "titleJa": "〜ことになっています",
    "titleZh": "按规定〜",
    "category": "workLife",
    "difficulty": 4,
    "targetExpression": "〜ことになっています",
    "targetExpressionReading": "〜ことになっています",
    "detect": "ことになっています|ことになって",
    "meaningJa": "規則・予定として決まっていることを言う",
    "meaningZh": "表达作为规则・预定已确定的事",
    "chineseSupport": "rich",
    "correctionPriority": "target",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w10m2",
    "week": 10,
    "order": 2,
    "titleJa": "〜なければなりません",
    "titleZh": "必须〜",
    "category": "workLife",
    "difficulty": 3,
    "targetExpression": "〜なければなりません",
    "targetExpressionReading": "〜なければなりません",
    "detect": "なければなりません|なければならない|なきゃ|ないといけ",
    "meaningJa": "義務・しなければならないことを言う",
    "meaningZh": "表达义务・必须做的事",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w10m3",
    "week": 10,
    "order": 3,
    "titleJa": "〜させていただきます",
    "titleZh": "请允许我〜",
    "category": "workLife",
    "difficulty": 5,
    "targetExpression": "〜させていただきます",
    "targetExpressionReading": "〜させていただきます",
    "detect": "させていただきます|させていただき|させてもらい",
    "meaningJa": "自分の行動をとても丁寧に言う（謙譲）",
    "meaningZh": "非常礼貌地表达自己的行为（谦让）",
    "chineseSupport": "rich",
    "correctionPriority": "target",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w10m4",
    "week": 10,
    "order": 4,
    "titleJa": "〜について確認したいです",
    "titleZh": "想确认关于〜",
    "category": "workLife",
    "difficulty": 4,
    "targetExpression": "〜について確認したいです",
    "targetExpressionReading": "〜についてかくにんしたいです",
    "detect": "について確認|についてかくにん|について聞きたい",
    "meaningJa": "あるテーマについて確認・質問する",
    "meaningZh": "就某个主题进行确认・提问",
    "chineseSupport": "normal",
    "correctionPriority": "target",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w10m5",
    "week": 10,
    "order": 5,
    "titleJa": "実用場面・総合",
    "titleZh": "实用场景・综合",
    "category": "workLife",
    "difficulty": 4,
    "targetExpression": "実用場面（総合）",
    "targetExpressionReading": "じつようばめん",
    "detect": "ことになっています|なければなりません|させていただき|について確認",
    "meaningJa": "仕事の場面で丁寧に説明・依頼する",
    "meaningZh": "在工作场景中礼貌地说明・请求",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w10m1",
      "w10m2",
      "w10m3",
      "w10m4"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w11m1",
    "week": 11,
    "order": 1,
    "titleJa": "一緒に〜ませんか",
    "titleZh": "要不要一起〜",
    "category": "badminton",
    "difficulty": 2,
    "targetExpression": "一緒に〜ませんか",
    "targetExpressionReading": "いっしょに〜ませんか",
    "detect": "一緒に.*ませんか|いっしょに.*ませんか|ませんか",
    "meaningJa": "相手を誘う言い方",
    "meaningZh": "邀请对方的说法",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w11m2",
    "week": 11,
    "order": 2,
    "titleJa": "〜ても大丈夫ですか",
    "titleZh": "〜也没关系吗",
    "category": "badminton",
    "difficulty": 3,
    "targetExpression": "〜ても大丈夫ですか",
    "targetExpressionReading": "〜てもだいじょうぶですか",
    "detect": "ても大丈夫|でも大丈夫|てもだいじょうぶ",
    "meaningJa": "相手の都合・可否をやわらかく確認する",
    "meaningZh": "委婉地确认对方是否方便・是否可以",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w11m3",
    "week": 11,
    "order": 3,
    "titleJa": "もう一度お願いします",
    "titleZh": "请再说一次",
    "category": "badminton",
    "difficulty": 2,
    "targetExpression": "もう一度お願いします",
    "targetExpressionReading": "もういちどおねがいします",
    "detect": "もう一度|もういちど|もう一回",
    "meaningJa": "聞き取れないときに聞き返す",
    "meaningZh": "听不清时请对方重复",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w11m4",
    "week": 11,
    "order": 4,
    "titleJa": "〜したほうがいいと思います",
    "titleZh": "我觉得最好〜",
    "category": "badminton",
    "difficulty": 4,
    "targetExpression": "〜したほうがいいと思います",
    "targetExpressionReading": "〜したほうがいいとおもいます",
    "detect": "ほうがいいと思|ほうがいいとおも|たほうがいい",
    "meaningJa": "相手にやわらかくアドバイスする",
    "meaningZh": "委婉地给对方建议",
    "chineseSupport": "normal",
    "correctionPriority": "target",
    "requiredPreviousItems": [],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w11m5",
    "week": 11,
    "order": 5,
    "titleJa": "バドミントン交流・総合",
    "titleZh": "羽毛球交流・综合",
    "category": "badminton",
    "difficulty": 3,
    "targetExpression": "バドミントン交流（総合）",
    "targetExpressionReading": "こうりゅう",
    "detect": "一緒に.*ませんか|ても大丈夫|もう一度|ほうがいいと思",
    "meaningJa": "交流場面で誘い・確認・助言を自然に使う",
    "meaningZh": "在交流场景中自然地邀请・确认・建议",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w11m1",
      "w11m2",
      "w11m3",
      "w11m4"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w12m1",
    "week": 12,
    "order": 1,
    "titleJa": "経験＋変化",
    "titleZh": "经历＋变化",
    "category": "integrated",
    "difficulty": 4,
    "targetExpression": "経験＋変化",
    "targetExpressionReading": "けいけん＋へんか",
    "detect": "たことがあり|ようになりました|てから|てきました",
    "meaningJa": "経験と成長を組み合わせて語る",
    "meaningZh": "把经历和成长组合起来讲",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w02m1",
      "w03m1"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w12m2",
    "week": 12,
    "order": 2,
    "titleJa": "問題＋相談",
    "titleZh": "问题＋咨询",
    "category": "integrated",
    "difficulty": 4,
    "targetExpression": "問題＋相談",
    "targetExpressionReading": "もんだい＋そうだん",
    "detect": "てしまいました|なくて困|どうすれば|ほうがいいですか",
    "meaningJa": "問題を説明して相談する",
    "meaningZh": "说明问题并咨询",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w06m1",
      "w06m3"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w12m3",
    "week": 12,
    "order": 3,
    "titleJa": "意見＋理由",
    "titleZh": "意见＋理由",
    "category": "integrated",
    "difficulty": 4,
    "targetExpression": "意見＋理由",
    "targetExpressionReading": "いけん＋りゆう",
    "detect": "と思います|からです|ので|私の場合",
    "meaningJa": "意見を理由つきでしっかり述べる",
    "meaningZh": "有理有据地陈述意见",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w07m1",
      "w07m4"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w12m4",
    "week": 12,
    "order": 4,
    "titleJa": "比較＋提案",
    "titleZh": "比较＋提议",
    "category": "integrated",
    "difficulty": 5,
    "targetExpression": "比較＋提案",
    "targetExpressionReading": "ひかく＋ていあん",
    "detect": "のほうが|に比べて|ほうがいいと思|ませんか",
    "meaningJa": "比較したうえで提案する",
    "meaningZh": "在比较之后提出建议",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w08m1",
      "w11m4"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  },
  {
    "id": "w12m5",
    "week": 12,
    "order": 5,
    "titleJa": "最終総合会話",
    "titleZh": "最终综合会话",
    "category": "integrated",
    "difficulty": 5,
    "targetExpression": "最終総合会話",
    "targetExpressionReading": "さいしゅうそうごう",
    "detect": "たことがあり|ようになりました|と思います|のほうが|ませんか",
    "meaningJa": "12週間の表現を自由に使って会話する",
    "meaningZh": "自由运用12周的表达进行会话",
    "chineseSupport": "normal",
    "correctionPriority": "both",
    "requiredPreviousItems": [
      "w12m1",
      "w12m2",
      "w12m3",
      "w12m4"
    ],
    "estimatedMinutes": 3,
    "isPublished": true,
    "curriculumVersion": "v1",
    "usageNotesJa": "",
    "usageNotesZh": "",
    "naturalExample": "",
    "simpleExample": "",
    "commonMistakes": [],
    "openingQuestion": "",
    "followUpQuestions": [],
    "hintLevels": [],
    "completionCriteria": "",
    "reviewPrompts": {
      "day1": "",
      "day3": "",
      "day7": ""
    },
    "alternateScenes": []
  }
];
