// N1文法 Unit 2（15項目 / 理由・目的・条件の書き言葉）。
// 例文・訳・解説はすべて自社で書き起こす。
import { n1g, type N1GrammarDraft } from './n1GrammarDrafts';

export const N1_GRAMMAR_DRAFTS_UNIT2: N1GrammarDraft[] = [
  n1g({
    grammarId: 'n1g-016', pattern: '〜ゆえ（に）', reading: 'ゆえに', unit: 2,
    meaningJa: '〜が理由で',
    explanationZh: '因为…。是「から・ので」的书面（文语）说法',
    formation: '名詞（＋の）／動詞・形容詞の普通形＋ゆえ（に）',
    usageScene: '论说文、正式的说明中陈述理由',
    nuance: '硬い書き言葉。話し言葉では使わない',
    register: 'written',
    examplesJa: ['経験が浅いゆえに、判断を誤りました。', '高齢ゆえの不安を訴える人が増えています。'],
    examplesZh: ['因为经验尚浅，判断出了错。', '诉说因高龄而产生的不安的人在增加。'],
    furigana: 'けいけんが あさい ゆえに、はんだんを あやまりました。',
    commonMistakesZh: '不用于日常会话。「おなかがすいたゆえに食べた」不自然，要用「から」',
    learnerFocus: '「ゆえに」在阅读中出现频率高，但自己说话时用「ので」即可',
    similarPatterns: ['〜ので', '〜ため'],
    contrast: '「ゆえに」＝論説文の書き言葉；「ので」＝話し言葉でも使える標準形',
    recognition: {
      promptZh: '「ゆえに」最接近下面哪一个？',
      options: ['ので', 'のに', 'ながら', 'ばかり'],
      answerIndex: 0,
      distractorReason: '「ゆえに」は理由を表す文語。逆接や同時進行ではない',
      distractorReasonZh: '「ゆえに」是表示理由的文语，不是逆接或同时进行',
      explanationZh: '「〜ゆえに」＝因为…（书面语）',
    },
    production: {
      promptJa: '理由を「〜ゆえに」で述べてください。', promptZh: '用「〜ゆえに」陈述一个理由。',
      expected: ['ゆえ'], acceptable: ['ゆえに'],
    },
    practice: {
      themeJa: '理由を硬い言い方で述べる', starterJa: '判断を間違えた理由は何でしたか？',
      starterZh: '判断出错的原因是什么？', targetUse: '〜ゆえに',
    },
    matchKeys: ['ゆえ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-017', pattern: '〜こととて', reading: 'こととて', unit: 2,
    meaningJa: '〜という事情なので（おわびの理由）',
    explanationZh: '因为是…（的情况），所以…。多用于道歉时说明缘由',
    formation: '名詞＋の／動詞・形容詞の普通形＋こととて',
    usageScene: '书信、正式场合的致歉',
    nuance: 'あやまるときの言い訳として使う古風な言い方',
    register: 'written',
    examplesJa: ['慣れぬこととて、ご迷惑をおかけしました。', '急なこととて、十分な準備ができませんでした。'],
    examplesZh: ['因为还不熟悉，给您添麻烦了。', '因为事出突然，没能做好充分准备。'],
    furigana: 'なれぬ こととて、ごめいわくを おかけしました。',
    commonMistakesZh: '后面要接道歉或请求谅解的内容，不接普通的结果',
    learnerFocus: '几乎只在书信里出现。考试考的是「＝〜ので（おわび）」这个对应',
    similarPatterns: ['〜ゆえに', '〜ので'],
    contrast: '「こととて」＝おわびの理由；「ゆえに」＝論理的な理由で、おわびとは限らない',
    recognition: {
      promptZh: '哪个句子用「こととて」自然？',
      options: ['不慣れなこととて、お許しください', '楽しいこととて、また行きます', '安いこととて、買いました', '晴れたこととて、出かけます'],
      answerIndex: 0,
      distractorReason: '「こととて」の後ろにはおわびや許しを求める言葉が来る',
      distractorReasonZh: '「こととて」后面接道歉或请求原谅的内容',
      explanationZh: '「〜こととて」＝因为是…（的情况），请见谅',
    },
    production: {
      promptJa: 'あやまるときの理由を「〜こととて」で言ってください。', promptZh: '用「〜こととて」说一个道歉时的理由。',
      expected: ['こととて'], acceptable: [],
    },
    practice: {
      themeJa: 'ていねいにあやまる', starterJa: '迷惑をかけてしまったことはありますか？',
      starterZh: '有过给别人添麻烦的事吗？', targetUse: '〜こととて',
    },
    matchKeys: ['こととて'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-018', pattern: '〜とあって', reading: 'とあって', unit: 2,
    meaningJa: '〜という特別な状況なので',
    explanationZh: '因为是…（特殊情况），所以…。多用于报道',
    formation: '名詞／動詞・形容詞の普通形＋とあって',
    usageScene: '新闻报道中说明「因为是这样的场合，所以出现了这种现象」',
    nuance: '当然そうなるという結果を導く。自分のことには使いにくい',
    register: 'written',
    examplesJa: ['連休とあって、駅は人でいっぱいでした。', '人気の店とあって、朝から列ができています。'],
    examplesZh: ['因为是连休，车站挤满了人。', '因为是人气店铺，一早就排起了队。'],
    furigana: 'れんきゅう とあって、えきは ひとで いっぱいでした。',
    commonMistakesZh: '不用于自己的行为：「私は忙しいとあって休んだ」不自然',
    learnerFocus: '「とあって」的后面必定是「大家都会那样做」的自然结果',
    similarPatterns: ['〜だけあって', '〜ので'],
    contrast: '「とあって」＝特別な事情→当然の結果（報道）；「だけあって」＝評価に見合う結果（ほめる）',
    recognition: {
      promptZh: '哪个句子用「とあって」自然？',
      options: ['祭りとあって町はにぎやかだ', '雨とあって私は傘を買った', '安いとあって私は買わない', '寒いとあって暑くなった'],
      answerIndex: 0,
      distractorReason: '「とあって」は多くの人に共通して起こる自然な結果を導く',
      distractorReasonZh: '「とあって」引出多数人共通的自然结果',
      explanationZh: '「〜とあって」＝因为是…的场合（所以自然会…）',
    },
    production: {
      promptJa: '混んでいた日のことを「〜とあって」で言ってください。', promptZh: '用「〜とあって」说一个很拥挤的日子。',
      expected: ['とあって'], acceptable: [],
    },
    practice: {
      themeJa: '混雑の理由を説明する', starterJa: '町がとても混んでいた日はありましたか？',
      starterZh: '有过街上非常拥挤的日子吗？', targetUse: '〜とあって',
    },
    matchKeys: ['とあって'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-019', pattern: '〜とあれば', reading: 'とあれば', unit: 2,
    meaningJa: '〜という事情なら（何でもする）',
    explanationZh: '如果是为了…的话（就…）。表示为此愿意付出',
    formation: '名詞／動詞普通形＋とあれば',
    usageScene: '表达「为了这个目的，我愿意做到那种程度」',
    nuance: '後ろに強い意志や決意が来る',
    register: 'written',
    examplesJa: ['子どものためとあれば、どんな苦労もします。', '必要とあれば、すぐに向かいます。'],
    examplesZh: ['如果是为了孩子，再苦我也愿意。', '如果有必要，我马上就过去。'],
    furigana: 'こどもの ため とあれば、どんな くろうも します。',
    commonMistakesZh: '后面接的是意志、决心，不接单纯的事实描写',
    learnerFocus: '「とあって」是既成事实的原因，「とあれば」是假设的条件。一字之差方向不同',
    similarPatterns: ['〜なら', '〜とあって'],
    contrast: '「とあれば」＝仮定の条件＋強い意志；「とあって」＝事実の理由＋自然な結果',
    recognition: {
      promptZh: '哪个句子用「とあれば」自然？',
      options: ['必要とあれば手伝います', '雨とあれば濡れました', '休みとあれば混んでいた', '安いとあれば買った'],
      answerIndex: 0,
      distractorReason: '「とあれば」の後ろには意志や決意が来る。過去の事実は置けない',
      distractorReasonZh: '「とあれば」后面接意志或决心，不能放过去的事实',
      explanationZh: '「〜とあれば」＝如果是为了…的话，（就愿意…）',
    },
    production: {
      promptJa: '「これのためなら何でもする」ことを「〜とあれば」で言ってください。',
      promptZh: '用「〜とあれば」说一件「为了它什么都愿意做」的事。',
      expected: ['とあれば'], acceptable: [],
    },
    practice: {
      themeJa: '大切なもののための決意', starterJa: '大切な人のためならどこまでできますか？',
      starterZh: '为了重要的人你能做到什么程度？', targetUse: '〜とあれば',
    },
    matchKeys: ['とあれば'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-020', pattern: '〜ではあるまいし', reading: 'ではあるまいし', unit: 2,
    meaningJa: '〜ではないのだから（〜するのはおかしい）',
    explanationZh: '又不是…（所以不该…）。带有责备的语气',
    formation: '名詞＋ではあるまいし／動詞普通形＋のではあるまいし',
    usageScene: '批评对方的行为不合身份、不合常理',
    nuance: '相手をたしなめる言い方。目上には使わない',
    register: 'spoken',
    examplesJa: ['子どもではあるまいし、自分で片づけてください。', '初めてではあるまいし、落ち着いてやりましょう。'],
    examplesZh: ['又不是小孩子，请自己收拾。', '又不是第一次，冷静点做吧。'],
    furigana: 'こども では あるまいし、じぶんで かたづけて ください。',
    commonMistakesZh: '语气较冲，不对长辈或客户使用',
    learnerFocus: '后面常接命令、劝告。理解为「你又不是…，所以应该…」',
    similarPatterns: ['〜じゃあるまいし', '〜わけではないのだから'],
    contrast: '「ではあるまいし」＝相手をたしなめる；「わけではないのだから」＝中立に理由を述べる',
    recognition: {
      promptZh: '「子どもではあるまいし」是什么意思？',
      options: ['又不是小孩子', '因为是小孩子', '想当小孩子', '像小孩子一样好'],
      answerIndex: 0,
      distractorReason: '「ではあるまいし」は「〜ではないのだから」の意味',
      distractorReasonZh: '「ではあるまいし」意为「又不是…」',
      explanationZh: '「〜ではあるまいし」＝又不是…（所以不该那样）',
    },
    production: {
      promptJa: '相手をたしなめる言い方を「〜ではあるまいし」で作ってください。',
      promptZh: '用「〜ではあるまいし」造一句劝诫对方的话。',
      expected: ['ではあるまいし'], acceptable: ['じゃあるまいし'],
    },
    practice: {
      themeJa: '軽くたしなめる', starterJa: '友達に「しっかりして」と言いたいときは？',
      starterZh: '想对朋友说「振作点」时怎么说？', targetUse: '〜ではあるまいし',
    },
    matchKeys: ['ではあるまいし', 'じゃあるまいし'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-021', pattern: '〜手前', reading: 'てまえ', unit: 2,
    meaningJa: '〜という立場上、〜しないわけにいかない',
    explanationZh: '碍于…的立场（不得不…）。因为在别人面前说过或做过',
    formation: '名詞＋の／動詞普通形＋手前',
    usageScene: '说明因为面子、立场而不得不做某事',
    nuance: '人の目を意識した理由。体面の話',
    register: 'spoken',
    examplesJa: ['やると言った手前、途中でやめられません。', '後輩の手前、弱音は吐けませんでした。'],
    examplesZh: ['碍于说过要做，中途不能放弃。', '在后辈面前，说不出泄气话。'],
    furigana: 'やると いった てまえ、とちゅうで やめられません。',
    commonMistakesZh: '不是位置的「前面」。这里是「碍于…的立场」的意思',
    learnerFocus: '后面几乎都接「〜できない」「〜わけにはいかない」等否定的可能形',
    similarPatterns: ['〜以上は', '〜からには'],
    contrast: '「手前」＝人目・体面が理由；「からには」＝決意が理由で、体面は関係ない',
    recognition: {
      promptZh: '哪个句子用「手前」自然？',
      options: ['約束した手前、行かないわけにはいかない', '駅の手前で約束した', '手前の店で買った', '手前に立って待った'],
      answerIndex: 0,
      distractorReason: '文法の「手前」は立場・体面の意味。場所の「手前」とは別',
      distractorReasonZh: '语法的「手前」指立场、面子，与表示位置的「手前」不同',
      explanationZh: '「〜手前」＝碍于…的立场，不能不…',
    },
    production: {
      promptJa: '立場上やめられなかったことを「〜手前」で言ってください。',
      promptZh: '用「〜手前」说一件碍于立场无法放弃的事。',
      expected: ['手前'], acceptable: ['てまえ'],
    },
    practice: {
      themeJa: '立場上できなかったこと', starterJa: '人の目があってやめられなかったことは？',
      starterZh: '有过因为顾及别人目光而无法放弃的事吗？', targetUse: '〜手前',
    },
    matchKeys: ['手前'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-022', pattern: '〜ばこそ', reading: 'ばこそ', unit: 2,
    meaningJa: '〜だからこそ（他でもなくその理由で）',
    explanationZh: '正因为…才…。强调唯一的、真正的理由',
    formation: '動詞・形容詞の仮定形＋ばこそ',
    usageScene: '说明严厉的态度其实出于善意',
    nuance: 'よい理由を強調するときに使う。後ろは肯定的な内容',
    register: 'written',
    examplesJa: ['大切に思えばこそ、厳しく言うのです。', '健康であればこそ、働き続けられます。'],
    examplesZh: ['正因为珍视，才严厉地说。', '正因为身体健康，才能一直工作。'],
    furigana: 'たいせつに おもえば こそ、きびしく いうのです。',
    commonMistakesZh: '后面不接负面结果。「嫌いであればこそ怒った」不自然',
    learnerFocus: '「〜からこそ」的书面版。看到「ば＋こそ」就换成「からこそ」理解',
    similarPatterns: ['〜からこそ', '〜ゆえに'],
    contrast: '「ばこそ」＝文語で、よい理由を強調；「からこそ」＝話し言葉でも使える',
    recognition: {
      promptZh: '「思えばこそ」是什么意思？',
      options: ['正因为这样想才…', '虽然这样想', '如果这样想', '不这样想'],
      answerIndex: 0,
      distractorReason: '「ばこそ」は理由の強調で、逆接や仮定ではない',
      distractorReasonZh: '「ばこそ」是强调理由，不是逆接或假设',
      explanationZh: '「〜ばこそ」＝正因为…才…',
    },
    production: {
      promptJa: '厳しくする理由を「〜ばこそ」で言ってください。', promptZh: '用「〜ばこそ」说明严格的理由。',
      expected: ['ばこそ'], acceptable: [],
    },
    practice: {
      themeJa: '厳しさの裏にある気持ち', starterJa: '厳しく言われて後で分かったことはありますか？',
      starterZh: '有过被严厉批评后来才明白的事吗？', targetUse: '〜ばこそ',
    },
    matchKeys: ['ばこそ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-023', pattern: '〜あっての', reading: 'あっての', unit: 2,
    meaningJa: '〜があるから成り立つ',
    explanationZh: '有…才有…。强调不可缺少的前提',
    formation: '名詞＋あっての＋名詞',
    usageScene: '致辞中感谢支持者，或强调基础的重要性',
    nuance: '感謝を述べる場面でよく使う',
    register: 'written',
    examplesJa: ['お客様あっての商売だと考えています。', '健康あっての仕事なので、無理はしません。'],
    examplesZh: ['我认为有顾客才有生意。', '有健康才有工作，所以不勉强。'],
    furigana: 'おきゃくさま あっての しょうばい だと かんがえて います。',
    commonMistakesZh: '前后都是名词。「働くあっての生活」不成立，要用名词「仕事あっての生活」',
    learnerFocus: '「AあってのB」＝没有A就没有B。考试常考前后名词的顺序',
    similarPatterns: ['〜なくしては', '〜のおかげで'],
    contrast: '「あっての」＝前提そのものを名詞で示す；「おかげで」＝理由を述べるだけ',
    recognition: {
      promptZh: '「読者あっての雑誌」是什么意思？',
      options: ['有读者才有杂志', '杂志比读者重要', '读者在读杂志', '杂志没有读者'],
      answerIndex: 0,
      distractorReason: '「AあってのB」はAが無ければBは成り立たないという意味',
      distractorReasonZh: '「AあってのB」表示没有A就没有B',
      explanationZh: '「〜あっての」＝有…才有…',
    },
    production: {
      promptJa: '大切な前提を「〜あっての」で言ってください。', promptZh: '用「〜あっての」说一个重要的前提。',
      expected: ['あっての'], acceptable: [],
    },
    practice: {
      themeJa: '支えてくれる存在に感謝する', starterJa: 'あなたの仕事や生活を支えているものは何ですか？',
      starterZh: '支撑你工作或生活的是什么？', targetUse: '〜あっての',
    },
    matchKeys: ['あっての'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-024', pattern: '〜なくして（は）', reading: 'なくしては', unit: 2,
    meaningJa: '〜がなければ（〜できない）',
    explanationZh: '没有…就（不能…）。是书面的必要条件说法',
    formation: '名詞＋なくして（は）',
    usageScene: '论说文中强调不可或缺的条件',
    nuance: '後ろは必ず打ち消し。硬い書き言葉',
    register: 'written',
    examplesJa: ['地域の協力なくして、この行事は続きません。', '努力なくしては、上達は望めません。'],
    examplesZh: ['没有社区的协助，这项活动无法延续。', '没有努力，就无法期待进步。'],
    furigana: 'ちいきの きょうりょく なくして、この ぎょうじは つづきません。',
    commonMistakesZh: '后面必须是否定。「協力なくして成功した」不成立',
    learnerFocus: '「あっての」是名词修饰，「なくしては」是条件句。用法位置不同',
    similarPatterns: ['〜あっての', '〜がなければ'],
    contrast: '「なくしては」＝条件節で後ろは否定；「あっての」＝名詞を修飾する形',
    recognition: {
      promptZh: '哪个句子用「なくしては」自然？',
      options: ['支援なくしては続けられない', '支援なくしては成功した', '支援なくしては便利だ', '支援なくしては買った'],
      answerIndex: 0,
      distractorReason: '「なくしては」の後ろは打ち消し。肯定の結果は置けない',
      distractorReasonZh: '「なくしては」后面接否定，不能放肯定的结果',
      explanationZh: '「〜なくしては」＝没有…就不能…',
    },
    production: {
      promptJa: '欠かせない条件を「〜なくしては」で言ってください。', promptZh: '用「〜なくしては」说一个不可或缺的条件。',
      expected: ['なくして'], acceptable: ['なくしては'],
    },
    practice: {
      themeJa: '欠かせないものを語る', starterJa: 'これが無ければ続かない、というものは？',
      starterZh: '有什么是「没有它就撑不下去」的？', targetUse: '〜なくしては',
    },
    matchKeys: ['なくして'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-025', pattern: '〜なしに', reading: 'なしに', unit: 2,
    meaningJa: '〜しないで',
    explanationZh: '不…（就…）。表示应有的步骤被省略',
    formation: '名詞＋なしに／動詞辞書形＋こと＋なしに',
    usageScene: '指出未经许可、未经联系就做某事',
    nuance: '本来必要な手順を踏んでいないという含みがある',
    register: 'written',
    examplesJa: ['連絡なしに休むのはやめましょう。', '許可なしに立ち入ることはできません。'],
    examplesZh: ['不联系就请假的做法还是别做。', '未经许可不得进入。'],
    furigana: 'れんらく なしに やすむのは やめましょう。',
    commonMistakesZh: '接动词时要用「〜ことなしに」。「行くなしに」不成立',
    learnerFocus: '「〜ないで」的书面版。告示牌上常见「許可なしに」',
    similarPatterns: ['〜ないで', '〜ことなく'],
    contrast: '「なしに」＝必要な手順を省いた（否定的）；「ことなく」＝ただ「〜しないまま」で中立',
    recognition: {
      promptZh: '哪个句子用「なしに」自然？',
      options: ['断りなしに使ってはいけない', '断りなしに許可を得た', '雨なしに濡れた', '朝なしに起きた'],
      answerIndex: 0,
      distractorReason: '「なしに」は本来必要な手続きを省く意味。時間や天候には付かない',
      distractorReasonZh: '「なしに」表示省略本应有的手续，不接时间或天气',
      explanationZh: '「〜なしに」＝不经…就…',
    },
    production: {
      promptJa: '手順を省くとよくないことを「〜なしに」で言ってください。',
      promptZh: '用「〜なしに」说一件省略步骤就不好的事。',
      expected: ['なしに'], acceptable: ['ことなしに'],
    },
    practice: {
      themeJa: '守るべき手順', starterJa: '職場で必ず必要な連絡は何ですか？',
      starterZh: '在职场上有什么联络是必须做的？', targetUse: '〜なしに',
    },
    matchKeys: ['なしに'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-026', pattern: '〜ずして', reading: 'ずして', unit: 2,
    meaningJa: '〜しないで（〜になる）',
    explanationZh: '不…就…。文语说法，多用于固定搭配',
    formation: '動詞ない形（ない→ず）＋して',
    usageScene: '书面表达「没做某事却出现了结果」',
    nuance: '「労せずして」「戦わずして」など決まった形で覚える',
    register: 'written',
    examplesJa: ['労せずして得たものは身につきません。', '戦わずして勝つのが一番だと言われます。'],
    examplesZh: ['不劳而获的东西留不住。', '常说不战而胜是最好的。'],
    furigana: 'ろうせずして えた ものは みに つきません。',
    commonMistakesZh: '「する」变成「せずして」，不是「しずして」',
    learnerFocus: '几乎只在固定搭配中出现。考试主要考辨认',
    similarPatterns: ['〜ないで', '〜なしに'],
    contrast: '「ずして」＝文語で固定表現中心；「ないで」＝自由に使える標準形',
    recognition: {
      promptZh: '「戦わずして」是什么意思？',
      options: ['不战（就…）', '战斗之后', '一边战斗', '为了战斗'],
      answerIndex: 0,
      distractorReason: '「ずして」は「〜しないで」の文語形',
      distractorReasonZh: '「ずして」是「〜しないで」的文语形式',
      explanationZh: '「〜ずして」＝不…就…',
    },
    production: {
      promptJa: '「苦労しないで手に入れる」を「労せずして」で言ってください。',
      promptZh: '用「労せずして」说「不费力就得到」。',
      expected: ['ずして'], acceptable: ['労せずして'],
    },
    practice: {
      themeJa: '努力と結果の関係', starterJa: '苦労して得たものと、簡単に得たものの違いは？',
      starterZh: '辛苦得来的和轻易得来的有什么不同？', targetUse: '〜ずして',
    },
    matchKeys: ['ずして'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-027', pattern: '〜とばかりに', reading: 'とばかりに', unit: 2,
    meaningJa: 'まるで「〜」と言うような様子で',
    explanationZh: '仿佛在说…似的。描写并未说出口的态度',
    formation: '引用（〜）＋とばかりに',
    usageScene: '描写他人的表情、动作所传达的意思',
    nuance: '実際には言っていないが、そう見える様子',
    register: 'written',
    examplesJa: ['もう帰れとばかりに、店の明かりが消されました。', '待っていましたとばかりに、みんなが集まりました。'],
    examplesZh: ['店里的灯灭了，仿佛在说该回去了。', '大家聚了过来，仿佛就等着这一刻。'],
    furigana: 'もう かえれ とばかりに、みせの あかりが けされました。',
    commonMistakesZh: '不用于自己的行为，用来描写别人看起来的样子',
    learnerFocus: '前面是引用的内容（命令形或句子），后面是动作',
    similarPatterns: ['〜と言わんばかりに', '〜ように'],
    contrast: '「とばかりに」＝そう言っているような態度；「ように」＝ただの比喩で態度に限らない',
    recognition: {
      promptZh: '「早く帰れとばかりに」是什么意思？',
      options: ['仿佛在说「快回去」似的', '说了「快回去」', '被要求快回去', '想快点回去'],
      answerIndex: 0,
      distractorReason: '実際に言葉にしていないが、そう言っているように見える様子を表す',
      distractorReasonZh: '表示并未真的说出口，但看起来像在那样说',
      explanationZh: '「〜とばかりに」＝仿佛在说…似的',
    },
    production: {
      promptJa: '態度で示された気持ちを「〜とばかりに」で言ってください。',
      promptZh: '用「〜とばかりに」描写用态度传达的意思。',
      expected: ['とばかりに'], acceptable: ['と言わんばかりに'],
    },
    practice: {
      themeJa: '言葉にしない気持ちを読む', starterJa: '言われなくても伝わった気持ちはありますか？',
      starterZh: '有过没被明说却感受到的意思吗？', targetUse: '〜とばかりに',
    },
    matchKeys: ['とばかりに'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-028', pattern: '〜んがため（に）', reading: 'んがために', unit: 2,
    meaningJa: '〜しようとする目的で',
    explanationZh: '为了…。是「ために」的文语说法，目的性很强',
    formation: '動詞ない形（ない→ん）＋がため（に）',
    usageScene: '论说文中说明强烈的目的',
    nuance: '「する」は「せんがため」になる。硬い書き言葉',
    register: 'written',
    examplesJa: ['生活を守らんがために、皆が声を上げました。', '記録を残さんがため、写真を撮り続けています。'],
    examplesZh: ['为了守护生活，大家都发出了声音。', '为了留下记录，一直在拍照。'],
    furigana: 'せいかつを まもらんが ために、みなが こえを あげました。',
    commonMistakesZh: '「する」的形式是「せんがため」，不是「しんがため」',
    learnerFocus: '看到「〜んがため」就换成「〜ようとして・〜ために」理解',
    similarPatterns: ['〜ために', '〜べく'],
    contrast: '「んがため」＝文語で目的を強調；「ために」＝標準的な目的の言い方',
    recognition: {
      promptZh: '「守らんがために」是什么意思？',
      options: ['为了守护', '虽然守护', '守护之后', '不守护'],
      answerIndex: 0,
      distractorReason: '「んがため」は目的を表す文語',
      distractorReasonZh: '「んがため」是表示目的的文语',
      explanationZh: '「〜んがために」＝为了…',
    },
    production: {
      promptJa: '強い目的を「〜んがために」で言ってください。', promptZh: '用「〜んがために」说一个强烈的目的。',
      expected: ['んがため'], acceptable: ['んがために'],
    },
    practice: {
      themeJa: '守りたいもののための行動', starterJa: '守るために行動したことはありますか？',
      starterZh: '有过为了守护而行动的事吗？', targetUse: '〜んがために',
    },
    matchKeys: ['んがため'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-029', pattern: '〜べく', reading: 'べく', unit: 2,
    meaningJa: '〜するために',
    explanationZh: '为了…。书面的目的说法，后接积极的行动',
    formation: '動詞辞書形＋べく（する→すべく）',
    usageScene: '正式的报告、公告中说明行动的目的',
    nuance: '後ろは意志的な行動。「べきだ」（義務）とは別',
    register: 'written',
    examplesJa: ['原因を確かめるべく、調査を始めました。', '要望に応えるべく、窓口を増やします。'],
    examplesZh: ['为了查明原因，开始了调查。', '为了回应需求，将增加窗口。'],
    furigana: 'げんいんを たしかめる べく、ちょうさを はじめました。',
    commonMistakesZh: '「する」是「すべく」。另外不要与表示义务的「べきだ」混同',
    learnerFocus: '「べく」＝为了（目的）／「べきだ」＝应该（义务）。同一个字根，意思不同',
    similarPatterns: ['〜ために', '〜んがために'],
    contrast: '「べく」＝硬い目的；「べきだ」＝義務・当然',
    recognition: {
      promptZh: '「確かめるべく」是什么意思？',
      options: ['为了确认', '应该确认', '不能确认', '确认之后'],
      answerIndex: 0,
      distractorReason: '「べく」は目的。義務の「べきだ」と混同しやすい',
      distractorReasonZh: '「べく」表示目的，容易与表示义务的「べきだ」混淆',
      explanationZh: '「〜べく」＝为了…',
    },
    production: {
      promptJa: '目的を「〜べく」で言ってください。', promptZh: '用「〜べく」说明一个目的。',
      expected: ['べく'], acceptable: ['すべく'],
    },
    practice: {
      themeJa: '目的をもって始めたこと', starterJa: '何かのために始めたことはありますか？',
      starterZh: '有为了某个目的而开始的事吗？', targetUse: '〜べく',
    },
    matchKeys: ['べく'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-030', pattern: '〜からある／〜からの', reading: 'からある／からの', unit: 2,
    meaningJa: '〜もの多さ・大きさがある',
    explanationZh: '多达…；重达…。强调数量或程度之大',
    formation: '数量詞＋からある（重さ・長さ）／数量詞＋からの（人数・金額）',
    usageScene: '报道中强调数字之大',
    nuance: '少ない数には使わない。必ず「多い・大きい」を強調する',
    register: 'written',
    examplesJa: ['十キロからある荷物を一人で運びました。', '千人からの人が会場に集まりました。'],
    examplesZh: ['一个人搬了重达十公斤的行李。', '多达一千人聚集到了会场。'],
    furigana: 'じゅっキロ から ある にもつを ひとりで はこびました。',
    commonMistakesZh: '重量、长度用「からある」；人数、金额用「からの」',
    learnerFocus: '不是「从…开始」。这里的「から」表示「以上、多达」',
    similarPatterns: ['〜以上', '〜も'],
    contrast: '「からある」＝驚くほど多いと強調；「以上」＝ただの下限で感情は無い',
    recognition: {
      promptZh: '「百人からの人」是什么意思？',
      options: ['多达一百人', '从一百人当中', '不到一百人', '大约一百人'],
      answerIndex: 0,
      distractorReason: '「からの」は「〜も」の意味で、数の多さを強調する',
      distractorReasonZh: '「からの」意为「多达」，强调数量之多',
      explanationZh: '「〜からの」＝多达…（人数、金额）',
    },
    production: {
      promptJa: '驚くほど大きい数を「〜からある」で言ってください。',
      promptZh: '用「〜からある」说一个大得惊人的数字。',
      expected: ['からある'], acceptable: ['からの'],
    },
    practice: {
      themeJa: '驚いた数字の話', starterJa: '数の多さに驚いた経験はありますか？',
      starterZh: '有过被数量之多惊到的经历吗？', targetUse: '〜からある',
    },
    matchKeys: ['からある', 'からの'], vocabularyLinks: [],
  }),
];
