// N1文法 Unit 5（15項目 / 範囲・限定・添加）。
// 例文・訳・解説はすべて自社で書き起こす。
import { n1g, type N1GrammarDraft } from './n1GrammarDrafts';

export const N1_GRAMMAR_DRAFTS_UNIT5: N1GrammarDraft[] = [
  n1g({
    grammarId: 'n1g-061', pattern: '〜に至るまで', reading: 'にいたるまで', unit: 5,
    meaningJa: '〜という細かいところまで',
    explanationZh: '甚至到…。强调范围之广、之细',
    formation: '名詞＋に至るまで',
    usageScene: '强调检查或准备做得非常彻底',
    nuance: '極端な例を挙げて範囲の広さを示す',
    register: 'written',
    examplesJa: ['服装から持ち物に至るまで、細かく決められています。', '書類の書き方から出し方に至るまで説明を受けました。'],
    examplesZh: ['从服装到随身物品，都有细致的规定。', '从文件的写法到提交方式，都听了说明。'],
    furigana: 'ふくそうから もちものに いたるまで、こまかく きめられて います。',
    commonMistakesZh: '常与「〜から」搭配：「AからBに至るまで」',
    learnerFocus: '「AからBに至るまで」整组记住。B放最细、最极端的例子',
    similarPatterns: ['〜まで', '〜から〜にかけて'],
    contrast: '「に至るまで」＝範囲の広さを強調；「から〜にかけて」＝時間や場所の連続',
    recognition: {
      promptZh: '「持ち物に至るまで」是什么意思？',
      options: ['甚至到随身物品', '到了随身物品的地方', '为了随身物品', '除了随身物品'],
      answerIndex: 0,
      distractorReason: '「に至るまで」は範囲の広さ・細かさを示す',
      distractorReasonZh: '「に至るまで」表示范围之广、之细',
      explanationZh: '「〜に至るまで」＝甚至到…',
    },
    production: {
      promptJa: '細かく決まっていることを「〜に至るまで」で言ってください。',
      promptZh: '用「〜に至るまで」说一件规定得很细的事。',
      expected: ['に至るまで'], acceptable: ['にいたるまで'],
    },
    practice: {
      themeJa: '細かい決まりの話', starterJa: '職場や学校の細かい決まりはありますか？',
      starterZh: '职场或学校有很细的规定吗？', targetUse: '〜に至るまで',
    },
    matchKeys: ['に至るまで'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-062', pattern: '〜たるもの', reading: 'たるもの', unit: 5,
    meaningJa: '〜という立場の人は（当然〜すべきだ）',
    explanationZh: '身为…就应该…。用于强调身份带来的责任',
    formation: '名詞＋たるもの（は）',
    usageScene: '训话、社论中强调应有的姿态',
    nuance: '後ろは「〜べきだ」など当然の主張が来る',
    register: 'written',
    examplesJa: ['責任者たるもの、最後まで見届けるべきです。', '教える者たるもの、まず自分が学ぶ必要があります。'],
    examplesZh: ['身为负责人，就应该看到最后。', '身为教人的人，首先自己必须学习。'],
    furigana: 'せきにんしゃ たる もの、さいごまで みとどける べきです。',
    commonMistakesZh: '前面是表示身份、职位的名词。不接普通事物',
    learnerFocus: '固定搭配「〜たるもの、〜べきだ」。考试常考后半的「べきだ」',
    similarPatterns: ['〜ともあろう者が', '〜として'],
    contrast: '「たるもの」＝立場としての当然の姿；「として」＝ただ立場を示すだけ',
    recognition: {
      promptZh: '「責任者たるもの」后面最可能接什么？',
      options: ['最後まで責任を持つべきだ', '休みたいと思った', '知らなかった', '来なかった'],
      answerIndex: 0,
      distractorReason: '「たるもの」の後ろは当然すべきことが来る',
      distractorReasonZh: '「たるもの」后面接理应做的事',
      explanationZh: '「〜たるもの」＝身为…就应该…',
    },
    production: {
      promptJa: '立場としての心構えを「〜たるもの」で言ってください。',
      promptZh: '用「〜たるもの」说一说某个身份应有的态度。',
      expected: ['たるもの'], acceptable: [],
    },
    practice: {
      themeJa: '立場と責任', starterJa: 'その立場の人に必要なことは何だと思いますか？',
      starterZh: '你觉得那个身份的人需要具备什么？', targetUse: '〜たるもの',
    },
    matchKeys: ['たるもの'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-063', pattern: '〜ともなると／〜ともなれば', reading: 'ともなると', unit: 5,
    meaningJa: '〜という段階になると、当然',
    explanationZh: '一到…的阶段，就（自然会…）',
    formation: '名詞／動詞辞書形＋ともなると／ともなれば',
    usageScene: '说明到了某个阶段自然出现的变化',
    nuance: '後ろは当然の結果。特別な立場や時期に使う',
    register: 'written',
    examplesJa: ['連休ともなると、道路が混みます。', '責任者ともなれば、判断を求められます。'],
    examplesZh: ['一到连休，道路就会堵。', '一旦成为负责人，就会被要求做判断。'],
    furigana: 'れんきゅう ともなると、どうろが こみます。',
    commonMistakesZh: '不用于日常的小事。要是「到了某个特别的阶段」',
    learnerFocus: '「ともなると」的后面是「当然会这样」。不是偶然的事',
    similarPatterns: ['〜となると', '〜になると'],
    contrast: '「ともなると」＝特別な段階＋当然の結果；「になると」＝ただの時期の変化',
    recognition: {
      promptZh: '「連休ともなると」后面最可能接什么？',
      options: ['道路が混む', '雨が降った', '本を読んだ', '休みたい'],
      answerIndex: 0,
      distractorReason: '「ともなると」の後ろは当然そうなる結果が来る',
      distractorReasonZh: '「ともなると」后面接理所当然的结果',
      explanationZh: '「〜ともなると」＝一到…的阶段就（自然会…）',
    },
    production: {
      promptJa: '特別な時期に起きることを「〜ともなると」で言ってください。',
      promptZh: '用「〜ともなると」说一件特定时期必然发生的事。',
      expected: ['ともなると'], acceptable: ['ともなれば'],
    },
    practice: {
      themeJa: '時期による変化', starterJa: '連休や年末はどんな様子になりますか？',
      starterZh: '连休或年末会是什么样子？', targetUse: '〜ともなると',
    },
    matchKeys: ['ともなると', 'ともなれば'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-064', pattern: '〜と相まって', reading: 'とあいまって', unit: 5,
    meaningJa: '〜と重なって、いっそう',
    explanationZh: '与…相互作用，更加…',
    formation: '名詞＋と相まって',
    usageScene: '说明两个因素叠加产生更大的效果',
    nuance: '二つの要素が合わさって効果が強まる',
    register: 'written',
    examplesJa: ['天気の良さと相まって、人出が増えました。', '値下げと相まって、売り上げが伸びました。'],
    examplesZh: ['加上天气好，人流增加了。', '与降价相互作用，销售额增长了。'],
    furigana: 'てんきの よさと あいまって、ひとでが ふえました。',
    commonMistakesZh: '两个因素都是同方向的。不用于相反的因素',
    learnerFocus: '理解为「A＋B＝效果更大」。是报道里的常见搭配',
    similarPatterns: ['〜に加えて', '〜も手伝って'],
    contrast: '「と相まって」＝互いに作用して強まる；「に加えて」＝ただ足すだけ',
    recognition: {
      promptZh: '「天気と相まって」是什么意思？',
      options: ['与天气相互作用（更加…）', '与天气相反', '因为天气不好', '不管天气'],
      answerIndex: 0,
      distractorReason: '「と相まって」は二つの要素が合わさって効果が強まる意味',
      distractorReasonZh: '「と相まって」表示两个因素叠加使效果增强',
      explanationZh: '「〜と相まって」＝与…相互作用，更加…',
    },
    production: {
      promptJa: '二つの理由が重なった話を「〜と相まって」で言ってください。',
      promptZh: '用「〜と相まって」说一件两个原因叠加的事。',
      expected: ['と相まって'], acceptable: ['とあいまって'],
    },
    practice: {
      themeJa: '重なった理由', starterJa: '二つの理由が重なってうまくいったことは？',
      starterZh: '有过两个原因叠加而成功的事吗？', targetUse: '〜と相まって',
    },
    matchKeys: ['相まって'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-065', pattern: '〜にとどまらず', reading: 'にとどまらず', unit: 5,
    meaningJa: '〜だけでなく、もっと広く',
    explanationZh: '不仅限于…，还扩展到…',
    formation: '名詞／動詞辞書形＋にとどまらず',
    usageScene: '说明影响范围超出了原来的领域',
    nuance: '後ろにはより広い範囲が来る',
    register: 'written',
    examplesJa: ['影響は地域にとどまらず、全国に広がりました。', '活動は学校にとどまらず、地域にも及んでいます。'],
    examplesZh: ['影响不仅限于本地区，还扩散到了全国。', '活动不仅限于学校，也扩及社区。'],
    furigana: 'えいきょうは ちいきに とどまらず、ぜんこくに ひろがりました。',
    commonMistakesZh: '后面必须是比前面更广的范围。反过来不成立',
    learnerFocus: '「AにとどまらずB」＝B比A更广。考试常考前后的大小关系',
    similarPatterns: ['〜だけでなく', '〜のみならず'],
    contrast: '「にとどまらず」＝範囲が外へ広がる；「だけでなく」＝ただ二つを並べる',
    recognition: {
      promptZh: '「地域にとどまらず」后面最可能接什么？',
      options: ['全国に広がった', '地域で終わった', '地域だけだ', '地域が減った'],
      answerIndex: 0,
      distractorReason: '「にとどまらず」の後ろはより広い範囲が来る',
      distractorReasonZh: '「にとどまらず」后面接更广的范围',
      explanationZh: '「〜にとどまらず」＝不仅限于…，还…',
    },
    production: {
      promptJa: '広がった影響を「〜にとどまらず」で言ってください。',
      promptZh: '用「〜にとどまらず」说一个扩散开的影响。',
      expected: ['にとどまらず'], acceptable: [],
    },
    practice: {
      themeJa: '広がった影響', starterJa: '小さな取り組みが広がった例を知っていますか？',
      starterZh: '你知道小举措扩散开来的例子吗？', targetUse: '〜にとどまらず',
    },
    matchKeys: ['にとどまらず'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-066', pattern: '〜はもとより', reading: 'はもとより', unit: 5,
    meaningJa: '〜はもちろん、さらに',
    explanationZh: '…自不必说，还…',
    formation: '名詞＋はもとより',
    usageScene: '说明范围包含了理所当然的部分和额外的部分',
    nuance: '前は当然含まれる例、後ろは意外な例',
    register: 'written',
    examplesJa: ['大人はもとより、子どもにも人気があります。', '平日はもとより、休日も開いています。'],
    examplesZh: ['大人自不必说，孩子也很喜欢。', '平日自不必说，假日也开门。'],
    furigana: 'おとなは もとより、こどもにも にんきが あります。',
    commonMistakesZh: '前面放理所当然的一方，后面放让人意外的一方',
    learnerFocus: '与「はもちろん」意思相同，「はもとより」更书面',
    similarPatterns: ['〜はもちろん', '〜のみならず'],
    contrast: '「はもとより」＝書き言葉；「はもちろん」＝話し言葉でも使える',
    recognition: {
      promptZh: '「大人はもとより」是什么意思？',
      options: ['大人自不必说（还有…）', '只有大人', '大人以前', '大人不行'],
      answerIndex: 0,
      distractorReason: '「はもとより」は「はもちろん」と同じ意味',
      distractorReasonZh: '「はもとより」与「はもちろん」同义',
      explanationZh: '「〜はもとより」＝…自不必说，还…',
    },
    production: {
      promptJa: '両方に当てはまることを「〜はもとより」で言ってください。',
      promptZh: '用「〜はもとより」说一件两方面都适用的事。',
      expected: ['はもとより'], acceptable: [],
    },
    practice: {
      themeJa: '幅広く人気があるもの', starterJa: '年齢に関係なく人気のあるものは何ですか？',
      starterZh: '有什么东西是不分年龄都受欢迎的？', targetUse: '〜はもとより',
    },
    matchKeys: ['はもとより'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-067', pattern: '〜はおろか', reading: 'はおろか', unit: 5,
    meaningJa: '〜どころか、もっと基本的なことさえ',
    explanationZh: '别说…了，连…都…。后面接否定',
    formation: '名詞＋はおろか',
    usageScene: '强调连最基本的事都做不到',
    nuance: '後ろは打ち消しか、否定的な内容',
    register: 'written',
    examplesJa: ['漢字はおろか、ひらがなも読めませんでした。', '外食はおろか、自炊する時間もありません。'],
    examplesZh: ['别说汉字了，连平假名都读不了。', '别说外出吃饭，连自己做饭的时间都没有。'],
    furigana: 'かんじは おろか、ひらがなも よめません でした。',
    commonMistakesZh: '前面放程度高的，后面放程度低的。顺序反了意思就不通',
    learnerFocus: '结构是「（难的）はおろか、（简单的）も〜ない」。考试常考顺序',
    similarPatterns: ['〜どころか', '〜すら'],
    contrast: '「はおろか」＝必ず否定と組む；「どころか」＝肯定の意外な展開にも使える',
    recognition: {
      promptZh: '哪个句子用「はおろか」自然？',
      options: ['漢字はおろかひらがなも書けない', 'ひらがなはおろか漢字も上手だ', '漢字はおろかよく書ける', 'ひらがなはおろか読める'],
      answerIndex: 0,
      distractorReason: '「はおろか」は前が難しい方、後ろが簡単な方で、必ず否定が来る',
      distractorReasonZh: '「はおろか」前面放较难的，后面放较容易的，且必须接否定',
      explanationZh: '「〜はおろか」＝别说…了，连…都不…',
    },
    production: {
      promptJa: '基本的なこともできない状況を「〜はおろか」で言ってください。',
      promptZh: '用「〜はおろか」说一个连基本的事都做不到的状况。',
      expected: ['はおろか'], acceptable: [],
    },
    practice: {
      themeJa: '始めたころの話', starterJa: '日本語を始めたころ、何ができませんでしたか？',
      starterZh: '刚开始学日语时，什么做不到？', targetUse: '〜はおろか',
    },
    matchKeys: ['はおろか'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-068', pattern: '〜のみならず', reading: 'のみならず', unit: 5,
    meaningJa: '〜だけでなく',
    explanationZh: '不仅…而且…。是「だけでなく」的书面语',
    formation: '名詞／動詞・形容詞の普通形＋のみならず',
    usageScene: '论说文中并列两个范围',
    nuance: '後ろには「も」が来ることが多い',
    register: 'written',
    examplesJa: ['本人のみならず、家族も参加できます。', '費用が高いのみならず、時間もかかります。'],
    examplesZh: ['不仅本人，家属也可以参加。', '不仅费用高，还很花时间。'],
    furigana: 'ほんにんの みならず、かぞくも さんか できます。',
    commonMistakesZh: '接名词时不加「の」以外的助词。「本人がのみならず」不成立',
    learnerFocus: '「のみならず」＝「だけでなく」。阅读中出现频率很高',
    similarPatterns: ['〜だけでなく', '〜にとどまらず'],
    contrast: '「のみならず」＝並列の書き言葉；「にとどまらず」＝範囲が外へ広がる',
    recognition: {
      promptZh: '「のみならず」最接近下面哪一个？',
      options: ['だけでなく', 'だけで', 'ばかりに', 'のように'],
      answerIndex: 0,
      distractorReason: '「のみならず」は「だけでなく」の書き言葉',
      distractorReasonZh: '「のみならず」是「だけでなく」的书面语',
      explanationZh: '「〜のみならず」＝不仅…而且…',
    },
    production: {
      promptJa: '二つのことを並べて「〜のみならず」で言ってください。',
      promptZh: '用「〜のみならず」并列两件事。',
      expected: ['のみならず'], acceptable: [],
    },
    practice: {
      themeJa: '二つの面を挙げる', starterJa: '良い点と困る点を両方挙げられますか？',
      starterZh: '能同时举出优点和难处吗？', targetUse: '〜のみならず',
    },
    matchKeys: ['のみならず'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-069', pattern: '〜をもって', reading: 'をもって', unit: 5,
    meaningJa: '〜で（区切り・手段）',
    explanationZh: '以…（为期限／为手段）。是正式的公告用语',
    formation: '名詞＋をもって',
    usageScene: '公告中说明截止时间或方式',
    nuance: '時を示すと「区切り」、道具を示すと「手段」になる',
    register: 'written',
    examplesJa: ['本日をもって受付を終了します。', '結果は書面をもってお知らせします。'],
    examplesZh: ['自今日起截止受理。', '结果将以书面形式通知。'],
    furigana: 'ほんじつを もって うけつけを しゅうりょう します。',
    commonMistakesZh: '日常会话不用。相当于正式文书里的「で」',
    learnerFocus: '两种意思：时间的「截止」和手段的「以…方式」。看前面的名词判断',
    similarPatterns: ['〜で', '〜により'],
    contrast: '「をもって」＝公的な文書の言い方；「で」＝日常の標準形',
    recognition: {
      promptZh: '「本日をもって」是什么意思？',
      options: ['以今天为限（截止）', '今天以外', '今天开始很久', '不是今天'],
      answerIndex: 0,
      distractorReason: '時を示す名詞に付くと区切りの意味になる',
      distractorReasonZh: '接表示时间的名词时表示截止、期限',
      explanationZh: '「〜をもって」＝以…为期限',
    },
    production: {
      promptJa: '終了のお知らせを「〜をもって」で書いてください。',
      promptZh: '用「〜をもって」写一句结束的通知。',
      expected: ['をもって'], acceptable: [],
    },
    practice: {
      themeJa: 'お知らせの書き方', starterJa: '受付の終了を伝えるとき、どう書きますか？',
      starterZh: '通知受理截止时该怎么写？', targetUse: '〜をもって',
    },
    matchKeys: ['をもって'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-070', pattern: '〜にして', reading: 'にして', unit: 5,
    meaningJa: '〜だからこそ／〜になって初めて',
    explanationZh: '正因为是…才…；到了…才…',
    formation: '名詞＋にして',
    usageScene: '强调只有那个人、那个阶段才做得到',
    nuance: '「〜にしてはじめて」「〜にしてこそ」の形が多い',
    register: 'written',
    examplesJa: ['六十歳にして、新しい仕事を始めました。', '経験者にして初めて分かることがあります。'],
    examplesZh: ['到了六十岁，开始了新的工作。', '有些事只有有经验的人才明白。'],
    furigana: 'ろくじゅっさい に して、あたらしい しごとを はじめました。',
    commonMistakesZh: '与表示状态的「〜にして」（＝一边）不同，注意语境',
    learnerFocus: '数字＋にして＝「到了…岁才」，人＋にして＝「只有…才」',
    similarPatterns: ['〜になって', '〜だからこそ'],
    contrast: '「にして」＝硬い強調；「になって」＝ただの時点',
    recognition: {
      promptZh: '「六十歳にして」是什么意思？',
      options: ['到了六十岁（才）', '六十岁之前', '不到六十岁', '六十岁左右'],
      answerIndex: 0,
      distractorReason: '数を示す語に付くと「その段階になって」の意味になる',
      distractorReasonZh: '接表示数量的词时表示「到了那个阶段」',
      explanationZh: '「〜にして」＝到了…才…',
    },
    production: {
      promptJa: 'ある年齢で始めたことを「〜にして」で言ってください。',
      promptZh: '用「〜にして」说一件在某个年龄开始的事。',
      expected: ['にして'], acceptable: [],
    },
    practice: {
      themeJa: '始めるのに遅すぎることはない', starterJa: '年をとってから始めたことはありますか？',
      starterZh: '有过上了年纪才开始的事吗？', targetUse: '〜にして',
    },
    matchKeys: ['にして'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-071', pattern: '〜こそあれ', reading: 'こそあれ', unit: 5,
    meaningJa: '〜はあるけれども',
    explanationZh: '虽然有…，但…。书面的让步说法',
    formation: '名詞／形容詞語幹＋こそあれ',
    usageScene: '论说文中承认程度差异后作出结论',
    nuance: '後ろは前を打ち消すような結論',
    register: 'written',
    examplesJa: ['差こそあれ、誰にでも悩みはあります。', '遅れこそあれ、必ず届きます。'],
    examplesZh: ['虽有差别，但谁都有烦恼。', '虽有延迟，但一定会送到。'],
    furigana: 'さ こそ あれ、だれにでも なやみは あります。',
    commonMistakesZh: '不是「正因为有」。这里是让步',
    learnerFocus: '「AこそあれB」＝虽然有A，但B。A常是「差・違い・遅れ」',
    similarPatterns: ['〜はあるが', '〜こそすれ'],
    contrast: '「こそあれ」＝存在を認めたうえで譲歩；「こそすれ」＝行為を認めたうえで否定',
    recognition: {
      promptZh: '「差こそあれ」是什么意思？',
      options: ['虽有差别，但…', '正因为有差别', '没有差别', '差别很大'],
      answerIndex: 0,
      distractorReason: '「こそあれ」は譲歩の言い方',
      distractorReasonZh: '「こそあれ」是让步的说法',
      explanationZh: '「〜こそあれ」＝虽然有…，但…',
    },
    production: {
      promptJa: '差はあっても共通することを「〜こそあれ」で言ってください。',
      promptZh: '用「〜こそあれ」说一件虽有差别但共通的事。',
      expected: ['こそあれ'], acceptable: [],
    },
    practice: {
      themeJa: 'みんなに共通すること', starterJa: '人によって違っても共通していることは？',
      starterZh: '虽因人而异但共通的是什么？', targetUse: '〜こそあれ',
    },
    matchKeys: ['こそあれ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-072', pattern: '〜こそすれ', reading: 'こそすれ', unit: 5,
    meaningJa: '〜することはあっても、〜はない',
    explanationZh: '只会…，绝不会…。后面必接否定',
    formation: '動詞ます形／名詞＋こそすれ',
    usageScene: '强调方向只有一个',
    nuance: '後ろは必ず打ち消し',
    register: 'written',
    examplesJa: ['増えこそすれ、減ることはないでしょう。', '感謝こそすれ、恨む気持ちはありません。'],
    examplesZh: ['只会增加，不会减少吧。', '只有感谢，没有怨恨。'],
    furigana: 'ふえ こそ すれ、へる ことは ない でしょう。',
    commonMistakesZh: '后面必须是否定。「増えこそすれ減った」不成立',
    learnerFocus: '「AこそすれBない」＝只会A不会B。B是A的反义',
    similarPatterns: ['〜こそあれ', '〜ことはあっても'],
    contrast: '「こそすれ」＝行為の方向を一つに限定；「こそあれ」＝存在を認めた譲歩',
    recognition: {
      promptZh: '「増えこそすれ」后面最可能接什么？',
      options: ['減ることはない', '減るだろう', '減った', '減りたい'],
      answerIndex: 0,
      distractorReason: '「こそすれ」の後ろは必ず打ち消しが来る',
      distractorReasonZh: '「こそすれ」后面必须接否定',
      explanationZh: '「〜こそすれ」＝只会…，绝不会…',
    },
    production: {
      promptJa: '一方向にしか変わらないことを「〜こそすれ」で言ってください。',
      promptZh: '用「〜こそすれ」说一件只朝一个方向变化的事。',
      expected: ['こそすれ'], acceptable: [],
    },
    practice: {
      themeJa: '増える一方のもの', starterJa: 'これからも増えると思うものは何ですか？',
      starterZh: '你觉得今后还会增加的是什么？', targetUse: '〜こそすれ',
    },
    matchKeys: ['こそすれ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-073', pattern: '〜であれ', reading: 'であれ', unit: 5,
    meaningJa: '〜でも（どんな場合でも）',
    explanationZh: '无论…都。与疑问词搭配',
    formation: '疑問詞／名詞＋であれ',
    usageScene: '强调条件不影响结论',
    nuance: '「何であれ」「どこであれ」の形が多い',
    register: 'written',
    examplesJa: ['理由が何であれ、約束は守ります。', 'どこであれ、行けば学びがあります。'],
    examplesZh: ['无论理由是什么，都会遵守约定。', '无论去哪里，去了就有收获。'],
    furigana: 'りゆうが なんで あれ、やくそくは まもります。',
    commonMistakesZh: '与「〜であれ〜であれ」（成对）不同，这里是单独使用',
    learnerFocus: '疑问词＋であれ＝无论…。是阅读中的高频形式',
    similarPatterns: ['〜であろうと', '〜にしても'],
    contrast: '「であれ」＝単独で「どんな〜でも」；「であれ〜であれ」＝二つを並べる',
    recognition: {
      promptZh: '「何であれ」是什么意思？',
      options: ['无论是什么', '是什么呢', '因为是什么', '什么都不是'],
      answerIndex: 0,
      distractorReason: '疑問詞＋であれ は「どんな〜でも」の意味',
      distractorReasonZh: '疑问词＋であれ 意为「无论…」',
      explanationZh: '「〜であれ」＝无论…都',
    },
    production: {
      promptJa: '条件に関係なく守ることを「何であれ」で言ってください。',
      promptZh: '用「何であれ」说一件不论条件都会遵守的事。',
      expected: ['であれ'], acceptable: ['何であれ'],
    },
    practice: {
      themeJa: '必ず守ること', starterJa: 'どんな時でも守っていることはありますか？',
      starterZh: '有什么是你无论何时都会遵守的？', targetUse: '〜であれ',
    },
    matchKeys: ['であれ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-074', pattern: '〜に限ったことではない', reading: 'にかぎったことではない', unit: 5,
    meaningJa: '〜だけの話ではない',
    explanationZh: '不只是…的问题。指出问题更普遍',
    formation: '名詞＋に限ったことではない',
    usageScene: '论说文中说明现象不限于某个范围',
    nuance: '「これは特別ではない」と一般化する言い方',
    register: 'written',
    examplesJa: ['人手不足はこの業界に限ったことではありません。', 'これは若い人に限ったことではありません。'],
    examplesZh: ['人手不足并不只是这个行业的问题。', '这并不只是年轻人的问题。'],
    furigana: 'ひとで ぶそくは この ぎょうかいに かぎった ことでは ありません。',
    commonMistakesZh: '前面接范围的名词。后面是「不只如此」的展开',
    learnerFocus: '＝「〜だけではない」。论说文里常用来把话题扩大',
    similarPatterns: ['〜だけではない', '〜にとどまらず'],
    contrast: '「に限ったことではない」＝一般化する；「にとどまらず」＝範囲が外へ広がる',
    recognition: {
      promptZh: '「この会社に限ったことではない」是什么意思？',
      options: ['不只是这家公司的问题', '只有这家公司', '这家公司没有', '这家公司最好'],
      answerIndex: 0,
      distractorReason: '「に限ったことではない」は範囲を広げて一般化する',
      distractorReasonZh: '「に限ったことではない」把范围扩大、加以一般化',
      explanationZh: '「〜に限ったことではない」＝不只是…的问题',
    },
    production: {
      promptJa: '広く見られる問題を「〜に限ったことではない」で言ってください。',
      promptZh: '用「〜に限ったことではない」说一个普遍存在的问题。',
      expected: ['に限ったこと'], acceptable: ['に限ったことではない'],
    },
    practice: {
      themeJa: '広く見られる問題', starterJa: 'あなたの周りで多くの人が困っていることは？',
      starterZh: '你周围很多人都在困扰的问题是什么？', targetUse: '〜に限ったことではない',
    },
    matchKeys: ['に限ったこと'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-075', pattern: '〜にひきかえ', reading: 'にひきかえ', unit: 5,
    meaningJa: '〜とは反対に',
    explanationZh: '与…相反；相比之下…',
    formation: '名詞＋（なの）にひきかえ／動詞・形容詞の普通形＋の＋にひきかえ',
    usageScene: '把两者放在一起作对比',
    nuance: '話し手の評価が入る。「に対して」より主観的',
    register: 'written',
    examplesJa: ['去年の忙しさにひきかえ、今年は落ち着いています。', '兄にひきかえ、弟はとても静かです。'],
    examplesZh: ['与去年的忙碌相反，今年很平静。', '与哥哥相反，弟弟非常安静。'],
    furigana: 'きょねんの いそがしさに ひきかえ、ことしは おちついて います。',
    commonMistakesZh: '两边要形成鲜明对比。相似的内容不能用',
    learnerFocus: '「にひきかえ」带说话人的评价，「に対して」是中立的对比',
    similarPatterns: ['〜に対して', '〜とは違って'],
    contrast: '「にひきかえ」＝主観的な対比；「に対して」＝客観的な対比',
    recognition: {
      promptZh: '「兄にひきかえ」是什么意思？',
      options: ['与哥哥相反', '和哥哥一样', '为了哥哥', '哥哥之后'],
      answerIndex: 0,
      distractorReason: '「にひきかえ」は反対のものを並べて対比する',
      distractorReasonZh: '「にひきかえ」把相反的事物并列作对比',
      explanationZh: '「〜にひきかえ」＝与…相反',
    },
    production: {
      promptJa: '二つを対比して「〜にひきかえ」で言ってください。',
      promptZh: '用「〜にひきかえ」对比两者。',
      expected: ['にひきかえ'], acceptable: [],
    },
    practice: {
      themeJa: '去年と今年の違い', starterJa: '去年と今年で大きく違うことはありますか？',
      starterZh: '去年和今年有什么大不同？', targetUse: '〜にひきかえ',
    },
    matchKeys: ['にひきかえ'], vocabularyLinks: [],
  }),
];
