// N1文法 Unit 4（15項目 / 逆接・譲歩）。
// 例文・訳・解説はすべて自社で書き起こす。
import { n1g, type N1GrammarDraft } from './n1GrammarDrafts';

export const N1_GRAMMAR_DRAFTS_UNIT4: N1GrammarDraft[] = [
  n1g({
    grammarId: 'n1g-046', pattern: '〜ながらも', reading: 'ながらも', unit: 4,
    meaningJa: '〜けれども',
    explanationZh: '虽然…但是…。是书面的逆接说法',
    formation: '動詞ます形／形容詞／名詞＋ながらも',
    usageScene: '论说文中承认一面、指出另一面',
    nuance: '前後が食い違う内容になる。同時進行の「ながら」とは別',
    register: 'written',
    examplesJa: ['狭いながらも、住みやすい部屋です。', '不安を感じながらも、前に進むことにしました。'],
    examplesZh: ['虽然狭小，却是住着舒服的房间。', '虽然感到不安，还是决定往前走。'],
    furigana: 'せまい ながらも、すみやすい へやです。',
    commonMistakesZh: '与同时进行的「ながら」区分：「歩きながら食べる」不是逆接',
    learnerFocus: '看到「ながらも」的「も」就知道是逆接，不是同时',
    similarPatterns: ['〜つつも', '〜けれども'],
    contrast: '「ながらも」＝逆接（〜のに）；「ながら」＝同時進行（〜しつつ）',
    recognition: {
      promptZh: '哪个句子用「ながらも」自然？',
      options: ['小さいながらも役に立つ道具だ', '歩きながらも食べた', '寝ながらも眠った', '書きながらも書いた'],
      answerIndex: 0,
      distractorReason: '「ながらも」は前後が食い違う逆接。同時動作には使わない',
      distractorReasonZh: '「ながらも」是前后相反的逆接，不用于同时动作',
      explanationZh: '「〜ながらも」＝虽然…但是…',
    },
    production: {
      promptJa: '欠点はあるが良いものを「〜ながらも」で言ってください。',
      promptZh: '用「〜ながらも」说一件有缺点但很好的东西。',
      expected: ['ながらも'], acceptable: [],
    },
    practice: {
      themeJa: '欠点はあるが気に入っているもの', starterJa: '不便でも気に入っているものはありますか？',
      starterZh: '有什么东西虽然不方便但你很喜欢？', targetUse: '〜ながらも',
    },
    matchKeys: ['ながらも'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-047', pattern: '〜つつも', reading: 'つつも', unit: 4,
    meaningJa: '〜と思っているのに（実際は違う）',
    explanationZh: '虽然…却…。多用于说自己言行不一',
    formation: '動詞ます形＋つつも',
    usageScene: '反省自己知道该做却没做',
    nuance: '「分かっているのにできない」という気持ちに合う',
    register: 'written',
    examplesJa: ['よくないと知りつつも、つい夜更かしします。', '行こうと思いつつも、行けないままです。'],
    examplesZh: ['明知不好，还是忍不住熬夜。', '虽然想去，却一直没能去成。'],
    furigana: 'よくないと しり つつも、つい よふかし します。',
    commonMistakesZh: '前面接动词ます形。不接名词',
    learnerFocus: '「知りつつも」「思いつつも」是最常见的形式，先记住这两个',
    similarPatterns: ['〜ながらも', '〜のに'],
    contrast: '「つつも」＝気持ちと行動のずれ；「ながらも」＝性質の食い違い（狭いが便利）',
    recognition: {
      promptZh: '「知りつつも」是什么意思？',
      options: ['虽然知道却…', '因为知道', '想知道', '不知道'],
      answerIndex: 0,
      distractorReason: '「つつも」は逆接。理由や願望ではない',
      distractorReasonZh: '「つつも」是逆接，不表示理由或愿望',
      explanationZh: '「〜つつも」＝虽然…却…',
    },
    production: {
      promptJa: '分かっているのにやめられないことを「〜つつも」で言ってください。',
      promptZh: '用「〜つつも」说一件明知却戒不掉的事。',
      expected: ['つつも'], acceptable: [],
    },
    practice: {
      themeJa: 'やめたいのに続けていること', starterJa: 'よくないと分かっていても続けていることは？',
      starterZh: '有什么明知不好却还在做的事？', targetUse: '〜つつも',
    },
    matchKeys: ['つつも'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-048', pattern: '〜といえども', reading: 'といえども', unit: 4,
    meaningJa: '〜であっても',
    explanationZh: '即使是…也…。用于强调「连这样的情况也不例外」',
    formation: '名詞／動詞・形容詞の普通形＋といえども',
    usageScene: '论说文中说明规则没有例外',
    nuance: '前に来るのは「例外になりそうなもの」',
    register: 'written',
    examplesJa: ['専門家といえども、間違えることはあります。', '子どもといえども、約束は守るべきです。'],
    examplesZh: ['即使是专家，也会出错。', '即使是孩子，也应该遵守约定。'],
    furigana: 'せんもんか と いえども、まちがえる ことは あります。',
    commonMistakesZh: '不是「据说」。「といえども」是逆接，不是引用',
    learnerFocus: '看到「といえども」就换成「でも・であっても」来理解',
    similarPatterns: ['〜であっても', '〜でも'],
    contrast: '「といえども」＝硬い文語の譲歩；「でも」＝話し言葉の標準形',
    recognition: {
      promptZh: '「専門家といえども」是什么意思？',
      options: ['即使是专家也…', '据专家说', '因为是专家', '专家想说'],
      answerIndex: 0,
      distractorReason: '「といえども」は譲歩。引用ではない',
      distractorReasonZh: '「といえども」表示让步，不是引用',
      explanationZh: '「〜といえども」＝即使是…也…',
    },
    production: {
      promptJa: '例外がないことを「〜といえども」で言ってください。',
      promptZh: '用「〜といえども」说一件没有例外的事。',
      expected: ['といえども'], acceptable: [],
    },
    practice: {
      themeJa: '例外を認めない話', starterJa: '誰にとっても例外がない決まりはありますか？',
      starterZh: '有什么规定是对谁都没有例外的？', targetUse: '〜といえども',
    },
    matchKeys: ['といえども'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-049', pattern: '〜とはいえ', reading: 'とはいえ', unit: 4,
    meaningJa: '〜とはいうものの、実際は',
    explanationZh: '虽说…但…。承认前提，然后否定预期',
    formation: '名詞／動詞・形容詞の普通形＋とはいえ',
    usageScene: '在文章开头承认前提，再提出保留',
    nuance: '前の内容から予想されることが実際は起きていない',
    register: 'written',
    examplesJa: ['春とはいえ、朝晩はまだ冷えます。', '慣れたとはいえ、緊張はします。'],
    examplesZh: ['虽说是春天，早晚还是很冷。', '虽说习惯了，还是会紧张。'],
    furigana: 'はる とはいえ、あさばんは まだ ひえます。',
    commonMistakesZh: '与「といえども」相近，但「とはいえ」更常出现在句首',
    learnerFocus: '「とはいえ、」放在句首时相当于「不过」。这是阅读的高频接续',
    similarPatterns: ['〜といっても', '〜ものの'],
    contrast: '「とはいえ」＝前提を認めつつ修正；「といえども」＝例外を認めない強い譲歩',
    recognition: {
      promptZh: '「春とはいえ」是什么意思？',
      options: ['虽说是春天（但…）', '因为是春天', '春天来了', '不是春天'],
      answerIndex: 0,
      distractorReason: '「とはいえ」は前提を認めたうえで逆のことを言う',
      distractorReasonZh: '「とはいえ」在承认前提后说出相反的情况',
      explanationZh: '「〜とはいえ」＝虽说…但…',
    },
    production: {
      promptJa: '予想と違ったことを「〜とはいえ」で言ってください。',
      promptZh: '用「〜とはいえ」说一件与预期不同的事。',
      expected: ['とはいえ'], acceptable: [],
    },
    practice: {
      themeJa: '季節と実感のずれ', starterJa: '季節と実際の気温が合わないと感じますか？',
      starterZh: '你觉得季节和实际气温对不上吗？', targetUse: '〜とはいえ',
    },
    matchKeys: ['とはいえ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-050', pattern: '〜ものを', reading: 'ものを', unit: 4,
    meaningJa: '〜すればよかったのに（残念だ）',
    explanationZh: '本来…就好了（可惜没有）。带遗憾和责备',
    formation: '動詞・形容詞の普通形＋ものを',
    usageScene: '为对方没做某事而感到惋惜',
    nuance: '後ろは省略されることが多い。「〜ものを。」で終わる',
    register: 'written',
    examplesJa: ['言ってくれれば手伝ったものを。', '早く言えばよかったものを、黙っていました。'],
    examplesZh: ['要是说一声我就帮忙了。', '早说就好了，却一直没吭声。'],
    furigana: 'いって くれれば てつだった ものを。',
    commonMistakesZh: '不是表示原因的「もので」。「ものを」带遗憾语气',
    learnerFocus: '常与「〜ば」搭配：「〜ば〜のに／〜ものを」。理解为「本来…就好了」',
    similarPatterns: ['〜のに', '〜ばよかった'],
    contrast: '「ものを」＝残念・非難の気持ちが強い；「のに」＝ただの逆接でも使える',
    recognition: {
      promptZh: '「言ってくれればよかったものを」是什么意思？',
      options: ['本来说一声就好了（可惜没说）', '说了就好了（已经说了）', '不用说也可以', '说了反而不好'],
      answerIndex: 0,
      distractorReason: '「ものを」は実際にはそうしなかったことへの残念な気持ちを表す',
      distractorReasonZh: '「ものを」表示对实际没那样做的惋惜',
      explanationZh: '「〜ものを」＝本来…就好了（可惜没有）',
    },
    production: {
      promptJa: '相手が言ってくれなくて残念だったことを「〜ものを」で言ってください。',
      promptZh: '用「〜ものを」说一件对方没说而你感到可惜的事。',
      expected: ['ものを'], acceptable: [],
    },
    practice: {
      themeJa: '言ってくれればよかった話', starterJa: '早く教えてほしかったことはありますか？',
      starterZh: '有什么事你希望别人早点告诉你？', targetUse: '〜ものを',
    },
    matchKeys: ['ものを'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-051', pattern: '〜ところを', reading: 'ところを', unit: 4,
    meaningJa: '〜という状況なのに（すみません／ありがとう）',
    explanationZh: '在…的时候（打扰了／麻烦您了）。用于寒暄',
    formation: '名詞＋の／動詞・形容詞の普通形＋ところを',
    usageScene: '会议、书信开头的寒暄',
    nuance: '後ろにお礼やおわびが来る決まった言い方',
    register: 'written',
    examplesJa: ['お忙しいところをありがとうございます。', 'お休みのところをすみません。'],
    examplesZh: ['百忙之中感谢您。', '休息时打扰您，不好意思。'],
    furigana: 'お いそがしい ところを ありがとう ございます。',
    commonMistakesZh: '不是表示地点的「ところ」。这里是「在…的场合」',
    learnerFocus: '「お忙しいところを」「お休みのところを」两句背下来就能直接用',
    similarPatterns: ['〜のに', '〜中'],
    contrast: '「ところを」＝あいさつの決まり文句；「のに」＝一般の逆接',
    recognition: {
      promptZh: '「お忙しいところを」后面最可能接什么？',
      options: ['ありがとうございます', '行きましょう', '知りません', '買いました'],
      answerIndex: 0,
      distractorReason: '「ところを」の後ろはお礼やおわびが来る',
      distractorReasonZh: '「ところを」后面接感谢或道歉',
      explanationZh: '「〜ところを」＝在…的时候（感谢／抱歉）',
    },
    production: {
      promptJa: 'あいさつを「お忙しいところを」で始めてください。',
      promptZh: '用「お忙しいところを」开头说一句寒暄。',
      expected: ['ところを'], acceptable: [],
    },
    practice: {
      themeJa: 'あいさつの言い方', starterJa: '忙しい人にお礼を言うときは何と言いますか？',
      starterZh: '向忙碌的人道谢时怎么说？', targetUse: '〜ところを',
    },
    matchKeys: ['ところを'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-052', pattern: '〜ならいざしらず', reading: 'ならいざしらず', unit: 4,
    meaningJa: '〜なら仕方ないが、〜は違う',
    explanationZh: '如果是…还情有可原，但…',
    formation: '名詞／動詞・形容詞の普通形＋ならいざしらず',
    usageScene: '指出对方的情况不属于可以原谅的范围',
    nuance: '前は許せる例、後ろは許せない例',
    register: 'written',
    examplesJa: ['子どもならいざしらず、大人がすることではありません。', '初日ならいざしらず、一か月たっています。'],
    examplesZh: ['如果是孩子还情有可原，但这不是大人该做的。', '如果是第一天还说得过去，可已经过了一个月。'],
    furigana: 'こども なら いざしらず、おとなが する ことでは ありません。',
    commonMistakesZh: '前后要形成对比。只写一边不成立',
    learnerFocus: '结构是「A ならいざしらず、B」＝A还行，B不行',
    similarPatterns: ['〜ならまだしも', '〜はともかく'],
    contrast: '「ならいざしらず」＝硬い書き言葉；「ならまだしも」＝話し言葉でも使える',
    recognition: {
      promptZh: '「子どもならいざしらず」后面最可能接什么？',
      options: ['大人がすることではない', '子どもが好きだ', '子どもに聞いた', '子どもも来る'],
      answerIndex: 0,
      distractorReason: '前は許せる例、後ろは許せない例という対比になる',
      distractorReasonZh: '前面是可以原谅的例子，后面是不可原谅的例子，形成对比',
      explanationZh: '「〜ならいざしらず」＝如果是…还情有可原，但…',
    },
    production: {
      promptJa: '許せる場合と許せない場合を「〜ならいざしらず」で対比してください。',
      promptZh: '用「〜ならいざしらず」对比可以原谅和不可原谅的情况。',
      expected: ['いざしらず'], acceptable: ['ならいざしらず'],
    },
    practice: {
      themeJa: '許せる範囲を線引きする', starterJa: 'これなら仕方ない、と思える場合はどんな場合ですか？',
      starterZh: '什么情况下你觉得「这也没办法」？', targetUse: '〜ならいざしらず',
    },
    matchKeys: ['いざしらず'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-053', pattern: '〜ならまだしも', reading: 'ならまだしも', unit: 4,
    meaningJa: '〜ならまだいいが、〜はひどい',
    explanationZh: '如果是…还好，但…就太过分了',
    formation: '名詞／動詞・形容詞の普通形＋ならまだしも',
    usageScene: '抱怨程度超过了可以接受的范围',
    nuance: '不満を述べる場面に使う',
    register: 'spoken',
    examplesJa: ['一度ならまだしも、三度も遅刻しました。', '遅れるならまだしも、連絡もありません。'],
    examplesZh: ['一次还好说，可迟到了三次。', '迟到还好说，可连联系都没有。'],
    furigana: 'いちど なら まだしも、さんども ちこく しました。',
    commonMistakesZh: '后面是让人不满的内容。不能接好事',
    learnerFocus: '和「ならいざしらず」意思接近，「ならまだしも」更口语、更带不满',
    similarPatterns: ['〜ならいざしらず', '〜はまだしも'],
    contrast: '「ならまだしも」＝不満の対比（話し言葉寄り）；「ならいざしらず」＝硬い書き言葉',
    recognition: {
      promptZh: '哪个句子用「ならまだしも」自然？',
      options: ['一度ならまだしも何度も遅れた', '一度ならまだしもうれしかった', '一度ならまだしも合格した', '一度ならまだしも褒められた'],
      answerIndex: 0,
      distractorReason: '「ならまだしも」の後ろは不満に思う内容が来る',
      distractorReasonZh: '「ならまだしも」后面接令人不满的内容',
      explanationZh: '「〜ならまだしも」＝如果是…还好，但…太过分',
    },
    production: {
      promptJa: '我慢できない例を「〜ならまだしも」で言ってください。',
      promptZh: '用「〜ならまだしも」说一件无法忍受的事。',
      expected: ['まだしも'], acceptable: ['ならまだしも'],
    },
    practice: {
      themeJa: '我慢できないこと', starterJa: 'ここまでなら許せる、という線はどこですか？',
      starterZh: '你能忍受的界线在哪里？', targetUse: '〜ならまだしも',
    },
    matchKeys: ['まだしも'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-054', pattern: '〜はさておき', reading: 'はさておき', unit: 4,
    meaningJa: '〜は今は考えないで',
    explanationZh: '…暂且不谈。用于切换话题',
    formation: '名詞＋はさておき',
    usageScene: '会议中把次要话题放一边，先谈重点',
    nuance: '前の話題を否定するのではなく、順番を後回しにする',
    register: 'spoken',
    examplesJa: ['費用はさておき、まず日程を決めましょう。', '細かい点はさておき、方向は合っています。'],
    examplesZh: ['费用暂且不谈，先定日程吧。', '细节暂且不论，方向是对的。'],
    furigana: 'ひようは さておき、まず にっていを きめましょう。',
    commonMistakesZh: '不是「不重要」，而是「以后再说」',
    learnerFocus: '会议里非常好用。「〜はさておき、まず…」整句记住',
    similarPatterns: ['〜はともかく', '〜は別として'],
    contrast: '「はさておき」＝順番を後回しにする；「はともかく」＝評価を保留する',
    recognition: {
      promptZh: '「費用はさておき」是什么意思？',
      options: ['费用暂且不谈', '费用最重要', '费用已经付了', '费用不需要'],
      answerIndex: 0,
      distractorReason: '「はさておき」は話題を後回しにする表現',
      distractorReasonZh: '「はさておき」表示把话题往后放',
      explanationZh: '「〜はさておき」＝…暂且不谈',
    },
    production: {
      promptJa: '後回しにしたい話題を「〜はさておき」で言ってください。',
      promptZh: '用「〜はさておき」说一个想稍后再谈的话题。',
      expected: ['はさておき'], acceptable: ['さておき'],
    },
    practice: {
      themeJa: '話の順番を整理する', starterJa: '会議で先に決めるべきことは何ですか？',
      starterZh: '开会时应该先定什么？', targetUse: '〜はさておき',
    },
    matchKeys: ['さておき'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-055', pattern: '〜もさることながら', reading: 'もさることながら', unit: 4,
    meaningJa: '〜ももちろんだが、それ以上に',
    explanationZh: '…固然如此，但更…。用于强调后者',
    formation: '名詞＋もさることながら',
    usageScene: '评价时指出更值得注意的一面',
    nuance: '前も認めたうえで、後ろをより強く言う',
    register: 'written',
    examplesJa: ['味もさることながら、店の雰囲気がいいです。', '値段もさることながら、使いやすさが大切です。'],
    examplesZh: ['味道固然好，店里的氛围也很棒。', '价格固然重要，好用与否更关键。'],
    furigana: 'あじも さる こと ながら、みせの ふんいきが いいです。',
    commonMistakesZh: '前面接名词。重点在后半句，不要弄反',
    learnerFocus: '考试常问「重点在前还是在后」。答案是后半句',
    similarPatterns: ['〜はもちろん', '〜に加えて'],
    contrast: '「もさることながら」＝後ろを強調；「はもちろん」＝両方を並べるだけ',
    recognition: {
      promptZh: '「味もさることながら」这句话的重点在哪里？',
      options: ['在后半句的内容', '在味道', '两者相同', '没有重点'],
      answerIndex: 0,
      distractorReason: '「もさることながら」は後ろの内容を強調する',
      distractorReasonZh: '「もさることながら」强调后半句的内容',
      explanationZh: '「〜もさることながら」＝…固然如此，但更…',
    },
    production: {
      promptJa: '二つの良さを「〜もさることながら」で比べてください。',
      promptZh: '用「〜もさることながら」比较两个优点。',
      expected: ['さることながら'], acceptable: ['もさることながら'],
    },
    practice: {
      themeJa: '店やものの良さを語る', starterJa: '好きな店の一番いいところはどこですか？',
      starterZh: '你喜欢的店最好的地方是什么？', targetUse: '〜もさることながら',
    },
    matchKeys: ['さることながら'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-056', pattern: '〜であれ〜であれ', reading: 'であれであれ', unit: 4,
    meaningJa: '〜でも〜でも（どちらでも同じ）',
    explanationZh: '无论是…还是…（都一样）',
    formation: '名詞＋であれ＋名詞＋であれ',
    usageScene: '说明规则对任何情况都适用',
    nuance: '対になる二つを並べて「どちらも同じ」と言う',
    register: 'written',
    examplesJa: ['晴れであれ雨であれ、練習は行います。', '大人であれ子どもであれ、料金は同じです。'],
    examplesZh: ['无论晴天还是雨天，都会训练。', '无论大人还是孩子，费用都相同。'],
    furigana: 'はれで あれ あめで あれ、れんしゅうは おこないます。',
    commonMistakesZh: '两边都要用名词，且通常是相对的一组',
    learnerFocus: '「〜であれ〜であれ」＝无论A还是B。看到就找成对的名词',
    similarPatterns: ['〜でも〜でも', '〜を問わず'],
    contrast: '「であれ〜であれ」＝硬い書き言葉；「でも〜でも」＝話し言葉',
    recognition: {
      promptZh: '「晴れであれ雨であれ」是什么意思？',
      options: ['无论晴天还是雨天', '如果是晴天或雨天', '晴天比雨天好', '既不晴也不雨'],
      answerIndex: 0,
      distractorReason: '「であれ〜であれ」はどちらの場合も同じという意味',
      distractorReasonZh: '「であれ〜であれ」表示两种情况都一样',
      explanationZh: '「〜であれ〜であれ」＝无论…还是…',
    },
    production: {
      promptJa: 'どちらでも同じことを「〜であれ〜であれ」で言ってください。',
      promptZh: '用「〜であれ〜であれ」说一件两种情况都一样的事。',
      expected: ['であれ'], acceptable: [],
    },
    practice: {
      themeJa: '条件に左右されないこと', starterJa: '天気に関係なく続けていることはありますか？',
      starterZh: '有什么事是不管天气都会做的？', targetUse: '〜であれ〜であれ',
    },
    matchKeys: ['であれ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-057', pattern: '〜であろうと', reading: 'であろうと', unit: 4,
    meaningJa: '〜であっても（関係なく）',
    explanationZh: '即使是…也（无关）',
    formation: '名詞＋であろうと／疑問詞＋であろうと',
    usageScene: '强调不因对象而改变',
    nuance: '「誰であろうと」「どんな理由であろうと」の形が多い',
    register: 'written',
    examplesJa: ['誰であろうと、決まりは同じです。', 'どんな理由であろうと、遅刻は遅刻です。'],
    examplesZh: ['无论是谁，规定都一样。', '无论什么理由，迟到就是迟到。'],
    furigana: 'だれで あろうと、きまりは おなじです。',
    commonMistakesZh: '与推测的「〜だろう」不同。这里是让步',
    learnerFocus: '与疑问词搭配时意思最清楚：誰／どこ／いつ＋であろうと',
    similarPatterns: ['〜であっても', '〜にせよ'],
    contrast: '「であろうと」＝譲歩（〜でも）；「だろう」＝推測',
    recognition: {
      promptZh: '「誰であろうと」是什么意思？',
      options: ['无论是谁', '大概是谁', '是谁呢', '不是谁'],
      answerIndex: 0,
      distractorReason: '「であろうと」は譲歩。推測の「だろう」とは違う',
      distractorReasonZh: '「であろうと」表示让步，与推测的「だろう」不同',
      explanationZh: '「〜であろうと」＝即使是…也',
    },
    production: {
      promptJa: '誰にでも当てはまることを「誰であろうと」で言ってください。',
      promptZh: '用「誰であろうと」说一件对谁都适用的事。',
      expected: ['であろうと'], acceptable: [],
    },
    practice: {
      themeJa: '例外のない決まり', starterJa: '誰にでも同じように守ってほしい決まりは？',
      starterZh: '有什么规定希望所有人都一样遵守？', targetUse: '〜であろうと',
    },
    matchKeys: ['であろうと'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-058', pattern: '〜たりとも', reading: 'たりとも', unit: 4,
    meaningJa: '（少しの数）も〜ない',
    explanationZh: '连…也不…。与最小的数量搭配，强调完全否定',
    formation: '一＋助数詞＋たりとも（＋否定）',
    usageScene: '强调一点都不允许',
    nuance: '「一日たりとも」「一円たりとも」など、数字の「一」と組む',
    register: 'written',
    examplesJa: ['一日たりとも休んだことはありません。', '一円たりともむだにできません。'],
    examplesZh: ['一天也没有休息过。', '一日元也不能浪费。'],
    furigana: 'いちにち たりとも やすんだ ことは ありません。',
    commonMistakesZh: '后面必须是否定。也不用于大数字',
    learnerFocus: '固定形式是「一〜たりとも〜ない」。数字必须是「一」',
    similarPatterns: ['〜も〜ない', '〜すら'],
    contrast: '「たりとも」＝最小単位を挙げて全否定；「すら」＝極端な例を挙げて強調',
    recognition: {
      promptZh: '哪个句子用「たりとも」自然？',
      options: ['一日たりとも忘れない', '三日たりとも忘れない', '一日たりとも忘れる', '毎日たりとも忘れない'],
      answerIndex: 0,
      distractorReason: '「一＋助数詞＋たりとも＋否定」が決まった形',
      distractorReasonZh: '固定形式是「一＋量词＋たりとも＋否定」',
      explanationZh: '「〜たりとも」＝连一…也不…',
    },
    production: {
      promptJa: '一度も休んでいないことを「一日たりとも」で言ってください。',
      promptZh: '用「一日たりとも」说一件一天也没间断的事。',
      expected: ['たりとも'], acceptable: [],
    },
    practice: {
      themeJa: '続けていること', starterJa: '一日も欠かさず続けていることはありますか？',
      starterZh: '有什么事你一天也没间断过？', targetUse: '〜たりとも',
    },
    matchKeys: ['たりとも'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-059', pattern: '〜にしたところで', reading: 'にしたところで', unit: 4,
    meaningJa: '〜の立場でも、結局は同じだ',
    explanationZh: '即便是…，结果也一样',
    formation: '名詞／動詞普通形＋にしたところで',
    usageScene: '指出换个立场也解决不了问题',
    nuance: '後ろは否定的・消極的な結論が来る',
    register: 'written',
    examplesJa: ['私にしたところで、いい案はありません。', '急いだにしたところで、間に合わないでしょう。'],
    examplesZh: ['即便是我，也没有好主意。', '即便赶时间，恐怕也来不及。'],
    furigana: 'わたしに した ところで、いい あんは ありません。',
    commonMistakesZh: '后面接消极的结论，不接好结果',
    learnerFocus: '＝「〜にしても」的强调形。理解为「就算…也没用」',
    similarPatterns: ['〜にしても', '〜にせよ'],
    contrast: '「にしたところで」＝結局だめだという含み；「にしても」＝中立の譲歩',
    recognition: {
      promptZh: '「私にしたところで」是什么意思？',
      options: ['即便是我（也…）', '我做的地方', '我打算做', '我做完了'],
      answerIndex: 0,
      distractorReason: '「にしたところで」は「〜にしても」と同じ譲歩',
      distractorReasonZh: '「にしたところで」与「〜にしても」同为让步',
      explanationZh: '「〜にしたところで」＝即便是…也…',
    },
    production: {
      promptJa: '立場を変えても同じだということを「〜にしたところで」で言ってください。',
      promptZh: '用「〜にしたところで」说明换了立场也一样。',
      expected: ['にしたところで'], acceptable: ['としたところで'],
    },
    practice: {
      themeJa: '立場を変えても変わらないこと', starterJa: '誰がやっても同じだと思うことはありますか？',
      starterZh: '有什么事你觉得谁做都一样？', targetUse: '〜にしたところで',
    },
    matchKeys: ['にしたところで'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-060', pattern: '〜とはいうものの', reading: 'とはいうものの', unit: 4,
    meaningJa: 'そうは言っても、実際は',
    explanationZh: '话虽如此，但实际上…',
    formation: '文＋とはいうものの',
    usageScene: '在文章中先承认前文，再提出现实的困难',
    nuance: '前の文を受けて、文頭に置くことが多い',
    register: 'written',
    examplesJa: ['続けたいとはいうものの、時間がありません。', '便利になったとはいうものの、費用は増えました。'],
    examplesZh: ['话虽说想继续，可没有时间。', '虽说变方便了，费用却增加了。'],
    furigana: 'つづけたい とは いう ものの、じかんが ありません。',
    commonMistakesZh: '后面是与前面相反的现实。不接同方向的内容',
    learnerFocus: '文章里出现在段落开头时，几乎等于「不过」',
    similarPatterns: ['〜とはいえ', '〜ものの'],
    contrast: '「とはいうものの」＝前の文全体を受ける；「ものの」＝一文の中の逆接',
    recognition: {
      promptZh: '「とはいうものの」后面最可能接什么？',
      options: ['与前面相反的现实', '同样的内容', '理由的说明', '例子的补充'],
      answerIndex: 0,
      distractorReason: '「とはいうものの」は逆接の接続',
      distractorReasonZh: '「とはいうものの」是表示逆接的连接',
      explanationZh: '「〜とはいうものの」＝话虽如此，但实际上…',
    },
    production: {
      promptJa: '思いと現実の差を「〜とはいうものの」で言ってください。',
      promptZh: '用「〜とはいうものの」说说想法与现实的差距。',
      expected: ['とはいうものの'], acceptable: [],
    },
    practice: {
      themeJa: '理想と現実', starterJa: 'やりたいのにできていないことはありますか？',
      starterZh: '有什么是想做却没能做的？', targetUse: '〜とはいうものの',
    },
    matchKeys: ['とはいうものの'], vocabularyLinks: [],
  }),
];
