// N1文法 Unit 1（15項目 / 「これしかない・気にしない」系＋強調の副助詞）。
// 例文・訳・解説はすべて自社で書き起こす。場面は日本で暮らす中国語話者が実際に読む文章に寄せる。
import { n1g, type N1GrammarDraft } from './n1GrammarDrafts';

export const N1_GRAMMAR_DRAFTS_UNIT1: N1GrammarDraft[] = [
  n1g({
    grammarId: 'n1g-001', pattern: '〜をおいて（他にない）', reading: 'をおいて', unit: 1,
    meaningJa: '〜以外に適した人・物はない',
    explanationZh: '除了…没有别的（合适的）。用于强调「非他莫属」',
    formation: '名詞＋をおいて（＋他にない／〜ない）',
    usageScene: '推荐人选、评价唯一的选择时',
    nuance: '必ず打ち消しと一緒に使う。ほめる文脈が多い',
    register: 'written',
    examplesJa: ['この仕事を任せられるのは、彼をおいて他にいません。', 'これをおいて他に方法はないと判断しました。'],
    examplesZh: ['能把这份工作交付的，除了他没有别人。', '判断除此之外没有别的办法。'],
    furigana: 'この しごとを まかせられるのは、かれを おいて ほかに いません。',
    commonMistakesZh: '不能用于肯定句。「彼をおいて適任だ」不成立，必须是「彼をおいて他にいない」',
    learnerFocus: '中文的「除了…」既可接肯定也可接否定，日语的「をおいて」只接否定',
    similarPatterns: ['〜以外に', '〜しかない'],
    contrast: '「をおいて」＝唯一で最適だと持ち上げる；「〜しかない」＝選択肢が他に無いだけで、ほめる意味は無い',
    recognition: {
      promptZh: '哪个句子用「をおいて」自然？',
      options: ['適任者は彼女をおいて他にいない', '彼女をおいて選ばれた', '雨をおいて中止した', '朝をおいて出発する'],
      answerIndex: 0,
      distractorReason: '「をおいて」は必ず打ち消しと組み、「他にない」と続く',
      distractorReasonZh: '「をおいて」必须与否定搭配，后接「他にない」',
      explanationZh: '「〜をおいて他にない」＝除了…再没有别的（最合适的）',
    },
    production: {
      promptJa: '「この人しかいない」と思う相手を「〜をおいて」で言ってください。',
      promptZh: '用「〜をおいて」说一个你觉得非他莫属的人。',
      expected: ['をおいて'], acceptable: ['をおいて他に'],
    },
    practice: {
      themeJa: '任せられる人を推薦する', starterJa: 'この仕事を任せるなら、誰がいいと思いますか？',
      starterZh: '这份工作交给谁比较好？', targetUse: '〜をおいて',
    },
    matchKeys: ['をおいて'],
    vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-002', pattern: '〜をものともせず', reading: 'をものともせず', unit: 1,
    meaningJa: '困難を問題にしないで、立ち向かう',
    explanationZh: '不把…当回事，毫不畏惧地…。多用于赞扬克服困难的行为',
    formation: '名詞＋をものともせず（に）',
    usageScene: '报道中称赞在恶劣条件下坚持的人',
    nuance: '第三者をほめる語。自分のことには使いにくい',
    register: 'written',
    examplesJa: ['雨をものともせず、選手たちは走り続けました。', '年齢をものともせず、新しい仕事に挑んでいます。'],
    examplesZh: ['选手们不惧风雨，一直跑了下去。', '不把年龄当回事，正在挑战新的工作。'],
    furigana: 'あめを ものともせず、せんしゅたちは はしりつづけました。',
    commonMistakesZh: '不用于自己：「私は雨をものともせず行った」不自然。也不接动词句，前面是名词',
    learnerFocus: '「不顾…」在中文可自述，日语的「をものともせず」基本是从外部称赞别人',
    similarPatterns: ['〜にもかかわらず', '〜を顧みず'],
    contrast: '「をものともせず」＝困難を軽々と越える（ほめる）；「にもかかわらず」＝ただ逆接で、評価は含まない',
    recognition: {
      promptZh: '哪个句子用「をものともせず」自然？',
      options: ['寒さをものともせず練習を続けた', '成功をものともせず喜んだ', '休みをものともせず寝た', 'お金をものともせず買えた'],
      answerIndex: 0,
      distractorReason: '前に来るのは乗り越える対象（困難）。よいことや楽なことは置けない',
      distractorReasonZh: '前面要接被克服的困难，不能放好事或轻松的事',
      explanationZh: '「〜をものともせず」＝不把困难当回事，勇敢面对',
    },
    production: {
      promptJa: '悪い条件の中でがんばっていた人について「〜をものともせず」で言ってください。',
      promptZh: '用「〜をものともせず」说说在恶劣条件下坚持的人。',
      expected: ['をものともせず'], acceptable: ['をものともせずに'],
    },
    practice: {
      themeJa: '困難に負けなかった人の話', starterJa: '大変な状況でもがんばっていた人を知っていますか？',
      starterZh: '你认识在艰难处境中仍坚持的人吗？', targetUse: '〜をものともせず',
    },
    matchKeys: ['をものともせず'],
    vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-003', pattern: '〜をよそに', reading: 'をよそに', unit: 1,
    meaningJa: '周りの心配や反対を気にしないで',
    explanationZh: '不顾…（周围的担心、反对）。带有批评的语气',
    formation: '名詞＋をよそに',
    usageScene: '报道中指出无视周围声音的行为',
    nuance: '「ものともせず」と違い、**よくない態度**として言うことが多い',
    register: 'written',
    examplesJa: ['住民の反対をよそに、工事が始まりました。', '周りの心配をよそに、本人は平気な顔をしています。'],
    examplesZh: ['不顾居民的反对，工程开始了。', '不顾周围的担心，本人一脸没事的样子。'],
    furigana: 'じゅうみんの はんたいを よそに、こうじが はじまりました。',
    commonMistakesZh: '前面接的是「周围的声音」（反对、担心、混乱），不接自己的困难',
    learnerFocus: '「をものともせず」是称赞，「をよそに」是批评。同样译成「不顾」，态度相反',
    similarPatterns: ['〜をものともせず', '〜にもかかわらず'],
    contrast: '「をよそに」＝周りの声を無視する（否定的）；「をものともせず」＝困難を乗り越える（肯定的）',
    recognition: {
      promptZh: '哪个句子用「をよそに」自然？',
      options: ['親の心配をよそに旅に出た', '雨をよそに傘を差した', '合格をよそに喜んだ', '努力をよそに続けた'],
      answerIndex: 0,
      distractorReason: '前に来るのは周囲の心配・反対など「人の声」。天候や自分の努力は置けない',
      distractorReasonZh: '前面要接周围的担心、反对等「他人的声音」，不能放天气或自己的努力',
      explanationZh: '「〜をよそに」＝不顾周围的担心或反对',
    },
    production: {
      promptJa: '周りの反対を気にせず何かをした話を「〜をよそに」で言ってください。',
      promptZh: '用「〜をよそに」说一件不顾周围反对做的事。',
      expected: ['をよそに'], acceptable: [],
    },
    practice: {
      themeJa: '周りの声を気にしなかった話', starterJa: '周りに反対されてもやったことはありますか？',
      starterZh: '有过被周围反对仍去做的事吗？', targetUse: '〜をよそに',
    },
    matchKeys: ['をよそに'],
    vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-004', pattern: '〜ならでは', reading: 'ならでは', unit: 1,
    meaningJa: '〜だけが持つ、〜にしかない',
    explanationZh: '只有…才有的。用于赞扬独特之处',
    formation: '名詞＋ならでは（の＋名詞／だ）',
    usageScene: '介绍地方特色、店铺特色、个人风格',
    nuance: 'ほめる文脈にだけ使う。観光や紹介の文でよく出る',
    register: 'written',
    examplesJa: ['この店ならではの味を楽しめます。', '地元の人ならではの案内が心に残りました。'],
    examplesZh: ['能品尝到这家店独有的味道。', '只有本地人才做得到的向导让我难忘。'],
    furigana: 'この みせ ならではの あじを たのしめます。',
    commonMistakesZh: '不用于负面内容：「この店ならではの汚さ」不自然。后面多接「の＋名词」',
    learnerFocus: '「只有…才有」在中文褒贬皆可，日语的「ならでは」只用于好的特色',
    similarPatterns: ['〜特有の', '〜しかない'],
    contrast: '「ならでは」＝そこだけの良さ（ほめる）；「特有の」＝中立で、悪い特徴にも使える',
    recognition: {
      promptZh: '哪个句子用「ならでは」自然？',
      options: ['この土地ならではの料理だ', '雨ならではの中止だ', '失敗ならではの結果だ', '朝ならではの遅刻だ'],
      answerIndex: 0,
      distractorReason: '「ならでは」はよい特色にだけ使う。失敗や中止のような否定的な内容は置けない',
      distractorReasonZh: '「ならでは」只用于好的特色，不能放失败、取消等负面内容',
      explanationZh: '「〜ならでは」＝只有…才有的（好的特色）',
    },
    production: {
      promptJa: 'あなたの故郷にしかない良さを「〜ならでは」で言ってください。',
      promptZh: '用「〜ならでは」说说你家乡独有的好。',
      expected: ['ならでは'], acceptable: ['ならではの'],
    },
    practice: {
      themeJa: '土地や店の特色を紹介する', starterJa: 'あなたの町にしかないものは何ですか？',
      starterZh: '你所在的城市有什么是别处没有的？', targetUse: '〜ならでは',
    },
    matchKeys: ['ならでは'],
    vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-005', pattern: '〜いかんによっては', reading: 'いかんによっては', unit: 1,
    meaningJa: '〜がどうであるかによって、結果が変わる',
    explanationZh: '根据…的情况（结果会不同）。用于正式的说明和条件',
    formation: '名詞（＋の）＋いかんによっては／いかんでは',
    usageScene: '公告、合同中说明「视情况而定」',
    nuance: '硬い書き言葉。話し言葉では「〜次第では」を使う',
    register: 'written',
    examplesJa: ['天候のいかんによっては、中止することがあります。', '結果いかんによっては、計画を見直します。'],
    examplesZh: ['视天气情况，有可能取消。', '视结果而定，将重新审视计划。'],
    furigana: 'てんこうの いかんによっては、ちゅうしする ことが あります。',
    commonMistakesZh: '前面只接名词，不接句子。「行くかどうかのいかんによっては」不自然',
    learnerFocus: '和「〜次第では」意思相同，但「いかんによっては」只出现在正式文书里',
    similarPatterns: ['〜次第では', '〜によっては'],
    contrast: '「いかんによっては」＝硬い書き言葉；「次第では」＝話し言葉でも使える',
    recognition: {
      promptZh: '哪个句子用「いかんによっては」自然？',
      options: ['状況のいかんによっては延期する', '状況のいかんによっては行った', 'いかんによっては雨が降った', '昨日のいかんによっては来た'],
      answerIndex: 0,
      distractorReason: '後ろに来るのはこれから起こりうること。過去の事実は置けない',
      distractorReasonZh: '后面要接今后可能发生的事，不能放已发生的过去事实',
      explanationZh: '「〜いかんによっては」＝视…的情况，结果可能不同',
    },
    production: {
      promptJa: '条件によって変わる予定を「〜いかんによっては」で言ってください。',
      promptZh: '用「〜いかんによっては」说一个视情况而定的安排。',
      expected: ['いかんによっては'], acceptable: ['いかんでは'],
    },
    practice: {
      themeJa: '条件つきの予定を伝える', starterJa: '状況によって変わる予定はありますか？',
      starterZh: '有什么安排是要看情况的吗？', targetUse: '〜いかんによっては',
    },
    matchKeys: ['いかんによって', 'いかんでは'],
    vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-006', pattern: '〜すら', reading: 'すら', unit: 1,
    meaningJa: '〜さえ（極端な例をあげる）',
    explanationZh: '连…都。举出极端的例子来强调',
    formation: '名詞＋すら／名詞＋ですら',
    usageScene: '强调状况严重、连最基本的事都做不到',
    nuance: '「さえ」より硬い。悪い状況の描写に多い',
    register: 'written',
    examplesJa: ['忙しくて、食事をする時間すらありません。', '専門家ですら答えられない質問でした。'],
    examplesZh: ['忙到连吃饭的时间都没有。', '那是连专家都答不上来的问题。'],
    furigana: 'いそがしくて、しょくじを する じかん すら ありません。',
    commonMistakesZh: '一般接名词。想接动词时用「〜さえ〜ない」或「〜すらしない」的形式',
    learnerFocus: '「连…都」的日语有「さえ・すら・まで」。「すら」是最书面的一个',
    similarPatterns: ['〜さえ', '〜まで'],
    contrast: '「すら」＝書き言葉で、否定と結びつきやすい；「さえ」＝話し言葉でも使え、条件の「〜さえ〜ば」もある',
    recognition: {
      promptZh: '哪个句子用「すら」自然？',
      options: ['名前すら知らない相手だった', 'すら食べれば元気になる', '雨すら降って中止した', '朝すら起きて出かけた'],
      answerIndex: 0,
      distractorReason: '「すら」は極端な例をあげて「〜も…ない」と言う形。条件や理由には使えない',
      distractorReasonZh: '「すら」用于举极端例子说「连…都不…」，不能表示条件或理由',
      explanationZh: '「〜すら」＝连…都（不）',
    },
    production: {
      promptJa: '忙しかった時期のことを「〜すら」で言ってください。',
      promptZh: '用「〜すら」说说你最忙的那段时期。',
      expected: ['すら'], acceptable: ['ですら'],
    },
    practice: {
      themeJa: '余裕がなかった時期の話', starterJa: '時間がなくてできなかったことはありますか？',
      starterZh: '有没有因为没时间而做不成的事？', targetUse: '〜すら',
    },
    matchKeys: ['すら'],
    vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-007', pattern: '〜だに', reading: 'だに', unit: 1,
    meaningJa: '〜さえ（〜するだけでも）',
    explanationZh: '连…都；光是…就…。多用于固定说法',
    formation: '動詞辞書形／名詞＋だに',
    usageScene: '书面表达强烈的感受',
    nuance: '「想像するだに」「微動だにしない」など、決まった形で覚えるのが実用的',
    register: 'written',
    examplesJa: ['想像するだに恐ろしい出来事でした。', '重い扉は押しても微動だにしませんでした。'],
    examplesZh: ['那是光想想都可怕的事件。', '沉重的门推了也纹丝不动。'],
    furigana: 'そうぞうする だに おそろしい できごとでした。',
    commonMistakesZh: '不能自由造句。基本上以「想像するだに」「微動だにしない」等固定形式使用',
    learnerFocus: '与「すら」意思相近，但「だに」几乎只出现在固定搭配里。考试主要考辨认',
    similarPatterns: ['〜すら', '〜さえ'],
    contrast: '「だに」＝固定表現が中心；「すら」＝自由に名詞に付けられる',
    recognition: {
      promptZh: '哪个句子用「だに」自然？',
      options: ['想像するだに恐ろしい', '食べるだにおいしい', '朝だに起きた', '雨だに降った'],
      answerIndex: 0,
      distractorReason: '「だに」は「想像するだに」など決まった形で使う。よい内容や単なる事実には付かない',
      distractorReasonZh: '「だに」用于「想像するだに」等固定形式，不接好事或单纯的事实',
      explanationZh: '「〜だに」＝连…都；光是…就…（书面固定说法）',
    },
    production: {
      promptJa: '考えるだけでこわいことを「想像するだに」で言ってください。',
      promptZh: '用「想像するだに」说一件光想就害怕的事。',
      expected: ['だに'], acceptable: ['想像するだに'],
    },
    practice: {
      themeJa: '考えるだけでこわいこと', starterJa: '想像するだけでこわいことはありますか？',
      starterZh: '有什么是光想想就觉得可怕的？', targetUse: '〜だに',
    },
    matchKeys: ['だに'],
    vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-008', pattern: '〜ごとき／〜ごとく', reading: 'ごとき／ごとく', unit: 1,
    meaningJa: '〜のような／〜のように',
    explanationZh: '如同…一样。是「ような・ように」的书面（文语）说法',
    formation: '名詞＋の＋ごとき／ごとく、動詞辞書形・た形＋（が）ごとく',
    usageScene: '正式的致辞、文学性的文章',
    nuance: '硬い文語。日常会話では使わない',
    register: 'written',
    examplesJa: ['彼は水が流れるごとく自然に話します。', '毎年のごとく、今年も同じ場所に集まりました。'],
    examplesZh: ['他说话如流水般自然。', '一如每年，今年也聚在了同一个地方。'],
    furigana: 'かれは みずが ながれる ごとく しぜんに はなします。',
    commonMistakesZh: '不要与表示轻蔑的「私ごとき」混同。那是另一个用法，意思是「像我这样的（人）」',
    learnerFocus: '考试主要考「＝ような・ように」的换说。看到「ごとく」先换成「ように」再读',
    similarPatterns: ['〜ような', '〜ように'],
    contrast: '「ごとく」＝文語で硬い；「ように」＝日常でも使える標準的な言い方',
    recognition: {
      promptZh: '「ごとく」最接近下面哪一个？',
      options: ['ように', 'ために', 'によって', 'ながら'],
      answerIndex: 0,
      distractorReason: '「ごとく」は比喩の「ように」の文語形',
      distractorReasonZh: '「ごとく」是比喻「ように」的文语形式',
      explanationZh: '「〜ごとく」＝「〜ように」的书面语',
    },
    production: {
      promptJa: '何かのたとえを「〜ごとく」で言ってください。',
      promptZh: '用「〜ごとく」说一个比喻。',
      expected: ['ごとく'], acceptable: ['ごとき'],
    },
    practice: {
      themeJa: 'たとえを使って説明する', starterJa: '何かにたとえて説明できますか？',
      starterZh: '能用比喻来说明吗？', targetUse: '〜ごとく',
    },
    matchKeys: ['ごとき', 'ごとく'],
    vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-009', pattern: '〜きらいがある', reading: 'きらいがある', unit: 1,
    meaningJa: '（よくない）傾向がある',
    explanationZh: '有…（不好的）倾向。是委婉的批评',
    formation: '動詞辞書形／名詞＋の ＋きらいがある',
    usageScene: '评价某人或某种做法的缺点时，委婉地指出',
    nuance: '必ず好ましくない傾向に使う。「好き嫌い」とは無関係',
    register: 'written',
    examplesJa: ['彼は物事を一人で抱え込むきらいがあります。', 'この計画は費用を軽く見るきらいがあります。'],
    examplesZh: ['他有把事情一个人扛下来的倾向。', '这个计划有轻视费用的倾向。'],
    furigana: 'かれは ものごとを ひとりで かかえこむ きらいが あります。',
    commonMistakesZh: '与「嫌い（讨厌）」无关。也不能用于好的倾向：「よく働くきらいがある」不自然',
    learnerFocus: '汉字写作「嫌いがある」，但意思是「倾向」。这是最容易误读的一个',
    similarPatterns: ['〜傾向がある', '〜がちだ'],
    contrast: '「きらいがある」＝よくない傾向を控えめに指摘；「傾向がある」＝よい傾向にも使える中立の語',
    recognition: {
      promptZh: '哪个句子用「きらいがある」自然？',
      options: ['結論を急ぐきらいがある', 'よく手伝うきらいがある', '毎日走るきらいがある', '朝が早いきらいがある'],
      answerIndex: 0,
      distractorReason: '「きらいがある」はよくない傾向にだけ使う。よい習慣には付かない',
      distractorReasonZh: '「きらいがある」只用于不好的倾向，不接好习惯',
      explanationZh: '「〜きらいがある」＝有（不好的）倾向',
    },
    production: {
      promptJa: '自分の直したいくせを「〜きらいがある」で言ってください。',
      promptZh: '用「〜きらいがある」说一个自己想改的毛病。',
      expected: ['きらいがある'], acceptable: ['きらいがあります'],
    },
    practice: {
      themeJa: '自分のくせを振り返る', starterJa: '直したいと思っているくせはありますか？',
      starterZh: '有什么想改掉的习惯吗？', targetUse: '〜きらいがある',
    },
    matchKeys: ['きらいがある'],
    vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-010', pattern: '〜にたえない', reading: 'にたえない', unit: 1,
    meaningJa: '（ひどくて）〜していられない／〜の気持ちでいっぱいだ',
    explanationZh: '不堪…；不胜…。有两种用法，要分开记',
    formation: '動詞辞書形＋にたえない／名詞（感情）＋にたえない',
    usageScene: '批评内容太差，或在正式致辞中表达强烈的感谢、遗憾',
    nuance: '「見るにたえない」＝ひどい／「感謝にたえない」＝強い感謝。同じ形で意味が反対に見える',
    register: 'written',
    examplesJa: ['あの建物は古く、見るにたえない状態です。', '皆さまのご協力には感謝にたえません。'],
    examplesZh: ['那栋建筑很旧，已到了不忍直视的状态。', '对各位的协助不胜感谢。'],
    furigana: 'あの たてものは ふるく、みるに たえない じょうたいです。',
    commonMistakesZh: '感情名词（感謝・遺憾・喜び）时是「不胜…」；动词时是「不堪…」。混用会意思相反',
    learnerFocus: '考试常考两种用法的区别。先看前面是「动词」还是「感情名词」',
    similarPatterns: ['〜がたい', '〜きれない'],
    contrast: '「にたえない」＝ひどくて耐えられない／強い感情；「〜がたい」＝したくてもできない（想像しがたい）',
    recognition: {
      promptZh: '「感謝にたえません」是什么意思？',
      options: ['不胜感谢', '不需要感谢', '无法感谢', '不想感谢'],
      answerIndex: 0,
      distractorReason: '感情の名詞に付くときは「その気持ちでいっぱいだ」の意味になる',
      distractorReasonZh: '接感情名词时表示「充满该情感」',
      explanationZh: '「感謝にたえない」＝不胜感谢（感谢之情非常强烈）',
    },
    production: {
      promptJa: '強く感謝している相手に「感謝にたえません」を使って言ってください。',
      promptZh: '用「感謝にたえません」向十分感谢的人表达。',
      expected: ['にたえない'], acceptable: ['にたえません'],
    },
    practice: {
      themeJa: '強い感謝を伝える', starterJa: '心から感謝している人はいますか？',
      starterZh: '有你打心底感谢的人吗？', targetUse: '〜にたえない',
    },
    matchKeys: ['にたえない', 'にたえません'],
    vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-011', pattern: '〜てやまない', reading: 'てやまない', unit: 1,
    meaningJa: 'ずっと〜と思い続けている',
    explanationZh: '衷心地…不已。用于表达持续而强烈的心愿',
    formation: '動詞て形＋やまない',
    usageScene: '致辞、书信中表达祝愿和期待',
    nuance: '願う・祈る・期待するなど、気持ちの動詞にだけ付く',
    register: 'written',
    examplesJa: ['皆さまのご健康を願ってやみません。', '若い人の活躍を期待してやまない。'],
    examplesZh: ['衷心祝愿各位身体健康。', '对年轻人的活跃期待不已。'],
    furigana: 'みなさまの ごけんこうを ねがって やみません。',
    commonMistakesZh: '不能接一般动作动词。「走ってやまない」「食べてやまない」不成立',
    learnerFocus: '能接的动词很有限：願う・祈る・期待する・愛する。整体背下来最快',
    similarPatterns: ['〜てならない', '〜を切に願う'],
    contrast: '「てやまない」＝自分から強く願い続ける；「てならない」＝自然にそう感じてしまう（気になってならない）',
    recognition: {
      promptZh: '哪个句子用「てやまない」自然？',
      options: ['ご成功を祈ってやみません', '毎日走ってやみません', 'ご飯を食べてやみません', '雨が降ってやみません'],
      answerIndex: 0,
      distractorReason: '「てやまない」は願う・祈るなど気持ちの動詞にだけ付く',
      distractorReasonZh: '「てやまない」只接祈愿、期待等表达心情的动词',
      explanationZh: '「〜てやまない」＝衷心地…不已',
    },
    production: {
      promptJa: '誰かへの願いを「〜てやみません」で言ってください。',
      promptZh: '用「〜てやみません」表达对某人的祝愿。',
      expected: ['てやまない'], acceptable: ['てやみません'],
    },
    practice: {
      themeJa: '相手への願いを伝える', starterJa: '大切な人に何を願いますか？',
      starterZh: '你想为重要的人祝愿什么？', targetUse: '〜てやまない',
    },
    matchKeys: ['てやまない', 'てやみません'],
    vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-012', pattern: '〜を余儀なくされる', reading: 'をよぎなくされる', unit: 1,
    meaningJa: '事情のせいで、仕方なく〜することになる',
    explanationZh: '被迫不得不…。强调并非本意',
    formation: '名詞＋を余儀なくされる',
    usageScene: '新闻报道中说明因外部原因而不得不做的事',
    nuance: '受け身の形で、本人に選ぶ余地がなかったことを表す',
    register: 'written',
    examplesJa: ['台風で大会は中止を余儀なくされました。', '体調を崩し、入院を余儀なくされました。'],
    examplesZh: ['因台风，大会被迫取消。', '身体不适，被迫住院。'],
    furigana: 'たいふうで たいかいは ちゅうしを よぎなく されました。',
    commonMistakesZh: '前面接名词（中止・変更・入院）。接动词时要先名词化',
    learnerFocus: '「不得不」有「〜ざるを得ない」和「〜を余儀なくされる」。后者更强调外部原因造成',
    similarPatterns: ['〜ざるを得ない', '〜しかない'],
    contrast: '「を余儀なくされる」＝外の事情で強いられる（報道の語）；「ざるを得ない」＝自分の判断としても仕方ない',
    recognition: {
      promptZh: '哪个句子用「を余儀なくされる」自然？',
      options: ['大雪で延期を余儀なくされた', '好きで参加を余儀なくされた', '楽しく旅行を余儀なくされた', '自分で決定を余儀なくされた'],
      answerIndex: 0,
      distractorReason: '本人の希望でしたことには使えない。外の事情で仕方なくなった場合だけ',
      distractorReasonZh: '不能用于本人愿意做的事，只用于因外部原因不得已的情况',
      explanationZh: '「〜を余儀なくされる」＝因外部原因被迫…',
    },
    production: {
      promptJa: '事情のせいで仕方なくしたことを「〜を余儀なくされました」で言ってください。',
      promptZh: '用「〜を余儀なくされました」说一件因故不得不做的事。',
      expected: ['余儀なく'], acceptable: ['を余儀なくされました'],
    },
    practice: {
      themeJa: '仕方なく変えた予定の話', starterJa: '事情で予定を変えたことはありますか？',
      starterZh: '有过因故改变计划的事吗？', targetUse: '〜を余儀なくされる',
    },
    matchKeys: ['余儀なく'],
    vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-013', pattern: '〜べからず／〜べからざる', reading: 'べからず／べからざる', unit: 1,
    meaningJa: '〜してはいけない（禁止）',
    explanationZh: '不得…；不可…。是告示牌上的文语禁止说法',
    formation: '動詞辞書形＋べからず／べからざる＋名詞',
    usageScene: '告示牌、规则的标示',
    nuance: '古い言い方。掲示以外では「〜べからざる〇〇」の形で見る',
    register: 'written',
    examplesJa: ['ここにごみを捨てるべからず、と書いてあります。', '欠くべからざる存在だと言われました。'],
    examplesZh: ['上面写着「不得在此丢弃垃圾」。', '被说是不可或缺的存在。'],
    furigana: 'ここに ごみを すてる べからず、と かいて あります。',
    commonMistakesZh: '不用于对人当面说话。当面说时用「〜てはいけません」',
    learnerFocus: '考试主要考辨认。「べからざる＋名词」＝「不可…的…」，如「欠くべからざる」',
    similarPatterns: ['〜てはいけない', '〜ないこと'],
    contrast: '「べからず」＝掲示の文語；「てはいけない」＝人に言うときの標準形',
    recognition: {
      promptZh: '「立ち入るべからず」是什么意思？',
      options: ['不得进入', '可以进入', '请进', '必须进入'],
      answerIndex: 0,
      distractorReason: '「べからず」は禁止を表す文語',
      distractorReasonZh: '「べからず」是表示禁止的文语',
      explanationZh: '「〜べからず」＝不得…（禁止）',
    },
    production: {
      promptJa: '掲示に書きそうな禁止を「〜べからず」で言ってください。',
      promptZh: '用「〜べからず」写一句像告示牌上的禁止。',
      expected: ['べからず'], acceptable: ['べからざる'],
    },
    practice: {
      themeJa: '掲示の日本語を読む', starterJa: '町で見た禁止の掲示を覚えていますか？',
      starterZh: '还记得在街上看到的禁止告示吗？', targetUse: '〜べからず',
    },
    matchKeys: ['べからず', 'べからざる'],
    vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-014', pattern: '〜まみれ', reading: 'まみれ', unit: 1,
    meaningJa: '（汚いものが）一面に付いている',
    explanationZh: '沾满…。多接脏东西或负面的东西',
    formation: '名詞＋まみれ',
    usageScene: '描写工作后、运动后的样子，或负债累累的状态',
    nuance: '汚れ・汗・ほこり・借金など、よくないものにだけ付く',
    register: 'spoken',
    examplesJa: ['作業のあと、服はほこりまみれでした。', '汗まみれになって荷物を運びました。'],
    examplesZh: ['作业结束后，衣服沾满了灰尘。', '满身大汗地搬了行李。'],
    furigana: 'さぎょうの あと、ふくは ほこり まみれでした。',
    commonMistakesZh: '不接好东西：「花まみれ」「幸せまみれ」不自然',
    learnerFocus: '「まみれ・だらけ・ずくめ」的区别是N1常考点。「まみれ」＝表面沾满液体或粉末',
    similarPatterns: ['〜だらけ', '〜ずくめ'],
    contrast: '「まみれ」＝表面いちめんに付く（汗・泥）；「だらけ」＝数が多い（間違いだらけ）；「ずくめ」＝全部それ（黒ずくめ）',
    recognition: {
      promptZh: '哪个句子用「まみれ」自然？',
      options: ['泥まみれの靴を洗った', '花まみれの庭を見た', '幸せまみれの日だった', '本まみれの棚を買った'],
      answerIndex: 0,
      distractorReason: '「まみれ」は汗・泥・ほこりのような汚れに付く。よいものには使えない',
      distractorReasonZh: '「まみれ」接汗、泥、灰尘等脏东西，不能接好的事物',
      explanationZh: '「〜まみれ」＝沾满（脏东西）',
    },
    production: {
      promptJa: '汚れた経験を「〜まみれ」で言ってください。',
      promptZh: '用「〜まみれ」说一次弄脏的经历。',
      expected: ['まみれ'], acceptable: [],
    },
    practice: {
      themeJa: '汚れた日の話', starterJa: '服がひどく汚れたことはありますか？',
      starterZh: '有过衣服弄得很脏的经历吗？', targetUse: '〜まみれ',
    },
    matchKeys: ['まみれ'],
    vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-015', pattern: '〜ずくめ', reading: 'ずくめ', unit: 1,
    meaningJa: '全部それだ、それが続く',
    explanationZh: '尽是…；清一色…。好事坏事都能接',
    formation: '名詞＋ずくめ',
    usageScene: '描写接连不断的好事，或全身同一颜色的打扮',
    nuance: '「いいことずくめ」「黒ずくめ」など、付く名詞が限られている',
    register: 'spoken',
    examplesJa: ['今年はいいことずくめの一年でした。', '黒ずくめの服装で式に出ました。'],
    examplesZh: ['今年是好事连连的一年。', '穿着一身黑参加了仪式。'],
    furigana: 'ことしは いい こと ずくめの いちねんでした。',
    commonMistakesZh: '不是「沾满」。「汗ずくめ」不自然，那要用「汗まみれ」',
    learnerFocus: '记住三个固定搭配就够用：「いいことずくめ」「黒ずくめ」「規則ずくめ」',
    similarPatterns: ['〜まみれ', '〜だらけ'],
    contrast: '「ずくめ」＝全部それで占められている；「まみれ」＝表面に付着している',
    recognition: {
      promptZh: '哪个句子用「ずくめ」自然？',
      options: ['いいことずくめの一週間だった', '泥ずくめの靴を洗った', '汗ずくめで働いた', 'ほこりずくめの棚だ'],
      answerIndex: 0,
      distractorReason: '汚れが付いている場合は「まみれ」。「ずくめ」は全部それで占められる意味',
      distractorReasonZh: '沾上脏东西时用「まみれ」；「ずくめ」表示全被它占满',
      explanationZh: '「〜ずくめ」＝尽是…；清一色…',
    },
    production: {
      promptJa: 'よいことが続いた時期を「いいことずくめ」で言ってください。',
      promptZh: '用「いいことずくめ」说一段好事连连的时期。',
      expected: ['ずくめ'], acceptable: ['いいことずくめ'],
    },
    practice: {
      themeJa: 'よいことが続いた時期', starterJa: '最近いいことは続きましたか？',
      starterZh: '最近有好事接连发生吗？', targetUse: '〜ずくめ',
    },
    matchKeys: ['ずくめ'],
    vocabularyLinks: [],
  }),
];
