// N1文法 Unit 3（15項目 / 時・タイミング・同時進行）。
// 例文・訳・解説はすべて自社で書き起こす。
import { n1g, type N1GrammarDraft } from './n1GrammarDrafts';

export const N1_GRAMMAR_DRAFTS_UNIT3: N1GrammarDraft[] = [
  n1g({
    grammarId: 'n1g-031', pattern: '〜が早いか', reading: 'がはやいか', unit: 3,
    meaningJa: '〜すると、すぐに',
    explanationZh: '刚一…就…。强调两个动作几乎同时',
    formation: '動詞辞書形＋が早いか',
    usageScene: '描写反应极快的动作',
    nuance: '後ろは過去の事実。自分の意志や予定には使わない',
    register: 'written',
    examplesJa: ['ベルが鳴るが早いか、教室を飛び出しました。', '席に着くが早いか、眠ってしまいました。'],
    examplesZh: ['铃刚一响就冲出了教室。', '刚一坐下就睡着了。'],
    furigana: 'ベルが なるが はやいか、きょうしつを とびだしました。',
    commonMistakesZh: '后面不能接意志、命令、请求。「が早いか行きましょう」不成立',
    learnerFocus: '「が早いか・や否や・なり」都是「刚…就…」。共同点是后面必须是过去的事实',
    similarPatterns: ['〜や否や', '〜なり'],
    contrast: '「が早いか」＝勢いのある反応；「や否や」＝書き言葉で中立；「なり」＝意外な行動が続く',
    recognition: {
      promptZh: '哪个句子用「が早いか」自然？',
      options: ['家に着くが早いか寝てしまった', '家に着くが早いか寝ましょう', '家に着くが早いか寝てください', '家に着くが早いか寝たい'],
      answerIndex: 0,
      distractorReason: '「が早いか」の後ろは起きた事実。意志・依頼・希望は置けない',
      distractorReasonZh: '「が早いか」后面接已发生的事实，不能放意志、请求、愿望',
      explanationZh: '「〜が早いか」＝刚一…就…',
    },
    production: {
      promptJa: 'すぐに行動した経験を「〜が早いか」で言ってください。',
      promptZh: '用「〜が早いか」说一次立刻行动的经历。',
      expected: ['が早いか'], acceptable: [],
    },
    practice: {
      themeJa: 'すぐに動いた話', starterJa: '合図と同時に動いた経験はありますか？',
      starterZh: '有过信号一响就立刻行动的经历吗？', targetUse: '〜が早いか',
    },
    matchKeys: ['が早いか'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-032', pattern: '〜や否や', reading: 'やいなや', unit: 3,
    meaningJa: '〜するとすぐに',
    explanationZh: '一…就…。书面语，多用于报道',
    formation: '動詞辞書形＋や否や',
    usageScene: '新闻中描写事件的连续发生',
    nuance: '「が早いか」より硬く、客観的な記述に使う',
    register: 'written',
    examplesJa: ['発表があるや否や、問い合わせが殺到しました。', '扉が開くや否や、人が流れ込みました。'],
    examplesZh: ['一发布，咨询就蜂拥而至。', '门一打开，人就涌了进来。'],
    furigana: 'はっぴょうが あるや いなや、といあわせが さっとう しました。',
    commonMistakesZh: '同样不能接意志和请求。后面是已经发生的事',
    learnerFocus: '「や否や」也可写成「や」。阅读时看到「〜や、…」要想到这个用法',
    similarPatterns: ['〜が早いか', '〜とたんに'],
    contrast: '「や否や」＝硬い書き言葉；「とたんに」＝話し言葉でも使え、意外性を含む',
    recognition: {
      promptZh: '「開くや否や」是什么意思？',
      options: ['一打开就…', '打开之前', '虽然打开了', '为了打开'],
      answerIndex: 0,
      distractorReason: '「や否や」は直後を表す。前後関係を逆にしない',
      distractorReasonZh: '「や否や」表示紧接其后，不要弄反前后顺序',
      explanationZh: '「〜や否や」＝一…就…',
    },
    production: {
      promptJa: '出来事が続けて起きた話を「〜や否や」で言ってください。',
      promptZh: '用「〜や否や」说一件接连发生的事。',
      expected: ['や否や'], acceptable: [],
    },
    practice: {
      themeJa: '続けて起きた出来事', starterJa: '何かの直後に別のことが起きた経験は？',
      starterZh: '有过某事之后紧接着发生别的事的经历吗？', targetUse: '〜や否や',
    },
    matchKeys: ['や否や'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-033', pattern: '〜なり', reading: 'なり', unit: 3,
    meaningJa: '〜すると、すぐに（意外な行動が続く）',
    explanationZh: '一…就…（做出意外的举动）',
    formation: '動詞辞書形＋なり',
    usageScene: '描写别人出人意料的举动',
    nuance: '主語は自分以外。後ろは驚くような行動',
    register: 'written',
    examplesJa: ['彼は席に着くなり、大きなため息をつきました。', '母は帰ってくるなり、荷物を片づけ始めました。'],
    examplesZh: ['他一坐下就长长地叹了口气。', '母亲一回来就开始收拾行李。'],
    furigana: 'かれは せきに つく なり、おおきな ためいきを つきました。',
    commonMistakesZh: '不用于自己的行为。也不能接意志形',
    learnerFocus: '「なり」有多种用法。这里是「刚…就…」，注意与「〜なりに（以…的方式）」区分',
    similarPatterns: ['〜が早いか', '〜や否や'],
    contrast: '「なり」＝他人の意外な行動；「が早いか」＝反応の速さそのもの',
    recognition: {
      promptZh: '哪个句子用「なり」（刚…就…）自然？',
      options: ['彼は入るなり座り込んだ', '私は入るなり座りたい', '入るなり座ってください', '入るなり座るつもりだ'],
      answerIndex: 0,
      distractorReason: '「なり」は自分以外の意外な行動。意志・依頼は置けない',
      distractorReasonZh: '「なり」用于他人出乎意料的举动，不能放意志或请求',
      explanationZh: '「〜なり」＝一…就…（做出意外的举动）',
    },
    production: {
      promptJa: '誰かの意外な行動を「〜なり」で言ってください。',
      promptZh: '用「〜なり」描写别人出乎意料的举动。',
      expected: ['なり'], acceptable: [],
    },
    practice: {
      themeJa: '意外な行動を見た話', starterJa: '人の意外な行動に驚いたことはありますか？',
      starterZh: '有过被别人的意外举动惊到吗？', targetUse: '〜なり',
    },
    matchKeys: ['なり'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-034', pattern: '〜そばから', reading: 'そばから', unit: 3,
    meaningJa: '〜しても、すぐにまた（元に戻る）',
    explanationZh: '刚…就又…。表示同样的事反复发生，带无奈语气',
    formation: '動詞辞書形／た形＋そばから',
    usageScene: '抱怨努力白费、反复徒劳',
    nuance: '繰り返し起きることに使う。一回だけの出来事には使わない',
    register: 'spoken',
    examplesJa: ['片づけるそばから、子どもが散らかします。', '覚えるそばから忘れてしまいます。'],
    examplesZh: ['刚收拾好，孩子就又弄乱。', '刚记住就又忘了。'],
    furigana: 'かたづける そばから、こどもが ちらかします。',
    commonMistakesZh: '不用于一次性的事件。必须是反复发生的情况',
    learnerFocus: '「が早いか」是一次的快，「そばから」是反复的徒劳。两者容易混',
    similarPatterns: ['〜たとたんに', '〜ては〜'],
    contrast: '「そばから」＝繰り返してむだになる；「たとたんに」＝一度きりの直後',
    recognition: {
      promptZh: '哪个句子用「そばから」自然？',
      options: ['覚えるそばから忘れる', '駅に着くそばから電話が鳴った', '卒業するそばから就職した', '起きるそばから出発した'],
      answerIndex: 0,
      distractorReason: '「そばから」は同じことが何度も繰り返される場合に使う',
      distractorReasonZh: '「そばから」用于同样的事反复发生的情况',
      explanationZh: '「〜そばから」＝刚…就又…（反复徒劳）',
    },
    production: {
      promptJa: '繰り返しむだになることを「〜そばから」で言ってください。',
      promptZh: '用「〜そばから」说一件反复白费的事。',
      expected: ['そばから'], acceptable: [],
    },
    practice: {
      themeJa: 'きりがないことの話', starterJa: 'やってもやってもきりがないことはありますか？',
      starterZh: '有什么事是做了又做也没完没了的？', targetUse: '〜そばから',
    },
    matchKeys: ['そばから'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-035', pattern: '〜つ〜つ', reading: 'つつ', unit: 3,
    meaningJa: '〜たり〜たり（二つの動作が交互に）',
    explanationZh: '时而…时而…。用固定的成对动词',
    formation: '動詞ます形＋つ＋（対になる）動詞ます形＋つ',
    usageScene: '描写来回、交替的样子',
    nuance: '「行きつ戻りつ」「押しつ押されつ」など、決まった組み合わせで使う',
    register: 'written',
    examplesJa: ['駅の前を行きつ戻りつして待ちました。', '二人は抜きつ抜かれつの接戦でした。'],
    examplesZh: ['在车站前来回踱步等待。', '两人是你追我赶的拉锯战。'],
    furigana: 'えきの まえを いきつ もどりつ して まちました。',
    commonMistakesZh: '不能自由组合动词。基本上是固定搭配',
    learnerFocus: '记住三个固定搭配就够：行きつ戻りつ・抜きつ抜かれつ・持ちつ持たれつ',
    similarPatterns: ['〜たり〜たり', '〜ながら'],
    contrast: '「つ〜つ」＝文語の固定表現；「たり〜たり」＝自由に作れる標準形',
    recognition: {
      promptZh: '「行きつ戻りつ」是什么意思？',
      options: ['来回走动', '去了就没回来', '一起去', '走得很快'],
      answerIndex: 0,
      distractorReason: '「つ〜つ」は二つの動作が交互に繰り返される様子',
      distractorReasonZh: '「つ〜つ」表示两个动作交替反复',
      explanationZh: '「〜つ〜つ」＝时而…时而…（来回）',
    },
    production: {
      promptJa: '迷って行ったり来たりした話を「行きつ戻りつ」で言ってください。',
      promptZh: '用「行きつ戻りつ」说一次犹豫着来回走的经历。',
      expected: ['つ'], acceptable: ['行きつ戻りつ'],
    },
    practice: {
      themeJa: '迷ったときの様子', starterJa: '入るかどうか迷って店の前を歩いたことは？',
      starterZh: '有过在店前犹豫要不要进去的经历吗？', targetUse: '〜つ〜つ',
    },
    matchKeys: ['つ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-036', pattern: '〜を皮切りに', reading: 'をかわきりに', unit: 3,
    meaningJa: '〜を始まりとして、次々と',
    explanationZh: '以…为开端，接连…',
    formation: '名詞＋を皮切りに（して）',
    usageScene: '报道中说明一系列活动的起点',
    nuance: '後ろは広がっていく展開。よい話に使うことが多い',
    register: 'written',
    examplesJa: ['東京公演を皮切りに、全国を回ります。', '一件の投稿を皮切りに、話題が広がりました。'],
    examplesZh: ['以东京公演为开端，将巡回全国。', '以一条投稿为开端，话题扩散开来。'],
    furigana: 'とうきょう こうえんを かわきりに、ぜんこくを まわります。',
    commonMistakesZh: '后面必须有「接连发生」的展开，只有一件事时不能用',
    learnerFocus: '「皮切り」＝第一步。看到就理解为「从…开始，一连串」',
    similarPatterns: ['〜を機に', '〜をはじめとして'],
    contrast: '「を皮切りに」＝次々に続く起点；「を機に」＝それをきっかけに変わる',
    recognition: {
      promptZh: '哪个句子用「を皮切りに」自然？',
      options: ['大阪を皮切りに全国で開催する', '大阪を皮切りに一度だけ行う', '大阪を皮切りに中止した', '大阪を皮切りに終わった'],
      answerIndex: 0,
      distractorReason: '「を皮切りに」は後ろに次々と続く展開が要る',
      distractorReasonZh: '「を皮切りに」后面需要接连不断的展开',
      explanationZh: '「〜を皮切りに」＝以…为开端，接连…',
    },
    production: {
      promptJa: '何かの始まりを「〜を皮切りに」で言ってください。',
      promptZh: '用「〜を皮切りに」说一个开端。',
      expected: ['を皮切りに'], acceptable: [],
    },
    practice: {
      themeJa: '広がっていった出来事', starterJa: '小さなことから広がった経験はありますか？',
      starterZh: '有过从小事扩散开来的经历吗？', targetUse: '〜を皮切りに',
    },
    matchKeys: ['皮切り'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-037', pattern: '〜を境に', reading: 'をさかいに', unit: 3,
    meaningJa: '〜を区切りとして、変わる',
    explanationZh: '以…为界（分界点），发生变化',
    formation: '名詞＋を境に（して）',
    usageScene: '说明某个时点前后的明显变化',
    nuance: '前と後ではっきり違うことを述べる',
    register: 'written',
    examplesJa: ['引っ越しを境に、生活が大きく変わりました。', '午後を境に雨が強くなりました。'],
    examplesZh: ['以搬家为界，生活发生了很大变化。', '以下午为界，雨变大了。'],
    furigana: 'ひっこしを さかいに、せいかつが おおきく かわりました。',
    commonMistakesZh: '后面必须有变化。只是「开始了」时用「を皮切りに」',
    learnerFocus: '「を境に」＝前后有变化／「を皮切りに」＝之后接连不断',
    similarPatterns: ['〜を機に', '〜以降'],
    contrast: '「を境に」＝前後の違いを強調；「を機に」＝きっかけとして新しく始める',
    recognition: {
      promptZh: '「引っ越しを境に」是什么意思？',
      options: ['以搬家为界（前后不同）', '为了搬家', '搬家之前', '一边搬家'],
      answerIndex: 0,
      distractorReason: '「を境に」はその時点の前後で状態が変わることを表す',
      distractorReasonZh: '「を境に」表示以该时点为界前后状态改变',
      explanationZh: '「〜を境に」＝以…为界，发生变化',
    },
    production: {
      promptJa: '生活が変わった時点を「〜を境に」で言ってください。',
      promptZh: '用「〜を境に」说一个生活改变的时点。',
      expected: ['を境に'], acceptable: [],
    },
    practice: {
      themeJa: '生活が変わった時', starterJa: 'あなたの生活が変わったきっかけは何ですか？',
      starterZh: '你生活改变的契机是什么？', targetUse: '〜を境に',
    },
    matchKeys: ['を境に'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-038', pattern: '〜てからというもの', reading: 'てからというもの', unit: 3,
    meaningJa: '〜てから、ずっと（状態が続いている）',
    explanationZh: '自从…以来，一直…。强调持续的变化',
    formation: '動詞て形＋からというもの',
    usageScene: '回顾某件事之后生活的持续变化',
    nuance: '一時的な変化ではなく、続いている状態に使う',
    register: 'written',
    examplesJa: ['日本に来てからというもの、毎日が発見の連続です。', '運動を始めてからというもの、よく眠れます。'],
    examplesZh: ['自从来到日本，每天都是接连不断的发现。', '自从开始运动，睡得很好。'],
    furigana: 'にほんに きて からと いう もの、まいにちが はっけんの れんぞくです。',
    commonMistakesZh: '不用于短暂的事。「昨日食べてからというもの」不自然',
    learnerFocus: '比「〜てから」更强调「一直持续到现在」的感受',
    similarPatterns: ['〜て以来', '〜てから'],
    contrast: '「てからというもの」＝気持ちを込めて長く続く変化；「て以来」＝客観的に時点を示す',
    recognition: {
      promptZh: '哪个句子用「てからというもの」自然？',
      options: ['引っ越してからというもの外食が減った', '昨日食べてからというもの眠い', '今朝起きてからというもの顔を洗った', '一度行ってからというもの行かない'],
      answerIndex: 0,
      distractorReason: '長く続いている変化に使う。短時間の出来事には合わない',
      distractorReasonZh: '用于长期持续的变化，不适合短时间的事',
      explanationZh: '「〜てからというもの」＝自从…以来一直…',
    },
    production: {
      promptJa: '生活が続けて変わったことを「〜てからというもの」で言ってください。',
      promptZh: '用「〜てからというもの」说一个持续至今的变化。',
      expected: ['てからというもの'], acceptable: [],
    },
    practice: {
      themeJa: '続いている変化', starterJa: '日本に来てから続いている変化はありますか？',
      starterZh: '来日本后有什么变化一直持续着？', targetUse: '〜てからというもの',
    },
    matchKeys: ['てからというもの'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-039', pattern: '〜がてら', reading: 'がてら', unit: 3,
    meaningJa: '〜のついでに',
    explanationZh: '顺便…。一次外出做两件事',
    formation: '名詞／動詞ます形＋がてら',
    usageScene: '说明外出时顺带办的事',
    nuance: '移動を伴う場面に多い。主な目的は前でも後ろでもよい',
    register: 'spoken',
    examplesJa: ['散歩がてら、郵便局に寄りました。', '買い物がてら、公園を歩きました。'],
    examplesZh: ['散步顺便去了趟邮局。', '购物顺便在公园走了走。'],
    furigana: 'さんぽ がてら、ゆうびんきょくに よりました。',
    commonMistakesZh: '一般用于伴随移动的场面。坐着做的两件事不太用',
    learnerFocus: '「がてら・かたがた・かたわら」是N1常考的三个。先按场面记',
    similarPatterns: ['〜ついでに', '〜かたがた'],
    contrast: '「がてら」＝日常の外出のついで；「かたがた」＝あいさつなど改まった用事',
    recognition: {
      promptZh: '哪个句子用「がてら」自然？',
      options: ['散歩がてら買い物をした', '仕事がてら会社を辞めた', '寝がてら夢を見た', '食べがてら太った'],
      answerIndex: 0,
      distractorReason: '「がてら」は外出のついでに別の用事をする場面に使う',
      distractorReasonZh: '「がてら」用于外出时顺便办别的事',
      explanationZh: '「〜がてら」＝顺便…',
    },
    production: {
      promptJa: 'ついでにしたことを「〜がてら」で言ってください。',
      promptZh: '用「〜がてら」说一件顺便做的事。',
      expected: ['がてら'], acceptable: [],
    },
    practice: {
      themeJa: '外出のついで', starterJa: '出かけたついでに何かしますか？',
      starterZh: '出门时会顺便做点什么吗？', targetUse: '〜がてら',
    },
    matchKeys: ['がてら'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-040', pattern: '〜かたがた', reading: 'かたがた', unit: 3,
    meaningJa: '〜を兼ねて（あいさつなどの改まった用事）',
    explanationZh: '兼…；顺便…。用于正式的问候场合',
    formation: '名詞＋かたがた',
    usageScene: '书信、正式访问的说明',
    nuance: '「お礼かたがた」「ごあいさつかたがた」など、改まった場面に限る',
    register: 'written',
    examplesJa: ['お礼かたがた、ご報告に伺いました。', 'ごあいさつかたがた、資料をお届けします。'],
    examplesZh: ['特来道谢并顺致报告。', '在问候的同时送上资料。'],
    furigana: 'おれい かたがた、ごほうこくに うかがいました。',
    commonMistakesZh: '只接名词，而且是正式的用事。日常琐事用「がてら」',
    learnerFocus: '几乎只在商务书信中出现。看到就理解为「兼…」',
    similarPatterns: ['〜がてら', '〜を兼ねて'],
    contrast: '「かたがた」＝改まった用事（書き言葉）；「がてら」＝日常のついで',
    recognition: {
      promptZh: '哪个句子用「かたがた」自然？',
      options: ['お礼かたがたご報告します', '散歩かたがた走った', '寝るかたがた休んだ', '食事かたがた太った'],
      answerIndex: 0,
      distractorReason: '「かたがた」はあいさつ・お礼など改まった用事に付く',
      distractorReasonZh: '「かたがた」接问候、道谢等正式用事',
      explanationZh: '「〜かたがた」＝兼…（正式场合）',
    },
    production: {
      promptJa: 'あいさつを兼ねた用事を「〜かたがた」で言ってください。',
      promptZh: '用「〜かたがた」说一件兼问候的事。',
      expected: ['かたがた'], acceptable: [],
    },
    practice: {
      themeJa: 'あらたまった訪問', starterJa: 'お礼を伝えに行ったことはありますか？',
      starterZh: '有过专程去道谢的经历吗？', targetUse: '〜かたがた',
    },
    matchKeys: ['かたがた'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-041', pattern: '〜かたわら', reading: 'かたわら', unit: 3,
    meaningJa: '主に〜をしながら、他のこともしている',
    explanationZh: '一边…一边…（长期并行的两件事）',
    formation: '名詞＋の／動詞辞書形＋かたわら',
    usageScene: '介绍某人本业之外还长期从事的活动',
    nuance: '長い期間続けている二つの活動に使う。今この瞬間の同時進行ではない',
    register: 'written',
    examplesJa: ['仕事のかたわら、地域の子どもに日本語を教えています。', '大学に通うかたわら、店を手伝っています。'],
    examplesZh: ['工作之余，还在教社区的孩子日语。', '上大学的同时，还在店里帮忙。'],
    furigana: 'しごとの かたわら、ちいきの こどもに にほんごを おしえて います。',
    commonMistakesZh: '不是「一边走一边吃」那种瞬间的同时。那要用「ながら」',
    learnerFocus: '「かたわら」＝长期的两件事；「ながら」＝当下的同时动作',
    similarPatterns: ['〜ながら', '〜一方で'],
    contrast: '「かたわら」＝長期の並行；「ながら」＝同じ時間の動作の重なり',
    recognition: {
      promptZh: '哪个句子用「かたわら」自然？',
      options: ['仕事のかたわら小説を書いている', '歩くかたわら食べた', '寝るかたわら起きた', '走るかたわら転んだ'],
      answerIndex: 0,
      distractorReason: '「かたわら」は長く続けている二つの活動に使う',
      distractorReasonZh: '「かたわら」用于长期并行的两项活动',
      explanationZh: '「〜かたわら」＝在做…的同时（长期）还做…',
    },
    production: {
      promptJa: '本業のほかに続けていることを「〜かたわら」で言ってください。',
      promptZh: '用「〜かたわら」说说本职之外长期做的事。',
      expected: ['かたわら'], acceptable: [],
    },
    practice: {
      themeJa: '仕事以外に続けていること', starterJa: '仕事のほかに続けていることはありますか？',
      starterZh: '工作之外你还长期做什么？', targetUse: '〜かたわら',
    },
    matchKeys: ['かたわら'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-042', pattern: '〜ながらに', reading: 'ながらに', unit: 3,
    meaningJa: '〜のままの状態で',
    explanationZh: '保持…的状态。多用于固定搭配',
    formation: '名詞／動詞ます形＋ながらに（して）',
    usageScene: '书面描写「保持原样地」',
    nuance: '「生まれながらに」「涙ながらに」「居ながらにして」が代表',
    register: 'written',
    examplesJa: ['涙ながらに当時のことを話してくれました。', '家に居ながらにして手続きができます。'],
    examplesZh: ['含着泪讲述了当时的事。', '足不出户就能办手续。'],
    furigana: 'なみだ ながらに とうじの ことを はなして くれました。',
    commonMistakesZh: '与表示逆接的「〜ながら（も）」不同。这里是「保持…的状态」',
    learnerFocus: '三个固定搭配背下来：生まれながらに・涙ながらに・居ながらにして',
    similarPatterns: ['〜のまま', '〜ながらも'],
    contrast: '「ながらに」＝状態のまま；「ながらも」＝逆接（〜のに）',
    recognition: {
      promptZh: '「涙ながらに」是什么意思？',
      options: ['含着泪地', '虽然流泪但', '为了流泪', '流泪之后'],
      answerIndex: 0,
      distractorReason: '「ながらに」は状態を保ったままの意味。逆接ではない',
      distractorReasonZh: '「ながらに」表示保持某状态，不是逆接',
      explanationZh: '「〜ながらに」＝保持…的状态',
    },
    production: {
      promptJa: '「家にいるまま何かができる」を「居ながらにして」で言ってください。',
      promptZh: '用「居ながらにして」说「待在家里就能做…」。',
      expected: ['ながらに'], acceptable: ['ながらにして'],
    },
    practice: {
      themeJa: '家にいながらできること', starterJa: '家にいたままできるようになったことは？',
      starterZh: '有什么变成待在家里就能做了？', targetUse: '〜ながらに',
    },
    matchKeys: ['ながらに'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-043', pattern: '〜矢先に', reading: 'やさきに', unit: 3,
    meaningJa: 'ちょうど〜しようとしたとき（に）',
    explanationZh: '正要…的时候（发生了别的事）',
    formation: '動詞た形＋矢先に',
    usageScene: '说明计划刚要开始就被打断',
    nuance: '後ろは予定を邪魔する出来事が来る',
    register: 'written',
    examplesJa: ['出かけようとした矢先に、電話が鳴りました。', '始めようと思った矢先に、体調を崩しました。'],
    examplesZh: ['正要出门的时候，电话响了。', '正想开始的时候，身体不适了。'],
    furigana: 'でかけようと した やさきに、でんわが なりました。',
    commonMistakesZh: '前面用「〜（よ）うとした矢先に」的形式，后面接意外的事',
    learnerFocus: '几乎固定为「〜ようとした矢先に」。整体记住最快',
    similarPatterns: ['〜ところに', '〜とたんに'],
    contrast: '「矢先に」＝これからという時に邪魔が入る；「とたんに」＝ある動作の直後',
    recognition: {
      promptZh: '「出かけようとした矢先に」是什么意思？',
      options: ['正要出门的时候', '出门之后', '为了出门', '不想出门'],
      answerIndex: 0,
      distractorReason: '「矢先に」は「ちょうどしようとしたとき」を表す',
      distractorReasonZh: '「矢先に」表示「正要做的时候」',
      explanationZh: '「〜矢先に」＝正要…的时候',
    },
    production: {
      promptJa: '予定が邪魔された話を「〜矢先に」で言ってください。',
      promptZh: '用「〜矢先に」说一次计划被打断的经历。',
      expected: ['矢先'], acceptable: ['矢先に'],
    },
    practice: {
      themeJa: '予定が狂った話', starterJa: '始めようとした時に邪魔が入ったことは？',
      starterZh: '有过正要开始却被打断的经历吗？', targetUse: '〜矢先に',
    },
    matchKeys: ['矢先'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-044', pattern: '〜間際に', reading: 'まぎわに', unit: 3,
    meaningJa: 'ちょうど〜する直前に',
    explanationZh: '就在快要…之前',
    formation: '名詞／動詞辞書形＋間際に',
    usageScene: '说明在截止或出发的最后关头发生的事',
    nuance: '時間的にぎりぎりであることを強調する',
    register: 'spoken',
    examplesJa: ['出発間際に忘れ物に気づきました。', '閉店間際に駆け込みました。'],
    examplesZh: ['就在出发前发现落了东西。', '在快打烊时冲了进去。'],
    furigana: 'しゅっぱつ まぎわに わすれものに きづきました。',
    commonMistakesZh: '「間際」是紧接着之前，不是之后',
    learnerFocus: '「矢先」是「正要…时」，「間際」是「就在…之前」。都强调时间紧',
    similarPatterns: ['〜直前に', '〜寸前で'],
    contrast: '「間際に」＝時間のぎりぎり前；「矢先に」＝始めようとした瞬間に邪魔が入る',
    recognition: {
      promptZh: '「閉店間際」是什么意思？',
      options: ['快要关门的时候', '关门之后', '开门的时候', '关门那天'],
      answerIndex: 0,
      distractorReason: '「間際」は直前を表す',
      distractorReasonZh: '「間際」表示紧接之前',
      explanationZh: '「〜間際に」＝就在快要…之前',
    },
    production: {
      promptJa: 'ぎりぎりの出来事を「〜間際に」で言ってください。',
      promptZh: '用「〜間際に」说一件卡在最后关头的事。',
      expected: ['間際'], acceptable: ['間際に'],
    },
    practice: {
      themeJa: 'ぎりぎりだった話', starterJa: '時間ぎりぎりで間に合ったことはありますか？',
      starterZh: '有过卡着点赶上的经历吗？', targetUse: '〜間際に',
    },
    matchKeys: ['間際'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-045', pattern: '〜きり（で）', reading: 'きり', unit: 3,
    meaningJa: '〜したまま、その後変化がない',
    explanationZh: '…之后就一直没有…。表示状态没有改变',
    formation: '動詞た形＋きり（＋否定）',
    usageScene: '说明某事之后再没有下文',
    nuance: '後ろは打ち消しか、変化のない状態',
    register: 'spoken',
    examplesJa: ['去年会ったきり、連絡していません。', '朝出かけたきり、帰ってきません。'],
    examplesZh: ['去年见过之后就再没联系。', '早上出门之后就没回来。'],
    furigana: 'きょねん あった きり、れんらく して いません。',
    commonMistakesZh: '与表示「只有」的「〜きり」（二人きり）不同，注意区分',
    learnerFocus: '「たきり〜ない」是固定搭配。后面基本是否定',
    similarPatterns: ['〜まま', '〜以来'],
    contrast: '「たきり」＝その後の変化が無い；「まま」＝状態がそのまま続く（否定でなくてもよい）',
    recognition: {
      promptZh: '「会ったきり連絡していない」是什么意思？',
      options: ['见过之后就没再联系', '见面时联系了', '见面前联系了', '一直在联系'],
      answerIndex: 0,
      distractorReason: '「たきり」は「その後は〜ない」を表す',
      distractorReasonZh: '「たきり」表示「之后就没有…」',
      explanationZh: '「〜たきり」＝…之后就一直没有…',
    },
    production: {
      promptJa: 'その後会っていない人を「〜たきり」で言ってください。',
      promptZh: '用「〜たきり」说一个之后再没见过的人。',
      expected: ['きり'], acceptable: ['たきり'],
    },
    practice: {
      themeJa: 'その後の連絡', starterJa: '長く連絡していない人はいますか？',
      starterZh: '有很久没联系的人吗？', targetUse: '〜たきり',
    },
    matchKeys: ['きり'], vocabularyLinks: [],
  }),
];
