// N1文法 Unit 9（15項目 / 様態・程度・比喩）。
// 例文・訳・解説はすべて自社で書き起こす。
import { n1g, type N1GrammarDraft } from './n1GrammarDrafts';

export const N1_GRAMMAR_DRAFTS_UNIT9: N1GrammarDraft[] = [
  n1g({
    grammarId: 'n1g-121', pattern: '〜んばかりに', reading: 'んばかりに', unit: 9,
    meaningJa: '今にも〜しそうなほど',
    explanationZh: '几乎要…似的。描写夸张的样子',
    formation: '動詞ない形（ない→ん）＋ばかりに',
    usageScene: '文学性地描写表情或场面',
    nuance: '実際にはそうなっていないが、そう見えるほど強い',
    register: 'written',
    examplesJa: ['泣き出さんばかりの顔をしていました。', '会場は割れんばかりの拍手に包まれました。'],
    examplesZh: ['当时一副几乎要哭出来的表情。', '会场被几乎要震裂似的掌声包围。'],
    furigana: 'なきださんばかりの かおを して いました。',
    commonMistakesZh: '「する」变成「せんばかり」。另外不要与「〜ばかりに（因为）」混同',
    learnerFocus: '「割れんばかりの拍手」是固定搭配，先记这个',
    similarPatterns: ['〜そうな', '〜と言わんばかりに'],
    contrast: '「んばかりに」＝今にもそうなりそうな様子；「ばかりに」＝そのせいで（原因）',
    recognition: {
      promptZh: '「泣き出さんばかりの顔」是什么意思？',
      options: ['几乎要哭出来的表情', '已经哭了的脸', '不想哭的表情', '哭完之后的脸'],
      answerIndex: 0,
      distractorReason: '「んばかり」は実際にはしていないが、そう見えるほどの様子',
      distractorReasonZh: '「んばかり」表示实际没有，但看起来快要如此',
      explanationZh: '「〜んばかりに」＝几乎要…似的',
    },
    production: {
      promptJa: '今にもそうなりそうな様子を「〜んばかりに」で言ってください。',
      promptZh: '用「〜んばかりに」描写快要发生的样子。',
      expected: ['んばかり'], acceptable: ['んばかりに'],
    },
    practice: {
      themeJa: '表情や場面の描写', starterJa: '印象に残っている人の表情はありますか？',
      starterZh: '有让你印象深刻的表情吗？', targetUse: '〜んばかりに',
    },
    matchKeys: ['んばかり'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-122', pattern: '〜ともなく／〜ともなしに', reading: 'ともなく', unit: 9,
    meaningJa: 'はっきりした意図なく〜する',
    explanationZh: '无意中…；漫不经心地…',
    formation: '動詞辞書形＋ともなく／ともなしに',
    usageScene: '描写不经意的动作',
    nuance: '同じ動詞を繰り返す形が多い（見るともなく見る）',
    register: 'written',
    examplesJa: ['見るともなくテレビを見ていました。', '聞くともなしに聞いた話が役に立ちました。'],
    examplesZh: ['漫不经心地看着电视。', '无意中听到的话派上了用场。'],
    furigana: 'みる ともなく テレビを みて いました。',
    commonMistakesZh: '不是否定。是「没有明确意图地做」',
    learnerFocus: '「見るともなく見る」「聞くともなしに聞く」两句整体记住',
    similarPatterns: ['〜なんとなく', '〜ながら'],
    contrast: '「ともなく」＝意図せずに；「ながら」＝二つの動作の同時進行',
    recognition: {
      promptZh: '「見るともなく見ていた」是什么意思？',
      options: ['漫不经心地看着', '完全没看', '认真地看', '想看却没看'],
      answerIndex: 0,
      distractorReason: '「ともなく」は意図せずにという意味で、否定ではない',
      distractorReasonZh: '「ともなく」表示无意中，并非否定',
      explanationZh: '「〜ともなく」＝无意中…',
    },
    production: {
      promptJa: '何気ない行動を「〜ともなく」で言ってください。',
      promptZh: '用「〜ともなく」描写一个不经意的动作。',
      expected: ['ともなく'], acceptable: ['ともなしに'],
    },
    practice: {
      themeJa: '何気ない時間', starterJa: '休みの日は何をして過ごしますか？',
      starterZh: '休息日你怎么过？', targetUse: '〜ともなく',
    },
    matchKeys: ['ともなく', 'ともなしに'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-123', pattern: '〜ないまでも', reading: 'ないまでも', unit: 9,
    meaningJa: '〜まではしなくても、せめて',
    explanationZh: '即使做不到…，至少也…',
    formation: '動詞ない形＋までも',
    usageScene: '提出退一步的最低要求',
    nuance: '後ろは「せめて〜くらいは」という内容',
    register: 'written',
    examplesJa: ['毎日とは言わないまでも、週に一度は運動したいです。', '全部覚えないまでも、要点は押さえましょう。'],
    examplesZh: ['即使做不到每天，也想一周运动一次。', '即使记不住全部，也要抓住要点。'],
    furigana: 'まいにちとは いわない までも、しゅうに いちどは うんどう したいです。',
    commonMistakesZh: '前面是较高的要求，后面是较低的底线。顺序不能反',
    learnerFocus: '常与「せめて」一起出现。是主张时的缓和说法',
    similarPatterns: ['〜とまではいかないが', '〜せめて'],
    contrast: '「ないまでも」＝高い方を諦めて低い方を求める；「までもない」＝そもそも不要',
    recognition: {
      promptZh: '「毎日とは言わないまでも」后面最可能接什么？',
      options: ['週に一度はしたい', '毎日必ずする', '一度もしない', 'したくない'],
      answerIndex: 0,
      distractorReason: '「ないまでも」の後ろは一段低い最低ラインが来る',
      distractorReasonZh: '「ないまでも」后面接退一步的最低要求',
      explanationZh: '「〜ないまでも」＝即使做不到…，至少也…',
    },
    production: {
      promptJa: 'せめてこれだけは、という希望を「〜ないまでも」で言ってください。',
      promptZh: '用「〜ないまでも」说出至少想做到的底线。',
      expected: ['ないまでも'], acceptable: [],
    },
    practice: {
      themeJa: '最低限の目標', starterJa: '毎日は無理でも続けたいことはありますか？',
      starterZh: '有什么虽做不到每天但想坚持的事？', targetUse: '〜ないまでも',
    },
    matchKeys: ['ないまでも'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-124', pattern: '〜ないとも限らない', reading: 'ないともかぎらない', unit: 9,
    meaningJa: '〜する可能性がないわけではない',
    explanationZh: '也未必不…；也有可能…。用于提醒防备',
    formation: '動詞ない形＋とも限らない',
    usageScene: '提醒万一的可能性',
    nuance: '二重否定で「可能性はある」と言う遠回しな表現',
    register: 'written',
    examplesJa: ['雨が降らないとも限らないので、傘を持ちます。', '間違いがないとも限りません。'],
    examplesZh: ['也未必不下雨，所以带伞。', '也未必没有错误。'],
    furigana: 'あめが ふらないとも かぎらないので、かさを もちます。',
    commonMistakesZh: '是双重否定＝有可能。不要理解成「不会…」',
    learnerFocus: '看到「ないとも限らない」先换成「かもしれない」理解',
    similarPatterns: ['〜かもしれない', '〜おそれがある'],
    contrast: '「ないとも限らない」＝遠回しに可能性を示す；「かもしれない」＝直接的な推測',
    recognition: {
      promptZh: '「降らないとも限らない」是什么意思？',
      options: ['也未必不下（有可能下）', '一定不下', '一定会下', '已经下了'],
      answerIndex: 0,
      distractorReason: '二重否定なので「可能性がある」という意味になる',
      distractorReasonZh: '双重否定，意为「有可能」',
      explanationZh: '「〜ないとも限らない」＝也未必不…',
    },
    production: {
      promptJa: '備えたほうがいいことを「〜ないとも限らない」で言ってください。',
      promptZh: '用「〜ないとも限らない」说一件最好防备的事。',
      expected: ['とも限らない'], acceptable: ['ないとも限りません'],
    },
    practice: {
      themeJa: '万一への備え', starterJa: '万一に備えて用意しているものはありますか？',
      starterZh: '你有为万一而准备的东西吗？', targetUse: '〜ないとも限らない',
    },
    matchKeys: ['とも限ら'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-125', pattern: '〜かのようだ', reading: 'かのようだ', unit: 9,
    meaningJa: '実際は違うが、まるで〜のようだ',
    explanationZh: '仿佛…一样。强调与事实不同',
    formation: '動詞・形容詞の普通形＋かのようだ／かのように',
    usageScene: '文学性地作比喻',
    nuance: '「ようだ」より「実際は違う」という含みが強い',
    register: 'written',
    examplesJa: ['まるで昨日のことであるかのように話します。', '時間が止まったかのような静けさでした。'],
    examplesZh: ['说得仿佛就是昨天的事一样。', '是仿佛时间停止了般的寂静。'],
    furigana: 'まるで きのうの ことで あるかの ように はなします。',
    commonMistakesZh: '常与「まるで」搭配。「かのように」是副词形',
    learnerFocus: '「まるで〜かのようだ」整组记住。是比喻的高级说法',
    similarPatterns: ['〜ようだ', '〜みたいだ'],
    contrast: '「かのようだ」＝事実と違うことを強調；「ようだ」＝推測にも使える',
    recognition: {
      promptZh: '「時間が止まったかのような」是什么意思？',
      options: ['仿佛时间停止了一样', '时间真的停了', '时间没有停', '时间快到了'],
      answerIndex: 0,
      distractorReason: '「かのようだ」は事実ではないが、そう感じられることを表す',
      distractorReasonZh: '「かのようだ」表示并非事实，但感觉如此',
      explanationZh: '「〜かのようだ」＝仿佛…一样',
    },
    production: {
      promptJa: '印象的な場面を「まるで〜かのようだ」で描いてください。',
      promptZh: '用「まるで〜かのようだ」描写一个印象深刻的场面。',
      expected: ['かのよう'], acceptable: ['かのようだ'],
    },
    practice: {
      themeJa: '印象的な場面', starterJa: '忘れられない静かな場面はありますか？',
      starterZh: '有让你难忘的安静场面吗？', targetUse: '〜かのようだ',
    },
    matchKeys: ['かのよう'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-126', pattern: '〜めく', reading: 'めく', unit: 9,
    meaningJa: '〜らしい感じになる',
    explanationZh: '有…的气息；带…的意味',
    formation: '名詞＋めく（春めく・皮肉めく）',
    usageScene: '描写季节的气息或语气的色彩',
    nuance: '「春めく」「謎めく」など、付く名詞が限られる',
    register: 'written',
    examplesJa: ['日差しが春めいてきました。', '謎めいた言い方が気になりました。'],
    examplesZh: ['阳光有了春天的气息。', '谜一般的说法让人在意。'],
    furigana: 'ひざしが はるめいて きました。',
    commonMistakesZh: '不能自由组合。常见的是春めく・秋めく・謎めく・皮肉めく',
    learnerFocus: '「〜めいた＋名词」的形式在阅读里最常见',
    similarPatterns: ['〜らしい', '〜のような'],
    contrast: '「めく」＝雰囲気が帯びる（限られた語）；「らしい」＝広く使える',
    recognition: {
      promptZh: '「春めいてきた」是什么意思？',
      options: ['有了春天的气息', '春天结束了', '不像春天', '春天来过了'],
      answerIndex: 0,
      distractorReason: '「めく」はその感じを帯びるという意味',
      distractorReasonZh: '「めく」表示带上那种气息',
      explanationZh: '「〜めく」＝有…的气息',
    },
    production: {
      promptJa: '季節の変化を「〜めく」で言ってください。',
      promptZh: '用「〜めく」描写季节的变化。',
      expected: ['めく'], acceptable: ['めいて'],
    },
    practice: {
      themeJa: '季節の移り変わり', starterJa: '季節の変化をどこで感じますか？',
      starterZh: '你从哪里感受到季节变化？', targetUse: '〜めく',
    },
    matchKeys: ['めく', 'めいた', 'めいて'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-127', pattern: '〜がましい', reading: 'がましい', unit: 9,
    meaningJa: '〜のように見えて、好ましくない',
    explanationZh: '有点像…（令人不快）',
    formation: '名詞／動詞ます形＋がましい',
    usageScene: '委婉批评言行给人的印象',
    nuance: '「言い訳がましい」「押しつけがましい」など否定的な語と組む',
    register: 'written',
    examplesJa: ['言い訳がましく聞こえないよう気をつけます。', '押しつけがましい言い方は避けたいです。'],
    examplesZh: ['注意不让人听起来像在找借口。', '想避免强加于人的说法。'],
    furigana: 'いいわけ がましく きこえないよう きを つけます。',
    commonMistakesZh: '只与负面的词搭配。好的意思不能用',
    learnerFocus: '记住两个搭配：言い訳がましい・押しつけがましい',
    similarPatterns: ['〜っぽい', '〜じみた'],
    contrast: '「がましい」＝そう見えて不快；「っぽい」＝ただ似ている（中立）',
    recognition: {
      promptZh: '「言い訳がましい」是什么意思？',
      options: ['听起来像在找借口（令人不快）', '解释得很清楚', '没有借口', '想找借口'],
      answerIndex: 0,
      distractorReason: '「がましい」はよくない印象を与えるという意味',
      distractorReasonZh: '「がましい」表示给人不好的印象',
      explanationZh: '「〜がましい」＝有点像…（令人不快）',
    },
    production: {
      promptJa: '避けたい言い方を「〜がましい」で言ってください。',
      promptZh: '用「〜がましい」说一种想避免的说法。',
      expected: ['がましい'], acceptable: ['がましく'],
    },
    practice: {
      themeJa: '伝え方の工夫', starterJa: '説明するとき気をつけていることはありますか？',
      starterZh: '你说明时会注意什么？', targetUse: '〜がましい',
    },
    matchKeys: ['がましい', 'がましく'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-128', pattern: '〜じみた', reading: 'じみた', unit: 9,
    meaningJa: '〜のように見える（よくない意味で）',
    explanationZh: '带有…的味道（多为负面）',
    formation: '名詞＋じみた',
    usageScene: '批评行为幼稚或不合场合',
    nuance: '「子どもじみた」「芝居じみた」など否定的な評価',
    register: 'spoken',
    examplesJa: ['子どもじみた争いはやめましょう。', '芝居じみた話し方が気になりました。'],
    examplesZh: ['别再做孩子气的争执了。', '演戏似的说话方式让人在意。'],
    furigana: 'こども じみた あらそいは やめましょう。',
    commonMistakesZh: '不是「沾上」。这里是「像…似的（不好）」',
    learnerFocus: '「じみた」几乎都带批评。褒义时用「〜らしい」',
    similarPatterns: ['〜がましい', '〜っぽい'],
    contrast: '「じみた」＝そう見えて幼稚・不自然；「らしい」＝ふさわしいという肯定',
    recognition: {
      promptZh: '「子どもじみた」是什么意思？',
      options: ['孩子气的（负面）', '像孩子一样可爱', '孩子做的', '为了孩子'],
      answerIndex: 0,
      distractorReason: '「じみた」は否定的な評価を含む',
      distractorReasonZh: '「じみた」含有负面评价',
      explanationZh: '「〜じみた」＝带有…的味道（负面）',
    },
    production: {
      promptJa: '幼く見える行動を「〜じみた」で言ってください。',
      promptZh: '用「〜じみた」说一个显得幼稚的行为。',
      expected: ['じみた'], acceptable: [],
    },
    practice: {
      themeJa: '大人の対応', starterJa: '大人らしい対応とはどんな対応だと思いますか？',
      starterZh: '你觉得成熟的应对是什么样的？', targetUse: '〜じみた',
    },
    matchKeys: ['じみた'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-129', pattern: '〜のなんの', reading: 'のなんの', unit: 9,
    meaningJa: '非常に〜だ（大げさに言う）',
    explanationZh: '别提多…了。口语的夸张强调',
    formation: '形容詞＋のなんの（って）',
    usageScene: '会话中夸张地描述感受',
    nuance: 'くだけた話し言葉。改まった場面では使わない',
    register: 'spoken',
    examplesJa: ['寒いのなんのって、手がかじかみました。', 'うれしいのなんの、声が出ませんでした。'],
    examplesZh: ['别提多冷了，手都冻僵了。', '别提多高兴了，都说不出话。'],
    furigana: 'さむいの なんのって、てが かじかみました。',
    commonMistakesZh: '只用于口语。书面用「極まりない」「この上ない」',
    learnerFocus: '听力和会话里会遇到。理解为「非常に〜だ」',
    similarPatterns: ['〜といったらない', '〜この上ない'],
    contrast: '「のなんの」＝くだけた話し言葉；「この上ない」＝書き言葉',
    recognition: {
      promptZh: '「寒いのなんの」是什么意思？',
      options: ['别提多冷了', '不太冷', '冷不冷呢', '冷过了'],
      answerIndex: 0,
      distractorReason: '「のなんの」は程度を大げさに強調する話し言葉',
      distractorReasonZh: '「のなんの」是夸张强调程度的口语',
      explanationZh: '「〜のなんの」＝别提多…了',
    },
    production: {
      promptJa: '大げさな感想を「〜のなんの」で言ってください。',
      promptZh: '用「〜のなんの」说一个夸张的感受。',
      expected: ['のなんの'], acceptable: [],
    },
    practice: {
      themeJa: '大げさに話す', starterJa: '今年の冬はどうでしたか？',
      starterZh: '今年冬天怎么样？', targetUse: '〜のなんの',
    },
    matchKeys: ['のなんの'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-130', pattern: '〜きっての', reading: 'きっての', unit: 9,
    meaningJa: '〜の中でいちばんの',
    explanationZh: '…中最出色的。用于称赞',
    formation: '場所・組織を表す名詞＋きっての＋名詞',
    usageScene: '介绍某地或某组织中的第一人',
    nuance: 'ほめる文脈にだけ使う',
    register: 'written',
    examplesJa: ['町きっての古い店だと言われています。', '社内きっての実力者に相談しました。'],
    examplesZh: ['据说是镇上最老的店。', '向公司里最有实力的人请教了。'],
    furigana: 'まち きっての ふるい みせだと いわれて います。',
    commonMistakesZh: '前面是范围（町・社内・国）。后面是名词',
    learnerFocus: '「〜きっての」＝范围内第一。与「屈指の」意思相近',
    similarPatterns: ['〜一の', '〜屈指の'],
    contrast: '「きっての」＝ある範囲の中で一番；「屈指の」＝上位に入るほど優れている',
    recognition: {
      promptZh: '「町きっての」是什么意思？',
      options: ['镇上最…的', '镇子以外的', '为了镇子', '镇子结束了'],
      answerIndex: 0,
      distractorReason: '「きっての」はその範囲で一番という意味',
      distractorReasonZh: '「きっての」表示在该范围内最…',
      explanationZh: '「〜きっての」＝…中最出色的',
    },
    production: {
      promptJa: '町で一番のものを「〜きっての」で言ってください。',
      promptZh: '用「〜きっての」说说镇上最…的东西。',
      expected: ['きっての'], acceptable: [],
    },
    practice: {
      themeJa: '町の自慢', starterJa: 'あなたの町の自慢は何ですか？',
      starterZh: '你所在城市最值得骄傲的是什么？', targetUse: '〜きっての',
    },
    matchKeys: ['きっての'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-131', pattern: '〜たる', reading: 'たる', unit: 9,
    meaningJa: '〜である（重々しい描写）',
    explanationZh: '…的（庄重的书面修饰）',
    formation: '副詞的な語＋たる＋名詞（堂々たる・確固たる）',
    usageScene: '正式描写态度或立场',
    nuance: '「堂々たる」「確固たる」など決まった語と組む',
    register: 'written',
    examplesJa: ['確固たる証拠が必要です。', '堂々たる態度で説明していました。'],
    examplesZh: ['需要确凿的证据。', '当时以堂堂正正的态度进行说明。'],
    furigana: 'かっこ たる しょうこが ひつようです。',
    commonMistakesZh: '不能自由组合。基本是「確固たる」「堂々たる」「歴然たる」',
    learnerFocus: '「たる＋名词」＝书面修饰。与「たるもの」（身份）不同',
    similarPatterns: ['〜とした', '〜な'],
    contrast: '「たる」＝文語の連体修飾；「たるもの」＝立場としての当然の姿',
    recognition: {
      promptZh: '「確固たる証拠」是什么意思？',
      options: ['确凿的证据', '不确定的证据', '没有证据', '找证据'],
      answerIndex: 0,
      distractorReason: '「たる」は文語の修飾で、ここでは「確かな」の意味',
      distractorReasonZh: '「たる」是文语修饰，此处意为「确凿的」',
      explanationZh: '「〜たる」＝…的（庄重的修饰）',
    },
    production: {
      promptJa: '確かな根拠を「確固たる」で言ってください。',
      promptZh: '用「確固たる」说一个确凿的依据。',
      expected: ['たる'], acceptable: ['確固たる'],
    },
    practice: {
      themeJa: '根拠の確かさ', starterJa: '主張するとき、何が必要だと思いますか？',
      starterZh: '主张时你觉得需要什么？', targetUse: '〜たる',
    },
    matchKeys: ['たる'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-132', pattern: '〜そのものだ', reading: 'そのものだ', unit: 9,
    meaningJa: 'まさに〜だ（そのままだ）',
    explanationZh: '简直就是…本身。强调完全符合',
    formation: '名詞／な形容詞語幹＋そのものだ',
    usageScene: '强调完全符合某种状态',
    nuance: '「元気そのもの」「真剣そのもの」など様子を表す語と組む',
    register: 'spoken',
    examplesJa: ['祖父は九十歳ですが健康そのものです。', '練習中の表情は真剣そのものでした。'],
    examplesZh: ['祖父九十岁了，却健康得很。', '练习时的表情非常认真。'],
    furigana: 'そふは きゅうじゅっさい ですが けんこう そのものです。',
    commonMistakesZh: '不是「那个东西」。这里是「完全就是…的状态」',
    learnerFocus: '「元気そのもの」「真剣そのもの」是最常见的搭配',
    similarPatterns: ['〜にほかならない', '〜きわまりない'],
    contrast: '「そのものだ」＝状態がまさにそれ；「にほかならない」＝本質の断定',
    recognition: {
      promptZh: '「健康そのもの」是什么意思？',
      options: ['非常健康', '健康的东西', '不健康', '想变健康'],
      answerIndex: 0,
      distractorReason: '「そのもの」は「まさにその状態だ」という強調',
      distractorReasonZh: '「そのもの」强调「正是那种状态」',
      explanationZh: '「〜そのものだ」＝简直就是…',
    },
    production: {
      promptJa: '人の様子を「〜そのものだ」で言ってください。',
      promptZh: '用「〜そのものだ」形容一个人的样子。',
      expected: ['そのもの'], acceptable: ['そのものだ'],
    },
    practice: {
      themeJa: '人の様子を伝える', starterJa: '元気な人を紹介してください。',
      starterZh: '介绍一个很有精神的人。', targetUse: '〜そのものだ',
    },
    matchKeys: ['そのもの'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-133', pattern: '〜というところだ', reading: 'というところだ', unit: 9,
    meaningJa: 'だいたい〜くらいだ',
    explanationZh: '大概就是…的程度。表示不多不少',
    formation: '数量・程度を表す語＋というところだ／といったところだ',
    usageScene: '回答程度或数量时给出大致的上限',
    nuance: '「多くてもこのくらい」という控えめな見積もり',
    register: 'spoken',
    examplesJa: ['進み具合は半分といったところです。', '待ち時間は十分というところでしょう。'],
    examplesZh: ['进度大概就一半左右。', '等待时间大概就十分钟吧。'],
    furigana: 'すすみ ぐあいは はんぶんと いった ところです。',
    commonMistakesZh: '表示「最多也就这么多」的语气，不是「至少」',
    learnerFocus: '「〜といったところだ」在会话里很自然。回答程度时好用',
    similarPatterns: ['〜くらいだ', '〜ほどだ'],
    contrast: '「というところだ」＝控えめな上限；「くらいだ」＝単なる概算',
    recognition: {
      promptZh: '「半分といったところだ」是什么意思？',
      options: ['大概就一半左右', '一半以上', '全部完成', '还没开始'],
      answerIndex: 0,
      distractorReason: '「というところだ」はだいたいの程度を控えめに言う',
      distractorReasonZh: '「というところだ」是保守地说出大致程度',
      explanationZh: '「〜というところだ」＝大概就是…的程度',
    },
    production: {
      promptJa: '進み具合を「〜といったところだ」で言ってください。',
      promptZh: '用「〜といったところだ」说一说进度。',
      expected: ['ところだ'], acceptable: ['といったところです'],
    },
    practice: {
      themeJa: '進み具合を伝える', starterJa: '今の勉強の進み具合はどのくらいですか？',
      starterZh: '你现在学习的进度大概如何？', targetUse: '〜というところだ',
    },
    matchKeys: ['というところ', 'といったところ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-134', pattern: '〜からなる', reading: 'からなる', unit: 9,
    meaningJa: '〜で構成されている',
    explanationZh: '由…构成',
    formation: '名詞＋からなる／から成る',
    usageScene: '说明组织或作品的构成',
    nuance: '硬い書き言葉。説明文で使う',
    register: 'written',
    examplesJa: ['この本は三つの章からなります。', '委員会は十人の委員からなる組織です。'],
    examplesZh: ['这本书由三章构成。', '委员会是由十名委员构成的组织。'],
    furigana: 'この ほんは みっつの しょうから なります。',
    commonMistakesZh: '不是「从…来」。这里是「由…构成」',
    learnerFocus: '说明文里的高频表达。「〜からなる」＝由…组成',
    similarPatterns: ['〜で構成される', '〜からできている'],
    contrast: '「からなる」＝構成要素を示す；「からできている」＝材料を示すことが多い',
    recognition: {
      promptZh: '「三つの章からなる」是什么意思？',
      options: ['由三章构成', '从第三章开始', '第三章结束', '没有第三章'],
      answerIndex: 0,
      distractorReason: '「からなる」は構成を表す',
      distractorReasonZh: '「からなる」表示构成',
      explanationZh: '「〜からなる」＝由…构成',
    },
    production: {
      promptJa: '何かの構成を「〜からなる」で説明してください。',
      promptZh: '用「〜からなる」说明某物的构成。',
      expected: ['からなる'], acceptable: ['から成る'],
    },
    practice: {
      themeJa: '構成を説明する', starterJa: 'よく読む本はどんな構成ですか？',
      starterZh: '你常读的书是什么结构？', targetUse: '〜からなる',
    },
    matchKeys: ['からなる', 'から成る'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-135', pattern: '〜と思いきや', reading: 'とおもいきや', unit: 9,
    meaningJa: '〜と思ったら、実際は違った',
    explanationZh: '本以为…结果却…。表示意外',
    formation: '普通形＋と思いきや',
    usageScene: '叙述与预想相反的结果',
    nuance: '意外さを表す。後ろは予想外の事実',
    register: 'written',
    examplesJa: ['空いていると思いきや、満席でした。', '簡単だと思いきや、手こずりました。'],
    examplesZh: ['本以为很空，结果满座了。', '本以为很简单，结果费了不少劲。'],
    furigana: 'あいて いると おもいきや、まんせき でした。',
    commonMistakesZh: '后面接与预想相反的事实。不接同方向的内容',
    learnerFocus: '「と思いきや」＝本以为…结果。阅读中表示转折的信号',
    similarPatterns: ['〜と思ったら', '〜に反して'],
    contrast: '「と思いきや」＝意外さを強調（書き言葉）；「と思ったら」＝話し言葉でも使える',
    recognition: {
      promptZh: '「空いていると思いきや」后面最可能接什么？',
      options: ['満席だった', 'やはり空いていた', '空いていて助かった', '空いているはずだ'],
      answerIndex: 0,
      distractorReason: '「と思いきや」の後ろは予想と反する事実が来る',
      distractorReasonZh: '「と思いきや」后面接与预想相反的事实',
      explanationZh: '「〜と思いきや」＝本以为…结果却…',
    },
    production: {
      promptJa: '予想外だったことを「〜と思いきや」で言ってください。',
      promptZh: '用「〜と思いきや」说一件出乎预料的事。',
      expected: ['と思いきや'], acceptable: [],
    },
    practice: {
      themeJa: '予想外の出来事', starterJa: '思っていたのと違った経験はありますか？',
      starterZh: '有过与预想不同的经历吗？', targetUse: '〜と思いきや',
    },
    matchKeys: ['と思いきや'], vocabularyLinks: [],
  }),
];
