// N1文法 Unit 10（15項目 / 文末・書き言葉の言い回し）。
// 例文・訳・解説はすべて自社で書き起こす。
import { n1g, type N1GrammarDraft } from './n1GrammarDrafts';

export const N1_GRAMMAR_DRAFTS_UNIT10: N1GrammarDraft[] = [
  n1g({
    grammarId: 'n1g-136', pattern: '〜ものと思われる', reading: 'ものとおもわれる', unit: 10,
    meaningJa: '〜だと考えられる（客観的な推測）',
    explanationZh: '被认为是…。是客观的书面推测',
    formation: '普通形＋ものと思われる',
    usageScene: '报道、报告中作出谨慎的推测',
    nuance: '書き手の主観を出さない言い方',
    register: 'written',
    examplesJa: ['原因は配線の劣化によるものと思われます。', '影響は限られたものと思われる。'],
    examplesZh: ['原因被认为是线路老化。', '影响被认为是有限的。'],
    furigana: 'げんいんは はいせんの れっかに よる ものと おもわれます。',
    commonMistakesZh: '不用于自己的意见。是客观的推测表达',
    learnerFocus: '新闻里几乎都用这个形式。看到就理解为「据推测」',
    similarPatterns: ['〜と考えられる', '〜とみられる'],
    contrast: '「ものと思われる」＝慎重で客観的；「と思う」＝話し手の主観',
    recognition: {
      promptZh: '「〜ものと思われる」的语气是什么？',
      options: ['客观、慎重的推测', '强烈的断定', '个人的希望', '直接的命令'],
      answerIndex: 0,
      distractorReason: '「ものと思われる」は主観を抑えた推測',
      distractorReasonZh: '「ものと思われる」是压低主观的推测',
      explanationZh: '「〜ものと思われる」＝被认为是…',
    },
    production: {
      promptJa: '原因の推測を「〜ものと思われます」で書いてください。',
      promptZh: '用「〜ものと思われます」写一个原因的推测。',
      expected: ['ものと思われ'], acceptable: ['ものと思われます'],
    },
    practice: {
      themeJa: '原因を推測する', starterJa: '身近な問題の原因を推測してみましょう。',
      starterZh: '试着推测身边问题的原因。', targetUse: '〜ものと思われる',
    },
    matchKeys: ['ものと思われ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-137', pattern: '〜とされている', reading: 'とされている', unit: 10,
    meaningJa: '一般に〜と考えられている',
    explanationZh: '一般被认为…。表示社会通行的看法',
    formation: '普通形＋とされている',
    usageScene: '说明社会共识或规定',
    nuance: '誰が決めたかを言わずに、共通認識として示す',
    register: 'written',
    examplesJa: ['この地域では昔から縁起がよいとされています。', 'この手続きは必要とされています。'],
    examplesZh: ['在这个地区，自古以来被认为是吉利的。', '这项手续被规定为必须的。'],
    furigana: 'この ちいきでは むかしから えんぎが よいと されて います。',
    commonMistakesZh: '不表示是谁认为的。这正是它的用途',
    learnerFocus: '论说文里的高频形式。「〜とされている」＝被认为',
    similarPatterns: ['〜と言われている', '〜ものと思われる'],
    contrast: '「とされている」＝社会の共通認識・規定；「と言われている」＝うわさや評判にも使う',
    recognition: {
      promptZh: '「とされている」是什么意思？',
      options: ['一般被认为…', '我认为…', '不这样认为', '正在决定'],
      answerIndex: 0,
      distractorReason: '「とされている」は一般的な認識を示す',
      distractorReasonZh: '「とされている」表示一般的共识',
      explanationZh: '「〜とされている」＝一般被认为…',
    },
    production: {
      promptJa: '一般に信じられていることを「〜とされている」で言ってください。',
      promptZh: '用「〜とされている」说一件普遍被认为的事。',
      expected: ['とされて'], acceptable: ['とされている'],
    },
    practice: {
      themeJa: '文化の中の常識', starterJa: 'あなたの国で縁起がよいとされるものは？',
      starterZh: '在你的国家什么被认为是吉利的？', targetUse: '〜とされている',
    },
    matchKeys: ['とされて'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-138', pattern: '〜つつある', reading: 'つつある', unit: 10,
    meaningJa: '少しずつ〜する方向に進んでいる',
    explanationZh: '正在逐渐…。强调变化的过程',
    formation: '動詞ます形＋つつある',
    usageScene: '报道中说明趋势',
    nuance: '「〜ている」より変化の途中であることを強調する',
    register: 'written',
    examplesJa: ['状況は少しずつ改善しつつあります。', '古い建物が姿を消しつつある。'],
    examplesZh: ['状况正在逐渐改善。', '古老的建筑正在逐渐消失。'],
    furigana: 'じょうきょうは すこしずつ かいぜん しつつ あります。',
    commonMistakesZh: '与「〜つつも」（虽然）不同。这里表示进行中的变化',
    learnerFocus: '与变化类动词搭配：増える・減る・改善する・消える',
    similarPatterns: ['〜ている', '〜一方だ'],
    contrast: '「つつある」＝変化の途中；「一方だ」＝一方向に進み続ける',
    recognition: {
      promptZh: '「改善しつつある」是什么意思？',
      options: ['正在逐渐改善', '已经改善完了', '没有改善', '想要改善'],
      answerIndex: 0,
      distractorReason: '「つつある」は変化の途中であることを表す',
      distractorReasonZh: '「つつある」表示变化正在进行中',
      explanationZh: '「〜つつある」＝正在逐渐…',
    },
    production: {
      promptJa: '進行中の変化を「〜つつある」で言ってください。',
      promptZh: '用「〜つつある」说一个正在进行的变化。',
      expected: ['つつある'], acceptable: ['つつあります'],
    },
    practice: {
      themeJa: '進んでいる変化', starterJa: '最近少しずつ変わってきたことはありますか？',
      starterZh: '最近有什么在慢慢改变？', targetUse: '〜つつある',
    },
    matchKeys: ['つつある'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-139', pattern: '〜ばかりだ', reading: 'ばかりだ', unit: 10,
    meaningJa: '（悪い方向へ）〜する一方だ',
    explanationZh: '一味地…（越来越糟）',
    formation: '動詞辞書形＋ばかりだ',
    usageScene: '说明状况持续恶化',
    nuance: 'よくない方向の変化に使うことが多い',
    register: 'written',
    examplesJa: ['対策がなく、不安は増すばかりです。', '費用は上がるばかりで、収入は変わりません。'],
    examplesZh: ['没有对策，不安只增不减。', '费用一味上涨，收入却没变。'],
    furigana: 'たいさくが なく、ふあんは ますばかりです。',
    commonMistakesZh: '与「〜たばかり」（刚刚）不同。接辞书形',
    learnerFocus: '「〜るばかりだ」＝越来越…。多用于负面变化',
    similarPatterns: ['〜一方だ', '〜つつある'],
    contrast: '「ばかりだ」＝悪化の一方；「つつある」＝良し悪しを問わない変化',
    recognition: {
      promptZh: '「不安は増すばかりだ」是什么意思？',
      options: ['不安只增不减', '不安减少了', '刚刚不安', '不再不安'],
      answerIndex: 0,
      distractorReason: '辞書形＋ばかりだ は一方向へ進み続ける意味',
      distractorReasonZh: '辞书形＋ばかりだ 表示朝一个方向持续发展',
      explanationZh: '「〜ばかりだ」＝一味地…（越来越糟）',
    },
    production: {
      promptJa: '悪くなる一方のことを「〜ばかりだ」で言ってください。',
      promptZh: '用「〜ばかりだ」说一件越来越糟的事。',
      expected: ['ばかりだ'], acceptable: ['ばかりです'],
    },
    practice: {
      themeJa: '悪くなっていること', starterJa: '最近悪くなっていると感じることは？',
      starterZh: '最近你觉得什么在变糟？', targetUse: '〜ばかりだ',
    },
    matchKeys: ['ばかりだ', 'ばかりです'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-140', pattern: '〜ずじまい', reading: 'ずじまい', unit: 10,
    meaningJa: '〜しないまま終わってしまった',
    explanationZh: '结果没能…。带遗憾语气',
    formation: '動詞ない形（ない→ず）＋じまい（する→せずじまい）',
    usageScene: '回顾没能实现的打算',
    nuance: '心残りの気持ちを含む',
    register: 'spoken',
    examplesJa: ['忙しくて、結局会えずじまいでした。', '買おうと思いながら、買わずじまいです。'],
    examplesZh: ['太忙了，结果没能见上。', '一直想买，结果没买成。'],
    furigana: 'いそがしくて、けっきょく あえず じまい でした。',
    commonMistakesZh: '「する」变成「せずじまい」。也常写成「〜ないままだった」',
    learnerFocus: '「〜ずじまい」＝结果没能…。是很有感情的表达',
    similarPatterns: ['〜ないままだ', '〜そびれる'],
    contrast: '「ずじまい」＝結局しないまま終わった残念さ；「そびれる」＝機会を逃した',
    recognition: {
      promptZh: '「会えずじまい」是什么意思？',
      options: ['结果没能见上', '见到了', '不想见', '正要见'],
      answerIndex: 0,
      distractorReason: '「ずじまい」はしないまま終わったことを表す',
      distractorReasonZh: '「ずじまい」表示没做成就结束了',
      explanationZh: '「〜ずじまい」＝结果没能…',
    },
    production: {
      promptJa: 'できないまま終わったことを「〜ずじまい」で言ってください。',
      promptZh: '用「〜ずじまい」说一件最终没做成的事。',
      expected: ['ずじまい'], acceptable: [],
    },
    practice: {
      themeJa: '心残りなこと', starterJa: 'やろうと思ってできなかったことはありますか？',
      starterZh: '有什么打算做却没做成的事？', targetUse: '〜ずじまい',
    },
    matchKeys: ['ずじまい'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-141', pattern: '〜あぐねる', reading: 'あぐねる', unit: 10,
    meaningJa: '〜しようとしてうまくいかず、迷う',
    explanationZh: '…得没有头绪；难以决定',
    formation: '動詞ます形＋あぐねる',
    usageScene: '说明反复尝试仍无结果',
    nuance: '「決めあぐねる」「言いあぐねる」など限られた動詞と組む',
    register: 'written',
    examplesJa: ['言い出しあぐねて、そのままになりました。', '結論を決めあぐねています。'],
    examplesZh: ['难以开口，就那样过去了。', '难以决定结论。'],
    furigana: 'いいだし あぐねて、そのままに なりました。',
    commonMistakesZh: '不能自由组合。常见的是決めあぐねる・言いあぐねる・待ちあぐねる',
    learnerFocus: '「あぐねる」＝做不下去而犯难。与「かねる」不同，重点在「反复尝试」',
    similarPatterns: ['〜かねる', '〜悩む'],
    contrast: '「あぐねる」＝試みたがうまくいかない；「かねる」＝立場上できない',
    recognition: {
      promptZh: '「決めあぐねる」是什么意思？',
      options: ['难以决定', '已经决定', '不想决定', '决定得快'],
      answerIndex: 0,
      distractorReason: '「あぐねる」はやってみてもうまくいかず迷う意味',
      distractorReasonZh: '「あぐねる」表示试了也不顺、拿不定主意',
      explanationZh: '「〜あぐねる」＝…得没有头绪',
    },
    production: {
      promptJa: '決められないことを「決めあぐねる」で言ってください。',
      promptZh: '用「決めあぐねる」说一件难以决定的事。',
      expected: ['あぐね'], acceptable: ['あぐねる'],
    },
    practice: {
      themeJa: '決められないこと', starterJa: 'なかなか決められないことはありますか？',
      starterZh: '有什么事你迟迟决定不了？', targetUse: '〜あぐねる',
    },
    matchKeys: ['あぐね'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-142', pattern: '〜そびれる', reading: 'そびれる', unit: 10,
    meaningJa: '〜する機会を逃す',
    explanationZh: '错过了…的机会',
    formation: '動詞ます形＋そびれる',
    usageScene: '说明因时机不对而没做成',
    nuance: 'するつもりだったのに機会を失った場合に使う',
    register: 'spoken',
    examplesJa: ['話しかけそびれて、そのまま帰りました。', '昼ご飯を食べそびれました。'],
    examplesZh: ['错过了搭话的时机，就那样回去了。', '错过了吃午饭。'],
    furigana: 'はなしかけ そびれて、そのまま かえりました。',
    commonMistakesZh: '不是「不想做」，而是「错过了机会」',
    learnerFocus: '「食べそびれる」「言いそびれる」在会话里很常用',
    similarPatterns: ['〜ずじまい', '〜損なう'],
    contrast: '「そびれる」＝機会を逃した；「ずじまい」＝結局しないまま終わった',
    recognition: {
      promptZh: '「話しかけそびれた」是什么意思？',
      options: ['错过了搭话的时机', '搭话了', '不想搭话', '被搭话了'],
      answerIndex: 0,
      distractorReason: '「そびれる」は機会を逃す意味',
      distractorReasonZh: '「そびれる」意为错过机会',
      explanationZh: '「〜そびれる」＝错过了…的机会',
    },
    production: {
      promptJa: '機会を逃したことを「〜そびれる」で言ってください。',
      promptZh: '用「〜そびれる」说一件错过时机的事。',
      expected: ['そびれ'], acceptable: ['そびれる'],
    },
    practice: {
      themeJa: '言えなかったこと', starterJa: '言おうとして言えなかったことはありますか？',
      starterZh: '有过想说却没说出口的事吗？', targetUse: '〜そびれる',
    },
    matchKeys: ['そびれ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-143', pattern: '〜てのける', reading: 'てのける', unit: 10,
    meaningJa: '難しいことを見事に〜する',
    explanationZh: '漂亮地做成了（难事）',
    formation: '動詞て形＋のける',
    usageScene: '称赞完成了别人做不到的事',
    nuance: '感心する気持ちを含む',
    register: 'written',
    examplesJa: ['彼は難しい仕事をやってのけました。', '一人で全部片づけてのけた。'],
    examplesZh: ['他漂亮地完成了难做的工作。', '一个人把全部都收拾好了。'],
    furigana: 'かれは むずかしい しごとを やって のけました。',
    commonMistakesZh: '用于难度高的事。日常小事不用',
    learnerFocus: '「やってのける」是最常见的形式，先记这个',
    similarPatterns: ['〜てみせる', '〜やり遂げる'],
    contrast: '「てのける」＝難事を見事にやった（結果の評価）；「てみせる」＝必ずやると宣言する',
    recognition: {
      promptZh: '「やってのけた」是什么意思？',
      options: ['漂亮地做成了', '试着做了', '没做成', '不想做'],
      answerIndex: 0,
      distractorReason: '「てのける」は難しいことを見事に成し遂げた意味',
      distractorReasonZh: '「てのける」意为出色地完成了难事',
      explanationZh: '「〜てのける」＝漂亮地做成了',
    },
    production: {
      promptJa: '難しいことを成し遂げた人を「〜てのける」で言ってください。',
      promptZh: '用「〜てのける」说一个完成难事的人。',
      expected: ['てのけ'], acceptable: ['てのける'],
    },
    practice: {
      themeJa: 'すごいと思った人', starterJa: 'すごいと思った人の話を教えてください。',
      starterZh: '说说让你佩服的人。', targetUse: '〜てのける',
    },
    matchKeys: ['てのけ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-144', pattern: '〜てみせる', reading: 'てみせる', unit: 10,
    meaningJa: '必ず〜すると強く決意する',
    explanationZh: '一定要…给（人）看。表示决心',
    formation: '動詞て形＋みせる',
    usageScene: '表达强烈的决心',
    nuance: '「やってみせる」は決意、「やって見せる」は実演。文脈で判断する',
    register: 'spoken',
    examplesJa: ['今年こそ合格してみせます。', '必ず結果を出してみせる。'],
    examplesZh: ['今年一定要考上给大家看。', '一定要做出成果。'],
    furigana: 'ことし こそ ごうかく して みせます。',
    commonMistakesZh: '与「〜てみる」（试着做）不同。这里是决心',
    learnerFocus: '「〜てみせる」＝一定要做到。与「〜てみる」差一个字，意思完全不同',
    similarPatterns: ['〜てみる', '〜てのける'],
    contrast: '「てみせる」＝決意の宣言；「てみる」＝試しにやる',
    recognition: {
      promptZh: '「合格してみせます」是什么意思？',
      options: ['一定要考上', '试着考一下', '考上过了', '考不上'],
      answerIndex: 0,
      distractorReason: '「てみせる」は強い決意を表す',
      distractorReasonZh: '「てみせる」表示强烈的决心',
      explanationZh: '「〜てみせる」＝一定要…',
    },
    production: {
      promptJa: '決意を「〜てみせます」で言ってください。',
      promptZh: '用「〜てみせます」表达决心。',
      expected: ['てみせ'], acceptable: ['てみせます'],
    },
    practice: {
      themeJa: '今年の決意', starterJa: '今年必ず達成したいことは何ですか？',
      starterZh: '今年你一定要达成的是什么？', targetUse: '〜てみせる',
    },
    matchKeys: ['てみせ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-145', pattern: '〜がい', reading: 'がい', unit: 10,
    meaningJa: '〜する価値・手ごたえ',
    explanationZh: '值得…的意义、成就感',
    formation: '動詞ます形＋がい（がある）',
    usageScene: '说明做某事有价值、有回报',
    nuance: '「やりがい」「생きがい」など名詞になった形が多い',
    register: 'spoken',
    examplesJa: ['教えがいのある生徒に出会いました。', 'この仕事にはやりがいがあります。'],
    examplesZh: ['遇到了值得教的学生。', '这份工作很有成就感。'],
    furigana: 'おしえがいの ある せいとに であいました。',
    commonMistakesZh: '接在动词ます形后面。「やりがい」是最常见的名词形',
    learnerFocus: '「やりがい」「生きがい」「教えがい」——三个记住就够用',
    similarPatterns: ['〜価値がある', '〜甲斐'],
    contrast: '「がい」＝手ごたえ・報われる感じ；「価値がある」＝客観的な値打ち',
    recognition: {
      promptZh: '「やりがいがある」是什么意思？',
      options: ['有成就感、值得做', '做不了', '不想做', '做完了'],
      answerIndex: 0,
      distractorReason: '「がい」は手ごたえや価値を表す',
      distractorReasonZh: '「がい」表示成就感或价值',
      explanationZh: '「〜がい」＝值得…的意义',
    },
    production: {
      promptJa: '手ごたえのあることを「〜がいがある」で言ってください。',
      promptZh: '用「〜がいがある」说一件有成就感的事。',
      expected: ['がい'], acceptable: ['がいがある'],
    },
    practice: {
      themeJa: '手ごたえのある仕事', starterJa: 'やりがいを感じるのはどんなときですか？',
      starterZh: '什么时候你会感到有成就感？', targetUse: '〜がい',
    },
    matchKeys: ['がい'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-146', pattern: '〜っぷり', reading: 'っぷり', unit: 10,
    meaningJa: '〜する様子・しかた',
    explanationZh: '…的样子、…的架势',
    formation: '動詞ます形／名詞＋っぷり',
    usageScene: '生动描写别人的做法',
    nuance: '「飲みっぷり」「話しっぷり」など、見ていて感心する様子に使う',
    register: 'spoken',
    examplesJa: ['彼の働きっぷりには感心します。', '見事な食べっぷりでした。'],
    examplesZh: ['他工作的样子令人佩服。', '吃得很痛快。'],
    furigana: 'かれの はたらきっぷりには かんしん します。',
    commonMistakesZh: '多用于正面或中性的描写。批评时不太用',
    learnerFocus: '「働きっぷり」「話しっぷり」——描写别人时很生动',
    similarPatterns: ['〜方', '〜様子'],
    contrast: '「っぷり」＝見ていて感心する様子；「〜方」＝ただのやり方',
    recognition: {
      promptZh: '「働きっぷり」是什么意思？',
      options: ['工作的样子、干劲', '工作的地方', '不工作', '工作时间'],
      answerIndex: 0,
      distractorReason: '「っぷり」は様子・しかたを表す',
      distractorReasonZh: '「っぷり」表示样子、做法',
      explanationZh: '「〜っぷり」＝…的样子',
    },
    production: {
      promptJa: '人の様子を「〜っぷり」で言ってください。',
      promptZh: '用「〜っぷり」描写一个人的样子。',
      expected: ['っぷり'], acceptable: [],
    },
    practice: {
      themeJa: '感心した人の様子', starterJa: '見ていて感心した人はいますか？',
      starterZh: '有让你看着就佩服的人吗？', targetUse: '〜っぷり',
    },
    matchKeys: ['っぷり'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-147', pattern: '〜まじき', reading: 'まじき', unit: 10,
    meaningJa: '〜してはいけない（立場として）',
    explanationZh: '不该…的（作为某种身份）',
    formation: '動詞辞書形＋まじき＋名詞',
    usageScene: '严厉批评不合身份的行为',
    nuance: '「あるまじき」の形がほとんど',
    register: 'written',
    examplesJa: ['責任者としてあるまじき対応でした。', '教える者にあるまじき発言だと批判されました。'],
    examplesZh: ['那是作为负责人不该有的应对。', '被批评是身为教育者不该有的发言。'],
    furigana: 'せきにんしゃ として ある まじき たいおう でした。',
    commonMistakesZh: '基本只用「あるまじき＋名词」的形式',
    learnerFocus: '「あるまじき」＝不该有的。是新闻里批评时的固定说法',
    similarPatterns: ['〜べきではない', '〜べからざる'],
    contrast: '「まじき」＝立場にふさわしくない（強い非難）；「べきではない」＝一般的な否定の主張',
    recognition: {
      promptZh: '「あるまじき対応」是什么意思？',
      options: ['不该有的应对', '应该有的应对', '有过的应对', '没有应对'],
      answerIndex: 0,
      distractorReason: '「まじき」は「〜してはいけない」の文語',
      distractorReasonZh: '「まじき」是「不该…」的文语形式',
      explanationZh: '「〜まじき」＝不该…的',
    },
    production: {
      promptJa: '立場にふさわしくない行動を「あるまじき」で言ってください。',
      promptZh: '用「あるまじき」说一个不合身份的行为。',
      expected: ['まじき'], acceptable: ['あるまじき'],
    },
    practice: {
      themeJa: '許されない行動', starterJa: 'その立場ではしてはいけないことは何ですか？',
      starterZh: '在那个身份上什么是绝不能做的？', targetUse: '〜まじき',
    },
    matchKeys: ['まじき'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-148', pattern: '〜なりに', reading: 'なりに', unit: 10,
    meaningJa: '〜にふさわしいやり方で',
    explanationZh: '以…自己的方式；尽…所能',
    formation: '名詞／動詞・形容詞の普通形＋なりに',
    usageScene: '肯定不完美但尽力的做法',
    nuance: '完璧ではないが、その立場では十分だという評価',
    register: 'spoken',
    examplesJa: ['私なりに考えて決めました。', '子どもは子どもなりに工夫しています。'],
    examplesZh: ['我以自己的方式思考后决定的。', '孩子有孩子自己的办法。'],
    furigana: 'わたし なりに かんがえて きめました。',
    commonMistakesZh: '与Unit 3的「なり」（刚…就）不同。这里是「以自己的方式」',
    learnerFocus: '「私なりに」是很实用的谦逊说法',
    similarPatterns: ['〜らしく', '〜に応じて'],
    contrast: '「なりに」＝その立場での精一杯；「らしく」＝典型的な姿にふさわしい',
    recognition: {
      promptZh: '「私なりに」是什么意思？',
      options: ['以我自己的方式', '和我一样', '代替我', '不是我'],
      answerIndex: 0,
      distractorReason: '「なりに」はその人にふさわしいやり方を表す',
      distractorReasonZh: '「なりに」表示以那个人的方式',
      explanationZh: '「〜なりに」＝以…自己的方式',
    },
    production: {
      promptJa: '自分の工夫を「私なりに」で言ってください。',
      promptZh: '用「私なりに」说说自己的做法。',
      expected: ['なりに'], acceptable: [],
    },
    practice: {
      themeJa: '自分の工夫', starterJa: '自分なりに工夫していることはありますか？',
      starterZh: '你有什么自己的小办法吗？', targetUse: '〜なりに',
    },
    matchKeys: ['なりに'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-149', pattern: '〜ずにすむ', reading: 'ずにすむ', unit: 10,
    meaningJa: '〜しなくてもよくなる',
    explanationZh: '用不着…就解决了',
    formation: '動詞ない形（ない→ず）＋にすむ',
    usageScene: '说明避免了麻烦',
    nuance: '心配していたことをしなくてよかったという安心',
    register: 'spoken',
    examplesJa: ['早めに直したので、買い替えずにすみました。', '説明したら、怒られずにすみました。'],
    examplesZh: ['早点修了，就不用换新的了。', '解释之后就没挨骂。'],
    furigana: 'はやめに なおしたので、かいかえずに すみました。',
    commonMistakesZh: '「する」变成「せずにすむ」。也可说「〜ないですむ」',
    learnerFocus: '「〜ずにすむ」＝免于…。是很实用的会话表达',
    similarPatterns: ['〜なくてもいい', '〜を免れる'],
    contrast: '「ずにすむ」＝結果的にしなくてよくなった；「なくてもいい」＝もともと必要がない',
    recognition: {
      promptZh: '「買い替えずにすんだ」是什么意思？',
      options: ['用不着换新的了', '换了新的', '必须换新的', '想换新的'],
      answerIndex: 0,
      distractorReason: '「ずにすむ」はしなくてよくなったという意味',
      distractorReasonZh: '「ずにすむ」表示结果不必做了',
      explanationZh: '「〜ずにすむ」＝用不着…',
    },
    production: {
      promptJa: '避けられたことを「〜ずにすんだ」で言ってください。',
      promptZh: '用「〜ずにすんだ」说一件被避免的麻烦。',
      expected: ['ずにすむ'], acceptable: ['ずにすんだ'],
    },
    practice: {
      themeJa: '助かった経験', starterJa: '早めに動いて助かったことはありますか？',
      starterZh: '有过因为早行动而免于麻烦的事吗？', targetUse: '〜ずにすむ',
    },
    matchKeys: ['ずにすむ', 'ずにすん'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-150', pattern: '〜ものやら', reading: 'ものやら', unit: 10,
    meaningJa: '〜のかどうか分からない',
    explanationZh: '不知道是否…。表示疑惑',
    formation: '疑問詞を含む句＋ものやら',
    usageScene: '表达对情况完全没有把握',
    nuance: '「どうしたものやら」「何を考えているものやら」の形が多い',
    register: 'spoken',
    examplesJa: ['どうしたものやら、見当がつきません。', '何を考えているものやら分かりません。'],
    examplesZh: ['不知该如何是好，毫无头绪。', '不知道在想什么。'],
    furigana: 'どう した ものやら、けんとうが つきません。',
    commonMistakesZh: '常与疑问词搭配。后面接「分からない」等',
    learnerFocus: '「どうしたものやら」整句记住，是很自然的困惑表达',
    similarPatterns: ['〜のだろうか', '〜かどうか'],
    contrast: '「ものやら」＝困惑を込めた疑い；「かどうか」＝中立に可否を問う',
    recognition: {
      promptZh: '「どうしたものやら」是什么意思？',
      options: ['不知该如何是好', '已经解决了', '不想解决', '做完了'],
      answerIndex: 0,
      distractorReason: '「ものやら」は分からないという困惑を表す',
      distractorReasonZh: '「ものやら」表示不明所以的困惑',
      explanationZh: '「〜ものやら」＝不知道是否…',
    },
    production: {
      promptJa: '困っている気持ちを「どうしたものやら」で言ってください。',
      promptZh: '用「どうしたものやら」表达为难的心情。',
      expected: ['ものやら'], acceptable: [],
    },
    practice: {
      themeJa: '困っていること', starterJa: '今どうすればいいか迷っていることはありますか？',
      starterZh: '现在有什么让你拿不定主意的事吗？', targetUse: '〜ものやら',
    },
    matchKeys: ['ものやら'], vocabularyLinks: [],
  }),
];
