// N1文法 Unit 8（15項目 / 立場・観点・基準・関連）。
// 例文・訳・解説はすべて自社で書き起こす。
import { n1g, type N1GrammarDraft } from './n1GrammarDrafts';

export const N1_GRAMMAR_DRAFTS_UNIT8: N1GrammarDraft[] = [
  n1g({
    grammarId: 'n1g-106', pattern: '〜にしてみれば', reading: 'にしてみれば', unit: 8,
    meaningJa: '〜の立場から見ると',
    explanationZh: '从…的角度来看',
    formation: '人を表す名詞＋にしてみれば',
    usageScene: '说明当事人的感受与外部看法不同',
    nuance: '人の気持ちに寄り添うときに使う',
    register: 'spoken',
    examplesJa: ['子どもにしてみれば、急な引っ越しは不安でしょう。', '店にしてみれば、値上げは苦しい決断です。'],
    examplesZh: ['从孩子的角度看，突然搬家会不安吧。', '从店家的角度看，涨价是艰难的决定。'],
    furigana: 'こどもに して みれば、きゅうな ひっこしは ふあん でしょう。',
    commonMistakesZh: '前面必须是人或组织。事物不能用',
    learnerFocus: '后面常接推测：「〜でしょう」「〜はずだ」',
    similarPatterns: ['〜にとっては', '〜からすれば'],
    contrast: '「にしてみれば」＝気持ちに寄り添う；「にとっては」＝中立に立場を示す',
    recognition: {
      promptZh: '「子どもにしてみれば」是什么意思？',
      options: ['从孩子的角度看', '试着做孩子', '对孩子来说很难', '孩子做的'],
      answerIndex: 0,
      distractorReason: '「にしてみれば」は立場から見た感じ方を表す',
      distractorReasonZh: '「にしてみれば」表示从该立场感受到的看法',
      explanationZh: '「〜にしてみれば」＝从…的角度来看',
    },
    production: {
      promptJa: '相手の立場から見た気持ちを「〜にしてみれば」で言ってください。',
      promptZh: '用「〜にしてみれば」说说从对方角度的感受。',
      expected: ['にしてみれば'], acceptable: ['にしてみたら'],
    },
    practice: {
      themeJa: '相手の気持ちを考える', starterJa: '相手の立場だったらどう感じると思いますか？',
      starterZh: '如果站在对方立场你会怎么想？', targetUse: '〜にしてみれば',
    },
    matchKeys: ['にしてみれば', 'にしてみたら'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-107', pattern: '〜からすると／〜からすれば', reading: 'からすると', unit: 8,
    meaningJa: '〜から判断すると',
    explanationZh: '从…来判断；根据…来看',
    formation: '名詞＋からすると／からすれば',
    usageScene: '根据证据、条件作出判断',
    nuance: '判断の根拠を示す。立場を示す用法もある',
    register: 'written',
    examplesJa: ['この様子からすると、間に合いそうです。', '経験からすれば、もう少し時間がかかります。'],
    examplesZh: ['从这个情况看，好像来得及。', '从经验来看，还要再花些时间。'],
    furigana: 'この ようすから すると、まにあい そうです。',
    commonMistakesZh: '后面接判断、推测，不接事实的叙述',
    learnerFocus: '「からすると」＝根据…判断。是阅读中判断根据的信号',
    similarPatterns: ['〜から見ると', '〜によれば'],
    contrast: '「からすると」＝判断の根拠；「によれば」＝情報の出どころ',
    recognition: {
      promptZh: '「この様子からすると」后面最可能接什么？',
      options: ['間に合いそうだ', '様子を見た', '様子が好きだ', '様子を作った'],
      answerIndex: 0,
      distractorReason: '「からすると」の後ろは判断や推測が来る',
      distractorReasonZh: '「からすると」后面接判断或推测',
      explanationZh: '「〜からすると」＝从…来判断',
    },
    production: {
      promptJa: '根拠を示して判断を「〜からすると」で言ってください。',
      promptZh: '用「〜からすると」给出依据并作判断。',
      expected: ['からすると'], acceptable: ['からすれば'],
    },
    practice: {
      themeJa: '根拠のある予想', starterJa: '今の様子から何が予想できますか？',
      starterZh: '从现在的情况能预测什么？', targetUse: '〜からすると',
    },
    matchKeys: ['からすると', 'からすれば'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-108', pattern: '〜に則って', reading: 'にのっとって', unit: 8,
    meaningJa: '〜に従って（規則・伝統）',
    explanationZh: '依照…（规则、传统）',
    formation: '名詞＋に則って',
    usageScene: '说明按照既定规则或惯例进行',
    nuance: '規則・伝統・手順など、決まっているものに従う',
    register: 'written',
    examplesJa: ['規則に則って審査を行います。', '古くからの作法に則って進めました。'],
    examplesZh: ['依照规则进行审查。', '按照自古以来的礼法推进。'],
    furigana: 'きそくに のっとって しんさを おこないます。',
    commonMistakesZh: '前面是规则、传统等。不接人或感情',
    learnerFocus: '「に則って」＝依规矩。公文里的高频表达',
    similarPatterns: ['〜に従って', '〜に基づいて'],
    contrast: '「に則って」＝規則・伝統に従う；「に基づいて」＝資料や根拠をもとにする',
    recognition: {
      promptZh: '「規則に則って」是什么意思？',
      options: ['依照规则', '违反规则', '制定规则', '不管规则'],
      answerIndex: 0,
      distractorReason: '「に則って」は決まりに従う意味',
      distractorReasonZh: '「に則って」意为遵照规定',
      explanationZh: '「〜に則って」＝依照…',
    },
    production: {
      promptJa: '決まりに従うことを「〜に則って」で言ってください。',
      promptZh: '用「〜に則って」说一件按规定进行的事。',
      expected: ['に則って'], acceptable: ['にのっとって'],
    },
    practice: {
      themeJa: '決まりに従う場面', starterJa: '職場で必ず守る手順はありますか？',
      starterZh: '职场里有必须遵守的流程吗？', targetUse: '〜に則って',
    },
    matchKeys: ['に則って', 'にのっとって'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-109', pattern: '〜に照らして', reading: 'にてらして', unit: 8,
    meaningJa: '〜と比べて確かめて',
    explanationZh: '对照…；参照…来判断',
    formation: '名詞＋に照らして',
    usageScene: '对照标准或法律来判断',
    nuance: '基準と突き合わせる意味。「に則って」より判断の色が強い',
    register: 'written',
    examplesJa: ['法律に照らして問題がないか確かめます。', '過去の例に照らして判断しました。'],
    examplesZh: ['对照法律确认有无问题。', '参照过去的例子作出了判断。'],
    furigana: 'ほうりつに てらして もんだいが ないか たしかめます。',
    commonMistakesZh: '不是「照亮」。这里是「对照…判断」',
    learnerFocus: '「に照らして」的后面是「判断・確認」。这是关键搭配',
    similarPatterns: ['〜に則って', '〜と比べて'],
    contrast: '「に照らして」＝基準と突き合わせて判断；「に則って」＝規則どおりに行う',
    recognition: {
      promptZh: '「法律に照らして」是什么意思？',
      options: ['对照法律（判断）', '照亮法律', '制定法律', '违反法律'],
      answerIndex: 0,
      distractorReason: '「に照らして」は基準と比べて確かめる意味',
      distractorReasonZh: '「に照らして」意为对照基准加以确认',
      explanationZh: '「〜に照らして」＝对照…判断',
    },
    production: {
      promptJa: '基準と比べる場面を「〜に照らして」で言ってください。',
      promptZh: '用「〜に照らして」说一个对照基准判断的场面。',
      expected: ['に照らして'], acceptable: ['にてらして'],
    },
    practice: {
      themeJa: '基準で判断する', starterJa: '何かを判断するとき、何と比べますか？',
      starterZh: '判断事情时你会对照什么？', targetUse: '〜に照らして',
    },
    matchKeys: ['に照らして', 'にてらして'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-110', pattern: '〜を踏まえて', reading: 'をふまえて', unit: 8,
    meaningJa: '〜を前提として考えて',
    explanationZh: '在…的基础上；考虑到…',
    formation: '名詞＋を踏まえて',
    usageScene: '会议中说明基于既有信息推进',
    nuance: '前の情報を土台にして次を考える',
    register: 'written',
    examplesJa: ['前回の反省を踏まえて計画を直しました。', '現場の声を踏まえた対応が必要です。'],
    examplesZh: ['在上次反省的基础上修改了计划。', '需要建立在现场声音之上的应对。'],
    furigana: 'ぜんかいの はんせいを ふまえて けいかくを なおしました。',
    commonMistakesZh: '前面是已有的信息、经验。不接将来的事',
    learnerFocus: '商务场合极常用。「〜を踏まえて」＝在…基础上',
    similarPatterns: ['〜に基づいて', '〜を考慮して'],
    contrast: '「を踏まえて」＝前の経験を土台にする；「に基づいて」＝根拠として使う',
    recognition: {
      promptZh: '「反省を踏まえて」是什么意思？',
      options: ['在反省的基础上', '不去反省', '为了反省', '反省之前'],
      answerIndex: 0,
      distractorReason: '「を踏まえて」は前のことを土台にする意味',
      distractorReasonZh: '「を踏まえて」意为以之前的事为基础',
      explanationZh: '「〜を踏まえて」＝在…的基础上',
    },
    production: {
      promptJa: '前の経験を生かす言い方を「〜を踏まえて」で作ってください。',
      promptZh: '用「〜を踏まえて」造一句活用以往经验的话。',
      expected: ['を踏まえ'], acceptable: ['を踏まえて'],
    },
    practice: {
      themeJa: '経験を次に生かす', starterJa: '前の失敗をどう生かしますか？',
      starterZh: '你会怎样把上次的失败用在下次？', targetUse: '〜を踏まえて',
    },
    matchKeys: ['踏まえ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-111', pattern: '〜をめぐって', reading: 'をめぐって', unit: 8,
    meaningJa: '〜について（意見が対立して）',
    explanationZh: '围绕…（展开争论）',
    formation: '名詞＋をめぐって',
    usageScene: '报道中说明争议的焦点',
    nuance: '後ろは議論・対立・争いが来ることが多い',
    register: 'written',
    examplesJa: ['料金の値上げをめぐって議論が続いています。', '土地の使い方をめぐる対立がありました。'],
    examplesZh: ['围绕涨价的讨论仍在继续。', '存在着围绕土地用途的对立。'],
    furigana: 'りょうきんの ねあげを めぐって ぎろんが つづいて います。',
    commonMistakesZh: '后面接争论、对立。单纯的说明用「について」',
    learnerFocus: '「をめぐって」＝有争议的话题。新闻里的高频表达',
    similarPatterns: ['〜について', '〜に関して'],
    contrast: '「をめぐって」＝対立・議論を含む；「について」＝中立に話題を示す',
    recognition: {
      promptZh: '「値上げをめぐって」后面最可能接什么？',
      options: ['議論が続いている', '買い物をした', '天気がよかった', '料理を作った'],
      answerIndex: 0,
      distractorReason: '「をめぐって」の後ろは議論や対立が来る',
      distractorReasonZh: '「をめぐって」后面接争论或对立',
      explanationZh: '「〜をめぐって」＝围绕…（展开争论）',
    },
    production: {
      promptJa: '議論になっている話題を「〜をめぐって」で言ってください。',
      promptZh: '用「〜をめぐって」说一个有争议的话题。',
      expected: ['をめぐ'], acceptable: ['をめぐって'],
    },
    practice: {
      themeJa: '議論になっている問題', starterJa: '最近議論になっている話題はありますか？',
      starterZh: '最近有什么有争议的话题？', targetUse: '〜をめぐって',
    },
    matchKeys: ['をめぐ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-112', pattern: '〜に至って', reading: 'にいたって', unit: 8,
    meaningJa: '〜という段階になって、やっと',
    explanationZh: '到了…的地步，才…',
    formation: '名詞／動詞辞書形＋に至って',
    usageScene: '说明事态严重后才有反应',
    nuance: '「今ごろになってやっと」という遅さの含みがある',
    register: 'written',
    examplesJa: ['事故が起きるに至って、ようやく対策が取られました。', 'ここに至って、方針を変えるのは難しいです。'],
    examplesZh: ['直到发生事故，才终于采取了对策。', '到了这个地步，改变方针很困难。'],
    furigana: 'じこが おきるに いたって、ようやく たいさくが とられました。',
    commonMistakesZh: '带有「太晚了」的批评语气。中性的时点用「〜になって」',
    learnerFocus: '常与「ようやく」「やっと」搭配。表示反应迟',
    similarPatterns: ['〜になって', '〜に至っては'],
    contrast: '「に至って」＝深刻な段階になってやっと；「になって」＝ただの時点',
    recognition: {
      promptZh: '「事故が起きるに至って」是什么意思？',
      options: ['直到发生事故（才…）', '为了不发生事故', '事故没有发生', '事故发生之前'],
      answerIndex: 0,
      distractorReason: '「に至って」は深刻な段階になってやっと、という意味',
      distractorReasonZh: '「に至って」表示到了严重阶段才…',
      explanationZh: '「〜に至って」＝到了…的地步才…',
    },
    production: {
      promptJa: '対応が遅れた例を「〜に至って」で言ってください。',
      promptZh: '用「〜に至って」说一个应对迟缓的例子。',
      expected: ['に至って'], acceptable: ['にいたって'],
    },
    practice: {
      themeJa: '対応が遅れた話', starterJa: '問題が大きくなってから動いた例を知っていますか？',
      starterZh: '你知道问题闹大后才行动的例子吗？', targetUse: '〜に至って',
    },
    matchKeys: ['に至って'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-113', pattern: '〜に至っては', reading: 'にいたっては', unit: 8,
    meaningJa: '（極端な例として）〜の場合はとくにひどい',
    explanationZh: '至于…更是…。举出最极端的例子',
    formation: '名詞＋に至っては',
    usageScene: '列举后指出其中最严重的一例',
    nuance: '後ろは驚くような程度が来る',
    register: 'written',
    examplesJa: ['遅刻が多く、昨日に至っては連絡もありませんでした。', '値上がりが続き、今月に至っては二倍です。'],
    examplesZh: ['经常迟到，昨天更是连联系都没有。', '持续涨价，这个月更是涨了一倍。'],
    furigana: 'ちこくが おおく、きのうに いたっては れんらくも ありません でした。',
    commonMistakesZh: '前面要有铺垫（一般的情况），后面才是最极端的例子',
    learnerFocus: '「に至っては」是列举的最后一步。前面通常已有例子',
    similarPatterns: ['〜ときたら', '〜となると'],
    contrast: '「に至っては」＝一連の中で最も極端な例；「に至って」＝時点の遅さ',
    recognition: {
      promptZh: '「昨日に至っては」是什么意思？',
      options: ['至于昨天更是…', '到了昨天为止', '昨天之前', '不是昨天'],
      answerIndex: 0,
      distractorReason: '「に至っては」は極端な例を取り上げる',
      distractorReasonZh: '「に至っては」用于举出最极端的例子',
      explanationZh: '「〜に至っては」＝至于…更是…',
    },
    production: {
      promptJa: '一番ひどい例を「〜に至っては」で言ってください。',
      promptZh: '用「〜に至っては」说出最严重的一例。',
      expected: ['に至っては'], acceptable: ['にいたっては'],
    },
    practice: {
      themeJa: '程度がひどい例', starterJa: '同じ問題の中で一番ひどかった例は？',
      starterZh: '同类问题中最严重的一例是什么？', targetUse: '〜に至っては',
    },
    matchKeys: ['に至っては'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-114', pattern: '〜ときたら', reading: 'ときたら', unit: 8,
    meaningJa: '〜については（不満だ）',
    explanationZh: '说起…（就来气）。用于抱怨',
    formation: '名詞＋ときたら',
    usageScene: '口语中抱怨身边的人或事',
    nuance: '後ろは不満や批判。身近な相手に使う',
    register: 'spoken',
    examplesJa: ['うちの上司ときたら、いつも急に予定を変えます。', 'この機械ときたら、すぐに止まります。'],
    examplesZh: ['说起我们上司，总是突然改变安排。', '说起这台机器，动不动就停。'],
    furigana: 'うちの じょうしと きたら、いつも きゅうに よていを かえます。',
    commonMistakesZh: '不用于尊敬的对象。语气随便，带抱怨',
    learnerFocus: '「〜ときたら」出现在会话里几乎一定接抱怨',
    similarPatterns: ['〜は', '〜に至っては'],
    contrast: '「ときたら」＝身近な相手への不満（話し言葉）；「に至っては」＝書き言葉で極端な例',
    recognition: {
      promptZh: '「うちの上司ときたら」后面最可能接什么？',
      options: ['いつも急に予定を変える', 'とても親切だ', '昇進した', '出張した'],
      answerIndex: 0,
      distractorReason: '「ときたら」の後ろは不満が来る',
      distractorReasonZh: '「ときたら」后面接不满',
      explanationZh: '「〜ときたら」＝说起…（就来气）',
    },
    production: {
      promptJa: '身近な不満を「〜ときたら」で言ってください。',
      promptZh: '用「〜ときたら」说一个身边的不满。',
      expected: ['ときたら'], acceptable: [],
    },
    practice: {
      themeJa: '身近な不満', starterJa: '身の回りで困っていることはありますか？',
      starterZh: '身边有什么让你为难的事？', targetUse: '〜ときたら',
    },
    matchKeys: ['ときたら'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-115', pattern: '〜にかかっている', reading: 'にかかっている', unit: 8,
    meaningJa: '〜によって決まる',
    explanationZh: '取决于…；关键在于…',
    formation: '名詞／疑問詞を含む句＋にかかっている',
    usageScene: '强调成败的关键',
    nuance: '重要な条件を一つに絞って示す',
    register: 'written',
    examplesJa: ['成功は準備にかかっています。', '続くかどうかは本人の気持ちにかかっている。'],
    examplesZh: ['成功取决于准备。', '能否持续取决于本人的心情。'],
    furigana: 'せいこうは じゅんびに かかって います。',
    commonMistakesZh: '不是「挂着」。这里是「取决于」',
    learnerFocus: '与「〜次第だ」意思接近。「にかかっている」更强调关键',
    similarPatterns: ['〜次第だ', '〜による'],
    contrast: '「にかかっている」＝成否の鍵；「次第だ」＝条件によって変わる',
    recognition: {
      promptZh: '「準備にかかっている」是什么意思？',
      options: ['取决于准备', '正在准备', '准备好了', '不用准备'],
      answerIndex: 0,
      distractorReason: '「にかかっている」は「〜で決まる」の意味',
      distractorReasonZh: '「にかかっている」意为「取决于…」',
      explanationZh: '「〜にかかっている」＝取决于…',
    },
    production: {
      promptJa: '成功の鍵を「〜にかかっている」で言ってください。',
      promptZh: '用「〜にかかっている」说说成功的关键。',
      expected: ['にかかっている'], acceptable: ['にかかっています'],
    },
    practice: {
      themeJa: '成功の鍵', starterJa: 'うまくいくかどうかは何で決まると思いますか？',
      starterZh: '你觉得成败取决于什么？', targetUse: '〜にかかっている',
    },
    matchKeys: ['にかかっている'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-116', pattern: '〜いかんによらず', reading: 'いかんによらず', unit: 8,
    meaningJa: '〜がどうであっても関係なく',
    explanationZh: '无论…如何都…',
    formation: '名詞（＋の）＋いかんによらず／いかんにかかわらず',
    usageScene: '公告中说明条件不影响结果',
    nuance: '「いかんによっては」（条件で変わる）と正反対',
    register: 'written',
    examplesJa: ['理由のいかんによらず、返金はできません。', '結果のいかんにかかわらず、報告します。'],
    examplesZh: ['无论理由如何，都不能退款。', '无论结果如何，都会报告。'],
    furigana: 'りゆうの いかんに よらず、へんきんは できません。',
    commonMistakesZh: '与「いかんによっては」正好相反，考试常放在一起考',
    learnerFocus: '「によっては」＝会变；「によらず」＝不变。一字之差意思相反',
    similarPatterns: ['〜を問わず', '〜にかかわらず'],
    contrast: '「いかんによらず」＝どうであっても同じ；「いかんによっては」＝条件で結果が変わる',
    recognition: {
      promptZh: '「理由のいかんによらず」是什么意思？',
      options: ['无论理由如何', '视理由而定', '因为有理由', '没有理由'],
      answerIndex: 0,
      distractorReason: '「によらず」は条件に関係ないという意味。「によっては」とは逆',
      distractorReasonZh: '「によらず」表示与条件无关，与「によっては」相反',
      explanationZh: '「〜いかんによらず」＝无论…如何',
    },
    production: {
      promptJa: '条件に関係ない決まりを「〜いかんによらず」で書いてください。',
      promptZh: '用「〜いかんによらず」写一条与条件无关的规定。',
      expected: ['いかんによらず'], acceptable: ['いかんにかかわらず'],
    },
    practice: {
      themeJa: '例外のない決まり', starterJa: '理由に関係なく決まっていることはありますか？',
      starterZh: '有什么规定是不论理由都一样的？', targetUse: '〜いかんによらず',
    },
    matchKeys: ['いかんによらず', 'いかんにかかわらず'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-117', pattern: '〜をいいことに', reading: 'をいいことに', unit: 8,
    meaningJa: '〜を都合よく利用して（よくない行い）',
    explanationZh: '趁着…（做不该做的事）。带批评语气',
    formation: '名詞＋の／動詞・形容詞の普通形＋の＋をいいことに',
    usageScene: '批评有人利用他人的善意或漏洞',
    nuance: '後ろは非難される行為が来る',
    register: 'written',
    examplesJa: ['注意されないのをいいことに、駐車が増えました。', '親切なのをいいことに、頼みすぎてしまいました。'],
    examplesZh: ['趁着没人提醒，停车的越来越多。', '趁着对方好心，拜托得太多了。'],
    furigana: 'ちゅうい されないのを いい ことに、ちゅうしゃが ふえました。',
    commonMistakesZh: '后面接不该做的行为。好的行为不能用',
    learnerFocus: '「いいこと」不是「好事」，而是「好机会」。这是最容易误解的点',
    similarPatterns: ['〜を利用して', '〜に乗じて'],
    contrast: '「をいいことに」＝非難を含む；「を利用して」＝中立に手段を述べる',
    recognition: {
      promptZh: '「注意されないのをいいことに」是什么意思？',
      options: ['趁着没被提醒（做了不该做的）', '因为被提醒了', '为了不被提醒', '提醒之后'],
      answerIndex: 0,
      distractorReason: '「をいいことに」は都合よく利用してよくないことをする意味',
      distractorReasonZh: '「をいいことに」表示趁机做不该做的事',
      explanationZh: '「〜をいいことに」＝趁着…（做不该做的事）',
    },
    production: {
      promptJa: 'よくない行いを「〜をいいことに」で言ってください。',
      promptZh: '用「〜をいいことに」说一件不该做的行为。',
      expected: ['をいいことに'], acceptable: [],
    },
    practice: {
      themeJa: 'ルールが守られない場面', starterJa: '注意する人がいないと乱れることはありますか？',
      starterZh: '有什么事在没人管时就会乱？', targetUse: '〜をいいことに',
    },
    matchKeys: ['をいいことに'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-118', pattern: '〜であれ何であれ', reading: 'であれなんであれ', unit: 8,
    meaningJa: '〜でも、そうでなくても、とにかく',
    explanationZh: '不管是…还是别的，总之…',
    formation: '名詞＋であれ何であれ',
    usageScene: '强调不管什么情况都要做',
    nuance: '「であれ」の強調形。会話でも使える',
    register: 'spoken',
    examplesJa: ['仕事であれ何であれ、約束は守ります。', '雨であれ何であれ、予定どおり行います。'],
    examplesZh: ['不管是工作还是别的，约定都要遵守。', '不管下雨还是怎样，都按计划进行。'],
    furigana: 'しごとで あれ なんで あれ、やくそくは まもります。',
    commonMistakesZh: '后面接不变的方针。不接会变化的内容',
    learnerFocus: '「であれ何であれ」是「であれ」的加强形，语气更坚决',
    similarPatterns: ['〜であれ', '〜にせよ'],
    contrast: '「であれ何であれ」＝強調して例外を認めない；「であれ」＝標準の譲歩',
    recognition: {
      promptZh: '「仕事であれ何であれ」是什么意思？',
      options: ['不管是工作还是别的', '只有工作', '不是工作', '工作以后'],
      answerIndex: 0,
      distractorReason: '「であれ何であれ」はどんな場合でもという強調',
      distractorReasonZh: '「であれ何であれ」强调无论何种情况',
      explanationZh: '「〜であれ何であれ」＝不管是…还是别的',
    },
    production: {
      promptJa: 'どんな場合でも守ることを「〜であれ何であれ」で言ってください。',
      promptZh: '用「〜であれ何であれ」说一件无论如何都会遵守的事。',
      expected: ['であれ何であれ'], acceptable: ['であれ'],
    },
    practice: {
      themeJa: '曲げない方針', starterJa: 'どんなときも変えないことはありますか？',
      starterZh: '有什么是你无论何时都不改变的？', targetUse: '〜であれ何であれ',
    },
    matchKeys: ['であれ何であれ'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-119', pattern: '〜ともあろう〜が', reading: 'ともあろう', unit: 8,
    meaningJa: '〜ほどの立場の人が（なぜ）',
    explanationZh: '身为…竟然…。表示失望和责备',
    formation: '名詞＋ともあろう＋名詞（人）＋が',
    usageScene: '批评有身份的人做出不相称的事',
    nuance: '後ろは驚きや非難。期待とのギャップを表す',
    register: 'written',
    examplesJa: ['責任者ともあろう人が、確認を怠りました。', '専門家ともあろう方が、間違えるとは驚きです。'],
    examplesZh: ['身为负责人，竟然疏于确认。', '身为专家竟然出错，令人吃惊。'],
    furigana: 'せきにんしゃとも あろう ひとが、かくにんを おこたりました。',
    commonMistakesZh: '前面必须是有身份、地位的名词。后面是负面的内容',
    learnerFocus: '「たるもの」是「应该如此」，「ともあろう」是「竟然没做到」',
    similarPatterns: ['〜たるもの', '〜のくせに'],
    contrast: '「ともあろう」＝期待を裏切った非難；「たるもの」＝あるべき姿の主張',
    recognition: {
      promptZh: '「責任者ともあろう人が」后面最可能接什么？',
      options: ['確認を怠った', '立派に務めた', '休みを取った', '出張した'],
      answerIndex: 0,
      distractorReason: '「ともあろう」の後ろは期待を裏切る内容が来る',
      distractorReasonZh: '「ともあろう」后面接辜负期待的内容',
      explanationZh: '「〜ともあろう〜が」＝身为…竟然…',
    },
    production: {
      promptJa: '立場に合わない行動を「〜ともあろう」で言ってください。',
      promptZh: '用「〜ともあろう」说一件与身份不符的行为。',
      expected: ['ともあろう'], acceptable: [],
    },
    practice: {
      themeJa: '立場と行動のずれ', starterJa: '立場に合わないと感じた行動はありますか？',
      starterZh: '有过觉得与身份不符的行为吗？', targetUse: '〜ともあろう',
    },
    matchKeys: ['ともあろう'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-120', pattern: '〜てまで／〜までして', reading: 'てまで／までして', unit: 8,
    meaningJa: 'そこまでの犠牲を払って〜する',
    explanationZh: '甚至不惜…也要…。表示做到了过分的程度',
    formation: '動詞て形＋まで／名詞＋までして',
    usageScene: '评价某人为达目的付出过度的代价',
    nuance: '「そこまでする必要があるのか」という気持ちを含むことが多い',
    register: 'written',
    examplesJa: ['借金をしてまで買う必要はありません。', '徹夜までして準備しました。'],
    examplesZh: ['没必要不惜借钱去买。', '甚至熬了通宵来准备。'],
    furigana: 'しゃっきんを して まで かう ひつようは ありません。',
    commonMistakesZh: '动词用「てまで」，名词用「までして」。接续要区分',
    learnerFocus: '后面常接「必要はない」「〜たくない」等否定的评价',
    similarPatterns: ['〜ほどまでに', '〜さえして'],
    contrast: '「てまで」＝行き過ぎた手段への評価；「ても」＝ただの逆接',
    recognition: {
      promptZh: '「借金をしてまで買う」是什么意思？',
      options: ['不惜借钱也要买', '借了钱就不买', '买了以后借钱', '不借钱地买'],
      answerIndex: 0,
      distractorReason: '「てまで」はそこまでの犠牲を払ってという意味',
      distractorReasonZh: '「てまで」表示不惜付出那样的代价',
      explanationZh: '「〜てまで」＝甚至不惜…也要…',
    },
    production: {
      promptJa: 'そこまでする必要はないことを「〜てまで」で言ってください。',
      promptZh: '用「〜てまで」说一件没必要做到那种程度的事。',
      expected: ['てまで'], acceptable: ['までして'],
    },
    practice: {
      themeJa: 'やりすぎだと思うこと', starterJa: 'そこまでしなくてもいいのに、と思うことは？',
      starterZh: '有什么事你觉得没必要做到那种程度？', targetUse: '〜てまで',
    },
    matchKeys: ['てまで', 'までして'], vocabularyLinks: [],
  }),
];
