// N1文法 Unit 6（15項目 / 断定・強い感情・評価）。
// 例文・訳・解説はすべて自社で書き起こす。
import { n1g, type N1GrammarDraft } from './n1GrammarDrafts';

export const N1_GRAMMAR_DRAFTS_UNIT6: N1GrammarDraft[] = [
  n1g({
    grammarId: 'n1g-076', pattern: '〜にほかならない', reading: 'にほかならない', unit: 6,
    meaningJa: 'まさに〜だ（それ以外ではない）',
    explanationZh: '正是…；无非是…。用于断定原因或本质',
    formation: '名詞＋にほかならない',
    usageScene: '论说文中断定原因',
    nuance: '強い断定。話し言葉では使わない',
    register: 'written',
    examplesJa: ['成功は努力の結果にほかなりません。', 'この問題は制度の欠陥にほかならない。'],
    examplesZh: ['成功正是努力的结果。', '这个问题无非是制度的缺陷。'],
    furigana: 'せいこうは どりょくの けっかに ほかなりません。',
    commonMistakesZh: '前面接名词。不接动词句',
    learnerFocus: '＝「まさに〜だ」。看到就理解为强烈的断定',
    similarPatterns: ['〜に違いない', '〜そのものだ'],
    contrast: '「にほかならない」＝断定（＝である）；「に違いない」＝推測（きっとそうだ）',
    recognition: {
      promptZh: '「努力の結果にほかならない」是什么意思？',
      options: ['正是努力的结果', '大概是努力的结果', '不是努力的结果', '努力之外的结果'],
      answerIndex: 0,
      distractorReason: '「にほかならない」は推測ではなく断定',
      distractorReasonZh: '「にほかならない」是断定，不是推测',
      explanationZh: '「〜にほかならない」＝正是…',
    },
    production: {
      promptJa: '原因を断定して「〜にほかならない」で言ってください。',
      promptZh: '用「〜にほかならない」断定一个原因。',
      expected: ['にほかならない'], acceptable: ['にほかなりません'],
    },
    practice: {
      themeJa: '成果の理由を断定する', starterJa: 'うまくいった一番の理由は何だと思いますか？',
      starterZh: '你觉得成功最主要的原因是什么？', targetUse: '〜にほかならない',
    },
    matchKeys: ['ほかならない'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-077', pattern: '〜に相違ない', reading: 'にそういない', unit: 6,
    meaningJa: 'きっと〜だ',
    explanationZh: '一定是…。是「に違いない」的书面语',
    formation: '名詞／動詞・形容詞の普通形＋に相違ない',
    usageScene: '正式文书中表达确信的推测',
    nuance: '根拠のある強い推測。断定ではない',
    register: 'written',
    examplesJa: ['本人が書いた文書に相違ありません。', '準備に時間がかかったに相違ない。'],
    examplesZh: ['这确实是本人所写的文件。', '一定是准备花了不少时间。'],
    furigana: 'ほんにんが かいた ぶんしょに そうい ありません。',
    commonMistakesZh: '与断定的「にほかならない」不同，这里仍是推测',
    learnerFocus: '「に相違ない」＝「に違いない」。文书里常见「相違ありません」',
    similarPatterns: ['〜に違いない', '〜はずだ'],
    contrast: '「に相違ない」＝硬い推測；「にほかならない」＝断定',
    recognition: {
      promptZh: '「に相違ない」最接近下面哪一个？',
      options: ['に違いない', 'かもしれない', 'わけがない', 'にすぎない'],
      answerIndex: 0,
      distractorReason: '「に相違ない」は確信のある推測',
      distractorReasonZh: '「に相違ない」是有把握的推测',
      explanationZh: '「〜に相違ない」＝一定是…',
    },
    production: {
      promptJa: '確信のある推測を「〜に相違ない」で言ってください。',
      promptZh: '用「〜に相違ない」说一个有把握的推测。',
      expected: ['に相違ない'], acceptable: ['に相違ありません'],
    },
    practice: {
      themeJa: '確かだと思うこと', starterJa: '証拠から見て確かだと思うことはありますか？',
      starterZh: '有什么是你从证据看认为确凿的？', targetUse: '〜に相違ない',
    },
    matchKeys: ['相違ない', '相違あり'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-078', pattern: '〜てしかるべきだ', reading: 'てしかるべきだ', unit: 6,
    meaningJa: '当然〜するべきだ',
    explanationZh: '理应…；应当…。带有要求的语气',
    formation: '動詞て形＋しかるべきだ',
    usageScene: '社论中主张理应采取的措施',
    nuance: '「べきだ」より硬く、当然さが強い',
    register: 'written',
    examplesJa: ['説明があってしかるべきだと思います。', '被害者には補償がなされてしかるべきです。'],
    examplesZh: ['我认为理应有个说明。', '对受害者理应给予补偿。'],
    furigana: 'せつめいが あって しかるべき だと おもいます。',
    commonMistakesZh: '不用于日常小事。用于主张正当性的场合',
    learnerFocus: '＝「当然〜すべきだ」。是评论文里的主张句型',
    similarPatterns: ['〜べきだ', '〜て当然だ'],
    contrast: '「てしかるべきだ」＝当然そうあるべき（硬い主張）；「べきだ」＝一般的な義務',
    recognition: {
      promptZh: '「説明があってしかるべきだ」是什么意思？',
      options: ['理应有个说明', '说明已经有了', '不需要说明', '说明太多了'],
      answerIndex: 0,
      distractorReason: '「てしかるべきだ」は当然そうあるべきだという主張',
      distractorReasonZh: '「てしかるべきだ」表示理应如此的主张',
      explanationZh: '「〜てしかるべきだ」＝理应…',
    },
    production: {
      promptJa: '当然あるべきことを「〜てしかるべきだ」で言ってください。',
      promptZh: '用「〜てしかるべきだ」说一件理应如此的事。',
      expected: ['しかるべき'], acceptable: ['てしかるべきだ'],
    },
    practice: {
      themeJa: '当然だと思う対応', starterJa: '本来こうあるべきだと思うことはありますか？',
      starterZh: '有什么是你觉得本该如此的？', targetUse: '〜てしかるべきだ',
    },
    matchKeys: ['しかるべき'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-079', pattern: '〜までもない', reading: 'までもない', unit: 6,
    meaningJa: '〜する必要がないほど当たり前だ',
    explanationZh: '用不着…；不必…。因为太明显',
    formation: '動詞辞書形＋までもない',
    usageScene: '说明不必特意说明或确认',
    nuance: '「言うまでもない」が代表的な形',
    register: 'written',
    examplesJa: ['言うまでもなく、安全が第一です。', 'わざわざ行くまでもない用件でした。'],
    examplesZh: ['不用说，安全第一。', '那是用不着特意跑一趟的事。'],
    furigana: 'いう までも なく、あんぜんが だいいちです。',
    commonMistakesZh: '不是「不能做」，而是「没必要做」',
    learnerFocus: '「言うまでもなく」是阅读的高频开头。整句记住',
    similarPatterns: ['〜必要がない', '〜には及ばない'],
    contrast: '「までもない」＝当たり前だから不要；「には及ばない」＝そこまでしなくてよい（遠慮）',
    recognition: {
      promptZh: '「言うまでもない」是什么意思？',
      options: ['不用说（也很明显）', '不能说', '不想说', '说不出来'],
      answerIndex: 0,
      distractorReason: '「までもない」は必要がないという意味',
      distractorReasonZh: '「までもない」表示没有必要',
      explanationZh: '「〜までもない」＝用不着…',
    },
    production: {
      promptJa: '当たり前のことを「言うまでもなく」で言ってください。',
      promptZh: '用「言うまでもなく」说一件理所当然的事。',
      expected: ['までもない'], acceptable: ['までもなく'],
    },
    practice: {
      themeJa: '当たり前のこと', starterJa: '仕事で一番大事なことは何ですか？',
      starterZh: '工作中最重要的是什么？', targetUse: '〜までもない',
    },
    matchKeys: ['までもない', 'までもなく'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-080', pattern: '〜には及ばない', reading: 'にはおよばない', unit: 6,
    meaningJa: 'そこまでする必要はない／〜ほどではない',
    explanationZh: '不必…；比不上…。有两个意思',
    formation: '動詞辞書形／名詞＋には及ばない',
    usageScene: '婉拒对方的好意，或比较两者高下',
    nuance: '相手の心配や好意をやわらかく断るときにも使う',
    register: 'written',
    examplesJa: ['ご心配には及びません。', '味では本店には及びません。'],
    examplesZh: ['不必担心。', '味道上比不上总店。'],
    furigana: 'ごしんぱいには およびません。',
    commonMistakesZh: '两个意思要看前面：动词→不必；名词→比不上',
    learnerFocus: '「ご心配には及びません」是很有用的商务表达，整句记住',
    similarPatterns: ['〜までもない', '〜ほどではない'],
    contrast: '「には及ばない」＝遠慮・比較；「までもない」＝当たり前だから不要',
    recognition: {
      promptZh: '「ご心配には及びません」是什么意思？',
      options: ['不必担心', '很担心', '请担心', '不能担心'],
      answerIndex: 0,
      distractorReason: '「には及ばない」は「その必要はない」の意味',
      distractorReasonZh: '「には及ばない」意为「没有那个必要」',
      explanationZh: '「〜には及ばない」＝不必…',
    },
    production: {
      promptJa: '相手の心配をやわらかく断る言い方を作ってください。',
      promptZh: '造一句婉拒对方担心的说法。',
      expected: ['には及ば'], acceptable: ['には及びません'],
    },
    practice: {
      themeJa: 'やわらかく断る', starterJa: '心配してくれた人に何と返しますか？',
      starterZh: '别人担心你时你怎么回应？', targetUse: '〜には及ばない',
    },
    matchKeys: ['には及ば'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-081', pattern: '〜に足る', reading: 'にたる', unit: 6,
    meaningJa: '〜するだけの価値がある',
    explanationZh: '值得…；足以…',
    formation: '動詞辞書形／名詞＋に足る',
    usageScene: '评价某事物有足够的价值',
    nuance: '「信頼に足る」「読むに足る」など評価の語と組む',
    register: 'written',
    examplesJa: ['信頼に足る相手だと感じました。', '読むに足る記事が少なくなりました。'],
    examplesZh: ['我觉得他是值得信赖的人。', '值得一读的报道变少了。'],
    furigana: 'しんらいに たる あいてだと かんじました。',
    commonMistakesZh: '否定形是「〜に足りない」。「に足らない」也可以',
    learnerFocus: '「信頼に足る」是最常见的搭配。先记这个',
    similarPatterns: ['〜に値する', '〜だけの価値がある'],
    contrast: '「に足る」＝条件を満たすだけの十分さ；「に値する」＝それだけの価値がある（評価）',
    recognition: {
      promptZh: '「信頼に足る」是什么意思？',
      options: ['值得信赖', '不能信赖', '想要信赖', '信赖过了'],
      answerIndex: 0,
      distractorReason: '「に足る」は十分な価値があるという意味',
      distractorReasonZh: '「に足る」表示具有足够的价值',
      explanationZh: '「〜に足る」＝值得…',
    },
    production: {
      promptJa: '信頼できる人を「〜に足る」で表してください。',
      promptZh: '用「〜に足る」形容一个值得信赖的人。',
      expected: ['に足る'], acceptable: ['に足りる'],
    },
    practice: {
      themeJa: '信頼できる人', starterJa: '信頼できる人の条件は何ですか？',
      starterZh: '值得信赖的人有什么条件？', targetUse: '〜に足る',
    },
    matchKeys: ['に足る'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-082', pattern: '〜の至り', reading: 'のいたり', unit: 6,
    meaningJa: '非常に〜だ（気持ちの極み）',
    explanationZh: '…之至。用于正式致辞表达强烈感情',
    formation: '名詞＋の至り',
    usageScene: '典礼、致辞中表达荣幸或惭愧',
    nuance: '「光栄の至り」「赤面の至り」など決まった形',
    register: 'written',
    examplesJa: ['お招きいただき、光栄の至りです。', '準備不足で、赤面の至りです。'],
    examplesZh: ['承蒙邀请，荣幸之至。', '准备不足，惭愧之至。'],
    furigana: 'おまねき いただき、こうえいの いたりです。',
    commonMistakesZh: '只接有限的名词。不能自由组合',
    learnerFocus: '记住「光栄の至り」一个就能应付致辞场合',
    similarPatterns: ['〜の極み', '〜極まりない'],
    contrast: '「の至り」＝気持ちの極み（あいさつ）；「の極み」＝状態の極み（贅沢の極み）',
    recognition: {
      promptZh: '「光栄の至り」是什么意思？',
      options: ['荣幸之至', '不太荣幸', '荣幸之前', '荣幸的地方'],
      answerIndex: 0,
      distractorReason: '「の至り」は感情の程度が最高であることを表す',
      distractorReasonZh: '「の至り」表示情感达到极点',
      explanationZh: '「〜の至り」＝…之至',
    },
    production: {
      promptJa: 'あいさつで気持ちを「〜の至り」で言ってください。',
      promptZh: '用「〜の至り」在致辞中表达心情。',
      expected: ['の至り'], acceptable: [],
    },
    practice: {
      themeJa: 'あいさつの表現', starterJa: '招かれたときのあいさつを考えてみましょう。',
      starterZh: '想一想受邀时的致辞。', targetUse: '〜の至り',
    },
    matchKeys: ['の至り'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-083', pattern: '〜の極み', reading: 'のきわみ', unit: 6,
    meaningJa: 'これ以上ない〜の状態',
    explanationZh: '…之极；极其…',
    formation: '名詞＋の極み',
    usageScene: '强调状态达到了顶点',
    nuance: 'よい意味にも悪い意味にも使える',
    register: 'written',
    examplesJa: ['連日の残業で疲労の極みでした。', '手作りの料理は贅沢の極みだと感じます。'],
    examplesZh: ['连日加班，疲惫至极。', '我觉得手工菜肴是极致的奢侈。'],
    furigana: 'れんじつの ざんぎょうで ひろうの きわみでした。',
    commonMistakesZh: '前面接名词。不接动词',
    learnerFocus: '「の至り」偏感情、「の極み」偏状态。搭配的名词不同',
    similarPatterns: ['〜の至り', '〜極まりない'],
    contrast: '「の極み」＝状態の頂点；「の至り」＝あいさつでの感情の極み',
    recognition: {
      promptZh: '「疲労の極み」是什么意思？',
      options: ['疲惫至极', '有点累', '不累', '累之前'],
      answerIndex: 0,
      distractorReason: '「の極み」は程度が最高であることを表す',
      distractorReasonZh: '「の極み」表示程度达到顶点',
      explanationZh: '「〜の極み」＝…之极',
    },
    production: {
      promptJa: '極端な状態を「〜の極み」で言ってください。',
      promptZh: '用「〜の極み」形容一个极端的状态。',
      expected: ['の極み'], acceptable: [],
    },
    practice: {
      themeJa: '極端だった経験', starterJa: '今までで一番疲れたのはいつですか？',
      starterZh: '你至今最累的是什么时候？', targetUse: '〜の極み',
    },
    matchKeys: ['の極み'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-084', pattern: '〜極まりない', reading: 'きわまりない', unit: 6,
    meaningJa: '非常に〜だ（悪い意味で）',
    explanationZh: '极其…（多用于负面评价）',
    formation: 'な形容詞語幹＋極まりない',
    usageScene: '强烈批评某种状态',
    nuance: 'ほとんど否定的な評価に使う',
    register: 'written',
    examplesJa: ['あの対応は失礼極まりないと思いました。', '危険極まりない行為が問題になっています。'],
    examplesZh: ['我觉得那种应对极其失礼。', '极其危险的行为正成为问题。'],
    furigana: 'あの たいおうは しつれい きわまりない と おもいました。',
    commonMistakesZh: '一般不用于好的评价。「うれしい極まりない」不自然',
    learnerFocus: '「極まりない」＝「極まる」。两个形式意思相同，这一点考试常考',
    similarPatterns: ['〜の極み', '〜この上ない'],
    contrast: '「極まりない」＝悪い評価に偏る；「この上ない」＝よい意味にも使える',
    recognition: {
      promptZh: '哪个句子用「極まりない」自然？',
      options: ['失礼極まりない態度だ', 'うれしい極まりない話だ', '安い極まりない店だ', '静か極まりない声だ'],
      answerIndex: 0,
      distractorReason: '「極まりない」はよくない評価に使う',
      distractorReasonZh: '「極まりない」用于负面评价',
      explanationZh: '「〜極まりない」＝极其…（负面）',
    },
    production: {
      promptJa: 'よくない状態を「〜極まりない」で言ってください。',
      promptZh: '用「〜極まりない」形容一个很糟的状态。',
      expected: ['極まりない'], acceptable: ['極まる'],
    },
    practice: {
      themeJa: '許せない対応', starterJa: '失礼だと感じた対応はありますか？',
      starterZh: '有过让你觉得失礼的应对吗？', targetUse: '〜極まりない',
    },
    matchKeys: ['極まりない', '極まる'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-085', pattern: '〜といったらない', reading: 'といったらない', unit: 6,
    meaningJa: '言葉にできないほど〜だ',
    explanationZh: '…得没法说；非常…。口语的强调',
    formation: '名詞／形容詞＋といったらない',
    usageScene: '口语中强调感受的强烈',
    nuance: 'よい意味にも悪い意味にも使えるが、大げさな言い方',
    register: 'spoken',
    examplesJa: ['あの日の暑さといったらありませんでした。', 'うれしいといったらないです。'],
    examplesZh: ['那天热得没法说。', '高兴得没法形容。'],
    furigana: 'あの ひの あつさと いったら ありません でした。',
    commonMistakesZh: '会话中常说「〜といったらない」，书面则用「極まりない」',
    learnerFocus: '「〜といったらない」＝「非常に〜だ」。是很自然的口语强调',
    similarPatterns: ['〜極まりない', '〜この上ない'],
    contrast: '「といったらない」＝話し言葉；「極まりない」＝書き言葉',
    recognition: {
      promptZh: '「暑さといったらない」是什么意思？',
      options: ['热得没法说', '不太热', '不说热', '说了热'],
      answerIndex: 0,
      distractorReason: '「といったらない」は程度が極端であることを表す',
      distractorReasonZh: '「といったらない」表示程度极端',
      explanationZh: '「〜といったらない」＝…得没法说',
    },
    production: {
      promptJa: '強い感想を「〜といったらない」で言ってください。',
      promptZh: '用「〜といったらない」说一个强烈的感受。',
      expected: ['といったら'], acceptable: ['といったらない'],
    },
    practice: {
      themeJa: '忘れられない感覚', starterJa: '一番暑かった日のことを覚えていますか？',
      starterZh: '还记得最热的那天吗？', targetUse: '〜といったらない',
    },
    matchKeys: ['といったら'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-086', pattern: '〜この上ない', reading: 'このうえない', unit: 6,
    meaningJa: 'これ以上ないほど〜だ',
    explanationZh: '再…不过了；无比…',
    formation: '形容詞／な形容詞＋この上ない',
    usageScene: '书面强调程度之高',
    nuance: 'よい意味にも悪い意味にも使える',
    register: 'written',
    examplesJa: ['迎えていただき、うれしいことこの上ありません。', '待たされて不便この上なかったです。'],
    examplesZh: ['承蒙迎接，无比高兴。', '一直等着，别提多不方便了。'],
    furigana: 'むかえて いただき、うれしい こと この うえ ありません。',
    commonMistakesZh: '与「極まりない」不同，好的评价也能用',
    learnerFocus: '「うれしいことこの上ない」的「こと」不要漏掉',
    similarPatterns: ['〜極まりない', '〜の極み'],
    contrast: '「この上ない」＝よい意味にも使える；「極まりない」＝悪い評価が中心',
    recognition: {
      promptZh: '「うれしいことこの上ない」是什么意思？',
      options: ['再高兴不过了', '不太高兴', '高兴之前', '高兴的地方'],
      answerIndex: 0,
      distractorReason: '「この上ない」は最高の程度を表す',
      distractorReasonZh: '「この上ない」表示程度最高',
      explanationZh: '「〜この上ない」＝再…不过了',
    },
    production: {
      promptJa: '最高の気持ちを「〜この上ない」で言ってください。',
      promptZh: '用「〜この上ない」表达最好的心情。',
      expected: ['この上ない'], acceptable: ['この上ありません'],
    },
    practice: {
      themeJa: '一番うれしかったこと', starterJa: '最近一番うれしかったことは何ですか？',
      starterZh: '最近最高兴的事是什么？', targetUse: '〜この上ない',
    },
    matchKeys: ['この上ない', 'この上あり'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-087', pattern: '〜てはばからない', reading: 'てはばからない', unit: 6,
    meaningJa: '遠慮せずに堂々と〜する',
    explanationZh: '毫不顾忌地…。多含批评',
    formation: '動詞て形＋はばからない',
    usageScene: '批评对方肆无忌惮的言行',
    nuance: '主語は自分以外。批判的な文脈が多い',
    register: 'written',
    examplesJa: ['彼は自分が一番だと言ってはばからない。', '批判を口にしてはばからない人でした。'],
    examplesZh: ['他毫不顾忌地说自己最强。', '那是个毫不避讳批评的人。'],
    furigana: 'かれは じぶんが いちばんだと いって はばからない。',
    commonMistakesZh: '不用于自己。基本是「言ってはばからない」的形式',
    learnerFocus: '「はばかる」＝顾忌。「はばからない」＝毫不顾忌',
    similarPatterns: ['〜堂々と', '〜平気で'],
    contrast: '「てはばからない」＝批判の含み；「堂々と」＝ほめる意味にもなる',
    recognition: {
      promptZh: '「言ってはばからない」是什么意思？',
      options: ['毫不顾忌地说', '不敢说', '想说却没说', '说得很小声'],
      answerIndex: 0,
      distractorReason: '「はばからない」は遠慮しないという意味',
      distractorReasonZh: '「はばからない」意为毫不顾忌',
      explanationZh: '「〜てはばからない」＝毫不顾忌地…',
    },
    production: {
      promptJa: '遠慮せずに言う人を「〜てはばからない」で表してください。',
      promptZh: '用「〜てはばからない」形容一个毫不顾忌的人。',
      expected: ['はばからない'], acceptable: [],
    },
    practice: {
      themeJa: '遠慮しない人', starterJa: '思ったことをそのまま言う人をどう思いますか？',
      starterZh: '你怎么看想到什么就说什么的人？', targetUse: '〜てはばからない',
    },
    matchKeys: ['はばからない'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-088', pattern: '〜を禁じ得ない', reading: 'をきんじえない', unit: 6,
    meaningJa: '〜という気持ちを抑えられない',
    explanationZh: '不禁…；难以抑制…的心情',
    formation: '感情の名詞＋を禁じ得ない',
    usageScene: '正式场合表达抑制不住的感情',
    nuance: '「涙」「怒り」「同情」など感情の名詞と組む',
    register: 'written',
    examplesJa: ['報道を見て、驚きを禁じ得ませんでした。', '当時を思い出すと涙を禁じ得ません。'],
    examplesZh: ['看到报道，不禁感到吃惊。', '一想起当时就忍不住流泪。'],
    furigana: 'ほうどうを みて、おどろきを きんじ えません でした。',
    commonMistakesZh: '前面只接感情名词。不接动词',
    learnerFocus: '主语一般是第一人称。是书面表达情感的高级说法',
    similarPatterns: ['〜ずにはいられない', '〜てならない'],
    contrast: '「を禁じ得ない」＝感情の名詞と組む書き言葉；「ずにはいられない」＝動作にも使える',
    recognition: {
      promptZh: '「涙を禁じ得ない」是什么意思？',
      options: ['忍不住流泪', '不许流泪', '不想流泪', '没有流泪'],
      answerIndex: 0,
      distractorReason: '「を禁じ得ない」は気持ちを抑えられないという意味',
      distractorReasonZh: '「を禁じ得ない」意为无法抑制情感',
      explanationZh: '「〜を禁じ得ない」＝不禁…',
    },
    production: {
      promptJa: '抑えられない気持ちを「〜を禁じ得ない」で言ってください。',
      promptZh: '用「〜を禁じ得ない」表达无法抑制的心情。',
      expected: ['禁じ得ない'], acceptable: ['禁じ得ません'],
    },
    practice: {
      themeJa: '心が動いた出来事', starterJa: 'ニュースを見て強く心が動いたことはありますか？',
      starterZh: '有过看新闻深受触动的时候吗？', targetUse: '〜を禁じ得ない',
    },
    matchKeys: ['禁じ得'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-089', pattern: '〜ずにはおかない', reading: 'ずにはおかない', unit: 6,
    meaningJa: '必ず〜させる（自然にそうなる）',
    explanationZh: '必然会使…；不由得让人…',
    formation: '動詞ない形（ない→ず）＋にはおかない',
    usageScene: '说明某事必然引起某种反应',
    nuance: '主語は物や出来事。人の意志ではなく自然な作用',
    register: 'written',
    examplesJa: ['あの映画は見る人を感動させずにはおかない。', 'この決定は議論を呼ばずにはおかないでしょう。'],
    examplesZh: ['那部电影必然让观众感动。', '这个决定必然会引发讨论。'],
    furigana: 'あの えいがは みる ひとを かんどう させずには おかない。',
    commonMistakesZh: '常与使役形搭配：「〜させずにはおかない」',
    learnerFocus: '主语是「事情」，不是人。理解为「必然引起…」',
    similarPatterns: ['〜ないではおかない', '〜ずにはいられない'],
    contrast: '「ずにはおかない」＝事が人にそうさせる；「ずにはいられない」＝自分が我慢できない',
    recognition: {
      promptZh: '「感動させずにはおかない」是什么意思？',
      options: ['必然让人感动', '不让人感动', '想让人感动', '感动之前'],
      answerIndex: 0,
      distractorReason: '「ずにはおかない」は必ずそうさせるという意味',
      distractorReasonZh: '「ずにはおかない」表示必然使之如此',
      explanationZh: '「〜ずにはおかない」＝必然会使…',
    },
    production: {
      promptJa: '必ず人の心を動かすものを「〜ずにはおかない」で言ってください。',
      promptZh: '用「〜ずにはおかない」说一件必然打动人的事。',
      expected: ['ずにはおかない'], acceptable: ['ないではおかない'],
    },
    practice: {
      themeJa: '心を動かす作品', starterJa: '見た人を必ず感動させる作品を知っていますか？',
      starterZh: '你知道必然打动观众的作品吗？', targetUse: '〜ずにはおかない',
    },
    matchKeys: ['ずにはおかない', 'ないではおかない'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-090', pattern: '〜てはかなわない', reading: 'てはかなわない', unit: 6,
    meaningJa: '〜されては困る、我慢できない',
    explanationZh: '…可受不了。表达无法忍受',
    formation: '動詞て形／形容詞くて＋はかなわない',
    usageScene: '抱怨持续的状态让人受不了',
    nuance: '話し言葉。続く状態への不満に使う',
    register: 'spoken',
    examplesJa: ['毎日こんなに暑くてはかないません。', '何度も同じことを聞かれてはかなわない。'],
    examplesZh: ['每天这么热可受不了。', '同样的事被问好几次可受不了。'],
    furigana: 'まいにち こんなに あつくては かないません。',
    commonMistakesZh: '不是「实现」的「かなう」。这里是「受不了」',
    learnerFocus: '「〜てはかなわない」＝「〜のは我慢できない」。会话里很好用',
    similarPatterns: ['〜てはたまらない', '〜ては困る'],
    contrast: '「てはかなわない」＝続く状態への不満；「ては困る」＝一般的に都合が悪い',
    recognition: {
      promptZh: '「暑くてはかなわない」是什么意思？',
      options: ['热得受不了', '不热了', '希望变热', '热也没关系'],
      answerIndex: 0,
      distractorReason: '「てはかなわない」は我慢できないという意味',
      distractorReasonZh: '「てはかなわない」意为无法忍受',
      explanationZh: '「〜てはかなわない」＝…可受不了',
    },
    production: {
      promptJa: '我慢できないことを「〜てはかなわない」で言ってください。',
      promptZh: '用「〜てはかなわない」说一件受不了的事。',
      expected: ['てはかなわない'], acceptable: ['てはかないません'],
    },
    practice: {
      themeJa: '我慢できないこと', starterJa: '毎日続くと困ることは何ですか？',
      starterZh: '什么事天天持续你会受不了？', targetUse: '〜てはかなわない',
    },
    matchKeys: ['てはかなわない', 'てはかない'], vocabularyLinks: [],
  }),
];
