// N1文法 Unit 7（15項目 / 可能・不可能・必然）。
// 例文・訳・解説はすべて自社で書き起こす。
import { n1g, type N1GrammarDraft } from './n1GrammarDrafts';

export const N1_GRAMMAR_DRAFTS_UNIT7: N1GrammarDraft[] = [
  n1g({
    grammarId: 'n1g-091', pattern: '〜ざるを得ない', reading: 'ざるをえない', unit: 7,
    meaningJa: '仕方なく〜するしかない',
    explanationZh: '不得不…。虽然不情愿但没有别的选择',
    formation: '動詞ない形（ない→ざる）＋を得ない（する→せざるを得ない）',
    usageScene: '说明因客观情况只能如此',
    nuance: '本意ではないという気持ちが入る',
    register: 'written',
    examplesJa: ['雨が続き、中止せざるを得ませんでした。', '費用を考えると、あきらめざるを得ません。'],
    examplesZh: ['连日下雨，不得不取消。', '考虑到费用，不得不放弃。'],
    furigana: 'あめが つづき、ちゅうし せざるを えません でした。',
    commonMistakesZh: '「する」变成「せざるを得ない」，不是「しざるを得ない」',
    learnerFocus: '「ざるを得ない」和「を余儀なくされる」都译成「不得不」。前者是自己的判断',
    similarPatterns: ['〜しかない', '〜を余儀なくされる'],
    contrast: '「ざるを得ない」＝自分の判断としても仕方ない；「を余儀なくされる」＝外から強いられる',
    recognition: {
      promptZh: '「中止せざるを得ない」是什么意思？',
      options: ['不得不取消', '不可以取消', '想取消', '取消了'],
      answerIndex: 0,
      distractorReason: '「ざるを得ない」は「〜するしかない」の意味',
      distractorReasonZh: '「ざるを得ない」意为「只能…」',
      explanationZh: '「〜ざるを得ない」＝不得不…',
    },
    production: {
      promptJa: '仕方なく決めたことを「〜ざるを得ない」で言ってください。',
      promptZh: '用「〜ざるを得ない」说一个不得已的决定。',
      expected: ['ざるを得ない'], acceptable: ['ざるを得ません'],
    },
    practice: {
      themeJa: '仕方なかった決断', starterJa: 'あきらめるしかなかったことはありますか？',
      starterZh: '有过只能放弃的事吗？', targetUse: '〜ざるを得ない',
    },
    matchKeys: ['ざるを得'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-092', pattern: '〜ずにはいられない', reading: 'ずにはいられない', unit: 7,
    meaningJa: 'どうしても〜してしまう',
    explanationZh: '忍不住…；不由得…',
    formation: '動詞ない形（ない→ず）＋にはいられない（する→せずにはいられない）',
    usageScene: '说明感情驱使下的行为',
    nuance: '自分の気持ちが抑えられない場合に使う',
    register: 'written',
    examplesJa: ['あの話を聞くと、笑わずにはいられません。', '困っている人を見ると、声をかけずにはいられない。'],
    examplesZh: ['一听那件事就忍不住笑。', '看到有困难的人就忍不住搭话。'],
    furigana: 'あの はなしを きくと、わらわずには いられません。',
    commonMistakesZh: '主语是自己。别人的事用「〜ずにはおかない」等其他形式',
    learnerFocus: '「ずにはいられない」＝自分が我慢できない／「ずにはおかない」＝必然そうさせる',
    similarPatterns: ['〜ないではいられない', '〜てならない'],
    contrast: '「ずにはいられない」＝我慢できない行動；「てならない」＝自然に強く感じる',
    recognition: {
      promptZh: '「笑わずにはいられない」是什么意思？',
      options: ['忍不住笑', '不能笑', '不想笑', '没有笑'],
      answerIndex: 0,
      distractorReason: '「ずにはいられない」は抑えられない気持ちを表す',
      distractorReasonZh: '「ずにはいられない」表示无法抑制的心情',
      explanationZh: '「〜ずにはいられない」＝忍不住…',
    },
    production: {
      promptJa: 'つい してしまうことを「〜ずにはいられない」で言ってください。',
      promptZh: '用「〜ずにはいられない」说一件你忍不住会做的事。',
      expected: ['ずにはいられない'], acceptable: ['ないではいられない'],
    },
    practice: {
      themeJa: 'つい してしまうこと', starterJa: 'つい してしまうことはありますか？',
      starterZh: '有什么是你忍不住会去做的？', targetUse: '〜ずにはいられない',
    },
    matchKeys: ['ずにはいられない', 'ないではいられない'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-093', pattern: '〜てならない', reading: 'てならない', unit: 7,
    meaningJa: '自然に強く〜と感じる',
    explanationZh: '…得不得了；不由得觉得…',
    formation: '動詞て形／形容詞くて＋ならない',
    usageScene: '表达自然涌上来的强烈感受',
    nuance: '気持ちや感覚の語と組む。意志的な動作には使わない',
    register: 'written',
    examplesJa: ['結果が気になってなりません。', '故郷のことが思い出されてなりません。'],
    examplesZh: ['非常在意结果。', '不由得想起故乡。'],
    furigana: 'けっかが きに なって なりません。',
    commonMistakesZh: '与意志动作不搭配。「行ってならない」不成立',
    learnerFocus: '常用的组合：気になってならない・思われてならない・残念でならない',
    similarPatterns: ['〜てたまらない', '〜てしかたがない'],
    contrast: '「てならない」＝自然にわいてくる感情（書き言葉）；「てたまらない」＝身体的な感覚にも使う',
    recognition: {
      promptZh: '「気になってならない」是什么意思？',
      options: ['非常在意', '不在意', '不该在意', '不再在意'],
      answerIndex: 0,
      distractorReason: '「てならない」は感情が自然に強く出ることを表す',
      distractorReasonZh: '「てならない」表示情感自然而强烈地涌现',
      explanationZh: '「〜てならない」＝…得不得了',
    },
    production: {
      promptJa: '気になって仕方ないことを「〜てならない」で言ってください。',
      promptZh: '用「〜てならない」说一件你非常在意的事。',
      expected: ['てならない'], acceptable: ['でならない'],
    },
    practice: {
      themeJa: '気になっていること', starterJa: '今いちばん気になっていることは何ですか？',
      starterZh: '你现在最在意的是什么？', targetUse: '〜てならない',
    },
    matchKeys: ['てならない', 'でならない'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-094', pattern: '〜かねない', reading: 'かねない', unit: 7,
    meaningJa: '〜という悪いことが起こるかもしれない',
    explanationZh: '有可能…（不好的事）',
    formation: '動詞ます形＋かねない',
    usageScene: '提醒可能发生的坏结果',
    nuance: 'よくない可能性にだけ使う',
    register: 'written',
    examplesJa: ['無理を続けると体を壊しかねません。', '確認を忘れると事故になりかねない。'],
    examplesZh: ['继续勉强的话有可能搞坏身体。', '忘记确认有可能酿成事故。'],
    furigana: 'むりを つづけると からだを こわし かねません。',
    commonMistakesZh: '不用于好事。「合格しかねない」不自然',
    learnerFocus: '「かねない」＝可能会（坏事）／「かねる」＝难以做到。两个是反方向',
    similarPatterns: ['〜おそれがある', '〜かもしれない'],
    contrast: '「かねない」＝悪い可能性；「かもしれない」＝良し悪しを問わない可能性',
    recognition: {
      promptZh: '哪个句子用「かねない」自然？',
      options: ['事故になりかねない', '合格しかねない', 'うれしくなりかねない', '成功しかねない'],
      answerIndex: 0,
      distractorReason: '「かねない」はよくない可能性にだけ使う',
      distractorReasonZh: '「かねない」只用于不好的可能性',
      explanationZh: '「〜かねない」＝有可能…（坏事）',
    },
    production: {
      promptJa: '起こりうる悪い結果を「〜かねない」で言ってください。',
      promptZh: '用「〜かねない」说一个可能发生的坏结果。',
      expected: ['かねない'], acceptable: ['かねません'],
    },
    practice: {
      themeJa: '注意したほうがいいこと', starterJa: '放っておくと危ないことは何ですか？',
      starterZh: '什么事放着不管会有危险？', targetUse: '〜かねない',
    },
    matchKeys: ['かねない', 'かねません'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-095', pattern: '〜かねる', reading: 'かねる', unit: 7,
    meaningJa: '（気持ちの上で）〜できない',
    explanationZh: '难以…；不便…。是委婉的拒绝',
    formation: '動詞ます形＋かねる',
    usageScene: '商务场合婉拒或表示无法回答',
    nuance: '能力がないのではなく、立場や気持ちの上でできない',
    register: 'written',
    examplesJa: ['その件はお答えしかねます。', 'ご希望には応じかねる状況です。'],
    examplesZh: ['那件事我难以回答。', '目前难以满足您的要求。'],
    furigana: 'その けんは お こたえ しかねます。',
    commonMistakesZh: '不是「能不能」的问题，而是委婉表示「做不到」',
    learnerFocus: '「〜しかねます」是商务日语最常用的婉拒。整句背下来',
    similarPatterns: ['〜ことができない', '〜わけにはいかない'],
    contrast: '「かねる」＝丁寧な断り；「できない」＝直接的な否定',
    recognition: {
      promptZh: '「お答えしかねます」是什么意思？',
      options: ['难以回答（婉拒）', '会回答', '想回答', '回答完了'],
      answerIndex: 0,
      distractorReason: '「かねる」は丁寧に「できない」と伝える言い方',
      distractorReasonZh: '「かねる」是礼貌地表达「做不到」',
      explanationZh: '「〜かねる」＝难以…（婉拒）',
    },
    production: {
      promptJa: 'ていねいに断る言い方を「〜かねます」で作ってください。',
      promptZh: '用「〜かねます」造一句礼貌的婉拒。',
      expected: ['かねる'], acceptable: ['かねます'],
    },
    practice: {
      themeJa: 'ていねいに断る', starterJa: '仕事で断るとき、どう言いますか？',
      starterZh: '工作中拒绝时你会怎么说？', targetUse: '〜かねる',
    },
    matchKeys: ['かねる', 'かねます'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-096', pattern: '〜がたい', reading: 'がたい', unit: 7,
    meaningJa: '〜するのが難しい',
    explanationZh: '难以…。多与心理动词搭配',
    formation: '動詞ます形＋がたい',
    usageScene: '书面表达难以相信、难以想象',
    nuance: '「信じがたい」「想像しがたい」など決まった組み合わせが多い',
    register: 'written',
    examplesJa: ['信じがたい話ですが、本当だそうです。', '当時の苦労は想像しがたいものでした。'],
    examplesZh: ['虽然难以置信，据说是真的。', '当时的辛苦难以想象。'],
    furigana: 'しんじ がたい はなしですが、ほんとうだ そうです。',
    commonMistakesZh: '与「にくい」不同：「がたい」多用于心理，「にくい」多用于物理',
    learnerFocus: '「食べにくい」不能说「食べがたい」。看动词的性质选择',
    similarPatterns: ['〜にくい', '〜かねる'],
    contrast: '「がたい」＝心理的に難しい（書き言葉）；「にくい」＝物理的にやりにくい',
    recognition: {
      promptZh: '哪个句子用「がたい」自然？',
      options: ['信じがたい話だ', '食べがたい料理だ', '歩きがたい道だ', '書きがたいペンだ'],
      answerIndex: 0,
      distractorReason: '「がたい」は心理的に難しい動詞と組む。物理的な難しさは「にくい」',
      distractorReasonZh: '「がたい」与心理类动词搭配，物理上的困难用「にくい」',
      explanationZh: '「〜がたい」＝难以…（心理上）',
    },
    production: {
      promptJa: '信じられない出来事を「〜がたい」で言ってください。',
      promptZh: '用「〜がたい」说一件难以置信的事。',
      expected: ['がたい'], acceptable: [],
    },
    practice: {
      themeJa: '信じられない話', starterJa: '信じられないような話を聞いたことはありますか？',
      starterZh: '有听过难以置信的事吗？', targetUse: '〜がたい',
    },
    matchKeys: ['がたい'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-097', pattern: '〜得る／〜得ない', reading: 'うる／えない', unit: 7,
    meaningJa: '〜する可能性がある／ない',
    explanationZh: '可能…／不可能…。表示可能性的书面说法',
    formation: '動詞ます形＋得る（うる／える）・得ない（えない）',
    usageScene: '论说文中讨论可能性',
    nuance: '肯定は「うる」とも「える」とも読む。否定は「えない」',
    register: 'written',
    examplesJa: ['誰にでも起こり得ることです。', 'そんな結果はあり得ないと思います。'],
    examplesZh: ['这是谁都可能发生的事。', '我认为那样的结果不可能。'],
    furigana: 'だれにでも おこり うる ことです。',
    commonMistakesZh: '否定形只读「えない」。「うない」是错的',
    learnerFocus: '「あり得ない」是日常也常用的形式。先从这个入手',
    similarPatterns: ['〜可能性がある', '〜かねない'],
    contrast: '「得る」＝可能性の有無を中立に述べる；「かねない」＝悪い可能性に限る',
    recognition: {
      promptZh: '「起こり得る」是什么意思？',
      options: ['可能发生', '已经发生', '不会发生', '希望发生'],
      answerIndex: 0,
      distractorReason: '「得る」は可能性があることを表す',
      distractorReasonZh: '「得る」表示存在可能性',
      explanationZh: '「〜得る」＝可能…',
    },
    production: {
      promptJa: '起こりうることを「〜得る」で言ってください。',
      promptZh: '用「〜得る」说一件可能发生的事。',
      expected: ['得る'], acceptable: ['得ない'],
    },
    practice: {
      themeJa: '起こりうること', starterJa: '誰にでも起こりうることは何だと思いますか？',
      starterZh: '你觉得什么事是谁都可能遇到的？', targetUse: '〜得る',
    },
    matchKeys: ['得る', '得ない'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-098', pattern: '〜べくもない', reading: 'べくもない', unit: 7,
    meaningJa: '〜できるはずがない',
    explanationZh: '根本不可能…。是很强的否定',
    formation: '動詞辞書形＋べくもない',
    usageScene: '书面强调完全没有可能',
    nuance: '「知るべくもない」「望むべくもない」など限られた動詞と組む',
    register: 'written',
    examplesJa: ['当時の事情は知るべくもありません。', '完全な解決は望むべくもない状況です。'],
    examplesZh: ['当时的情形根本无从得知。', '完全的解决根本无从期待。'],
    furigana: 'とうじの じじょうは しる べくも ありません。',
    commonMistakesZh: '不能自由组合。基本上是「知る・望む・比べる」等少数动词',
    learnerFocus: '看到「べくもない」就理解为「まったく〜できない」',
    similarPatterns: ['〜ようがない', '〜はずがない'],
    contrast: '「べくもない」＝文語の強い不可能；「ようがない」＝方法が無いという不可能',
    recognition: {
      promptZh: '「知るべくもない」是什么意思？',
      options: ['根本无从得知', '应该知道', '不想知道', '知道了'],
      answerIndex: 0,
      distractorReason: '「べくもない」は可能性が全く無いことを表す',
      distractorReasonZh: '「べくもない」表示完全没有可能',
      explanationZh: '「〜べくもない」＝根本不可能…',
    },
    production: {
      promptJa: 'まったく分からないことを「知るべくもない」で言ってください。',
      promptZh: '用「知るべくもない」说一件完全无从得知的事。',
      expected: ['べくもない'], acceptable: ['べくもありません'],
    },
    practice: {
      themeJa: '知りようがないこと', starterJa: '調べても分からなかったことはありますか？',
      starterZh: '有过怎么查也查不到的事吗？', targetUse: '〜べくもない',
    },
    matchKeys: ['べくもな'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-099', pattern: '〜ようがない', reading: 'ようがない', unit: 7,
    meaningJa: '〜する方法がない',
    explanationZh: '没法…；无从…。因为没有手段',
    formation: '動詞ます形＋ようがない',
    usageScene: '说明因为缺少条件而无法进行',
    nuance: '方法・手段が無いという理由に限る',
    register: 'spoken',
    examplesJa: ['連絡先が分からず、知らせようがありません。', '壊れ方がひどく、直しようがない。'],
    examplesZh: ['不知道联系方式，没法通知。', '坏得太严重，没法修。'],
    furigana: 'れんらくさきが わからず、しらせ ようが ありません。',
    commonMistakesZh: '强调的是「没有办法」，不是「不想做」',
    learnerFocus: '「〜ようがない」很实用，会话里也常说',
    similarPatterns: ['〜ことができない', '〜べくもない'],
    contrast: '「ようがない」＝手段が無い；「べくもない」＝可能性そのものが無い（硬い）',
    recognition: {
      promptZh: '「知らせようがない」是什么意思？',
      options: ['没法通知', '不想通知', '不许通知', '通知了'],
      answerIndex: 0,
      distractorReason: '「ようがない」は方法が無いという意味',
      distractorReasonZh: '「ようがない」表示没有办法',
      explanationZh: '「〜ようがない」＝没法…',
    },
    production: {
      promptJa: '手段が無くてできないことを「〜ようがない」で言ってください。',
      promptZh: '用「〜ようがない」说一件因没办法而做不到的事。',
      expected: ['ようがない'], acceptable: ['ようがありません'],
    },
    practice: {
      themeJa: '手段がなくて困った話', starterJa: '連絡が取れなくて困ったことはありますか？',
      starterZh: '有过联系不上而为难的经历吗？', targetUse: '〜ようがない',
    },
    matchKeys: ['ようがな'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-100', pattern: '〜っこない', reading: 'っこない', unit: 7,
    meaningJa: '絶対に〜しない',
    explanationZh: '绝不可能…。是口语的强烈否定',
    formation: '動詞ます形＋っこない',
    usageScene: '朋友之间断言不可能',
    nuance: 'くだけた話し言葉。目上には使わない',
    register: 'spoken',
    examplesJa: ['今から行っても間に合いっこないよ。', 'そんな話、信じっこない。'],
    examplesZh: ['现在去也绝对赶不上。', '那种话绝不可能相信。'],
    furigana: 'いまから いっても まにあいっこないよ。',
    commonMistakesZh: '很随便的说法，正式场合用「〜はずがない」',
    learnerFocus: '「っこない」＝「絶対に〜ない」。听力里常出现',
    similarPatterns: ['〜はずがない', '〜わけがない'],
    contrast: '「っこない」＝くだけた話し言葉；「はずがない」＝標準的な否定の推量',
    recognition: {
      promptZh: '「間に合いっこない」是什么意思？',
      options: ['绝对赶不上', '刚好赶上', '可能赶上', '赶上了'],
      answerIndex: 0,
      distractorReason: '「っこない」は強い否定',
      distractorReasonZh: '「っこない」是强烈的否定',
      explanationZh: '「〜っこない」＝绝不可能…',
    },
    production: {
      promptJa: '絶対にできないことを「〜っこない」で言ってください。',
      promptZh: '用「〜っこない」说一件绝对做不到的事。',
      expected: ['っこない'], acceptable: [],
    },
    practice: {
      themeJa: '無理だと思うこと', starterJa: '絶対に無理だと思うことはありますか？',
      starterZh: '有什么是你觉得绝对做不到的？', targetUse: '〜っこない',
    },
    matchKeys: ['っこない'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-101', pattern: '〜までのことだ', reading: 'までのことだ', unit: 7,
    meaningJa: 'だめなら〜するだけだ（覚悟）',
    explanationZh: '大不了…就是了。表示已有心理准备',
    formation: '動詞辞書形＋までのことだ',
    usageScene: '说明退一步的打算',
    nuance: '開き直った覚悟を表す',
    register: 'spoken',
    examplesJa: ['断られたら、また探すまでのことです。', 'だめなら一からやり直すまでのことだ。'],
    examplesZh: ['被拒绝的话，大不了再找就是了。', '不行的话，大不了从头再来。'],
    furigana: 'ことわられたら、また さがす までの ことです。',
    commonMistakesZh: '不是表示范围的「まで」。这里是「大不了…」',
    learnerFocus: '常与假设搭配：「〜たら、〜までのことだ」',
    similarPatterns: ['〜だけだ', '〜ばそれまでだ'],
    contrast: '「までのことだ」＝次善の策を取る覚悟；「ばそれまでだ」＝そこで終わりという諦め',
    recognition: {
      promptZh: '「また探すまでのことだ」是什么意思？',
      options: ['大不了再找就是了', '找到为止', '不用再找', '找过了'],
      answerIndex: 0,
      distractorReason: '「までのことだ」は「〜すればいいだけだ」という覚悟',
      distractorReasonZh: '「までのことだ」表示「大不了…就行」的心理准备',
      explanationZh: '「〜までのことだ」＝大不了…就是了',
    },
    production: {
      promptJa: 'だめだったときの覚悟を「〜までのことだ」で言ってください。',
      promptZh: '用「〜までのことだ」说说失败时的打算。',
      expected: ['までのことだ'], acceptable: ['までのことです'],
    },
    practice: {
      themeJa: 'だめだったときの構え', starterJa: 'うまくいかなかったらどうしますか？',
      starterZh: '如果不顺利你会怎么办？', targetUse: '〜までのことだ',
    },
    matchKeys: ['までのこと'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-102', pattern: '〜ばそれまでだ', reading: 'ばそれまでだ', unit: 7,
    meaningJa: '〜したら、そこで終わりだ',
    explanationZh: '一旦…就完了。强调无可挽回',
    formation: '動詞仮定形＋ばそれまでだ',
    usageScene: '提醒某个结果一旦发生就无法挽回',
    nuance: '警告や諦めの気持ちを含む',
    register: 'spoken',
    examplesJa: ['忘れてしまえばそれまでです。', 'データが消えればそれまでだ。'],
    examplesZh: ['一旦忘了就完了。', '数据一旦消失就完了。'],
    furigana: 'わすれて しまえば それまでです。',
    commonMistakesZh: '与「までのことだ」不同，这里没有「再来一次」的余地',
    learnerFocus: '「ばそれまで」＝到此为止、没有下文。是提醒的说法',
    similarPatterns: ['〜たらおしまいだ', '〜までのことだ'],
    contrast: '「ばそれまでだ」＝取り返しがつかない；「までのことだ」＝次の手がある',
    recognition: {
      promptZh: '「消えればそれまでだ」是什么意思？',
      options: ['一旦消失就完了', '消失也没关系', '不会消失', '消失之后再说'],
      answerIndex: 0,
      distractorReason: '「ばそれまでだ」は取り返しがつかないという意味',
      distractorReasonZh: '「ばそれまでだ」表示无可挽回',
      explanationZh: '「〜ばそれまでだ」＝一旦…就完了',
    },
    production: {
      promptJa: '取り返しがつかないことを「〜ばそれまでだ」で言ってください。',
      promptZh: '用「〜ばそれまでだ」说一件无可挽回的事。',
      expected: ['それまでだ'], acceptable: ['ばそれまでです'],
    },
    practice: {
      themeJa: '気をつけていること', starterJa: '失敗したら取り返しがつかないことは何ですか？',
      starterZh: '有什么事一旦失败就无法挽回？', targetUse: '〜ばそれまでだ',
    },
    matchKeys: ['それまで'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-103', pattern: '〜始末だ', reading: 'しまつだ', unit: 7,
    meaningJa: '（悪い経過の末に）〜という結果になった',
    explanationZh: '结果落到…的地步。带责备语气',
    formation: '動詞辞書形＋始末だ',
    usageScene: '叙述一连串问题最后的糟糕结果',
    nuance: '前に悪い経過があり、最後に最悪の結果が来る',
    register: 'written',
    examplesJa: ['遅刻を重ね、ついに来なくなる始末です。', '注意しても直らず、けんかになる始末でした。'],
    examplesZh: ['接连迟到，最后竟然不来了。', '提醒也不改，最后竟然吵了起来。'],
    furigana: 'ちこくを かさね、ついに こなく なる しまつです。',
    commonMistakesZh: '只用于坏结果。好的结果不能用',
    learnerFocus: '常与「ついに」「あげく」一起出现。整段是「越来越糟」的叙述',
    similarPatterns: ['〜あげく', '〜結果'],
    contrast: '「始末だ」＝悪い結末への非難；「あげく」＝長い経過の末の（悪い）結果',
    recognition: {
      promptZh: '哪个句子用「始末だ」自然？',
      options: ['注意しても直らず、けんかになる始末だ', '努力して合格する始末だ', '毎日楽しく過ごす始末だ', '無事に終わる始末だ'],
      answerIndex: 0,
      distractorReason: '「始末だ」は悪い結末にだけ使う',
      distractorReasonZh: '「始末だ」只用于糟糕的结局',
      explanationZh: '「〜始末だ」＝结果落到…的地步',
    },
    production: {
      promptJa: '悪い結末を「〜始末だ」で言ってください。',
      promptZh: '用「〜始末だ」说一个糟糕的结局。',
      expected: ['始末だ'], acceptable: ['始末です'],
    },
    practice: {
      themeJa: 'うまくいかなかった話', starterJa: '何度注意しても直らなかったことはありますか？',
      starterZh: '有过提醒多次也没改的事吗？', targetUse: '〜始末だ',
    },
    matchKeys: ['始末'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-104', pattern: '〜次第だ', reading: 'しだいだ', unit: 7,
    meaningJa: '〜によって決まる／〜という事情だ',
    explanationZh: '取决于…；就是这样的情况。有两个用法',
    formation: '名詞＋次第だ／動詞・形容詞の普通形＋次第です',
    usageScene: '说明取决于什么，或在书信中说明原委',
    nuance: '名詞＋次第＝「〜によって決まる」、文＋次第です＝「〜という事情です」',
    register: 'written',
    examplesJa: ['参加できるかは天気次第です。', 'そのような理由で、ご連絡した次第です。'],
    examplesZh: ['能否参加取决于天气。', '出于上述理由，特此联系。'],
    furigana: 'さんか できるかは てんき しだいです。',
    commonMistakesZh: '两个用法要靠前面判断：名词→取决于；句子→说明原委',
    learnerFocus: '商务邮件常见「〜した次第です」。这是「情况说明」的用法',
    similarPatterns: ['〜による', '〜というわけだ'],
    contrast: '「名詞＋次第」＝〜で決まる；「文＋次第です」＝そういう事情だ',
    recognition: {
      promptZh: '「天気次第です」是什么意思？',
      options: ['取决于天气', '天气很好', '天气变了', '不看天气'],
      answerIndex: 0,
      distractorReason: '名詞に付く「次第」は「〜によって決まる」の意味',
      distractorReasonZh: '接名词的「次第」意为「取决于…」',
      explanationZh: '「〜次第だ」＝取决于…',
    },
    production: {
      promptJa: '何かで決まることを「〜次第だ」で言ってください。',
      promptZh: '用「〜次第だ」说一件取决于某条件的事。',
      expected: ['次第'], acceptable: ['次第です'],
    },
    practice: {
      themeJa: '条件で決まること', starterJa: '予定が何で決まりますか？',
      starterZh: '你的安排取决于什么？', targetUse: '〜次第だ',
    },
    matchKeys: ['次第'], vocabularyLinks: [],
  }),
  n1g({
    grammarId: 'n1g-105', pattern: '〜に難くない', reading: 'にかたくない', unit: 7,
    meaningJa: '簡単に〜できる（想像・理解）',
    explanationZh: '不难…（想象、理解）。是书面的固定说法',
    formation: '名詞／動詞辞書形＋に難くない',
    usageScene: '论说文中说明「不难想象当时的心情」',
    nuance: '「想像に難くない」「察するに難くない」の形がほとんど',
    register: 'written',
    examplesJa: ['当時の苦労は想像に難くありません。', '不安だったことは察するに難くない。'],
    examplesZh: ['当时的辛苦不难想象。', '不难体察当时的不安。'],
    furigana: 'とうじの くろうは そうぞうに かたく ありません。',
    commonMistakesZh: '不能自由组合动词。基本是「想像に難くない」「察するに難くない」',
    learnerFocus: '「難くない」＝不难。注意读作「かたくない」，不是「なんくない」',
    similarPatterns: ['〜やすい', '〜できる'],
    contrast: '「に難くない」＝書き言葉の固定表現；「〜やすい」＝一般的に簡単だ',
    recognition: {
      promptZh: '「想像に難くない」是什么意思？',
      options: ['不难想象', '难以想象', '不去想象', '想象过了'],
      answerIndex: 0,
      distractorReason: '「難くない」は「難しくない」の意味',
      distractorReasonZh: '「難くない」意为「不难」',
      explanationZh: '「〜に難くない」＝不难…（想象、理解）',
    },
    production: {
      promptJa: '容易に想像できることを「想像に難くない」で言ってください。',
      promptZh: '用「想像に難くない」说一件不难想象的事。',
      expected: ['に難くない'], acceptable: ['に難くありません'],
    },
    practice: {
      themeJa: '相手の気持ちを察する', starterJa: '相手の苦労が想像できた場面はありますか？',
      starterZh: '有过能想象到对方辛苦的时候吗？', targetUse: '〜に難くない',
    },
    matchKeys: ['に難くな'], vocabularyLinks: [],
  }),
];
