// N2文法 使用場面カテゴリ（自動分類・文法本文は不変更）。
// 生成: scripts相当のルールベース分類。低confidence項目は docs/n2-category-audit.md を参照。
// 人間レビューで修正する場合はこのマップだけを編集する（本文・例文に触れない）。

export type N2CategoryId =
  | 'work' | 'reason' | 'condition' | 'contrast' | 'decision' | 'emotion'
  | 'time' | 'degree' | 'limit' | 'adversative' | 'hearsay' | 'formal' | 'daily' | 'other';

export interface N2ItemCategory {
  primary: N2CategoryId;
  secondary: N2CategoryId[];
  confidence: 'high' | 'medium' | 'low';
}

export const N2_ITEM_CATEGORIES: Record<string, N2ItemCategory> = {
  'n2g-001': { primary: 'time', secondary: [], confidence: 'high' },
  'n2g-002': { primary: 'reason', secondary: [], confidence: 'high' },
  'n2g-003': { primary: 'reason', secondary: [], confidence: 'high' },
  'n2g-004': { primary: 'adversative', secondary: ['contrast'], confidence: 'medium' },
  'n2g-005': { primary: 'contrast', secondary: [], confidence: 'high' },
  'n2g-006': { primary: 'formal', secondary: [], confidence: 'high' },
  'n2g-007': { primary: 'reason', secondary: [], confidence: 'high' },
  'n2g-008': { primary: 'time', secondary: [], confidence: 'high' },
  'n2g-009': { primary: 'time', secondary: [], confidence: 'high' },
  'n2g-010': { primary: 'decision', secondary: ['hearsay'], confidence: 'medium' },
  'n2g-011': { primary: 'decision', secondary: [], confidence: 'high' },
  'n2g-012': { primary: 'decision', secondary: [], confidence: 'high' },
  'n2g-013': { primary: 'reason', secondary: [], confidence: 'high' },
  'n2g-014': { primary: 'hearsay', secondary: [], confidence: 'high' },
  'n2g-015': { primary: 'emotion', secondary: [], confidence: 'high' },
  'n2g-016': { primary: 'reason', secondary: [], confidence: 'high' },
  'n2g-017': { primary: 'condition', secondary: [], confidence: 'high' },
  'n2g-018': { primary: 'reason', secondary: [], confidence: 'high' },
  'n2g-019': { primary: 'time', secondary: [], confidence: 'high' },
  'n2g-020': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-021': { primary: 'degree', secondary: [], confidence: 'high' },
  'n2g-022': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-023': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-024': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-025': { primary: 'time', secondary: [], confidence: 'high' },
  'n2g-026': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-027': { primary: 'hearsay', secondary: [], confidence: 'high' },
  'n2g-028': { primary: 'hearsay', secondary: [], confidence: 'high' },
  'n2g-029': { primary: 'degree', secondary: [], confidence: 'high' },
  'n2g-030': { primary: 'adversative', secondary: [], confidence: 'high' },
  'n2g-031': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-032': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-033': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-034': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-035': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-036': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-037': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-038': { primary: 'contrast', secondary: [], confidence: 'high' },
  'n2g-039': { primary: 'degree', secondary: [], confidence: 'high' },
  'n2g-040': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-041': { primary: 'degree', secondary: [], confidence: 'high' },
  'n2g-042': { primary: 'adversative', secondary: [], confidence: 'high' },
  'n2g-043': { primary: 'degree', secondary: [], confidence: 'high' },
  'n2g-044': { primary: 'emotion', secondary: ['hearsay'], confidence: 'medium' },
  'n2g-045': { primary: 'reason', secondary: [], confidence: 'high' },
  'n2g-046': { primary: 'decision', secondary: [], confidence: 'high' },
  'n2g-047': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-048': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-049': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-050': { primary: 'decision', secondary: [], confidence: 'high' },
  'n2g-051': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-052': { primary: 'time', secondary: [], confidence: 'high' },
  'n2g-053': { primary: 'decision', secondary: [], confidence: 'high' },
  'n2g-054': { primary: 'time', secondary: [], confidence: 'high' },
  'n2g-055': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-056': { primary: 'time', secondary: [], confidence: 'high' },
  'n2g-057': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-058': { primary: 'decision', secondary: [], confidence: 'high' },
  'n2g-059': { primary: 'reason', secondary: [], confidence: 'high' },
  'n2g-060': { primary: 'reason', secondary: [], confidence: 'high' },
  'n2g-061': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-062': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-063': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-064': { primary: 'adversative', secondary: [], confidence: 'high' },
  'n2g-065': { primary: 'time', secondary: [], confidence: 'high' },
  'n2g-066': { primary: 'limit', secondary: [], confidence: 'high' },
  'n2g-067': { primary: 'time', secondary: [], confidence: 'high' },
  'n2g-068': { primary: 'degree', secondary: [], confidence: 'high' },
  'n2g-069': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-070': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-071': { primary: 'adversative', secondary: [], confidence: 'high' },
  'n2g-072': { primary: 'time', secondary: [], confidence: 'high' },
  'n2g-073': { primary: 'degree', secondary: [], confidence: 'high' },
  'n2g-074': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-075': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-076': { primary: 'time', secondary: [], confidence: 'high' },
  'n2g-077': { primary: 'condition', secondary: [], confidence: 'high' },
  'n2g-078': { primary: 'emotion', secondary: [], confidence: 'high' },
  'n2g-079': { primary: 'emotion', secondary: [], confidence: 'high' },
  'n2g-080': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-081': { primary: 'emotion', secondary: [], confidence: 'high' },
  'n2g-082': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-083': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-084': { primary: 'time', secondary: [], confidence: 'high' },
  'n2g-085': { primary: 'decision', secondary: ['hearsay'], confidence: 'medium' },
  'n2g-086': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-087': { primary: 'contrast', secondary: [], confidence: 'high' },
  'n2g-088': { primary: 'adversative', secondary: [], confidence: 'high' },
  'n2g-089': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-090': { primary: 'hearsay', secondary: [], confidence: 'high' },
  'n2g-091': { primary: 'contrast', secondary: [], confidence: 'high' },
  'n2g-092': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-093': { primary: 'degree', secondary: [], confidence: 'high' },
  'n2g-094': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-095': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-096': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-097': { primary: 'condition', secondary: [], confidence: 'high' },
  'n2g-098': { primary: 'work', secondary: [], confidence: 'high' },
  'n2g-099': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-100': { primary: 'condition', secondary: ['emotion'], confidence: 'medium' },
  'n2g-101': { primary: 'decision', secondary: [], confidence: 'high' },
  'n2g-102': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-103': { primary: 'adversative', secondary: [], confidence: 'high' },
  'n2g-104': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-105': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-106': { primary: 'formal', secondary: [], confidence: 'high' },
  'n2g-107': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-108': { primary: 'formal', secondary: [], confidence: 'high' },
  'n2g-109': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-110': { primary: 'limit', secondary: [], confidence: 'high' },
  'n2g-111': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-112': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-113': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-114': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-115': { primary: 'decision', secondary: [], confidence: 'high' },
  'n2g-116': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-117': { primary: 'formal', secondary: [], confidence: 'high' },
  'n2g-118': { primary: 'time', secondary: [], confidence: 'high' },
  'n2g-119': { primary: 'work', secondary: [], confidence: 'high' },
  'n2g-120': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-121': { primary: 'adversative', secondary: [], confidence: 'high' },
  'n2g-122': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-123': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-124': { primary: 'hearsay', secondary: [], confidence: 'high' },
  'n2g-125': { primary: 'formal', secondary: [], confidence: 'high' },
  'n2g-126': { primary: 'hearsay', secondary: [], confidence: 'high' },
  'n2g-127': { primary: 'reason', secondary: [], confidence: 'high' },
  'n2g-128': { primary: 'time', secondary: [], confidence: 'high' },
  'n2g-129': { primary: 'work', secondary: [], confidence: 'high' },
  'n2g-130': { primary: 'contrast', secondary: [], confidence: 'high' },
  'n2g-131': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-132': { primary: 'adversative', secondary: [], confidence: 'high' },
  'n2g-133': { primary: 'formal', secondary: [], confidence: 'high' },
  'n2g-134': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-135': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-136': { primary: 'degree', secondary: [], confidence: 'high' },
  'n2g-137': { primary: 'limit', secondary: [], confidence: 'high' },
  'n2g-138': { primary: 'formal', secondary: [], confidence: 'high' },
  'n2g-139': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-140': { primary: 'limit', secondary: [], confidence: 'high' },
  'n2g-141': { primary: 'reason', secondary: [], confidence: 'high' },
  'n2g-142': { primary: 'work', secondary: [], confidence: 'high' },
  'n2g-143': { primary: 'work', secondary: [], confidence: 'high' },
  'n2g-144': { primary: 'condition', secondary: ['degree'], confidence: 'medium' },
  'n2g-145': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-146': { primary: 'contrast', secondary: [], confidence: 'high' },
  'n2g-147': { primary: 'decision', secondary: [], confidence: 'high' },
  'n2g-148': { primary: 'decision', secondary: [], confidence: 'high' },
  'n2g-149': { primary: 'degree', secondary: [], confidence: 'high' },
  'n2g-150': { primary: 'decision', secondary: [], confidence: 'high' },
  'n2g-151': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-152': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-153': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-154': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-155': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-156': { primary: 'emotion', secondary: [], confidence: 'high' },
  'n2g-157': { primary: 'emotion', secondary: [], confidence: 'high' },
  'n2g-158': { primary: 'reason', secondary: [], confidence: 'high' },
  'n2g-159': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-160': { primary: 'condition', secondary: [], confidence: 'high' },
  'n2g-161': { primary: 'adversative', secondary: [], confidence: 'high' },
  'n2g-162': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-163': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-164': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-165': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-166': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-167': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-168': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-169': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-170': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-171': { primary: 'decision', secondary: [], confidence: 'high' },
  'n2g-172': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-173': { primary: 'work', secondary: [], confidence: 'high' },
  'n2g-174': { primary: 'work', secondary: [], confidence: 'high' },
  'n2g-175': { primary: 'formal', secondary: [], confidence: 'high' },
  'n2g-176': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-177': { primary: 'work', secondary: [], confidence: 'high' },
  'n2g-178': { primary: 'other', secondary: [], confidence: 'low' },
  'n2g-179': { primary: 'formal', secondary: [], confidence: 'high' },
  'n2g-180': { primary: 'other', secondary: [], confidence: 'low' },
};

/** カテゴリの表示定義（ja/zh）。教材本文ではなくUIラベルのみ */
export const N2_CATEGORY_DEFS: { id: N2CategoryId; ja: string; zh: string; descJa: string; descZh: string }[] = [
  { id: 'work', ja: '仕事で使う', zh: '工作中常用', descJa: '会議・報告・説明で使いやすい表現', descZh: '会议、汇报、说明中常用的表达' },
  { id: 'reason', ja: '理由・原因', zh: '表达原因', descJa: '原因や理由を分かりやすく話す', descZh: '把原因和理由说清楚' },
  { id: 'condition', ja: '条件・仮定', zh: '条件与假设', descJa: '「もし〜なら」を伝える', descZh: '表达「如果〜的话」' },
  { id: 'contrast', ja: '比較・対比', zh: '比较与对比', descJa: '2つのことを比べて話す', descZh: '对比两件事来表达' },
  { id: 'decision', ja: '判断・決意', zh: '判断与决定', descJa: '自分の考え・決めたことを言う', descZh: '表达自己的判断和决定' },
  { id: 'emotion', ja: '感情・評価', zh: '感情与评价', descJa: '気持ちや感想を伝える', descZh: '表达心情和感想' },
  { id: 'time', ja: '時間・順序', zh: '时间与顺序', descJa: 'いつ・どの順番かを表す', descZh: '表达时间点和先后顺序' },
  { id: 'degree', ja: '程度・強調', zh: '程度与强调', descJa: 'どのくらいかを強めて言う', descZh: '强调程度的表达' },
  { id: 'limit', ja: '限定', zh: '限定', descJa: '「〜だけ」と範囲をしぼる', descZh: '限定范围的表达' },
  { id: 'adversative', ja: '逆接', zh: '转折', descJa: '「でも・のに」の流れで話す', descZh: '表达转折关系' },
  { id: 'hearsay', ja: '伝聞・推測', zh: '转述与推测', descJa: '聞いた話や予想を伝える', descZh: '转述听说的事或做出推测' },
  { id: 'formal', ja: '書き言葉・正式', zh: '书面语与正式表达', descJa: 'ビジネス文書・お知らせで見る表現', descZh: '常见于商务文书和通知' },
  { id: 'daily', ja: '日常会話', zh: '日常会话', descJa: 'ふだんの会話でよく使う', descZh: '日常对话中常用' },
  { id: 'other', ja: 'その他', zh: '其他', descJa: '分類を確認中の表現', descZh: '分类确认中的表达' },
];

/** カテゴリでの絞り込み（primary または secondary に含む） */
export const byCategory = <T extends { grammarId: string }>(items: T[], cat: N2CategoryId): T[] =>
  items.filter((g) => {
    const c = N2_ITEM_CATEGORIES[g.grammarId];
    return !!c && (c.primary === cat || c.secondary.includes(cat));
  });
