// Phase 3P-5: N2文法完成draft Unit 10（No.136〜150の15文型）。
// rightsStatus: teacher_created_confirmed。第1例文=原本（無改変）、第2例文=独自（実生活）。
import type { N2GrammarDraft } from './n2GrammarDrafts';

const g = (p: Omit<N2GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey' | 'runtimeExampleOrigin'> & { reviewKey?: string; runtimeExampleOrigin?: N2GrammarDraft['runtimeExampleOrigin'] }): N2GrammarDraft =>
  ({ level: 'N2', route: 'n2-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, runtimeExampleOrigin: 'source_confirmed', ...p });

const src = (text: string, hash: string) =>
  ({ text, hash, rightsStatus: 'teacher_created_confirmed' as const });

export const N2_GRAMMAR_DRAFTS_UNIT10: N2GrammarDraft[] = [
  g({ grammarId: 'n2g-136', pattern: '〜抜く', reading: 'ぬく', unit: 10, zhSourceRowId: null,
    meaningJa: '困難があっても最後まで〜し切る',
    explanationZh: '…到底、坚持…完。克服困难把动作贯彻到最后',
    formation: '動詞ます形（語幹） ＋抜く',
    usageScene: '跑完马拉松、想透一个问题、坚持做完困难的事',
    nuance: '「苦しくても最後まで」の根性の響き。淡々とした完了は「〜終わる」',
    register: 'both',
    matchKeys: ['抜き', '抜く', '抜い'],
    sourceExample: src('マラソンでゴールまで走り抜きました。', '316c0e14cacedaa9'),
    examplesJa: ['マラソンでゴールまで走り抜きました。',
                 '一度始めたことは、最後までやり抜くと決めています。'],
    examplesZh: ['马拉松坚持跑到了终点。', '一旦开始的事，我决心坚持做到底。'],
    furigana: 'マラソンで ゴールまで はしりぬきました。',
    commonMistakesZh: '「〜きる」是把全部做完（食べきる＝吃光），「〜抜く」是顶着困难做到底（走り抜く＝咬牙跑完）。没有困难感的场合用「抜く」会显得夸张',
    learnerFocus: '「考え抜いた結論です」＝深思熟虑后的结论。表决心、谈毅力时的加分动词',
    similarPatterns: ['〜きる', '〜通す'],
    contrast: '「抜く」＝困難を乗り越えて最後まで；「きる」＝全部・完全に；「通す」＝最初から最後まで貫く',
    recognition: { promptZh: '哪个搭配最能表现「咬牙坚持到底」？',
      options: ['フルマラソンを走り抜いた', 'ジュースを飲み抜いた', 'テレビを見抜いた', '昼寝をし抜いた'],
      answerIndex: 0, distractorReason: '其余三项没有克服困难的语感（見抜く另有「看穿」之意）',
      explanationZh: '「抜く」要配有苦难感的坚持' },
    production: { promptJa: '最後までやりとげた経験を「〜抜く」で言ってください。',
      promptZh: '用「〜抜く」说一次坚持到底的经历。',
      expected: ['抜'], acceptable: ['やり抜いた', '走り抜いた'] },
    practice: { themeJa: '根性を見せた経験を語る', starterJa: '途中でやめたくなったのに、最後までやり切ったことはありますか？',
      starterZh: '有没有中途想放弃却坚持到底的事？', targetUse: '〜抜く' },
    vocabularyLinks: ['fi-owaru', 'fi-ganbaru'] }),
  g({ grammarId: 'n2g-137', pattern: '〜のみならず', reading: 'のみならず', unit: 10, zhSourceRowId: null,
    meaningJa: '〜だけでなく（書き言葉）',
    explanationZh: '不仅…而且…。「だけでなく」的书面语，论文、报告、新闻常用',
    formation: '名詞／普通形（な形容詞・名詞は＋である） ＋のみならず',
    usageScene: '论文陈述影响范围、报告列举多重因素',
    nuance: '硬い書面語。後半に「も・まで・さえ」が呼応する',
    register: 'written',
    sourceExample: src('継続的に学習を続けるには、気合のみならず、習慣化させる仕組みづくりが大切です。', 'daac9e7fd86c7a19'),
    examplesJa: ['継続的に学習を続けるには、気合のみならず、習慣化させる仕組みづくりが大切です。',
                 'この問題は日本のみならず、世界全体に関わっています。'],
    examplesZh: ['要持续学习，不仅靠干劲，建立习惯化的机制也很重要。', '这个问题不仅关系日本，还关系到全世界。'],
    furigana: 'けいぞくてきに がくしゅうを つづけるには、きあいのみならず、しゅうかんかさせる しくみづくりが たいせつです。',
    commonMistakesZh: '口语聊天里用「のみならず」会像在念论文，日常说「だけでなく」。书面写作时后半别忘了呼应的「も」',
    learnerFocus: '把作文里的「だけでなく」升级成「のみならず」，文体立刻从N3变N2。JLPT读解高频',
    similarPatterns: ['〜ばかりか', '〜に加えて'],
    contrast: '「のみならず」＝書面の累加；「ばかりか」＝意外性を強調；「に加えて」＝中立の追加',
    recognition: { promptZh: '想把「彼は英語だけでなく、フランス語も話す」写得更书面，选哪个？',
      options: ['英語のみならず、フランス語も', '英語ばっかりで、フランス語も', '英語に限って、フランス語も', '英語はおろか、フランス語も'],
      answerIndex: 0, distractorReason: '「ばっかり」是口语的只顾、「に限って」是偏偏、「はおろか」用于负面递进',
      explanationZh: '「だけでなく」的书面替换＝「のみならず」' },
    production: { promptJa: '二つ以上の要素を「〜のみならず」で書き言葉風に言ってください。',
      promptZh: '用「〜のみならず」书面地列举两个以上要素。',
      expected: ['のみならず'], acceptable: ['〜のみならず〜も'] },
    practice: { themeJa: '書き言葉で意見を述べる', starterJa: '日本語学習に必要なものを、レポート風に二つ挙げてください。',
      starterZh: '用报告的文体列举两个学日语必需的东西。', targetUse: '〜のみならず' },
    vocabularyLinks: ['fi-shuukan', 'fi-benkyo'] }),
  g({ grammarId: 'n2g-138', pattern: '〜のもとで', reading: 'のもとで', unit: 10, zhSourceRowId: null,
    meaningJa: '〜の指導・影響・条件の下で',
    explanationZh: '在…（指导、庇护、条件）之下。处于某人某物的影响范围内做事',
    formation: '名詞 ＋のもとで（のもとに）',
    usageScene: '在老师指导下学习、在新制度下工作、在父母呵护下成长',
    nuance: '物理的な真下ではなく、影響・支配・保護の範囲内',
    register: 'written',
    sourceExample: src('先生の指導のもとで、なんとかN1にも合格することができました。', '711e461c15561546'),
    examplesJa: ['先生の指導のもとで、なんとかN1にも合格することができました。',
                 '新しい制度のもとで、働き方が大きく変わりました。'],
    examplesZh: ['在老师的指导下，总算连N1也合格了。', '在新制度之下，工作方式发生了很大变化。'],
    furigana: 'せんせいの しどうの もとで、なんとか エヌワンにも ごうかくする ことが できました。',
    commonMistakesZh: '和物理的「下（した）」不同：「木の下で休む」用した、「指導のもとで学ぶ」用もと。写成汉字「下で」时读音歧义，平假名「のもとで」更稳',
    learnerFocus: '介绍学习经历的正式说法：「李先生のもとで日本語を学びました」。简历、自我介绍都好用',
    similarPatterns: ['〜の下で', '〜において'],
    contrast: '「のもとで」＝指導・影響の範囲内；「において」＝場・分野の提示；「の中で」＝物理・集合の内側',
    recognition: { promptZh: '「田中コーチのもとで練習した」的意思是？',
      options: ['在田中教练的指导下练习', '在田中教练的正下方练习', '代替田中教练练习', '和田中教练比赛'],
      answerIndex: 0, distractorReason: '「のもとで」表示指导・影响范围，不是物理位置',
      explanationZh: '抽象的「在…之下」' },
    production: { promptJa: '誰かの指導・支えの下での経験を「〜のもとで」で言ってください。',
      promptZh: '用「〜のもとで」说一段在某人指导（支持）下的经历。',
      expected: ['のもとで'], acceptable: ['〜のもとに'] },
    practice: { themeJa: '恩師・恩人を紹介する', starterJa: 'あなたの成長を支えてくれた人は誰ですか？',
      starterZh: '谁支撑了你的成长？', targetUse: '〜のもとで' },
    vocabularyLinks: ['fi-sensei', 'fi-shigoto'] }),
  g({ grammarId: 'n2g-139', pattern: '〜はおろか', reading: 'はおろか', unit: 10, zhSourceRowId: null,
    meaningJa: '〜はもちろん、それ以前のものさえ（否定的）',
    explanationZh: '别说…就连…也（不）。连更基本的都不行，多用于消极叙述',
    formation: '名詞 ＋はおろか',
    usageScene: '诉说困境：别说旅行连购物都去不了、别说存款连房租都付不起',
    nuance: '後半に「も・さえ・すら」＋否定が呼応。深刻・嘆きの響き',
    register: 'both',
    sourceExample: src('ロックダウンで、旅行はおろか、買い物にすら行くことができませんでした。', '08ff6f8577533079'),
    examplesJa: ['ロックダウンで、旅行はおろか、買い物にすら行くことができませんでした。',
                 '骨折した直後は、運動はおろか、階段の上り下りもできませんでした。'],
    examplesZh: ['封控期间，别说旅行，连买东西都去不了。', '骨折后不久，别说运动，连上下楼梯都做不到。'],
    furigana: 'ロックダウンで、りょこうは おろか、かいものにすら いくことが できませんでした。',
    commonMistakesZh: '「はおろか」基本配否定・消极内容，积极递进（不仅会…还会…）用「はもちろん」。后半必须有「も・さえ・すら」',
    learnerFocus: '诉苦的最强递进：「貯金はおろか、家賃も払えない」。程度感比「どころか」更沉重',
    similarPatterns: ['〜どころか', '〜はもちろん'],
    contrast: '「はおろか」＝否定的な深刻さ（書面寄り）；「どころか」＝予想の反転（会話も可）；「はもちろん」＝肯定的な当然の累加',
    recognition: { promptZh: '「漢字はおろか、ひらがなも書けなかった」的状况是？',
      options: ['连平假名都不会写（更别说汉字）', '汉字和平假名这两种字都写得非常好', '只会写汉字，而平假名一个也不会写', '其实都会写，只是不想动手写字而已'],
      answerIndex: 0, distractorReason: '「はおろか」＝连更基础的后项都不行',
      explanationZh: '否定的「别说A连B都不」' },
    production: { promptJa: '大変だった時期を「〜はおろか」で言ってください。',
      promptZh: '用「〜はおろか」描述一段艰难时期。',
      expected: ['はおろか'], acceptable: ['〜はおろか〜も'] },
    practice: { themeJa: '苦労した時期を振り返る', starterJa: '来日直後（学習初期）、何が一番できませんでしたか？',
      starterZh: '刚来日本（刚开始学）时，最做不到的是什么？', targetUse: '〜はおろか' },
    vocabularyLinks: ['fi-iku', 'fi-kau'] }),
  g({ grammarId: 'n2g-140', pattern: '〜ばかりか', reading: 'ばかりか', unit: 10, zhSourceRowId: null,
    meaningJa: '〜だけでなく、（意外にも）その上',
    explanationZh: '岂止…连…也、不但…而且。累加时带「居然还」的意外感',
    formation: '動詞・い形容詞普通形／な形容詞＋な／名詞 ＋ばかりか',
    usageScene: '惊叹某人多才、回顾起点之低、抱怨祸不单行',
    nuance: '累加＋驚き。良いことにも悪いことにも使う',
    register: 'both',
    sourceExample: src('最初は挨拶ばかりか、「あいうえお」すら読めませんでした。', 'a7aca23d1eeb977e'),
    examplesJa: ['最初は挨拶ばかりか、「あいうえお」すら読めませんでした。',
                 '彼は仕事ばかりか、家事も完璧にこなします。'],
    examplesZh: ['最开始别说打招呼，连「あいうえお」都读不了。', '他不但工作出色，连家务也做得完美。'],
    furigana: 'さいしょは あいさつばかりか、「あいうえお」すら よめませんでした。',
    commonMistakesZh: '和「ばかりに」（只因为…才倒霉）一字之差完全不同。「ばかりか」后半常呼应「も・さえ・まで」，别接命令・劝诱句',
    learnerFocus: '讲自己的成长故事时超好用：「最初はひらがなばかりか、挨拶もできなかった」→现在的对比让听者印象深刻',
    similarPatterns: ['〜のみならず', '〜はおろか'],
    contrast: '「ばかりか」＝累加＋意外；「のみならず」＝書面の中立累加；「はおろか」＝否定方向の深刻な递进',
    recognition: { promptZh: '「彼は歌ばかりか、作曲までできる」的语气是？',
      options: ['不但会唱，居然还会作曲', '他只会唱歌，完全不会作曲', '因为唱了歌所以倒霉', '让他别唱歌快去作曲'],
      answerIndex: 0, distractorReason: '「ばかりか…まで」＝累加＋意外的感叹',
      explanationZh: '「岂止…连…都」的正向惊叹' },
    production: { promptJa: '意外な「その上」を「〜ばかりか」で言ってください。',
      promptZh: '用「〜ばかりか」说一个「不但…居然还…」。',
      expected: ['ばかりか'], acceptable: ['〜ばかりか〜も'] },
    practice: { themeJa: '成長のビフォーアフターを語る', starterJa: '学習を始めた頃と今、何が一番変わりましたか？',
      starterZh: '刚开始学时和现在，变化最大的是什么？', targetUse: '〜ばかりか' },
    vocabularyLinks: ['fi-yomu', 'fi-hajimeru'] }),
  g({ grammarId: 'n2g-141', pattern: '〜ばかりに', reading: 'ばかりに', unit: 10, zhSourceRowId: null,
    meaningJa: 'ただ〜が原因で（悪い結果・後悔）',
    explanationZh: '只因为…（导致了坏结果）。带懊悔的原因表达',
    formation: '動詞た形・普通形／な形容詞＋な・である ＋ばかりに',
    usageScene: '后悔多说了一句话、只因迟到一分钟错过末班车',
    nuance: '「たったそれだけのせいで」という悔しさ。原本例文は散財への軽い自嘲',
    register: 'spoken',
    sourceExample: src('高級の車を買ったばかりに、毎日のようにドライブをしています。', 'bf11b73a92751007'),
    examplesJa: ['高級の車を買ったばかりに、毎日のようにドライブをしています。',
                 '一言多く言ったばかりに、けんかになってしまいました。'],
    examplesZh: ['只因买了豪车，现在几乎天天去兜风（自嘲）。', '只因多说了一句话，吵了起来。'],
    furigana: 'こうきゅうの くるまを かった ばかりに、まいにちのように ドライブを しています。',
    commonMistakesZh: '标准用法后项是坏结果・懊悔：「勉強したばかりに合格した」不成立。和「ばかりか」（累加）一字之差，先看后项是好是坏',
    learnerFocus: '悔恨的标准句式：「安さにひかれて買ったばかりに、すぐ壊れた」。吐槽购物失败必备',
    similarPatterns: ['〜せいで', '〜たために'],
    contrast: '「ばかりに」＝小さな原因→悪い結果の後悔；「せいで」＝原因への非難；「ために」＝中立の因果',
    recognition: { promptZh: '「パスポートを忘れたばかりに、飛行機に乗れなかった」的心情是？',
      options: ['只因忘带护照而懊悔不已', '幸好忘了护照', '故意不带护照', '和护照无关'],
      answerIndex: 0, distractorReason: '「ばかりに」＝只因一个小失误导致坏结果的悔恨',
      explanationZh: '小原因→大损失的后悔' },
    production: { promptJa: '小さな原因で失敗した経験を「〜ばかりに」で言ってください。',
      promptZh: '用「〜ばかりに」说一次因小失大的经历。',
      expected: ['ばかりに'], acceptable: ['〜たばかりに'] },
    practice: { themeJa: '失敗談を面白く話す', starterJa: '「あれさえなければ…」という失敗はありますか？',
      starterZh: '有没有「要不是那个就好了」的失败？', targetUse: '〜ばかりに' },
    vocabularyLinks: ['fi-takai', 'fi-komaru'] }),
  g({ grammarId: 'n2g-142', pattern: '〜はともかくとして', reading: 'はともかくとして', unit: 10, zhSourceRowId: null,
    meaningJa: '〜のことはいったん置いておいて',
    explanationZh: '姑且不论…、先不管…。把前项暂时搁置，聚焦更重要的后项',
    formation: '名詞 ＋はともかく（として）',
    usageScene: '先不论结果肯定努力、先不管味道夸摆盘、跳过闲话进正题',
    nuance: '前項を否定はせず保留にする。話題の交通整理に便利',
    register: 'spoken',
    sourceExample: src('結果はともかくとして、毎日努力できたことを称賛したいです。', 'f20a6a10dc8b58ac'),
    examplesJa: ['結果はともかくとして、毎日努力できたことを称賛したいです。',
                 '見た目はともかくとして、味は保証します。'],
    examplesZh: ['结果姑且不论，每天都能努力这一点值得称赞。', '卖相先不说，味道我保证。'],
    furigana: 'けっかは ともかくとして、まいにち どりょく できたことを しょうさん したいです。',
    commonMistakesZh: 'Unit7学过的「ならともかく」是假定对比（要是…倒也罢了），「はともかく」是搁置话题。助词「なら/は」决定用法',
    learnerFocus: '把话题拉回重点的口头技：「冗談はともかく、本題に入りましょう」。会议、闲聊都用得上',
    similarPatterns: ['〜は別として', '〜ならともかく'],
    contrast: '「はともかく」＝棚上げして先へ；「は別として」＝切り分けて除外；「ならともかく」＝許容できる仮定との対比',
    recognition: { promptZh: '「値段はともかく、デザインは最高だ」的态度是？',
      options: ['价格先不谈，设计超棒', '价格和设计两方面都很差', '因为价格便宜所以设计才好', '只在乎价格，完全不看设计'],
      answerIndex: 0, distractorReason: '「はともかく」＝搁置前项、突出后项评价',
      explanationZh: '先把价格放一边，聚焦设计' },
    production: { promptJa: '一つを保留して別の点をほめる文を「〜はともかく」で作ってください。',
      promptZh: '用「〜はともかく」搁置一点、称赞另一点。',
      expected: ['はともかく'], acceptable: ['〜はともかくとして'] },
    practice: { themeJa: '話題を整理して伝える', starterJa: '「結果はともかく、よくやった」と言いたい経験はありますか？',
      starterZh: '有没有想说「结果先不论，干得漂亮」的经历？', targetUse: '〜はともかくとして' },
    vocabularyLinks: ['fi-mondai', 'fi-kimochi'] }),
  g({ grammarId: 'n2g-143', pattern: '〜は別として', reading: 'はべつとして', unit: 10, zhSourceRowId: null,
    meaningJa: '〜は切り離して考えて',
    explanationZh: '…另当别论、除…之外。把前项从讨论中切分出去',
    formation: '名詞／〜かどうか ＋は別として',
    usageScene: '喜欢与否和擅长与否分开谈、特殊情况除外的规则说明',
    nuance: '「かどうかは別として」の形で判断を保留するのが定番',
    register: 'both',
    sourceExample: src('得意かどうかは別として、絵を描くのが好きです。', '623abc9fff401c1d'),
    examplesJa: ['得意かどうかは別として、絵を描くのが好きです。',
                 '冗談は別として、そろそろ真剣に考えましょう。'],
    examplesZh: ['擅不擅长另当别论，我就是喜欢画画。', '玩笑归玩笑，差不多该认真考虑了。'],
    furigana: 'とくいかどうかは べつとして、えを かくのが すきです。',
    commonMistakesZh: '「はともかく」偏口语的「先不提」，「は別として」更客观的「切分出去」。「冗談は別として」＝玩笑归玩笑，切换认真模式的信号',
    learnerFocus: '兴趣自我介绍的好帮手：「上手かどうかは別として、歌が好きです」。不用怕被追问水平',
    similarPatterns: ['〜はともかく', '〜を除いて'],
    contrast: '「は別として」＝対象を切り分ける；「はともかく」＝いったん棚上げ；「を除いて」＝集合からの除外',
    recognition: { promptZh: '「行けるかどうかは別として、話だけは聞きたい」的意思是？',
      options: ['去不去另说，先想听听内容', '肯定一定会去', '绝对不去，内容也完全不想听', '已经去过了'],
      answerIndex: 0, distractorReason: '「かどうかは別として」＝保留判断、先做后项',
      explanationZh: '判断切分：先听再说' },
    production: { promptJa: '上手下手を切り離して好きなことを「〜は別として」で言ってください。',
      promptZh: '用「〜は別として」介绍一个不论水平高低都喜欢的爱好。',
      expected: ['は別として'], acceptable: ['かどうかは別として'] },
    practice: { themeJa: '趣味を気軽に語る', starterJa: '上手じゃなくても好きなことはありますか？',
      starterZh: '有没有虽然不擅长但很喜欢的事？', targetUse: '〜は別として' },
    vocabularyLinks: ['fi-suki', 'fi-kaku'] }),
  g({ grammarId: 'n2g-144', pattern: '〜ば〜ほど', reading: 'ばほど', unit: 10, zhSourceRowId: 'n3row-3',
    meaningJa: '〜すればするほど、程度が増す',
    explanationZh: '越…越…。同一动词重复，表示程度随行为累积而上升',
    formation: '動詞ば形 ＋同じ動詞辞書形 ＋ほど',
    usageScene: '越学越聪明、越聊越开心、越想越不明白',
    nuance: '同じ動詞を2回繰り返すのが型。い形容詞は「安ければ安いほど」',
    register: 'both',
    matchKeys: ['ばするほど', 'せば話すほど'],
    sourceExample: src('勉強すればするほど、賢くなります。', 'fef63c38954518cc'),
    examplesJa: ['勉強すればするほど、賢くなります。',
                 '日本語は、話せば話すほど楽しくなります。'],
    examplesZh: ['越学习越聪明。', '日语越说越有意思。'],
    furigana: 'べんきょう すれば するほど、かしこく なります。',
    commonMistakesZh: '最常见错误是省略重复：「勉強すればほど」×。动词必须出现两次「すればするほど」。名词句用「〜であればあるほど」',
    learnerFocus: '中文「越…越…」的直译对应，是少数能直接套的句型。先把「話せば話すほど」说顺，开口率暴涨',
    similarPatterns: ['〜につれて', '〜ほど'],
    contrast: '「ば〜ほど」＝行為量と程度の比例；「につれて」＝変化に伴う変化；「ほど」単独＝程度の比喩',
    recognition: { promptZh: '「越考虑越不明白」的正确说法是？',
      options: ['考えれば考えるほど、わからなくなる', '考えればほど、わからなくなる', '考えるほど考えれば、わからなくなる', '考えれば考えると、わからなくなる'],
      answerIndex: 0, distractorReason: '动词要以「ば形＋辞书形＋ほど」的顺序重复出现',
      explanationZh: '「Vば＋V辞書形＋ほど」的固定型' },
    production: { promptJa: '「やるほど良くなる」ことを「〜ば〜ほど」で言ってください。',
      promptZh: '用「〜ば〜ほど」说一件越做越好的事。',
      expected: ['ほど'], acceptable: ['すればするほど'] },
    practice: { themeJa: '上達の実感を語る', starterJa: '「やればやるほど面白い」と感じることは何ですか？',
      starterZh: '有什么事让你觉得越做越有意思？', targetUse: '〜ば〜ほど' },
    vocabularyLinks: ['fi-jouzu', 'fi-hanasu'] }),
  g({ grammarId: 'n2g-145', pattern: '〜はもちろん', reading: 'はもちろん', unit: 10, zhSourceRowId: null,
    meaningJa: '〜は当然として、さらに',
    explanationZh: '…自不必说，连…也。前项理所当然，后项进一步扩展范围',
    formation: '名詞 ＋はもちろん（はもとより＝より書面）',
    usageScene: '大人自不必说连孩子也用手机、平日当然周末也练习',
    nuance: '肯定方向の当然＋拡張。「はもとより」は改まった文書向け',
    register: 'both',
    matchKeys: ['はもちろん', 'はもとより'],
    sourceExample: src('最近は大人はもちろん、子供ですら、スマホを使う人が多くなりました。', '4630b2b6522fae84'),
    examplesJa: ['最近は大人はもちろん、子供ですら、スマホを使う人が多くなりました。',
                 '平日はもちろん、週末も日本語に触れるようにしています。'],
    examplesZh: ['最近别说大人，连孩子用智能手机的都多了。', '工作日自不必说，周末我也尽量接触日语。'],
    furigana: 'さいきんは おとなは もちろん、こどもですら、スマホを つかう ひとが おおくなりました。',
    commonMistakesZh: '积极扩展用「はもちろん」，消极递进用「はおろか」：「日本語はもちろん英語も話せる」（正）／「日本語はおろか挨拶もできない」（负）。方向选错会很怪',
    learnerFocus: '介绍城市、店铺、自己的多面性都好用：「観光はもちろん、食べ物も最高です」',
    similarPatterns: ['〜のみならず', '〜はおろか'],
    contrast: '「はもちろん」＝当然＋肯定的拡張；「のみならず」＝書面の累加；「はおろか」＝否定方向の递进',
    recognition: { promptZh: '「このアプリは初心者はもちろん、上級者にも人気だ」是说？',
      options: ['新手当然爱用，高手也喜欢', '只有新手才会使用', '高手绝对不会去用', '新手高手都不用'],
      answerIndex: 0, distractorReason: '「はもちろん…にも」＝范围的肯定扩展',
      explanationZh: '前项当然成立＋后项也成立' },
    production: { promptJa: '当然の前提に一歩足して「〜はもちろん」で言ってください。',
      promptZh: '用「〜はもちろん」在理所当然之上再加一层。',
      expected: ['はもちろん'], acceptable: ['〜はもとより'] },
    practice: { themeJa: '故郷の魅力を紹介する', starterJa: 'あなたの故郷の、食べ物以外の魅力も教えてください。',
      starterZh: '介绍一下你家乡除了美食之外的魅力。', targetUse: '〜はもちろん' },
    vocabularyLinks: ['fi-kazoku', 'fi-tsukau'] }),
  g({ grammarId: 'n2g-146', pattern: '〜反面', reading: 'はんめん', unit: 10, zhSourceRowId: null,
    meaningJa: '〜という面の一方で（対照的な面もある）',
    explanationZh: '…的另一面却…。同一事物对照性的两面',
    formation: '動詞・い形容詞普通形／な形容詞＋な・である／名詞＋である ＋反面',
    usageScene: '语法难但熟了就能说、都市方便但易疲惫、工作自由但不稳定',
    nuance: '「一方で」より対照性が強い。長所と短所のセットで使うことが多い',
    register: 'written',
    sourceExample: src('文法は難しい反面、慣れれば自然と話せるようになります。', '04e793dbd6ea87fa'),
    examplesJa: ['文法は難しい反面、慣れれば自然と話せるようになります。',
                 '都会の生活は便利な反面、疲れることも多いです。'],
    examplesZh: ['语法虽难，另一面是熟悉后自然就能开口。', '都市生活方便，另一面也常让人疲惫。'],
    furigana: 'ぶんぽうは むずかしい はんめん、なれれば しぜんと はなせる ように なります。',
    commonMistakesZh: 'な形容词接续是「便利な反面」，名词是「仕事である反面」。接续错误高发。前后必须是同一事物的两面，不同事物的对比用「〜に対して」',
    learnerFocus: '面试谈优缺点的框架：「慎重な反面、決断に時間がかかります」。自我分析显得客观',
    similarPatterns: ['〜一方で', '〜代わりに'],
    contrast: '「反面」＝同一物の対照的な二面；「一方で」＝並列（対照弱め）；「代わりに」＝交換・代償',
    recognition: { promptZh: '「この仕事は自由な反面、＿＿」最自然的接续是？',
      options: ['責任も重い', '給料も自由だ', '休みも自由だ', '毎日楽しい'],
      answerIndex: 0, distractorReason: '「反面」后面要接与「自由」对照的另一面（负担），同方向内容不成立',
      explanationZh: '「反面」需要对照性的另一面' },
    production: { promptJa: '物事の二面性を「〜反面」で言ってください。',
      promptZh: '用「〜反面」说说一件事物的两面性。',
      expected: ['反面'], acceptable: ['〜な反面'] },
    practice: { themeJa: '長所と短所を客観的に語る', starterJa: '今の生活のいい面と大変な面を教えてください。',
      starterZh: '说说你现在生活好的一面和辛苦的一面。', targetUse: '〜反面' },
    vocabularyLinks: ['fi-muzukashii', 'fi-nareru'] }),
  g({ grammarId: 'n2g-147', pattern: '〜べき', reading: 'べき', unit: 10, zhSourceRowId: 'n3row-5',
    meaningJa: '〜するのが当然だ（話し手の当為判断）',
    explanationZh: '应该…（理应如此）。说话人基于道理的当然判断',
    formation: '動詞辞書形 ＋べき（「する」は「すべき」も可）',
    usageScene: '主张守时是应该的、劝身体不适就该休息',
    nuance: '理屈上の当然。法律の義務は「なければならない」。目上には押しつけがましい',
    register: 'both',
    sourceExample: src('今からでも例文集を読んで覚えるべきです。', '2b6a0eb46b9ce090'),
    examplesJa: ['今からでも例文集を読んで覚えるべきです。',
                 '体調が悪いときは、無理をせず休むべきです。'],
    examplesZh: ['现在开始也应该读例句集记下来。', '身体不舒服时，就应该别硬撑好好休息。'],
    furigana: 'いまからでも れいぶんしゅうを よんで おぼえるべきです。',
    commonMistakesZh: '过去的懊悔用「べきだった」（本应该…）：「もっと早く始めるべきだった」。对上级用「べき」显得说教，换「〜たほうがいいかもしれません」',
    learnerFocus: '「べきだった」的后悔用法出场率极高：「昨日寝るべきだった」。先掌握过去形反而实用',
    similarPatterns: ['〜なければならない', '〜ものだ'],
    contrast: '「べき」＝理屈からの当然；「なければならない」＝義務・必要；「ものだ」＝社会通念・常識',
    recognition: { promptZh: '「あのとき謝るべきだった」的心情是？',
      options: ['后悔当时没道歉', '庆幸当时道歉了', '认为不该道歉', '已经道歉过了'],
      answerIndex: 0, distractorReason: '「べきだった」＝本应做却没做的后悔',
      explanationZh: '当为的过去形＝悔恨' },
    production: { promptJa: '「本来ならこうすべき」という意見を「〜べき」で言ってください。',
      promptZh: '用「〜べき」说一个你认为理应如此的主张。',
      expected: ['べき'], acceptable: ['〜べきだ', '〜べきです'] },
    practice: { themeJa: '筋の通った意見を言う', starterJa: '社会の中で「これは守るべきだ」と思うルールは何ですか？',
      starterZh: '你觉得社会上「理应遵守」的规则是什么？', targetUse: '〜べき' },
    vocabularyLinks: ['fi-genki', 'fi-neru'] }),
  g({ grammarId: 'n2g-148', pattern: '〜ほかない', reading: 'ほかない', unit: 10, zhSourceRowId: null,
    meaningJa: '〜する以外に方法がない（あきらめの選択）',
    explanationZh: '只好…、只能…。没有别的办法，无奈接受唯一选项',
    formation: '動詞辞書形 ＋ほか（は）ない／よりほかはない',
    usageScene: '末班车没了只好打车、没人替班只能自己做',
    nuance: '消去法の消極的選択。前向きな「に限る」と正反対の気分',
    register: 'both',
    matchKeys: ['ほかはない', 'ほかない', 'ほかありません'],
    sourceExample: src('終電がなくなったので、タクシーで帰るほかはないです。', '9c8634d83f6140a3'),
    examplesJa: ['終電がなくなったので、タクシーで帰るほかはないです。',
                 '代わりの人がいない以上、自分でやるほかありません。'],
    examplesZh: ['末班车没了，只好打车回家。', '既然没人能替，只能自己来做。'],
    furigana: 'しゅうでんが なくなったので、タクシーで かえる ほかは ないです。',
    commonMistakesZh: '和「に限る」气氛相反：「タクシーに限る」是主动推荐（打车最棒），「タクシーで帰るほかない」是无奈（只好打车）。心情选错句意全反',
    learnerFocus: '表达无可奈何的成熟说法：「こうなったら、待つほかないですね」。比「しかたない」更书面',
    similarPatterns: ['〜しかない', '〜ざるを得ない'],
    contrast: '「ほかない」＝方法の消去による消極選択；「しかない」＝口語で同義；「ざるを得ない」＝不本意な義務感がより強い',
    recognition: { promptZh: '「こうなったら、歩いて帰るほかない」的心情是？',
      options: ['无奈之下只能走回去', '很想走路回家（开心）', '拒绝走路回家', '已经到家了'],
      answerIndex: 0, distractorReason: '「ほかない」是消去法的无奈，不是积极愿望',
      explanationZh: '别无选择的接受' },
    production: { promptJa: '仕方なく選んだことを「〜ほかない」で言ってください。',
      promptZh: '用「〜ほかない」说一次别无选择的经历。',
      expected: ['ほか'], acceptable: ['〜ほかはない', '〜ほかありません'] },
    practice: { themeJa: 'ピンチの対応を話す', starterJa: '「もうこれしかない！」と覚悟を決めた経験はありますか？',
      starterZh: '有过「只剩这一条路」的时刻吗？', targetUse: '〜ほかない' },
    vocabularyLinks: ['fi-densha', 'fi-kaeru'] }),
  g({ grammarId: 'n2g-149', pattern: '〜ほど', reading: 'ほど', unit: 10, zhSourceRowId: 'n3row-105',
    meaningJa: '〜という程度に／〜くらい',
    explanationZh: '到…的程度。用比喻、极端例子来形容程度之高',
    formation: '動詞普通形／い形容詞／名詞 ＋ほど',
    usageScene: '高兴到想哭、忙到没时间吃饭、程度的比喻表达',
    nuance: '程度の高さを実感を込めて描く。「ば〜ほど」との使い分けに注意',
    register: 'both',
    sourceExample: src('試験勉強をすればするほど、会話力が上がるわけではないです。', '177603cbbb41740c'),
    examplesJa: ['試験勉強をすればするほど、会話力が上がるわけではないです。',
                 '泣きたいほど、うれしかったです。'],
    examplesZh: ['并不是应试学习做得越多，会话能力就越高。', '高兴得都想哭了。'],
    furigana: 'しけんべんきょうを すれば するほど、かいわりょくが あがる わけではないです。',
    commonMistakesZh: '比喻程度时「ほど」和「くらい」可换，但「死ぬほど疲れた」这类夸张惯用多用「ほど」。比较句「AほどBない」（没有比A更B的）是另一重要用法',
    learnerFocus: '「死ぬほど」「泣きたいほど」「数えきれないほど」三个高频搭配先背下来，表达力立刻翻倍',
    similarPatterns: ['〜くらい', '〜ば〜ほど'],
    contrast: '「ほど」＝程度の比喩・強調；「くらい」＝軽い程度にも使える；「ば〜ほど」＝比例変化の型',
    recognition: { promptZh: '「今日は死ぬほど忙しかった」的意思是？',
      options: ['忙到要命（夸张形容）', '真的遇到了生命危险的意思', '其实一点也不忙，非常清闲', '正在忙着帮别人操办葬礼的事'],
      answerIndex: 0, distractorReason: '「死ぬほど」是程度夸张的惯用比喻',
      explanationZh: '用极端比喻形容程度之高' },
    production: { promptJa: '程度の高さを比喩で「〜ほど」で言ってください。',
      promptZh: '用「〜ほど」夸张地形容一次程度。',
      expected: ['ほど'], acceptable: ['死ぬほど', '泣きたいほど'] },
    practice: { themeJa: '感情を大きく表現する', starterJa: '最近「泣きたいほど」うれしかった（大変だった）ことは？',
      starterZh: '最近有没有高兴（辛苦）到想哭的事？', targetUse: '〜ほど' },
    vocabularyLinks: ['fi-ureshii', 'fi-kanjiru'] }),
  g({ grammarId: 'n2g-150', pattern: '〜まい', reading: 'まい', unit: 10, zhSourceRowId: null,
    meaningJa: '絶対〜しない（意志）／〜ないだろう（推量）',
    explanationZh: '绝不…（决心）；大概不会…（推测）。文言残留的否定表达',
    formation: '動詞辞書形 ＋まい（Ⅱ類・Ⅲ類は「見まい・すまい・来（こ）まい」等も）',
    usageScene: '发誓再也不去被宰的店、书面里推测大概不会发生',
    nuance: '意志用法は一人称の固い決意。推量用法は書面語で「〜ないだろう」',
    register: 'written',
    sourceExample: src('あそこの飲食店でぼったくりをされて、もう二度と行くまいと思いました。', 'e828b32588b8d8ed'),
    examplesJa: ['あそこの飲食店でぼったくりをされて、もう二度と行くまいと思いました。',
                 '彼はもう来まいと思っていたら、遅れて現れました。'],
    examplesZh: ['在那家店被宰了一顿，心想再也不去了。', '本以为他大概不会来了，结果他迟到了才出现。'],
    furigana: 'あそこの いんしょくてんで ぼったくりを されて、もう にどと いくまいと おもいました。',
    commonMistakesZh: '意志用法主语只能是自己：「彼は行くまいと思った」若表他的决心要说「行くまいと思っているようだ」。「二度と〜まい」是决心的定型搭配',
    learnerFocus: '发狠话的书面表达：「もう夜更かしはすまい」。日记、小说里常见，口语说「絶対しない」即可',
    similarPatterns: ['〜ないつもりだ', '〜ないだろう'],
    contrast: '「まい」＝固い否定の意志／書面の否定推量；「ないつもりだ」＝中立の否定予定；「ないだろう」＝口語寄りの否定推測',
    recognition: { promptZh: '「二度と遅刻はするまい」的意思是？',
      options: ['下定决心再也不迟到', '大概今后还是会迟到吧', '让别人别迟到', '已经迟到了两次'],
      answerIndex: 0, distractorReason: '「二度と〜まい」＝强烈的否定决心',
      explanationZh: '一人称的坚定否定意志' },
    production: { promptJa: '固い決意を「二度と〜まい」で言ってください。',
      promptZh: '用「二度と〜まい」发一个狠誓。',
      expected: ['まい'], acceptable: ['二度と〜まい'] },
    practice: { themeJa: '教訓を決意に変える', starterJa: '失敗から「もう二度としない」と決めたことはありますか？',
      starterZh: '有没有从失败中发誓「再也不做」的事？', targetUse: '〜まい' },
    vocabularyLinks: ['fi-taberu', 'fi-kimeru'] }),
];
