// Phase 3P-5: N2文法完成draft Unit 3（原本No.31〜45・13文型）＋Unit1穴埋め2件（n2g-009/010）。
// rightsStatus: teacher_created_confirmed（CEO確認済み）。原本例文をruntime使用可。
import type { N2GrammarDraft } from './n2GrammarDrafts';

const g = (p: Omit<N2GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey' | 'runtimeExampleOrigin'> & { reviewKey?: string; runtimeExampleOrigin?: N2GrammarDraft['runtimeExampleOrigin'] }): N2GrammarDraft =>
  ({ level: 'N2', route: 'n2-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, runtimeExampleOrigin: 'source_confirmed', ...p });

const src = (text: string, hash: string) =>
  ({ text, hash, rightsStatus: 'teacher_created_confirmed' as const });

/** Unit1の未執筆だった2件（訂正記録参照）＋Unit3の13件。 */
export const N2_GRAMMAR_DRAFTS_UNIT3: N2GrammarDraft[] = [
  g({ grammarId: 'n2g-009', pattern: '〜うちは', reading: 'うちは', unit: 1, zhSourceRowId: null,
    meaningJa: 'その状態が続く間は（変わらない）',
    explanationZh: '只要还处于…的状态，（结果）就不会变',
    formation: '動詞辞書形／ている形／ない形／名詞＋の ＋うちは',
    usageScene: '指出方法不变则结果不变、条件持续期间的状态',
    nuance: '和「うちに」（趁着）只差一个字，意思却不同。「うちは」表示状态持续期间的限定',
    register: 'both',
    sourceExample: src('真面目に文法だけ勉強しているうちは、会話力は上がりません。', 'f10b09cc80af7139'),
    examplesJa: ['真面目に文法だけ勉強しているうちは、会話力は上がりません。',
                 '完璧を求めているうちは、話し始められません。'],
    examplesZh: ['只是认真地光学语法的话，会话能力不会提高。', '只要还在追求完美，就开不了口。'],
    furigana: 'まじめに ぶんぽうだけ べんきょうしている うちは、かいわりょくは あがりません。',
    commonMistakesZh: '容易把「うちに」（趁着…做）和「うちは」（在…期间一直）弄混。「は」带有对比和限定的意味',
    learnerFocus: '最适合用来说明学习方法上的反省。按「〜ているうちは〜ない」这个形式整套记',
    similarPatterns: ['〜うちに', '〜限りは'],
    contrast: '「うちは」＝状態が続く間は（否定的結果が多い）；「うちに」＝状態が変わる前に',
    recognition: { promptZh: '「独身のうちは自由だ」是什么意思？',
      options: ['单身期间是自由的', '趁单身要快点结婚', '不想单身', '已经结婚了'],
      answerIndex: 0, distractorReason: '「うちは」表示该状态持续期间的情况',
      explanationZh: '「〜うちは」= 在…期间一直' },
    production: { promptJa: '「このやり方のままでは変わらない」を「〜うちは」で言ってください。',
      promptZh: '用「〜うちは」表达方法不变结果就不变。',
      expected: ['うちは'], acceptable: ['〜ているうちは'] },
    practice: { themeJa: '学習方法を見直す', starterJa: 'どんな勉強のままでは上達しないと思いますか？',
      starterZh: '你觉得怎样的学习方式不会进步？', targetUse: '〜うちは' },
    vocabularyLinks: ['fi-benkyo', 'fi-hanasu'] }),
  g({ grammarId: 'n2g-010', pattern: '〜（し）ようではないか', reading: 'ようではないか', unit: 1, zhSourceRowId: null,
    meaningJa: 'みんなで〜しよう（呼びかけ）',
    explanationZh: '让我们一起…吧（正式的号召）',
    formation: '動詞意向形 ＋ではないか（じゃないか）',
    usageScene: '演讲、会议上号召大家一起行动',
    nuance: '演讲腔，比较生硬。日常会话里说「〜しようよ」',
    register: 'written',
    matchKeys: ['ようではないか', 'ようじゃないか'],
    sourceExample: src('そろそろ日本語の勉強をしようではないか。＝〜しましょうよ＝しようじゃないですか', '07026ef9249b8811'),
    examplesJa: ['そろそろ日本語の勉強をしようではないか。',
                 'この問題を、みんなで解決しようではないか。'],
    examplesZh: ['差不多该学日语了吧，让我们开始吧。', '让我们大家一起解决这个问题吧。'],
    furigana: 'そろそろ にほんごの べんきょうを しようでは ないか。',
    commonMistakesZh: '形式上是疑问句，意思却是很强的劝诱。读成上扬的「ではないか？」会被误解',
    learnerFocus: '用在演讲的结尾很有气势。先做到在阅读和听力里能听出这是「号召」',
    similarPatterns: ['〜ましょう', '〜しよう'],
    contrast: '丁寧さ・硬さ: 「しよう」＜「しましょう」＜「しようではないか」（演説調）',
    recognition: { promptZh: '「協力しようではないか」的语气是？',
      options: ['正式地号召大家合作', '询问是否合作', '拒绝合作', '抱怨合作'],
      answerIndex: 0, distractorReason: '形式是疑问，实际是强烈的号召',
      explanationZh: '演讲腔的号召说法' },
    production: { promptJa: 'スピーチの締めを「〜ようではないか」で言ってください。',
      promptZh: '用「〜ようではないか」说一句演讲结尾。',
      expected: ['ようではないか'], acceptable: ['〜しようではないか'] },
    practice: { themeJa: 'スピーチ調で呼びかける', starterJa: 'クラスのみんなに何かを呼びかけるとしたら？',
      starterZh: '如果要号召班里的大家做一件事，你会说什么？', targetUse: '〜ようではないか' },
    vocabularyLinks: ['fi-ganbaru', 'fi-mondai'] }),
  g({ grammarId: 'n2g-031', pattern: '〜からいうと', reading: 'からいうと', unit: 3, zhSourceRowId: null,
    meaningJa: '〜の立場・観点から判断すると',
    explanationZh: '从…（立场/角度）来说',
    formation: '名詞 ＋からいうと／からいえば',
    usageScene: '从专业、经验、立场出发发表意见',
    nuance: '像「私からいうと」这样直接放人称有点不自然，说「立場からいうと」更稳妥',
    register: 'both',
    sourceExample: src('中国人の立場からいうと、日本の大学の英語レベルはすごく簡単です。', '83f210a8636b2c6f'),
    examplesJa: ['中国人の立場からいうと、日本の大学の英語レベルはすごく簡単です。',
                 '経験からいうと、毎日少しずつのほうが続きます。'],
    examplesZh: ['从中国人的角度来说，日本大学的英语水平非常简单。', '从经验来说，每天一点点更容易坚持。'],
    furigana: 'ちゅうごくじんの たちばから いうと、にほんの だいがくの えいごレベルは すごく かんたんです。',
    commonMistakesZh: '直接说「私からいうと」不自然，要说「私の立場からいうと」「私の経験からいうと」',
    learnerFocus: '会议上表达意见的开场白。想传达中日双语者的独特视角时很好用',
    similarPatterns: ['〜からすると', '〜から見ると', '〜にとって'],
    contrast: '「からいうと」「からすると」「から見ると」はほぼ同義（判断の観点）。「にとって」は評価対象',
    recognition: { promptZh: '「プロからいうと」的意思是？',
      options: ['从专业角度来说', '对着专业人士说的话', '成为一名专业人士', '根本就不是专业的'],
      answerIndex: 0, distractorReason: '「からいうと」表示判断的出发点',
      explanationZh: '表明判断的角度' },
    production: { promptJa: '自分の経験からの意見を「〜からいうと」で言ってください。',
      promptZh: '用「〜からいうと」从你的经验发表意见。',
      expected: ['からいうと'], acceptable: ['経験からいうと', '立場からいうと'] },
    practice: { themeJa: '経験者として意見を言う', starterJa: '日本語学習の経験からいうと、何が一番大切ですか？',
      starterZh: '从你学日语的经验来说，什么最重要？', targetUse: '〜からいうと' },
    vocabularyLinks: ['fi-keiken', 'fi-iken'] }),
  g({ grammarId: 'n2g-032', pattern: '〜からこそ', reading: 'からこそ', unit: 3, zhSourceRowId: null,
    meaningJa: 'まさに〜だから（理由の強調）',
    explanationZh: '正因为…才…。强调理由',
    formation: '動詞・い形容詞普通形／な形容詞・名詞＋だ ＋からこそ',
    usageScene: '强调「正因为有这个原因」，多用于积极评价',
    nuance: '比普通的「から」更强地肯定理由。用在表达感谢和自豪的语境里很出彩',
    register: 'both',
    sourceExample: src('たくさん頑張ったからこそ、今のレベルに到達できたと思います。', '4da9d100870616dc'),
    examplesJa: ['たくさん頑張ったからこそ、今のレベルに到達できたと思います。',
                 '外国人だからこそ、気づける違いがあります。'],
    examplesZh: ['正因为付出了很多努力，才达到了现在的水平。', '正因为是外国人，才能注意到的差异。'],
    furigana: 'たくさん がんばったからこそ、いまの レベルに とうたつ できたと おもいます。',
    commonMistakesZh: '注意「こそ」的位置。「からこそ」是一个整体，写成「こそから」是错的',
    learnerFocus: '面试时讲「外国人だからこそ貢献できること」（正因为是外国人才能做的贡献）很有说服力，是把劣势转成优势的固定说法',
    similarPatterns: ['〜から', '〜おかげで'],
    contrast: '「から」＝中立の理由；「からこそ」＝理由の強調（誇り・感謝）；「おかげで」＝感謝',
    recognition: { promptZh: '「あなただからこそ頼みたい」的语气是？',
      options: ['正因为是你才想拜托（强调）', '随便谁都行', '不想拜托你', '这件事情已经拜托给别的人去做了'],
      answerIndex: 0, distractorReason: '「からこそ」强调该理由的特别性',
      explanationZh: '强调理由' },
    production: { promptJa: '努力の成果を「〜からこそ」で言ってください。',
      promptZh: '用「〜からこそ」说努力带来的成果。',
      expected: ['からこそ'], acceptable: ['頑張ったからこそ'] },
    practice: { themeJa: '自分の強みをポジティブに語る',
      starterJa: '外国人だからこそできること、何があると思いますか？',
      starterZh: '正因为是外国人才能做到的事，你觉得有什么？', targetUse: '〜からこそ' },
    vocabularyLinks: ['fi-ganbaru', 'fi-keiken'] }),
  g({ grammarId: 'n2g-033', pattern: '〜からして', reading: 'からして', unit: 3, zhSourceRowId: null,
    meaningJa: '〜から判断して／〜をはじめとして',
    explanationZh: '光从…来看（就…）。举最基本的例子做判断',
    formation: '名詞 ＋からして',
    usageScene: '从外观、第一印象做判断',
    nuance: '含有「光是从…就已经…」的意味。既可以用于批评，也可以用于称赞',
    register: 'both',
    sourceExample: src('この料理の色からして、絶対に辛い食べ物だと分かります。', 'a2780c5486618795'),
    examplesJa: ['この料理の色からして、絶対に辛い食べ物だと分かります。',
                 'あの店は、入口の雰囲気からして高そうです。'],
    examplesZh: ['光看这道菜的颜色，就知道绝对是辣的。', '那家店光看门口的氛围就显得很贵。'],
    furigana: 'この りょうりの いろからして、ぜったいに からい たべものだと わかります。',
    commonMistakesZh: '和「からすると」（从…判断）相似，但「からして」强调「光是从第一点就已经…」',
    learnerFocus: '聊第一印象时很好用。也可以用来称赞，比如「名前からして面白い」（光名字就有意思）',
    similarPatterns: ['〜からすると', '〜から見ると'],
    contrast: '「からして」＝代表例を挙げて「もうこの時点で」；「からすると」＝根拠からの推測',
    recognition: { promptZh: '「タイトルからして面白そう」是什么意思？',
      options: ['光看标题就觉得有意思', '觉得标题起得不太好', '还没有看到标题', '觉得标题太难懂了'],
      answerIndex: 0, distractorReason: '「からして」表示从最初的一点就能判断',
      explanationZh: '根据第一个要素做出的判断' },
    production: { promptJa: '見た目からの判断を「〜からして」で言ってください。',
      promptZh: '用「〜からして」根据外观做判断。',
      expected: ['からして'], acceptable: ['色からして', '雰囲気からして'] },
    practice: { themeJa: '第一印象を話す', starterJa: '日本に来て、何からして違うと感じましたか？',
      starterZh: '来日本后，你从哪一点就感觉到不同？', targetUse: '〜からして' },
    vocabularyLinks: ['fi-wakaru', 'fi-kanjiru'] }),
  g({ grammarId: 'n2g-035', pattern: '〜からといって', reading: 'からといって', unit: 3, zhSourceRowId: null,
    meaningJa: '〜という理由だけでは（…とは限らない）',
    explanationZh: '虽说…但（并不能因此就…）。否定片面推论',
    formation: '動詞・い形容詞普通形／な形容詞・名詞＋だ ＋からといって',
    usageScene: '提醒不要以单一理由下结论',
    nuance: '后半句一定是部分否定或提醒（「〜とは限らない」「〜わけではない」、不可大意）',
    register: 'both',
    sourceExample: src('褒められたからといって、油断は禁物です。', 'db77b8067c81d3cf'),
    examplesJa: ['褒められたからといって、油断は禁物です。',
                 '日本に住んでいるからといって、自然に上手になるわけではありません。'],
    examplesZh: ['虽说被夸奖了，但不能大意。', '虽说住在日本，也不会自然而然变好。'],
    furigana: 'ほめられたからと いって、ゆだんは きんもつです。',
    commonMistakesZh: '后半句用肯定结尾就不成立。说「〜からといって、嬉しいです」是错的',
    learnerFocus: '很适合用来讲「光住在那里并不会进步」这个学习上的真相',
    similarPatterns: ['〜だけで', '〜とは限らない'],
    contrast: '「からといって」＋部分否定はセット。「から」だけなら普通の理由',
    recognition: { promptZh: '「安いからといって」后面最自然的是？',
      options: ['買いすぎはよくない', 'たくさん買います', '嬉しいです', '高いです'],
      answerIndex: 0, distractorReason: '「からといって」后面要接否定或提醒',
      explanationZh: '否定片面的推论' },
    production: { promptJa: '「それだけでは十分でない」ことを「〜からといって」で言ってください。',
      promptZh: '用「〜からといって」表达仅凭该理由并不够。',
      expected: ['からといって'], acceptable: ['〜からといって〜わけではない'] },
    practice: { themeJa: '学習の思い込みを正す',
      starterJa: '「日本にいれば上手になる」と思いますか？「〜からといって」で答えてみましょう',
      starterZh: '你觉得「在日本就会变好」吗？用「〜からといって」回答', targetUse: '〜からといって' },
    vocabularyLinks: ['fi-benkyo', 'fi-nareru'] }),
  g({ grammarId: 'n2g-036', pattern: '〜からには', reading: 'からには', unit: 3, zhSourceRowId: null,
    meaningJa: '〜のだから、当然（決意・義務）',
    explanationZh: '既然…就（要）…。表示决心或当然的义务',
    formation: '動詞普通形 ＋からには',
    usageScene: '表明决心：既然开始了就要坚持到底',
    nuance: '和「以上は」基本同义，稍微偏口语。后半句接决心、义务或理所当然的内容',
    register: 'both',
    sourceExample: src('たくさん教えてもらったからには、試験に合格しなければなりません。', '38d4bee8cb9e8a5a'),
    examplesJa: ['たくさん教えてもらったからには、試験に合格しなければなりません。',
                 '日本で働くからには、敬語から逃げられません。'],
    examplesZh: ['既然承蒙教了这么多，就必须考过考试。', '既然要在日本工作，就避不开敬语。'],
    furigana: 'たくさん おしえて もらったからには、しけんに ごうかく しなければ なりません。',
    commonMistakesZh: '后半句要接决心或义务。像「〜からには、たぶん行きます」这样弱的推测不自然',
    learnerFocus: '和「以上は」（偏书面）配成一对记。这是表明决心的两大说法',
    similarPatterns: ['〜以上は', '〜のだから'],
    contrast: '「からには」＝口語寄りの決意；「以上は」＝書面寄り。意味はほぼ同じ',
    recognition: { promptZh: '「引き受けたからには」后面最自然的是？',
      options: ['最後までやります', 'やめるかもしれません', '知りません', '関係ありません'],
      answerIndex: 0, distractorReason: '「からには」后面接决心或义务',
      explanationZh: '既然…就要…' },
    production: { promptJa: '決意を「〜からには」で言ってください。',
      promptZh: '用「〜からには」表达决心。',
      expected: ['からには'], acceptable: ['始めたからには', '来たからには'] },
    practice: { themeJa: '決意を語る', starterJa: '日本に来たからには、何を成し遂げたいですか？',
      starterZh: '既然来了日本，你想完成什么？', targetUse: '〜からには' },
    vocabularyLinks: ['fi-ganbaru', 'fi-shigoto'] }),
  g({ grammarId: 'n2g-038', pattern: '〜代わりに', reading: 'かわりに', unit: 3, zhSourceRowId: 'n3row-83',
    meaningJa: '〜の代わりとして／〜する一方で（交換）',
    explanationZh: '作为替代…／作为交换…。这是N3「かわりに」在N2里的用法（谈交换条件）',
    formation: '動詞普通形／名詞＋の ＋代わりに',
    usageScene: '用于谈判、交易的场面（「〜する代わりに〜してほしい」）',
    nuance: '到了N2会增加「AするからにはBを求める」这种提出交换条件的用法',
    register: 'both',
    sourceExample: src('私があなたの授業を受ける代わりに、何がなんでも試験合格へ導いてください。', 'ca7e133b4307e464'),
    examplesJa: ['私があなたの授業を受ける代わりに、何がなんでも試験合格へ導いてください。',
                 '残業を引き受ける代わりに、明日は早く帰らせてください。'],
    examplesZh: ['我上你的课作为交换，请务必带我考过考试。', '我接下加班作为交换，请让我明天早点回去。'],
    furigana: 'わたしが あなたの じゅぎょうを うける かわりに、なにが なんでも しけんごうかくへ みちびいて ください。',
    commonMistakesZh: '和N3的「替代」用法的区别：N2可以用来「提出交换条件」，是谈判的工具',
    learnerFocus: '职场谈判时，「〜する代わりに〜してもらえますか」能不伤和气地提出条件',
    similarPatterns: ['〜代わりに（N3・代替）', '〜てもらう代わりに'],
    contrast: 'N3用法＝単純な代替；N2用法＝give and takeの交渉',
    recognition: { promptZh: '「手伝う代わりに、今度おごってください」是什么关系？',
      options: ['交换条件（我帮忙，你请客）', '只是单纯的替代，没有任何交换', '直接拒绝了帮忙，什么都不肯做', '完全免费地帮忙，不要任何回报'],
      answerIndex: 0, distractorReason: '这是「代わりに」的交换条件用法',
      explanationZh: '有来有往的谈判说法' },
    production: { promptJa: '交換条件を「〜代わりに」で提案してください。',
      promptZh: '用「〜代わりに」提出一个交换条件。',
      expected: ['代わりに'], acceptable: ['〜する代わりに'] },
    practice: { themeJa: '角を立てない交渉をする',
      starterJa: '同僚に何かを頼むとき、交換条件をどう出しますか？',
      starterZh: '拜托同事时，你会怎么提出交换条件？', targetUse: '〜代わりに' },
    vocabularyLinks: ['fi-soudan', 'fi-shigoto'] }),
  g({ grammarId: 'n2g-039', pattern: '〜気味', reading: 'ぎみ', unit: 3, zhSourceRowId: null,
    meaningJa: '少し〜の傾向がある（体調・状態）',
    explanationZh: '有点…、稍微有…的倾向（多为不好的状态）',
    formation: '動詞ます形／名詞 ＋気味',
    usageScene: '说明轻微的身体不适、状态倾向',
    nuance: '固定说法有「疲れ気味」「風邪気味」「太り気味」，表示自己感觉到的轻微症状',
    register: 'both',
    sourceExample: src('最近、忙しすぎて、疲れ気味です。', 'e6478c7275d5ea2f'),
    examplesJa: ['最近、忙しすぎて、疲れ気味です。', '少し風邪気味なので、今日は早めに休みます。'],
    examplesZh: ['最近太忙，有点疲惫。', '有点感冒的征兆，今天早点休息。'],
    furigana: 'さいきん、いそがしすぎて、つかれぎみです。',
    commonMistakesZh: '「がち」说的是频率上的倾向，「気味」说的是现在的轻微状态。比起「遅刻気味」，「遅刻しがち」更自然',
    learnerFocus: '作为描述身体状况的词很实用。请假联络时常说「風邪気味で…」（有点感冒）',
    similarPatterns: ['〜がち', '〜っぽい'],
    contrast: '「気味」＝今の軽い状態；「がち」＝繰り返しの傾向；「っぽい」＝性質の印象',
    recognition: { promptZh: '「風邪気味です」是什么状态？',
      options: ['有点感冒的征兆', '感冒已经非常严重了', '感冒好了', '从不感冒'],
      answerIndex: 0, distractorReason: '「気味」表示轻微的状态倾向',
      explanationZh: '自己感觉到的轻微症状' },
    production: { promptJa: '軽い体調不良を「〜気味」で言ってください。',
      promptZh: '用「〜気味」说轻微的身体不适。',
      expected: ['気味'], acceptable: ['疲れ気味', '風邪気味'] },
    practice: { themeJa: '体調を軽く伝える', starterJa: '最近、何か「〜気味」なことはありますか？',
      starterZh: '最近有什么「有点…」的状态吗？', targetUse: '〜気味' },
    vocabularyLinks: ['fi-isogashii', 'fi-genki'] }),
  g({ grammarId: 'n2g-040', pattern: '〜（た）きりだ', reading: 'きりだ', unit: 3, zhSourceRowId: 'n3row-84',
    meaningJa: '〜して以来、そのままだ',
    explanationZh: '自从…就一直（没）…。这是N3「きり」表示状态持续的强调用法',
    formation: '動詞た形 ＋きり（だ）',
    usageScene: '说明中断后一直没恢复的状态',
    nuance: '在句尾说成「〜たきりだ」。N3学的是接续用法，N2再加上句尾用法',
    register: 'both',
    sourceExample: src('骨折をしたきり、運動をしていないです。', 'dd38a779ade9a50d'),
    examplesJa: ['骨折をしたきり、運動をしていないです。', '大学を卒業したきり、英語は使っていません。'],
    examplesZh: ['自从骨折后就一直没运动。', '大学毕业后就再没用过英语。'],
    furigana: 'こっせつを したきり、うんどうを していないです。',
    commonMistakesZh: '后半句接「していない」等否定或没有变化的内容。不能用于肯定的持续',
    learnerFocus: '最适合用来说明自己「有一段空白期」。和「想重新开始」的语境搭配着用会显得积极',
    similarPatterns: ['〜て以来', '〜まま'],
    contrast: '「たきり」＝中断の強調（否定続き）；「て以来」＝中立の起点；「まま」＝状態保持',
    recognition: { promptZh: '「会ったきりだ」是什么意思？',
      options: ['见过一次后就再没见', '之后还经常见面', '约好明天要见面', '从来不想见面'],
      answerIndex: 0, distractorReason: '「たきり」表示之后一直没有后续',
      explanationZh: '中断状态的持续' },
    production: { promptJa: 'ブランクがあることを「〜たきり」で言ってください。',
      promptZh: '用「〜たきり」说一件中断已久的事。',
      expected: ['きり'], acceptable: ['〜たきり'] },
    practice: { themeJa: '再開したいことを話す', starterJa: '「〜したきり、やっていない」ことはありますか？',
      starterZh: '有什么事是「做过一次后就再没做」的？', targetUse: '〜たきり' },
    vocabularyLinks: ['fi-owaru', 'fi-hajimeru'] }),
  g({ grammarId: 'n2g-041', pattern: '〜きる', reading: 'きる', unit: 3, zhSourceRowId: null,
    meaningJa: '最後まで完全に〜する',
    explanationZh: '…完、…到底。彻底完成',
    formation: '動詞ます形 ＋きる／きれる／きれない',
    usageScene: '强调坚持到最后：跑完全程、用完、卖光',
    nuance: '否定的可能形「〜きれない」（…不完）也很常见（「食べきれない」「数えきれない」）',
    register: 'both',
    sourceExample: src('筋トレを最後の一回までやりきることができました。', '24624db504a065bb'),
    examplesJa: ['筋トレを最後の一回までやりきることができました。',
                 '量が多すぎて、一人では食べきれません。'],
    examplesZh: ['肌肉训练坚持做完了最后一次。', '量太多，一个人吃不完。'],
    furigana: 'きんトレを さいごの いっかいまで やりきることが できました。',
    commonMistakesZh: '「終わる」是自然结束，「きる」是靠意志坚持到最后。区别在于有没有成就感',
    learnerFocus: '「やりきった」（做到底了）能传达出达成感，面试和总结时很有力',
    similarPatterns: ['〜終わる', '〜抜く'],
    contrast: '「きる」＝完全にやり終える；「抜く」＝困難を乗り越えて最後まで；「終わる」＝中立',
    recognition: { promptZh: '「食べきれない」是什么意思？',
      options: ['吃不完', '不想吃', '吃完了', '很好吃'],
      answerIndex: 0, distractorReason: '「きれない」表示无法彻底完成',
      explanationZh: '「〜きれない」= …不完' },
    production: { promptJa: '最後までやり遂げた経験を「〜きる」で言ってください。',
      promptZh: '用「〜きる」说一次坚持到底的经历。',
      expected: ['き'], acceptable: ['やりきった', '走りきった'] },
    practice: { themeJa: 'やり遂げた経験を話す', starterJa: '最後までやりきった経験はありますか？',
      starterZh: '有坚持做完到最后的经历吗？', targetUse: '〜きる' },
    vocabularyLinks: ['fi-ganbaru', 'fi-owaru'] }),
  g({ grammarId: 'n2g-042', pattern: '〜くせに', reading: 'くせに', unit: 3, zhSourceRowId: null,
    meaningJa: '〜のに（非難・軽蔑を込めて）',
    explanationZh: '明明…却…（带责备、轻蔑的语气）',
    formation: '動詞・い形容詞普通形／な形容詞＋な／名詞＋の ＋くせに',
    usageScene: '亲近的人之间的抱怨、自嘲',
    nuance: '比「のに」更带情绪，也更失礼。对长辈上司绝对不能用，自嘲则没问题',
    register: 'spoken',
    sourceExample: src('何時間も寝たくせに、まだ眠たいです。', 'a24c8a5c2c4b5cda'),
    examplesJa: ['何時間も寝たくせに、まだ眠たいです。', '知っているくせに、教えてくれませんでした。'],
    examplesZh: ['明明睡了好几个小时，却还困（自嘲）。', '明明知道，却不告诉我。'],
    furigana: 'なんじかんも ねたくせに、まだ ねむたいです。',
    commonMistakesZh: '对上司和客户使用是很失礼的。换成「のに」就安全。用在自己身上则显得亲切',
    learnerFocus: '首先要能听懂（日剧和日常会话里很常见）。自己要用的话，先从自嘲开始',
    similarPatterns: ['〜のに', '〜にもかかわらず'],
    contrast: '感情の強さ: 「にもかかわらず」（書面・中立）＜「のに」（不満）＜「くせに」（非難）',
    recognition: { promptZh: '「くせに」不能对谁使用？',
      options: ['上司や客', '親しい友人（冗談で）', '自分（自嘲）', '弟や妹'],
      answerIndex: 0, distractorReason: '「くせに」带责备语气，对上位者失礼',
      explanationZh: '对长辈上司连「のに」都要谨慎，「くせに」则是禁用' },
    production: { promptJa: '自分への自嘲を「〜くせに」で言ってください。',
      promptZh: '用「〜くせに」自嘲一下。',
      expected: ['くせに'], acceptable: ['〜たくせに'] },
    practice: { themeJa: '自嘲で笑いを取る', starterJa: '「〜したくせに、まだ〜」という自分の矛盾はありますか？',
      starterZh: '你有「明明…却还…」的自相矛盾吗？', targetUse: '〜くせに' },
    vocabularyLinks: ['fi-neru', 'fi-wasureru'] }),
  g({ grammarId: 'n2g-043', pattern: '〜くらい', reading: 'くらい', unit: 3, zhSourceRowId: null,
    meaningJa: '〜程度の（軽視・最低限）',
    explanationZh: '…这种程度（的话）。表示程度轻，「至少」「起码」',
    formation: '動詞普通形／名詞 ＋くらい（ぐらい）',
    usageScene: '表示「这点小事我也会」，说的是最低限度的要求',
    nuance: '带轻视意味的「くらい」，用法不同可能失礼，也可能是谦虚',
    register: 'spoken',
    sourceExample: src('これくらいの簡単な曲であれば、私もピアノを弾くことができます。', 'd9196b9fec29b6c9'),
    examplesJa: ['これくらいの簡単な曲であれば、私もピアノを弾くことができます。',
                 'あいさつくらいは、日本語でできるようになりたいです。'],
    examplesZh: ['这种程度的简单曲子，我也能弹。', '至少打招呼，希望能用日语做到。'],
    furigana: 'これくらいの かんたんな きょくで あれば、わたしも ピアノを ひくことが できます。',
    commonMistakesZh: '对别人说「これくらいできるでしょ」很失礼。用在自己身上就成了谦虚',
    learnerFocus: '「〜くらいは」（至少…）很适合用来设定谦虚的目标。和「せめて」配成一对记',
    similarPatterns: ['〜ほど', '〜程度'],
    contrast: '「くらい」＝軽視・最低限（口語）；「ほど」＝程度の高さ；「程度」＝書面',
    recognition: { promptZh: '「名前くらいは書けます」的语气是？',
      options: ['谦虚地说至少会写名字', '自豪地夸耀自己写得很好', '说自己完全不会写任何字', '表示根本就不想动手写字'],
      answerIndex: 0, distractorReason: '自分に使う「くらい」は謙遜',
      explanationZh: '最低限度的谦虚说法' },
    production: { promptJa: '最低限できることを「〜くらい」で言ってください。',
      promptZh: '用「〜くらい」谦虚地说至少会做的事。',
      expected: ['くらい'], acceptable: ['〜くらいは', '〜ぐらい'] },
    practice: { themeJa: '謙遜しながらできることを言う',
      starterJa: '「これくらいならできます」と言えることはありますか？',
      starterZh: '有什么是你能说「这种程度的话我会」的？', targetUse: '〜くらい' },
    vocabularyLinks: ['fi-kantan', 'fi-kaku'] }),
  g({ grammarId: 'n2g-044', pattern: '〜ことか', reading: 'ことか', unit: 3, zhSourceRowId: null,
    meaningJa: 'どれほど〜だったことか（感嘆）',
    explanationZh: '多么…啊（感叹）。与疑问词呼应表达强烈感慨',
    formation: 'どれだけ／どんなに／何度 ＋〜た ＋ことか',
    usageScene: '回顾长期的辛苦、喜悦时的感叹',
    nuance: '书面语和演讲腔。用「どんなに嬉しかったことか」来表达万千感慨',
    register: 'written',
    sourceExample: src('今日、筋トレをどれだけしたことか。疲れすぎてもう動けないです。', '0385dc750ca8d490'),
    examplesJa: ['今日、筋トレをどれだけしたことか。疲れすぎてもう動けないです。',
                 '合格の知らせを聞いて、どんなに嬉しかったことか。'],
    examplesZh: ['今天做了多少肌肉训练啊。累得已经动不了了。', '听到合格的消息，是多么高兴啊。'],
    furigana: 'きょう、きんトレを どれだけ したことか。つかれすぎて もう うごけないです。',
    commonMistakesZh: '一定要和「どれだけ」「どんなに」「何度」等疑问词搭配。单独用「〜ことか」不完整',
    learnerFocus: '用在演讲的高潮处能传达感情。在阅读里能认出这是「感叹」很重要',
    similarPatterns: ['〜ことだろう', '〜ものだ'],
    contrast: '「ことか」＝感嘆（疑問詞と呼応）；「ことだろう」＝推量含み；「ものだ」＝しみじみ',
    recognition: { promptZh: '「何度あきらめようと思ったことか」的语气是？',
      options: ['感叹想放弃过多少次', '询问对方一共放弃过多少次', '从没想过放弃', '已经放弃了'],
      answerIndex: 0, distractorReason: '疑問詞＋ことか是感叹，不是提问',
      explanationZh: '感嘆表現' },
    production: { promptJa: '長い努力の感慨を「どんなに〜ことか」で言ってください。',
      promptZh: '用「どんなに〜ことか」感叹长期的努力。',
      expected: ['ことか'], acceptable: ['どんなに〜ことか', 'どれだけ〜ことか'] },
    practice: { themeJa: '感慨を込めて振り返る',
      starterJa: '日本語学習で「どんなに大変だったことか」と思う瞬間はありましたか？',
      starterZh: '学日语时有过「多么不容易啊」的瞬间吗？', targetUse: 'どんなに〜ことか' },
    vocabularyLinks: ['fi-ganbaru', 'fi-ureshii'] }),
  g({ grammarId: 'n2g-045', pattern: '〜ことから', reading: 'ことから', unit: 3, zhSourceRowId: null,
    meaningJa: '〜という事実が理由・由来となって',
    explanationZh: '由于…（的事实）、因…而得名',
    formation: '動詞・い形容詞普通形／な形容詞＋な／名詞＋である ＋ことから',
    usageScene: '说明地名的由来、事情的起因（书面）',
    nuance: '表示客观的由来和依据。比「から」更具说明性，偏书面',
    register: 'written',
    sourceExample: src('日本語と中国語ができることから、翻訳の仕事の依頼が来ました。', 'e84c2addf836ab1c'),
    examplesJa: ['日本語と中国語ができることから、翻訳の仕事の依頼が来ました。',
                 '桜の名所であることから、この駅は春に大変混雑します。'],
    examplesZh: ['由于会日语和中文，来了翻译工作的委托。', '因为是赏樱名胜，这个车站春天非常拥挤。'],
    furigana: 'にほんごと ちゅうごくごが できることから、ほんやくの しごとの いらいが きました。',
    commonMistakesZh: '主观的理由用「から」，客观的事实由来用「ことから」。这是新闻和说明文的文体',
    learnerFocus: '讲双语能力带来的机会的例句，可以直接拿来做自我推荐',
    similarPatterns: ['〜ため', '〜ので'],
    contrast: '「ことから」＝事実由来（書面・説明）；「ため」＝書面の理由；「ので」＝丁寧な理由',
    recognition: { promptZh: '「ことから」的文体特点是？',
      options: ['书面的、说明性的', '非常随便的口语', '强硬的命令语气', '不确定的疑问语气'],
      answerIndex: 0, distractorReason: '「ことから」用于书面说明由来',
      explanationZh: '客观由来的说明' },
    production: { promptJa: '自分の強みが生んだ機会を「〜ことから」で言ってください。',
      promptZh: '用「〜ことから」说你的优势带来的机会。',
      expected: ['ことから'], acceptable: ['できることから'] },
    practice: { themeJa: '強みと機会を結びつけて話す',
      starterJa: 'あなたの能力がきっかけで、何か機会が生まれたことはありますか？',
      starterZh: '你的能力带来过什么机会吗？', targetUse: '〜ことから' },
    vocabularyLinks: ['fi-nihongo', 'fi-shigoto'] }),
];
