// Phase 3P-5: N2文法完成draft Unit 4（原本No.46〜60・15文型）。
// rightsStatus: teacher_created_confirmed。原本例文をruntime使用可。
import type { N2GrammarDraft } from './n2GrammarDrafts';

const g = (p: Omit<N2GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey' | 'runtimeExampleOrigin'> & { reviewKey?: string; runtimeExampleOrigin?: N2GrammarDraft['runtimeExampleOrigin'] }): N2GrammarDraft =>
  ({ level: 'N2', route: 'n2-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, runtimeExampleOrigin: 'source_confirmed', ...p });

const src = (text: string, hash: string) =>
  ({ text, hash, rightsStatus: 'teacher_created_confirmed' as const });

export const N2_GRAMMAR_DRAFTS_UNIT4: N2GrammarDraft[] = [
  g({ grammarId: 'n2g-046', pattern: '〜ことだ（目標・大切なこと）', reading: 'ことだ', unit: 4, zhSourceRowId: null,
    meaningJa: '（目標・大事なのは）〜することだ',
    explanationZh: '（目标/重要的）是…。用「事」来概括目标或建议',
    formation: '動詞辞書形／ない形 ＋ことだ',
    usageScene: '陈述目标、给出建议（大切なのは〜ことだ）',
    nuance: '用作忠告时（如「迷ったら休むことだ」）不能对长辈上司使用',
    register: 'both',
    sourceExample: src('私の目標は今の自分以上の日本語レベルになることです。', '0e93018d3fb1d45d'),
    examplesJa: ['私の目標は今の自分以上の日本語レベルになることです。',
                 '上達の近道は、毎日声に出すことです。'],
    examplesZh: ['我的目标是达到超过现在的日语水平。', '进步的捷径就是每天开口朗读。'],
    furigana: 'わたしの もくひょうは いまの じぶん いじょうの にほんごレベルに なることです。',
    commonMistakesZh: '「〜ことだ」的忠告用法有居高临下的味道，只对平辈和晚辈用。讲目标的句子则对谁都能用',
    learnerFocus: '用一句话说出目标的句型「私の目標は〜ことです」，是自我介绍和面试的必备句型',
    similarPatterns: ['〜ことです', '〜べきだ'],
    contrast: '「ことだ」＝目標の名詞化／軽い忠告；「べきだ」＝強い当為',
    recognition: { promptZh: '「大切なのは続けることだ」是什么意思？',
      options: ['重要的是坚持', '不用坚持', '已经坚持了', '无法坚持'],
      answerIndex: 0, distractorReason: '「〜ことだ」把动作名词化后作出判断',
      explanationZh: '「大切なのは〜ことだ」= 重要的是…' },
    production: { promptJa: '今年の目標を「私の目標は〜ことです」で言ってください。',
      promptZh: '用「私の目標は〜ことです」说今年的目标。',
      expected: ['ことです'], acceptable: ['〜ことだ'] },
    practice: { themeJa: '目標を一文で言う', starterJa: 'あなたの今年の目標を一文で言ってみましょう',
      starterZh: '用一句话说说你今年的目标', targetUse: '〜ことです' },
    vocabularyLinks: ['fi-yotei', 'fi-tsuzukeru'] }),
  g({ grammarId: 'n2g-047', pattern: '〜ことだから', reading: 'ことだから', unit: 4, zhSourceRowId: null,
    meaningJa: 'よく知っている〜だから、きっと',
    explanationZh: '（正因为了解）…的为人，所以肯定…',
    formation: '人物名詞＋の ＋ことだから',
    usageScene: '基于对某人性格的了解做推测',
    nuance: '前提是「很了解那个人」。好的推测和坏的推测都能用',
    register: 'both',
    sourceExample: src('私の旦那のことだから、きっと、今日はお祝いをしてくれるだろう。', '3c8b00e6ed6c53e2'),
    examplesJa: ['私の旦那のことだから、きっと、今日はお祝いをしてくれるだろう。',
                 '几帳面な彼のことだから、もう準備は終わっているはずです。'],
    examplesZh: ['我老公那个人嘛，今天肯定会为我庆祝的。', '以他一丝不苟的性格，准备肯定已经做完了。'],
    furigana: 'わたしの だんなの ことだから、きっと、きょうは おいわいを して くれるだろう。',
    commonMistakesZh: '只能用于人。说「雨のことだから」是错的。后半句接推测（「だろう」「はずだ」）',
    learnerFocus: '聊身边人性格时的常用说法。按「〜のことだから、きっと〜だろう」整套记',
    similarPatterns: ['〜だから', '〜はずだ'],
    contrast: '「ことだから」＝人物理解に基づく推量；「だから」＝一般の理由',
    recognition: { promptZh: '「時間に厳しい部長のことだから」后面最自然的是？',
      options: ['もう会議室にいるはずだ', '遅刻するだろう', '会議を忘れている', '来ないと思う'],
      answerIndex: 0, distractorReason: '性格（時間に厳しい）と整合する推測が続く',
      explanationZh: '了解这个人 → 做出与之相符的推测' },
    production: { promptJa: 'よく知っている人の行動を「〜のことだから」で推測してください。',
      promptZh: '用「〜のことだから」推测你熟悉的人的行动。',
      expected: ['ことだから'], acceptable: ['〜のことだから'] },
    practice: { themeJa: '身近な人を推測で語る', starterJa: '家族や友達の「いつもの行動」を推測してみましょう',
      starterZh: '推测一下家人或朋友「一贯的行动」', targetUse: '〜のことだから' },
    vocabularyLinks: ['fi-kazoku', 'fi-tomodachi'] }),
  g({ grammarId: 'n2g-048', pattern: '〜ことなく', reading: 'ことなく', unit: 4, zhSourceRowId: null,
    meaningJa: '一度も〜しないで（書面）',
    explanationZh: '没有…、不曾…（书面）。「〜ないで」的正式形',
    formation: '動詞辞書形 ＋ことなく',
    usageScene: '书面描述「未曾中断」「没有放弃」',
    nuance: '比「ないで」生硬，用在讲成就的语境里很出彩',
    register: 'written',
    sourceExample: src('今日は一度も休むことなく、文法の学習をしていました。', 'fa8e6fc95392fa26'),
    examplesJa: ['今日は一度も休むことなく、文法の学習をしていました。',
                 '彼はあきらめることなく、挑戦を続けました。'],
    examplesZh: ['今天一次也没休息，一直在学语法。', '他不曾放弃，持续挑战。'],
    furigana: 'きょうは いちども やすむことなく、ぶんぽうの がくしゅうを していました。',
    commonMistakesZh: '会话里用「〜ないで」「〜ずに」更自然。「ことなく」适合书面和演讲',
    learnerFocus: '在简历和演讲里表达坚持不懈，这是最合适的书面说法',
    similarPatterns: ['〜ないで', '〜ずに'],
    contrast: '文体: 「ないで」（口語）＜「ずに」（中間）＜「ことなく」（書面）',
    recognition: { promptZh: '「ことなく」的文体是？',
      options: ['书面・正式', '非常口语', '幼儿用语', '命令形'],
      answerIndex: 0, distractorReason: '「ことなく」是「ないで」的书面形',
      explanationZh: '书面语中表示否定的持续' },
    production: { promptJa: '続けた努力を「〜ことなく」で言ってください。',
      promptZh: '用「〜ことなく」说你不曾中断的努力。',
      expected: ['ことなく'], acceptable: ['休むことなく', 'あきらめることなく'] },
    practice: { themeJa: '継続をフォーマルに語る', starterJa: 'あきらめることなく続けていることはありますか？',
      starterZh: '有什么是你不曾放弃一直坚持的？', targetUse: '〜ことなく' },
    vocabularyLinks: ['fi-tsuzukeru', 'fi-ganbaru'] }),
  g({ grammarId: 'n2g-050', pattern: '〜ことはない', reading: 'ことはない', unit: 4, zhSourceRowId: null,
    meaningJa: '〜する必要はない（励まし）',
    explanationZh: '没必要…、用不着…（多用于安慰鼓励）',
    formation: '動詞辞書形 ＋ことはない',
    usageScene: '安慰別人：不用着急、不用道歉',
    nuance: '固定说法有「焦ることはない」「謝ることはない」，语气很温和',
    register: 'both',
    sourceExample: src('今、点数が取れないからといって、焦ることはないですよ。', '87e6c64ba5534e12'),
    examplesJa: ['今、点数が取れないからといって、焦ることはないですよ。',
                 'あなたが謝ることはありません。'],
    examplesZh: ['虽说现在拿不到分数，也没必要着急。', '你没有必要道歉。'],
    furigana: 'いま、てんすうが とれないからと いって、あせることは ないですよ。',
    commonMistakesZh: '不要和「〜たことはない」（没做过、经验）混淆。辞書形＋「ことはない」＝没必要',
    learnerFocus: '鼓励人的固定说法。「心配することはないですよ」能让人际关系变得柔和',
    similarPatterns: ['〜必要はない', '〜なくてもいい'],
    contrast: '「ことはない」＝励ましの「不必」；「なくてもいい」＝許可寄り；「必要はない」＝事務的',
    recognition: { promptZh: '「急ぐことはないですよ」的语气是？',
      options: ['安慰对方不用急', '催促对方动作快一点', '责备对方动作太慢了', '表示自己心里很着急'],
      answerIndex: 0, distractorReason: '「ことはない」是温柔的「没必要」',
      explanationZh: '鼓励的说法' },
    production: { promptJa: '落ち込む友達を「〜ことはない」で励ましてください。',
      promptZh: '用「〜ことはない」安慰失落的朋友。',
      expected: ['ことはない'], acceptable: ['焦ることはない', '心配することはない'] },
    practice: { themeJa: '友達を励ます', starterJa: '試験に落ちた友達に、何と声をかけますか？',
      starterZh: '朋友考试没过，你会怎么安慰？', targetUse: '〜ことはない' },
    vocabularyLinks: ['fi-komaru', 'fi-genki'] }),
  g({ grammarId: 'n2g-051', pattern: '〜際は', reading: 'さいは', unit: 4, zhSourceRowId: null,
    meaningJa: '〜するとき（改まった場面）',
    explanationZh: '在…之际、…的时候（正式）',
    formation: '動詞辞書形／た形／名詞＋の ＋際（は・に）',
    usageScene: '公告、商务邮件、指南中的「时候」',
    nuance: '「とき」的郑重说法，是广播和告示的固定用词',
    register: 'written',
    sourceExample: src('旅行に行く際は、エアコンの電源を切ったか確認しましょう。', '4331414a1fd4faca'),
    examplesJa: ['旅行に行く際は、エアコンの電源を切ったか確認しましょう。',
                 'お降りの際は、足元にご注意ください。'],
    examplesZh: ['去旅行时，要确认空调电源是否已关。', '下车时请注意脚下。'],
    furigana: 'りょこうに いく さいは、エアコンの でんげんを きったか かくにん しましょう。',
    commonMistakesZh: '日常会话里用多了太生硬。比起「明日会う際は」，「明日会うときは」更自然',
    learnerFocus: '电车广播里的「お降りの際は」每天都能听到，听得懂生活会轻松很多',
    similarPatterns: ['〜とき', '〜にあたって'],
    contrast: '「とき」＝中立；「際」＝改まり；「にあたって」＝節目の開始',
    recognition: { promptZh: '「お問い合わせの際は」多出现在哪里？',
      options: ['公司通知・网站', '朋友的聊天', '孩子的日记', '歌词'],
      answerIndex: 0, distractorReason: '「際」是正式场合的「时候」',
      explanationZh: '郑重场合的「とき」' },
    production: { promptJa: '案内文を「〜際は」で書いてください。',
      promptZh: '用「〜際は」写一句指南。',
      expected: ['際'], acceptable: ['〜際は', '〜際に'] },
    practice: { themeJa: '案内文を読める・書ける', starterJa: '駅や店の「〜際は」の掲示を見たことがありますか？',
      starterZh: '你见过车站或店里「〜際は」的告示吗？', targetUse: '〜際は' },
    vocabularyLinks: ['fi-kakunin', 'fi-densha'] }),
  g({ grammarId: 'n2g-052', pattern: '〜最中に', reading: 'さいちゅうに', unit: 4, zhSourceRowId: null,
    meaningJa: 'ちょうど〜している途中に（邪魔が入る）',
    explanationZh: '正在…的时候（偏偏发生了别的事）',
    formation: '動詞ている形／名詞＋の ＋最中に',
    usageScene: '正开会时手机响了、正洗澡时来快递',
    nuance: '表示正在进行的当口，带有被打扰、被中断的意味。比「〜ているとき」更有戏剧性',
    register: 'both',
    sourceExample: src('勉強をしている最中に、友達から連絡がきて、集中できませんでした。', '55153034c77b6461'),
    examplesJa: ['勉強をしている最中に、友達から連絡がきて、集中できませんでした。',
                 '会議の最中に、スマホが鳴ってしまいました。'],
    examplesZh: ['正在学习时朋友来联系，没法集中。', '正开会时手机响了。'],
    furigana: 'べんきょうを している さいちゅうに、ともだちから れんらくが きて、しゅうちゅう できませんでした。',
    commonMistakesZh: '「最中」的后半句多是「打扰、麻烦」。好的事情用「〜ているときに」更自然',
    learnerFocus: '打断别人时道歉的固定说法是「会議の最中にすみません」',
    similarPatterns: ['〜ているときに', '〜途中で'],
    contrast: '「最中に」＝真っ只中＋中断の含み；「ときに」＝中立；「途中で」＝進行の中間点',
    recognition: { promptZh: '「食事の最中に電話が来た」的语感是？',
      options: ['正吃饭时偏偏来电话（被打扰）', '吃完饭并且收拾完之后才来的电话', '正好想接电话很开心', '根本没有来过电话'],
      answerIndex: 0, distractorReason: '「最中に」含被打扰的语感',
      explanationZh: '打扰正在进行的事' },
    production: { promptJa: '邪魔が入った経験を「〜最中に」で言ってください。',
      promptZh: '用「〜最中に」说一次被打扰的经历。',
      expected: ['最中'], acceptable: ['〜最中に'] },
    practice: { themeJa: '集中を邪魔された話をする', starterJa: '何かの最中に邪魔が入ったことはありますか？',
      starterZh: '有正做事时被打扰的经历吗？', targetUse: '〜最中に' },
    vocabularyLinks: ['fi-renraku', 'fi-benkyo'] }),
  g({ grammarId: 'n2g-053', pattern: '〜ざるを得ない', reading: 'ざるをえない', unit: 4, zhSourceRowId: null,
    meaningJa: '（仕方なく）〜しなければならない',
    explanationZh: '不得不…、只能…（无奈）',
    formation: '動詞ない形の語幹 ＋ざるを得ない（する→せざるを得ない）',
    usageScene: '说明被形势所迫的选择',
    nuance: '书面腔。含有无奈、不情愿的意味，比「するしかない」更生硬',
    register: 'written',
    // 語として完成した形を先に置く（cloze の正解表示が「ざるを得」で切れないように）
    matchKeys: ['ざるを得ない', 'ざるを得ません', 'ざるを得'],
    sourceExample: src('残りの2ヶ月で合格するには、効率よく勉強せざるを得ないです。', '96604581e89508c7'),
    examplesJa: ['残りの2ヶ月で合格するには、効率よく勉強せざるを得ないです。',
                 '台風のため、旅行は中止せざるを得ませんでした。'],
    examplesZh: ['要在剩下两个月内合格，不得不高效学习。', '因为台风，旅行不得不中止。'],
    furigana: 'のこりの にかげつで ごうかく するには、こうりつよく べんきょう せざるを えないです。',
    commonMistakesZh: '「する」要变成「せざるを得ない」（写成「しざる」是错的）。只有这个变化特殊，整个背下来',
    learnerFocus: '新闻和商务文书里很常见，如「値上げせざるを得ない」（不得不涨价）。先做到在阅读里能认出来',
    similarPatterns: ['〜しかない', '〜ほかない'],
    contrast: '「ざるを得ない」＝書面・無念；「しかない」＝口語；「ほかない」＝中間',
    recognition: { promptZh: '「中止せざるを得ない」的心情是？',
      options: ['无奈、不情愿地只能中止', '高高兴兴地决定中止', '坚决拒绝中止活动', '和中止完全没有关系'],
      answerIndex: 0, distractorReason: '「ざるを得ない」含不本意',
      explanationZh: '无奈只好…' },
    production: { promptJa: '仕方なくした選択を「〜ざるを得ない」で言ってください。',
      promptZh: '用「〜ざるを得ない」说一次无奈的选择。',
      expected: ['ざるを得'], acceptable: ['〜ざるを得ない', 'せざるを得ない'] },
    practice: { themeJa: '不本意な決断を語る', starterJa: '仕方なく何かを決めた経験はありますか？',
      starterZh: '有过无奈之下做决定的经历吗？', targetUse: '〜ざるを得ない' },
    vocabularyLinks: ['fi-kimeru', 'fi-muri'] }),
  g({ grammarId: 'n2g-054', pattern: '〜次第', reading: 'しだい', unit: 4, zhSourceRowId: null,
    meaningJa: '①〜によって決まる ②〜したらすぐ',
    explanationZh: '①取决于… ②一…立刻（就）',
    formation: '①名詞＋次第だ ②動詞ます形＋次第',
    usageScene: '①归结责任・条件 ②商务承诺（确认后立刻联系）',
    nuance: '②「確認でき次第ご連絡します」（一确认好就联系您）是商务邮件的黄金句型',
    register: 'written',
    sourceExample: src('この会社が生き残るかどうかは、社長次第です。', '0ff2002a9eee4272'),
    examplesJa: ['この会社が生き残るかどうかは、社長次第です。',
                 '詳細が分かり次第、ご連絡いたします。'],
    examplesZh: ['这家公司能否存活，取决于社长。', '一旦了解详情，立刻与您联系。'],
    furigana: 'この かいしゃが いきのこるか どうかは、しゃちょう しだいです。',
    commonMistakesZh: '①接名词，②接「ます形」。接续不同意思也不同，注意区分',
    learnerFocus: '会用「〜次第ご連絡します」，商务邮件一下子就专业起来',
    similarPatterns: ['〜によって', '〜たらすぐ'],
    contrast: '①「次第だ」＝決定要因；②「〜次第」＝即時の対応（丁寧）',
    recognition: { promptZh: '「分かり次第連絡します」是什么意思？',
      options: ['一知道就立刻联系', '也有可能就不联系了', '明天有空的时候再联系', '在这之前就已经联系了'],
      answerIndex: 0, distractorReason: 'ます形＋次第 = 一…立刻',
      explanationZh: '商务上表示立即响应的说法' },
    production: { promptJa: 'ビジネスメールの返事を「〜次第」で書いてください。',
      promptZh: '用「〜次第」写一句商务邮件回复。',
      expected: ['次第'], acceptable: ['分かり次第', '確認でき次第'] },
    practice: { themeJa: 'ビジネスの約束をする', starterJa: '「確認してから連絡する」を丁寧に言ってみましょう',
      starterZh: '试着礼貌地说「确认后联系」', targetUse: '〜次第' },
    vocabularyLinks: ['fi-renraku', 'fi-kakunin'] }),
  g({ grammarId: 'n2g-056', pattern: '〜末に', reading: 'すえに', unit: 4, zhSourceRowId: null,
    meaningJa: 'いろいろ〜した結果、最終的に',
    explanationZh: '经过…（一番周折）最终…',
    formation: '動詞た形／名詞＋の ＋末に',
    usageScene: '说明经过长时间考虑后的决定',
    nuance: '包含过程的漫长和辛苦。和「あげく」不同，好的结果也能用',
    register: 'written',
    sourceExample: src('色々考えた末にN1の試験にもチャレンジすることにしました。', 'b4cdc64e3135d409'),
    examplesJa: ['色々考えた末にN1の試験にもチャレンジすることにしました。',
                 '議論の末に、計画は一部変更されました。'],
    examplesZh: ['再三考虑之后，决定也挑战N1考试。', '讨论到最后，计划做了部分修改。'],
    furigana: 'いろいろ かんがえた すえに エヌワンの しけんにも チャレンジ することに しました。',
    commonMistakesZh: '「あげく」只用于不好的结局，「末に」好的结果也可以。积极的决定用「末に」',
    learnerFocus: '「考えた末に」（再三考虑之后）是讲重要决定时的固定说法，可以用来说明跳槽和留学',
    similarPatterns: ['〜あげく', '〜結果'],
    contrast: '「末に」＝長い過程＋どちらの結果も可；「あげく」＝負面限定；「結果」＝中立',
    recognition: { promptZh: '「悩んだ末に留学を決めた」的语感是？',
      options: ['经过长期烦恼后最终决定（正面）', '烦恼了很长时间之后最终还是放弃了', '没有经过任何烦恼', '被别人强迫做的决定'],
      answerIndex: 0, distractorReason: '「末に」表示长过程后的最终决定',
      explanationZh: '长时间过程之后的决定' },
    production: { promptJa: '悩んで決めたことを「〜末に」で言ってください。',
      promptZh: '用「〜末に」说一次深思后的决定。',
      expected: ['末に'], acceptable: ['考えた末に', '悩んだ末に'] },
    practice: { themeJa: '大きな決断の経緯を話す', starterJa: '長く悩んで決めたことはありますか？',
      starterZh: '有经过长期烦恼才决定的事吗？', targetUse: '〜末に' },
    vocabularyLinks: ['fi-kangaeru', 'fi-kimeru'] }),
  g({ grammarId: 'n2g-057', pattern: '〜ずにすむ', reading: 'ずにすむ', unit: 4, zhSourceRowId: null,
    meaningJa: '〜しなくてよくなる（助かった）',
    explanationZh: '不用…就解决了、免于…（松了口气）',
    formation: '動詞ない形の語幹 ＋ずにすむ（する→せずにすむ）',
    usageScene: '说明幸运地避免了麻烦',
    nuance: '含有「幸好」的安心感。「〜なくてすむ」也是同样的意思',
    register: 'both',
    matchKeys: ['ずにすみ', 'ずに済'],
    sourceExample: src('雨が止んだので、傘を持たずにすみました。', '455bcaeaea02f670'),
    examplesJa: ['雨が止んだので、傘を持たずにすみました。',
                 '早めに気づいたので、大きなミスにならずにすみました。'],
    examplesZh: ['因为雨停了，不用带伞了。', '因为发现得早，没有酿成大错。'],
    furigana: 'あめが やんだので、かさを もたずに すみました。',
    commonMistakesZh: '和「〜ずにはいられない」（禁不住要…）形式相似，意思完全不同，注意不要混',
    learnerFocus: '「〜ずにすんだ」是「幸好没…」的安心感，用来汇报避免了麻烦很方便',
    similarPatterns: ['〜なくてすむ', '〜ないで済む'],
    contrast: '「ずにすむ」＝回避できた安堵；「なくてもいい」＝単なる不要',
    recognition: { promptZh: '「並ばずにすんだ」的心情是？',
      options: ['庆幸不用排队', '不得不排队', '想排队', '排了很久'],
      answerIndex: 0, distractorReason: '「ずにすむ」表示避免了麻烦的安堵',
      explanationZh: '避开了麻烦的安心' },
    production: { promptJa: '運よく避けられたことを「〜ずにすみました」で言ってください。',
      promptZh: '用「〜ずにすみました」说一次幸运避开的麻烦。',
      expected: ['ずにすみ'], acceptable: ['〜ずにすんだ'] },
    practice: { themeJa: '「助かった」経験を話す', starterJa: '最近、「〜せずにすんだ」ことはありますか？',
      starterZh: '最近有什么「幸好不用做」的事吗？', targetUse: '〜ずにすみました' },
    vocabularyLinks: ['fi-komaru', 'fi-mondai'] }),
  g({ grammarId: 'n2g-058', pattern: '〜ずにはいられない', reading: 'ずにはいられない', unit: 4, zhSourceRowId: null,
    meaningJa: 'どうしても〜してしまう（抑えられない）',
    explanationZh: '禁不住…、不由得…（无法抑制）',
    formation: '動詞ない形の語幹 ＋ずにはいられない（する→せずにはいられない）',
    usageScene: '描述抑制不住的感情、冲动',
    nuance: '感情自然而然地涌上来，偏书面腔',
    register: 'written',
    matchKeys: ['ずにはいられない', 'ずにはいられません', 'ずにはいられ'],
    sourceExample: src('何回も不合格だった場合、自信を無くさずにはいられないです。', 'b1be06c7a3764897'),
    examplesJa: ['何回も不合格だった場合、自信を無くさずにはいられないです。',
                 'あの映画を見ると、泣かずにはいられません。'],
    examplesZh: ['多次不合格的话，禁不住会失去自信。', '看那部电影，就忍不住要哭。'],
    furigana: 'なんかいも ふごうかく だった ばあい、じしんを なくさずには いられないです。',
    commonMistakesZh: '注意不要和「ずにすむ」（免于）混淆。核心是「いられない」＝忍不住',
    learnerFocus: '写读后感和评论时，「感動せずにはいられない」（不能不感动）是很强的赞美',
    similarPatterns: ['〜てしまう', '〜ないではいられない'],
    contrast: '「ずにはいられない」＝抑えられない衝動；「てしまう」＝結果の後悔・完了',
    recognition: { promptZh: '「笑わずにはいられなかった」是什么意思？',
      options: ['忍不住笑了', '忍住了没有笑', '一点也不想笑', '怎么也笑不出来'],
      answerIndex: 0, distractorReason: '「ずにはいられない」= 无法抑制',
      explanationZh: '抑制不住的感情' },
    production: { promptJa: '抑えられなかった感情を「〜ずにはいられない」で言ってください。',
      promptZh: '用「〜ずにはいられない」说一次抑制不住的感情。',
      expected: ['ずにはいられ'], acceptable: ['〜ずにはいられません'] },
    practice: { themeJa: '感情が動いた作品を語る', starterJa: '泣かずにはいられなかった映画や動画はありますか？',
      starterZh: '有让你忍不住落泪的电影或视频吗？', targetUse: '〜ずにはいられない' },
    vocabularyLinks: ['fi-kanjiru', 'fi-kanashii'] }),
  g({ grammarId: 'n2g-059', pattern: '〜せいで', reading: 'せいで', unit: 4, zhSourceRowId: 'n3row-104',
    meaningJa: '〜が原因で（悪い結果）',
    explanationZh: '都怪…、因为…（导致坏结果）',
    formation: '動詞普通形／名詞＋の ＋せいで',
    usageScene: '说明坏结果的原因（含归咎）',
    nuance: 'N3也会学。N2还会讲到「せいか」（也许是因为）等派生说法',
    register: 'both',
    sourceExample: src('昨日の地震のせいで、電車が遅延しています。', '098ec798d791e2e9'),
    examplesJa: ['昨日の地震のせいで、電車が遅延しています。',
                 '寝不足のせいか、今日は集中できません。'],
    examplesZh: ['都怪昨天的地震，电车在晚点。', '也许是因为睡眠不足，今天无法集中。'],
    furigana: 'きのうの じしんの せいで、でんしゃが ちえん しています。',
    commonMistakesZh: '用在人身上会变成指责。换成「〜せいか」表示推测，语气会缓和',
    learnerFocus: '分清「せいで」（断定的归咎）和「せいか」（推测），说话就不会伤和气',
    similarPatterns: ['〜おかげで', '〜ため'],
    contrast: '「せいで」＝負面帰責；「おかげで」＝正面；「せいか」＝推測の帰責',
    recognition: { promptZh: '「寝不足のせいか、頭が痛い」的「せいか」表示？',
      options: ['也许是因为（推测）', '一定是因为（断定）', '多亏了', '为了'],
      answerIndex: 0, distractorReason: '「せいか」是弱化的推测归因',
      explanationZh: '推测性的归咎' },
    production: { promptJa: '悪い結果の原因を「〜せいで」で言ってください。',
      promptZh: '用「〜せいで」说明坏结果的原因。',
      expected: ['せい'], acceptable: ['〜のせいで', '〜せいか'] },
    practice: { themeJa: '不調の原因を推測する', starterJa: '最近の不調、何のせいだと思いますか？',
      starterZh: '最近的不顺，你觉得是因为什么？', targetUse: '〜せいで／せいか' },
    vocabularyLinks: ['fi-densha', 'fi-riyuu'] }),
  g({ grammarId: 'n2g-060', pattern: '〜たいばかりに', reading: 'たいばかりに', unit: 4, zhSourceRowId: null,
    meaningJa: '〜したい一心で（無理までした）',
    explanationZh: '就因为一心想…（甚至做了勉强的事）',
    formation: '動詞ます形＋たい ＋ばかりに',
    usageScene: '说明为了一个愿望做出的大胆行动',
    nuance: '后半句是「做到那个地步」的勉强和牺牲，接不好的结果的情况也很多',
    register: 'written',
    sourceExample: src('あの俳優に会いたいばかりに、イタリアへ旅行をすることを決めました。', 'fa4f8b21fd9ec4b0'),
    examplesJa: ['あの俳優に会いたいばかりに、イタリアへ旅行をすることを決めました。',
                 '早く帰りたいばかりに、昼休みも仕事をしました。'],
    examplesZh: ['就因为一心想见那位演员，决定去意大利旅行。', '就因为想早点回家，连午休都在工作。'],
    furigana: 'あの はいゆうに あいたい ばかりに、イタリアへ りょこうを することを きめました。',
    commonMistakesZh: '「ばかりに」单独用是「就因为…（导致坏结果）」。「たいばかりに」则是愿望成了动机',
    learnerFocus: '用来讲为了追星、为了目标而做的疯狂事，很有感情，聊天时容易聊开',
    similarPatterns: ['〜ばかりに', '〜あまり'],
    contrast: '「たいばかりに」＝願望が動機の無理；「あまり」＝感情の過度；「ばかりに」＝原因＋悪結果',
    recognition: { promptZh: '「会いたいばかりに」暗示什么？',
      options: ['为见面甚至做了勉强的事', '其实一点也不想去和对方见面', '只是偶然见到了面', '见面本来就很容易'],
      answerIndex: 0, distractorReason: '「たいばかりに」表示愿望驱动的过度行动',
      explanationZh: '因为太想要而勉强行事' },
    production: { promptJa: '何かをしたい一心でした無理を「〜たいばかりに」で言ってください。',
      promptZh: '用「〜たいばかりに」说一次为愿望而做的勉强。',
      expected: ['たいばかりに'], acceptable: ['〜たいばかりに'] },
    practice: { themeJa: '推し・目標のための無茶を話す', starterJa: '何かをしたいばかりに、無理をしたことはありますか？',
      starterZh: '有过一心想做某事而勉强自己的经历吗？', targetUse: '〜たいばかりに' },
    vocabularyLinks: ['fi-kyoumi', 'fi-kimeru'] }),
];
