// Phase 3P-5後 Priority 3: 同義判断待ち7件の「人間判断不要field」完成版（pre-draft）。
// ⚠️ N2_GRAMMAR_DRAFTS には含めない（恒等式 173+7+0+0=180 を維持）。
// 統合するか別項目として残すか・canonical ID・level配置・approved relation は人間判断。
// 判断確定後、統合なら相手項目のsimilarPatterns/contrastへ吸収、別項目ならdraftsへ昇格できる。
import type { N2GrammarDraft } from './n2GrammarDrafts';

/** 同義関係の分類候補（人間が確定させる。ここでは candidate 止まり） */
export type N2MergeRelationCandidate =
  | 'exact_synonym'
  | 'same_core_different_register'
  | 'same_core_different_nuance'
  | 'different_formation'
  | 'different_usage_scene'
  | 'one_way_replaceable'
  | 'separate_grammar';

export interface N2GrammarPredraft extends N2GrammarDraft {
  mergeDecision: {
    /** 原本メモ「◯と同じ」の相手grammarId */
    pairedWith: string;
    /** 原本の注記そのまま */
    sourceNote: string;
    /** 自動分類の候補（approvedではない） */
    relationCandidate: N2MergeRelationCandidate;
    /** 候補の根拠（1行） */
    rationale: string;
    /** 人間にしか決められない項目 */
    humanDecisionRequired: readonly ['merge_or_separate', 'canonical_id', 'level_placement', 'approved_relation'];
  };
}

const HUMAN_ITEMS = ['merge_or_separate', 'canonical_id', 'level_placement', 'approved_relation'] as const;

const g = (p: Omit<N2GrammarPredraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey' | 'runtimeExampleOrigin'> & { reviewKey?: string; runtimeExampleOrigin?: N2GrammarDraft['runtimeExampleOrigin'] }): N2GrammarPredraft =>
  ({ level: 'N2', route: 'n2-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, runtimeExampleOrigin: 'source_confirmed', ...p });

const src = (text: string, hash: string) =>
  ({ text, hash, rightsStatus: 'teacher_created_confirmed' as const });

const md = (pairedWith: string, sourceNote: string, relationCandidate: N2MergeRelationCandidate, rationale: string) =>
  ({ pairedWith, sourceNote, relationCandidate, rationale, humanDecisionRequired: HUMAN_ITEMS });

export const N2_GRAMMAR_PREDRAFTS_AWAITING_MERGE: N2GrammarPredraft[] = [
  g({ grammarId: 'n2g-007', pattern: '〜上は', reading: 'うえは', unit: 1, zhSourceRowId: null,
    mergeDecision: md('n2g-003', '3と同じ', 'same_core_different_register',
      '「以上は」とほぼ同義。「上は」の方が文語的・改まった決意表明に寄る'),
    meaningJa: '〜したからには、当然（覚悟を持って）',
    explanationZh: '既然…就（要有觉悟）…。比「以上は」更书面、更有破釜沉舟感的表达',
    formation: '動詞た形・辞書形 ＋上は',
    usageScene: '下定决心的宣言、接受任务后的表态',
    nuance: '「以上は」より硬く、覚悟の宣言に寄る。日常会話ではやや大げさ',
    register: 'written',
    sourceExample: src('目標を決めた上は、覚悟（かくご）を決めてやりきるしかありません。', '8f9f6267c978f59d'),
    examplesJa: ['目標を決めた上は、覚悟（かくご）を決めてやりきるしかありません。',
                 '引き受けた上は、途中で投げ出すわけにはいきません。'],
    examplesZh: ['既然定下了目标，就只能下定决心干到底。', '既然接下了，就不能中途撂挑子。'],
    furigana: 'もくひょうを きめた うえは、かくごを きめて やりきる しか ありません。',
    commonMistakesZh: '「上は」「以上は」「からには」三者近义：「からには」最口语、「以上は」中间、「上は」最文言。也注意与「〜上で（在…之后/方面）」区分',
    learnerFocus: '就职表态的最高级：「入社した上は、全力を尽くします」。庄重感强，面试压轴用',
    similarPatterns: ['〜以上は', '〜からには'],
    contrast: '「上は」＝文語的な覚悟宣言；「以上は」＝標準的な当然の責任；「からには」＝口語寄り',
    recognition: { promptZh: '「約束した上は、必ず守ります」的语气是？',
      options: ['庄重地表明履约的觉悟', '随口敷衍的应付', '拒绝遵守约定', '询问是否要遵守'],
      answerIndex: 0, distractorReason: '「上は」是带觉悟的郑重表态',
      explanationZh: '文言色彩的决意宣言' },
    production: { promptJa: '覚悟の宣言を「〜上は」で言ってください。',
      promptZh: '用「〜上は」做一个庄重的表态。',
      expected: ['上は'], acceptable: ['〜た上は'] },
    practice: { themeJa: '覚悟を宣言する', starterJa: '何かを最後までやり切ると決めた経験はありますか？',
      starterZh: '有没有下定决心干到底的经历？', targetUse: '〜上は' },
    vocabularyLinks: ['fi-kimeru', 'fi-ganbaru'] }),
  g({ grammarId: 'n2g-018', pattern: '〜が契機で', reading: 'がけいきで', unit: 2, zhSourceRowId: null,
    mergeDecision: md('n2g-016', '16と同じ', 'same_core_different_register',
      '「がきっかけで」と同義。「契機」は漢語で書面・フォーマル寄り'),
    meaningJa: '〜がきっかけになって（改まった言い方）',
    explanationZh: '以…为契机。「きっかけ」的书面汉语版，正式文书、报告常用',
    formation: '名詞 ＋が契機で（を契機に・を契機として）',
    usageScene: '写报告说明转折点、正式介绍事业的起点',
    nuance: '「きっかけ」より硬い。「を契機に」の形も頻出',
    register: 'written',
    sourceExample: src('日本語授業が契機で、試験の点数が大幅に上がりました。', 'd0d11ba57e5da7e2'),
    examplesJa: ['日本語授業が契機で、試験の点数が大幅に上がりました。',
                 '転職が契機で、生活のリズムが大きく変わりました。'],
    examplesZh: ['以日语课为契机，考试分数大幅提高了。', '以跳槽为契机，生活节奏发生了很大变化。'],
    furigana: 'にほんご じゅぎょうが けいきで、しけんの てんすうが おおはばに あがりました。',
    commonMistakesZh: '口语聊天用「きっかけ」，书面报告用「契機」。中文「契机」和日语「契機」同字同义，注意读音けいき',
    learnerFocus: '中文母语者的免费礼物：「契机」直接对应。写正式作文时替换「きっかけ」即刻显得高级',
    similarPatterns: ['〜がきっかけで', '〜を機に'],
    contrast: '「が契機で」＝書面の転機表現；「がきっかけで」＝日常の同義表現；「を機に」＝節目からの行動転換',
    recognition: { promptZh: '「留学を契機として、人生観が変わった」的文体是？',
      options: ['书面正式的表达', '儿童的口语', '粗鲁的俚语', '古代的和歌'],
      answerIndex: 0, distractorReason: '「契機」是书面汉语词',
      explanationZh: '「きっかけ」的正式版' },
    production: { promptJa: '人生の転機を「〜が契機で」で改まって言ってください。',
      promptZh: '用「〜が契機で」正式地讲一个人生转折点。',
      expected: ['契機'], acceptable: ['〜を契機に'] },
    practice: { themeJa: '転機をフォーマルに語る', starterJa: 'あなたの学習の転機になった出来事は何ですか？',
      starterZh: '什么事成了你学习的转折点？', targetUse: '〜が契機で' },
    vocabularyLinks: ['fi-kawaru', 'fi-benkyo'] }),
  g({ grammarId: 'n2g-024', pattern: '〜かと思えば', reading: 'かとおもえば', unit: 2, zhSourceRowId: null,
    mergeDecision: md('n2g-023', '23と同じ', 'exact_synonym',
      '「かと思うと」とほぼ交換可能。「思えば」は仮定形で対比の含みがわずかに強い'),
    meaningJa: '〜したと思ったら（すぐ正反対のことが）',
    explanationZh: '刚以为…就（又）…。前后急转，多用于变化无常的对比',
    formation: '動詞た形 ＋かと思えば（かと思うと・かと思ったら）',
    usageScene: '感叹天气反复无常、孩子情绪说变就变',
    nuance: '変わり身の早さへの驚き・あきれ。自分の意志的行動には使わない',
    register: 'both',
    sourceExample: src('夏が来たかと思えば、また寒くなってきました。', '87f9cdfe87ab005e'),
    examplesJa: ['夏が来たかと思えば、また寒くなってきました。',
                 '泣いていたかと思えば、もう笑っています。'],
    examplesZh: ['刚觉得夏天来了，又冷了起来。', '刚才还在哭，这会儿又笑了。'],
    furigana: 'なつが きたかと おもえば、また さむく なって きました。',
    commonMistakesZh: '主语的急变要「出乎说话人预料」：说自己计划中的行动（吃完饭就学习）不能用。和「たとたん」（一…就）比，多了「意外・无常」的感叹',
    learnerFocus: '吐槽善变的天气和人的神句：「晴れたかと思えば雨」。春秋换季时天天用得上',
    similarPatterns: ['〜かと思うと', '〜たとたん'],
    contrast: '「かと思えば」＝急転への驚き（仮定形で対比強め）；「かと思うと」＝同義の標準形；「たとたん」＝直後の出来事',
    recognition: { promptZh: '「静かになったかと思えば、また騒ぎ出した」的样子是？',
      options: ['刚安静下来又闹起来了', '一直保持安静', '一直吵闹从没安静', '再也不会吵闹了'],
      answerIndex: 0, distractorReason: '「かと思えば」＝状态急转的反复',
      explanationZh: '变化无常的对比' },
    production: { promptJa: '変わりやすいものを「〜かと思えば」で言ってください。',
      promptZh: '用「〜かと思えば」吐槽一个变化无常的事物。',
      expected: ['かと思えば'], acceptable: ['〜かと思ったら'] },
    practice: { themeJa: '変化の速さをぼやく', starterJa: '最近「変わり身が早い！」と思ったことは？',
      starterZh: '最近有什么让你觉得「变得真快」？', targetUse: '〜かと思えば' },
    vocabularyLinks: ['fi-samui', 'fi-kawaru'] }),
  g({ grammarId: 'n2g-064', pattern: '〜たところが', reading: 'たところが', unit: 5, zhSourceRowId: null,
    mergeDecision: md('n2g-063', '63と同じ', 'same_core_different_nuance',
      '「たところ」＝中立の発見。「たところが」＝期待と逆の結果（逆接）。一方向のみ交換可能'),
    meaningJa: '〜したら、（予想に反して）',
    explanationZh: '本以为…结果却…。行动后出现与预期相反的结果',
    formation: '動詞た形 ＋ところが',
    usageScene: '以为他知道结果他也不知道、以为便宜结果更贵',
    nuance: '「が」が付くと逆接が確定。中立の「たところ」との差が判断待ちの核',
    register: 'both',
    sourceExample: src('彼なら知っていると思って聞いたところが、彼も知らなかったです。', 'a5353c5775ce195f'),
    examplesJa: ['彼なら知っていると思って聞いたところが、彼も知らなかったです。',
                 '安いと思って買ったところが、隣の店のほうがさらに安かったです。'],
    examplesZh: ['本以为他知道就去问了，结果他也不知道。', '本以为便宜就买了，结果隔壁店更便宜。'],
    furigana: 'かれなら しっていると おもって きいた ところが、かれも しらなかったです。',
    commonMistakesZh: '「問い合わせたところ、翌日返事が来た」（中立结果）／「問い合わせたところが、返事が来ない」（事与愿违）。有没有「が」方向不同',
    learnerFocus: '讲「本以为…谁知…」的故事必备。失败谈有了这个词就有了转折点',
    similarPatterns: ['〜たところ', '〜のに'],
    contrast: '「たところが」＝期待→逆の結果；「たところ」＝行動→中立の判明；「のに」＝不満の逆接',
    recognition: { promptZh: '「頼りにして聞いたところが、知らなかった」的展开是？',
      options: ['本指望他知道，结果落空了', '果然如预期他知道', '一开始就没抱希望', '他详细地告诉了我'],
      answerIndex: 0, distractorReason: '「たところが」＝预期与结果相反',
      explanationZh: '期待落空的逆转' },
    production: { promptJa: '期待と逆だった経験を「〜たところが」で言ってください。',
      promptZh: '用「〜たところが」说一次事与愿违的经历。',
      expected: ['ところが'], acceptable: ['〜たところが'] },
    practice: { themeJa: '当てが外れた話をする', starterJa: '「きっと大丈夫」と思ったのに外れた経験は？',
      starterZh: '有没有「本以为稳了」却落空的经历？', targetUse: '〜たところが' },
    vocabularyLinks: ['fi-kiku', 'fi-wakaru'] }),
  g({ grammarId: 'n2g-099', pattern: '〜とは限らない', reading: 'とはかぎらない', unit: 7, zhSourceRowId: null,
    mergeDecision: md('n2g-086', '86と同じ', 'same_core_different_nuance',
      '「というものではない」＝通念の否定。「とは限らない」＝例外の存在。部分否定同士だが焦点が異なる'),
    meaningJa: '必ずしも〜ではない（例外がある）',
    explanationZh: '未必…、不一定…。指出例外的存在，否定「凡是…都…」',
    formation: '動詞・い形容詞普通形／な形容詞・名詞（だ） ＋とは限らない',
    usageScene: '提醒高分未必会说、贵的未必好',
    nuance: '「必ずしも」と呼応しやすい。断定を避ける知的な留保',
    register: 'both',
    sourceExample: src('N1試験で高得点をとれるからといって、仕事で使える会話力があるとは限らないです。', 'c460a00ae74fe178'),
    examplesJa: ['N1試験で高得点をとれるからといって、仕事で使える会話力があるとは限らないです。',
                 '値段が高いものが、必ずしも良いとは限りません。'],
    examplesZh: ['即使N1考了高分，也未必有工作中能用的会话能力。', '价格贵的东西未必就好。'],
    furigana: 'エヌワン しけんで こうとくてんを とれる からと いって、しごとで つかえる かいわりょくが あるとは かぎらないです。',
    commonMistakesZh: '和「わけがない」（不可能）不同——「とは限らない」承认多数情况成立、只是有例外。「からといって〜とは限らない」是黄金搭配',
    learnerFocus: '反驳刻板印象的礼貌武器：「中国人がみんな辛いもの好きとは限りませんよ」。不冲突地纠正对方',
    similarPatterns: ['〜というものではない', '〜わけではない'],
    contrast: '「とは限らない」＝例外の指摘；「というものではない」＝通念そのものの否定；「わけではない」＝誤解の部分訂正',
    recognition: { promptZh: '「有名な店がおいしいとは限らない」的立场是？',
      options: ['有名的店也有不好吃的例外', '有名的店全都不好吃', '有名的店绝对都好吃', '没有一家有名的店'],
      answerIndex: 0, distractorReason: '「とは限らない」＝多数成立但存在例外',
      explanationZh: '「未必」的例外指摘' },
    production: { promptJa: '思い込みへの反例を「〜とは限らない」で言ってください。',
      promptZh: '用「〜とは限らない」反驳一个刻板印象。',
      expected: ['とは限らない'], acceptable: ['〜とは限りません'] },
    practice: { themeJa: '思い込みをやわらかく正す', starterJa: '「みんなそう思ってるけど実は違う」ことはありますか？',
      starterZh: '有什么「大家都以为如此其实未必」的事？', targetUse: '〜とは限らない' },
    vocabularyLinks: ['fi-takai', 'fi-shigoto'] }),
  g({ grammarId: 'n2g-104', pattern: '〜なくはない', reading: 'なくはない', unit: 7, zhSourceRowId: null,
    mergeDecision: md('n2g-102', '102と同じ', 'exact_synonym',
      '「ないではない」とほぼ交換可能な二重否定。「なくはない」の方が口語頻度が高い'),
    meaningJa: '〜ないわけではない（弱い肯定）',
    explanationZh: '也不是不…。二重否定的弱肯定，带保留和犹豫',
    formation: '動詞ない形（なく）／い形容詞（〜くなく）＋はない',
    usageScene: '勉强承认可行、含蓄表达兴趣、有保留地让步',
    nuance: '「行けなくはない」＝条件次第で可能。素直な肯定より含みが多い',
    register: 'spoken',
    sourceExample: src('今からお店に行けなくはないですが、もう夜遅いのでやめておきます。', 'b6810bcb0091e835'),
    examplesJa: ['今からお店に行けなくはないですが、もう夜遅いのでやめておきます。',
                 '心配な点がなくはないですが、挑戦してみます。'],
    examplesZh: ['现在去店里也不是去不了，但夜深了还是算了。', '担心的地方也不是没有，但我想挑战一下。'],
    furigana: 'いまから おみせに いけなくは ないですが、もう よるおそいので やめて おきます。',
    commonMistakesZh: '弱肯定不是热情答应：对方听到「食べられなくはない」会理解为「不太想吃」。真心推荐时别用双重否定',
    learnerFocus: '和U7「ないことはない」是亲兄弟。含蓄拒绝的前半句：「興味がなくはないんですが…」',
    similarPatterns: ['〜ないではない', '〜ないことはない'],
    contrast: '「なくはない」＝口語頻度高の弱い肯定；「ないではない」＝同義でやや書面；「ないことはない」＝条件付き可能の含み',
    recognition: { promptZh: '「おいしくなくはない」的评价大约是？',
      options: ['勉强算好吃（不算难吃）', '非常好吃极力推荐', '难吃到无法入口', '还没有尝过味道'],
      answerIndex: 0, distractorReason: '双重否定＝有保留的及格分',
      explanationZh: '弱肯定的微妙评价' },
    production: { promptJa: '含みを持たせた返事を「〜なくはない」で言ってください。',
      promptZh: '用「〜なくはない」做一个有保留的回应。',
      expected: ['なくはない'], acceptable: ['〜なくはありません'] },
    practice: { themeJa: '本音を少しだけ見せる', starterJa: '「興味がなくはない」ことはありますか？',
      starterZh: '有没有「也不是没兴趣」的事？', targetUse: '〜なくはない' },
    vocabularyLinks: ['fi-iku', 'fi-kimochi'] }),
  g({ grammarId: 'n2g-162', pattern: '〜矢先に', reading: 'やさきに', unit: 11, zhSourceRowId: null,
    mergeDecision: md('n2g-094', '94と同じ', 'same_core_different_nuance',
      '原本例文は094と同一文。「矢先に」＝しようとした直前の出鼻を挫かれる含み。「ところに」＝場面への到来（中立）'),
    meaningJa: 'まさに〜しようとした、その直前に',
    explanationZh: '正要…的节骨眼上（被打断）。行动即将开始的瞬间发生了别的事',
    formation: '動詞辞書形＋（よう）とした ＋矢先に',
    usageScene: '正要出门快递来了、刚要睡觉电话响了',
    nuance: '「出鼻をくじかれる」含みが強い。開始直前限定で「ところに」より範囲が狭い',
    register: 'written',
    sourceExample: src('外に出かけようとした矢先に、配達員がやって来ました。', 'c901143a3e3e9ba7'),
    examplesJa: ['外に出かけようとした矢先に、配達員がやって来ました。',
                 '寝ようとした矢先に、友達から電話がかかってきました。'],
    examplesZh: ['正要出门的节骨眼上，快递员来了。', '刚要睡觉的那一刻，朋友打来了电话。'],
    furigana: 'そとに でかけようと した やさきに、はいたついんが やって きました。',
    commonMistakesZh: '「矢先」原意是箭头，比喻「行动即将离弦的瞬间」。只能用于开始前的一刻：进行中的场面（吃着饭时）用「最中に」，不用「矢先に」',
    learnerFocus: '比「ところに」更有戏剧感：「帰ろうとした矢先に仕事を頼まれた」。职场吐槽的画面感神器',
    similarPatterns: ['〜ところに', '〜とたん'],
    contrast: '「矢先に」＝開始直前の出鼻（狭い）；「ところに」＝場面への到来（広い）；「とたん」＝完了直後',
    recognition: { promptZh: '「出発しようとした矢先に雨が降ってきた」的时机是？',
      options: ['正要出发的那一刻', '出发很久之后', '回来之后', '根本没打算出发'],
      answerIndex: 0, distractorReason: '「矢先に」限定于行动开始的前一瞬',
      explanationZh: '出鼻をくじかれる瞬間' },
    production: { promptJa: '出鼻をくじかれた経験を「〜矢先に」で言ってください。',
      promptZh: '用「〜矢先に」说一次正要行动就被打断的经历。',
      expected: ['矢先に'], acceptable: ['〜ようとした矢先に'] },
    practice: { themeJa: 'タイミングの悪さを笑い話に', starterJa: '「今からやろうとしたのに！」という経験はありますか？',
      starterZh: '有没有「我正要做呢！」就被打断的经历？', targetUse: '〜矢先に' },
    vocabularyLinks: ['fi-deru', 'fi-renraku'] }),
];
