// Phase 3P-5: N2文法完成draft Unit 7（No.91〜105のうち13文型。099/104は同義判断待ち）。
// rightsStatus: teacher_created_confirmed。第1例文=原本、第2例文=独自（実生活）。
import type { N2GrammarDraft } from './n2GrammarDrafts';

const g = (p: Omit<N2GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey' | 'runtimeExampleOrigin'> & { reviewKey?: string; runtimeExampleOrigin?: N2GrammarDraft['runtimeExampleOrigin'] }): N2GrammarDraft =>
  ({ level: 'N2', route: 'n2-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, runtimeExampleOrigin: 'source_confirmed', ...p });

const src = (text: string, hash: string) =>
  ({ text, hash, rightsStatus: 'teacher_created_confirmed' as const });

export const N2_GRAMMAR_DRAFTS_UNIT7: N2GrammarDraft[] = [
  g({ grammarId: 'n2g-091', pattern: '〜どころか', reading: 'どころか', unit: 7, zhSourceRowId: null,
    meaningJa: '〜はもちろん、それ以上に／予想と正反対に',
    explanationZh: '别说…（连…都）／岂止…。程度远超预想或与预想相反',
    formation: '動詞・い形容詞普通形／な形容詞・名詞 ＋どころか',
    usageScene: '强调程度：别说走路，连站都难',
    nuance: '后半句大大超出、甚至推翻前半句，带有惊讶或诉说的语气',
    register: 'both',
    sourceExample: src('骨折したせいで、歩くどころか、立つのも難しいです。', 'b4e7d9f0158dafb9'),
    examplesJa: ['骨折したせいで、歩くどころか、立つのも難しいです。',
                 '節約どころか、先月より出費が増えてしまいました。'],
    examplesZh: ['因为骨折，别说走路，连站着都难。', '别说省钱了，开销比上个月还多了。'],
    furigana: 'こっせつした せいで、あるくどころか、たつのも むずかしいです。',
    commonMistakesZh: '后半句常和「も」呼应（「〜どころか…も」）。前后的程度差是关键',
    learnerFocus: '和中文的「别说…连…都」结构几乎一样，所以学起来很快，会话里可以用来强调',
    similarPatterns: ['〜ばかりか', '〜どころではない'],
    contrast: '「どころか」＝程度の反転・上回り；「ばかりか」＝累加（さらに）',
    recognition: { promptZh: '「漢字どころか、ひらがなも読めない」是什么意思？',
      options: ['别说汉字，连平假名都不会读', '汉字和平假名都会', '只会汉字', '只会平假名'],
      answerIndex: 0, distractorReason: '「どころか」后接程度更基础的否定',
      explanationZh: '别说A连B都…' },
    production: { promptJa: '程度の差を「〜どころか」で言ってください。',
      promptZh: '用「〜どころか」强调程度差。',
      expected: ['どころか'], acceptable: ['〜どころか〜も'] },
    practice: { themeJa: '想像以上だったことを話す', starterJa: '「〜どころか」と言いたくなった経験は？',
      starterZh: '有过想说「岂止如此」的经历吗？', targetUse: '〜どころか' },
    vocabularyLinks: ['fi-muzukashii', 'fi-fueru'] }),
  g({ grammarId: 'n2g-092', pattern: '〜ところだった', reading: 'ところだった', unit: 7, zhSourceRowId: null,
    meaningJa: 'もう少しで〜するところだった（危なかった）',
    explanationZh: '差点就…（幸好没有）',
    formation: '動詞辞書形 ＋ところだった',
    usageScene: '差点迟到、差点忘记',
    nuance: '差点出事又躲过了的安心感。和「あやうく」「もう少しで」呼应',
    register: 'both',
    sourceExample: src('N2例文集に出会わなかったら、試験までに文法が覚えられないところでした。', '54600c68d61c0941'),
    examplesJa: ['N2例文集に出会わなかったら、試験までに文法が覚えられないところでした。',
                 'あやうく終電を逃すところでした。'],
    examplesZh: ['要不是遇到N2例句集，差点到考试都记不完语法。', '差点错过末班车。'],
    furigana: 'エヌツーれいぶんしゅうに であわなかったら、しけんまでに ぶんぽうが おぼえられない ところでした。',
    commonMistakesZh: '实际上并没有发生。「遅刻するところだった」＝并没有迟到。不要和已经发生的事混淆',
    learnerFocus: '「危なかった！」（好险）的常用说法，迟到、忘带东西这类话题天天用得上',
    similarPatterns: ['〜そうになった', '〜かけた'],
    contrast: '「ところだった」＝未遂＋安堵；「そうになった」＝直前まで行った',
    recognition: { promptZh: '「忘れるところだった」的事实是？',
      options: ['差点忘（实际没忘）', '已经完全彻底地忘掉了', '现在正打算要去把它忘记', '绝对不可能会忘记这件事'],
      answerIndex: 0, distractorReason: '「ところだった」表示未遂',
      explanationZh: '死里逃生般的安心' },
    production: { promptJa: '危なかった経験を「〜ところだった」で言ってください。',
      promptZh: '用「〜ところだった」说一次险些发生的事。',
      expected: ['ところだった'], acceptable: ['〜ところでした'] },
    practice: { themeJa: 'ヒヤリとした話をする', starterJa: '最近「危なかった！」ことはありますか？',
      starterZh: '最近有「好险！」的事吗？', targetUse: '〜ところだった' },
    vocabularyLinks: ['fi-wasureru', 'fi-densha'] }),
  g({ grammarId: 'n2g-093', pattern: '〜どころではない', reading: 'どころではない', unit: 7, zhSourceRowId: null,
    meaningJa: '〜する余裕・状況ではない',
    explanationZh: '哪有心思…、根本顾不上…',
    formation: '動詞辞書形／名詞 ＋どころではない',
    usageScene: '忙得顾不上休假、疫情下谈不上旅行',
    nuance: '情况紧迫到不允许。「それどころではない」是会话里的固定说法',
    register: 'both',
    sourceExample: src('コロナ禍で、海外旅行どころではないです。', '04f6531b20bdcc6a'),
    examplesJa: ['コロナ禍で、海外旅行どころではないです。',
                 '引っ越しの準備で、勉強どころではありませんでした。'],
    examplesZh: ['疫情之下，根本谈不上出国旅行。', '忙着准备搬家，哪有心思学习。'],
    furigana: 'コロナかで、かいがいりょこう どころでは ないです。',
    commonMistakesZh: '和「どころか」（岂止）形式相似，其实是两回事。「どころではない」＝没有余力',
    learnerFocus: '「それどころではない」是拒绝打扰时很有力的一句，紧急时候很管用',
    similarPatterns: ['〜余裕がない', '〜場合ではない'],
    contrast: '「どころではない」＝状況が許さない；「場合ではない」＝時機が不適切',
    recognition: { promptZh: '「食事どころではない」是什么状态？',
      options: ['忙/急得顾不上吃饭', '正在吃饭', '吃得很开心', '不饿'],
      answerIndex: 0, distractorReason: '「どころではない」=没有做…的余裕',
      explanationZh: '没有余力' },
    production: { promptJa: '余裕がなかった時期を「〜どころではない」で言ってください。',
      promptZh: '用「〜どころではない」说一段顾不上…的时期。',
      expected: ['どころでは'], acceptable: ['〜どころではなかった'] },
    practice: { themeJa: '忙しかった時期を振り返る', starterJa: '「〜どころではなかった」時期はありますか？',
      starterZh: '有过「根本顾不上…」的时期吗？', targetUse: '〜どころではない' },
    vocabularyLinks: ['fi-isogashii', 'fi-benkyo'] }),
  g({ grammarId: 'n2g-094', pattern: '〜ところに', reading: 'ところに', unit: 7, zhSourceRowId: null,
    meaningJa: 'ちょうど〜の場面に（何かが起きた）',
    explanationZh: '正…的时候（恰巧发生了）',
    formation: '動詞辞書形／ている形／た形 ＋ところに（ところへ）',
    usageScene: '正要出门时快递来了、正说着人就到了',
    nuance: '时机正好赶上，好的巧合和坏的巧合都能用',
    register: 'both',
    sourceExample: src('外に出かけようとしたところに、配達員がやって来ました。', '7d2d17dffe3d4e51'),
    examplesJa: ['外に出かけようとしたところに、配達員がやって来ました。',
                 '噂をしていたところに、本人が現れました。'],
    examplesZh: ['正要出门的时候，快递员来了。', '正说着他呢，本人就出现了。'],
    furigana: 'そとに でかけようと した ところに、はいたついんが やって きました。',
    commonMistakesZh: '「ところに」的后半句典型是某件事到来（来る、現れる、電話が鳴る）',
    learnerFocus: '「いいところに来たね」（来得正好）是欢迎人的固定说法，也是理解日本人时机文化的入口',
    similarPatterns: ['〜たとたん', '〜最中に'],
    contrast: '「ところに」＝場面への到来；「最中に」＝進行の真っ只中；「たとたん」＝直後',
    recognition: { promptZh: '「出かけようとしたところに電話が来た」的时机是？',
      options: ['正要出门时', '出门很久后', '回家后', '没打算出门'],
      answerIndex: 0, distractorReason: '「ところに」表示恰在该场面',
      explanationZh: '场面和到来正好赶上' },
    production: { promptJa: 'タイミングが重なった経験を「〜ところに」で言ってください。',
      promptZh: '用「〜ところに」说一次时机凑巧的事。',
      expected: ['ところに'], acceptable: ['〜ところへ'] },
    practice: { themeJa: '偶然のタイミングを話す', starterJa: '「ちょうどそのとき！」という偶然はありましたか？',
      starterZh: '有过「恰好那时！」的巧合吗？', targetUse: '〜ところに' },
    vocabularyLinks: ['fi-deru', 'fi-renraku'] }),
  g({ grammarId: 'n2g-095', pattern: '〜ところを', reading: 'ところを', unit: 7, zhSourceRowId: null,
    meaningJa: '〜している場面を（見られた・捕まえた）',
    explanationZh: '正…的时候（被看到/被抓住）',
    formation: '動詞ている形／辞書形／た形 ＋ところを',
    usageScene: '打瞌睡被老师发现、行窃被当场抓住',
    nuance: '被看到、被抓住的那个场面。「お忙しいところを」是请求前的铺垫',
    register: 'both',
    sourceExample: src('授業中に寝ているところを先生に見つかってしまいました。', '90b8c65a1187f5cc'),
    examplesJa: ['授業中に寝ているところを先生に見つかってしまいました。',
                 'お忙しいところをすみませんが、少しよろしいですか。'],
    examplesZh: ['上课打瞌睡被老师发现了。', '百忙之中打扰您，方便说两句吗？'],
    furigana: 'じゅぎょうちゅうに ねている ところを せんせいに みつかって しまいました。',
    commonMistakesZh: '「お忙しいところを」已经固化成寒暄语，整套记下来，请求就会显得礼貌',
    learnerFocus: '「お忙しいところをすみません」是职场上打断别人的固定说法，今天就能用',
    similarPatterns: ['〜ところに', '〜場面を'],
    contrast: '「ところを」＝目撃・捕捉の対象；「ところに」＝到来のタイミング',
    recognition: { promptZh: '「お忙しいところをすみません」什么时候说？',
      options: ['打扰忙碌的人时的开场白', '和对方分手道别时说的寒暄话', '一起吃饭时的客套话', '收到礼物时的感谢语'],
      answerIndex: 0, distractorReason: '依頼・割り込みの前置き',
      explanationZh: '请求前礼貌的铺垫' },
    production: { promptJa: '割り込みの前置きを「お忙しいところを」で言ってください。',
      promptZh: '用「お忙しいところを」说打扰的开场白。',
      expected: ['ところを'], acceptable: ['お忙しいところをすみません'] },
    practice: { themeJa: '丁寧に割り込む練習', starterJa: '上司に急ぎの質問。最初の一言は？',
      starterZh: '有急事问上司，第一句怎么说？', targetUse: 'お忙しいところを' },
    vocabularyLinks: ['fi-neru', 'fi-isogashii'] }),
  g({ grammarId: 'n2g-096', pattern: '〜としか言いようがない', reading: 'としかいいようがない', unit: 7, zhSourceRowId: null,
    meaningJa: '〜以外に表現のしようがない',
    explanationZh: '只能说是…、除了说…没别的形容',
    formation: '名詞・な形容詞／文 ＋としか言いようがない',
    usageScene: '对超乎寻常的事给出唯一评价',
    nuance: '强调对评价的断定，既能用于赞赏，也能用于无语',
    register: 'both',
    matchKeys: ['としか言いようが'],
    // 原本は「試験を合格」。runtime例文のみ標準的な「試験に合格」へ正規化（原本は無改変で保持）
    sourceExample: src('1ヶ月でN2の試験を合格できたのは、生徒自身が優秀としか言いようがないです。', 'a7963770e3e54c5d'),
    examplesJa: ['1ヶ月でN2の試験に合格できたのは、生徒自身が優秀としか言いようがないです。',
                 'あのタイミングで雨が止んだのは、幸運としか言いようがありません。'],
    examplesZh: ['一个月就考过N2，只能说是学生本人优秀。', '雨在那个时机停了，只能说是幸运。'],
    furigana: 'いっかげつで エヌツーの しけんに ごうかく できたのは、せいと じしんが ゆうしゅうとしか いいようが ないです。',
    commonMistakesZh: '「言いよう」＝说法。写成「言い様がない」也一样。语气很强，不要滥用',
    learnerFocus: '可以用作最高级的赞美，如「見事としか言いようがない」（只能说漂亮）',
    similarPatterns: ['〜と言うほかない', '〜に違いない'],
    contrast: '「としか言いようがない」＝表現の唯一性；「に違いない」＝確信の推定',
    recognition: { promptZh: '「奇跡としか言いようがない」的语气是？',
      options: ['只能用奇迹来形容（强调）', '断定这不是什么奇迹', '也许是奇迹说不清楚', '表示很讨厌奇迹'],
      answerIndex: 0, distractorReason: '唯一の表現だと強調する',
      explanationZh: '强调断定的评价' },
    production: { promptJa: '驚いた出来事を「〜としか言いようがない」で評してください。',
      promptZh: '用「〜としか言いようがない」评价一件惊人的事。',
      expected: ['言いようがな'], acceptable: ['〜としか言いようがない'] },
    practice: { themeJa: '最大級の評価を伝える', starterJa: '「すごいとしか言いようがない」経験は？',
      starterZh: '有什么「只能说厉害」的经历？', targetUse: '〜としか言いようがない' },
    vocabularyLinks: ['fi-jouzu', 'fi-ureshii'] }),
  g({ grammarId: 'n2g-097', pattern: '〜としたら', reading: 'としたら', unit: 7, zhSourceRowId: null,
    meaningJa: 'もし〜と仮定したら',
    explanationZh: '假如…的话（基于假定推论）',
    formation: '文（普通形） ＋としたら／とすれば／とすると',
    usageScene: '假设条件下的提问、推论',
    nuance: '「としたら」偏口语，「とすれば」偏逻辑，「とすると」重结论',
    register: 'both',
    sourceExample: src('今日、授業をするとしたら、何時からできますか？', '5458566fa0063618'),
    examplesJa: ['今日、授業をするとしたら、何時からできますか？',
                 '日本で家を買うとしたら、どの街がいいですか。'],
    examplesZh: ['假如今天上课的话，几点能开始？', '假如在日本买房，哪个城市好？'],
    furigana: 'きょう、じゅぎょうを すると したら、なんじから できますか？',
    commonMistakesZh: '比「たら」的假设色彩更强。既能用于以实现为前提的商量，也能用于纯假想的话题',
    learnerFocus: '「もし〜としたら？」是能把话题展开的万能提问，很适合作为闲聊的起点',
    similarPatterns: ['〜たら', '〜と仮定して'],
    contrast: '「としたら」＝仮定の枠組み；「たら」＝条件一般',
    recognition: { promptZh: '「引っ越すとしたら」是什么前提？',
      options: ['假如要搬家的话', '已经搬完家住下了', '根本就不打算搬家', '现在正在搬家的过程中'],
      answerIndex: 0, distractorReason: '「としたら」引入假定',
      explanationZh: '搭出假设的框架' },
    production: { promptJa: '仮定の質問を「〜としたら」で作ってください。',
      promptZh: '用「〜としたら」造一个假设性问题。',
      expected: ['としたら'], acceptable: ['〜とすれば', '〜とすると'] },
    practice: { themeJa: 'もしもの話で盛り上がる', starterJa: 'もし1年休みが取れるとしたら、何をしますか？',
      starterZh: '假如能休一年假，你做什么？', targetUse: '〜としたら' },
    vocabularyLinks: ['fi-yotei', 'fi-kangaeru'] }),
  g({ grammarId: 'n2g-098', pattern: '〜とともに', reading: 'とともに', unit: 7, zhSourceRowId: 'n3row-76',
    meaningJa: '〜と同時に／〜につれて／〜と一緒に',
    explanationZh: '①与…同时 ②随着… ③与…一起（书面）',
    formation: '名詞／動詞辞書形 ＋とともに',
    usageScene: '书面描述变化的伴随、共同行动',
    nuance: '三种用法要看上下文区分。新闻和致辞里的常客',
    register: 'written',
    sourceExample: src('コロナ拡大とともに、リモートワークが普及しました。', '5cba3ec5119dec32'),
    examplesJa: ['コロナ拡大とともに、リモートワークが普及しました。',
                 '年齢とともに、好みも変わってきました。'],
    examplesZh: ['随着疫情扩大，远程办公普及了。', '随着年龄增长，喜好也变了。'],
    furigana: 'コロナかくだいと ともに、リモートワークが ふきゅう しました。',
    commonMistakesZh: '会话里用「〜と一緒に」「〜につれて」更自然。「とともに」偏书面',
    learnerFocus: '阅读新闻时很常见。看到「〜とともに」就要想到是伴随发生的变化',
    similarPatterns: ['〜につれて', '〜と同時に'],
    contrast: '「とともに」＝書面の伴随；「につれて」＝連動変化；「と同時に」＝時点の一致',
    recognition: { promptZh: '「経済成長とともに」的意思是？',
      options: ['随着经济增长', '经济完全没有增长', '在经济之前', '与经济无关'],
      answerIndex: 0, distractorReason: '変化の伴随',
      explanationZh: '书面语中表示伴随变化' },
    production: { promptJa: '変化の伴随を「〜とともに」で言ってください。',
      promptZh: '用「〜とともに」描述伴随变化。',
      expected: ['とともに'], acceptable: ['年齢とともに'] },
    practice: { themeJa: '時代の変化を語る', starterJa: '何とともに、あなたの生活は変わりましたか？',
      starterZh: '随着什么，你的生活发生了变化？', targetUse: '〜とともに' },
    vocabularyLinks: ['fi-kawaru', 'fi-fueru'] }),
  g({ grammarId: 'n2g-100', pattern: '〜ないことには', reading: 'ないことには', unit: 7, zhSourceRowId: null,
    meaningJa: '〜しなければ（結果は分からない・できない）',
    explanationZh: '不…的话（就无从…）',
    formation: '動詞ない形 ＋ことには＋否定',
    usageScene: '不试不知道、不见面谈不了',
    nuance: '后半句一定是否定，可以用来催人「先做了再说」',
    register: 'both',
    sourceExample: src('一度試してみないことには、結果は分かりません。', 'd7d3715c37ddda13'),
    examplesJa: ['一度試してみないことには、結果は分かりません。',
                 '実物を見ないことには、決められません。'],
    examplesZh: ['不先试一次，就不知道结果。', '不看实物，就没法决定。'],
    furigana: 'いちど ためして みない ことには、けっかは わかりません。',
    commonMistakesZh: '后半句必须是否定。说「試さないことには、分かります」不成立',
    learnerFocus: '「やってみないことには」（不试试的话）是鼓励人挑战的积极说法',
    similarPatterns: ['〜てからでないと', '〜なければ'],
    contrast: '「ないことには」＝前提の欠如→不可；「てからでないと」＝手順の前提',
    recognition: { promptZh: '「会ってみないことには」后面是？',
      options: ['何とも言えません', 'よく分かります', '決めました', '行きません'],
      answerIndex: 0, distractorReason: '後半は否定・不可',
      explanationZh: '缺少前提就得不到结果' },
    production: { promptJa: '「まず試すべき」を「〜ないことには」で言ってください。',
      promptZh: '用「〜ないことには」表达要先尝试。',
      expected: ['ないことには'], acceptable: ['試してみないことには'] },
    practice: { themeJa: '挑戦を促す', starterJa: '迷っている友達に「やってみないことには…」と言ってみましょう',
      starterZh: '对犹豫的朋友说「不试试的话…」', targetUse: '〜ないことには' },
    vocabularyLinks: ['fi-wakaru', 'fi-kimeru'] }),
  g({ grammarId: 'n2g-101', pattern: '〜ないことはない', reading: 'ないことはない', unit: 7, zhSourceRowId: null,
    meaningJa: '〜できないわけではない（条件つきの肯定）',
    explanationZh: '也不是不…（有保留的肯定）',
    formation: '動詞ない形 ＋ことはない',
    usageScene: '勉强承认可以做到',
    nuance: '用双重否定表达弱肯定，含有「勉强一下也不是不行」的意味',
    register: 'spoken',
    matchKeys: ['ないことはな', 'ないことはあり'],
    // 原本は「食べれない」（ら抜き）。runtime例文のみ「食べられない」へ正規化（原本は無改変で保持）
    sourceExample: src('ちょっと辛いですが、食べれないことはないです。', 'dd31f8fa917879ab'),
    examplesJa: ['ちょっと辛いですが、食べられないことはないです。',
                 '今日中に終わらせられないことはないですが、かなり大変です。'],
    examplesZh: ['虽然有点辣，也不是不能吃。', '今天之内也不是做不完，但相当吃力。'],
    furigana: 'ちょっと からいですが、たべられない ことは ないです。',
    commonMistakesZh: '是勉强的肯定，不是爽快答应。对方会理解为「有条件的同意」',
    learnerFocus: '对于勉强的请求，可以用「できなくはないですが…」把话留有余地，转入条件商量',
    similarPatterns: ['〜なくはない', '〜わけではない'],
    contrast: '「ないことはない」＝条件つき可能；「わけではない」＝部分否定',
    recognition: { promptZh: '「行けないことはない」的语气是？',
      options: ['勉强能去（有保留）', '毫无保留地一定去', '斩钉截铁绝对不去', '实际上已经去过了'],
      answerIndex: 0, distractorReason: '二重否定の弱い肯定',
      explanationZh: '有条件的肯定' },
    production: { promptJa: '条件つきの引き受けを「〜ないことはない」で言ってください。',
      promptZh: '用「〜ないことはない」有保留地接受。',
      expected: ['ないことはな'], acceptable: ['できないことはない'] },
    practice: { themeJa: '含みのある返事をする', starterJa: '無理めな頼まれごと、どう返しますか？',
      starterZh: '被拜托有点勉强的事，你怎么回？', targetUse: '〜ないことはない' },
    vocabularyLinks: ['fi-taberu', 'fi-muri'] }),
  g({ grammarId: 'n2g-102', pattern: '〜ないでもない', reading: 'ないでもない', unit: 7, zhSourceRowId: null,
    meaningJa: '〜する気持ちが少しはある',
    explanationZh: '也不是完全不…、多少有点…',
    formation: '動詞ない形 ＋でもない／〜ないものでもない',
    usageScene: '部分理解、有限的让步',
    nuance: '「分からないでもない」＝你的心情我多少能理解，是成熟的留有余地的说法',
    register: 'both',
    matchKeys: ['ないでもな', 'ないでも'],
    sourceExample: src('私も似たような経験があるので、彼の言っていることが分からないでもないです。', 'ba9a01d721fab9e5'),
    examplesJa: ['私も似たような経験があるので、彼の言っていることが分からないでもないです。',
                 '条件次第では、引き受けないでもないです。'],
    examplesZh: ['我也有过类似经历，他说的也不是不能理解。', '看条件的话，也不是不能接。'],
    furigana: 'わたしも にたような けいけんが あるので、かれの いっていることが わからないでも ないです。',
    commonMistakesZh: '和赞成不一样。可以保留「我理解，但我不同意」的立场，是成年人的说法',
    learnerFocus: '既能缓和对立，又能守住自己的立场，在讨论时很宝贵',
    similarPatterns: ['〜ないことはない', '〜なくはない', '〜なくはない'],
    contrast: '「ないでもない」＝心情の部分的容認；「ないことはない」＝可能性の容認。「なくはない」＝同義の口語頻出形（CEO判断で本項へ統合）',
    recognition: { promptZh: '「分からないでもない」的立场是？',
      options: ['多少能理解（但未必同意）', '完全同意对方所说的每一句话', '一点也不能够理解对方的想法', '根本就没有在听对方说话'],
      answerIndex: 0, distractorReason: '部分的な理解の表明',
      explanationZh: '留有余地的认可' },
    production: { promptJa: '部分的な理解を「〜ないでもない」で言ってください。',
      promptZh: '用「〜ないでもない」表达部分理解。',
      expected: ['ないでもな'], acceptable: ['分からないでもない'] },
    practice: { themeJa: '反対意見に含みを持たせる', starterJa: '完全には賛成できない意見に、どう返しますか？',
      starterZh: '对不能完全赞成的意见，你怎么回应？', targetUse: '〜ないでもない' },
    vocabularyLinks: ['fi-wakaru', 'fi-iken'] }),
  g({ grammarId: 'n2g-103', pattern: '〜ながらも', reading: 'ながらも', unit: 7, zhSourceRowId: null,
    meaningJa: '〜のに／〜けれども（逆接）',
    explanationZh: '虽然…却…（书面逆接）',
    formation: '動詞ます形／い形容詞／な形容詞／名詞 ＋ながら（も）',
    usageScene: '明知却…、虽小却…',
    nuance: '和表示同时进行的「ながら」不同，这是转折用法，如「狭いながらも楽しい我が家」（虽小但快乐的家）',
    register: 'written',
    sourceExample: src('今のままでは合格できないと知りながらも、テスト勉強をせずに遊んでばかりいました。', '371b5a536722c012'),
    examplesJa: ['今のままでは合格できないと知りながらも、テスト勉強をせずに遊んでばかりいました。',
                 '狭いながらも、居心地のいい部屋です。'],
    examplesZh: ['明知这样下去考不过，却不复习光顾着玩。', '虽然狭小，却是舒适的房间。'],
    furigana: 'いまの ままでは ごうかく できないと しりながらも、テストべんきょうを せずに あそんで ばかり いました。',
    commonMistakesZh: '表示同时的「ながら」和表示转折的「ながらも」要看上下文区分。「知りながら（も）」是转折',
    learnerFocus: '自省句「知りながらも、つい」（明明知道，还是忍不住）是成熟的反省说法，写作文时很出彩',
    similarPatterns: ['〜のに', '〜つつも'],
    contrast: '「ながらも」＝書面逆接；「つつも」＝同系のより硬い形；「のに」＝感情的',
    recognition: { promptZh: '「残念ながら」的「ながら」是哪种？',
      options: ['逆接（虽然遗憾但…）', '表示两件事情同时在进行', '表示前后因果关系', '表示行为的目的'],
      answerIndex: 0, distractorReason: '「残念ながら」は逆接の慣用形',
      explanationZh: '转折用法的固定形式' },
    production: { promptJa: '自省を「〜と知りながらも」で言ってください。',
      promptZh: '用「〜と知りながらも」表达自省。',
      expected: ['ながらも'], acceptable: ['知りながらも'] },
    practice: { themeJa: '分かっちゃいるけど、を語る', starterJa: '「よくないと知りながらも」してしまうことは？',
      starterZh: '有明知不好却还做的事吗？', targetUse: '〜ながらも' },
    vocabularyLinks: ['fi-wakaru', 'fi-benkyo'] }),
  g({ grammarId: 'n2g-105', pattern: '〜ならともかく', reading: 'ならともかく', unit: 7, zhSourceRowId: null,
    meaningJa: '〜なら仕方ないが（そうではないのだから）',
    explanationZh: '要是…倒也罢了（可实际不是）',
    formation: '名詞／文（普通形） ＋ならともかく',
    usageScene: '对比可原谅的情况，强调当前不可接受',
    nuance: '前半句是可以接受的假设，后半句是对现实的不满或要求',
    register: 'both',
    sourceExample: src('この問題は今回だけならともかく、いつも間違える問題です。', 'd511b14b4b44a3d0'),
    examplesJa: ['この問題は今回だけならともかく、いつも間違える問題です。',
                 '新人ならともかく、入社5年目でこのミスは困ります。'],
    examplesZh: ['这道题要是只错这一次倒也罢了，可总是错。', '要是新人倒也罢了，入职5年还犯这错就难办了。'],
    furigana: 'この もんだいは こんかいだけなら ともかく、いつも まちがえる もんだいです。',
    commonMistakesZh: '前半句要放「还能接受的那一方」。顺序反过来意思就乱了',
    learnerFocus: '能有条理地提出抱怨和意见。不带情绪，却能把问题点凸显出来',
    similarPatterns: ['〜はともかく', '〜ならまだしも'],
    contrast: '「ならともかく」＝仮定との対比；「はともかく」＝話題の棚上げ',
    recognition: { promptZh: '「一度ならともかく」暗示什么？',
      options: ['一次倒也罢了（可不止一次）', '表示只发生过一次', '表示一次也不允许', '表示什么都没发生'],
      answerIndex: 0, distractorReason: '許容できる仮定と現実の対比',
      explanationZh: '通过对比来强调' },
    production: { promptJa: '許せる場合と現実を「〜ならともかく」で対比してください。',
      promptZh: '用「〜ならともかく」对比可接受与现实。',
      expected: ['ならともかく'], acceptable: ['一度ならともかく'] },
    practice: { themeJa: '筋道立てて指摘する', starterJa: '「〜ならともかく」と言いたくなる場面は？',
      starterZh: '什么场合想说「要是…倒也罢了」？', targetUse: '〜ならともかく' },
    vocabularyLinks: ['fi-mondai', 'fi-komaru'] }),
  // CEO統合判断（2026-07-30）: 独立文型として維持 → 本編昇格（元・同義判断待ちpre-draft）
  g({ grammarId: 'n2g-099', pattern: '〜とは限らない', reading: 'とはかぎらない', unit: 7, zhSourceRowId: null,
    meaningJa: '必ずしも〜ではない（例外がある）',
    explanationZh: '未必…、不一定…。指出例外的存在，否定「凡是…都…」',
    formation: '動詞・い形容詞普通形／な形容詞・名詞（だ） ＋とは限らない',
    usageScene: '提醒高分未必会说、贵的未必好',
    nuance: '常和「必ずしも」呼应，是回避断言的、有分寸的保留说法',
    register: 'both',
    sourceExample: src('N1試験で高得点をとれるからといって、仕事で使える会話力があるとは限らないです。', 'c460a00ae74fe178'),
    examplesJa: ['N1試験で高得点をとれるからといって、仕事で使える会話力があるとは限らないです。',
                 '値段が高いものが、必ずしも良いとは限りません。'],
    examplesZh: ['即使N1考了高分，也未必有工作中能用的会话能力。', '价格贵的东西未必就好。'],
    furigana: 'エヌワン しけんで こうとくてんを とれる からと いって、しごとで つかえる かいわりょくが あるとは かぎらないです。',
    commonMistakesZh: '和「わけがない」（不可能）不同——「とは限らない」承认多数情况成立、只是有例外。「からといって〜とは限らない」是黄金搭配',
    learnerFocus: '反驳刻板印象的礼貌武器：「中国人がみんな辛いもの好きとは限りませんよ」。不冲突地纠正对方',
    similarPatterns: ['〜というものではない', '〜わけではない'],
    contrast: '「とは限らない」＝例外の指摘；「というものではない」＝通念そのものの否定；「わけではない」＝誤解の部分訂正',
    recognition: { promptZh: '「有名な店がおいしいとは限らない」的立场是？',
      options: ['有名的店也有不好吃的例外', '有名的店无一例外全都不好吃', '有名的店没有一家是不好吃的', '这个地方连一家有名的店都没有'],
      answerIndex: 0, distractorReason: '「とは限らない」＝多数成立但存在例外',
      explanationZh: '「未必」的例外指摘' },
    production: { promptJa: '思い込みへの反例を「〜とは限らない」で言ってください。',
      promptZh: '用「〜とは限らない」反驳一个刻板印象。',
      expected: ['とは限らない'], acceptable: ['〜とは限りません'] },
    practice: { themeJa: '思い込みをやわらかく正す', starterJa: '「みんなそう思ってるけど実は違う」ことはありますか？',
      starterZh: '有什么「大家都以为如此其实未必」的事？', targetUse: '〜とは限らない' },
    vocabularyLinks: ['fi-takai', 'fi-shigoto'] }),
];
