// Phase 3P-5: N2文法完成draft Unit 8（No.106〜120の15文型）。
// rightsStatus: teacher_created_confirmed。第1例文=原本（無改変）、第2例文=独自（実生活）。
import type { N2GrammarDraft } from './n2GrammarDrafts';

const g = (p: Omit<N2GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey' | 'runtimeExampleOrigin'> & { reviewKey?: string; runtimeExampleOrigin?: N2GrammarDraft['runtimeExampleOrigin'] }): N2GrammarDraft =>
  ({ level: 'N2', route: 'n2-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, runtimeExampleOrigin: 'source_confirmed', ...p });

const src = (text: string, hash: string) =>
  ({ text, hash, rightsStatus: 'teacher_created_confirmed' as const });

export const N2_GRAMMAR_DRAFTS_UNIT8: N2GrammarDraft[] = [
  g({ grammarId: 'n2g-106', pattern: '〜にあたって', reading: 'にあたって', unit: 8, zhSourceRowId: null,
    meaningJa: '〜という特別な節目・機会に（改まって）',
    explanationZh: '值此…之际、在…（这一重要时刻）。用于开始新事物或迎来节点时的郑重表达',
    formation: '動詞辞書形／名詞 ＋にあたって（にあたり）',
    usageScene: '开学致辞、入职问候、周年纪念等郑重的节点场合',
    nuance: '日常の小さな行為には使わない。節目を意識した改まった響き',
    register: 'written',
    sourceExample: src('結婚記念10周年にあたって、大きなイベントをしようと思っています。', '4dddddd7c160874b'),
    examplesJa: ['結婚記念10周年にあたって、大きなイベントをしようと思っています。',
                 '新しい仕事を始めるにあたって、必要な準備を確認しました。'],
    examplesZh: ['值结婚十周年之际，打算办一场大型活动。', '开始新工作之际，确认了必要的准备。'],
    furigana: 'けっこんきねん じゅっしゅうねんに あたって、おおきな イベントを しようと おもって います。',
    commonMistakesZh: '不能用于日常小事：「寝るにあたって」不自然。只用于开学、就职、纪念日等有仪式感的节点',
    learnerFocus: '中文「值此…之际」几乎只出现在书面贺词里，日语「にあたって」在口头致辞也常用。自我介绍开场「入社にあたって」很得体',
    similarPatterns: ['〜に際して', '〜に先立って'],
    contrast: '「にあたって」＝節目の改まった表明；「に際して」＝手続き・案内の定型；「に先立って」＝本番前の準備行為',
    recognition: { promptZh: '哪个句子用「にあたって」最自然？',
      options: ['留学するにあたって、住む場所を探した', '毎朝歯を磨くにあたって、水を使う', 'コンビニに行くにあたって、財布を持った', 'テレビを見るにあたって、座った'],
      answerIndex: 0, distractorReason: '其余三项都是日常小事，没有节点的郑重感',
      explanationZh: '「にあたって」只用于人生节点、正式活动等重要时刻' },
    production: { promptJa: '新しく何かを始めるときの準備を「〜にあたって」で言ってください。',
      promptZh: '用「〜にあたって」说说开始新事物时做的准备。',
      expected: ['にあたって'], acceptable: ['〜にあたり'] },
    practice: { themeJa: '新生活の節目を語る', starterJa: '新しい環境を始めるにあたって、何を準備しましたか？',
      starterZh: '开始新环境时，你做了什么准备？', targetUse: '〜にあたって' },
    vocabularyLinks: ['fi-hajimeru', 'fi-yotei'] }),
  g({ grammarId: 'n2g-107', pattern: '〜において', reading: 'において', unit: 8, zhSourceRowId: 'n3row-119',
    meaningJa: '〜で（場所・場面・分野を改まって示す）',
    explanationZh: '在…（场所、场合、领域）。「で」的正式书面说法，也可指抽象领域',
    formation: '名詞 ＋において（における＋名詞）',
    usageScene: '会议通知、颁奖典礼、论文中指明场所或领域',
    nuance: '場所の「で」の硬い言い方。抽象的な分野（教育において等）にも使える',
    register: 'written',
    sourceExample: src('この授業は会話力を上げることにおいて、他の教室よりも力を入れています。', '5db95ffeebc4507f'),
    examplesJa: ['この授業は会話力を上げることにおいて、他の教室よりも力を入れています。',
                 '表彰式は本社ビルにおいて行われます。'],
    examplesZh: ['这门课在提高会话能力方面，比其他教室更下功夫。', '颁奖仪式将在总部大楼举行。'],
    furigana: 'この じゅぎょうは かいわりょくを あげる ことに おいて、ほかの きょうしつよりも ちからを いれて います。',
    commonMistakesZh: '日常口语用「で」就好：「コンビニにおいて買った」显得滑稽。名词修饰要用「における」：「日本における教育」',
    learnerFocus: '中文「在…方面／在…举行」都对应「において」。写正式邮件、报告时替换「で」立刻显得专业',
    similarPatterns: ['〜で', '〜における'],
    contrast: '「において」＝場所・分野の改まった提示；「にかけては」＝得意分野の自慢；「で」＝日常の中立表現',
    recognition: { promptZh: '哪句的「において」用得不自然？',
      options: ['トイレにおいて歯を磨いた', '会議は東京において行われた', '教育において大切なこと', '式典は講堂において行う'],
      answerIndex: 0, distractorReason: '日常小场所用「で」，「において」用于正式场合与抽象领域',
      explanationZh: '「において」是「で」的郑重版，日常琐事不用' },
    production: { promptJa: '改まった場面の案内を「〜において」で言ってください。',
      promptZh: '用「〜において」正式地说明活动地点。',
      expected: ['において'], acceptable: ['〜における'] },
    practice: { themeJa: '改まった案内文を作る', starterJa: 'イベントの開催場所を、丁寧な案内文で伝えてみましょう。',
      starterZh: '试着用正式的通知句式说明活动地点。', targetUse: '〜において' },
    vocabularyLinks: ['fi-shigoto', 'fi-setsumei'] }),
  g({ grammarId: 'n2g-108', pattern: '〜に応じて', reading: 'におうじて', unit: 8, zhSourceRowId: null,
    meaningJa: '〜に合わせて、それぞれ変える',
    explanationZh: '根据…、按照…（相应地调整变化）。前项不同，后项的做法也随之不同',
    formation: '名詞 ＋に応じて（に応じた＋名詞）',
    usageScene: '按水平分班、按经验定工资、按人数换房间',
    nuance: '前項の変化・違いに合わせて後項を柔軟に変えるのが核',
    register: 'both',
    matchKeys: ['に応じて', 'に応じた'],
    sourceExample: src('会話特化型の授業内容は生徒のレベルに応じて、合わせることができます。', '1202bafda7f4541d'),
    examplesJa: ['会話特化型の授業内容は生徒のレベルに応じて、合わせることができます。',
                 '経験に応じて、給料が決まります。'],
    examplesZh: ['会话特训课的内容可以根据学生的水平来调整。', '工资根据经验决定。'],
    furigana: 'かいわ とっかがたの じゅぎょうないようは せいとの レベルに おうじて、あわせる ことが できます。',
    commonMistakesZh: '和「に応えて」（回应期待）同源不同义：「レベルに応じて変える」＝按水平调整；「期待に応えて頑張る」＝不辜负期待。汉字都是「応」，中文学习者最易混',
    learnerFocus: '中文一个「根据」对应日语「に応じて／によって／に基づいて」。「に応じて」强调灵活调整，谈个性化服务时最合适',
    similarPatterns: ['〜によって', '〜に応えて'],
    contrast: '「に応じて」＝違いに合わせ調整；「によって」＝場合ごとに異なる事実；「に基づいて」＝基準・根拠に忠実',
    recognition: { promptZh: '「レベルに応じてクラスを分ける」是什么意思？',
      options: ['按水平高低分成不同班级', '不管水平都在同一班', '回应大家的期待开班', '按报名顺序分班'],
      answerIndex: 0, distractorReason: '「に応じて」表示按前项的差异相应调整',
      explanationZh: '前项（水平）不同→后项（班级）也随之不同' },
    production: { promptJa: '状況によってやり方を変えることを「〜に応じて」で言ってください。',
      promptZh: '用「〜に応じて」说说根据情况调整做法的例子。',
      expected: ['に応じて'], acceptable: ['〜に応じた'] },
    practice: { themeJa: '柔軟な対応を説明する', starterJa: '相手や状況に応じて、やり方を変えていることはありますか？',
      starterZh: '你会根据对象或情况调整做法吗？', targetUse: '〜に応じて' },
    vocabularyLinks: ['fi-kawaru', 'fi-kimeru'] }),
  g({ grammarId: 'n2g-109', pattern: '〜にかかわらず', reading: 'にかかわらず', unit: 8, zhSourceRowId: 'n3row-118',
    meaningJa: '〜に関係なく',
    explanationZh: '无论…都…、不管…与否。前项的差异不影响后项',
    formation: '名詞／動詞辞書形＋ない形／対になる語 ＋にかかわらず',
    usageScene: '不论晴雨照常举办、不问经验均可报名',
    nuance: '「高い低い」「あるなし」のような対語と相性がよい。掲示・募集要項の定番',
    register: 'both',
    sourceExample: src('社会に出ると、学校の成績が高い低いにかかわらず、成果が求められる。', '58ed3a3681346a74'),
    examplesJa: ['社会に出ると、学校の成績が高い低いにかかわらず、成果が求められる。',
                 '経験の有無にかかわらず、応募できます。'],
    examplesZh: ['进入社会后，不管在校成绩好坏，都要求拿出成果。', '不论有无经验，都可以应聘。'],
    furigana: 'しゃかいに でると、がっこうの せいせきが たかい ひくいに かかわらず、せいかが もとめられる。',
    commonMistakesZh: '最大陷阱是「にもかかわらず」（尽管…却…）：多一个「も」意思完全变。「雨にかかわらず行く」＝不管下不下雨都去；「雨にもかかわらず来た」＝尽管下着雨却还是来了',
    learnerFocus: '中文「无论」和「尽管」分得很清，日语只差一个「も」。做题时先找「も」再判断句意，是稳定拿分点',
    similarPatterns: ['〜を問わず', '〜にもかかわらず'],
    contrast: '「にかかわらず」＝無関係（无论）；「にもかかわらず」＝逆接（尽管却）；「を問わず」＝募集要項でより硬い',
    recognition: { promptZh: '「経験の有無にかかわらず採用します」的意思是？',
      options: ['有没有经验都可能被录用', '只录用有经验的人', '尽管没经验却被录用了', '只录用没经验的人'],
      answerIndex: 0, distractorReason: '「にかかわらず」＝前项差异不影响结果，选项三是「にもかかわらず」的意思',
      explanationZh: '不管有无经验，结果（可应聘）不变' },
    production: { promptJa: '条件に関係なく成り立つことを「〜にかかわらず」で言ってください。',
      promptZh: '用「〜にかかわらず」说一件不受条件影响的事。',
      expected: ['にかかわらず'], acceptable: ['〜に関わらず'] },
    practice: { themeJa: '条件不問のルールを説明する', starterJa: '天気や人数にかかわらず、必ずやると決めていることはありますか？',
      starterZh: '有没有不管天气人数如何都一定会做的事？', targetUse: '〜にかかわらず' },
    vocabularyLinks: ['fi-keiken', 'fi-mondai'] }),
  g({ grammarId: 'n2g-110', pattern: '〜に限って', reading: 'にかぎって', unit: 8, zhSourceRowId: null,
    meaningJa: '〜だけ特別に／よりによって〜のときだけ',
    explanationZh: '仅限…；偏偏在…的时候。①限定优惠 ②墨菲定律式的「偏偏」③「我家孩子绝不会」的信任',
    formation: '名詞 ＋に限って',
    usageScene: '限时优惠告知、抱怨偏偏赶时间时公交不来、为家人辩护',
    nuance: '「急いでいる時に限って」は不運への恨み節。「うちの子に限って」は強い信頼',
    register: 'both',
    matchKeys: ['に限って'],
    sourceExample: src('今回、4月中に限って、文法例文集をプレゼントしています。', '65bd05e6009fefc4'),
    examplesJa: ['今回、4月中に限って、文法例文集をプレゼントしています。',
                 '急いでいる朝に限って、バスがなかなか来ません。'],
    examplesZh: ['这次仅限4月期间，赠送语法例句集。', '偏偏在赶时间的早上，公交车迟迟不来。'],
    furigana: 'こんかい、しがつちゅうに かぎって、ぶんぽう れいぶんしゅうを プレゼントして います。',
    commonMistakesZh: '三个用法语气完全不同：期间限定（中性）、偏偏不巧（抱怨）、绝不会（信任）。把「うちの子に限って」理解成「只有我家孩子会」正好相反',
    learnerFocus: '抱怨用法最有生活感：「大事な日に限って寝坊する」。学会它，吐槽立刻地道',
    similarPatterns: ['〜に限り', '〜だけ'],
    contrast: '「に限って」＝限定＋偏偏＋信任の三用法；「に限り」＝掲示の期間・対象限定のみ；「だけ」＝中立の限定',
    recognition: { promptZh: '「大事な試験の日に限って、電車が遅れた」的语气是？',
      options: ['偏偏在重要日子倒霉（抱怨）', '只有考试日电车才开', '考试日电车打折', '电车每天都迟到'],
      answerIndex: 0, distractorReason: '此用法表示「偏偏赶上」的不走运',
      explanationZh: '「大事な日に限って＋不運」＝墨菲定律式的抱怨' },
    production: { promptJa: '「よりによって」という不運を「〜に限って」で言ってください。',
      promptZh: '用「〜に限って」吐槽一次「偏偏在那时」的不走运。',
      expected: ['に限って'], acceptable: ['〜の日に限って'] },
    practice: { themeJa: '不運な偶然を吐露する', starterJa: '「よりによって今日！?」という経験はありますか？',
      starterZh: '有过「偏偏是今天！?」的经历吗？', targetUse: '〜に限って' },
    vocabularyLinks: ['fi-basu', 'fi-isogashii'] }),
  g({ grammarId: 'n2g-111', pattern: '〜に限る', reading: 'にかぎる', unit: 8, zhSourceRowId: null,
    meaningJa: '〜が一番いい（話し手の主観的おすすめ）',
    explanationZh: '最好是…、…最棒。说话人主观的「首选」，带有经验之谈的语气',
    formation: '名詞／動詞辞書形・ない形 ＋に限る',
    usageScene: '冷天推荐火锅、疲惫时主张早睡、夏天主张吹空调',
    nuance: '個人の実感からの断言。客観データの比較には使わない',
    register: 'spoken',
    matchKeys: ['に限る', 'に限り'],
    sourceExample: src('寒い日は、熱々の火鍋に限ります。', 'cb7b639fd6a30199'),
    examplesJa: ['寒い日は、熱々の火鍋に限ります。',
                 '疲れた日は、早く寝るに限ります。'],
    examplesZh: ['冷天最棒的就是热腾腾的火锅。', '累的日子最好就是早点睡。'],
    furigana: 'さむい ひは、あつあつの ひなべに かぎります。',
    commonMistakesZh: '「に限って」（偏偏/仅限）形近义远：「寒い日に限って火鍋がない」＝偏偏冷天没火锅。「〜するに限る」前接辞书形，不是た形',
    learnerFocus: '聊天安利自己的最爱时最好用：「疲れたときは甘いものに限る」。比「〜が一番好き」更有人生经验的味道',
    similarPatterns: ['〜が一番だ', '〜に越したことはない'],
    contrast: '「に限る」＝主観の首選断言；「に越したことはない」＝当然そのほうが望ましい；「が一番だ」＝素直な最上級',
    recognition: { promptZh: '想表达「夏天就得吃凉面」，哪句对？',
      options: ['夏は冷たい麺に限る', '夏は冷たい麺に限って', '夏は冷たい麺に限らず', '夏は冷たい麺のに限る'],
      answerIndex: 0, distractorReason: '「に限って」是偏偏、「に限らず」是不限于，接续「のに限る」是错形',
      explanationZh: '主观推荐用「名詞＋に限る」' },
    production: { promptJa: 'あなたの「これが一番！」を「〜に限る」で言ってください。',
      promptZh: '用「〜に限る」安利你心中的最佳选择。',
      expected: ['に限る'], acceptable: ['〜に限ります'] },
    practice: { themeJa: 'マイベストを語る', starterJa: '疲れた日の過ごし方、あなたのおすすめは何ですか？',
      starterZh: '累的日子你最推荐怎么过？', targetUse: '〜に限る' },
    vocabularyLinks: ['fi-taberu', 'fi-neru'] }),
  g({ grammarId: 'n2g-112', pattern: '〜にかけては', reading: 'にかけては', unit: 8, zhSourceRowId: null,
    meaningJa: '〜の分野・技能では（誰にも負けない）',
    explanationZh: '论…、在…方面（数一数二）。用于自信领域的正面评价',
    formation: '名詞／動詞辞書形＋こと ＋にかけては',
    usageScene: '自我推销特长、夸奖同事的拿手绝活',
    nuance: 'プラス評価専用。後半に「一番」「誰にも負けない」「定評がある」が呼応',
    register: 'both',
    sourceExample: src('例文集を作ることにかけては、定評があります。', '65df984babdccadb'),
    examplesJa: ['例文集を作ることにかけては、定評があります。',
                 '料理の速さにかけては、家族の誰にも負けません。'],
    examplesZh: ['论编写例句集，是有口皆碑的。', '论做菜的速度，家里谁都比不过我。'],
    furigana: 'れいぶんしゅうを つくる ことに かけては、ていひょうが あります。',
    commonMistakesZh: '只用于夸（自己或别人）。说弱项「漢字にかけては苦手だ」不成立，要说「漢字については苦手だ」',
    learnerFocus: '面试说强项的高级句式：「データ整理にかけては自信があります」比「得意です」更显专业',
    similarPatterns: ['〜に関しては', '〜において'],
    contrast: '「にかけては」＝得意分野の自負；「に関しては」＝中立の話題提示；「において」＝改まった場・分野の提示',
    recognition: { promptZh: '「暗記にかけては彼の右に出る者はいない」是什么意思？',
      options: ['论背诵没人比得过他', '他不擅长背诵', '他只会背诵别的不行', '他站在别人右边背诵'],
      answerIndex: 0, distractorReason: '「にかけては」＋最高评价＝该领域第一',
      explanationZh: '「右に出る者はいない」是搭配「にかけては」的惯用夸法' },
    production: { promptJa: '自分の得意分野を「〜にかけては」で紹介してください。',
      promptZh: '用「〜にかけては」介绍你的拿手领域。',
      expected: ['にかけては'], acceptable: ['〜ことにかけては'] },
    practice: { themeJa: '得意技を売り込む', starterJa: '「これにかけては負けない」というものはありますか？',
      starterZh: '有没有「论这个我不输任何人」的本领？', targetUse: '〜にかけては' },
    vocabularyLinks: ['fi-jouzu', 'fi-tsukuru'] }),
  g({ grammarId: 'n2g-113', pattern: '〜に決まっている', reading: 'にきまっている', unit: 8, zhSourceRowId: null,
    meaningJa: '絶対に〜だ（話し手の強い確信）',
    explanationZh: '肯定是…、必定…。说话人凭常识或感情做出的强烈断定',
    formation: '動詞・い形容詞普通形／な形容詞・名詞 ＋に決まっている',
    usageScene: '断言不努力就考不上、安慰朋友「肯定没问题」',
    nuance: '根拠は主観・常識。会話的で押しが強い。目上への断定は失礼になりうる',
    register: 'spoken',
    matchKeys: ['に決まって'],
    sourceExample: src('何もせずに試験を受けても、合格できないに決まっています。', '98100133d0713bb1'),
    examplesJa: ['何もせずに試験を受けても、合格できないに決まっています。',
                 '毎日練習すれば、上手になるに決まっています。'],
    examplesZh: ['什么都不做就去考试，肯定考不过。', '每天练习的话，肯定会进步。'],
    furigana: 'なにも せずに しけんを うけても、ごうかく できないに きまって います。',
    commonMistakesZh: '和「ことになっている」（按规定…）完全不同：「会議は9時に決まっている」是「定好了9点」，「9時に始まるに決まっている」是「肯定9点开始」。看前面是名词还是句子',
    learnerFocus: '鼓励朋友时的定番：「大丈夫、受かるに決まってるよ」。中文「肯定行的啦」的语气',
    similarPatterns: ['〜に違いない', '〜はずだ'],
    contrast: '「に決まっている」＝感情混じりの断言（口語）；「に違いない」＝推理による確信（書面寄り）；「はずだ」＝根拠ある推測',
    recognition: { promptZh: '朋友担心考试，想说「你肯定没问题」，哪句最自然？',
      options: ['大丈夫、受かるに決まってるよ', '大丈夫、受かることになってるよ', '大丈夫、受かるところだったよ', '大丈夫、受かるどころではないよ'],
      answerIndex: 0, distractorReason: '「ことになっている」是规定、「ところだった」是差点、「どころではない」是顾不上',
      explanationZh: '给人打气的强断定用「に決まっている」' },
    production: { promptJa: '強い確信を「〜に決まっている」で言ってください。',
      promptZh: '用「〜に決まっている」说一个你笃定的判断。',
      expected: ['に決まって'], acceptable: ['〜に決まっています'] },
    practice: { themeJa: '友達を励ます', starterJa: '不安がっている友達に、自信を持たせる一言をかけてみましょう。',
      starterZh: '朋友没信心时，你会怎么给他打气？', targetUse: '〜に決まっている' },
    vocabularyLinks: ['fi-ganbaru', 'fi-benkyo'] }),
  g({ grammarId: 'n2g-114', pattern: '〜に加えて', reading: 'にくわえて', unit: 8, zhSourceRowId: null,
    meaningJa: '〜だけでなく、さらに',
    explanationZh: '加上…、不仅…而且…。在前项基础上又添加同方向的后项',
    formation: '名詞 ＋に加えて（に加え）',
    usageScene: '说明开销叠加、条件累加、能力多面',
    nuance: '後半に「も」が呼応しやすい。良いこと悪いこと両方の累加に使える',
    register: 'both',
    matchKeys: ['に加えて', 'に加え'],
    sourceExample: src('授業に加えて、自己学習の習慣も大事です。', '3958e7f254e9ad52'),
    examplesJa: ['授業に加えて、自己学習の習慣も大事です。',
                 '家賃に加えて、光熱費もかかります。'],
    examplesZh: ['除了上课，自学的习惯也很重要。', '房租之外，还要花水电煤气费。'],
    furigana: 'じゅぎょうに くわえて、じこがくしゅうの しゅうかんも だいじです。',
    commonMistakesZh: '前接名词：「勉強するに加えて」不自然，要名词化成「勉強に加えて」。中文「除了…还」很容易带出「〜以外に」，两者都对但「に加えて」更书面',
    learnerFocus: '陈述多重理由时的连接词。写申请理由书时「日本語学習に加えて、文化理解も深めたい」很好用',
    similarPatterns: ['〜ばかりか', '〜のみならず'],
    contrast: '「に加えて」＝中立の累加；「ばかりか」＝意外性を強調；「のみならず」＝硬い書面語',
    recognition: { promptZh: '「彼は英語に加えて、中国語も話せる」的意思是？',
      options: ['英语之外还会说中文', '只会英语不会中文', '用英语代替中文', '英语和中文都不会'],
      answerIndex: 0, distractorReason: '「に加えて」表示在前项之上再加后项',
      explanationZh: '前项（英语）成立，又加上后项（中文）' },
    production: { promptJa: '重なっている負担や強みを「〜に加えて」で言ってください。',
      promptZh: '用「〜に加えて」说说叠加的负担或优势。',
      expected: ['に加えて'], acceptable: ['〜に加え'] },
    practice: { themeJa: '重なる事情を説明する', starterJa: '最近、出費や予定が重なったことはありますか？',
      starterZh: '最近有没有开销或安排叠在一起的情况？', targetUse: '〜に加えて' },
    vocabularyLinks: ['fi-okane', 'fi-shuukan'] }),
  g({ grammarId: 'n2g-115', pattern: '〜に越したことはない', reading: 'にこしたことはない', unit: 8, zhSourceRowId: null,
    meaningJa: '〜が一番望ましい（当然そのほうがいい）',
    explanationZh: '最好…、…是再好不过的。承认「理所当然那样更好」的稳妥建议',
    formation: '動詞辞書形／い形容詞／名詞（である） ＋に越したことはない',
    usageScene: '劝人早做准备、承认健康第一、保守的建议',
    nuance: '「まあ当然そうだよね」という常識的な望ましさ。押しつけがましくない',
    register: 'both',
    matchKeys: ['に越したことは'],
    sourceExample: src('どんなにつらいことがあっても、生きているに越したことはないです。', 'cd75502b00c98be0'),
    examplesJa: ['どんなにつらいことがあっても、生きているに越したことはないです。',
                 '準備は早いに越したことはありません。'],
    examplesZh: ['无论多么难受，活着总是最好的。', '准备这种事，越早越好。'],
    furigana: 'どんなに つらい ことが あっても、いきて いるに こしたことは ないです。',
    commonMistakesZh: '不是比较句「AよりBがいい」，而是「（能…的话）当然最好」。常和「用心するに越したことはない」等谨慎类动词搭配',
    learnerFocus: '给建议时比「〜たほうがいい」更委婉成熟：「確認するに越したことはないですよ」不带说教味',
    similarPatterns: ['〜に限る', '〜たほうがいい'],
    contrast: '「に越したことはない」＝当然の望ましさ（控えめ）；「に限る」＝主観の首選（押しが強い）；「たほうがいい」＝直接の助言',
    recognition: { promptZh: '「早めに予約するに越したことはない」的语气是？',
      options: ['能早订当然最好（稳妥建议）', '必须现在马上订', '不订也完全没关系', '已经订完了'],
      answerIndex: 0, distractorReason: '「に越したことはない」是当然更好的温和劝告，不是强制',
      explanationZh: '常识性的「越…越好」' },
    production: { promptJa: '控えめな助言を「〜に越したことはない」で言ってください。',
      promptZh: '用「〜に越したことはない」给一个稳妥的建议。',
      expected: ['に越したことは'], acceptable: ['〜に越したことはありません'] },
    practice: { themeJa: '後輩へ穏やかに助言する', starterJa: '後輩に「早めにやっておくといい」ことを教えるなら何ですか？',
      starterZh: '要提醒后辈「早点做比较好」的事，你会说什么？', targetUse: '〜に越したことはない' },
    vocabularyLinks: ['fi-genki', 'fi-yotei'] }),
  g({ grammarId: 'n2g-116', pattern: '〜に応えて', reading: 'にこたえて', unit: 8, zhSourceRowId: null,
    meaningJa: '〜（期待・要望・声援）にこたえる形で',
    explanationZh: '应…（要求）、不辜负…（期待）。回应他人的期待、要求、声援而行动',
    formation: '名詞（期待・要望・声援・リクエスト） ＋に応えて',
    usageScene: '店铺回应顾客需求、歌手回应粉丝安可、不辜负父母期待',
    nuance: '前に来る名詞はほぼ「期待・要望・声援・リクエスト」系に固定',
    register: 'written',
    matchKeys: ['に応えて'],
    sourceExample: src('お客様の要望に応えて、人気の化粧品を仕入れました。', '7ba10e3d3377ec68'),
    examplesJa: ['お客様の要望に応えて、人気の化粧品を仕入れました。',
                 'ファンの声援に応えて、アンコールを歌いました。'],
    examplesZh: ['应顾客的要求，进了热门化妆品。', '回应粉丝的欢呼，唱了安可曲。'],
    furigana: 'おきゃくさまの ようぼうに こたえて、にんきの けしょうひんを しいれました。',
    commonMistakesZh: '「に応じて」（按…调整）与「に応えて」（回应期待）是本课最易混的一对：「レベルに応じて」按水平调整／「期待に応えて」不辜负期待。前接名词的类型完全不同',
    learnerFocus: '中文「不辜负」的正面语感与「に応えて」完全对应。写自我介绍「親の期待に応えて留学を決めた」很自然',
    similarPatterns: ['〜に応じて', '〜に沿って'],
    contrast: '「に応えて」＝期待・要望への回応；「に応じて」＝違いへの調整；「に沿って」＝方針・希望からずれない',
    recognition: { promptZh: '哪个搭配是对的？',
      options: ['アンケートの声に応えてメニューを増やした', '天気に応えて傘を持った', '身長に応えて席を決めた', '年齢に応えて料金が変わる'],
      answerIndex: 0, distractorReason: '其余三项是按条件调整，应该用「に応じて」',
      explanationZh: '「に応えて」前面只放期待・要望・声援类名词' },
    production: { promptJa: '誰かの期待にこたえた経験を「〜に応えて」で言ってください。',
      promptZh: '用「〜に応えて」说一次回应他人期待的经历。',
      expected: ['に応えて'], acceptable: ['〜の期待に応えて'] },
    practice: { themeJa: '期待にこたえた話をする', starterJa: '家族や友達の期待にこたえられた経験はありますか？',
      starterZh: '有过不辜负家人朋友期待的经历吗？', targetUse: '〜に応えて' },
    vocabularyLinks: ['fi-kimochi', 'fi-kau'] }),
  g({ grammarId: 'n2g-117', pattern: '〜に際して', reading: 'にさいして', unit: 8, zhSourceRowId: null,
    meaningJa: '〜するとき（改まった手続き・案内の場面で）',
    explanationZh: '在…之际、当…之时（正式）。多见于手续说明、规章、通知文',
    formation: '動詞辞書形／名詞 ＋に際して（に際し）',
    usageScene: '报名须知、使用条款、开通服务时的说明文',
    nuance: '案内文・規約の定型。日常会話では「〜とき」で十分',
    register: 'written',
    sourceExample: src('お申し込みに際して、ネットで手続きが可能です。', '47397a82decff056'),
    examplesJa: ['お申し込みに際して、ネットで手続きが可能です。',
                 'ご利用に際して、注意事項をお読みください。'],
    examplesZh: ['申请时，可以在网上办理手续。', '使用前，请阅读注意事项。'],
    furigana: 'おもうしこみに さいして、ネットで てつづきが かのうです。',
    commonMistakesZh: '「にあたって」（节点的郑重表态）与「に際して」（手续场面的公文体）方向不同：致辞用「にあたって」，须知用「に際して」。聊天里说「食事に際して」会显得像机器人',
    learnerFocus: '看懂日本的报名页面、合同条款的关键词。见到「〜に際して」就知道后面是注意事项',
    similarPatterns: ['〜にあたって', '〜の際は'],
    contrast: '「に際して」＝手続き・案内の公文体；「にあたって」＝節目の改まった表明；「の際は」＝案内掲示の軽い定型',
    recognition: { promptZh: '「ご搭乗に際して」最可能出现在哪里？',
      options: ['机场的登机须知', '朋友间的聊天', '给家人的微信', '菜谱的步骤说明'],
      answerIndex: 0, distractorReason: '「に際して」是正式手续文体，不用于私人对话',
      explanationZh: '公告・须知类文体的标志' },
    production: { promptJa: '手続きの案内文を「〜に際して」で作ってください。',
      promptZh: '用「〜に際して」写一句手续说明。',
      expected: ['に際して'], acceptable: ['〜に際し'] },
    practice: { themeJa: '案内文を読める・作れる', starterJa: '申込ページの注意書きを、丁寧な一文で作ってみましょう。',
      starterZh: '试着写一句报名页面的注意说明。', targetUse: '〜に際して' },
    vocabularyLinks: ['fi-kakunin', 'fi-yomu'] }),
  g({ grammarId: 'n2g-118', pattern: '〜に先立って', reading: 'にさきだって', unit: 8, zhSourceRowId: null,
    meaningJa: '〜の前に（本番に先行して準備を行う）',
    explanationZh: '在…之前（先行做…）。正式活动前的先行安排',
    formation: '動詞辞書形／名詞 ＋に先立って（に先立ち）',
    usageScene: '公映前的试映会、开业前的内览会、会议前的资料分发',
    nuance: '単なる時間の前後ではなく「本番のための先行準備」。式典・告知文で多用',
    register: 'written',
    matchKeys: ['に先立って', 'に先立ち'],
    sourceExample: src('映画の一般公開に先立って、試写会を行う予定です。', 'c279e8fcc4c69949'),
    examplesJa: ['映画の一般公開に先立って、試写会を行う予定です。',
                 '開店に先立って、スタッフ全員で最終確認をしました。'],
    examplesZh: ['在电影公映之前，计划先办试映会。', '开店之前，全体员工做了最后确认。'],
    furigana: 'えいがの いっぱんこうかいに さきだって、ししゃかいを おこなう よていです。',
    commonMistakesZh: '和「〜前に」的区别：吃饭前洗手这种日常顺序用「前に」。「に先立って」要有正式的「本番」，前面是大事，后面是它的先行环节',
    learnerFocus: '新闻和公司通知的常客：「発売に先立って予約を受け付ける」。看懂它，商业资讯不再卡壳',
    similarPatterns: ['〜前に', '〜にあたって'],
    contrast: '「に先立って」＝本番前の先行準備（硬い）；「前に」＝日常の時間順序；「にあたって」＝節目そのものへの姿勢',
    recognition: { promptZh: '「発売に先立って、体験会を開いた」的顺序是？',
      options: ['先办体验会，之后才发售', '先发售，之后办体验会', '同时进行', '都没有举行'],
      answerIndex: 0, distractorReason: '「Aに先立ってB」＝B先行、A在后',
      explanationZh: '「に先立って」后项先行于前项大事' },
    production: { promptJa: '本番前の準備を「〜に先立って」で言ってください。',
      promptZh: '用「〜に先立って」说一件正式活动前的先行准备。',
      expected: ['に先立'], acceptable: ['〜に先立ち'] },
    practice: { themeJa: '式・発表前の段取りを話す', starterJa: '大事な本番の前に、必ずやっておくことはありますか？',
      starterZh: '重要活动之前，你一定会先做什么？', targetUse: '〜に先立って' },
    vocabularyLinks: ['fi-miru', 'fi-kakunin'] }),
  g({ grammarId: 'n2g-119', pattern: '〜に従って', reading: 'にしたがって', unit: 8, zhSourceRowId: null,
    meaningJa: '〜のとおりに／〜が進むにつれて',
    explanationZh: '按照…；随着…。①遵照指示规则 ②随前项变化后项也变化',
    formation: '名詞／動詞辞書形 ＋に従って（に従い）',
    usageScene: '按说明书操作、按指示行动；北上气温渐低等渐变描述',
    nuance: '①指示・規則遵守 ②連動変化の二用法。②は「につれて」と交換可',
    register: 'both',
    matchKeys: ['に従って', 'に従い'],
    sourceExample: src('例文集マニュアルに従って、読む練習を毎日繰り返せば、話せるようになります。', 'c397b6d37d602494'),
    examplesJa: ['例文集マニュアルに従って、読む練習を毎日繰り返せば、話せるようになります。',
                 '北へ行くに従って、気温が下がっていきます。'],
    examplesZh: ['按照例句集手册每天反复朗读练习，就能开口说了。', '越往北走，气温越低。'],
    furigana: 'れいぶんしゅう マニュアルに したがって、よむ れんしゅうを まいにち くりかえせば、はなせる ように なります。',
    commonMistakesZh: '变化用法可换「につれて」，但遵守用法不行：「先生の指示につれて」是错句。前面是「指示・規則・マニュアル」时只能用「に従って」',
    learnerFocus: '一个词打通「按照」和「随着」两个中文词。先判断前项是规则还是变化，再定用法',
    similarPatterns: ['〜につれて', '〜に沿って'],
    contrast: '「に従って」＝遵守＋連動の二用法；「につれて」＝連動変化のみ；「に沿って」＝方針からずれない',
    recognition: { promptZh: '哪句的「に従って」不能换成「につれて」？',
      options: ['説明書に従って組み立てた', '年を取るに従って体力が落ちる', '暗くなるに従って気温が下がる', '慣れるに従って速くなる'],
      answerIndex: 0, distractorReason: '遵守指示的用法是「に従って」专属，其余三项是连动变化可以互换',
      explanationZh: '前项是「説明書」＝遵守用法，不能换' },
    production: { promptJa: 'ルールに沿った行動を「〜に従って」で言ってください。',
      promptZh: '用「〜に従って」说一件按规则做的事。',
      expected: ['に従'], acceptable: ['〜に従い'] },
    practice: { themeJa: '手順どおりに説明する', starterJa: '何かをマニュアルどおりにやって、うまくいった経験はありますか？',
      starterZh: '有没有按手册一步步做而成功的经历？', targetUse: '〜に従って' },
    vocabularyLinks: ['fi-tsuzukeru', 'fi-hanasu'] }),
  g({ grammarId: 'n2g-120', pattern: '〜にしたら', reading: 'にしたら', unit: 8, zhSourceRowId: null,
    meaningJa: '〜の立場から見れば',
    explanationZh: '在…看来、对…来说（设身处地）。站在他人立场推测其感受',
    formation: '名詞（人・立場） ＋にしたら（にすれば・にしてみれば）',
    usageScene: '体谅父母的担心、理解孩子的视角、揣摩对方难处',
    nuance: '人の心情を思いやる推測。自分のことには使わない',
    register: 'spoken',
    matchKeys: ['にしたら', 'にすれば', 'にしてみれば'],
    sourceExample: src('子供の立場にしたら、この社会情勢は複雑で理解できないです。', '77347067de2a517d'),
    examplesJa: ['子供の立場にしたら、この社会情勢は複雑で理解できないです。',
                 '親にしたら、子供の一人暮らしは心配なものです。'],
    examplesZh: ['站在孩子的立场，这种社会形势复杂得难以理解。', '在父母看来，孩子独自生活总是让人担心的。'],
    furigana: 'こどもの たちばに したら、この しゃかいじょうせいは ふくざつで りかい できないです。',
    commonMistakesZh: '主语必须是「别人」：「私にしたら」谈自己的感想不自然，说「私としては」。前面基本只接人・立场名词，物用「にとって」',
    learnerFocus: '表达同理心的关键句式：「あなたにしてみれば大変でしたよね」。吵架降温、安慰人都靠它',
    similarPatterns: ['〜にとって', '〜として'],
    contrast: '「にしたら」＝他者の立場に立つ想像；「にとって」＝評価の基準（人にも物にも）；「として」＝資格・役割',
    recognition: { promptZh: '「彼にしたら、その注意はショックだったはずだ」的视角是？',
      options: ['站在他的立场推测他的感受', '说话人自己受了打击', '他毫不在意', '注意的内容是错的'],
      answerIndex: 0, distractorReason: '「にしたら」＝设身处地推测他人心情',
      explanationZh: '为他人着想的推测表达' },
    production: { promptJa: '相手の立場に立った推測を「〜にしたら」で言ってください。',
      promptZh: '用「〜にしたら」站在别人的角度说说他的感受。',
      expected: ['にしたら'], acceptable: ['〜にすれば', '〜にしてみれば'] },
    practice: { themeJa: '相手の気持ちを思いやる', starterJa: '家族はあなたの留学をどう感じていると思いますか？',
      starterZh: '你觉得家人是怎么看你留学这件事的？', targetUse: '〜にしたら' },
    vocabularyLinks: ['fi-kazoku', 'fi-kangaeru'] }),
];
