// Phase 3P-5: N2文法完成draft Unit 9（No.121〜135の15文型）。
// rightsStatus: teacher_created_confirmed。第1例文=原本（無改変）、第2例文=独自（実生活）。
import type { N2GrammarDraft } from './n2GrammarDrafts';

const g = (p: Omit<N2GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey' | 'runtimeExampleOrigin'> & { reviewKey?: string; runtimeExampleOrigin?: N2GrammarDraft['runtimeExampleOrigin'] }): N2GrammarDraft =>
  ({ level: 'N2', route: 'n2-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, runtimeExampleOrigin: 'source_confirmed', ...p });

const src = (text: string, hash: string) =>
  ({ text, hash, rightsStatus: 'teacher_created_confirmed' as const });

export const N2_GRAMMAR_DRAFTS_UNIT9: N2GrammarDraft[] = [
  g({ grammarId: 'n2g-121', pattern: '〜にしては', reading: 'にしては', unit: 9, zhSourceRowId: 'n3row-97',
    meaningJa: '〜という前提から予想されることと違って',
    explanationZh: '照理说…却、就…而言（出乎意料地）。以前项属性为基准，后项却偏离常识预期',
    formation: '動詞普通形／名詞 ＋にしては',
    usageScene: '夸新手做得好、说某人不像其年龄、评价与身份不符的表现',
    nuance: '前提と実態のギャップが核。ほめにもけなしにも使う',
    register: 'both',
    sourceExample: src('素人にしては、絵を描くのがうますぎます。', 'e099a9cfa16ceaa3'),
    examplesJa: ['素人にしては、絵を描くのがうますぎます。',
                 '初めてにしては、上手にできましたね。'],
    examplesZh: ['作为外行来说，画画得太好了。', '第一次能做成这样，很不错了。'],
    furigana: 'しろうとに しては、えを かくのが うますぎます。',
    commonMistakesZh: '必须有「不符预期」的落差：「学生にしては勉強ができる」不成立（学生会学习是理所当然）。和「として」（作为…的身份）完全不同',
    learnerFocus: '中文「就…而言算不错了」的微妙让步。夸人时注意：「日本人にしては」这类话可能失礼，先想清预设',
    similarPatterns: ['〜わりには', '〜として'],
    contrast: '「にしては」＝具体的な前提とのギャップ；「わりには」＝程度との不釣り合い（前提があいまいでも可）；「として」＝資格・立場そのもの',
    recognition: { promptZh: '哪句的「にしては」用得自然？',
      options: ['新人にしては、落ち着いています', '学生にしては、学校に通っています', '冬にしては、12月です', '日本人にしては、日本語を話します'],
      answerIndex: 0, distractorReason: '其余三项的后项都是前提的当然结果，没有落差',
      explanationZh: '「にしては」需要前提与实际的反差' },
    production: { promptJa: '予想外の上手さを「〜にしては」でほめてください。',
      promptZh: '用「〜にしては」夸一个超出预期的表现。',
      expected: ['にしては'], acceptable: ['初めてにしては'] },
    practice: { themeJa: '意外な一面をほめる', starterJa: '周りの人の「意外な特技」を見つけたことはありますか？',
      starterZh: '你发现过身边人「意想不到的本领」吗？', targetUse: '〜にしては' },
    vocabularyLinks: ['fi-jouzu', 'fi-kaku'] }),
  g({ grammarId: 'n2g-122', pattern: '〜にしても', reading: 'にしても', unit: 9, zhSourceRowId: 'n3row-98',
    meaningJa: 'たとえ〜だとしても／〜の場合でも',
    explanationZh: '即使…也、就算…也。让步假定：即便承认前项，后项的主张仍然成立',
    formation: '動詞・い形容詞普通形／な形容詞・名詞 ＋にしても',
    usageScene: '就算不去也该回个话、无论选哪个都要先做决定',
    nuance: '「いずれにしても」（いずれ＝どちら）は「不管怎样」の定型句',
    register: 'both',
    sourceExample: src('いずれにしても、そろそろ旅行に行くか行かないか決めなければいけません。', '469d639c390a6651'),
    examplesJa: ['いずれにしても、そろそろ旅行に行くか行かないか決めなければいけません。',
                 '忙しいにしても、返事ぐらいはできるはずです。'],
    examplesZh: ['不管怎样，差不多该决定去不去旅行了。', '就算再忙，回个话总是可以的吧。'],
    furigana: 'いずれに しても、そろそろ りょこうに いくか いかないか きめなければ いけません。',
    commonMistakesZh: '「にしても」带轻微不满或让步语气，客观陈述用「ても」即可。「AにしてもBにしても」＝无论A还是B，两个都要提',
    learnerFocus: '会话万能句「いずれにしても」（反正、总之）先背下来。转向结论时一句救场',
    similarPatterns: ['たとえ〜ても', '〜としても'],
    contrast: '「にしても」＝譲歩＋話し手の含み（不満・驚き）；「としても」＝仮定の論理展開；「ても」＝中立の逆接',
    recognition: { promptZh: '「行けないにしても、連絡はしてほしい」的语气是？',
      options: ['就算去不了，至少希望联系一下', '因为去不了，所以干脆不要联系了', '只有去得了的时候才需要联系一下', '在这之前就已经跟对方联系过一次了'],
      answerIndex: 0, distractorReason: '「にしても」是让步：承认前项，仍提出最低限度的要求',
      explanationZh: '让步＋「至少要…」的期待' },
    production: { promptJa: '最低限のお願いを「〜にしても」で言ってください。',
      promptZh: '用「〜にしても」提一个「就算…至少也…」的请求。',
      expected: ['にしても'], acceptable: ['いずれにしても'] },
    practice: { themeJa: '譲歩しつつ主張する', starterJa: '「就算…也至少…」と言いたくなった場面はありますか？',
      starterZh: '有没有想说「就算…至少也…」的时候？', targetUse: '〜にしても' },
    vocabularyLinks: ['fi-kimeru', 'fi-renraku'] }),
  g({ grammarId: 'n2g-123', pattern: '〜に過ぎない', reading: 'にすぎない', unit: 9, zhSourceRowId: null,
    meaningJa: 'ただ〜であるだけだ（それ以上ではない）',
    explanationZh: '只不过是…而已。把事物的价值、程度往小里说的谦逊或冷静评价',
    formation: '動詞普通形／名詞 ＋に過ぎない',
    usageScene: '谦虚回应夸奖、冷静指出「只是开始」、淡化个人意见',
    nuance: '矮小化・限定の響き。誇張を抑えて客観的に聞こえる',
    register: 'both',
    matchKeys: ['に過ぎない', 'に過ぎません', 'に過ぎ'],
    sourceExample: src('宇宙の大きさから見れば、小さな悩みに過ぎないです。', 'd15b7de1ab042d98'),
    examplesJa: ['宇宙の大きさから見れば、小さな悩みに過ぎないです。',
                 'それは私の個人的な意見に過ぎません。'],
    examplesZh: ['从宇宙的尺度来看，这不过是小小的烦恼而已。', '那只不过是我的个人意见。'],
    furigana: 'うちゅうの おおきさから みれば、ちいさな なやみに すぎないです。',
    commonMistakesZh: '方向是「往小说」：夸自己的成果时用会显得别扭。「合格は通過点に過ぎない」是自我鞭策的谦逊，不是骄傲',
    learnerFocus: '发表意见时的缓冲垫：「一つの案に過ぎませんが…」。降低对抗感，日式沟通的润滑剂',
    similarPatterns: ['〜だけだ', '〜にほかならない'],
    contrast: '「に過ぎない」＝小さく見積もる；「にほかならない」＝まさにそれだと高く断定。方向が正反対',
    recognition: { promptZh: '「これは始まりに過ぎない」想表达什么？',
      options: ['这只是开始（不止于此）', '这已经是最后的终点，结束了', '这根本算不上开始', '全部都已经结束了'],
      answerIndex: 0, distractorReason: '「に過ぎない」＝仅仅是，暗示不止于此',
      explanationZh: '把现状定位为「仅仅是…」' },
    production: { promptJa: '謙遜の一言を「〜に過ぎない」で言ってください。',
      promptZh: '用「〜に過ぎない」谦虚地回应一句夸奖。',
      expected: ['に過ぎ'], acceptable: ['〜に過ぎません'] },
    practice: { themeJa: '謙遜しながら意見を言う', starterJa: 'ほめられたとき、謙遜してどう返しますか？',
      starterZh: '被夸奖时，你会怎么谦虚地回应？', targetUse: '〜に過ぎない' },
    vocabularyLinks: ['fi-iken', 'fi-chiisai'] }),
  g({ grammarId: 'n2g-124', pattern: '〜に相違ない', reading: 'にそういない', unit: 9, zhSourceRowId: null,
    meaningJa: '〜に間違いない（改まった確信）',
    explanationZh: '必定是…、无疑是…。书面语的强确信推断，多见于报告、推理文',
    formation: '動詞・い形容詞普通形／な形容詞・名詞 ＋に相違ない',
    usageScene: '书面报告下结论、推理小说断案、确认文件真伪',
    nuance: '「に違いない」の文語版。会話で使うと芝居がかって聞こえる',
    register: 'written',
    matchKeys: ['に相違ない', 'に相違ありません', 'に相違'],
    sourceExample: src('両親はどちらもO型なので、私の血液型はO型に相違ないです。', 'bd83c79425ffb494'),
    examplesJa: ['両親はどちらもO型なので、私の血液型はO型に相違ないです。',
                 'この署名は本人のものに相違ありません。'],
    examplesZh: ['父母都是O型血，所以我的血型无疑是O型。', '这个签名无疑是本人的。'],
    furigana: 'りょうしんは どちらも オーがたなので、わたしの けつえきがたは オーがたに そういないです。',
    commonMistakesZh: '「相違ありません」是窗口、合同确认的定型句（「以上の内容に相違ありません」＝内容属实）。日常聊天说「雨が降るに相違ない」会像old侦探',
    learnerFocus: '办手续签字前常见「記載内容に相違ないことを確認しました」。看懂它才能放心签名',
    similarPatterns: ['〜に違いない', '〜に決まっている'],
    contrast: '「に相違ない」＝文書・改まった確信；「に違いない」＝一般的な確信推量；「に決まっている」＝口語の感情的断定',
    recognition: { promptZh: '「記載内容に相違ありません」最可能出现在哪里？',
      options: ['申请表格的确认栏', '朋友的闲聊', '给孩子的留言', '菜谱说明'],
      answerIndex: 0, distractorReason: '「相違ありません」是文书确认的定型表达',
      explanationZh: '正式文书中「内容属实」的固定说法' },
    production: { promptJa: '書類確認の定型文を「〜に相違ない」で言ってください。',
      promptZh: '用「〜に相違ない」说一句文件确认用语。',
      expected: ['に相違'], acceptable: ['相違ありません'] },
    practice: { themeJa: '書類の確認表現を身につける', starterJa: '申込書の最後にある確認文を読んで、意味を説明してみましょう。',
      starterZh: '试着解释申请表最后确认栏的意思。', targetUse: '〜に相違ない' },
    vocabularyLinks: ['fi-kakunin', 'fi-kazoku'] }),
  g({ grammarId: 'n2g-125', pattern: '〜に沿って', reading: 'にそって', unit: 9, zhSourceRowId: null,
    meaningJa: '〜から離れないように（物理的・方針的に）',
    explanationZh: '沿着…；按照…（不偏离）。①沿河沿路 ②遵循方针、计划、希望',
    formation: '名詞 ＋に沿って（に沿った＋名詞）',
    usageScene: '沿着河边散步的描述、按计划推进、按客户希望提案',
    nuance: '「線・流れからずれない」イメージ。抽象用法は方針・計画・期待と相性良',
    register: 'both',
    sourceExample: src('この計画に沿って、勉強をすれば、絶対大丈夫です。', 'd78d7f4940988a25'),
    examplesJa: ['この計画に沿って、勉強をすれば、絶対大丈夫です。',
                 '川に沿って、桜の木が植えられています。'],
    examplesZh: ['只要按这个计划学习，绝对没问题。', '沿着河边种着一排樱花树。'],
    furigana: 'この けいかくに そって、べんきょうを すれば、ぜったい だいじょうぶです。',
    commonMistakesZh: '抽象用法的前项是「计划・方针・希望・主题」等线状概念。「先生に沿って勉強する」不行，人要用「に従って」',
    learnerFocus: '汇报进度的靠谱句式：「計画に沿って進んでいます」。让上司安心的一句话',
    similarPatterns: ['〜に従って', '〜に基づいて'],
    contrast: '「に沿って」＝線・方針からずれない；「に従って」＝指示に服従／連動変化；「に基づいて」＝土台・根拠の上に立つ',
    recognition: { promptZh: '「お客様のご希望に沿ったプランをご提案します」的意思是？',
      options: ['提出符合客户希望的方案', '提出完全无视客户希望的方案', '希望客户接受任意一个方案', '让客户沿着这条路一直往前走'],
      answerIndex: 0, distractorReason: '「希望に沿う」＝不偏离对方希望',
      explanationZh: '抽象的「沿着」＝贴合、不偏离' },
    production: { promptJa: '計画どおりの進行を「〜に沿って」で報告してください。',
      promptZh: '用「〜に沿って」汇报按计划进行的状况。',
      expected: ['に沿って'], acceptable: ['〜に沿った'] },
    practice: { themeJa: '進捗を安心感を持って伝える', starterJa: '今の学習は、立てた計画に沿って進んでいますか？',
      starterZh: '你现在的学习按当初的计划进行着吗？', targetUse: '〜に沿って' },
    vocabularyLinks: ['fi-benkyo', 'fi-iku'] }),
  g({ grammarId: 'n2g-126', pattern: '〜に違いない', reading: 'にちがいない', unit: 9, zhSourceRowId: 'n3row-101',
    meaningJa: 'きっと〜だ（根拠のある強い推量）',
    explanationZh: '一定是…。基于线索或情理做出的高确信度推测',
    formation: '動詞・い形容詞普通形／な形容詞・名詞 ＋に違いない',
    usageScene: '看到灯亮推断人还在、根据实力推断能合格',
    nuance: '推理の響き。断定はしないが確信は強い',
    register: 'both',
    matchKeys: ['に違いな'],
    sourceExample: src('今の実力であれば合格するに違いないです。', '0c9b167af17e789f'),
    examplesJa: ['今の実力であれば合格するに違いないです。',
                 '電気がついているから、まだ会社にいるに違いない。'],
    examplesZh: ['凭现在的实力，一定能合格。', '灯还亮着，人一定还在公司。'],
    furigana: 'いまの じつりょくで あれば ごうかくするに ちがいないです。',
    commonMistakesZh: '三兄弟排序：「はずだ」（合理推断）＜「に違いない」（强确信）＜「に決まっている」（感情断定・口语）。书面推理选「に違いない」最安全',
    learnerFocus: '中文「肯定是」的标准对应。读小说、看剧的心理描写高频词，先认识再会用',
    similarPatterns: ['〜はずだ', '〜に決まっている'],
    contrast: '「に違いない」＝根拠→強い確信；「はずだ」＝理屈上そうなる；「に決まっている」＝感情的な押しの断定',
    recognition: { promptZh: '「かばんがない。教室に忘れたに違いない」的确信来源是？',
      options: ['根据线索（包不见了）的推断', '自己亲眼看到包就放在教室里面', '毫无根据的乱猜', '别人告诉他的事实'],
      answerIndex: 0, distractorReason: '「に違いない」是有线索但未确认的强推测',
      explanationZh: '线索→高确信推理' },
    production: { promptJa: '手がかりからの推理を「〜に違いない」で言ってください。',
      promptZh: '用「〜に違いない」根据线索做一个推理。',
      expected: ['に違いな'], acceptable: ['〜に違いありません'] },
    practice: { themeJa: '状況から推理する', starterJa: '友達が最近楽しそうです。何かあったと思いますか？',
      starterZh: '朋友最近很开心，你猜发生了什么？', targetUse: '〜に違いない' },
    vocabularyLinks: ['fi-shigoto', 'fi-wakaru'] }),
  g({ grammarId: 'n2g-127', pattern: '〜につき', reading: 'につき', unit: 9, zhSourceRowId: null,
    meaningJa: '〜ごとに／〜のため（掲示・案内で）',
    explanationZh: '每…；因…（公告体）。①单位换算（每人每件）②告示中的理由说明',
    formation: '名詞 ＋につき',
    usageScene: '价目表（每人500日元）、告示（因施工暂停）、师生配比说明',
    nuance: '①1人につき＝配分 ②雨天につき中止＝掲示の理由。どちらも硬い書面',
    register: 'written',
    sourceExample: src('オンライン授業では1人から3人につき、1人の先生が担当します。', '2f44eaaf785f19d3'),
    examplesJa: ['オンライン授業では1人から3人につき、1人の先生が担当します。',
                 '工事中につき、通り抜けはご遠慮ください。'],
    examplesZh: ['线上课程每1到3名学生，配一名老师负责。', '施工期间，请勿穿行。'],
    furigana: 'オンライン じゅぎょうでは ひとりから さんにんに つき、ひとりの せんせいが たんとうします。',
    commonMistakesZh: '理由用法只出现在告示・通知里：口语说「風邪につき休みます」很生硬，说「風邪なので」。换算用法「1個につき100円」=每个100日元',
    learnerFocus: '在日本看懂门口贴纸的关键：「本日貸切につき」「定休日につき」。旅游点餐、逛街全用得上',
    similarPatterns: ['〜あたり', '〜のため'],
    contrast: '「につき」＝掲示の理由／単位配分；「あたり」＝平均・単位の計算；「のため」＝理由の一般形',
    recognition: { promptZh: '门上贴着「改装中につき休業」，意思是？',
      options: ['因装修暂停营业', '装修完毕重新开业', '每次装修都营业', '装修期间照常营业'],
      answerIndex: 0, distractorReason: '「〜につき」在告示中＝因…的理由说明',
      explanationZh: '掲示の「因…」＝につき' },
    production: { promptJa: 'お知らせの掲示文を「〜につき」で作ってください。',
      promptZh: '用「〜につき」写一句告示。',
      expected: ['につき'], acceptable: ['〜中につき'] },
    practice: { themeJa: '掲示文を読める・作れる', starterJa: '店の入口に貼る「お休みのお知らせ」を書いてみましょう。',
      starterZh: '试着写一张店门口的停业告示。', targetUse: '〜につき' },
    vocabularyLinks: ['fi-sensei', 'fi-setsumei'] }),
  g({ grammarId: 'n2g-128', pattern: '〜につけ', reading: 'につけ', unit: 9, zhSourceRowId: null,
    meaningJa: '〜するたびに自然と（感情がわく）／〜でも〜でも',
    explanationZh: '每当…就（不由得）…；无论…还是…。后项多是自然涌起的情感',
    formation: '動詞辞書形／対の語（雨につけ雪につけ） ＋につけ',
    usageScene: '每当听到这首歌就想家、无论晴雨都坚持的习惯',
    nuance: '後半は「思い出す・感じる」等の自発的感情。意志的行動は不自然',
    register: 'written',
    sourceExample: src('雨につけ、雪につけ、毎日散歩をすることは日課です。', 'fce880e81f4a2245'),
    examplesJa: ['雨につけ、雪につけ、毎日散歩をすることは日課です。',
                 'この歌を聞くにつけ、故郷を思い出します。'],
    examplesZh: ['无论下雨还是下雪，每天散步是日课。', '每当听到这首歌，就想起故乡。'],
    furigana: 'あめに つけ、ゆきに つけ、まいにち さんぽを することは にっかです。',
    commonMistakesZh: '「聞くにつけ勉強する」（每听就学习）不自然——后项要的是情感不是行动。表行动的「每当」用「たびに」',
    learnerFocus: '「何かにつけ」（动不动就…）是好用的固定短语：「彼は何かにつけ文句を言う」',
    similarPatterns: ['〜たびに', '〜と'],
    contrast: '「につけ」＝自然にわく感情（書面）；「たびに」＝毎回の反復（中立）；「と」＝条件反射的な連動',
    recognition: { promptZh: '哪句的「につけ」用得自然？',
      options: ['写真を見るにつけ、当時を思い出す', '写真を見るにつけ、掃除をする', '写真を見るにつけ、電話をかける', '写真を見るにつけ、買い物に行く'],
      answerIndex: 0, distractorReason: '后项须是自然涌现的情感，其余都是意志性行动',
      explanationZh: '「につけ」＋思い出す・感じる类' },
    production: { promptJa: '思い出がよみがえる瞬間を「〜につけ」で言ってください。',
      promptZh: '用「〜につけ」说一个触景生情的瞬间。',
      expected: ['につけ'], acceptable: ['〜を見るにつけ'] },
    practice: { themeJa: '故郷や思い出を語る', starterJa: '何を見ると（聞くと）、故郷を思い出しますか？',
      starterZh: '看到（听到）什么会让你想起故乡？', targetUse: '〜につけ' },
    vocabularyLinks: ['fi-kiku', 'fi-kimochi'] }),
  g({ grammarId: 'n2g-129', pattern: '〜に伴って', reading: 'にともなって', unit: 9, zhSourceRowId: null,
    meaningJa: '〜という変化・出来事と一緒に',
    explanationZh: '随着…、伴随…。前项的大变化带动后项变化，或大事件附带的手续',
    formation: '名詞／動詞辞書形＋の ＋に伴って（に伴い）',
    usageScene: '科技普及带来的变化、搬家伴随的手续、升职伴随的责任',
    nuance: '規模の大きい変化・出来事向き。日常の小さな連動には大げさ',
    register: 'written',
    matchKeys: ['に伴っ', 'に伴い'],
    sourceExample: src('SNSやオンラインの普及に伴って、授業がやりやすくなりました。', '19eba0360cd99bc8'),
    examplesJa: ['SNSやオンラインの普及に伴って、授業がやりやすくなりました。',
                 '引っ越しに伴って、住所変更の手続きをしました。'],
    examplesZh: ['随着社交媒体和线上化的普及，授课变得容易了。', '伴随搬家，办理了地址变更手续。'],
    furigana: 'エスエヌエスや オンラインの ふきゅうに ともなって、じゅぎょうが やりやすく なりました。',
    commonMistakesZh: '「歩くに伴って疲れる」这类小事不用。前项要够大：普及・成長・発展・引っ越し・転職。新闻高频词',
    learnerFocus: '写变化类小作文的加分词：「経済の発展に伴って生活が便利になった」比「〜ので」高一档',
    similarPatterns: ['〜につれて', '〜とともに'],
    contrast: '「に伴って」＝大きな変化・出来事に付随；「につれて」＝連続的な連動変化；「とともに」＝同時性の並記',
    recognition: { promptZh: '「昇進に伴って、責任も重くなった」的关系是？',
      options: ['升职带来了责任加重', '因为责任重所以升职', '升职和责任无关', '拒绝了升职'],
      answerIndex: 0, distractorReason: '「に伴って」＝前项变化附带后项变化',
      explanationZh: '大变化＋随之而来的变化' },
    production: { promptJa: '大きな変化に伴う変化を「〜に伴って」で言ってください。',
      promptZh: '用「〜に伴って」描述一个大变化带来的连锁变化。',
      expected: ['に伴'], acceptable: ['〜に伴い'] },
    practice: { themeJa: '時代の変化を語る', starterJa: 'ここ数年で、生活はどう変わりましたか？きっかけは？',
      starterZh: '这几年你的生活因为什么发生了变化？', targetUse: '〜に伴って' },
    vocabularyLinks: ['fi-kawaru', 'fi-benri'] }),
  g({ grammarId: 'n2g-130', pattern: '〜に反して', reading: 'にはんして', unit: 9, zhSourceRowId: null,
    meaningJa: '〜（予想・期待）とは逆に',
    explanationZh: '与…相反。结果和预想、期待、意愿背道而驰',
    formation: '名詞（予想・期待・意志・命令） ＋に反して（に反する＋名詞）',
    usageScene: '结果出乎预料、违背父母期待的人生选择',
    nuance: '前に来る名詞は予想・期待・意向・規則系にほぼ固定',
    register: 'written',
    matchKeys: ['に反し', 'に反する'],
    sourceExample: src('親の期待に反して、就職をせずに日本に行くことになりました。', '701b88a359c78e0a'),
    examplesJa: ['親の期待に反して、就職をせずに日本に行くことになりました。',
                 '予想に反して、試合はあっさり終わりました。'],
    examplesZh: ['违背父母的期待，没有就业而是去了日本。', '与预想相反，比赛轻易就结束了。'],
    furigana: 'おやの きたいに はんして、しゅうしょくを せずに にほんに いく ことに なりました。',
    commonMistakesZh: '前项名词有限制：「天気に反して」不行（天气不是预想类名词），要说「天気予報に反して」。任意逆接用「のに」',
    learnerFocus: '讲自己人生选择的戏剧性转折：「周囲の反対に反して留学を決めた」。故事感立刻出来',
    similarPatterns: ['〜にもかかわらず', '〜と反対に'],
    contrast: '「に反して」＝予想・期待の逆の結果；「にもかかわらず」＝条件をものともしない逆接；「と反対に」＝単純な方向の対比',
    recognition: { promptZh: '「大方の予想に反して、新人が優勝した」的意思是？',
      options: ['出乎多数人预料，新人夺冠了', '正如大家所预料的，新人夺冠了', '新人正如大家预期的那样落败了', '那一场比赛因为下雨被取消掉了'],
      answerIndex: 0, distractorReason: '「予想に反して」＝结果与预想相反',
      explanationZh: '预想⇔结果的反转' },
    production: { promptJa: '予想と逆だった出来事を「〜に反して」で言ってください。',
      promptZh: '用「〜に反して」说一件与预想相反的事。',
      expected: ['に反し'], acceptable: ['予想に反して'] },
    practice: { themeJa: '人生の意外な展開を話す', starterJa: '周りの予想と違う道を選んだことはありますか？',
      starterZh: '你做过和周围人预想不同的选择吗？', targetUse: '〜に反して' },
    vocabularyLinks: ['fi-yotei', 'fi-owaru'] }),
  g({ grammarId: 'n2g-131', pattern: '〜にほかならない', reading: 'にほかならない', unit: 9, zhSourceRowId: null,
    meaningJa: 'まさに〜そのものだ（他の何ものでもない）',
    explanationZh: '正是…、无非是…。断定「不是别的，正是这个」，用于强调本质和原因',
    formation: '名詞 ＋にほかならない',
    usageScene: '把成功归因于努力、点明事情的本质',
    nuance: '書面の力強い断定。理由・本質の強調に使う',
    register: 'written',
    matchKeys: ['にほかなら'],
    sourceExample: src('一年以内に合格できたのは、生徒自身の努力にほかならないです。', 'ec2e6d92e50c67c5'),
    examplesJa: ['一年以内に合格できたのは、生徒自身の努力にほかならないです。',
                 '成功の理由は、毎日の積み重ねにほかなりません。'],
    examplesZh: ['一年之内就能合格，靠的正是学生自身的努力。', '成功的原因，无非是每天的积累。'],
    furigana: 'いちねん いないに ごうかく できたのは、せいと じしんの どりょくに ほかならないです。',
    commonMistakesZh: '和「に過ぎない」正相反：「努力にほかならない」＝正是努力（抬高）；「努力に過ぎない」＝不过是努力（贬低）。选错方向意思颠倒',
    learnerFocus: '感谢致辞的高级句式：「今日があるのは皆さんの支えにほかなりません」。真诚又有分量',
    similarPatterns: ['〜に過ぎない', '〜というものだ'],
    contrast: '「にほかならない」＝まさにそれと高く断定；「に過ぎない」＝それだけと低く見積もる；「というものだ」＝実感を込めた評価',
    recognition: { promptZh: '「この結果は努力の証にほかならない」的语气是？',
      options: ['强调结果正是努力的证明', '结果只不过是碰巧运气好罢了', '结果与努力无关', '否定努力的价值'],
      answerIndex: 0, distractorReason: '「にほかならない」是抬高式断定，选项二是「に過ぎない」的方向',
      explanationZh: '「不是别的，正是…」的力量感' },
    production: { promptJa: '成功の本当の理由を「〜にほかならない」で言ってください。',
      promptZh: '用「〜にほかならない」点明成功的真正原因。',
      expected: ['にほかなら'], acceptable: ['〜にほかなりません'] },
    practice: { themeJa: '感謝を力強く伝える', starterJa: '今の自分があるのは、誰の（何の）おかげだと思いますか？',
      starterZh: '你觉得今天的自己靠的是谁（什么）？', targetUse: '〜にほかならない' },
    vocabularyLinks: ['fi-ganbaru', 'fi-tsuzukeru'] }),
  g({ grammarId: 'n2g-132', pattern: '〜にもかかわらず', reading: 'にもかかわらず', unit: 9, zhSourceRowId: null,
    meaningJa: '〜なのに（それをものともせず）',
    explanationZh: '尽管…却…。前项条件本应阻碍，后项却依然发生，带意外・敬意・不满',
    formation: '動詞・い形容詞普通形／な形容詞・名詞（である） ＋にもかかわらず',
    usageScene: '尽管恶劣天气仍有很多人到场、尽管很冷却穿短袖',
    nuance: '書面寄りの逆接。予想を裏切る事実への驚き・評価がこもる',
    register: 'both',
    matchKeys: ['にもかかわらず', 'にも関わらず'],
    sourceExample: src('今日は寒かったにも関わらず、半袖で外に出てしまいました。', '0f0e027a8ea6fbde'),
    examplesJa: ['今日は寒かったにも関わらず、半袖で外に出てしまいました。',
                 '悪天候にもかかわらず、大勢のお客さんが来てくれました。'],
    examplesZh: ['尽管今天很冷，还是穿着短袖出了门。', '尽管天气恶劣，还是来了很多客人。'],
    furigana: 'きょうは さむかったにも かかわらず、はんそでで そとに でて しまいました。',
    commonMistakesZh: 'Unit8学过的「にかかわらず」（无论）只差一个「も」：「天気にかかわらず開催」＝风雨无阻办；「悪天候にもかかわらず来た」＝尽管坏天气却来了。考试必考的一对',
    learnerFocus: '向帮助自己的人道谢时的敬意表达：「お忙しいにもかかわらず、ありがとうございます」',
    similarPatterns: ['〜のに', '〜にかかわらず'],
    contrast: '「にもかかわらず」＝書面寄りの逆接（敬意・驚き）；「のに」＝口語の逆接（不満が出やすい）；「にかかわらず」＝無関係（逆接ではない）',
    recognition: { promptZh: '选出「尽管下雨还是来了」的正确说法：',
      options: ['雨にもかかわらず、来てくれた', '雨にかかわらず、来てくれた', '雨に応じて、来てくれた', '雨に沿って、来てくれた'],
      answerIndex: 0, distractorReason: '「にかかわらず」是无论（不合语境的转折义）、「に応じて」是按照、「に沿って」是沿着',
      explanationZh: '逆接要用带「も」的「にもかかわらず」' },
    production: { promptJa: '困難をものともしなかった出来事を「〜にもかかわらず」で言ってください。',
      promptZh: '用「〜にもかかわらず」说一件不受阻碍照样发生的事。',
      expected: ['にもかかわらず'], acceptable: ['〜にも関わらず'] },
    practice: { themeJa: '感謝と敬意を伝える', starterJa: '忙しい中、あなたを助けてくれた人はいますか？',
      starterZh: '有人在百忙之中帮过你吗？', targetUse: '〜にもかかわらず' },
    vocabularyLinks: ['fi-samui', 'fi-deru'] }),
  g({ grammarId: 'n2g-133', pattern: '〜に基づいて', reading: 'にもとづいて', unit: 9, zhSourceRowId: null,
    meaningJa: '〜を根拠・土台にして',
    explanationZh: '基于…、根据…。以数据、规则、事实为根据展开后项',
    formation: '名詞 ＋に基づいて（に基づく＋名詞）',
    usageScene: '基于数据改善、依据法律判断、根据事实报道',
    nuance: '根拠への忠実さが核。論文・ビジネス文書の定番',
    register: 'written',
    matchKeys: ['に基づ'],
    sourceExample: src('ルールに基づいて挑戦しましょう。', '1f05493ab908c3dd'),
    examplesJa: ['ルールに基づいて挑戦しましょう。',
                 'アンケートの結果に基づいて、メニューを改善しました。'],
    examplesZh: ['让我们按照规则来挑战吧。', '基于问卷结果，改进了菜单。'],
    furigana: 'ルールに もとづいて ちょうせん しましょう。',
    commonMistakesZh: '「に応じて」是灵活调整、「に基づいて」是忠于根据：「レベルに応じて授業を変える」／「文法書に基づいて教える」。前项是数据・规则时选「に基づいて」',
    learnerFocus: '写报告的可信度担保：「事実に基づいて説明します」。主张有据，说服力翻倍',
    similarPatterns: ['〜をもとにして', '〜に沿って'],
    contrast: '「に基づいて」＝根拠に忠実；「をもとにして」＝材料から作り出す（自由度高め）；「に沿って」＝方針からずれない',
    recognition: { promptZh: '「データに基づいて判断する」的态度是？',
      options: ['以数据为根据来判断', '完全凭自己的感觉判断', '完全无视数据来做判断', '让数据自己去做出判断'],
      answerIndex: 0, distractorReason: '「に基づいて」＝以…为根据',
      explanationZh: '根拠→判断的忠实关系' },
    production: { promptJa: '根拠のある主張を「〜に基づいて」で言ってください。',
      promptZh: '用「〜に基づいて」做一个有根据的主张。',
      expected: ['に基づ'], acceptable: ['〜に基づき'] },
    practice: { themeJa: '根拠を示して提案する', starterJa: '何かを変えたいとき、どんな根拠を示しますか？',
      starterZh: '想改变什么时，你会拿出什么根据？', targetUse: '〜に基づいて' },
    vocabularyLinks: ['fi-kangaeru', 'fi-mondai'] }),
  g({ grammarId: 'n2g-134', pattern: '〜にわたって', reading: 'にわたって', unit: 9, zhSourceRowId: null,
    meaningJa: '〜の範囲・期間の全体に及んで',
    explanationZh: '长达…、遍及…、多方面…。强调期间、范围、次数之广',
    formation: '名詞（期間・範囲・回数） ＋にわたって（にわたる＋名詞）',
    usageScene: '工程长达三个月、特长遍及多个领域、大雨波及全境',
    nuance: '「広い・長い・多い」ことへの感嘆が入る。狭い範囲には不自然',
    register: 'written',
    matchKeys: ['にわたっ', 'にわたる'],
    sourceExample: src('英語、日本語、ピアノ、生花など、多岐にわたる特技があります。', '046b956e022d3de1'),
    examplesJa: ['英語、日本語、ピアノ、生花など、多岐にわたる特技があります。',
                 '道路工事は3か月にわたって行われました。'],
    examplesZh: ['英语、日语、钢琴、插花，特长遍及多个领域。', '道路施工持续了长达三个月。'],
    furigana: 'えいご、にほんご、ピアノ、いけばな など、たきに わたる とくぎが あります。',
    commonMistakesZh: '「10分にわたって」这种短时间会滑稽——要有「真久/真广」的分量。「多岐にわたる」（涉及多方面）是高频固定搭配',
    learnerFocus: '介绍经历的升级句：「5年にわたって日本語を学んできました」比「5年間勉強した」更显郑重',
    similarPatterns: ['〜を通じて', '〜の間'],
    contrast: '「にわたって」＝範囲・期間の広がりを強調；「を通じて」＝期間の始終ずっと；「の間」＝中立の期間表現',
    recognition: { promptZh: '「試験範囲は3課から10課にわたる」的意思是？',
      options: ['考试范围覆盖第3到10课', '只考第3课和第10课这两课', '考试不含3到10课', '考试只有10分钟'],
      answerIndex: 0, distractorReason: '「にわたる」表示范围的整体覆盖',
      explanationZh: '范围之广的强调' },
    production: { promptJa: '長い期間の継続を「〜にわたって」で言ってください。',
      promptZh: '用「〜にわたって」说一件持续很久的事。',
      expected: ['にわた'], acceptable: ['〜にわたり'] },
    practice: { themeJa: '自分の歩みを重みを持って語る', starterJa: '長く続けてきたことを、面接風に紹介してみましょう。',
      starterZh: '用面试的口吻介绍一件你坚持很久的事。', targetUse: '〜にわたって' },
    vocabularyLinks: ['fi-keiken', 'fi-tanoshii'] }),
  g({ grammarId: 'n2g-135', pattern: '〜抜きでは', reading: 'ぬきでは', unit: 9, zhSourceRowId: null,
    meaningJa: '〜がなければ（成り立たない）',
    explanationZh: '没有…就（不行）。去掉前项，后项就难以成立；「冗談抜きで」＝不开玩笑',
    formation: '名詞 ＋抜きでは（抜きで・抜きに）',
    usageScene: '强调某人某物不可或缺、切换认真模式说正事',
    nuance: '「抜きでは＋否定・困難」が基本形。「〜抜きで」は「无…状态下」',
    register: 'spoken',
    matchKeys: ['抜きで', '抜きに'],
    sourceExample: src('先生の指導抜きでは合格までいくのが難しいです。', '5b4de8da25053476'),
    examplesJa: ['先生の指導抜きでは合格までいくのが難しいです。',
                 '冗談抜きで、今回は本当に頑張りました。'],
    examplesZh: ['没有老师的指导，很难走到合格这一步。', '不开玩笑，这次真的很努力了。'],
    furigana: 'せんせいの しどう ぬきでは ごうかくまで いくのが むずかしいです。',
    commonMistakesZh: '「抜きでは」后面必须接否定・困难：「先生抜きでは合格できた」是矛盾句。点餐用法「わさび抜きでお願いします」（不要芥末）也常用',
    learnerFocus: '表白感谢的实感句：「みなさんの応援抜きでは、ここまで来られませんでした」。饭馆点餐「〜抜きで」立刻实用',
    similarPatterns: ['〜なしでは', '〜がなければ'],
    contrast: '「抜きでは」＝除外すると成立しない；「なしでは」＝ほぼ同義（やや硬め）；「がなければ」＝条件文の一般形',
    recognition: { promptZh: '在寿司店说「わさび抜きでお願いします」是想要？',
      options: ['不放芥末的寿司', '多加芥末的寿司', '只要芥末', '拔掉鱼的寿司'],
      answerIndex: 0, distractorReason: '「〜抜きで」＝去掉…的状态',
      explanationZh: '「抜き」＝抜く（去掉）的名词形' },
    production: { promptJa: '欠かせない存在への感謝を「〜抜きでは」で言ってください。',
      promptZh: '用「〜抜きでは」感谢一个不可或缺的人。',
      expected: ['抜きで'], acceptable: ['〜抜きには'] },
    practice: { themeJa: '欠かせない人を語る', starterJa: 'あなたの学習に欠かせない人（もの）は誰（何）ですか？',
      starterZh: '你的学习中不可缺少的人（东西）是？', targetUse: '〜抜きでは' },
    vocabularyLinks: ['fi-muri', 'fi-komaru'] }),
];
