// Phase R2: N2文法完成draft Unit 1（No.1〜15のうち14文型。007は同義判断待ち）。
// n2GrammarDrafts.ts から分離（Unit単位lazy chunk境界のため）。内容は無変更。
import type { N2GrammarDraft } from './n2GrammarDrafts';

const g = (p: Omit<N2GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey' | 'runtimeExampleOrigin'> & { reviewKey?: string; runtimeExampleOrigin?: N2GrammarDraft['runtimeExampleOrigin'] }): N2GrammarDraft =>
  ({ level: 'N2', route: 'n2-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, runtimeExampleOrigin: 'original_authored', ...p });

/** Unit 1（15文型）。原本No.1〜15に対応。 */
export const N2_GRAMMAR_DRAFTS_UNIT1: N2GrammarDraft[] = [
  g({ grammarId: 'n2g-001', pattern: '〜あげく', reading: 'あげく', unit: 1, zhSourceRowId: null,
    meaningJa: '〜した結果、（よくない）結末になった',
    explanationZh: '…之后终于…（结果多为负面）。经过长时间的努力或纠结，最后落得某个（不好的）结局',
    formation: '動詞た形／名詞＋の ＋あげく',
    usageScene: '讲述折腾很久最后失败、犹豫很久最后做了错误选择的经历',
    nuance: '几乎只用于负面结局。中性的「结果」用「〜結果」',
    register: 'written',
    sourceExample: { text: '試験前日（ぜんじつ）に徹夜をしたあげく、当日寝坊をしてしまいました。', hash: '27a6e197c608d692', rightsStatus: 'teacher_created_confirmed' },
    examplesJa: ['何度も設定を変えたあげく、結局もとに戻しました。', '長時間迷ったあげく、何も買わずに帰りました。'],
    examplesZh: ['改了好几次设置，结果又改回了原样。', '犹豫了很久，结果什么都没买就回去了。'],
    furigana: 'なんども せっていを かえた あげく、けっきょく もとに もどしました。',
    commonMistakesZh: '不能用于好结果。「たくさん勉強したあげく合格した」不自然，要用「〜結果」',
    learnerFocus: '中文「结果」褒贬皆可，日语「あげく」限定负面。这是选词准确度的关键',
    similarPatterns: ['〜結果', '〜末に'],
    contrast: '「あげく」＝负面结局；「末に」＝可褒可贬（多为经过努力）；「結果」＝中性',
    recognition: { promptZh: '哪个句子用「あげく」自然？',
      options: ['さんざん迷ったあげく、買わなかった', '努力したあげく、合格した', '寝たあげく、元気になった', '食べたあげく、おいしかった'],
      answerIndex: 0, distractorReason: '「あげく」只用于折腾之后的负面结局',
      explanationZh: '「〜あげく」= 折腾很久后落得（不好的）结果' },
    production: { promptJa: '長く迷って結局うまくいかなかった経験を「〜あげく」で言ってください。',
      promptZh: '用「〜あげく」说一次折腾很久却没成的经历。',
      expected: ['あげく'], acceptable: ['〜たあげく'] },
    practice: { themeJa: '長く悩んだ末の失敗を話す', starterJa: '長く悩んだのに、うまくいかなかったことはありますか？',
      starterZh: '有过纠结很久却没成的事吗？', targetUse: '〜あげく' },
    vocabularyLinks: ['fi-komaru', 'fi-kimeru'] }),
  g({ grammarId: 'n2g-002', pattern: '〜あまり', reading: 'あまり', unit: 1, zhSourceRowId: 'n3row-2',
    meaningJa: '〜しすぎて、その結果',
    explanationZh: '因为过于…导致…。程度过高，引起了通常不会有的结果',
    formation: '動詞辞書形／名詞＋の ＋あまり',
    usageScene: '说明因为太紧张、太高兴、太在意而做出反常行为',
    nuance: '前项多是感情或状态的过度。书面语',
    register: 'written',
    sourceExample: { text: '周りの目線を気にするあまり、言いたいことが言えなくなってしまいました。', hash: '25836597d3aaed91', rightsStatus: 'teacher_created_confirmed' },
    examplesJa: ['締め切りを気にするあまり、内容の確認がおろそかになりました。', 'うれしさのあまり、泣いてしまいました。'],
    examplesZh: ['因为太在意截止日期，内容的确认反而马虎了。', '因为太高兴，不由得哭了出来。'],
    furigana: 'しめきりを きにする あまり、ないようの かくにんが おろそかに なりました。',
    commonMistakesZh: '名词接续要加「の」：「うれしさのあまり」。「うれしいあまり」是错的',
    learnerFocus: '与副词「あまり〜ない」（不太…）同形不同义，靠位置区分：句中接续＝过于，句首＋否定＝不太',
    similarPatterns: ['〜すぎて', '〜ほど'],
    contrast: '「あまり」＝书面、程度过度导致结果；「すぎて」＝口语常用',
    recognition: { promptZh: '「緊張のあまり」是什么意思？',
      options: ['因为太紧张', '不太紧张', '有点紧张', '不紧张'],
      answerIndex: 0, distractorReason: '接续用法的「あまり」表示程度过度',
      explanationZh: '名詞＋の＋あまり = 因为过于…' },
    production: { promptJa: '感情が高ぶって普段しないことをした経験を「〜あまり」で言ってください。',
      promptZh: '用「〜あまり」说一次因情绪过度而做出反常举动的经历。',
      expected: ['あまり'], acceptable: ['〜のあまり', '〜するあまり'] },
    practice: { themeJa: '感情が高ぶった経験を話す', starterJa: '緊張やうれしさのあまり、何かしてしまったことはありますか？',
      starterZh: '有过因太紧张或太高兴而做出什么举动吗？', targetUse: '〜あまり' },
    vocabularyLinks: ['fi-kimochi', 'fi-ureshii'] }),
  g({ grammarId: 'n2g-003', pattern: '〜以上は', reading: 'いじょうは', unit: 1, zhSourceRowId: null,
    meaningJa: '〜のだから、当然〜すべきだ',
    explanationZh: '既然…就（应该）…。前项成立，后项就是理所当然的责任或决心',
    formation: '動詞・い形容詞普通形／な形容詞・名詞＋である ＋以上は',
    usageScene: '表明决心、说明既然接受了就要负责',
    nuance: '后项接义务・决心・忠告（〜べきだ・〜なければならない・〜つもりだ）',
    register: 'written',
    sourceExample: { text: 'N2合格を目標にする以上は、文法も勉強しなければいけません。', hash: '037ac78462672141', rightsStatus: 'teacher_created_confirmed' },
    examplesJa: ['担当になった以上は、最後まで面倒を見ます。', '引き受けた以上は、最後まで責任を持ちます。'],
    examplesZh: ['既然当了负责人，就负责到最后。', '既然接下了，就负责到底。'],
    furigana: 'たんとうに なった いじょうは、さいごまで めんどうを みます。',
    commonMistakesZh: '后项不能是单纯的事实描述。必须是义务、决心或忠告',
    learnerFocus: '面试和职场表决心时很有力。「引き受けた以上は」是很成熟的表达',
    similarPatterns: ['〜からには', '〜上は'],
    contrast: '「以上は」「からには」几乎同义；「からには」更口语',
    recognition: { promptZh: '「日本で働く以上は、＿＿」后面最自然的是？',
      options: ['敬語を覚えるべきです', '日本は島国です', '天気がいいです', '桜がきれいです'],
      answerIndex: 0, distractorReason: '「以上は」后面要接义务・决心・忠告',
      explanationZh: '「〜以上は」＋义务・决心・忠告 的结构' },
    production: { promptJa: '自分の決意を「〜以上は」で言ってください。',
      promptZh: '用「〜以上は」表达你的决心。',
      expected: ['以上は'], acceptable: ['〜する以上は', '〜した以上は'] },
    practice: { themeJa: '決意を表明する', starterJa: '日本語を勉強する以上は、何を目指しますか？',
      starterZh: '既然学日语，你的目标是什么？', targetUse: '〜以上は' },
    vocabularyLinks: ['fi-yotei', 'fi-ganbaru'] }),
  g({ grammarId: 'n2g-004', pattern: '〜一方で', reading: 'いっぽうで', unit: 1, zhSourceRowId: null,
    meaningJa: '一方では〜、他方では〜（二つの面を並べる）',
    explanationZh: '一方面…另一方面…。并列说明同一事物的两个侧面',
    formation: '動詞・い形容詞普通形／な形容詞＋な／名詞＋である ＋一方で',
    usageScene: '客观分析优缺点、说明自己的能力有强有弱',
    nuance: '不是转折，而是并列两个事实。书面・论说文常用',
    register: 'written',
    sourceExample: { text: '試験合格はできる一方で、会話力がまだ乏しい（とぼしい）/低いです。', hash: '1a89cf8db23da7fb', rightsStatus: 'teacher_created_confirmed' },
    examplesJa: ['この街は家賃が安い一方で、駅までの距離があります。', '仕事は忙しい一方で、やりがいもあります。'],
    examplesZh: ['这个城市一方面房租便宜，另一方面离车站有距离。', '工作一方面很忙，另一方面也很有成就感。'],
    furigana: 'この まちは やちんが やすい いっぽうで、えきまでの きょりが あります。',
    commonMistakesZh: '「一方だ」（越来越…）和「一方で」（一方面）形近意不同，不要混用',
    learnerFocus: '面试自我分析时用「〜一方で」能显得客观成熟，比只说优点更可信',
    similarPatterns: ['〜反面', '〜一方だ'],
    contrast: '「一方で」＝并列两面；「反面」＝对比性更强；「一方だ」＝单向变化',
    recognition: { promptZh: '「便利な一方で、値段が高い」是什么关系？',
      options: ['并列说明优点和缺点', '只说了优点没说缺点', '只说了缺点没说优点', '前后是因果关系'],
      answerIndex: 0, distractorReason: '「一方で」并列两个侧面',
      explanationZh: '「〜一方で」= 一方面…另一方面…' },
    production: { promptJa: '日本の生活の良い面と大変な面を「〜一方で」で言ってください。',
      promptZh: '用「〜一方で」说说日本生活的好与不易。',
      expected: ['一方で'], acceptable: ['〜一方で'] },
    practice: { themeJa: '物事を両面から話す', starterJa: '日本での仕事、良い面と大変な面を一文で言ってみましょう',
      starterZh: '用一句话说说在日本工作的好与难', targetUse: '〜一方で' },
    vocabularyLinks: ['fi-shigoto', 'fi-taihen'] }),
  g({ grammarId: 'n2g-005', pattern: '〜一方だ', reading: 'いっぽうだ', unit: 1, zhSourceRowId: null,
    meaningJa: 'ますます〜になっていく（一方向の変化）',
    explanationZh: '越来越…、不断地…。变化只朝一个方向发展',
    formation: '動詞辞書形 ＋一方だ',
    usageScene: '描述物价上涨、人口减少等持续的单向变化',
    nuance: '多用于不好的变化。新闻・论说文常见',
    register: 'written',
    sourceExample: { text: '日本に来て7年以上過ごしているから、周り（他人）から日本語ができると思われる一方だ。＝ばかりだ', hash: '756cdec712dcc514', rightsStatus: 'teacher_created_confirmed' },
    examplesJa: ['スマホを見る時間は、増える一方です。', '物価は上がる一方です。'],
    examplesZh: ['看手机的时间不断增加。', '物价不断上涨。'],
    furigana: 'スマホを みる じかんは、ふえる いっぽうです。',
    commonMistakesZh: '只接动词辞书形。「上がった一方だ」是错的',
    learnerFocus: '读日本新闻时高频。「〜一方だ」出现时，作者通常在表达担忧',
    similarPatterns: ['〜ばかりだ', '〜つつある'],
    contrast: '「一方だ」＝单向持续（多负面）；「つつある」＝正在变化（中性）',
    recognition: { promptZh: '「増える一方だ」是什么意思？',
      options: ['不断增加', '增加后减少', '没有变化', '开始减少'],
      answerIndex: 0, distractorReason: '「一方だ」表示单向持续的变化',
      explanationZh: '「〜一方だ」= 一直朝一个方向变化' },
    production: { promptJa: '最近増え続けている・減り続けていることを「〜一方だ」で言ってください。',
      promptZh: '用「〜一方だ」说一件持续增加或减少的事。',
      expected: ['一方'], acceptable: ['〜一方だ', '〜一方です'] },
    practice: { themeJa: '社会の変化を語る', starterJa: '最近、増える一方・減る一方だと感じることはありますか？',
      starterZh: '最近你觉得什么在持续增加或减少？', targetUse: '〜一方だ' },
    vocabularyLinks: ['fi-fueru', 'fi-heru'] }),
  g({ grammarId: 'n2g-006', pattern: '〜上では', reading: 'うえでは', unit: 1, zhSourceRowId: null,
    meaningJa: '〜という点から見ると',
    explanationZh: '在…方面、从…来看。限定讨论的范围或角度',
    formation: '名詞＋の／動詞辞書形 ＋上では',
    usageScene: '说明「就数据而言」「就规定而言」等限定角度的判断',
    nuance: '常暗示「但实际情况可能不同」（データの上では順調だが…）',
    register: 'written',
    sourceExample: { text: '会話力を上げる上では、話す練習も必要です。', hash: 'c2c37b0794c2f162', rightsStatus: 'teacher_created_confirmed' },
    examplesJa: ['制度を理解する上では、まず条文を読む必要があります。', '数字の上では順調ですが、現場は大変です。'],
    examplesZh: ['在理解制度这方面，首先需要读条文。', '数字上很顺利，但现场很辛苦。'],
    furigana: 'せいどを りかいする うえでは、まず じょうぶんを よむ ひつようが あります。',
    commonMistakesZh: '和「〜うえで」（之后）区别：加「は」变成「在…方面」的角度限定',
    learnerFocus: '商务报告中「データの上では」暗示后面有转折，是重要的信号词',
    similarPatterns: ['〜において', '〜に関して'],
    contrast: '「上では」＝限定角度（常有转折）；「において」＝场所・领域（中性）',
    recognition: { promptZh: '「計算の上では問題ありません」暗示什么？',
      options: ['理论上没问题，但实际可能有', '理论和实际都完全没问题', '理论上就有很大的问题', '还没有做任何计算'],
      answerIndex: 0, distractorReason: '「上では」常暗示实际情况与之不同',
      explanationZh: '「〜上では」= 就…而言（暗示有例外）' },
    production: { promptJa: '「理論上は問題ないが実際は…」を「〜上では」で言ってください。',
      promptZh: '用「〜上では」说「理论上没问题但实际…」。',
      expected: ['上では'], acceptable: ['〜の上では'] },
    practice: { themeJa: '理論と現実の差を話す', starterJa: '計画通りにいかなかった経験はありますか？',
      starterZh: '有过没按计划进行的经历吗？', targetUse: '〜上では' },
    vocabularyLinks: ['fi-joukyou', 'fi-mondai'] }),
  g({ grammarId: 'n2g-008', pattern: '〜うちに', reading: 'うちに', unit: 1, zhSourceRowId: 'n3row-45',
    meaningJa: 'その状態が続いている間に（変わる前に）',
    explanationZh: '趁着…（还没变化的时候）。强调不趁现在做就来不及',
    formation: '動詞辞書形／ない形／ている形／い形容詞／な形容詞＋な／名詞＋の ＋うちに',
    usageScene: '提醒趁热吃、趁没忘记记下来、趁年轻多挑战',
    nuance: '含紧迫感：状态会变，所以要抓紧。「あいだに」没有这层含义',
    register: 'both',
    sourceExample: { text: '忘れないうちに、メモをします。', hash: 'e87bd6f0c1bd3f5d', rightsStatus: 'teacher_created_confirmed' },
    examplesJa: ['気持ちが冷めないうちに、申し込みを済ませました。', '若いうちに、いろいろ挑戦したほうがいいです。'],
    examplesZh: ['趁热情还没冷却，把报名办完了。', '趁年轻，最好多做些尝试。'],
    furigana: 'きもちが さめない うちに、もうしこみを すませました。',
    commonMistakesZh: '「〜ないうちに」（趁还没…）是高频形式。「忘れるうちに」是错的',
    learnerFocus: '「あついうちに召し上がってください」（趁热吃）是待客的常用语，务必掌握',
    similarPatterns: ['〜あいだに', '〜前に'],
    contrast: '「うちに」＝趁状态未变（有紧迫感）；「あいだに」＝期间内；「前に」＝单纯的之前',
    recognition: { promptZh: '「熱いうちに食べてください」是什么意思？',
      options: ['趁热吃', '等凉了再吃', '不要吃', '慢慢吃'],
      answerIndex: 0, distractorReason: '「うちに」表示趁状态还没改变',
      explanationZh: '「〜うちに」= 趁着…' },
    production: { promptJa: '「忘れる前にする」ことを「〜ないうちに」で言ってください。',
      promptZh: '用「〜ないうちに」说趁着还没忘记要做的事。',
      expected: ['うちに'], acceptable: ['忘れないうちに', '〜ないうちに'] },
    practice: { themeJa: '今のうちにしておきたいことを話す', starterJa: '若いうちに、何をしておきたいですか？',
      starterZh: '趁年轻你想做什么？', targetUse: '〜うちに' },
    vocabularyLinks: ['fi-wasureru', 'fi-atarashii'] }),
  g({ grammarId: 'n2g-011', pattern: '〜得る', reading: 'うる／える', unit: 1, zhSourceRowId: null,
    meaningJa: '〜する可能性がある／〜できる',
    explanationZh: '可能…、能够…。表示理论上的可能性',
    formation: '動詞ます形 ＋得る（辞書形は「うる」、活用は「える」）',
    usageScene: '论说文、商务讨论中说明可能性',
    nuance: '书面语。「あり得る」（有可能）是最常用的形式',
    register: 'written',
    sourceExample: { text: 'あなたのポテンシャルであれば、N1合格も一年以内で十分あり得ると思います。', hash: '898c1bf67fdbe07a', rightsStatus: 'teacher_created_confirmed' },
    examplesJa: ['準備さえ十分なら、半年での合格もあり得ます。', 'この方法でも解決し得ると考えています。'],
    examplesZh: ['只要准备充分，半年内合格也是有可能的。', '我认为用这个方法也能解决。'],
    furigana: 'じゅんびさえ じゅうぶんなら、はんとしでの ごうかくも ありえます。',
    commonMistakesZh: '辞书形读「うる」，其他活用读「える」（あり得ない＝ありえない）。读音是难点',
    learnerFocus: '会话中说「あり得ない！」（不可能！）很常见，是听力高频词',
    similarPatterns: ['〜かもしれない', '〜可能性がある'],
    contrast: '「得る」＝书面的可能性；「かもしれない」＝口语推测',
    recognition: { promptZh: '「あり得ない」的读音是？',
      options: ['ありえない', 'ありうない', 'ありとくない', 'あります'],
      answerIndex: 0, distractorReason: '否定形读「えない」，辞书形才读「うる」',
      explanationZh: '得る＝うる（辞書形）／得ない＝えない' },
    production: { promptJa: '可能性があることを「〜得る」で言ってください。',
      promptZh: '用「〜得る」说一件有可能的事。',
      expected: ['得'], acceptable: ['あり得ます', '〜し得る'] },
    practice: { themeJa: '可能性を論じる', starterJa: '1年でN2に合格することはあり得ると思いますか？',
      starterZh: '你觉得一年内通过N2有可能吗？', targetUse: '〜得る' },
    vocabularyLinks: ['fi-tabun', 'fi-kangaeru'] }),
  g({ grammarId: 'n2g-012', pattern: '〜得ない', reading: 'えない', unit: 1, zhSourceRowId: null,
    meaningJa: '〜する可能性がない／〜できない',
    explanationZh: '不可能…、无法…。表示可能性被否定',
    formation: '動詞ます形 ＋得ない',
    usageScene: '强烈否定某种可能性',
    nuance: '「あり得ない」在口语中也表示「太离谱了」的惊讶',
    register: 'both',
    sourceExample: { text: '辛い食べ物に慣れていない人であれば、四川料理は完食し得ないと思います。', hash: 'e044f759317d19d0', rightsStatus: 'teacher_created_confirmed' },
    examplesJa: ['経験のない人が一人で対応し得ない案件です。', 'そんなミスは、普通あり得ません。'],
    examplesZh: ['这是没有经验的人无法独自应对的案子。', '那样的失误，正常来说不可能发生。'],
    furigana: 'けいけんの ない ひとが ひとりで たいおうしえない あんけんです。',
    commonMistakesZh: '「あり得ない」在年轻人口语中也用作「太夸张了」的感叹，语气很强',
    learnerFocus: '对上司说「あり得ません」否定其判断会很失礼，要用「難しいかと思います」',
    similarPatterns: ['〜わけがない', '〜はずがない'],
    contrast: '「得ない」＝理论上不可能（书面）；「わけがない」＝口语的强烈否定',
    recognition: { promptZh: '「経験のない人が一人で対応し得ない案件」是什么样的案件？',
      options: ['没有经验的人不可能独自应对的案件', '谁都能轻松独自应对的案件', '必须由没有经验的人应对的案件', '已经应对完毕的案件'],
      answerIndex: 0, distractorReason: '「し得ない」＝该可能性被否定（书面）',
      explanationZh: '动词ます形＋得ない＝不可能…。※对上司否定时不要直接说「あり得ません」，用「難しいかと思います」缓冲（见学习要点）' },
    production: { promptJa: '可能性がないことを「〜得ない」で言ってください。',
      promptZh: '用「〜得ない」说一件不可能的事。',
      expected: ['得'], acceptable: ['あり得ません', '〜し得ない'] },
    practice: { themeJa: '否定の言い方を選ぶ', starterJa: '上司の案に反対するとき、どう言いますか？',
      starterZh: '反对上司的方案时你怎么说？', targetUse: '〜得ない' },
    vocabularyLinks: ['fi-muri', 'fi-iken'] }),
  g({ grammarId: 'n2g-013', pattern: '〜おかげで', reading: 'おかげで', unit: 1, zhSourceRowId: 'n3row-103',
    meaningJa: '〜のおかげで良い結果になった',
    explanationZh: '托…的福、多亏了…。只用于好的结果',
    formation: '名詞＋の／動詞た形 ＋おかげで',
    usageScene: '感谢帮助过自己的人、说明成功的原因',
    nuance: '坏结果用「〜せいで」。用反会变成讽刺',
    register: 'both',
    sourceExample: { text: '好きな俳優のおかげで、つらい時に頑張ることができました。', hash: 'e3a4b87a26cfd731', rightsStatus: 'teacher_created_confirmed' },
    examplesJa: ['先輩が教えてくれたおかげで、手順を早く覚えられました。', '皆さんのおかげで、無事に終わりました。'],
    examplesZh: ['多亏前辈教我，很快就记住了流程。', '托大家的福，顺利结束了。'],
    furigana: 'せんぱいが おしえて くれた おかげで、てじゅんを はやく おぼえられました。',
    commonMistakesZh: '「おかげさまで」是寒暄定型，被问「元気ですか」时可答「おかげさまで元気です」',
    learnerFocus: 'N3でも学ぶが、N2では「〜おかげか」（也许是托…的福）など曖昧表现も出る',
    similarPatterns: ['〜せいで', '〜によって'],
    contrast: '「おかげで」＝正面；「せいで」＝负面；「によって」＝中性',
    recognition: { promptZh: '「おかげさまで」什么时候用？',
      options: ['被问候近况时的礼貌回应', '向对方道歉时的开场白', '拒绝对方邀请时的说法', '命令对方做事时的说法'],
      answerIndex: 0, distractorReason: '「おかげさまで」是寒暄的固定回应',
      explanationZh: '「おかげさまで元気です」是标准回应' },
    production: { promptJa: '感謝を「〜おかげで」で伝えてください。',
      promptZh: '用「〜おかげで」表达感谢。',
      expected: ['おかげで'], acceptable: ['〜のおかげで'] },
    practice: { themeJa: '支えてくれた人に感謝する', starterJa: '日本での生活で、誰のおかげで助かりましたか？',
      starterZh: '在日本生活中，多亏了谁帮了你？', targetUse: '〜おかげで' },
    vocabularyLinks: ['fi-tomodachi', 'fi-ganbaru'] }),
  g({ grammarId: 'n2g-014', pattern: '〜恐れがある', reading: 'おそれがある', unit: 1, zhSourceRowId: 'n3row-82',
    meaningJa: '悪いことが起きる可能性がある',
    explanationZh: '有…的危险、恐怕会…。仅用于不好的可能性',
    formation: '動詞辞書形／名詞＋の ＋恐れがある',
    usageScene: '灾害警报、健康风险、事故风险的正式通告',
    nuance: '正式书面。好事不能用',
    register: 'written',
    sourceExample: { text: '日本では近いうちに大きな地震がくる恐れがあります。', hash: '1ebccfade357935e', rightsStatus: 'teacher_created_confirmed' },
    examplesJa: ['連休中は、駅が大変混雑する恐れがあります。', '大雨のため、川が増水する恐れがあります。'],
    examplesZh: ['连休期间车站恐怕会非常拥挤。', '因为大雨，河水有上涨的危险。'],
    furigana: 'れんきゅうちゅうは、えきが たいへん こんざつする おそれが あります。',
    commonMistakesZh: '只用于负面。好的可能性用「〜可能性がある」',
    learnerFocus: '防灾广播、气象警报中必现。听懂它关系到人身安全',
    similarPatterns: ['〜可能性がある', '〜かねない'],
    contrast: '「恐れがある」＝正式警告；「かねない」＝口语的担忧；「可能性」＝中性',
    recognition: { promptZh: '哪个不能用「恐れがある」？',
      options: ['合格する恐れがある', '事故が起きる恐れがある', '停電する恐れがある', '遅れる恐れがある'],
      answerIndex: 0, distractorReason: '「恐れ」只用于不好的可能性',
      explanationZh: '好事用「可能性がある」' },
    production: { promptJa: '天気の警報を「〜恐れがあります」で言ってください。',
      promptZh: '用「〜恐れがあります」说一条天气警报。',
      expected: ['恐れが'], acceptable: ['〜恐れがあります'] },
    practice: { themeJa: '防災情報を読み取る', starterJa: '日本で地震や台風の警報を聞いたことがありますか？',
      starterZh: '你在日本听过地震或台风警报吗？', targetUse: '〜恐れがあります' },
    vocabularyLinks: ['fi-joukyou', 'fi-hitsuyou'] }),
  g({ grammarId: 'n2g-015', pattern: '〜甲斐がある', reading: 'かいがある', unit: 1, zhSourceRowId: null,
    meaningJa: '努力した価値があった',
    explanationZh: '没有白费、值得。付出的努力得到了回报',
    formation: '動詞た形／名詞＋の ＋甲斐がある（甲斐があって）',
    usageScene: '努力后取得成果时的感慨',
    nuance: '正面。否定形「甲斐がない」表示白费了',
    register: 'written',
    sourceExample: { text: 'たくさん勉強をした甲斐があって、無事（ぶじ）、試験に受かりました。', hash: '1c25d38a461f4340', rightsStatus: 'teacher_created_confirmed' },
    examplesJa: ['早起きを続けた甲斐があって、朝の時間に余裕ができました。', '毎日練習した甲斐があって、うまく話せるようになりました。'],
    examplesZh: ['坚持早起没有白费，早上有了富余的时间。', '每天练习没有白费，变得能说得很好了。'],
    furigana: 'はやおきを つづけた かいが あって、あさの じかんに よゆうが できました。',
    commonMistakesZh: '「〜甲斐があって」（多亏…没白费）是最常用的形式，后面接好结果',
    learnerFocus: '「やりがいがある」（有成就感）是同源的高频词，工作话题中常用',
    similarPatterns: ['〜だけのことはある', '〜やりがい'],
    contrast: '「甲斐がある」＝努力有回报；「やりがい」＝做起来有价值（做之前也能说）',
    recognition: { promptZh: '「勉強した甲斐があった」是什么意思？',
      options: ['学习没有白费', '学习白费了', '不想学习', '学习很难'],
      answerIndex: 0, distractorReason: '「甲斐がある」表示努力得到了回报',
      explanationZh: '「〜甲斐があって」= 没有白费' },
    production: { promptJa: '努力が報われた経験を「〜甲斐があって」で言ってください。',
      promptZh: '用「〜甲斐があって」说一次努力得到回报的经历。',
      expected: ['甲斐が'], acceptable: ['〜甲斐があって', '〜甲斐がありました'] },
    practice: { themeJa: '努力が実った経験を話す', starterJa: '頑張った甲斐があったと感じた経験はありますか？',
      starterZh: '有过觉得努力没白费的经历吗？', targetUse: '〜甲斐があって' },
    vocabularyLinks: ['fi-ganbaru', 'fi-ureshii'] }),
  // CEO統合判断（2026-07-30）: 独立文型として維持 → 本編昇格（元・同義判断待ちpre-draft）
  g({ grammarId: 'n2g-007', pattern: '〜上は', reading: 'うえは', unit: 1, zhSourceRowId: null,
    meaningJa: '〜したからには、当然（覚悟を持って）',
    explanationZh: '既然…就（要有觉悟）…。比「以上は」更书面、更有破釜沉舟感的表达',
    formation: '動詞た形・辞書形 ＋上は',
    usageScene: '下定决心的宣言、接受任务后的表态',
    nuance: '「以上は」より硬く、覚悟の宣言に寄る。日常会話ではやや大げさ',
    register: 'written',
    runtimeExampleOrigin: 'source_confirmed',
    sourceExample: { text: '目標を決めた上は、覚悟（かくご）を決めてやりきるしかありません。', hash: '8f9f6267c978f59d', rightsStatus: 'teacher_created_confirmed' },
    examplesJa: ['目標を決めた上は、覚悟（かくご）を決めてやりきるしかありません。',
                 '引き受けた上は、途中で投げ出すわけにはいきません。'],
    examplesZh: ['既然定下了目标，就只能下定决心干到底。', '既然接下了，就不能中途撂挑子。'],
    furigana: 'もくひょうを きめた うえは、かくごを きめて やりきる しか ありません。',
    commonMistakesZh: '「上は」「以上は」「からには」三者近义：「からには」最口语、「以上は」中间、「上は」最文言。也注意与「〜上で（在…之后/方面）」区分',
    learnerFocus: '就职表态的最高级：「入社した上は、全力を尽くします」。庄重感强，面试压轴用',
    similarPatterns: ['〜以上は', '〜からには'],
    contrast: '「上は」＝文語的な覚悟宣言；「以上は」＝標準的な当然の責任；「からには」＝口語寄り',
    recognition: { promptZh: '「約束した上は、必ず守ります」的语气是？',
      options: ['庄重地表明履约的觉悟', '随口敷衍的应付', '拒绝遵守约定', '询问是否要遵守'],
      answerIndex: 0, distractorReason: '「上は」是带觉悟的郑重表态',
      explanationZh: '文言色彩的决意宣言' },
    production: { promptJa: '覚悟の宣言を「〜上は」で言ってください。',
      promptZh: '用「〜上は」做一个庄重的表态。',
      expected: ['上は'], acceptable: ['〜た上は'] },
    practice: { themeJa: '覚悟を宣言する', starterJa: '何かを最後までやり切ると決めた経験はありますか？',
      starterZh: '有没有下定决心干到底的经历？', targetUse: '〜上は' },
    vocabularyLinks: ['fi-kimeru', 'fi-ganbaru'] }),
];
