// Phase 3P-5: N2文法完成draft Unit 3（原本No.31〜45・13文型）＋Unit1穴埋め2件（n2g-009/010）。
// rightsStatus: teacher_created_confirmed（CEO確認済み）。原本例文をruntime使用可。
import type { N2GrammarDraft } from './n2GrammarDrafts';

const g = (p: Omit<N2GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey' | 'runtimeExampleOrigin'> & { reviewKey?: string; runtimeExampleOrigin?: N2GrammarDraft['runtimeExampleOrigin'] }): N2GrammarDraft =>
  ({ level: 'N2', route: 'n2-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, runtimeExampleOrigin: 'source_confirmed', ...p });

const src = (text: string, hash: string) =>
  ({ text, hash, rightsStatus: 'teacher_created_confirmed' as const });

/** Unit1の未執筆だった2件（訂正記録参照）＋Unit3の13件。 */
export const N2_GRAMMAR_DRAFTS_UNIT3: N2GrammarDraft[] = [
  g({ grammarId: 'n2g-009', pattern: '〜うちは', reading: 'うちは', unit: 1, zhSourceRowId: null,
    meaningJa: 'その状態が続く間は（変わらない）',
    explanationZh: '只要还处于…的状态，（结果）就不会变',
    formation: '動詞辞書形／ている形／ない形／名詞＋の ＋うちは',
    usageScene: '指出方法不变则结果不变、条件持续期间的状态',
    nuance: '「うちに」（趁着）と一字違いで意味が異なる。「うちは」は状態継続の限定',
    register: 'both',
    sourceExample: src('真面目に文法だけ勉強しているうちは、会話力は上がりません。', 'f10b09cc80af7139'),
    examplesJa: ['真面目に文法だけ勉強しているうちは、会話力は上がりません。',
                 '完璧を求めているうちは、話し始められません。'],
    examplesZh: ['只是认真地光学语法的话，会话能力不会提高。', '只要还在追求完美，就开不了口。'],
    furigana: 'まじめに ぶんぽうだけ べんきょうしている うちは、かいわりょくは あがりません。',
    commonMistakesZh: '「うちに」（趁着…做）と「うちは」（在…期间一直）の混同。「は」は対比・限定の含み',
    learnerFocus: '学習方法の反省を述べるのに最適。「〜ているうちは〜ない」の形で覚える',
    similarPatterns: ['〜うちに', '〜限りは'],
    contrast: '「うちは」＝状態が続く間は（否定的結果が多い）；「うちに」＝状態が変わる前に',
    recognition: { promptZh: '「独身のうちは自由だ」是什么意思？',
      options: ['单身期间是自由的', '趁单身要快点结婚', '不想单身', '已经结婚了'],
      answerIndex: 0, distractorReason: '「うちは」表示该状态持续期间的情况',
      explanationZh: '「〜うちは」= 在…期间一直' },
    production: { promptJa: '「このやり方のままでは変わらない」を「〜うちは」で言ってください。',
      promptZh: '用「〜うちは」表达方法不变结果就不变。',
      expected: ['うちは'], acceptable: ['〜ているうちは'] },
    practice: { themeJa: '学習方法を見直す', starterJa: 'どんな勉強のままでは上達しないと思いますか？',
      starterZh: '你觉得怎样的学习方式不会进步？', targetUse: '〜うちは' },
    vocabularyLinks: ['fi-benkyo', 'fi-hanasu'] }),
  g({ grammarId: 'n2g-010', pattern: '〜（し）ようではないか', reading: 'ようではないか', unit: 1, zhSourceRowId: null,
    meaningJa: 'みんなで〜しよう（呼びかけ）',
    explanationZh: '让我们一起…吧（正式的号召）',
    formation: '動詞意向形 ＋ではないか（じゃないか）',
    usageScene: '演讲、会议上号召大家一起行动',
    nuance: '演説調で硬い。日常会話では「〜しようよ」',
    register: 'written',
    matchKeys: ['ようではないか', 'ようじゃないか'],
    sourceExample: src('そろそろ日本語の勉強をしようではないか。＝〜しましょうよ＝しようじゃないですか', '07026ef9249b8811'),
    examplesJa: ['そろそろ日本語の勉強をしようではないか。',
                 'この問題を、みんなで解決しようではないか。'],
    examplesZh: ['差不多该学日语了吧，让我们开始吧。', '让我们大家一起解决这个问题吧。'],
    furigana: 'そろそろ にほんごの べんきょうを しようでは ないか。',
    commonMistakesZh: '疑問文の形だが意味は強い勧誘。「ではないか？」と上げ調子で読むと誤解される',
    learnerFocus: 'スピーチの締めで使うと格好がつく。読解・聴解で「呼びかけ」と分かることが先決',
    similarPatterns: ['〜ましょう', '〜しよう'],
    contrast: '丁寧さ・硬さ: 「しよう」＜「しましょう」＜「しようではないか」（演説調）',
    recognition: { promptZh: '「協力しようではないか」的语气是？',
      options: ['正式地号召大家合作', '询问是否合作', '拒绝合作', '抱怨合作'],
      answerIndex: 0, distractorReason: '形式是疑问，实际是强烈的号召',
      explanationZh: '演説調の呼びかけ表現' },
    production: { promptJa: 'スピーチの締めを「〜ようではないか」で言ってください。',
      promptZh: '用「〜ようではないか」说一句演讲结尾。',
      expected: ['ようではないか'], acceptable: ['〜しようではないか'] },
    practice: { themeJa: 'スピーチ調で呼びかける', starterJa: 'クラスのみんなに何かを呼びかけるとしたら？',
      starterZh: '如果要号召班里的大家做一件事，你会说什么？', targetUse: '〜ようではないか' },
    vocabularyLinks: ['fi-ganbaru', 'fi-mondai'] }),
  g({ grammarId: 'n2g-031', pattern: '〜からいうと', reading: 'からいうと', unit: 3, zhSourceRowId: null,
    meaningJa: '〜の立場・観点から判断すると',
    explanationZh: '从…（立场/角度）来说',
    formation: '名詞 ＋からいうと／からいえば',
    usageScene: '从专业、经验、立场出发发表意见',
    nuance: '「私からいうと」のように人を直接置くのはやや不自然。「立場からいうと」が安全',
    register: 'both',
    sourceExample: src('中国人の立場からいうと、日本の大学の英語レベルはすごく簡単です。', '83f210a8636b2c6f'),
    examplesJa: ['中国人の立場からいうと、日本の大学の英語レベルはすごく簡単です。',
                 '経験からいうと、毎日少しずつのほうが続きます。'],
    examplesZh: ['从中国人的角度来说，日本大学的英语水平非常简单。', '从经验来说，每天一点点更容易坚持。'],
    furigana: 'ちゅうごくじんの たちばから いうと、にほんの だいがくの えいごレベルは すごく かんたんです。',
    commonMistakesZh: '直接说「私からいうと」不自然，要说「私の立場からいうと」「私の経験からいうと」',
    learnerFocus: '会议上表达意见的开场。中日双语者的独特视角を伝えるときに便利',
    similarPatterns: ['〜からすると', '〜から見ると', '〜にとって'],
    contrast: '「からいうと」「からすると」「から見ると」はほぼ同義（判断の観点）。「にとって」は評価対象',
    recognition: { promptZh: '「プロからいうと」的意思是？',
      options: ['从专业角度来说', '对专业人士说', '成为专业人士', '不是专业的'],
      answerIndex: 0, distractorReason: '「からいうと」表示判断的出发点',
      explanationZh: '判断の観点を示す' },
    production: { promptJa: '自分の経験からの意見を「〜からいうと」で言ってください。',
      promptZh: '用「〜からいうと」从你的经验发表意见。',
      expected: ['からいうと'], acceptable: ['経験からいうと', '立場からいうと'] },
    practice: { themeJa: '経験者として意見を言う', starterJa: '日本語学習の経験からいうと、何が一番大切ですか？',
      starterZh: '从你学日语的经验来说，什么最重要？', targetUse: '〜からいうと' },
    vocabularyLinks: ['fi-keiken', 'fi-iken'] }),
  g({ grammarId: 'n2g-032', pattern: '〜からこそ', reading: 'からこそ', unit: 3, zhSourceRowId: null,
    meaningJa: 'まさに〜だから（理由の強調）',
    explanationZh: '正因为…才…。强调理由',
    formation: '動詞・い形容詞普通形／な形容詞・名詞＋だ ＋からこそ',
    usageScene: '强调「正因为有这个原因」，多用于积极评价',
    nuance: '普通の「から」より理由を強く肯定する。感謝・誇りの文脈で映える',
    register: 'both',
    sourceExample: src('たくさん頑張ったからこそ、今のレベルに到達できたと思います。', '4da9d100870616dc'),
    examplesJa: ['たくさん頑張ったからこそ、今のレベルに到達できたと思います。',
                 '外国人だからこそ、気づける違いがあります。'],
    examplesZh: ['正因为付出了很多努力，才达到了现在的水平。', '正因为是外国人，才能注意到的差异。'],
    furigana: 'たくさん がんばったからこそ、いまの レベルに とうたつ できたと おもいます。',
    commonMistakesZh: '「こそ」の位置に注意。「からこそ」で一語。「こそから」は誤り',
    learnerFocus: '面接で「外国人だからこそ貢献できること」を語ると強い。ポジティブ変換の定番',
    similarPatterns: ['〜から', '〜おかげで'],
    contrast: '「から」＝中立の理由；「からこそ」＝理由の強調（誇り・感謝）；「おかげで」＝感謝',
    recognition: { promptZh: '「あなただからこそ頼みたい」的语气是？',
      options: ['正因为是你才想拜托（强调）', '随便谁都行', '不想拜托你', '已经拜托别人了'],
      answerIndex: 0, distractorReason: '「からこそ」强调该理由的特别性',
      explanationZh: '理由の強調' },
    production: { promptJa: '努力の成果を「〜からこそ」で言ってください。',
      promptZh: '用「〜からこそ」说努力带来的成果。',
      expected: ['からこそ'], acceptable: ['頑張ったからこそ'] },
    practice: { themeJa: '自分の強みをポジティブに語る',
      starterJa: '外国人だからこそできること、何があると思いますか？',
      starterZh: '正因为是外国人才能做到的事，你觉得有什么？', targetUse: '〜からこそ' },
    vocabularyLinks: ['fi-ganbaru', 'fi-keiken'] }),
  g({ grammarId: 'n2g-033', pattern: '〜からして', reading: 'からして', unit: 3, zhSourceRowId: null,
    meaningJa: '〜から判断して／〜をはじめとして',
    explanationZh: '光从…来看（就…）。举最基本的例子做判断',
    formation: '名詞 ＋からして',
    usageScene: '从外观、第一印象做判断',
    nuance: '「まず〜からもう…」という含み。批判にも褒めにも使う',
    register: 'both',
    sourceExample: src('この料理の色からして、絶対に辛い食べ物だと分かります。', 'a2780c5486618795'),
    examplesJa: ['この料理の色からして、絶対に辛い食べ物だと分かります。',
                 'あの店は、入口の雰囲気からして高そうです。'],
    examplesZh: ['光看这道菜的颜色，就知道绝对是辣的。', '那家店光看门口的氛围就显得很贵。'],
    furigana: 'この りょうりの いろからして、ぜったいに からい たべものだと わかります。',
    commonMistakesZh: '「からすると」（从…判断）と似るが、「からして」は「最初の一点からもう」という強調',
    learnerFocus: '第一印象を語る雑談で活躍。「名前からして面白い」など褒めにも使える',
    similarPatterns: ['〜からすると', '〜から見ると'],
    contrast: '「からして」＝代表例を挙げて「もうこの時点で」；「からすると」＝根拠からの推測',
    recognition: { promptZh: '「タイトルからして面白そう」是什么意思？',
      options: ['光看标题就觉得有意思', '觉得标题起得不太好', '还没有看到标题', '觉得标题太难懂了'],
      answerIndex: 0, distractorReason: '「からして」表示从最初的一点就能判断',
      explanationZh: '最初の一点からの判断' },
    production: { promptJa: '見た目からの判断を「〜からして」で言ってください。',
      promptZh: '用「〜からして」根据外观做判断。',
      expected: ['からして'], acceptable: ['色からして', '雰囲気からして'] },
    practice: { themeJa: '第一印象を話す', starterJa: '日本に来て、何からして違うと感じましたか？',
      starterZh: '来日本后，你从哪一点就感觉到不同？', targetUse: '〜からして' },
    vocabularyLinks: ['fi-wakaru', 'fi-kanjiru'] }),
  g({ grammarId: 'n2g-035', pattern: '〜からといって', reading: 'からといって', unit: 3, zhSourceRowId: null,
    meaningJa: '〜という理由だけでは（…とは限らない）',
    explanationZh: '虽说…但（并不能因此就…）。否定片面推论',
    formation: '動詞・い形容詞普通形／な形容詞・名詞＋だ ＋からといって',
    usageScene: '提醒不要以单一理由下结论',
    nuance: '後半は必ず部分否定・注意（〜とは限らない・〜わけではない・油断禁物）',
    register: 'both',
    sourceExample: src('褒められたからといって、油断は禁物です。', 'db77b8067c81d3cf'),
    examplesJa: ['褒められたからといって、油断は禁物です。',
                 '日本に住んでいるからといって、自然に上手になるわけではありません。'],
    examplesZh: ['虽说被夸奖了，但不能大意。', '虽说住在日本，也不会自然而然变好。'],
    furigana: 'ほめられたからと いって、ゆだんは きんもつです。',
    commonMistakesZh: '後半を肯定で終えると不成立。「〜からといって、嬉しいです」は誤り',
    learnerFocus: '「住んでいるだけでは上達しない」という学習の真実を語るのにぴったり',
    similarPatterns: ['〜だけで', '〜とは限らない'],
    contrast: '「からといって」＋部分否定はセット。「から」だけなら普通の理由',
    recognition: { promptZh: '「安いからといって」后面最自然的是？',
      options: ['買いすぎはよくない', 'たくさん買います', '嬉しいです', '高いです'],
      answerIndex: 0, distractorReason: '「からといって」后面要接否定或提醒',
      explanationZh: '片面推論の否定' },
    production: { promptJa: '「それだけでは十分でない」ことを「〜からといって」で言ってください。',
      promptZh: '用「〜からといって」表达仅凭该理由并不够。',
      expected: ['からといって'], acceptable: ['〜からといって〜わけではない'] },
    practice: { themeJa: '学習の思い込みを正す',
      starterJa: '「日本にいれば上手になる」と思いますか？「〜からといって」で答えてみましょう',
      starterZh: '你觉得「在日本就会变好」吗？用「〜からといって」回答', targetUse: '〜からといって' },
    vocabularyLinks: ['fi-benkyo', 'fi-nareru'] }),
  g({ grammarId: 'n2g-036', pattern: '〜からには', reading: 'からには', unit: 3, zhSourceRowId: null,
    meaningJa: '〜のだから、当然（決意・義務）',
    explanationZh: '既然…就（要）…。表示决心或当然的义务',
    formation: '動詞普通形 ＋からには',
    usageScene: '表明决心：既然开始了就要坚持到底',
    nuance: '「以上は」とほぼ同義でやや口語寄り。後半は決意・義務・当然',
    register: 'both',
    sourceExample: src('たくさん教えてもらったからには、試験に合格しなければなりません。', '38d4bee8cb9e8a5a'),
    examplesJa: ['たくさん教えてもらったからには、試験に合格しなければなりません。',
                 '日本で働くからには、敬語から逃げられません。'],
    examplesZh: ['既然承蒙教了这么多，就必须考过考试。', '既然要在日本工作，就避不开敬语。'],
    furigana: 'たくさん おしえて もらったからには、しけんに ごうかく しなければ なりません。',
    commonMistakesZh: '後半は決意・義務。「〜からには、たぶん行きます」のような弱い推量は不自然',
    learnerFocus: '「以上は」（書面寄り）とセットで覚える。決意表明の二大表現',
    similarPatterns: ['〜以上は', '〜のだから'],
    contrast: '「からには」＝口語寄りの決意；「以上は」＝書面寄り。意味はほぼ同じ',
    recognition: { promptZh: '「引き受けたからには」后面最自然的是？',
      options: ['最後までやります', 'やめるかもしれません', '知りません', '関係ありません'],
      answerIndex: 0, distractorReason: '「からには」后面接决心或义务',
      explanationZh: '既然…就要…' },
    production: { promptJa: '決意を「〜からには」で言ってください。',
      promptZh: '用「〜からには」表达决心。',
      expected: ['からには'], acceptable: ['始めたからには', '来たからには'] },
    practice: { themeJa: '決意を語る', starterJa: '日本に来たからには、何を成し遂げたいですか？',
      starterZh: '既然来了日本，你想完成什么？', targetUse: '〜からには' },
    vocabularyLinks: ['fi-ganbaru', 'fi-shigoto'] }),
  g({ grammarId: 'n2g-038', pattern: '〜代わりに', reading: 'かわりに', unit: 3, zhSourceRowId: 'n3row-83',
    meaningJa: '〜の代わりとして／〜する一方で（交換）',
    explanationZh: '代替…／作为交换…。N3の「かわりに」のN2用法（交換条件の交渉）',
    formation: '動詞普通形／名詞＋の ＋代わりに',
    usageScene: '交渉・取引の場面（〜する代わりに〜してほしい）',
    nuance: 'N2では「AするからにはBを求める」交換条件の用法が加わる',
    register: 'both',
    sourceExample: src('私があなたの授業を受ける代わりに、何がなんでも試験合格へ導いてください。', 'ca7e133b4307e464'),
    examplesJa: ['私があなたの授業を受ける代わりに、何がなんでも試験合格へ導いてください。',
                 '残業を引き受ける代わりに、明日は早く帰らせてください。'],
    examplesZh: ['我上你的课作为交换，请务必带我考过考试。', '我接下加班作为交换，请让我明天早点回去。'],
    furigana: 'わたしが あなたの じゅぎょうを うける かわりに、なにが なんでも しけんごうかくへ みちびいて ください。',
    commonMistakesZh: 'N3の「代替」用法との違い: N2では「交換条件の提示」ができる。交渉の道具になる',
    learnerFocus: '職場の交渉で「〜する代わりに〜してもらえますか」は角を立てずに条件を出せる',
    similarPatterns: ['〜代わりに（N3・代替）', '〜てもらう代わりに'],
    contrast: 'N3用法＝単純な代替；N2用法＝give and takeの交渉',
    recognition: { promptZh: '「手伝う代わりに、今度おごってください」是什么关系？',
      options: ['交换条件（我帮忙，你请客）', '单纯的替代没有交换', '直接拒绝了帮忙', '完全免费地帮忙'],
      answerIndex: 0, distractorReason: '这是「代わりに」的交换条件用法',
      explanationZh: 'give and take の交渉表現' },
    production: { promptJa: '交換条件を「〜代わりに」で提案してください。',
      promptZh: '用「〜代わりに」提出一个交换条件。',
      expected: ['代わりに'], acceptable: ['〜する代わりに'] },
    practice: { themeJa: '角を立てない交渉をする',
      starterJa: '同僚に何かを頼むとき、交換条件をどう出しますか？',
      starterZh: '拜托同事时，你会怎么提出交换条件？', targetUse: '〜代わりに' },
    vocabularyLinks: ['fi-soudan', 'fi-shigoto'] }),
  g({ grammarId: 'n2g-039', pattern: '〜気味', reading: 'ぎみ', unit: 3, zhSourceRowId: null,
    meaningJa: '少し〜の傾向がある（体調・状態）',
    explanationZh: '有点…、稍微有…的倾向（多为不好的状态）',
    formation: '動詞ます形／名詞 ＋気味',
    usageScene: '说明轻微的身体不适、状态倾向',
    nuance: '「疲れ気味」「風邪気味」「太り気味」が定番。軽い自覚症状',
    register: 'both',
    sourceExample: src('最近、忙しすぎて、疲れ気味です。', 'e6478c7275d5ea2f'),
    examplesJa: ['最近、忙しすぎて、疲れ気味です。', '少し風邪気味なので、今日は早めに休みます。'],
    examplesZh: ['最近太忙，有点疲惫。', '有点感冒的征兆，今天早点休息。'],
    furigana: 'さいきん、いそがしすぎて、つかれぎみです。',
    commonMistakesZh: '「がち」（頻度の傾向）と「気味」（今の軽い状態）の違い。「遅刻気味」より「遅刻しがち」が自然',
    learnerFocus: '体調を伝える語彙として実用度が高い。「風邪気味で…」は休暇連絡の定番',
    similarPatterns: ['〜がち', '〜っぽい'],
    contrast: '「気味」＝今の軽い状態；「がち」＝繰り返しの傾向；「っぽい」＝性質の印象',
    recognition: { promptZh: '「風邪気味です」是什么状态？',
      options: ['有点感冒的征兆', '感冒很严重', '感冒好了', '从不感冒'],
      answerIndex: 0, distractorReason: '「気味」表示轻微的状态倾向',
      explanationZh: '軽い自覚症状' },
    production: { promptJa: '軽い体調不良を「〜気味」で言ってください。',
      promptZh: '用「〜気味」说轻微的身体不适。',
      expected: ['気味'], acceptable: ['疲れ気味', '風邪気味'] },
    practice: { themeJa: '体調を軽く伝える', starterJa: '最近、何か「〜気味」なことはありますか？',
      starterZh: '最近有什么「有点…」的状态吗？', targetUse: '〜気味' },
    vocabularyLinks: ['fi-isogashii', 'fi-genki'] }),
  g({ grammarId: 'n2g-040', pattern: '〜（た）きりだ', reading: 'きりだ', unit: 3, zhSourceRowId: 'n3row-84',
    meaningJa: '〜して以来、そのままだ',
    explanationZh: '自从…就一直（没）…。N3「きり」の状態継続強調形',
    formation: '動詞た形 ＋きり（だ）',
    usageScene: '说明中断后一直没恢复的状态',
    nuance: '文末で「〜たきりだ」と言い切る形。N3では接続用法を学び、N2で文末用法を足す',
    register: 'both',
    sourceExample: src('骨折をしたきり、運動をしていないです。', 'dd38a779ade9a50d'),
    examplesJa: ['骨折をしたきり、運動をしていないです。', '大学を卒業したきり、英語は使っていません。'],
    examplesZh: ['自从骨折后就一直没运动。', '大学毕业后就再没用过英语。'],
    furigana: 'こっせつを したきり、うんどうを していないです。',
    commonMistakesZh: '後半は「していない」等の否定・不変化。肯定の継続には使えない',
    learnerFocus: '「ブランクがある」ことの説明に最適。再開の文脈（また始めたい）とセットで使うと前向き',
    similarPatterns: ['〜て以来', '〜まま'],
    contrast: '「たきり」＝中断の強調（否定続き）；「て以来」＝中立の起点；「まま」＝状態保持',
    recognition: { promptZh: '「会ったきりだ」是什么意思？',
      options: ['见过一次后就再没见', '之后还经常见面', '约好明天要见面', '从来不想见面'],
      answerIndex: 0, distractorReason: '「たきり」表示之后一直没有后续',
      explanationZh: '中断状態の継続' },
    production: { promptJa: 'ブランクがあることを「〜たきり」で言ってください。',
      promptZh: '用「〜たきり」说一件中断已久的事。',
      expected: ['きり'], acceptable: ['〜たきり'] },
    practice: { themeJa: '再開したいことを話す', starterJa: '「〜したきり、やっていない」ことはありますか？',
      starterZh: '有什么事是「做过一次后就再没做」的？', targetUse: '〜たきり' },
    vocabularyLinks: ['fi-owaru', 'fi-hajimeru'] }),
  g({ grammarId: 'n2g-041', pattern: '〜きる', reading: 'きる', unit: 3, zhSourceRowId: null,
    meaningJa: '最後まで完全に〜する',
    explanationZh: '…完、…到底。彻底完成',
    formation: '動詞ます形 ＋きる／きれる／きれない',
    usageScene: '强调坚持到最后：跑完全程、用完、卖光',
    nuance: '「〜きれない」（…不完）の否定可能形も頻出（食べきれない・数えきれない）',
    register: 'both',
    sourceExample: src('筋トレを最後の一回までやりきることができました。', '24624db504a065bb'),
    examplesJa: ['筋トレを最後の一回までやりきることができました。',
                 '量が多すぎて、一人では食べきれません。'],
    examplesZh: ['肌肉训练坚持做完了最后一次。', '量太多，一个人吃不完。'],
    furigana: 'きんトレを さいごの いっかいまで やりきることが できました。',
    commonMistakesZh: '「終わる」は自然に終わる、「きる」は意志で最後までやり抜く。達成感の有無が違う',
    learnerFocus: '「やりきった」は達成の実感を伝える言葉。面接・振り返りで強い',
    similarPatterns: ['〜終わる', '〜抜く'],
    contrast: '「きる」＝完全にやり終える；「抜く」＝困難を乗り越えて最後まで；「終わる」＝中立',
    recognition: { promptZh: '「食べきれない」是什么意思？',
      options: ['吃不完', '不想吃', '吃完了', '很好吃'],
      answerIndex: 0, distractorReason: '「きれない」表示无法彻底完成',
      explanationZh: '「〜きれない」= …不完' },
    production: { promptJa: '最後までやり遂げた経験を「〜きる」で言ってください。',
      promptZh: '用「〜きる」说一次坚持到底的经历。',
      expected: ['き'], acceptable: ['やりきった', '走りきった'] },
    practice: { themeJa: 'やり遂げた経験を話す', starterJa: '最後までやりきった経験はありますか？',
      starterZh: '有坚持做完到最后的经历吗？', targetUse: '〜きる' },
    vocabularyLinks: ['fi-ganbaru', 'fi-owaru'] }),
  g({ grammarId: 'n2g-042', pattern: '〜くせに', reading: 'くせに', unit: 3, zhSourceRowId: null,
    meaningJa: '〜のに（非難・軽蔑を込めて）',
    explanationZh: '明明…却…（带责备、轻蔑的语气）',
    formation: '動詞・い形容詞普通形／な形容詞＋な／名詞＋の ＋くせに',
    usageScene: '亲近的人之间的抱怨、自嘲',
    nuance: '「のに」より感情的で失礼。目上には絶対使わない。自嘲はOK',
    register: 'spoken',
    sourceExample: src('何時間も寝たくせに、まだ眠たいです。', 'a24c8a5c2c4b5cda'),
    examplesJa: ['何時間も寝たくせに、まだ眠たいです。', '知っているくせに、教えてくれませんでした。'],
    examplesZh: ['明明睡了好几个小时，却还困（自嘲）。', '明明知道，却不告诉我。'],
    furigana: 'なんじかんも ねたくせに、まだ ねむたいです。',
    commonMistakesZh: '対上司・客户使用は大失礼。「のに」に置き換えれば安全。自分への自嘲は親しみになる',
    learnerFocus: '聞き取れることが最優先（ドラマ・日常会話で頻出）。自分で使うのは自嘲から',
    similarPatterns: ['〜のに', '〜にもかかわらず'],
    contrast: '感情の強さ: 「にもかかわらず」（書面・中立）＜「のに」（不満）＜「くせに」（非難）',
    recognition: { promptZh: '「くせに」不能对谁使用？',
      options: ['上司や客', '親しい友人（冗談で）', '自分（自嘲）', '弟や妹'],
      answerIndex: 0, distractorReason: '「くせに」带责备语气，对上位者失礼',
      explanationZh: '目上には「のに」も慎重に、「くせに」は禁止' },
    production: { promptJa: '自分への自嘲を「〜くせに」で言ってください。',
      promptZh: '用「〜くせに」自嘲一下。',
      expected: ['くせに'], acceptable: ['〜たくせに'] },
    practice: { themeJa: '自嘲で笑いを取る', starterJa: '「〜したくせに、まだ〜」という自分の矛盾はありますか？',
      starterZh: '你有「明明…却还…」的自相矛盾吗？', targetUse: '〜くせに' },
    vocabularyLinks: ['fi-neru', 'fi-wasureru'] }),
  g({ grammarId: 'n2g-043', pattern: '〜くらい', reading: 'くらい', unit: 3, zhSourceRowId: null,
    meaningJa: '〜程度の（軽視・最低限）',
    explanationZh: '…这种程度（的话）。表示程度轻，「至少」「起码」',
    formation: '動詞普通形／名詞 ＋くらい（ぐらい）',
    usageScene: '说「这点小事我也会」、最低限の要求',
    nuance: '軽視の「くらい」は使い方次第で失礼にも謙遜にもなる',
    register: 'spoken',
    sourceExample: src('これくらいの簡単な曲であれば、私もピアノを弾くことができます。', 'd9196b9fec29b6c9'),
    examplesJa: ['これくらいの簡単な曲であれば、私もピアノを弾くことができます。',
                 'あいさつくらいは、日本語でできるようになりたいです。'],
    examplesZh: ['这种程度的简单曲子，我也能弹。', '至少打招呼，希望能用日语做到。'],
    furigana: 'これくらいの かんたんな きょくで あれば、わたしも ピアノを ひくことが できます。',
    commonMistakesZh: '他人に「これくらいできるでしょ」は失礼。自分に使えば謙遜になる',
    learnerFocus: '「〜くらいは」（至少…）は謙虚な目標設定に便利。「せめて」とセットで覚える',
    similarPatterns: ['〜ほど', '〜程度'],
    contrast: '「くらい」＝軽視・最低限（口語）；「ほど」＝程度の高さ；「程度」＝書面',
    recognition: { promptZh: '「名前くらいは書けます」的语气是？',
      options: ['谦虚地说至少会写名字', '自豪地夸耀写得很好', '说自己完全不会写字', '表示根本不想写字'],
      answerIndex: 0, distractorReason: '自分に使う「くらい」は謙遜',
      explanationZh: '最低限の謙遜表現' },
    production: { promptJa: '最低限できることを「〜くらい」で言ってください。',
      promptZh: '用「〜くらい」谦虚地说至少会做的事。',
      expected: ['くらい'], acceptable: ['〜くらいは', '〜ぐらい'] },
    practice: { themeJa: '謙遜しながらできることを言う',
      starterJa: '「これくらいならできます」と言えることはありますか？',
      starterZh: '有什么是你能说「这种程度的话我会」的？', targetUse: '〜くらい' },
    vocabularyLinks: ['fi-kantan', 'fi-kaku'] }),
  g({ grammarId: 'n2g-044', pattern: '〜ことか', reading: 'ことか', unit: 3, zhSourceRowId: null,
    meaningJa: 'どれほど〜だったことか（感嘆）',
    explanationZh: '多么…啊（感叹）。与疑问词呼应表达强烈感慨',
    formation: 'どれだけ／どんなに／何度 ＋〜た ＋ことか',
    usageScene: '回顾长期的辛苦、喜悦时的感叹',
    nuance: '書面・スピーチ調。「どんなに嬉しかったことか」で万感を込める',
    register: 'written',
    sourceExample: src('今日、筋トレをどれだけしたことか。疲れすぎてもう動けないです。', '0385dc750ca8d490'),
    examplesJa: ['今日、筋トレをどれだけしたことか。疲れすぎてもう動けないです。',
                 '合格の知らせを聞いて、どんなに嬉しかったことか。'],
    examplesZh: ['今天做了多少肌肉训练啊。累得已经动不了了。', '听到合格的消息，是多么高兴啊。'],
    furigana: 'きょう、きんトレを どれだけ したことか。つかれすぎて もう うごけないです。',
    commonMistakesZh: '必ず「どれだけ・どんなに・何度」等の疑問詞とセット。単独の「〜ことか」は不完全',
    learnerFocus: 'スピーチの山場で使うと感情が伝わる。読解では「感嘆」と識別できることが大事',
    similarPatterns: ['〜ことだろう', '〜ものだ'],
    contrast: '「ことか」＝感嘆（疑問詞と呼応）；「ことだろう」＝推量含み；「ものだ」＝しみじみ',
    recognition: { promptZh: '「何度あきらめようと思ったことか」的语气是？',
      options: ['感叹想放弃过多少次', '询问放弃的次数', '从没想过放弃', '已经放弃了'],
      answerIndex: 0, distractorReason: '疑問詞＋ことか是感叹，不是提问',
      explanationZh: '感嘆表現' },
    production: { promptJa: '長い努力の感慨を「どんなに〜ことか」で言ってください。',
      promptZh: '用「どんなに〜ことか」感叹长期的努力。',
      expected: ['ことか'], acceptable: ['どんなに〜ことか', 'どれだけ〜ことか'] },
    practice: { themeJa: '感慨を込めて振り返る',
      starterJa: '日本語学習で「どんなに大変だったことか」と思う瞬間はありましたか？',
      starterZh: '学日语时有过「多么不容易啊」的瞬间吗？', targetUse: 'どんなに〜ことか' },
    vocabularyLinks: ['fi-ganbaru', 'fi-ureshii'] }),
  g({ grammarId: 'n2g-045', pattern: '〜ことから', reading: 'ことから', unit: 3, zhSourceRowId: null,
    meaningJa: '〜という事実が理由・由来となって',
    explanationZh: '由于…（的事实）、因…而得名',
    formation: '動詞・い形容詞普通形／な形容詞＋な／名詞＋である ＋ことから',
    usageScene: '说明地名的由来、事情的起因（书面）',
    nuance: '客観的な由来・根拠。「から」より説明的で書面調',
    register: 'written',
    sourceExample: src('日本語と中国語ができることから、翻訳の仕事の依頼が来ました。', 'e84c2addf836ab1c'),
    examplesJa: ['日本語と中国語ができることから、翻訳の仕事の依頼が来ました。',
                 '桜の名所であることから、この駅は春に大変混雑します。'],
    examplesZh: ['由于会日语和中文，来了翻译工作的委托。', '因为是赏樱名胜，这个车站春天非常拥挤。'],
    furigana: 'にほんごと ちゅうごくごが できることから、ほんやくの しごとの いらいが きました。',
    commonMistakesZh: '主観的な理由には「から」、客観的な事実由来には「ことから」。ニュース・説明文の文体',
    learnerFocus: '双语能力がもたらす機会を語る例文がそのまま自己PRに使える',
    similarPatterns: ['〜ため', '〜ので'],
    contrast: '「ことから」＝事実由来（書面・説明）；「ため」＝書面の理由；「ので」＝丁寧な理由',
    recognition: { promptZh: '「ことから」的文体特点是？',
      options: ['书面的、说明性的', '非常随便的口语', '强硬的命令语气', '不确定的疑问语气'],
      answerIndex: 0, distractorReason: '「ことから」用于书面说明由来',
      explanationZh: '客観的由来の説明' },
    production: { promptJa: '自分の強みが生んだ機会を「〜ことから」で言ってください。',
      promptZh: '用「〜ことから」说你的优势带来的机会。',
      expected: ['ことから'], acceptable: ['できることから'] },
    practice: { themeJa: '強みと機会を結びつけて話す',
      starterJa: 'あなたの能力がきっかけで、何か機会が生まれたことはありますか？',
      starterZh: '你的能力带来过什么机会吗？', targetUse: '〜ことから' },
    vocabularyLinks: ['fi-nihongo', 'fi-shigoto'] }),
];
