// Phase 3P-5: N2文法完成draft Unit 4（原本No.46〜60・15文型）。
// rightsStatus: teacher_created_confirmed。原本例文をruntime使用可。
import type { N2GrammarDraft } from './n2GrammarDrafts';

const g = (p: Omit<N2GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey' | 'runtimeExampleOrigin'> & { reviewKey?: string; runtimeExampleOrigin?: N2GrammarDraft['runtimeExampleOrigin'] }): N2GrammarDraft =>
  ({ level: 'N2', route: 'n2-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, runtimeExampleOrigin: 'source_confirmed', ...p });

const src = (text: string, hash: string) =>
  ({ text, hash, rightsStatus: 'teacher_created_confirmed' as const });

export const N2_GRAMMAR_DRAFTS_UNIT4: N2GrammarDraft[] = [
  g({ grammarId: 'n2g-046', pattern: '〜ことだ（目標・大切なこと）', reading: 'ことだ', unit: 4, zhSourceRowId: null,
    meaningJa: '（目標・大事なのは）〜することだ',
    explanationZh: '（目标/重要的）是…。用「事」来概括目标或建议',
    formation: '動詞辞書形／ない形 ＋ことだ',
    usageScene: '陈述目标、给出建议（大切なのは〜ことだ）',
    nuance: '忠告用法（迷ったら休むことだ）は目上には使わない',
    register: 'both',
    sourceExample: src('私の目標は今の自分以上の日本語レベルになることです。', '4950617283940516'),
    examplesJa: ['私の目標は今の自分以上の日本語レベルになることです。',
                 '上達の近道は、毎日声に出すことです。'],
    examplesZh: ['我的目标是达到超过现在的日语水平。', '进步的捷径就是每天开口朗读。'],
    furigana: 'わたしの もくひょうは いまの じぶん いじょうの にほんごレベルに なることです。',
    commonMistakesZh: '「〜ことだ」の忠告用法は上から目線。対等・目下にのみ。目標文は誰にでも使える',
    learnerFocus: '目標を一文で言う型「私の目標は〜ことです」は自己紹介・面接の必須構文',
    similarPatterns: ['〜ことです', '〜べきだ'],
    contrast: '「ことだ」＝目標の名詞化／軽い忠告；「べきだ」＝強い当為',
    recognition: { promptZh: '「大切なのは続けることだ」是什么意思？',
      options: ['重要的是坚持', '不用坚持', '已经坚持了', '无法坚持'],
      answerIndex: 0, distractorReason: '「〜ことだ」把动作名词化后作出判断',
      explanationZh: '「大切なのは〜ことだ」= 重要的是…' },
    production: { promptJa: '今年の目標を「私の目標は〜ことです」で言ってください。',
      promptZh: '用「私の目標は〜ことです」说今年的目标。',
      expected: ['ことです'], acceptable: ['〜ことだ'] },
    practice: { themeJa: '目標を一文で言う', starterJa: 'あなたの今年の目標を一文で言ってみましょう',
      starterZh: '用一句话说说你今年的目标', targetUse: '〜ことです' },
    vocabularyLinks: ['fi-yotei', 'fi-tsuzukeru'] }),
  g({ grammarId: 'n2g-047', pattern: '〜ことだから', reading: 'ことだから', unit: 4, zhSourceRowId: null,
    meaningJa: 'よく知っている〜だから、きっと',
    explanationZh: '（正因为了解）…的为人，所以肯定…',
    formation: '人物名詞＋の ＋ことだから',
    usageScene: '基于对某人性格的了解做推测',
    nuance: '前提は「その人をよく知っている」。良い推測にも悪い推測にも使う',
    register: 'both',
    sourceExample: src('私の旦那のことだから、きっと、今日はお祝いをしてくれるだろう。', '5061728394051627'),
    examplesJa: ['私の旦那のことだから、きっと、今日はお祝いをしてくれるだろう。',
                 '几帳面な彼のことだから、もう準備は終わっているはずです。'],
    examplesZh: ['我老公那个人嘛，今天肯定会为我庆祝的。', '以他一丝不苟的性格，准备肯定已经做完了。'],
    furigana: 'わたしの だんなの ことだから、きっと、きょうは おいわいを して くれるだろう。',
    commonMistakesZh: '人物にしか使えない。「雨のことだから」は誤り。後半は推量（だろう・はずだ）',
    learnerFocus: '身近な人の性格を語る雑談の定番。「〜のことだから、きっと〜だろう」で丸ごと覚える',
    similarPatterns: ['〜だから', '〜はずだ'],
    contrast: '「ことだから」＝人物理解に基づく推量；「だから」＝一般の理由',
    recognition: { promptZh: '「時間に厳しい部長のことだから」后面最自然的是？',
      options: ['もう会議室にいるはずだ', '遅刻するだろう', '会議を忘れている', '来ないと思う'],
      answerIndex: 0, distractorReason: '性格（時間に厳しい）と整合する推測が続く',
      explanationZh: '人物理解 → 一致する推量' },
    production: { promptJa: 'よく知っている人の行動を「〜のことだから」で推測してください。',
      promptZh: '用「〜のことだから」推测你熟悉的人的行动。',
      expected: ['ことだから'], acceptable: ['〜のことだから'] },
    practice: { themeJa: '身近な人を推測で語る', starterJa: '家族や友達の「いつもの行動」を推測してみましょう',
      starterZh: '推测一下家人或朋友「一贯的行动」', targetUse: '〜のことだから' },
    vocabularyLinks: ['fi-kazoku', 'fi-tomodachi'] }),
  g({ grammarId: 'n2g-048', pattern: '〜ことなく', reading: 'ことなく', unit: 4, zhSourceRowId: null,
    meaningJa: '一度も〜しないで（書面）',
    explanationZh: '没有…、不曾…（书面）。「〜ないで」的正式形',
    formation: '動詞辞書形 ＋ことなく',
    usageScene: '书面描述「未曾中断」「没有放弃」',
    nuance: '「ないで」より硬く、達成の文脈で映える',
    register: 'written',
    sourceExample: src('今日は一度も休むことなく、文法の学習をしていました。', '6172839405162738'),
    examplesJa: ['今日は一度も休むことなく、文法の学習をしていました。',
                 '彼はあきらめることなく、挑戦を続けました。'],
    examplesZh: ['今天一次也没休息，一直在学语法。', '他不曾放弃，持续挑战。'],
    furigana: 'きょうは いちども やすむことなく、ぶんぽうの がくしゅうを していました。',
    commonMistakesZh: '会話では「〜ないで」「〜ずに」が自然。「ことなく」は書面・スピーチ向き',
    learnerFocus: '履歴書・スピーチで努力の継続を表すのに最適な書面表現',
    similarPatterns: ['〜ないで', '〜ずに'],
    contrast: '文体: 「ないで」（口語）＜「ずに」（中間）＜「ことなく」（書面）',
    recognition: { promptZh: '「ことなく」的文体是？',
      options: ['书面・正式', '非常口语', '幼儿用语', '命令形'],
      answerIndex: 0, distractorReason: '「ことなく」是「ないで」的书面形',
      explanationZh: '書面の否定継続' },
    production: { promptJa: '続けた努力を「〜ことなく」で言ってください。',
      promptZh: '用「〜ことなく」说你不曾中断的努力。',
      expected: ['ことなく'], acceptable: ['休むことなく', 'あきらめることなく'] },
    practice: { themeJa: '継続をフォーマルに語る', starterJa: 'あきらめることなく続けていることはありますか？',
      starterZh: '有什么是你不曾放弃一直坚持的？', targetUse: '〜ことなく' },
    vocabularyLinks: ['fi-tsuzukeru', 'fi-ganbaru'] }),
  g({ grammarId: 'n2g-050', pattern: '〜ことはない', reading: 'ことはない', unit: 4, zhSourceRowId: null,
    meaningJa: '〜する必要はない（励まし）',
    explanationZh: '没必要…、用不着…（多用于安慰鼓励）',
    formation: '動詞辞書形 ＋ことはない',
    usageScene: '安慰別人：不用着急、不用道歉',
    nuance: '「焦ることはない」「謝ることはない」が定番。優しい響き',
    register: 'both',
    sourceExample: src('今、点数が取れないからといって、焦ることはないですよ。', '7283940516273849'),
    examplesJa: ['今、点数が取れないからといって、焦ることはないですよ。',
                 'あなたが謝ることはありません。'],
    examplesZh: ['虽说现在拿不到分数，也没必要着急。', '你没有必要道歉。'],
    furigana: 'いま、てんすうが とれないからと いって、あせることは ないですよ。',
    commonMistakesZh: '「〜たことはない」（没做过・経験）と混同しない。辞書形＋ことはない＝没必要',
    learnerFocus: '励ましの決まり文句。「心配することはないですよ」は人間関係を柔らかくする',
    similarPatterns: ['〜必要はない', '〜なくてもいい'],
    contrast: '「ことはない」＝励ましの「不必」；「なくてもいい」＝許可寄り；「必要はない」＝事務的',
    recognition: { promptZh: '「急ぐことはないですよ」的语气是？',
      options: ['安慰对方不用急', '催促对方快点', '责备对方太慢', '自己在着急'],
      answerIndex: 0, distractorReason: '「ことはない」是温柔的「没必要」',
      explanationZh: '励ましの表現' },
    production: { promptJa: '落ち込む友達を「〜ことはない」で励ましてください。',
      promptZh: '用「〜ことはない」安慰失落的朋友。',
      expected: ['ことはない'], acceptable: ['焦ることはない', '心配することはない'] },
    practice: { themeJa: '友達を励ます', starterJa: '試験に落ちた友達に、何と声をかけますか？',
      starterZh: '朋友考试没过，你会怎么安慰？', targetUse: '〜ことはない' },
    vocabularyLinks: ['fi-komaru', 'fi-genki'] }),
  g({ grammarId: 'n2g-051', pattern: '〜際は', reading: 'さいは', unit: 4, zhSourceRowId: null,
    meaningJa: '〜するとき（改まった場面）',
    explanationZh: '在…之际、…的时候（正式）',
    formation: '動詞辞書形／た形／名詞＋の ＋際（は・に）',
    usageScene: '公告、商务邮件、指南中的「时候」',
    nuance: '「とき」の改まった形。アナウンス・掲示の定番',
    register: 'written',
    sourceExample: src('旅行に行く際は、エアコンの電源を切ったか確認しましょう。', '8394051627384950'),
    examplesJa: ['旅行に行く際は、エアコンの電源を切ったか確認しましょう。',
                 'お降りの際は、足元にご注意ください。'],
    examplesZh: ['去旅行时，要确认空调电源是否已关。', '下车时请注意脚下。'],
    furigana: 'りょこうに いく さいは、エアコンの でんげんを きったか かくにん しましょう。',
    commonMistakesZh: '日常会話で多用すると硬すぎる。「明日会う際は」より「明日会うときは」が自然',
    learnerFocus: '電車のアナウンス「お降りの際は」は毎日聞く表現。聞き取れると生活が楽',
    similarPatterns: ['〜とき', '〜にあたって'],
    contrast: '「とき」＝中立；「際」＝改まり；「にあたって」＝節目の開始',
    recognition: { promptZh: '「お問い合わせの際は」多出现在哪里？',
      options: ['公司通知・网站', '朋友的聊天', '孩子的日记', '歌词'],
      answerIndex: 0, distractorReason: '「際」是正式场合的「时候」',
      explanationZh: '改まった場面の「とき」' },
    production: { promptJa: '案内文を「〜際は」で書いてください。',
      promptZh: '用「〜際は」写一句指南。',
      expected: ['際'], acceptable: ['〜際は', '〜際に'] },
    practice: { themeJa: '案内文を読める・書ける', starterJa: '駅や店の「〜際は」の掲示を見たことがありますか？',
      starterZh: '你见过车站或店里「〜際は」的告示吗？', targetUse: '〜際は' },
    vocabularyLinks: ['fi-kakunin', 'fi-densha'] }),
  g({ grammarId: 'n2g-052', pattern: '〜最中に', reading: 'さいちゅうに', unit: 4, zhSourceRowId: null,
    meaningJa: 'ちょうど〜している途中に（邪魔が入る）',
    explanationZh: '正在…的时候（偏偏发生了别的事）',
    formation: '動詞ている形／名詞＋の ＋最中に',
    usageScene: '正开会时手机响了、正洗澡时来快递',
    nuance: '進行の真っ只中＋邪魔・中断の含み。「〜ているとき」より劇的',
    register: 'both',
    sourceExample: src('勉強をしている最中に、友達から連絡がきて、集中できませんでした。', '9405162738495061'),
    examplesJa: ['勉強をしている最中に、友達から連絡がきて、集中できませんでした。',
                 '会議の最中に、スマホが鳴ってしまいました。'],
    examplesZh: ['正在学习时朋友来联系，没法集中。', '正开会时手机响了。'],
    furigana: 'べんきょうを している さいちゅうに、ともだちから れんらくが きて、しゅうちゅう できませんでした。',
    commonMistakesZh: '「最中」の後半は多く「邪魔・トラブル」。良い出来事には「〜ているときに」が自然',
    learnerFocus: '「会議の最中にすみません」は割り込むときのお詫びの定番',
    similarPatterns: ['〜ているときに', '〜途中で'],
    contrast: '「最中に」＝真っ只中＋中断の含み；「ときに」＝中立；「途中で」＝進行の中間点',
    recognition: { promptZh: '「食事の最中に電話が来た」的语感是？',
      options: ['正吃饭时偏偏来电话（被打扰）', '吃完饭后来电话', '正好想接电话', '没有来电话'],
      answerIndex: 0, distractorReason: '「最中に」含被打扰的语感',
      explanationZh: '進行中の邪魔' },
    production: { promptJa: '邪魔が入った経験を「〜最中に」で言ってください。',
      promptZh: '用「〜最中に」说一次被打扰的经历。',
      expected: ['最中'], acceptable: ['〜最中に'] },
    practice: { themeJa: '集中を邪魔された話をする', starterJa: '何かの最中に邪魔が入ったことはありますか？',
      starterZh: '有正做事时被打扰的经历吗？', targetUse: '〜最中に' },
    vocabularyLinks: ['fi-renraku', 'fi-benkyo'] }),
  g({ grammarId: 'n2g-053', pattern: '〜ざるを得ない', reading: 'ざるをえない', unit: 4, zhSourceRowId: null,
    meaningJa: '（仕方なく）〜しなければならない',
    explanationZh: '不得不…、只能…（无奈）',
    formation: '動詞ない形の語幹 ＋ざるを得ない（する→せざるを得ない）',
    usageScene: '说明被形势所迫的选择',
    nuance: '書面調。無念さ・不本意の含み。「するしかない」より硬い',
    register: 'written',
    matchKeys: ['ざるを得'],
    sourceExample: src('残りの2ヶ月で合格するには、効率よく勉強せざるを得ないです。', '0516273849506172'),
    examplesJa: ['残りの2ヶ月で合格するには、効率よく勉強せざるを得ないです。',
                 '台風のため、旅行は中止せざるを得ませんでした。'],
    examplesZh: ['要在剩下两个月内合格，不得不高效学习。', '因为台风，旅行不得不中止。'],
    furigana: 'のこりの にかげつで ごうかく するには、こうりつよく べんきょう せざるを えないです。',
    commonMistakesZh: '「する」は「せざるを得ない」（しざる×）。この変化だけ特殊なので丸暗記',
    learnerFocus: 'ニュース・ビジネス文書頻出。「値上げせざるを得ない」等、読解での認識が先決',
    similarPatterns: ['〜しかない', '〜ほかない'],
    contrast: '「ざるを得ない」＝書面・無念；「しかない」＝口語；「ほかない」＝中間',
    recognition: { promptZh: '「中止せざるを得ない」的心情是？',
      options: ['无奈、不情愿地只能中止', '高兴地中止', '拒绝中止', '与中止无关'],
      answerIndex: 0, distractorReason: '「ざるを得ない」含不本意',
      explanationZh: '仕方なく…する' },
    production: { promptJa: '仕方なくした選択を「〜ざるを得ない」で言ってください。',
      promptZh: '用「〜ざるを得ない」说一次无奈的选择。',
      expected: ['ざるを得'], acceptable: ['〜ざるを得ない', 'せざるを得ない'] },
    practice: { themeJa: '不本意な決断を語る', starterJa: '仕方なく何かを決めた経験はありますか？',
      starterZh: '有过无奈之下做决定的经历吗？', targetUse: '〜ざるを得ない' },
    vocabularyLinks: ['fi-kimeru', 'fi-muri'] }),
  g({ grammarId: 'n2g-054', pattern: '〜次第', reading: 'しだい', unit: 4, zhSourceRowId: null,
    meaningJa: '①〜によって決まる ②〜したらすぐ',
    explanationZh: '①取决于… ②一…立刻（就）',
    formation: '①名詞＋次第だ ②動詞ます形＋次第',
    usageScene: '①归结责任・条件 ②商务承诺（确认后立刻联系）',
    nuance: '②「確認でき次第ご連絡します」はビジネスメールの黄金定型',
    register: 'written',
    sourceExample: src('この会社が生き残るかどうかは、社長次第です。', '1627384950617283'),
    examplesJa: ['この会社が生き残るかどうかは、社長次第です。',
                 '詳細が分かり次第、ご連絡いたします。'],
    examplesZh: ['这家公司能否存活，取决于社长。', '一旦了解详情，立刻与您联系。'],
    furigana: 'この かいしゃが いきのこるか どうかは、しゃちょう しだいです。',
    commonMistakesZh: '①は名詞接続、②はます形接続。接続で意味が変わる二刀流に注意',
    learnerFocus: '「〜次第ご連絡します」を使えるとビジネスメールが一気にプロらしくなる',
    similarPatterns: ['〜によって', '〜たらすぐ'],
    contrast: '①「次第だ」＝決定要因；②「〜次第」＝即時の対応（丁寧）',
    recognition: { promptZh: '「分かり次第連絡します」是什么意思？',
      options: ['一知道就立刻联系', '可能不联系', '明天联系', '已经联系了'],
      answerIndex: 0, distractorReason: 'ます形＋次第 = 一…立刻',
      explanationZh: 'ビジネスの即応表現' },
    production: { promptJa: 'ビジネスメールの返事を「〜次第」で書いてください。',
      promptZh: '用「〜次第」写一句商务邮件回复。',
      expected: ['次第'], acceptable: ['分かり次第', '確認でき次第'] },
    practice: { themeJa: 'ビジネスの約束をする', starterJa: '「確認してから連絡する」を丁寧に言ってみましょう',
      starterZh: '试着礼貌地说「确认后联系」', targetUse: '〜次第' },
    vocabularyLinks: ['fi-renraku', 'fi-kakunin'] }),
  g({ grammarId: 'n2g-056', pattern: '〜末に', reading: 'すえに', unit: 4, zhSourceRowId: null,
    meaningJa: 'いろいろ〜した結果、最終的に',
    explanationZh: '经过…（一番周折）最终…',
    formation: '動詞た形／名詞＋の ＋末に',
    usageScene: '说明经过长时间考虑后的决定',
    nuance: '過程の長さ・苦労を含む。「あげく」と違い良い結果にも使える',
    register: 'written',
    sourceExample: src('色々考えた末にN1の試験にもチャレンジすることにしました。', '2738495061728394'),
    examplesJa: ['色々考えた末にN1の試験にもチャレンジすることにしました。',
                 '議論の末に、計画は一部変更されました。'],
    examplesZh: ['再三考虑之后，决定也挑战N1考试。', '讨论到最后，计划做了部分修改。'],
    furigana: 'いろいろ かんがえた すえに エヌワンの しけんにも チャレンジ することに しました。',
    commonMistakesZh: '「あげく」は負面結局限定、「末に」は良い結果もOK。前向きな決断は「末に」',
    learnerFocus: '「考えた末に」は重要な決断を語るときの定番。転職・留学の説明に使える',
    similarPatterns: ['〜あげく', '〜結果'],
    contrast: '「末に」＝長い過程＋どちらの結果も可；「あげく」＝負面限定；「結果」＝中立',
    recognition: { promptZh: '「悩んだ末に留学を決めた」的语感是？',
      options: ['经过长期烦恼后最终决定（正面）', '烦恼后放弃了', '没有烦恼', '被迫决定'],
      answerIndex: 0, distractorReason: '「末に」表示长过程后的最终决定',
      explanationZh: '長い過程の末の決断' },
    production: { promptJa: '悩んで決めたことを「〜末に」で言ってください。',
      promptZh: '用「〜末に」说一次深思后的决定。',
      expected: ['末に'], acceptable: ['考えた末に', '悩んだ末に'] },
    practice: { themeJa: '大きな決断の経緯を話す', starterJa: '長く悩んで決めたことはありますか？',
      starterZh: '有经过长期烦恼才决定的事吗？', targetUse: '〜末に' },
    vocabularyLinks: ['fi-kangaeru', 'fi-kimeru'] }),
  g({ grammarId: 'n2g-057', pattern: '〜ずにすむ', reading: 'ずにすむ', unit: 4, zhSourceRowId: null,
    meaningJa: '〜しなくてよくなる（助かった）',
    explanationZh: '不用…就解决了、免于…（松了口气）',
    formation: '動詞ない形の語幹 ＋ずにすむ（する→せずにすむ）',
    usageScene: '说明幸运地避免了麻烦',
    nuance: '「助かった」という安堵の含み。「〜なくてすむ」も同義',
    register: 'both',
    matchKeys: ['ずにすみ', 'ずに済'],
    sourceExample: src('雨が止んだので、傘を持たずにすみました。', '3849506172839405'),
    examplesJa: ['雨が止んだので、傘を持たずにすみました。',
                 '早めに気づいたので、大きなミスにならずにすみました。'],
    examplesZh: ['因为雨停了，不用带伞了。', '因为发现得早，没有酿成大错。'],
    furigana: 'あめが やんだので、かさを もたずに すみました。',
    commonMistakesZh: '「〜ずにはいられない」（禁不住要…）と形が似るが意味は全く別。混同注意',
    learnerFocus: '「〜ずにすんだ」は「幸好没…」の安堵。トラブル回避の報告に便利',
    similarPatterns: ['〜なくてすむ', '〜ないで済む'],
    contrast: '「ずにすむ」＝回避できた安堵；「なくてもいい」＝単なる不要',
    recognition: { promptZh: '「並ばずにすんだ」的心情是？',
      options: ['庆幸不用排队', '不得不排队', '想排队', '排了很久'],
      answerIndex: 0, distractorReason: '「ずにすむ」表示避免了麻烦的安堵',
      explanationZh: '回避の安堵' },
    production: { promptJa: '運よく避けられたことを「〜ずにすみました」で言ってください。',
      promptZh: '用「〜ずにすみました」说一次幸运避开的麻烦。',
      expected: ['ずにすみ'], acceptable: ['〜ずにすんだ'] },
    practice: { themeJa: '「助かった」経験を話す', starterJa: '最近、「〜せずにすんだ」ことはありますか？',
      starterZh: '最近有什么「幸好不用做」的事吗？', targetUse: '〜ずにすみました' },
    vocabularyLinks: ['fi-komaru', 'fi-mondai'] }),
  g({ grammarId: 'n2g-058', pattern: '〜ずにはいられない', reading: 'ずにはいられない', unit: 4, zhSourceRowId: null,
    meaningJa: 'どうしても〜してしまう（抑えられない）',
    explanationZh: '禁不住…、不由得…（无法抑制）',
    formation: '動詞ない形の語幹 ＋ずにはいられない（する→せずにはいられない）',
    usageScene: '描述抑制不住的感情、冲动',
    nuance: '感情の自然な高まり。書面調',
    register: 'written',
    matchKeys: ['ずにはいられ'],
    sourceExample: src('何回も不合格だった場合、自信を無くさずにはいられないです。', '4950617283940517'),
    examplesJa: ['何回も不合格だった場合、自信を無くさずにはいられないです。',
                 'あの映画を見ると、泣かずにはいられません。'],
    examplesZh: ['多次不合格的话，禁不住会失去自信。', '看那部电影，就忍不住要哭。'],
    furigana: 'なんかいも ふごうかく だった ばあい、じしんを なくさずには いられないです。',
    commonMistakesZh: '「ずにすむ」（免于）と混同注意。「いられない」＝我慢できない、が核',
    learnerFocus: '感想文・レビューで「感動せずにはいられない」は強い賛辞になる',
    similarPatterns: ['〜てしまう', '〜ないではいられない'],
    contrast: '「ずにはいられない」＝抑えられない衝動；「てしまう」＝結果の後悔・完了',
    recognition: { promptZh: '「笑わずにはいられなかった」是什么意思？',
      options: ['忍不住笑了', '忍住没笑', '不想笑', '笑不出来'],
      answerIndex: 0, distractorReason: '「ずにはいられない」= 无法抑制',
      explanationZh: '抑えられない感情' },
    production: { promptJa: '抑えられなかった感情を「〜ずにはいられない」で言ってください。',
      promptZh: '用「〜ずにはいられない」说一次抑制不住的感情。',
      expected: ['ずにはいられ'], acceptable: ['〜ずにはいられません'] },
    practice: { themeJa: '感情が動いた作品を語る', starterJa: '泣かずにはいられなかった映画や動画はありますか？',
      starterZh: '有让你忍不住落泪的电影或视频吗？', targetUse: '〜ずにはいられない' },
    vocabularyLinks: ['fi-kanjiru', 'fi-kanashii'] }),
  g({ grammarId: 'n2g-059', pattern: '〜せいで', reading: 'せいで', unit: 4, zhSourceRowId: 'n3row-104',
    meaningJa: '〜が原因で（悪い結果）',
    explanationZh: '都怪…、因为…（导致坏结果）',
    formation: '動詞普通形／名詞＋の ＋せいで',
    usageScene: '说明坏结果的原因（含归咎）',
    nuance: 'N3でも学ぶ。N2では「せいか」（也许是因为）等の派生も扱う',
    register: 'both',
    sourceExample: src('昨日の地震のせいで、電車が遅延しています。', '5061728394051628'),
    examplesJa: ['昨日の地震のせいで、電車が遅延しています。',
                 '寝不足のせいか、今日は集中できません。'],
    examplesZh: ['都怪昨天的地震，电车在晚点。', '也许是因为睡眠不足，今天无法集中。'],
    furigana: 'きのうの じしんの せいで、でんしゃが ちえん しています。',
    commonMistakesZh: '人に対して使うと非難になる。「〜せいか」なら推測でトーンダウンできる',
    learnerFocus: '「せいで」（断定の帰責）と「せいか」（推測）の使い分けで角が立たない',
    similarPatterns: ['〜おかげで', '〜ため'],
    contrast: '「せいで」＝負面帰責；「おかげで」＝正面；「せいか」＝推測の帰責',
    recognition: { promptZh: '「寝不足のせいか、頭が痛い」的「せいか」表示？',
      options: ['也许是因为（推测）', '一定是因为（断定）', '多亏了', '为了'],
      answerIndex: 0, distractorReason: '「せいか」是弱化的推测归因',
      explanationZh: '推測の帰責' },
    production: { promptJa: '悪い結果の原因を「〜せいで」で言ってください。',
      promptZh: '用「〜せいで」说明坏结果的原因。',
      expected: ['せい'], acceptable: ['〜のせいで', '〜せいか'] },
    practice: { themeJa: '不調の原因を推測する', starterJa: '最近の不調、何のせいだと思いますか？',
      starterZh: '最近的不顺，你觉得是因为什么？', targetUse: '〜せいで／せいか' },
    vocabularyLinks: ['fi-densha', 'fi-riyuu'] }),
  g({ grammarId: 'n2g-060', pattern: '〜たいばかりに', reading: 'たいばかりに', unit: 4, zhSourceRowId: null,
    meaningJa: '〜したい一心で（無理までした）',
    explanationZh: '就因为一心想…（甚至做了勉强的事）',
    formation: '動詞ます形＋たい ＋ばかりに',
    usageScene: '说明为了一个愿望做出的大胆行动',
    nuance: '後半は「そこまでした」という無理・犠牲。悪い結果が続くことも多い',
    register: 'written',
    sourceExample: src('あの俳優に会いたいばかりに、イタリアへ旅行をすることを決めました。', '6172839405162739'),
    examplesJa: ['あの俳優に会いたいばかりに、イタリアへ旅行をすることを決めました。',
                 '早く帰りたいばかりに、昼休みも仕事をしました。'],
    examplesZh: ['就因为一心想见那位演员，决定去意大利旅行。', '就因为想早点回家，连午休都在工作。'],
    furigana: 'あの はいゆうに あいたい ばかりに、イタリアへ りょこうを することを きめました。',
    commonMistakesZh: '「ばかりに」単体は「就因为…（导致坏结果）」。「たいばかりに」は願望が動機',
    learnerFocus: '推し活・目標のための無茶を語る、感情のこもった表現。雑談で盛り上がる',
    similarPatterns: ['〜ばかりに', '〜あまり'],
    contrast: '「たいばかりに」＝願望が動機の無理；「あまり」＝感情の過度；「ばかりに」＝原因＋悪結果',
    recognition: { promptZh: '「会いたいばかりに」暗示什么？',
      options: ['为见面甚至做了勉强的事', '不想见面', '偶然见到了', '见面很容易'],
      answerIndex: 0, distractorReason: '「たいばかりに」表示愿望驱动的过度行动',
      explanationZh: '願望ゆえの無理' },
    production: { promptJa: '何かをしたい一心でした無理を「〜たいばかりに」で言ってください。',
      promptZh: '用「〜たいばかりに」说一次为愿望而做的勉强。',
      expected: ['たいばかりに'], acceptable: ['〜たいばかりに'] },
    practice: { themeJa: '推し・目標のための無茶を話す', starterJa: '何かをしたいばかりに、無理をしたことはありますか？',
      starterZh: '有过一心想做某事而勉强自己的经历吗？', targetUse: '〜たいばかりに' },
    vocabularyLinks: ['fi-kyoumi', 'fi-kimeru'] }),
];
