// Phase 3P-5: N2文法完成draft Unit 11（No.151〜165のうち14文型。162（矢先に）は同義判断待ち）。
// rightsStatus: teacher_created_confirmed。第1例文=原本（無改変）、第2例文=独自（実生活）。
// 158（ものだから）のみ原本例文が回想「たものだ」用法のため、runtime例文は独自作成（original_authored）。
import type { N2GrammarDraft } from './n2GrammarDrafts';

const g = (p: Omit<N2GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey' | 'runtimeExampleOrigin'> & { reviewKey?: string; runtimeExampleOrigin?: N2GrammarDraft['runtimeExampleOrigin'] }): N2GrammarDraft =>
  ({ level: 'N2', route: 'n2-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, runtimeExampleOrigin: 'source_confirmed', ...p });

const src = (text: string, hash: string) =>
  ({ text, hash, rightsStatus: 'teacher_created_confirmed' as const });

export const N2_GRAMMAR_DRAFTS_UNIT11: N2GrammarDraft[] = [
  g({ grammarId: 'n2g-151', pattern: '〜ままに', reading: 'ままに', unit: 11, zhSourceRowId: null,
    meaningJa: '〜の状態のまま／〜に任せて',
    explanationZh: '保持…的状态（着）；任凭…摆布。①开着灯睡着（原样不动）②任人指使、随心所欲',
    formation: '動詞た形＋まま（に）／名詞＋の＋まま／言われる・思う＋ままに',
    usageScene: '开着灯睡着了、任凭店员推销就买了、随心所欲地旅行',
    nuance: '「言われるままに」＝毫无主见地照做。「足の向くままに」＝随性而行的自由',
    register: 'both',
    matchKeys: ['まま'],
    sourceExample: src('気合いで勉強をしていたら、電気をつけたまま、寝てしまいました。', '3b94ac50a7c2c012'),
    examplesJa: ['気合いで勉強をしていたら、電気をつけたまま、寝てしまいました。',
                 '店員に言われるままに、高い教材を買ってしまいました。'],
    examplesZh: ['铆足劲学习，结果开着灯就睡着了。', '任凭店员一说，就买下了昂贵的教材。'],
    furigana: 'きあいで べんきょうを していたら、でんきを つけたまま、ねてしまいました。',
    commonMistakesZh: '中文「开着灯」的「着」＝「たまま」。「言われるままに買った」暗含「没主见」的反省，夸自主选择时不能用',
    learnerFocus: '「靴のまま」「つけたまま」是生活必需表达。进屋忘脱鞋被提醒「靴のままはダメ」，先听懂再会说',
    similarPatterns: ['〜たまま', '〜に任せて'],
    contrast: '「ままに」＝状態保持／成り行き任せ；「に任せて」＝判断を委ねる；「〜っぱなし」＝放置への非難',
    recognition: { promptZh: '「言われるままに契約した」的语气是？',
      options: ['没多想就任人摆布签了约', '仔细考虑后自主签约', '拒绝了签约', '让对方签了约'],
      answerIndex: 0, distractorReason: '「言われるままに」＝被动地照办、缺乏主见',
      explanationZh: '任凭他人指使的被动感' },
    production: { promptJa: '状態をそのままにしてしまった失敗を「〜まま」で言ってください。',
      promptZh: '用「〜まま」说一次保持原样造成的小失败。',
      expected: ['まま'], acceptable: ['〜たまま', '言われるままに'] },
    practice: { themeJa: 'うっかり話をする', starterJa: '何かを「つけたまま」「開けたまま」にしてしまった経験は？',
      starterZh: '有没有「开着…就…」的粗心经历？', targetUse: '〜ままに' },
    vocabularyLinks: ['fi-neru', 'fi-kau'] }),
  g({ grammarId: 'n2g-152', pattern: '〜もかまわず', reading: 'もかまわず', unit: 11, zhSourceRowId: null,
    meaningJa: '〜を気にしないで（普通は気にすることなのに）',
    explanationZh: '不顾…、不在乎…。对通常该在意的事毫不介意地行动',
    formation: '名詞／動詞辞書形＋の ＋もかまわず',
    usageScene: '不顾淋湿继续跑、不顾旁人眼光大声哭、不顾形象大笑',
    nuance: '「人目もかまわず」（不顾旁人眼光）是常用说法，适合描写入迷和拼命的样子',
    register: 'written',
    sourceExample: src('雨の中、びしょ濡れになるのもかまわず、走り続けました。', '067a6b6c894e01ae'),
    examplesJa: ['雨の中、びしょ濡れになるのもかまわず、走り続けました。',
                 '人目もかまわず、大声で泣いてしまいました。'],
    examplesZh: ['雨中不顾浑身湿透，一直跑了下去。', '不顾旁人眼光，放声大哭了。'],
    furigana: 'あめのなか、びしょぬれに なるのも かまわず、はしりつづけました。',
    commonMistakesZh: '和「にもかかわらず」（尽管）不同：「もかまわず」的主语是人、主动无视；「にもかかわらず」是客观转折。「服が汚れるのもかまわず」注意「の」不能丢',
    learnerFocus: '描写拼命瞬间的画面感表达：「なりふりかまわず頑張った」（不顾形象地拼）也是好用的惯用形',
    similarPatterns: ['〜を気にせず', '〜にもかかわらず'],
    contrast: '「もかまわず」＝本人が意に介さない；「を気にせず」＝中立の無視；「にもかかわらず」＝状況の逆接',
    recognition: { promptZh: '「服が汚れるのもかまわず、子供を助けた」体现了什么？',
      options: ['顾不上弄脏衣服去救孩子', '因为怕弄脏衣服所以没有去救', '先换好了衣服然后才去救孩子', '让孩子自己把衣服弄得很脏'],
      answerIndex: 0, distractorReason: '「もかまわず」＝不在乎该在意的事而行动',
      explanationZh: '奋不顾身的无视' },
    production: { promptJa: '夢中で何かをした経験を「〜もかまわず」で言ってください。',
      promptZh: '用「〜もかまわず」说一次奋不顾身的经历。',
      expected: ['もかまわず'], acceptable: ['人目もかまわず'] },
    practice: { themeJa: '夢中になった瞬間を語る', starterJa: '周りを気にせず夢中になったことはありますか？',
      starterZh: '有没有不顾周围、全情投入的时刻？', targetUse: '〜もかまわず' },
    vocabularyLinks: ['fi-kimochi', 'fi-tsuzukeru'] }),
  g({ grammarId: 'n2g-153', pattern: '〜も当然だ', reading: 'もとうぜんだ', unit: 11, zhSourceRowId: null,
    meaningJa: '〜のも当たり前だ（理由を認める）',
    explanationZh: '…也是理所当然的。基于前项理由，后项结果毫不奇怪',
    formation: '動詞・い形容詞普通形＋の／な形容詞＋なの／名詞＋なの ＋も当然だ',
    usageScene: '认可努力后的进步、承认长期不打扫落满灰、理解他人的愤怒',
    nuance: '带有认可、接受的语气。「怒るのも当然だ」（生气也是应该的）也能用来表示共情',
    register: 'spoken',
    sourceExample: src('ずっと掃除をしていなかったら、ほこりだらけになるのも当然です。', 'b662c94be6f3601e'),
    examplesJa: ['ずっと掃除をしていなかったら、ほこりだらけになるのも当然です。',
                 '毎日練習しているのだから、上手になるのも当然です。'],
    examplesZh: ['一直不打扫的话，落满灰尘也是当然的。', '每天都在练习，进步也是理所当然的。'],
    furigana: 'ずっと そうじを していなかったら、ほこりだらけに なるのも とうぜんです。',
    commonMistakesZh: '「のも当然だ」的「の」（名词化）容易丢：「上手になるも当然だ」×。共情用法「あなたが怒るのも当然です」很暖，背下来',
    learnerFocus: '安慰人时的共情句：「悔しいと思うのも当然ですよ」。承认对方情绪合理，是高情商日语',
    similarPatterns: ['〜のも無理はない', '〜わけだ'],
    contrast: '「も当然だ」＝理の当然の承認；「のも無理はない」＝同情的な納得；「わけだ」＝理屈の合点',
    recognition: { promptZh: '朋友被骗了很生气，想表示理解，说哪句最合适？',
      options: ['怒るのも当然だよ', '怒るのも当然じゃないよ', '怒るはずがないよ', '怒ってはいけないよ'],
      answerIndex: 0, distractorReason: '共情要承认对方愤怒的合理性，其余三项都在否定',
      explanationZh: '「怒るのも当然だ」＝你生气是应该的' },
    production: { promptJa: '相手の気持ちへの共感を「〜のも当然だ」で言ってください。',
      promptZh: '用「〜のも当然だ」共情对方的心情。',
      expected: ['も当然'], acceptable: ['〜のも当然です'] },
    practice: { themeJa: '相手に共感を示す', starterJa: '友達の怒りや悲しみに「当然だよ」と言ってあげた経験は？',
      starterZh: '有没有对朋友说过「你这样想是应该的」？', targetUse: '〜も当然だ' },
    vocabularyLinks: ['fi-jouzu', 'fi-ganbaru'] }),
  g({ grammarId: 'n2g-154', pattern: '〜も〜なら〜も', reading: 'もならも', unit: 11, zhSourceRowId: null,
    meaningJa: '〜も〜も両方悪い（あきれ）',
    explanationZh: '…也不像话，…也不像话（双方都有责任）。无奈或讽刺地各打五十大板',
    formation: '名詞＋も＋同じ名詞＋なら、名詞＋も＋同じ名詞',
    usageScene: '吐槽家长孩子都有问题、老师学生双方都不像话',
    nuance: '只用于责备和无语，不用在夸奖的场合',
    register: 'spoken',
    matchKeys: ['も親なら', 'も先生なら'],
    sourceExample: src('親も親なら子も子ですね。', '868f90c313712d30'),
    examplesJa: ['親も親なら子も子ですね。',
                 '遅刻する先生も先生なら、居眠りする生徒も生徒だ。'],
    examplesZh: ['家长也不像话，孩子也不像话。', '迟到的老师不像话，打瞌睡的学生也不像话。'],
    furigana: 'おやも おやなら こも こですね。',
    commonMistakesZh: '同一名词要重复两次（親も親なら）：「親も子なら」×。只能用于负面评价，「夫妻俩都优秀」不能套这个句型',
    learnerFocus: '中文「半斤八两」「一个样」的日语版。吐槽剧情、新闻时的地道表达，注意别当面用（很失礼）',
    similarPatterns: ['〜も〜ば〜も', 'どっちもどっち'],
    contrast: '「も〜なら〜も」＝双方への非難；「も〜ば〜も」＝中立の並列；「どっちもどっち」＝口語の五十歩百歩',
    recognition: { promptZh: '「店も店なら客も客だ」的评价是？',
      options: ['店和客人双方都不像话', '店和客人双方都非常优秀', '只有店有问题', '只有客人有问题'],
      answerIndex: 0, distractorReason: '此句型专用于责备双方',
      explanationZh: '各打五十大板式的无语说法' },
    production: { promptJa: '両方に問題がある状況を「〜も〜なら〜も」で言ってください。',
      promptZh: '用「〜も〜なら〜も」吐槽双方都有问题的状况。',
      expected: ['なら'], acceptable: ['親も親なら子も子'] },
    practice: { themeJa: 'ニュースやドラマを吐槽する', starterJa: '「どっちもどっちだ」と思った出来事はありますか？',
      starterZh: '有没有觉得「双方都有问题」的事？', targetUse: '〜も〜なら〜も' },
    vocabularyLinks: ['fi-kazoku', 'fi-sensei'] }),
  g({ grammarId: 'n2g-155', pattern: '〜ものか', reading: 'ものか', unit: 11, zhSourceRowId: null,
    meaningJa: '絶対に〜しない（反語の強い否定）',
    explanationZh: '才不…呢、绝不…。用反问形式表达强烈否定的决心',
    formation: '動詞辞書形／い形容詞／な形容詞＋な ＋ものか（もんか・もんですか）',
    usageScene: '发誓再不去坑人的店、赌气说绝不认输',
    nuance: '不是疑问而是反问。「もんか」是口语，「ものですか」是礼貌形式',
    register: 'spoken',
    matchKeys: ['ものか', 'もんか', 'もんですか'],
    sourceExample: src('ぼったくりをするお店には、二度と行くもんですか。', 'fd689bc09638502f'),
    examplesJa: ['ぼったくりをするお店には、二度と行くもんですか。',
                 'あんなチームに負けるものか。'],
    examplesZh: ['宰客的店，才不会再去第二次呢。', '才不会输给那种队伍呢。'],
    furigana: 'ぼったくりを する おみせには、にどと いくもんですか。',
    commonMistakesZh: '形式是疑问、意思是强否定：「行くもんですか」不是在问要不要去，而是「绝不去」。真的提问要用「行きますか」',
    learnerFocus: '和U10的「まい」同义但更口语更带情绪：「負けるもんか！」是热血台词的定番。动漫日剧高频',
    similarPatterns: ['〜まい', '絶対〜ない'],
    contrast: '「ものか」＝感情的な反語否定（口語）；「まい」＝固い書面の否定意志；「絶対〜ない」＝直接的な否定',
    recognition: { promptZh: '「二度と頼むもんか」的真实意思是？',
      options: ['再也不会拜托了（强烈否定）', '想再拜托一次', '在询问能否拜托', '已经拜托过两次'],
      answerIndex: 0, distractorReason: '「もんか」是反问形式的强否定，不是疑问',
      explanationZh: '反语＝表面疑问、实为「绝不」' },
    production: { promptJa: '悔しさをバネにした決意を「〜ものか」で言ってください。',
      promptZh: '用「〜ものか」说一句不服输的狠话。',
      expected: ['ものか'], acceptable: ['〜もんか', '〜もんですか'] },
    practice: { themeJa: '悔しさを表現する', starterJa: '「絶対に負けない！」と思った瞬間はありますか？',
      starterZh: '有过「绝不认输！」的瞬间吗？', targetUse: '〜ものか' },
    vocabularyLinks: ['fi-iku', 'fi-kimeru'] }),
  g({ grammarId: 'n2g-156', pattern: '〜ものがある', reading: 'ものがある', unit: 11, zhSourceRowId: null,
    meaningJa: '〜と感じさせる何かがある（感嘆の評価）',
    explanationZh: '有令人…之处、颇有…的地方。对某种特质发出由衷感叹',
    formation: '動詞辞書形／い形容詞／な形容詞＋な ＋ものがある',
    usageScene: '感叹中国发展之快、称赞歌声的感染力、认可作品的魅力',
    nuance: '用于「目を見張るものがある」「心を打つものがある」等表示评价的固定说法',
    register: 'written',
    sourceExample: src('中国のここ十数年の発展には、目を見張るものがあります。', 'd4522bc3251e6e06'),
    examplesJa: ['中国のここ十数年の発展には、目を見張るものがあります。',
                 '彼の歌声には、人を引きつけるものがあります。'],
    examplesZh: ['中国这十几年的发展，令人瞠目。', '他的歌声有一种吸引人的力量。'],
    furigana: 'ちゅうごくの ここ じゅうすうねんの はってんには、めを みはる ものが あります。',
    commonMistakesZh: '不是「拥有物品」：「彼には車があるものがある」×。前面放的是让人产生某种感受的性质（感心する・胸を打つ・見るべき）',
    learnerFocus: '高级夸法：「あなたの努力には頭が下がるものがあります」。比「すごい」高好几个段位',
    similarPatterns: ['〜ところがある', '〜感じがする'],
    contrast: '「ものがある」＝性質への感嘆評価；「ところがある」＝一面の指摘（中立）；「感じがする」＝主観の印象',
    recognition: { promptZh: '「彼の情熱には、人を動かすものがある」是在？',
      options: ['感叹他的热情有感染力', '说他非常喜欢帮别人搬东西', '批评他做事情太过于冲动了', '说他对工作完全没有热情'],
      answerIndex: 0, distractorReason: '「ものがある」＝对特质的感叹式肯定',
      explanationZh: '由衷的性质感叹' },
    production: { promptJa: '心を動かされた対象を「〜ものがある」で評価してください。',
      promptZh: '用「〜ものがある」感叹一个打动你的事物。',
      expected: ['ものがあ'], acceptable: ['目を見張るものがある'] },
    practice: { themeJa: '感動を大人の言葉で伝える', starterJa: '最近、思わず感心したことは何ですか？',
      starterZh: '最近有什么让你由衷感叹的事？', targetUse: '〜ものがある' },
    vocabularyLinks: ['fi-kanjiru', 'fi-kiku'] }),
  g({ grammarId: 'n2g-157', pattern: '〜ものだ', reading: 'ものだ', unit: 11, zhSourceRowId: null,
    meaningJa: '本来〜であるのが普通だ／〜だなあ（感慨）',
    explanationZh: '本来就是…（本性、常识）；真是…啊（感叹）；「たものだ」＝过去常常…（怀念）',
    formation: '動詞辞書形・普通形／い形容詞／な形容詞＋な ＋ものだ',
    usageScene: '陈述人之常情、感叹时间飞逝、怀念过去常做的事',
    nuance: '三种用法：讲本质、感叹、回忆（「た形＋ものだ」）。说「ものです」更礼貌',
    register: 'both',
    sourceExample: src('年を取れば、記憶力は衰えるものです。', '659e63e510e26797'),
    examplesJa: ['年を取れば、記憶力は衰えるものです。',
                 '時間がたつのは、本当に早いものですね。'],
    examplesZh: ['上了年纪，记忆力衰退是自然规律。', '时间过得真快啊。'],
    furigana: 'としを とれば、きおくりょくは おとろえる ものです。',
    commonMistakesZh: '三种用法靠前文判断：辞書形＋「ものだ」＝本性；感叹句＋「ものだ」＝感慨；た形＋「ものだ」＝怀旧（「昔はよく遊んだものだ」）。全都当成「东西」来理解就读不懂了',
    learnerFocus: '「早いものですね」是寒暄万能句：年末、久别重逢都能用。先掌握感叹用法',
    similarPatterns: ['〜べきだ', '〜ことだ'],
    contrast: '「ものだ」＝一般論・本質・感慨；「べきだ」＝話し手の当為主張；「ことだ」＝個別の助言',
    recognition: { promptZh: '「昔はよく川で泳いだものだ」的语气是？',
      options: ['怀念过去常去游泳', '现在正打算要去游泳', '命令别人去游泳', '否认游过泳'],
      answerIndex: 0, distractorReason: '「た形＋ものだ」＝对往昔习惯的怀念',
      explanationZh: '回想用法的「ものだ」' },
    production: { promptJa: '一般論や感慨を「〜ものだ」で言ってください。',
      promptZh: '用「〜ものだ」说一句人之常情或感叹。',
      expected: ['ものだ', 'ものです'], acceptable: ['早いものですね'] },
    practice: { themeJa: '人生の実感を語る', starterJa: '「時間がたつのは早いなあ」と感じるのはどんなときですか？',
      starterZh: '什么时候你会感叹时间过得快？', targetUse: '〜ものだ' },
    vocabularyLinks: ['fi-wasureru', 'fi-tanoshii'] }),
  g({ grammarId: 'n2g-158', pattern: '〜ものだから', reading: 'ものだから', unit: 11, zhSourceRowId: null,
    runtimeExampleOrigin: 'original_authored',
    meaningJa: '〜なので（言い訳がましい理由）',
    explanationZh: '因为…（辩解语气）。为迟到、失败等做解释时的理由表达',
    formation: '動詞・い形容詞普通形／な形容詞＋な／名詞＋な ＋ものだから（もので・もんだから）',
    usageScene: '解释迟到原因、辩解为什么买多了、说明不得已的情况',
    nuance: '带有「实在没办法」的辩解语气。后半句不接意志或命令',
    register: 'spoken',
    sourceExample: src('昔は、よく外で遊んだものです。', '27c2719725d08de8'),
    examplesJa: ['初めての道だったものだから、迷ってしまいました。',
                 'うれしかったものだから、つい大声を出してしまいました。'],
    examplesZh: ['因为是第一次走的路，所以迷路了。', '因为太高兴，不由得大声叫了出来。'],
    furigana: 'はじめての みちだった ものだから、まよって しまいました。',
    commonMistakesZh: '后项不能接意志・命令：「疲れたものだから、休みましょう」×。辩解时配「つい・うっかり・しまった」最自然。原本例句是「たものだ」（怀旧）用法，注意区分',
    learnerFocus: '迟到道歉的万能句：「電車が遅れたものですから…」。比「から」更有「情有可原」的恳求感',
    similarPatterns: ['〜ので', '〜ばかりに'],
    contrast: '「ものだから」＝弁解の理由；「ので」＝中立の理由；「ばかりに」＝後悔の原因',
    recognition: { promptZh: '「道が混んでいたものですから」最适合的场景是？',
      options: ['为迟到道歉时的解释', '炫耀开车技术', '命令对方开车', '拒绝坐车'],
      answerIndex: 0, distractorReason: '「ものですから」是辩解语气的理由说明',
      explanationZh: '情有可原的辩解' },
    production: { promptJa: '遅刻や失敗の言い訳を「〜ものだから」で言ってください。',
      promptZh: '用「〜ものだから」为一次迟到（失误）辩解。',
      expected: ['ものだから', 'ものですから'], acceptable: ['〜もので'] },
    practice: { themeJa: '角を立てずに弁解する', starterJa: '遅れた理由を、感じよく説明してみてください。',
      starterZh: '试着得体地解释一次迟到的原因。', targetUse: '〜ものだから' },
    vocabularyLinks: ['fi-komaru', 'fi-ureshii'] }),
  g({ grammarId: 'n2g-159', pattern: '〜ものではない', reading: 'ものではない', unit: 11, zhSourceRowId: null,
    meaningJa: '〜するべきではない（一般的な訓戒）',
    explanationZh: '不该…、不应当…。基于社会常识的训诫，对事不对人',
    formation: '動詞辞書形 ＋ものではない',
    usageScene: '教导不该背后说人坏话、不该浪费食物',
    nuance: '不是攻击个人，而是当作「世间的道理」来劝导，多是长辈对晚辈使用',
    register: 'both',
    sourceExample: src('陰で人の悪口を言うものではないです。', '619063e601d1ce88'),
    examplesJa: ['陰で人の悪口を言うものではないです。',
                 '食べ物を粗末にするものではありません。'],
    examplesZh: ['不该在背后说人坏话。', '不应当糟蹋食物。'],
    furigana: 'かげで ひとの わるぐちを いう ものではないです。',
    commonMistakesZh: '训诫的是「一般人的行为准则」：具体禁止某人某次行为用「てはいけない」。「人を見た目で判断するものではない」这类普世道理最典型',
    learnerFocus: '长辈口吻的道理句。自己少用命令别人，但听懂日剧里长辈的教诲全靠它',
    similarPatterns: ['〜べきではない', '〜てはいけない'],
    contrast: '「ものではない」＝社会通念の訓戒；「べきではない」＝話し手の当為判断；「てはいけない」＝個別の禁止',
    recognition: { promptZh: '「約束を破るものではない」的性质是？',
      options: ['做人不该违约的普遍道理', '针对某一次违约行为的处罚', '允许对方违约的一份正式通知', '关于违约具体方法的详细说明'],
      answerIndex: 0, distractorReason: '「ものではない」是一般化的社会训诫',
      explanationZh: '普世道理的说法' },
    production: { promptJa: '世の中の道理を「〜ものではない」で言ってください。',
      promptZh: '用「〜ものではない」说一条做人的道理。',
      expected: ['ものでは'], acceptable: ['〜ものではありません'] },
    practice: { themeJa: '大切にしている道理を語る', starterJa: '子どもに伝えたい「してはいけないこと」は何ですか？',
      starterZh: '你想告诉孩子「不该做的事」是什么？', targetUse: '〜ものではない' },
    vocabularyLinks: ['fi-taberu', 'fi-hanasu'] }),
  g({ grammarId: 'n2g-160', pattern: '〜ものなら', reading: 'ものなら', unit: 11, zhSourceRowId: null,
    meaningJa: 'もし〜できるなら（実現しにくい願望）',
    explanationZh: '要是能…的话（真想…）。可能性低的愿望，常配可能形',
    formation: '動詞可能形 ＋ものなら',
    usageScene: '要是能去意大利就好了、要是能回到学生时代',
    nuance: '常和「できるものならしたい」搭配。核心含义是实现起来很困难',
    register: 'spoken',
    sourceExample: src('イタリアに行けるものなら行きたいですが、遠すぎます。', '4b9a7ad2901d683e'),
    examplesJa: ['イタリアに行けるものなら行きたいですが、遠すぎます。',
                 '戻れるものなら、学生時代に戻りたいです。'],
    examplesZh: ['要是能去意大利真想去，但太远了。', '要是能回去，真想回到学生时代。'],
    furigana: 'イタリアに いける ものなら いきたいですが、とおすぎます。',
    commonMistakesZh: '前接可能形是铁则：「行くものなら」×→「行けるものなら」○。另有「（よ）うものなら」（要是敢…就会有严重后果）是姊妹句型，注意区分',
    learnerFocus: '聊梦想的软化剂：「できるものなら世界一周したい」。愿望＋自嘲的余味，聊天显得有人情味',
    similarPatterns: ['〜たら', '〜としたら'],
    contrast: '「ものなら」＝実現困難な願望（可能形＋）；「たら」＝中立の仮定；「（よ）うものなら」＝やったら大変なことになる',
    recognition: { promptZh: '「休めるものなら休みたい」隐含的意思是？',
      options: ['实际上很难休息', '马上就要休息了', '已经休息过了', '不想休息'],
      answerIndex: 0, distractorReason: '「ものなら」暗含实现可能性低',
      explanationZh: '想而难得的愿望' },
    production: { promptJa: '実現しにくい願望を「〜ものなら」で言ってください。',
      promptZh: '用「〜ものなら」说一个难以实现的愿望。',
      expected: ['ものなら'], acceptable: ['できるものなら'] },
    practice: { themeJa: '夢を気軽に語る', starterJa: '「できるものなら」やってみたいことは何ですか？',
      starterZh: '「要是能做到」你最想做什么？', targetUse: '〜ものなら' },
    vocabularyLinks: ['fi-kaeru', 'fi-suki'] }),
  g({ grammarId: 'n2g-161', pattern: '〜ものの', reading: 'ものの', unit: 11, zhSourceRowId: null,
    meaningJa: '〜したが、しかし（期待どおりでない）',
    explanationZh: '虽然…但是…。前项成立，后项却没达到预期的书面转折',
    formation: '動詞・い形容詞普通形／な形容詞＋な・である ＋ものの',
    usageScene: '虽然读了却没记住、虽然报了名却在犹豫',
    nuance: '「とはいうものの」是放在句首的固定说法。前后基本是同一个主语',
    register: 'written',
    sourceExample: src('例文集を1度読んだものの、全然覚えていないです。', 'f6b91503c032de43'),
    examplesJa: ['例文集を1度読んだものの、全然覚えていないです。',
                 '申し込んだものの、行くかどうか迷っています。'],
    examplesZh: ['虽然把例句集读了一遍，却完全没记住。', '虽然报了名，却还在犹豫去不去。'],
    furigana: 'れいぶんしゅうを いちど よんだ ものの、ぜんぜん おぼえて いないです。',
    commonMistakesZh: '「ものの」前后要是同一主语：说「私は誘ったものの、彼は来なかった」不自然。「もの」系的句型最多，靠后面接什么来判断：「ものの」＝转折、「ものだから」＝理由、「ものなら」＝愿望',
    learnerFocus: '写学习心得的诚实转折：「始めたものの続かない」。承认现状的书面表达，反思文必备',
    similarPatterns: ['〜が', '〜とはいえ'],
    contrast: '「ものの」＝期待外れの書面転折；「が」＝中立の逆接；「とはいえ」＝認めつつ反論',
    recognition: { promptZh: '「買ったものの、一度も使っていない」的状况是？',
      options: ['买是买了，却一次没用过', '没买所以没用', '买了以后每天都在认真使用', '打算今天去买'],
      answerIndex: 0, distractorReason: '「ものの」＝前项成立、后项不如预期',
      explanationZh: '「虽然…却…」的落差' },
    production: { promptJa: 'やり始めたのに続かないことを「〜ものの」で言ってください。',
      promptZh: '用「〜ものの」坦白一件有始无终的事。',
      expected: ['ものの'], acceptable: ['〜たものの'] },
    practice: { themeJa: '三日坊主を告白する', starterJa: '始めたのに続かなかったことはありますか？',
      starterZh: '有没有开始了却没坚持下来的事？', targetUse: '〜ものの' },
    vocabularyLinks: ['fi-yomu', 'fi-benkyo'] }),
  g({ grammarId: 'n2g-163', pattern: '〜やら〜やら', reading: 'やらやら', unit: 11, zhSourceRowId: null,
    meaningJa: '〜や〜など（ごちゃごちゃと色々）',
    explanationZh: '又是…又是…。杂乱列举，带「乱糟糟、应接不暇」的语感',
    formation: '名詞＋やら＋名詞＋やら／動詞・い形容詞＋やら',
    usageScene: '包里塞满各种东西、搬家又打包又办手续忙翻天',
    nuance: '表达乱七八糟的多和手忙脚乱的实感。用「〜やら〜やらで」可以引出理由',
    register: 'spoken',
    sourceExample: src('カバンの中に本やらパソコンやらが入っていて、重すぎます。', 'e10dc73efef168fe'),
    examplesJa: ['カバンの中に本やらパソコンやらが入っていて、重すぎます。',
                 '引っ越しは、荷造りやら手続きやらで大忙しでした。'],
    examplesZh: ['包里又是书又是电脑，重得要命。', '搬家又是打包又是办手续，忙得团团转。'],
    furigana: 'カバンの なかに ほんやら パソコンやらが はいっていて、おもすぎます。',
    commonMistakesZh: '中立列举用「や」（本やノート）；「やら」自带「乱・多・烦」的情绪。「うれしいやら恥ずかしいやら」（又喜又羞）是情感混杂的定番',
    learnerFocus: '「うれしいやら悲しいやら」百感交集的表达，获奖感言、毕业感想都能用',
    similarPatterns: ['〜や〜など', '〜とか〜とか'],
    contrast: '「やら〜やら」＝雑多・慌ただしさの実感；「や」＝中立の例示；「とか」＝口語のぼかし列挙',
    recognition: { promptZh: '「うれしいやら恥ずかしいやら」形容的心情是？',
      options: ['又高兴又害羞，百感交集', '心里只有单纯的高兴', '心里只有单纯的害羞', '完全没有任何感觉'],
      answerIndex: 0, distractorReason: '「やら〜やら」＝多种情绪混杂',
      explanationZh: '情感混杂的列举' },
    production: { promptJa: '忙しかった日を「〜やら〜やら」で言ってください。',
      promptZh: '用「〜やら〜やら」描述手忙脚乱的一天。',
      expected: ['やら'], acceptable: ['〜やら〜やらで'] },
    practice: { themeJa: '慌ただしい日を再現する', starterJa: '最近、一番バタバタした日はどんな日でしたか？',
      starterZh: '最近最手忙脚乱的一天是怎样的？', targetUse: '〜やら〜やら' },
    vocabularyLinks: ['fi-isogashii', 'fi-tsukau'] }),
  g({ grammarId: 'n2g-164', pattern: '〜ようがない', reading: 'ようがない', unit: 11, zhSourceRowId: null,
    meaningJa: '〜する方法・手段がない',
    explanationZh: '想…也没法…。不是能力不够，而是手段本身不存在',
    formation: '動詞ます形（語幹） ＋ようがない',
    usageScene: '没有教材没法学、不知道联系方式没法通知',
    nuance: '完全没有办法可想。如「直しようがない」（没法修）「連絡のしようがない」（没法联系）',
    register: 'both',
    sourceExample: src('手元に文法学習の本や例文集がないと勉強しようがないです。', 'ec46ed2f82e09a35'),
    examplesJa: ['手元に文法学習の本や例文集がないと勉強しようがないです。',
                 '連絡先を知らないので、知らせようがありません。'],
    examplesZh: ['手边没有语法书和例句集，想学也没法学。', '不知道联系方式，想通知也无从通知。'],
    furigana: 'てもとに ぶんぽうがくしゅうの ほんや れいぶんしゅうが ないと べんきょう しようがないです。',
    commonMistakesZh: '和「できない」的区别：「泳げない」＝能力不行；「プールが閉まっていて泳ぎようがない」＝没有条件。U7学过的「としか言いようがない」正是本句型的固定化',
    learnerFocus: '解释客观困难的免责表达：「データが消えて、確認しようがないんです」。说明「不是我不想做」',
    similarPatterns: ['〜できない', '〜わけにはいかない'],
    contrast: '「ようがない」＝手段が存在しない；「できない」＝能力・可能性の否定；「わけにはいかない」＝事情が許さない',
    recognition: { promptZh: '「住所がわからないので、送りようがない」的困难在于？',
      options: ['缺少寄送的必要信息', '没有力气去邮局寄东西', '根本就不想寄东西给对方', '其实早就已经寄出去了'],
      answerIndex: 0, distractorReason: '「ようがない」＝手段条件不存在，不是意愿或能力问题',
      explanationZh: '客观上无从下手' },
    production: { promptJa: '手段がなくて困ったことを「〜ようがない」で言ってください。',
      promptZh: '用「〜ようがない」说一次无从下手的困境。',
      expected: ['ようが'], acceptable: ['〜ようがありません'] },
    practice: { themeJa: '客観的な困難を説明する', starterJa: '「やりたくてもできなかった」状況を説明してみてください。',
      starterZh: '解释一次「想做也没法做」的状况。', targetUse: '〜ようがない' },
    vocabularyLinks: ['fi-renraku', 'fi-setsumei'] }),
  g({ grammarId: 'n2g-165', pattern: '〜ようで', reading: 'ようで', unit: 11, zhSourceRowId: null,
    meaningJa: '〜のように見えて（実は違う）',
    explanationZh: '看似…（其实）…。表面印象和实际相反的转折',
    formation: '動詞普通形／い形容詞／な形容詞＋な／名詞＋の ＋ようで',
    usageScene: '看似呆萌其实是学霸、看似简单其实很深奥',
    nuance: '核心是「看起来是…，其实…」的反转，适合描写人和事物的两面性',
    register: 'both',
    sourceExample: src('彼は一見、天然なようで、すごく秀才です。', '9c72a33d282e38fa'),
    examplesJa: ['彼は一見、天然なようで、すごく秀才です。',
                 'この文型は簡単なようで、実は奥が深いです。'],
    examplesZh: ['他看似呆萌，其实是个大学霸。', '这个句型看似简单，其实很有深度。'],
    furigana: 'かれは いっけん、てんねんな ようで、すごく しゅうさいです。',
    commonMistakesZh: '「一見〜ようで、実は…」是黄金组合。只说「簡単なようで」而后项同方向（本当に簡単だ）就失去转折意义',
    learnerFocus: '介绍反差魅力的句式：「厳しいようで、優しい先生です」。人物描写立体起来',
    similarPatterns: ['〜ように見えて', '〜そうで'],
    contrast: '「ようで」＝見た目と実態の逆転；「ように見えて」＝ほぼ同義（説明的）；「そうで」＝様態推測とのギャップ',
    recognition: { promptZh: '「近いようで遠い」形容的是？',
      options: ['看着近其实远', '真的很近', '越来越近', '完全不知道距离'],
      answerIndex: 0, distractorReason: '「ようで」＝表面印象与实际的反差',
      explanationZh: '外表⇔实际的落差' },
    production: { promptJa: '見た目と中身のギャップを「〜ようで」で言ってください。',
      promptZh: '用「〜ようで」介绍一个有反差的人或事物。',
      expected: ['ようで'], acceptable: ['一見〜ようで'] },
    practice: { themeJa: 'ギャップを紹介する', starterJa: 'あなたの「見た目と違う」一面は何ですか？',
      starterZh: '你有什么「和外表不一样」的一面？', targetUse: '〜ようで' },
    vocabularyLinks: ['fi-kantan', 'fi-muzukashii'] }),
  // CEO統合判断（2026-07-30）: 独立文型として維持 → 本編昇格（元・同義判断待ちpre-draft）
  g({ grammarId: 'n2g-162', pattern: '〜矢先に', reading: 'やさきに', unit: 11, zhSourceRowId: null,
    meaningJa: 'まさに〜しようとした、その直前に',
    explanationZh: '正要…的节骨眼上（被打断）。行动即将开始的瞬间发生了别的事',
    formation: '動詞辞書形＋（よう）とした ＋矢先に',
    usageScene: '正要出门快递来了、刚要睡觉电话响了',
    nuance: '强烈含有「刚开头就被打断」的意味。只用于刚要开始的瞬间，范围比「ところに」窄',
    register: 'written',
    sourceExample: src('外に出かけようとした矢先に、配達員がやって来ました。', 'c901143a3e3e9ba7'),
    examplesJa: ['外に出かけようとした矢先に、配達員がやって来ました。',
                 '寝ようとした矢先に、友達から電話がかかってきました。'],
    examplesZh: ['正要出门的节骨眼上，快递员来了。', '刚要睡觉的那一刻，朋友打来了电话。'],
    furigana: 'そとに でかけようと した やさきに、はいたついんが やって きました。',
    commonMistakesZh: '「矢先」原意是箭头，比喻「行动即将离弦的瞬间」。只能用于开始前的一刻：进行中的场面（吃着饭时）用「最中に」，不用「矢先に」',
    learnerFocus: '比「ところに」更有戏剧感：「帰ろうとした矢先に仕事を頼まれた」。职场吐槽的画面感神器',
    similarPatterns: ['〜ところに', '〜とたん'],
    contrast: '「矢先に」＝開始直前の出鼻（狭い）；「ところに」＝場面への到来（広い）；「とたん」＝完了直後',
    recognition: { promptZh: '「出発しようとした矢先に雨が降ってきた」的时机是？',
      options: ['正要出发的那一刻', '出发之后过了很久的时候', '回来之后', '根本没打算出发'],
      answerIndex: 0, distractorReason: '「矢先に」限定于行动开始的前一瞬',
      explanationZh: '刚开头就被打断的瞬间' },
    production: { promptJa: '出鼻をくじかれた経験を「〜矢先に」で言ってください。',
      promptZh: '用「〜矢先に」说一次正要行动就被打断的经历。',
      expected: ['矢先に'], acceptable: ['〜ようとした矢先に'] },
    practice: { themeJa: 'タイミングの悪さを笑い話に', starterJa: '「今からやろうとしたのに！」という経験はありますか？',
      starterZh: '有没有「我正要做呢！」就被打断的经历？', targetUse: '〜矢先に' },
    vocabularyLinks: ['fi-deru', 'fi-renraku'] }),
];
