// Phase 3P-5: N2文法完成draft Unit 12（No.166〜180の15文型）。最終Unit。
// rightsStatus: teacher_created_confirmed。第1例文=原本（無改変）、第2例文=独自（実生活）。
// 169（わけだ）のみ原本例文に文型が現れないため、runtime例文は独自作成（original_authored）。
import type { N2GrammarDraft } from './n2GrammarDrafts';

const g = (p: Omit<N2GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey' | 'runtimeExampleOrigin'> & { reviewKey?: string; runtimeExampleOrigin?: N2GrammarDraft['runtimeExampleOrigin'] }): N2GrammarDraft =>
  ({ level: 'N2', route: 'n2-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, runtimeExampleOrigin: 'source_confirmed', ...p });

const src = (text: string, hash: string) =>
  ({ text, hash, rightsStatus: 'teacher_created_confirmed' as const });

export const N2_GRAMMAR_DRAFTS_UNIT12: N2GrammarDraft[] = [
  g({ grammarId: 'n2g-166', pattern: '〜ようでは', reading: 'ようでは', unit: 12, zhSourceRowId: null,
    meaningJa: '〜という状態では（良くない見通しだ）',
    explanationZh: '要是（连）…的话（就没指望了）。以现状为条件，给出消极的预测',
    formation: '動詞普通形 ＋ようでは',
    usageScene: '提醒后辈这样下去不行、自我反省这种状态没法进步',
    nuance: '後件は必ず否定的な見通し。説教・戒めの響き',
    register: 'both',
    sourceExample: src('このような失敗で挫けるようでは、前に進むことは難しいですよ。', '8036dbe38be00427'),
    examplesJa: ['このような失敗で挫けるようでは、前に進むことは難しいですよ。',
                 '毎回遅刻するようでは、周りの信頼を失いますよ。'],
    examplesZh: ['要是这点失败就气馁的话，很难继续前进哦。', '要是每次都迟到的话，会失去周围人的信任哦。'],
    furigana: 'このような しっぱいで くじける ようでは、まえに すすむ ことは むずかしいですよ。',
    commonMistakesZh: '后件必须是消极预测：「頑張るようでは、合格します」×。积极条件用「ば・たら」。「これしきのことで諦めるようでは」是典型的激励型说教',
    learnerFocus: '自我反省的句式：「この程度で緊張するようでは、まだまだですね」。谦虚又显得有上进心',
    similarPatterns: ['〜ては', '〜ようなら'],
    contrast: '「ようでは」＝現状条件→悪い見通し；「ては」＝繰り返し・仮定の悪条件；「ようなら」＝様子の仮定（中立）',
    recognition: { promptZh: '「基礎を疎かにするようでは、上達しない」的语气是？',
      options: ['告诫：轻视基础就不会进步', '表扬对方的基础很扎实', '说明基础根本不重要', '夸奖已经进步很快了'],
      answerIndex: 0, distractorReason: '「ようでは」后接消极预测，是告诫语气',
      explanationZh: '「这样下去不行」的警示' },
    production: { promptJa: '自分への戒めを「〜ようでは」で言ってください。',
      promptZh: '用「〜ようでは」说一句自我告诫。',
      expected: ['ようでは'], acceptable: ['〜するようでは'] },
    practice: { themeJa: '自分に喝を入れる', starterJa: '「このままではダメだ」と思ったことはありますか？',
      starterZh: '有没有觉得「这样下去不行」的时候？', targetUse: '〜ようでは' },
    vocabularyLinks: ['fi-mondai', 'fi-ganbaru'] }),
  g({ grammarId: 'n2g-167', pattern: '〜ようなら', reading: 'ようなら', unit: 12, zhSourceRowId: null,
    meaningJa: 'もし〜という様子なら',
    explanationZh: '如果（看样子）…的话。根据观察到的迹象做条件假定',
    formation: '動詞普通形／い形容詞／な形容詞＋な ＋ようなら（ば）',
    usageScene: '烧不退就去医院、赶不上就提前联系',
    nuance: '様子・見込みへの仮定。医療・連絡・案内の場面と相性良',
    register: 'both',
    sourceExample: src('来週の授業に出られないようならば、前日までにご連絡ください。', '67119b111ade34e5'),
    examplesJa: ['来週の授業に出られないようならば、前日までにご連絡ください。',
                 '明日になっても熱が下がらないようなら、病院に行ってください。'],
    examplesZh: ['如果下周不能来上课，请在前一天之前联系我。', '如果到明天烧还不退，请去医院。'],
    furigana: 'らいしゅうの じゅぎょうに でられない ようならば、ぜんじつまでに ごれんらく ください。',
    commonMistakesZh: '「たら」是事实条件（如果发生），「ようなら」是样态观察（看情况要是…）。看医生、请假等「视情况而定」的场景专用',
    learnerFocus: '请假、预约变更的礼貌条件句：「都合が悪いようなら、日程を変えましょうか」。体贴感满分',
    similarPatterns: ['〜たら', '〜ば'],
    contrast: '「ようなら」＝様子を見ての仮定；「たら」＝成立後の条件；「ば」＝一般的条件',
    recognition: { promptZh: '「痛みが続くようなら、また来てください」最可能是谁说的？',
      options: ['医生对患者', '店员推销商品', '老师批改作业', '朋友邀约吃饭'],
      answerIndex: 0, distractorReason: '「〜ようなら」+再来院是诊疗结尾的定型句',
      explanationZh: '视情况而定的医嘱' },
    production: { promptJa: '相手を気づかう条件を「〜ようなら」で言ってください。',
      promptZh: '用「〜ようなら」说一句体贴的条件句。',
      expected: ['ようなら'], acceptable: ['〜ようならば'] },
    practice: { themeJa: '気づかいの連絡をする', starterJa: '体調が悪そうな友達に、どんな声をかけますか？',
      starterZh: '朋友看起来不舒服，你会怎么关心？', targetUse: '〜ようなら' },
    vocabularyLinks: ['fi-renraku', 'fi-byouin'] }),
  g({ grammarId: 'n2g-168', pattern: '〜わけがない', reading: 'わけがない', unit: 12, zhSourceRowId: 'n3row-28',
    meaningJa: '絶対に〜ない（根拠を持った全否定）',
    explanationZh: '不可能…、绝不会…。基于情理的全盘否定',
    formation: '動詞・い形容詞普通形／な形容詞＋な／名詞＋の ＋わけがない',
    usageScene: '断言疫情下父母不可能来日、偷懒不可能进步',
    nuance: '「そんな道理はない」という強い否定。会話では「わけない」も',
    register: 'spoken',
    sourceExample: src('コロナ禍で出入国が難しい今、両親が日本に来れるわけがないです。', 'f776ed15c893044e'),
    examplesJa: ['コロナ禍で出入国が難しい今、両親が日本に来れるわけがないです。',
                 '毎日サボっていて、上手になるわけがないです。'],
    examplesZh: ['疫情下出入境困难，父母不可能来日本。', '天天偷懒，不可能会进步。'],
    furigana: 'コロナかで しゅつにゅうこくが むずかしい いま、りょうしんが にほんに これる わけが ないです。',
    commonMistakesZh: '「わけがない」（全否定：不可能）和「わけではない」（部分否定：并非）是最容易混的一对。一字之差，考试必挖坑',
    learnerFocus: '吐槽不合理时的爽快否定：「あんな値段、買えるわけがない」。语气强，对上级慎用',
    similarPatterns: ['〜はずがない', '〜っこない'],
    contrast: '「わけがない」＝道理からの全否定；「はずがない」＝推理からの否定；「っこない」＝口語の可能性否定',
    recognition: { promptZh: '「彼が嘘をつくわけがない」表达的是？',
      options: ['坚信他不可能说谎', '确定他说了谎', '希望他说谎', '不知道他是否说谎'],
      answerIndex: 0, distractorReason: '「わけがない」＝基于对人品的了解的全否定',
      explanationZh: '情理上的「不可能」' },
    production: { promptJa: 'あり得ないことを「〜わけがない」で言ってください。',
      promptZh: '用「〜わけがない」否定一件不可能的事。',
      expected: ['わけが'], acceptable: ['〜わけがありません'] },
    practice: { themeJa: '常識で判断を語る', starterJa: '「そんなの無理に決まってる！」と思ったことは？',
      starterZh: '有没有觉得「那绝对不可能」的事？', targetUse: '〜わけがない' },
    vocabularyLinks: ['fi-kazoku', 'fi-muri'] }),
  g({ grammarId: 'n2g-169', pattern: '〜わけだ', reading: 'わけだ', unit: 12, zhSourceRowId: null,
    runtimeExampleOrigin: 'original_authored',
    meaningJa: 'なるほど、だから〜なのだ（論理的な納得）',
    explanationZh: '难怪…、也就是说…。得知理由后恍然大悟，或从前提推出当然的结论',
    formation: '動詞・い形容詞普通形／な形容詞＋な／名詞＋という ＋わけだ',
    usageScene: '得知对方每天学3小时后感叹「难怪进步快」、发现窗开着感叹「难怪冷」',
    nuance: '「道理で〜わけだ」の呼応が定番。計算・推論の帰結にも使う',
    register: 'spoken',
    sourceExample: src('一回の授業で3単元を進めれば、6回の授業でN2の文法を全てやり終えることができます。', '5f0c14a2dc776680'),
    examplesJa: ['毎日3時間も勉強しているんですか。それなら上達が早いわけだ。',
                 '窓が開いていたのか。道理で寒いわけです。'],
    examplesZh: ['每天学3个小时？难怪进步这么快。', '原来窗户开着啊，难怪这么冷。'],
    furigana: 'まいにち さんじかんも べんきょう して いるんですか。それなら じょうたつが はやい わけだ。',
    commonMistakesZh: '「わけだ」表示恍然大悟的合理结论，不是单纯的「所以」。「道理で（难怪）」和「わけだ」是黄金搭档。原本例句是计算推论的场面（3单元×6次课＝全部学完＝就是说…），运用时配「という」更顺',
    learnerFocus: '听懂对方解释后回一句「そういうわけですか」（原来如此），会话立刻有来有往',
    similarPatterns: ['〜はずだ', '〜ということだ'],
    contrast: '「わけだ」＝理由を知った納得；「はずだ」＝当然の推論（未確認）；「ということだ」＝伝聞・言い換え',
    recognition: { promptZh: '「道理で日本語が上手なわけだ」之前最可能听到了什么？',
      options: ['他在日本住了十年', '他从来没有学过日语', '他一点也不喜欢日本', '他明天第一次去日本'],
      answerIndex: 0, distractorReason: '「わけだ」需要一个能解释「日语好」的理由',
      explanationZh: '理由→「难怪」的恍然大悟' },
    production: { promptJa: '理由を聞いて納得した気持ちを「〜わけだ」で言ってください。',
      promptZh: '用「〜わけだ」表达恍然大悟。',
      expected: ['わけだ', 'わけです'], acceptable: ['道理で〜わけだ'] },
    practice: { themeJa: '相づちで会話をつなぐ', starterJa: '最近「なるほど！」と納得したことはありますか？',
      starterZh: '最近有什么让你恍然大悟的事？', targetUse: '〜わけだ' },
    vocabularyLinks: ['fi-benkyo', 'fi-wakaru'] }),
  g({ grammarId: 'n2g-170', pattern: '〜わけではない', reading: 'わけではない', unit: 12, zhSourceRowId: 'n3row-29',
    meaningJa: '全部が〜とは限らない（部分否定）',
    explanationZh: '并非…、并不是说…。否定「全部如此」的误解，留有余地',
    formation: '動詞・い形容詞普通形／な形容詞＋な ＋わけではない',
    usageScene: '澄清「不是讨厌只是不常吃」、说明「不是反对只是担心」',
    nuance: '相手の誤解をやわらかく訂正する。「という」を挟むと更に丁寧',
    register: 'both',
    sourceExample: src('日本人は辛い食べ物が苦手と言っても、全く食べられないというわけではないです。', 'ddee07d917ac01a3'),
    examplesJa: ['日本人は辛い食べ物が苦手と言っても、全く食べられないというわけではないです。',
                 '反対しているわけではなく、少し心配なだけです。'],
    examplesZh: ['虽说日本人不擅长吃辣，但也并非完全不能吃。', '我并不是反对，只是有点担心而已。'],
    furigana: 'にほんじんは からい たべものが にがてと いっても、まったく たべられない という わけではないです。',
    commonMistakesZh: '和「わけがない」（不可能）方向完全不同：「食べられないわけではない」＝也不是不能吃（能吃一点）；「食べられるわけがない」＝根本不可能吃。选错就把让步说成了断言',
    learnerFocus: '避免误会的润滑句：「嫌いなわけではないんですが…」。拒绝邀请、表达保留意见都靠它缓冲',
    similarPatterns: ['〜とは限らない', '〜わけがない'],
    contrast: '「わけではない」＝部分否定（留有余地）；「とは限らない」＝例外の存在；「わけがない」＝全否定',
    recognition: { promptZh: '「行きたくないわけではないが、時間がない」的真意是？',
      options: ['想去但没时间', '其实一点也不想去', '肯定会去', '已经去过了'],
      answerIndex: 0, distractorReason: '「わけではない」否定的是「不想去」这个误解',
      explanationZh: '部分否定：意愿存在，条件不允许' },
    production: { promptJa: '誤解をやわらかく訂正する一言を「〜わけではない」で言ってください。',
      promptZh: '用「〜わけではない」温和地澄清一个误会。',
      expected: ['わけでは'], acceptable: ['〜というわけではない'] },
    practice: { themeJa: '角を立てずに断る', starterJa: '誘いを断るとき、どう言えば感じがいいですか？',
      starterZh: '拒绝邀请时怎么说才不伤感情？', targetUse: '〜わけではない' },
    vocabularyLinks: ['fi-taberu', 'fi-suki'] }),
  g({ grammarId: 'n2g-171', pattern: '〜わけにはいかない', reading: 'わけにはいかない', unit: 12, zhSourceRowId: 'n3row-30',
    meaningJa: '（事情・道義があって）〜できない',
    explanationZh: '（情理上）不能…。能力上可以，但立场、责任、道义不允许',
    formation: '動詞辞書形 ＋わけにはいかない／ない形＋ないわけにはいかない',
    usageScene: '考试临近不能放弃、大家都在努力自己不能先走',
    nuance: '「ないわけにはいかない」＝不得不。責任感・義理の表現',
    register: 'both',
    sourceExample: src('試験まであと３日なので、諦めるわけにはいかないです。', '627fe719e4186874'),
    examplesJa: ['試験まであと３日なので、諦めるわけにはいかないです。',
                 'みんなが頑張っているのに、私だけ帰るわけにはいきません。'],
    examplesZh: ['离考试只剩3天，不能就这么放弃。', '大家都在努力，我不能一个人先回去。'],
    furigana: 'しけんまで あと みっかなので、あきらめる わけには いかないです。',
    commonMistakesZh: '不是能力问题：「泳げないので泳ぐわけにはいかない」×（那是できない）。是「立场上不允许」。双重否定「行かないわけにはいかない」＝不得不去',
    learnerFocus: '表现责任感的句式：「約束したので、破るわけにはいきません」。职场信用度+1',
    similarPatterns: ['〜ようがない', '〜ざるを得ない'],
    contrast: '「わけにはいかない」＝事情・道義上の不可；「ようがない」＝手段が無い；「ざるを得ない」＝不本意だがやるしかない',
    recognition: { promptZh: '「明日は大事な発表があるので、休むわけにはいかない」的理由是？',
      options: ['责任在身不能休息', '身体不允许休息', '不知道怎么休息', '已经休息过了'],
      answerIndex: 0, distractorReason: '「わけにはいかない」是立场・责任上的不能',
      explanationZh: '道义上「不能休」' },
    production: { promptJa: '責任があってできないことを「〜わけにはいかない」で言ってください。',
      promptZh: '用「〜わけにはいかない」说一件因责任而不能做的事。',
      expected: ['わけには'], acceptable: ['〜わけにはいきません'] },
    practice: { themeJa: '責任感を言葉にする', starterJa: '「自分だけやめるわけにはいかない」と思った経験は？',
      starterZh: '有没有「不能只有我放弃」的经历？', targetUse: '〜わけにはいかない' },
    vocabularyLinks: ['fi-shigoto', 'fi-kaeru'] }),
  g({ grammarId: 'n2g-172', pattern: '〜わりには', reading: 'わりには', unit: 12, zhSourceRowId: null,
    meaningJa: '〜の程度から予想されるより（意外に）',
    explanationZh: '与…不相称地、虽然…却（比预期）。程度和结果不成比例',
    formation: '動詞・い形容詞普通形／な形容詞＋な／名詞＋の ＋わりに（は）',
    usageScene: '努力很多结果一般、价格贵量却少、年龄大却显年轻',
    nuance: '予想とのズレを軽く指摘。ほめにもけなしにも',
    register: 'spoken',
    sourceExample: src('たくさん努力をしたわりには、結果はイマイチでした。', '18339d5480c67a70'),
    examplesJa: ['たくさん努力をしたわりには、結果はイマイチでした。',
                 '値段が高いわりには、量が少なかったです。'],
    examplesZh: ['虽然付出了很多努力，结果却不怎么样。', '价格挺贵，量却很少。'],
    furigana: 'たくさん どりょくを した わりには、けっかは イマイチでした。',
    commonMistakesZh: 'U9的「にしては」需要具体前提（素人にしては），「わりには」接程度性内容（頑張ったわりに・高いわりに）。「年のわりに若い」是夸人定番但对长辈慎用',
    learnerFocus: '点评性价比的神器：「安いわりにおいしい」。探店分享用起来立刻像本地人',
    similarPatterns: ['〜にしては', '〜のに'],
    contrast: '「わりには」＝程度との不釣り合い；「にしては」＝属性前提とのギャップ；「のに」＝単純な期待外れの不満',
    recognition: { promptZh: '「このレストラン、安いわりにおいしいね」的评价是？',
      options: ['便宜却好吃（超出预期）', '又贵又难吃，完全不值得去', '因为价格很贵所以才会好吃', '因为便宜所以难吃也很正常'],
      answerIndex: 0, distractorReason: '「わりに」＝与价格水平不相称地好',
      explanationZh: '性价比的惊喜' },
    production: { promptJa: '予想とのギャップを「〜わりには」で言ってください。',
      promptZh: '用「〜わりには」点评一个出乎意料的性价比。',
      expected: ['わりに'], acceptable: ['〜わりには'] },
    practice: { themeJa: 'お店や商品をレビューする', starterJa: '最近「値段のわりに良かった」ものはありますか？',
      starterZh: '最近有没有觉得「物超所值」的东西？', targetUse: '〜わりには' },
    vocabularyLinks: ['fi-takai', 'fi-keiken'] }),
  g({ grammarId: 'n2g-173', pattern: '〜を中心に', reading: 'をちゅうしんに', unit: 12, zhSourceRowId: 'n3row-115',
    meaningJa: '〜を真ん中・重点にして',
    explanationZh: '以…为中心、以…为重点。物理的中心或活动的重心',
    formation: '名詞 ＋を中心に（を中心として・を中心とした＋名詞）',
    usageScene: '地球绕太阳转、以会话为重点学习、以年轻人为中心流行',
    nuance: '物理的中心と活動の重点の二用法。計画・紹介文で多用',
    register: 'both',
    sourceExample: src('太陽を中心に地球が回っています。', '6eb9988e75545f1f'),
    examplesJa: ['太陽を中心に地球が回っています。',
                 '会話練習を中心に、毎日30分学習しています。'],
    examplesZh: ['地球以太阳为中心旋转。', '我以会话练习为重点，每天学习30分钟。'],
    furigana: 'たいようを ちゅうしんに ちきゅうが まわって います。',
    commonMistakesZh: '修饰名词用「を中心とした／を中心とする」：「若者を中心としたブーム」。「を中心に」后面直接跟动词句',
    learnerFocus: '说明学习方法的框架句：「文法を中心に復習しています」。汇报学习计划显得有条理',
    similarPatterns: ['〜を中心として', '〜をメインに'],
    contrast: '「を中心に」＝重点・中核の提示；「をはじめ」＝代表例からの展開；「をメインに」＝口語的な主軸表現',
    recognition: { promptZh: '「駅を中心に店が増えている」描述的是？',
      options: ['以车站为中心店铺在增多', '车站里的店在减少', '店铺开得离车站越来越远了', '车站没有店铺'],
      answerIndex: 0, distractorReason: '「を中心に」＝以…为核心扩展',
      explanationZh: '中心→周边的扩展图' },
    production: { promptJa: '学習や生活の重点を「〜を中心に」で言ってください。',
      promptZh: '用「〜を中心に」说说你的学习（生活）重心。',
      expected: ['を中心に'], acceptable: ['〜を中心として'] },
    practice: { themeJa: '自分の学習法を紹介する', starterJa: '今、何を中心に日本語を勉強していますか？',
      starterZh: '你现在以什么为重点学日语？', targetUse: '〜を中心に' },
    vocabularyLinks: ['fi-hanasu', 'fi-shuukan'] }),
  g({ grammarId: 'n2g-174', pattern: '〜を通じて', reading: 'をつうじて', unit: 12, zhSourceRowId: 'n3row-113',
    meaningJa: '〜を手段・媒介として／〜の間ずっと',
    explanationZh: '通过…（媒介）；整个…期间。①通过某渠道 ②贯穿整个期间',
    formation: '名詞 ＋を通じて（を通して）',
    usageScene: '通过APP找到教材、通过朋友认识、一年到头雨都很少',
    nuance: '手段用法は間接的な媒介。期間用法は「一年を通じて」等',
    register: 'written',
    sourceExample: src('「小红书」を通じて、N2例文集を見つけることができました。', '6d8454421df60447'),
    examplesJa: ['「小红书」を通じて、N2例文集を見つけることができました。',
                 'この町は一年を通じて、雨が少ないです。'],
    examplesZh: ['通过小红书，找到了N2例句集。', '这个城市一年到头雨都很少。'],
    furigana: '「シャオホンシュー」を つうじて、エヌツー れいぶんしゅうを みつける ことが できました。',
    commonMistakesZh: '「を通じて」和「を通して」基本可换（通して更主动些）。直接手段用「で」：「はさみを通じて切る」×→「はさみで切る」。媒介要有「间接性」',
    learnerFocus: '自我介绍的加分句：「アニメを通じて日本語に興味を持ちました」。说清兴趣的来龙去脉',
    similarPatterns: ['〜を通して', '〜によって'],
    contrast: '「を通じて」＝媒介・期間全体；「によって」＝手段・原因の一般形；「で」＝直接の道具',
    recognition: { promptZh: '「友人を通じて彼女と知り合った」的认识方式是？',
      options: ['经朋友介绍认识的', '直接搭话认识的', '和朋友绝交了', '还没有认识'],
      answerIndex: 0, distractorReason: '「を通じて」＝以…为媒介',
      explanationZh: '间接媒介的渠道' },
    production: { promptJa: '何かとの出会いのきっかけを「〜を通じて」で言ってください。',
      promptZh: '用「〜を通じて」说说你与某物结缘的渠道。',
      expected: ['を通じて'], acceptable: ['〜を通して'] },
    practice: { themeJa: '出会いのきっかけを語る', starterJa: '日本語（日本文化）とは、何を通じて出会いましたか？',
      starterZh: '你是通过什么接触到日语（日本文化）的？', targetUse: '〜を通じて' },
    vocabularyLinks: ['fi-miru', 'fi-au'] }),
  g({ grammarId: 'n2g-175', pattern: '〜を問わず', reading: 'をとわず', unit: 12, zhSourceRowId: null,
    meaningJa: '〜に関係なく（掲示・募集の硬い表現）',
    explanationZh: '不问…、不分…。公告、招募中表示不设限制',
    formation: '名詞（対語・有無・国籍・年齢等） ＋を問わず',
    usageScene: '招聘不问经验、比赛不分年龄性别、昼夜不停',
    nuance: '「昼夜を問わず」「経験の有無を問わず」等、対や範囲の名詞と結ぶ',
    register: 'written',
    sourceExample: src('国籍を問わず、仲良くなれるといいなと思いました。', 'c1ed489816153d5f'),
    examplesJa: ['国籍を問わず、仲良くなれるといいなと思いました。',
                 'この大会は、年齢や性別を問わず参加できます。'],
    examplesZh: ['真希望不分国籍都能成为好朋友。', '这个比赛不分年龄性别都能参加。'],
    furigana: 'こくせきを とわず、なかよく なれると いいなと おもいました。',
    commonMistakesZh: 'U8的「にかかわらず」几乎同义，但「を問わず」更书面、更常见于招募要项。前面放「天気」等具体名词时「にかかわらず」更自然',
    learnerFocus: '看懂招聘启事的关键词：「学歴・経験を問わず」＝不限学历经验。找工作、报名前先扫这一行',
    similarPatterns: ['〜にかかわらず', '〜に関係なく'],
    contrast: '「を問わず」＝募集・掲示の無条件（硬）；「にかかわらず」＝無関係の一般形；「に関係なく」＝口語寄り',
    recognition: { promptZh: '招聘写着「経験を問わず歓迎」，意思是？',
      options: ['有无经验都欢迎', '只要有经验的人', '只要没经验的人', '不欢迎任何人'],
      answerIndex: 0, distractorReason: '「を問わず」＝不设该条件的限制',
      explanationZh: '不问条件的开放态度' },
    production: { promptJa: '条件を設けない案内を「〜を問わず」で作ってください。',
      promptZh: '用「〜を問わず」写一句不设限制的招募语。',
      expected: ['を問わず'], acceptable: ['〜の有無を問わず'] },
    practice: { themeJa: 'イベント募集文を作る', starterJa: '誰でも参加できるイベントの案内文を作ってみましょう。',
      starterZh: '试着写一句「谁都能参加」的活动通知。', targetUse: '〜を問わず' },
    vocabularyLinks: ['fi-tanoshii', 'fi-tomodachi'] }),
  g({ grammarId: 'n2g-176', pattern: '〜を除いては', reading: 'をのぞいては', unit: 12, zhSourceRowId: null,
    meaningJa: '〜以外は（全部）',
    explanationZh: '除…之外（全都）。指出唯一例外，其余全面成立',
    formation: '名詞 ＋を除いて（は）',
    usageScene: '除工作日白天外都有空、除雨天外每天跑步',
    nuance: '例外の明示。「〜を除けば」なら仮定的な評価にも',
    register: 'both',
    sourceExample: src('平日の昼間を除いては、基本いつでも、日本語学習に役立つ資料を作っています。', '39da225cf14ef204'),
    examplesJa: ['平日の昼間を除いては、基本いつでも、日本語学習に役立つ資料を作っています。',
                 '雨の日を除いては、毎朝30分歩いています。'],
    examplesZh: ['除了工作日白天，基本随时都在制作日语学习资料。', '除了雨天，每天早上都走30分钟。'],
    furigana: 'へいじつの ひるまを のぞいては、きほん いつでも、にほんごがくしゅうに やくだつ しりょうを つくって います。',
    commonMistakesZh: '后项必须是「全面」的陈述：「雨の日を除いては、時々歩く」很怪（除外后应是全都）。口语可用「以外は」',
    learnerFocus: '说明自己时间安排的清晰表达：「日曜を除いては、いつでも大丈夫です」。约时间干脆利落',
    similarPatterns: ['〜以外は', '〜は別として'],
    contrast: '「を除いては」＝唯一の例外＋全面成立；「以外は」＝口語の同義；「は別として」＝議論からの切り分け',
    recognition: { promptZh: '「彼を除いては、全員賛成した」的意思是？',
      options: ['只有他反对，其余都赞成', '包括他在内所有人全都赞成', '包括他在内所有人全都反对', '只有他一个人赞成，其余反对'],
      answerIndex: 0, distractorReason: '「を除いては」＝唯一例外，其余全部',
      explanationZh: '例外一人＋全体成立' },
    production: { promptJa: '唯一の例外つきの習慣を「〜を除いては」で言ってください。',
      promptZh: '用「〜を除いては」说一个只有一个例外的习惯。',
      expected: ['を除いて'], acceptable: ['〜を除けば'] },
    practice: { themeJa: '自分の生活リズムを説明する', starterJa: '「〜以外はいつでもOK」なあなたの空き時間は？',
      starterZh: '你的空闲时间是「除了…随时都行」？', targetUse: '〜を除いては' },
    vocabularyLinks: ['fi-iku', 'fi-genki'] }),
  g({ grammarId: 'n2g-177', pattern: '〜をはじめ', reading: 'をはじめ', unit: 12, zhSourceRowId: 'n3row-114',
    meaningJa: '〜を代表例として、その他も',
    explanationZh: '以…为首、以…为代表（还有其他同类）。列举时先举最典型的',
    formation: '名詞 ＋をはじめ（をはじめとして・をはじめとする＋名詞）',
    usageScene: '致谢时以校长为首、旅行去了以日本为代表的多国',
    nuance: '代表格＋同類の広がり。式辞・紹介文の定番',
    register: 'written',
    sourceExample: src('日本をはじめ、いろんな国に旅行をしました。', '829f14c31fad6f8c'),
    examplesJa: ['日本をはじめ、いろんな国に旅行をしました。',
                 '両親をはじめ、多くの人に支えられて今があります。'],
    examplesZh: ['以日本为代表，去了很多国家旅行。', '有以父母为首的许多人支持，才有今天的我。'],
    furigana: 'にほんを はじめ、いろんな くにに りょこうを しました。',
    commonMistakesZh: '「をはじめ」的前项必须是同类中的代表：「犬をはじめ、たくさんの家具」×（类别不同）。修饰名词用「をはじめとする」',
    learnerFocus: '获奖感言、婚礼致辞的黄金开头：「先生をはじめ、皆さまに感謝します」。正式场合一句到位',
    similarPatterns: ['〜を代表として', '〜など'],
    contrast: '「をはじめ」＝代表例→同類へ展開；「を中心に」＝重点・中核；「など」＝単純な例示',
    recognition: { promptZh: '「校長先生をはじめ、諸先生方に感謝します」在感谢谁？',
      options: ['以校长为首的全体老师', '只感谢校长一人', '除校长外的老师', '学生们'],
      answerIndex: 0, distractorReason: '「をはじめ」＝代表＋其余同类全体',
      explanationZh: '代表例＋同类的整体感谢' },
    production: { promptJa: '感謝の言葉を「〜をはじめ」で言ってください。',
      promptZh: '用「〜をはじめ」说一段致谢。',
      expected: ['をはじめ'], acceptable: ['〜をはじめとして'] },
    practice: { themeJa: 'スピーチで感謝を述べる', starterJa: '受賞スピーチ風に、支えてくれた人へ感謝を述べてみましょう。',
      starterZh: '用获奖感言的口吻感谢支持你的人。', targetUse: '〜をはじめ' },
    vocabularyLinks: ['fi-iku', 'fi-kazoku'] }),
  g({ grammarId: 'n2g-178', pattern: '〜を踏まえて', reading: 'をふまえて', unit: 12, zhSourceRowId: null,
    meaningJa: '〜を前提・材料として次を考えて',
    explanationZh: '在总结…的基础上、结合…（做下一步）。消化前项经验后规划后项',
    formation: '名詞（結果・意見・反省・現状） ＋を踏まえて',
    usageScene: '总结这次结果定下次目标、结合大家意见修改方案',
    nuance: 'ビジネス・会議の頻出語。「反省を踏まえて」は成長の定型',
    register: 'written',
    sourceExample: src('今回の結果を踏まえて、次の目標を計画した方がよいです。', 'cbac7522492fa448'),
    examplesJa: ['今回の結果を踏まえて、次の目標を計画した方がよいです。',
                 '皆さんの意見を踏まえて、企画を修正しました。'],
    examplesZh: ['最好在总结这次结果的基础上，规划下一个目标。', '结合大家的意见，修改了企划。'],
    furigana: 'こんかいの けっかを ふまえて、つぎの もくひょうを けいかく した ほうが よいです。',
    commonMistakesZh: 'U9的「に基づいて」是忠于根据（数据→判断），「を踏まえて」是消化经验再展开（结果→下一步）。会议上说「それを踏まえて」＝在此基础上',
    learnerFocus: '商务日语的高频词。「前回の反省を踏まえて」开头的汇报，显得你会复盘',
    similarPatterns: ['〜に基づいて', '〜を受けて'],
    contrast: '「を踏まえて」＝経験・結果を消化して次へ；「に基づいて」＝根拠に忠実；「を受けて」＝出来事への対応',
    recognition: { promptZh: '「失敗を踏まえて、やり方を変えた」的过程是？',
      options: ['吸取失败教训后改变做法', '无视失败的教训继续原来的做法', '因失败而放弃', '还没有开始做'],
      answerIndex: 0, distractorReason: '「を踏まえて」＝把前项作为经验教训消化后行动',
      explanationZh: '复盘→改进的流程' },
    production: { promptJa: '反省を次に生かす計画を「〜を踏まえて」で言ってください。',
      promptZh: '用「〜を踏まえて」说一个吸取教训后的计划。',
      expected: ['を踏まえて'], acceptable: ['反省を踏まえて'] },
    practice: { themeJa: '振り返りから次を語る', starterJa: '最近の反省を、次にどう生かしますか？',
      starterZh: '最近的教训你打算怎么用在下一步？', targetUse: '〜を踏まえて' },
    vocabularyLinks: ['fi-kangaeru', 'fi-yotei'] }),
  g({ grammarId: 'n2g-179', pattern: '〜をめぐって', reading: 'をめぐって', unit: 12, zhSourceRowId: null,
    meaningJa: '〜を争点・話題の的にして',
    explanationZh: '围绕…（展开争论、讨论）。后项多是对立、争执、议论',
    formation: '名詞（争点になる話題） ＋をめぐって（をめぐる＋名詞）',
    usageScene: '围绕安全性进行讨论、围绕遗产家人争执、围绕新规展开争论',
    nuance: '後件は「争う・対立する・議論する・裁判になる」等の攻防系',
    register: 'written',
    sourceExample: src('機械の安全性をめぐって、いろんな施策の検討をしています。', '9d6914d211588b64'),
    examplesJa: ['機械の安全性をめぐって、いろんな施策の検討をしています。',
                 '遺産をめぐって、家族が対立するドラマをよく見ます。'],
    examplesZh: ['围绕机器的安全性，正在讨论各种对策。', '我常看围绕遗产家人对立的电视剧。'],
    furigana: 'きかいの あんぜんせいを めぐって、いろんな しさくの けんとうを しています。',
    commonMistakesZh: '和「について」的区别：「について」中立地谈论；「をめぐって」暗含多方争执・攻防。「彼について話す」（聊他）／「彼をめぐって争う」（为他争风吃醋）',
    learnerFocus: '新闻读解的关键词：「法案をめぐって与野党が対立」。看到它就知道后面是争议',
    similarPatterns: ['〜について', '〜に関して'],
    contrast: '「をめぐって」＝争点への多方攻防；「について」＝中立の話題提示；「に関して」＝硬い関連提示',
    recognition: { promptZh: '「その土地をめぐって、争いが続いている」说明？',
      options: ['围绕那块地的争执在持续', '那块地无人问津', '争执已经解决', '大家在地上跑圈'],
      answerIndex: 0, distractorReason: '「をめぐって」后接对立・争执类内容',
      explanationZh: '争点＋攻防的构造' },
    production: { promptJa: '議論になっている話題を「〜をめぐって」で紹介してください。',
      promptZh: '用「〜をめぐって」介绍一个有争议的话题。',
      expected: ['をめぐって'], acceptable: ['〜をめぐる'] },
    practice: { themeJa: 'ニュースを要約する', starterJa: '最近気になった「議論になっている話題」は何ですか？',
      starterZh: '最近你关注的有争议的话题是什么？', targetUse: '〜をめぐって' },
    vocabularyLinks: ['fi-iken', 'fi-mondai'] }),
  g({ grammarId: 'n2g-180', pattern: '〜をもとにして', reading: 'をもとにして', unit: 12, zhSourceRowId: null,
    meaningJa: '〜を材料・原型にして（作り出す）',
    explanationZh: '以…为素材（原型）创作。把前项当作材料加工出后项',
    formation: '名詞 ＋をもとに（して）（をもとにした＋名詞）',
    usageScene: '根据亲身经历编写例句、根据真实事件拍电影',
    nuance: '創作・加工の自由度がある。忠実な根拠は「に基づいて」',
    register: 'both',
    sourceExample: src('私自身の経験をもとにして、例文をたくさん作りました。ありがとうございました。', '299c161f4452369d'),
    examplesJa: ['私自身の経験をもとにして、例文をたくさん作りました。ありがとうございました。',
                 'このドラマは、実際の事件をもとにして作られました。'],
    examplesZh: ['以我自身的经验为素材，编写了很多例句。谢谢大家。', '这部剧是根据真实事件改编的。'],
    furigana: 'わたしじしんの けいけんを もとにして、れいぶんを たくさん つくりました。ありがとうございました。',
    commonMistakesZh: '三个「根据」收官整理：「をもとにして」＝素材加工（改编）；「に基づいて」＝忠于根据（依据）；「を踏まえて」＝消化经验（结合）。写作文时按加工自由度选择',
    learnerFocus: '介绍作品来历的句式：「実話をもとにした映画」（根据真实故事改编的电影）。聊影视剧立刻用上',
    similarPatterns: ['〜に基づいて', '〜を踏まえて'],
    contrast: '「をもとにして」＝材料からの創作（自由度高）；「に基づいて」＝根拠への忠実；「を踏まえて」＝経験の消化',
    recognition: { promptZh: '「実話をもとにした映画」是什么样的电影？',
      options: ['根据真实故事改编的电影', '内容完全是虚构出来的电影', '纪录片一样原封不动的实录', '还完全没有开始拍摄的电影'],
      answerIndex: 0, distractorReason: '「をもとにした」＝以素材为原型的再创作（有改编）',
      explanationZh: '素材→创作的加工关系' },
    production: { promptJa: '経験から何かを作った話を「〜をもとにして」で言ってください。',
      promptZh: '用「〜をもとにして」说一件从经验中创造出来的东西。',
      expected: ['をもとに'], acceptable: ['〜をもとにした'] },
    practice: { themeJa: '自分の経験を作品にする', starterJa: 'あなたの経験をもとに、何かを作るとしたら何を作りますか？',
      starterZh: '如果以你的经历为素材创作，你想做什么？', targetUse: '〜をもとにして' },
    vocabularyLinks: ['fi-keiken', 'fi-tsukuru'] }),
];
