// Phase 3P-5: N2文法完成draft Unit 5（No.61〜75・14文型）＋繰越4件（034/037/049/055）。
// rightsStatus: teacher_created_confirmed。第1例文=原本（文型が明確）、第2例文=独自（実生活）。
import type { N2GrammarDraft } from './n2GrammarDrafts';

const g = (p: Omit<N2GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey' | 'runtimeExampleOrigin'> & { reviewKey?: string; runtimeExampleOrigin?: N2GrammarDraft['runtimeExampleOrigin'] }): N2GrammarDraft =>
  ({ level: 'N2', route: 'n2-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, runtimeExampleOrigin: 'source_confirmed', ...p });

const src = (text: string, hash: string) =>
  ({ text, hash, rightsStatus: 'teacher_created_confirmed' as const });

export const N2_GRAMMAR_DRAFTS_UNIT5: N2GrammarDraft[] = [
  // ── 繰越4件 ──
  g({ grammarId: 'n2g-034', pattern: '〜からすると', reading: 'からすると', unit: 3, zhSourceRowId: null,
    meaningJa: '〜を根拠に判断すると',
    explanationZh: '从…来推断。以某个迹象为根据做推测',
    formation: '名詞 ＋からすると／からすれば',
    usageScene: '从邮件内容、表情、数据等迹象做推测',
    nuance: '原本メモに「31・37と同じ」とあるが、「からすると」は根拠→推測の含みが最も強い。' +
            '後半は推量（かもしれない・ようだ）が続きやすい',
    register: 'both',
    sourceExample: src('このメールの内容からすると、私に好意があるかもしれないです。', '6ae853d6f100c992'),
    examplesJa: ['このメールの内容からすると、私に好意があるかもしれないです。',
                 '返信の速さからすると、急ぎの案件のようです。'],
    examplesZh: ['从这封邮件的内容来推断，说不定对我有好感。', '从回复的速度来看，似乎是急件。'],
    furigana: 'この メールの ないようから すると、わたしに こういが あるかも しれないです。',
    commonMistakesZh: '「からすると」の後半は推量で受ける。「からすると、行きます」のような意志文は不自然',
    learnerFocus: '証拠→推測の流れを作る接続。「からいうと」（立場）との違いは根拠の具体性',
    similarPatterns: ['〜からいうと', '〜から見ると', '〜から判断して'],
    contrast: '「からすると」＝根拠からの推測；「からいうと」＝立場・観点；「から見ると」＝視点',
    recognition: { promptZh: '「足跡からすると」后面最自然的是？',
      options: ['犯人は二人いたようだ', '私は行きます', '足が痛いです', '靴を買います'],
      answerIndex: 0, distractorReason: '「からすると」の後半は根拠に基づく推量',
      explanationZh: '根拠→推量の流れ' },
    production: { promptJa: '相手の様子からの推測を「〜からすると」で言ってください。',
      promptZh: '用「〜からすると」根据对方的样子做推测。',
      expected: ['からすると'], acceptable: ['〜からすれば'] },
    practice: { themeJa: 'サインから推測する', starterJa: '同僚の様子からすると、今日は忙しそうですか？',
      starterZh: '从同事的样子来推断，今天忙吗？', targetUse: '〜からすると' },
    vocabularyLinks: ['fi-jouhou', 'fi-tabun'] }),
  g({ grammarId: 'n2g-037', pattern: '〜から見ると', reading: 'からみると', unit: 3, zhSourceRowId: null,
    meaningJa: '〜の視点・状況から見て',
    explanationZh: '从…（的角度/形势）来看',
    formation: '名詞 ＋から見ると／から見れば／から見て',
    usageScene: '从当前形势、别人的角度评价事情',
    nuance: '原本メモに「31・34と同じ」とあるが、「から見ると」は視点の移動が核。' +
            '他者視点（外国人から見ると）の用法が特徴的',
    register: 'both',
    sourceExample: src('今のコロナ情勢から見ると、留学をするのは難しいです。', '6055f21a13227085'),
    examplesJa: ['今のコロナ情勢から見ると、留学をするのは難しいです。',
                 '日本人から見ると普通のことでも、外国人には驚きです。'],
    examplesZh: ['从现在的疫情形势来看，留学很难。', '在日本人看来很平常的事，对外国人来说却很吃惊。'],
    furigana: 'いまの コロナじょうせいから みると、りゅうがくを するのは むずかしいです。',
    commonMistakesZh: '「から見ると」は視点の切り替え。自分の意見を強く主張するなら「と思います」で受ける',
    learnerFocus: '「中国人から見ると〜」で文化差を語ると、雑談・発表で説得力が出る',
    similarPatterns: ['〜からすると', '〜からいうと', '〜にとって'],
    contrast: '「から見ると」＝視点；「からすると」＝根拠推測；「にとって」＝利害・評価の対象',
    recognition: { promptZh: '「外国人から見ると」是什么意思？',
      options: ['在外国人看来', '因为是外国人', '外国人正在看', '看外国人'],
      answerIndex: 0, distractorReason: '「から見ると」表示视点的切换',
      explanationZh: '視点の移動' },
    production: { promptJa: '文化の違いを「中国人から見ると」で言ってください。',
      promptZh: '用「中国人から見ると」说一个文化差异。',
      expected: ['から見ると'], acceptable: ['〜から見れば', '〜から見て'] },
    practice: { themeJa: '自国の視点で日本を語る', starterJa: '中国人から見ると、日本の何が不思議ですか？',
      starterZh: '在中国人看来，日本的什么很不可思议？', targetUse: '〜から見ると' },
    vocabularyLinks: ['fi-joukyou', 'fi-chugoku'] }),
  g({ grammarId: 'n2g-049', pattern: '〜ことは〜が', reading: 'ことは〜が', unit: 4, zhSourceRowId: null,
    meaningJa: '確かに〜ではあるが（留保つきの認め）',
    explanationZh: '…是…，但是…。先承认再转折',
    formation: '同じ用言を繰り返す: Aことは＋A＋が',
    usageScene: '承认优点后指出问题（好吃是好吃，但太贵）',
    nuance: '同一語の繰り返しが形式上の特徴。譲歩→本音の流れ',
    register: 'both',
    matchKeys: ['ことは'],
    sourceExample: src('このイチゴは美味しいことは美味しいが、値段が高すぎて、なかなか買えません。', '313fac6b7e589ec3'),
    examplesJa: ['このイチゴは美味しいことは美味しいが、値段が高すぎて、なかなか買えません。',
                 '行くことは行きますが、遅れるかもしれません。'],
    examplesZh: ['这草莓好吃是好吃，但价格太贵，轻易买不起。', '去是会去的，但可能会迟到。'],
    furigana: 'この イチゴは おいしいことは おいしいが、ねだんが たかすぎて、なかなか かえません。',
    commonMistakesZh: '同じ語を2回繰り返すのが必須。「美味しいことは高いが」は不成立',
    learnerFocus: '角を立てずに本音を言う日本的な話法。依頼を渋々受けるときにも便利',
    similarPatterns: ['〜には〜が', '〜けど'],
    contrast: '「ことは〜が」＝譲歩してから本音；「けど」＝単純な逆接',
    recognition: { promptZh: '「読んだことは読んだが」暗示什么？',
      options: ['读是读了，但（没太懂等）', '完全没有读过一页', '读得非常认真透彻', '根本就不想去读'],
      answerIndex: 0, distractorReason: '先承认事实，后面接保留意见',
      explanationZh: '譲歩＋留保' },
    production: { promptJa: '「いいけれど問題もある」ことを「〜ことは〜が」で言ってください。',
      promptZh: '用「〜ことは〜が」说一件好是好但有问题的事。',
      expected: ['ことは'], acceptable: ['美味しいことは美味しいが'] },
    practice: { themeJa: '本音を柔らかく言う', starterJa: '日本の生活で「いいことはいいが…」と思うことは？',
      starterZh: '日本生活中有什么「好是好，但…」的事？', targetUse: '〜ことは〜が' },
    vocabularyLinks: ['fi-takai', 'fi-oishii'] }),
  g({ grammarId: 'n2g-055', pattern: '〜上は（じょうは）', reading: 'じょうは', unit: 4, zhSourceRowId: null,
    meaningJa: '〜の面では（データ上・表面上）',
    explanationZh: '在…层面上、从…上看（数据上/表面上/法律上）',
    formation: '名詞 ＋上（じょう）は',
    usageScene: '「数据上没问题但…」等、限定した側面の判断',
    nuance: '「〜上では」とほぼ同義。後半に「実際は…」の転換が来やすい',
    register: 'written',
    matchKeys: ['上は', '上では'],
    sourceExample: src('データ上は問題ないですが、常に警戒しないといけないです。', '1eac1299b4b78a82'),
    examplesJa: ['データ上は問題ないですが、常に警戒しないといけないです。',
                 '書類上は完了していますが、現場の確認が残っています。'],
    examplesZh: ['数据上没有问题，但必须时刻警惕。', '文件上已经完成，但现场确认还没做。'],
    furigana: 'データじょうは もんだい ないですが、つねに けいかい しないと いけないです。',
    commonMistakesZh: '「じょう」と読む。「うえ」と読むと別の文型（〜した上は）になる',
    learnerFocus: 'ビジネス報告の頻出。「表面上」「規則上」「計算上」など生産的な接尾',
    similarPatterns: ['〜上では', '〜の面では'],
    contrast: '「上は」＝側面の限定（転換含み）；「上で」＝〜してから',
    recognition: { promptZh: '「規則上はできません」暗示什么？',
      options: ['按规则不行（但也许有变通）', '完全没有相关规则', '规则明确允许这样做', '不知道规则的内容'],
      answerIndex: 0, distractorReason: '「上は」限定该侧面，常暗示其他侧面不同',
      explanationZh: '側面の限定' },
    production: { promptJa: '「表面上は〜が実際は」を「〜上は」で言ってください。',
      promptZh: '用「〜上は」说表面与实际的差异。',
      expected: ['上は'], acceptable: ['データ上は', '書類上は'] },
    practice: { themeJa: '建前と実際を報告する', starterJa: '「予定上は順調」でも実際はどうですか？',
      starterZh: '「计划上顺利」，实际怎么样？', targetUse: '〜上は' },
    vocabularyLinks: ['fi-mondai', 'fi-kakunin'] }),
  // ── Unit 5 本体 ──
  g({ grammarId: 'n2g-061', pattern: '〜だけあって', reading: 'だけあって', unit: 5, zhSourceRowId: null,
    meaningJa: 'さすが〜だから（それにふさわしく）',
    explanationZh: '不愧是…、正因为是…（名副其实）',
    formation: '名詞／動詞・形容詞普通形 ＋だけあって',
    usageScene: '夸奖某人不愧是（出身/职业/经验）',
    nuance: '感心・賞賛の含み。悪い内容には使いにくい',
    register: 'both',
    sourceExample: src('彼は北海道出身だけあって、寒さには強いようです。', '82b38e3f639aec79'),
    examplesJa: ['彼は北海道出身だけあって、寒さには強いようです。',
                 '毎日練習しているだけあって、発音がきれいです。'],
    examplesZh: ['他不愧是北海道出身，好像很耐寒。', '不愧是每天都练习，发音很漂亮。'],
    furigana: 'かれは ほっかいどう しゅっしん だけあって、さむさには つよいようです。',
    commonMistakesZh: '賞賛専用に近い。「不愧是骗子」のような皮肉は「だけあって」では不自然',
    learnerFocus: '人を褒める高級表現。「さすが」と併用すると自然（さすが〜だけあって）',
    similarPatterns: ['〜だけに', '〜にふさわしく'],
    contrast: '「だけあって」＝ふさわしい結果への感心；「だけに」＝それゆえ一層',
    recognition: { promptZh: '「元教師だけあって説明が上手だ」的语气是？',
      options: ['不愧是当过老师，说明很棒（赞赏）', '虽然当过老师却不行', '想当老师', '讨厌老师'],
      answerIndex: 0, distractorReason: '「だけあって」表示名副其实的赞赏',
      explanationZh: '賞賛の「不愧是」' },
    production: { promptJa: '人を「〜だけあって」で褒めてください。',
      promptZh: '用「〜だけあって」夸奖一个人。',
      expected: ['だけあって'], acceptable: ['さすが〜だけあって'] },
    practice: { themeJa: '身近な人を褒める', starterJa: '「さすが〜だけあって」と感心した人はいますか？',
      starterZh: '有让你觉得「不愧是…」的人吗？', targetUse: '〜だけあって' },
    vocabularyLinks: ['fi-jouzu', 'fi-shusshin'] }),
  g({ grammarId: 'n2g-062', pattern: 'たとえ〜ても', reading: 'たとえ〜ても', unit: 5, zhSourceRowId: null,
    meaningJa: 'もし〜という場合でも（変わらない）',
    explanationZh: '即使…也…。「ても」的强调形',
    formation: 'たとえ＋動詞て形／い形容詞くて／名詞・な形容詞で ＋も',
    usageScene: '表明无论条件如何都不改变的决心',
    nuance: '「たとえ」が仮定を強調。決意・約束の文脈で力強い',
    register: 'both',
    matchKeys: ['たとえ'],
    sourceExample: src('たとえ今は無理であっても、いつかまた中国に戻りたいです。', 'f7091b2c73639dc0'),
    examplesJa: ['たとえ今は無理であっても、いつかまた中国に戻りたいです。',
                 'たとえ反対されても、この道を選びます。'],
    examplesZh: ['即使现在做不到，总有一天也想再回中国。', '即使被反对，我也选这条路。'],
    furigana: 'たとえ いまは むりで あっても、いつか また ちゅうごくに もどりたいです。',
    commonMistakesZh: '「たとえ」と呼応するのは「ても」。「たとえ〜たら」は誤り',
    learnerFocus: '決意表明のスピーチで最も映える構文の一つ。「たとえ〜ても、私は〜」の型で',
    similarPatterns: ['〜ても', 'どんなに〜ても'],
    contrast: '「たとえ〜ても」＝仮定の強調；「どんなに〜ても」＝程度の強調',
    recognition: { promptZh: '「たとえ」和哪个呼应？',
      options: ['〜ても', '〜たら', '〜なら', '〜ので'],
      answerIndex: 0, distractorReason: '「たとえ〜ても」是固定呼应',
      explanationZh: '呼応の固定形' },
    production: { promptJa: '決意を「たとえ〜ても」で言ってください。',
      promptZh: '用「たとえ〜ても」表达决心。',
      expected: ['たとえ'], acceptable: ['たとえ〜ても'] },
    practice: { themeJa: '変わらない決意を語る', starterJa: 'たとえ何があっても続けたいことは？',
      starterZh: '即使发生什么也想坚持的事是什么？', targetUse: 'たとえ〜ても' },
    vocabularyLinks: ['fi-muri', 'fi-kimeru'] }),
  g({ grammarId: 'n2g-063', pattern: '〜たところ', reading: 'たところ', unit: 5, zhSourceRowId: null,
    meaningJa: '〜したら（その結果…だった）',
    explanationZh: '（做了）…之后，（发现/结果）…。书面的偶发结果',
    formation: '動詞た形 ＋ところ',
    usageScene: '报告尝试后的结果（问了之后对方爽快答应等）',
    nuance: '因果ではなく「してみたら偶然こうだった」。ビジネス報告の定番',
    register: 'written',
    sourceExample: src('日本語授業をお願いしたところ、快く引き受けてくれました。', 'ebbfa437803435f5'),
    examplesJa: ['日本語授業をお願いしたところ、快く引き受けてくれました。',
                 '問い合わせたところ、在庫があるとのことでした。'],
    examplesZh: ['拜托对方上日语课，结果对方爽快地答应了。', '咨询之后，得知有库存。'],
    furigana: 'にほんごじゅぎょうを おねがいした ところ、こころよく ひきうけて くれました。',
    commonMistakesZh: '「たら」より書面的で、意外・発見の含み。命令や意志は続かない',
    learnerFocus: 'ビジネスメールの報告文「確認したところ〜でした」は超頻出',
    similarPatterns: ['〜たら', '〜た結果'],
    contrast: '「たところ」＝試行→偶発結果（書面）；「たら」＝口語；「た結果」＝因果',
    recognition: { promptZh: '「調べたところ」多用于什么场合？',
      options: ['商务报告（查了之后得知…）', '向部下下达命令时', '在卡拉OK唱歌时', '和邻居打招呼时'],
      answerIndex: 0, distractorReason: '「たところ」是书面报告的定番',
      explanationZh: '試行の結果報告' },
    production: { promptJa: '確認結果を「〜たところ」で報告してください。',
      promptZh: '用「〜たところ」报告确认结果。',
      expected: ['たところ'], acceptable: ['確認したところ', '聞いたところ'] },
    practice: { themeJa: 'ビジネス報告を書く', starterJa: '「問い合わせた結果」を丁寧に報告してみましょう',
      starterZh: '试着礼貌地报告咨询结果', targetUse: '〜たところ' },
    vocabularyLinks: ['fi-kakunin', 'fi-renraku'] }),
  g({ grammarId: 'n2g-065', pattern: '〜たとたんに', reading: 'たとたんに', unit: 5, zhSourceRowId: null,
    meaningJa: '〜した直後に（予期しないことが起きた）',
    explanationZh: '刚一…就（突然）…',
    formation: '動詞た形 ＋とたん（に）',
    usageScene: '描述刚做完某事瞬间发生的意外',
    nuance: '後半は予期しない出来事。自分の意志的行動は続かない',
    register: 'both',
    sourceExample: src('電車に乗ったとたんに、電車が急に止まりました。', '9c699da5a4c71c87'),
    examplesJa: ['電車に乗ったとたんに、電車が急に止まりました。',
                 '窓を開けたとたん、強い風が入ってきました。'],
    examplesZh: ['刚上电车，电车就突然停了。', '刚一开窗，强风就吹了进来。'],
    furigana: 'でんしゃに のった とたんに、でんしゃが きゅうに とまりました。',
    commonMistakesZh: '後半に意志文は不可。「家に着いたとたん、勉強しよう」は誤り',
    learnerFocus: 'ハプニングを語る定番。「か〜ないかのうちに」より使用頻度が高く汎用的',
    similarPatterns: ['〜か〜ないかのうちに', '〜と同時に'],
    contrast: '「たとたん」＝直後の意外；「と同時に」＝中立の同時',
    recognition: { promptZh: '「立ち上がったとたん」后面最自然的是？',
      options: ['めまいがした', '勉強しようと思う', '明日行く', 'ゆっくり考える'],
      answerIndex: 0, distractorReason: '後半は予期しない出来事',
      explanationZh: '直後の意外な出来事' },
    production: { promptJa: 'ハプニングを「〜たとたん」で言ってください。',
      promptZh: '用「〜たとたん」说一次突发事件。',
      expected: ['たとたん'], acceptable: ['〜たとたんに'] },
    practice: { themeJa: 'ハプニングを話す', starterJa: '「〜したとたん」に何かが起きた経験は？',
      starterZh: '有「刚一…就」发生什么的经历吗？', targetUse: '〜たとたんに' },
    vocabularyLinks: ['fi-densha', 'fi-deru'] }),
  g({ grammarId: 'n2g-066', pattern: '〜たばかり', reading: 'たばかり', unit: 5, zhSourceRowId: null,
    meaningJa: '〜した直後だ（まだ時間がたっていない）',
    explanationZh: '刚…（不久）。说话人觉得时间还短',
    formation: '動詞た形 ＋ばかり',
    usageScene: '刚来日本、刚起床、刚学过',
    nuance: '心理的な「まだ間もない」。実時間が長くても使える（去年来たばかり）',
    register: 'both',
    sourceExample: src('起きたばかりなのに、勉強をしなければいけません。', 'bf7b21f5bfefe8e4'),
    examplesJa: ['起きたばかりなのに、勉強をしなければいけません。',
                 '日本に来たばかりの頃は、電車の乗り方も分かりませんでした。'],
    examplesZh: ['明明刚起床，却必须学习。', '刚来日本的时候，连电车怎么坐都不知道。'],
    furigana: 'おきた ばかりなのに、べんきょうを しなければ いけません。',
    commonMistakesZh: '「たところ」（直後の一点）と違い「たばかり」は心理的な近さ。1年前でも「来たばかり」と言える',
    learnerFocus: '「来日したばかりの頃」は自分史を語る万能フレーズ',
    similarPatterns: ['〜たところだ', '〜て間もない'],
    contrast: '「たばかり」＝心理的な近さ；「たところ」＝物理的直後',
    recognition: { promptZh: '「習ったばかりなのに忘れた」的心情是？',
      options: ['明明刚学就忘了（懊恼）', '已经学了很长时间', '完全还没有开始学', '根本就不想学习'],
      answerIndex: 0, distractorReason: '「たばかり」+「のに」表达与预期的落差',
      explanationZh: '心理的な直後' },
    production: { promptJa: '来日した頃のことを「〜たばかり」で言ってください。',
      promptZh: '用「〜たばかり」说说刚来日本的时候。',
      expected: ['ばかり'], acceptable: ['来たばかり', '始めたばかり'] },
    practice: { themeJa: '初心者だった頃を振り返る', starterJa: '日本に来たばかりの頃、何に困りましたか？',
      starterZh: '刚来日本时，你为什么发愁？', targetUse: '〜たばかり' },
    vocabularyLinks: ['fi-okiru', 'fi-komaru'] }),
  g({ grammarId: 'n2g-067', pattern: '〜たびに', reading: 'たびに', unit: 5, zhSourceRowId: null,
    meaningJa: '〜するといつも',
    explanationZh: '每次…都会…。同一动作每次伴随同样的反应',
    formation: '動詞辞書形／名詞＋の ＋たびに',
    usageScene: '每次听这首歌都想起…、每次出错都不安',
    nuance: '繰り返し＋そのたび同じ反応。感情・記憶と相性がよい',
    register: 'both',
    sourceExample: src('間違えるたびに不安になります。', 'bf23726864a94264'),
    examplesJa: ['間違えるたびに不安になります。',
                 'この曲を聞くたびに、故郷を思い出します。'],
    examplesZh: ['每次出错都会不安。', '每次听这首歌，都会想起故乡。'],
    furigana: 'まちがえる たびに ふあんに なります。',
    commonMistakesZh: '接続は辞書形。「間違えたたびに」は誤り',
    learnerFocus: '「〜たびに思い出す」は郷愁・思い出話の定番。会話が深まる',
    similarPatterns: ['〜と、いつも', '〜ごとに'],
    contrast: '「たびに」＝毎回同じ反応；「ごとに」＝間隔・単位',
    recognition: { promptZh: '「帰国するたびに」是什么意思？',
      options: ['每次回国都…', '只回国一次', '不回国', '回国之后就不来了'],
      answerIndex: 0, distractorReason: '「たびに」表示每次都',
      explanationZh: '繰り返しの毎回' },
    production: { promptJa: '毎回起きることを「〜たびに」で言ってください。',
      promptZh: '用「〜たびに」说每次都会发生的事。',
      expected: ['たびに'], acceptable: ['聞くたびに', '会うたびに'] },
    practice: { themeJa: '繰り返す気持ちを話す', starterJa: '何をするたびに、故郷を思い出しますか？',
      starterZh: '每次做什么会想起故乡？', targetUse: '〜たびに' },
    vocabularyLinks: ['fi-omou', 'fi-kiku'] }),
  g({ grammarId: 'n2g-068', pattern: '〜だらけ', reading: 'だらけ', unit: 5, zhSourceRowId: null,
    meaningJa: '〜がたくさんついている／多すぎる（悪いもの）',
    explanationZh: '满是…、净是…（负面的东西）',
    formation: '名詞 ＋だらけ',
    usageScene: '满手伤、满地垃圾、错误百出',
    nuance: '負面限定（傷・泥・間違い・ほこり）。良いものには使わない',
    register: 'both',
    sourceExample: src('毎日料理や皿洗いをしていると、手が傷だらけになります。', 'ea36b54950f12edb'),
    examplesJa: ['毎日料理や皿洗いをしていると、手が傷だらけになります。',
                 '初めて書いた作文は、間違いだらけでした。'],
    examplesZh: ['每天做饭洗碗，手上满是伤口。', '第一次写的作文错误百出。'],
    furigana: 'まいにち りょうりや さらあらいを していると、てが きずだらけに なります。',
    commonMistakesZh: '「花だらけ」のような良いものは不自然。良い充満は「〜でいっぱい」',
    learnerFocus: '「間違いだらけでもいい」は学習マインドの話で頻出。自嘲にも使える',
    similarPatterns: ['〜でいっぱい', '〜まみれ'],
    contrast: '「だらけ」＝負面の多さ；「まみれ」＝表面に付着（泥まみれ）；「でいっぱい」＝中立',
    recognition: { promptZh: '「だらけ」的搭配哪个自然？',
      options: ['間違いだらけ', '花だらけの祝福', '笑顔だらけの賞', '希望だらけ'],
      answerIndex: 0, distractorReason: '「だらけ」用于负面事物',
      explanationZh: '負面限定の充満' },
    production: { promptJa: '失敗の多さを「〜だらけ」で言ってください。',
      promptZh: '用「〜だらけ」说满是错误的状态。',
      expected: ['だらけ'], acceptable: ['間違いだらけ', '傷だらけ'] },
    practice: { themeJa: '初心者時代を笑って話す', starterJa: '最初は間違いだらけだったことは何ですか？',
      starterZh: '你有什么一开始错误百出的事？', targetUse: '〜だらけ' },
    vocabularyLinks: ['fi-mondai', 'fi-hajimeru'] }),
  g({ grammarId: 'n2g-069', pattern: '〜ついでに', reading: 'ついでに', unit: 5, zhSourceRowId: null,
    meaningJa: '〜する機会を利用して、一緒に',
    explanationZh: '顺便…。利用做A的机会做B',
    formation: '動詞辞書形／た形／名詞＋の ＋ついでに',
    usageScene: '购物顺便取钱、出差顺便观光',
    nuance: '主目的はA、Bは付随。目上への依頼では「お手数ですが」を添える',
    register: 'both',
    sourceExample: src('買い物に行くついでに、ATMでお金を下ろしました。', '0a3f1b687de7a15d'),
    examplesJa: ['買い物に行くついでに、ATMでお金を下ろしました。',
                 '出張のついでに、その街の観光もしてきました。'],
    examplesZh: ['去买东西顺便在ATM取了钱。', '出差顺便在那个城市观了光。'],
    furigana: 'かいものに いく ついでに、エーティーエムで おかねを おろしました。',
    commonMistakesZh: '人に頼むとき「ついでに」だけだと軽く聞こえる。「もしついでがあれば」で柔らかく',
    learnerFocus: '生活効率の話題で自然に使える。「ついでと言っては何ですが」は大人の前置き',
    similarPatterns: ['〜がてら', '〜を機に'],
    contrast: '「ついでに」＝付随行動；「がてら」＝兼ねて（書面寄り）',
    recognition: { promptZh: '「散歩のついでに牛乳を買った」的主要目的是？',
      options: ['散步（买牛奶是顺便）', '专门出门去买牛奶', '在家里面喝牛奶', '出门去外面跑步'],
      answerIndex: 0, distractorReason: '「ついでに」的前项是主目的',
      explanationZh: '主目的＋付随行動' },
    production: { promptJa: '「ついでに」で効率よくしたことを言ってください。',
      promptZh: '用「ついでに」说一次顺便完成的事。',
      expected: ['ついでに'], acceptable: ['〜のついでに'] },
    practice: { themeJa: '効率のいい行動を話す', starterJa: '何かのついでにしていることはありますか？',
      starterZh: '你有什么顺便做的事吗？', targetUse: '〜ついでに' },
    vocabularyLinks: ['fi-kau', 'fi-iku'] }),
  g({ grammarId: 'n2g-070', pattern: '〜っこない', reading: 'っこない', unit: 5, zhSourceRowId: null,
    meaningJa: '絶対に〜ない（口語の強い否定）',
    explanationZh: '绝不可能…（口语的强烈否定）',
    formation: '動詞ます形 ＋っこない',
    usageScene: '朋友间断言不可能',
    nuance: 'かなり口語。目上には「〜わけがない」も避け「難しいと思います」',
    register: 'spoken',
    sourceExample: src('できっこないことでも、挑戦する価値はあります。', 'c12969753216db23'),
    examplesJa: ['できっこないことでも、挑戦する価値はあります。',
                 'そんなに覚えられっこないよ。'],
    examplesZh: ['即使是绝不可能做到的事，也有挑战的价值。', '那么多根本记不住啦。'],
    furigana: 'できっこない ことでも、ちょうせんする かちは あります。',
    commonMistakesZh: '完全な口語。作文・メールに書かない。友達との会話専用',
    learnerFocus: 'ドラマ・日常会話の聞き取り用。「無理に決まってる」と同じ温度感',
    similarPatterns: ['〜わけがない', '〜はずがない'],
    contrast: '口語度: 「はずがない」＜「わけがない」＜「っこない」',
    recognition: { promptZh: '「間に合いっこない」的语气是？',
      options: ['绝对赶不上（口语断言）', '也许还赶得上末班车', '已经顺利赶上了车', '这是正式的书面报告'],
      answerIndex: 0, distractorReason: '「っこない」是口语的强烈否定',
      explanationZh: '口語の強否定' },
    production: { promptJa: '友達との会話で「絶対無理」を「〜っこない」で言ってください。',
      promptZh: '用「〜っこない」在朋友对话中说绝对不可能。',
      expected: ['っこない'], acceptable: ['できっこない', '分かりっこない'] },
    practice: { themeJa: 'カジュアルに冗談を言う', starterJa: '「そんなの、できっこない！」と思ったことは？',
      starterZh: '有觉得「那绝对做不到！」的事吗？', targetUse: '〜っこない' },
    vocabularyLinks: ['fi-muri', 'fi-oboeru'] }),
  g({ grammarId: 'n2g-071', pattern: '〜つつ', reading: 'つつ', unit: 5, zhSourceRowId: null,
    meaningJa: '〜しながら（書面）／〜と思いながらも',
    explanationZh: '①一边…一边（书面）②虽然…却（明知故犯）',
    formation: '動詞ます形 ＋つつ（も）',
    usageScene: '①书面的同时进行 ②明知不好却还做',
    nuance: '②「つつも」は「だめだと思いつつも、つい」の自省文が定番',
    register: 'written',
    sourceExample: src('分からない単語を調べつつ、問題を解いています。', '8f222af2b55f15af'),
    examplesJa: ['分からない単語を調べつつ、問題を解いています。',
                 'よくないと思いつつも、夜中にラーメンを食べてしまいました。'],
    examplesZh: ['一边查不懂的单词，一边做题。', '明知不好，却还是半夜吃了拉面。'],
    furigana: 'わからない たんごを しらべつつ、もんだいを といています。',
    commonMistakesZh: '「ながら」の書面形。会話では「ながら」が自然。②の逆接用法は「つつも」',
    learnerFocus: '「思いつつも、つい〜」は自省・言い訳の大人な言い回し。作文で映える',
    similarPatterns: ['〜ながら', '〜のに'],
    contrast: '「つつ」＝書面の同時／逆接；「ながら」＝口語の同時',
    recognition: { promptZh: '「だめだと思いつつも」后面最自然的是？',
      options: ['つい買ってしまった', '買いませんでした', '買う予定はない', '買い物が好きだ'],
      answerIndex: 0, distractorReason: '「つつも」+明知故犯的行动',
      explanationZh: '自省の逆接' },
    production: { promptJa: '「よくないと思いつつも」した経験を言ってください。',
      promptZh: '用「〜つつも」说一次明知故犯的经历。',
      expected: ['つつ'], acceptable: ['思いつつも'] },
    practice: { themeJa: '小さな言い訳を笑って話す', starterJa: '「だめだと思いつつ」してしまうことは？',
      starterZh: '有什么明知不好却忍不住做的事？', targetUse: '〜つつも' },
    vocabularyLinks: ['fi-shiraberu', 'fi-taberu'] }),
  g({ grammarId: 'n2g-072', pattern: '〜つつある', reading: 'つつある', unit: 5, zhSourceRowId: null,
    meaningJa: '今まさに変化の途中だ',
    explanationZh: '正在逐渐…。变化正在进行中',
    formation: '動詞ます形 ＋つつある',
    usageScene: '描述缓慢但确实的变化（书面/新闻）',
    nuance: '進行中の変化。「ている」より変化の途中感が強い。書面調',
    register: 'written',
    sourceExample: src('だんだん日本語が分かりつつあります。', '38a6db34832878d2'),
    examplesJa: ['だんだん日本語が分かりつつあります。',
                 '働き方は、確実に変わりつつあります。'],
    examplesZh: ['渐渐地日语正在变得能懂了。', '工作方式正在切实地发生变化。'],
    furigana: 'だんだん にほんごが わかりつつ あります。',
    commonMistakesZh: '「つつ」（同時・逆接）と「つつある」（変化進行）は別物。「ある」の有無で意味が変わる',
    learnerFocus: '自分の成長を客観的に語れる。「上達しつつある」は面談・振り返りで使える',
    similarPatterns: ['〜ている', '〜一方だ'],
    contrast: '「つつある」＝変化の途中（中立）；「一方だ」＝単方向（多く負面）',
    recognition: { promptZh: '「回復しつつある」是什么状态？',
      options: ['正在逐渐恢复', '已完全恢复', '恶化了', '没有变化'],
      answerIndex: 0, distractorReason: '「つつある」表示变化进行中',
      explanationZh: '進行中の変化' },
    production: { promptJa: '自分の変化を「〜つつある」で言ってください。',
      promptZh: '用「〜つつある」说你正在发生的变化。',
      expected: ['つつあ'], acceptable: ['分かりつつある', '慣れつつある'] },
    practice: { themeJa: '成長の途中を語る', starterJa: '今、何が「できつつある」と感じますか？',
      starterZh: '你觉得现在什么「正在逐渐做到」？', targetUse: '〜つつある' },
    vocabularyLinks: ['fi-kawaru', 'fi-nareru'] }),
  g({ grammarId: 'n2g-073', pattern: '〜っぽい', reading: 'っぽい', unit: 5, zhSourceRowId: null,
    meaningJa: '〜の感じがする／〜しやすい',
    explanationZh: '①有点像…、…感 ②容易…（忘れっぽい）',
    formation: '名詞／動詞ます形 ＋っぽい（い形容詞活用）',
    usageScene: '①印象（子供っぽい・安っぽい）②性质（忘れっぽい・飽きっぽい）',
    nuance: 'カジュアル。①はやや批判的な含みが出やすい',
    register: 'spoken',
    sourceExample: src('最近歳をとって、忘れっぽいことが多いです。', '8f481f915bea3019'),
    examplesJa: ['最近歳をとって、忘れっぽいことが多いです。',
                 'この服は色が安っぽく見えるので、やめました。'],
    examplesZh: ['最近上了年纪，变得健忘。', '这件衣服颜色显得廉价，所以没买。'],
    furigana: 'さいきん としを とって、わすれっぽい ことが おおいです。',
    commonMistakesZh: '「子供っぽい」（幼稚・批判）と「子供らしい」（像孩子该有的样子・中立）は別',
    learnerFocus: '「〜らしい」との対比が試験頻出。っぽい=負面寄りの印象',
    similarPatterns: ['〜らしい', '〜みたい'],
    contrast: '「っぽい」＝印象（負面寄り）；「らしい」＝典型性（中立〜正面）',
    recognition: { promptZh: '「大人っぽい」和「大人らしい」，哪个更可能是夸奖高中生？',
      options: ['大人っぽい（显得成熟）', '大人らしい（有大人样）', '两个都不能使用', '两个都非常失礼'],
      answerIndex: 0, distractorReason: '对还不是大人的人说「大人っぽい」是夸成熟',
      explanationZh: 'っぽい=像…的印象' },
    production: { promptJa: '自分の性質を「〜っぽい」で言ってください。',
      promptZh: '用「〜っぽい」说说自己的性格倾向。',
      expected: ['っぽい'], acceptable: ['忘れっぽい', '飽きっぽい'] },
    practice: { themeJa: '自分の性質を軽く話す', starterJa: '自分は「〜っぽい」性格だと思いますか？',
      starterZh: '你觉得自己是容易…的性格吗？', targetUse: '〜っぽい' },
    vocabularyLinks: ['fi-wasureru', 'fi-kimochi'] }),
  g({ grammarId: 'n2g-074', pattern: '〜つもりだ', reading: 'つもりだ', unit: 5, zhSourceRowId: null,
    meaningJa: '〜する意志だ／〜したと思い込んでいる',
    explanationZh: '①打算… ②自以为…（实际未必）',
    formation: '①動詞辞書形＋つもりだ ②動詞た形／形容詞＋つもりだ',
    usageScene: '①计划 ②「说明清楚了（自以为）」的认知差',
    nuance: 'N2では②の「思い込み」用法が主役。「言ったつもり」＝说了（我以为）',
    register: 'both',
    sourceExample: src('明日から勉強をするつもりです。', '07263de13953ab96'),
    examplesJa: ['明日から勉強をするつもりです。',
                 'ちゃんと説明したつもりでしたが、伝わっていませんでした。'],
    examplesZh: ['打算从明天开始学习。', '我自以为好好说明了，结果没传达到。'],
    furigana: 'あしたから べんきょうを する つもりです。',
    commonMistakesZh: '「た形＋つもり」は「自以为做了」。①の意志と混同すると誤読する',
    learnerFocus: '仕事のすれ違い「送ったつもりでした」は謝罪と原因説明を兼ねる実用表現',
    similarPatterns: ['〜予定だ', '〜と思い込む'],
    contrast: '辞書形＋つもり＝意志；た形＋つもり＝思い込み。接続で意味が反転',
    recognition: { promptZh: '「送ったつもりでした」是什么意思？',
      options: ['自以为发了（实际没发）', '现在打算马上就发', '确认过一定发出了', '完全不想发消息'],
      answerIndex: 0, distractorReason: 'た形＋つもり＝自以为做了',
      explanationZh: '思い込みの用法' },
    production: { promptJa: '「したつもりだったが実際は違った」経験を言ってください。',
      promptZh: '用「〜たつもり」说一次自以为做了的失误。',
      expected: ['つもり'], acceptable: ['〜たつもりでした'] },
    practice: { themeJa: 'すれ違いの経験を話す', starterJa: '「言ったつもり」ですれ違ったことはありますか？',
      starterZh: '有过「自以为说了」而产生误会的事吗？', targetUse: '〜たつもり' },
    vocabularyLinks: ['fi-setsumei', 'fi-tsutaeru'] }),
  g({ grammarId: 'n2g-075', pattern: '〜つもりで', reading: 'つもりで', unit: 5, zhSourceRowId: null,
    meaningJa: '〜のような気持ちで（実際は違うが）',
    explanationZh: '当作…、抱着…的心态（去做）',
    formation: '動詞辞書形／た形／名詞＋の ＋つもりで',
    usageScene: '当作正式演出来练习、当作被骗买一次',
    nuance: '仮想の心構え。「本番のつもりで」「死んだつもりで」等の定型',
    register: 'both',
    sourceExample: src('毎日頑張るつもりでスケジュールを立てましたが、無理でした。', '6ecb84227b35cdfa'),
    examplesJa: ['毎日頑張るつもりでスケジュールを立てましたが、無理でした。',
                 '本番のつもりで、声に出して練習しましょう。'],
    examplesZh: ['抱着每天都努力的打算排了日程，结果做不到。', '当作正式上场，出声练习吧。'],
    furigana: 'まいにち がんばる つもりで スケジュールを たてましたが、むりでした。',
    commonMistakesZh: '「つもりだ」（意志・思い込み）と「つもりで」（心構えで行動）は用法が違う',
    learnerFocus: '「本番のつもりで練習する」は学習アドバイスの定番。自分にも他人にも使える',
    similarPatterns: ['〜気持ちで', '〜と思って'],
    contrast: '「つもりで」＝仮想の心構え；「気持ちで」＝より軽い心情',
    recognition: { promptZh: '「本番のつもりで練習する」是什么意思？',
      options: ['当作正式演出来练习', '不练习', '正式演出中', '讨厌练习'],
      answerIndex: 0, distractorReason: '「つもりで」=抱着…的心态',
      explanationZh: '仮想の心構え' },
    production: { promptJa: '心構えを「〜つもりで」で言ってください。',
      promptZh: '用「〜つもりで」说你的心态。',
      expected: ['つもりで'], acceptable: ['本番のつもりで'] },
    practice: { themeJa: '練習の心構えを話す', starterJa: '会話練習を「何のつもりで」やっていますか？',
      starterZh: '你抱着什么心态做会话练习？', targetUse: '〜つもりで' },
    vocabularyLinks: ['fi-ganbaru', 'fi-junbi'] }),
  // CEO統合判断（2026-07-30）: 独立文型として維持 → 本編昇格（元・同義判断待ちpre-draft）
  g({ grammarId: 'n2g-064', pattern: '〜たところが', reading: 'たところが', unit: 5, zhSourceRowId: null,
    meaningJa: '〜したら、（予想に反して）',
    explanationZh: '本以为…结果却…。行动后出现与预期相反的结果',
    formation: '動詞た形 ＋ところが',
    usageScene: '以为他知道结果他也不知道、以为便宜结果更贵',
    nuance: '「が」が付くと逆接が確定。中立の「たところ」との差が判断待ちの核',
    register: 'both',
    sourceExample: src('彼なら知っていると思って聞いたところが、彼も知らなかったです。', 'a5353c5775ce195f'),
    examplesJa: ['彼なら知っていると思って聞いたところが、彼も知らなかったです。',
                 '安いと思って買ったところが、隣の店のほうがさらに安かったです。'],
    examplesZh: ['本以为他知道就去问了，结果他也不知道。', '本以为便宜就买了，结果隔壁店更便宜。'],
    furigana: 'かれなら しっていると おもって きいた ところが、かれも しらなかったです。',
    commonMistakesZh: '「問い合わせたところ、翌日返事が来た」（中立结果）／「問い合わせたところが、返事が来ない」（事与愿违）。有没有「が」方向不同',
    learnerFocus: '讲「本以为…谁知…」的故事必备。失败谈有了这个词就有了转折点',
    similarPatterns: ['〜たところ', '〜のに'],
    contrast: '「たところが」＝期待→逆の結果；「たところ」＝行動→中立の判明；「のに」＝不満の逆接',
    recognition: { promptZh: '「頼りにして聞いたところが、知らなかった」的展开是？',
      options: ['本指望他知道，结果落空了', '果然如预期他知道', '一开始就没抱希望', '他详细地告诉了我'],
      answerIndex: 0, distractorReason: '「たところが」＝预期与结果相反',
      explanationZh: '期待落空的逆转' },
    production: { promptJa: '期待と逆だった経験を「〜たところが」で言ってください。',
      promptZh: '用「〜たところが」说一次事与愿违的经历。',
      expected: ['ところが'], acceptable: ['〜たところが'] },
    practice: { themeJa: '当てが外れた話をする', starterJa: '「きっと大丈夫」と思ったのに外れた経験は？',
      starterZh: '有没有「本以为稳了」却落空的经历？', targetUse: '〜たところが' },
    vocabularyLinks: ['fi-kiku', 'fi-wakaru'] }),
];
