// Phase 3P-5: N2文法完成draft Unit 6（No.76〜90・15文型）。
// rightsStatus: teacher_created_confirmed。第1例文=原本、第2例文=独自（実生活）。
import type { N2GrammarDraft } from './n2GrammarDrafts';

const g = (p: Omit<N2GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey' | 'runtimeExampleOrigin'> & { reviewKey?: string; runtimeExampleOrigin?: N2GrammarDraft['runtimeExampleOrigin'] }): N2GrammarDraft =>
  ({ level: 'N2', route: 'n2-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, runtimeExampleOrigin: 'source_confirmed', ...p });

const src = (text: string, hash: string) =>
  ({ text, hash, rightsStatus: 'teacher_created_confirmed' as const });

export const N2_GRAMMAR_DRAFTS_UNIT6: N2GrammarDraft[] = [
  g({ grammarId: 'n2g-076', pattern: '〜て以来', reading: 'ていらい', unit: 6, zhSourceRowId: null,
    meaningJa: '〜してから今までずっと',
    explanationZh: '自从…以来（状态一直持续到现在）',
    formation: '動詞て形 ＋以来',
    usageScene: '结婚以来、来日以来的持续状态',
    nuance: '一回きりの出来事が起点。「て以来ずっと」の形が多い。近い過去には使わない',
    register: 'written',
    sourceExample: src('結婚して以来、平和な日々を過ごしています。', 'e1c84a504fbc8256'),
    examplesJa: ['結婚して以来、平和な日々を過ごしています。',
                 '来日して以来、一度も帰国していません。'],
    examplesZh: ['结婚以来，一直过着平静的日子。', '来日本以来，一次也没回过国。'],
    furigana: 'けっこんして いらい、へいわな ひびを すごして います。',
    commonMistakesZh: '「昨日食べて以来」のような近い過去は不自然。ある程度の期間が必要',
    learnerFocus: '「来日して以来」は自分史を語る定番の起点表現',
    similarPatterns: ['〜てから', '〜たきり'],
    contrast: '「て以来」＝起点から継続（中立）；「たきり」＝その後何もない（否定的）',
    recognition: { promptZh: '「卒業して以来」是什么意思？',
      options: ['毕业以来一直…', '毕业之前', '快要毕业', '完全没有打算要毕业'],
      answerIndex: 0, distractorReason: '「て以来」表示从起点持续至今',
      explanationZh: '起点からの継続' },
    production: { promptJa: '来日してからの変化を「〜て以来」で言ってください。',
      promptZh: '用「〜て以来」说来日本以来的变化。',
      expected: ['以来'], acceptable: ['来日して以来'] },
    practice: { themeJa: '人生の節目からの変化を話す', starterJa: '日本に来て以来、続けていることは？',
      starterZh: '来日本以来一直坚持的事是什么？', targetUse: '〜て以来' },
    vocabularyLinks: ['fi-kuru', 'fi-tsuzukeru'] }),
  g({ grammarId: 'n2g-077', pattern: '〜てからでないと', reading: 'てからでないと', unit: 6, zhSourceRowId: 'n3row-92',
    meaningJa: '〜した後でなければ（できない）',
    explanationZh: '不先…就（不能）…',
    formation: '動詞て形 ＋からでないと＋否定',
    usageScene: '说明前提条件：不确认就不能回答',
    nuance: '後半は必ず否定・不可能。手順の説明に便利',
    register: 'both',
    sourceExample: src('人間は失敗をしてからでないと、なかなか学ばないです。', 'f6c4e770e5b6a6af'),
    examplesJa: ['人間は失敗をしてからでないと、なかなか学ばないです。',
                 '上司に確認してからでないと、お返事できません。'],
    examplesZh: ['人不先经历失败，就很难学到东西。', '不先跟上司确认，就无法答复。'],
    furigana: 'にんげんは しっぱいを してから でないと、なかなか まなばないです。',
    commonMistakesZh: '後半は否定が必須。「確認してからでないと、できます」は不成立',
    learnerFocus: '仕事の保留「確認してからでないと〜できません」は角の立たない断り方',
    similarPatterns: ['〜ないと', '〜てはじめて'],
    contrast: '「てからでないと」＝前提＋不可；「てはじめて」＝経験して初めて分かる',
    recognition: { promptZh: '「許可をもらってからでないと」后面是？',
      options: ['使えません', '使えます', '使いましょう', '使いたい'],
      answerIndex: 0, distractorReason: '後半は否定・不可能が必須',
      explanationZh: '前提条件＋否定' },
    production: { promptJa: '仕事の保留を「〜てからでないと」で言ってください。',
      promptZh: '用「〜てからでないと」保留答复。',
      expected: ['てからでないと'], acceptable: ['確認してからでないと'] },
    practice: { themeJa: '丁寧に保留する', starterJa: 'すぐ返事できないとき、どう伝えますか？',
      starterZh: '不能立刻答复时你怎么说？', targetUse: '〜てからでないと' },
    vocabularyLinks: ['fi-kakunin', 'fi-soudan'] }),
  g({ grammarId: 'n2g-078', pattern: '〜てしょうがない', reading: 'てしょうがない', unit: 6, zhSourceRowId: null,
    meaningJa: '〜で耐えられないほどだ（口語）',
    explanationZh: '…得不得了、…得受不了（口语）',
    formation: '動詞て形／い形容詞くて／な形容詞で ＋しょうがない',
    usageScene: '困得不行、想家想得不行',
    nuance: '「しかたがない」の口語形。感情・感覚の自然な高まり',
    register: 'spoken',
    sourceExample: src('今日は眠たくてしょうがないです。', '6af0c7651cce7054'),
    examplesJa: ['今日は眠たくてしょうがないです。',
                 '故郷の料理が食べたくてしょうがありません。'],
    examplesZh: ['今天困得不行。', '想吃家乡菜想得不得了。'],
    furigana: 'きょうは ねむたくて しょうがないです。',
    commonMistakesZh: '意志的行動には不可。「勉強してしょうがない」は誤り。感情・感覚限定',
    learnerFocus: '「たまらない」「ならない」との3兄弟。口語では「しょうがない」が最頻',
    similarPatterns: ['〜てたまらない', '〜てならない'],
    contrast: '口語度: 「ならない」（書面）＜「たまらない」＜「しょうがない」（口語）',
    recognition: { promptZh: '「気になってしょうがない」是什么状态？',
      options: ['在意得不得了', '完全不在意', '有点在意', '不想在意'],
      answerIndex: 0, distractorReason: '「てしょうがない」表示程度极高',
      explanationZh: '感情の極み（口語）' },
    production: { promptJa: '今の強い気持ちを「〜てしょうがない」で言ってください。',
      promptZh: '用「〜てしょうがない」说你此刻的强烈感受。',
      expected: ['しょうがない'], acceptable: ['〜てしょうがないです'] },
    practice: { themeJa: '我慢できない気持ちを話す', starterJa: '最近「〜てしょうがない」ことは？',
      starterZh: '最近有什么「…得不行」的事？', targetUse: '〜てしょうがない' },
    vocabularyLinks: ['fi-kimochi', 'fi-taberu'] }),
  g({ grammarId: 'n2g-079', pattern: '〜てたまらない', reading: 'てたまらない', unit: 6, zhSourceRowId: null,
    meaningJa: '〜で我慢できない',
    explanationZh: '…得难以忍受、非常想…',
    formation: '動詞て形／い形容詞くて／な形容詞で ＋たまらない',
    usageScene: '想见得不得了、疼得受不了',
    nuance: '感情・欲求・身体感覚の限界。書面にも使える中間的文体',
    register: 'both',
    sourceExample: src('あの俳優に会いたくてたまらないです。', '8753ad9b9a52bc78'),
    examplesJa: ['あの俳優に会いたくてたまらないです。',
                 '歯が痛くてたまらないので、病院に行きます。'],
    examplesZh: ['想见那位演员想得不得了。', '牙疼得受不了，要去医院。'],
    furigana: 'あの はいゆうに あいたくて たまらないです。',
    commonMistakesZh: '「たまらない」単独でも「最高だ」の意（このラーメンはたまらない）。文脈で判別',
    learnerFocus: '「〜たくてたまらない」（非常想…）は願望の最上級。推し活の話で活躍',
    similarPatterns: ['〜てしょうがない', '〜てならない'],
    contrast: '「たまらない」＝我慢の限界；「しょうがない」＝口語の同義；「ならない」＝書面',
    recognition: { promptZh: '「会いたくてたまらない」的程度是？',
      options: ['非常想见（最高级）', '只是有那么一点点想见', '完全不想去和对方见面', '早就已经见过很多次了'],
      answerIndex: 0, distractorReason: '「てたまらない」表示欲求的极限',
      explanationZh: '願望の最上級' },
    production: { promptJa: '強い願望を「〜たくてたまらない」で言ってください。',
      promptZh: '用「〜たくてたまらない」说强烈的愿望。',
      expected: ['たまらない'], acceptable: ['〜たくてたまらない'] },
    practice: { themeJa: '今一番したいことを話す', starterJa: '今、何がしたくてたまらないですか？',
      starterZh: '现在你最想做什么（想得不得了）？', targetUse: '〜てたまらない' },
    vocabularyLinks: ['fi-au', 'fi-kyoumi'] }),
  g({ grammarId: 'n2g-080', pattern: '〜てでも', reading: 'てでも', unit: 6, zhSourceRowId: null,
    meaningJa: '（極端な手段を使って）でも〜したい',
    explanationZh: '哪怕…也要…。不惜极端手段',
    formation: '動詞て形 ＋でも',
    usageScene: '表达不惜代价的强烈决心',
    nuance: '「並んででも食べたい」「借金してでも」等、極端例＋強い意志',
    register: 'both',
    sourceExample: src('どんなにお金をかけてでも、いつか俳優に会いにイタリアに行きます。', '05ad8b06fc11de57'),
    examplesJa: ['どんなにお金をかけてでも、いつか俳優に会いにイタリアに行きます。',
                 '徹夜してでも、明日までに仕上げます。'],
    examplesZh: ['哪怕花再多钱，总有一天也要去意大利见那位演员。', '哪怕熬夜，也要在明天之前完成。'],
    furigana: 'どんなに おかねを かけてでも、いつか はいゆうに あいに イタリアに いきます。',
    commonMistakesZh: '後半は意志・願望。「徹夜してでも、眠いです」は不成立',
    learnerFocus: '決意の強さを一段上げる。「たとえ〜ても」より手段の極端さが際立つ',
    similarPatterns: ['たとえ〜ても', '〜だけでも'],
    contrast: '「てでも」＝極端な手段も辞さず；「ても」＝条件の譲歩',
    recognition: { promptZh: '「並んででも食べたい」的心情是？',
      options: ['哪怕排队也想吃（强烈）', '不想排队，所以决定不吃了', '讨厌这家店', '已经吃过了'],
      answerIndex: 0, distractorReason: '「てでも」表示不惜代价',
      explanationZh: '手段を選ばない意志' },
    production: { promptJa: '強い決意を「〜てでも」で言ってください。',
      promptZh: '用「〜てでも」表达不惜代价的决心。',
      expected: ['てでも'], acceptable: ['並んででも', '徹夜してでも'] },
    practice: { themeJa: 'そこまでしてもしたいことを話す', starterJa: '「〜してでも」やりたいことは？',
      starterZh: '有什么是「哪怕…也要做」的事？', targetUse: '〜てでも' },
    vocabularyLinks: ['fi-iku', 'fi-kimeru'] }),
  g({ grammarId: 'n2g-081', pattern: '〜てならない', reading: 'てならない', unit: 6, zhSourceRowId: null,
    meaningJa: '自然に〜という気持ちが湧いて抑えられない（書面）',
    explanationZh: '不由得…、…得不得了（书面）',
    formation: '動詞て形／い形容詞くて／な形容詞で ＋ならない',
    usageScene: '书面表达抑制不住的感觉（気がする・思える・残念）',
    nuance: '「気がしてならない」「思えてならない」等、自発的心情と相性がよい',
    register: 'written',
    sourceExample: src('先ほどの問題を間違えた気がしてならないです。', '369c86fdae3d9ecf'),
    examplesJa: ['先ほどの問題を間違えた気がしてならないです。',
                 '合格発表が気になってならなかった。'],
    examplesZh: ['总觉得刚才那道题做错了。', '当时对合格发表在意得不得了。'],
    furigana: 'さきほどの もんだいを まちがえた きが して ならないです。',
    commonMistakesZh: '三兄弟の中で最も書面的。会話では「しょうがない」が自然',
    learnerFocus: '「気がしてならない」は不安の丁寧な吐露。試験後の心境にぴったり',
    similarPatterns: ['〜てたまらない', '〜てしょうがない'],
    contrast: '「ならない」＝書面・自発心情；「たまらない」＝欲求・感覚；「しょうがない」＝口語',
    recognition: { promptZh: '「残念でならない」的文体是？',
      options: ['书面的强烈遗憾', '口语的随意', '命令', '疑问'],
      answerIndex: 0, distractorReason: '「てならない」是书面的感情强调',
      explanationZh: '書面の感情強調' },
    production: { promptJa: '不安な気持ちを「気がしてならない」で言ってください。',
      promptZh: '用「気がしてならない」表达不安。',
      expected: ['てならな'], acceptable: ['気がしてならない'] },
    practice: { themeJa: '試験後の心境を話す', starterJa: '試験の後、「間違えた気がしてならない」経験は？',
      starterZh: '考完试后有过「总觉得做错了」的经历吗？', targetUse: '〜てならない' },
    vocabularyLinks: ['fi-kanjiru', 'fi-mondai'] }),
  g({ grammarId: 'n2g-082', pattern: '〜てはいられない', reading: 'てはいられない', unit: 6, zhSourceRowId: null,
    meaningJa: 'のんびり〜している場合ではない',
    explanationZh: '不能一直…、没工夫…',
    formation: '動詞て形 ＋はいられない',
    usageScene: '考试前不能睡、不能再等了',
    nuance: '状況の切迫感。「こうしてはいられない」は行動開始の合図',
    register: 'both',
    sourceExample: src('明日テストなので、今日は寝てはいられないです。', '417092763f9fcb95'),
    examplesJa: ['明日テストなので、今日は寝てはいられないです。',
                 '締め切りが近いので、休んではいられません。'],
    examplesZh: ['明天考试，今天可不能睡大觉。', '截止日期临近，没工夫休息。'],
    furigana: 'あした テストなので、きょうは ねては いられないです。',
    commonMistakesZh: '「〜ずにはいられない」（禁不住做）と方向が逆。「てはいられない」=不能继续做',
    learnerFocus: '切迫感の表明。「のんびりしてはいられない」で自分を奮い立たせる',
    similarPatterns: ['〜ずにはいられない', '〜場合ではない'],
    contrast: '「てはいられない」＝継続不可（やめて動く）；「ずにはいられない」＝抑制不可（してしまう）',
    recognition: { promptZh: '「笑ってはいられない」是什么意思？',
      options: ['不是笑的时候（事态严重）', '有趣得忍不住笑了', '一直笑个不停没停', '心里很想笑出来'],
      answerIndex: 0, distractorReason: '「てはいられない」表示不能继续该状态',
      explanationZh: '状況の切迫' },
    production: { promptJa: '切迫した状況を「〜てはいられない」で言ってください。',
      promptZh: '用「〜てはいられない」表达紧迫感。',
      expected: ['てはいられ'], acceptable: ['寝てはいられない', '休んではいられない'] },
    practice: { themeJa: '気持ちを切り替えた瞬間を話す', starterJa: '「のんびりしてはいられない」と思った経験は？',
      starterZh: '有过「不能再悠哉了」的时刻吗？', targetUse: '〜てはいられない' },
    vocabularyLinks: ['fi-neru', 'fi-isogashii'] }),
  g({ grammarId: 'n2g-083', pattern: '〜てばかりはいられない', reading: 'てばかりはいられない', unit: 6, zhSourceRowId: null,
    meaningJa: 'いつまでも〜し続けるわけにはいかない',
    explanationZh: '不能总是…、不能一味…',
    formation: '動詞て形 ＋ばかりはいられない',
    usageScene: '不能总靠别人、不能一直伤心下去',
    nuance: '「てはいられない」＋「ばかり」で反復・依存の打ち切り',
    register: 'both',
    sourceExample: src('試験中は一人で解くので、先生に頼ってばかりはいられないです。', '616179569c34e0f2'),
    examplesJa: ['試験中は一人で解くので、先生に頼ってばかりはいられないです。',
                 '落ち込んでばかりはいられないので、次の準備を始めます。'],
    examplesZh: ['考试时要一个人做题，不能总依赖老师。', '不能一味消沉，我要开始准备下一步。'],
    furigana: 'しけんちゅうは ひとりで とくので、せんせいに たよって ばかりは いられないです。',
    commonMistakesZh: '「ばかり」が入ると「一味依存・反復」の打ち切りに限定される',
    learnerFocus: '自立の決意表明。「頼ってばかりはいられない」は成長物語の定番句',
    similarPatterns: ['〜てはいられない', '〜わけにはいかない'],
    contrast: '「てばかりはいられない」＝依存・反復の打ち切り；「てはいられない」＝状態の打ち切り',
    recognition: { promptZh: '「泣いてばかりはいられない」的心情是？',
      options: ['不能一直哭，要振作', '想要就这样一直哭下去', '根本就一次也没有哭过', '故意惹得别人哭了起来'],
      answerIndex: 0, distractorReason: '「ばかりはいられない」表示要结束反复状态',
      explanationZh: '前を向く決意' },
    production: { promptJa: '自立の決意を「〜てばかりはいられない」で言ってください。',
      promptZh: '用「〜てばかりはいられない」表达自立的决心。',
      expected: ['ばかりはいられ'], acceptable: ['頼ってばかりはいられない'] },
    practice: { themeJa: '自立を決めた瞬間を話す', starterJa: '「〜てばかりはいられない」と思ったのはいつ？',
      starterZh: '什么时候觉得「不能总是…」？', targetUse: '〜てばかりはいられない' },
    vocabularyLinks: ['fi-ganbaru', 'fi-kimeru'] }),
  g({ grammarId: 'n2g-084', pattern: '〜てはじめて', reading: 'てはじめて', unit: 6, zhSourceRowId: null,
    meaningJa: '〜して、そのとき初めて（分かった）',
    explanationZh: '直到…才（第一次明白/体会到）',
    formation: '動詞て形 ＋はじめて',
    usageScene: '失去后才懂得珍惜、生病后才知健康可贵',
    nuance: '経験→気づきの構文。人生訓と相性抜群',
    register: 'both',
    sourceExample: src('病気になってはじめて家族の大切さが分かりました。', '0131ddb1f8f3325d'),
    examplesJa: ['病気になってはじめて家族の大切さが分かりました。',
                 '一人暮らしをしてはじめて、親のありがたさに気づきました。'],
    examplesZh: ['生了病才第一次明白家人的重要。', '一个人生活后，才体会到父母的恩情。'],
    furigana: 'びょうきに なって はじめて かぞくの たいせつさが わかりました。',
    commonMistakesZh: '後半は「分かった・気づいた」等の認識動詞が定番。行動文は不自然',
    learnerFocus: '人生の学びを語る黄金構文。スピーチの核になる',
    similarPatterns: ['〜てからでないと', '〜てこそ'],
    contrast: '「てはじめて」＝経験後の気づき；「てからでないと」＝前提条件',
    recognition: { promptZh: '「失ってはじめて分かる」是什么意思？',
      options: ['失去后才明白', '失去前就明白', '不想明白', 'never明白'],
      answerIndex: 0, distractorReason: '「てはじめて」表示经历后才认识到',
      explanationZh: '経験→気づき' },
    production: { promptJa: '経験して気づいたことを「〜てはじめて」で言ってください。',
      promptZh: '用「〜てはじめて」说一个经历后才明白的道理。',
      expected: ['はじめて'], acceptable: ['〜てはじめて分かった'] },
    practice: { themeJa: '経験から得た学びを話す', starterJa: '日本に来てはじめて分かったことは？',
      starterZh: '来日本后才第一次明白的事是什么？', targetUse: '〜てはじめて' },
    vocabularyLinks: ['fi-wakaru', 'fi-kazoku'] }),
  g({ grammarId: 'n2g-085', pattern: '〜ということだ', reading: 'ということだ', unit: 6, zhSourceRowId: null,
    meaningJa: '①つまり〜という意味だ ②〜だそうだ（伝聞）',
    explanationZh: '①也就是说… ②据说…（传闻）',
    formation: '文 ＋ということだ',
    usageScene: '①总结含义 ②转述新闻・通知',
    nuance: '①は結論の言い換え。②はニュース調の伝聞',
    register: 'written',
    sourceExample: src('試験まで残り３日。残りわずかということです。', '48e786687a5aa2f8'),
    examplesJa: ['試験まで残り3日。残りわずかということです。',
                 '来月から料金が変わるということです。'],
    examplesZh: ['离考试还剩3天。也就是说所剩无几了。', '据说下个月起费用要变。'],
    furigana: 'しけんまで のこり みっか。のこり わずかと いうことです。',
    commonMistakesZh: '①要約と②伝聞は文脈で判別。「つまり」があれば①、出典があれば②',
    learnerFocus: '会議の確認「〜ということですね？」は認識合わせの必須表現',
    similarPatterns: ['〜そうだ（伝聞）', 'つまり'],
    contrast: '「ということだ」＝要約/硬い伝聞；「そうだ」＝軽い伝聞',
    recognition: { promptZh: '「中止ということです」（通知）是？',
      options: ['据通知，中止了', '我自己决定要中止', '也许中止', '不中止'],
      answerIndex: 0, distractorReason: '通知の伝聞用法',
      explanationZh: '伝聞の「ということだ」' },
    production: { promptJa: '相手の話を「つまり〜ということですね」で確認してください。',
      promptZh: '用「つまり〜ということですね」确认对方的意思。',
      expected: ['ということ'], acceptable: ['〜ということですね'] },
    practice: { themeJa: '会議で認識を確認する', starterJa: '相手の長い説明を一文でまとめてみましょう',
      starterZh: '试着把对方的长说明总结成一句话', targetUse: 'つまり〜ということですね' },
    vocabularyLinks: ['fi-setsumei', 'fi-kakunin'] }),
  g({ grammarId: 'n2g-086', pattern: '〜というものではない', reading: 'というものではない', unit: 6, zhSourceRowId: null,
    meaningJa: '〜とは一概に言えない',
    explanationZh: '并不是说…（就行）。否定普遍论断',
    formation: '文（普通形） ＋というものではない',
    usageScene: '反驳「只要…就行」的想法',
    nuance: '一般論への婉曲な反論。「わけではない」より論説調',
    register: 'written',
    sourceExample: src('ひたすら文法の勉強をすればよいというものではないです。', 'de7d90b413523ac9'),
    examplesJa: ['ひたすら文法の勉強をすればよいというものではないです。',
                 '高ければ品質がいいというものではありません。'],
    examplesZh: ['并不是说一味学语法就行。', '并不是贵就等于质量好。'],
    furigana: 'ひたすら ぶんぽうの べんきょうを すれば よいと いうものでは ないです。',
    commonMistakesZh: '「〜ばいいというものではない」の形が最頻。反語的に持論へつなげる',
    learnerFocus: '学習法談義で「暗記すればいいというものではない」は説得力のある一言',
    similarPatterns: ['〜わけではない', '〜とは限らない'],
    contrast: '「というものではない」＝一般論の否定（論説）；「わけではない」＝部分否定',
    recognition: { promptZh: '「速ければいいというものではない」的主张是？',
      options: ['不是快就好（还有别的重要因素）', '不管怎样越快就越好', '做得越慢反而就越好', '速度完全无所谓'],
      answerIndex: 0, distractorReason: '普遍論の否定',
      explanationZh: '一概に言えない' },
    production: { promptJa: '「〜ばいいというものではない」で持論を言ってください。',
      promptZh: '用「〜ばいいというものではない」发表你的见解。',
      expected: ['というものでは'], acceptable: ['〜というものではない'] },
    practice: { themeJa: '学習法の持論を語る', starterJa: '「〜すればいいというものではない」と思うことは？',
      starterZh: '你觉得什么事「并不是…就行」？', targetUse: '〜というものではない' },
    vocabularyLinks: ['fi-benkyo', 'fi-iken'] }),
  g({ grammarId: 'n2g-087', pattern: '〜というより', reading: 'というより', unit: 6, zhSourceRowId: null,
    meaningJa: '〜と言うより、むしろ',
    explanationZh: '与其说是…不如说是…',
    formation: '文（普通形）／名詞 ＋というより',
    usageScene: '修正表达：与其说讨厌不如说不习惯',
    nuance: '前の表現を退けて、より適切な言い方へ。後半に「むしろ」が呼応しやすい',
    register: 'both',
    sourceExample: src('日本の納豆が嫌いというより、食べ慣れていないものを食べるのが嫌です。', 'b5254799721d4d65'),
    examplesJa: ['日本の納豆が嫌いというより、食べ慣れていないものを食べるのが嫌です。',
                 '彼は先生というより、友達のような存在です。'],
    examplesZh: ['与其说讨厌纳豆，不如说是讨厌吃不习惯的东西。', '与其说他是老师，不如说像朋友。'],
    furigana: 'にほんの なっとうが きらいと いうより、たべなれて いないものを たべるのが いやです。',
    commonMistakesZh: '比較の「より」と混同しない。「というより」は言い方の修正',
    learnerFocus: '微妙なニュアンスを正確に伝える大人の言い直し。誤解を防ぐ',
    similarPatterns: ['〜より', 'むしろ'],
    contrast: '「というより」＝表現の修正；「より」＝対象の比較',
    recognition: { promptZh: '「怒っているというより悲しい」是什么意思？',
      options: ['与其说生气不如说难过', '又生气又高兴', '只是生气', '不难过'],
      answerIndex: 0, distractorReason: '前の表現を修正してより適切に',
      explanationZh: '表現の言い直し' },
    production: { promptJa: '誤解されそうな気持ちを「〜というより」で言い直してください。',
      promptZh: '用「〜というより」修正容易被误解的表达。',
      expected: ['というより'], acceptable: ['〜というより、むしろ'] },
    practice: { themeJa: '正確に言い直す', starterJa: '「嫌い」と誤解されがちだが実は違う、というものは？',
      starterZh: '有什么容易被误会成「讨厌」其实不是的？', targetUse: '〜というより' },
    vocabularyLinks: ['fi-suki', 'fi-kimochi'] }),
  g({ grammarId: 'n2g-088', pattern: '〜といっても', reading: 'といっても', unit: 6, zhSourceRowId: null,
    meaningJa: '〜とは言うものの（実際は程度が違う）',
    explanationZh: '虽说…（其实程度有限/情况不同）',
    formation: '文（普通形）／名詞 ＋といっても',
    usageScene: '纠正对方可能的过高想象',
    nuance: '謙遜・訂正の前置き。「料理ができるといっても、卵焼きだけです」',
    register: 'both',
    sourceExample: src('日本語学習といっても、知識をつける学習、会話力を上げる学習など色々あります。', '8758a9fce1bbd644'),
    examplesJa: ['日本語学習といっても、知識をつける学習、会話力を上げる学習など色々あります。',
                 '旅行に行ったといっても、隣の県に一泊しただけです。'],
    examplesZh: ['虽说是日语学习，也分积累知识的学习、提高会话的学习等很多种。', '虽说去旅行了，也只是在邻县住了一晚。'],
    furigana: 'にほんごがくしゅうと いっても、ちしきを つける がくしゅう、かいわりょくを あげる がくしゅうなど いろいろ あります。',
    commonMistakesZh: '谦虚表达的常用句式。为了不显得炫耀，用来把实际情况说得低一些',
    learnerFocus: '「日本語ができるといっても、日常会話だけです」は謙遜の即戦力',
    similarPatterns: ['〜とはいえ', '〜けれども'],
    contrast: '「といっても」＝程度の下方修正；「とはいえ」＝書面の逆接',
    recognition: { promptZh: '「泳げるといっても」后面最自然的是？',
      options: ['25メートルだけです', 'オリンピック選手です', '泳げません', '海が嫌いです'],
      answerIndex: 0, distractorReason: '実際の程度を控えめに訂正する',
      explanationZh: '謙遜の訂正' },
    production: { promptJa: '謙遜しながら実態を「〜といっても」で言ってください。',
      promptZh: '用「〜といっても」谦虚地说明实际情况。',
      expected: ['といっても'], acceptable: ['〜といっても〜だけです'] },
    practice: { themeJa: '謙遜して訂正する', starterJa: '「日本語ができる」と言われたら、どう返しますか？',
      starterZh: '被夸「日语很好」时你怎么谦虚地回应？', targetUse: '〜といっても' },
    vocabularyLinks: ['fi-benkyo', 'fi-hanasu'] }),
  g({ grammarId: 'n2g-089', pattern: '〜とおりに', reading: 'とおりに', unit: 6, zhSourceRowId: null,
    meaningJa: '〜と同じように',
    explanationZh: '按照…、正如…那样。与指示或预想完全一致',
    formation: '動詞辞書形／た形＋とおりに ／ 名詞＋の＋とおりに（どおりに）',
    usageScene: '按照菜谱、按照说明、正如预想',
    nuance: '名詞接続は「どおり」と濁る（予定どおり・計画どおり）',
    register: 'both',
    sourceExample: src('レシピに書いてあるとおりに作れば、誰でもスイーツを作れます。', '0913d5a0ac28a855'),
    examplesJa: ['レシピに書いてあるとおりに作れば、誰でもスイーツを作れます。',
                 '説明書のとおりに設定したのに、動きません。'],
    examplesZh: ['按照菜谱做的话，谁都能做出甜点。', '明明按说明书设置了，却不能用。'],
    furigana: 'レシピに かいてある とおりに つくれば、だれでも スイーツを つくれます。',
    commonMistakesZh: '名詞接続の濁音化（予定どおり）を忘れやすい。「予定とおり」は誤り',
    learnerFocus: '「思ったとおり」「言われたとおり」は日常・仕事の両方で高頻度',
    similarPatterns: ['〜ように', '〜に従って'],
    contrast: '「とおりに」＝完全一致；「ように」＝近似・目標',
    recognition: { promptZh: '「予定どおり」的读法为什么是「どおり」？',
      options: ['名詞接続で濁音化する', '是一种错误的写法', '是某地的方言说法', '是过时的古语说法'],
      answerIndex: 0, distractorReason: '名詞＋とおり→どおりと濁る',
      explanationZh: '連濁のルール' },
    production: { promptJa: '手順に従ったことを「〜とおりに」で言ってください。',
      promptZh: '用「〜とおりに」说按照步骤做的事。',
      expected: ['とおり'], acceptable: ['〜どおりに', '書いてあるとおりに'] },
    practice: { themeJa: '手順どおりの経験を話す', starterJa: 'レシピどおりに作って成功（失敗）したことは？',
      starterZh: '有按菜谱做成功（失败）的经历吗？', targetUse: '〜とおりに' },
    vocabularyLinks: ['fi-tsukuru', 'fi-setsumei'] }),
  g({ grammarId: 'n2g-090', pattern: '〜とか', reading: 'とか', unit: 6, zhSourceRowId: null,
    meaningJa: '〜と聞いた（曖昧な伝聞・口語）',
    explanationZh: '听说…（来着）。口语的模糊传闻',
    formation: '文（普通形） ＋とか',
    usageScene: '转述不太确定的消息',
    nuance: '文末の「とか」は責任を持たない軽い伝聞。若者・口語',
    register: 'spoken',
    sourceExample: src('今日は地震の影響で終日電車が動かないとか。', 'e6bf26de9bf5124c'),
    examplesJa: ['今日は地震の影響で終日電車が動かないとか。',
                 '田中さん、来月結婚するとか。'],
    examplesZh: ['听说今天受地震影响电车全天停运来着。', '听说田中先生下个月结婚来着。'],
    furigana: 'きょうは じしんの えいきょうで しゅうじつ でんしゃが うごかないとか。',
    commonMistakesZh: '列挙の「とか」（AとかBとか）と文末伝聞の「とか」は別用法',
    learnerFocus: '噂話の聞き取りで頻出。自分が言うと無責任に響くので注意',
    similarPatterns: ['〜そうだ', '〜らしい'],
    contrast: '「とか」＝最も曖昧な伝聞（口語）；「らしい」＝根拠ある伝聞；「そうだ」＝中立伝聞',
    recognition: { promptZh: '文末的「〜とか」表示？',
      options: ['不太确定的传闻', '强烈的断定', '命令', '愿望'],
      answerIndex: 0, distractorReason: '文末とか＝曖昧な伝聞',
      explanationZh: '軽い伝聞' },
    production: { promptJa: '曖昧に聞いた話を「〜とか」で伝えてください。',
      promptZh: '用「〜とか」转述不太确定的消息。',
      expected: ['とか'], acceptable: ['〜とか聞きました'] },
    practice: { themeJa: '噂話を軽く伝える', starterJa: '最近聞いた「〜とか」という話は？',
      starterZh: '最近听说了什么「据说…来着」的事？', targetUse: '〜とか' },
    vocabularyLinks: ['fi-kiku', 'fi-densha'] }),
];
