// Phase 3P-5: N2文法完成draft Unit 2（原本No.16〜30・15文型）。
// rightsStatus: teacher_created_confirmed（CEO確認済み）のため、原本例文をruntimeで使用できる。
// 原本例文と新規例文を比較し、学習効果の高い方を examplesJa[0] に置く。
import type { N2GrammarDraft } from './n2GrammarDrafts';

const g = (p: Omit<N2GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey' | 'runtimeExampleOrigin'> & { reviewKey?: string; runtimeExampleOrigin?: N2GrammarDraft['runtimeExampleOrigin'] }): N2GrammarDraft =>
  ({ level: 'N2', route: 'n2-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, runtimeExampleOrigin: 'source_confirmed', ...p });

const src = (text: string, hash: string) =>
  ({ text, hash, rightsStatus: 'teacher_created_confirmed' as const });

export const N2_GRAMMAR_DRAFTS_UNIT2: N2GrammarDraft[] = [
  g({ grammarId: 'n2g-016', pattern: '〜がきっかけで', reading: 'がきっかけで', unit: 2, zhSourceRowId: null,
    meaningJa: '〜が始まりとなって（変化が起きた）',
    explanationZh: '以…为契机、由…开始。某件事成为后来变化的起点',
    formation: '名詞 ＋がきっかけで／がきっかけになって',
    usageScene: '说明自己开始学日语、换工作、认识某人的起因',
    nuance: '起点は小さな出来事でよい。良い変化にも悪い変化にも使えるが、良い変化が多い',
    register: 'both',
    sourceExample: src('「小红书」がきっかけで、オンラインの日本語会話授業があることを知りました。', '78ac6a4bc6d4e2c0'),
    examplesJa: ['「小红书」がきっかけで、オンラインの日本語会話授業があることを知りました。',
                 '同僚の一言がきっかけで、日本語の勉強を再開しました。'],
    examplesZh: ['以小红书为契机，我知道了有在线日语会话课。', '同事的一句话成了契机，我重新开始学日语。'],
    furigana: '「シャオホンシュー」が きっかけで、オンラインの にほんごかいわじゅぎょうが あることを しりました。',
    commonMistakesZh: '「〜をきっかけに」（以…为契机，更书面）と形が違うだけでほぼ同義。「が」と「を」で助詞が変わる',
    learnerFocus: '自我介绍时说明「为什么开始学日语」的最自然表达。面试・交流会で使える',
    similarPatterns: ['〜をきっかけに', '〜が契機で'],
    contrast: '「がきっかけで」＝会话寄り；「をきっかけに」＝书面寄り；「が契機で」＝最も硬い',
    recognition: { promptZh: '「留学がきっかけで日本語を始めました」是什么意思？',
      options: ['留学成了开始学日语的契机', '留学的时候日语已经很好', '不打算留学', '留学结束了'],
      answerIndex: 0, distractorReason: '「がきっかけで」表示后项变化的起点',
      explanationZh: '「〜がきっかけで」= 以…为契机' },
    production: { promptJa: '日本語を始めたきっかけを「〜がきっかけで」で言ってください。',
      promptZh: '用「〜がきっかけで」说说你开始学日语的契机。',
      expected: ['がきっかけ'], acceptable: ['〜がきっかけで', '〜がきっかけになって'] },
    practice: { themeJa: '日本語を始めたきっかけを話す',
      starterJa: '日本語を勉強し始めたきっかけは何ですか？', starterZh: '你开始学日语的契机是什么？',
      targetUse: '〜がきっかけで' },
    vocabularyLinks: ['fi-benkyo', 'fi-hajimeru'] }),
  g({ grammarId: 'n2g-017', pattern: '〜限りは／〜ない限り', reading: 'かぎりは／ないかぎり', unit: 2, zhSourceRowId: null,
    meaningJa: 'その状態が続く間は／〜しなければ（結果は変わらない）',
    explanationZh: '只要…就（不会变）／除非…否则…。表示条件不变则结果不变',
    formation: '動詞辞書形／ない形／名詞＋である ＋限り（は）',
    matchKeys: ['限り'],
    usageScene: '说明「不改变做法就不会有结果」的因果、条件的界限',
    nuance: '「ない限り」の形が特に頻出。強い条件を表す',
    register: 'written',
    sourceExample: src('教科書だけで勉強する限りは、会話力はなかなか上がらないと思います。', 'ee1ed44488b18952'),
    examplesJa: ['教科書だけで勉強する限りは、会話力はなかなか上がりません。',
                 '本人が希望しない限り、異動はありません。'],
    examplesZh: ['只靠课本学习的话，会话能力很难提高。', '除非本人希望，否则不会调动。'],
    furigana: 'きょうかしょだけで べんきょうする かぎりは、かいわりょくは なかなか あがりません。',
    commonMistakesZh: '「ない限り」の後ろは否定的・限定的な結果が来る。「ない限り、うまくいきます」は不自然',
    learnerFocus: '中文「只要…就」是肯定条件、「除非」是否定条件。日语は「限り」「ない限り」で対応が変わる',
    similarPatterns: ['〜ないと', '〜なければ'],
    contrast: '「限り」＝条件が続く間ずっと（書面）；「なければ」＝単純条件（口語）',
    recognition: { promptZh: '「連絡がない限り、予定通りです」是什么意思？',
      options: ['除非有联系，否则按原计划', '不管怎样一定会有联系', '计划已经被取消掉了', '之前已经联系过了'],
      answerIndex: 0, distractorReason: '「ない限り」表示除非该条件成立，否则维持现状',
      explanationZh: '「〜ない限り」= 除非…否则…' },
    production: { promptJa: '条件が変わらなければ結果も変わらないことを「〜限り」で言ってください。',
      promptZh: '用「〜限り」表达条件不变结果就不变。',
      expected: ['限り'], acceptable: ['〜限りは', '〜ない限り'] },
    practice: { themeJa: '上達しない原因を分析する',
      starterJa: '何を変えない限り、日本語は上達しないと思いますか？', starterZh: '你觉得不改变什么，日语就无法进步？',
      targetUse: '〜ない限り' },
    vocabularyLinks: ['fi-benkyo', 'fi-hanasu'] }),
  g({ grammarId: 'n2g-019', pattern: '〜かけ', reading: 'かけ', unit: 2, zhSourceRowId: null,
    meaningJa: '途中まで〜した／〜しそうになっている',
    explanationZh: '…到一半、快要…了。动作进行到中途或即将发生',
    formation: '動詞ます形 ＋かけ／かける／かけた',
    usageScene: '说明吃到一半的食物、写到一半的报告、快坏掉的东西',
    nuance: '「〜かけの」で名詞修飾も多い（読みかけの本）',
    register: 'both',
    sourceExample: src('ずっと冷蔵庫に入れていた牛乳が腐りかけていました。', '19ed1f1b79b42615'),
    examplesJa: ['ずっと冷蔵庫に入れていた牛乳が腐りかけていました。',
                 '読みかけの本が、机の上に三冊あります。'],
    examplesZh: ['一直放在冰箱里的牛奶快坏了。', '桌上有三本读到一半的书。'],
    furigana: 'ずっと れいぞうこに いれていた ぎゅうにゅうが くさりかけて いました。',
    commonMistakesZh: '「〜かけ」是「中途」，不是「开始」。「食べかけ」是吃到一半，不是刚开始吃',
    learnerFocus: '生活中「食べかけ」「読みかけ」「やりかけ」很常用。中文没有对应的一个词',
    similarPatterns: ['〜途中', '〜始める'],
    contrast: '「かけ」＝中途で止まっている；「始める」＝開始した；「途中」＝名詞',
    recognition: { promptZh: '「書きかけのメール」是什么状态？',
      options: ['写到一半的邮件', '写完的邮件', '还没开始写', '删掉的邮件'],
      answerIndex: 0, distractorReason: '「〜かけ」表示动作进行到中途',
      explanationZh: '「〜かけ」= 做到一半' },
    production: { promptJa: '途中で止まっているものを「〜かけ」で言ってください。',
      promptZh: '用「〜かけ」说一件做到一半的事。',
      expected: ['かけ'], acceptable: ['〜かけの', '〜かけています'] },
    practice: { themeJa: 'やりかけのことを話す',
      starterJa: '今、やりかけになっていることはありますか？', starterZh: '现在有做到一半的事吗？',
      targetUse: '〜かけ' },
    vocabularyLinks: ['fi-yomu', 'fi-owaru'] }),
  g({ grammarId: 'n2g-020', pattern: '〜がたい', reading: 'がたい', unit: 2, zhSourceRowId: null,
    meaningJa: '〜するのが難しい（気持ちの上で）',
    explanationZh: '难以…（心理上难，不是能力上难）',
    formation: '動詞ます形 ＋がたい',
    usageScene: '说明难忘的经历、难以相信的消息、难以理解的行为',
    nuance: '書面語。「忘れがたい」「信じがたい」「理解しがたい」が定番',
    register: 'written',
    sourceExample: src('大好きな俳優に街で出会えたことは、本当に忘れがたいことです。', '797cc882119d0d8c'),
    examplesJa: ['大好きな俳優に街で出会えたことは、本当に忘れがたいことです。',
                 'この結果は、正直、信じがたいものでした。'],
    examplesZh: ['在街上遇到最喜欢的演员，真是难以忘怀。', '这个结果，说实话难以置信。'],
    furigana: 'だいすきな はいゆうに まちで であえた ことは、ほんとうに わすれがたい ことです。',
    commonMistakesZh: '「にくい」は物理的・技術的に難しい、「がたい」は心理的に難しい。「書きがたい」は不自然',
    learnerFocus: '「忘れられない」（口語）と「忘れがたい」（書面）の使い分け。作文・スピーチで効く',
    similarPatterns: ['〜にくい', '〜られない'],
    contrast: '「がたい」＝心理的な困難（書面）；「にくい」＝物理的・技術的な困難',
    recognition: { promptZh: '哪个搭配自然？',
      options: ['忘れがたい思い出', '書きがたいペン', '歩きがたい道', '見がたいテレビ'],
      answerIndex: 0, distractorReason: '「がたい」用于心理上难以做到的事，物理困难用「にくい」',
      explanationZh: '心理的な困難 →「がたい」' },
    production: { promptJa: '忘れられない経験を「〜がたい」で言ってください。',
      promptZh: '用「〜がたい」说一次难忘的经历。',
      expected: ['がたい'], acceptable: ['忘れがたい', '信じがたい'] },
    practice: { themeJa: '忘れられない経験を語る',
      starterJa: '日本での忘れがたい経験を教えてください。', starterZh: '说说你在日本难忘的经历。',
      targetUse: '〜がたい' },
    vocabularyLinks: ['fi-wasureru', 'fi-keiken'] }),
  g({ grammarId: 'n2g-021', pattern: '〜がちだ', reading: 'がちだ', unit: 2, zhSourceRowId: 'n3row-9',
    meaningJa: 'そうなる傾向が強い（多くは良くないこと）',
    explanationZh: '容易…、往往…（多用于不好的倾向）',
    formation: '動詞ます形／名詞 ＋がちだ',
    usageScene: '说明自己的坏习惯、身体容易出的状况',
    nuance: '几乎只用于消极内容。N3でも学ぶが、N2では「〜がちな傾向」など書面用法も出る',
    register: 'both',
    sourceExample: src('いつもいろんなことが中途半端（ちゅうとはんぱ）になりがちです。', '5cd03e6b12657bc3'),
    examplesJa: ['いつもいろんなことが中途半端になりがちです。',
                 '一人暮らしだと、食事が偏りがちになります。'],
    examplesZh: ['很多事总是容易半途而废。', '一个人住的话，饮食容易不均衡。'],
    furigana: 'いつも いろんなことが ちゅうとはんぱに なりがちです。',
    commonMistakesZh: '不能用于好事。「上手になりがち」は誤り。正面は「〜やすい」',
    learnerFocus: '中文「容易」褒贬皆可，日语「がち」几乎专用于负面。这是选词准确度的分水岭',
    similarPatterns: ['〜やすい', '〜ぎみ'],
    contrast: '「やすい」＝中性；「がち」＝负面の頻度傾向；「ぎみ」＝軽い状態の傾向',
    recognition: { promptZh: '哪个句子用「がち」不自然？',
      options: ['最近、成績が上がりがちだ', '疲れると忘れがちだ', '雨の日は遅刻しがちだ', '冬は風邪をひきがちだ'],
      answerIndex: 0, distractorReason: '成绩上升是好事，「がち」不用于正面内容',
      explanationZh: '正面内容用「〜やすい」' },
    production: { promptJa: '自分の良くない傾向を「〜がちだ」で言ってください。',
      promptZh: '用「〜がちだ」说说你不好的倾向。',
      expected: ['がち'], acceptable: ['〜がちです', '〜がちになります'] },
    practice: { themeJa: '直したい傾向を話す',
      starterJa: '忙しいと、つい何をしがちですか？', starterZh: '忙的时候你往往会怎样？',
      targetUse: '〜がちです' },
    vocabularyLinks: ['fi-isogashii', 'fi-shuukan'] }),
  g({ grammarId: 'n2g-022', pattern: '〜かというと', reading: 'かというと', unit: 2, zhSourceRowId: null,
    meaningJa: '（どちらかを選ぶなら）〜のほうだ',
    explanationZh: '要说…的话、硬要说的话。委婉地表明倾向',
    formation: 'どちらか／なぜ／何 ＋かというと',
    usageScene: '婉转说明自己的偏好或理由，避免断言',
    nuance: '「どちらかというと」の形が最頻出。断定を避ける日本的な言い回し',
    register: 'both',
    sourceExample: src('どちらかというと、勉強は好きではありません。', 'f08b7b05fe76b4fe'),
    examplesJa: ['どちらかというと、勉強は好きではありません。',
                 'なぜ日本を選んだかというと、食文化に興味があったからです。'],
    examplesZh: ['硬要说的话，我不太喜欢学习。', '要说为什么选日本，是因为对饮食文化有兴趣。'],
    furigana: 'どちらかと いうと、べんきょうは すきでは ありません。',
    commonMistakesZh: '「どちらかというと」是缓和语气的定型。中文直译「哪一个的话」会不自然',
    learnerFocus: '日本人不喜欢强断言。「どちらかというと」を使うと角が立たない。面接・雑談で有用',
    similarPatterns: ['〜と言えば', '〜のほうが'],
    contrast: '「どちらかというと」＝婉曲な傾向表明；「〜のほうが」＝はっきりした比較',
    recognition: { promptZh: '「どちらかというと苦手です」的语气是？',
      options: ['委婉地说不太擅长', '直说自己完全不会', '自信地说非常擅长', '表示非常喜欢做'],
      answerIndex: 0, distractorReason: '「どちらかというと」是缓和断言的表达',
      explanationZh: '婉转表达倾向' },
    production: { promptJa: '好みを「どちらかというと」で婉曲に言ってください。',
      promptZh: '用「どちらかというと」委婉说明你的偏好。',
      expected: ['かというと'], acceptable: ['どちらかというと'] },
    practice: { themeJa: '好みを角が立たないように話す',
      starterJa: 'インドア派とアウトドア派、どちらかというとどちらですか？',
      starterZh: '室内派还是户外派，硬要说你偏哪个？', targetUse: 'どちらかというと' },
    vocabularyLinks: ['fi-suki', 'fi-iken'] }),
  g({ grammarId: 'n2g-023', pattern: '〜かと思うと', reading: 'かとおもうと', unit: 2, zhSourceRowId: null,
    meaningJa: '〜したと思ったら、すぐに（意外な次のことが起きる）',
    explanationZh: '刚以为…就…、刚…马上就…。表示紧接着发生了意外的事',
    formation: '動詞た形 ＋かと思うと／かと思えば',
    usageScene: '描述天气、孩子、宠物的急な変化',
    nuance: '後半は話し手にとって意外なこと。自分の行動には使いにくい',
    register: 'written',
    sourceExample: src('飼っている犬がもう寝たかと思うと、急に吠（ほ）え出しました。', '8b6444ef294e3c4d'),
    examplesJa: ['飼っている犬がもう寝たかと思うと、急に吠え出しました。',
                 '雨がやんだかと思うと、また降り出しました。'],
    examplesZh: ['刚以为养的狗睡了，突然又叫了起来。', '刚以为雨停了，又下了起来。'],
    furigana: 'かっている いぬが もう ねたかと おもうと、きゅうに ほえだしました。',
    commonMistakesZh: '主语是第三者或自然现象。「私は寝たかと思うと起きた」は不自然',
    learnerFocus: '「〜たとたん」（刚一…就）と近いが、「かと思うと」は話し手の意外感が強い',
    similarPatterns: ['〜たとたん', '〜やいなや'],
    contrast: '「たとたん」＝時間的な直後；「かと思うと」＝意外感を伴う直後',
    recognition: { promptZh: '「かと思うと」的后半句特点是？',
      options: ['出乎说话人意料的事', '预料之中的事', '自己的计划', '很久以后的事'],
      answerIndex: 0, distractorReason: '「かと思うと」强调紧接着发生了意外的事',
      explanationZh: '意外な直後の出来事' },
    production: { promptJa: '急な変化を「〜かと思うと」で言ってください。',
      promptZh: '用「〜かと思うと」描述突然的变化。',
      expected: ['かと思う'], acceptable: ['〜かと思うと', '〜かと思えば'] },
    practice: { themeJa: '天気や子どもの急な変化を話す',
      starterJa: '最近、急に変わったことはありますか？天気でも人でも構いません',
      starterZh: '最近有什么突然变化的事？天气或人都可以', targetUse: '〜かと思うと' },
    vocabularyLinks: ['fi-kawaru', 'fi-neru'] }),
  g({ grammarId: 'n2g-025', pattern: '〜か〜ないかのうちに', reading: 'か〜ないかのうちに', unit: 2, zhSourceRowId: null,
    meaningJa: '〜するかしないかの、ほとんど同時に',
    explanationZh: '刚要…还没…的时候就…。表示几乎同时发生',
    formation: '動詞辞書形＋か＋同じ動詞のない形＋かのうちに',
    matchKeys: ['かのうちに'],
    usageScene: '描述惊险的瞬间：刚上车门就关了、刚坐下就被叫走',
    nuance: '「〜たとたん」より、さらに時間差がない印象',
    register: 'written',
    sourceExample: src('電車に乗るか乗らないかのうちに、ドアが閉まってしまいました。', '81c28c5cc2bf8c74'),
    examplesJa: ['電車に乗るか乗らないかのうちに、ドアが閉まってしまいました。',
                 '座るか座らないかのうちに、名前を呼ばれました。'],
    examplesZh: ['刚上电车还没站稳，门就关了。', '刚要坐下还没坐下，就被叫了名字。'],
    furigana: 'でんしゃに のるか のらないかの うちに、ドアが しまって しまいました。',
    commonMistakesZh: '同じ動詞を「辞書形＋か＋ない形＋か」で繰り返す。動詞が違うと成立しない',
    learnerFocus: '同一动词重复两次是这个句型的形式特征。中文没有对应结构，需要整体记忆',
    similarPatterns: ['〜たとたん', '〜やいなや'],
    contrast: '時間差の短さ: 「か〜ないかのうちに」＜「やいなや」＜「たとたん」',
    recognition: { promptZh: '「乗るか乗らないかのうちに」是什么时候？',
      options: ['刚上车还没上稳的瞬间', '上车很久以后', '还没到车站', '下车以后'],
      answerIndex: 0, distractorReason: '这个句型表示几乎同时的瞬间',
      explanationZh: '几乎没有时间差的瞬间' },
    production: { promptJa: 'ぎりぎりだった瞬間を「〜か〜ないかのうちに」で言ってください。',
      promptZh: '用「〜か〜ないかのうちに」描述惊险的瞬间。',
      expected: ['かのうちに'], acceptable: ['〜か〜ないかのうちに'] },
    practice: { themeJa: 'ぎりぎりだった経験を話す',
      starterJa: '間に合うか間に合わないか、ぎりぎりだった経験はありますか？',
      starterZh: '有过差点来不及的惊险经历吗？', targetUse: '〜か〜ないかのうちに' },
    vocabularyLinks: ['fi-noru', 'fi-densha'] }),
  g({ grammarId: 'n2g-026', pattern: '〜か何か', reading: 'かなにか', unit: 2, zhSourceRowId: null,
    meaningJa: '〜など（はっきり決めていない例）',
    explanationZh: '…之类的、…什么的。举个例子但不确定',
    formation: '名詞 ＋か何か',
    usageScene: '还没决定送什么礼物、买什么东西时的说法',
    nuance: '会话で頻出。決めきっていない柔らかさが出る',
    register: 'spoken',
    sourceExample: src('旦那の誕生日には、ネクタイか何かをプレゼントしようと思います。', 'b7ee2508d37d84d2'),
    examplesJa: ['旦那の誕生日には、ネクタイか何かをプレゼントしようと思います。',
                 'お茶か何か、飲みますか。'],
    examplesZh: ['老公生日想送领带之类的。', '喝点茶什么的吗？'],
    furigana: 'だんなの たんじょうびには、ネクタイか なにかを プレゼントしようと おもいます。',
    commonMistakesZh: '「〜など」より口语、より漠然。書面では「〜など」が自然',
    learnerFocus: '接待客人时「お茶か何か飲みますか」は非常に自然。丸暗記して使える',
    similarPatterns: ['〜など', '〜とか'],
    contrast: '「か何か」＝会话・漠然；「など」＝书面；「とか」＝会话・列挙',
    recognition: { promptZh: '「コーヒーか何か」是什么意思？',
      options: ['咖啡之类的（还没定）', '一定是咖啡', '不要咖啡', '咖啡和别的都要'],
      answerIndex: 0, distractorReason: '「か何か」表示举例但不确定',
      explanationZh: '「〜か何か」= …之类的' },
    production: { promptJa: '客に飲み物をすすめる言い方を「〜か何か」で言ってください。',
      promptZh: '用「〜か何か」向客人推荐饮料。',
      expected: ['か何か'], acceptable: ['お茶か何か', 'コーヒーか何か'] },
    practice: { themeJa: '来客にすすめる',
      starterJa: 'お客さんが来たとき、何をすすめますか？「〜か何か」で言ってみましょう',
      starterZh: '客人来时你会推荐什么？用「〜か何か」说说', targetUse: '〜か何か' },
    vocabularyLinks: ['fi-nomu', 'fi-kau'] }),
  g({ grammarId: 'n2g-027', pattern: '〜かねない', reading: 'かねない', unit: 2, zhSourceRowId: null,
    meaningJa: '〜する可能性がある（悪いことが）',
    explanationZh: '有可能…（不好的事）、说不定会…',
    formation: '動詞ます形 ＋かねない',
    usageScene: '提醒风险、说明放任不管的后果',
    nuance: '悪い結果限定。「〜かねます」（できません）とは別物なので注意',
    register: 'written',
    sourceExample: src('今のまま改善できなければ、また失敗しかねないと思います。＝失敗する可能性がある', '013d0a6acaa93289'),
    examplesJa: ['今のまま改善できなければ、また失敗しかねないと思います。',
                 '確認を怠ると、大きな問題になりかねません。'],
    examplesZh: ['如果就这样不改善，说不定还会失败。', '疏于确认的话，有可能演变成大问题。'],
    furigana: 'いまの まま かいぜん できなければ、また しっぱい しかねないと おもいます。',
    commonMistakesZh: '「かねない」（有可能发生坏事）と「かねる」（做不到）は正反対に近い。混同注意',
    learnerFocus: '「〜かねない」は警告、「〜かねます」は丁寧な拒否。ビジネスで両方出るので区別必須',
    similarPatterns: ['〜恐れがある', '〜かもしれない'],
    contrast: '「かねない」＝悪い可能性（やや口語も可）；「恐れがある」＝正式な警告；「かもしれない」＝中性',
    recognition: { promptZh: '「事故になりかねない」是什么意思？',
      options: ['有可能酿成事故', '绝对不会有事故', '事故已经发生了', '事故解决了'],
      answerIndex: 0, distractorReason: '「かねない」表示有发生坏事的可能',
      explanationZh: '「〜かねない」= 有可能（发生坏事）' },
    production: { promptJa: '放置した場合のリスクを「〜かねません」で言ってください。',
      promptZh: '用「〜かねません」说明放任不管的风险。',
      expected: ['かねな'], acceptable: ['〜かねません', '〜かねない'] },
    practice: { themeJa: 'リスクを伝える',
      starterJa: '仕事で「このままだと危ない」と伝えるとき、どう言いますか？',
      starterZh: '工作中要提醒「这样下去有危险」时你怎么说？', targetUse: '〜かねません' },
    vocabularyLinks: ['fi-mondai', 'fi-kakunin'] }),
  g({ grammarId: 'n2g-028', pattern: '〜かねる', reading: 'かねる', unit: 2, zhSourceRowId: null,
    meaningJa: '（したいが）〜できない',
    explanationZh: '难以…、无法…（礼貌的拒绝）',
    formation: '動詞ます形 ＋かねる（〜かねます）',
    usageScene: '商务场合礼貌地拒绝、说明无法判断',
    nuance: '「できません」より柔らかく丁寧。接客・ビジネスの定番',
    register: 'written',
    sourceExample: src('テストの点数が高いという情報では、会話力の実力を判断しかねます。　＝判断できないです', '87b96f5ddb690c17'),
    examplesJa: ['テストの点数が高いという情報では、会話力の実力を判断しかねます。',
                 '申し訳ございませんが、こちらではお答えいたしかねます。'],
    examplesZh: ['仅凭考试分数高这一信息，难以判断会话的实力。', '非常抱歉，这边难以回答。'],
    furigana: 'テストの てんすうが たかいという じょうほうでは、かいわりょくの じつりょくを はんだん しかねます。',
    commonMistakesZh: '「かねます」是礼貌的「做不到」。「かねません」は「有可能发生坏事」で逆の意味',
    learnerFocus: '接客・カスタマーサポートの定型。「いたしかねます」は最も丁寧な断り方の一つ',
    similarPatterns: ['〜できません', '〜は難しいです'],
    contrast: '丁寧さ: 「できません」＜「難しいです」＜「〜かねます」',
    recognition: { promptZh: '「お答えいたしかねます」是什么意思？',
      options: ['难以回答（礼貌的拒绝）', '表示一定会认真回答', '表示已经回答完毕了', '表示很想马上回答'],
      answerIndex: 0, distractorReason: '「かねます」是礼貌地表示做不到',
      explanationZh: '「〜かねます」= 难以…（礼貌拒绝）' },
    production: { promptJa: '丁寧に断る言い方を「〜かねます」で言ってください。',
      promptZh: '用「〜かねます」礼貌地拒绝。',
      expected: ['かねます'], acceptable: ['〜かねます', 'いたしかねます'] },
    practice: { themeJa: '丁寧に断る練習',
      starterJa: 'お客様の要望に応えられないとき、日本語でどう伝えますか？',
      starterZh: '无法满足客户要求时，你用日语怎么表达？', targetUse: '〜かねます' },
    vocabularyLinks: ['fi-setsumei', 'fi-muri'] }),
  g({ grammarId: 'n2g-029', pattern: '〜かのようだ', reading: 'かのようだ', unit: 2, zhSourceRowId: null,
    meaningJa: '実際は違うが、まるで〜のようだ',
    explanationZh: '仿佛…一样、宛如…。实际不是，但感觉如此',
    formation: '動詞普通形／名詞＋である ＋かのようだ／かのような／かのように',
    usageScene: '文学的な描写、強い比喩',
    nuance: '「ようだ」より比喩性が強く、書面的。「まるで」と一緒に使うことが多い',
    register: 'written',
    sourceExample: src('まるで、天国にいるかのような気分です。', '3b3f2b1c575e8508'),
    examplesJa: ['まるで、天国にいるかのような気分です。',
                 '彼は何も知らないかのように話を続けました。'],
    examplesZh: ['简直像在天堂一样的心情。', '他仿佛什么都不知道似的继续说着。'],
    furigana: 'まるで、てんごくに いるかのような きぶんです。',
    commonMistakesZh: '「ようだ」より強い比喩。日常会話で多用すると大げさに聞こえる',
    learnerFocus: '作文・スピーチで印象を強めたいときに効く。「まるで〜かのようだ」でセット',
    similarPatterns: ['〜ようだ', '〜みたいだ'],
    contrast: '比喩の強さ: 「みたい」＜「ようだ」＜「かのようだ」',
    recognition: { promptZh: '「かのようだ」和「ようだ」的区别是？',
      options: ['「かのようだ」比喻性更强、更书面', '意思完全相同', '「かのようだ」更口语', '「かのようだ」表示确定'],
      answerIndex: 0, distractorReason: '「かのようだ」是更强的比喻，偏书面',
      explanationZh: '比喩の強さと文体が違う' },
    production: { promptJa: '強い比喩を「まるで〜かのようだ」で言ってください。',
      promptZh: '用「まるで〜かのようだ」做一个强比喻。',
      expected: ['かのよう'], acceptable: ['まるで〜かのようです'] },
    practice: { themeJa: '印象を比喩で伝える',
      starterJa: '初めて日本に来た日の気持ちを、比喩で表してみましょう',
      starterZh: '试着用比喻表达第一次来日本那天的心情', targetUse: 'まるで〜かのようだ' },
    vocabularyLinks: ['fi-kimochi', 'fi-kanjiru'] }),
  g({ grammarId: 'n2g-030', pattern: '〜からいいようなものの', reading: 'からいいようなものの', unit: 2, zhSourceRowId: null,
    meaningJa: '〜だったからよかったが、そうでなければ大変だった',
    explanationZh: '幸好…否则就…。表示侥幸，暗示后果本可能很糟',
    formation: '動詞・い形容詞普通形 ＋からいいようなものの',
    usageScene: '事后回想「幸好…」并提醒风险',
    nuance: '後半に「もし〜だったら大変だった」が続く。反省・注意喚起の含み',
    register: 'written',
    sourceExample: src('合格できたからいいようなものの、あと一つ間違えたら不合格でした。', 'ace5a6878478c7ca'),
    examplesJa: ['合格できたからいいようなものの、あと一つ間違えたら不合格でした。',
                 '軽いけがで済んだからいいようなものの、大事故になるところでした。'],
    examplesZh: ['幸好合格了，再错一道就不及格了。', '幸好只是轻伤，差点酿成大事故。'],
    furigana: 'ごうかく できたから いいような ものの、あと ひとつ まちがえたら ふごうかくでした。',
    commonMistakesZh: '長い形なので丸ごと覚える。後半に「危なかった」内容が必ず続く',
    learnerFocus: '反省を述べる高度な表現。使えると日本語が一段上に見える。まず読解で認識できることを目標に',
    similarPatterns: ['〜てよかったものの', '〜からよかったが'],
    contrast: '「からいいようなものの」＝侥幸＋警告；「〜てよかった」＝単純な安堵',
    recognition: { promptZh: '「間に合ったからいいようなものの」暗示什么？',
      options: ['幸好赶上了，差点没赶上', '时间充裕完全没有问题', '最终还是没有赶上', '根本不需要赶时间'],
      answerIndex: 0, distractorReason: '这个句型暗示后果本可能很糟',
      explanationZh: '侥幸＋本可能出事的警告' },
    production: { promptJa: '危なかった経験を「〜からいいようなものの」で言ってください。',
      promptZh: '用「〜からいいようなものの」说一次侥幸的经历。',
      expected: ['いいようなものの'], acceptable: ['〜からいいようなものの'] },
    practice: { themeJa: '危なかった経験を振り返る',
      starterJa: '「あぶなかった」と思った経験はありますか？', starterZh: '有过觉得「好险」的经历吗？',
      targetUse: '〜からいいようなものの' },
    vocabularyLinks: ['fi-mondai', 'fi-ureshii'] }),
];
