// Phase 3P-4: N3文法完成draft バッチ4（原因・比較・限定・例示 の19文型・最終）。全draft。
import type { N3GrammarDraft } from './n3GrammarDrafts';

const g = (p: Omit<N3GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey'> & { reviewKey?: string }): N3GrammarDraft =>
  ({ level: 'N3', route: 'n3-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, ...p });

export const N3_GRAMMAR_DRAFTS_BATCH4: N3GrammarDraft[] = [
  g({ grammarId: 'n3g-niyotte', sourceRowId: 'n3row-78', pattern: '〜によって', reading: 'によって',
    meaningJa: '原因・手段・受身の動作主', explanationZh: '①因为…（原因）②通过…（手段）③被…（被动的动作主）',
    formation: '名詞 ＋によって',
    usageScene: '新闻报道原因、说明方法、书面被动句',
    nuance: '书面语。会话中原因用「〜で」、手段用「〜で」更自然',
    register: 'written',
    examplesJa: ['大雪によって、道路が通行止めになりました。', 'この問題は話し合いによって解決しました。'],
    examplesZh: ['因为大雪，道路禁止通行了。', '这个问题通过协商解决了。'],
    furigana: 'おおゆきに よって、どうろが つうこうどめに なりました。',
    commonMistakesZh: '会话里说「事故で電車が遅れた」更自然。「によって」偏新闻和公文',
    learnerFocus: '「によっては」（也有…的情况）和「によって」意思不同，多一个「は」意思就变了',
    similarPatterns: ['〜で', '〜のせいで', '〜によっては'],
    contrast: '「によって」＝书面原因/手段；「で」＝口语；「のせいで」＝负面归咎',
    recognition: { promptZh: '「地震によって被害が出た」多出现在哪里？',
      options: ['新闻报道', '朋友闲聊', '儿歌', '菜谱'],
      answerIndex: 0, distractorReason: '「によって」是书面正式表达',
      explanationZh: '新闻・公文常用「によって」' },
    production: { promptJa: '電車が遅れた原因を「〜によって」で言ってください。',
      promptZh: '用「〜によって」说明电车晚点的原因。',
      expected: ['によって'], acceptable: ['事故によって'] },
    practice: { themeJa: 'ニュース調で原因を説明する', starterJa: '今日のニュースの出来事を「〜によって」で説明してみましょう',
      starterZh: '试着用「〜によって」说明今天新闻里的事', targetUse: '〜によって' },
    vocabularyLinks: ['fi-densha', 'fi-mondai'], unit: 'n3g-unit-5' }),
  g({ grammarId: 'n3g-aidani', sourceRowId: 'n3row-79', pattern: '〜あいだに', reading: 'あいだに',
    meaningJa: 'ある期間の中で（その間に）', explanationZh: '在…期间（做了某事）。强调在期限内完成',
    formation: '動詞ている形／名詞＋の／い形容詞 ＋あいだに',
    usageScene: '说明趁着在日本的期间要多旅行、趁孩子睡着时做事',
    nuance: '「あいだに」＝期间内的某个时点；「あいだ」＝整段期间持续',
    register: 'both',
    examplesJa: ['子どもが学校にいるあいだに、買い物を済ませます。', '子どもが寝ているあいだに、掃除をしました。'],
    examplesZh: ['趁孩子在学校的时候，把东西买好。', '趁孩子睡觉时打扫了卫生。'],
    furigana: 'こどもが がっこうに いるあいだに、かいものを すませます。',
    commonMistakesZh: '「あいだ」和「あいだに」差一个「に」，意思不同：持续 vs 期间内的一个动作',
    learnerFocus: '「〜うちに」也是「趁着」，但更强调「不趁现在就来不及了」的紧迫感',
    similarPatterns: ['〜うちに', '〜あいだ'],
    contrast: '「あいだに」期间内完成；「あいだ」全程持续；「うちに」趁还没变化',
    recognition: { promptZh: '「留学しているあいだに」暗示什么？',
      options: ['要在留学期间做完某事', '留学结束以后', '留学之前', '不留学'],
      answerIndex: 0, distractorReason: '「あいだに」表示在这段期间内完成某动作',
      explanationZh: '「〜あいだに」= 趁着…期间' },
    production: { promptJa: '日本にいるあいだにしたいことを言ってください。',
      promptZh: '说说你想趁在日本期间做的事。',
      expected: ['あいだに'], acceptable: ['〜あいだに〜したい'] },
    practice: { themeJa: '日本滞在中の目標を話す', starterJa: '日本にいるあいだに、何をしたいですか？',
      starterZh: '趁在日本期间你想做什么？', targetUse: '〜あいだに' },
    vocabularyLinks: ['fi-nihon', 'fi-yotei'], unit: 'n3g-unit-9' }),
  g({ grammarId: 'n3g-uede', sourceRowId: 'n3row-80', pattern: '〜うえで', reading: 'うえで',
    meaningJa: '〜してから（その結果をふまえて）', explanationZh: '在…之后（基于该结果再做下一步）',
    formation: '動詞た形／名詞＋の ＋うえで',
    usageScene: '商务流程说明：确认之后再提交、商量之后再决定',
    nuance: '强调「前项是后项的前提」。单纯的时间先后用「〜てから」',
    register: 'written',
    examplesJa: ['見積もりを比べたうえで、決めたいと思います。', '家族と相談のうえで、お返事します。'],
    examplesZh: ['想比较过报价之后再决定。', '和家人商量之后再答复您。'],
    furigana: 'みつもりを くらべた うえで、きめたいと おもいます。',
    commonMistakesZh: '和「〜上に」（而且）形似意不同。「うえで」是「之后」，「上に」是「加之」',
    learnerFocus: '商务邮件高频。「検討のうえ、ご連絡いたします」是非常实用的定型句',
    similarPatterns: ['〜てから', '〜あとで'],
    contrast: '「うえで」＝以前项为前提（正式）；「てから」＝单纯的先后；「あとで」＝之后',
    recognition: { promptZh: '「ご検討のうえ、ご返事ください」是什么意思？',
      options: ['请考虑之后再答复', '请立刻答复', '不用答复', '已经答复了'],
      answerIndex: 0, distractorReason: '「うえで」表示以前项为前提再做后项',
      explanationZh: '商务定型：考虑之后再…' },
    production: { promptJa: 'ビジネスメールで「確認してから返事する」を「〜うえで」で言ってください。',
      promptZh: '用「〜うえで」写商务邮件里的「确认之后答复」。',
      expected: ['うえで'], acceptable: ['確認のうえ', '確認したうえで'] },
    practice: { themeJa: 'ビジネスメールの定型を使う', starterJa: '返事を保留するとき、日本語で何と書きますか？',
      starterZh: '要暂缓答复时用日语怎么写？', targetUse: '〜うえで' },
    vocabularyLinks: ['fi-kakunin', 'fi-soudan'], unit: 'n3g-unit-9' }),
  g({ grammarId: 'n3g-osoregaaru', sourceRowId: 'n3row-82', pattern: '〜おそれがある', reading: 'おそれがある',
    meaningJa: '悪いことが起きる可能性がある', explanationZh: '有…的危险、恐怕会…。仅用于不好的可能性',
    formation: '動詞辞書形／名詞＋の ＋おそれがある',
    usageScene: '天气警报、事故风险、健康风险的正式通告',
    nuance: '书面且正式。好事不能用（合格するおそれ ×）',
    register: 'written',
    examplesJa: ['土砂崩れが起きるおそれがあるため、通行を止めています。', '大雪のため、電車が止まるおそれがあります。'],
    examplesZh: ['因为有发生塌方的危险，正在封路。', '因为大雪，电车有停运的可能。'],
    furigana: 'どしゃくずれが おきる おそれが あるため、つうこうを とめて います。',
    commonMistakesZh: '只用于负面。好的可能性用「〜可能性がある」（中性）',
    learnerFocus: '灾害警报、公司通知里常见。听懂它意味着能提前避险，是生活安全相关的重要文型',
    similarPatterns: ['〜可能性がある', '〜かもしれない'],
    contrast: '「おそれがある」＝负面正式；「可能性がある」＝中性；「かもしれない」＝口语',
    recognition: { promptZh: '哪个用「おそれがある」不自然？',
      options: ['試験に合格するおそれがある', '大雨になるおそれがある', '事故が起きるおそれがある', '停電するおそれがある'],
      answerIndex: 0, distractorReason: '「おそれ」只用于不好的可能性',
      explanationZh: '好事用「可能性がある」' },
    production: { promptJa: '天気の警報を「〜おそれがあります」で言ってください。',
      promptZh: '用「〜おそれがあります」说一条天气警报。',
      expected: ['おそれがあ'], acceptable: ['〜おそれがあります'] },
    practice: { themeJa: '災害情報を読み取る', starterJa: '日本で災害の注意報を見たことがありますか？',
      starterZh: '你在日本见过灾害警报吗？', targetUse: '〜おそれがあります' },
    vocabularyLinks: ['fi-densha', 'fi-joukyou'], unit: 'n3g-unit-6' }),
  g({ grammarId: 'n3g-kawarini', sourceRowId: 'n3row-83', pattern: '〜かわりに', reading: 'かわりに',
    meaningJa: '〜の代わりとして／〜する一方で', explanationZh: '①代替…②虽然…但作为交换…',
    formation: '動詞普通形／名詞＋の ＋かわりに',
    usageScene: '说明用别的方式代替、或说明得失的平衡',
    nuance: '②的「有得有失」用法在会话中很常见（家賃は高いかわりに駅が近い）',
    register: 'both',
    examplesJa: ['会社は駅から遠いかわりに、家賃が安いです。', 'この部屋は狭いかわりに、家賃が安いです。'],
    examplesZh: ['公司离车站远，但作为交换房租便宜。', '这房间虽小，但房租便宜。'],
    furigana: 'かいしゃは えきから とおい かわりに、やちんが やすいです。',
    commonMistakesZh: '名詞接续要加「の」：「私のかわりに」。人称代词也一样',
    learnerFocus: '「〜かわりに」表示交换关系，比只说缺点更客观、更成熟的表达方式',
    similarPatterns: ['〜代わりに', '〜反面'],
    contrast: '「かわりに」＝代替或交换；「〜が」＝单纯转折',
    recognition: { promptZh: '「給料は安いかわりに、時間の自由がある」是什么意思？',
      options: ['工资低但时间自由（有得有失）', '工资低而且不自由', '工资高且自由', '没有工作'],
      answerIndex: 0, distractorReason: '「かわりに」表示得失的交换关系',
      explanationZh: '「〜かわりに」= 作为交换' },
    production: { promptJa: '今の仕事や住まいの「得と損」を「〜かわりに」で言ってください。',
      promptZh: '用「〜かわりに」说说现在工作或住处的得与失。',
      expected: ['かわりに'], acceptable: ['〜かわりに'] },
    practice: { themeJa: '今の生活の得失を話す', starterJa: '今の住まいや仕事の「いい点と悪い点」を一文で言ってみましょう',
      starterZh: '用一句话说说现在住处或工作的优缺点', targetUse: '〜かわりに' },
    vocabularyLinks: ['fi-yasui', 'fi-shigoto'], unit: 'n3g-unit-5' }),
  g({ grammarId: 'n3g-kiri', sourceRowId: 'n3row-84', pattern: '〜きり', reading: 'きり',
    meaningJa: '〜して以来ずっと（その後変化がない）', explanationZh: '自从…就再没…。表示动作之后状态一直没变',
    formation: '動詞た形 ＋きり（＋否定）',
    usageScene: '说明和某人失联、东西借出去没还',
    nuance: '后项几乎必是否定。含遗憾或不满',
    register: 'both',
    examplesJa: ['傘を貸したきり、まだ返ってきていません。', '本を貸したきり、返ってきません。'],
    examplesZh: ['伞借出去后就一直没还回来。', '书借出去后就没还回来。'],
    furigana: 'かさを かしたきり、まだ かえって きていません。',
    commonMistakesZh: '后项必须是否定或消极内容。「会ったきり、毎日連絡しています」不自然',
    learnerFocus: '「〜たきり」＋否定是固定搭配。少了否定意思就不成立',
    similarPatterns: ['〜まま', '〜以来'],
    contrast: '「きり」＝之后再没…（含遗憾）；「まま」＝状态保持；「以来」＝中性的时间起点',
    recognition: { promptZh: '「国に帰ったきり」后面最自然的是？',
      options: ['戻ってきません', '毎日会っています', '元気です', '楽しいです'],
      answerIndex: 0, distractorReason: '「〜たきり」后面要接否定或消极的结果',
      explanationZh: '「〜たきり＋否定」是固定形' },
    production: { promptJa: '連絡が途絶えた経験を「〜たきり」で言ってください。',
      promptZh: '用「〜たきり」说一次失联的经历。',
      expected: ['きり'], acceptable: ['会ったきり', '〜たきり'] },
    practice: { themeJa: '疎遠になった友人の話をする', starterJa: '会ったきり、連絡していない人はいますか？',
      starterZh: '有见过一面后就没再联系的人吗？', targetUse: '〜たきり' },
    vocabularyLinks: ['fi-au', 'fi-renraku'], unit: 'n3g-unit-3' }),
  g({ grammarId: 'n3g-kotoninaruto', sourceRowId: 'n3row-86', pattern: '〜こととなると', reading: 'こととなると',
    meaningJa: 'その話題になると（特別な反応をする）', explanationZh: '一谈到…就…。表示遇到特定话题时的特殊反应',
    formation: '名詞＋の ＋こととなると（ことになると）',
    usageScene: '描述某人一说到某话题就变了个人似的',
    nuance: '强调对该话题的特殊态度（热情或回避）',
    register: 'both',
    examplesJa: ['お金のこととなると、彼は急に慎重になります。', '野球のこととなると、父は止まりません。'],
    examplesZh: ['一谈到钱，他就突然变得谨慎。', '一说到棒球，父亲就滔滔不绝。'],
    furigana: 'おかねの こととなると、かれは きゅうに しんちょうに なります。',
    commonMistakesZh: '名詞接续要加「の」：「彼のこととなると」。忘记「の」是常见错误',
    learnerFocus: '这是描写人物性格的生动表达，在闲聊中能让日语显得地道',
    similarPatterns: ['〜については', '〜に関しては'],
    contrast: '「こととなると」＝一谈到就有特殊反应；「については」＝中性的话题标记',
    recognition: { promptZh: '「食べ物のこととなると、彼は真剣だ」是什么意思？',
      options: ['一说到吃的他就特别认真', '他讨厌吃的', '他不吃东西', '他在做饭'],
      answerIndex: 0, distractorReason: '「こととなると」表示遇到该话题时的特殊反应',
      explanationZh: '「〜こととなると」= 一谈到…就' },
    production: { promptJa: '身近な人の「これになると変わる」を「〜こととなると」で言ってください。',
      promptZh: '用「〜こととなると」说说身边人一谈到某事就变样。',
      expected: ['こととなると'], acceptable: ['〜のこととなると'] },
    practice: { themeJa: '人の意外な一面を話す', starterJa: '何かのこととなると人が変わる、そんな人はいますか？',
      starterZh: '有没有一谈到某事就像变了个人的人？', targetUse: '〜こととなると' },
    vocabularyLinks: ['fi-tomodachi', 'fi-kyoumi'], unit: 'n3g-unit-9' }),
  g({ grammarId: 'n3g-shikanai', sourceRowId: 'n3row-87', pattern: '〜しかない', reading: 'しかない',
    meaningJa: 'それ以外に方法がない', explanationZh: '只能…、只好…。别无他法',
    formation: '動詞辞書形／名詞 ＋しかない',
    usageScene: '说明没有选择余地的处境：只能干了、只剩这一条路',
    nuance: '含无奈，但也可用于鼓励自己（やるしかない！）',
    register: 'both',
    examplesJa: ['もうやるしかありません。', '終電がないので、タクシーで帰るしかない。'],
    examplesZh: ['只能干了。', '没有末班车了，只能打车回去。'],
    furigana: 'もう やるしか ありません。',
    commonMistakesZh: '「しか」后面必须是否定形（ない・ありません）。写成「しかある」是错的',
    learnerFocus: '「やるしかない」是日本人给自己打气的常用语，学会后表达会很自然',
    similarPatterns: ['〜だけだ', '〜ほかない'],
    contrast: '「しかない」＝没别的办法（无奈）；「だけ」＝只是（中性）',
    recognition: { promptZh: '「歩いて帰るしかない」是什么心情？',
      options: ['没别的办法，只好走回去', '很想走回去', '不打算回去', '有很多选择'],
      answerIndex: 0, distractorReason: '「しかない」含无可选择的无奈',
      explanationZh: '「〜しかない」= 只能…' },
    production: { promptJa: '選択肢がない状況を「〜しかない」で言ってください。',
      promptZh: '用「〜しかない」说一个别无选择的处境。',
      expected: ['しかな'], acceptable: ['〜しかない', '〜しかありません'] },
    practice: { themeJa: '困った状況での判断を話す', starterJa: '終電を逃したら、どうしますか？',
      starterZh: '错过末班车你会怎么办？', targetUse: '〜しかない' },
    vocabularyLinks: ['fi-kaeru', 'fi-komaru'], unit: 'n3g-unit-7' }),
  g({ grammarId: 'n3g-sugiru', sourceRowId: 'n3row-88', pattern: '〜すぎる', reading: 'すぎる',
    meaningJa: '程度が limit を超えている', explanationZh: '太…、过于…。超过了合适的程度（多为负面）',
    formation: '動詞ます形／い形容詞（〜い削除）／な形容詞語幹 ＋すぎる',
    usageScene: '说自己吃太多、工作太忙、价格太贵',
    nuance: '含「不好」的评价。单纯的程度高用「とても」',
    register: 'both',
    examplesJa: ['今週は少し働きすぎたので、週末は休みます。', 'この仕事は忙しすぎます。'],
    examplesZh: ['这周工作有点过头了，周末要休息。', '这份工作太忙了。'],
    furigana: 'こんしゅうは すこし はたらきすぎたので、しゅうまつは やすみます。',
    commonMistakesZh: '「いい」→「よすぎる」、「ない」→「なさすぎる」是特殊变化',
    learnerFocus: '「とても高い」（很贵・中性）与「高すぎる」（太贵了・负面评价）的差别要分清',
    similarPatterns: ['〜とても', '〜ほど'],
    contrast: '「すぎる」＝超过限度（负面）；「とても」＝程度高（中性）',
    recognition: { promptZh: '「この服は高すぎます」的语气是？',
      options: ['觉得太贵了（负面评价）', '觉得很好', '价格合适', '不知道价格'],
      answerIndex: 0, distractorReason: '「すぎる」表示超过了合适的程度',
      explanationZh: '「〜すぎる」= 太…了（含负面）' },
    production: { promptJa: '「〜すぎた」経験を言ってください。',
      promptZh: '用「〜すぎた」说一次做过头的经历。',
      expected: ['すぎ'], acceptable: ['食べすぎました', '〜すぎた'] },
    practice: { themeJa: 'やりすぎた経験を話す', starterJa: '最近、何かをしすぎたことはありますか？',
      starterZh: '最近有什么事做过头了吗？', targetUse: '〜すぎる' },
    vocabularyLinks: ['fi-taberu', 'fi-takai'], unit: 'n3g-unit-8' }),
  g({ grammarId: 'n3g-toiunoha', sourceRowId: 'n3row-93', pattern: '〜というのは', reading: 'というのは',
    meaningJa: '〜の意味は（定義・説明）', explanationZh: '所谓的…就是…。用于定义或解释词语',
    formation: '名詞／引用句 ＋というのは〜ことだ',
    usageScene: '向别人解释生词、说明专有名词',
    nuance: '句尾常用「〜ことです」「〜という意味です」呼应',
    register: 'both',
    examplesJa: ['「時短」というのは、時間を短くする工夫のことです。', '「もったいない」というのは、無駄にしたくない気持ちです。'],
    examplesZh: ['所谓「時短」就是缩短时间的办法。', '所谓「もったいない」是不想浪费的心情。'],
    furigana: '「じたん」というのは、じかんを みじかく する くふうの ことです。',
    commonMistakesZh: '句尾要呼应「〜ことです」「〜という意味です」，只说前半句会不完整',
    learnerFocus: '不懂的词可以问「〜というのはどういう意味ですか」，是学习中最实用的提问句',
    similarPatterns: ['〜とは', '〜って'],
    contrast: '「というのは」中性；「とは」更正式（辞典）；「って」是口语',
    recognition: { promptZh: '想问某个词的意思，最自然的是？',
      options: ['「〜」というのはどういう意味ですか', '「〜」は何ですか', '「〜」を教えて', '「〜」ですか'],
      answerIndex: 0, distractorReason: '询问词义的定型是「〜というのはどういう意味ですか」',
      explanationZh: '这是询问词义的标准问法' },
    production: { promptJa: '中国語の言葉を一つ、「〜というのは〜ことです」で説明してください。',
      promptZh: '用「〜というのは〜ことです」解释一个中文词。',
      expected: ['というのは'], acceptable: ['〜というのは〜ことです'] },
    practice: { themeJa: '母語の言葉を日本語で説明する', starterJa: '中国語の言葉を一つ、日本語で説明してみましょう',
      starterZh: '试着用日语解释一个中文词', targetUse: '〜というのは〜ことです' },
    vocabularyLinks: ['fi-setsumei', 'fi-nihongo'], unit: 'n3g-unit-9' }),
  g({ grammarId: 'n3g-nikurabete', sourceRowId: 'n3row-96', pattern: '〜にくらべて', reading: 'にくらべて',
    meaningJa: '〜と比較すると', explanationZh: '与…相比。用于两者的比较',
    formation: '名詞 ＋にくらべて（に比べると）',
    usageScene: '比较去年和今年、中国和日本、以前和现在',
    nuance: '客观比较。「〜より」更口语、更简短',
    register: 'both',
    examplesJa: ['先月にくらべて、問い合わせが倍に増えました。', '中国にくらべて、日本は物価が高いと思います。'],
    examplesZh: ['和上个月相比，咨询增加了一倍。', '和中国相比，我觉得日本物价高。'],
    furigana: 'せんげつに くらべて、といあわせが ばいに ふえました。',
    commonMistakesZh: '「より」也是「比」，但「にくらべて」用于整体比较，「より」用于具体项目的高低',
    learnerFocus: '介绍中日差异时的高频表达。自我介绍和闲聊都能用',
    similarPatterns: ['〜より', '〜に対して'],
    contrast: '「にくらべて」＝整体比较；「より」＝具体的高低对比',
    recognition: { promptZh: '「去年にくらべて」是把今年和什么比？',
      options: ['和去年比', '和明年比', '和上个月比', '不比较'],
      answerIndex: 0, distractorReason: '「〜にくらべて」的「〜」是比较的基准',
      explanationZh: '「Aにくらべて、B」= 和A相比，B…' },
    production: { promptJa: '日本と中国を「〜にくらべて」で比べてください。',
      promptZh: '用「〜にくらべて」比较日本和中国。',
      expected: ['くらべて'], acceptable: ['〜にくらべて', '〜に比べて'] },
    practice: { themeJa: '日本と故郷を比べる', starterJa: '故郷にくらべて、日本はどうですか？',
      starterZh: '和家乡相比，日本怎么样？', targetUse: '〜にくらべて' },
    vocabularyLinks: ['fi-kuraberu', 'fi-chugoku'], unit: 'n3g-unit-9' }),
  g({ grammarId: 'n3g-nisuginai', sourceRowId: 'n3row-99', pattern: '〜にすぎない', reading: 'にすぎない',
    meaningJa: 'ただ〜だけで、大したことはない', explanationZh: '只不过是…而已。强调程度不高、不值一提',
    formation: '名詞／動詞普通形 ＋にすぎない',
    usageScene: '谦虚地说自己只是做了本分、或说明某事只是一部分',
    nuance: '书面且略正式。谦虚或贬低的语气',
    register: 'written',
    examplesJa: ['今回の成果は、チーム全体の力の一部にすぎません。', '私は自分の仕事をしたにすぎません。'],
    examplesZh: ['这次的成果不过是团队整体力量的一部分。', '我只不过是做了自己的工作而已。'],
    furigana: 'こんかいの せいかは、チームぜんたいの ちからの いちぶに すぎません。',
    commonMistakesZh: '被表扬时说「自分の仕事をしたにすぎません」很谦虚，但过度使用会显得生硬',
    learnerFocus: '日本文化重视谦虚，被夸奖时的回应表达值得掌握，但也不必每次都用',
    similarPatterns: ['〜だけだ', '〜しかない'],
    contrast: '「にすぎない」＝贬低程度（书面）；「だけ」＝中性的限定',
    recognition: { promptZh: '「これは想像にすぎない」是什么意思？',
      options: ['这只不过是想象罢了', '这是事实', '这很重要', '这是命令'],
      answerIndex: 0, distractorReason: '「にすぎない」贬低前项的价值或程度',
      explanationZh: '「〜にすぎない」= 只不过是…' },
    production: { promptJa: 'ほめられたときの謙遜を「〜にすぎません」で言ってください。',
      promptZh: '用「〜にすぎません」谦虚地回应表扬。',
      expected: ['すぎません'], acceptable: ['〜にすぎません'] },
    practice: { themeJa: 'ほめられたときの返し方', starterJa: '仕事をほめられたら、日本語で何と返しますか？',
      starterZh: '工作被表扬时你用日语怎么回应？', targetUse: '〜にすぎません' },
    vocabularyLinks: ['fi-shigoto', 'fi-setsumei'], unit: 'n3g-unit-9' }),
  g({ grammarId: 'n3g-niyotteha', sourceRowId: 'n3row-100', pattern: '〜によっては', reading: 'によっては',
    meaningJa: '場合によってそうなることもある', explanationZh: '也有…的情况、根据…而不同。表示因情况而异',
    formation: '名詞 ＋によっては',
    usageScene: '说明因人而异、因情况而异，留有余地',
    nuance: '比「によって」多了「は」，意思变成「也有…的情况」',
    register: 'both',
    examplesJa: ['曜日によっては、窓口が混むことがあります。', '日によっては、とても混んでいます。'],
    examplesZh: ['有些日子窗口会很挤。', '有些日子会非常拥挤。'],
    furigana: 'ようびに よっては、まどぐちが こむことが あります。',
    commonMistakesZh: '「によって」（因为/通过）和「によっては」（也有…的情况）只差一个「は」，意思完全不同',
    learnerFocus: '避免一概而论时非常有用。日本人喜欢留余地，这个表达很符合语感',
    similarPatterns: ['〜によって', '〜場合がある'],
    contrast: '「によって」＝原因/手段；「によっては」＝因情况而异（有例外）',
    recognition: { promptZh: '「人によっては辛いと感じます」是什么意思？',
      options: ['也有人会觉得辣', '所有人都觉得辣', '没人觉得辣', '我觉得辣'],
      answerIndex: 0, distractorReason: '「によっては」表示只有部分情况如此',
      explanationZh: '「〜によっては」= 也有…的情况' },
    production: { promptJa: '一概に言えないことを「〜によっては」で言ってください。',
      promptZh: '用「〜によっては」说一件不能一概而论的事。',
      expected: ['によっては'], acceptable: ['人によっては', '〜によっては'] },
    practice: { themeJa: '一般化を避けて話す', starterJa: '「人によって違う」ことを、日本語で言ってみましょう',
      starterZh: '试着用日语说「因人而异」的事', targetUse: '〜によっては' },
    vocabularyLinks: ['fi-tomodachi', 'fi-joukyou'], unit: 'n3g-unit-9' }),
  g({ grammarId: 'n3g-noyouna', sourceRowId: 'n3row-102', pattern: '〜のような', reading: 'のような',
    meaningJa: '〜のような（例示・たとえ）', explanationZh: '像…那样的、…之类的。举出具体的例子',
    formation: '名詞＋のような＋名詞 ／ 〜のように＋動詞',
    usageScene: '举例说明自己喜欢的类型、想成为的样子',
    nuance: '「のような」修饰名词，「のように」修饰动词',
    register: 'both',
    examplesJa: ['和食のような、あっさりした料理をよく作ります。', '先生のように上手に話したいです。'],
    examplesZh: ['我常做和食那样清淡的菜。', '想像老师那样说得流利。'],
    furigana: 'わしょくの ような、あっさりした りょうりを よく つくります。',
    commonMistakesZh: '「のような＋名詞」／「のように＋動詞・形容詞」。词性搭配错误很常见',
    learnerFocus: '举例是说明喜好的最有效方式。「〜のような〜」能让表达具体生动',
    similarPatterns: ['〜みたいな', '〜など'],
    contrast: '「のような」正式；「みたいな」口语；「など」是列举',
    recognition: { promptZh: '「先生＿＿上手に話したい」空格是？',
      options: ['のように', 'のような', 'のようだ', 'のように な'],
      answerIndex: 0, distractorReason: '修饰动词「話したい」要用「のように」',
      explanationZh: '「のように＋動詞」／「のような＋名詞」' },
    production: { promptJa: '好きなタイプを「〜のような」で言ってください。',
      promptZh: '用「〜のような」说你喜欢的类型。',
      expected: ['のような'], acceptable: ['〜のような', '〜のように'] },
    practice: { themeJa: '好きなものを例で説明する', starterJa: 'どんなスポーツや音楽が好きですか？例を挙げてみましょう',
      starterZh: '你喜欢什么运动或音乐？举个例子', targetUse: '〜のような' },
    vocabularyLinks: ['fi-suki', 'fi-sensei'], unit: 'n3g-unit-9' }),
  g({ grammarId: 'n3g-nookagede', sourceRowId: 'n3row-103', pattern: '〜のおかげで', reading: 'のおかげで',
    meaningJa: '〜のおかげで良い結果になった', explanationZh: '托…的福、多亏了…。用于好的结果',
    formation: '名詞＋の／動詞た形 ＋おかげで',
    usageScene: '感谢老师、家人、同事的帮助',
    nuance: '只用于好结果。坏结果用「〜のせいで」',
    register: 'both',
    examplesJa: ['同僚が手伝ってくれたおかげで、締め切りに間に合いました。', '皆さんのおかげで、無事に終わりました。'],
    examplesZh: ['多亏同事帮忙，赶上了截止日期。', '托大家的福，顺利结束了。'],
    furigana: 'どうりょうが てつだって くれた おかげで、しめきりに まにあいました。',
    commonMistakesZh: '好事用「おかげで」，坏事用「せいで」。用反了会变成讽刺',
    learnerFocus: '「おかげさまで」是日常寒暄的固定表达，被问「元気ですか」时可回「おかげさまで元気です」',
    similarPatterns: ['〜のせいで', '〜によって'],
    contrast: '「おかげで」＝正面归功；「せいで」＝负面归咎；「によって」＝中性原因',
    recognition: { promptZh: '「雨のおかげで試合が中止になった」这句话给人什么感觉？',
      options: ['像在讽刺（中止本是坏事却说托福）', '很自然', '很有礼貌', '很正式'],
      answerIndex: 0, distractorReason: '「おかげで」只用于好结果，用在坏结果上会变成讽刺',
      explanationZh: '坏结果要用「〜のせいで」' },
    production: { promptJa: '感謝を「〜のおかげで」で伝えてください。',
      promptZh: '用「〜のおかげで」表达感谢。',
      expected: ['おかげで'], acceptable: ['〜のおかげで'] },
    practice: { themeJa: '感謝を伝える', starterJa: '誰のおかげで今の自分がありますか？',
      starterZh: '多亏了谁才有现在的你？', targetUse: '〜のおかげで' },
    vocabularyLinks: ['fi-sensei', 'fi-kazoku'], unit: 'n3g-unit-5' }),
  g({ grammarId: 'n3g-noseide', sourceRowId: 'n3row-104', pattern: '〜のせいで', reading: 'のせいで',
    meaningJa: '〜が原因で悪い結果になった', explanationZh: '因为…（导致坏结果）。含责怪的语气',
    formation: '名詞＋の／動詞普通形 ＋せいで',
    usageScene: '说明失败、迟到、身体不适的原因',
    nuance: '含归咎。对人使用会伤感情，对事物较安全',
    register: 'both',
    examplesJa: ['道が混んでいたせいで、約束の時間に遅れました。', '雨のせいで、洗濯物が乾きません。'],
    examplesZh: ['因为路上堵车，比约定时间晚了。', '因为下雨，衣服干不了。'],
    furigana: 'みちが こんでいた せいで、やくそくの じかんに おくれました。',
    commonMistakesZh: '对人说「あなたのせいで」是很强的指责。职场上尽量用「〜ため」等中性表达',
    learnerFocus: '归咎自己（自分のせいで）可以，归咎他人要非常谨慎，这是日语的人际禁忌',
    similarPatterns: ['〜のおかげで', '〜ため', '〜によって'],
    contrast: '「せいで」＝负面归咎；「おかげで」＝正面；「ため」＝中性正式',
    recognition: { promptZh: '哪个说法在职场上最安全？',
      options: ['電車の遅れのため、遅刻しました', 'あなたのせいで遅刻しました', '部長のせいです', '誰かのせいだ'],
      answerIndex: 0, distractorReason: '「せいで」指责他人容易伤和气，中性说明用「ため」',
      explanationZh: '职场上用「〜のため」更安全' },
    production: { promptJa: '遅刻の理由を「〜せいで」で言ってください（自分の原因で）。',
      promptZh: '用「〜せいで」说明迟到的原因（自己的原因）。',
      expected: ['せいで'], acceptable: ['寝坊したせいで', '〜のせいで'] },
    practice: { themeJa: '失敗の原因を説明する', starterJa: '遅刻したとき、原因をどう説明しますか？',
      starterZh: '迟到时你怎么说明原因？', targetUse: '〜のせいで' },
    vocabularyLinks: ['fi-okiru', 'fi-riyuu'], unit: 'n3g-unit-5' }),
  g({ grammarId: 'n3g-yanado', sourceRowId: 'n3row-107', pattern: '〜や〜など', reading: 'やなど',
    meaningJa: '名詞を例として挙げる', explanationZh: '…啊…之类的。列举名词的代表例（还有其他）',
    formation: '名詞＋や＋名詞（＋など）',
    usageScene: '介绍喜欢的食物、去过的地方',
    nuance: '「と」是全部列举；「や〜など」暗示还有别的',
    register: 'both',
    examplesJa: ['休みの日は、映画や美術館などに行きます。', '休みの日は、映画や買い物などに行きます。'],
    examplesZh: ['休息日会去看电影、逛美术馆什么的。', '休息日会去看电影、买东西什么的。'],
    furigana: 'やすみのひは、えいがや びじゅつかん などに いきます。',
    commonMistakesZh: '「と」是全部（寿司とラーメンが好き＝只喜欢这两个）；「や」是举例（还有别的）',
    learnerFocus: '自我介绍时用「や〜など」显得自然，用「と」会显得刻板或信息不全',
    similarPatterns: ['〜と', '〜たり〜たり'],
    contrast: '「と」＝全部列举；「や〜など」＝名词的举例；「たり」＝动作的举例',
    recognition: { promptZh: '「寿司やラーメンなどが好きです」暗示什么？',
      options: ['除了这些还喜欢别的', '只喜欢这两样', '都不喜欢', '不知道'],
      answerIndex: 0, distractorReason: '「や〜など」暗示列举的只是代表例',
      explanationZh: '「や〜など」= 举例（还有其他）' },
    production: { promptJa: '好きな食べ物を「〜や〜など」で言ってください。',
      promptZh: '用「〜や〜など」说你喜欢的食物。',
      expected: ['や'], acceptable: ['〜や〜など'] },
    practice: { themeJa: '好きなものを挙げる', starterJa: '日本の食べ物で好きなものを、いくつか挙げてください',
      starterZh: '举几个你喜欢的日本食物', targetUse: '〜や〜など' },
    vocabularyLinks: ['fi-suki', 'fi-taberu'], unit: 'n3g-unit-9' }),
  g({ grammarId: 'n3g-nikagiri', sourceRowId: 'n3row-120', pattern: '〜に限り', reading: 'にかぎり',
    meaningJa: '〜だけ特別に（限定）', explanationZh: '仅限…。用于告示、优惠等正式的限定',
    formation: '名詞 ＋に限り',
    usageScene: '店铺告示、优惠条件、活动的参加限制',
    nuance: '非常正式。会话中用「〜だけ」',
    register: 'written',
    examplesJa: ['本日に限り、全品20%引きです。', '学生に限り、無料でご利用いただけます。'],
    examplesZh: ['仅限今天，全场8折。', '仅限学生可免费使用。'],
    furigana: 'ほんじつに かぎり、ぜんぴん にじゅっパーセントびきです。',
    commonMistakesZh: '这是告示体。对朋友说「今日に限り安い」会很奇怪，要说「今日だけ安い」',
    learnerFocus: '在日本购物时看懂「〜に限り」的条件能省钱，是生活实用文型',
    similarPatterns: ['〜だけ', '〜に限らず'],
    contrast: '「に限り」＝仅限（正式告示）；「だけ」＝口语；「に限らず」＝不限于（相反）',
    recognition: { promptZh: '「女性に限り、割引します」是什么意思？',
      options: ['只有女性可以打折', '女性不能打折', '所有人都打折', '男性打折'],
      answerIndex: 0, distractorReason: '「に限り」表示仅限该对象',
      explanationZh: '「〜に限り」= 仅限…' },
    production: { promptJa: '店の告知を「〜に限り」で書いてください。',
      promptZh: '用「〜に限り」写一条店铺告示。',
      expected: ['に限り'], acceptable: ['本日に限り', '〜に限り'] },
    practice: { themeJa: 'セールの条件を読み取る', starterJa: '日本の店で「〜に限り」の表示を見たことがありますか？',
      starterZh: '你在日本的店里见过「〜に限り」的告示吗？', targetUse: '〜に限り' },
    vocabularyLinks: ['fi-yasui', 'fi-gakusei'], unit: 'n3g-unit-10' }),
  g({ grammarId: 'n3g-nikagirazu', sourceRowId: 'n3row-121', pattern: '〜に限らず', reading: 'にかぎらず',
    meaningJa: '〜だけでなく、他も', explanationZh: '不仅限于…，（其他也）…。范围的扩大',
    formation: '名詞 ＋に限らず',
    usageScene: '说明活动面向所有人、现象不限于某个群体',
    nuance: '和「に限り」（限定）相反，是范围扩大。书面语',
    register: 'written',
    examplesJa: ['社員に限らず、家族も利用できる制度です。', '若い人に限らず、幅広い年代に人気があります。'],
    examplesZh: ['不仅限于员工，家属也能使用的制度。', '不仅是年轻人，各个年龄层都受欢迎。'],
    furigana: 'しゃいんに かぎらず、かぞくも りよう できる せいどです。',
    commonMistakesZh: '「に限り」（仅限）与「に限らず」（不限于）意思相反，读告示时看错会误解条件',
    learnerFocus: '一字之差意思相反的一对，是阅读理解的重要考点，也影响实际生活判断',
    similarPatterns: ['〜だけでなく', '〜に限り'],
    contrast: '「に限らず」＝范围扩大；「に限り」＝范围限定。完全相反',
    recognition: { promptZh: '「社員に限らず参加できます」是什么意思？',
      options: ['不是员工也能参加', '只有员工能参加', '员工不能参加', '谁都不能参加'],
      answerIndex: 0, distractorReason: '「に限らず」表示不限于该对象，范围更广',
      explanationZh: '「〜に限らず」= 不仅限于…' },
    production: { promptJa: '参加条件が広いことを「〜に限らず」で言ってください。',
      promptZh: '用「〜に限らず」说明参加条件很宽。',
      expected: ['に限らず'], acceptable: ['学生に限らず', '〜に限らず'] },
    practice: { themeJa: '募集条件を説明する', starterJa: 'イベントの参加条件を「〜に限らず」で説明してみましょう',
      starterZh: '试着用「〜に限らず」说明活动的参加条件', targetUse: '〜に限らず' },
    vocabularyLinks: ['fi-gakusei', 'fi-tomodachi'], unit: 'n3g-unit-10' }),
];
