// Phase 3P-4: N3文法完成draft バッチ2（推量・伝聞・許可義務・理由 の19文型）。
// 完成条件はn3GrammarDrafts.tsと同一（全field完備のみ収録）。全draft。
import type { N3GrammarDraft } from './n3GrammarDrafts';

const g = (p: Omit<N3GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey'> & { reviewKey?: string }): N3GrammarDraft =>
  ({ level: 'N3', route: 'n3-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, ...p });

export const N3_GRAMMAR_DRAFTS_BATCH2: N3GrammarDraft[] = [
  g({ grammarId: 'n3g-nitotte', sourceRowId: 'n3row-37', pattern: '〜にとって', reading: 'にとって',
    meaningJa: '〜の立場から見ると', explanationZh: '对…来说。从某人/某组织的立场来评价',
    formation: '名詞 ＋にとって（は／も）',
    usageScene: '说明同一件事对不同人的意义不同：对我来说很重要／对公司来说是机会',
    nuance: '后面接评价性的词（大切だ・重要だ・難しい）。不接具体动作',
    register: 'both',
    examplesJa: ['私にとって彼は特別な人です。', '外国人にとって、敬語は難しいです。'],
    examplesZh: ['对我来说他是特别的人。', '对外国人来说，敬语很难。'],
    furigana: 'わたしにとって かれは とくべつな ひとです。',
    commonMistakesZh: '和「〜に対して」（对…采取行动）混淆。「にとって」是立场评价，不能说「私にとって説明した」',
    learnerFocus: '中文「对我来说」和「对我」都是一个「对」，日语要分「にとって」（评价）和「に対して」（行为对象）',
    similarPatterns: ['〜に対して', '〜として'],
    contrast: '「にとって」＝立场评价；「に対して」＝行为的对象；「として」＝以…的身份',
    recognition: { promptZh: '哪个句子正确？',
      options: ['私にとって大切な人です', '私にとって説明しました', '私にとって行きます', '私にとって食べます'],
      answerIndex: 0, distractorReason: '「にとって」后面要接评价，不接具体动作',
      explanationZh: '「〜にとって＋評価の言葉」が基本形' },
    production: { promptJa: '自分にとって大切なものを「〜にとって」で言ってください。',
      promptZh: '用「〜にとって」说说对你来说重要的东西。',
      expected: ['にとって'], acceptable: ['私にとって'] },
    practice: { themeJa: '自分にとって大切なものを話す', starterJa: 'あなたにとって、いちばん大切なものは何ですか？',
      starterZh: '对你来说最重要的是什么？', targetUse: '〜にとって' },
    vocabularyLinks: ['fi-hitsuyou', 'fi-kazoku'], unit: 'n3g-unit-6' }),
  g({ grammarId: 'n3g-niyoruto', sourceRowId: 'n3row-38', pattern: '〜によると', reading: 'によると',
    meaningJa: '情報の出どころを示す', explanationZh: '根据…（消息来源）。表示信息是从哪里得到的',
    formation: '名詞 ＋によると（によれば）',
    usageScene: '转述天气预报、新闻、别人说的话',
    nuance: '句尾必须呼应传闻形式「〜そうだ」「〜ということだ」',
    register: 'both',
    examplesJa: ['天気予報によると、明日は雨だそうです。', 'ニュースによると、電車が止まっているそうです。'],
    examplesZh: ['据天气预报说，明天下雨。', '据新闻说，电车停运了。'],
    furigana: 'てんきよほうに よると、あしたは あめだそうです。',
    commonMistakesZh: '句尾忘记用「そうです」是最常见的错误。「〜によると、明日は雨です」不自然',
    learnerFocus: '「によると」和句尾「そうだ」是一对，必须同时出现。这是日语转述的固定结构',
    similarPatterns: ['〜そうだ（伝聞）', '〜ということだ'],
    contrast: '「によると」提示来源；「そうだ」标记转述。两者配合使用',
    recognition: { promptZh: '「天気予報によると、明日は雨＿＿」空格里最自然的是？',
      options: ['だそうです', 'です', 'でした', 'ですか'],
      answerIndex: 0, distractorReason: '「によると」要求句尾呼应传闻形式',
      explanationZh: '「〜によると〜そうだ」是固定搭配' },
    production: { promptJa: '天気予報の情報を「〜によると〜そうです」で伝えてください。',
      promptZh: '用「〜によると〜そうです」转述天气预报。',
      expected: ['によると'], acceptable: ['天気予報によると', '〜によると〜そうです'] },
    practice: { themeJa: 'ニュースや天気を伝える', starterJa: '今日のニュースや天気予報を、日本語で伝えてみましょう',
      starterZh: '试着用日语转述今天的新闻或天气', targetUse: '〜によると〜そうです' },
    vocabularyLinks: ['fi-jouhou', 'fi-tsutaeru'], unit: 'n3g-unit-6' }),
  g({ grammarId: 'n3g-youda', sourceRowId: 'n3row-39', pattern: '〜ようだ', reading: 'ようだ',
    meaningJa: '見た様子からそう判断する', explanationZh: '好像…。根据自己看到的情况做出的判断',
    formation: '動詞・い形容詞普通形／な形容詞＋な／名詞＋の ＋ようだ',
    usageScene: '看到对方脸色不好、房间没人时，说出自己的推测',
    nuance: '依据是自己直接观察到的。比「らしい」更主观、更有把握',
    register: 'both',
    examplesJa: ['彼は病気のようです。', '誰もいないようですね。'],
    examplesZh: ['他好像生病了。', '好像没有人在呢。'],
    furigana: 'かれは びょうきの ようです。',
    commonMistakesZh: '名詞接续要加「の」：「病気のようだ」。写成「病気ようだ」是错的',
    learnerFocus: '「ようだ」（我看到的推测）／「らしい」（听说）／「みたい」（口语）三者的依据不同',
    similarPatterns: ['〜らしい', '〜みたい', '〜そうだ'],
    contrast: '「ようだ」＝自己观察；「らしい」＝听来的；「みたい」＝ようだ的口语形',
    recognition: { promptZh: '看到同事脸色苍白，最自然的说法是？',
      options: ['具合が悪いようですね', '具合が悪いらしいですね', '具合が悪いそうですね', '具合が悪いだろうか'],
      answerIndex: 0, distractorReason: '自己亲眼看到的情况用「ようだ」，听说的用「らしい／そうだ」',
      explanationZh: '直接观察 →「ようだ」' },
    production: { promptJa: '見た様子から推測することを「〜ようです」で言ってください。',
      promptZh: '用「〜ようです」说出你根据所见做的推测。',
      expected: ['ようです'], acceptable: ['〜のようです', '〜ようだ'] },
    practice: { themeJa: '様子から推測して話す', starterJa: '外の様子を見て、天気がどうか「〜ようです」で言ってみましょう',
      starterZh: '看看外面，用「〜ようです」说说天气', targetUse: '〜ようです' },
    vocabularyLinks: ['fi-byouin', 'fi-genki'], unit: 'n3g-unit-6' }),
  g({ grammarId: 'n3g-rashii', sourceRowId: 'n3row-40', pattern: '〜らしい', reading: 'らしい',
    meaningJa: '聞いた話から推測する', explanationZh: '听说…、好像…。根据外部信息（传闻）做出的推测',
    formation: '動詞・い形容詞普通形／な形容詞・名詞（そのまま）＋らしい',
    usageScene: '把从同事、新闻听来的消息告诉别人，但不完全确定',
    nuance: '把责任放在消息来源上，自己不打包票。另有「男らしい」（有男子气概）的接尾词用法',
    register: 'both',
    examplesJa: ['彼は来月引っ越すらしいです。', 'あの店は今日休みらしいよ。'],
    examplesZh: ['听说他下个月要搬家。', '那家店今天好像休息。'],
    furigana: 'かれは らいげつ ひっこすらしいです。',
    commonMistakesZh: '接尾词用法「学生らしい学生」（像个学生样的学生）和推测用法不同，要靠上下文区分',
    learnerFocus: '不确定的消息用「らしい」比断定说「です」安全，是日本人常用的缓冲表达',
    similarPatterns: ['〜ようだ', '〜そうだ（伝聞）'],
    contrast: '「らしい」＝听来的推测；「そうだ」＝纯转述（不加自己判断）；「ようだ」＝自己观察',
    recognition: { promptZh: '「彼は来ないらしい」的信息来源是？',
      options: ['从别人那里听说的', '自己亲眼看到的', '自己的猜想', '他本人对我说的'],
      answerIndex: 0, distractorReason: '「らしい」表示根据外部信息推测',
      explanationZh: '「らしい」= 从传闻得到的推测' },
    production: { promptJa: '人から聞いた話を「〜らしいです」で伝えてください。',
      promptZh: '用「〜らしいです」转述你听来的消息。',
      expected: ['らしい'], acceptable: ['〜らしいです', '〜らしいよ'] },
    practice: { themeJa: '聞いた話を伝える', starterJa: '最近、人から聞いた話を「〜らしいです」で教えてください',
      starterZh: '用「〜らしいです」告诉我你最近听说的事', targetUse: '〜らしいです' },
    vocabularyLinks: ['fi-kiku', 'fi-jouhou'], unit: 'n3g-unit-6' }),
  g({ grammarId: 'n3g-mitai', sourceRowId: 'n3row-41', pattern: '〜みたい', reading: 'みたい',
    meaningJa: '〜ようだ（会話）／〜に似ている', explanationZh: '（口语）好像…、像…一样',
    formation: '動詞・い形容詞普通形／な形容詞・名詞（そのまま）＋みたい',
    usageScene: '和朋友聊天时的推测，或比喻某物像另一物',
    nuance: '「ようだ」的口语版。正式文书要用「ようだ」',
    register: 'spoken',
    examplesJa: ['このケーキはアイスみたいですね。', '彼、まだ来てないみたい。'],
    examplesZh: ['这个蛋糕像冰淇淋一样呢。', '他好像还没来。'],
    furigana: 'このケーキは アイスみたいですね。',
    commonMistakesZh: '名詞接续不加「の」：「アイスみたい」（○）／「アイスのみたい」（×）。和「ようだ」的接续不同',
    learnerFocus: '「〜のようだ」需要「の」，「〜みたい」不需要。这个接续差异是常见失分点',
    similarPatterns: ['〜ようだ', '〜っぽい'],
    contrast: '「みたい」口语；「ようだ」正式；「っぽい」更随意且多含负面（子どもっぽい）',
    recognition: { promptZh: '哪个接续正确？',
      options: ['子どもみたい', '子どものみたい', '子どもなみたい', '子どもだみたい'],
      answerIndex: 0, distractorReason: '「みたい」直接接名词，不加「の」',
      explanationZh: '名詞＋みたい（「の」不要）' },
    production: { promptJa: '何かを別のものにたとえて「〜みたい」で言ってください。',
      promptZh: '用「〜みたい」把某物比喻成另一物。',
      expected: ['みたい'], acceptable: ['〜みたいです', '〜みたい'] },
    practice: { themeJa: 'たとえを使って話す', starterJa: '今日の天気を何かにたとえると？「〜みたい」で言ってみましょう',
      starterZh: '今天的天气像什么？用「〜みたい」说说', targetUse: '〜みたい' },
    vocabularyLinks: ['fi-kore', 'fi-oishii'], unit: 'n3g-unit-6' }),
  g({ grammarId: 'n3g-teshimau', sourceRowId: 'n3row-42', pattern: '〜てしまう', reading: 'てしまう',
    meaningJa: '完全に終わる／後悔する', explanationZh: '①做完、彻底完成 ②不小心…了（含后悔）',
    formation: '動詞て形 ＋しまう（口語: 〜ちゃう）',
    usageScene: '说自己不小心做错了事，或强调一口气做完',
    nuance: '②的后悔用法更常见。语气上带「糟糕」的心情',
    register: 'both',
    examplesJa: ['財布を忘れてしまった。', '面白くて、一日で読んでしまいました。'],
    examplesZh: ['不小心把钱包忘了。', '太有意思了，一天就读完了。'],
    furigana: 'さいふを わすれて しまった。',
    commonMistakesZh: '写邮件道歉时要用「〜てしまいました」，不能用口语的「〜ちゃいました」',
    learnerFocus: '中文的「了」不区分「完成」和「懊悔」，日语用「てしまう」明确表达懊悔的心情',
    similarPatterns: ['〜ちゃう', '〜終わる'],
    contrast: '「〜終わる」只表示动作结束（中性）；「〜てしまう」多带感情（后悔或彻底）',
    recognition: { promptZh: '「宿題を忘れてしまいました」说话人的心情是？',
      options: ['后悔、觉得糟糕', '很高兴', '无所谓', '很自豪'],
      answerIndex: 0, distractorReason: '「てしまう」在这个语境下表示后悔',
      explanationZh: '「〜てしまう」常表示懊悔' },
    production: { promptJa: 'うっかりした失敗を「〜てしまいました」で言ってください。',
      promptZh: '用「〜てしまいました」说一次不小心的失误。',
      expected: ['てしまいました'], acceptable: ['〜てしまった'] },
    practice: { themeJa: '失敗を丁寧に報告する', starterJa: '仕事でミスをしたとき、どう報告しますか？',
      starterZh: '工作中出错时你怎么报告？', targetUse: '〜てしまいました' },
    vocabularyLinks: ['fi-wasureru', 'fi-komaru'], unit: 'n3g-unit-3' }),
  g({ grammarId: 'n3g-temiru', sourceRowId: 'n3row-43', pattern: '〜てみる', reading: 'てみる',
    meaningJa: '試しに〜する', explanationZh: '试着…、…看看。表示尝试性的动作',
    formation: '動詞て形 ＋みる',
    usageScene: '推荐别人尝试、或说明自己打算试一下',
    nuance: '含「不知道结果如何，先试试」的轻松语气。推荐时很常用',
    register: 'both',
    examplesJa: ['この料理を作ってみます。', '一度、着物を着てみたいです。'],
    examplesZh: ['我试着做这道菜。', '想试穿一次和服。'],
    furigana: 'このりょうりを つくって みます。',
    commonMistakesZh: '「〜てみたい」（想试试）是高频表达。「〜てみる」＋「たい」的组合要熟练',
    learnerFocus: '推荐别人时说「食べてみてください」比「食べてください」更柔和，是重要的语气差异',
    similarPatterns: ['〜てみたい', '〜ようとする'],
    contrast: '「てみる」是实际尝试；「ようとする」是试图但可能没成功',
    recognition: { promptZh: '推荐朋友尝试某道菜，最柔和的说法是？',
      options: ['食べてみてください', '食べてください', '食べなさい', '食べろ'],
      answerIndex: 0, distractorReason: '「てみて」含「试试看」的余地，语气最柔和',
      explanationZh: '「〜てみてください」= 请试试看' },
    production: { promptJa: '日本でやってみたいことを「〜てみたいです」で言ってください。',
      promptZh: '用「〜てみたいです」说说你在日本想尝试的事。',
      expected: ['てみたい'], acceptable: ['〜てみたいです', '〜てみます'] },
    practice: { themeJa: '日本でやってみたいことを話す', starterJa: '日本で何をやってみたいですか？',
      starterZh: '在日本你想尝试什么？', targetUse: '〜てみたいです' },
    vocabularyLinks: ['fi-tsukuru', 'fi-kyoumi'], unit: 'n3g-unit-3' }),
  g({ grammarId: 'n3g-tearu', sourceRowId: 'n3row-45', pattern: '〜てある', reading: 'てある',
    meaningJa: '誰かがして、その結果が残っている', explanationZh: '（有人做过后）…着。强调人为动作留下的状态',
    formation: '他動詞て形 ＋ある',
    usageScene: '说明房间、办公室里已经准备好的状态',
    nuance: '暗示「有人特意做了」。自然状态用「〜ている」',
    register: 'both',
    examplesJa: ['ドアが開けてあります。', '会議の資料は、もう印刷してあります。'],
    examplesZh: ['门（被人）开着。', '会议资料已经印好了。'],
    furigana: 'ドアが あけて あります。',
    commonMistakesZh: '「ドアが開いています」（自然开着）／「ドアが開けてあります」（有人特意开的）。他动词＋てある',
    learnerFocus: '自动词＋ている（状态）与他动词＋てある（人为结果）的对比，是N3的核心难点',
    similarPatterns: ['〜ている', '〜ておく'],
    contrast: '「〜てある」＝已做好的状态；「〜ておく」＝为将来先做；「〜ている」＝自然状态或进行中',
    recognition: { promptZh: '「窓が開けてあります」暗示什么？',
      options: ['有人特意打开了窗户', '窗户自己开了', '窗户坏了', '窗户关着'],
      answerIndex: 0, distractorReason: '他动词＋てある表示人为动作的结果状态',
      explanationZh: '「他動詞＋てある」= 有人做了并保持着' },
    production: { promptJa: '準備が終わっている状態を「〜てあります」で言ってください。',
      promptZh: '用「〜てあります」说准备已经做好的状态。',
      expected: ['てあります'], acceptable: ['〜てある', '印刷してあります'] },
    practice: { themeJa: '準備の状況を報告する', starterJa: '会議の準備は、どこまでしてありますか？',
      starterZh: '会议准备到什么程度了？', targetUse: '〜てあります' },
    vocabularyLinks: ['fi-junbi', 'fi-hairu'], unit: 'n3g-unit-3' }),
  g({ grammarId: 'n3g-teoku', sourceRowId: 'n3row-46', pattern: '〜ておく', reading: 'ておく',
    meaningJa: '前もって準備する／そのままにする', explanationZh: '①事先做好 ②就那样放着',
    formation: '動詞て形 ＋おく（口語: 〜とく）',
    usageScene: '分工准备、或说明有意保持某个状态',
    nuance: '①是最常用的准备义。②如「窓を開けておく」（就让窗户开着）',
    register: 'both',
    examplesJa: ['明日のために準備しておきます。', '資料はここに置いておきますね。'],
    examplesZh: ['我为明天先准备好。', '资料我就放在这里了。'],
    furigana: 'あしたの ために じゅんびして おきます。',
    commonMistakesZh: '和「〜てある」混淆。「ておく」重点是「为了以后而做」，「てある」重点是「已完成的状态」',
    learnerFocus: '职场高频。「確認しておきます」（我先确认好）是非常实用的回应',
    similarPatterns: ['〜てある', '〜とく'],
    contrast: '「ておく」＝事先做（动作视角）；「てある」＝已做好（状态视角）',
    recognition: { promptZh: '上司让你确认资料，你要说「我先确认好」，最自然的是？',
      options: ['確認しておきます', '確認してあります', '確認しています', '確認しました'],
      answerIndex: 0, distractorReason: '还没做、准备去做用「〜ておきます」',
      explanationZh: '「〜ておきます」= 我会先做好' },
    production: { promptJa: '明日のために準備することを「〜ておきます」で言ってください。',
      promptZh: '用「〜ておきます」说你为明天先准备的事。',
      expected: ['ておきます'], acceptable: ['〜ておく', '準備しておきます'] },
    practice: { themeJa: '仕事の準備を伝える', starterJa: '明日のために、何をしておきますか？',
      starterZh: '为了明天你会先准备什么？', targetUse: '〜ておきます' },
    vocabularyLinks: ['fi-junbi', 'fi-kakunin'], unit: 'n3g-unit-3' }),
  g({ grammarId: 'n3g-temoii', sourceRowId: 'n3row-47', pattern: '〜てもいい', reading: 'てもいい',
    meaningJa: '〜する許可がある', explanationZh: '可以…、…也行。表示许可或征求许可',
    formation: '動詞て形 ＋もいい（ですか）',
    usageScene: '向上司、店员请求许可：可以先走吗／可以试穿吗',
    nuance: '疑问形是请求许可；肯定形是给予许可。对上司更礼貌的是「〜てもよろしいでしょうか」',
    register: 'both',
    examplesJa: ['帰ってもいいですか。', 'ここに座ってもいいですよ。'],
    examplesZh: ['我可以回去了吗？', '你可以坐这里。'],
    furigana: 'かえっても いいですか。',
    commonMistakesZh: '对上司说「帰ってもいいですか」略随意。更礼貌的是「お先に失礼してもよろしいでしょうか」',
    learnerFocus: '请求许可的敬语阶梯：てもいい＜てもよろしい＜てもよろしいでしょうか。场合决定用哪个',
    similarPatterns: ['〜てもよろしいでしょうか', '〜させてください'],
    contrast: '「てもいいですか」＝一般请求；「させてください」＝更主动地请求让我做',
    recognition: { promptZh: '对社长请求先下班，最合适的是？',
      options: ['お先に失礼してもよろしいでしょうか', '帰ってもいい？', '帰るよ', '帰ってもいいですか'],
      answerIndex: 0, distractorReason: '对上位者需要更高的敬语层级',
      explanationZh: '对上司用「〜てもよろしいでしょうか」' },
    production: { promptJa: '店で試着の許可を「〜てもいいですか」で聞いてください。',
      promptZh: '用「〜てもいいですか」在店里请求试穿。',
      expected: ['てもいいですか'], acceptable: ['着てもいいですか', '試着してもいいですか'] },
    practice: { themeJa: '許可を求める練習', starterJa: '店やオフィスで、何か許可を求めてみましょう',
      starterZh: '试着在店里或办公室请求许可', targetUse: '〜てもいいですか' },
    vocabularyLinks: ['fi-kaeru', 'fi-ie'], unit: 'n3g-unit-7' }),
  g({ grammarId: 'n3g-nakutemoii', sourceRowId: 'n3row-48', pattern: '〜なくてもいい', reading: 'なくてもいい',
    meaningJa: '〜する必要がない', explanationZh: '不…也可以、不必…',
    formation: '動詞ない形（〜ない→〜なくて）＋もいい',
    usageScene: '告诉对方不必做某事，减轻对方负担',
    nuance: '比「〜する必要はありません」更柔和、口语化',
    register: 'both',
    examplesJa: ['無理に食べなくてもいいですよ。', '明日は早く来なくてもいいです。'],
    examplesZh: ['不用勉强吃也可以。', '明天不用早来。'],
    furigana: 'むりに たべなくても いいですよ。',
    commonMistakesZh: '变形是「食べない→食べなくて＋もいい」。写成「食べないでもいい」较少见',
    learnerFocus: '被别人客气时回答「気にしなくてもいいですよ」很实用，是体贴的表达',
    similarPatterns: ['〜必要はない', '〜なくて大丈夫'],
    contrast: '「なくてもいい」柔和许可；「必要はない」更事务性；「なくて大丈夫」最口语',
    recognition: { promptZh: '「来なくてもいいです」是什么意思？',
      options: ['不来也可以', '必须来', '不能来', '想来就来'],
      answerIndex: 0, distractorReason: '「なくてもいい」表示没有必要',
      explanationZh: '「〜なくてもいい」= 不…也没关系' },
    production: { promptJa: '相手に「無理しなくていい」ことを「〜なくてもいいです」で伝えてください。',
      promptZh: '用「〜なくてもいいです」告诉对方不用勉强。',
      expected: ['なくてもいい'], acceptable: ['〜なくてもいいです', '無理しなくてもいいです'] },
    practice: { themeJa: '相手の負担を減らす言い方', starterJa: '相手に「しなくていい」と伝えたい場面はありますか？',
      starterZh: '有想告诉对方「不用做」的场合吗？', targetUse: '〜なくてもいいです' },
    vocabularyLinks: ['fi-muri', 'fi-taberu'], unit: 'n3g-unit-7' }),
  g({ grammarId: 'n3g-nakerebanaranai', sourceRowId: 'n3row-49', pattern: '〜なければならない', reading: 'なければならない',
    meaningJa: '義務がある（しなければいけない）', explanationZh: '必须…。表示规则或情况要求的义务',
    formation: '動詞ない形（〜ない→〜なければ）＋ならない',
    usageScene: '说明规定、期限、不得不做的事',
    nuance: '书面且客观（规则如此）。口语常缩成「〜なきゃ」',
    register: 'written',
    examplesJa: ['明日までに提出しなければなりません。', '外国人は在留カードを持たなければならない。'],
    examplesZh: ['必须在明天之前提交。', '外国人必须携带在留卡。'],
    furigana: 'あしたまでに ていしゅつ しなければ なりません。',
    commonMistakesZh: '变形长且容易错：「する→しなければ」「来る→来なければ」「食べる→食べなければ」',
    learnerFocus: '口语缩约「〜なきゃ」「〜なくちゃ」听力上必须能还原。书面写全形',
    similarPatterns: ['〜なくてはいけない', '〜べきだ'],
    contrast: '「なければならない」偏规则（客观）；「なくてはいけない」偏个别情况；「べきだ」是主观建议',
    recognition: { promptZh: '「〜なきゃ」是哪个的缩约形？',
      options: ['〜なければ', '〜ながら', '〜なさい', '〜ないで'],
      answerIndex: 0, distractorReason: '「なきゃ」是「なければ」的口语缩约',
      explanationZh: '「なければ」→「なきゃ」' },
    production: { promptJa: '今週しなければならないことを言ってください。',
      promptZh: '说说这周你必须做的事。',
      expected: ['なければなりません'], acceptable: ['〜なければならない', '〜なきゃいけない'] },
    practice: { themeJa: '締め切りのある仕事を話す', starterJa: '今週、何をしなければなりませんか？',
      starterZh: '这周你必须做什么？', targetUse: '〜なければなりません' },
    vocabularyLinks: ['fi-shigoto', 'fi-hitsuyou'], unit: 'n3g-unit-7' }),
  g({ grammarId: 'n3g-nakutewaikenai', sourceRowId: 'n3row-50', pattern: '〜なくてはいけない', reading: 'なくてはいけない',
    meaningJa: '（この場面では）〜する必要がある', explanationZh: '必须…（针对具体情况的义务）',
    formation: '動詞ない形（〜ない→〜なくて）＋はいけない',
    usageScene: '说明具体场合下不得不做的事：得吃药、得去一趟',
    nuance: '比「なければならない」更贴近个别情况和口语。缩约形は「〜なくちゃ」',
    register: 'both',
    examplesJa: ['薬を飲まなくてはいけません。', '今日は早く帰らなくてはいけない。'],
    examplesZh: ['必须吃药。', '今天得早点回去。'],
    furigana: 'くすりを のまなくては いけません。',
    commonMistakesZh: '「なくては」→口语「なくちゃ」。「なければ」→「なきゃ」。两组缩约形不要混',
    learnerFocus: '两个「必须」的差别：规则性用「なければならない」，眼前的事用「なくてはいけない」',
    similarPatterns: ['〜なければならない', '〜なくちゃ'],
    contrast: '客观规则 vs 眼前情况。日常会话中「なくちゃ」出现频率最高',
    recognition: { promptZh: '「薬を飲まなくちゃ」的完整形是？',
      options: ['薬を飲まなくてはいけない', '薬を飲んでもいい', '薬を飲まないでいい', '薬を飲みたい'],
      answerIndex: 0, distractorReason: '「なくちゃ」是「なくては（いけない）」的缩约',
      explanationZh: '「なくては」→「なくちゃ」' },
    production: { promptJa: '今日しなくてはいけないことを言ってください。',
      promptZh: '说说你今天必须做的事。',
      expected: ['なくてはいけません'], acceptable: ['〜なくてはいけない', '〜なくちゃ'] },
    practice: { themeJa: '今日の予定の中の「必須」を話す', starterJa: '今日、絶対にしなくてはいけないことは何ですか？',
      starterZh: '今天你非做不可的是什么？', targetUse: '〜なくてはいけません' },
    vocabularyLinks: ['fi-kusuri', 'fi-kaeru'], unit: 'n3g-unit-7' }),
  g({ grammarId: 'n3g-deshou', sourceRowId: 'n3row-51', pattern: '〜でしょう', reading: 'でしょう',
    meaningJa: '推量／相手への確認', explanationZh: '①大概…吧（推测）②…对吧？（向对方确认）',
    formation: '動詞・い形容詞普通形／な形容詞・名詞（そのまま）＋でしょう',
    usageScene: '天气预报的推测、或向对方确认共识',
    nuance: '①降调是推测；②升调是确认。语调改变意思',
    register: 'both',
    examplesJa: ['明日は雨が降るでしょう。', '日本の夏は暑いでしょう？'],
    examplesZh: ['明天大概会下雨吧。', '日本的夏天很热吧？'],
    furigana: 'あしたは あめが ふるでしょう。',
    commonMistakesZh: '对上司说「わかるでしょう？」有强迫同意的感觉，容易失礼。确认要用「〜ですよね」',
    learnerFocus: '「でしょう」的两个用法靠语调区分，听力中要注意句尾升降',
    similarPatterns: ['〜だろう', '〜かもしれない', '〜ですよね'],
    contrast: '「でしょう」把握较大；「かもしれない」把握小；「だろう」是「でしょう」的普通形',
    recognition: { promptZh: '「明日は晴れるでしょう」最可能出自哪里？',
      options: ['天气预报', '命令', '道歉', '感谢'],
      answerIndex: 0, distractorReason: '「でしょう」的推测用法是天气预报的定型表达',
      explanationZh: '天气预报固定用「〜でしょう」' },
    production: { promptJa: '明日の天気を「〜でしょう」で予想してください。',
      promptZh: '用「〜でしょう」预测明天的天气。',
      expected: ['でしょう'], acceptable: ['雨が降るでしょう', '晴れるでしょう'] },
    practice: { themeJa: '天気や状況を予想する', starterJa: '明日の天気はどうなるでしょうか？予想してみましょう',
      starterZh: '明天天气会怎样？预测一下', targetUse: '〜でしょう' },
    vocabularyLinks: ['fi-samui', 'fi-atsui'], unit: 'n3g-unit-6' }),
  g({ grammarId: 'n3g-darou', sourceRowId: 'n3row-52', pattern: '〜だろう', reading: 'だろう',
    meaningJa: '〜でしょうの普通形（推量）', explanationZh: '（普通体）应该…吧。「でしょう」的普通形',
    formation: '動詞・い形容詞普通形／な形容詞・名詞（そのまま）＋だろう',
    usageScene: '自言自语、和朋友说话、写文章（论说文）',
    nuance: '对上司使用会失礼。文章中表示笔者的推测则很常见',
    register: 'both',
    examplesJa: ['彼はもうすぐ来るだろう。', 'この問題は難しいだろう。'],
    examplesZh: ['他应该快来了吧。', '这个问题应该很难吧。'],
    furigana: 'かれは もうすぐ くるだろう。',
    commonMistakesZh: '对上司说「来るだろう」很失礼。敬体要用「来るでしょう」',
    learnerFocus: '普通体和敬体的选择反映人际关系，日语中比中文严格得多',
    similarPatterns: ['〜でしょう', '〜と思う'],
    contrast: '「だろう」＝普通体推测；「でしょう」＝敬体；「と思う」＝明确表示是自己的意见',
    recognition: { promptZh: '对上司报告推测时应该用？',
      options: ['〜でしょう', '〜だろう', '〜だろうな', '〜だろ'],
      answerIndex: 0, distractorReason: '对上位者需要敬体',
      explanationZh: '敬体「でしょう」/ 普通体「だろう」' },
    production: { promptJa: '友達との会話で推測を「〜だろう」で言ってください。',
      promptZh: '用「〜だろう」在和朋友的对话中做推测。',
      expected: ['だろう'], acceptable: ['〜だろう', '来るだろう'] },
    practice: { themeJa: '普通体で推測を言う', starterJa: '友達と話すとき、推測をどう言いますか？',
      starterZh: '和朋友说话时你怎么表达推测？', targetUse: '〜だろう' },
    vocabularyLinks: ['fi-kuru', 'fi-muzukashii'], unit: 'n3g-unit-6' }),
  g({ grammarId: 'n3g-kamoshirenai', sourceRowId: 'n3row-53', pattern: '〜かもしれない', reading: 'かもしれない',
    meaningJa: '可能性がある（確信は低い）', explanationZh: '也许…、可能…。可能性存在但把握不大',
    formation: '動詞・い形容詞普通形／な形容詞・名詞（そのまま）＋かもしれない',
    usageScene: '不确定的预测、留有余地的发言',
    nuance: '把握程度低于「でしょう」。敬体是「かもしれません」',
    register: 'both',
    examplesJa: ['彼は病気かもしれない。', '道が混んでいるかもしれませんから、早めに出ましょう。'],
    examplesZh: ['他可能生病了。', '路上可能堵车，我们早点出发吧。'],
    furigana: 'かれは びょうき かもしれない。',
    commonMistakesZh: '名詞・な形容詞直接接：「病気かもしれない」（○）／「病気だかもしれない」（×）',
    learnerFocus: '日本的会话喜欢留余地，「かもしれません」比断定说法更受欢迎，是重要的沟通策略',
    similarPatterns: ['〜でしょう', '〜と思う'],
    contrast: '把握度：「〜です」＞「でしょう」＞「かもしれない」',
    recognition: { promptZh: '把握程度最低的是？',
      options: ['雨が降るかもしれません', '雨が降ります', '雨が降るでしょう', '雨が降るはずです'],
      answerIndex: 0, distractorReason: '「かもしれない」表示可能性存在但不确定',
      explanationZh: '「かもしれない」是把握最低的推测' },
    production: { promptJa: '確信がないことを「〜かもしれません」で言ってください。',
      promptZh: '用「〜かもしれません」说一件你不太确定的事。',
      expected: ['かもしれ'], acceptable: ['〜かもしれません', '〜かもしれない'] },
    practice: { themeJa: '断定を避けて話す', starterJa: '確信がないことを、日本語でどう言いますか？',
      starterZh: '不确定的事你用日语怎么说？', targetUse: '〜かもしれません' },
    vocabularyLinks: ['fi-byouin', 'fi-tabun'], unit: 'n3g-unit-6' }),
  g({ grammarId: 'n3g-nasai', sourceRowId: 'n3row-54', pattern: '〜なさい', reading: 'なさい',
    meaningJa: '目上から目下への穏やかな命令', explanationZh: '（长辈对晚辈）请…、快…。柔和的命令',
    formation: '動詞ます形 ＋なさい',
    usageScene: '父母对孩子、老师对学生、考试题目的指示文',
    nuance: '比命令形（食べろ）柔和，但仍是上对下。同事之间不能用',
    register: 'both',
    examplesJa: ['早く寝なさい。', '次の質問に答えなさい。'],
    examplesZh: ['快去睡觉。', '请回答下面的问题。'],
    furigana: 'はやく ねなさい。',
    commonMistakesZh: '对同事或上司使用非常失礼。想请对方做事要用「〜てください」',
    learnerFocus: '考试卷上的「〜なさい」（答えなさい）经常出现，读懂即可，自己几乎不用',
    similarPatterns: ['〜てください', '命令形'],
    contrast: '上下关系：命令形＞なさい＞てください＞ていただけませんか',
    recognition: { promptZh: '「〜なさい」适合谁对谁说？',
      options: ['父母对孩子', '部下对上司', '同事之间', '客户对店员'],
      answerIndex: 0, distractorReason: '「なさい」是上对下的命令，平级或对上会失礼',
      explanationZh: '「なさい」限于长辈对晚辈' },
    production: { promptJa: '試験の指示文「答えなさい」のような文を作ってください。',
      promptZh: '造一个像考试指示那样的「〜なさい」句子。',
      expected: ['なさい'], acceptable: ['書きなさい', '答えなさい'] },
    practice: { themeJa: '指示文の読み取り', starterJa: '試験や教科書で「〜なさい」を見たことがありますか？',
      starterZh: '你在考试或课本上见过「〜なさい」吗？', targetUse: '〜なさい（読解）' },
    vocabularyLinks: ['fi-neru', 'fi-mondai'], unit: 'n3g-unit-7' }),
  g({ grammarId: 'n3g-tsumori', sourceRowId: 'n3row-56', pattern: '〜つもり', reading: 'つもり',
    meaningJa: 'そうする意志・予定がある', explanationZh: '打算…。表示说话人的意图',
    formation: '動詞辞書形／ない形 ＋つもりだ',
    usageScene: '说明自己的计划：打算减肥、打算换工作',
    nuance: '比「〜ようと思う」更坚定，但比「〜ことにした」少了「已经定了」的感觉',
    register: 'both',
    examplesJa: ['明日からダイエットするつもりです。', '今年は国に帰らないつもりです。'],
    examplesZh: ['我打算从明天开始减肥。', '今年打算不回国。'],
    furigana: 'あしたから ダイエットする つもりです。',
    commonMistakesZh: '第三人称用「〜つもりらしい」。直接说「彼は行くつもりです」有断定别人内心的感觉',
    learnerFocus: '「つもり」是自己的意志。别人的打算要加「らしい」「ようだ」等推测',
    similarPatterns: ['〜ようと思う', '〜ことにする', '〜予定だ'],
    contrast: '「予定」＝日程已定（客观）；「つもり」＝个人意志；「ことにした」＝刚做的决定',
    recognition: { promptZh: '哪个最强调「已经安排好的日程」？',
      options: ['来週帰国する予定です', '来週帰国するつもりです', '来週帰国しようと思います', '来週帰国したいです'],
      answerIndex: 0, distractorReason: '「予定」表示客观已定的安排',
      explanationZh: '「予定」＝客观日程；「つもり」＝个人意志' },
    production: { promptJa: '今年やるつもりのことを「〜つもりです」で言ってください。',
      promptZh: '用「〜つもりです」说说你今年打算做的事。',
      expected: ['つもり'], acceptable: ['〜つもりです', '〜つもりだ'] },
    practice: { themeJa: '今年の計画を話す', starterJa: '今年、何をするつもりですか？',
      starterZh: '今年你打算做什么？', targetUse: '〜つもりです' },
    vocabularyLinks: ['fi-yotei', 'fi-kimeru'], unit: 'n3g-unit-4' }),
  g({ grammarId: 'n3g-naide', sourceRowId: 'n3row-58', pattern: '〜ないで', reading: 'ないで',
    meaningJa: '〜しない状態で（別のことをする）', explanationZh: '不…就…、没有…（做了别的）',
    formation: '動詞ない形 ＋で',
    usageScene: '说明省略了某个步骤：没吃早饭就去了学校',
    nuance: '「〜ずに」是书面形式，意思相同',
    register: 'both',
    examplesJa: ['朝ごはんを食べないで学校に行きました。', '何も言わないで帰ってしまった。'],
    examplesZh: ['没吃早饭就去学校了。', '什么都没说就回去了。'],
    furigana: 'あさごはんを たべないで がっこうに いきました。',
    commonMistakesZh: '和「〜なくて」（原因）混淆。「食べなくて」是「因为没吃」，「食べないで」是「没吃就…」',
    learnerFocus: '「ないで」＝附带状况；「なくて」＝原因。中文都可以说「没…就」，日语必须区分',
    similarPatterns: ['〜ずに', '〜なくて'],
    contrast: '「ないで」＝不做A而做B；「なくて」＝因为没做A所以B',
    recognition: { promptZh: '「傘を持たないで出かけた」是什么意思？',
      options: ['没带伞就出门了', '因为没有伞所以困扰', '带着伞出门了', '不想带伞'],
      answerIndex: 0, distractorReason: '「ないで」表示在不做某事的状态下做了另一件事',
      explanationZh: '「〜ないで〜する」= 不…就…' },
    production: { promptJa: '何かをしないで出かけた経験を「〜ないで」で言ってください。',
      promptZh: '用「〜ないで」说一次省略了某事就出门的经历。',
      expected: ['ないで'], acceptable: ['食べないで', '持たないで'] },
    practice: { themeJa: '朝の習慣を話す', starterJa: '朝ごはんを食べないで出かけることがありますか？',
      starterZh: '你有不吃早饭就出门的时候吗？', targetUse: '〜ないで' },
    vocabularyLinks: ['fi-taberu', 'fi-deru'], unit: 'n3g-unit-5' }),
];
