// Phase 3P-4: N3文法の完成draft（監督指示準拠）。
// 「完成draft」= 説明Ja/Zh・接続・用法場面・ニュアンス・文体・例文2〜3（日中）・ふりがな・
// 誤用注意・学習者フォーカス・類似/対比文型・認識問題・産出問題・会話練習・語彙リンク・
// 復習キー・route・Unit・出典 がすべて揃ったもののみ。
// 揃わない候補は追加せず、n3-grammar-source-audit.json に理由付きで残す。
// 出典: Excel「N3の文法120例文集」（120行→独立文型76・完全重複6・N2重なり38）。
// N2重なり分はレベル配置が人間判断のため、ここには入れない（awaiting_level_decision）。

/** 文体。会話専用の縮約形（〜ちゃう等）を書き言葉で使わせないために持つ。 */
export type GrammarRegister = 'spoken' | 'written' | 'both';

export interface N3GrammarDraft {
  grammarId: string;            // n3g-<連番でない安定キー>
  sourceRowId: string;          // n3-grammar-source-audit.json への追跡
  pattern: string;
  reading: string;              // 文型の読み（かな）
  level: 'N3';
  meaningJa: string;
  explanationZh: string;        // 中文の説明（一語訳で済ませない）
  formation: string;            // 接続（動詞辞書形＋等）
  usageScene: string;           // どんな場面で使うか（中文）
  nuance: string;               // ニュアンス・含み（中文）
  register: GrammarRegister;
  examplesJa: string[];         // 2〜3例
  examplesZh: string[];         // 同数
  furigana: string;             // 第1例文の読み補助
  commonMistakesZh: string;     // 中国語母語者の典型的誤用
  learnerFocus: string;         // この文型で中国語母語者が特に注意する点（中文）
  similarPatterns: string[];    // 類似文型
  contrast: string;             // 類似文型との違い（中文）
  recognition: {                // 意味・用法の選択問題
    promptZh: string; options: string[]; answerIndex: number;
    distractorReason: string; explanationZh: string;
  };
  production: {                 // 産出（穴埋め・場面応答）
    promptJa: string; promptZh: string; expected: string[]; acceptable: string[];
  };
  practice: {                   // 会話・作文練習
    themeJa: string; starterJa: string; starterZh: string; targetUse: string;
  };
  vocabularyLinks: string[];    // 既存140語のitemId（誤答時の復習導線）
  reviewKey: string;
  route: 'n3-grammar';
  unit: string;                 // n3g-unit-1 〜（用法系統でまとめる）
  reviewStatus: 'draft';
  humanReviewed: false;
  approved: false;
}

const g = (p: Omit<N3GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey'> & { reviewKey?: string }): N3GrammarDraft =>
  ({ level: 'N3', route: 'n3-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, ...p });

/** バッチ1: 判断・決定・状態（unit-1）＋会話縮約形（unit-2）の19文型。 */
export const N3_GRAMMAR_DRAFTS_BATCH1: N3GrammarDraft[] = [
  g({ grammarId: 'n3g-bakaridenaku', sourceRowId: 'n3row-4', pattern: '〜ばかりでなく', reading: 'ばかりでなく',
    meaningJa: '〜だけでなく、さらに…も', explanationZh: '不仅…而且…。前项已经成立，再追加程度更高或范围更广的后项',
    formation: '名詞／動詞普通形／い形容詞普通形／な形容詞＋である ＋ばかりでなく',
    usageScene: '介绍某人的能力、某物的优点时，想强调「不止这一点」',
    nuance: '比「〜だけでなく」更书面、更正式。后项常带「も」呼应',
    register: 'written',
    examplesJa: ['彼は英語ばかりでなく、中国語も話せます。', 'この店は安いばかりでなく、味もいいです。'],
    examplesZh: ['他不仅会英语，还会中文。', '这家店不仅便宜，味道也好。'],
    furigana: 'かれは えいごばかりでなく、ちゅうごくごも はなせます。',
    commonMistakesZh: '误把「ばかり」当成「只有」而理解成否定。这里的「ばかりでなく」是「不仅」，后面一定有追加内容',
    learnerFocus: '后半句要用「も」呼应，写成「〜ばかりでなく、〜も」才自然。只写前半句会让人觉得话没说完',
    similarPatterns: ['〜だけでなく', '〜のみならず'],
    contrast: '「だけでなく」口语书面都可用；「ばかりでなく」偏书面；「のみならず」最正式',
    recognition: { promptZh: '「この部屋は広いばかりでなく、＿＿」后面最自然的是？',
      options: ['駅にも近いです', '狭いです', '広くないです', '高いですか'],
      answerIndex: 0, distractorReason: '「ばかりでなく」要求后项是追加的优点，不能是否定或矛盾内容',
      explanationZh: '前项「広い」是优点，后项要追加另一个优点并用「も」呼应' },
    production: { promptJa: 'あなたの町のいいところを「〜ばかりでなく」で2つ言ってください。',
      promptZh: '用「〜ばかりでなく」说说你所在城市的两个优点。',
      expected: ['ばかりでなく'], acceptable: ['〜ばかりでなく、〜も'] },
    practice: { themeJa: '住んでいる町の良さを二つ挙げる', starterJa: 'あなたの町は、どんなところがいいですか？',
      starterZh: '你住的地方哪里好？', targetUse: '〜ばかりでなく、〜も' },
    vocabularyLinks: ['fi-benri', 'fi-yasui'], unit: 'n3g-unit-1' }),
  g({ grammarId: 'n3g-kke', sourceRowId: 'n3row-7', pattern: '〜っけ', reading: 'っけ',
    meaningJa: '忘れたことを相手に確認する', explanationZh: '（口语）好像是…来着？用于确认自己记不清的事',
    formation: '普通形＋っけ（名詞・な形容詞は「だっけ」）',
    usageScene: '想不起约定的时间、对方的名字、明天是否放假时，向熟人确认',
    nuance: '亲密语气。对上司或客户使用会显得随便，正式场合用「〜でしたでしょうか」',
    register: 'spoken',
    examplesJa: ['明日って休みだっけ？', '会議は何時からだっけ？'],
    examplesZh: ['明天是休息日来着？', '会议是几点开始来着？'],
    furigana: 'あしたって やすみだっけ？',
    commonMistakesZh: '对上司说「明日休みだっけ？」很失礼。要用「明日はお休みでしたでしょうか」',
    learnerFocus: '中文的「来着」没有敬语区分，日语的「っけ」严格限于熟人之间。判断对象很重要',
    similarPatterns: ['〜でしたよね', '〜だったよね'],
    contrast: '「〜よね」是寻求同意（我记得是这样吧）；「〜っけ」是自己真的忘了',
    recognition: { promptZh: '「〜っけ」适合对谁使用？',
      options: ['关系好的同事', '第一次见的客户', '公司社长', '面试官'],
      answerIndex: 0, distractorReason: '「っけ」是随意的口语，对上位者和外部人员失礼',
      explanationZh: '「っけ」限于熟人之间的随意确认' },
    production: { promptJa: '友達に、待ち合わせの時間を忘れたので「〜っけ」で聞いてください。',
      promptZh: '忘了和朋友约的时间，用「〜っけ」问一下。',
      expected: ['っけ'], acceptable: ['何時だっけ', '何時からだっけ'] },
    practice: { themeJa: '忘れたことを友達に確認する', starterJa: '友達との約束、何時でしたか？「〜っけ」で聞いてみましょう',
      starterZh: '和朋友约的几点？用「〜っけ」问问看', targetUse: '〜だっけ／〜たっけ' },
    vocabularyLinks: ['fi-nanji', 'fi-yakusoku'], unit: 'n3g-unit-2' }),
  g({ grammarId: 'n3g-furiwosuru', sourceRowId: 'n3row-8', pattern: '〜ふりをする', reading: 'ふりをする',
    meaningJa: '実際はそうでないのに、そう見せる', explanationZh: '假装…。实际并非如此，却做出那样的样子',
    formation: '動詞普通形／い形容詞／な形容詞＋な／名詞＋の ＋ふりをする',
    usageScene: '描述别人（或自己）装作不知道、装睡、装忙的行为',
    nuance: '含轻微的批评或自嘲。中性描述可用「〜ように見せる」',
    register: 'both',
    examplesJa: ['彼は知らないふりをした。', '電車で寝たふりをして、席を譲りませんでした。'],
    examplesZh: ['他装作不知道。', '在电车上装睡，没有让座。'],
    furigana: 'かれは しらないふりを した。',
    commonMistakesZh: '「ふり」前面的动词多用「〜ない形」或「〜た形」。「知るふり」不自然，要说「知っているふり」',
    learnerFocus: '中文「装作不知道」对应日语「知らないふりをする」（否定形）。直译成「知るふり」会错',
    similarPatterns: ['〜ように見せる', '〜つもりだ'],
    contrast: '「ふりをする」是明确的伪装；「ように見せる」较中性；「つもり」是自以为',
    recognition: { promptZh: '「装作不知道」用日语说是？',
      options: ['知らないふりをする', '知るふりをする', '知りたいふりをする', '知られるふりをする'],
      answerIndex: 0, distractorReason: '伪装的内容是「不知道」这个状态，所以用否定形',
      explanationZh: '「〜ないふりをする」= 装作不…' },
    production: { promptJa: '寝ていないのに寝ているように見せることを「〜ふりをする」で言ってください。',
      promptZh: '用「〜ふりをする」表达装睡。',
      expected: ['ふりをする'], acceptable: ['寝たふりをする', '寝ているふりをする'] },
    practice: { themeJa: 'ふりをした経験を話す', starterJa: '何かのふりをしたことがありますか？',
      starterZh: '你有过装作某样子的经历吗？', targetUse: '〜ふりをした' },
    vocabularyLinks: ['fi-wakaru', 'fi-neru'], unit: 'n3g-unit-1' }),
  g({ grammarId: 'n3g-gachi', sourceRowId: 'n3row-9', pattern: '〜がち', reading: 'がち',
    meaningJa: 'そうなる傾向が強い（多くは良くないこと）', explanationZh: '容易…、往往…（多用于不好的倾向）',
    formation: '動詞ます形／名詞 ＋がち',
    usageScene: '说明自己或他人的坏习惯、身体容易出的状况、季节性的倾向',
    nuance: '几乎只用于消极内容。「幸せになりがち」这种正面用法不自然',
    register: 'both',
    examplesJa: ['冬は風邪をひきがちです。', '忙しいと、朝ごはんを抜きがちになります。'],
    examplesZh: ['冬天容易感冒。', '一忙就往往不吃早饭。'],
    furigana: 'ふゆは かぜを ひきがちです。',
    commonMistakesZh: '不能用于好事。「日本語が上手になりがち」是错的，要说「上手になりやすい」',
    learnerFocus: '中文「容易」褒贬都能用，日语「がち」几乎专用于负面。正面用「〜やすい」',
    similarPatterns: ['〜やすい', '〜ぎみ'],
    contrast: '「やすい」中性（褒贬都可）；「がち」偏负面的频率倾向；「ぎみ」是轻微的状态倾向',
    recognition: { promptZh: '哪个句子用「がち」不自然？',
      options: ['この時期は成績が上がりがちだ', '雨の日は遅刻しがちだ', '疲れると忘れがちだ', '冬は風邪をひきがちだ'],
      answerIndex: 0, distractorReason: '成绩上升是好事，「がち」不用于正面内容',
      explanationZh: '「がち」用于消极倾向。正面内容用「〜やすい」' },
    production: { promptJa: '自分の良くない習慣を「〜がち」で言ってください。',
      promptZh: '用「〜がち」说说你的一个坏习惯。',
      expected: ['がち'], acceptable: ['〜がちです', '〜がちになります'] },
    practice: { themeJa: '忙しいときの悪い習慣を話す', starterJa: '忙しいとき、つい何をしがちですか？',
      starterZh: '忙的时候你往往会怎样？', targetUse: '〜がちです' },
    vocabularyLinks: ['fi-isogashii', 'fi-wasureru'], unit: 'n3g-unit-1' }),
  g({ grammarId: 'n3g-gasuru', sourceRowId: 'n3row-12', pattern: '〜がする', reading: 'がする',
    meaningJa: '音・におい・味・感じを感じ取る', explanationZh: '感觉到（声音、气味、味道等）。用于五官捕捉到的信息',
    formation: '名詞（音・におい・味・感じ・気）＋がする',
    usageScene: '闻到味道、听到声音、有某种预感时',
    nuance: '不是主动去闻去听，而是「自然感觉到」。所以助词是「が」不是「を」',
    register: 'both',
    examplesJa: ['いいにおいがする。', '外で変な音がしました。'],
    examplesZh: ['有股好闻的味道。', '外面有奇怪的声音。'],
    furigana: 'いいにおいが する。',
    commonMistakesZh: '误用「においをする」。感知类名词一律用「が」：音がする・味がする・気がする',
    learnerFocus: '中文「闻到味道」是及物结构，日语却是「においがする」（自动词结构）。助词是最大的难点',
    similarPatterns: ['〜が聞こえる', '〜が見える'],
    contrast: '「音がする」是「有声音」；「音が聞こえる」是「（我）能听见」，视角不同',
    recognition: { promptZh: '正确的说法是？',
      options: ['いいにおいがします', 'いいにおいをします', 'いいにおいにします', 'いいにおいでします'],
      answerIndex: 0, distractorReason: '感知类名词固定搭配助词「が」',
      explanationZh: '「におい／音／味／気＋がする」是固定形式' },
    production: { promptJa: '台所からいいにおいがすることを「〜がする」で言ってください。',
      promptZh: '用「〜がする」说厨房飘来香味。',
      expected: ['がする'], acceptable: ['においがします', 'いいにおいがします'] },
    practice: { themeJa: '家で感じるにおいや音を話す', starterJa: '今、何かにおいや音がしますか？',
      starterZh: '现在有什么气味或声音吗？', targetUse: '〜がします' },
    vocabularyLinks: ['fi-kiku', 'fi-kanjiru'], unit: 'n3g-unit-3' }),
  g({ grammarId: 'n3g-koto-meirei', sourceRowId: 'n3row-19', pattern: '〜こと（指示）', reading: 'こと',
    meaningJa: '規則として「〜しなさい／してはいけない」を示す', explanationZh: '（书面规定）必须…／不得…。用于规章、告示、通知',
    formation: '動詞辞書形／動詞ない形 ＋こと',
    usageScene: '公司规定、学校通知、宿舍规则等书面告示',
    nuance: '没有主语、语气强硬、事务性。口头对人使用会很生硬',
    register: 'written',
    examplesJa: ['ここに入らないこと。', '提出物は金曜日までに出すこと。'],
    examplesZh: ['不得入内。', '提交物须在周五之前交出。'],
    furigana: 'ここに はいらないこと。',
    commonMistakesZh: '这是告示专用。对同事说「早く出すこと」会像在训人，口语要说「出してください」',
    learnerFocus: '看到日本公司的通知、宿舍规则时经常出现。读懂比自己写更重要',
    similarPatterns: ['〜ないでください', '〜なければならない'],
    contrast: '「〜てください」是请求；「〜こと」是规定；「〜なければならない」是说明义务',
    recognition: { promptZh: '「ゴミは分けて出すこと。」这句话最可能出现在哪里？',
      options: ['公寓的告示牌', '朋友的短信', '恋人的情话', '面试的自我介绍'],
      answerIndex: 0, distractorReason: '「〜こと」是事务性的书面规定，不用于私人对话',
      explanationZh: '规章告示的固定表达' },
    production: { promptJa: '「ここでタバコを吸ってはいけない」を掲示の文体「〜こと」で書いてください。',
      promptZh: '把「这里禁止吸烟」写成告示体的「〜こと」。',
      expected: ['こと'], acceptable: ['ここでタバコを吸わないこと'] },
    practice: { themeJa: '職場や住まいの掲示を読む', starterJa: '会社や家で「〜こと」と書かれた掲示を見たことがありますか？',
      starterZh: '你在公司或住处见过「〜こと」的告示吗？', targetUse: '〜こと（掲示）' },
    vocabularyLinks: ['fi-deru', 'fi-hairu'], unit: 'n3g-unit-4' }),
  g({ grammarId: 'n3g-kotogaaru', sourceRowId: 'n3row-20', pattern: '〜ことがある', reading: 'ことがある',
    meaningJa: 'ときどきそうすることがある', explanationZh: '有时会…。表示偶尔发生的事',
    formation: '動詞辞書形／ない形 ＋ことがある',
    usageScene: '介绍自己的生活习惯中「偶尔发生」的部分',
    nuance: '强调频率不高。「〜たことがある」（经验）形式不同、意思也不同',
    register: 'both',
    examplesJa: ['夜遅くまで起きていることがある。', '休みの日は、一日中家にいることがあります。'],
    examplesZh: ['有时会熬到很晚。', '休息日有时一整天待在家。'],
    furigana: 'よるおそくまで おきていることが ある。',
    commonMistakesZh: '和「〜たことがある」（曾经有过的经验）混淆。辞书形＝偶尔会做，た形＝有过经验',
    learnerFocus: '「行くことがある」（有时去）与「行ったことがある」（去过）差一个字，意思完全不同',
    similarPatterns: ['〜たことがある', '〜ときどき〜する'],
    contrast: '辞书形＋ことがある＝频率；た形＋ことがある＝经验',
    recognition: { promptZh: '「日本語で電話することがあります」是什么意思？',
      options: ['有时会用日语打电话', '曾经用日语打过电话', '必须用日语打电话', '不能用日语打电话'],
      answerIndex: 0, distractorReason: '辞书形＋ことがある表示频率，不是经验',
      explanationZh: '「辞書形＋ことがある」= 有时会做' },
    production: { promptJa: 'ときどきすることを「〜ことがあります」で言ってください。',
      promptZh: '用「〜ことがあります」说你偶尔做的事。',
      expected: ['ことがあります'], acceptable: ['〜ことがある'] },
    practice: { themeJa: 'ときどきする習慣を話す', starterJa: '休みの日、ときどきすることはありますか？',
      starterZh: '休息日你偶尔会做什么？', targetUse: '〜ことがあります' },
    vocabularyLinks: ['fi-okiru', 'fi-ie'], unit: 'n3g-unit-4' }),
  g({ grammarId: 'n3g-kotonisuru', sourceRowId: 'n3row-21', pattern: '〜ことにする', reading: 'ことにする',
    meaningJa: '自分の意志で決める', explanationZh: '（自己）决定…。主语主动做出的决定',
    formation: '動詞辞書形／ない形 ＋ことにする',
    usageScene: '宣布自己的决定：戒烟、开始运动、换工作',
    nuance: '「〜ことにした」＝已经决定了；「〜ことにしている」＝当成习惯坚持',
    register: 'both',
    examplesJa: ['毎日運動することにした。', '夜10時以降は食べないことにしています。'],
    examplesZh: ['我决定每天运动。', '我规定自己晚上10点以后不吃东西。'],
    furigana: 'まいにち うんどうすることに した。',
    commonMistakesZh: '和「〜ことになる」（被决定／自然而然定下来）混淆。自己决定用「する」，被决定用「なる」',
    learnerFocus: '日语用自动词「なる」淡化个人意志，是文化习惯。谁做的决定决定了用哪个',
    similarPatterns: ['〜ことになる', '〜つもりだ'],
    contrast: '「ことにする」＝我决定；「ことになる」＝（外部原因）定下来了；「つもり」＝打算（还没定死）',
    recognition: { promptZh: '「来月から大阪に転勤することになりました」暗示什么？',
      options: ['是公司的决定，不是自己选的', '自己主动申请调职', '还在考虑中', '拒绝了调职'],
      answerIndex: 0, distractorReason: '「ことになる」表示由外部（公司）决定',
      explanationZh: '「ことになる」隐含「不是我自己决定的」' },
    production: { promptJa: '最近自分で決めたことを「〜ことにしました」で言ってください。',
      promptZh: '用「〜ことにしました」说说你最近的一个决定。',
      expected: ['ことにしました'], acceptable: ['〜ことにした', '〜ことにしています'] },
    practice: { themeJa: '自分で決めたことを話す', starterJa: '最近、自分で何かを決めましたか？',
      starterZh: '最近你自己做了什么决定？', targetUse: '〜ことにしました' },
    vocabularyLinks: ['fi-kimeru', 'fi-shuukan'], unit: 'n3g-unit-4' }),
  g({ grammarId: 'n3g-kotoninaru', sourceRowId: 'n3row-22', pattern: '〜ことになる', reading: 'ことになる',
    meaningJa: '（自分以外の力で）そう決まる', explanationZh: '（被）决定…。由组织、他人或情势定下来',
    formation: '動詞辞書形／ない形 ＋ことになる',
    usageScene: '向别人报告公司的人事安排、会议决定、规则变更',
    nuance: '即使实际是自己争取的，用「ことになる」显得谦虚，是日本职场的常用表达',
    register: 'both',
    examplesJa: ['来月から大阪に転勤することになりました。', '会議は来週に延期することになりました。'],
    examplesZh: ['下个月起要调职去大阪了。', '会议决定延期到下周。'],
    furigana: 'らいげつから おおさかに てんきんすることに なりました。',
    commonMistakesZh: '结婚、跳槽等个人喜事在日本也常说「〜ことになりました」，这是谦虚，不是被迫',
    learnerFocus: '中文习惯说「我决定了」，日语职场更常用「〜ことになりました」淡化自我主张',
    similarPatterns: ['〜ことにする', '〜そうだ'],
    contrast: '「ことにする」＝我决定；「ことになる」＝定下来了（谦虚或他决）',
    recognition: { promptZh: '向公司同事报告自己要结婚，最自然的是？',
      options: ['結婚することになりました', '結婚することにします', '結婚するつもりです', '結婚しろ'],
      answerIndex: 0, distractorReason: '报告个人喜事时日语习惯用「ことになりました」显得谦虚',
      explanationZh: '「ことになりました」是职场报告的定型表达' },
    production: { promptJa: '会社で決まったことを「〜ことになりました」で報告してください。',
      promptZh: '用「〜ことになりました」报告公司定下来的事。',
      expected: ['ことになりました'], acceptable: ['〜ことになった'] },
    practice: { themeJa: '決まったことを報告する', starterJa: '最近、何か決まったことはありますか？報告してみましょう',
      starterZh: '最近有什么定下来的事？试着报告一下', targetUse: '〜ことになりました' },
    vocabularyLinks: ['fi-kimaru', 'fi-shigoto'], unit: 'n3g-unit-4' }),
  g({ grammarId: 'n3g-mama', sourceRowId: 'n3row-24', pattern: '〜まま', reading: 'まま',
    meaningJa: 'ある状態が変わらずに続く', explanationZh: '保持…的状态（不做本该做的改变）',
    formation: '動詞た形／ない形／名詞＋の／い形容詞／な形容詞＋な ＋まま',
    usageScene: '说明「开着灯就睡了」「穿着鞋进屋」等状态没有恢复的情形',
    nuance: '常含「本来应该关掉/脱掉却没有」的轻微负面语气',
    register: 'both',
    examplesJa: ['電気をつけたまま寝てしまった。', '靴を履いたまま入らないでください。'],
    examplesZh: ['开着灯就睡着了。', '请不要穿着鞋进来。'],
    furigana: 'でんきを つけたまま ねてしまった。',
    commonMistakesZh: '「まま」前面的动词用た形表示「已经做了并保持」。用辞书形（つけるまま）不自然',
    learnerFocus: '日本进屋要脱鞋，「靴を履いたまま」是生活中常听到的提醒，务必掌握',
    similarPatterns: ['〜ながら', '〜きり'],
    contrast: '「まま」是状态持续（不动）；「ながら」是两个动作同时进行（都在动）',
    recognition: { promptZh: '「窓を開けたまま出かけた」是什么意思？',
      options: ['窗户开着就出门了', '关上窗户出门了', '出门后打开了窗户', '没有出门'],
      answerIndex: 0, distractorReason: '「た形＋まま」表示做了动作后状态一直保持',
      explanationZh: '「〜たまま」= 保持…的状态' },
    production: { promptJa: 'うっかりそのままにしてしまった経験を「〜まま」で言ってください。',
      promptZh: '用「〜まま」说一次忘记恢复原状的经历。',
      expected: ['まま'], acceptable: ['〜たまま', 'つけたまま'] },
    practice: { themeJa: 'うっかりそのままにした経験を話す', starterJa: 'エアコンや電気をつけたまま出かけたことがありますか？',
      starterZh: '你有过开着空调或灯就出门的经历吗？', targetUse: '〜たまま' },
    vocabularyLinks: ['fi-neru', 'fi-hairu'], unit: 'n3g-unit-3' }),
  g({ grammarId: 'n3g-youtosuru', sourceRowId: 'n3row-25', pattern: '〜ようとする', reading: 'ようとする',
    meaningJa: '〜しようと試みる／ちょうど〜する直前', explanationZh: '试图…／正要…的时候',
    formation: '動詞意向形 ＋とする',
    usageScene: '描述「刚要出门电话响了」这类事件的时间点，或努力尝试但没成功',
    nuance: '「〜ようとしたとき」几乎固定用于「正要…的时候发生了别的事」',
    register: 'both',
    examplesJa: ['ドアを開けようとしたとき、電話が鳴った。', '何度も直そうとしましたが、できませんでした。'],
    examplesZh: ['正要开门时电话响了。', '试着修了好几次，但没修好。'],
    furigana: 'ドアを あけようとしたとき、でんわが なった。',
    commonMistakesZh: '需要动词的意向形（開けよう・しよう・来よう）。用辞书形「開けるとする」意思完全不同',
    learnerFocus: '意向形变化是难点：一类動詞「書く→書こう」、二类「開ける→開けよう」、三类「する→しよう」',
    similarPatterns: ['〜つもりだ', '〜ところだ'],
    contrast: '「ようとする」是正要做/尝试；「つもり」是打算；「ところだ」强调时间点',
    recognition: { promptZh: '「出かけようとしたとき、雨が降ってきた」是什么时候下的雨？',
      options: ['正要出门的那一刻', '出门很久以后', '出门之前一小时', '完全没下雨'],
      answerIndex: 0, distractorReason: '「ようとしたとき」指动作即将发生的瞬间',
      explanationZh: '「〜ようとしたとき」= 正要…的时候' },
    production: { promptJa: '「出かける直前に何かが起きた」を「〜ようとしたとき」で言ってください。',
      promptZh: '用「〜ようとしたとき」说「正要出门时发生了某事」。',
      expected: ['ようとした'], acceptable: ['出かけようとしたとき'] },
    practice: { themeJa: 'タイミングの悪かった出来事を話す', starterJa: '何かをしようとしたときに、邪魔が入った経験はありますか？',
      starterZh: '有过正要做某事时被打断的经历吗？', targetUse: '〜ようとしたとき' },
    vocabularyLinks: ['fi-deru', 'fi-renraku'], unit: 'n3g-unit-3' }),
  g({ grammarId: 'n3g-younisuru', sourceRowId: 'n3row-26', pattern: '〜ようにする', reading: 'ようにする',
    meaningJa: '努力して習慣にする', explanationZh: '尽量做到…、努力养成…的习惯',
    formation: '動詞辞書形／ない形 ＋ようにする',
    usageScene: '说明自己为健康、学习而努力保持的习惯',
    nuance: '「〜ようにしている」＝一直在努力保持；「〜ようになった」＝变得能够（结果）',
    register: 'both',
    examplesJa: ['早く寝るようにしている。', '毎日運動するようにしています。'],
    examplesZh: ['我尽量早睡。', '我尽量每天运动。'],
    furigana: 'はやく ねるようにしている。',
    commonMistakesZh: '和「〜ようになる」（变得会…）混淆。「する」＝自己努力，「なる」＝能力或状态的变化',
    learnerFocus: '「日本語が話せるようになりました」（变得会说）与「話すようにしています」（尽量说）意思不同',
    similarPatterns: ['〜ようになる', '〜ことにしている'],
    contrast: '「ようにする」＝努力；「ようになる」＝变化的结果；「ことにしている」＝自己定的规矩（更强）',
    recognition: { promptZh: '「野菜を食べるようにしています」是什么意思？',
      options: ['我尽量吃蔬菜', '我变得会吃蔬菜了', '我讨厌蔬菜', '我不吃蔬菜'],
      answerIndex: 0, distractorReason: '「ようにする」表示自己努力保持的习惯',
      explanationZh: '「〜ようにしている」= 尽量做到…' },
    production: { promptJa: '健康のために気をつけていることを「〜ようにしています」で言ってください。',
      promptZh: '用「〜ようにしています」说说你为健康做的努力。',
      expected: ['ようにしています'], acceptable: ['〜ようにする', '〜ようにしている'] },
    practice: { themeJa: '健康のための習慣を話す', starterJa: '健康のために、何かするようにしていますか？',
      starterZh: '为了健康你尽量做什么？', targetUse: '〜ようにしています' },
    vocabularyLinks: ['fi-neru', 'fi-ganbaru'], unit: 'n3g-unit-4' }),
  g({ grammarId: 'n3g-youniiu', sourceRowId: 'n3row-27', pattern: '〜ように言う', reading: 'ようにいう',
    meaningJa: '「〜しなさい」と間接的に伝える', explanationZh: '（转述）叫…做…、要求…做…',
    formation: '動詞辞書形／ない形 ＋ように言う（伝える・頼む）',
    usageScene: '转达医生、上司、老师的指示给第三方',
    nuance: '常以被动形「〜ように言われた」出现，表示自己被要求',
    register: 'both',
    examplesJa: ['医者に酒をやめるように言われた。', '部長に会議室を予約するように言われました。'],
    examplesZh: ['医生叫我戒酒。', '部长让我预约会议室。'],
    furigana: 'いしゃに さけを やめるように いわれた。',
    commonMistakesZh: '不能直接引用命令。「医者は『酒をやめろ』と言った」太生硬，转述要用「〜ように言われた」',
    learnerFocus: '日语转述指示时避免直接引用命令形，这是重要的语用习惯',
    similarPatterns: ['〜と言われた', '〜てほしいと言われた'],
    contrast: '「〜と言われた」是直接引用内容；「〜ように言われた」是转述指示',
    recognition: { promptZh: '「先生に宿題を出すように言われました」是谁要求谁？',
      options: ['老师要求我', '我要求老师', '我要求同学', '没有人要求'],
      answerIndex: 0, distractorReason: '「〜に〜ように言われた」中「に」标记要求方',
      explanationZh: '被动形「言われた」＝我被（に的对象）要求' },
    production: { promptJa: '医者や上司に何か指示された経験を「〜ように言われました」で言ってください。',
      promptZh: '用「〜ように言われました」说一次被医生或上司要求的经历。',
      expected: ['ように言われました'], acceptable: ['〜ように言われた'] },
    practice: { themeJa: '受けた指示を伝える', starterJa: '最近、誰かに何かするように言われましたか？',
      starterZh: '最近有人要求你做什么吗？', targetUse: '〜ように言われました' },
    vocabularyLinks: ['fi-tsutaeru', 'fi-byouin'], unit: 'n3g-unit-4' }),
  g({ grammarId: 'n3g-temo', sourceRowId: 'n3row-31', pattern: '〜ても', reading: 'ても',
    meaningJa: 'たとえ〜という条件でも結果は変わらない', explanationZh: '即使…也…。前项条件不影响后项结果',
    formation: '動詞て形／い形容詞（〜くて）／な形容詞・名詞（〜でも）＋も',
    usageScene: '强调自己的坚持、或说明规则不因情况改变',
    nuance: '常与「たとえ」「どんなに」搭配加强语气',
    register: 'both',
    examplesJa: ['寒くても、ジョギングを続けます。', 'どんなに忙しくても、家族と話す時間は作ります。'],
    examplesZh: ['即使冷也继续跑步。', '再忙也会挤出和家人说话的时间。'],
    furigana: 'さむくても、ジョギングを つづけます。',
    commonMistakesZh: 'い形容詞是「寒くても」（くて＋も），不是「寒いても」。变形是最常见的错误点',
    learnerFocus: '中文「即使…也」一个结构，日语要按词性变形：動詞て形／形容詞くて／名詞でも',
    similarPatterns: ['〜のに', '〜たとしても'],
    contrast: '「ても」是假设的让步；「のに」是对已发生事实的意外或不满',
    recognition: { promptZh: '「雨が降っても行きます」是什么意思？',
      options: ['即使下雨也去', '因为下雨所以不去', '下雨了很遗憾', '希望不要下雨'],
      answerIndex: 0, distractorReason: '「ても」表示让步，不是原因',
      explanationZh: '「〜ても」= 即使…也…' },
    production: { promptJa: '「疲れていても続けること」を「〜ても」で言ってください。',
      promptZh: '用「〜ても」说「即使累也会坚持的事」。',
      expected: ['ても'], acceptable: ['疲れていても', '忙しくても'] },
    practice: { themeJa: '何があっても続けたいことを話す', starterJa: 'どんなに忙しくても続けたいことはありますか？',
      starterZh: '再忙也想坚持的事是什么？', targetUse: '〜ても' },
    vocabularyLinks: ['fi-samui', 'fi-tsuzukeru'], unit: 'n3g-unit-5' }),
  g({ grammarId: 'n3g-chadame', sourceRowId: 'n3row-32', pattern: '〜ちゃだめ', reading: 'ちゃだめ',
    meaningJa: '〜してはいけない（会話）', explanationZh: '（口语）不能…、不许…。「〜てはだめ」的缩约形',
    formation: '動詞て形の「て」→「ちゃ」（で→じゃ）＋だめ',
    usageScene: '朋友、家人、对孩子的日常提醒',
    nuance: '亲近而随意。对上司、客户使用会失礼',
    register: 'spoken',
    examplesJa: ['ここでタバコを吸っちゃだめだよ。', '遊んでばかりいちゃだめだよ。'],
    examplesZh: ['这里不能抽烟哦。', '不能光顾着玩哦。'],
    furigana: 'ここで タバコを すっちゃだめだよ。',
    commonMistakesZh: '「読んで」类（で结尾）变成「読んじゃだめ」。清浊要跟着て形走',
    learnerFocus: '正式场合要用「〜てはいけません」。缩约形只用于熟人之间',
    similarPatterns: ['〜てはいけない', '〜ないで'],
    contrast: '「〜てはいけません」正式；「〜ちゃだめ」口语随意；「〜ないで」是请求不要做',
    recognition: { promptZh: '「飲んで」的「〜ちゃだめ」形式是？',
      options: ['飲んじゃだめ', '飲んちゃだめ', '飲みちゃだめ', '飲むちゃだめ'],
      answerIndex: 0, distractorReason: 'て形以「で」结尾时缩约为「じゃ」',
      explanationZh: '「〜で」→「〜じゃ」、「〜て」→「〜ちゃ」' },
    production: { promptJa: '友達に「ここで写真を撮ってはいけない」を口語で言ってください。',
      promptZh: '用口语对朋友说「这里不能拍照」。',
      expected: ['ちゃだめ'], acceptable: ['撮っちゃだめ', '撮っちゃだめだよ'] },
    practice: { themeJa: '友達へのカジュアルな注意', starterJa: '友達に注意したいことを、口語で言ってみましょう',
      starterZh: '试着用口语提醒朋友一件事', targetUse: '〜ちゃだめ' },
    vocabularyLinks: ['fi-tsukau', 'fi-tanoshii'], unit: 'n3g-unit-2' }),
  g({ grammarId: 'n3g-chau', sourceRowId: 'n3row-33', pattern: '〜ちゃう', reading: 'ちゃう',
    meaningJa: '〜てしまう（完了・後悔）の会話形', explanationZh: '（口语）…掉了、…完了。「〜てしまう」的缩约形',
    formation: '動詞て形の「て」→「ちゃう」（で→じゃう）',
    usageScene: '和朋友说自己不小心做了什么、或吃完喝完',
    nuance: '多含「糟糕、不小心」的懊恼，也可表示「干脆做完」',
    register: 'spoken',
    examplesJa: ['宿題を忘れちゃった。', 'ケーキ、全部食べちゃった。'],
    examplesZh: ['作业忘带了。', '蛋糕全吃光了。'],
    furigana: 'しゅくだいを わすれちゃった。',
    commonMistakesZh: '工作邮件里不能用。要写「忘れてしまいました」。缩约形是口语专用',
    learnerFocus: '日本人日常会话大量使用缩约形，听力上必须能还原成「〜てしまう」',
    similarPatterns: ['〜てしまう', '〜ちゃだめ'],
    contrast: '「〜てしまう」标准形（书面可用）；「〜ちゃう」口语缩约',
    recognition: { promptZh: '「食べちゃった」的标准形是？',
      options: ['食べてしまった', '食べておいた', '食べている', '食べたい'],
      answerIndex: 0, distractorReason: '「ちゃう」是「てしまう」的缩约',
      explanationZh: '「〜てしまった」→「〜ちゃった」' },
    production: { promptJa: 'うっかりしたことを「〜ちゃった」で言ってください。',
      promptZh: '用「〜ちゃった」说一件不小心做的事。',
      expected: ['ちゃった'], acceptable: ['忘れちゃった', '食べちゃった'] },
    practice: { themeJa: '失敗を友達に話す', starterJa: '今日、うっかりしたことはありますか？口語で話しましょう',
      starterZh: '今天有不小心做错的事吗？用口语说说', targetUse: '〜ちゃった' },
    vocabularyLinks: ['fi-wasureru', 'fi-taberu'], unit: 'n3g-unit-2' }),
  g({ grammarId: 'n3g-toku', sourceRowId: 'n3row-34', pattern: '〜とく', reading: 'とく',
    meaningJa: '〜ておく（準備しておく）の会話形', explanationZh: '（口语）先…好、事先…。「〜ておく」的缩约形',
    formation: '動詞て形の「て」→「とく」（で→どく）',
    usageScene: '和家人朋友分工准备：我先买好、我先订好',
    nuance: '含「为将来做准备」的意思，语气轻松',
    register: 'spoken',
    examplesJa: ['水を買っとくね。', '席、予約しとくよ。'],
    examplesZh: ['我先把水买好。', '座位我先订好。'],
    furigana: 'みずを かっとくね。',
    commonMistakesZh: '和「〜ちゃう」（做完了）混淆。「とく」是「为以后先做好」，「ちゃう」是「做掉了」',
    learnerFocus: '职场邮件写「準備しておきます」，对同事口头说「準備しとくね」，场合区分很重要',
    similarPatterns: ['〜ておく', '〜てある'],
    contrast: '「〜ておく」标准形；「〜とく」口语；「〜てある」强调状态已完成',
    recognition: { promptZh: '「買っとく」的意思是？',
      options: ['事先买好（为以后）', '买错了', '不买', '正在买'],
      answerIndex: 0, distractorReason: '「〜ておく」表示事先做好准备',
      explanationZh: '「〜とく」=「〜ておく」= 先做好' },
    production: { promptJa: '友達に「先に予約しておく」と口語で言ってください。',
      promptZh: '用口语对朋友说「我先订好」。',
      expected: ['とく'], acceptable: ['予約しとく', '予約しとくね'] },
    practice: { themeJa: '友達との準備の分担を話す', starterJa: '友達との集まりで、何をしておきますか？口語で言ってみましょう',
      starterZh: '和朋友聚会你先准备什么？用口语说', targetUse: '〜とく' },
    vocabularyLinks: ['fi-kau', 'fi-yoyaku'], unit: 'n3g-unit-2' }),
  g({ grammarId: 'n3g-tatte', sourceRowId: 'n3row-35', pattern: '〜たって', reading: 'たって',
    meaningJa: '〜ても（会話）', explanationZh: '（口语）即使…也…。「〜ても」的口语形',
    formation: '動詞た形／い形容詞（〜く）＋たって',
    usageScene: '和朋友强调「就算…我也不…」',
    nuance: '带点执拗或不服气的语气，比「ても」更随意',
    register: 'spoken',
    examplesJa: ['安くたって、買わない。', 'どんなに謝ったって、許さないよ。'],
    examplesZh: ['再便宜我也不买。', '你再怎么道歉我也不原谅。'],
    furigana: 'やすくたって、かわない。',
    commonMistakesZh: 'い形容詞是「安くたって」（く＋たって）。写成「安いたって」是错的',
    learnerFocus: '正式场合和写作要用「〜ても」。「たって」是熟人之间的口语',
    similarPatterns: ['〜ても', '〜ところで'],
    contrast: '「ても」通用；「たって」口语且带情绪；「ところで」表示徒劳（书面）',
    recognition: { promptZh: '「行ったって、誰もいないよ」是什么意思？',
      options: ['就算去了也没人', '去了就有人', '不想去', '一起去吧'],
      answerIndex: 0, distractorReason: '「たって」＝即使…也',
      explanationZh: '「〜たって」是「〜ても」的口语形' },
    production: { promptJa: '「安くても買わない」を口語の「〜たって」で言ってください。',
      promptZh: '把「再便宜也不买」改成口语的「〜たって」。',
      expected: ['たって'], acceptable: ['安くたって買わない'] },
    practice: { themeJa: '譲れないこだわりを話す', starterJa: 'どんなに勧められても買わない物はありますか？',
      starterZh: '有什么是别人再推荐你也不买的？', targetUse: '〜たって' },
    vocabularyLinks: ['fi-yasui', 'fi-kau'], unit: 'n3g-unit-2' }),
  g({ grammarId: 'n3g-nagara', sourceRowId: 'n3row-36', pattern: '〜ながら', reading: 'ながら',
    meaningJa: '二つの動作を同時にする', explanationZh: '一边…一边…。同一个人同时进行两个动作',
    formation: '動詞ます形 ＋ながら',
    usageScene: '说明自己边听音乐边学习、边走边打电话等日常场景',
    nuance: '主要动作是后半句。「音楽を聞きながら勉強する」重点在学习',
    register: 'both',
    examplesJa: ['音楽を聞きながら勉強します。', '歩きながらスマホを見るのは危ないです。'],
    examplesZh: ['一边听音乐一边学习。', '边走路边看手机很危险。'],
    furigana: 'おんがくを ききながら べんきょうします。',
    commonMistakesZh: '两个动作必须是同一个人做的。「母が料理しながら、私が食べる」是错的',
    learnerFocus: '中文「一边…一边」两个主语也能用，日语「ながら」必须同一主语。这是关键差异',
    similarPatterns: ['〜まま', '〜つつ'],
    contrast: '「ながら」两个动作都在进行；「まま」是状态保持不变；「つつ」是书面语',
    recognition: { promptZh: '哪个句子用「ながら」正确？',
      options: ['歌を歌いながら料理します', '弟が寝ながら私が勉強します', '雨が降りながら出かけます', '本ながら読みます'],
      answerIndex: 0, distractorReason: '「ながら」要求两个动作的主语相同，且接ます形',
      explanationZh: '同一个人的两个同时动作 + ます形＋ながら' },
    production: { promptJa: '普段、同時にしていることを「〜ながら」で言ってください。',
      promptZh: '用「〜ながら」说你平时同时做的两件事。',
      expected: ['ながら'], acceptable: ['聞きながら', '見ながら'] },
    practice: { themeJa: '「ながら」でしていることを話す', starterJa: '何かをしながら勉強することがありますか？',
      starterZh: '你会一边做别的事一边学习吗？', targetUse: '〜ながら' },
    vocabularyLinks: ['fi-kiku', 'fi-benkyo'], unit: 'n3g-unit-3' }),
];

import { N3_GRAMMAR_DRAFTS_BATCH2 } from './n3GrammarDrafts2';
import { N3_GRAMMAR_DRAFTS_BATCH3 } from './n3GrammarDrafts3';
import { N3_GRAMMAR_DRAFTS_BATCH4 } from './n3GrammarDrafts4';

/** 現在の完成draft（全バッチ集約）。追加は「全field完備」のバッチのみ。 */
export const N3_GRAMMAR_DRAFTS: N3GrammarDraft[] = [
  ...N3_GRAMMAR_DRAFTS_BATCH1,
  ...N3_GRAMMAR_DRAFTS_BATCH2,
  ...N3_GRAMMAR_DRAFTS_BATCH3,
  ...N3_GRAMMAR_DRAFTS_BATCH4,
];

export const n3GrammarDraftById = (id: string): N3GrammarDraft | undefined =>
  N3_GRAMMAR_DRAFTS.find((d) => d.grammarId === id);
