// Phase 3P-4: N3文法完成draft バッチ3（理由・逆接・変化・程度 の19文型）。全draft。
import type { N3GrammarDraft } from './n3GrammarDrafts';

const g = (p: Omit<N3GrammarDraft, 'level' | 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey'> & { reviewKey?: string }): N3GrammarDraft =>
  ({ level: 'N3', route: 'n3-grammar', reviewStatus: 'draft', humanReviewed: false,
     approved: false, reviewKey: p.grammarId, ...p });

export const N3_GRAMMAR_DRAFTS_BATCH3: N3GrammarDraft[] = [
  g({ grammarId: 'n3g-you-ishi', sourceRowId: 'n3row-55', pattern: '〜よう（意志形）', reading: 'よう',
    meaningJa: '〜しよう（意志・誘い）', explanationZh: '（意志形）…吧、要…。表示自己的意志或邀请对方',
    formation: 'Ⅰ類: 書く→書こう ／ Ⅱ類: 見る→見よう ／ Ⅲ類: する→しよう・来る→来よう',
    matchKeys: ['よう', 'こう', 'ごう', 'そう', 'とう', 'ろう', 'おう'],
    usageScene: '邀请朋友、自言自语下决心、和「〜と思う」组合表达打算',
    nuance: '对上司不能用意志形邀请，要用「〜ませんか」',
    register: 'spoken',
    examplesJa: ['来週、みんなでご飯を食べに行こう。', '今年こそ、日本語を頑張ろうと思います。'],
    examplesZh: ['下周大家一起去吃饭吧。', '今年一定要努力学日语。'],
    furigana: 'らいしゅう、みんなで ごはんを たべに いこう。',
    commonMistakesZh: '三类动词的变形要记牢：「する」→「しよう」、「来る」→「来（こ）よう」。这两个最容易错',
    learnerFocus: '「〜ようと思う」（打算）是意志形最实用的用法，比单独用意志形更常见',
    similarPatterns: ['〜ませんか', '〜つもりだ'],
    contrast: '「〜よう」随意（对朋友）；「〜ませんか」礼貌邀请；「つもり」是说明打算',
    recognition: { promptZh: '「する」的意志形是？',
      options: ['しよう', 'すよう', 'するよう', 'さよう'],
      answerIndex: 0, distractorReason: '三类动词「する」的意志形是「しよう」',
      explanationZh: '「する」→「しよう」、「来る」→「来よう」' },
    production: { promptJa: '友達を映画に誘う言い方を意志形で言ってください。',
      promptZh: '用意志形邀请朋友看电影。',
      expected: ['よう'], acceptable: ['見よう', '行こう'] },
    practice: { themeJa: '友達を誘う', starterJa: '週末、友達を何かに誘ってみましょう',
      starterZh: '试着周末邀请朋友做点什么', targetUse: '〜よう' },
    vocabularyLinks: ['fi-miru', 'fi-tomodachi'], unit: 'n3g-unit-4' }),
  g({ grammarId: 'n3g-kotogadekiru', sourceRowId: 'n3row-57', pattern: '〜ことができる', reading: 'ことができる',
    meaningJa: '〜する能力・可能性がある', explanationZh: '能…、可以…。表示能力或条件允许',
    formation: '動詞辞書形 ＋ことができる',
    usageScene: '正式说明自己的能力、或说明设施允许做什么',
    nuance: '比可能形（話せる）更正式、书面。口语多用可能形',
    register: 'written',
    examplesJa: ['ここでは日本語を学ぶことができます。', 'カードで払うことができますか。'],
    examplesZh: ['在这里可以学日语。', '可以刷卡支付吗？'],
    furigana: 'ここでは にほんごを まなぶことが できます。',
    commonMistakesZh: '「話せる」和「話すことができる」意思相同，但简历、说明书等书面场合用后者更正式',
    learnerFocus: '面试说自己的能力时，「〜ことができます」比「〜られます」显得更郑重',
    similarPatterns: ['可能形（〜られる）', '〜が可能だ'],
    contrast: '可能形＝口语简洁；「ことができる」＝书面正式；「が可能だ」＝最正式（公告）',
    recognition: { promptZh: '写简历时说「会说日语」，最正式的是？',
      options: ['日本語を話すことができます', '日本語が話せます', '日本語話せる', '日本語しゃべれる'],
      answerIndex: 0, distractorReason: '书面正式场合用「〜ことができます」',
      explanationZh: '正式书面 →「〜ことができます」' },
    production: { promptJa: '自分ができることを「〜ことができます」で言ってください。',
      promptZh: '用「〜ことができます」说说你会做的事。',
      expected: ['ことができ'], acceptable: ['〜ことができます'] },
    practice: { themeJa: '面接で能力を説明する', starterJa: '面接で「私は〜ことができます」と言ってみましょう',
      starterZh: '试着在面试中说「私は〜ことができます」', targetUse: '〜ことができます' },
    vocabularyLinks: ['fi-hanasu', 'fi-shigoto'], unit: 'n3g-unit-7' }),
  g({ grammarId: 'n3g-noni', sourceRowId: 'n3row-59', pattern: '〜のに', reading: 'のに',
    meaningJa: '〜だが、期待と違う（不満・意外）', explanationZh: '明明…却…。表示与预期相反，含不满或意外',
    formation: '動詞・い形容詞普通形／な形容詞＋な／名詞＋な ＋のに',
    usageScene: '抱怨天气、别人的行为与预想不同时',
    nuance: '带感情（不满・惋惜）。纯客观的转折用「〜が」「〜けど」',
    register: 'both',
    examplesJa: ['早く家を出たのに、電車が遅れて遅刻しました。', 'たくさん勉強したのに、合格できませんでした。'],
    examplesZh: ['明明早早出了门，却因电车晚点迟到了。', '明明学了很多，却没能合格。'],
    furigana: 'はやく いえを でたのに、でんしゃが おくれて ちこく しました。',
    commonMistakesZh: '名詞・な形容詞接续要加「な」：「静かなのに」「学生なのに」',
    learnerFocus: '「のに」带情绪，用在客观陈述里会让人觉得你在抱怨。中立转折用「が」',
    similarPatterns: ['〜けど', '〜ても'],
    contrast: '「のに」＝已发生的事实＋不满；「ても」＝假设的让步；「けど」＝中立转折',
    recognition: { promptZh: '「約束したのに、来なかった」说话人的心情是？',
      options: ['不满、失望', '高兴、很开心', '无所谓、不在意', '感谢、很感激'],
      answerIndex: 0, distractorReason: '「のに」表示与预期相反并带负面情绪',
      explanationZh: '「〜のに」常含不满' },
    production: { promptJa: '期待と違ったことを「〜のに」で言ってください。',
      promptZh: '用「〜のに」说一件不如预期的事。',
      expected: ['のに'], acceptable: ['〜のに', '勉強したのに'] },
    practice: { themeJa: '期待外れの経験を話す', starterJa: '頑張ったのに、うまくいかなかったことはありますか？',
      starterZh: '有过明明努力了却不顺利的事吗？', targetUse: '〜のに' },
    vocabularyLinks: ['fi-samui', 'fi-ganbaru'], unit: 'n3g-unit-5' }),
  g({ grammarId: 'n3g-node', sourceRowId: 'n3row-60', pattern: '〜ので', reading: 'ので',
    meaningJa: '（丁寧・客観的な）理由', explanationZh: '因为…（较客气、客观的理由）',
    formation: '動詞・い形容詞普通形／な形容詞＋な／名詞＋な ＋ので',
    usageScene: '向上司请假、向客户说明原因',
    nuance: '比「から」柔和客观，请假、道歉时更常用',
    register: 'both',
    examplesJa: ['子どもの熱が下がらないので、今日は在宅にします。', '電車が遅れたので、遅刻しました。'],
    examplesZh: ['因为孩子的烧没退，今天我在家办公。', '因为电车晚点，我迟到了。'],
    furigana: 'こどもの ねつが さがらないので、きょうは ざいたくに します。',
    commonMistakesZh: '名詞・な形容詞接「な」：「病気なので」。写成「病気ので」是错的',
    learnerFocus: '向上司说明理由时「ので」比「から」礼貌，是职场必备的语感差异',
    similarPatterns: ['〜から', '〜ため'],
    contrast: '「ので」＝客观柔和；「から」＝主观直接；「ため」＝书面正式',
    recognition: { promptZh: '向上司请假，最合适的是？',
      options: ['熱があるので、休ませていただきます', '熱があるから休む', '熱があるので休め', '熱がある'],
      answerIndex: 0, distractorReason: '对上司需要「ので」＋敬语表达',
      explanationZh: '「ので」＋敬语 = 礼貌的理由说明' },
    production: { promptJa: '会社を休む理由を「〜ので」で伝えてください。',
      promptZh: '用「〜ので」说明请假的理由。',
      expected: ['ので'], acceptable: ['〜ので休みます', '風邪をひいたので'] },
    practice: { themeJa: '休みの連絡をする', starterJa: '体調が悪いとき、会社に何と連絡しますか？',
      starterZh: '身体不舒服时你怎么跟公司联系？', targetUse: '〜ので' },
    vocabularyLinks: ['fi-kaisha', 'fi-renraku'], unit: 'n3g-unit-5' }),
  g({ grammarId: 'n3g-kara-riyuu', sourceRowId: 'n3row-61', pattern: '〜から（理由）', reading: 'から',
    meaningJa: '（主観的な）理由', explanationZh: '因为…（主观的、直接的理由）',
    formation: '動詞・い形容詞・な形容詞・名詞のふつう形／ていねい形 ＋から',
    usageScene: '和朋友说明理由、强调自己的判断依据',
    nuance: '主观性强。对上司单用「から」略显强硬',
    register: 'both',
    examplesJa: ['明日は早いから、今日はもう帰ります。', '雨だから、タクシーで行きましょう。'],
    examplesZh: ['因为明天要早起，今天我先回去了。', '因为下雨，我们打车去吧。'],
    furigana: 'あしたは はやいから、きょうは もう かえります。',
    commonMistakesZh: '句尾是命令、劝诱时用「から」更自然；说明客观情况时用「ので」',
    learnerFocus: '「から」和「ので」的选择反映说话人的态度，是中国语母语者最常被指出的语感差',
    similarPatterns: ['〜ので', '〜ため'],
    contrast: '主观「から」／客观「ので」／书面「ため」',
    recognition: { promptZh: '「危ないから、気をつけて」这里为什么用「から」？',
      options: ['后面是提醒/劝告，主观语气自然', '因为前面说的是谁都知道的客观事实', '因为是书面语', '因为对上司说话'],
      answerIndex: 0, distractorReason: '劝诱・命令等主观句尾常配「から」',
      explanationZh: '劝告・命令的句子多用「から」' },
    production: { promptJa: '断る理由を「〜から」で言ってください。',
      promptZh: '用「〜から」说明拒绝的理由。',
      expected: ['から'], acceptable: ['忙しいから', '〜から行けません'] },
    practice: { themeJa: '誘いを断る', starterJa: '誘いを断るとき、理由をどう説明しますか？',
      starterZh: '拒绝邀请时你怎么说明理由？', targetUse: '〜から' },
    vocabularyLinks: ['fi-isogashii', 'fi-iku'], unit: 'n3g-unit-5' }),
  g({ grammarId: 'n3g-taritari', sourceRowId: 'n3row-62', pattern: '〜たり〜たりする', reading: 'たりたりする',
    meaningJa: '例としていくつかの動作を挙げる', explanationZh: '又…又…、…啊…啊之类的。列举有代表性的几个动作',
    formation: '動詞た形 ＋り（２つ以上）＋する',
    usageScene: '介绍休息日的活动、旅行做了什么',
    nuance: '暗示「还有别的」。全部列举完用「〜て、〜て」',
    register: 'both',
    examplesJa: ['休みの日は、部屋を片づけたり散歩したりします。', '週末は、掃除をしたり買い物をしたりしました。'],
    examplesZh: ['休息日会收拾房间、散散步什么的。', '周末打扫卫生、买东西什么的。'],
    furigana: 'やすみのひは、へやを かたづけたり さんぽ したり します。',
    commonMistakesZh: '句尾必须有「する／します」。只说「歌ったり踊ったり」话没说完',
    learnerFocus: '连接用た形（歌った→歌ったり）。变形错了会很明显',
    similarPatterns: ['〜て、〜て', '〜や〜など'],
    contrast: '「たり」＝举例（还有别的）；「て」＝按顺序全部列出；「や〜など」＝名词的举例',
    recognition: { promptZh: '「休みの日は本を読んだり音楽を聞いたり＿＿」空格是？',
      options: ['します', 'です', 'ました', 'ある'],
      answerIndex: 0, distractorReason: '「たり〜たり」句尾要用「する」',
      explanationZh: '「〜たり〜たりする」是完整形' },
    production: { promptJa: '休みの日にすることを「〜たり〜たりします」で言ってください。',
      promptZh: '用「〜たり〜たりします」说休息日做的事。',
      expected: ['たり'], acceptable: ['〜たり〜たりします'] },
    practice: { themeJa: '休日の過ごし方を話す', starterJa: '休みの日は、何をしたりしますか？',
      starterZh: '休息日你都做些什么？', targetUse: '〜たり〜たりします' },
    vocabularyLinks: ['fi-yomu', 'fi-kiku'], unit: 'n3g-unit-8' }),
  g({ grammarId: 'n3g-yasui', sourceRowId: 'n3row-63', pattern: '〜やすい', reading: 'やすい',
    meaningJa: '〜するのが簡単だ／そうなりやすい', explanationZh: '容易…、好…（褒贬皆可，中性）',
    formation: '動詞ます形 ＋やすい（い形容詞として活用）',
    usageScene: '评价书好读、路好走、这个季节容易感冒',
    nuance: '中性，褒贬都能用。负面倾向用「がち」更自然',
    register: 'both',
    examplesJa: ['このアプリは操作が分かりやすいです。', 'この靴は歩きやすいので気に入っています。'],
    examplesZh: ['这个软件操作很好懂。', '这双鞋好走，我很喜欢。'],
    furigana: 'この アプリは そうさが わかりやすいです。',
    commonMistakesZh: '变化和い形容詞一样：「読みやすくない」「読みやすかった」。这个变化常被忽略',
    learnerFocus: '「やすい」（中性）与「がち」（负面）的区别，是选词准确度的分水岭',
    similarPatterns: ['〜にくい', '〜がち'],
    contrast: '「やすい」⇔「にくい」是一对；「がち」偏负面频率',
    recognition: { promptZh: '「わかりやすい説明」是什么意思？',
      options: ['容易理解的说明', '难懂的说明', '很长的说明', '错误的说明'],
      answerIndex: 0, distractorReason: '「〜やすい」= 容易…',
      explanationZh: '「わかりやすい」= 好懂' },
    production: { promptJa: '使いやすいものを「〜やすい」で言ってください。',
      promptZh: '用「〜やすい」说一个好用的东西。',
      expected: ['やすい'], acceptable: ['使いやすい', '読みやすい'] },
    practice: { themeJa: '使いやすいアプリや道具を話す', starterJa: '最近使って「使いやすい」と思ったものはありますか？',
      starterZh: '最近有觉得好用的东西吗？', targetUse: '〜やすい' },
    vocabularyLinks: ['fi-yomu', 'fi-benri'], unit: 'n3g-unit-8' }),
  g({ grammarId: 'n3g-nikui', sourceRowId: 'n3row-64', pattern: '〜にくい', reading: 'にくい',
    meaningJa: '〜するのが難しい', explanationZh: '难…、不好…。做某事有困难',
    formation: '動詞ます形 ＋にくい（い形容詞として活用）',
    usageScene: '说明字难写、话难说出口、路难走',
    nuance: '是能力以外的「客观上困难」。「言いにくい」还含心理上难以启齿',
    register: 'both',
    examplesJa: ['この靴は少し歩きにくいです。', 'ちょっと言いにくいことがあるんですが…'],
    examplesZh: ['这双鞋有点不好走。', '有件事有点难开口…'],
    furigana: 'この くつは すこし あるきにくいです。',
    commonMistakesZh: '「言いにくい」不是「不会说」，而是「难以启齿」。这是很实用的社交表达',
    learnerFocus: '「ちょっと言いにくいんですが」是提出难开口请求时的缓冲句，职场非常有用',
    similarPatterns: ['〜づらい', '〜やすい'],
    contrast: '「にくい」客观困难；「づらい」偏心理・身体上的难受；「やすい」是反义',
    recognition: { promptZh: '「言いにくいことがあるんですが」暗示什么？',
      options: ['接下来要说难开口的事', '说话人一句日语也不会说', '说话人现在一句话也不想说', '说话人的声音太小听不见'],
      answerIndex: 0, distractorReason: '「言いにくい」表示心理上难以启齿',
      explanationZh: '这是提出难开口话题的缓冲句' },
    production: { promptJa: '使いにくいものを「〜にくい」で言ってください。',
      promptZh: '用「〜にくい」说一个不好用的东西。',
      expected: ['にくい'], acceptable: ['使いにくい', '書きにくい'] },
    practice: { themeJa: '言いにくいことを切り出す練習', starterJa: '「ちょっと言いにくいんですが」の後、何と続けますか？',
      starterZh: '说完「有点难开口」后你会怎么接？', targetUse: '〜にくい' },
    vocabularyLinks: ['fi-kaku', 'fi-muzukashii'], unit: 'n3g-unit-8' }),
  g({ grammarId: 'n3g-hajimeru', sourceRowId: 'n3row-65', pattern: '〜始める', reading: 'はじめる',
    meaningJa: '〜し始める（動作の開始）', explanationZh: '开始…。表示动作的开始',
    formation: '動詞ます形 ＋始める',
    usageScene: '说明什么时候开始学习、开始下雨',
    nuance: '「〜出す」是突然开始（雨が降り出す）。「始める」较中性',
    register: 'both',
    examplesJa: ['去年から日本語を勉強し始めました。', '急に雨が降り始めた。'],
    examplesZh: ['从去年开始学日语。', '突然开始下雨了。'],
    furigana: 'きょねんから にほんごを べんきょうし はじめました。',
    commonMistakesZh: '复合动词的前项用ます形：「勉強し」＋「始める」。写成「勉強する始める」是错的',
    learnerFocus: '「〜始める／〜続ける／〜終わる」是一组复合动词，能表达动作的开始・持续・结束',
    similarPatterns: ['〜出す', '〜続ける'],
    contrast: '「始める」中性开始；「出す」突然开始；「続ける」持续',
    recognition: { promptZh: '「日本語を勉強し始めました」是什么意思？',
      options: ['开始学日语了', '学完日语了', '不学日语了', '一直在学日语'],
      answerIndex: 0, distractorReason: '「〜始める」表示动作的开始',
      explanationZh: '「〜始める」= 开始做…' },
    production: { promptJa: 'いつ日本語を勉強し始めたか言ってください。',
      promptZh: '说说你什么时候开始学日语的。',
      expected: ['始め'], acceptable: ['勉強し始めました'] },
    practice: { themeJa: '始めたきっかけを話す', starterJa: 'いつ、なぜ日本語を勉強し始めましたか？',
      starterZh: '你什么时候、为什么开始学日语的？', targetUse: '〜始めました' },
    vocabularyLinks: ['fi-hajimeru', 'fi-benkyo'], unit: 'n3g-unit-8' }),
  g({ grammarId: 'n3g-owaru-fukugou', sourceRowId: 'n3row-66', pattern: '〜終わる', reading: 'おわる',
    meaningJa: '〜し終わる（動作の完了）', explanationZh: '…完。表示动作全部结束',
    formation: '動詞ます形 ＋終わる',
    usageScene: '说明看完书、吃完饭、写完报告',
    nuance: '客观地表示动作结束，不带「てしまう」的感情色彩',
    register: 'both',
    examplesJa: ['報告書をやっと書き終わりました。', '食べ終わったら、お皿を下げてください。'],
    examplesZh: ['报告终于写完了。', '吃完后请把盘子收走。'],
    furigana: 'ほうこくしょを やっと かきおわりました。',
    commonMistakesZh: '和「〜てしまう」的区别：「読み終わった」是客观读完，「読んでしまった」可能含「不小心读完了」',
    learnerFocus: '「〜終わったら」（做完之后）在指示、说明步骤时很常用',
    similarPatterns: ['〜てしまう', '〜きる'],
    contrast: '「終わる」＝客观完成；「てしまう」＝带感情；「きる」＝彻底完成（全部用尽）',
    recognition: { promptZh: '「食べ終わったら教えてください」是什么时候告诉？',
      options: ['吃完之后', '吃之前', '正在吃的时候', '不用告诉'],
      answerIndex: 0, distractorReason: '「〜終わったら」= 做完之后',
      explanationZh: '「〜終わったら」= …完之后' },
    production: { promptJa: '何かをし終わった経験を「〜終わりました」で言ってください。',
      promptZh: '用「〜終わりました」说你做完的事。',
      expected: ['終わ'], acceptable: ['読み終わりました', '書き終わりました'] },
    practice: { themeJa: '今日終わらせたことを話す', starterJa: '今日、何をし終わりましたか？',
      starterZh: '今天你做完了什么？', targetUse: '〜終わりました' },
    vocabularyLinks: ['fi-owaru', 'fi-yomu'], unit: 'n3g-unit-8' }),
  g({ grammarId: 'n3g-tsuzukeru-fukugou', sourceRowId: 'n3row-67', pattern: '〜続ける', reading: 'つづける',
    meaningJa: '〜し続ける（動作の継続）', explanationZh: '持续…、一直…。表示动作不间断地进行',
    formation: '動詞ます形 ＋続ける',
    usageScene: '说明坚持了多久、雨一直下',
    nuance: '强调不间断。中断后再开始用「また〜始める」',
    register: 'both',
    examplesJa: ['3年間、日本語を勉強し続けています。', '朝から雨が降り続けている。'],
    examplesZh: ['我持续学了三年日语。', '从早上就一直在下雨。'],
    furigana: 'さんねんかん、にほんごを べんきょうし つづけています。',
    commonMistakesZh: '表示现在仍在持续用「〜続けています」。用「続けました」会变成「持续过（已结束）」',
    learnerFocus: '「〜続けています」是介绍自己坚持之事的最佳表达，面试和自我介绍都好用',
    similarPatterns: ['〜ている', '〜始める'],
    contrast: '「続ける」强调不间断的持续；「ている」只是状态或进行',
    recognition: { promptZh: '「10年間働き続けています」是什么意思？',
      options: ['持续工作了10年，现在还在', '10年前工作过', '要工作10年', '不想工作'],
      answerIndex: 0, distractorReason: '「〜続けています」表示至今仍在持续',
      explanationZh: '「〜続けています」= 一直持续到现在' },
    production: { promptJa: '長く続けていることを「〜続けています」で言ってください。',
      promptZh: '用「〜続けています」说说你长期坚持的事。',
      expected: ['続け'], acceptable: ['勉強し続けています'] },
    practice: { themeJa: '長く続けていることを話す', starterJa: '何年ぐらい日本語を勉強し続けていますか？',
      starterZh: '你持续学日语多久了？', targetUse: '〜続けています' },
    vocabularyLinks: ['fi-tsuzukeru', 'fi-benkyo'], unit: 'n3g-unit-8' }),
  g({ grammarId: 'n3g-youninaru', sourceRowId: 'n3row-68', pattern: '〜ようになる', reading: 'ようになる',
    meaningJa: 'できなかったことができるようになる（変化）', explanationZh: '变得能…、变得会…。表示能力或习惯的变化',
    formation: '動詞辞書形／可能形／ない形（〜なくなる）＋ようになる',
    usageScene: '汇报自己的学习进步：变得能听懂了、变得会做饭了',
    nuance: '强调「以前不行，现在行了」的变化过程',
    register: 'both',
    examplesJa: ['漢字のメニューが読めるようになりました。', '最近、朝早く起きられるようになった。'],
    examplesZh: ['变得能看懂汉字菜单了。', '最近变得能早起了。'],
    furigana: 'かんじの メニューが よめるように なりました。',
    commonMistakesZh: '和「〜ようにする」（努力去做）混淆。「なる」是结果的变化，「する」是自己的努力',
    learnerFocus: '汇报学习成果时最有成就感的表达。「〜られるようになりました」是可能形＋变化',
    similarPatterns: ['〜ようにする', '〜てくる'],
    contrast: '「ようになる」＝变化的结果；「ようにする」＝努力的过程',
    recognition: { promptZh: '「泳げるようになりました」是什么意思？',
      options: ['变得会游泳了', '从以前开始就一直会游泳', '不会游泳', '想学游泳'],
      answerIndex: 0, distractorReason: '「〜ようになる」表示从不会到会的变化',
      explanationZh: '「可能形＋ようになる」= 变得能…' },
    production: { promptJa: '日本語でできるようになったことを言ってください。',
      promptZh: '说说你在日语上变得能做到的事。',
      expected: ['ようになりました'], acceptable: ['〜ようになった'] },
    practice: { themeJa: '日本語の上達を報告する', starterJa: '日本語で、何ができるようになりましたか？',
      starterZh: '日语上你变得能做什么了？', targetUse: '〜ようになりました' },
    vocabularyLinks: ['fi-hanasu', 'fi-nareru'], unit: 'n3g-unit-8' }),
  g({ grammarId: 'n3g-bakari', sourceRowId: 'n3row-69', pattern: '〜ばかり', reading: 'ばかり',
    meaningJa: '〜だけ（同じことの繰り返しへの不満）', explanationZh: '光…、总是…、净是…。多含说话人的不满',
    formation: '名詞／動詞て形 ＋ばかり',
    usageScene: '抱怨对方只玩不学、自己净吃外卖',
    nuance: '带批评语气。中性的「只有」用「だけ」',
    register: 'both',
    examplesJa: ['休みの日は、動画ばかり見ています。', '最近、コンビニ弁当ばかり食べています。'],
    examplesZh: ['休息日光在看视频。', '最近净吃便利店便当。'],
    furigana: 'やすみのひは、どうが ばかり みています。',
    commonMistakesZh: '「だけ」是中性的「只」，「ばかり」多含负面评价。夸人不能用「ばかり」',
    learnerFocus: '「〜てばかりいる」（老是在做…）是抱怨他人行为的定型，听力中很常见',
    similarPatterns: ['〜だけ', '〜しか〜ない'],
    contrast: '「だけ」中性；「ばかり」含不满；「しか〜ない」强调少（遗憾）',
    recognition: { promptZh: '「ゲームばかりしている」的语气是？',
      options: ['带批评（老是打游戏）', '表扬', '中立描述', '羡慕'],
      answerIndex: 0, distractorReason: '「ばかり」多含说话人的不满',
      explanationZh: '「〜ばかり」= 光做…（含批评）' },
    production: { promptJa: '最近そればかりしていることを「〜ばかり」で言ってください。',
      promptZh: '用「〜ばかり」说你最近老在做的事。',
      expected: ['ばかり'], acceptable: ['〜ばかりしています', '〜ばかり食べています'] },
    practice: { themeJa: '最近の偏った習慣を話す', starterJa: '最近、何かばかりしていませんか？',
      starterZh: '最近你是不是老在做同一件事？', targetUse: '〜ばかり' },
    vocabularyLinks: ['fi-taberu', 'fi-shuukan'], unit: 'n3g-unit-8' }),
  g({ grammarId: 'n3g-youni-mokuteki', sourceRowId: 'n3row-70', pattern: '〜ように（目的）', reading: 'ように',
    meaningJa: 'そうなることを目指して', explanationZh: '为了…（能够…）。表示目的（非意志性结果）',
    formation: '動詞可能形／ない形／自動詞 ＋ように',
    usageScene: '说明为了不忘记而记笔记、为了能听懂而多听',
    nuance: '前项是「非自己意志能直接控制的结果」。意志动作用「〜ために」',
    register: 'both',
    examplesJa: ['遅れないように、一本早い電車に乗ります。', '聞こえるように、大きい声で話してください。'],
    examplesZh: ['为了不迟到，坐早一班的电车。', '为了能听见，请大声说。'],
    furigana: 'おくれないように、いっぽん はやい でんしゃに のります。',
    commonMistakesZh: '「ために」接意志动词（留学するために）；「ように」接可能形・否定・自动词（忘れないように）',
    learnerFocus: '中文「为了」一个词，日语要按「能不能自己控制」分「ために」和「ように」。这是N3核心难点',
    similarPatterns: ['〜ために', '〜ようにする'],
    contrast: '意志动作→「ために」；可能・状态・否定→「ように」',
    recognition: { promptZh: '「日本語が上手になる＿＿、毎日練習します」空格是？',
      options: ['ように', 'ために', 'から', 'ので'],
      answerIndex: 0, distractorReason: '「上手になる」是非意志的结果，用「ように」',
      explanationZh: '非意志的结果 →「ように」' },
    production: { promptJa: '目的を「〜ように」で言ってください。',
      promptZh: '用「〜ように」说明一个目的。',
      expected: ['ように'], acceptable: ['忘れないように', '〜ように〜します'] },
    practice: { themeJa: '目標のための工夫を話す', starterJa: '日本語が上達するように、何をしていますか？',
      starterZh: '为了日语进步你做了什么？', targetUse: '〜ように' },
    vocabularyLinks: ['fi-wasureru', 'fi-benkyo'], unit: 'n3g-unit-9' }),
  g({ grammarId: 'n3g-tagaru', sourceRowId: 'n3row-71', pattern: '〜たがる', reading: 'たがる',
    meaningJa: '（第三者が）〜したそうにしている', explanationZh: '（第三者）想…。描述别人表现出的愿望',
    formation: '動詞ます形 ＋たがる（〜たがっている）',
    usageScene: '描述孩子想玩、同事想早点回家',
    nuance: '不能用于自己。自己的愿望用「〜たい」',
    register: 'both',
    examplesJa: ['同僚が新しい部署へ移りたがっています。', '彼は日本へ行きたがっている。'],
    examplesZh: ['同事想调到新部门去。', '他想去日本。'],
    furigana: 'どうりょうが あたらしい ぶしょへ うつりたがって います。',
    commonMistakesZh: '「私は行きたがる」是错的。自己用「行きたい」，第三者用「行きたがっている」',
    learnerFocus: '日语严格区分「自己的心情（能直接说）」和「别人的心情（只能观察）」。这是重要的思维差异',
    similarPatterns: ['〜たい', '〜てほしい'],
    contrast: '自分＝「たい」；第三者＝「たがる」；相手にしてほしい＝「てほしい」',
    recognition: { promptZh: '哪个说法正确？',
      options: ['弟は行きたがっています', '私は行きたがっています', '弟は行きたいです（客观描述时）', '私は行きたがる'],
      answerIndex: 0, distractorReason: '「たがる」只用于第三者',
      explanationZh: '第三者的愿望 →「〜たがっている」' },
    production: { promptJa: '家族や友達がしたがっていることを言ってください。',
      promptZh: '说说你家人或朋友想做的事。',
      expected: ['たがっ'], acceptable: ['行きたがっています', '〜たがっている'] },
    practice: { themeJa: '家族の希望を伝える', starterJa: '家族が何かをしたがっていますか？',
      starterZh: '你家人想做什么吗？', targetUse: '〜たがっています' },
    vocabularyLinks: ['fi-iku', 'fi-kazoku'], unit: 'n3g-unit-9' }),
  g({ grammarId: 'n3g-souda-yousu', sourceRowId: 'n3row-72', pattern: '〜そうだ（様態）', reading: 'そうだ',
    meaningJa: '見た目からそう思われる', explanationZh: '看起来…。根据外观做出的即时判断',
    formation: '動詞ます形／い形容詞（〜い削除）／な形容詞語幹 ＋そうだ',
    usageScene: '看到食物说「看起来好吃」、看到天空说「像要下雨」',
    nuance: '只凭外观。与「〜そうだ（伝聞）」形态相近但接续不同',
    register: 'both',
    examplesJa: ['荷物、重そうですね。持ちましょうか。', '雨が降りそうです。'],
    examplesZh: ['行李看起来很重呢。我来拿吧？', '像是要下雨了。'],
    furigana: 'にもつ、おもそうですね。もちましょうか。',
    commonMistakesZh: '「いい」→「よさそう」、「ない」→「なさそう」是特殊变化，必须单独记',
    learnerFocus: '样态「おいしそう」（ます形/词干接）与传闻「おいしいそうだ」（普通形接）只差一点，靠接续区分',
    similarPatterns: ['〜そうだ（伝聞）', '〜ようだ'],
    contrast: '様態＝外观判断（接词干）；伝聞＝听说（接普通形）',
    recognition: { promptZh: '看到蛋糕说「看起来好吃」是？',
      options: ['おいしそうです', 'おいしいそうです', 'おいしいようです', 'おいしいらしいです'],
      answerIndex: 0, distractorReason: '样态用词干接续「おいしそう」，传闻用普通形「おいしいそう」',
      explanationZh: '从外表看上去 →「おいしそう」' },
    production: { promptJa: '食べ物を見て「〜そうです」で感想を言ってください。',
      promptZh: '看着食物用「〜そうです」说感想。',
      expected: ['そう'], acceptable: ['おいしそうです', '楽しそうです'] },
    practice: { themeJa: '見た目の感想を言う', starterJa: '写真を見て「〜そうですね」と感想を言ってみましょう',
      starterZh: '看着照片用「〜そうですね」说感想', targetUse: '〜そうです' },
    vocabularyLinks: ['fi-oishii', 'fi-tanoshii'], unit: 'n3g-unit-9' }),
  g({ grammarId: 'n3g-tehoshii', sourceRowId: 'n3row-73', pattern: '〜てほしい', reading: 'てほしい',
    meaningJa: '相手に〜してもらいたい', explanationZh: '希望（别人）…。表达对他人行为的期望',
    formation: '動詞て形 ＋ほしい（〜ないでほしい）',
    usageScene: '向家人、同事表达希望：希望你多听我说、希望别迟到',
    nuance: '对上司直接说会失礼，要用「〜ていただけますか」',
    register: 'both',
    examplesJa: ['会議の資料は前日までに送ってほしいです。', '遅刻しないでほしいです。'],
    examplesZh: ['希望会议资料在前一天之前发过来。', '希望你别迟到。'],
    furigana: 'かいぎの しりょうは ぜんじつまでに おくって ほしいです。',
    commonMistakesZh: '和「〜たい」（自己想做）混淆。「行きたい」是我想去，「行ってほしい」是希望你去',
    learnerFocus: '对上司不能用「〜てほしい」。请求要用「〜ていただけますか」，这是职场必修',
    similarPatterns: ['〜たい', '〜てもらいたい', '〜ていただけますか'],
    contrast: '「てほしい」＝对平级/晚辈的期望；「ていただけますか」＝对上位者的请求',
    recognition: { promptZh: '对上司提出请求，最合适的是？',
      options: ['確認していただけますか', '確認してほしいです', '確認して', '確認しろ'],
      answerIndex: 0, distractorReason: '对上位者要用「〜ていただけますか」',
      explanationZh: '对上司用敬语请求形式' },
    production: { promptJa: '家族にしてほしいことを「〜てほしいです」で言ってください。',
      promptZh: '用「〜てほしいです」说你希望家人做的事。',
      expected: ['てほしい'], acceptable: ['〜てほしいです'] },
    practice: { themeJa: '相手への希望を伝える', starterJa: '周りの人に、何をしてほしいですか？',
      starterZh: '你希望身边的人做什么？', targetUse: '〜てほしいです' },
    vocabularyLinks: ['fi-kiku', 'fi-tsutaeru'], unit: 'n3g-unit-9' }),
  g({ grammarId: 'n3g-nikuwaete', sourceRowId: 'n3row-75', pattern: '〜にくわえて', reading: 'にくわえて',
    meaningJa: '〜に加えて、さらに', explanationZh: '不仅…还…、除…之外还…。追加同类的事项',
    formation: '名詞 ＋にくわえて',
    usageScene: '说明天气恶劣的叠加、工作负担的叠加',
    nuance: '书面。口语用「〜だけでなく」「〜も」',
    register: 'written',
    examplesJa: ['人手不足にくわえて、注文も増えています。', '残業にくわえて、休日出勤も増えました。'],
    examplesZh: ['不仅人手不足，订单也在增加。', '除了加班，休息日上班也增加了。'],
    furigana: 'ひとでぶそくに くわえて、ちゅうもんも ふえて います。',
    commonMistakesZh: '后项常带「も」。只写前项会不完整',
    learnerFocus: '新闻和商务邮件中常见。会话中说「雨も降ってるし、風も強いし」更自然',
    similarPatterns: ['〜だけでなく', '〜ばかりでなく', '〜上に'],
    contrast: '「にくわえて」＝追加（书面）；「上に」＝雪上加霜（更负面）',
    recognition: { promptZh: '「〜にくわえて」多用于什么场合？',
      options: ['新闻、商务邮件等书面', '朋友闲聊', '孩子的对话', '唱歌'],
      answerIndex: 0, distractorReason: '「にくわえて」是书面语',
      explanationZh: '书面追加表达' },
    production: { promptJa: '悪条件が重なったことを「〜にくわえて」で言ってください。',
      promptZh: '用「〜にくわえて」说几个叠加的不利条件。',
      expected: ['にくわえて'], acceptable: ['〜にくわえて〜も'] },
    practice: { themeJa: '忙しさの理由を説明する', starterJa: '最近忙しい理由を、二つ重ねて説明してみましょう',
      starterZh: '试着叠加说明你最近忙的两个原因', targetUse: '〜にくわえて' },
    vocabularyLinks: ['fi-shigoto', 'fi-isogashii'], unit: 'n3g-unit-1' }),
  g({ grammarId: 'n3g-nitaishite', sourceRowId: 'n3row-77', pattern: '〜に対して', reading: 'にたいして',
    meaningJa: '〜を相手・対象として', explanationZh: '对…（采取某种态度或行为）',
    formation: '名詞 ＋に対して',
    usageScene: '说明对某人的态度、对提问的回答',
    nuance: '也有「与之相对」的对比用法（前者に対して後者は）',
    register: 'written',
    examplesJa: ['お客様に対しては、必ず敬語を使います。', '質問に対して、丁寧に答えました。'],
    examplesZh: ['对客人一定要用敬语。', '对提问做了礼貌的回答。'],
    furigana: 'おきゃくさまに たいしては、かならず けいごを つかいます。',
    commonMistakesZh: '和「にとって」（立场评价）混淆。「に対して」是行为的对象',
    learnerFocus: '「〜に対して」＋态度・行为；「〜にとって」＋评价。搭配的后项完全不同',
    similarPatterns: ['〜にとって', '〜に'],
    contrast: '「に対して」＝行为对象；「にとって」＝立场评价',
    recognition: { promptZh: '「お客様に対して失礼のないように」是什么意思？',
      options: ['注意不要对客人失礼', '对客人来说是很失礼的', '客人对我们的态度很失礼', '尽量不要去见那位客人'],
      answerIndex: 0, distractorReason: '「に対して」标记行为的对象',
      explanationZh: '「〜に対して」= 对（某对象）' },
    production: { promptJa: '相手への態度を「〜に対して」で言ってください。',
      promptZh: '用「〜に対して」说对某人的态度。',
      expected: ['に対して'], acceptable: ['お客様に対して'] },
    practice: { themeJa: '接客の心がけを話す', starterJa: 'お客様に対して、どんなことに気をつけますか？',
      starterZh: '对客人你会注意什么？', targetUse: '〜に対して' },
    vocabularyLinks: ['fi-sensei', 'fi-kankei'], unit: 'n3g-unit-1' }),
];
