// Phase R1: N3/N2 overlap 38件のUsage構造化（同一文型をN3/N2で二重Item化しない）。
// アンカー=N2 grammarId（completeDraft済み）。N3シート行はそのItemの「N3 core Usage」として従属する。
// levelPlacement（最終的にどのレベルの学習ルートへ出すか）は人間判断待ちのまま（自動確定しない）。
// 生成元: docs/ai-course/production/generated/n3-grammar-source-audit.json（n2_overlap・awaiting_level_decision）
export type OverlapRelationCandidate =
  | 'same_item_same_usage'
  | 'same_item_extended_usage'
  | 'same_pattern_different_usage'
  | 'different_register'
  | 'different_nuance'
  | 'relation_only'
  | 'human_decision_required';

export interface GrammarOverlapUsage {
  /** アンカーItem（既存N2 completeDraftのgrammarId）。新Itemは作らない */
  n2ItemId: string;
  /** N3シート行の出典ID（provenance） */
  n3SourceRowId: string;
  pattern: string;
  /** N3シートが供給するコアUsage（このItemのN3向け面） */
  core: { levelCandidate: 'N3'; meaningJa: string; meaningZh: string; exampleJa: string; exampleZh: string };
  /** N2 draft側の扱いとの関係（candidate。approved relationは人間判断） */
  relationCandidate: OverlapRelationCandidate;
  rationale: string;
  /** レベル最終配置は人間判断（自動確定しない） */
  levelPlacement: 'awaiting_level_decision';
  reviewKey: string;
  sourceRefs: string[];
}

const u = (p: Omit<GrammarOverlapUsage, 'levelPlacement' | 'reviewKey' | 'sourceRefs'>): GrammarOverlapUsage =>
  ({ ...p, levelPlacement: 'awaiting_level_decision', reviewKey: `overlap-${p.n2ItemId}`,
     sourceRefs: [p.n3SourceRowId, p.n2ItemId] });

export const N3_N2_OVERLAP_USAGES: GrammarOverlapUsage[] = [
  u({ n2ItemId: 'n2g-002', n3SourceRowId: 'n3row-2', pattern: '~あまり',
    core: { levelCandidate: 'N3', meaningJa: '~しすぎて結果が出る', meaningZh: '因为过于...导致...',
      exampleJa: 'うれしさのあまり、泣いてしまった。', exampleZh: '因为太高兴了,不由得哭了出来。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-144', n3SourceRowId: 'n3row-3', pattern: '~ば~ほど',
    core: { levelCandidate: 'N3', meaningJa: '~すればするほど', meaningZh: '越...越...',
      exampleJa: '勉強すればするほど、上手になります。', exampleZh: '越学习越擅长。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-147', n3SourceRowId: 'n3row-5', pattern: '~べき',
    core: { levelCandidate: 'N3', meaningJa: '~するのが当然だ', meaningZh: '应该...',
      exampleJa: '約束は守るべきだ。', exampleZh: '应该遵守约定。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-068', n3SourceRowId: 'n3row-6', pattern: '~だらけ',
    core: { levelCandidate: 'N3', meaningJa: '~がたくさんある(悪い意味)', meaningZh: '满是...(多为负面)',
      exampleJa: 'この部屋はゴミだらけだ。', exampleZh: '这个房间到处都是垃圾。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-020', n3SourceRowId: 'n3row-10', pattern: '~がたい',
    core: { levelCandidate: 'N3', meaningJa: '~しにくい(心理的に)', meaningZh: '难以...',
      exampleJa: '信じがたい話ですね。', exampleZh: '真是难以置信的事情。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-039', n3SourceRowId: 'n3row-11', pattern: '~気味',
    core: { levelCandidate: 'N3', meaningJa: '~の傾向がある', meaningZh: '有点...的倾向',
      exampleJa: '最近疲れ気味です。', exampleZh: '最近有点疲惫。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-025', n3SourceRowId: 'n3row-13', pattern: '~か~ないかのうちに',
    core: { levelCandidate: 'N3', meaningJa: 'すぐに', meaningZh: '刚...就...',
      exampleJa: 'ベルが鳴るか鳴らないかのうちに、学生は教室を出た。', exampleZh: '铃声刚响起,学生就走出了教室。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-023', n3SourceRowId: 'n3row-14', pattern: '~かと思うと',
    core: { levelCandidate: 'N3', meaningJa: '~した直後に', meaningZh: '刚...就...',
      exampleJa: '空が暗くなったかと思うと、雨が降り出した。', exampleZh: '天刚变暗就开始下雨了。' },
    relationCandidate: 'same_item_extended_usage',
    rationale: 'N3=「した直後に」のコア。N2 draftは「急転・正反対の対比」の含みまで拡張' }),
  u({ n2ItemId: 'n2g-029', n3SourceRowId: 'n3row-15', pattern: '~かのようだ',
    core: { levelCandidate: 'N3', meaningJa: 'まるで~のようだ', meaningZh: '仿佛...一样',
      exampleJa: '彼はまるで夢を見ているかのようだ。', exampleZh: '他仿佛在做梦一样。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-035', n3SourceRowId: 'n3row-16', pattern: '~からといって',
    core: { levelCandidate: 'N3', meaningJa: '理由にはならない', meaningZh: '虽说...但不能...',
      exampleJa: '高いからといって、品質がいいとは限らない。', exampleZh: '虽说价格高,但不一定质量好。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-041', n3SourceRowId: 'n3row-17', pattern: '~きる',
    core: { levelCandidate: 'N3', meaningJa: '最後まで~する', meaningZh: '完全地...',
      exampleJa: '全部食べきった。', exampleZh: '全部吃完了。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-042', n3SourceRowId: 'n3row-18', pattern: '~くせに',
    core: { levelCandidate: 'N3', meaningJa: '非難の気持ち', meaningZh: '明明...却...',
      exampleJa: '知っているくせに、教えてくれなかった。', exampleZh: '明明知道却不告诉我。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-049', n3SourceRowId: 'n3row-23', pattern: '~ことは~が',
    core: { levelCandidate: 'N3', meaningJa: '一応~だが', meaningZh: '虽说...但是...',
      exampleJa: '行くことは行くが、あまり気が進まない。', exampleZh: '虽说会去,但并不是很情愿。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-168', n3SourceRowId: 'n3row-28', pattern: '~わけがない',
    core: { levelCandidate: 'N3', meaningJa: '絶対~ない', meaningZh: '不可能...',
      exampleJa: '彼がそんなことをするわけがない。', exampleZh: '他不可能做那种事。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-170', n3SourceRowId: 'n3row-29', pattern: '~わけではない',
    core: { levelCandidate: 'N3', meaningJa: '全部が~とは限らない', meaningZh: '并非...',
      exampleJa: '嫌いなわけではないが、あまり食べない。', exampleZh: '并不是讨厌,只是不太常吃。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-171', n3SourceRowId: 'n3row-30', pattern: '~わけにはいかない',
    core: { levelCandidate: 'N3', meaningJa: 'できない事情がある', meaningZh: '不能...',
      exampleJa: '試験があるから、休むわけにはいかない。', exampleZh: '因为有考试,不能请假。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-066', n3SourceRowId: 'n3row-44', pattern: '~たばかり',
    core: { levelCandidate: 'N3', meaningJa: '~した直後', meaningZh: '刚刚...',
      exampleJa: '彼は来たばかりです。', exampleZh: '他刚来。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-063', n3SourceRowId: 'n3row-74', pattern: '~たところ',
    core: { levelCandidate: 'N3', meaningJa: 'したら...', meaningZh: '刚...就...',
      exampleJa: '聞いたところ、彼は辞めたらしい。', exampleZh: '一打听才知道他辞职了。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-098', n3SourceRowId: 'n3row-76', pattern: '~とともに',
    core: { levelCandidate: 'N3', meaningJa: '~と一緒に', meaningZh: '和...一起',
      exampleJa: '家族とともに暮らす。', exampleZh: '和家人一起生活。' },
    relationCandidate: 'same_item_extended_usage',
    rationale: 'N3=「と一緒に」のコア。N2 draftは「同時進行・連動変化（書面）」まで拡張' }),
  u({ n2ItemId: 'n2g-008', n3SourceRowId: 'n3row-81', pattern: '~うちに',
    core: { levelCandidate: 'N3', meaningJa: '~している間に', meaningZh: '趁着...期间',
      exampleJa: '若いうちに勉強しておいたほうがいい。', exampleZh: '趁年轻多学习比较好。' },
    relationCandidate: 'same_item_extended_usage',
    rationale: 'N3=「している間に（趁着）」のコア。N2 draftは「変化する前に・ないうちに」まで拡張' }),
  u({ n2ItemId: 'n2g-044', n3SourceRowId: 'n3row-85', pattern: '~ことか',
    core: { levelCandidate: 'N3', meaningJa: '感嘆', meaningZh: '多么...',
      exampleJa: 'どんなにうれしかったことか。', exampleZh: '我有多高兴啊。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-065', n3SourceRowId: 'n3row-89', pattern: '~たとたん(に)',
    core: { levelCandidate: 'N3', meaningJa: '~した直後', meaningZh: '刚...就...',
      exampleJa: '立ち上がったとたん、めまいがした。', exampleZh: '刚站起来就头晕了。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-067', n3SourceRowId: 'n3row-90', pattern: '~たびに',
    core: { levelCandidate: 'N3', meaningJa: '~するといつも', meaningZh: '每当...',
      exampleJa: '旅行のたびに新しい発見がある。', exampleZh: '每次旅行都有新发现。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-077', n3SourceRowId: 'n3row-91', pattern: '~てからでないと',
    core: { levelCandidate: 'N3', meaningJa: '~しなければ', meaningZh: '不...就不行',
      exampleJa: '許可をもらってからでないと入れない。', exampleZh: '必须得到许可才能进入。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-085', n3SourceRowId: 'n3row-92', pattern: '~ということだ',
    core: { levelCandidate: 'N3', meaningJa: '伝聞・説明', meaningZh: '也就是说...',
      exampleJa: '明日から出張だということだ。', exampleZh: '也就是说从明天开始出差。' },
    relationCandidate: 'same_item_extended_usage',
    rationale: 'N3=「伝聞・説明」のコア。N2 draftは「言い換え・帰結（つまり…ということだ）」まで拡張' }),
  u({ n2ItemId: 'n2g-088', n3SourceRowId: 'n3row-94', pattern: '~といっても',
    core: { levelCandidate: 'N3', meaningJa: '実際は~', meaningZh: '虽说...',
      exampleJa: '料理が得意といっても簡単なものだけです。', exampleZh: '虽说擅长做饭,也只是简单的料理。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-087', n3SourceRowId: 'n3row-95', pattern: '~というより',
    core: { levelCandidate: 'N3', meaningJa: 'AよりB', meaningZh: '与其说是A不如说是B',
      exampleJa: '怒っているというより、呆れている。', exampleZh: '与其说是生气,不如说是无语。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-121', n3SourceRowId: 'n3row-97', pattern: '~にしては',
    core: { levelCandidate: 'N3', meaningJa: '予想外', meaningZh: '照理说...',
      exampleJa: '彼は新人にしては上手だ。', exampleZh: '他虽然是新人却很擅长。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-122', n3SourceRowId: 'n3row-98', pattern: '~にしても',
    core: { levelCandidate: 'N3', meaningJa: '仮定・譲歩', meaningZh: '即使...',
      exampleJa: '行かないにしても、連絡ぐらいして。', exampleZh: '就算不去,也联系一下吧。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-126', n3SourceRowId: 'n3row-101', pattern: '~に違いない',
    core: { levelCandidate: 'N3', meaningJa: 'きっと~だ', meaningZh: '一定...',
      exampleJa: '彼は来るに違いない。', exampleZh: '他一定会来。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-149', n3SourceRowId: 'n3row-105', pattern: '~ほど',
    core: { levelCandidate: 'N3', meaningJa: '程度', meaningZh: '越...越...',
      exampleJa: '忙しいほど燃える。', exampleZh: '越忙越有干劲。' },
    relationCandidate: 'same_item_extended_usage',
    rationale: 'N3=「程度」のコア。N2 draftは「程度の比喩・AほどBない比較」まで拡張' }),
  u({ n2ItemId: 'n2g-174', n3SourceRowId: 'n3row-113', pattern: '~を通じて',
    core: { levelCandidate: 'N3', meaningJa: '手段・期間', meaningZh: '通过.../在...期间',
      exampleJa: '先生を通じて知り合った。', exampleZh: '通过老师认识的。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-177', n3SourceRowId: 'n3row-114', pattern: '~をはじめ',
    core: { levelCandidate: 'N3', meaningJa: '代表例', meaningZh: '以...为首',
      exampleJa: '校長先生をはじめ、先生方に感謝します。', exampleZh: '感谢以校长为首的各位老师。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-173', n3SourceRowId: 'n3row-115', pattern: '~を中心に',
    core: { levelCandidate: 'N3', meaningJa: '中心・主に', meaningZh: '以...为中心',
      exampleJa: '学生を中心にアンケートを行った。', exampleZh: '以学生为中心进行问卷调查。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-081', n3SourceRowId: 'n3row-116', pattern: '~てならない',
    core: { levelCandidate: 'N3', meaningJa: '感情の強調', meaningZh: '非常...',
      exampleJa: '会いたくてならない。', exampleZh: '非常想见。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-053', n3SourceRowId: 'n3row-117', pattern: '~ざるを得ない',
    core: { levelCandidate: 'N3', meaningJa: 'どうしても~するしかない', meaningZh: '不得不...',
      exampleJa: '認めざるを得ない。', exampleZh: '不得不承认。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-109', n3SourceRowId: 'n3row-118', pattern: '~にかかわらず',
    core: { levelCandidate: 'N3', meaningJa: '関係なく', meaningZh: '无论...',
      exampleJa: '雨かどうかにかかわらず、行きます。', exampleZh: '无论下不下雨都去。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
  u({ n2ItemId: 'n2g-107', n3SourceRowId: 'n3row-119', pattern: '~において',
    core: { levelCandidate: 'N3', meaningJa: '場所や状況', meaningZh: '在...(场所)',
      exampleJa: '会議は東京において行われた。', exampleZh: '会议在东京举行。' },
    relationCandidate: 'same_item_same_usage',
    rationale: 'N3シートの意味・例文とN2 draftのコア用法が一致。単一Item＋単一Usageで足りる見込み' }),
];

export const overlapByN2Id = (id: string): GrammarOverlapUsage | undefined =>
  N3_N2_OVERLAP_USAGES.find(o => o.n2ItemId === id);
