// Phase 3P-3: オノマトペ完成draft バッチ5（ぽかぽか〜よれよれ・16語・最終）。
// 完成条件はonomatopoeiaDrafts.tsと同一（全field完備のみ収録）。全draft。
import type { OnomatopoeiaDraft } from './onomatopoeiaDrafts';

const d = (p: Omit<OnomatopoeiaDraft, 'unit' | 'publishStatus' | 'humanReviewed' | 'approved' | 'reviewKey'> & { reviewKey?: string }): OnomatopoeiaDraft =>
  ({ unit: 'ono-unit-1', publishStatus: 'draft', humanReviewed: false, approved: false,
     reviewKey: p.id, ...p });

export const ONOMATOPOEIA_DRAFTS_BATCH5: OnomatopoeiaDraft[] = [
  d({ id: 'ono-pokapoka', sourceCandidateId: 'a9402d819cd8d5e7', surface: 'ぽかぽか', kana: 'ぽかぽか',
    category: 'gitaigo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '心地よく暖かい様子', meaningZh: '（状态）暖洋洋、暖烘烘（舒服的暖）',
    nuanceZh: '春の日差し・お風呂上がりの体・こたつ。「ひんやり」の暖かさ版で、必ず心地よい暖かさ',
    similarJa: ['ほかほか', 'ひんやり'],
    examples: [
      { ja: '今日は日差しがぽかぽかして、春らしいです。', zh: '今天阳光暖洋洋的，很有春天的感觉。' },
      { ja: 'お風呂に入って、体がぽかぽかしています。', zh: '泡完澡身体暖烘烘的。' },
    ],
    commonMistakeZh: '「暑い」（热・不快になり得る）と違い「ぽかぽか」は常に心地よい。真夏の炎天下には使わない',
    recognition: { promptZh: '「ぽかぽか」是哪种温度感？',
      options: ['舒服的暖洋洋', '热得难受', '冷得发抖', '不冷不热没感觉'],
      answerIndex: 0, feedbackZh: '心地よい暖かさ =「ぽかぽか」' },
    production: { promptJa: '春の陽気を「ぽかぽか」で言ってください。',
      promptZh: '用「ぽかぽか」形容春天的天气。',
      expected: ['ぽかぽか'], acceptable: ['ぽかぽかしています', 'ぽかぽかです'] },
    conversation: { themeJa: 'ぽかぽか陽気の日の過ごし方を話す',
      starterJa: 'ぽかぽかした日は、外に出たくなりますか？', starterZh: '暖洋洋的日子你想出门吗？',
      targetExpressions: ['ぽかぽか'], followUpJa: '日本の春と故郷の春、どちらが好きですか？',
      followUpZh: '日本的春天和家乡的春天你更喜欢哪个？' },
    difficulty: 'basic' }),
  d({ id: 'ono-bokoboko', sourceCandidateId: '7aafe6bc2ab98cc9', surface: 'ぼこぼこ', kana: 'ぼこぼこ',
    category: 'gitaigo', usagePatterns: ['da-na', 'ni-naru'],
    meaningJa: '表面に穴やくぼみが多い様子', meaningZh: '（状态）坑坑洼洼、凹凸不平',
    nuanceZh: '道路の穴・へこんだ車体など。「ぼこぼこにする」は暴力表現（打得鼻青脸肿）なので学習者は状態描写用法を中心に',
    similarJa: ['でこぼこ', 'ざらざら'],
    examples: [
      { ja: 'この道はぼこぼこしていて、自転車だと危ないです。', zh: '这条路坑坑洼洼，骑自行车很危险。' },
      { ja: '雹が降って、車がぼこぼこになりました。', zh: '下了冰雹，车被砸得坑坑洼洼。' },
    ],
    commonMistakeZh: '「でこぼこ」（凹凸）とほぼ同義だが「ぼこぼこ」の方が崩れた・傷んだ印象が強い。暴力の意味もあるので使用場面に注意',
    recognition: { promptZh: '「道がぼこぼこ」是什么路况？',
      options: ['坑坑洼洼', '平坦光滑', '笔直宽阔', '刚铺好的'],
      answerIndex: 0, feedbackZh: '穴だらけ =「ぼこぼこ」' },
    production: { promptJa: '悪い道路の状態を「ぼこぼこ」で言ってください。',
      promptZh: '用「ぼこぼこ」描述糟糕的路面。',
      expected: ['ぼこぼこ'], acceptable: ['ぼこぼこです', 'ぼこぼこしています'] },
    conversation: { themeJa: '道路・自転車事情を話す',
      starterJa: '家の近くに、ぼこぼこした道はありますか？', starterZh: '你家附近有坑洼的路吗？',
      targetExpressions: ['ぼこぼこ'], followUpJa: '日本の道路は整備されていると感じますか？',
      followUpZh: '你觉得日本的道路维护得好吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-bosabosa', sourceCandidateId: 'd452b25cdbf0cd85', surface: 'ぼさぼさ', kana: 'ぼさぼさ',
    category: 'gitaigo', usagePatterns: ['da-na', 'suru'],
    meaningJa: '髪が乱れて整っていない様子', meaningZh: '（状态）（头发）乱蓬蓬、鸡窝头',
    nuanceZh: '寝起き・手入れしていない髪。「ぼさぼさのまま出かける」は身だしなみ話題の定番',
    similarJa: ['くしゃくしゃ', 'さらさら'],
    examples: [
      { ja: '寝坊して、髪がぼさぼさのまま出勤しました。', zh: '睡过头，顶着乱蓬蓬的头发去上班。' },
      { ja: '在宅勤務の日は、髪がぼさぼさでも気になりません。', zh: '居家办公的日子头发乱糟糟也无所谓。' },
    ],
    commonMistakeZh: '「ぼさぼさ」はほぼ髪専用。服のしわは「よれよれ」「しわしわ」。乱れの対象で語を選ぶ',
    recognition: { promptZh: '「ぼさぼさ」形容什么？',
      options: ['乱蓬蓬的头发', '整齐的西装', '光亮的皮鞋', '干净的房间'],
      answerIndex: 0, feedbackZh: '乱れた髪 =「ぼさぼさ」' },
    production: { promptJa: '寝起きの髪を「ぼさぼさ」で言ってください。',
      promptZh: '用「ぼさぼさ」形容刚睡醒的头发。',
      expected: ['ぼさぼさ'], acceptable: ['ぼさぼさです', 'ぼさぼさでした'] },
    conversation: { themeJa: '朝の身支度の時間を話す',
      starterJa: '朝、髪がぼさぼさのとき、どうやって直しますか？', starterZh: '早上头发乱蓬蓬时你怎么打理？',
      targetExpressions: ['ぼさぼさ'], followUpJa: '朝の準備には何分かかりますか？',
      followUpZh: '早上收拾要花几分钟？' },
    difficulty: 'basic' }),
  d({ id: 'ono-marumaru', sourceCandidateId: '9936c1713b5ea367', surface: 'まるまる', kana: 'まるまる',
    category: 'gitaigo', usagePatterns: ['to-verb', 'suru'],
    meaningJa: '丸くふくらんで太っている様子・丸ごと全部', meaningZh: '（状态）①圆滚滚、胖乎乎 ②整整、全部（まるまる一日）',
    nuanceZh: '①「まるまる太った猫」は可愛い系の丸さ。②「まるまる一日かかった」（花了整整一天）の副詞用法が実用的',
    similarJa: ['ころころ', 'ぽっちゃり'],
    examples: [
      { ja: 'まるまる太った猫が、ひなたで寝ています。', zh: '圆滚滚的猫在向阳处睡觉。' },
      { ja: '引っ越しの片付けに、まるまる二日かかりました。', zh: '收拾搬家的东西花了整整两天。' },
    ],
    commonMistakeZh: '「まるまる一日」=「整整一天」の用法は時間表現として頻出。丸い意味だけで覚えると聞き取れない',
    recognition: { promptZh: '「まるまる一日かかった」是什么意思？',
      options: ['花了整整一天', '只花了一小会', '一天都没花', '花了半天'],
      answerIndex: 0, feedbackZh: '「まるまる＋期間」= 整整〜' },
    production: { promptJa: '時間がかかったことを「まるまる」で言ってください。',
      promptZh: '用「まるまる」说花了很长时间的事。',
      expected: ['まるまる'], acceptable: ['まるまる一日かかりました', 'まるまる二日かかりました'] },
    conversation: { themeJa: '丸一日かかった作業を話す',
      starterJa: '最近、まるまる一日かかった作業はありますか？', starterZh: '最近有花了整整一天的活儿吗？',
      targetExpressions: ['まるまる'], followUpJa: 'まるまる一日自由なら、何をしたいですか？',
      followUpZh: '如果有整整一天自由时间你想做什么？' },
    difficulty: 'plus' }),
  d({ id: 'ono-mukamuka', sourceCandidateId: 'c4bb1b028fe5b943', surface: 'むかむか', kana: 'むかむか',
    category: 'gijougo', usagePatterns: ['suru'],
    meaningJa: '①吐き気がする様子 ②怒りがこみ上げる様子', meaningZh: '（感觉）①恶心想吐 ②窝火、来气',
    nuanceZh: '①二日酔い・乗り物酔いの吐き気（症状表現として実用）。②思い出すたび腹が立つ「むかつく」の元',
    similarJa: ['いらいら', 'きもちわるい'],
    examples: [
      { ja: '二日酔いで、胃がむかむかします。', zh: '宿醉，胃里恶心想吐。' },
      { ja: '失礼なことを言われて、むかむかしました。', zh: '被说了失礼的话，一阵窝火。' },
    ],
    commonMistakeZh: '若者語「むかつく」（气死了）はここから。病院では①の意味で「胃がむかむかする」と伝えると吐き気として通じる',
    recognition: { promptZh: '「胃がむかむかする」是什么症状？',
      options: ['恶心想吐', '肚子饿', '心情很好', '发烧'],
      answerIndex: 0, feedbackZh: '吐き気 =「むかむか」' },
    production: { promptJa: '乗り物酔いの症状を「むかむか」で言ってください。',
      promptZh: '用「むかむか」描述晕车的症状。',
      expected: ['むかむか'], acceptable: ['むかむかします', '胃がむかむかします'] },
    conversation: { themeJa: '乗り物酔いの対策を話す',
      starterJa: 'バスや船で、むかむかしたことがありますか？', starterZh: '坐大巴或船时恶心过吗？',
      targetExpressions: ['むかむか'], followUpJa: '酔いやすいとき、どんな対策をしますか？',
      followUpZh: '容易晕车时你有什么对策？' },
    difficulty: 'basic' }),
  d({ id: 'ono-mukimuki', sourceCandidateId: 'c64d68034117d4d8', surface: 'むきむき', kana: 'むきむき',
    category: 'gitaigo', usagePatterns: ['da-na'],
    meaningJa: '筋肉が発達してたくましい様子', meaningZh: '（状态）肌肉发达、浑身腱子肉',
    nuanceZh: 'ジムのトレーナー・ボディビルダー。カジュアルで少しユーモラスな響き。褒め言葉として使える',
    similarJa: ['がっしり', 'ひょろひょろ'],
    examples: [
      { ja: 'ジムのトレーナーは、むきむきです。', zh: '健身房的教练浑身肌肉。' },
      { ja: '毎日筋トレして、むきむきになりたいです。', zh: '想每天撸铁练出一身肌肉。' },
    ],
    commonMistakeZh: '「むきむき」は筋肉の隆起。ただ体格がいいのは「がっしり」。細身は「ひょろひょろ」。体型3点セットで覚える',
    recognition: { promptZh: '「むきむき」形容哪种体型？',
      options: ['肌肉发达', '瘦竹竿', '圆滚滚', '普通体型'],
      answerIndex: 0, feedbackZh: '筋肉質 =「むきむき」' },
    production: { promptJa: '筋肉がすごい人を「むきむき」で言ってください。',
      promptZh: '用「むきむき」形容肌肉发达的人。',
      expected: ['むきむき'], acceptable: ['むきむきです', 'むきむきになりたいです'] },
    conversation: { themeJa: '筋トレ・運動習慣を話す',
      starterJa: 'むきむきになりたいですか？それとも健康維持で十分ですか？', starterZh: '你想练出肌肉吗？还是保持健康就够？',
      targetExpressions: ['むきむき'], followUpJa: 'ジムに通ったことがありますか？',
      followUpZh: '你去过健身房吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-muzumuzu', sourceCandidateId: '3cb85e04156cf1ca', surface: 'むずむず', kana: 'むずむず',
    category: 'gijougo', usagePatterns: ['suru'],
    meaningJa: 'かゆくて落ち着かない様子・したくてたまらない様子', meaningZh: '（感觉）①（鼻子等）痒痒的 ②手痒痒、跃跃欲试',
    nuanceZh: '①花粉症の鼻のむずむず（春の定番症状）。②「言いたくてむずむずする」（憋不住想说）の比喩も',
    similarJa: ['かゆい', 'うずうず'],
    examples: [
      { ja: '花粉症で、鼻がむずむずします。', zh: '花粉症，鼻子痒痒的。' },
      { ja: '答えを言いたくて、むずむずしました。', zh: '憋着答案不能说，心里直痒痒。' },
    ],
    commonMistakeZh: '「かゆい」はっきりした痒み、「むずむず」はくすぐったい前兆的な痒み。花粉症の症状説明で使い分けると伝わる',
    recognition: { promptZh: '春天「鼻がむずむず」很可能是？',
      options: ['花粉症的征兆', '吃饱了', '感到寒冷', '心情低落'],
      answerIndex: 0, feedbackZh: '花粉症の代表症状 = 鼻のむずむず' },
    production: { promptJa: '花粉症の症状を「むずむず」で言ってください。',
      promptZh: '用「むずむず」描述花粉症的症状。',
      expected: ['むずむず'], acceptable: ['むずむずします', '鼻がむずむずします'] },
    conversation: { themeJa: '花粉症の有無・対策を話す',
      starterJa: '春、鼻がむずむずしますか？花粉症はありますか？', starterZh: '春天鼻子会痒吗？你有花粉症吗？',
      targetExpressions: ['むずむず'], followUpJa: '中国にいたときも、花粉症がありましたか？',
      followUpZh: '在中国时也有花粉症吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-mushamusha', sourceCandidateId: '9d43afc90e1e68e6', surface: 'むしゃむしゃ', kana: 'むしゃむしゃ',
    category: 'giongo', usagePatterns: ['to-verb'],
    meaningJa: '勢いよく食べ続ける様子', meaningZh: '（拟声）大口大口地嚼、狼吞虎咽',
    nuanceZh: '豪快に食べ続ける音。うさぎが野菜を食べる音にも人の爆食にも。品はないが元気な印象',
    similarJa: ['もぐもぐ', 'ぱくぱく'],
    examples: [
      { ja: 'お腹が空いていたので、おにぎりをむしゃむしゃ食べました。', zh: '肚子饿了，大口大口地吃饭团。' },
      { ja: 'うさぎがキャベツをむしゃむしゃ食べています。', zh: '兔子大口嚼着卷心菜。' },
    ],
    commonMistakeZh: '「むしゃむしゃ」豪快、「もぐもぐ」口を閉じて咀嚼。食事マナーの文脈では「もぐもぐ」が上品',
    recognition: { promptZh: '「むしゃむしゃ」是怎么吃？',
      options: ['大口大口不停地嚼', '小口优雅地吃', '不吃', '只喝汤'],
      answerIndex: 0, feedbackZh: '豪快な食べ方 =「むしゃむしゃ」' },
    production: { promptJa: 'お腹が空いて食べた様子を「むしゃむしゃ」で言ってください。',
      promptZh: '用「むしゃむしゃ」描述饿了大吃的样子。',
      expected: ['むしゃむしゃ'], acceptable: ['むしゃむしゃ食べました', 'むしゃむしゃ食べています'] },
    conversation: { themeJa: 'お腹ぺこぺこの時の食事を話す',
      starterJa: 'すごくお腹が空いたとき、何をむしゃむしゃ食べたいですか？', starterZh: '特别饿的时候你想大口吃什么？',
      targetExpressions: ['むしゃむしゃ'], followUpJa: '人前では食べ方に気をつけますか？',
      followUpZh: '在人前吃饭你会注意吃相吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-meramera', sourceCandidateId: 'a271df9951ba0b30', surface: 'めらめら', kana: 'めらめら',
    category: 'gitaigo', usagePatterns: ['to-verb'],
    meaningJa: '炎が勢いよく燃え上がる様子', meaningZh: '（状态）（火焰）熊熊燃烧、（斗志）燃起来',
    nuanceZh: '実際の炎と「闘志がめらめら燃える」（斗志熊熊）の比喩。スポーツ・仕事のやる気表現として使える',
    similarJa: ['ぼうぼう', 'ちらちら'],
    examples: [
      { ja: 'キャンプファイヤーが、めらめら燃えています。', zh: '营火熊熊燃烧。' },
      { ja: 'ライバルを見て、闘志がめらめら燃えてきました。', zh: '看到对手，斗志熊熊燃烧起来。' },
    ],
    commonMistakeZh: '中文「燃起来了」の感覚に近い比喩用法あり。嫉妬の炎にも使う（嫉妬でめらめら）',
    recognition: { promptZh: '「闘志がめらめら」是什么状态？',
      options: ['斗志熊熊燃烧', '完全没干劲', '很困', '很冷静'],
      answerIndex: 0, feedbackZh: '燃え上がるやる気 =「めらめら」' },
    production: { promptJa: 'やる気が出た瞬間を「めらめら」で言ってください。',
      promptZh: '用「めらめら」说斗志燃起的瞬间。',
      expected: ['めらめら'], acceptable: ['めらめら燃えてきました', 'めらめらしてきました'] },
    conversation: { themeJa: 'やる気に火がつく瞬間を話す',
      starterJa: 'どんなとき、やる気がめらめら燃えますか？', starterZh: '什么时候你的干劲会熊熊燃烧？',
      targetExpressions: ['めらめら'], followUpJa: 'ライバルがいると頑張れるタイプですか？',
      followUpZh: '有对手你会更努力吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-meromero', sourceCandidateId: 'ab936b5dc43be821', surface: 'めろめろ', kana: 'めろめろ',
    category: 'gijougo', usagePatterns: ['da-na', 'ni-naru'],
    meaningJa: '夢中になって理性を失うほど好きな様子', meaningZh: '（状态）神魂颠倒、爱得晕头转向、被迷得不行',
    nuanceZh: '恋人・アイドル・孫・ペットに骨抜きの状態。「孫にめろめろ」（被孙子迷得不行）は微笑ましい定番',
    similarJa: ['ぞっこん', 'でれでれ'],
    examples: [
      { ja: '祖父は、初孫にめろめろです。', zh: '爷爷被第一个孙子迷得神魂颠倒。' },
      { ja: '推しのアイドルに、めろめろになっています。', zh: '被本命偶像迷得晕头转向。' },
    ],
    commonMistakeZh: '「大好き」より理性を失った度合いが強い。ビジネス文書には不向きなカジュアル語',
    recognition: { promptZh: '「孫にめろめろ」的爷爷是什么状态？',
      options: ['疼孙子疼得不行', '讨厌孙子', '没见过孙子', '在教训孙子'],
      answerIndex: 0, feedbackZh: '夢中で骨抜き =「めろめろ」' },
    production: { promptJa: '夢中になっているものを「めろめろ」で言ってください。',
      promptZh: '用「めろめろ」说你着迷的对象。',
      expected: ['めろめろ'], acceptable: ['めろめろです', 'めろめろになっています'] },
    conversation: { themeJa: '推し・夢中なものを語る',
      starterJa: '今、めろめろになっているもの（推し・ペットなど）はありますか？', starterZh: '现在有让你着迷的对象（本命、宠物等）吗？',
      targetExpressions: ['めろめろ'], followUpJa: 'どこがそんなに魅力的ですか？',
      followUpZh: '到底哪里那么有魅力？' },
    difficulty: 'plus' }),
  d({ id: 'ono-mokumoku', sourceCandidateId: '67b76b18fb87e470', surface: 'もくもく', kana: 'もくもく',
    category: 'gitaigo', usagePatterns: ['to-verb', 'suru'],
    meaningJa: '煙や雲が盛んに湧き上がる様子', meaningZh: '（状态）（烟、云）滚滚升腾、一团团冒出',
    nuanceZh: '煙突の煙・入道雲・湯気。※同音の「黙々と働く」（もくもく=默默）は漢語で別語。混同注意',
    similarJa: ['ゆらゆら', 'ぷかぷか'],
    examples: [
      { ja: '煙突から煙がもくもく出ています。', zh: '烟囱里滚滚地冒着烟。' },
      { ja: '夏の空に、入道雲がもくもく湧いています。', zh: '夏日天空积雨云一团团涌起。' },
    ],
    commonMistakeZh: '「黙々と」（默默地）と発音が同じで紛らわしい。「煙がもくもく」はオノマトペ、「黙々と働く」は漢語副詞',
    recognition: { promptZh: '「もくもく」（拟态词）形容什么？',
      options: ['烟滚滚上升', '安静地工作', '快速奔跑', '大声唱歌'],
      answerIndex: 0, feedbackZh: '煙・雲の湧き上がり =「もくもく」' },
    production: { promptJa: '煙や雲の様子を「もくもく」で言ってください。',
      promptZh: '用「もくもく」描述烟或云。',
      expected: ['もくもく'], acceptable: ['もくもく出ています', 'もくもく湧いています'] },
    conversation: { themeJa: '夏の空・雲の思い出を話す',
      starterJa: '夏のもくもくした入道雲を見ると、何を思い出しますか？', starterZh: '看到夏天翻滚的积雨云你会想起什么？',
      targetExpressions: ['もくもく'], followUpJa: '「黙々と働く」という言葉も聞いたことがありますか？',
      followUpZh: '你也听过「黙々と働く」这个词吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-mogumogu', sourceCandidateId: 'a3909cade803de06', surface: 'もぐもぐ', kana: 'もぐもぐ',
    category: 'gitaigo', usagePatterns: ['to-verb', 'suru'],
    meaningJa: '口を閉じてよく噛んで食べる様子', meaningZh: '（状态）闭着嘴嚼、嚼个不停',
    nuanceZh: '口を閉じた上品な咀嚼。子どもへの「もぐもぐしようね」は食育の定番。口いっぱいで話せない様子にも',
    similarJa: ['むしゃむしゃ', 'ぱくぱく'],
    examples: [
      { ja: '口にいっぱい入れて、もぐもぐしています。', zh: '嘴里塞得满满的，嚼个不停。' },
      { ja: 'よく噛んで、もぐもぐ食べましょう。', zh: '要好好咀嚼慢慢吃。' },
    ],
    commonMistakeZh: '「もぐもぐ」は口を閉じた咀嚼でマナー的に良い方。「くちゃくちゃ」（吧唧嘴）は最悪のマナー violation。対で覚える',
    recognition: { promptZh: '礼仪上好的吃法是？',
      options: ['もぐもぐ（闭嘴嚼）', 'くちゃくちゃ（吧唧嘴）', '张着嘴嚼', '边说话边喷饭'],
      answerIndex: 0, feedbackZh: '口を閉じて噛む =「もぐもぐ」' },
    production: { promptJa: 'よく噛んで食べる様子を「もぐもぐ」で言ってください。',
      promptZh: '用「もぐもぐ」描述细嚼慢咽。',
      expected: ['もぐもぐ'], acceptable: ['もぐもぐ食べます', 'もぐもぐしています'] },
    conversation: { themeJa: '食事のスピード・マナーを話す',
      starterJa: '食べるのは速いですか？もぐもぐゆっくり派ですか？', starterZh: '你吃饭快还是细嚼慢咽派？',
      targetExpressions: ['もぐもぐ'], followUpJa: '日本と中国で、食事マナーの違いを感じますか？',
      followUpZh: '中日的餐桌礼仪你觉得有差异吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-mochimochi', sourceCandidateId: '401a1970982864c0', surface: 'もちもち', kana: 'もちもち',
    category: 'gitaigo', usagePatterns: ['suru', 'da-na'],
    meaningJa: '餅のように弾力があって柔らかい食感', meaningZh: '（状态）软糯Q弹、有嚼劲',
    nuanceZh: '団子・タピオカ・うどん・肌にも。中国語の「Q弹」にほぼ対応。グルメ番組の超頻出語',
    similarJa: ['ふわふわ', 'こしがある'],
    examples: [
      { ja: 'このうどんは、もちもちしていておいしいです。', zh: '这乌冬面Q弹好吃。' },
      { ja: '湯圆は、もちもちした食感が魅力です。', zh: '汤圆的魅力就是软糯Q弹的口感。' },
    ],
    commonMistakeZh: '中文「Q弹」「糯叽叽」に相当。タピオカブームで日本でも大活躍した語。肌の「もちもち肌」は褒め言葉',
    recognition: { promptZh: '「もちもち」最接近中文的哪个词？',
      options: ['Q弹软糯', '干巴巴', '脆脆的', '稀溜溜'],
      answerIndex: 0, feedbackZh: '弾力のある柔らかさ =「もちもち」≈ Q弹' },
    production: { promptJa: '好きなもちもち食品を「もちもち」で言ってください。',
      promptZh: '用「もちもち」说你喜欢的Q弹食物。',
      expected: ['もちもち'], acceptable: ['もちもちしています', 'もちもちです'] },
    conversation: { themeJa: 'もちもち食感の食べ物を語る',
      starterJa: 'もちもちした食べ物で、一番好きなのは何ですか？', starterZh: '软糯Q弹的食物里你最喜欢什么？',
      targetExpressions: ['もちもち'], followUpJa: '中国の「Q弹」という言葉と似ていますね。ほかに対応する言葉はありますか？',
      followUpZh: '和中文的「Q弹」很像吧。还有别的对应词吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-motemote', sourceCandidateId: '99859f29e51dddde', surface: 'もてもて', kana: 'もてもて',
    category: 'gitaigo', usagePatterns: ['da-na'],
    meaningJa: '異性から非常に人気がある様子', meaningZh: '（状态）大受欢迎、桃花旺、万人迷',
    nuanceZh: '「モテる」の強調形。学生時代の思い出話・芸能人の話題で使う軽い表現',
    similarJa: ['もてる', 'ちやほや'],
    examples: [
      { ja: '彼は学生時代、もてもてだったそうです。', zh: '听说他学生时代是万人迷。' },
      { ja: '優しくて料理もできる人は、もてもてです。', zh: '又温柔又会做饭的人特别受欢迎。' },
    ],
    commonMistakeZh: '「人気がある」は万人向け（商品にも）、「もてもて」は恋愛的な人気限定。会社の人気者に使うと誤解を招く',
    recognition: { promptZh: '「もてもて」是哪方面受欢迎？',
      options: ['恋爱方面大受欢迎', '工作能力被认可', '商品畅销', '会读书'],
      answerIndex: 0, feedbackZh: '異性からの人気 =「もてもて」' },
    production: { promptJa: '人気がある人を「もてもて」で言ってください。',
      promptZh: '用「もてもて」形容受欢迎的人。',
      expected: ['もてもて'], acceptable: ['もてもてです', 'もてもてでした'] },
    conversation: { themeJa: 'もてる条件について雑談する',
      starterJa: '日本で「もてもて」な人は、どんな人だと思いますか？', starterZh: '你觉得在日本什么样的人受欢迎？',
      targetExpressions: ['もてもて'], followUpJa: '中国で人気がある条件と違いはありますか？',
      followUpZh: '和中国受欢迎的条件有区别吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-yurayura', sourceCandidateId: '663a3982707333d6', surface: 'ゆらゆら', kana: 'ゆらゆら',
    category: 'gitaigo', usagePatterns: ['to-verb', 'suru'],
    meaningJa: 'ゆっくり揺れ動く様子', meaningZh: '（状态）轻轻摇曳、缓缓晃动',
    nuanceZh: 'ろうそくの炎・カーテン・船・地震の横揺れ。ゆったりした揺れ。激しい揺れは「ぐらぐら」',
    similarJa: ['ぶらぶら', 'ぐらぐら'],
    examples: [
      { ja: 'ろうそくの火が、ゆらゆら揺れています。', zh: '烛火轻轻摇曳。' },
      { ja: '地震で、部屋がゆらゆら揺れました。', zh: '地震时房间缓缓晃动。' },
    ],
    commonMistakeZh: '地震表現: 弱くゆっくり=ゆらゆら、激しい=ぐらぐら。日本生活の地震描写で使い分けられると正確',
    recognition: { promptZh: '「ゆらゆら」是哪种晃动？',
      options: ['缓慢轻柔地摇', '剧烈地摇', '完全不动', '快速旋转'],
      answerIndex: 0, feedbackZh: 'ゆっくりした揺れ =「ゆらゆら」' },
    production: { promptJa: '揺れるものを「ゆらゆら」で言ってください。',
      promptZh: '用「ゆらゆら」描述摇曳的东西。',
      expected: ['ゆらゆら'], acceptable: ['ゆらゆら揺れています', 'ゆらゆらしています'] },
    conversation: { themeJa: '初めて地震を経験した話をする',
      starterJa: '日本で初めて地震のゆらゆらを感じたとき、どうでしたか？', starterZh: '在日本第一次感到地震晃动时你什么反应？',
      targetExpressions: ['ゆらゆら'], followUpJa: '地震のとき、どう行動すればいいか知っていますか？',
      followUpZh: '地震时该怎么做你知道吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-yoreyore', sourceCandidateId: '77422822ee8d3cbb', surface: 'よれよれ', kana: 'よれよれ',
    category: 'gitaigo', usagePatterns: ['da-na', 'ni-naru'],
    meaningJa: '服などが古くなって形が崩れた様子', meaningZh: '（状态）（衣服）旧得变形、皱皱巴巴',
    nuanceZh: '着古したTシャツ・くたびれたスーツ。人にも「よれよれになって帰宅」（疲惫不堪地回家）と使う',
    similarJa: ['しわしわ', 'ぼろぼろ'],
    examples: [
      { ja: 'よれよれのTシャツは、部屋着にしています。', zh: '旧得变形的T恤当家居服穿。' },
      { ja: '残業続きで、よれよれになって帰りました。', zh: '连日加班，疲惫不堪地回了家。' },
    ],
    commonMistakeZh: '「しわしわ」はしわだけ（アイロンで直る）、「よれよれ」は型崩れ（直らない）。買い替えサインが「よれよれ」',
    recognition: { promptZh: '「よれよれのシャツ」是什么状态？',
      options: ['旧得变形走样', '崭新笔挺', '刚熨好', '还带着吊牌'],
      answerIndex: 0, feedbackZh: '型崩れした古着感 =「よれよれ」' },
    production: { promptJa: '古くなった服を「よれよれ」で言ってください。',
      promptZh: '用「よれよれ」形容穿旧的衣服。',
      expected: ['よれよれ'], acceptable: ['よれよれです', 'よれよれになりました'] },
    conversation: { themeJa: '服の買い替えタイミングを話す',
      starterJa: 'よれよれになった服、すぐ捨てますか？部屋着にしますか？', starterZh: '穿旧变形的衣服你马上扔还是当家居服？',
      targetExpressions: ['よれよれ'], followUpJa: '服はどのくらいの頻度で買いますか？',
      followUpZh: '你多久买一次衣服？' },
    difficulty: 'basic' }),
];
