// Phase 3P-3: オノマトペ完成draft教材（監督指示§5-13準拠）。
// 「完成draft」= 必須field（意味・中文・ニュアンス・例文2・誤りやすい点・
// recognition/production問題・会話練習・復習キー・Unit）がすべて揃ったもののみ。
// 揃わない候補はここへ追加せず、completeness manifestに未完成として残す。
// 既存140語のVocabularyItem体系へは統合しない（統合はreuse判断と同じく人間判断後）。
// 出典: Excel「オノマトペ100集（完成版）」（rights: teacher_created_assumed・
// sourceCandidateIdでintake manifestへ追跡可能）。全件draft・labPreview限定表示。

export type OnomatopoeiaCategory =
  | 'giongo'    // 擬音語（実際の音: がらがら・ざあざあ）
  | 'gitaigo'   // 擬態語（様子・状態: きらきら・ぐちゃぐちゃ）
  | 'gijougo';  // 擬情語（気持ち・感覚: いらいら・うきうき）

/** 実際の構文パターン。surfaceだけでなく使い方を教材に持たせる（§7） */
export type OnomatopoeiaUsagePattern =
  | 'suru'      // 〜する／〜している（いらいらする）
  | 'to-verb'   // 〜と＋動詞／副詞的（きらきら（と）輝く）
  | 'da-na'     // 〜だ／〜な（教室ががらがらだ）
  | 'ni-naru';  // 〜になる（ぐちゃぐちゃになる）

export interface OnomatopoeiaDraft {
  id: string;                    // 安定ID（ono-<かなローマ字>）。行順ID禁止
  sourceCandidateId: string;     // intake manifest（content-candidates.json）への追跡
  surface: string;
  kana: string;
  category: OnomatopoeiaCategory;
  usagePatterns: OnomatopoeiaUsagePattern[];
  meaningJa: string;
  meaningZh: string;             // 一語訳で済ませない（拟声/状态/心理の区分を含む・§8）
  nuanceZh: string;              // 使用場面・程度・語気の補足（中文）
  similarJa: string[];           // 類義（区別対象）
  examples: { ja: string; zh: string }[];  // 最低2例（§9: 成人向け場面・訳の一致）
  commonMistakeZh: string;       // 中国語母語者が誤りやすい点
  recognition: {                 // 意味・場面の選択問題（§10）
    promptZh: string; options: string[]; answerIndex: number; feedbackZh: string;
  };
  production: {                  // 場面応答・穴埋め（§10）
    promptJa: string; promptZh: string; expected: string[]; acceptable: string[];
  };
  conversation: {                // 学習者自身が使う練習（§11）
    themeJa: string; starterJa: string; starterZh: string;
    targetExpressions: string[]; followUpJa: string; followUpZh: string;
  };
  reviewKey: string;             // 既存Sense別復習の安定キー（間隔規則は不変・§12）
  unit: 'ono-unit-1';
  difficulty: 'basic' | 'plus';
  publishStatus: 'draft';
  humanReviewed: false;
  approved: false;
}

const d = (p: Omit<OnomatopoeiaDraft, 'unit' | 'publishStatus' | 'humanReviewed' | 'approved' | 'reviewKey'> & { reviewKey?: string }): OnomatopoeiaDraft =>
  ({ unit: 'ono-unit-1', publishStatus: 'draft', humanReviewed: false, approved: false,
     reviewKey: p.id, ...p });

/** バッチ1: Excel先頭22候補のうち21語（あたふた〜ぐっすり）。
 *  未収録1語: ぐったり（例文の場面設計が未了→バッチ2へ。理由はmanifestに記録）。 */
export const ONOMATOPOEIA_DRAFTS_BATCH1: OnomatopoeiaDraft[] = [
  d({ id: 'ono-atafuta', sourceCandidateId: '063e99a2b21e1654', surface: 'あたふた', kana: 'あたふた',
    category: 'gitaigo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '慌てて落ち着きなく動く様子', meaningZh: '（状态）慌慌张张、手忙脚乱的样子',
    nuanceZh: '突发状况让人来不及准备时用。程度比「バタバタ」更慌乱，多含狼狈感',
    similarJa: ['ばたばた', 'おろおろ'],
    examples: [
      { ja: '財布を忘れて、朝からあたふたしました。', zh: '忘带钱包，一早上手忙脚乱。' },
      { ja: '急に会議が入って、あたふたと資料を準備しました。', zh: '突然加了会议，慌慌张张地准备资料。' },
    ],
    commonMistakeZh: '中文常直译成「慌张」，但「あたふた」强调*动作*上的忙乱，只表示心情紧张时用「はらはら」「どきどき」更自然',
    recognition: { promptZh: '哪种场景适合用「あたふた」？',
      options: ['出门前找不到钥匙到处翻', '躺着安静地听音乐', '慢慢地散步', '认真地做笔记'],
      answerIndex: 0, feedbackZh: '「あたふた」用于突发状况下手忙脚乱的动作' },
    production: { promptJa: '朝、寝坊しました。「あたふた」を使って説明してください。',
      promptZh: '早上睡过头了。用「あたふた」说明当时的样子。',
      expected: ['あたふた'], acceptable: ['あたふたしました', 'あたふたと準備しました'] },
    conversation: { themeJa: '慌てた朝の経験を話す',
      starterJa: '朝、時間がなくて慌てたことがありますか？', starterZh: '早上有过时间不够手忙脚乱的经历吗？',
      targetExpressions: ['あたふた'], followUpJa: 'あたふたしないために、何か工夫していますか？',
      followUpZh: '为了不手忙脚乱，你有什么对策吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-atsuatsu', sourceCandidateId: 'af3451f1c90221cb', surface: 'あつあつ', kana: 'あつあつ',
    category: 'gitaigo', usagePatterns: ['da-na'],
    meaningJa: '①食べ物がとても熱いこと ②恋人がとても仲がいいこと', meaningZh: '（状态）①食物滚烫、热腾腾 ②情侣关系火热、如胶似漆',
    nuanceZh: '①是本义，用于刚做好的食物（褒义，好吃的信号）。②是比喻，多带调侃语气',
    similarJa: ['ほかほか', 'らぶらぶ'],
    examples: [
      { ja: 'あつあつのラーメンを食べました。', zh: '吃了热腾腾的拉面。' },
      { ja: 'あの二人は結婚したばかりで、あつあつです。', zh: '那两个人刚结婚，正如胶似漆。' },
    ],
    commonMistakeZh: '形容天气热不能用「あつあつ」（要用「暑い」）。「あつあつ」只用于食物温度和情侣关系',
    recognition: { promptZh: '「あつあつ」不能用于下面哪个？',
      options: ['今天天气', '刚出锅的火锅', '新婚夫妻', '刚炸好的天妇罗'],
      answerIndex: 0, feedbackZh: '天气热用「暑い」。「あつあつ」用于食物和情侣' },
    production: { promptJa: '冬に食べたい料理を「あつあつ」を使って言ってください。',
      promptZh: '用「あつあつ」说说冬天想吃的东西。',
      expected: ['あつあつ'], acceptable: ['あつあつの鍋', 'あつあつのおでん'] },
    conversation: { themeJa: '熱いうちに食べたい料理を話す',
      starterJa: '冬に食べたくなる、あつあつの料理は何ですか？', starterZh: '冬天想吃的热腾腾的食物是什么？',
      targetExpressions: ['あつあつ'], followUpJa: '猫舌ですか？あつあつの料理は苦手ですか？',
      followUpZh: '你怕烫吗？吃不了太烫的东西吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-assari', sourceCandidateId: '3c199140f9172b42', surface: 'あっさり', kana: 'あっさり',
    category: 'gitaigo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '①味が薄くて軽いこと ②物事が簡単に終わること', meaningZh: '（状态）①味道清淡 ②事情轻易地、干脆地（完成/放弃）',
    nuanceZh: '①菜的味道不油腻（多为褒义）。②出乎意料地简单、没有纠缠，如「あっさり勝った」「あっさり諦めた」',
    similarJa: ['さっぱり', 'すんなり'],
    examples: [
      { ja: 'この店のスープはあっさりしていて、飲みやすいです。', zh: '这家店的汤很清淡，很好入口。' },
      { ja: '難しいと思った手続きが、あっさり終わりました。', zh: '本以为很难的手续，轻轻松松就办完了。' },
    ],
    commonMistakeZh: '「あっさり」和「さっぱり」都可译成「清淡/爽口」，但「さっぱり分からない」（完全不懂）的用法「あっさり」没有，不要混用',
    recognition: { promptZh: '「あっさり負けました」是什么意思？',
      options: ['轻易地输了', '味道清淡', '打得很艰苦', '差点赢了'],
      answerIndex: 0, feedbackZh: '「あっさり＋动词」表示事情简单干脆地发生' },
    production: { promptJa: '好きな味を「あっさり」か「こってり」で言ってください。',
      promptZh: '用「あっさり」或「こってり」说说你喜欢的口味。',
      expected: ['あっさり'], acceptable: ['あっさりした料理が好きです', 'あっさり系が好きです'] },
    conversation: { themeJa: '好みの味付けについて話す',
      starterJa: 'ラーメンは、あっさり系とこってり系、どちらが好きですか？', starterZh: '拉面你喜欢清淡系还是浓厚系？',
      targetExpressions: ['あっさり'], followUpJa: '故郷の料理は、あっさりしていますか？',
      followUpZh: '你家乡的菜清淡吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-ichaicha', sourceCandidateId: '8ee7f65e9ac9a101', surface: 'いちゃいちゃ', kana: 'いちゃいちゃ',
    category: 'gitaigo', usagePatterns: ['suru'],
    meaningJa: '恋人同士が人前で仲良くふれあう様子', meaningZh: '（状态）情侣当众亲热、打情骂俏',
    nuanceZh: '多少带「让旁人看不下去」的调侃或批评语气。描写自己时多为自嘲',
    similarJa: ['あつあつ', 'べたべた'],
    examples: [
      { ja: '電車の中でいちゃいちゃしているカップルがいました。', zh: '电车里有一对情侣在卿卿我我。' },
      { ja: '人前でいちゃいちゃするのは、日本では少し恥ずかしいです。', zh: '在日本，当众亲热会让人有点难为情。' },
    ],
    commonMistakeZh: '只用于恋人之间的亲昵。朋友之间关系好不能用「いちゃいちゃ」（用「仲がいい」）',
    recognition: { promptZh: '「いちゃいちゃ」用于谁之间？',
      options: ['情侣之间', '同事之间', '师生之间', '店员和客人之间'],
      answerIndex: 0, feedbackZh: '「いちゃいちゃ」专指恋人间的亲昵行为' },
    production: { promptJa: '公園で見たカップルの様子を「いちゃいちゃ」で言ってください。',
      promptZh: '用「いちゃいちゃ」描述在公园看到的情侣。',
      expected: ['いちゃいちゃ'], acceptable: ['いちゃいちゃしていました'] },
    conversation: { themeJa: '人前での恋人のふるまいについて話す',
      starterJa: '人前でいちゃいちゃするカップルを見て、どう思いますか？', starterZh: '看到当众秀恩爱的情侣你怎么想？',
      targetExpressions: ['いちゃいちゃ'], followUpJa: '中国と日本で、人前でのふるまいに違いがありますか？',
      followUpZh: '中国和日本在当众亲昵方面有差异吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-iraira', sourceCandidateId: '437d0361900d724b', surface: 'いらいら', kana: 'いらいら',
    category: 'gijougo', usagePatterns: ['suru'],
    meaningJa: '思い通りにならず、気持ちが落ち着かない・怒りっぽくなる様子', meaningZh: '（心理）烦躁、焦躁、心里冒火',
    nuanceZh: '事情不顺（等待、堵车、干扰）导致的持续性烦躁。比「怒る」程度轻但持续',
    similarJa: ['むかむか', 'かりかり'],
    examples: [
      { ja: '電車が遅れて、いらいらしました。', zh: '电车晚点，让人烦躁。' },
      { ja: '試験の前は、少しいらいらしやすくなります。', zh: '考试前容易变得焦躁。' },
    ],
    commonMistakeZh: '中文「着急」偏「焦虑担心」时用「はらはら」「そわそわ」更贴切；「いらいら」的核心是*不耐烦・冒火*',
    recognition: { promptZh: '哪种情况最适合「いらいら」？',
      options: ['排队排了40分钟队伍不动', '收到礼物很开心', '看恐怖片很害怕', '睡前放松地看书'],
      answerIndex: 0, feedbackZh: '事情不顺、不耐烦时用「いらいら」' },
    production: { promptJa: '最近いらいらしたことを一つ言ってください。',
      promptZh: '说一件最近让你烦躁的事。',
      expected: ['いらいら'], acceptable: ['いらいらしました', 'いらいらします'] },
    conversation: { themeJa: 'いらいらしたときの解消法を話す',
      starterJa: 'いらいらしたとき、どうやって気分を変えますか？', starterZh: '烦躁的时候你怎么调整心情？',
      targetExpressions: ['いらいら'], followUpJa: '日本の生活で、いらいらすることはありますか？',
      followUpZh: '日本生活中有让你烦躁的事吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-ukiuki', sourceCandidateId: '7c9d6bbf65db60c7', surface: 'うきうき', kana: 'うきうき',
    category: 'gijougo', usagePatterns: ['suru'],
    meaningJa: '楽しみで心が弾む様子', meaningZh: '（心理）兴高采烈、心情雀跃、期待得坐不住',
    nuanceZh: '对*即将发生的*开心事（约会、旅行、周末）的期待感。心情轻飘飘的正面词',
    similarJa: ['わくわく', 'るんるん'],
    examples: [
      { ja: '明日から旅行なので、うきうきしています。', zh: '明天开始去旅行，心情雀跃。' },
      { ja: '給料日の前は、少しうきうきします。', zh: '发工资前总有点雀跃。' },
    ],
    commonMistakeZh: '「わくわく」偏「对内容的期待・兴奋」，「うきうき」偏「心情轻快・脚步都轻了」。译成中文都是「兴奋」但侧重不同',
    recognition: { promptZh: '「うきうき」描述哪种心情？',
      options: ['期待周末约会心情轻快', '工作失误后沮丧', '深夜一个人害怕', '对朋友的话生气'],
      answerIndex: 0, feedbackZh: '「うきうき」= 对开心的事满心期待、心情轻快' },
    production: { promptJa: '最近うきうきした予定を言ってください。',
      promptZh: '说说最近让你雀跃的安排。',
      expected: ['うきうき'], acceptable: ['うきうきしています', 'うきうきしました'] },
    conversation: { themeJa: '楽しみな予定について話す',
      starterJa: '今、うきうきするような予定がありますか？', starterZh: '现在有让你雀跃的安排吗？',
      targetExpressions: ['うきうき'], followUpJa: 'その日が来たら、まず何をしますか？',
      followUpZh: '那天到了你会先做什么？' },
    difficulty: 'basic' }),
  d({ id: 'ono-ukkari', sourceCandidateId: '43eec80299c2839b', surface: 'うっかり', kana: 'うっかり',
    category: 'gitaigo', usagePatterns: ['to-verb', 'suru'],
    meaningJa: '注意が足りず、つい忘れたり間違えたりする様子', meaningZh: '（状态）一不留神、不小心（忘记/搞错）',
    nuanceZh: '无恶意的疏忽。常与「忘れる」「間違える」搭配，道歉时用可以减轻责任感',
    similarJa: ['つい', 'ぼんやり'],
    examples: [
      { ja: '会議の時間をうっかり忘れました。', zh: '一不留神忘了开会时间。' },
      { ja: 'うっかりして、駅を乗り過ごしました。', zh: '一走神，坐过站了。' },
    ],
    commonMistakeZh: '「うっかり」是副词性用法为主（うっかり忘れた）。中文「马虎」是性格评价，日语说性格用「そそっかしい」',
    recognition: { promptZh: '「うっかり」最常和哪个词搭配？',
      options: ['忘れる', '走る', '食べる', '買う'],
      answerIndex: 0, feedbackZh: '「うっかり忘れる」是最典型的搭配' },
    production: { promptJa: '最近うっかりした失敗を言ってください。',
      promptZh: '说一件最近不小心搞砸的小事。',
      expected: ['うっかり'], acceptable: ['うっかり忘れました', 'うっかりしていました'] },
    conversation: { themeJa: 'うっかりミスの経験を話す',
      starterJa: '最近、何かうっかりしたことがありますか？', starterZh: '最近有一不留神出的错吗？',
      targetExpressions: ['うっかり'], followUpJa: 'うっかりミスを防ぐために、何かしていますか？',
      followUpZh: '为了防止疏忽出错你做些什么？' },
    difficulty: 'basic' }),
  d({ id: 'ono-utouto', sourceCandidateId: '20c85833ac20ec2b', surface: 'うとうと', kana: 'うとうと',
    category: 'gitaigo', usagePatterns: ['suru'],
    meaningJa: '眠くて浅く眠りかける様子', meaningZh: '（状态）打瞌睡、迷迷糊糊快睡着',
    nuanceZh: '不该睡的场合（电车里、开会中、看电视时）快睡着的浅睡状态。深睡是「ぐっすり」',
    similarJa: ['うつらうつら', 'こっくり'],
    examples: [
      { ja: '電車の中で、ついうとうとしてしまいました。', zh: '在电车里不知不觉打起了瞌睡。' },
      { ja: '昼ごはんの後は、仕事中にうとうとしやすいです。', zh: '午饭后工作时容易犯困打盹。' },
    ],
    commonMistakeZh: '「うとうと」（浅睡・打盹）和「ぐっすり」（熟睡）方向相反。「睡得很香」不能用「うとうと」',
    recognition: { promptZh: '「うとうと」是哪种状态？',
      options: ['电车里迷糊快睡着', '晚上熟睡8小时', '失眠睡不着', '早上精神地起床'],
      answerIndex: 0, feedbackZh: '「うとうと」= 浅浅地打瞌睡' },
    production: { promptJa: 'どんなときにうとうとしますか？「うとうと」を使って答えてください。',
      promptZh: '你什么时候会打瞌睡？用「うとうと」回答。',
      expected: ['うとうと'], acceptable: ['うとうとします', 'うとうとしてしまいます'] },
    conversation: { themeJa: '眠くなる場面について話す',
      starterJa: '電車でうとうとして、乗り過ごしたことがありますか？', starterZh: '有没有在电车上打瞌睡坐过站的经历？',
      targetExpressions: ['うとうと'], followUpJa: '眠くなったとき、どうやって我慢しますか？',
      followUpZh: '犯困的时候你怎么撑住？' },
    difficulty: 'basic' }),
  d({ id: 'ono-uruuru', sourceCandidateId: 'e604eeb07c83382d', surface: 'うるうる', kana: 'うるうる',
    category: 'gijougo', usagePatterns: ['suru'],
    meaningJa: '感動などで涙が出そうになる様子', meaningZh: '（心理・状态）眼眶湿润、热泪盈眶',
    nuanceZh: '感动或委屈时「眼里含泪但还没流下来」。大哭是「わんわん」，无声流泪是「ぽろぽろ」',
    similarJa: ['じんわり', 'ぽろぽろ'],
    examples: [
      { ja: '映画のラストで、目がうるうるしました。', zh: '电影结尾看得眼眶湿润。' },
      { ja: '子どもの入学式で、うるうるしてしまいました。', zh: '孩子的入学典礼上不禁热泪盈眶。' },
    ],
    commonMistakeZh: '「うるうる」停在「将哭未哭」。已经流泪要用「涙が出た」「ぽろぽろ泣いた」',
    recognition: { promptZh: '「目がうるうるする」是什么状态？',
      options: ['眼眶含泪快哭了', '大声痛哭', '眼睛很干', '开心大笑'],
      answerIndex: 0, feedbackZh: '「うるうる」= 泪水在眼眶里打转' },
    production: { promptJa: '感動してうるうるした経験を言ってください。',
      promptZh: '说一次感动到眼眶湿润的经历。',
      expected: ['うるうる'], acceptable: ['うるうるしました', '目がうるうるしました'] },
    conversation: { themeJa: '感動した映画・場面を話す',
      starterJa: '最近、うるうるした映画や動画がありますか？', starterZh: '最近有让你眼眶湿润的电影或视频吗？',
      targetExpressions: ['うるうる'], followUpJa: 'どんな場面に弱いですか？家族もの？動物もの？',
      followUpZh: '你最吃哪种场面？亲情类？动物类？' },
    difficulty: 'plus' }),
  d({ id: 'ono-urouro', sourceCandidateId: '955cb050383fd52c', surface: 'うろうろ', kana: 'うろうろ',
    category: 'gitaigo', usagePatterns: ['suru'],
    meaningJa: '行き先が決まらず、同じあたりを行ったり来たりする様子', meaningZh: '（状态）来回转悠、徘徊、瞎晃',
    nuanceZh: '迷路或没目的地转来转去。在别人家或店里「うろうろ」会显得可疑，含轻微负面色彩',
    similarJa: ['きょろきょろ', 'ぶらぶら'],
    examples: [
      { ja: '道に迷って、駅の前をうろうろしました。', zh: '迷了路，在车站前来回转悠。' },
      { ja: '知らない人が家の前をうろうろしていて、少し怖かったです。', zh: '陌生人在家门口转来转去，有点吓人。' },
    ],
    commonMistakeZh: '悠闲散步逛街用「ぶらぶら」（中性・愉快）；「うろうろ」是找不到方向的徘徊，语感不同',
    recognition: { promptZh: '哪个场景是「うろうろ」？',
      options: ['迷路后在同一路口来回走', '周末悠闲地逛商店街', '直线跑向目的地', '坐着不动等人'],
      answerIndex: 0, feedbackZh: '没方向地来回走 =「うろうろ」；悠闲闲逛 =「ぶらぶら」' },
    production: { promptJa: '道に迷ったときの様子を「うろうろ」で言ってください。',
      promptZh: '用「うろうろ」描述你迷路时的样子。',
      expected: ['うろうろ'], acceptable: ['うろうろしました', 'うろうろしてしまいました'] },
    conversation: { themeJa: '道に迷った経験を話す',
      starterJa: '日本で道に迷って、うろうろしたことがありますか？', starterZh: '在日本迷过路、来回转悠过吗？',
      targetExpressions: ['うろうろ'], followUpJa: '迷ったとき、人に聞きますか？地図を見ますか？',
      followUpZh: '迷路时你问人还是看地图？' },
    difficulty: 'basic' }),
  d({ id: 'ono-odoodo', sourceCandidateId: '6aa10b109227beb4', surface: 'おどおど', kana: 'おどおど',
    category: 'gijougo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '自信がなく、不安そうにびくびくしている様子', meaningZh: '（心理）畏畏缩缩、惴惴不安、怯生生',
    nuanceZh: '在陌生环境或严厉的人面前不敢抬头、声音变小的状态。含「缺乏自信」的评价',
    similarJa: ['びくびく', 'そわそわ'],
    examples: [
      { ja: '面接で、おどおどしてしまいました。', zh: '面试时紧张得畏畏缩缩。' },
      { ja: '日本語に自信がなくて、電話のとき、おどおどします。', zh: '对日语没自信，打电话时总是怯生生的。' },
    ],
    commonMistakeZh: '「緊張する」是中性的紧张；「おどおど」带「胆怯、没自信」的负面观感，描述别人时要注意',
    recognition: { promptZh: '「おどおど」的人是什么样子？',
      options: ['不敢看对方、声音很小', '自信满满地发言', '生气地大声说话', '开心地笑'],
      answerIndex: 0, feedbackZh: '「おどおど」= 不安、没自信的样子' },
    production: { promptJa: '初めての場面でおどおどした経験を言ってください。',
      promptZh: '说一次在陌生场合畏畏缩缩的经历。',
      expected: ['おどおど'], acceptable: ['おどおどしました', 'おどおどしてしまいました'] },
    conversation: { themeJa: '緊張する場面と克服法を話す',
      starterJa: 'どんな場面で、おどおどしてしまいますか？', starterZh: '你在什么场合会畏畏缩缩？',
      targetExpressions: ['おどおど'], followUpJa: '堂々と話すために、何かコツがありますか？',
      followUpZh: '为了从容说话你有什么诀窍？' },
    difficulty: 'plus' }),
  d({ id: 'ono-gakkari', sourceCandidateId: '911c6b734d31d9f9', surface: 'がっかり', kana: 'がっかり',
    category: 'gijougo', usagePatterns: ['suru'],
    meaningJa: '期待が外れて落ち込む様子', meaningZh: '（心理）失望、泄气、大失所望',
    nuanceZh: '期待落空时的失落。「残念」偏「遗憾（客观）」，「がっかり」偏「情绪上的失落」',
    similarJa: ['しょんぼり', 'がくっと'],
    examples: [
      { ja: '楽しみにしていた店が休みで、がっかりしました。', zh: '期待已久的店没开门，太失望了。' },
      { ja: '試験の結果を見て、がっかりしました。', zh: '看到考试结果，很泄气。' },
    ],
    commonMistakeZh: '对人「你让我失望」直译「あなたにがっかりした」语气很重，商务上慎用；表遗憾用「残念です」更安全',
    recognition: { promptZh: '哪种情况用「がっかり」？',
      options: ['期待的演唱会取消了', '中了彩票', '朋友准时到了', '天气和预报一样'],
      answerIndex: 0, feedbackZh: '期待落空 →「がっかり」' },
    production: { promptJa: '最近がっかりしたことを一つ言ってください。',
      promptZh: '说一件最近让你失望的事。',
      expected: ['がっかり'], acceptable: ['がっかりしました', 'がっかりです'] },
    conversation: { themeJa: '期待と違った経験を話す',
      starterJa: '日本で、期待と違ってがっかりしたことがありますか？', starterZh: '在日本有过期待落空而失望的事吗？',
      targetExpressions: ['がっかり'], followUpJa: '逆に、期待以上でうれしかったことは？',
      followUpZh: '反过来，有超出期待的惊喜吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-garagara', sourceCandidateId: '55dec0f747037ca1', surface: 'がらがら', kana: 'がらがら',
    category: 'gitaigo', usagePatterns: ['da-na'],
    meaningJa: '中に人や物がほとんどなく、空いている様子', meaningZh: '（状态）空荡荡、（电车/店里）没什么人',
    nuanceZh: '电车、餐厅、电影院等「本该有人却很空」。另有拟声用法（がらがらと戸を開ける）和嗓子哑（声ががらがら）',
    similarJa: ['すかすか', 'ひっそり'],
    examples: [
      { ja: '平日の昼間なので、電車はがらがらでした。', zh: '工作日的白天，电车空荡荡的。' },
      { ja: '風邪で声ががらがらになりました。', zh: '感冒了，嗓子变得沙哑。' },
    ],
    commonMistakeZh: '「がらがら」（空）的反义是「ぎっしり」「満員」。形容店里冷清也可用，但当着店员面说不礼貌',
    recognition: { promptZh: '「電車ががらがら」是什么状态？',
      options: ['车厢几乎没人', '车厢挤满了人', '电车晚点了', '电车很快'],
      answerIndex: 0, feedbackZh: '「がらがら」= 空荡荡' },
    production: { promptJa: '空いていた場所の様子を「がらがら」で言ってください。',
      promptZh: '用「がらがら」描述你见过的很空的场所。',
      expected: ['がらがら'], acceptable: ['がらがらでした', 'がらがらです'] },
    conversation: { themeJa: '混んでいる時間・空いている時間を話す',
      starterJa: 'あなたの使う電車は、何時ごろ、がらがらになりますか？', starterZh: '你坐的电车几点左右会变空？',
      targetExpressions: ['がらがら'], followUpJa: '混んでいる電車を避けるために、何かしていますか？',
      followUpZh: '为了避开拥挤的电车你会做什么？' },
    difficulty: 'basic' }),
  d({ id: 'ono-gisshiri', sourceCandidateId: '7013cb010316bbe8', surface: 'ぎっしり', kana: 'ぎっしり',
    category: 'gitaigo', usagePatterns: ['to-verb'],
    meaningJa: '隙間なく詰まっている様子', meaningZh: '（状态）满满当当、塞得密密实实',
    nuanceZh: '空间或日程「毫无空隙」。「予定がぎっしり」（日程排满）是高频用法',
    similarJa: ['びっしり', 'ぱんぱん'],
    examples: [
      { ja: '来週は予定がぎっしり詰まっています。', zh: '下周日程排得满满当当。' },
      { ja: 'お弁当箱に、おかずがぎっしり入っています。', zh: '便当盒里菜塞得满满的。' },
    ],
    commonMistakeZh: '「ぎっしり」多接「詰まる/入る」。人多拥挤（电车）常用「ぎゅうぎゅう」，注意分工',
    recognition: { promptZh: '「予定がぎっしり」是什么意思？',
      options: ['日程排得满满的', '日程全是空的', '忘了日程', '日程被取消'],
      answerIndex: 0, feedbackZh: '「ぎっしり」= 满满地塞着，没有空隙' },
    production: { promptJa: '忙しい週の予定を「ぎっしり」で言ってください。',
      promptZh: '用「ぎっしり」说说忙碌的一周。',
      expected: ['ぎっしり'], acceptable: ['ぎっしりです', 'ぎっしり詰まっています'] },
    conversation: { themeJa: '予定の詰まり具合を話す',
      starterJa: '今週の予定は、ぎっしりですか？余裕がありますか？', starterZh: '这周日程是排满了还是比较宽松？',
      targetExpressions: ['ぎっしり'], followUpJa: '予定がぎっしりの週は、どうやって休みますか？',
      followUpZh: '日程排满的一周你怎么休息？' },
    difficulty: 'basic' }),
  d({ id: 'ono-kyorokyoro', sourceCandidateId: 'e94a654c39308276', surface: 'きょろきょろ', kana: 'きょろきょろ',
    category: 'gitaigo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '落ち着かずに周りをあちこち見回す様子', meaningZh: '（状态）东张西望、四处张望',
    nuanceZh: '找东西/人或不安时的左顾右盼。在正式场合「きょろきょろしない」是常见提醒',
    similarJa: ['うろうろ', 'ちらちら'],
    examples: [
      { ja: '初めての駅で、出口が分からず、きょろきょろしました。', zh: '第一次到这个车站，找不到出口，东张西望。' },
      { ja: '待ち合わせの相手を探して、きょろきょろ見回しました。', zh: '找约好的人，四处张望。' },
    ],
    commonMistakeZh: '「うろうろ」是*脚*来回走，「きょろきょろ」是*眼睛*来回看。可以站着きょろきょろ',
    recognition: { promptZh: '「きょろきょろ」动的是哪里？',
      options: ['眼睛・视线', '脚', '手', '嘴'],
      answerIndex: 0, feedbackZh: '「きょろきょろ」= 视线四处张望' },
    production: { promptJa: '人を探しているときの様子を「きょろきょろ」で言ってください。',
      promptZh: '用「きょろきょろ」描述找人时的样子。',
      expected: ['きょろきょろ'], acceptable: ['きょろきょろしました', 'きょろきょろ探しました'] },
    conversation: { themeJa: '初めての場所での行動を話す',
      starterJa: '初めての場所で、きょろきょろしてしまうタイプですか？', starterZh: '在陌生的地方你会东张西望吗？',
      targetExpressions: ['きょろきょろ'], followUpJa: '迷わないために、事前に何を調べますか？',
      followUpZh: '为了不迷路你会提前查什么？' },
    difficulty: 'basic' }),
  d({ id: 'ono-kirakira', sourceCandidateId: 'b5cfc9e134272d13', surface: 'きらきら', kana: 'きらきら',
    category: 'gitaigo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '光が細かく美しく輝く様子', meaningZh: '（状态）闪闪发光、亮晶晶',
    nuanceZh: '星星、宝石、水面等美丽的闪耀。也比喻「眼睛发亮」「闪闪发光的人生」等正面形象',
    similarJa: ['ぴかぴか', 'ぎらぎら'],
    examples: [
      { ja: '夜空に星がきらきら輝いています。', zh: '夜空中星星闪闪发光。' },
      { ja: '子どもたちは目をきらきらさせて話を聞いていました。', zh: '孩子们眼睛发亮地听着故事。' },
    ],
    commonMistakeZh: '「ぎらぎら」（刺眼、油光、欲望感）是负面版本。夏天的烈日是「ぎらぎら」不是「きらきら」',
    recognition: { promptZh: '哪个用「きらきら」不自然？',
      options: ['盛夏刺眼的烈日', '夜空的星星', '钻石戒指', '孩子发亮的眼睛'],
      answerIndex: 0, feedbackZh: '刺眼的强光用「ぎらぎら」' },
    production: { promptJa: 'きれいだと思った景色を「きらきら」で言ってください。',
      promptZh: '用「きらきら」描述你觉得美的景色。',
      expected: ['きらきら'], acceptable: ['きらきらしていました', 'きらきら輝いていました'] },
    conversation: { themeJa: 'きれいだった景色を話す',
      starterJa: '日本で見た、きらきらした景色はありますか？', starterZh: '在日本见过什么闪闪发光的景色吗？',
      targetExpressions: ['きらきら'], followUpJa: '夜景と星空、どちらが好きですか？',
      followUpZh: '夜景和星空你更喜欢哪个？' },
    difficulty: 'basic' }),
  d({ id: 'ono-girigiri', sourceCandidateId: '16e22c6efe991c6b', surface: 'ぎりぎり', kana: 'ぎりぎり',
    category: 'gitaigo', usagePatterns: ['da-na', 'to-verb'],
    meaningJa: '限界に非常に近く、余裕がない様子', meaningZh: '（状态）擦边、勉勉强强、压线（赶上/及格）',
    nuanceZh: '时间、金钱、分数等「差一点就不行」。「ぎりぎりセーフ」（压线过关）是常用口语',
    similarJa: ['すれすれ', 'かつかつ'],
    examples: [
      { ja: '電車にぎりぎり間に合いました。', zh: '勉勉强强赶上了电车。' },
      { ja: '締め切りぎりぎりにレポートを出しました。', zh: '踩着截止时间交了报告。' },
    ],
    commonMistakeZh: '「ぎりぎり」既可作副词（ぎりぎり間に合う）也可接名词（ぎりぎりの生活）。中文「极限」是名词，注意词性差',
    recognition: { promptZh: '「ぎりぎりセーフ」是什么意思？',
      options: ['差点不行但勉强过关', '彻底失败了', '提前很久完成', '放弃了'],
      answerIndex: 0, feedbackZh: '「ぎりぎりセーフ」= 压线安全过关' },
    production: { promptJa: '時間に間に合った経験を「ぎりぎり」で言ってください。',
      promptZh: '用「ぎりぎり」说一次勉强赶上的经历。',
      expected: ['ぎりぎり'], acceptable: ['ぎりぎり間に合いました', 'ぎりぎりでした'] },
    conversation: { themeJa: '時間の使い方のタイプを話す',
      starterJa: '待ち合わせは早めに着くタイプですか？ぎりぎりのタイプですか？', starterZh: '赴约你是提前到还是踩点到？',
      targetExpressions: ['ぎりぎり'], followUpJa: 'ぎりぎりになってしまう原因は何だと思いますか？',
      followUpZh: '你觉得总是踩点的原因是什么？' },
    difficulty: 'basic' }),
  d({ id: 'ono-guigui', sourceCandidateId: '2498bf0e63ac3a21', surface: 'ぐいぐい', kana: 'ぐいぐい',
    category: 'gitaigo', usagePatterns: ['to-verb'],
    meaningJa: '力強く押したり引いたり、勢いよく進む様子', meaningZh: '（状态）一个劲儿地（拉/推/喝/逼近）、势头很猛',
    nuanceZh: '物理上用力连续拉拽，也形容人际上「强势推进」（ぐいぐい来る人 = 攻势很猛的人）',
    similarJa: ['ずんずん', 'がんがん'],
    examples: [
      { ja: '犬がリードをぐいぐい引っ張ります。', zh: '狗一个劲儿地拽牵引绳。' },
      { ja: '彼はぐいぐい話しかけてくるタイプです。', zh: '他是那种攻势很猛、不断搭话的类型。' },
    ],
    commonMistakeZh: '「ぐいぐい来る」形容人主动过头，含压迫感，可褒可贬。夸人积极用「積極的」更安全',
    recognition: { promptZh: '「ぐいぐい来る人」是什么样的人？',
      options: ['主动得让人有点招架不住', '安静内向的人', '总是迟到的人', '爱睡觉的人'],
      answerIndex: 0, feedbackZh: '「ぐいぐい来る」= 攻势猛、距离感近' },
    production: { promptJa: '力強く引っ張る様子を「ぐいぐい」で言ってください。',
      promptZh: '用「ぐいぐい」描述用力拉拽的样子。',
      expected: ['ぐいぐい'], acceptable: ['ぐいぐい引っ張ります', 'ぐいぐい来ます'] },
    conversation: { themeJa: '積極的な人との付き合い方を話す',
      starterJa: 'ぐいぐい来る人は得意ですか？苦手ですか？', starterZh: '攻势很猛的人你应付得来吗？',
      targetExpressions: ['ぐいぐい'], followUpJa: '自分はぐいぐいいくタイプですか？待つタイプですか？',
      followUpZh: '你自己是主动出击型还是等待型？' },
    difficulty: 'plus' }),
  d({ id: 'ono-kusukusu', sourceCandidateId: '5e2668a8a9ef180b', surface: 'くすくす', kana: 'くすくす',
    category: 'giongo', usagePatterns: ['to-verb'],
    meaningJa: '声をおさえて小さく笑う様子', meaningZh: '（拟声）偷笑、抿着嘴咯咯地笑',
    nuanceZh: '不能大笑的场合忍不住的小声笑。大笑是「げらげら」，微笑无声是「にこにこ」',
    similarJa: ['にこにこ', 'げらげら'],
    examples: [
      { ja: '授業中、隣の人がくすくす笑っていました。', zh: '上课时旁边的人在偷偷地笑。' },
      { ja: '子どもたちが漫画を読んで、くすくす笑っています。', zh: '孩子们看着漫画咯咯偷笑。' },
    ],
    commonMistakeZh: '「くすくす」必须是*出小声*的笑；完全无声的微笑用「にこにこ」。中文「偷笑」两者都可指，注意区分',
    recognition: { promptZh: '「くすくす」是哪种笑？',
      options: ['压低声音的偷笑', '放声大笑', '无声的微笑', '苦笑'],
      answerIndex: 0, feedbackZh: '小声忍笑 =「くすくす」' },
    production: { promptJa: '笑いを我慢した経験を「くすくす」で言ってください。',
      promptZh: '用「くすくす」说一次忍笑的经历。',
      expected: ['くすくす'], acceptable: ['くすくす笑いました', 'くすくす笑ってしまいました'] },
    conversation: { themeJa: '笑ってはいけない場面の話をする',
      starterJa: '笑ってはいけない場面で、くすくす笑ってしまったことがありますか？', starterZh: '有没有在不该笑的场合偷笑过？',
      targetExpressions: ['くすくす'], followUpJa: 'どんなことで笑いが止まらなくなりますか？',
      followUpZh: '什么事会让你笑到停不下来？' },
    difficulty: 'basic' }),
  d({ id: 'ono-guchagucha', sourceCandidateId: '7685803706ee68b7', surface: 'ぐちゃぐちゃ', kana: 'ぐちゃぐちゃ',
    category: 'gitaigo', usagePatterns: ['da-na', 'ni-naru'],
    meaningJa: '形が崩れて乱れている様子', meaningZh: '（状态）乱七八糟、稀烂、一团糟',
    nuanceZh: '房间、头发、计划、心情都可用。含「已经崩坏、不可收拾」的强烈程度',
    similarJa: ['めちゃくちゃ', 'ばらばら'],
    examples: [
      { ja: '忙しくて、部屋がぐちゃぐちゃになりました。', zh: '太忙了，房间乱得一团糟。' },
      { ja: '雨で髪がぐちゃぐちゃです。', zh: '被雨淋得头发乱糟糟的。' },
    ],
    commonMistakeZh: '「めちゃくちゃ」可作程度副词（めちゃくちゃおいしい=超好吃），「ぐちゃぐちゃ」不能这样用，只表示混乱状态',
    recognition: { promptZh: '哪个说法不自然？',
      options: ['ぐちゃぐちゃおいしい', '部屋がぐちゃぐちゃ', '髪がぐちゃぐちゃ', '予定がぐちゃぐちゃ'],
      answerIndex: 0, feedbackZh: '程度副词「超〜」用「めちゃくちゃ」，「ぐちゃぐちゃ」只表混乱' },
    production: { promptJa: '散らかった状態を「ぐちゃぐちゃ」で言ってください。',
      promptZh: '用「ぐちゃぐちゃ」描述凌乱的状态。',
      expected: ['ぐちゃぐちゃ'], acceptable: ['ぐちゃぐちゃです', 'ぐちゃぐちゃになりました'] },
    conversation: { themeJa: '片付けについて話す',
      starterJa: '忙しいとき、部屋がぐちゃぐちゃになりますか？', starterZh: '忙的时候你房间会乱成一团吗？',
      targetExpressions: ['ぐちゃぐちゃ'], followUpJa: 'いつ、どうやって片付けますか？',
      followUpZh: '你什么时候、怎么收拾？' },
    difficulty: 'basic' }),
  d({ id: 'ono-gussuri', sourceCandidateId: '4200d7fe17646b5c', surface: 'ぐっすり', kana: 'ぐっすり',
    category: 'gitaigo', usagePatterns: ['to-verb'],
    meaningJa: '深く気持ちよく眠る様子', meaningZh: '（状态）酣睡、睡得很沉很香',
    nuanceZh: '理想的深度睡眠。几乎只和「眠る/寝る」搭配。浅睡打盹是「うとうと」',
    similarJa: ['すやすや', 'うとうと'],
    examples: [
      { ja: '昨日は運動したので、ぐっすり眠れました。', zh: '昨天运动了，睡得特别香。' },
      { ja: '週末は朝までぐっすり寝たいです。', zh: '周末想一觉酣睡到天亮。' },
    ],
    commonMistakeZh: '「ぐっすり」只用于睡眠。「休息得很好」不能说「ぐっすり休んだ」（要用「ゆっくり休んだ」）',
    recognition: { promptZh: '「ぐっすり」和哪个词搭配？',
      options: ['眠る', '食べる', '歩く', '話す'],
      answerIndex: 0, feedbackZh: '「ぐっすり眠る」= 睡得香甜' },
    production: { promptJa: 'よく眠れた日のことを「ぐっすり」で言ってください。',
      promptZh: '用「ぐっすり」说说睡得好的一天。',
      expected: ['ぐっすり'], acceptable: ['ぐっすり眠れました', 'ぐっすり寝ました'] },
    conversation: { themeJa: '睡眠の質について話す',
      starterJa: '最近、ぐっすり眠れていますか？', starterZh: '最近睡得香吗？',
      targetExpressions: ['ぐっすり'], followUpJa: 'ぐっすり眠るために、何かしていますか？',
      followUpZh: '为了睡个好觉你会做什么？' },
    difficulty: 'basic' }),
];

/** 現在の完成draft（全バッチ集約）。追加は「全field完備」のバッチのみ。 */
export const ONOMATOPOEIA_DRAFTS: OnomatopoeiaDraft[] = [...ONOMATOPOEIA_DRAFTS_BATCH1];

export const onomatopoeiaDraftById = (id: string): OnomatopoeiaDraft | undefined =>
  ONOMATOPOEIA_DRAFTS.find((o) => o.id === id);
