// Phase 3P-3: オノマトペ完成draft バッチ3（ずきずき〜ひそひそ・21語）。
// 完成条件はonomatopoeiaDrafts.tsと同一（全field完備のみ収録）。全draft。
import type { OnomatopoeiaDraft } from './onomatopoeiaDrafts';

const d = (p: Omit<OnomatopoeiaDraft, 'unit' | 'publishStatus' | 'humanReviewed' | 'approved' | 'reviewKey'> & { reviewKey?: string }): OnomatopoeiaDraft =>
  ({ unit: 'ono-unit-1', publishStatus: 'draft', humanReviewed: false, approved: false,
     reviewKey: p.id, ...p });

export const ONOMATOPOEIA_DRAFTS_BATCH3: OnomatopoeiaDraft[] = [
  d({ id: 'ono-zukizuki', sourceCandidateId: 'ee6d8f8ddd02d2cc', surface: 'ずきずき', kana: 'ずきずき',
    category: 'gijougo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '脈打つように強く痛む様子', meaningZh: '（感觉）一跳一跳地剧痛、抽痛',
    nuanceZh: '虫歯・頭痛・傷口の「脉动式疼痛」。病院で最も使う痛み表現の一つ',
    similarJa: ['じんじん', 'ひりひり'],
    examples: [
      { ja: '虫歯がずきずき痛みます。', zh: '蛀牙一跳一跳地疼。' },
      { ja: '頭がずきずきして、仕事に集中できません。', zh: '头一抽一抽地疼，没法集中工作。' },
    ],
    commonMistakeZh: '中文「疼」一个字，日语按痛法分：ずきずき（抽痛）・じんじん（麻痛）・ひりひり（灼痛）・きりきり（绞痛）。就医时用对词、诊断更准',
    recognition: { promptZh: '「ずきずき」最适合哪种痛？',
      options: ['蛀牙一跳一跳地疼', '腿麻酥酥地疼', '晒伤火辣辣地疼', '胃拧着疼'],
      answerIndex: 0, feedbackZh: '脉动式抽痛 =「ずきずき」' },
    production: { promptJa: '頭痛の症状を「ずきずき」で言ってください。',
      promptZh: '用「ずきずき」描述头痛的症状。',
      expected: ['ずきずき'], acceptable: ['ずきずきします', 'ずきずき痛みます'] },
    conversation: { themeJa: '病院・薬局で痛みを伝える練習',
      starterJa: '「頭がずきずき痛みます」と薬局で伝える練習をしましょう。いつからですか？', starterZh: '练习在药店说「頭がずきずき痛みます」。什么时候开始的？',
      targetExpressions: ['ずきずき'], followUpJa: '薬を買うとき、日本語で困ったことはありますか？',
      followUpZh: '买药时用日语遇到过困难吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-sukkiri', sourceCandidateId: 'e36600b23eafb373', surface: 'すっきり', kana: 'すっきり',
    category: 'gijougo', usagePatterns: ['suru'],
    meaningJa: '余分なものがなくなって気持ちがいい様子', meaningZh: '（心理・状态）神清气爽、痛快、（房间）清爽利落',
    nuanceZh: '悩み解消・よく寝た朝・片付いた部屋など「胸のつかえが取れた」爽快感。使用範囲が広い高頻度語',
    similarJa: ['さっぱり', 'すかっと'],
    examples: [
      { ja: '悩みを話したら、気持ちがすっきりしました。', zh: '把烦恼说出来后，心里痛快多了。' },
      { ja: '部屋を片付けて、すっきりしました。', zh: '收拾了房间，清爽多了。' },
    ],
    commonMistakeZh: '「さっぱり」偏身体表面的清爽（洗澡後）、「すっきり」偏内心・状態の爽快（悩み解消・整理後）。重なる場面も多いが核が違う',
    recognition: { promptZh: '哪种情况最适合「すっきり」？',
      options: ['说出烦恼后心情舒畅', '房间越来越乱', '没睡醒头很重', '吃太饱难受'],
      answerIndex: 0, feedbackZh: '郁结消除的爽快 =「すっきり」' },
    production: { promptJa: 'よく眠れた朝の気分を「すっきり」で言ってください。',
      promptZh: '用「すっきり」说说睡饱后的早晨。',
      expected: ['すっきり'], acceptable: ['すっきりしました', 'すっきりです'] },
    conversation: { themeJa: '気持ちをすっきりさせる方法を話す',
      starterJa: 'もやもやした気持ちを、どうやってすっきりさせますか？', starterZh: '心里憋闷时你怎么让自己痛快起来？',
      targetExpressions: ['すっきり'], followUpJa: '最近、何かすっきりしたことがありましたか？',
      followUpZh: '最近有什么让你舒畅的事吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-subesube', sourceCandidateId: '9e0f146dfb71d240', surface: 'すべすべ', kana: 'すべすべ',
    category: 'gitaigo', usagePatterns: ['suru', 'da-na'],
    meaningJa: '肌などの表面が滑らかで気持ちいい様子', meaningZh: '（状态）（皮肤）光滑细腻、滑溜溜',
    nuanceZh: '赤ちゃんの肌・温泉上がりの肌の褒め言葉。温泉の「美肌の湯」の定番表現',
    similarJa: ['つるつる', 'さらさら'],
    examples: [
      { ja: '温泉に入ったら、肌がすべすべになりました。', zh: '泡了温泉，皮肤变得光滑细腻。' },
      { ja: '赤ちゃんの肌は、すべすべしています。', zh: '婴儿的皮肤滑溜溜的。' },
    ],
    commonMistakeZh: '「つるつる」も滑らかだが、路面がつるつる（打滑・危険）など負の用法もある。肌の褒め言葉は「すべすべ」が安全',
    recognition: { promptZh: '「すべすべ」最常形容什么？',
      options: ['泡温泉后的皮肤', '结冰的路面', '粗糙的墙壁', '打结的头发'],
      answerIndex: 0, feedbackZh: '光滑细腻的肌肤 =「すべすべ」' },
    production: { promptJa: '温泉の効果を「すべすべ」で言ってください。',
      promptZh: '用「すべすべ」说说温泉的效果。',
      expected: ['すべすべ'], acceptable: ['すべすべになりました', 'すべすべです'] },
    conversation: { themeJa: '温泉の経験を話す',
      starterJa: '日本の温泉に入ったことがありますか？肌がすべすべになりましたか？', starterZh: '你泡过日本温泉吗？皮肤变光滑了吗？',
      targetExpressions: ['すべすべ'], followUpJa: 'おすすめの温泉地はありますか？行ってみたい所は？',
      followUpZh: '有推荐或想去的温泉地吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-suyasuya', sourceCandidateId: 'db8d5af977d93065', surface: 'すやすや', kana: 'すやすや',
    category: 'gitaigo', usagePatterns: ['to-verb'],
    meaningJa: '安らかに気持ちよさそうに眠る様子', meaningZh: '（状态）（婴儿般）安静香甜地睡',
    nuanceZh: '穏やかな寝息のイメージ。赤ちゃん・猫の眠りに最適。大人の熟睡は「ぐっすり」が普通',
    similarJa: ['ぐっすり', 'うとうと'],
    examples: [
      { ja: '抱っこすると、子犬はすやすや寝てしまいました。', zh: '一抱起来，小狗就安静地睡着了。' },
      { ja: '猫がひざの上ですやすや寝ています。', zh: '猫在膝盖上安静地睡着。' },
    ],
    commonMistakeZh: '「ぐっすり」は睡眠の深さ（自分にも使う）、「すやすや」は寝姿の可愛らしさ（他人・赤ちゃん向け）。「私はすやすや寝た」はやや不自然',
    recognition: { promptZh: '「すやすや」最适合形容谁？',
      options: ['熟睡的婴儿', '打呼噜的大叔', '失眠的人', '刚起床的人'],
      answerIndex: 0, feedbackZh: '安らかな寝姿 =「すやすや」' },
    production: { promptJa: '赤ちゃんや猫の寝ている様子を「すやすや」で言ってください。',
      promptZh: '用「すやすや」描述婴儿或猫睡觉的样子。',
      expected: ['すやすや'], acceptable: ['すやすや眠っています', 'すやすや寝ています'] },
    conversation: { themeJa: 'ペット・家族の寝姿について話す',
      starterJa: '家族やペットがすやすや寝ている姿を見て、どう感じますか？', starterZh: '看到家人或宠物睡得香甜你有什么感觉？',
      targetExpressions: ['すやすや'], followUpJa: '「ぐっすり」と「すやすや」、どう使い分けますか？',
      followUpZh: '「ぐっすり」和「すやすや」你会怎么区分？' },
    difficulty: 'plus' }),
  d({ id: 'ono-surasura', sourceCandidateId: '275ec2361632798f', surface: 'すらすら', kana: 'すらすら',
    category: 'gitaigo', usagePatterns: ['to-verb'],
    meaningJa: 'つかえずに滑らかに進む様子（話す・読む・書く）', meaningZh: '（状态）流利地、顺畅地（说/读/写）',
    nuanceZh: '語学学習者の目標を表す定番語。「すらすら話せるようになりたい」は自己紹介で使える',
    similarJa: ['ぺらぺら', 'さくさく'],
    examples: [
      { ja: '日本語がすらすら話せるようになりたいです。', zh: '想变得能流利地说日语。' },
      { ja: '漢字が多い文章も、すらすら読めるようになりました。', zh: '汉字多的文章也能顺畅地读了。' },
    ],
    commonMistakeZh: '「ぺらぺら」は流暢さの*結果*（他人評価っぽい・自称すると自慢に聞こえる）、「すらすら」は動作の滑らかさで自分の目標にも自然に使える',
    recognition: { promptZh: '「すらすら」不能搭配哪个？',
      options: ['すらすら食べる', 'すらすら読む', 'すらすら書く', 'すらすら答える'],
      answerIndex: 0, feedbackZh: '「すらすら」用于说・读・写・答等顺畅进行的动作' },
    production: { promptJa: '日本語の目標を「すらすら」で言ってください。',
      promptZh: '用「すらすら」说说你的日语目标。',
      expected: ['すらすら'], acceptable: ['すらすら話せるようになりたいです', 'すらすら読めるようになりたいです'] },
    conversation: { themeJa: '日本語の上達目標を話す',
      starterJa: '何をすらすらできるようになりたいですか？会話？読解？', starterZh: '你想在哪方面变得流畅？会话？阅读？',
      targetExpressions: ['すらすら'], followUpJa: 'すらすら話せた！と感じた瞬間はありますか？',
      followUpZh: '有过「说得很流利！」的瞬间吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-zokuzoku', sourceCandidateId: '1b75adf0700c3a40', surface: 'ぞくぞく', kana: 'ぞくぞく',
    category: 'gijougo', usagePatterns: ['suru'],
    meaningJa: '①寒気がする様子 ②興奮・期待で震える様子', meaningZh: '（感觉）①发冷、打寒战 ②兴奋得发抖、起鸡皮疙瘩',
    nuanceZh: '①発熱時の悪寒（風邪のサイン）。②スリルや期待のわくわく（映画・試合）。文脈で正反対の意味になる',
    similarJa: ['ぶるぶる', 'わくわく'],
    examples: [
      { ja: '熱があるみたいで、体がぞくぞくします。', zh: '好像发烧了，浑身发冷。' },
      { ja: '決勝戦を見ていて、ぞくぞくしました。', zh: '看决赛看得浑身起鸡皮疙瘩。' },
    ],
    commonMistakeZh: '風邪の「ぞくぞく」を医者に伝えると悪寒として通じる。「怖くてぞくぞく」（毛骨悚然）もあり、文脈判断が必要',
    recognition: { promptZh: '「体がぞくぞくする」+发烧，是什么信号？',
      options: ['感冒发冷（恶寒）', '很兴奋', '很开心', '吃饱了'],
      answerIndex: 0, feedbackZh: '发烧+ぞくぞく = 恶寒，感冒的典型症状' },
    production: { promptJa: '風邪のひき始めの症状を「ぞくぞく」で言ってください。',
      promptZh: '用「ぞくぞく」描述感冒初期的症状。',
      expected: ['ぞくぞく'], acceptable: ['ぞくぞくします', '体がぞくぞくします'] },
    conversation: { themeJa: '風邪のひき始めのサインを話す',
      starterJa: '風邪のひき始めに、ぞくぞくしたらどうしますか？', starterZh: '感冒初期发冷时你会怎么做？',
      targetExpressions: ['ぞくぞく'], followUpJa: '興奮してぞくぞくした経験もありますか？',
      followUpZh: '也有过兴奋得起鸡皮疙瘩的经历吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-sokkuri', sourceCandidateId: '3c49e42b87b94d95', surface: 'そっくり', kana: 'そっくり',
    category: 'gitaigo', usagePatterns: ['da-na'],
    meaningJa: '顔や姿が非常によく似ている様子', meaningZh: '（状态）一模一样、长得极像',
    nuanceZh: '親子・兄弟・そっくりさん（模仿艺人）。「〜にそっくり」の形で使う。似ている度が最上級',
    similarJa: ['似ている', 'うりふたつ'],
    examples: [
      { ja: '声の高さが、母にそっくりだと言われます。', zh: '别人说我的声调和妈妈一模一样。' },
      { ja: 'この味、母の料理にそっくりで、懐かしくなりました。', zh: '这个味道和妈妈做的菜一模一样，好怀念。' },
    ],
    commonMistakeZh: '助詞は「〜*に*そっくり」。「〜とそっくり」も通じるが「に」が標準。「似ている」より程度が強い',
    recognition: { promptZh: '「そっくり」的正确用法是？',
      options: ['父にそっくりです', '父がそっくりです', '父をそっくりです', '父でそっくりです'],
      answerIndex: 0, feedbackZh: '「（人）にそっくり」= 和（人）一模一样' },
    production: { promptJa: '家族の誰に似ているか「そっくり」で言ってください。',
      promptZh: '用「そっくり」说说你像家里的谁。',
      expected: ['そっくり'], acceptable: ['母にそっくりです', '父にそっくりです'] },
    conversation: { themeJa: '家族の似ているところを話す',
      starterJa: '顔や性格、家族の誰にそっくりだと言われますか？', starterZh: '长相或性格，别人说你和家里谁最像？',
      targetExpressions: ['そっくり'], followUpJa: '性格も似ていますか？違いますか？',
      followUpZh: '性格也像吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-sotto', sourceCandidateId: '7c927a4c4b933d3b', surface: 'そっと', kana: 'そっと',
    category: 'gitaigo', usagePatterns: ['to-verb'],
    meaningJa: '音を立てず、静かにやさしく動く様子', meaningZh: '（状态）轻轻地、悄悄地、小心翼翼地',
    nuanceZh: '善意・配慮の「悄悄」（不吵醒人・不打扰人）。「そっとしておく」（让人静一静）は思いやりの定型句',
    similarJa: ['こそこそ', 'ゆっくり'],
    examples: [
      { ja: '赤ちゃんを起こさないように、そっとドアを閉めました。', zh: '为了不吵醒婴儿，轻轻地关上了门。' },
      { ja: '落ち込んでいる友達を、そっとしておきました。', zh: '朋友情绪低落，就让他自己静一静。' },
    ],
    commonMistakeZh: '「こそこそ」是心里有鬼的偷偷（负面），「そっと」是体贴的轻轻（正面）。中文都译「悄悄」，日语色彩相反',
    recognition: { promptZh: '「そっとしておいて」是什么意思？',
      options: ['让我一个人静一静', '快点过来', '大声说话', '一起吵闹'],
      answerIndex: 0, feedbackZh: '「そっとしておく」= 不打扰、给对方空间' },
    production: { promptJa: '静かに何かをする様子を「そっと」で言ってください。',
      promptZh: '用「そっと」描述轻手轻脚做事。',
      expected: ['そっと'], acceptable: ['そっと閉めました', 'そっと置きました'] },
    conversation: { themeJa: '落ち込んだ人への接し方を話す',
      starterJa: '友達が落ち込んでいるとき、話しかけますか？そっとしておきますか？', starterZh: '朋友情绪低落时，你会搭话还是让他静静？',
      targetExpressions: ['そっと'], followUpJa: '自分が落ち込んだときは、どうしてほしいですか？',
      followUpZh: '你自己低落时希望别人怎么做？' },
    difficulty: 'basic' }),
  d({ id: 'ono-nikoniko', sourceCandidateId: 'da9ac9c5b7c99cf6', surface: 'にこにこ', kana: 'にこにこ',
    category: 'gitaigo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '声を出さず、嬉しそうに笑顔でいる様子', meaningZh: '（状态）笑眯眯、满面笑容',
    nuanceZh: '声のない自然な笑顔。「にこにこしている人」は好印象の定番描写。接客・面接の褒め言葉にも',
    similarJa: ['くすくす', 'にやにや'],
    examples: [
      { ja: 'あの店員さんは、いつもにこにこしていて感じがいいです。', zh: '那位店员总是笑眯眯的，让人舒服。' },
      { ja: '孫の写真を見て、祖母がにこにこしています。', zh: '奶奶看着孙子的照片，笑眯眯的。' },
    ],
    commonMistakeZh: '「にこにこ」（开朗友善）と「にやにや」（意味深・让人发毛）は印象が正反対。夸人只能用「にこにこ」',
    recognition: { promptZh: '给人好印象的笑是哪个？',
      options: ['にこにこ', 'にやにや', 'げらげら（在葬礼上）', 'くすくす（在面试中）'],
      answerIndex: 0, feedbackZh: '自然温和的笑容 =「にこにこ」' },
    production: { promptJa: '感じのいい人の様子を「にこにこ」で言ってください。',
      promptZh: '用「にこにこ」描述让人有好感的人。',
      expected: ['にこにこ'], acceptable: ['にこにこしています', 'にこにこ笑っています'] },
    conversation: { themeJa: '笑顔の効果について話す',
      starterJa: 'にこにこしている人を見ると、どんな気持ちになりますか？', starterZh: '看到笑眯眯的人你心情如何？',
      targetExpressions: ['にこにこ'], followUpJa: '仕事のとき、にこにこを意識していますか？',
      followUpZh: '工作时你会有意识地保持笑容吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-niyaniya', sourceCandidateId: '943a4aaacea40d0f', surface: 'にやにや', kana: 'にやにや',
    category: 'gitaigo', usagePatterns: ['suru'],
    meaningJa: '訳ありげに一人で笑いをこらえている様子', meaningZh: '（状态）暗自窃笑、皮笑肉不笑、意味深长地笑',
    nuanceZh: '思い出し笑い・たくらみ・スマホを見ながらの笑いなど「理由がわからない笑い」。見る側に不気味・不快感を与えることも',
    similarJa: ['にこにこ', 'くすくす'],
    examples: [
      { ja: 'スマホを見ながら、にやにやしていました。', zh: '一边看手机一边偷偷地笑。' },
      { ja: '「何をにやにやしているの？」と聞かれました。', zh: '被问「你一个人在傻笑什么？」' },
    ],
    commonMistakeZh: '「にやにや」を褒め言葉と誤解しない。感じのいい笑顔は「にこにこ」。中文「窃笑」に近く、多少不気味',
    recognition: { promptZh: '「にやにやしないで」的语气是？',
      options: ['别一个人傻笑（有点不舒服）', '请多笑一笑', '笑得真好看', '请大声笑'],
      answerIndex: 0, feedbackZh: '「にやにや」让旁人不舒服，所以会被制止' },
    production: { promptJa: '思い出し笑いの様子を「にやにや」で言ってください。',
      promptZh: '用「にやにや」描述想起趣事偷笑的样子。',
      expected: ['にやにや'], acceptable: ['にやにやしてしまいました', 'にやにやしていました'] },
    conversation: { themeJa: '思い出し笑いの経験を話す',
      starterJa: '思い出してにやにやしてしまうことはありますか？', starterZh: '有没有想起来就忍不住偷笑的事？',
      targetExpressions: ['にやにや'], followUpJa: '「にこにこ」と「にやにや」の違い、説明できますか？',
      followUpZh: '你能说明「にこにこ」和「にやにや」的区别吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-nyoronyoro', sourceCandidateId: 'c9e4a5b3a7cf09fb', surface: 'にょろにょろ', kana: 'にょろにょろ',
    category: 'gitaigo', usagePatterns: ['to-verb', 'suru'],
    meaningJa: '蛇などの細長いものがくねって進む様子', meaningZh: '（状态）（蛇等）蜿蜒爬行、扭动前进',
    nuanceZh: '蛇・うなぎ・ミミズ専用に近い。「くねくね」は形状（静的にも）、「にょろにょろ」は進む動き',
    similarJa: ['くねくね', 'うようよ'],
    examples: [
      { ja: '蛇がにょろにょろと草むらへ入っていきました。', zh: '蛇蜿蜒着爬进了草丛。' },
      { ja: '水槽の中で、うなぎがにょろにょろ動いています。', zh: '水槽里鳗鱼扭来扭去地游动。' },
    ],
    commonMistakeZh: '「にょろにょろ」是细长生物的*移动*。山路弯曲（静的）は「くねくね」。動くかどうかで選ぶ',
    recognition: { promptZh: '「にょろにょろ」最适合形容什么？',
      options: ['蛇在爬行', '山路的形状', '猫在跳', '鸟在飞'],
      answerIndex: 0, feedbackZh: '细长生物扭动前进 =「にょろにょろ」' },
    production: { promptJa: '蛇やうなぎの動きを「にょろにょろ」で言ってください。',
      promptZh: '用「にょろにょろ」描述蛇或鳗鱼的动作。',
      expected: ['にょろにょろ'], acceptable: ['にょろにょろ動いています', 'にょろにょろしています'] },
    conversation: { themeJa: '苦手な生き物について話す',
      starterJa: 'にょろにょろした生き物は、平気ですか？苦手ですか？', starterZh: '扭来扭去的生物你怕不怕？',
      targetExpressions: ['にょろにょろ'], followUpJa: 'うなぎは食べるのは好きですか？',
      followUpZh: '鳗鱼你喜欢吃吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-nurunuru', sourceCandidateId: '4c2e352f6a36df6a', surface: 'ぬるぬる', kana: 'ぬるぬる',
    category: 'gitaigo', usagePatterns: ['suru', 'da-na'],
    meaningJa: '表面が滑って気持ち悪いほど滑らかな様子', meaningZh: '（状态）滑溜溜、黏滑（多含不适感）',
    nuanceZh: 'うなぎ・石けんの残り・排水口など「濡れて滑る」不快寄りの感触。温泉の湯は「とろとろ」と言うと褒め言葉',
    similarJa: ['ねばねば', 'つるつる'],
    examples: [
      { ja: '雨上がりの石段はぬるぬるして危ないです。', zh: '雨后的石阶滑溜溜的很危险。' },
      { ja: 'お風呂の床がぬるぬるするので、掃除しました。', zh: '浴室地板黏滑黏滑的，打扫了一下。' },
    ],
    commonMistakeZh: '「ぬるぬる」偏「湿滑（不快）」、「ねばねば」偏「粘稠拉丝」。纳豆是ねばねば，鳗鱼是ぬるぬる',
    recognition: { promptZh: '「ぬるぬる」的触感是？',
      options: ['湿湿滑滑（有点不舒服）', '干燥粗糙', '蓬松柔软', '坚硬冰冷'],
      answerIndex: 0, feedbackZh: '湿滑感 =「ぬるぬる」' },
    production: { promptJa: '滑りやすい床の状態を「ぬるぬる」で言ってください。',
      promptZh: '用「ぬるぬる」描述滑滑的地板。',
      expected: ['ぬるぬる'], acceptable: ['ぬるぬるしています', 'ぬるぬるします'] },
    conversation: { themeJa: '苦手な食感について話す',
      starterJa: 'ぬるぬるした食べ物は、好きですか？苦手ですか？', starterZh: '滑溜溜的食物你喜欢还是怕？',
      targetExpressions: ['ぬるぬる'], followUpJa: '中国の料理で、ぬるぬるしたものはありますか？',
      followUpZh: '中国菜里有滑溜溜的东西吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-nebaneba', sourceCandidateId: 'acccc8efa611f356', surface: 'ねばねば', kana: 'ねばねば',
    category: 'gitaigo', usagePatterns: ['suru', 'da-na'],
    meaningJa: '糸を引くように粘り気がある様子', meaningZh: '（状态）黏糊糊、拉丝、粘稠',
    nuanceZh: '納豆・オクラ・とろろの定番語。日本では「ねばねば食材=健康にいい」という文化的文脈がある',
    similarJa: ['ぬるぬる', 'とろとろ'],
    examples: [
      { ja: 'とろろは、ねばねばした食感が特徴です。', zh: '山药泥的特点就是黏糊糊的口感。' },
      { ja: 'オクラを切ると、ねばねばが出てきます。', zh: '切秋葵会出黏黏的丝。' },
    ],
    commonMistakeZh: '「ねばねば」は粘って糸を引く（納豆）。単に湿って滑るのは「ぬるぬる」。中文「黏」一字で両方を覆うので要区別',
    recognition: { promptZh: '「ねばねば」的代表食物是？',
      options: ['纳豆', '米饭', '天妇罗', '拉面'],
      answerIndex: 0, feedbackZh: '拉丝粘稠 =「ねばねば」、纳豆是代表' },
    production: { promptJa: '納豆の食感を「ねばねば」で言ってください。',
      promptZh: '用「ねばねば」描述纳豆的口感。',
      expected: ['ねばねば'], acceptable: ['ねばねばしています', 'ねばねばです'] },
    conversation: { themeJa: '納豆が食べられるか話す',
      starterJa: 'ねばねばした納豆、食べられますか？', starterZh: '黏糊糊的纳豆你敢吃吗？',
      targetExpressions: ['ねばねば'], followUpJa: '初めて納豆を見たとき、どう思いましたか？',
      followUpZh: '第一次见到纳豆你什么感想？' },
    difficulty: 'basic' }),
  d({ id: 'ono-hakihaki', sourceCandidateId: 'd10af6efd27b6e75', surface: 'はきはき', kana: 'はきはき',
    category: 'gitaigo', usagePatterns: ['to-verb', 'suru'],
    meaningJa: '話し方や態度がはっきりして気持ちいい様子', meaningZh: '（状态）（说话）干脆利落、爽朗清楚',
    nuanceZh: '面接・接客での高評価ワード。「はきはき答える」は就活アドバイスの定番。声量+明瞭さ+積極性',
    similarJa: ['てきぱき', 'ぼそぼそ'],
    examples: [
      { ja: '面接では、はきはき答えることが大切です。', zh: '面试时干脆清楚地回答很重要。' },
      { ja: '彼女ははきはきしていて、印象がいいです。', zh: '她说话爽朗利落，印象很好。' },
    ],
    commonMistakeZh: '「はきはき」は話し方、「てきぱき」は動作・仕事ぶり。面接対策では両方使えるが対象が違う',
    recognition: { promptZh: '「はきはき」形容什么？',
      options: ['说话清楚爽朗', '动作缓慢', '声音小听不清', '沉默不语'],
      answerIndex: 0, feedbackZh: '说话干脆明了 =「はきはき」' },
    production: { promptJa: '面接でのアドバイスを「はきはき」で言ってください。',
      promptZh: '用「はきはき」说一条面试建议。',
      expected: ['はきはき'], acceptable: ['はきはき答えます', 'はきはき話します'] },
    conversation: { themeJa: '日本語面接の話し方を練習する',
      starterJa: '日本語の面接で、はきはき話す自信がありますか？', starterZh: '用日语面试你有信心说得干脆利落吗？',
      targetExpressions: ['はきはき'], followUpJa: '緊張すると声が小さくなりますか？対策は？',
      followUpZh: '紧张时声音会变小吗？有什么对策？' },
    difficulty: 'basic' }),
  d({ id: 'ono-bashabasha', sourceCandidateId: 'eb46cd17236d1bbc', surface: 'ばしゃばしゃ', kana: 'ばしゃばしゃ',
    category: 'giongo', usagePatterns: ['to-verb', 'suru'],
    meaningJa: '水を勢いよくはね散らす音・様子', meaningZh: '（拟声）哗啦哗啦地溅水、扑腾水花',
    nuanceZh: '子どものプール遊び・洗顔・犬の水浴びなど。豪快に水がはねる音。静かな水音は「ちゃぷちゃぷ」',
    similarJa: ['ちゃぷちゃぷ', 'ざぶざぶ'],
    examples: [
      { ja: '子どもたちがプールでばしゃばしゃ遊んでいます。', zh: '孩子们在泳池里扑腾着玩水。' },
      { ja: '冷たい水で、ばしゃばしゃ顔を洗いました。', zh: '用凉水哗啦哗啦地洗了脸。' },
    ],
    commonMistakeZh: '「ばしゃばしゃ」は水しぶきの音。雨の「ざあざあ」、静かな水遊びの「ちゃぷちゃぷ」と使い分ける',
    recognition: { promptZh: '「ばしゃばしゃ」是什么声音？',
      options: ['溅水花的声音', '下大雨的声音', '风吹的声音', '打雷的声音'],
      answerIndex: 0, feedbackZh: '水花飞溅 =「ばしゃばしゃ」' },
    production: { promptJa: '水遊びや洗顔の様子を「ばしゃばしゃ」で言ってください。',
      promptZh: '用「ばしゃばしゃ」描述玩水或洗脸。',
      expected: ['ばしゃばしゃ'], acceptable: ['ばしゃばしゃ洗いました', 'ばしゃばしゃ遊んでいます'] },
    conversation: { themeJa: '夏の水遊びの思い出を話す',
      starterJa: '子どものころ、ばしゃばしゃ水遊びをしましたか？', starterZh: '小时候你玩过扑腾水花的游戏吗？',
      targetExpressions: ['ばしゃばしゃ'], followUpJa: '日本のプールや海に行ったことがありますか？',
      followUpZh: '你去过日本的泳池或海边吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-battari', sourceCandidateId: '09518998c4e9be4d', surface: 'ばったり', kana: 'ばったり',
    category: 'gitaigo', usagePatterns: ['to-verb'],
    meaningJa: '①突然倒れる様子 ②偶然出会う様子', meaningZh: '（状态）①扑通倒下 ②不期而遇、偶然碰见',
    nuanceZh: '②「ばったり会う」（偶遇）が会話頻出。「駅でばったり元同僚に会った」など。①は疲労・病気で倒れ込む',
    similarJa: ['ぐったり', 'たまたま'],
    examples: [
      { ja: '駅で、昔の同僚にばったり会いました。', zh: '在车站偶然碰见了以前的同事。' },
      { ja: '疲れて、ベッドにばったり倒れました。', zh: '累得扑通一声倒在床上。' },
    ],
    commonMistakeZh: '「ばったり会う」は偶然性が核。約束して会うのは「会う」だけ。「たまたま会った」より生き生きした表現',
    recognition: { promptZh: '「ばったり会いました」是怎么见的？',
      options: ['偶然碰见', '约好见面', '视频通话', '没见到'],
      answerIndex: 0, feedbackZh: '「ばったり会う」= 不期而遇' },
    production: { promptJa: '偶然の出会いを「ばったり」で言ってください。',
      promptZh: '用「ばったり」说一次偶遇。',
      expected: ['ばったり'], acceptable: ['ばったり会いました', 'ばったり倒れました'] },
    conversation: { themeJa: '偶然の再会エピソードを話す',
      starterJa: '意外な場所で、知り合いにばったり会ったことがありますか？', starterZh: '在意想不到的地方偶遇过熟人吗？',
      targetExpressions: ['ばったり'], followUpJa: '日本で中国の知り合いにばったり会ったら、驚きますか？',
      followUpZh: '在日本偶遇中国的熟人你会吃惊吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-bacchiri', sourceCandidateId: '1d71857e8fbc421c', surface: 'ばっちり', kana: 'ばっちり',
    category: 'gitaigo', usagePatterns: ['da-na', 'to-verb'],
    meaningJa: '完璧にうまくいく様子', meaningZh: '（状态）妥妥的、完美搞定、十拿九稳',
    nuanceZh: '「準備はばっちりです」は職場・試験前の頼もしい返事。カジュアル寄りだが職場でも使える便利語',
    similarJa: ['ばっちし', 'ぴったり'],
    examples: [
      { ja: '明日のプレゼンの準備は、ばっちりです。', zh: '明天演讲的准备妥妥的。' },
      { ja: 'テストで、ばっちり100点を取りました。', zh: '考试稳稳拿了100分。' },
    ],
    commonMistakeZh: '目上への正式報告では「準備は万全です」がより丁寧。「ばっちり」は同僚・友人向けの明るい表現',
    recognition: { promptZh: '「準備はばっちりです」的意思是？',
      options: ['准备得很完美', '还没开始准备', '不想准备', '准备失败了'],
      answerIndex: 0, feedbackZh: '「ばっちり」= 完美、没问题' },
    production: { promptJa: '準備ができたことを「ばっちり」で言ってください。',
      promptZh: '用「ばっちり」说准备好了。',
      expected: ['ばっちり'], acceptable: ['ばっちりです', '準備はばっちりです'] },
    conversation: { themeJa: '準備万端の予定について話す',
      starterJa: '最近、「ばっちり！」と言えるほど準備したことはありますか？', starterZh: '最近有准备得「妥妥的」的事吗？',
      targetExpressions: ['ばっちり'], followUpJa: '準備しすぎるタイプですか？直前型ですか？',
      followUpZh: '你是过度准备型还是临时抱佛脚型？' },
    difficulty: 'basic' }),
  d({ id: 'ono-harahara', sourceCandidateId: 'd3d5b14bca1983a2', surface: 'はらはら', kana: 'はらはら',
    category: 'gijougo', usagePatterns: ['suru'],
    meaningJa: '悪い結果にならないか、見ていて不安な様子', meaningZh: '（心理）捏一把汗、提心吊胆',
    nuanceZh: '見守る側の不安（子どもの初舞台・サーカス・接戦の試合）。「はらはらどきどき」で緊張と興奮のセット',
    similarJa: ['どきどき', 'ひやひや'],
    examples: [
      { ja: '子どもの発表会を、はらはらしながら見ていました。', zh: '提心吊胆地看着孩子的演出。' },
      { ja: '財布が見つかるかどうか、はらはらしました。', zh: '钱包能不能找回来，捏了一把汗。' },
    ],
    commonMistakeZh: '「いらいら」（不耐烦）と「はらはら」（担心）は全く違う感情。中文「着急」がどちらにも訳せるため混同しやすい',
    recognition: { promptZh: '「はらはら」是哪种心情？',
      options: ['担心出事、捏一把汗', '不耐烦、冒火', '开心雀跃', '困倦想睡'],
      answerIndex: 0, feedbackZh: '見守る不安 =「はらはら」' },
    production: { promptJa: '心配しながら見守った経験を「はらはら」で言ってください。',
      promptZh: '用「はらはら」说一次捏着汗旁观的经历。',
      expected: ['はらはら'], acceptable: ['はらはらしました', 'はらはらしながら見ました'] },
    conversation: { themeJa: 'はらはらした瞬間を話す',
      starterJa: '最近、はらはらした出来事はありますか？', starterZh: '最近有让你捏一把汗的事吗？',
      targetExpressions: ['はらはら'], followUpJa: '「いらいら」と「はらはら」、もう使い分けられますか？',
      followUpZh: '「いらいら」和「はらはら」你能区分了吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-pikapika', sourceCandidateId: '14bb6f195ddccfc0', surface: 'ぴかぴか', kana: 'ぴかぴか',
    category: 'gitaigo', usagePatterns: ['suru', 'da-na'],
    meaningJa: '磨かれて光っている様子・新品の様子', meaningZh: '（状态）锃亮、崭新发光',
    nuanceZh: '磨いた靴・洗った車・新品（ぴかぴかの一年生=新入生）。努力の成果としての輝きに使うと気持ちいい',
    similarJa: ['きらきら', 'つやつや'],
    examples: [
      { ja: '靴を磨いて、ぴかぴかにしました。', zh: '把鞋擦得锃亮。' },
      { ja: 'ぴかぴかの新車を買いました。', zh: '买了辆崭新锃亮的车。' },
    ],
    commonMistakeZh: '「きらきら」は光の粒の輝き（星・宝石）、「ぴかぴか」は磨かれた面の光（靴・床）。磨く対象は「ぴかぴか」',
    recognition: { promptZh: '「ぴかぴか」最适合形容什么？',
      options: ['擦得锃亮的皮鞋', '夜空的星星', '粗糙的墙', '湿透的衣服'],
      answerIndex: 0, feedbackZh: '磨出来的光亮 =「ぴかぴか」' },
    production: { promptJa: '掃除や磨いた成果を「ぴかぴか」で言ってください。',
      promptZh: '用「ぴかぴか」说说打扫或擦拭的成果。',
      expected: ['ぴかぴか'], acceptable: ['ぴかぴかにしました', 'ぴかぴかです'] },
    conversation: { themeJa: '磨く・手入れの習慣を話す',
      starterJa: '靴や車を、ぴかぴかに手入れするタイプですか？', starterZh: '你是会把鞋或车保养得锃亮的类型吗？',
      targetExpressions: ['ぴかぴか'], followUpJa: 'ぴかぴかにすると、気分も変わりますか？',
      followUpZh: '擦得锃亮后心情也会变好吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-bishobisho', sourceCandidateId: 'd7ddc77dfda5e951', surface: 'びしょびしょ', kana: 'びしょびしょ',
    category: 'gitaigo', usagePatterns: ['da-na', 'ni-naru'],
    meaningJa: 'ひどく濡れている様子', meaningZh: '（状态）湿透、湿淋淋',
    nuanceZh: '雨・汗・水こぼしで「絞れるほど濡れた」不快な状態。「びしょ濡れ」も同義でよく使う',
    similarJa: ['ずぶぬれ', 'じめじめ'],
    examples: [
      { ja: '急な雨で、服がびしょびしょになりました。', zh: '突然下雨，衣服湿透了。' },
      { ja: '夏は汗でシャツがびしょびしょです。', zh: '夏天衬衫被汗湿透。' },
    ],
    commonMistakeZh: '「濡れた」は中立、「びしょびしょ」は程度が重い（湿透）。少し濡れた程度で使うと大げさ',
    recognition: { promptZh: '「びしょびしょ」是湿到什么程度？',
      options: ['湿透（能拧出水）', '有点潮', '完全干燥', '结冰了'],
      answerIndex: 0, feedbackZh: '彻底湿透 =「びしょびしょ」' },
    production: { promptJa: '雨に降られた経験を「びしょびしょ」で言ってください。',
      promptZh: '用「びしょびしょ」说一次被雨淋的经历。',
      expected: ['びしょびしょ'], acceptable: ['びしょびしょになりました', 'びしょびしょです'] },
    conversation: { themeJa: '突然の雨への備えを話す',
      starterJa: '傘がなくて、びしょびしょになったことがありますか？', starterZh: '有没有没带伞被淋透过？',
      targetExpressions: ['びしょびしょ'], followUpJa: '折りたたみ傘をいつも持ち歩きますか？',
      followUpZh: '你会随身带折叠伞吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-hisohiso', sourceCandidateId: 'ac153c1ee6fb0fd1', surface: 'ひそひそ', kana: 'ひそひそ',
    category: 'giongo', usagePatterns: ['to-verb'],
    meaningJa: '人に聞こえないように小声で話す様子', meaningZh: '（拟声）窃窃私语、咬耳朵',
    nuanceZh: '内緒話の音。「ひそひそ話」で名詞にも。悪口の連想もあるが「こそこそ」より中立寄り',
    similarJa: ['こそこそ', 'ぼそぼそ'],
    examples: [
      { ja: '映画館では、ひそひそ話すのもマナー違反です。', zh: '在电影院窃窃私语也是不礼貌的。' },
      { ja: '二人は何か、ひそひそ相談しています。', zh: '两人在小声商量着什么。' },
    ],
    commonMistakeZh: '「ひそひそ」は音量（小声）、「こそこそ」は態度（鬼祟）。善意の内緒話（サプライズ相談）は「ひそひそ」が合う',
    recognition: { promptZh: '「ひそひそ」是怎么说话？',
      options: ['压低声音悄悄说', '大声喊', '清楚爽朗地说', '不说话'],
      answerIndex: 0, feedbackZh: '小声私语 =「ひそひそ」' },
    production: { promptJa: '内緒話の様子を「ひそひそ」で言ってください。',
      promptZh: '用「ひそひそ」描述说悄悄话。',
      expected: ['ひそひそ'], acceptable: ['ひそひそ話しています', 'ひそひそ相談しています'] },
    conversation: { themeJa: '内緒話・サプライズの経験を話す',
      starterJa: 'サプライズの計画で、ひそひそ相談したことがありますか？', starterZh: '为了惊喜计划咬过耳朵吗？',
      targetExpressions: ['ひそひそ'], followUpJa: '「ひそひそ」と「こそこそ」、印象の違いが分かりますか？',
      followUpZh: '「ひそひそ」和「こそこそ」的印象差异你感觉到了吗？' },
    difficulty: 'basic' }),
];
