// Phase 3P-3: オノマトペ完成draft バッチ2（ぐったり〜すかすか・21語）。
// 完成条件はonomatopoeiaDrafts.tsと同一（全field完備のみ収録）。全draft。
import type { OnomatopoeiaDraft } from './onomatopoeiaDrafts';

const d = (p: Omit<OnomatopoeiaDraft, 'unit' | 'publishStatus' | 'humanReviewed' | 'approved' | 'reviewKey'> & { reviewKey?: string }): OnomatopoeiaDraft =>
  ({ unit: 'ono-unit-1', publishStatus: 'draft', humanReviewed: false, approved: false,
     reviewKey: p.id, ...p });

export const ONOMATOPOEIA_DRAFTS_BATCH2: OnomatopoeiaDraft[] = [
  d({ id: 'ono-guttari', sourceCandidateId: 'c26bd533110d2d57', surface: 'ぐったり', kana: 'ぐったり',
    category: 'gitaigo', usagePatterns: ['suru'],
    meaningJa: '疲れや暑さで力が抜けて動けない様子', meaningZh: '（状态）累瘫、精疲力竭、蔫了',
    nuanceZh: '体力耗尽「瘫着不想动」的状态。中暑、加班后、搬家后常用。宠物・孩子生病时也用',
    similarJa: ['くたくた', 'へとへと'],
    examples: [
      { ja: '引っ越しで一日中働いて、ぐったりしました。', zh: '搬家忙了一整天，累瘫了。' },
      { ja: '暑さで、犬がぐったりしています。', zh: '天太热，狗都蔫了。' },
    ],
    commonMistakeZh: '「疲れた」是感受，「ぐったり」是*瘫软的样子*。别人看得出来的疲惫才用「ぐったり」',
    recognition: { promptZh: '「ぐったり」是什么状态？',
      options: ['累得瘫着不想动', '精神饱满', '有点困但能撑', '生气发抖'],
      answerIndex: 0, feedbackZh: '「ぐったり」= 力气被抽干、瘫软' },
    production: { promptJa: 'とても疲れた日のことを「ぐったり」で言ってください。',
      promptZh: '用「ぐったり」说说累坏了的一天。',
      expected: ['ぐったり'], acceptable: ['ぐったりしました', 'ぐったりでした'] },
    conversation: { themeJa: '疲れ切った日の過ごし方を話す',
      starterJa: '仕事でぐったりした日は、何をして回復しますか？', starterZh: '工作累瘫的日子你怎么恢复？',
      targetExpressions: ['ぐったり'], followUpJa: '今週は、ぐったりする日がありましたか？',
      followUpZh: '这周有累瘫的日子吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-kunekune', sourceCandidateId: '9409fbeb6d9891b8', surface: 'くねくね', kana: 'くねくね',
    category: 'gitaigo', usagePatterns: ['to-verb', 'suru'],
    meaningJa: '細長いものが曲がりくねっている様子', meaningZh: '（状态）弯弯曲曲、扭来扭去',
    nuanceZh: '山路、河流、虫子的动きなど「细长物的连续弯曲」。人扭动身体也可用（略带滑稽感）',
    similarJa: ['ぐにゃぐにゃ', 'うねうね'],
    examples: [
      { ja: '山道がくねくね曲がっていて、車酔いしました。', zh: '山路弯弯曲曲，晕车了。' },
      { ja: '子どもが恥ずかしがって、くねくねしています。', zh: '孩子害羞得扭来扭去。' },
    ],
    commonMistakeZh: '「くねくね」用于*细长物*的弯曲。纸张等平面物的弯折用「ぐにゃぐにゃ」「くしゃくしゃ」',
    recognition: { promptZh: '哪个最适合「くねくね」？',
      options: ['盘山公路', '笔直的高速公路', '平坦的广场', '方形的房间'],
      answerIndex: 0, feedbackZh: '细长而弯曲 =「くねくね」' },
    production: { promptJa: '曲がりくねった道を「くねくね」で言ってください。',
      promptZh: '用「くねくね」描述弯曲的路。',
      expected: ['くねくね'], acceptable: ['くねくねしています', 'くねくね曲がっています'] },
    conversation: { themeJa: '山道・ドライブの経験を話す',
      starterJa: 'くねくねした山道を運転したことがありますか？', starterZh: '开过弯弯曲曲的山路吗？',
      targetExpressions: ['くねくね'], followUpJa: '車酔いはしやすいほうですか？',
      followUpZh: '你容易晕车吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-kurakura', sourceCandidateId: '15e38b99ce9d1048', surface: 'くらくら', kana: 'くらくら',
    category: 'gijougo', usagePatterns: ['suru'],
    meaningJa: 'めまいがして倒れそうな様子', meaningZh: '（感觉）头晕目眩、天旋地转',
    nuanceZh: '站起来时、中暑、发烧时的眩晕。病院で症状を伝えるときに使える実用語',
    similarJa: ['ふらふら', 'ぼーっと'],
    examples: [
      { ja: '急に立ち上がったら、頭がくらくらしました。', zh: '突然站起来，头一阵发晕。' },
      { ja: '熱で頭がくらくらして、仕事を早退しました。', zh: '发烧头晕，提前下班了。' },
    ],
    commonMistakeZh: '「くらくら」是*头晕*，「ふらふら」是*脚步不稳*。医院里描述症状时区分开会更准确',
    recognition: { promptZh: '「頭がくらくらする」适合告诉谁？',
      options: ['医生（描述症状）', '美发师（要求发型）', '店员（点菜）', '司机（指路）'],
      answerIndex: 0, feedbackZh: '「くらくら」是常用症状表达，就医时很有用' },
    production: { promptJa: '体調が悪いときの症状を「くらくら」で言ってください。',
      promptZh: '用「くらくら」描述不舒服时的症状。',
      expected: ['くらくら'], acceptable: ['くらくらします', '頭がくらくらします'] },
    conversation: { themeJa: '病院で症状を伝える練習',
      starterJa: '病院で「頭がくらくらします」と伝える練習をしましょう。いつからですか？', starterZh: '练习在医院说「頭がくらくらします」。从什么时候开始的？',
      targetExpressions: ['くらくら'], followUpJa: 'ほかに、日本語で言える症状はありますか？',
      followUpZh: '还有别的能用日语说的症状吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-kurukuru', sourceCandidateId: '26f751460538ece8', surface: 'くるくる', kana: 'くるくる',
    category: 'gitaigo', usagePatterns: ['to-verb'],
    meaningJa: '軽やかに何度も回る様子', meaningZh: '（状态）滴溜溜地转、一圈圈地转',
    nuanceZh: '轻快的旋转（陀螺、舞蹈、卷发）。「予定がくるくる変わる」（计划变来变去）的比喻用法也常见',
    similarJa: ['ぐるぐる', 'ころころ'],
    examples: [
      { ja: '子どもが公園でくるくる回って遊んでいます。', zh: '孩子在公园里转着圈玩。' },
      { ja: '上司の指示がくるくる変わって、困ります。', zh: '上司的指示变来变去，很头疼。' },
    ],
    commonMistakeZh: '「くるくる」轻快小圈，「ぐるぐる」沉重大圈（且有「思绪打转」用法）。浊音变大变重是オノマトペ的规律',
    recognition: { promptZh: '「指示がくるくる変わる」是什么意思？',
      options: ['指示频繁变来变去', '指示很明确', '指示被取消了', '指示太长'],
      answerIndex: 0, feedbackZh: '「くるくる変わる」= 变来变去' },
    production: { promptJa: '回るものを「くるくる」で言ってください。',
      promptZh: '用「くるくる」描述旋转的东西。',
      expected: ['くるくる'], acceptable: ['くるくる回ります', 'くるくる回っています'] },
    conversation: { themeJa: 'よく変わる予定への対応を話す',
      starterJa: '予定がくるくる変わる人が近くにいますか？', starterZh: '你身边有计划变来变去的人吗？',
      targetExpressions: ['くるくる'], followUpJa: '予定が変わったとき、どう対応しますか？',
      followUpZh: '计划有变时你怎么应对？' },
    difficulty: 'basic' }),
  d({ id: 'ono-gessori', sourceCandidateId: 'a35c4abadb4c53d9', surface: 'げっそり', kana: 'げっそり',
    category: 'gitaigo', usagePatterns: ['suru'],
    meaningJa: '急に痩せて、やつれた様子', meaningZh: '（状态）瘦得脱相、憔悴、面容枯槁',
    nuanceZh: '病气・过劳・打击导致的「短期间明显消瘦」。含担心的语气。也表「彻底没了兴致」（げっそりする）',
    similarJa: ['がりがり', 'やつれる'],
    examples: [
      { ja: '彼は残業続きで、げっそりしています。', zh: '他连续加班，整个人都憔悴了。' },
      { ja: '病気で1週間寝ていたら、頬がげっそりしました。', zh: '生病躺了一周，脸颊都瘦凹了。' },
    ],
    commonMistakeZh: '夸人瘦了变漂亮不能用「げっそり」（负面词）。褒义的「瘦了」用「すっきりした」「痩せてきれいになった」',
    recognition: { promptZh: '「げっそり」是褒义还是贬义？',
      options: ['贬义（憔悴、令人担心）', '褒义（苗条漂亮）', '中性（没有感情）', '看场合都是褒义'],
      answerIndex: 0, feedbackZh: '「げっそり」含「憔悴」的负面语感，不能用来夸人' },
    production: { promptJa: '疲れてやつれた人の様子を「げっそり」で言ってください。',
      promptZh: '用「げっそり」描述憔悴的人。',
      expected: ['げっそり'], acceptable: ['げっそりしています', 'げっそりしました'] },
    conversation: { themeJa: '働きすぎの同僚を気づかう会話',
      starterJa: '同僚がげっそりしていたら、何と声をかけますか？', starterZh: '同事看起来很憔悴时你会说什么？',
      targetExpressions: ['げっそり'], followUpJa: '自分がげっそりするほど忙しかった時期はありますか？',
      followUpZh: '你有过忙到憔悴的时期吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-geragera', sourceCandidateId: 'c978fd2668bca434', surface: 'げらげら', kana: 'げらげら',
    category: 'giongo', usagePatterns: ['to-verb'],
    meaningJa: '大きな声で遠慮なく笑う様子', meaningZh: '（拟声）哈哈大笑、放声大笑',
    nuanceZh: '不加抑制的大笑。场合によっては「品がない」と受け取られることもある。小声偷笑是「くすくす」',
    similarJa: ['くすくす', 'にこにこ'],
    examples: [
      { ja: 'お笑い番組を見て、げらげら笑いました。', zh: '看搞笑节目哈哈大笑。' },
      { ja: '電車の中でげらげら笑うのは、少し恥ずかしいです。', zh: '在电车里放声大笑有点不好意思。' },
    ],
    commonMistakeZh: '「げらげら」和「くすくす」是音量的两端。正式场合の描写では「大声で笑う」の方が中立',
    recognition: { promptZh: '「げらげら」是哪种笑？',
      options: ['放声大笑', '小声偷笑', '微笑', '冷笑'],
      answerIndex: 0, feedbackZh: '大声不加掩饰的笑 =「げらげら」' },
    production: { promptJa: '大笑いした経験を「げらげら」で言ってください。',
      promptZh: '用「げらげら」说一次大笑的经历。',
      expected: ['げらげら'], acceptable: ['げらげら笑いました'] },
    conversation: { themeJa: '笑った番組・動画について話す',
      starterJa: '最近、げらげら笑った動画や番組はありますか？', starterZh: '最近有让你哈哈大笑的视频或节目吗？',
      targetExpressions: ['げらげら'], followUpJa: '日本のお笑いを見たことがありますか？',
      followUpZh: '你看过日本的搞笑节目吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-gokugoku', sourceCandidateId: '8e02193ada8728eb', surface: 'ごくごく', kana: 'ごくごく',
    category: 'giongo', usagePatterns: ['to-verb'],
    meaningJa: '喉を鳴らして勢いよく飲む様子', meaningZh: '（拟声）咕咚咕咚地大口喝',
    nuanceZh: '口渇時に一気に飲む音。ビール、水、牛乳など。少しずつ飲むのは「ちびちび」',
    similarJa: ['ぐびぐび', 'ちびちび'],
    examples: [
      { ja: '運動の後、水をごくごく飲みました。', zh: '运动后咕咚咕咚地喝水。' },
      { ja: 'お風呂上がりの牛乳をごくごく飲むのが好きです。', zh: '喜欢洗完澡后大口喝牛奶。' },
    ],
    commonMistakeZh: '「ごくごく」只用于*喝*。大口吃饭用「ぱくぱく」「もりもり」，不要混用',
    recognition: { promptZh: '「ごくごく」和哪个动词搭配？',
      options: ['飲む', '食べる', '走る', '寝る'],
      answerIndex: 0, feedbackZh: '「ごくごく飲む」= 大口喝' },
    production: { promptJa: '喉が渇いたときの様子を「ごくごく」で言ってください。',
      promptZh: '用「ごくごく」描述口渴时喝水的样子。',
      expected: ['ごくごく'], acceptable: ['ごくごく飲みます', 'ごくごく飲みました'] },
    conversation: { themeJa: '好きな飲み物と飲み方を話す',
      starterJa: '暑い日、何をごくごく飲みたくなりますか？', starterZh: '热天你想大口喝什么？',
      targetExpressions: ['ごくごく'], followUpJa: 'お酒はごくごく派ですか？ちびちび派ですか？',
      followUpZh: '喝酒你是大口派还是小口慢酌派？' },
    difficulty: 'basic' }),
  d({ id: 'ono-kosokoso', sourceCandidateId: '4725bb854f9af9a5', surface: 'こそこそ', kana: 'こそこそ',
    category: 'gitaigo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '人に知られないように隠れて何かをする様子', meaningZh: '（状态）偷偷摸摸、鬼鬼祟祟',
    nuanceZh: '含「隐瞒・见不得人」的负面语感。「こそこそ話す」（交头接耳）は聞かれたくない話',
    similarJa: ['ひそひそ', 'そっと'],
    examples: [
      { ja: '二人が廊下でこそこそ話しています。', zh: '两个人在走廊里偷偷说话。' },
      { ja: 'こそこそしないで、はっきり言ってください。', zh: '别偷偷摸摸的，请直说。' },
    ],
    commonMistakeZh: '善意的「悄悄地」（不打扰别人）用「そっと」；「こそこそ」带「心里有鬼」的负面色彩',
    recognition: { promptZh: '「こそこそ」的语感是？',
      options: ['偷偷摸摸（负面）', '安静体贴（正面）', '大大方方', '热热闹闹'],
      answerIndex: 0, feedbackZh: '「こそこそ」= 见不得人的偷偷摸摸' },
    production: { promptJa: '隠れて何かをする様子を「こそこそ」で言ってください。',
      promptZh: '用「こそこそ」描述偷偷做事的样子。',
      expected: ['こそこそ'], acceptable: ['こそこそしています', 'こそこそ話しています'] },
    conversation: { themeJa: '職場のひそひそ話について話す',
      starterJa: '職場でこそこそ話している人を見たら、気になりますか？', starterZh: '看到同事偷偷咬耳朵你会在意吗？',
      targetExpressions: ['こそこそ'], followUpJa: '「そっと」と「こそこそ」の違いを説明できますか？',
      followUpZh: '你能说明「そっと」和「こそこそ」的区别吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-goshigoshi', sourceCandidateId: 'f0dbe7a82da22ed1', surface: 'ごしごし', kana: 'ごしごし',
    category: 'giongo', usagePatterns: ['to-verb'],
    meaningJa: '力を入れてこする様子', meaningZh: '（拟声）用力搓洗、使劲擦',
    nuanceZh: '洗衣服、擦地板、搓背等の力仕事。「目をごしごしこすらない」は日常の注意表現',
    similarJa: ['ぴかぴか', 'さっと'],
    examples: [
      { ja: '汚れた靴をごしごし洗いました。', zh: '把脏鞋子使劲刷干净了。' },
      { ja: '目がかゆくても、ごしごしこすらないでください。', zh: '眼睛痒也不要使劲揉。' },
    ],
    commonMistakeZh: '「ごしごし」是带摩擦音的用力搓。轻轻擦拭用「さっと拭く」「軽く拭く」',
    recognition: { promptZh: '「ごしごし」的动作是？',
      options: ['用力搓・刷', '轻轻碰', '慢慢看', '大声说'],
      answerIndex: 0, feedbackZh: '用力反复摩擦 =「ごしごし」' },
    production: { promptJa: '掃除や洗濯の様子を「ごしごし」で言ってください。',
      promptZh: '用「ごしごし」描述打扫或洗衣。',
      expected: ['ごしごし'], acceptable: ['ごしごし洗います', 'ごしごしこすります'] },
    conversation: { themeJa: '掃除・洗濯の習慣を話す',
      starterJa: '週末、何をごしごし洗いますか？', starterZh: '周末你会使劲刷洗什么？',
      targetExpressions: ['ごしごし'], followUpJa: '掃除は好きですか？苦手ですか？',
      followUpZh: '你喜欢打扫吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-gochagocha', sourceCandidateId: 'fc98110b26c1d80b', surface: 'ごちゃごちゃ', kana: 'ごちゃごちゃ',
    category: 'gitaigo', usagePatterns: ['suru', 'da-na'],
    meaningJa: 'いろいろな物が入り混じって整理されていない様子', meaningZh: '（状态）乱糟糟、杂乱无章',
    nuanceZh: '物・情報・話が「多而杂乱」。「ごちゃごちゃ言う」（罗里吧嗦地抱怨）という用法もある',
    similarJa: ['ぐちゃぐちゃ', 'ばらばら'],
    examples: [
      { ja: '机の上がごちゃごちゃしていて、探し物が見つかりません。', zh: '桌上乱糟糟的，要找的东西找不到。' },
      { ja: '頭の中がごちゃごちゃして、整理できません。', zh: '脑子里乱成一团，理不清头绪。' },
    ],
    commonMistakeZh: '「ぐちゃぐちゃ」是形状崩坏的烂糟糟，「ごちゃごちゃ」是多物混杂的乱糟糟。房间乱两者都可，湿透的纸只能「ぐちゃぐちゃ」',
    recognition: { promptZh: '「ごちゃごちゃ言わないで」是什么意思？',
      options: ['别罗里吧嗦地抱怨', '请大声说', '请再说一遍', '请安静地整理'],
      answerIndex: 0, feedbackZh: '「ごちゃごちゃ言う」= 啰嗦地发牢骚' },
    production: { promptJa: '散らかった机を「ごちゃごちゃ」で言ってください。',
      promptZh: '用「ごちゃごちゃ」描述凌乱的桌子。',
      expected: ['ごちゃごちゃ'], acceptable: ['ごちゃごちゃしています', 'ごちゃごちゃです'] },
    conversation: { themeJa: '整理整頓について話す',
      starterJa: 'あなたの机は、ごちゃごちゃしていますか？整っていますか？', starterZh: '你的桌子是乱糟糟还是整整齐齐？',
      targetExpressions: ['ごちゃごちゃ'], followUpJa: '頭がごちゃごちゃしたとき、どう整理しますか？',
      followUpZh: '思绪乱的时候你怎么整理？' },
    difficulty: 'basic' }),
  d({ id: 'ono-kotsukotsu', sourceCandidateId: 'ab367b9615d44dff', surface: 'こつこつ', kana: 'こつこつ',
    category: 'gitaigo', usagePatterns: ['to-verb'],
    meaningJa: '地道に少しずつ努力を続ける様子', meaningZh: '（状态）踏踏实实、一点一点坚持',
    nuanceZh: '日本文化で高く評価される美徳語。貯金・勉強・練習と相性がよい。褒め言葉として安心して使える',
    similarJa: ['じっくり', 'ちゃくちゃく'],
    examples: [
      { ja: 'こつこつ貯めたお金で、自転車を買いました。', zh: '用一点一点存下的钱买了自行车。' },
      { ja: 'こつこつ貯金して、旅行に行きました。', zh: '一点一点存钱，去了旅行。' },
    ],
    commonMistakeZh: '中文「努力」偏拼劲，「こつこつ」强调*细水长流的坚持*。夸日本同事时「こつこつ頑張っていますね」很地道',
    recognition: { promptZh: '「こつこつ」最适合形容哪种人？',
      options: ['每天坚持背10个单词的人', '一夜暴富的人', '三分钟热度的人', '爱睡懒觉的人'],
      answerIndex: 0, feedbackZh: '持续的小努力 =「こつこつ」' },
    production: { promptJa: '続けている努力を「こつこつ」で言ってください。',
      promptZh: '用「こつこつ」说说你在坚持的努力。',
      expected: ['こつこつ'], acceptable: ['こつこつ勉強しています', 'こつこつ続けています'] },
    conversation: { themeJa: '長く続けている努力を話す',
      starterJa: '何をこつこつ続けていますか？', starterZh: '你在踏实坚持做什么？',
      targetExpressions: ['こつこつ'], followUpJa: 'こつこつ型と一気型、自分はどちらですか？',
      followUpZh: '细水长流型和一鼓作气型，你是哪种？' },
    difficulty: 'basic' }),
  d({ id: 'ono-kotteri', sourceCandidateId: '8c1f1118e01dc48a', surface: 'こってり', kana: 'こってり',
    category: 'gitaigo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '味が濃くて油分が多い感じ', meaningZh: '（状态）（味道）浓厚、油重、味浓',
    nuanceZh: '拉面・豚骨汤の定番表現。好きな人には褒め言葉。「あっさり」の対義語としてセットで覚える',
    similarJa: ['あっさり', 'ぎとぎと'],
    examples: [
      { ja: 'こってりした豚骨ラーメンが大好きです。', zh: '最爱浓厚的豚骨拉面。' },
      { ja: '疲れた日は、こってりしたものが食べたくなります。', zh: '累的日子就想吃味道浓重的东西。' },
    ],
    commonMistakeZh: '负面的「油腻腻」是「ぎとぎと」。「こってり」本身多为中性〜正面（浓郁）',
    recognition: { promptZh: '「こってり」的反义词是？',
      options: ['あっさり', 'ぎっしり', 'ぐっすり', 'がっかり'],
      answerIndex: 0, feedbackZh: '味道浓厚⇔清淡 =「こってり⇔あっさり」' },
    production: { promptJa: '好きなラーメンを「こってり」か「あっさり」で言ってください。',
      promptZh: '用「こってり」或「あっさり」说说你喜欢的拉面。',
      expected: ['こってり'], acceptable: ['こってり系が好きです', 'こってりしたラーメン'] },
    conversation: { themeJa: 'ラーメンの好みで盛り上がる',
      starterJa: 'こってりラーメンの おすすめの店はありますか？', starterZh: '有推荐的浓厚系拉面店吗？',
      targetExpressions: ['こってり'], followUpJa: '中国の麺料理は、こってり系が多いですか？',
      followUpZh: '中国的面食浓厚系多吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-konagona', sourceCandidateId: 'eed1c287bbd2629e', surface: 'こなごな', kana: 'こなごな',
    category: 'gitaigo', usagePatterns: ['ni-naru'],
    meaningJa: '硬い物が細かく砕ける様子', meaningZh: '（状态）摔得粉碎、粉身碎骨',
    nuanceZh: '「粉々になる」の形でほぼ固定。ガラス・陶器の破損に。夢や心が砕ける比喩もある',
    similarJa: ['ばらばら', 'ぼろぼろ'],
    examples: [
      { ja: 'うっかりぶつけて、コップがこなごなに割れました。', zh: '不小心撞了一下，杯子摔得粉碎。' },
      { ja: 'お気に入りのマグカップが、こなごなに割れました。', zh: '心爱的马克杯摔得粉碎。' },
    ],
    commonMistakeZh: '「ばらばら」是散成几块，「こなごな」是碎成粉末级。碎的程度不同',
    recognition: { promptZh: '「こなごな」形容哪种碎法？',
      options: ['碎成细小的渣', '裂了一条缝', '分成两半', '完好无损'],
      answerIndex: 0, feedbackZh: '碎得很细 =「こなごな」' },
    production: { promptJa: '何かが割れた経験を「こなごな」で言ってください。',
      promptZh: '用「こなごな」说一次摔碎东西的经历。',
      expected: ['こなごな'], acceptable: ['こなごなになりました', 'こなごなに割れました'] },
    conversation: { themeJa: '物を壊した失敗談を話す',
      starterJa: '大事な物をこなごなにしてしまったことがありますか？', starterZh: '有没有把重要的东西摔得粉碎过？',
      targetExpressions: ['こなごな'], followUpJa: 'スマホの画面、今までに何回割りましたか？',
      followUpZh: '手机屏幕你摔碎过几次？' },
    difficulty: 'plus' }),
  d({ id: 'ono-sappari', sourceCandidateId: '648351f4db78d8fc', surface: 'さっぱり', kana: 'さっぱり',
    category: 'gitaigo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '①爽やかで気持ちがいい様子 ②（否定と共に）全然', meaningZh: '（状态）①清爽、爽快 ②（接否定）完全（不）',
    nuanceZh: '①风呂上がり・散髪後・あっさりした味。②「さっぱり分からない」=完全不懂（重要な第2用法）',
    similarJa: ['すっきり', 'あっさり'],
    examples: [
      { ja: 'シャワーを浴びて、さっぱりしました。', zh: '冲了个澡，浑身清爽。' },
      { ja: '先生の説明が難しくて、さっぱり分かりませんでした。', zh: '老师的说明太难，完全没听懂。' },
    ],
    commonMistakeZh: '「さっぱり分からない」の「さっぱり」は「清爽」ではなく「完全に（〜ない）」。否定文とセットの用法を知らないと誤読する',
    recognition: { promptZh: '「さっぱり分からない」是什么意思？',
      options: ['完全不懂', '基本懂了', '清爽地明白了', '有点懂'],
      answerIndex: 0, feedbackZh: '「さっぱり＋否定」= 完全（不）〜' },
    production: { promptJa: 'お風呂上がりの気分を「さっぱり」で言ってください。',
      promptZh: '用「さっぱり」说说洗完澡的感觉。',
      expected: ['さっぱり'], acceptable: ['さっぱりしました', 'さっぱりします'] },
    conversation: { themeJa: '気分転換の方法を話す',
      starterJa: '気分をさっぱりさせたいとき、何をしますか？', starterZh: '想让心情清爽时你做什么？',
      targetExpressions: ['さっぱり'], followUpJa: '「さっぱり分からない」と言った経験はありますか？',
      followUpZh: '你有过想说「完全不懂」的时候吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-sarasara', sourceCandidateId: 'c4ee5b567cccbcb5', surface: 'さらさら', kana: 'さらさら',
    category: 'gitaigo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '乾いていて滑らかな様子・軽やかに流れる様子', meaningZh: '（状态）（头发）柔顺光滑、（小溪）潺潺、（书写）流畅',
    nuanceZh: '髪・砂・小川・ペンの動きなど「軽くて引っかからない」感触。シャンプーCMの定番語',
    similarJa: ['つるつる', 'ざらざら'],
    examples: [
      { ja: '風に乗って、砂がさらさら流れていきます。', zh: '随着风，沙子沙沙地流走。' },
      { ja: '小川がさらさら流れています。', zh: '小溪潺潺流淌。' },
    ],
    commonMistakeZh: '「さらさら」（干爽顺滑）の反対は「ざらざら」（粗糙）と「べたべた」（黏腻）。湿气の日の髪は「べたべた」',
    recognition: { promptZh: '「さらさら」的头发是什么样的？',
      options: ['柔顺光滑', '油腻打结', '粗糙干枯', '湿漉漉'],
      answerIndex: 0, feedbackZh: '顺滑不打结 =「さらさら」' },
    production: { promptJa: '髪や川の様子を「さらさら」で言ってください。',
      promptZh: '用「さらさら」描述头发或小溪。',
      expected: ['さらさら'], acceptable: ['さらさらです', 'さらさらになりました'] },
    conversation: { themeJa: '髪のケアについて話す',
      starterJa: '髪をさらさらに保つために、何かしていますか？', starterZh: '为了保持头发柔顺你做什么护理？',
      targetExpressions: ['さらさら'], followUpJa: '日本のシャンプーと中国のシャンプー、どちらを使いますか？',
      followUpZh: '你用日本的还是中国的洗发水？' },
    difficulty: 'basic' }),
  d({ id: 'ono-zarazara', sourceCandidateId: 'd6f87eb84b98910e', surface: 'ざらざら', kana: 'ざらざら',
    category: 'gitaigo', usagePatterns: ['suru', 'da-na'],
    meaningJa: '表面が粗くて滑らかでない様子', meaningZh: '（状态）（表面）粗糙、涩涩的、砂砂的',
    nuanceZh: '砂壁・乾燥肌・砂の床など「触ると引っかかる」感触。肌の状態を伝えるときに実用的',
    similarJa: ['さらさら', 'つるつる'],
    examples: [
      { ja: '冬は乾燥して、肌がざらざらします。', zh: '冬天干燥，皮肤变得粗糙。' },
      { ja: '砂で床がざらざらしています。', zh: '地板上有沙子，踩着砂砂的。' },
    ],
    commonMistakeZh: '「さらさら」（顺滑・褒义）と「ざらざら」（粗糙・贬义）は清音・浊音の対。浊音=不快はオノマトペの重要規則',
    recognition: { promptZh: '「ざらざら」的触感是？',
      options: ['粗糙拉手', '光滑', '柔软', '冰凉'],
      answerIndex: 0, feedbackZh: '表面粗糙 =「ざらざら」' },
    production: { promptJa: '乾燥した肌の状態を「ざらざら」で言ってください。',
      promptZh: '用「ざらざら」描述干燥的皮肤。',
      expected: ['ざらざら'], acceptable: ['ざらざらします', 'ざらざらしています'] },
    conversation: { themeJa: '乾燥対策について話す',
      starterJa: '冬、肌がざらざらしませんか？どんな対策をしていますか？', starterZh: '冬天皮肤会变粗糙吗？你怎么保养？',
      targetExpressions: ['ざらざら'], followUpJa: '「さらさら」と「ざらざら」、音の違いで意味が変わるのは面白いですね。ほかに知っていますか？',
      followUpZh: '清音浊音改变意思很有趣吧。你还知道别的例子吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-jimejime', sourceCandidateId: 'a923c38a618533fa', surface: 'じめじめ', kana: 'じめじめ',
    category: 'gitaigo', usagePatterns: ['suru'],
    meaningJa: '湿気が多くて不快な様子', meaningZh: '（状态）潮乎乎、湿闷（令人不适）',
    nuanceZh: '梅雨の定番語。天気だけでなく「じめじめした性格」（阴郁的性格）という比喩もある',
    similarJa: ['むしむし', 'からっと'],
    examples: [
      { ja: '地下の倉庫はじめじめしていて、本が傷みます。', zh: '地下仓库很潮湿，书会受损。' },
      { ja: '日本の夏は、じめじめして蒸し暑いです。', zh: '日本的夏天又湿又闷热。' },
    ],
    commonMistakeZh: '「湿度が高い」は中立、「じめじめ」は*不快感込み*。心地よい潤いは「しっとり」（褒义）',
    recognition: { promptZh: '「じめじめ」什么时候用？',
      options: ['梅雨季潮湿难受时', '空气干爽时', '晴天户外时', '雪天时'],
      answerIndex: 0, feedbackZh: '潮湿+不舒服 =「じめじめ」' },
    production: { promptJa: '梅雨の様子を「じめじめ」で言ってください。',
      promptZh: '用「じめじめ」描述梅雨季。',
      expected: ['じめじめ'], acceptable: ['じめじめしています', 'じめじめします'] },
    conversation: { themeJa: '梅雨の過ごし方を話す',
      starterJa: '日本のじめじめした梅雨、どうやって乗り切っていますか？', starterZh: '日本潮乎乎的梅雨季你怎么熬过去？',
      targetExpressions: ['じめじめ'], followUpJa: '故郷の気候と比べて、日本の湿気はどうですか？',
      followUpZh: '和家乡气候比，日本的湿气怎么样？' },
    difficulty: 'basic' }),
  d({ id: 'ono-shuwashuwa', sourceCandidateId: 'c414814b912cbdee', surface: 'しゅわしゅわ', kana: 'しゅわしゅわ',
    category: 'giongo', usagePatterns: ['suru'],
    meaningJa: '炭酸の泡がはじける様子', meaningZh: '（拟声）气泡咝咝地冒、（碳酸）气泡翻腾',
    nuanceZh: 'ソーダ・ビール・入浴剤の泡。爽快感のある擬音。飲料の商品説明でよく見る',
    similarJa: ['ぱちぱち', 'ぶくぶく'],
    examples: [
      { ja: '注いだばかりのビールが、しゅわしゅわ音を立てています。', zh: '刚倒好的啤酒咝咝地冒着气泡。' },
      { ja: 'お風呂に入浴剤を入れると、しゅわしゅわ泡が出ます。', zh: '浴缸里放入浴剂，咝咝地冒泡。' },
    ],
    commonMistakeZh: '「しゅわしゅわ」是碳酸类的细泡。锅里咕嘟咕嘟的沸腾是「ぐつぐつ」，不要混用',
    recognition: { promptZh: '「しゅわしゅわ」形容什么？',
      options: ['碳酸饮料的气泡', '锅里炖菜沸腾', '风吹树叶', '下大雨'],
      answerIndex: 0, feedbackZh: '碳酸气泡 =「しゅわしゅわ」' },
    production: { promptJa: '炭酸飲料の様子を「しゅわしゅわ」で言ってください。',
      promptZh: '用「しゅわしゅわ」描述碳酸饮料。',
      expected: ['しゅわしゅわ'], acceptable: ['しゅわしゅわしています', 'しゅわしゅわします'] },
    conversation: { themeJa: '好きな炭酸飲料について話す',
      starterJa: 'しゅわしゅわした飲み物は好きですか？', starterZh: '你喜欢带气的饮料吗？',
      targetExpressions: ['しゅわしゅわ'], followUpJa: 'お風呂のしゅわしゅわする入浴剤を使ったことがありますか？',
      followUpZh: '用过咝咝冒泡的入浴剂吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-jirojiro', sourceCandidateId: '054d91cac253f571', surface: 'じろじろ', kana: 'じろじろ',
    category: 'gitaigo', usagePatterns: ['to-verb'],
    meaningJa: '遠慮なくじっと見つめる様子', meaningZh: '（状态）目不转睛地盯着看、上下打量',
    nuanceZh: '失礼な視線の代表語。「じろじろ見ないで」は不快を伝える定型句。マナーの話題で頻出',
    similarJa: ['ちらちら', 'じっと'],
    examples: [
      { ja: 'スーツ姿が珍しいのか、後輩にじろじろ見られました。', zh: '可能是西装少见，被后辈上下打量。' },
      { ja: '電車で外国人だからか、じろじろ見られて嫌でした。', zh: '在电车上可能因为是外国人，被人盯着看很不舒服。' },
    ],
    commonMistakeZh: '「じっと見る」是专注地看（中性），「じろじろ見る」是无礼地打量（负面）。程度と失礼さが違う',
    recognition: { promptZh: '「じろじろ見る」给人什么感觉？',
      options: ['不礼貌、令人不适', '亲切友好', '认真学习', '害羞可爱'],
      answerIndex: 0, feedbackZh: '无遠慮の視線 =「じろじろ」（失礼）' },
    production: { promptJa: '見られて嫌だった経験を「じろじろ」で言ってください。',
      promptZh: '用「じろじろ」说一次被盯着看的不快经历。',
      expected: ['じろじろ'], acceptable: ['じろじろ見られました', 'じろじろ見ないでください'] },
    conversation: { themeJa: '視線のマナーについて話す',
      starterJa: '日本で、じろじろ見られたと感じたことがありますか？', starterZh: '在日本有被人盯着看的经历吗？',
      targetExpressions: ['じろじろ'], followUpJa: '中国と日本で、視線のマナーに違いはありますか？',
      followUpZh: '中日之间看人的礼仪有差异吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-jinjin', sourceCandidateId: '942759decb33e082', surface: 'じんじん', kana: 'じんじん',
    category: 'gijougo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: 'しびれるように痛みが続く様子', meaningZh: '（感觉）阵阵刺痛、麻酥酥地疼',
    nuanceZh: '正座後のしびれ・打撲・寒さで手が痛むときの「脉动般持续的疼/麻」。症状説明に実用的',
    similarJa: ['ずきずき', 'ひりひり'],
    examples: [
      { ja: '正座をしていたら、足がじんじんしびれました。', zh: '跪坐久了，脚麻得阵阵发疼。' },
      { ja: '寒さで指先がじんじんします。', zh: '冻得指尖阵阵刺痛。' },
    ],
    commonMistakeZh: '头的抽痛是「ずきずき」，烧伤的刺痛是「ひりひり」，麻痛是「じんじん」。医院で使い分けると症状が正確に伝わる',
    recognition: { promptZh: '「じんじん」最适合哪种痛？',
      options: ['腿麻后的阵阵麻痛', '头一跳一跳地痛', '晒伤火辣辣地痛', '完全不痛'],
      answerIndex: 0, feedbackZh: '麻+持续痛 =「じんじん」' },
    production: { promptJa: '足がしびれた経験を「じんじん」で言ってください。',
      promptZh: '用「じんじん」说一次腿麻的经历。',
      expected: ['じんじん'], acceptable: ['じんじんします', 'じんじんしびれました'] },
    conversation: { themeJa: '正座の経験について話す',
      starterJa: '正座をして、足がじんじんしたことがありますか？', starterZh: '跪坐后脚麻得刺痛过吗？',
      targetExpressions: ['じんじん'], followUpJa: '痛みの言葉（ずきずき・ひりひり）も使い分けられそうですか？',
      followUpZh: '疼痛的其他说法你能区分使用吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-sukasuka', sourceCandidateId: 'df9d07434204a00f', surface: 'すかすか', kana: 'すかすか',
    category: 'gitaigo', usagePatterns: ['da-na'],
    meaningJa: '中身が少なく、隙間が多い様子', meaningZh: '（状态）空落落、稀稀拉拉、（内容）空洞',
    nuanceZh: '電車・冷蔵庫・スケジュール帳など「本来入るべき物が少ない」。「がらがら」より中身のなさを強調',
    similarJa: ['がらがら', 'ぎっしり'],
    examples: [
      { ja: '給料日前で、冷蔵庫がすかすかです。', zh: '发工资前，冰箱空空如也。' },
      { ja: '連休明けの電車は、意外とすかすかでした。', zh: '连休结束后的电车意外地空。' },
    ],
    commonMistakeZh: '「がらがら」偏「场所没人」，「すかすか」偏「容器没装满」。冰箱空了用「すかすか」更自然',
    recognition: { promptZh: '「冷蔵庫がすかすか」是什么状态？',
      options: ['冰箱几乎空了', '冰箱塞得满满', '冰箱坏了', '冰箱很冷'],
      answerIndex: 0, feedbackZh: '中身が少ない =「すかすか」' },
    production: { promptJa: '中身が少ない様子を「すかすか」で言ってください。',
      promptZh: '用「すかすか」描述空落落的状态。',
      expected: ['すかすか'], acceptable: ['すかすかです', 'すかすかでした'] },
    conversation: { themeJa: '冷蔵庫の中身について話す',
      starterJa: '今、あなたの冷蔵庫はすかすかですか？ぎっしりですか？', starterZh: '现在你的冰箱是空落落还是满满的？',
      targetExpressions: ['すかすか'], followUpJa: '買い物は週に何回行きますか？',
      followUpZh: '你一周买几次菜？' },
    difficulty: 'basic' }),
];
