// Phase 3P-3: オノマトペ完成draft バッチ4（ぴったり〜べろべろ・21語）。
// 完成条件はonomatopoeiaDrafts.tsと同一（全field完備のみ収録）。全draft。
import type { OnomatopoeiaDraft } from './onomatopoeiaDrafts';

const d = (p: Omit<OnomatopoeiaDraft, 'unit' | 'publishStatus' | 'humanReviewed' | 'approved' | 'reviewKey'> & { reviewKey?: string }): OnomatopoeiaDraft =>
  ({ unit: 'ono-unit-1', publishStatus: 'draft', humanReviewed: false, approved: false,
     reviewKey: p.id, ...p });

export const ONOMATOPOEIA_DRAFTS_BATCH4: OnomatopoeiaDraft[] = [
  d({ id: 'ono-pittari', sourceCandidateId: 'e4685e6889c08780', surface: 'ぴったり', kana: 'ぴったり',
    category: 'gitaigo', usagePatterns: ['da-na', 'to-verb'],
    meaningJa: '大きさ・好み・条件が完全に合う様子', meaningZh: '（状态）正合适、恰好、严丝合缝',
    nuanceZh: '服のサイズ・待ち合わせ時刻・相性まで幅広い。「あなたにぴったり」は接客の定番の褒め言葉',
    similarJa: ['ちょうど', 'ぶかぶか'],
    examples: [
      { ja: 'この靴は、サイズがぴったりです。', zh: '这双鞋尺码正合适。' },
      { ja: '3時ぴったりに会議が始まりました。', zh: '会议3点整准时开始。' },
    ],
    commonMistakeZh: '「ぴったり」は時刻にも使える（3時ぴったり=3点整）。中文「合适」だけで覚えると時刻用法を見落とす',
    recognition: { promptZh: '「サイズがぴったり」是什么意思？',
      options: ['尺码正合适', '太大了', '太小了', '没有货'],
      answerIndex: 0, feedbackZh: '完全吻合 =「ぴったり」' },
    production: { promptJa: '買い物でサイズが合ったことを「ぴったり」で言ってください。',
      promptZh: '用「ぴったり」说买东西尺码合适。',
      expected: ['ぴったり'], acceptable: ['ぴったりです', 'ぴったりでした'] },
    conversation: { themeJa: '自分にぴったりの物を話す',
      starterJa: '最近買った物で、自分にぴったりだった物はありますか？', starterZh: '最近买的东西里有正合适你的吗？',
      targetExpressions: ['ぴったり'], followUpJa: '日本の服のサイズは、合いますか？',
      followUpZh: '日本衣服的尺码适合你吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-hyorohyoro', sourceCandidateId: 'b70a57b8fd1cd541', surface: 'ひょろひょろ', kana: 'ひょろひょろ',
    category: 'gitaigo', usagePatterns: ['suru', 'da-na'],
    meaningJa: '細長くて弱々しい様子', meaningZh: '（状态）细高瘦弱、豆芽菜似的',
    nuanceZh: '背が高いのに細くて頼りない体型・植物の徒長。やや негативные評価を含むので人に直接言うのは注意',
    similarJa: ['がりがり', 'ひょろり'],
    examples: [
      { ja: '日光が足りなくて、野菜の苗がひょろひょろしています。', zh: '光照不够，菜苗长得细弱。' },
      { ja: '学生のころは、ひょろひょろでした。', zh: '学生时代我瘦得像豆芽菜。' },
    ],
    commonMistakeZh: '「痩せている」は中立、「ひょろひょろ」は「弱々しい」評価込み。他人の体型には使わないのが無難（自虐はOK）',
    recognition: { promptZh: '「ひょろひょろ」的印象是？',
      options: ['细高而弱不禁风', '结实健壮', '矮胖', '灵活敏捷'],
      answerIndex: 0, feedbackZh: '细长无力 =「ひょろひょろ」' },
    production: { promptJa: '昔の自分の体型を「ひょろひょろ」で言ってください。',
      promptZh: '用「ひょろひょろ」说说以前的体型（自嘲）。',
      expected: ['ひょろひょろ'], acceptable: ['ひょろひょろでした', 'ひょろひょろしていました'] },
    conversation: { themeJa: '学生時代の体型・運動を話す',
      starterJa: '学生のころは、ひょろひょろでしたか？がっしりでしたか？', starterZh: '学生时代你是瘦竹竿还是壮实型？',
      targetExpressions: ['ひょろひょろ'], followUpJa: '今、体型維持のために何かしていますか？',
      followUpZh: '现在为保持体型做什么吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-pyonpyon', sourceCandidateId: '214023e36ed777e5', surface: 'ぴょんぴょん', kana: 'ぴょんぴょん',
    category: 'gitaigo', usagePatterns: ['to-verb'],
    meaningJa: '軽く何度も跳ねる様子', meaningZh: '（状态）蹦蹦跳跳、一蹦一蹦',
    nuanceZh: 'うさぎ・カエル・喜ぶ子ども。軽快で可愛い跳ね方。重い一回のジャンプは「どすん」系',
    similarJa: ['ぴょこぴょこ', 'とんとん'],
    examples: [
      { ja: 'うさぎがぴょんぴょん跳ねています。', zh: '兔子蹦蹦跳跳。' },
      { ja: '子どもが嬉しくて、ぴょんぴょん跳んでいます。', zh: '孩子高兴得蹦蹦跳跳。' },
    ],
    commonMistakeZh: '「ぴょんぴょん」は連続の軽いジャンプ。1回だけなら「ぴょんと跳ぶ」。回数のニュアンスを持つ',
    recognition: { promptZh: '「ぴょんぴょん」最适合形容什么？',
      options: ['兔子连续跳', '大象走路', '鱼游泳', '鸟飞翔'],
      answerIndex: 0, feedbackZh: '轻快连跳 =「ぴょんぴょん」' },
    production: { promptJa: '動物や子どもの跳ねる様子を「ぴょんぴょん」で言ってください。',
      promptZh: '用「ぴょんぴょん」描述动物或孩子蹦跳。',
      expected: ['ぴょんぴょん'], acceptable: ['ぴょんぴょん跳ねています', 'ぴょんぴょん跳んでいます'] },
    conversation: { themeJa: '嬉しかった瞬間の反応を話す',
      starterJa: '嬉しくてぴょんぴょん跳びたくなった経験はありますか？', starterZh: '有高兴得想蹦起来的经历吗？',
      targetExpressions: ['ぴょんぴょん'], followUpJa: '日本でうさぎカフェに行ったことがありますか？',
      followUpZh: '你去过日本的兔子咖啡吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-hirahira', sourceCandidateId: '0bee5c306acbfd44', surface: 'ひらひら', kana: 'ひらひら',
    category: 'gitaigo', usagePatterns: ['to-verb', 'suru'],
    meaningJa: '薄く軽いものが舞う様子', meaningZh: '（状态）（花瓣、蝴蝶）翩翩飞舞、轻轻飘落',
    nuanceZh: '桜の花びら・蝶・カーテン。日本の春の描写の定番。「桜がひらひら舞う」は覚えておきたい美しい表現',
    similarJa: ['はらはら', 'ふわふわ'],
    examples: [
      { ja: '桜の花びらが、ひらひらと舞っています。', zh: '樱花花瓣翩翩飘舞。' },
      { ja: '蝶がひらひら飛んでいます。', zh: '蝴蝶翩翩飞舞。' },
    ],
    commonMistakeZh: '雪は「ちらちら」「しんしん」、花びら・蝶は「ひらひら」。舞うものの質感で選ぶ',
    recognition: { promptZh: '「ひらひら」最适合形容什么？',
      options: ['樱花花瓣飘落', '大石头滚落', '大雨倾盆', '汽车疾驰'],
      answerIndex: 0, feedbackZh: '轻薄物飘舞 =「ひらひら」' },
    production: { promptJa: '桜の散る様子を「ひらひら」で言ってください。',
      promptZh: '用「ひらひら」描述樱花飘落。',
      expected: ['ひらひら'], acceptable: ['ひらひら舞っています', 'ひらひら散っています'] },
    conversation: { themeJa: '花見の経験を話す',
      starterJa: '桜がひらひら舞う中で、お花見をしたことがありますか？', starterZh: '在樱花飘舞中赏过花吗？',
      targetExpressions: ['ひらひら'], followUpJa: 'おすすめの花見スポットはありますか？',
      followUpZh: '有推荐的赏樱地点吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-biribiri', sourceCandidateId: 'a705d3f103dbc8b0', surface: 'びりびり', kana: 'びりびり',
    category: 'gijougo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '電気が流れてしびれる様子・紙を破る音', meaningZh: '（感觉・拟声）①电得发麻 ②哗啦哗啦撕（纸）',
    nuanceZh: '①静電気・電気ショックのしびれ。②紙を破る音（びりびり破る）。冬のドアノブの静電気で使う機会が多い',
    similarJa: ['じんじん', 'ばりばり'],
    examples: [
      { ja: '冬はドアノブで、静電気がびりびりします。', zh: '冬天碰门把手被静电电得发麻。' },
      { ja: '要らない書類を、びりびり破りました。', zh: '把不要的文件哗啦哗啦撕掉了。' },
    ],
    commonMistakeZh: '「びりびり」には電気と紙破りの2用法。文脈で判断。しびれ続ける痛みは「じんじん」と区別',
    recognition: { promptZh: '冬天碰门把手「びりびり」是什么？',
      options: ['静电电到了', '门坏了', '手很冷', '门很重'],
      answerIndex: 0, feedbackZh: '电流的麻感 =「びりびり」' },
    production: { promptJa: '静電気の経験を「びりびり」で言ってください。',
      promptZh: '用「びりびり」说被静电电到的经历。',
      expected: ['びりびり'], acceptable: ['びりびりしました', 'びりびりします'] },
    conversation: { themeJa: '冬の静電気対策を話す',
      starterJa: '冬、静電気でびりびりしませんか？対策はありますか？', starterZh: '冬天被静电电到吗？有什么对策？',
      targetExpressions: ['びりびり'], followUpJa: '乾燥する日本の冬、ほかに困ることはありますか？',
      followUpZh: '干燥的日本冬天还有别的困扰吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-hinyari', sourceCandidateId: 'a8795aa52f7d5a91', surface: 'ひんやり', kana: 'ひんやり',
    category: 'gitaigo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '心地よく冷たい様子', meaningZh: '（状态）凉丝丝、冰冰凉凉（舒服的凉）',
    nuanceZh: '夏の木陰・冷感グッズ・冷たいシーツなど「気持ちいい涼しさ」。不快な寒さ（寒い・ぞくぞく）とは逆',
    similarJa: ['すずしい', 'ぞくぞく'],
    examples: [
      { ja: '木陰に入ると、ひんやりして気持ちいいです。', zh: '走进树荫，凉丝丝的很舒服。' },
      { ja: '夏は、ひんやりする枕を使っています。', zh: '夏天用凉感枕头。' },
    ],
    commonMistakeZh: '「ひんやり」は基本的に心地よい涼しさ（正面）。凍える寒さは「ぞくぞく」「ぶるぶる」。日本の冷感商品名によく登場',
    recognition: { promptZh: '「ひんやり」是哪种凉？',
      options: ['舒服的凉丝丝', '冻得发抖', '发烧发冷', '热得难受'],
      answerIndex: 0, feedbackZh: '心地よい涼しさ =「ひんやり」' },
    production: { promptJa: '夏の涼しい場所を「ひんやり」で言ってください。',
      promptZh: '用「ひんやり」描述夏天凉快的地方。',
      expected: ['ひんやり'], acceptable: ['ひんやりします', 'ひんやりして気持ちいいです'] },
    conversation: { themeJa: '夏の暑さ対策を話す',
      starterJa: '日本の夏、ひんやりグッズを使っていますか？', starterZh: '日本的夏天你用凉感用品吗？',
      targetExpressions: ['ひんやり'], followUpJa: 'おすすめの暑さ対策があったら教えてください',
      followUpZh: '有推荐的防暑对策请告诉我' },
    difficulty: 'basic' }),
  d({ id: 'ono-fukafuka', sourceCandidateId: 'acafe2f247a02237', surface: 'ふかふか', kana: 'ふかふか',
    category: 'gitaigo', usagePatterns: ['suru', 'da-na'],
    meaningJa: '柔らかくふくらんで気持ちいい様子', meaningZh: '（状态）松软蓬松（被褥、沙发）',
    nuanceZh: '干した布団・ソファ・パンケーキ。「太陽の匂いのふかふか布団」は日本の生活文化の定番描写',
    similarJa: ['ふわふわ', 'ぺちゃんこ'],
    examples: [
      { ja: '布団を干したら、ふかふかになりました。', zh: '被子晒过后变得松软蓬松。' },
      { ja: 'このソファは、ふかふかで気持ちいいです。', zh: '这沙发松软舒服。' },
    ],
    commonMistakeZh: '「ふわふわ」は軽さ・浮遊感（綿飴・雲）、「ふかふか」は厚みのある弾力（布団・ソファ）。押した感触で選ぶ',
    recognition: { promptZh: '「ふかふか」最适合形容什么？',
      options: ['晒过的被子', '硬邦邦的地板', '瘪了的气球', '薄薄的纸'],
      answerIndex: 0, feedbackZh: '厚实松软 =「ふかふか」' },
    production: { promptJa: '干した布団の気持ちよさを「ふかふか」で言ってください。',
      promptZh: '用「ふかふか」说说晒过的被子。',
      expected: ['ふかふか'], acceptable: ['ふかふかです', 'ふかふかになりました'] },
    conversation: { themeJa: '布団を干す習慣について話す',
      starterJa: '布団を太陽に干して、ふかふかにする習慣はありますか？', starterZh: '你有晒被子让它蓬松的习惯吗？',
      targetExpressions: ['ふかふか'], followUpJa: '中国でも布団を干しますか？',
      followUpZh: '在中国也晒被子吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-bukabuka', sourceCandidateId: '2858d9586d4ab43c', surface: 'ぶかぶか', kana: 'ぶかぶか',
    category: 'gitaigo', usagePatterns: ['da-na'],
    meaningJa: '服や靴が大きすぎる様子', meaningZh: '（状态）（衣服鞋子）过于肥大、松松垮垮',
    nuanceZh: 'サイズが合わない大きさ。「ぴったり」の対義語。子どもが大人の服を着た様子にも',
    similarJa: ['ぴったり', 'だぼだぼ'],
    examples: [
      { ja: 'ネットで買った靴が、ぶかぶかでした。', zh: '网购的鞋子太大了，松松垮垮。' },
      { ja: '痩せたので、ズボンがぶかぶかになりました。', zh: '瘦了，裤子变得松垮垮的。' },
    ],
    commonMistakeZh: '大きすぎ=ぶかぶか、小さすぎ=きつい、ちょうど=ぴったり。試着の三点セットで覚える',
    recognition: { promptZh: '「ぶかぶか」是什么状态？',
      options: ['衣服太大', '衣服太小', '正合身', '衣服破了'],
      answerIndex: 0, feedbackZh: '过大松垮 =「ぶかぶか」' },
    production: { promptJa: 'サイズが大きすぎた買い物を「ぶかぶか」で言ってください。',
      promptZh: '用「ぶかぶか」说一次买大了的购物。',
      expected: ['ぶかぶか'], acceptable: ['ぶかぶかでした', 'ぶかぶかです'] },
    conversation: { themeJa: 'ネット通販の失敗談を話す',
      starterJa: 'ネットで買った服がぶかぶかだったことはありますか？', starterZh: '网购的衣服有买大过吗？',
      targetExpressions: ['ぶかぶか'], followUpJa: '服はネット派ですか？お店で試着派ですか？',
      followUpZh: '买衣服你是网购派还是试穿派？' },
    difficulty: 'basic' }),
  d({ id: 'ono-fusafusa', sourceCandidateId: '074d08805f17f268', surface: 'ふさふさ', kana: 'ふさふさ',
    category: 'gitaigo', usagePatterns: ['suru', 'da-na'],
    meaningJa: '毛が豊かにたくさんある様子', meaningZh: '（状态）（毛发）浓密丰盈',
    nuanceZh: '髪・犬猫の毛・しっぽ。羨望込みの褒め言葉。薄毛の対義的表現として会話のネタにも',
    similarJa: ['もふもふ', 'つやつや'],
    examples: [
      { ja: '祖父は80歳でも、髪がふさふさです。', zh: '爷爷80岁头发还很浓密。' },
      { ja: 'この犬は、毛がふさふさしていてかわいいです。', zh: '这只狗毛茸茸的很可爱。' },
    ],
    commonMistakeZh: '「ふさふさ」は毛量の多さ。触り心地のモフモフ感は「もふもふ」（ネット由来の新しい語）。両方知っていると便利',
    recognition: { promptZh: '「ふさふさ」形容什么？',
      options: ['浓密的头发', '光头', '短指甲', '平坦的路'],
      answerIndex: 0, feedbackZh: '毛发浓密 =「ふさふさ」' },
    production: { promptJa: '動物の毛の様子を「ふさふさ」で言ってください。',
      promptZh: '用「ふさふさ」描述动物的毛。',
      expected: ['ふさふさ'], acceptable: ['ふさふさしています', 'ふさふさです'] },
    conversation: { themeJa: 'ペットの毛のお手入れを話す',
      starterJa: 'ふさふさした動物は好きですか？触りたくなりますか？', starterZh: '毛茸茸的动物你喜欢吗？想摸吗？',
      targetExpressions: ['ふさふさ'], followUpJa: '犬派ですか？猫派ですか？',
      followUpZh: '你是狗派还是猫派？' },
    difficulty: 'plus' }),
  d({ id: 'ono-fukkura', sourceCandidateId: '5856fd24f8da0b73', surface: 'ふっくら', kana: 'ふっくら',
    category: 'gitaigo', usagePatterns: ['to-verb', 'suru'],
    meaningJa: '柔らかくふくらんでいる様子（食べ物・頬など）', meaningZh: '（状态）（面包、米饭）松软饱满、（脸颊）圆润',
    nuanceZh: '炊きたてご飯・焼きたてパンの最高の褒め言葉。人の頬には「健康的で好ましい丸み」の褒め表現',
    similarJa: ['ふかふか', 'もちもち'],
    examples: [
      { ja: 'ご飯がふっくら炊けました。', zh: '米饭焖得松软饱满。' },
      { ja: 'このパンは、ふっくらしていておいしいです。', zh: '这面包松软好吃。' },
    ],
    commonMistakeZh: '人に「ふっくらしましたね」は「胖了」の婉曲表現になり得るので注意。食べ物への使用が安全',
    recognition: { promptZh: '「ふっくら」最适合形容什么？',
      options: ['刚焖好的米饭', '硬掉的面包', '瘪气球', '干燥的沙漠'],
      answerIndex: 0, feedbackZh: '松软饱满 =「ふっくら」' },
    production: { promptJa: 'おいしいご飯やパンを「ふっくら」で言ってください。',
      promptZh: '用「ふっくら」形容好吃的米饭或面包。',
      expected: ['ふっくら'], acceptable: ['ふっくら炊けました', 'ふっくらしています'] },
    conversation: { themeJa: 'ご飯の炊き方・好みを話す',
      starterJa: 'ふっくらしたご飯と硬めのご飯、どちらが好きですか？', starterZh: '松软的米饭和偏硬的米饭你喜欢哪种？',
      targetExpressions: ['ふっくら'], followUpJa: '日本の米と中国の米、違いを感じますか？',
      followUpZh: '日本米和中国米你觉得有区别吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-furafura', sourceCandidateId: '287ef9367536f329', surface: 'ふらふら', kana: 'ふらふら',
    category: 'gitaigo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '力が入らず、ゆれて安定しない様子', meaningZh: '（状态）摇摇晃晃、脚步虚浮、（头）发飘',
    nuanceZh: '疲労・空腹・熱で体が安定しない。「目的なくふらふら出歩く」（瞎逛）の用法もある',
    similarJa: ['くらくら', 'よろよろ'],
    examples: [
      { ja: '熱で、足元がふらふらします。', zh: '发烧走路发飘。' },
      { ja: '徹夜明けで、ふらふらのまま出勤しました。', zh: '熬了通宵，摇摇晃晃地去上班。' },
    ],
    commonMistakeZh: '「くらくら」は頭の中のめまい、「ふらふら」は体・足元の不安定。セットで症状説明に使える',
    recognition: { promptZh: '「ふらふら」的状态是？',
      options: ['站不稳摇摇晃晃', '稳稳站着', '跑得飞快', '睡得很沉'],
      answerIndex: 0, feedbackZh: '体の不安定 =「ふらふら」' },
    production: { promptJa: '疲れて安定しない様子を「ふらふら」で言ってください。',
      promptZh: '用「ふらふら」描述累得站不稳。',
      expected: ['ふらふら'], acceptable: ['ふらふらします', 'ふらふらです'] },
    conversation: { themeJa: '無理をした日の体調を話す',
      starterJa: '寝不足でふらふらになったことがありますか？', starterZh: '有睡眠不足摇摇晃晃过吗？',
      targetExpressions: ['ふらふら'], followUpJa: '「くらくら」と「ふらふら」、部位の違いが分かりますか？',
      followUpZh: '「くらくら」和「ふらふら」的部位区别你明白吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-burabura', sourceCandidateId: 'a22698d6e8fcdffd', surface: 'ぶらぶら', kana: 'ぶらぶら',
    category: 'gitaigo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '①物が揺れる様子 ②目的なくのんびり歩く様子', meaningZh: '（状态）①晃来晃去 ②溜达、闲逛',
    nuanceZh: '②「街をぶらぶらする」（闲逛）が会話頻出。休日の過ごし方の定番表現。のんびり・気楽なニュアンス',
    similarJa: ['うろうろ', 'ゆらゆら'],
    examples: [
      { ja: '休みの日は、商店街をぶらぶらします。', zh: '休息日在商店街闲逛。' },
      { ja: '足をぶらぶらさせて、ベンチに座っています。', zh: '坐在长椅上晃着腿。' },
    ],
    commonMistakeZh: '楽しい閑逛=ぶらぶら（正面）、迷って徘徊=うろうろ（負面）。同じ「走来走去」でも気分が逆',
    recognition: { promptZh: '「街をぶらぶらする」是什么感觉？',
      options: ['悠闲地逛街', '迷路了着急', '赶时间狂奔', '站着不动'],
      answerIndex: 0, feedbackZh: '悠闲闲逛 =「ぶらぶら」' },
    production: { promptJa: '休日の過ごし方を「ぶらぶら」で言ってください。',
      promptZh: '用「ぶらぶら」说说休息日怎么过。',
      expected: ['ぶらぶら'], acceptable: ['ぶらぶらします', 'ぶらぶらしました'] },
    conversation: { themeJa: 'ぶらぶらするのに好きな街を話す',
      starterJa: 'ぶらぶらするのが好きな街はどこですか？', starterZh: '你喜欢在哪条街闲逛？',
      targetExpressions: ['ぶらぶら'], followUpJa: '一人でぶらぶら派ですか？誰かと一緒派ですか？',
      followUpZh: '你喜欢一个人逛还是结伴逛？' },
    difficulty: 'basic' }),
  d({ id: 'ono-buruburu', sourceCandidateId: 'c98ddd536692387c', surface: 'ぶるぶる', kana: 'ぶるぶる',
    category: 'gitaigo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '寒さや恐怖で小刻みに震える様子', meaningZh: '（状态）（冷得/怕得）发抖、哆嗦',
    nuanceZh: '寒さ・恐怖・緊張の震え。スマホのバイブ音にも使う（ぶるぶる鳴る）。犬が体を振るのも「ぶるぶるっ」',
    similarJa: ['がたがた', 'ぞくぞく'],
    examples: [
      { ja: '寒くて、ぶるぶる震えました。', zh: '冷得直哆嗦。' },
      { ja: 'ポケットでスマホがぶるぶる鳴っています。', zh: '手机在口袋里嗡嗡震动。' },
    ],
    commonMistakeZh: '「ぶるぶる」は小刻み、「がたがた」はもっと大きい震え（歯ががたがた鳴るほどの寒さ・恐怖）。程度差で使い分け',
    recognition: { promptZh: '「ぶるぶる」是什么状态？',
      options: ['冷得发抖', '热得出汗', '开心地跳', '安静地睡'],
      answerIndex: 0, feedbackZh: '小刻みな震え =「ぶるぶる」' },
    production: { promptJa: '寒かった経験を「ぶるぶる」で言ってください。',
      promptZh: '用「ぶるぶる」说一次冷得发抖的经历。',
      expected: ['ぶるぶる'], acceptable: ['ぶるぶる震えました', 'ぶるぶるしました'] },
    conversation: { themeJa: '一番寒かった経験を話す',
      starterJa: '今までで一番、ぶるぶる震えるほど寒かったのはいつですか？', starterZh: '至今最冷得发抖的是什么时候？',
      targetExpressions: ['ぶるぶる'], followUpJa: '故郷の冬と日本の冬、どちらが体にこたえますか？',
      followUpZh: '家乡的冬天和日本的冬天哪个更难熬？' },
    difficulty: 'basic' }),
  d({ id: 'ono-fuwafuwa', sourceCandidateId: 'c70eed2ec5ad131f', surface: 'ふわふわ', kana: 'ふわふわ',
    category: 'gitaigo', usagePatterns: ['suru', 'da-na', 'to-verb'],
    meaningJa: '軽くて柔らかく、浮くような様子', meaningZh: '（状态）软绵绵、轻飘飘（棉花糖、云朵）',
    nuanceZh: '綿飴・雲・パンケーキ・気持ちが浮つく状態まで。かわいい系語彙の代表。スイーツの説明で頻出',
    similarJa: ['ふかふか', 'ふっくら'],
    examples: [
      { ja: 'このパンケーキは、ふわふわでおいしいです。', zh: '这松饼软绵绵的好吃。' },
      { ja: '空にふわふわした雲が浮かんでいます。', zh: '天上飘着软绵绵的云。' },
    ],
    commonMistakeZh: '気持ちが「ふわふわする」は「心不在焉・飘飘然」の意。物の柔らかさと気持ちの浮つき、両方ある',
    recognition: { promptZh: '「ふわふわ」最适合形容什么？',
      options: ['棉花糖', '石头', '铁板', '冰块'],
      answerIndex: 0, feedbackZh: '轻软浮感 =「ふわふわ」' },
    production: { promptJa: '好きなスイーツを「ふわふわ」で言ってください。',
      promptZh: '用「ふわふわ」形容你喜欢的甜点。',
      expected: ['ふわふわ'], acceptable: ['ふわふわです', 'ふわふわしています'] },
    conversation: { themeJa: 'ふわふわスイーツの店を話す',
      starterJa: 'ふわふわのパンケーキやかき氷、食べたことがありますか？', starterZh: '吃过软绵绵的松饼或刨冰吗？',
      targetExpressions: ['ふわふわ'], followUpJa: 'おすすめのスイーツ店を教えてください',
      followUpZh: '推荐一家甜品店吧' },
    difficulty: 'basic' }),
  d({ id: 'ono-punpun', sourceCandidateId: '730e92fa45b46612', surface: 'ぷんぷん', kana: 'ぷんぷん',
    category: 'gijougo', usagePatterns: ['suru', 'to-verb'],
    meaningJa: '分かりやすく怒っている様子', meaningZh: '（状态）气鼓鼓、怒气冲冲（外露的生气）',
    nuanceZh: '子どもっぽい・かわいげのある怒り方。深刻な激怒には使わない。「匂いがぷんぷんする」（气味刺鼻）の用法も',
    similarJa: ['かんかん', 'いらいら'],
    examples: [
      { ja: '妹は、けんかしてぷんぷん怒っています。', zh: '妹妹吵完架气鼓鼓的。' },
      { ja: '約束を忘れられて、彼女はぷんぷんです。', zh: '被忘了约定，她气呼呼的。' },
    ],
    commonMistakeZh: '深刻な怒りは「かんかんに怒る」。「ぷんぷん」はどこか可愛い怒り。上司の激怒に使うと軽く聞こえて危険',
    recognition: { promptZh: '「ぷんぷん」是哪种生气？',
      options: ['气鼓鼓（有点可爱）', '暴怒摔东西', '冷战不理人', '完全不生气'],
      answerIndex: 0, feedbackZh: '外露で子どもっぽい怒り =「ぷんぷん」' },
    production: { promptJa: '軽く怒っている人を「ぷんぷん」で言ってください。',
      promptZh: '用「ぷんぷん」描述气鼓鼓的人。',
      expected: ['ぷんぷん'], acceptable: ['ぷんぷんしています', 'ぷんぷん怒っています'] },
    conversation: { themeJa: '怒り方のタイプを話す',
      starterJa: '怒るとぷんぷん顔に出るタイプですか？我慢するタイプですか？', starterZh: '生气时你是写在脸上还是憋着？',
      targetExpressions: ['ぷんぷん'], followUpJa: '最近、ぷんぷんしたことはありますか？',
      followUpZh: '最近有气鼓鼓的事吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-pekopeko', sourceCandidateId: '79e4f58e9227a550', surface: 'ぺこぺこ', kana: 'ぺこぺこ',
    category: 'gijougo', usagePatterns: ['da-na', 'suru'],
    meaningJa: '①お腹がとても空いている様子 ②何度も頭を下げる様子', meaningZh: '（状态）①肚子饿瘪了 ②点头哈腰',
    nuanceZh: '①「お腹がぺこぺこ」は空腹の定番表現（カジュアル）。②「ぺこぺこ謝る」は卑屈な平身低頭（やや негатив）',
    similarJa: ['はらぺこ', 'ぐうぐう'],
    examples: [
      { ja: '朝から何も食べていなくて、お腹がぺこぺこです。', zh: '从早上就没吃东西，肚子饿瘪了。' },
      { ja: '彼は上司にぺこぺこしています。', zh: '他对上司点头哈腰。' },
    ],
    commonMistakeZh: '①は自分に使ってOKの可愛い表現。②を人に言うと「奴颜婢膝」の批判になる。意味が全く違うので文脈注意',
    recognition: { promptZh: '「お腹がぺこぺこ」是什么意思？',
      options: ['肚子很饿', '吃太饱', '肚子疼', '不想吃饭'],
      answerIndex: 0, feedbackZh: '空腹 =「ぺこぺこ」' },
    production: { promptJa: 'お腹が空いたことを「ぺこぺこ」で言ってください。',
      promptZh: '用「ぺこぺこ」说肚子饿了。',
      expected: ['ぺこぺこ'], acceptable: ['ぺこぺこです', 'お腹がぺこぺこです'] },
    conversation: { themeJa: '空腹時の定番メニューを話す',
      starterJa: 'お腹がぺこぺこのとき、何が食べたくなりますか？', starterZh: '饿瘪了的时候你最想吃什么？',
      targetExpressions: ['ぺこぺこ'], followUpJa: '仕事中、お腹が鳴って恥ずかしかったことはありますか？',
      followUpZh: '工作时肚子叫过很尴尬吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-betabeta', sourceCandidateId: '1901ddcbaa3ef4f7', surface: 'べたべた', kana: 'べたべた',
    category: 'gitaigo', usagePatterns: ['suru', 'da-na'],
    meaningJa: '汗や汚れで粘りつく不快な様子', meaningZh: '（状态）黏糊糊、黏腻（汗、油污）',
    nuanceZh: '汗ばむ夏の肌・油汚れ・シールの跡。恋人がべたべたする（黏人）の用法も。基本的に不快寄り',
    similarJa: ['ねばねば', 'さらさら'],
    examples: [
      { ja: '夏は汗で、肌がべたべたします。', zh: '夏天出汗，皮肤黏糊糊的。' },
      { ja: 'テーブルが油でべたべたしています。', zh: '桌子上油乎乎黏糊糊的。' },
    ],
    commonMistakeZh: '「ねばねば」は食べ物の粘り（中立〜正面）、「べたべた」は肌・物の不快な粘つき（負面）。納豆にべたべたは使わない',
    recognition: { promptZh: '「べたべた」的感觉是？',
      options: ['黏糊糊不舒服', '干爽舒服', '冰凉清爽', '蓬松柔软'],
      answerIndex: 0, feedbackZh: '不快な粘つき =「べたべた」' },
    production: { promptJa: '夏の汗の不快感を「べたべた」で言ってください。',
      promptZh: '用「べたべた」说夏天出汗的黏腻感。',
      expected: ['べたべた'], acceptable: ['べたべたします', 'べたべたです'] },
    conversation: { themeJa: '夏のべたべた対策を話す',
      starterJa: '夏、肌がべたべたするとき、どうしていますか？', starterZh: '夏天皮肤黏糊糊时你怎么办？',
      targetExpressions: ['べたべた'], followUpJa: '日本の夏と故郷の夏、どちらがべたべたしますか？',
      followUpZh: '日本的夏天和家乡的夏天哪个更黏腻？' },
    difficulty: 'basic' }),
  d({ id: 'ono-pechanko', sourceCandidateId: '457303937a89fa36', surface: 'ぺちゃんこ', kana: 'ぺちゃんこ',
    category: 'gitaigo', usagePatterns: ['da-na', 'ni-naru'],
    meaningJa: 'つぶれて平らになった様子', meaningZh: '（状态）压瘪、扁塌塌',
    nuanceZh: '風船・タイヤ・つぶれたパン・髪のボリュームダウンまで。「ぺちゃんこになる」の形が多い',
    similarJa: ['ぺったんこ', 'ふっくら'],
    examples: [
      { ja: '自転車のタイヤが、ぺちゃんこになっていました。', zh: '自行车胎瘪了。' },
      { ja: 'かばんの中でパンがぺちゃんこになりました。', zh: '面包在包里被压扁了。' },
    ],
    commonMistakeZh: '「ぺちゃんこ」は押しつぶされた結果。もともと薄いものには使わない（紙がぺちゃんこ×）',
    recognition: { promptZh: '「タイヤがぺちゃんこ」是什么状态？',
      options: ['轮胎没气瘪了', '轮胎是新的', '轮胎很脏', '轮胎在转'],
      answerIndex: 0, feedbackZh: '压瘪 =「ぺちゃんこ」' },
    production: { promptJa: 'つぶれた物を「ぺちゃんこ」で言ってください。',
      promptZh: '用「ぺちゃんこ」说被压扁的东西。',
      expected: ['ぺちゃんこ'], acceptable: ['ぺちゃんこになりました', 'ぺちゃんこです'] },
    conversation: { themeJa: 'かばんの中の失敗談を話す',
      starterJa: 'かばんの中で食べ物がぺちゃんこになったことはありますか？', starterZh: '包里的食物被压扁过吗？',
      targetExpressions: ['ぺちゃんこ'], followUpJa: '自転車のタイヤ、自分で直せますか？',
      followUpZh: '自行车胎瘪了你会自己修吗？' },
    difficulty: 'plus' }),
  d({ id: 'ono-hetoheto', sourceCandidateId: '5b28b736ade22fc4', surface: 'へとへと', kana: 'へとへと',
    category: 'gijougo', usagePatterns: ['da-na', 'ni-naru'],
    meaningJa: '疲れ果てて力が残っていない様子', meaningZh: '（状态）精疲力尽、累到极点',
    nuanceZh: '「へとへとになる」「もうへとへとだ」。運動・仕事・引っ越し後の極度の疲労。「ぐったり」は見た目、「へとへと」は本人の感覚寄り',
    similarJa: ['ぐったり', 'くたくた'],
    examples: [
      { ja: '10キロ走って、もうへとへとです。', zh: '跑了10公里，已经精疲力尽。' },
      { ja: '繁忙期は、毎日へとへとになります。', zh: '旺季每天都累到极点。' },
    ],
    commonMistakeZh: '「疲れた」の最上級クラス。軽い疲れに使うと大げさ。「くたくた」もほぼ同義で言い換え可能',
    recognition: { promptZh: '「へとへと」是疲劳的哪个程度？',
      options: ['精疲力尽（极度疲劳）', '有点累', '精神很好', '刚睡醒'],
      answerIndex: 0, feedbackZh: '疲労の最上級 =「へとへと」' },
    production: { promptJa: '疲れ果てた日を「へとへと」で言ってください。',
      promptZh: '用「へとへと」说累坏了的一天。',
      expected: ['へとへと'], acceptable: ['へとへとです', 'へとへとになりました'] },
    conversation: { themeJa: 'へとへとになった日の夕食を話す',
      starterJa: 'へとへとの日は、料理しますか？買って帰りますか？', starterZh: '精疲力尽的日子你做饭还是买着吃？',
      targetExpressions: ['へとへと'], followUpJa: '疲れた日の一番の楽しみは何ですか？',
      followUpZh: '疲惫日子里最大的享受是什么？' },
    difficulty: 'basic' }),
  d({ id: 'ono-perapera', sourceCandidateId: 'bde4f67d11948018', surface: 'ぺらぺら', kana: 'ぺらぺら',
    category: 'gitaigo', usagePatterns: ['da-na', 'to-verb'],
    meaningJa: '①外国語を流暢に話す様子 ②紙などが薄い様子', meaningZh: '（状态）①外语说得流利 ②（纸张）薄薄的',
    nuanceZh: '①学習者の憧れ表現「日本語ぺらぺらですね」は最高の褒め言葉。②「ぺらぺらの紙」（薄纸）は別義',
    similarJa: ['すらすら', 'ぺろぺろ'],
    examples: [
      { ja: '彼女は日本語がぺらぺらです。', zh: '她日语说得很流利。' },
      { ja: 'いつか、日本語をぺらぺらに話せるようになりたいです。', zh: '希望有一天能说一口流利的日语。' },
    ],
    commonMistakeZh: '自分で「私は日本語がぺらぺらです」と言うと自慢に聞こえる。目標として「ぺらぺらになりたい」は自然',
    recognition: { promptZh: '「日本語がぺらぺら」是什么水平？',
      options: ['说得非常流利', '完全不会', '只会写', '只会听'],
      answerIndex: 0, feedbackZh: '流暢な会話力 =「ぺらぺら」' },
    production: { promptJa: '語学の目標を「ぺらぺら」で言ってください。',
      promptZh: '用「ぺらぺら」说你的外语目标。',
      expected: ['ぺらぺら'], acceptable: ['ぺらぺらになりたいです', 'ぺらぺらに話したいです'] },
    conversation: { themeJa: 'ぺらぺらになったらしたいことを話す',
      starterJa: '日本語がぺらぺらになったら、最初に何をしたいですか？', starterZh: '日语说流利了你最想先做什么？',
      targetExpressions: ['ぺらぺら'], followUpJa: '周りに「ぺらぺらだね」と言われたことはありますか？',
      followUpZh: '有被人夸过「日语真流利」吗？' },
    difficulty: 'basic' }),
  d({ id: 'ono-berobero', sourceCandidateId: 'b0043e8839de0507', surface: 'べろべろ', kana: 'べろべろ',
    category: 'gitaigo', usagePatterns: ['to-verb', 'da-na'],
    meaningJa: '①舌でなめ回す様子 ②ひどく酔っている様子', meaningZh: '（状态）①（伸舌头）舔来舔去 ②烂醉如泥',
    nuanceZh: '①犬がべろべろなめる。②「べろべろに酔う」（喝得烂醉）は飲み会文化の頻出表現。②の方が会話で有用',
    similarJa: ['ぺろぺろ', 'ふらふら'],
    examples: [
      { ja: '犬が顔をべろべろなめてきます。', zh: '狗舔得我满脸口水。' },
      { ja: '忘年会で、先輩がべろべろに酔っていました。', zh: '忘年会上前辈喝得烂醉。' },
    ],
    commonMistakeZh: '軽くなめるのは「ぺろぺろ」（かわいい）、大胆になめ回す・泥酔は「べろべろ」。清音と濁音で程度が変わる典型例',
    recognition: { promptZh: '「べろべろに酔う」是什么状态？',
      options: ['喝得烂醉', '微醺', '完全没喝', '只喝了一口'],
      answerIndex: 0, feedbackZh: '泥酔 =「べろべろ」' },
    production: { promptJa: '飲み会で酔った人を「べろべろ」で言ってください。',
      promptZh: '用「べろべろ」描述喝醉的人。',
      expected: ['べろべろ'], acceptable: ['べろべろに酔っていました', 'べろべろでした'] },
    conversation: { themeJa: '日本の飲み会文化について話す',
      starterJa: '日本の飲み会で、べろべろに酔った人を見たことがありますか？', starterZh: '在日本的酒局上见过烂醉的人吗？',
      targetExpressions: ['べろべろ'], followUpJa: '中国の宴会と日本の飲み会、違いはありますか？',
      followUpZh: '中国的宴席和日本的酒局有什么不同？' },
    difficulty: 'plus' }),
];
