// Phase 3P-3: 会話contextual接続の拡張バッチ3（な形容詞・場所・名詞・変化動詞）。全draft。
import type { VocabularyConversationPractice } from './vocabConversationPractice';

const d = (p: Omit<VocabularyConversationPractice, 'practiceType' | 'reviewStatus' | 'estimatedMinutes'> & { estimatedMinutes?: number }): VocabularyConversationPractice =>
  ({ estimatedMinutes: 3, practiceType: 'vocabulary', reviewStatus: 'draft', ...p });

export const VOCAB_CONVERSATION_PRACTICES_BATCH3: VocabularyConversationPractice[] = [
  d({ itemId: 'fi-shizuka', themeJa: '静かな場所について話す', themeZh: '聊聊安静的地方',
    starterQuestionJa: 'あなたの家の周りは静かですか？', starterQuestionZh: '你家周围安静吗？',
    targetExpressions: ['静かです', '静かな', '静かに'],
    supportExpressionsJa: ['夜は静かです', '静かな場所で勉強したいです', '図書館は静かです'],
    supportExpressionsZh: ['晚上很安静', '想在安静的地方学习', '图书馆很安静'],
    followUpQuestionJa: '静かな場所と にぎやかな場所、どちらが好きですか？', followUpQuestionZh: '安静的地方和热闹的地方你喜欢哪个？' }),
  d({ itemId: 'fi-benri', themeJa: '便利なものについて話す', themeZh: '聊聊方便的东西',
    starterQuestionJa: '日本の生活で、何が便利だと思いますか？', starterQuestionZh: '日本生活中你觉得什么方便？',
    targetExpressions: ['便利です', '便利な', '便利で'],
    supportExpressionsJa: ['コンビニは便利です', '交通が便利な町です', 'このアプリは便利で、よく使います'],
    supportExpressionsZh: ['便利店很方便', '交通方便的城市', '这个软件很方便，常用'],
    followUpQuestionJa: '中国のほうが便利なものは ありますか？', followUpQuestionZh: '有什么是中国更方便的？' }),
  d({ itemId: 'fi-kantan', themeJa: '簡単なこと・難しくないことを話す', themeZh: '聊聊简单的事',
    starterQuestionJa: '日本語で、何がいちばん簡単でしたか？', starterQuestionZh: '日语里什么最简单？',
    targetExpressions: ['簡単です', '簡単な', '簡単に'],
    supportExpressionsJa: ['ひらがなは簡単でした', '簡単な料理なら作れます', '簡単に説明してください'],
    supportExpressionsZh: ['平假名很简单', '简单的菜我会做', '请简单说明'],
    followUpQuestionJa: '簡単にできる料理を 教えてください', followUpQuestionZh: '教我一道简单的菜吧' }),
  d({ itemId: 'fi-yuumei', themeJa: '有名なものについて話す', themeZh: '聊聊有名的事物',
    starterQuestionJa: 'あなたの故郷で有名なものは何ですか？', starterQuestionZh: '你家乡有什么有名的东西？',
    targetExpressions: ['有名です', '有名な', '有名で'],
    supportExpressionsJa: ['〜が有名です', '有名な観光地があります', 'この店はラーメンで有名です'],
    supportExpressionsZh: ['〜很有名', '有有名的景点', '这家店以拉面出名'],
    followUpQuestionJa: '日本で 行ってみたい有名な場所はありますか？', followUpQuestionZh: '日本有想去的有名的地方吗？' }),
  d({ itemId: 'fi-jouzu', themeJa: '上手なこと・得意なことを話す', themeZh: '聊聊擅长的事',
    starterQuestionJa: '何が上手だと言われますか？', starterQuestionZh: '别人说你什么做得好？',
    targetExpressions: ['が上手です', '上手に', '上手だ'],
    supportExpressionsJa: ['料理が上手です', 'まだ上手に話せません', '日本語が上手ですね、と言われました'],
    supportExpressionsZh: ['擅长做饭', '还说得不好', '别人夸我日语说得好'],
    followUpQuestionJa: '日本語が上手になるために 何をしていますか？', followUpQuestionZh: '为了日语变好你在做什么？' }),
  d({ itemId: 'fi-ie', themeJa: '家について話す', themeZh: '聊聊你的家',
    starterQuestionJa: '今の家はどうですか？', starterQuestionZh: '现在住的家怎么样？',
    targetExpressions: ['家は', '家に', '家で'],
    supportExpressionsJa: ['家は駅から近いです', '家に猫がいます', '週末は家でゆっくりします'],
    supportExpressionsZh: ['家离车站近', '家里有猫', '周末在家休息'],
    followUpQuestionJa: '家で 何をするのが好きですか？', followUpQuestionZh: '在家喜欢做什么？' }),
  d({ itemId: 'fi-eki', themeJa: '駅について話す', themeZh: '聊聊车站',
    starterQuestionJa: 'いちばん近い駅はどこですか？', starterQuestionZh: '离你最近的车站是哪个？',
    targetExpressions: ['駅は', '駅で', '駅まで'],
    supportExpressionsJa: ['〜駅が近いです', '駅で友達と待ち合わせます', '駅まで歩いて10分です'],
    supportExpressionsZh: ['〜站很近', '在车站和朋友碰头', '走到车站10分钟'],
    followUpQuestionJa: '駅の近くに 何がありますか？', followUpQuestionZh: '车站附近有什么？' }),
  d({ itemId: 'fi-gakkou', themeJa: '学校について話す', themeZh: '聊聊学校',
    starterQuestionJa: '日本語学校に通ったことがありますか？', starterQuestionZh: '你上过日语学校吗？',
    targetExpressions: ['学校に', '学校で', '学校の'],
    supportExpressionsJa: ['学校に通っています', '学校で友達ができました', '学校の宿題が多いです'],
    supportExpressionsZh: ['在上学', '在学校交到了朋友', '学校作业很多'],
    followUpQuestionJa: '学校で いちばん楽しかったことは何ですか？', followUpQuestionZh: '在学校最开心的事是什么？' }),
  d({ itemId: 'fi-byouin', themeJa: '病院について話す', themeZh: '聊聊医院',
    starterQuestionJa: '日本で病院に行ったことがありますか？', starterQuestionZh: '在日本去过医院吗？',
    targetExpressions: ['病院に', '病院で', '病院へ'],
    supportExpressionsJa: ['風邪で病院に行きました', '病院で長く待ちました', '日本語で症状を言うのが難しいです'],
    supportExpressionsZh: ['感冒去了医院', '在医院等了很久', '用日语说症状很难'],
    followUpQuestionJa: '病院で 困ったことはありますか？', followUpQuestionZh: '在医院遇到过困难吗？' }),
  d({ itemId: 'fi-kusuri', themeJa: '薬について話す', themeZh: '聊聊吃药',
    starterQuestionJa: '風邪のとき、すぐ薬を飲みますか？', starterQuestionZh: '感冒时你马上吃药吗？',
    targetExpressions: ['薬を', '薬は', '薬が'],
    supportExpressionsJa: ['薬を飲みます', '薬はドラッグストアで買います', '薬が効きました'],
    supportExpressionsZh: ['吃药', '在药妆店买药', '药起作用了'],
    followUpQuestionJa: '日本の薬と中国の薬、どちらをよく使いますか？', followUpQuestionZh: '日本药和中国药你常用哪个？' }),
  d({ itemId: 'fi-mizu', themeJa: '水・飲み物の習慣を話す', themeZh: '聊聊喝水的习惯',
    starterQuestionJa: '毎日、水をたくさん飲みますか？', starterQuestionZh: '你每天喝很多水吗？',
    targetExpressions: ['水を', '水は', '水が'],
    supportExpressionsJa: ['朝、水を飲みます', '日本は水道の水が飲めます', '冷たい水はあまり飲みません'],
    supportExpressionsZh: ['早上喝水', '日本自来水能喝', '不太喝凉水'],
    followUpQuestionJa: '中国では 温かいお湯をよく飲みますか？', followUpQuestionZh: '在中国常喝热水吗？' }),
  d({ itemId: 'fi-tomodachi', themeJa: '友達について話す', themeZh: '聊聊朋友',
    starterQuestionJa: '日本で友達ができましたか？', starterQuestionZh: '在日本交到朋友了吗？',
    targetExpressions: ['友達が', '友達と', '友達に'],
    supportExpressionsJa: ['友達ができました', '友達と食事に行きます', '中国の友達に電話します'],
    supportExpressionsZh: ['交到了朋友', '和朋友去吃饭', '给中国的朋友打电话'],
    followUpQuestionJa: '友達と 何をして遊びますか？', followUpQuestionZh: '和朋友一起做什么玩？' }),
  d({ itemId: 'fi-kazoku', themeJa: '家族について話す', themeZh: '聊聊家人',
    starterQuestionJa: '家族は何人ですか？', starterQuestionZh: '你家有几口人？',
    targetExpressions: ['家族は', '家族と', '家族に'],
    supportExpressionsJa: ['家族は4人です', '家族と週末に電話します', '家族に会いたいです'],
    supportExpressionsZh: ['家里四口人', '周末和家人通话', '想见家人'],
    followUpQuestionJa: '家族と どんな話をしますか？', followUpQuestionZh: '和家人聊什么？' }),
  d({ itemId: 'fi-shigoto', themeJa: '仕事の内容について話す', themeZh: '聊聊工作内容',
    starterQuestionJa: 'どんな仕事をしていますか？', starterQuestionZh: '你做什么样的工作？',
    targetExpressions: ['仕事は', '仕事を', '仕事が'],
    supportExpressionsJa: ['仕事は営業です', '今日は仕事が多いです', '新しい仕事を探しています'],
    supportExpressionsZh: ['工作是销售', '今天工作很多', '在找新工作'],
    followUpQuestionJa: '仕事で 日本語を使いますか？', followUpQuestionZh: '工作中用日语吗？' }),
  d({ itemId: 'fi-okane', themeJa: 'お金の使い方について話す', themeZh: '聊聊花钱',
    starterQuestionJa: '何にいちばんお金を使いますか？', starterQuestionZh: '你花钱最多的是什么？',
    targetExpressions: ['お金を', 'お金が', 'お金は'],
    supportExpressionsJa: ['食べ物にお金を使います', 'お金がかかります', 'お金を貯めています'],
    supportExpressionsZh: ['花在吃的上', '很花钱', '在存钱'],
    followUpQuestionJa: 'お金が あったら何をしたいですか？', followUpQuestionZh: '有钱的话想做什么？' }),
  d({ itemId: 'fi-basu', themeJa: 'バスの利用について話す', themeZh: '聊聊坐公交',
    starterQuestionJa: 'バスによく乗りますか？', starterQuestionZh: '你常坐公交车吗？',
    targetExpressions: ['バスに', 'バスで', 'バスは'],
    supportExpressionsJa: ['バスで通勤します', 'バスはあまり乗りません', '日本のバスは前から降ります'],
    supportExpressionsZh: ['坐公交上班', '不太坐公交', '日本的公交从前门下车'],
    followUpQuestionJa: '電車とバス、どちらをよく使いますか？', followUpQuestionZh: '电车和公交你常用哪个？' }),
  d({ itemId: 'fi-kawaru', themeJa: '変わったことについて話す', themeZh: '聊聊发生的变化',
    starterQuestionJa: '日本に来て、何が変わりましたか？', starterQuestionZh: '来日本后有什么变化？',
    targetExpressions: ['が変わりました', 'が変わって', 'は変わりません'],
    supportExpressionsJa: ['生活が変わりました', '考え方が変わって、前向きになりました', '性格は変わりません'],
    supportExpressionsZh: ['生活变了', '想法变了，变积极了', '性格没变'],
    followUpQuestionJa: 'これから 何が変わると思いますか？', followUpQuestionZh: '你觉得今后会有什么变化？' }),
  d({ itemId: 'fi-kaeru-change', themeJa: '自分で変えたことを話す', themeZh: '聊聊自己主动改变的事',
    starterQuestionJa: '最近、何か習慣を変えましたか？', starterQuestionZh: '最近改变了什么习惯吗？',
    targetExpressions: ['を変えました', 'を変えて', 'を変えたい'],
    supportExpressionsJa: ['起きる時間を変えました', '勉強のやり方を変えてみます', '仕事を変えたいです'],
    supportExpressionsZh: ['改变了起床时间', '试着改变学习方法', '想换工作'],
    followUpQuestionJa: '変えて よかったことはありますか？', followUpQuestionZh: '有什么改了之后觉得好的？' }),
  d({ itemId: 'fi-fueru', themeJa: '増えたものについて話す', themeZh: '聊聊增加的事物',
    starterQuestionJa: '日本に来てから、何が増えましたか？', starterQuestionZh: '来日本后什么变多了？',
    targetExpressions: ['が増えました', 'が増えて'],
    supportExpressionsJa: ['知っている単語が増えました', '仕事が増えて忙しいです', '体重が増えました'],
    supportExpressionsZh: ['认识的单词变多了', '工作变多了很忙', '体重增加了'],
    followUpQuestionJa: 'これから 増やしたいものは何ですか？', followUpQuestionZh: '今后想增加什么？' }),
  d({ itemId: 'fi-heru', themeJa: '減ったものについて話す', themeZh: '聊聊减少的事物',
    starterQuestionJa: '最近、何か減ったものがありますか？', starterQuestionZh: '最近有什么变少了吗？',
    targetExpressions: ['が減りました', 'が減って'],
    supportExpressionsJa: ['自由な時間が減りました', '中国語を話す機会が減って、少し寂しいです', '貯金が減りました'],
    supportExpressionsZh: ['自由时间变少了', '说中文的机会变少，有点寂寞', '存款变少了'],
    followUpQuestionJa: '減らしたい習慣は ありますか？', followUpQuestionZh: '有想减少的习惯吗？' }),
  d({ itemId: 'fi-hajimeru', themeJa: '始めたことについて話す', themeZh: '聊聊开始做的事',
    starterQuestionJa: '最近、何か新しいことを始めましたか？', starterQuestionZh: '最近开始了什么新的事吗？',
    targetExpressions: ['を始めました', 'を始めて', 'を始めたい'],
    supportExpressionsJa: ['日本語の勉強を始めました', '運動を始めて1か月です', '料理を始めたいです'],
    supportExpressionsZh: ['开始学日语了', '开始运动一个月了', '想开始学做饭'],
    followUpQuestionJa: 'いつから 日本語を始めましたか？', followUpQuestionZh: '什么时候开始学日语的？' }),
  d({ itemId: 'fi-owaru', themeJa: '終わる時間について話す', themeZh: '聊聊结束的时间',
    starterQuestionJa: '仕事は何時に終わりますか？', starterQuestionZh: '工作几点结束？',
    targetExpressions: ['が終わります', 'が終わって', 'が終わりました'],
    supportExpressionsJa: ['6時に仕事が終わります', '会議が終わってから連絡します', 'やっとレポートが終わりました'],
    supportExpressionsZh: ['6点下班', '会议结束后联系', '报告终于写完了'],
    followUpQuestionJa: '仕事が終わったあと、何をしますか？', followUpQuestionZh: '下班后做什么？' }),
  d({ itemId: 'fi-tsuzukeru', themeJa: '続けていることを話す', themeZh: '聊聊坚持在做的事',
    starterQuestionJa: '何か長く続けていることはありますか？', starterQuestionZh: '有什么长期坚持的事吗？',
    targetExpressions: ['を続けています', 'を続けて', 'を続けたい'],
    supportExpressionsJa: ['日本語の勉強を続けています', '運動を続けて半年です', 'この仕事を続けたいです'],
    supportExpressionsZh: ['坚持学日语', '坚持运动半年了', '想继续这份工作'],
    followUpQuestionJa: '続けるコツは 何だと思いますか？', followUpQuestionZh: '你觉得坚持的秘诀是什么？' }),
  d({ itemId: 'fi-tsuzuku', themeJa: '続いている状態を話す', themeZh: '聊聊持续的状态',
    starterQuestionJa: '暑い日が続いていますね。体調はどうですか？', starterQuestionZh: '连续高温呢。身体怎么样？',
    targetExpressions: ['が続いています', 'が続きます', 'が続いて'],
    supportExpressionsJa: ['忙しい日が続いています', '雨が続いて洗濯できません', '会議が続きます'],
    supportExpressionsZh: ['连续忙碌', '连着下雨没法洗衣服', '会议一个接一个'],
    followUpQuestionJa: '疲れが続くとき、どうしますか？', followUpQuestionZh: '一直疲劳的时候怎么办？' }),
  d({ itemId: 'fi-kimeru', themeJa: '自分で決めたことを話す', themeZh: '聊聊自己做的决定',
    starterQuestionJa: '日本に来ることは、自分で決めましたか？', starterQuestionZh: '来日本是你自己决定的吗？',
    targetExpressions: ['を決めました', 'に決めました', 'を決めて'],
    supportExpressionsJa: ['自分で決めました', '引っ越しを決めました', '毎日30分勉強すると決めています'],
    supportExpressionsZh: ['自己决定的', '决定搬家了', '决定每天学30分钟'],
    followUpQuestionJa: '大きなことを決めるとき、だれに相談しますか？', followUpQuestionZh: '做重大决定时和谁商量？' }),
  d({ itemId: 'fi-kimaru', themeJa: '決まったことについて話す', themeZh: '聊聊定下来的事',
    starterQuestionJa: '来月の予定は、もう決まりましたか？', starterQuestionZh: '下个月的安排定了吗？',
    targetExpressions: ['が決まりました', 'が決まって', 'が決まったら'],
    supportExpressionsJa: ['予定が決まりました', '引っ越し先が決まってほっとしました', '決まったら連絡します'],
    supportExpressionsZh: ['安排定了', '搬家的地方定了，松了口气', '定了就联系你'],
    followUpQuestionJa: 'まだ決まっていないことは ありますか？', followUpQuestionZh: '还有什么没定下来的吗？' }),
];
