// Phase 3P-3: 会話contextual接続の拡張バッチ2（基礎の動詞・形容詞・場所）。全draft。
import type { VocabularyConversationPractice } from './vocabConversationPractice';

const d = (p: Omit<VocabularyConversationPractice, 'practiceType' | 'reviewStatus' | 'estimatedMinutes'> & { estimatedMinutes?: number }): VocabularyConversationPractice =>
  ({ estimatedMinutes: 3, practiceType: 'vocabulary', reviewStatus: 'draft', ...p });

export const VOCAB_CONVERSATION_PRACTICES_BATCH2: VocabularyConversationPractice[] = [
  d({ itemId: 'fi-tsukau', themeJa: 'よく使うものについて話す', themeZh: '聊聊你常用的东西',
    starterQuestionJa: '仕事で何をよく使いますか？', starterQuestionZh: '工作中你常用什么？',
    targetExpressions: ['を使います', 'を使って', 'を使いました'],
    supportExpressionsJa: ['パソコンを使います', '辞書アプリを使っています', '日本語を使う機会が少ないです'],
    supportExpressionsZh: ['用电脑', '在用词典软件', '用日语的机会很少'],
    followUpQuestionJa: '日本語を どこで使いますか？', followUpQuestionZh: '你在哪里用日语？' }),
  d({ itemId: 'fi-tsukuru', themeJa: '料理・作るものについて話す', themeZh: '聊聊做饭和制作的东西',
    starterQuestionJa: 'よく料理を作りますか？', starterQuestionZh: '你常做饭吗？',
    targetExpressions: ['を作ります', 'を作って', 'を作りました'],
    supportExpressionsJa: ['晩ごはんを作ります', '中国料理を作りました', '資料を作っています'],
    supportExpressionsZh: ['做晚饭', '做了中国菜', '在做资料'],
    followUpQuestionJa: '得意な料理は 何ですか？', followUpQuestionZh: '你拿手的菜是什么？' }),
  d({ itemId: 'fi-au', themeJa: '人と会うことについて話す', themeZh: '聊聊与人见面',
    starterQuestionJa: '週末、だれかに会いますか？', starterQuestionZh: '周末会见谁吗？',
    targetExpressions: ['に会います', 'に会いました', 'に会って'],
    supportExpressionsJa: ['友達に会います', '先週、同僚に会いました', '久しぶりに会って嬉しかったです'],
    supportExpressionsZh: ['见朋友', '上周见了同事', '久别重逢很开心'],
    followUpQuestionJa: '国の家族に いつ会えますか？', followUpQuestionZh: '什么时候能见到老家的家人？' }),
  d({ itemId: 'fi-neru', themeJa: '寝る時間・睡眠について話す', themeZh: '聊聊睡觉时间和睡眠',
    starterQuestionJa: '毎日、何時ごろ寝ますか？', starterQuestionZh: '每天几点左右睡觉？',
    targetExpressions: ['に寝ます', '寝て', '寝ました'],
    supportExpressionsJa: ['12時ごろ寝ます', '昨日は早く寝ました', 'よく寝られませんでした'],
    supportExpressionsZh: ['12点左右睡', '昨天睡得早', '没睡好'],
    followUpQuestionJa: '寝る前に 何をしますか？', followUpQuestionZh: '睡前做什么？' }),
  d({ itemId: 'fi-hairu', themeJa: '入る場所・組織について話す', themeZh: '聊聊进入的场所或组织',
    starterQuestionJa: '仕事のあと、お風呂に入りますか？', starterQuestionZh: '下班后你泡澡吗？',
    targetExpressions: ['に入ります', 'に入って', 'に入りました'],
    supportExpressionsJa: ['お風呂に入ります', '今の会社に去年入りました', 'カフェに入って休みました'],
    supportExpressionsZh: ['泡澡', '去年进了现在的公司', '进咖啡店休息了'],
    followUpQuestionJa: '今の会社に いつ入りましたか？', followUpQuestionZh: '什么时候进的现在的公司？' }),
  d({ itemId: 'fi-deru', themeJa: '家を出る時間・外出を話す', themeZh: '聊聊出门时间',
    starterQuestionJa: '朝、何時に家を出ますか？', starterQuestionZh: '早上几点出门？',
    targetExpressions: ['を出ます', 'を出て', 'に出ます'],
    supportExpressionsJa: ['8時に家を出ます', '会議に出ます', '会社を出てから買い物します'],
    supportExpressionsZh: ['8点出门', '参加会议', '离开公司后去买东西'],
    followUpQuestionJa: '明日は 何時に出ますか？', followUpQuestionZh: '明天几点出门？' }),
  d({ itemId: 'fi-noru', themeJa: '乗り物について話す', themeZh: '聊聊乘坐的交通工具',
    starterQuestionJa: '毎日、何に乗りますか？', starterQuestionZh: '每天坐什么交通工具？',
    targetExpressions: ['に乗ります', 'に乗って', 'に乗りました'],
    supportExpressionsJa: ['電車に乗ります', '自転車に乗って駅まで行きます', '新幹線に乗りました'],
    supportExpressionsZh: ['坐电车', '骑自行车去车站', '坐了新干线'],
    followUpQuestionJa: '日本で 新幹線に乗ったことがありますか？', followUpQuestionZh: '在日本坐过新干线吗？' }),
  d({ itemId: 'fi-oriru', themeJa: '降りる駅について話す', themeZh: '聊聊下车的车站',
    starterQuestionJa: '会社へ行くとき、どこの駅で降りますか？', starterQuestionZh: '去公司在哪站下车？',
    targetExpressions: ['で降ります', 'を降りて', 'で降りて'],
    supportExpressionsJa: ['〜駅で降ります', '次の駅で降りてください', 'バスを降りて5分歩きます'],
    supportExpressionsZh: ['在〜站下车', '请在下一站下车', '下公交后走5分钟'],
    followUpQuestionJa: '駅を降りてから 家まで何分ですか？', followUpQuestionZh: '出站后到家要几分钟？' }),
  d({ itemId: 'fi-chiisai', themeJa: '小さいものについて話す', themeZh: '用「小」描述东西',
    starterQuestionJa: '今の部屋は大きいですか？小さいですか？', starterQuestionZh: '现在的房间大还是小？',
    targetExpressions: ['小さい', '小さくて'],
    supportExpressionsJa: ['部屋は小さいです', '小さくて安い店が好きです', '字が小さくて読めません'],
    supportExpressionsZh: ['房间很小', '喜欢小而便宜的店', '字太小看不清'],
    followUpQuestionJa: '小さいころ、何が好きでしたか？', followUpQuestionZh: '小时候你喜欢什么？' }),
  d({ itemId: 'fi-takai', themeJa: '高いもの・高い場所を話す', themeZh: '聊聊贵的东西和高的地方',
    starterQuestionJa: '日本で何が高いと思いますか？', starterQuestionZh: '你觉得日本什么东西贵？',
    targetExpressions: ['高い', '高くて'],
    supportExpressionsJa: ['果物が高いです', '家賃が高くて大変です', 'スカイツリーは高いです'],
    supportExpressionsZh: ['水果很贵', '房租贵，很辛苦', '晴空塔很高'],
    followUpQuestionJa: '中国と日本、どちらが物価が高いですか？', followUpQuestionZh: '中国和日本哪边物价高？' }),
  d({ itemId: 'fi-yasui', themeJa: '安い店・ものについて話す', themeZh: '聊聊便宜的店和东西',
    starterQuestionJa: '家の近くに安いスーパーがありますか？', starterQuestionZh: '你家附近有便宜的超市吗？',
    targetExpressions: ['安い', '安くて'],
    supportExpressionsJa: ['あの店は安いです', '安くておいしい店を知っています', '業務スーパーが安いです'],
    supportExpressionsZh: ['那家店很便宜', '知道又便宜又好吃的店', '业务超市很便宜'],
    followUpQuestionJa: '安くて おすすめの店はどこですか？', followUpQuestionZh: '有什么便宜又推荐的店？' }),
  d({ itemId: 'fi-atarashii', themeJa: '新しく始めたことを話す', themeZh: '聊聊新开始的事',
    starterQuestionJa: '最近、何か新しいものを買いましたか？', starterQuestionZh: '最近买了什么新东西吗？',
    targetExpressions: ['新しい', '新しく'],
    supportExpressionsJa: ['新しいスマホを買いました', '新しい仕事を探しています', '新しい単語を覚えました'],
    supportExpressionsZh: ['买了新手机', '在找新工作', '记住了新单词'],
    followUpQuestionJa: '新しく 始めたいことはありますか？', followUpQuestionZh: '有什么想新开始的事吗？' }),
  d({ itemId: 'fi-furui', themeJa: '古いもの・場所について話す', themeZh: '聊聊旧的东西和古老的地方',
    starterQuestionJa: '古い町と新しい町、どちらが好きですか？', starterQuestionZh: '你喜欢古老的城市还是新城市？',
    targetExpressions: ['古い', '古くて'],
    supportExpressionsJa: ['京都は古い町です', '古いスマホを使っています', '古くて有名なお寺があります'],
    supportExpressionsZh: ['京都是古老的城市', '在用旧手机', '有古老而有名的寺庙'],
    followUpQuestionJa: '中国の古い町で おすすめはどこですか？', followUpQuestionZh: '中国的古城你推荐哪里？' }),
  d({ itemId: 'fi-samui', themeJa: '寒い季節について話す', themeZh: '聊聊寒冷的季节',
    starterQuestionJa: 'あなたの故郷の冬は寒いですか？', starterQuestionZh: '你家乡的冬天冷吗？',
    targetExpressions: ['寒い', '寒くて'],
    supportExpressionsJa: ['故郷はとても寒いです', '今朝は寒かったです', '寒くて外に出たくないです'],
    supportExpressionsZh: ['家乡非常冷', '今天早上很冷', '太冷了不想出门'],
    followUpQuestionJa: '寒い日は 何を食べたいですか？', followUpQuestionZh: '冷天想吃什么？' }),
  d({ itemId: 'fi-isogashii', themeJa: '忙しさについて話す', themeZh: '聊聊忙碌',
    starterQuestionJa: '最近、忙しいですか？', starterQuestionZh: '最近忙吗？',
    targetExpressions: ['忙しい', '忙しくて'],
    supportExpressionsJa: ['今週はとても忙しいです', '忙しくて勉強できません', '月末はいつも忙しいです'],
    supportExpressionsZh: ['这周非常忙', '忙得没法学习', '月底总是很忙'],
    followUpQuestionJa: '忙しいとき、どうやって休みますか？', followUpQuestionZh: '忙的时候怎么休息？' }),
  d({ itemId: 'fi-tanoshii', themeJa: '楽しかったことを話す', themeZh: '聊聊开心的事',
    starterQuestionJa: '最近、何が楽しかったですか？', starterQuestionZh: '最近有什么开心的事？',
    targetExpressions: ['楽しい', '楽しかった', '楽しくて'],
    supportExpressionsJa: ['旅行が楽しかったです', '友達と話すのは楽しいです', '仕事は大変ですが楽しいです'],
    supportExpressionsZh: ['旅行很开心', '和朋友聊天很开心', '工作辛苦但很开心'],
    followUpQuestionJa: '日本の生活で 何がいちばん楽しいですか？', followUpQuestionZh: '日本生活中什么最开心？' }),
  d({ itemId: 'fi-muzukashii', themeJa: '難しいことについて話す', themeZh: '聊聊觉得难的事',
    starterQuestionJa: '日本語で何がいちばん難しいですか？', starterQuestionZh: '日语里什么最难？',
    targetExpressions: ['難しい', '難しくて'],
    supportExpressionsJa: ['敬語が難しいです', '漢字の読み方が難しくて困ります', '思ったより難しくないです'],
    supportExpressionsZh: ['敬语很难', '汉字的读法太难，很头疼', '没有想象中难'],
    followUpQuestionJa: '難しいとき、だれに聞きますか？', followUpQuestionZh: '遇到难题时问谁？' }),
  d({ itemId: 'fi-chikai', themeJa: '近い場所について話す', themeZh: '聊聊近的地方',
    starterQuestionJa: '家から駅は近いですか？', starterQuestionZh: '你家离车站近吗？',
    targetExpressions: ['近い', '近くて', '近くに'],
    supportExpressionsJa: ['駅から近いです', '近くにコンビニがあります', '会社が近くて便利です'],
    supportExpressionsZh: ['离车站很近', '附近有便利店', '公司近，很方便'],
    followUpQuestionJa: '家の近くで よく行く店はありますか？', followUpQuestionZh: '家附近有常去的店吗？' }),
  d({ itemId: 'fi-tooi', themeJa: '遠い場所について話す', themeZh: '聊聊远的地方',
    starterQuestionJa: '会社（学校）は家から遠いですか？', starterQuestionZh: '公司（学校）离家远吗？',
    targetExpressions: ['遠い', '遠くて'],
    supportExpressionsJa: ['少し遠いです', '遠くて時間がかかります', '故郷は日本から遠いです'],
    supportExpressionsZh: ['有点远', '太远了很花时间', '家乡离日本很远'],
    followUpQuestionJa: '遠くても 行きたい場所はありますか？', followUpQuestionZh: '有没有再远也想去的地方？' }),
  d({ itemId: 'fi-ooi', themeJa: '多いものについて話す', themeZh: '用「多」描述事物',
    starterQuestionJa: '今の仕事は、仕事の量が多いですか？', starterQuestionZh: '现在的工作量多吗？',
    targetExpressions: ['多い', '多くて'],
    supportExpressionsJa: ['仕事が多いです', '東京は人が多くて疲れます', '中国人の同僚が多いです'],
    supportExpressionsZh: ['工作很多', '东京人多很累', '中国同事很多'],
    followUpQuestionJa: 'この町は 何が多いと思いますか？', followUpQuestionZh: '你觉得这个城市什么多？' }),
  d({ itemId: 'fi-sukunai', themeJa: '少ないものについて話す', themeZh: '用「少」描述事物',
    starterQuestionJa: '日本で、日本語を話す機会は多いですか？少ないですか？', starterQuestionZh: '在日本说日语的机会多还是少？',
    targetExpressions: ['少ない', '少なくて'],
    supportExpressionsJa: ['話す機会が少ないです', '休みが少なくて大変です', '知っている単語がまだ少ないです'],
    supportExpressionsZh: ['说的机会很少', '休息少很辛苦', '认识的单词还很少'],
    followUpQuestionJa: '時間が少ないとき、どう勉強しますか？', followUpQuestionZh: '时间少的时候怎么学习？' }),
  d({ itemId: 'fi-oishii', themeJa: 'おいしかったものを話す', themeZh: '聊聊好吃的东西',
    starterQuestionJa: '日本で食べて、何がいちばんおいしかったですか？', starterQuestionZh: '在日本吃过什么最好吃？',
    targetExpressions: ['おいしい', 'おいしかった', 'おいしくて'],
    supportExpressionsJa: ['ラーメンがおいしかったです', 'この店はおいしくて安いです', '故郷の料理がいちばんおいしいです'],
    supportExpressionsZh: ['拉面很好吃', '这家店好吃又便宜', '家乡菜最好吃'],
    followUpQuestionJa: 'おいしい店を 教えてください', followUpQuestionZh: '请推荐好吃的店' }),
  d({ itemId: 'fi-suki', themeJa: '好きなことについて話す', themeZh: '聊聊喜欢的事物',
    starterQuestionJa: '休みの日、何をするのが好きですか？', starterQuestionZh: '休息日你喜欢做什么？',
    targetExpressions: ['が好きです', 'が好きで'],
    supportExpressionsJa: ['映画が好きです', '料理をするのが好きです', '甘いものが好きで、よく買います'],
    supportExpressionsZh: ['喜欢电影', '喜欢做饭', '喜欢甜食，常常买'],
    followUpQuestionJa: '日本の食べ物で 何が好きですか？', followUpQuestionZh: '日本食物里你喜欢什么？' }),
  d({ itemId: 'fi-genki', themeJa: '体調・元気かどうかを話す', themeZh: '聊聊身体和精神状态',
    starterQuestionJa: '最近、元気ですか？', starterQuestionZh: '最近好吗？',
    targetExpressions: ['元気です', '元気が', '元気に'],
    supportExpressionsJa: ['おかげさまで元気です', '最近少し元気がありません', '家族は元気に暮らしています'],
    supportExpressionsZh: ['托您的福很好', '最近有点没精神', '家人生活得很好'],
    followUpQuestionJa: '元気がないとき、何をしますか？', followUpQuestionZh: '没精神的时候做什么？' }),
];
