// Phase 3P-3: 会話contextual接続の拡張バッチ1（基礎Unit1-2の未接続語）。全draft。
// 方針はvocabConversationPractice.tsと同一: 決定的スクリプト練習・部分一致判定・保存なし。
// 対象語の実例文（CEO確定値を含む）と整合するthemeにする。判定規則・復習規則は変更しない。
import type { VocabularyConversationPractice } from './vocabConversationPractice';

const d = (p: Omit<VocabularyConversationPractice, 'practiceType' | 'reviewStatus' | 'estimatedMinutes'> & { estimatedMinutes?: number }): VocabularyConversationPractice =>
  ({ estimatedMinutes: 3, practiceType: 'vocabulary', reviewStatus: 'draft', ...p });

export const VOCAB_CONVERSATION_PRACTICES_BATCH1: VocabularyConversationPractice[] = [
  d({ itemId: 'fi-namae', themeJa: '名前を伝える・聞く', themeZh: '介绍和询问名字',
    starterQuestionJa: 'お名前は何ですか？', starterQuestionZh: '你叫什么名字？',
    targetExpressions: ['名前は', '名前です'],
    supportExpressionsJa: ['私の名前は〜です', 'お名前を教えてください', '〜と呼んでください'],
    supportExpressionsZh: ['我的名字是〜', '请告诉我您的名字', '请叫我〜'],
    followUpQuestionJa: '名前は 中国語でどう書きますか？', followUpQuestionZh: '你的名字用中文怎么写？' }),
  d({ itemId: 'fi-shusshin', themeJa: '出身地について話す', themeZh: '聊聊你的家乡',
    starterQuestionJa: 'ご出身はどちらですか？', starterQuestionZh: '你是哪里人？',
    targetExpressions: ['出身です', '出身は'],
    supportExpressionsJa: ['〜の出身です', '出身は〜です', '〜から来ました'],
    supportExpressionsZh: ['我是〜出身', '老家在〜', '我从〜来'],
    followUpQuestionJa: '出身の町は どんなところですか？', followUpQuestionZh: '你的家乡是什么样的地方？' }),
  d({ itemId: 'fi-chugoku', themeJa: '中国のことを紹介する', themeZh: '介绍中国',
    starterQuestionJa: '中国のどこから来ましたか？', starterQuestionZh: '你来自中国哪里？',
    targetExpressions: ['中国の', '中国から', '中国では'],
    supportExpressionsJa: ['中国の〜から来ました', '中国では〜が有名です', '中国の食べ物が恋しいです'],
    supportExpressionsZh: ['我来自中国的〜', '在中国〜很有名', '想念中国的食物'],
    followUpQuestionJa: '中国で おすすめの場所はどこですか？', followUpQuestionZh: '中国有什么推荐的地方？' }),
  d({ itemId: 'fi-nihon', themeJa: '日本の印象を話す', themeZh: '聊聊对日本的印象',
    starterQuestionJa: '日本はどうですか？', starterQuestionZh: '你觉得日本怎么样？',
    targetExpressions: ['日本は', '日本の', '日本で'],
    supportExpressionsJa: ['日本は便利です', '日本の〜が好きです', '日本で〜をしたいです'],
    supportExpressionsZh: ['日本很方便', '喜欢日本的〜', '想在日本做〜'],
    followUpQuestionJa: '日本で 驚いたことはありますか？', followUpQuestionZh: '在日本有什么让你吃惊的事吗？' }),
  d({ itemId: 'fi-gakusei', themeJa: '学生かどうか・学生時代を話す', themeZh: '聊聊学生身份或学生时代',
    starterQuestionJa: '今、学生ですか？', starterQuestionZh: '你现在是学生吗？',
    targetExpressions: ['学生です', '学生の', '学生では'],
    supportExpressionsJa: ['日本語学校の学生です', '学生ではありません', '学生のとき〜しました'],
    supportExpressionsZh: ['我是日语学校的学生', '我不是学生', '学生时代做过〜'],
    followUpQuestionJa: '学生のとき、何が好きでしたか？', followUpQuestionZh: '学生时代你喜欢什么？' }),
  d({ itemId: 'fi-kaishain', themeJa: '会社員として自己紹介する', themeZh: '作为公司职员做自我介绍',
    starterQuestionJa: 'お仕事は何ですか？', starterQuestionZh: '你做什么工作？',
    targetExpressions: ['会社員です', '会社員で'],
    supportExpressionsJa: ['私は会社員です', 'IT会社の会社員です', '会社員で、営業をしています'],
    supportExpressionsZh: ['我是公司职员', '在IT公司上班', '是公司职员，做销售'],
    followUpQuestionJa: '仕事は 楽しいですか？', followUpQuestionZh: '工作开心吗？' }),
  d({ itemId: 'fi-kaisha', themeJa: '会社について話す', themeZh: '聊聊你的公司',
    starterQuestionJa: '会社はどこにありますか？', starterQuestionZh: '你的公司在哪里？',
    targetExpressions: ['会社は', '会社に', '会社の'],
    supportExpressionsJa: ['会社は〜にあります', '会社に電車で行きます', '会社の人はやさしいです'],
    supportExpressionsZh: ['公司在〜', '坐电车去公司', '公司的人很好'],
    followUpQuestionJa: '会社まで どのくらいかかりますか？', followUpQuestionZh: '到公司要多久？' }),
  d({ itemId: 'fi-nihongo', themeJa: '日本語学習の理由を話す', themeZh: '聊聊你学日语的原因',
    starterQuestionJa: 'どうして日本語を勉強していますか？', starterQuestionZh: '你为什么学日语？',
    targetExpressions: ['日本語を', '日本語で', '日本語が'],
    supportExpressionsJa: ['仕事で日本語を使います', '日本語で話したいです', '日本語が好きです'],
    supportExpressionsZh: ['工作中要用日语', '想用日语交流', '喜欢日语'],
    followUpQuestionJa: '日本語で 何ができるようになりたいですか？', followUpQuestionZh: '你想用日语做到什么？' }),
  d({ itemId: 'fi-suru', themeJa: '週末にすることを話す', themeZh: '聊聊周末做的事',
    starterQuestionJa: '週末、何をしますか？', starterQuestionZh: '周末你做什么？',
    targetExpressions: ['をします', 'をしました', 'をして'],
    supportExpressionsJa: ['買い物をします', '掃除をしました', '運動をしています'],
    supportExpressionsZh: ['去买东西', '打扫了卫生', '在做运动'],
    followUpQuestionJa: '先週末は 何をしましたか？', followUpQuestionZh: '上周末做了什么？' }),
  d({ itemId: 'fi-kaku', themeJa: '書くものについて話す', themeZh: '聊聊你写的东西',
    starterQuestionJa: '日本語で何か書きますか？', starterQuestionZh: '你用日语写什么吗？',
    targetExpressions: ['を書きます', 'を書いて', 'を書きました'],
    supportExpressionsJa: ['メールを書きます', '日記を書いています', '漢字を書くのが難しいです'],
    supportExpressionsZh: ['写邮件', '在写日记', '写汉字很难'],
    followUpQuestionJa: '漢字を書くのは 好きですか？', followUpQuestionZh: '你喜欢写汉字吗？' }),
  d({ itemId: 'fi-yomu', themeJa: '読むものについて話す', themeZh: '聊聊你读的东西',
    starterQuestionJa: '何か日本語で読んでいますか？', starterQuestionZh: '你在用日语读什么吗？',
    targetExpressions: ['を読みます', 'を読んで', 'を読みました'],
    supportExpressionsJa: ['マンガを読みます', 'ニュースを読んでいます', '本を読むのが好きです'],
    supportExpressionsZh: ['看漫画', '在读新闻', '喜欢读书'],
    followUpQuestionJa: '最近、何を読みましたか？', followUpQuestionZh: '最近读了什么？' }),
  d({ itemId: 'fi-kau', themeJa: '買い物について話す', themeZh: '聊聊购物',
    starterQuestionJa: '週末、何を買いましたか？', starterQuestionZh: '周末买了什么？',
    targetExpressions: ['を買います', 'を買いました', 'を買って'],
    supportExpressionsJa: ['スーパーで〜を買いました', 'ネットで買います', '何も買いませんでした'],
    supportExpressionsZh: ['在超市买了〜', '在网上买', '什么都没买'],
    followUpQuestionJa: 'よく どこで買い物しますか？', followUpQuestionZh: '你常在哪里买东西？' }),
  d({ itemId: 'fi-kaeru', themeJa: '帰る時間について話す', themeZh: '聊聊回家的时间',
    starterQuestionJa: '毎日、何時ごろ家に帰りますか？', starterQuestionZh: '每天几点回家？',
    targetExpressions: ['に帰ります', 'に帰って', '帰りました'],
    supportExpressionsJa: ['7時ごろ家に帰ります', '遅く帰りました', '国に帰りたいです'],
    supportExpressionsZh: ['7点左右回家', '回去晚了', '想回国'],
    followUpQuestionJa: '帰ってから 何をしますか？', followUpQuestionZh: '回家后做什么？' }),
  d({ itemId: 'fi-wakaru', themeJa: '分かること・分からないことを伝える', themeZh: '表达懂与不懂',
    starterQuestionJa: '日本語のニュースは分かりますか？', starterQuestionZh: '你能听懂日语新闻吗？',
    targetExpressions: ['分かります', '分かりません', '分かって'],
    supportExpressionsJa: ['少し分かります', 'ぜんぜん分かりません', '意味が分かりました'],
    supportExpressionsZh: ['懂一点', '完全不懂', '明白意思了'],
    followUpQuestionJa: '何が いちばん分かりにくいですか？', followUpQuestionZh: '什么最难懂？' }),
  d({ itemId: 'fi-aru', themeJa: '持ち物・予定があるか話す', themeZh: '聊聊有什么东西或安排',
    starterQuestionJa: '今週、予定がありますか？', starterQuestionZh: '这周有安排吗？',
    targetExpressions: ['があります', 'はありません', 'があって'],
    supportExpressionsJa: ['約束があります', '時間がありません', '近くにコンビニがあります'],
    supportExpressionsZh: ['有约', '没有时间', '附近有便利店'],
    followUpQuestionJa: '家の近くに 何がありますか？', followUpQuestionZh: '你家附近有什么？' }),
  d({ itemId: 'fi-iru-exist', themeJa: '家族やペットがいるか話す', themeZh: '聊聊家人或宠物',
    starterQuestionJa: '日本に家族がいますか？', starterQuestionZh: '在日本有家人吗？',
    targetExpressions: ['がいます', 'はいません', 'がいて'],
    supportExpressionsJa: ['妻（夫）がいます', '子どもが2人います', '日本に友達がいません'],
    supportExpressionsZh: ['有妻子（丈夫）', '有两个孩子', '在日本没有朋友'],
    followUpQuestionJa: '国に だれがいますか？', followUpQuestionZh: '在老家有谁？' }),
  d({ itemId: 'fi-neko', themeJa: 'ペット・好きな動物を話す', themeZh: '聊聊宠物和喜欢的动物',
    starterQuestionJa: '猫と犬、どちらが好きですか？', starterQuestionZh: '猫和狗你喜欢哪个？',
    targetExpressions: ['猫が', '猫を', '猫は'],
    supportExpressionsJa: ['猫が好きです', '猫を飼っています', '猫はかわいいです'],
    supportExpressionsZh: ['喜欢猫', '养着猫', '猫很可爱'],
    followUpQuestionJa: '動物を 飼ったことがありますか？', followUpQuestionZh: '你养过动物吗？' }),
  d({ itemId: 'fi-densha', themeJa: '電車での通勤・移動を話す', themeZh: '聊聊坐电车通勤出行',
    starterQuestionJa: '毎日、電車に乗りますか？', starterQuestionZh: '你每天坐电车吗？',
    targetExpressions: ['電車で', '電車に', '電車が'],
    supportExpressionsJa: ['電車で会社に行きます', '電車が混んでいます', '電車の中で音楽を聞きます'],
    supportExpressionsZh: ['坐电车去公司', '电车很挤', '在电车里听音乐'],
    followUpQuestionJa: '日本の電車は どう思いますか？', followUpQuestionZh: '你觉得日本的电车怎么样？' }),
  d({ itemId: 'fi-okiru', themeJa: '起きる時間について話す', themeZh: '聊聊起床时间',
    starterQuestionJa: '毎朝、何時に起きますか？', starterQuestionZh: '每天早上几点起床？',
    targetExpressions: ['に起きます', 'に起きて', '起きました'],
    supportExpressionsJa: ['6時に起きます', '今朝は遅く起きました', '起きてすぐ水を飲みます'],
    supportExpressionsZh: ['6点起床', '今天早上起晚了', '起床后马上喝水'],
    followUpQuestionJa: '休みの日は 何時に起きますか？', followUpQuestionZh: '休息日几点起床？' }),
  d({ itemId: 'fi-ikura', themeJa: '値段を聞く・話す', themeZh: '询问和谈论价格',
    starterQuestionJa: '日本のランチは、だいたいいくらですか？', starterQuestionZh: '日本的午餐大概多少钱？',
    targetExpressions: ['いくら'],
    supportExpressionsJa: ['これはいくらですか', '1000円ぐらいです', 'いくらかかりますか'],
    supportExpressionsZh: ['这个多少钱', '大概1000日元', '要花多少钱'],
    followUpQuestionJa: '家賃は いくらぐらいですか？', followUpQuestionZh: '房租大概多少钱？' }),
  d({ itemId: 'fi-ikutsu', themeJa: '数を聞く・話す', themeZh: '询问和谈论数量',
    starterQuestionJa: 'かばんの中に、荷物がいくつありますか？', starterQuestionZh: '包里有几件东西？',
    targetExpressions: ['いくつ'],
    supportExpressionsJa: ['いくつありますか', '3つあります', 'いくつか買いました'],
    supportExpressionsZh: ['有几个', '有三个', '买了几个'],
    followUpQuestionJa: '今日、新しい単語をいくつ覚えましたか？', followUpQuestionZh: '今天记住了几个新单词？' }),
  d({ itemId: 'fi-nanji', themeJa: '時間を聞く・話す', themeZh: '询问和谈论时间',
    starterQuestionJa: '今、何時ですか？', starterQuestionZh: '现在几点？',
    targetExpressions: ['何時'],
    supportExpressionsJa: ['何時に始まりますか', '何時までですか', '9時からです'],
    supportExpressionsZh: ['几点开始', '到几点', '从9点开始'],
    followUpQuestionJa: '仕事（学校）は 何時から何時までですか？', followUpQuestionZh: '工作（学校）从几点到几点？' }),
  d({ itemId: 'fi-kore', themeJa: '目の前のものを指して話す', themeZh: '指着眼前的东西说',
    starterQuestionJa: 'これは日本語で何と言いますか？', starterQuestionZh: '这个用日语怎么说？',
    targetExpressions: ['これは', 'これを', 'これが'],
    supportExpressionsJa: ['これは〜です', 'これをください', 'これが好きです'],
    supportExpressionsZh: ['这是〜', '请给我这个', '喜欢这个'],
    followUpQuestionJa: 'それは 何ですか？', followUpQuestionZh: '那是什么？' }),
  d({ itemId: 'fi-en', themeJa: '円で値段を言う', themeZh: '用日元说价格',
    starterQuestionJa: '毎月、食費はだいたい何円ぐらいですか？', starterQuestionZh: '每个月伙食费大概多少日元？',
    targetExpressions: ['円です', '円ぐらい', '円で'],
    supportExpressionsJa: ['3万円ぐらいです', '100円で買えます', '1000円札しかありません'],
    supportExpressionsZh: ['大概3万日元', '100日元就能买', '只有1000日元纸币'],
    followUpQuestionJa: '日本で いちばん高かった買い物は何円でしたか？', followUpQuestionZh: '在日本买过最贵的东西是多少日元？' }),
  d({ itemId: 'fi-kudasai', themeJa: '店で注文する・頼む', themeZh: '在店里点单和请求',
    starterQuestionJa: 'カフェで何を注文しますか？「〜をください」と言ってみましょう', starterQuestionZh: '在咖啡店你会点什么？试着说「〜をください」',
    targetExpressions: ['をください', 'てください'],
    supportExpressionsJa: ['コーヒーをください', 'お水をください', 'ゆっくり話してください'],
    supportExpressionsZh: ['请给我咖啡', '请给我水', '请说慢一点'],
    followUpQuestionJa: '店員に 何かお願いしたいとき、何と言いますか？', followUpQuestionZh: '想拜托店员时怎么说？' }),
];
