// Phase 3P-3: 会話contextual接続の拡張バッチ4（思考・伝達動詞／N3準備の名詞・形容詞・副詞）。全draft。
import type { VocabularyConversationPractice } from './vocabConversationPractice';

const d = (p: Omit<VocabularyConversationPractice, 'practiceType' | 'reviewStatus' | 'estimatedMinutes'> & { estimatedMinutes?: number }): VocabularyConversationPractice =>
  ({ estimatedMinutes: 3, practiceType: 'vocabulary', reviewStatus: 'draft', ...p });

export const VOCAB_CONVERSATION_PRACTICES_BATCH4: VocabularyConversationPractice[] = [
  d({ itemId: 'fi-omou', themeJa: '思ったことを伝える', themeZh: '表达自己的想法',
    starterQuestionJa: '日本の夏について、どう思いますか？', starterQuestionZh: '你觉得日本的夏天怎么样？',
    targetExpressions: ['と思います', 'と思いました'],
    supportExpressionsJa: ['暑いと思います', 'いいと思います', '難しいと思いました'],
    supportExpressionsZh: ['我觉得很热', '我觉得不错', '我当时觉得很难'],
    followUpQuestionJa: '10年後、日本にいると思いますか？', followUpQuestionZh: '你觉得10年后你还在日本吗？' }),
  d({ itemId: 'fi-kangaeru', themeJa: '考えていることを話す', themeZh: '聊聊正在考虑的事',
    starterQuestionJa: '今、何か考えていることがありますか？', starterQuestionZh: '现在有什么在考虑的事吗？',
    targetExpressions: ['を考えています', 'を考えて', 'を考えました'],
    supportExpressionsJa: ['転職を考えています', 'よく考えてから決めます', '将来のことを考えています'],
    supportExpressionsZh: ['在考虑换工作', '好好考虑后再决定', '在考虑将来的事'],
    followUpQuestionJa: '「思う」と「考える」の違いが分かりますか？', followUpQuestionZh: '你知道「思う」和「考える」的区别吗？' }),
  d({ itemId: 'fi-kanjiru', themeJa: '感じたことを話す', themeZh: '聊聊感受',
    starterQuestionJa: '日本に来て、文化の違いを感じましたか？', starterQuestionZh: '来日本后感受到文化差异了吗？',
    targetExpressions: ['を感じます', 'を感じました', 'と感じて'],
    supportExpressionsJa: ['違いを感じました', 'ストレスを感じます', '成長を感じています'],
    supportExpressionsZh: ['感受到了差异', '感到有压力', '感觉到自己在成长'],
    followUpQuestionJa: '最近、幸せを感じた瞬間はありますか？', followUpQuestionZh: '最近有感到幸福的瞬间吗？' }),
  d({ itemId: 'fi-tsutaeru', themeJa: '伝えたいことを話す', themeZh: '聊聊想传达的话',
    starterQuestionJa: '家族に何か伝えたいことがありますか？', starterQuestionZh: '有什么想对家人说的吗？',
    targetExpressions: ['を伝えます', 'を伝えたい', 'に伝えて'],
    supportExpressionsJa: ['感謝を伝えたいです', '気持ちを日本語で伝えるのは難しいです', '上司に伝えておきます'],
    supportExpressionsZh: ['想表达感谢', '用日语表达心情很难', '我会转告上司'],
    followUpQuestionJa: '日本語で気持ちを伝えるとき、何が難しいですか？', followUpQuestionZh: '用日语表达心情时什么最难？' }),
  d({ itemId: 'fi-setsumei', themeJa: '説明する場面について話す', themeZh: '聊聊需要说明的场景',
    starterQuestionJa: '仕事で何かを説明することがありますか？', starterQuestionZh: '工作中需要说明什么吗？',
    targetExpressions: ['説明します', '説明して', '説明が'],
    supportExpressionsJa: ['使い方を説明します', 'もう一度説明してください', '説明が分かりやすかったです'],
    supportExpressionsZh: ['说明使用方法', '请再说明一次', '说明很容易懂'],
    followUpQuestionJa: '日本語で説明するとき、どんな工夫をしますか？', followUpQuestionZh: '用日语说明时你有什么技巧？' }),
  d({ itemId: 'fi-soudan', themeJa: '相談する相手について話す', themeZh: '聊聊商量的对象',
    starterQuestionJa: '困ったとき、だれに相談しますか？', starterQuestionZh: '遇到困难时和谁商量？',
    targetExpressions: ['に相談します', '相談して', '相談が'],
    supportExpressionsJa: ['友達に相談します', '上司に相談してから決めます', '相談があるんですが…'],
    supportExpressionsZh: ['和朋友商量', '和上司商量后再定', '我有事想商量…'],
    followUpQuestionJa: '「相談があるんですが」と言ってみましょう。何を相談しますか？', followUpQuestionZh: '试着说「相談があるんですが」。你想商量什么？' }),
  d({ itemId: 'fi-renraku', themeJa: '連絡の手段について話す', themeZh: '聊聊联系方式',
    starterQuestionJa: '家族とはどうやって連絡を取りますか？', starterQuestionZh: '你和家人怎么联系？',
    targetExpressions: ['連絡します', '連絡を', '連絡が'],
    supportExpressionsJa: ['WeChatで連絡します', '後で連絡します', '会社から連絡が来ました'],
    supportExpressionsZh: ['用微信联系', '稍后联系', '公司来联系了'],
    followUpQuestionJa: '遅刻しそうなとき、会社に何と連絡しますか？', followUpQuestionZh: '快迟到时怎么跟公司联系？' }),
  d({ itemId: 'fi-kakunin', themeJa: '確認する習慣について話す', themeZh: '聊聊确认的习惯',
    starterQuestionJa: '家を出る前に、何を確認しますか？', starterQuestionZh: '出门前你确认什么？',
    targetExpressions: ['を確認します', '確認して', '確認しました'],
    supportExpressionsJa: ['かぎを確認します', 'メールを確認してから返事します', '予定を確認しました'],
    supportExpressionsZh: ['确认钥匙', '确认邮件后再回复', '确认了日程'],
    followUpQuestionJa: '仕事で「ご確認ください」を使ったことがありますか？', followUpQuestionZh: '工作中用过「ご確認ください」吗？' }),
  d({ itemId: 'fi-junbi', themeJa: '準備していることを話す', themeZh: '聊聊在准备的事',
    starterQuestionJa: '明日のために、何か準備しますか？', starterQuestionZh: '为了明天你会准备什么？',
    targetExpressions: ['を準備します', '準備して', '準備が'],
    supportExpressionsJa: ['お弁当を準備します', '会議の資料を準備しています', '準備ができました'],
    supportExpressionsZh: ['准备便当', '在准备会议资料', '准备好了'],
    followUpQuestionJa: '旅行の前に 何を準備しますか？', followUpQuestionZh: '旅行前准备什么？' }),
  d({ itemId: 'fi-yoyaku', themeJa: '予約の経験を話す', themeZh: '聊聊预约的经历',
    starterQuestionJa: '日本語でレストランを予約したことがありますか？', starterQuestionZh: '用日语预约过餐厅吗？',
    targetExpressions: ['を予約します', '予約して', '予約を'],
    supportExpressionsJa: ['ネットで予約します', '電話で予約するのは緊張します', '病院の予約を取りました'],
    supportExpressionsZh: ['在网上预约', '打电话预约很紧张', '挂了医院的号'],
    followUpQuestionJa: '電話で「予約したいんですが」と言ってみましょう', followUpQuestionZh: '试着在电话里说「予約したいんですが」' }),
  d({ itemId: 'fi-riyou', themeJa: 'よく利用するサービスを話す', themeZh: '聊聊常用的服务',
    starterQuestionJa: 'どんなアプリやサービスをよく利用しますか？', starterQuestionZh: '你常用什么软件或服务？',
    targetExpressions: ['を利用します', '利用して', '利用しています'],
    supportExpressionsJa: ['ネットバンクを利用しています', '図書館を利用します', '初めて利用します'],
    supportExpressionsZh: ['在用网上银行', '利用图书馆', '第一次使用'],
    followUpQuestionJa: '「使う」と「利用する」、どちらが丁寧だと思いますか？', followUpQuestionZh: '「使う」和「利用する」你觉得哪个更正式？' }),
  d({ itemId: 'fi-erabu', themeJa: '選ぶ基準について話す', themeZh: '聊聊选择的标准',
    starterQuestionJa: 'レストランを選ぶとき、何を大事にしますか？', starterQuestionZh: '选餐厅时你看重什么？',
    targetExpressions: ['を選びます', '選んで', '選びました'],
    supportExpressionsJa: ['安い店を選びます', '口コミを見て選んでいます', 'この仕事を選びました'],
    supportExpressionsZh: ['选便宜的店', '看评价来选', '选择了这份工作'],
    followUpQuestionJa: 'どうして日本を選びましたか？', followUpQuestionZh: '为什么选择了日本？' }),
  d({ itemId: 'fi-shiraberu', themeJa: '調べ方について話す', themeZh: '聊聊查资料的方法',
    starterQuestionJa: '分からない単語があるとき、どうやって調べますか？', starterQuestionZh: '遇到不懂的单词怎么查？',
    targetExpressions: ['を調べます', '調べて', '調べました'],
    supportExpressionsJa: ['アプリで調べます', '調べてから行きます', '行き方を調べました'],
    supportExpressionsZh: ['用软件查', '查好了再去', '查了怎么去'],
    followUpQuestionJa: '最近、何を調べましたか？', followUpQuestionZh: '最近查了什么？' }),
  d({ itemId: 'fi-oboeru', themeJa: '覚え方について話す', themeZh: '聊聊记忆方法',
    starterQuestionJa: '単語をどうやって覚えていますか？', starterQuestionZh: '你怎么记单词？',
    targetExpressions: ['を覚えます', '覚えて', '覚えました'],
    supportExpressionsJa: ['毎日10個覚えます', '例文で覚えています', '名前を覚えるのが苦手です'],
    supportExpressionsZh: ['每天记10个', '用例句记', '不擅长记名字'],
    followUpQuestionJa: '今日、覚えた日本語を一つ教えてください', followUpQuestionZh: '告诉我一个你今天记住的日语' }),
  d({ itemId: 'fi-wasureru', themeJa: '忘れた経験を話す', themeZh: '聊聊忘记东西的经历',
    starterQuestionJa: '最近、何か忘れたことがありますか？', starterQuestionZh: '最近忘了什么事吗？',
    targetExpressions: ['を忘れました', '忘れて', '忘れないように'],
    supportExpressionsJa: ['傘を忘れました', '単語をすぐ忘れてしまいます', '忘れないようにメモします'],
    supportExpressionsZh: ['忘了伞', '单词马上就忘', '为了不忘记会做笔记'],
    followUpQuestionJa: '忘れ物をしたとき、日本語で何と言いますか？', followUpQuestionZh: '忘带东西时用日语怎么说？' }),
  d({ itemId: 'fi-kuraberu', themeJa: '比べて話す', themeZh: '比较着说',
    starterQuestionJa: '日本と中国の生活を比べて、どうですか？', starterQuestionZh: '比较日本和中国的生活，怎么样？',
    targetExpressions: ['と比べて', 'を比べます', '比べると'],
    supportExpressionsJa: ['中国と比べて物価が高いです', '去年と比べて上達しました', '値段を比べてから買います'],
    supportExpressionsZh: ['和中国比物价高', '和去年比进步了', '比完价格再买'],
    followUpQuestionJa: '1年前の自分と比べて、何が変わりましたか？', followUpQuestionZh: '和一年前的自己比，有什么变化？' }),
  d({ itemId: 'fi-nareru', themeJa: '慣れたことについて話す', themeZh: '聊聊习惯了的事',
    starterQuestionJa: '日本の生活にもう慣れましたか？', starterQuestionZh: '习惯日本的生活了吗？',
    targetExpressions: ['に慣れました', 'に慣れて', 'に慣れません'],
    supportExpressionsJa: ['生活に慣れました', '仕事に慣れてきました', '敬語にまだ慣れません'],
    supportExpressionsZh: ['习惯生活了', '渐渐习惯工作了', '还不习惯敬语'],
    followUpQuestionJa: 'いちばん慣れるのに時間がかかったことは何ですか？', followUpQuestionZh: '什么事花了最长时间才习惯？' }),
  d({ itemId: 'fi-komaru', themeJa: '困った経験を話す', themeZh: '聊聊为难的经历',
    starterQuestionJa: '日本で困ったことがありますか？', starterQuestionZh: '在日本遇到过为难的事吗？',
    targetExpressions: ['困ります', '困りました', '困って'],
    supportExpressionsJa: ['道が分からなくて困りました', '敬語が分からないと困ります', '困ったときは駅員に聞きます'],
    supportExpressionsZh: ['不认路很为难', '不懂敬语会很麻烦', '为难时问站务员'],
    followUpQuestionJa: '困ったとき、日本語でどう助けを求めますか？', followUpQuestionZh: '为难时用日语怎么求助？' }),
  d({ itemId: 'fi-ganbaru', themeJa: '頑張っていることを話す', themeZh: '聊聊在努力的事',
    starterQuestionJa: '今、何を頑張っていますか？', starterQuestionZh: '现在在努力做什么？',
    targetExpressions: ['を頑張っています', '頑張ります', '頑張って'],
    supportExpressionsJa: ['日本語を頑張っています', '明日も頑張ります', '「頑張ってください」と言われました'],
    supportExpressionsZh: ['在努力学日语', '明天也加油', '别人对我说「加油」'],
    followUpQuestionJa: '「頑張って」と言われたら、何と答えますか？', followUpQuestionZh: '别人说「頑張って」时你怎么回答？' }),
  d({ itemId: 'fi-kimochi', themeJa: '気持ちを言葉にする', themeZh: '把心情说出来',
    starterQuestionJa: '今日はどんな気持ちですか？', starterQuestionZh: '今天心情怎么样？',
    targetExpressions: ['気持ちが', '気持ちを', '気持ちです'],
    supportExpressionsJa: ['気持ちがいいです', '感謝の気持ちを伝えたいです', '複雑な気持ちです'],
    supportExpressionsZh: ['心情舒畅', '想表达感谢的心情', '心情复杂'],
    followUpQuestionJa: '朝の散歩は気持ちがいいですよ。試したことがありますか？', followUpQuestionZh: '早上散步很舒服哦。你试过吗？' }),
  d({ itemId: 'fi-kibun', themeJa: '気分について話す', themeZh: '聊聊情绪状态',
    starterQuestionJa: '気分がいいとき、何をしたくなりますか？', starterQuestionZh: '心情好的时候想做什么？',
    targetExpressions: ['気分が', '気分です', '気分転換'],
    supportExpressionsJa: ['今日は気分がいいです', '気分が悪くなりました', '気分転換に散歩します'],
    supportExpressionsZh: ['今天心情好', '感觉不舒服了', '散步换换心情'],
    followUpQuestionJa: '「気分」と「気持ち」の違いを意識したことがありますか？', followUpQuestionZh: '你注意过「気分」和「気持ち」的区别吗？' }),
  d({ itemId: 'fi-riyuu', themeJa: '理由を説明する', themeZh: '说明理由',
    starterQuestionJa: '日本語を勉強する理由は何ですか？', starterQuestionZh: '你学日语的理由是什么？',
    targetExpressions: ['理由は', '理由が', '理由で'],
    supportExpressionsJa: ['理由は仕事です', '特に理由はありません', '家庭の理由で休みます'],
    supportExpressionsZh: ['理由是工作', '没有特别的理由', '因家庭原因请假'],
    followUpQuestionJa: '会社を休むとき、理由をどう伝えますか？', followUpQuestionZh: '请假时怎么说明理由？' }),
  d({ itemId: 'fi-iken', themeJa: '意見を言う練習', themeZh: '练习发表意见',
    starterQuestionJa: '会議で意見を言うことがありますか？', starterQuestionZh: '开会时你发表意见吗？',
    targetExpressions: ['意見を', '意見は', '意見が'],
    supportExpressionsJa: ['意見を言うのは緊張します', '私の意見は〜です', 'いい意見だと思います'],
    supportExpressionsZh: ['发表意见很紧张', '我的意见是〜', '我觉得是好意见'],
    followUpQuestionJa: '日本では意見をはっきり言いにくいと感じますか？', followUpQuestionZh: '你觉得在日本很难直说意见吗？' }),
  d({ itemId: 'fi-keiken', themeJa: '経験を話す', themeZh: '聊聊经历',
    starterQuestionJa: '日本で、いい経験ができましたか？', starterQuestionZh: '在日本有过好的经历吗？',
    targetExpressions: ['経験が', '経験を', '経験は'],
    supportExpressionsJa: ['いい経験になりました', '接客の経験があります', '初めての経験です'],
    supportExpressionsZh: ['成了好的经历', '有接待客人的经验', '第一次的经历'],
    followUpQuestionJa: '仕事の面接で、どんな経験をアピールしますか？', followUpQuestionZh: '面试时你会强调什么经验？' }),
  d({ itemId: 'fi-yotei', themeJa: '予定を話す', themeZh: '聊聊日程安排',
    starterQuestionJa: '今週末の予定は何ですか？', starterQuestionZh: '这周末有什么安排？',
    targetExpressions: ['予定が', '予定です', '予定は'],
    supportExpressionsJa: ['友達と会う予定です', '特に予定がありません', '予定が変わりました'],
    supportExpressionsZh: ['打算和朋友见面', '没有特别的安排', '安排变了'],
    followUpQuestionJa: '来月、何か大きな予定がありますか？', followUpQuestionZh: '下个月有什么重要安排吗？' }),
  d({ itemId: 'fi-shuukan', themeJa: '習慣について話す', themeZh: '聊聊习惯',
    starterQuestionJa: '毎日の習慣はありますか？', starterQuestionZh: '你有每天的习惯吗？',
    targetExpressions: ['習慣が', '習慣です', '習慣に'],
    supportExpressionsJa: ['朝コーヒーを飲む習慣があります', '日本の習慣に驚きました', '勉強を習慣にしたいです'],
    supportExpressionsZh: ['有早上喝咖啡的习惯', '对日本的习惯感到吃惊', '想把学习变成习惯'],
    followUpQuestionJa: '日本の習慣で 驚いたものはありますか？', followUpQuestionZh: '日本的习惯里有让你吃惊的吗？' }),
  d({ itemId: 'fi-houhou', themeJa: '方法について話す', themeZh: '聊聊方法',
    starterQuestionJa: 'あなたの勉強方法を教えてください', starterQuestionZh: '介绍一下你的学习方法吧',
    targetExpressions: ['方法は', '方法が', '方法で'],
    supportExpressionsJa: ['いい方法を探しています', 'この方法で覚えました', '支払い方法を選んでください'],
    supportExpressionsZh: ['在找好方法', '用这个方法记住的', '请选择支付方式'],
    followUpQuestionJa: 'ほかの人の勉強方法で 試したいものはありますか？', followUpQuestionZh: '有想试试别人的学习方法吗？' }),
  d({ itemId: 'fi-mondai', themeJa: '問題について話す', themeZh: '聊聊问题',
    starterQuestionJa: '今、何か問題がありますか？', starterQuestionZh: '现在有什么问题吗？',
    targetExpressions: ['問題が', '問題は', '問題ありません'],
    supportExpressionsJa: ['特に問題ありません', '問題が起きました', 'それは大きな問題ですね'],
    supportExpressionsZh: ['没什么问题', '出问题了', '那是个大问题啊'],
    followUpQuestionJa: '仕事で問題が起きたら、まずどうしますか？', followUpQuestionZh: '工作出问题时你先做什么？' }),
  d({ itemId: 'fi-joukyou', themeJa: '状況を説明する', themeZh: '说明情况',
    starterQuestionJa: '今の仕事（勉強）の状況はどうですか？', starterQuestionZh: '现在工作（学习）的情况怎么样？',
    targetExpressions: ['状況は', '状況を', '状況が'],
    supportExpressionsJa: ['状況は順調です', '状況を説明します', '状況が変わりました'],
    supportExpressionsZh: ['情况顺利', '我来说明情况', '情况变了'],
    followUpQuestionJa: '上司に状況を報告するとき、何から話しますか？', followUpQuestionZh: '向上司汇报情况时先说什么？' }),
  d({ itemId: 'fi-kankei', themeJa: '人間関係について話す', themeZh: '聊聊人际关系',
    starterQuestionJa: '職場の人間関係はどうですか？', starterQuestionZh: '职场的人际关系怎么样？',
    targetExpressions: ['関係が', '関係は', '関係ありません'],
    supportExpressionsJa: ['関係は良好です', '仕事に関係がある話です', '私には関係ありません'],
    supportExpressionsZh: ['关系很好', '是和工作有关的话题', '和我没关系'],
    followUpQuestionJa: 'いい人間関係を作るコツは 何だと思いますか？', followUpQuestionZh: '你觉得建立好人际关系的秘诀是什么？' }),
  d({ itemId: 'fi-jouhou', themeJa: '情報の集め方を話す', themeZh: '聊聊怎么获取信息',
    starterQuestionJa: '日本の情報はどこで集めますか？', starterQuestionZh: '你从哪里获取日本的信息？',
    targetExpressions: ['情報を', '情報が', '情報は'],
    supportExpressionsJa: ['SNSで情報を集めます', '正しい情報か確認します', '役に立つ情報でした'],
    supportExpressionsZh: ['在社交平台收集信息', '确认信息是否正确', '是有用的信息'],
    followUpQuestionJa: '中国語の情報と日本語の情報、どちらを信じますか？', followUpQuestionZh: '中文信息和日语信息你更相信哪个？' }),
  d({ itemId: 'fi-tsugou', themeJa: '都合を伝える', themeZh: '表达时间方便与否',
    starterQuestionJa: '来週、都合がいい日はいつですか？', starterQuestionZh: '下周哪天方便？',
    targetExpressions: ['都合が', '都合の', '都合で'],
    supportExpressionsJa: ['金曜日は都合がいいです', '都合が悪くなりました', '家の都合で休みます'],
    supportExpressionsZh: ['周五方便', '变得不方便了', '因家里的事请假'],
    followUpQuestionJa: '誘いを断るとき、「都合が悪い」をどう使いますか？', followUpQuestionZh: '拒绝邀请时怎么用「都合が悪い」？' }),
  d({ itemId: 'fi-yakusoku', themeJa: '約束について話す', themeZh: '聊聊约定',
    starterQuestionJa: '今週、だれかと約束がありますか？', starterQuestionZh: '这周和谁有约吗？',
    targetExpressions: ['約束が', '約束を', '約束です'],
    supportExpressionsJa: ['友達と約束があります', '約束を守ります', '約束の時間に遅れました'],
    supportExpressionsZh: ['和朋友有约', '遵守约定', '比约定时间晚了'],
    followUpQuestionJa: '約束に遅れそうなとき、何と連絡しますか？', followUpQuestionZh: '快赴约迟到时怎么联系对方？' }),
  d({ itemId: 'fi-kyoumi', themeJa: '興味があることを話す', themeZh: '聊聊感兴趣的事',
    starterQuestionJa: '最近、何に興味がありますか？', starterQuestionZh: '最近对什么感兴趣？',
    targetExpressions: ['に興味が', '興味を'],
    supportExpressionsJa: ['日本の文化に興味があります', '投資に興味を持ちました', 'あまり興味がありません'],
    supportExpressionsZh: ['对日本文化感兴趣', '对投资产生了兴趣', '不太感兴趣'],
    followUpQuestionJa: '子どものころ、何に興味がありましたか？', followUpQuestionZh: '小时候对什么感兴趣？' }),
  // 「嬉しい」は瞬間の感情、「楽しい」は続く時間。中国語ではどちらも「开心」と訳せてしまうため、
  // zh側を「高兴（その瞬間）」に寄せて fi-tanoshii と混ざらないようにする。
  d({ itemId: 'fi-ureshii', themeJa: '嬉しかったことを話す', themeZh: '聊聊让你高兴的瞬间',
    starterQuestionJa: '最近、嬉しかったことは何ですか？', starterQuestionZh: '最近有什么事让你特别高兴？',
    targetExpressions: ['嬉しい', '嬉しかった', '嬉しくて'],
    supportExpressionsJa: ['ほめられて嬉しかったです', '日本語が通じると嬉しいです', '嬉しくて友達に話しました'],
    supportExpressionsZh: ['被夸奖的时候很高兴', '日语能说通就很高兴', '高兴得告诉了朋友'],
    followUpQuestionJa: 'その時の気持ちは「嬉しい」でしたか、「楽しい」でしたか？',
    followUpQuestionZh: '当时的心情是「嬉しい」还是「楽しい」呢？' }),
  d({ itemId: 'fi-kanashii', themeJa: '悲しい気持ちを話す', themeZh: '聊聊难过的心情',
    starterQuestionJa: '日本で悲しいと感じたことがありますか？', starterQuestionZh: '在日本有过难过的时候吗？',
    targetExpressions: ['悲しい', '悲しかった', '悲しくて'],
    supportExpressionsJa: ['家族と離れて悲しいです', '悲しいニュースを見ました', '悲しいとき音楽を聞きます'],
    supportExpressionsZh: ['和家人分开很难过', '看到了难过的新闻', '难过时听音乐'],
    followUpQuestionJa: '悲しいとき、どうやって元気を出しますか？', followUpQuestionZh: '难过时怎么让自己振作？' }),
  d({ itemId: 'fi-sabishii', themeJa: '寂しさについて話す', themeZh: '聊聊寂寞',
    starterQuestionJa: '一人の生活は寂しいですか？', starterQuestionZh: '一个人生活寂寞吗？',
    targetExpressions: ['寂しい', '寂しく', '寂しさ'],
    supportExpressionsJa: ['ときどき寂しいです', '慣れて寂しくなくなりました', '正月は家族に会えなくて寂しいです'],
    supportExpressionsZh: ['有时会寂寞', '习惯了就不寂寞了', '过年见不到家人很寂寞'],
    followUpQuestionJa: '寂しいとき、だれと話しますか？', followUpQuestionZh: '寂寞的时候和谁聊天？' }),
  d({ itemId: 'fi-hazukashii', themeJa: '恥ずかしかった経験を話す', themeZh: '聊聊尴尬的经历',
    starterQuestionJa: '日本語を間違えて恥ずかしかったことがありますか？', starterQuestionZh: '有没有说错日语觉得尴尬的时候？',
    targetExpressions: ['恥ずかしい', '恥ずかしかった', '恥ずかしくて'],
    supportExpressionsJa: ['間違えて恥ずかしかったです', '人前で話すのは恥ずかしいです', '恥ずかしくて言えませんでした'],
    supportExpressionsZh: ['说错了很尴尬', '在人前说话很害羞', '不好意思没说出口'],
    followUpQuestionJa: '間違いを恐れないために、どう考えたらいいと思いますか？', followUpQuestionZh: '你觉得怎么想才能不怕出错？' }),
  d({ itemId: 'fi-kibishii', themeJa: '厳しさについて話す', themeZh: '聊聊严格',
    starterQuestionJa: '日本の会社は厳しいと思いますか？', starterQuestionZh: '你觉得日本公司严格吗？',
    targetExpressions: ['厳しい', '厳しく', '厳しくて'],
    supportExpressionsJa: ['時間に厳しいです', '上司は厳しいですがやさしいです', '冬の寒さが厳しいです'],
    supportExpressionsZh: ['对时间很严格', '上司严格但人很好', '冬天的寒冷很严酷'],
    followUpQuestionJa: '厳しくてもよかったと思う経験はありますか？', followUpQuestionZh: '有没有虽然严格但觉得值得的经历？' }),
  d({ itemId: 'fi-taihen', themeJa: '大変なことを話す', themeZh: '聊聊辛苦的事',
    starterQuestionJa: '日本の生活で、何がいちばん大変ですか？', starterQuestionZh: '日本生活中什么最辛苦？',
    targetExpressions: ['大変です', '大変でした', '大変で'],
    supportExpressionsJa: ['仕事と勉強の両立が大変です', '引っ越しが大変でした', '大変ですが頑張ります'],
    supportExpressionsZh: ['工作学习兼顾很辛苦', '搬家很辛苦', '虽然辛苦但会努力'],
    followUpQuestionJa: '「大変ですね」と相手に言う練習をしましょう。どんな場面で使いますか？', followUpQuestionZh: '练习对别人说「大変ですね」。什么场合用？' }),
  d({ itemId: 'fi-hitsuyou', themeJa: '必要なものを話す', themeZh: '聊聊需要的东西',
    starterQuestionJa: '日本の生活で、何が必要だと思いますか？', starterQuestionZh: '日本生活需要什么？',
    targetExpressions: ['が必要です', '必要な', '必要ありません'],
    supportExpressionsJa: ['日本語が必要です', '必要な書類を準備します', '心配は必要ありません'],
    supportExpressionsZh: ['需要日语', '准备需要的材料', '不需要担心'],
    followUpQuestionJa: '仕事で必要な日本語は 何だと思いますか？', followUpQuestionZh: '工作需要什么样的日语？' }),
  d({ itemId: 'fi-muri', themeJa: '無理をしないことについて話す', themeZh: '聊聊不要勉强',
    starterQuestionJa: '忙しいとき、無理をしてしまいますか？', starterQuestionZh: '忙的时候会勉强自己吗？',
    targetExpressions: ['無理を', '無理です', '無理しないで'],
    supportExpressionsJa: ['無理をしないでください', '毎日3時間は無理です', '無理せず休みます'],
    supportExpressionsZh: ['请不要勉强', '每天3小时做不到', '不勉强，好好休息'],
    followUpQuestionJa: '「無理しないでね」と友達に言ってみましょう', followUpQuestionZh: '试着对朋友说「無理しないでね」' }),
  d({ itemId: 'fi-fukuzatsu', themeJa: '複雑なことを話す', themeZh: '聊聊复杂的事',
    starterQuestionJa: '日本で、何の手続きが複雑でしたか？', starterQuestionZh: '在日本什么手续最复杂？',
    targetExpressions: ['複雑です', '複雑な', '複雑で'],
    supportExpressionsJa: ['役所の手続きが複雑です', '複雑な気持ちです', '話が複雑で分かりません'],
    supportExpressionsZh: ['政府手续很复杂', '心情复杂', '事情太复杂搞不懂'],
    followUpQuestionJa: '複雑な話を聞くとき、どうやって確認しますか？', followUpQuestionZh: '听复杂的内容时怎么确认？' }),
  d({ itemId: 'fi-jiyuu', themeJa: '自由な時間について話す', themeZh: '聊聊自由时间',
    starterQuestionJa: '自由な時間があったら、何をしたいですか？', starterQuestionZh: '有自由时间的话想做什么？',
    targetExpressions: ['自由な', '自由に', '自由が'],
    supportExpressionsJa: ['自由な時間が欲しいです', '自由に使えるお金', '週末は自由に過ごします'],
    supportExpressionsZh: ['想要自由时间', '可自由支配的钱', '周末自由安排'],
    followUpQuestionJa: 'あなたにとって「自由」とは何ですか？', followUpQuestionZh: '对你来说「自由」是什么？' }),
  d({ itemId: 'fi-tabun', themeJa: '推測して話す', themeZh: '带着推测说话',
    starterQuestionJa: '明日の天気はどうだと思いますか？「たぶん」を使ってみましょう', starterQuestionZh: '你觉得明天天气怎么样？试着用「たぶん」',
    targetExpressions: ['たぶん'],
    supportExpressionsJa: ['たぶん晴れです', 'たぶん大丈夫です', 'たぶん行けると思います'],
    supportExpressionsZh: ['大概是晴天', '应该没问题', '我想大概能去'],
    followUpQuestionJa: '来年も日本にいますか？「たぶん」で答えてみましょう', followUpQuestionZh: '明年还在日本吗？用「たぶん」回答' }),
  d({ itemId: 'fi-kanarazu', themeJa: '必ずすることを話す', themeZh: '聊聊一定会做的事',
    starterQuestionJa: '毎日、必ずすることは何ですか？', starterQuestionZh: '每天一定做的事是什么？',
    targetExpressions: ['必ず'],
    supportExpressionsJa: ['必ず歯を磨きます', '約束は必ず守ります', '帰ったら必ず連絡します'],
    supportExpressionsZh: ['一定刷牙', '一定遵守约定', '回去后一定联系'],
    followUpQuestionJa: '「たぶん」と「必ず」、どう使い分けますか？', followUpQuestionZh: '「たぶん」和「必ず」怎么区分使用？' }),
  d({ itemId: 'fi-saikin', themeJa: '最近のことを話す', themeZh: '聊聊最近的事',
    starterQuestionJa: '最近、どうですか？', starterQuestionZh: '最近怎么样？',
    targetExpressions: ['最近'],
    supportExpressionsJa: ['最近忙しいです', '最近始めたことがあります', '最近のニュースを見ましたか'],
    supportExpressionsZh: ['最近很忙', '最近开始了新的事', '看最近的新闻了吗'],
    followUpQuestionJa: '最近ハマっていることは ありますか？', followUpQuestionZh: '最近迷上什么了吗？' }),
  d({ itemId: 'fi-zenzen', themeJa: '「全然」で程度を話す', themeZh: '用「全然」表达程度',
    starterQuestionJa: 'お酒は飲みますか？飲まない人は「全然」を使ってみましょう', starterQuestionZh: '你喝酒吗？不喝的话试着用「全然」',
    targetExpressions: ['全然'],
    supportExpressionsJa: ['全然飲みません', '全然分かりませんでした', '全然大丈夫です'],
    supportExpressionsZh: ['完全不喝', '完全没听懂', '完全没问题（口语）'],
    followUpQuestionJa: '「全然大丈夫」は口語表現です。どんな場面で聞きましたか？', followUpQuestionZh: '「全然大丈夫」是口语。你在什么场合听到过？' }),
  d({ itemId: 'fi-nakanaka', themeJa: '「なかなか」で話す', themeZh: '用「なかなか」表达',
    starterQuestionJa: 'なかなかできないことがありますか？', starterQuestionZh: '有什么迟迟做不到的事吗？',
    targetExpressions: ['なかなか'],
    supportExpressionsJa: ['なかなか覚えられません', 'なかなか時間がありません', 'この店はなかなかいいです'],
    supportExpressionsZh: ['怎么也记不住', '总是没时间', '这家店相当不错'],
    followUpQuestionJa: '「なかなか＋ない」と「なかなかいい」、両方使ってみましょう', followUpQuestionZh: '试着用「なかなか＋ない」和「なかなかいい」两种' }),
  d({ itemId: 'fi-yatto', themeJa: '「やっと」できたことを話す', themeZh: '聊聊终于做到的事',
    starterQuestionJa: '最近、やっとできたことはありますか？', starterQuestionZh: '最近有什么终于做到的事吗？',
    targetExpressions: ['やっと'],
    supportExpressionsJa: ['やっと慣れました', 'やっと金曜日です', 'やっと言いたいことが言えました'],
    supportExpressionsZh: ['终于习惯了', '终于到周五了', '终于说出了想说的话'],
    followUpQuestionJa: 'やっと達成したい目標は 何ですか？', followUpQuestionZh: '你想最终达成的目标是什么？' }),
  d({ itemId: 'fi-tsumari', themeJa: '「つまり」で言い換える', themeZh: '用「つまり」换个说法',
    starterQuestionJa: 'あなたの仕事を、つまり一言で言うと何ですか？', starterQuestionZh: '你的工作，简单说就是什么？',
    targetExpressions: ['つまり'],
    supportExpressionsJa: ['つまり、お客様をサポートする仕事です', 'つまり、こういうことですか？', 'つまり行けないということです'],
    supportExpressionsZh: ['也就是支持客户的工作', '也就是说，是这么回事吗？', '总之就是去不了'],
    followUpQuestionJa: '相手の話を「つまり〜ですか？」と確認してみましょう', followUpQuestionZh: '试着用「つまり〜ですか？」确认对方的话' }),
  d({ itemId: 'fi-sorede', themeJa: '「それで」で話をつなぐ', themeZh: '用「それで」承接话题',
    starterQuestionJa: '昨日、何かありましたか？「それで」を使って続けてみましょう', starterQuestionZh: '昨天发生了什么？试着用「それで」接下去',
    targetExpressions: ['それで'],
    supportExpressionsJa: ['雨でした。それで、家にいました', 'それで、どうなりましたか？', '疲れました。それで早く寝ました'],
    supportExpressionsZh: ['下雨了。所以待在家', '然后呢，怎么样了？', '累了。所以早早睡了'],
    followUpQuestionJa: '相手に「それで？」と続きを聞いてみましょう', followUpQuestionZh: '试着用「それで？」问对方后续' }),
];
