// 漢字バンク N4 バッチB — 仕事・学校（30字）。
//
// 方針（kanjiTypes.ts の鉄則に従う）:
// - 読み・訳・例語・注記はすべて自社で書き起こした。他ソースの読み・訳・例文を写していない。
// - onyomi / kunyomi は「常用漢字表にある読みのうち、N5/N4段階の学習に必要な主要な読み」だけを載せる。
//   稀用の読み（例: 事の「ズ」、室の「むろ」、発の「ホツ」）は学習者を混乱させるので意図的に載せない。
//   → したがって空配列は「常用の読みが無い」ではなく「この段階で覚える読みが無い」の意味を含む。
// - 画数・部首は1字ずつ確認して書いた。自信の持てない字は入れていない。
// - words は層C語彙バンク（ALL_VOCAB_CONTENT の active_beta）に実在する語を優先し、
//   実在するものは inVocabBank: true、教材上どうしても外せない基本語のみ false で補った
//   （このバッチでは「仕事」「働く」「英会話」「英国」の4語）。
// - chineseNote は中国語母語者にとって一番価値がある欄なので、
//   ①简体字との字形差 ②中国語と意味・語感がずれる点 ③日本語独自の搭配 のどれかを必ず具体的に書く。
import type { KanjiEntry } from './kanjiTypes';

const BATCH_ID = 'n4b';

export const KANJI_N4_B: KanjiEntry[] = [
  {
    entryId: 'kj-n4b-01',
    character: '仕',
    onyomi: ['シ'],
    kunyomi: ['つか・える'],
    meaningZh: '任职、做事；侍奉',
    strokeCount: 5,
    radical: { form: '亻', readingJa: 'にんべん', meaningZh: '与人有关' },
    level: 'N4',
    words: [
      { surface: '仕事', reading: 'しごと', glossZh: '工作；活儿', inVocabBank: false },
      { surface: '仕方', reading: 'しかた', glossZh: '做法；方法', inVocabBank: true },
      { surface: '仕組み', reading: 'しくみ', glossZh: '结构；机制', inVocabBank: true },
    ],
    chineseNote: '中文的「仕」几乎只出现在「仕途」这类书面词里，日常不用；日语却把它当高频字，而且多半不表示"做官"，'
      + '而是构成「仕事」＝工作、「仕方」＝做法。看到「仕」不要按中文语感理解，要整词记。',
    mnemonicZh: '「亻（人）」＋「士（有身份的人）」＝人去任职办事 → 引申出日语最常用的「仕事」。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-02',
    character: '事',
    onyomi: ['ジ'],
    kunyomi: ['こと'],
    meaningZh: '事情、事件',
    strokeCount: 8,
    radical: { form: '亅', readingJa: 'はねぼう', meaningZh: '竖钩，表示钩状竖笔的构件' },
    level: 'N4',
    words: [
      { surface: '用事', reading: 'ようじ', glossZh: '（要办的）事情', inVocabBank: true },
      { surface: '返事', reading: 'へんじ', glossZh: '回答；回信', inVocabBank: true },
      { surface: '食事', reading: 'しょくじ', glossZh: '吃饭；饭菜', inVocabBank: true },
      { surface: '火事', reading: 'かじ', glossZh: '火灾', inVocabBank: true },
    ],
    chineseNote: '字形与中文完全相同，但搭配差很多：「用事」＝要办的私事、「返事」＝回话/回信、「火事」＝火灾、'
      + '「食事」＝吃饭。这些说法中文都没有，照字面直译会说不通。',
    mnemonicZh: '一竖钩从上贯到底，像手举着记事的旗杆；把最上面的一横当作"一件"，记成"一件一件的事"。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-03',
    character: '働',
    onyomi: ['ドウ'],
    kunyomi: ['はたら・く'],
    meaningZh: '劳动、工作',
    strokeCount: 13,
    radical: { form: '亻', readingJa: 'にんべん', meaningZh: '与人有关' },
    level: 'N4',
    words: [
      { surface: '働く', reading: 'はたらく', glossZh: '工作；劳动', inVocabBank: false },
      { surface: '労働', reading: 'ろうどう', glossZh: '劳动', inVocabBank: true },
    ],
    chineseNote: '这是日本自造的汉字（国字），中文里没有这个字，字典里也查不到。'
      + '它的音读「ドウ」是直接借「動」的。务必和「動」分开：「働く」＝工作，「動く」＝移动、运转。',
    mnemonicZh: '「亻（人）」＋「動（动）」＝人在动 → 就是"干活、工作"。日本人在「動」上加了个人旁造出这个字。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-04',
    character: '業',
    onyomi: ['ギョウ'],
    kunyomi: ['わざ'],
    meaningZh: '行业、事业；学业',
    strokeCount: 13,
    radical: { form: '木', readingJa: 'き', meaningZh: '与树木有关' },
    level: 'N4',
    words: [
      { surface: '授業', reading: 'じゅぎょう', glossZh: '课；上课', inVocabBank: true },
      { surface: '卒業', reading: 'そつぎょう', glossZh: '毕业', inVocabBank: true },
      { surface: '残業', reading: 'ざんぎょう', glossZh: '加班', inVocabBank: true },
      { surface: '工業', reading: 'こうぎょう', glossZh: '工业', inVocabBank: true },
    ],
    chineseNote: '简体字是「业」，字形差别极大，日文写法下半是完整的「木」，写的时候常被漏掉。'
      + '词义也别照搬：日语「授業」＝上课（不是"授业"这种文言说法），「残業」＝加班，中文都不这么说。',
    mnemonicZh: '上半像并排挂着工具的木架，下面是「木」＝木匠干的活儿 → 引申为"行业、事业"。'
      + '笔顺是先写上半的横竖，最后写「木」。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-05',
    character: '員',
    onyomi: ['イン'],
    kunyomi: [],
    meaningZh: '（组织中的）成员、人员',
    strokeCount: 10,
    radical: { form: '口', readingJa: 'くち', meaningZh: '与嘴、开口的东西有关' },
    level: 'N4',
    words: [
      { surface: '社員', reading: 'しゃいん', glossZh: '公司职员', inVocabBank: true },
      { surface: '店員', reading: 'てんいん', glossZh: '店员', inVocabBank: true },
      { surface: '全員', reading: 'ぜんいん', glossZh: '全体成员；所有人', inVocabBank: true },
      { surface: '公務員', reading: 'こうむいん', glossZh: '公务员', inVocabBank: true },
    ],
    chineseNote: '简体字是「员」。日文上半是「口」（有三笔的方框），不是「囗（大方框）」，也不是简体的「员」。'
      + '词义上注意：日语「社員」＝公司职员，跟中文"社员（合作社成员）"完全不是一回事。',
    mnemonicZh: '上面「口」＋下面「貝（古代的钱）」＝清点钱和人头 → 组织里在册的"成员"。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-06',
    character: '者',
    onyomi: ['シャ'],
    kunyomi: ['もの'],
    meaningZh: '（做某事的）人',
    strokeCount: 8,
    radical: { form: '耂', readingJa: 'おいかんむり', meaningZh: '与年老的人有关' },
    level: 'N4',
    words: [
      { surface: '医者', reading: 'いしゃ', glossZh: '医生', inVocabBank: true },
      { surface: '学者', reading: 'がくしゃ', glossZh: '学者', inVocabBank: true },
      { surface: '記者', reading: 'きしゃ', glossZh: '记者', inVocabBank: true },
      { surface: '歯医者', reading: 'はいしゃ', glossZh: '牙医；牙科诊所', inVocabBank: true },
    ],
    chineseNote: '日本新字体不带那一点，写成「者」，与中文简体同形（日本旧字体有点，古书上能看到）。'
      + '读音要分工记：构词时读「シャ」，单独当名词读「もの」，而「もの」语气生硬、多用于书面，'
      + '日常说人还是用「人（ひと）」。',
    mnemonicZh: '「耂（老字头）」＋「日」，本义与烧煮有关，后来固定表示"做某事的人" → 「医者」「学者」「記者」。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-07',
    character: '部',
    onyomi: ['ブ'],
    kunyomi: [],
    meaningZh: '部分；部门',
    strokeCount: 11,
    radical: { form: '阝', readingJa: 'おおざと', meaningZh: '在字的右边，与城邑、地区有关' },
    level: 'N4',
    words: [
      { surface: '部屋', reading: 'へや', glossZh: '房间', inVocabBank: true },
      { surface: '全部', reading: 'ぜんぶ', glossZh: '全部', inVocabBank: true },
      { surface: '部長', reading: 'ぶちょう', glossZh: '部长（部门负责人）', inVocabBank: true },
      { surface: '部分', reading: 'ぶぶん', glossZh: '部分', inVocabBank: true },
    ],
    chineseNote: '字形与中文相同，意思也接近。最需要注意的是「部屋（へや）」：这里的「部」读「へ」，'
      + '是日语特有的读法，不能按音读「ブ」去拼成「ぶおく」。这是初学者最常读错的词之一。',
    mnemonicZh: '左边「咅」表音，右边「阝」是"邑"变来的右耳旁＝城镇地区 → 划分出来的"区块、部门"。'
      + '右耳旁一律表示地方，左耳旁（阜）表示土坡。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-08',
    character: '課',
    onyomi: ['カ'],
    kunyomi: [],
    meaningZh: '科室；（教科书的）一课；分派任务',
    strokeCount: 15,
    radical: { form: '言', readingJa: 'ごんべん', meaningZh: '与语言、说话有关' },
    level: 'N4',
    words: [
      { surface: '課長', reading: 'かちょう', glossZh: '科长', inVocabBank: true },
      { surface: '課題', reading: 'かだい', glossZh: '待解决的问题；课题', inVocabBank: true },
      { surface: '課', reading: 'か', glossZh: '（教科书的）课', inVocabBank: true },
    ],
    chineseNote: '简体字是「课」。中文的「课」基本只指课程，日语的「課」除此之外更常指公司里的"科室"：'
      + '「課長」＝科长，级别在「部長」之下。看到日本公司名片上的「課」，想的应该是部门而不是上课。',
    mnemonicZh: '「言（说话）」＋「果（结果）」＝用言语考核成果 → 分派任务、考核；再引申为教科书的"一课"。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-09',
    character: '室',
    onyomi: ['シツ'],
    kunyomi: [],
    meaningZh: '房间、屋子',
    strokeCount: 9,
    radical: { form: '宀', readingJa: 'うかんむり', meaningZh: '与房屋有关' },
    level: 'N4',
    words: [
      { surface: '教室', reading: 'きょうしつ', glossZh: '教室', inVocabBank: true },
      { surface: '会議室', reading: 'かいぎしつ', glossZh: '会议室', inVocabBank: true },
      { surface: '研究室', reading: 'けんきゅうしつ', glossZh: '研究室', inVocabBank: true },
    ],
    chineseNote: '字形和意思都与中文一致，是很好记的字。日语里它几乎只作词尾表示房间，'
      + '而且读音固定为「シツ」，不会变成浊音，例如「教室」「会議室」「研究室」都是「〜しつ」。',
    mnemonicZh: '「宀（宝盖＝房子）」＋「至（到达）」＝人走进去落脚的地方 → 房间。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-10',
    character: '工',
    onyomi: ['コウ', 'ク'],
    kunyomi: [],
    meaningZh: '工程、工匠；手工',
    strokeCount: 3,
    radical: { form: '工', readingJa: 'たくみ', meaningZh: '与工匠、工具有关' },
    level: 'N4',
    words: [
      { surface: '工業', reading: 'こうぎょう', glossZh: '工业', inVocabBank: true },
      { surface: '工場', reading: 'こうじょう', glossZh: '工厂', inVocabBank: true },
      { surface: '工夫', reading: 'くふう', glossZh: '想办法；下功夫改进', inVocabBank: true },
    ],
    chineseNote: '字形与中文相同，但日语有两个音读，这是中文母语者最容易读错的地方：'
      + '一般读「コウ」（「工業」「工場」），少数词读「ク」（「工夫（くふう）」＝想办法）。'
      + '看到「工夫」千万别读成「こうふ」。',
    mnemonicZh: '像木匠用的曲尺（角尺）的形状 → 工具、工程。只有三画，也是「空」「左」「江」等字的部件。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-11',
    character: '用',
    onyomi: ['ヨウ'],
    kunyomi: ['もち・いる'],
    meaningZh: '使用；要办的事',
    strokeCount: 5,
    radical: { form: '用', readingJa: 'もちいる', meaningZh: '自身就是部首，表示使用' },
    level: 'N4',
    words: [
      { surface: '用事', reading: 'ようじ', glossZh: '（要办的）事情', inVocabBank: true },
      { surface: '用意', reading: 'ようい', glossZh: '备好（需要的东西）', inVocabBank: true },
      { surface: '利用', reading: 'りよう', glossZh: '利用；使用（设施、服务）', inVocabBank: true },
      { surface: '使用', reading: 'しよう', glossZh: '使用（正式说法）', inVocabBank: true },
    ],
    chineseNote: '字形与中文相同，但两个高频搭配中文没有，必须单独记：'
      + '「用事がある」＝有事要办（不是"有用"），「用意する」＝准备好。'
      + '另外训读「用いる」是书面语，日常口语用「使う」。',
    mnemonicZh: '像一个能盛东西的桶从侧面看的样子 → 派上用场、使用。中间那一竖要贯通到底。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-12',
    character: '品',
    onyomi: ['ヒン'],
    kunyomi: ['しな'],
    meaningZh: '物品；品质、格调',
    strokeCount: 9,
    radical: { form: '口', readingJa: 'くち', meaningZh: '与嘴、开口的东西有关' },
    level: 'N4',
    words: [
      { surface: '商品', reading: 'しょうひん', glossZh: '商品', inVocabBank: true },
      { surface: '作品', reading: 'さくひん', glossZh: '作品', inVocabBank: true },
      { surface: '食品', reading: 'しょくひん', glossZh: '食品', inVocabBank: true },
      { surface: '品物', reading: 'しなもの', glossZh: '东西；商品', inVocabBank: true },
    ],
    chineseNote: '字形与中文相同，意思也接近。要记的是读音分工非常整齐：'
      + '汉语词里读音读「ヒン」（「商品」「作品」「食品」），和训读词搭配时读「しな」（「品物」）。'
      + '掌握这条规律，这个字基本不会读错。',
    mnemonicZh: '三个「口」摞在一起，像摆放着的许多器物 → 物品；再引申为品级、品质。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-13',
    character: '計',
    onyomi: ['ケイ'],
    kunyomi: ['はか・る'],
    meaningZh: '计算、测量；计划',
    strokeCount: 9,
    radical: { form: '言', readingJa: 'ごんべん', meaningZh: '与语言、说话有关' },
    level: 'N4',
    words: [
      { surface: '時計', reading: 'とけい', glossZh: '钟；表', inVocabBank: true },
      { surface: '計画', reading: 'けいかく', glossZh: '计划', inVocabBank: true },
      { surface: '計算', reading: 'けいさん', glossZh: '计算', inVocabBank: true },
      { surface: '合計', reading: 'ごうけい', glossZh: '合计；总共', inVocabBank: true },
    ],
    chineseNote: '简体字是「计」。最需要单独记的是「時計（とけい）」＝钟表：'
      + '中文不会用"计"来称呼钟表，而且这个词的读音是特例，不能按「じけい」去拼。',
    mnemonicZh: '「言（说）」＋「十（数目）」＝用言语数数 → 计算、计量，再引申为事先算好的"计划"。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-14',
    character: '図',
    onyomi: ['ズ', 'ト'],
    kunyomi: ['はか・る'],
    meaningZh: '图、图表；谋划',
    strokeCount: 7,
    radical: { form: '囗', readingJa: 'くにがまえ', meaningZh: '与围起来的范围有关' },
    level: 'N4',
    words: [
      { surface: '図書館', reading: 'としょかん', glossZh: '图书馆', inVocabBank: true },
      { surface: '地図', reading: 'ちず', glossZh: '地图', inVocabBank: true },
      { surface: '合図', reading: 'あいず', glossZh: '信号；示意', inVocabBank: true },
      { surface: '図', reading: 'ず', glossZh: '图；图表', inVocabBank: true },
    ],
    chineseNote: '这个字必须单独记字形：中文繁体是「圖」、简体是「图」，日本新字体写成「図」，'
      + '框里上面是两小笔（像「丷」）、下面是一个「メ」，连外框一共七画，三种写法互不相同。'
      + '读音也有两个：一般读「ズ」（「地図」「合図」），'
      + '但「図書」「図書館」读「ト」。',
    mnemonicZh: '外面「囗」是围起来的范围，里面是画上去的记号 → 在框里画出来的东西＝图。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-15',
    character: '発',
    onyomi: ['ハツ'],
    kunyomi: [],
    meaningZh: '出发；发出、开始',
    strokeCount: 9,
    radical: { form: '癶', readingJa: 'はつがしら', meaningZh: '表示两只脚向外张开、迈步' },
    level: 'N4',
    words: [
      { surface: '発表', reading: 'はっぴょう', glossZh: '发表；公布', inVocabBank: true },
      { surface: '出発', reading: 'しゅっぱつ', glossZh: '出发', inVocabBank: true },
      { surface: '発音', reading: 'はつおん', glossZh: '发音', inVocabBank: true },
      { surface: '発見', reading: 'はっけん', glossZh: '发现', inVocabBank: true },
    ],
    chineseNote: '中文繁体是「發」、简体是「发」，日本新字体「発」又是第三种写法，上半必须写成「癶」。'
      + '还有一点：简体「发」同时对应「發」和「髪（头发）」两个字，但日语的「発」只对应「發」，'
      + '头发要写「髪（かみ）」，不能混。',
    mnemonicZh: '上面的「癶」是两只脚向外张开、正要迈出去的样子 → 出发、发出。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-16',
    character: '表',
    onyomi: ['ヒョウ'],
    kunyomi: ['おもて', 'あらわ・す', 'あらわ・れる'],
    meaningZh: '表面、正面；表格；表达出来',
    strokeCount: 8,
    radical: { form: '衣', readingJa: 'ころも', meaningZh: '与衣服有关' },
    level: 'N4',
    words: [
      { surface: '発表', reading: 'はっぴょう', glossZh: '发表；公布', inVocabBank: true },
      { surface: '表', reading: 'ひょう', glossZh: '表格', inVocabBank: true },
      { surface: '代表', reading: 'だいひょう', glossZh: '代表', inVocabBank: true },
      { surface: '表す', reading: 'あらわす', glossZh: '表示；表达出来', inVocabBank: true },
    ],
    chineseNote: '字形与中文相同，但日语的义项和读音都比中文多，必须连词记：'
      + '读「ひょう」时是"表格"，读「おもて」时是"正面、外面"（与「裏（うら）＝背面」相对），'
      + '读「あらわす」时是"表达出来"。同一个字换个读音意思就变了。',
    mnemonicZh: '上半是「主」形，下半是「衣」＝穿在外面的那层衣服 → 外表、表面。部首取「衣」。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-17',
    character: '集',
    onyomi: ['シュウ'],
    kunyomi: ['あつ・まる', 'あつ・める'],
    meaningZh: '聚集、收集',
    strokeCount: 12,
    radical: { form: '隹', readingJa: 'ふるとり', meaningZh: '与鸟有关（短尾的鸟）' },
    level: 'N4',
    words: [
      { surface: '集める', reading: 'あつめる', glossZh: '把…收集起来', inVocabBank: true },
      { surface: '集まる', reading: 'あつまる', glossZh: '（人或物）聚到一起', inVocabBank: true },
      { surface: '集中', reading: 'しゅうちゅう', glossZh: '集中（注意力）', inVocabBank: true },
      { surface: '集まり', reading: 'あつまり', glossZh: '聚会；集合', inVocabBank: true },
    ],
    chineseNote: '字形与中文相同，难点在日语区分自动词和他动词，中文一个"集合/收集"就全包了：'
      + '「集まる」＝（人自己）聚过来，「集める」＝（有人）把东西收集起来。'
      + '说「学生が集まる」不能说成「学生を集まる」。',
    mnemonicZh: '上面「隹（短尾鸟）」＋下面「木」＝鸟停满了树 → 聚集。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-18',
    character: '意',
    onyomi: ['イ'],
    kunyomi: [],
    meaningZh: '心意、想法；意思',
    strokeCount: 13,
    radical: { form: '心', readingJa: 'こころ', meaningZh: '与心理、感情有关' },
    level: 'N4',
    words: [
      { surface: '意味', reading: 'いみ', glossZh: '意思；意义', inVocabBank: true },
      { surface: '注意', reading: 'ちゅうい', glossZh: '注意；提醒', inVocabBank: true },
      { surface: '用意', reading: 'ようい', glossZh: '备好（需要的东西）', inVocabBank: true },
      { surface: '意外', reading: 'いがい', glossZh: '意外的；没想到的', inVocabBank: true },
    ],
    chineseNote: '字形与中文相同，但组词后语感有出入：日语「意味」就是普通的"意思、含义"，'
      + '而中文的"意味"多带"暗示、含有某种意味"的味道，用法窄得多。'
      + '另外「用意」＝准备，跟中文的"用意（居心）"完全是两回事。',
    mnemonicZh: '上面「音（声音）」＋下面「心」＝心里发出的声音 → 心意、想法、意思。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-19',
    character: '教',
    onyomi: ['キョウ'],
    kunyomi: ['おし・える', 'おそ・わる'],
    meaningZh: '教导、教授',
    strokeCount: 11,
    radical: { form: '攵', readingJa: 'のぶん', meaningZh: '与手持棍棒的动作（敲打、促使）有关' },
    level: 'N4',
    words: [
      { surface: '教える', reading: 'おしえる', glossZh: '教；告诉', inVocabBank: true },
      { surface: '教室', reading: 'きょうしつ', glossZh: '教室', inVocabBank: true },
      { surface: '教育', reading: 'きょういく', glossZh: '教育', inVocabBank: true },
      { surface: '教科書', reading: 'きょうかしょ', glossZh: '教科书；课本', inVocabBank: true },
    ],
    chineseNote: '字形与中文相同，但日语有一对读音要成对记，中文没有这种对立：'
      + '「教える」＝我教别人，「教わる」＝我跟别人学（受教的一方）。'
      + '「先生に教わる」＝跟老师学，说成「先生に教える」意思就反了。',
    mnemonicZh: '左边是「孝」的变形（孩子在学），右边「攵」是手拿教鞭的样子 → 教导。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-20',
    character: '育',
    onyomi: ['イク'],
    kunyomi: ['そだ・つ', 'そだ・てる'],
    meaningZh: '养育、培养；成长',
    strokeCount: 8,
    radical: { form: '月', readingJa: 'にくづき', meaningZh: '与身体、血肉有关' },
    level: 'N4',
    words: [
      { surface: '教育', reading: 'きょういく', glossZh: '教育', inVocabBank: true },
      { surface: '体育', reading: 'たいいく', glossZh: '体育（课）', inVocabBank: true },
      { surface: '育つ', reading: 'そだつ', glossZh: '（自然地）成长、长大', inVocabBank: true },
      { surface: '育てる', reading: 'そだてる', glossZh: '养育；培养', inVocabBank: true },
    ],
    chineseNote: '字形与中文相同，「教育」「体育」的意思也一样，比较好上手。'
      + '要注意的是自他成对：「育つ」＝自己长大（无人施力），「育てる」＝把…养大（有人施力）。'
      + '另外这里的「月」是"肉月"，与月亮无关。',
    mnemonicZh: '上半是倒过来的「子」（婴儿头朝下出生的样子），下面是肉月 → 婴儿长出血肉＝养育、成长。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-21',
    character: '英',
    onyomi: ['エイ'],
    kunyomi: [],
    meaningZh: '出众、精华；英国（音译用字）',
    strokeCount: 8,
    radical: { form: '艹', readingJa: 'くさかんむり', meaningZh: '与草、植物有关' },
    level: 'N4',
    words: [
      { surface: '英語', reading: 'えいご', glossZh: '英语', inVocabBank: true },
      { surface: '英会話', reading: 'えいかいわ', glossZh: '英语会话（课）', inVocabBank: false },
      { surface: '英国', reading: 'えいこく', glossZh: '英国', inVocabBank: false },
    ],
    chineseNote: '字形与中文相同，但使用范围窄得多：日语里它几乎只出现在与英国、英语有关的词上。'
      + '中文常用的"英雄""精英""英俊"在日语中很少见，不要拿中文的语感去类推造词。',
    mnemonicZh: '「艹（草字头）」＋「央（中央）」＝花草里最居中、最出挑的那一株 → 出众、精华；'
      + '后来被借去音译「英国」。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-22',
    character: '研',
    onyomi: ['ケン'],
    kunyomi: ['と・ぐ'],
    meaningZh: '研磨；钻研',
    strokeCount: 9,
    radical: { form: '石', readingJa: 'いしへん', meaningZh: '与石头有关' },
    level: 'N4',
    words: [
      { surface: '研究', reading: 'けんきゅう', glossZh: '研究', inVocabBank: true },
      { surface: '研究室', reading: 'けんきゅうしつ', glossZh: '研究室', inVocabBank: true },
      { surface: '研修', reading: 'けんしゅう', glossZh: '进修；岗前培训', inVocabBank: true },
    ],
    chineseNote: '字形与中文简体相同，「研究」的意思也一样。'
      + '不同的是训读「研ぐ（とぐ）」＝磨（刀）、淘（米），中文的"研"没有这两个用法，'
      + '日本人做饭时说的「米を研ぐ」就是淘米。',
    mnemonicZh: '「石」＋「幵（平齐）」＝把石头磨平磨齐 → 研磨；引申为反复琢磨＝钻研、研究。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-23',
    character: '究',
    onyomi: ['キュウ'],
    kunyomi: ['きわ・める'],
    meaningZh: '追究到底、探究',
    strokeCount: 7,
    radical: { form: '穴', readingJa: 'あなかんむり', meaningZh: '与洞穴、孔有关' },
    level: 'N4',
    words: [
      { surface: '研究', reading: 'けんきゅう', glossZh: '研究', inVocabBank: true },
      { surface: '研究室', reading: 'けんきゅうしつ', glossZh: '研究室', inVocabBank: true },
    ],
    chineseNote: '字形与中文相同。日语里这个字基本只出现在「研究」及其派生词中，'
      + '中文那种"究竟""追究责任"的说法日语不用「究」，而说「一体（いったい）」「責任を問う」。'
      + '训读「究める」属于书面语，日常几乎不出现。',
    mnemonicZh: '「穴（洞）」＋「九（数到头的数字）」＝把洞探到最深处 → 追究到底。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-24',
    character: '試',
    onyomi: ['シ'],
    kunyomi: ['ため・す', 'こころ・みる'],
    meaningZh: '尝试；测验',
    strokeCount: 13,
    radical: { form: '言', readingJa: 'ごんべん', meaningZh: '与语言、说话有关' },
    level: 'N4',
    words: [
      { surface: '試験', reading: 'しけん', glossZh: '考试', inVocabBank: true },
      { surface: '試合', reading: 'しあい', glossZh: '比赛（分胜负的）', inVocabBank: true },
      { surface: '試す', reading: 'ためす', glossZh: '试；尝试做', inVocabBank: true },
    ],
    chineseNote: '简体字是「试」。这个字最大的坑是词义：日语「試験」＝考试，'
      + '而中文的"试验"是做实验（日语要说「実験」）。二者写法接近、意思不同，很容易搞混。'
      + '另外「試合（しあい）」＝比赛，中文也没有这个词。',
    mnemonicZh: '「言」＋「式（一定的做法）」＝按既定方式用言语检验 → 尝试、测验。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-25',
    character: '験',
    onyomi: ['ケン'],
    kunyomi: [],
    meaningZh: '检验、查验',
    strokeCount: 18,
    radical: { form: '馬', readingJa: 'うまへん', meaningZh: '与马有关' },
    level: 'N4',
    words: [
      { surface: '試験', reading: 'しけん', glossZh: '考试', inVocabBank: true },
      { surface: '実験', reading: 'じっけん', glossZh: '实验', inVocabBank: true },
      { surface: '受験', reading: 'じゅけん', glossZh: '参加考试；报考', inVocabBank: true },
    ],
    chineseNote: '中文繁体是「驗」、简体是「验」，日本新字体写成「験」，右半的写法与两者都不同，要单独看清楚。'
      + '而且日语的「馬」旁保留四点底，简体「验」左边已经变成「马」，笔画差很多。'
      + '常用词只有「試験」「実験」「受験」几个，记住这几个基本够用。',
    mnemonicZh: '「馬」＋右边表示查验的部件＝古时查看马的成色好坏 → 检验、验证。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-26',
    character: '練',
    onyomi: ['レン'],
    kunyomi: ['ね・る'],
    meaningZh: '练习、反复做熟；锤炼',
    strokeCount: 14,
    radical: { form: '糸', readingJa: 'いとへん', meaningZh: '与丝线、纺织有关' },
    level: 'N4',
    words: [
      { surface: '練習', reading: 'れんしゅう', glossZh: '练习', inVocabBank: true },
      { surface: '訓練', reading: 'くんれん', glossZh: '训练', inVocabBank: true },
    ],
    chineseNote: '简体字是「练」，日文保留完整的绞丝旁「糸」，右半写「東」。'
      + '「練習」「訓練」的意思与中文一致，但训读「練る（ねる）」＝揉（面团）、推敲（方案），'
      + '中文的"练"没有这两个意思，「計画を練る」＝仔细推敲计划。',
    mnemonicZh: '「糸（丝线）」＋「東」＝把生丝反复煮、反复捶打成熟丝 → 反复做直到熟练。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-27',
    character: '習',
    onyomi: ['シュウ'],
    kunyomi: ['なら・う'],
    meaningZh: '学习、反复练熟；习惯',
    strokeCount: 11,
    radical: { form: '羽', readingJa: 'はね', meaningZh: '与羽毛、翅膀有关' },
    level: 'N4',
    words: [
      { surface: '練習', reading: 'れんしゅう', glossZh: '练习', inVocabBank: true },
      { surface: '習う', reading: 'ならう', glossZh: '学；跟人学', inVocabBank: true },
      { surface: '復習', reading: 'ふくしゅう', glossZh: '复习', inVocabBank: true },
      { surface: '予習', reading: 'よしゅう', glossZh: '预习', inVocabBank: true },
    ],
    chineseNote: '简体字是「习」，只有三画；日文的「習」上面是完整的「羽」（由两个「习」并排组成），共十一画，差别极大，'
      + '必须重新记字形。用法上也有区分：「習う」＝有人教着学（跟老师、师傅学），'
      + '「学ぶ」＝自己学、学问上的学，中文都说"学"，容易混。',
    mnemonicZh: '上面「羽（翅膀）」＋下面「白」（原本是「自」）＝雏鸟一次次扇翅膀学飞 → 反复练习。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-28',
    character: '質',
    onyomi: ['シツ'],
    kunyomi: [],
    meaningZh: '性质、品质；本质',
    strokeCount: 15,
    radical: { form: '貝', readingJa: 'かい', meaningZh: '与钱财、财物有关' },
    level: 'N4',
    words: [
      { surface: '質問', reading: 'しつもん', glossZh: '提问；问题', inVocabBank: true },
      { surface: '性質', reading: 'せいしつ', glossZh: '性质；性情', inVocabBank: true },
      { surface: '品質', reading: 'ひんしつ', glossZh: '质量', inVocabBank: true },
    ],
    chineseNote: '简体字是「质」，日文保留上面两个「斤」和下面完整的「貝」。'
      + '词义上有一个必须注意的差别：日语「質問」是中性的"提问"，学生上课举手就用它；'
      + '而中文的"质问"是责问、语气强硬。按中文语感理解会觉得日本人说话很冲。',
    mnemonicZh: '上面两个「斤（斧头）」＋下面「貝（钱财）」＝用斧头去衡量财物的成色 → 本质、品质。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-29',
    character: '問',
    onyomi: ['モン'],
    kunyomi: ['と・う', 'と・い'],
    meaningZh: '询问；问题',
    strokeCount: 11,
    radical: { form: '口', readingJa: 'くち', meaningZh: '与嘴、开口的东西有关' },
    level: 'N4',
    words: [
      { surface: '質問', reading: 'しつもん', glossZh: '提问；问题', inVocabBank: true },
      { surface: '問い', reading: 'とい', glossZh: '问题；提问', inVocabBank: true },
      { surface: '学問', reading: 'がくもん', glossZh: '学问；做学问', inVocabBank: true },
      { surface: '問う', reading: 'とう', glossZh: '询问；追究（责任）', inVocabBank: true },
    ],
    chineseNote: '简体字是「问」，日文外框是完整的「門」。'
      + '用法上要注意：日常口语里"问"用「聞く（きく）」，「問う」是书面、正式的说法，'
      + '常见于「責任を問う」＝追究责任。跟人提问一般说「質問する」。',
    mnemonicZh: '外框「門」＋里面「口」＝站在门口开口打听 → 询问。'
      + '部首取里面的「口」而不是外框，因为表意的是"开口问"。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
  {
    entryId: 'kj-n4b-30',
    character: '答',
    onyomi: ['トウ'],
    kunyomi: ['こた・える', 'こた・え'],
    meaningZh: '回答；答案',
    strokeCount: 12,
    radical: { form: '竹', readingJa: 'たけかんむり', meaningZh: '与竹子、竹制品有关' },
    level: 'N4',
    words: [
      { surface: '答える', reading: 'こたえる', glossZh: '回答', inVocabBank: true },
      { surface: '答え', reading: 'こたえ', glossZh: '回答；答案', inVocabBank: true },
      { surface: '答案', reading: 'とうあん', glossZh: '答卷（写着答案的纸）', inVocabBank: true },
    ],
    chineseNote: '字形与中文相同。要注意两点：助词用「に」，说「質問に答える」，不说「を」；'
      + '还有一个同音词「応える（こたえる）」＝回应期待、见效，写法不同、意思不同，听写时容易写错。',
    mnemonicZh: '「竹（竹字头）」＋「合（相合）」＝古人把回信写在竹简上，内容要与来信相合 → 回答。',
    state: 'active_beta',
    reviewNotes: [],
    batchId: BATCH_ID,
  },
];
