/**
 * 教材の穴を埋める文法項目（2026-09-10 Phase 2-2）。
 *
 * 【どこから来たか】
 * Phase 1 で「関連（similarPatterns）として参照されているのに、項目が無い」表現が265出た。
 * Alias層で仕分けたら、書き方の違い（alias 43・partial 59・ambiguous 19・non-item 5）を除いて
 * **本当に無いものは139**。そのうち、複数の項目から参照されている、または
 * JLPTの標準的な文法項目として成立するものだけをここに足す。
 * **265件を265教材にはしない。** 1回しか参照されず、文法項目でもない語句（〜場面を・つまり）は足さない。
 *
 * 【構造は既存と同じ】
 * N3 ドラフトの27フィールド（Phase 1 で正準と決めたもの）をそのまま使う。
 * 別の形を作ると、出題・復習・会話への接続を全部作り直すことになる。
 *
 * 【学習者には出さない（まだ）】
 * この配列は N3_GRAMMAR_DRAFTS へ**連結しない**。出題プール（advContent）は
 * N3_GRAMMAR_DRAFTS を読むので、ここに置いたものは学習者の画面に出ない。
 * 知識グラフと Alias 索引だけがこれを読む＝「関連」として辿れるようにはなるが、
 * 問題として出るのは人が中身を確認してからにする（大量生成した教材を即公開しない）。
 *
 * 【IDの形】
 * 綴り式（n3g-nitsurete）。knowledgeId が読める形で、既存の番号式（n2g-001）とは衝突しない。
 * N2 相当の項目も綴り式にする＝ n2GrammarIndex の178件（番号式）を1件も動かさない。
 *
 * 【語彙リンク】
 * 実在する fi- のIDだけを使う（無いIDへ繋ぐと dangling になる。QAで検出される）。
 */

import type { GrammarRegister } from '../n3GrammarDrafts';

export interface GrammarGapDraft {
  grammarId: string;
  /** Phase 1 の未解決一覧への追跡（どの表示文字列から来たか） */
  sourceRowId: string;
  pattern: string;
  reading: string;
  level: 'N3' | 'N2';
  meaningJa: string;
  explanationZh: string;
  formation: string;
  usageScene: string;
  nuance: string;
  register: GrammarRegister;
  examplesJa: string[];
  examplesZh: string[];
  furigana: string;
  commonMistakesZh: string;
  learnerFocus: string;
  similarPatterns: string[];
  contrast: string;
  recognition: { promptZh: string; options: string[]; answerIndex: number; distractorReason: string; explanationZh: string };
  production: { promptJa: string; promptZh: string; expected: string[]; acceptable: string[] };
  practice: { themeJa: string; starterJa: string; starterZh: string; targetUse: string };
  matchKeys?: string[];
  vocabularyLinks: string[];
  reviewKey: string;
  route: 'gap-grammar';
  unit: string;
  reviewStatus: 'draft';
  humanReviewed: false;
  approved: false;
}

const g = (
  p: Omit<GrammarGapDraft, 'route' | 'reviewStatus' | 'humanReviewed' | 'approved' | 'reviewKey'>,
): GrammarGapDraft => ({ route: 'gap-grammar', reviewStatus: 'draft', humanReviewed: false, approved: false, reviewKey: p.grammarId, ...p });

export const GRAMMAR_GAP_DRAFTS: GrammarGapDraft[] = [
  g({ grammarId: 'n3g-nitsurete', sourceRowId: 'gap:〜につれて', pattern: '〜につれて', reading: 'につれて', level: 'N3',
    meaningJa: '一方が変わると、それに合わせてもう一方も変わる', explanationZh: '随着…。前项变化，后项也跟着一起变化。前后都是「变化」',
    formation: '動詞辞書形／名詞 ＋につれて', usageScene: '说明气温、年龄、时间等的变化带来的另一种变化',
    nuance: '后项多为自然发生的变化，不用于说话人的意志（×につれて、〜しましょう）', register: 'both',
    examplesJa: ['年を取るにつれて、早起きになった。', '春が近づくにつれて、日が長くなる。'],
    examplesZh: ['随着年龄增长，起得越来越早了。', '随着春天临近，白天越来越长。'],
    furigana: 'としを とるにつれて、はやおきに なった。',
    commonMistakesZh: '后项不能是意志・命令（×につれて頑張ろう）。要用「〜ば〜ほど」表达「越…越…」时也可以',
    learnerFocus: '「随着」不要直接翻成「〜と一緒に」。「につれて」强调两边都在变化',
    similarPatterns: ['〜にしたがって', '〜ば〜ほど', '〜とともに'],
    contrast: '「につれて」＝伴随变化（自然）；「ば〜ほど」＝程度成比例；「とともに」＝书面、可用于意志',
    recognition: { promptZh: '哪一句用「につれて」自然？', options: ['年を取るにつれて、体力が落ちてきた', '駅に着くにつれて、電話してください', '雨が降るにつれて、傘を買った', '朝になるにつれて、起きます'],
      answerIndex: 0, distractorReason: '后项必须是随之发生的「变化」，不能是意志・命令・单次动作', explanationZh: '「につれて」=随着…，前后都是变化' },
    production: { promptJa: '日本に来てから変わったことを「〜につれて」で言ってください。', promptZh: '用「〜につれて」说来日本后随着时间发生的变化。', expected: ['につれて'], acceptable: ['〜につれて'] },
    practice: { themeJa: '時間とともに変わったこと', starterJa: '日本の生活に慣れるにつれて、何が変わりましたか？', starterZh: '随着习惯日本的生活，有什么变了？', targetUse: '〜につれて' },
    vocabularyLinks: ['fi-kawaru', 'fi-fueru'], unit: 'gap-unit-change' }),

  g({ grammarId: 'n3g-dakedenaku', sourceRowId: 'gap:〜だけでなく', pattern: '〜だけでなく', reading: 'だけでなく', level: 'N3',
    meaningJa: '〜だけではなく、さらに…も', explanationZh: '不只…，还…。在已有的基础上再追加一项',
    formation: '名詞／動詞普通形／い形容詞／な形容詞＋な ＋だけでなく', usageScene: '介绍某人的优点、某地的好处时，强调「不止这一点」',
    nuance: '口语・书面都可以。后项常带「も」呼应。比「ばかりでなく」更日常', register: 'both',
    examplesJa: ['彼は英語だけでなく、中国語も話せる。', 'この店は安いだけでなく、味もいい。'],
    examplesZh: ['他不只会英语，中文也会说。', '这家店不只便宜，味道也好。'],
    furigana: 'かれは えいごだけでなく、ちゅうごくごも はなせる。',
    commonMistakesZh: '后项漏掉「も」（×中国語話せる）。「だけじゃなくて」是口语形',
    learnerFocus: '「不仅…而且…」的日常说法。写作可换成「〜ばかりでなく」',
    similarPatterns: ['〜ばかりでなく', '〜に限らず', '〜はもちろん'],
    contrast: '「だけでなく」＝日常；「ばかりでなく」＝书面正式；「はもちろん」＝前项理所当然',
    recognition: { promptZh: '「安いだけでなく、味もいい」的意思是？', options: ['不只便宜，味道也好', '虽然便宜但味道不好', '只是便宜而已', '因为便宜所以好吃'],
      answerIndex: 0, distractorReason: '「だけでなく…も」＝在前项之上再追加', explanationZh: '「〜だけでなく〜も」= 不只…还…' },
    production: { promptJa: '自分のいいところを2つ、「〜だけでなく〜も」で言ってください。', promptZh: '用「〜だけでなく〜も」说自己的两个优点。', expected: ['だけでなく'], acceptable: ['だけじゃなく'] },
    practice: { themeJa: '好きな店・場所を2つの点でほめる', starterJa: 'よく行く店の、いいところを2つ教えてください。', starterZh: '说说你常去的店的两个优点。', targetUse: '〜だけでなく〜も' },
    vocabularyLinks: ['fi-takai'], unit: 'gap-unit-addition' }),

  g({ grammarId: 'n3g-sae', sourceRowId: 'gap:〜さえ', pattern: '〜さえ', reading: 'さえ', level: 'N3',
    meaningJa: '極端な例をあげて「それでも」「それすら」と言う', explanationZh: '连…都…。举一个极端的例子，说明程度',
    formation: '名詞（＋助詞）＋さえ', usageScene: '强调「连最基本的都不行」或「连最难的都行」',
    nuance: '多用于负面（连…都不…）。「〜さえ〜ば」是另一个用法（只要…就…）', register: 'both',
    examplesJa: ['忙しくて、ご飯を食べる時間さえない。', '子どもでさえ知っていることだ。'],
    examplesZh: ['忙得连吃饭的时间都没有。', '这是连小孩都知道的事。'],
    furigana: 'いそがしくて、ごはんを たべる じかんさえ ない。',
    commonMistakesZh: '「さえ」和「まで」都可译成「连」，但「まで」偏「甚至（追加）」，「さえ」偏「连最基本的」',
    learnerFocus: '「さえ」后面多接否定或负面。表达「连…都会」的正面时更常用「でも」',
    similarPatterns: ['〜すら', '〜まで', '〜でも'],
    contrast: '「さえ」＝极端例＋多否定；「すら」＝更书面；「まで」＝范围扩大到意外的程度',
    recognition: { promptZh: '「時間さえない」表达的是？', options: ['连时间都没有（极端地忙）', '只有时间', '有一点时间', '时间够用'],
      answerIndex: 0, distractorReason: '「さえ」举极端例子说明「连最基本的都没有」', explanationZh: '「〜さえない」= 连…都没有' },
    production: { promptJa: 'とても忙しかった日のことを「〜さえ」で言ってください。', promptZh: '用「〜さえ」说一次特别忙的日子。', expected: ['さえ'], acceptable: ['〜さえない', '〜さえ'] },
    practice: { themeJa: '忙しすぎた経験', starterJa: '最近いちばん忙しかった日は、どんな日でしたか？', starterZh: '最近最忙的一天是怎样的？', targetUse: '〜さえ' },
    vocabularyLinks: ['fi-taberu', 'fi-komaru'], unit: 'gap-unit-emphasis' }),

  g({ grammarId: 'n3g-takekka', sourceRowId: 'gap:〜結果／〜た結果', pattern: '〜た結果', reading: 'たけっか', level: 'N3',
    meaningJa: '〜した後、その結果として', explanationZh: '…的结果，…。做了前项，得到后项这个结果',
    formation: '動詞た形／名詞＋の ＋結果', usageScene: '说明努力・调查・讨论之后得到了什么结论',
    nuance: '书面偏多。后项是「结果」，可好可坏', register: 'written',
    examplesJa: ['話し合った結果、来月引っ越すことにした。', '調査の結果、原因がわかった。'],
    examplesZh: ['商量的结果，决定下个月搬家。', '调查的结果，弄清了原因。'],
    furigana: 'はなしあった けっか、らいげつ ひっこすことに した。',
    commonMistakesZh: '「〜あげく」只能用于负面结局，「〜結果」中性。别混用',
    learnerFocus: '「〜た結果」＝中性的「结果」。写报告时很常用',
    similarPatterns: ['〜あげく', '〜末に', '〜ので'],
    contrast: '「結果」＝中性；「あげく」＝折腾后的负面结局；「末に」＝经过努力后（多正面）',
    recognition: { promptZh: '哪一句自然？', options: ['相談した結果、辞めることにした', '相談した結果、明日会いましょう', '相談した結果ので、辞めた', '相談する結果、辞めた'],
      answerIndex: 0, distractorReason: '前接た形；后项是结论，不是邀约', explanationZh: '「〜た結果」= …的结果，…' },
    production: { promptJa: '何かを決めたときのことを「〜た結果」で言ってください。', promptZh: '用「〜た結果」说一次做决定的经过。', expected: ['結果'], acceptable: ['〜た結果'] },
    practice: { themeJa: '考えて決めたこと', starterJa: '最近、よく考えて決めたことはありますか？', starterZh: '最近有认真考虑后决定的事吗？', targetUse: '〜た結果' },
    matchKeys: ['結果'],
    vocabularyLinks: ['fi-kimeru'], unit: 'gap-unit-result' }),

  g({ grammarId: 'n3g-nikanshite', sourceRowId: 'gap:〜に関して／〜に関しては', pattern: '〜に関して', reading: 'にかんして', level: 'N3',
    meaningJa: '〜について（話題を示す・やや硬い）', explanationZh: '关于…。提出话题，比「について」正式',
    formation: '名詞 ＋に関して／に関しては／に関する＋名詞', usageScene: '会议、邮件、报告中提出要谈的主题',
    nuance: '「に関しては」＝把它作为主题并与其他对比；「に関する」＝修饰名词', register: 'written',
    examplesJa: ['この件に関して、質問はありますか。', '費用に関しては、後で説明します。'],
    examplesZh: ['关于这件事，有什么问题吗？', '关于费用，之后再说明。'],
    furigana: 'この けんに かんして、しつもんは ありますか。',
    commonMistakesZh: '「について」也可以，但邮件・会议用「に関して」更正式。口语聊天用「について」即可',
    learnerFocus: '「关于」在工作场合的说法。修饰名词时用「〜に関する＋名詞」',
    similarPatterns: ['〜について', '〜をめぐって', '〜に対して'],
    contrast: '「に関して」＝关于（正式）；「について」＝关于（一般）；「に対して」＝对…（对象）',
    recognition: { promptZh: '在会议上提出主题，最正式的是？', options: ['この件に関して', 'この件のこと', 'この件って', 'この件を'],
      answerIndex: 0, distractorReason: '「に関して」是正式场合提出话题的说法', explanationZh: '「〜に関して」= 关于…（正式）' },
    production: { promptJa: '会議で話したいことを「〜に関して」で切り出してください。', promptZh: '用「〜に関して」在会议上提出话题。', expected: ['に関して'], acceptable: ['に関しては', 'に関する'] },
    practice: { themeJa: '仕事で話題を切り出す', starterJa: '今日の会議で、何について話したいですか？', starterZh: '今天的会议上你想谈什么？', targetUse: '〜に関して' },
    vocabularyLinks: ['fi-kimeru'], unit: 'gap-unit-topic' }),

  g({ grammarId: 'n3g-gimi', sourceRowId: 'gap:〜ぎみ', pattern: '〜ぎみ', reading: 'ぎみ', level: 'N3',
    meaningJa: '少し〜の傾向がある（よくない方向）', explanationZh: '有点…、略微…。感觉稍微偏向某种状态（多为不好的）',
    formation: '動詞ます形／名詞 ＋ぎみ', usageScene: '说身体、心情、工作状态「有点不太好」',
    nuance: '说话人的感觉，程度轻。「疲れぎみ」「風邪ぎみ」「遅れぎみ」', register: 'both',
    examplesJa: ['最近、少し疲れぎみです。', '今日は風邪ぎみなので、早く帰ります。'],
    examplesZh: ['最近有点累。', '今天有点感冒，早点回去。'],
    furigana: 'さいきん、すこし つかれぎみです。',
    commonMistakesZh: '不能用于好的倾向（×元気ぎみ）。「〜がち」是「经常会…」，含义不同',
    learnerFocus: '身体不舒服时的委婉说法。比「疲れている」更轻、更客气',
    similarPatterns: ['〜がち', '〜っぽい', '〜傾向がある'],
    contrast: '「ぎみ」＝现在有点这种感觉；「がち」＝经常容易变成…；「っぽい」＝像…的样子',
    recognition: { promptZh: '「風邪ぎみ」的意思是？', options: ['有点感冒的感觉', '感冒很严重', '经常感冒', '感冒好了'],
      answerIndex: 0, distractorReason: '「ぎみ」是轻微的倾向', explanationZh: '「〜ぎみ」= 有点…' },
    production: { promptJa: '最近の体調を「〜ぎみ」で言ってください。', promptZh: '用「〜ぎみ」说最近的身体状况。', expected: ['ぎみ'], acceptable: ['気味'] },
    practice: { themeJa: '体調を伝える', starterJa: '最近、体の調子はどうですか？', starterZh: '最近身体怎么样？', targetUse: '〜ぎみ' },
    matchKeys: ['ぎみ', '気味'],
    vocabularyLinks: ['fi-komaru'], unit: 'gap-unit-state' }),

  g({ grammarId: 'n3g-todoujini', sourceRowId: 'gap:〜と同時に', pattern: '〜と同時に', reading: 'とどうじに', level: 'N3',
    meaningJa: '〜するのと同じ時に／〜であると同時に…でもある', explanationZh: '与…同时。两件事同时发生；或一个事物同时具有两种性质',
    formation: '動詞辞書形／名詞 ＋と同時に', usageScene: '说明「一…就…」的同时动作，或「既是…也是…」',
    nuance: '书面偏多。口语的「一…就…」多用「〜たとたん」「〜とすぐ」', register: 'written',
    examplesJa: ['ドアを開けると同時に、電話が鳴った。', '彼は父であると同時に、会社の社長でもある。'],
    examplesZh: ['开门的同时，电话响了。', '他既是父亲，同时也是公司的社长。'],
    furigana: 'ドアを あけると どうじに、でんわが なった。',
    commonMistakesZh: '「同時に」前面要接辞书形（×開けたと同時に）',
    learnerFocus: '两个用法：时间上的「同时」和性质上的「既…又…」',
    similarPatterns: ['〜たとたん', '〜とともに', '〜一方で'],
    contrast: '「と同時に」＝同一时刻／兼具；「たとたん」＝刚一…就（意外）；「とともに」＝伴随',
    recognition: { promptZh: '哪一句正确？', options: ['ベルが鳴ると同時に、試験が始まった', 'ベルが鳴ったと同時に、試験が始まった', 'ベルが鳴ると同時、試験が始まった', 'ベルが鳴る同時に、試験が始まった'],
      answerIndex: 0, distractorReason: '接辞书形＋と同時に', explanationZh: '「〜と同時に」= 与…同时' },
    production: { promptJa: '2つのことが同時に起きた経験を言ってください。', promptZh: '用「〜と同時に」说两件事同时发生的经历。', expected: ['と同時に'], acceptable: ['同時に'] },
    practice: { themeJa: '同時に起きたこと', starterJa: '何かが同時に起きて、びっくりしたことはありますか？', starterZh: '有没有两件事同时发生让你吓一跳的经历？', targetUse: '〜と同時に' },
    vocabularyLinks: ['fi-kaeru'], unit: 'gap-unit-time' }),

  g({ grammarId: 'n3g-gotoni', sourceRowId: 'gap:〜ごとに', pattern: '〜ごとに', reading: 'ごとに', level: 'N3',
    meaningJa: '〜のたびに／〜の間隔で', explanationZh: '每…。每隔一定的时间・距离，或每一次',
    formation: '名詞／動詞辞書形 ＋ごとに', usageScene: '说频率（每三天）、间隔（每一站）、每次（每次见面）',
    nuance: '「〜おきに」是「每隔…」，间隔的数法不同：「3日ごとに」＝每3天，「3日おきに」＝隔3天', register: 'both',
    examplesJa: ['この薬は6時間ごとに飲んでください。', '会うごとに、彼は元気になっている。'],
    examplesZh: ['这个药请每6小时吃一次。', '每次见面，他都更精神了。'],
    furigana: 'この くすりは ろくじかんごとに のんで ください。',
    commonMistakesZh: '「ごとに」和「おきに」在数字上容易混：「1日ごとに」＝每天，「1日おきに」＝隔一天',
    learnerFocus: '吃药、乘车、日程都用得到。「每次…」用「動詞辞書形＋ごとに」',
    similarPatterns: ['〜おきに', '〜たびに', '〜ずつ'],
    contrast: '「ごとに」＝每…（含端点）；「おきに」＝每隔…（不含端点）；「たびに」＝每当…时',
    recognition: { promptZh: '「6時間ごとに飲む」是？', options: ['每6小时吃一次', '6小时后吃一次', '吃6小时', '隔6天吃一次'],
      answerIndex: 0, distractorReason: '「ごとに」= 每…', explanationZh: '「〜ごとに」= 每…' },
    production: { promptJa: '自分の習慣を「〜ごとに」で言ってください。', promptZh: '用「〜ごとに」说自己的习惯。', expected: ['ごとに'], acceptable: ['毎'] },
    practice: { themeJa: '決まった間隔でやること', starterJa: '定期的にやっていることはありますか？', starterZh: '有定期做的事吗？', targetUse: '〜ごとに' },
    vocabularyLinks: ['fi-fueru'], unit: 'gap-unit-time' }),

  g({ grammarId: 'n3g-hitsuyouwanai', sourceRowId: 'gap:〜必要はない', pattern: '〜必要はない', reading: 'ひつようはない', level: 'N3',
    meaningJa: '〜しなくてもいい（その必要がない）', explanationZh: '没有必要…。不用做那件事',
    formation: '動詞辞書形 ＋必要はない／必要がない', usageScene: '安慰对方「不用担心」「不用道歉」，或说明手续不需要',
    nuance: '比「〜なくてもいい」更明确地否定「必要性」。安慰时很常用', register: 'both',
    examplesJa: ['そんなに心配する必要はありません。', '予約する必要はないので、直接来てください。'],
    examplesZh: ['没有必要那么担心。', '不需要预约，请直接来。'],
    furigana: 'そんなに しんぱいする ひつようは ありません。',
    commonMistakesZh: '前接辞书形（×心配した必要はない）。「必要ない」是口语省略',
    learnerFocus: '安慰别人时最好用的一句：「謝る必要はないですよ」',
    similarPatterns: ['〜なくてもいい', '〜までもない', '〜ことはない'],
    contrast: '「必要はない」＝没必要（客观）；「ことはない」＝用不着（劝告）；「までもない」＝不必到那种程度',
    recognition: { promptZh: '朋友一直道歉，你想说「不用道歉」，最自然的是？', options: ['謝る必要はないよ', '謝ったほうがいいよ', '謝ってはいけないよ', '謝るはずがないよ'],
      answerIndex: 0, distractorReason: '「必要はない」= 没有必要', explanationZh: '「〜必要はない」= 没必要…' },
    production: { promptJa: '相手を安心させる一言を「〜必要はない」で言ってください。', promptZh: '用「〜必要はない」说一句让对方安心的话。', expected: ['必要はない'], acceptable: ['必要はありません', '必要がない', '必要ない'] },
    practice: { themeJa: '相手を安心させる', starterJa: '友達がとても心配しています。何と言いますか？', starterZh: '朋友很担心，你会说什么？', targetUse: '〜必要はない' },
    matchKeys: ['必要はない', '必要はありません', '必要がない'],
    vocabularyLinks: ['fi-komaru'], unit: 'gap-unit-necessity' }),

  g({ grammarId: 'n3g-hazuganai', sourceRowId: 'gap:〜はずがない', pattern: '〜はずがない', reading: 'はずがない', level: 'N3',
    meaningJa: '〜ということは絶対にない（根拠のある強い否定）', explanationZh: '不可能…。根据理由，强烈否定某种可能性',
    formation: '動詞／い形容詞普通形、な形容詞＋な、名詞＋の ＋はずがない', usageScene: '「他不可能迟到」「不可能这么便宜」这种有根据的否定',
    nuance: '有根据的判断。没根据的猜测用「〜わけがない」（更口语）', register: 'both',
    examplesJa: ['彼が約束を忘れるはずがない。', 'こんなに安いはずがない。何かおかしい。'],
    examplesZh: ['他不可能忘了约定。', '不可能这么便宜，有点不对劲。'],
    furigana: 'かれが やくそくを わすれる はずが ない。',
    commonMistakesZh: '「〜はずだ」的否定不是「はずではない」，而是「はずがない」。「〜ないはずだ」是「应该不会」（弱）',
    learnerFocus: '「はずがない」（不可能，强）和「ないはずだ」（应该不会，弱）语气差别大',
    similarPatterns: ['〜はずだ', '〜わけがない', '〜ないはずだ'],
    contrast: '「はずがない」＝不可能（有根据・强）；「わけがない」＝不可能（口语）；「ないはずだ」＝应该不会（弱）',
    recognition: { promptZh: '「彼が来ないはずがない」的意思是？', options: ['他不可能不来（一定会来）', '他应该不来', '他不可能来', '不知道他来不来'],
      answerIndex: 0, distractorReason: '双重否定＝一定会来', explanationZh: '「〜ないはずがない」= 不可能不…' },
    production: { promptJa: '「絶対にありえない」と思うことを「〜はずがない」で言ってください。', promptZh: '用「〜はずがない」说你觉得绝不可能的事。', expected: ['はずがない'], acceptable: ['はずがありません', 'はずない'] },
    practice: { themeJa: '信じられないこと', starterJa: '「それはありえない」と思ったことはありますか？', starterZh: '有没有觉得「那不可能」的事？', targetUse: '〜はずがない' },
    matchKeys: ['はずがない', 'はずがありません', 'はずない'],
    vocabularyLinks: ['fi-kimeru'], unit: 'gap-unit-judgement' }),

  g({ grammarId: 'n3g-kanouseigaaru', sourceRowId: 'gap:〜可能性がある', pattern: '〜可能性がある', reading: 'かのうせいがある', level: 'N3',
    meaningJa: '〜かもしれない（起こりうる）', explanationZh: '有可能…。比「かもしれない」更客观、更书面',
    formation: '動詞普通形／名詞＋の ＋可能性がある／高い／低い', usageScene: '新闻、报告、医生的说明中说明可能性',
    nuance: '可以说「高い／低い」来表示程度。口语聊天用「かもしれない」更自然', register: 'written',
    examplesJa: ['午後から雨が降る可能性があります。', '手術が必要になる可能性は低いです。'],
    examplesZh: ['下午有可能下雨。', '需要手术的可能性很低。'],
    furigana: 'ごごから あめが ふる かのうせいが あります。',
    commonMistakesZh: '「可能性」不能用「多い／少ない」，要用「高い／低い」',
    learnerFocus: '医生、通知、新闻里高频。听懂「可能性が高い／低い」很重要',
    similarPatterns: ['〜かもしれない', '〜おそれがある', '〜恐れがある'],
    contrast: '「可能性がある」＝中性的可能；「おそれがある」＝不好的可能；「かもしれない」＝口语推测',
    recognition: { promptZh: '医生说「入院の可能性は低いです」，意思是？', options: ['住院的可能性很低', '一定要住院', '不能住院', '住院费很便宜'],
      answerIndex: 0, distractorReason: '「可能性が低い」= 可能性小', explanationZh: '「〜可能性が低い」= …的可能性低' },
    production: { promptJa: '明日の予定について「〜可能性がある」で言ってください。', promptZh: '用「〜可能性がある」说明天可能发生的事。', expected: ['可能性'], acceptable: ['可能性がある', '可能性が高い'] },
    practice: { themeJa: 'これから起こりそうなこと', starterJa: '来月、起こりそうなことはありますか？', starterZh: '下个月有什么可能发生的事？', targetUse: '〜可能性がある' },
    matchKeys: ['可能性'],
    vocabularyLinks: ['fi-kawaru'], unit: 'gap-unit-judgement' }),

  g({ grammarId: 'n3g-igaini', sourceRowId: 'gap:〜以外に', pattern: '〜以外に', reading: 'いがいに', level: 'N3',
    meaningJa: '〜のほかに', explanationZh: '除…之外（还有）。在已有的之上追加，或表示「除了…没有」',
    formation: '名詞／動詞辞書形 ＋以外に（も）／以外は', usageScene: '问「除此之外还有吗」；说「除了他没人会」',
    nuance: '「以外に（も）」＝除了…还有；「以外は」＝除了…都；「以外にない」＝只有', register: 'both',
    examplesJa: ['日本語以外に、英語も勉強しています。', '彼以外に、この仕事ができる人はいない。'],
    examplesZh: ['除了日语，还在学英语。', '除了他，没有人能做这份工作。'],
    furigana: 'にほんご いがいに、えいごも べんきょう しています。',
    commonMistakesZh: '「以外に」后接肯定＝还有；后接否定＝只有。别弄反',
    learnerFocus: '问店员「これ以外にありますか」（还有别的吗）是购物常用句',
    similarPatterns: ['〜のほかに', '〜を除いて', '〜しか'],
    contrast: '「以外に」＝除了…（追加或唯一）；「のほかに」＝另外还有；「を除いて」＝排除（书面）',
    recognition: { promptZh: '「彼以外にできる人はいない」是？', options: ['只有他会', '他不会', '除了他大家都会', '谁都不会'],
      answerIndex: 0, distractorReason: '「以外に…ない」= 只有…', explanationZh: '「〜以外に〜ない」= 除了…没有' },
    production: { promptJa: '勉強していることを「〜以外に」で2つ言ってください。', promptZh: '用「〜以外に」说自己在学的两样东西。', expected: ['以外に'], acceptable: ['以外にも', '以外'] },
    practice: { themeJa: '「ほかには？」に答える', starterJa: '日本語のほかに、何か勉強していますか？', starterZh: '除了日语还在学什么？', targetUse: '〜以外に' },
    matchKeys: ['以外'],
    vocabularyLinks: ['fi-fueru'], unit: 'gap-unit-addition' }),

  g({ grammarId: 'n3g-tochuude', sourceRowId: 'gap:〜途中／〜途中で', pattern: '〜途中で', reading: 'とちゅうで', level: 'N3',
    meaningJa: '〜している間に／〜へ行く間に', explanationZh: '在…途中、…的路上。事情做到一半，或去某处的路上',
    formation: '動詞辞書形／名詞＋の ＋途中で／途中に', usageScene: '说「上班路上」「会议中途」发生了什么',
    nuance: '「途中で」强调「在中途（发生了）」；「途中に」偏「在路上（有某物）」', register: 'both',
    examplesJa: ['会社へ行く途中で、忘れ物に気づいた。', '会議の途中で、電話がかかってきた。'],
    examplesZh: ['去公司的路上，发现忘了东西。', '会议中途，来了电话。'],
    furigana: 'かいしゃへ いく とちゅうで、わすれものに きづいた。',
    commonMistakesZh: '前接辞书形（×行った途中で）。「途中」前面可以是「名詞＋の」',
    learnerFocus: '迟到时的解释「来る途中で電車が止まった」很实用',
    similarPatterns: ['〜間に', '〜最中に', '〜ながら'],
    contrast: '「途中で」＝中途（进程）；「最中に」＝正在…的时候（强调正当时）；「間に」＝期间',
    recognition: { promptZh: '「来る途中で電車が止まった」是？', options: ['来的路上电车停了', '来之前电车停了', '到了之后电车停了', '电车没停'],
      answerIndex: 0, distractorReason: '「途中で」= 在途中', explanationZh: '「〜途中で」= 在…途中' },
    production: { promptJa: '遅れた理由を「〜途中で」で言ってください。', promptZh: '用「〜途中で」说迟到的理由。', expected: ['途中'], acceptable: ['途中で', '途中に'] },
    practice: { themeJa: '遅れた理由を伝える', starterJa: '遅刻したとき、どう説明しますか？', starterZh: '迟到的时候你怎么解释？', targetUse: '〜途中で' },
    matchKeys: ['途中'],
    vocabularyLinks: ['fi-kaeru'], unit: 'gap-unit-time' }),

  g({ grammarId: 'n3g-kirenai', sourceRowId: 'gap:〜きれない', pattern: '〜きれない', reading: 'きれない', level: 'N3',
    meaningJa: '最後まで〜することができない（量が多すぎて）', explanationZh: '…不完。因为量太多，无法全部做完',
    formation: '動詞ます形 ＋きれない／きれる／きる', usageScene: '「吃不完」「数不清」「用不完」',
    nuance: '「〜きる」＝全部做完；「〜きれない」＝做不完。多与「多すぎて」搭配', register: 'both',
    examplesJa: ['料理が多すぎて、食べきれなかった。', '本が多くて、一日では読みきれない。'],
    examplesZh: ['菜太多，没吃完。', '书太多，一天读不完。'],
    furigana: 'りょうりが おおすぎて、たべきれなかった。',
    commonMistakesZh: '「できない」是「不会・不能」，「きれない」是「量太多做不完」。别用「食べられない」表达「吃不完」',
    learnerFocus: '在餐厅说「食べきれないので、持ち帰れますか」很实用',
    similarPatterns: ['〜きる', '〜られない', '〜すぎる'],
    contrast: '「きれない」＝量多做不完；「られない」＝没有能力・不被允许；「すぎる」＝过度',
    recognition: { promptZh: '「食べきれない」的意思是？', options: ['吃不完（太多）', '不能吃（不允许）', '不好吃', '不想吃'],
      answerIndex: 0, distractorReason: '「きれない」= 量太多做不完', explanationZh: '「〜きれない」= …不完' },
    production: { promptJa: '多すぎて終わらなかった経験を「〜きれない」で言ってください。', promptZh: '用「〜きれない」说一次因为太多没做完的经历。', expected: ['きれ'], acceptable: ['きれない', 'きれなかった'] },
    practice: { themeJa: '多すぎたこと', starterJa: '多すぎて困ったことはありますか？', starterZh: '有没有因为太多而为难的事？', targetUse: '〜きれない' },
    matchKeys: ['きれない', 'きれなかった', 'きれる'],
    vocabularyLinks: ['fi-taberu'], unit: 'gap-unit-degree' }),

  g({ grammarId: 'n2g-baaidewanai', sourceRowId: 'gap:〜場合ではない', pattern: '〜場合ではない', reading: 'ばあいではない', level: 'N2',
    meaningJa: '今は〜している時ではない（もっと大事なことがある）', explanationZh: '现在不是…的时候。有更要紧的事，不能做那件事',
    formation: '動詞辞書形／ている形 ＋場合ではない／場合じゃない', usageScene: '催促别人「现在不是玩的时候」，或自我警醒',
    nuance: '带责备或紧迫感。「場合じゃない」是口语', register: 'both',
    examplesJa: ['今は遊んでいる場合ではない。試験は明日だ。', '笑っている場合じゃないよ。'],
    examplesZh: ['现在不是玩的时候，明天就考试了。', '现在可不是笑的时候。'],
    furigana: 'いまは あそんでいる ばあいでは ない。しけんは あしただ。',
    commonMistakesZh: '「場合」在这里不是「情况」，而是「时候」。别翻成「不是这种情况」',
    learnerFocus: '和「〜どころではない」类似，都表示「顾不上」',
    similarPatterns: ['〜どころではない', '〜ている場合か', '〜べきではない'],
    contrast: '「場合ではない」＝不是做那事的时候（有更要紧的）；「どころではない」＝根本顾不上；「べきではない」＝不应该',
    recognition: { promptZh: '「遊んでいる場合ではない」的语气是？', options: ['现在不是玩的时候（有要紧事）', '不知道该不该玩', '玩也可以', '已经玩过了'],
      answerIndex: 0, distractorReason: '「場合ではない」= 现在不是做那事的时候', explanationZh: '「〜場合ではない」= 不是…的时候' },
    production: { promptJa: '忙しいときに自分に言う言葉を「〜場合ではない」で言ってください。', promptZh: '用「〜場合ではない」说忙的时候对自己说的话。', expected: ['場合ではない'], acceptable: ['場合じゃない', '場合ではありません'] },
    practice: { themeJa: '優先順位を決める', starterJa: '「今はそれどころじゃない」と思ったことはありますか？', starterZh: '有没有觉得「现在顾不上那个」的时候？', targetUse: '〜場合ではない' },
    matchKeys: ['場合ではない', '場合じゃない'],
    vocabularyLinks: ['fi-kimeru'], unit: 'gap-unit-judgement' }),

  g({ grammarId: 'n2g-towaie', sourceRowId: 'gap:〜とはいえ', pattern: '〜とはいえ', reading: 'とはいえ', level: 'N2',
    meaningJa: '〜と言っても（実際は）', explanationZh: '虽说…，但…。承认前项，但实际情况和想象不同',
    formation: '名詞／普通形 ＋とはいえ', usageScene: '「虽说是春天，还是很冷」这种「话虽如此」',
    nuance: '书面偏多。口语可用「〜といっても」', register: 'written',
    examplesJa: ['春とはいえ、朝はまだ寒い。', '子どもとはいえ、言っていいことと悪いことがある。'],
    examplesZh: ['虽说是春天，早上还是冷。', '虽说是孩子，也有能说和不能说的话。'],
    furigana: 'はるとはいえ、あさは まだ さむい。',
    commonMistakesZh: '「とはいえ」不能接「けれども」（×とはいえけれども）。它本身已含转折',
    learnerFocus: '「话虽如此」的正式说法。写作和报告里好用',
    similarPatterns: ['〜といっても', '〜ものの', '〜が'],
    contrast: '「とはいえ」＝虽说（书面）；「といっても」＝虽说（口语）；「ものの」＝虽然…但（结果不如预期）',
    recognition: { promptZh: '「春とはいえ、朝は寒い」是？', options: ['虽说是春天，早上还是冷', '因为是春天所以冷', '春天早上不冷', '春天还没到'],
      answerIndex: 0, distractorReason: '「とはいえ」= 虽说…但', explanationZh: '「〜とはいえ」= 虽说…' },
    production: { promptJa: '「そうは言っても」と思うことを「〜とはいえ」で言ってください。', promptZh: '用「〜とはいえ」说一件「话虽如此」的事。', expected: ['とはいえ'], acceptable: ['とは言え'] },
    practice: { themeJa: '「言われていることと実際」', starterJa: '「〜と言われているけど、実際は違う」と思うことはありますか？', starterZh: '有没有「大家都那么说，其实不然」的事？', targetUse: '〜とはいえ' },
    matchKeys: ['とはいえ', 'とは言え'],
    vocabularyLinks: ['fi-kawaru'], unit: 'gap-unit-contrast' }),

  g({ grammarId: 'n2g-wokini', sourceRowId: 'gap:〜を機に', pattern: '〜を機に', reading: 'をきに', level: 'N2',
    meaningJa: '〜をきっかけにして', explanationZh: '以…为契机。因为某件事而开始做另一件事',
    formation: '名詞／動詞辞書形＋の ＋を機に／を機会に', usageScene: '「以结婚为契机搬家」「以转职为契机开始学习」',
    nuance: '正式。口语用「〜をきっかけに」', register: 'written',
    examplesJa: ['結婚を機に、東京へ引っ越した。', '転職を機に、日本語の勉強を始めた。'],
    examplesZh: ['以结婚为契机，搬到了东京。', '以换工作为契机，开始学日语。'],
    furigana: 'けっこんを きに、とうきょうへ ひっこした。',
    commonMistakesZh: '「機」读「き」，不是「はた」。书面语，聊天用「きっかけに」',
    learnerFocus: '自我介绍说「来日本的契机」时正好用',
    similarPatterns: ['〜をきっかけに', '〜を契機に', '〜てから'],
    contrast: '「を機に」＝以…为契机（正式）；「をきっかけに」＝同义（口语）；「てから」＝单纯的时间先后',
    recognition: { promptZh: '「転職を機に勉強を始めた」是？', options: ['以换工作为契机开始学习', '因为学习而换了工作', '换工作前就在学习', '换工作后停止学习'],
      answerIndex: 0, distractorReason: '「を機に」= 以…为契机（之后开始）', explanationZh: '「〜を機に」= 以…为契机' },
    production: { promptJa: '日本語を始めたきっかけを「〜を機に」で言ってください。', promptZh: '用「〜を機に」说开始学日语的契机。', expected: ['を機に'], acceptable: ['をきっかけに'] },
    practice: { themeJa: '始めたきっかけ', starterJa: '日本語の勉強を始めたきっかけは何ですか？', starterZh: '你开始学日语的契机是什么？', targetUse: '〜を機に' },
    matchKeys: ['を機に', 'をきっかけに'],
    vocabularyLinks: ['fi-kawaru', 'fi-kimeru'], unit: 'gap-unit-cause' }),

  g({ grammarId: 'n2g-yainaya', sourceRowId: 'gap:〜やいなや', pattern: '〜やいなや', reading: 'やいなや', level: 'N2',
    meaningJa: '〜するとすぐに（ほぼ同時に）', explanationZh: '刚一…就…。前项刚发生，后项立刻发生',
    formation: '動詞辞書形 ＋やいなや', usageScene: '描写「一到家就」「一说完就」的紧接动作',
    nuance: '书面、文章体。口语用「〜たとたん」「〜とすぐ」。后项不能是意志', register: 'written',
    examplesJa: ['家に帰るやいなや、ベッドに倒れこんだ。', '発表が終わるやいなや、拍手が起こった。'],
    examplesZh: ['一到家就倒在床上。', '发表一结束，掌声就响了起来。'],
    furigana: 'いえに かえるやいなや、ベッドに たおれこんだ。',
    commonMistakesZh: '前接辞书形（×帰ったやいなや）。后项是已发生的事，不能是命令・意志',
    learnerFocus: '小说、新闻里出现。会说「たとたん」的话，「やいなや」只需能读懂',
    similarPatterns: ['〜たとたん', '〜か〜ないかのうちに', '〜が早いか'],
    contrast: '「やいなや」＝书面「刚一…就」；「たとたん」＝口语、含意外；「か〜ないかのうちに」＝几乎同时',
    recognition: { promptZh: '哪一句正确？', options: ['ベルが鳴るやいなや、走り出した', 'ベルが鳴ったやいなや、走り出した', 'ベルが鳴るやいなや、走ろう', 'ベルが鳴るやいなや、走ってください'],
      answerIndex: 0, distractorReason: '接辞书形；后项是已发生的动作', explanationZh: '「〜やいなや」= 刚一…就' },
    production: { promptJa: '急いで何かをした経験を「〜やいなや」で言ってください。', promptZh: '用「〜やいなや」说一次急着做某事的经历。', expected: ['やいなや'], acceptable: ['や否や'] },
    practice: { themeJa: 'すぐに行動したこと', starterJa: '何かが終わった瞬間にすぐ動いたことはありますか？', starterZh: '有没有什么事一结束就马上行动的经历？', targetUse: '〜やいなや' },
    matchKeys: ['やいなや', 'や否や'],
    vocabularyLinks: ['fi-kaeru'], unit: 'gap-unit-time' }),

  g({ grammarId: 'n2g-nakuwanai', sourceRowId: 'gap:〜なくはない', pattern: '〜なくはない', reading: 'なくはない', level: 'N2',
    meaningJa: '全くないわけではない（少しはある）', explanationZh: '并非完全没有；也不是不…。用双重否定表示「多少有一点」',
    formation: '動詞ない形（〜なく）／い形容詞（〜くなく）／な形容詞・名詞（〜でなく） ＋はない', usageScene: '不想说得太肯定时的委婉表达',
    nuance: '语气弱、含保留。「食べなくはない」＝也不是不吃（但不太爱吃）', register: 'both',
    examplesJa: ['お酒は飲めなくはないが、あまり好きではない。', 'その意見も、わからなくはない。'],
    examplesZh: ['酒也不是不能喝，只是不太喜欢。', '那个意见我也不是不能理解。'],
    furigana: 'おさけは のめなくは ないが、あまり すきでは ない。',
    commonMistakesZh: '双重否定＝弱肯定，不是强肯定。「わからなくはない」≠「よくわかる」',
    learnerFocus: '日本人的委婉表达。听到「なくはない」要理解成「有一点，但不多」',
    similarPatterns: ['〜ないこともない', '〜ないわけではない', '〜なくもない'],
    contrast: '三者几乎同义。「ないこともない」更口语；「ないわけではない」略正式',
    recognition: { promptZh: '「飲めなくはない」的意思是？', options: ['也不是不能喝（能喝一点）', '完全不能喝', '很能喝', '必须喝'],
      answerIndex: 0, distractorReason: '双重否定＝弱肯定', explanationZh: '「〜なくはない」= 并非不…' },
    production: { promptJa: 'あまり好きではないが、できることを「〜なくはない」で言ってください。', promptZh: '用「〜なくはない」说一件不太喜欢但能做的事。', expected: ['なくはない'], acceptable: ['なくもない', 'ないこともない'] },
    practice: { themeJa: 'はっきり言いにくいこと', starterJa: '好きでも嫌いでもないものはありますか？', starterZh: '有没有说不上喜欢也说不上讨厌的东西？', targetUse: '〜なくはない' },
    matchKeys: ['なくはない', 'なくもない'],
    vocabularyLinks: ['fi-taberu'], unit: 'gap-unit-judgement' }),

  g({ grammarId: 'n2g-keikougaaru', sourceRowId: 'gap:〜傾向がある', pattern: '〜傾向がある', reading: 'けいこうがある', level: 'N2',
    meaningJa: '〜しがちだ（全体としてそうなりやすい）', explanationZh: '有…的倾向。整体上容易往某个方向发展',
    formation: '動詞辞書形／名詞＋の ＋傾向がある／傾向にある', usageScene: '报告、分析中描述趋势（年轻人有…的倾向）',
    nuance: '客观、书面。个人的习惯用「〜がち」', register: 'written',
    examplesJa: ['最近の若者は、車を持たない傾向がある。', '彼は物事を悪く考える傾向がある。'],
    examplesZh: ['最近的年轻人有不买车的倾向。', '他有把事情往坏处想的倾向。'],
    furigana: 'さいきんの わかものは、くるまを もたない けいこうが ある。',
    commonMistakesZh: '「傾向」读「けいこう」。说个人小习惯时用「〜がち」更自然',
    learnerFocus: '写报告、说明数据时的固定表达',
    similarPatterns: ['〜がち', '〜ぎみ', '〜傾向にある'],
    contrast: '「傾向がある」＝整体趋势（客观）；「がち」＝个人容易…（略负面）；「ぎみ」＝现在有点…',
    recognition: { promptZh: '「車を持たない傾向がある」是？', options: ['有不买车的倾向', '绝对不买车', '一定要买车', '车很贵'],
      answerIndex: 0, distractorReason: '「傾向がある」= 有…的倾向（不是绝对）', explanationZh: '「〜傾向がある」= 有…倾向' },
    production: { promptJa: '自分の国の人の特徴を「〜傾向がある」で言ってください。', promptZh: '用「〜傾向がある」说自己国家的人的特点。', expected: ['傾向'], acceptable: ['傾向がある', '傾向にある'] },
    practice: { themeJa: '傾向を説明する', starterJa: '最近の若い人について、感じることはありますか？', starterZh: '你对最近的年轻人有什么感觉？', targetUse: '〜傾向がある' },
    matchKeys: ['傾向'],
    vocabularyLinks: ['fi-fueru'], unit: 'gap-unit-state' }),

  g({ grammarId: 'n2g-nioite', sourceRowId: 'gap:〜における／〜において', pattern: '〜において', reading: 'において', level: 'N2',
    meaningJa: '〜で（場所・時代・分野を示す、硬い言い方）', explanationZh: '在…（地点・时代・领域）。「で」的正式说法',
    formation: '名詞 ＋において／における＋名詞', usageScene: '演讲、报告、正式文书',
    nuance: '「における」修饰名词。日常口语不用', register: 'written',
    examplesJa: ['会議は本社において行われます。', '現代社会における教育の役割について考える。'],
    examplesZh: ['会议将在总公司举行。', '思考教育在现代社会中的作用。'],
    furigana: 'かいぎは ほんしゃに おいて おこなわれます。',
    commonMistakesZh: '「において」不能用于日常对话（×駅において会いましょう）',
    learnerFocus: '正式通知、演讲里常见。能读懂即可，口语不用',
    similarPatterns: ['〜で', '〜にて', '〜に関して'],
    contrast: '「において」＝正式的「在」；「にて」＝更书面（通知）；「で」＝日常',
    recognition: { promptZh: '正式通知中「本社において行われます」是？', options: ['在总公司举行', '关于总公司', '由总公司决定', '总公司以外'],
      answerIndex: 0, distractorReason: '「において」= 在…（场所）', explanationZh: '「〜において」= 在…' },
    production: { promptJa: '正式な案内文を「〜において」で書いてください。', promptZh: '用「〜において」写一句正式的通知。', expected: ['において'], acceptable: ['における'] },
    practice: { themeJa: '正式な案内を書く', starterJa: 'イベントの案内を正式に書くとしたら、どう書きますか？', starterZh: '如果要正式写活动通知，你会怎么写？', targetUse: '〜において' },
    matchKeys: ['において', 'における'],
    vocabularyLinks: ['fi-kimeru'], unit: 'gap-unit-formal' }),

  g({ grammarId: 'n2g-tsutsumo', sourceRowId: 'gap:〜つつも', pattern: '〜つつも', reading: 'つつも', level: 'N2',
    meaningJa: '〜しながらも（それに反して）', explanationZh: '虽然…却…。明知道前项，却做了相反的后项',
    formation: '動詞ます形 ＋つつも／つつ', usageScene: '「明知不好却还是…」的自省・反省',
    nuance: '书面。口语用「〜ながらも」。后项多为与前项矛盾的行为', register: 'written',
    examplesJa: ['体に悪いと知りつつも、夜遅くまで食べてしまう。', '悪いと思いつつも、嘘をついた。'],
    examplesZh: ['明知对身体不好，还是吃到深夜。', '虽然觉得不对，还是撒了谎。'],
    furigana: 'からだに わるいと しりつつも、よる おそくまで たべて しまう。',
    commonMistakesZh: '「つつ」（一边…一边）和「つつも」（虽然…却）不同。「も」带来转折',
    learnerFocus: '反省时的固定句式「〜と知りつつも」',
    similarPatterns: ['〜ながらも', '〜のに', '〜ものの'],
    contrast: '「つつも」＝明知却（书面）；「ながらも」＝同义（口语可）；「のに」＝明明…却（不满）',
    recognition: { promptZh: '「悪いと知りつつも食べた」是？', options: ['明知不好还是吃了', '不知道不好所以吃了', '因为好所以吃了', '没吃'],
      answerIndex: 0, distractorReason: '「つつも」= 明知…却', explanationZh: '「〜つつも」= 虽然…却' },
    production: { promptJa: 'やめられない習慣を「〜と知りつつも」で言ってください。', promptZh: '用「〜と知りつつも」说一个戒不掉的习惯。', expected: ['つつも'], acceptable: ['つつ', 'ながらも'] },
    practice: { themeJa: 'やめられないこと', starterJa: 'よくないと分かっているのに、やめられないことはありますか？', starterZh: '有没有明知不好却戒不掉的事？', targetUse: '〜つつも' },
    matchKeys: ['つつも'],
    vocabularyLinks: ['fi-taberu'], unit: 'gap-unit-contrast' }),

  g({ grammarId: 'n2g-tekoso', sourceRowId: 'gap:〜てこそ', pattern: '〜てこそ', reading: 'てこそ', level: 'N2',
    meaningJa: '〜して初めて（それがあってこそ）', explanationZh: '只有…才…。强调前项是后项成立的必要条件',
    formation: '動詞て形 ＋こそ', usageScene: '说人生道理、强调经验的重要性',
    nuance: '后项多为「本当の〜だ」「意味がある」等评价', register: 'written',
    examplesJa: ['苦労してこそ、成功の喜びがわかる。', '自分で経験してこそ、本当に理解できる。'],
    examplesZh: ['只有吃过苦，才懂得成功的喜悦。', '只有亲身经历，才能真正理解。'],
    furigana: 'くろうしてこそ、せいこうの よろこびが わかる。',
    commonMistakesZh: '「こそ」单独用是「正是」，「てこそ」是「只有…才」。位置不同意思不同',
    learnerFocus: '说道理时的强调句式。日常聊天不太用',
    similarPatterns: ['〜て初めて', '〜ばこそ', '〜からこそ'],
    contrast: '「てこそ」＝只有做了才（条件）；「て初めて」＝做了之后才第一次（时间）；「からこそ」＝正因为',
    recognition: { promptZh: '「経験してこそわかる」是？', options: ['只有经历了才明白', '经历了也不明白', '不经历也明白', '经历之前就明白'],
      answerIndex: 0, distractorReason: '「てこそ」= 只有…才', explanationZh: '「〜てこそ」= 只有…才' },
    production: { promptJa: '自分が大切だと思うことを「〜てこそ」で言ってください。', promptZh: '用「〜てこそ」说你觉得重要的道理。', expected: ['てこそ'], acceptable: ['こそ'] },
    practice: { themeJa: '大切だと思うこと', starterJa: '「〜して初めてわかった」ことはありますか？', starterZh: '有没有「做了才明白」的事？', targetUse: '〜てこそ' },
    matchKeys: ['てこそ'],
    vocabularyLinks: ['fi-kawaru'], unit: 'gap-unit-emphasis' }),
];

export const grammarGapById = (id: string): GrammarGapDraft | undefined =>
  GRAMMAR_GAP_DRAFTS.find((d) => d.grammarId === id);
