/**
 * ビルド後にdist/index.htmlを読み取り、
 * 正しいハッシュを埋め込んだdist/_worker.jsを自動生成するスクリプト。
 * CF Pages v3 の Clean URLs バグを回避するため index.html を Worker に埋め込む。
 */
// existsSync は security側のCSP生成（.env から Supabase オリジンを読む）で、
// fileURLToPath は HEAD側の staticSeo.json 読み込みで使う。両方いる。
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';

/**
 * 静的ページのtitle/description（src/lib/seo/staticSeo.json が正）。
 * 画面側は react-helmet-async で同じ文言を入れており、staticSeo.test.ts が突き合わせる。
 * ここでWorkerに埋め込むのは、JSを実行しないクローラー（WeChat・小紅書・LINE・X・Baidu）
 * のため。これが無いと中国語ページも日本語のバドミントン文言のまま配られる。
 *
 * ビルドは必ずリポジトリ直下から走るが、テストからも呼ばれるので
 * カレントディレクトリに依存しないフォールバックを持たせている。
 */
const staticSeoRaw = (() => {
  try {
    return readFileSync('src/lib/seo/staticSeo.json', 'utf8');
  } catch (_) {
    return readFileSync(fileURLToPath(new URL('../src/lib/seo/staticSeo.json', import.meta.url)), 'utf8');
  }
})();
const staticSeo = JSON.parse(staticSeoRaw).pages;

/**
 * 販売LPの本文（JSを実行しないクローラー向け・2026-08-26）。
 * scripts/ai-course/generate-lp-prerender.mts が lpContent.ts から生成する。
 * 素のHTML本文が212文字しかなく、GPTBot/ClaudeBot 等が販売ページを読めていなかった。
 * staticSeo.json と同じく、カレントディレクトリに依存しない読み方をする。
 */
const lpPrerenderRaw = (() => {
  try {
    return readFileSync('src/lib/seo/lpPrerender.json', 'utf8');
  } catch (_) {
    return readFileSync(fileURLToPath(new URL('../src/lib/seo/lpPrerender.json', import.meta.url)), 'utf8');
  }
})();
const lpPrerender = JSON.parse(lpPrerenderRaw);
const LP_PRERENDER_JSON = JSON.stringify({ ja: lpPrerender.ja, zh: lpPrerender.zh });
const STATIC_SEO_JSON = JSON.stringify(
  Object.fromEntries(Object.entries(staticSeo).map(([k, v]) => [
    k,
    // body = プリレンダ本文（2026-08-24）。素のHTMLの可視テキストが0文字だった問題を埋める
    { ja: v.ja, zh: v.zh, image: v.image ?? null, body: v.body ?? null },
  ])),
);

/**
 * index.html から Worker のソースを組み立てる。
 *
 * 【なぜ関数にして export するか】
 * プリレンダは「実際に素のHTMLに出るか」が命なので、テストから**この関数を呼んで**
 * 生成されたWorkerをそのまま評価し、本文・JSON-LD・canonical・hreflangを確認している
 * （src/lib/seo/workerPrerender.test.mjs）。文字列を目で確認するテストでは、
 * 生成物が壊れていても気づけない。
 */
export function buildWorkerSource(indexHtml) {
// バッククオートをエスケープ
const escapedHtml = indexHtml.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

// CSPの connect-src に入れる Supabase のオリジンをビルド時に確定させる。
// 環境変数 → .env の順で探し、見つからなければCSPを出力しない（誤ったオリジンで
// 通信をブロックするより、CSP無しの方が安全side）。
const supabaseOrigin = (() => {
  const raw =
    process.env.VITE_SUPABASE_URL ||
    (existsSync('.env') ? (readFileSync('.env', 'utf8').match(/^VITE_SUPABASE_URL=(.+)$/m)?.[1] ?? '') : '');
  try {
    return raw ? new URL(raw.trim()).origin : '';
  } catch {
    return '';
  }
})();
if (!supabaseOrigin) {
  console.warn('⚠️  VITE_SUPABASE_URL を特定できなかったため CSP(Report-Only) は出力しません');
}

const workerContent = `// Auto-generated by scripts/generate-worker.mjs
// CF Pages v3 Clean URLs 500エラーを回避するためindex.htmlを直接埋め込む

const INDEX_HTML = \`${escapedHtml}\`;
const SUPABASE_ORIGIN = ${JSON.stringify(supabaseOrigin)};

// ── LCP画像のpreload注入 ──
// SPAはJS起動後にしか画像を発見できないため、HTML段階で先読みさせてLCPを縮める。
// srcset/sizes は表示側（HomePage.tsx / staticImageSets.ts / blogImages.ts）と
// 完全一致させること。ズレると二重ダウンロードになる。
const HERO_PRELOAD =
  '<link rel="preload" as="image" type="image/webp" ' +
  'imagesrcset="/hero-768.webp 768w, /hero-1280.webp 1280w, /hero-1376.webp 1376w" ' +
  'imagesizes="100vw" fetchpriority="high">';
const HOME_PATH_RE = /^\\/(?:(?:ja|zh)\\/?)?$/;

const BLOG_COVER_SIZES = '(min-width: 928px) 864px, calc(100vw - 2rem)';
function buildCoverPreload(imageUrl) {
  const m = imageUrl.match(
    /^(https:\\/\\/[^\\s"]+\\/storage\\/v1\\/object\\/public\\/blog-images\\/.+?)(?:_w(?:480|960|1600)\\.webp|\\.(?:jpe?g|png|webp|heic|heif))$/i
  );
  if (m) {
    const base = m[1];
    return '<link rel="preload" as="image" type="image/webp" imagesrcset="' +
      escAttr(base + '_w480.webp') + ' 480w, ' +
      escAttr(base + '_w960.webp') + ' 960w, ' +
      escAttr(base + '_w1600.webp') + ' 1600w" ' +
      'imagesizes="' + BLOG_COVER_SIZES + '" fetchpriority="high">';
  }
  // 変種規約に乗らないURL（外部画像・GIF等）は原本をそのままpreload
  return '<link rel="preload" as="image" href="' + escAttr(imageUrl) + '" fetchpriority="high">';
}

// sitemap.xml 動的生成
async function generateSitemap(env) {
  const staticUrls = [
    { path: '',              priority: '1.0', freq: 'weekly' },
    { path: 'activity',      priority: '0.9', freq: 'weekly' },
    { path: 'level-guide',   priority: '0.8', freq: 'monthly' },
    { path: 'faq',           priority: '0.8', freq: 'monthly' },
    { path: 'venues',        priority: '0.7', freq: 'monthly' },
    // 国際交流（2026-08-24 新設）。実測で「国際交流」「外国人」系の検索語は表示0件だった
    { path: 'international', priority: '0.8', freq: 'monthly' },
    // 地域ページ（2026-08-28 新設）。会場名「芝園公民館」では3か月73表示あるのに、
    // 「川口市 バドミントン」は18位・「バドミントン 川口」は17位で受け皿が無かった。
    // 戸田は検索語として1度も表示されていない（＝土俵に上がっていない）
    { path: 'kawaguchi',     priority: '0.9', freq: 'monthly' },
    { path: 'toda',          priority: '0.7', freq: 'monthly' },
    // 主催者ページ・大会一覧（2026-08-31）。/tournaments はルートが無いまま
    // 200 を返して index.html のフォールバックを見せていたので、実体を作って登録した
    { path: 'about',         priority: '0.7', freq: 'monthly' },
    { path: 'tournaments',   priority: '0.9', freq: 'weekly' },
    // 種目別の恒常ページ（2026-08-24）。大会は終わると一覧から消えるので、
    // 種目＋地域の検索（例: ミックスダブルス 大会 埼玉）を受ける常設URLを置く
    { path: 'tournaments/singles',       priority: '0.8', freq: 'weekly' },
    { path: 'tournaments/doubles',       priority: '0.8', freq: 'weekly' },
    { path: 'tournaments/mixed-doubles', priority: '0.8', freq: 'weekly' },
    { path: 'contact',       priority: '0.6', freq: 'monthly' },
    // シャトル供養カウンター（2026-08-28 追加）。今まで Helmet が1つも無く、素のHTMLが
    // トップの文言のままだった。自己参照canonicalとhreflangを出す以上、sitemapにも載せる
    // （「正規URLとして名乗るがsitemapには載せない」という中途半端な状態を作らない）
    { path: 'shuttle-roadmap', priority: '0.4', freq: 'monthly' },
    // blog 一覧は jaOnlyUrls（/zh/blog は /ja/blog へ canonical のまま）。
    // 記事ごとの中国語版は下の zhPosts で /zh/blog/:id として送る
    { path: 'join',          priority: '0.6', freq: 'monthly' },
    { path: 'results/vol1',  priority: '0.6', freq: 'yearly' },
    { path: 'results/vol2',  priority: '0.6', freq: 'yearly' },
    { path: 'results/vol3',  priority: '0.6', freq: 'yearly' },
    { path: 'cancel-policy', priority: '0.5', freq: 'monthly' },
    // バド本体の法務3ページ（2026-08-24 追加）。有料の申込を受けている以上、
    // 特商法表記・プライバシーポリシー・利用規約は検索からも辿れる場所に置く
    { path: 'tokushoho',     priority: '0.3', freq: 'yearly' },
    { path: 'privacy',       priority: '0.3', freq: 'yearly' },
    { path: 'terms',         priority: '0.3', freq: 'yearly' },
    // AI日本語コース（2026-08-22 追加）。それまでsitemapに1本も入っておらず、
    // サイト内リンクも管理画面からしか無かったので、検索から発見される経路がゼロだった
    { path: 'ai-course',                 priority: '0.9', freq: 'weekly' },
    // /ai-course/shoko・/yuto は**載せない**（2026-08-23）。
    // 広告用のvariant LPで noindex,follow を出しているため、sitemapに載せると
    // Search Console が「送信されたURLがnoindexです」で毎回エラーを出す（自分で作った矛盾）。
    { path: 'ai-course/terms',           priority: '0.3', freq: 'yearly' },
    { path: 'ai-course/privacy',         priority: '0.3', freq: 'yearly' },
    { path: 'ai-course/ai-disclosure',   priority: '0.3', freq: 'yearly' },
    { path: 'ai-course/tokushoho',       priority: '0.3', freq: 'yearly' },
    { path: 'ai-course/cancel-policy',   priority: '0.3', freq: 'yearly' },
    { path: 'ai-course/data-deletion',   priority: '0.3', freq: 'yearly' },
    { path: 'ai-course/account-deletion', priority: '0.3', freq: 'yearly' },
    { path: 'ai-course/contact',         priority: '0.4', freq: 'yearly' },
  ];

  // 日本語版しか中身が無いURL（中国語URLは日本語版へcanonicalしているのでsitemapには載せない）
  // security側も terms / privacy / tokushoho の3本を足していたが、
  // 上の staticUrls に同じ3本が既に入っているため重複追加はしない
  const jaOnlyUrls = [
    { path: 'blog', priority: '0.7', freq: 'weekly' },
  ];

  const langs = ['ja', 'zh'];
  let urls = '';

  // Supabase REST API で公開中の大会・通常活動を取得（失敗しても静的URLは返す）
  let tournaments = [];
  let activities = [];
  let posts = [];
  // 中国語本文がある記事（/zh/blog/:id をsitemapに載せてよい記事）
  let zhPosts = [];
  try {
    const supabaseUrl = env.VITE_SUPABASE_URL || env.SUPABASE_URL || '';
    const supabaseKey = env.VITE_SUPABASE_ANON_KEY || env.SUPABASE_ANON_KEY || '';
    if (supabaseUrl && supabaseKey) {
      const headers = {
        apikey: supabaseKey,
        Authorization: 'Bearer ' + supabaseKey,
      };
      const res = await fetch(
        supabaseUrl + '/rest/v1/tournaments?select=id,updated_at&visibility=eq.published',
        { headers }
      );
      if (res.ok) tournaments = await res.json();

      // 開催予定の通常活動（キャンセル・アーカイブ済みを除く）
      const today = new Date().toISOString().slice(0, 10);
      const actRes = await fetch(
        supabaseUrl + '/rest/v1/activities?select=id,date&status=neq.cancelled&archived_at=is.null&date=gte.' + today,
        { headers }
      );
      if (actRes.ok) activities = await actRes.json();

      // 公開済みのブログ記事（2026-08-23 追加）。それまで一覧だけがsitemapにあり、
      // 記事そのものは1本も載っていなかった＝大会レポートが検索に出る経路が無かった
      const postRes = await fetch(
        // 公開判定は画面（useBlogPosts）と同じにする:
        // status が published か NULL（旧データはNULL）で、published_at が現在以前
        supabaseUrl + '/rest/v1/blog_posts?select=id,updated_at,created_at'
          + '&or=(status.eq.published,status.is.null)'
          + '&published_at=lte.' + new Date().toISOString()
          + '&order=created_at.desc&limit=500',
        { headers }
      );
      if (postRes.ok) posts = await postRes.json();

      // 中国語本文がある記事だけ /zh/blog/:id も送る（2026-08-25）。
      // 未訳の記事は canonical を /ja/blog/:id へ寄せているので、送ると
      // Search Console が「送信されたURLに正規URLとして別のページが選択されています」を出す。
      // ⚠️ content_zh 列が無い環境（migration適用前・staging未適用）では 400 が返る。
      //    そのときは zh は0件のまま進む＝**日本語のsitemapは今までどおり出る**。
      const zhRes = await fetch(
        supabaseUrl + '/rest/v1/blog_posts?select=id,updated_at,created_at'
          + '&or=(status.eq.published,status.is.null)'
          + '&published_at=lte.' + new Date().toISOString()
          + '&content_zh=not.is.null&content_zh=not.eq.'
          + '&order=created_at.desc&limit=500',
        { headers }
      );
      if (zhRes.ok) zhPosts = await zhRes.json();
    }
  } catch (_) {}

  for (const p of posts) {
    const lm = (p.updated_at || p.created_at || '').slice(0, 10);
    urls += '\\n  <url>\\n    <loc>https://kawabado.com/ja/blog/' + p.id + '</loc>' + (lm ? '\\n    <lastmod>' + lm + '</lastmod>' : '') + '\\n    <changefreq>monthly</changefreq>\\n    <priority>0.6</priority>\\n  </url>';
  }
  for (const p of zhPosts) {
    const lm = (p.updated_at || p.created_at || '').slice(0, 10);
    urls += '\\n  <url>\\n    <loc>https://kawabado.com/zh/blog/' + p.id + '</loc>' + (lm ? '\\n    <lastmod>' + lm + '</lastmod>' : '') + '\\n    <changefreq>monthly</changefreq>\\n    <priority>0.6</priority>\\n  </url>';
  }
  for (const u of jaOnlyUrls) {
    urls += '\\n  <url>\\n    <loc>https://kawabado.com/ja/' + u.path + '</loc>\\n    <changefreq>' + u.freq + '</changefreq>\\n    <priority>' + u.priority + '</priority>\\n  </url>';
  }

  for (const lang of langs) {
    for (const u of staticUrls) {
      const loc = u.path === ''
        ? 'https://kawabado.com/' + lang + '/'
        : 'https://kawabado.com/' + lang + '/' + u.path;
      urls += '\\n  <url>\\n    <loc>' + loc + '</loc>\\n    <changefreq>' + u.freq + '</changefreq>\\n    <priority>' + u.priority + '</priority>\\n  </url>';
    }
    for (const t of tournaments) {
      const lastmod = t.updated_at ? t.updated_at.slice(0, 10) : '';
      urls += '\\n  <url>\\n    <loc>https://kawabado.com/' + lang + '/tournaments/' + t.id + '</loc>' + (lastmod ? '\\n    <lastmod>' + lastmod + '</lastmod>' : '') + '\\n    <changefreq>daily</changefreq>\\n    <priority>0.9</priority>\\n  </url>';
    }
    for (const a of activities) {
      urls += '\\n  <url>\\n    <loc>https://kawabado.com/' + lang + '/activity/' + a.id + '</loc>\\n    <changefreq>daily</changefreq>\\n    <priority>0.8</priority>\\n  </url>';
    }
  }

  return '<?xml version="1.0" encoding="UTF-8"?>\\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' + urls + '\\n</urlset>';
}

// ── ページ別OGP（LINE/WeChat/X等のクローラーはJSを実行しないため、Worker側で差し込む） ──

/**
 * 静的ページのtitle/description。src/lib/seo/staticSeo.json が正。
 * キーは /:lang/ 以降のパス（'' はトップ）。staticSeo.test.ts がJSONと画面の一致を見る。
 */
const STATIC_SEO = ${STATIC_SEO_JSON};

const SITE = 'https://kawabado.com';

// ══ プリレンダ本文（2026-08-24） ══
//
// 【なぜ要るか】
// 本番実測: kawabado.com の素のHTMLは全ページ「1,692B・可視テキスト0文字・h1が0個・JSON-LDが0個」。
// Workerが差し込んでいたのは <head> だけで、**中身は1文字も配っていなかった**。
// robots.txt では GPTBot・ClaudeBot・PerplexityBot など16種のAIクローラーを明示Allowしているのに、
// そのクローラーが取得する本文が0文字＝許可だけして何も渡していない状態だった。
// 自社内の反証もある: wild-flow.com/animalflow は静的HTMLで可視テキスト2,270文字あり、実際に読まれている。
//
// 【なぜ #root の外に置くか】
// src/main.tsx は hydrateRoot ではなく createRoot().render() を使う。
// #root の中に本文を入れると React の初回コミットで捨てられる（ちらつき・警告の恐れ）ので、
// #root には触らず**その手前**に別のコンテナとして置く。main.tsx を変更せずに済む形を選んだ。
//
// 【なぜ hidden / display:none にしないか】
// クローラーにだけ見せる隠しテキストは Google が嫌う。ここは人にも見える普通の本文として出し、
// React が最初の描画をした瞬間にJSが消す（JSが動かない環境では残る＝真っ白より良い）。
// 中身は画面と同じ事実だけ。src/lib/seo/staticSeo.json が正で、金額は画面ソースと突き合わせている。

/** プリレンダ本文に添えるサイト内リンク。素のHTMLに <a> が1本も無いとクローラーは巡回できない */
const NAV = [
  { path: '',                          ja: '川口・蕨バドミントン交流会 トップ', zh: '川口・蕨羽毛球交流会 首页' },
  { path: 'activity',                  ja: '通常活動 一覧',                     zh: '常规活动列表' },
  { path: 'tournaments/singles',       ja: 'シングルス大会',                    zh: '单打比赛' },
  { path: 'tournaments/doubles',       ja: 'ダブルス大会',                      zh: '双打比赛' },
  { path: 'tournaments/mixed-doubles', ja: 'ミックスダブルス大会',              zh: '混合双打比赛' },
  { path: 'international',             ja: '国際交流バドミントン',              zh: '国际交流羽毛球' },
  { path: 'kawaguchi',                 ja: '川口市のバドミントンサークル',      zh: '川口市的羽毛球社团' },
  { path: 'toda',                      ja: '戸田からのアクセス',                zh: '从户田出发的交通' },
  { path: 'about',                     ja: 'カワバドについて（主催者）',        zh: '关于kawabado（主办人）' },
  { path: 'tournaments',               ja: '大会一覧',                          zh: '赛事一览' },
  { path: 'level-guide',               ja: 'クラス分け案内',                    zh: '级别说明' },
  { path: 'venues',                    ja: '会場ガイド',                        zh: '会场指南' },
  { path: 'faq',                       ja: 'よくある質問',                      zh: '常见问题' },
  // ブログ一覧は canonical を /ja/blog へ寄せたまま（2026-08-25 時点。記事ごとの中国語版は
  // /zh/blog/:id が自己参照canonicalになる）。クローラー向けのこのリンクは正規URLへ送る
  { path: 'blog',                      ja: 'ブログ',                            zh: '博客', jaOnly: true },
  { path: 'join',                      ja: '特典登録',                          zh: '优惠注册' },
  { path: 'contact',                   ja: 'お問い合わせ',                      zh: '联系我们' },
  { path: 'cancel-policy',             ja: 'キャンセルポリシー',                zh: '取消政策' },
  { path: 'tokushoho',                 ja: '特定商取引法に基づく表記',          zh: '基于特定商业交易法的标示' },
  { path: 'privacy',                   ja: 'プライバシーポリシー',              zh: '隐私政策' },
  { path: 'terms',                     ja: '利用規約',                          zh: '使用条款' },
];

/**
 * 実体（エンティティ）情報。src/pages/HomePage.tsx の orgJsonLd と**同じ内容**を持つ。
 * Workerはビルド時に埋め込む独立ファイルなので import できない。
 * ズレたら workerPrerender.test.mjs が落ちる（片方だけ直す事故を防ぐ）。
 */
/**
 * 公式SNS等のプロフィールURL。src/lib/seo/brandSameAs.ts の BRAND_SAME_AS と**同じ内容**。
 * Workerは独立ファイルなのでimportできない。ズレたら seoConventions.test.mjs が落ちる。
 * 実在が確認できたURLだけ入れること（判断基準: docs/seo/brand-entity-signals.md）。
 */
const BRAND_SAME_AS = ['https://x.com/kawabado'];

const ORG_JSONLD = {
  '@context': 'https://schema.org',
  // 空のあいだは sameAs キーごと出さない（空配列は「SNSが無い」という主張になる）
  ...(BRAND_SAME_AS.length > 0 ? { sameAs: BRAND_SAME_AS } : {}),
  // SportsClub（＝LocalBusiness のサブタイプ）を足した（2026-08-28）。
  // 別ノードを立てず1つの @id のままにする理由は HomePage.tsx のコメント参照
  '@type': ['Organization', 'SportsOrganization', 'SportsClub'],
  '@id': 'https://kawabado.com/#organization',
  name: '川口・蕨バドミントン交流会',
  alternateName: ['kawabado', 'カワバド', '川口・蕨羽毛球交流会'],
  url: 'https://kawabado.com',
  logo: { '@type': 'ImageObject', url: 'https://kawabado.com/favicon.png' },
  image: 'https://kawabado.com/ogp-v2.jpg',
  description: '埼玉県川口市・蕨市で平日夜に開催するバドミントン交流会。'
    + '超初級からオープンまで全レベルが対象で、1人での参加が中心。'
    + '多国籍のメンバーが参加し、中国語での問い合わせ・申し込みにも対応しています。',
  email: 'info@kawabado.com',
  sport: 'バドミントン',
  // 団体の address は書かない（特商法ページが「住所は請求があれば開示」と名乗っているため）。
  // 住所は会場（location）の側にだけ持たせる。理由の全文は HomePage.tsx のコメント
  location: [
    {
      '@type': 'SportsActivityLocation',
      name: '芝園公民館',
      address: { '@type': 'PostalAddress', streetAddress: '芝園町3-15', addressLocality: '川口市', addressRegion: '埼玉県', addressCountry: 'JP' },
    },
    {
      '@type': 'SportsActivityLocation',
      name: '蕨市民体育館',
      address: { '@type': 'PostalAddress', streetAddress: '北町1-27-15', addressLocality: '蕨市', addressRegion: '埼玉県', addressCountry: 'JP' },
    },
  ],
  areaServed: [
    { '@type': 'City', name: '川口市', address: { '@type': 'PostalAddress', addressRegion: '埼玉県', addressCountry: 'JP' } },
    { '@type': 'City', name: '蕨市', address: { '@type': 'PostalAddress', addressRegion: '埼玉県', addressCountry: 'JP' } },
    { '@type': 'City', name: '戸田市', address: { '@type': 'PostalAddress', addressRegion: '埼玉県', addressCountry: 'JP' } },
  ],
  knowsLanguage: ['ja', 'zh-Hans'],
  contactPoint: {
    '@type': 'ContactPoint',
    contactType: 'customer support',
    email: 'info@kawabado.com',
    availableLanguage: ['Japanese', 'Chinese'],
    url: 'https://kawabado.com/ja/contact',
  },
};

const WEBSITE_JSONLD = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  '@id': 'https://kawabado.com/#website',
  name: '川口・蕨バドミントン交流会',
  url: 'https://kawabado.com',
  inLanguage: ['ja', 'zh'],
  publisher: { '@id': 'https://kawabado.com/#organization' },
};

/** 会場。src/pages/VenueGuidePage.tsx の VENUES と同じ（officialName / locality / street / image） */
const VENUES = [
  { id: 'shibaen-kouminkan', officialName: '芝園公民館',     locality: '川口市', street: '芝園町3-15',   image: '/venues/shibaen-kouminkan.jpg' },
  { id: 'warabi-taiikukan',  officialName: '蕨市民体育館',   locality: '蕨市',   street: '北町1-27-15',  image: '/venues/warabi-taiikukan.jpg' },
];

function venuesJsonLd(lang) {
  return VENUES.map(function (v) {
    return {
      '@context': 'https://schema.org',
      '@type': 'SportsActivityLocation',
      '@id': SITE + '/' + lang + '/venues#' + v.id,
      name: v.officialName,
      image: SITE + v.image,
      address: {
        '@type': 'PostalAddress',
        streetAddress: v.street,
        addressLocality: v.locality,
        addressRegion: '埼玉県',
        addressCountry: 'JP',
      },
      containedInPlace: { '@type': 'AdministrativeArea', name: v.locality },
    };
  });
}

function breadcrumbJsonLd(lang, name, path) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: lang === 'zh' ? '首页' : 'ホーム', item: SITE + '/' + lang + '/' },
      { '@type': 'ListItem', position: 2, name: name, item: SITE + path },
    ],
  };
}

/**
 * ブログ記事の BlogPosting（2026-08-31 追加）。
 *
 * 【なぜ要るか】
 * 画面側（src/pages/BlogDetailPage.tsx の articleSchema）は前から BlogPosting を出していたが、
 * **素のHTMLには BreadcrumbList しか入っていなかった**。
 * Google は JS を実行するので影響が無く、実測するまで誰も気づけない状態だった。
 * 一方 WeChat・小紅書・Baidu・GPTBot は素のHTMLしか見ないので、
 * これらから見ると「記事である」ことすら名乗れていなかった。
 *
 * 【画面側と同じ形にすること】
 * 同じURLで2つの BlogPosting が食い違うと、どちらが本当か分からなくなる。
 * BlogDetailPage.tsx の articleSchema を変えたらこちらも直す。
 * src/lib/seo/seoConventions.test.mjs が両者のキーの一致を見ている。
 */
function blogPostingJsonLd(o) {
  const published = o.publishedAt || o.createdAt || null;
  return Object.assign({
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: o.title,
    description: o.description,
    // 本文の言語を名乗る（UIの言語ではない）。中国語URLでも本文が日本語なら ja
    inLanguage: o.lang,
    mainEntityOfPage: o.canonical,
    publisher: { '@id': SITE + '/#organization' },
  },
  published ? { datePublished: published } : {},
  o.updatedAt || published ? { dateModified: o.updatedAt || published } : {},
  o.image ? { image: o.image } : {});
}

function faqJsonLd(items) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: items.map(function (q) {
      return { '@type': 'Question', name: q.q, acceptedAnswer: { '@type': 'Answer', text: q.a } };
    }),
  };
}

/** SportsEvent。src/components/seo/EventSchema.tsx と同じ形（大会詳細・通常活動詳細） */
function eventJsonLd(o) {
  const e = {
    '@context': 'https://schema.org',
    '@type': 'SportsEvent',
    name: o.name,
    startDate: o.startDate,
    endDate: o.endDate,
    eventStatus: 'https://schema.org/' + (o.eventStatus || 'EventScheduled'),
    eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode',
    location: {
      '@type': 'Place',
      name: o.locationName,
      address: {
        '@type': 'PostalAddress',
        streetAddress: o.streetAddress || undefined,
        addressRegion: '埼玉県',
        addressCountry: 'JP',
      },
    },
    organizer: { '@type': 'Organization', name: '川口・蕨バドミントン交流会（kawabado）', url: SITE },
    performer: { '@type': 'PerformingGroup', name: '川口・蕨バドミントン交流会（kawabado）' },
    offers: {
      '@type': 'Offer',
      price: o.price,
      priceCurrency: 'JPY',
      availability: 'https://schema.org/' + (o.availability || 'InStock'),
      url: o.url,
    },
  };
  if (o.description) e.description = o.description;
  return e;
}

/**
 * JSON-LD を素のHTMLに出す。data-kb-prerender を付けておき、
 * React が描画した瞬間に消す（React側は Helmet が同じ内容を入れるので**二重にならない**）。
 * '<' を \\u003c に置き換えるのは </script> でHTMLを閉じてしまう事故を防ぐため（JSONとしては同値）。
 */
function jsonLdTags(list) {
  if (!list || !list.length) return '';
  return list.map(function (o) {
    return '<script type="application/ld+json" data-kb-prerender>'
      + JSON.stringify(o).replace(/</g, '\\\\u003c')
      + '</script>';
  }).join('\\n    ');
}

const PRERENDER_STYLE = 'max-width:44rem;margin:0 auto;padding:1.5rem 1rem;'
  + 'font-family:system-ui,sans-serif;line-height:1.9;color:#1f2937';

/**
 * React の初回描画でプリレンダ本文とJSON-LDを消すスクリプト。
 *
 * 【なぜ MutationObserver か（ちらつきが出ない理由）】
 * MutationObserver のコールバックは、変更を起こしたタスクの**末尾のマイクロタスク**で走る。
 * ブラウザの描画はタスク＋マイクロタスクの後なので、
 * 「Reactの中身とプリレンダ本文が両方見えている状態」は一度も描画されない。
 * ＝レイアウトシフト（CLS）にならない。setTimeout にすると1フレーム挟まって見える。
 *
 * 【なぜタイムアウトで消さないか】
 * JSが落ちて React が描けなかったとき、本文が残っていれば真っ白ではなく読める画面になる。
 * 時間で消すと、そのとき最悪の状態（何も無い画面）になる。
 *
 * 【なぜ head の JSON-LD も消すか】
 * React側（Helmet）が同じ構造化データを入れる。両方残すと二重になるので、
 * 描画された時点でこちら側を引っ込める。JSを実行しないクローラーには残る。
 */
const PRERENDER_CLEANUP = '<script>(function(){'
  + 'var p=document.getElementById("kb-prerender"),r=document.getElementById("root");'
  + 'if(!p||!r)return;'
  + 'function drop(){'
  + 'if(p&&p.parentNode)p.parentNode.removeChild(p);'
  + 'var l=document.querySelectorAll("script[data-kb-prerender]");'
  + 'for(var i=0;i<l.length;i++){if(l[i].parentNode)l[i].parentNode.removeChild(l[i]);}'
  + '}'
  + 'if(r.firstChild){drop();return;}'
  + 'var mo=new MutationObserver(function(){mo.disconnect();drop();});'
  + 'mo.observe(r,{childList:true});'
  + '})();</script>';

function renderNav(lang, list) {
  let items = '';
  for (const n of (list || NAV)) {
    const href = '/' + (n.jaOnly ? 'ja' : lang) + '/' + n.path;
    items += '<li><a href="' + href + '">' + escAttr(n[lang] || n.ja) + '</a></li>';
  }
  return '<nav aria-label="' + (lang === 'zh' ? '站点导航' : 'サイト内リンク') + '"><ul>' + items + '</ul></nav>';
}

/** staticSeo.json の body（h1 / lead / paragraphs / facts / faq）をHTMLにする */
function renderBodyHtml(body, lang) {
  if (!body || !body.h1) return '';
  let h = '<h1>' + escAttr(body.h1) + '</h1>';
  if (body.lead) h += '<p>' + escAttr(body.lead) + '</p>';
  const paras = body.paragraphs || [];
  for (const p of paras) h += '<p>' + escAttr(p) + '</p>';
  const facts = body.facts || [];
  if (facts.length) {
    h += '<dl>';
    for (const f of facts) h += '<dt>' + escAttr(f.label) + '</dt><dd>' + escAttr(f.value) + '</dd>';
    h += '</dl>';
  }
  const faq = body.faq || [];
  if (faq.length) {
    h += '<section><h2>' + (lang === 'zh' ? '常见问题' : 'よくある質問') + '</h2>';
    for (const q of faq) h += '<h3>' + escAttr(q.q) + '</h3><p>' + escAttr(q.a) + '</p>';
    h += '</section>';
  }
  return h;
}

/** HTML本文（ブログ記事など）をプレーンな段落配列にする。素のHTMLへ入れるのは要約ではなく本文そのもの */
function htmlToParagraphs(html, limit) {
  const text = String(html || '')
    .replace(/<(script|style)[^>]*>[\\s\\S]*?<\\/\\1>/gi, ' ')
    .replace(/<\\/(p|div|li|h[1-6]|blockquote|tr)>/gi, '\\n')
    .replace(/<br\\s*\\/?>/gi, '\\n')
    .replace(/<[^>]*>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"');
  const out = [];
  let total = 0;
  for (const line of text.split('\\n')) {
    const s = line.replace(/[ \\t]+/g, ' ').trim();
    if (!s) continue;
    if (total + s.length > (limit || 1200)) break;
    out.push(s);
    total += s.length;
  }
  return out;
}

/** 販売LPの本文。<noscript> として素のHTMLへ入れる（ブラウザでは描画されない） */
const LP_PRERENDER = ${LP_PRERENDER_JSON};

/** noscript の中に置く本文を組む。**実際のページと同じ内容**（クローキングにしない） */
function lpNoscriptHtml(lang) {
  const doc = LP_PRERENDER[lang] || LP_PRERENDER.ja;
  if (!doc) return '';
  let html = '<h1>' + escAttr(doc.title) + '</h1>';
  for (const b of doc.blocks) {
    if (b.h) html += '<h2>' + escAttr(b.h) + '</h2>';
    for (const line of (b.p || [])) html += '<p>' + escAttr(line) + '</p>';
  }
  return '<noscript><div id="lp-content">' + html + '</div></noscript>';
}

/** 検索結果に出さないURL。src/components/seo/privateRoutes.ts と同じ並び（テストで突き合わせる） */
const PRIVATE_PATTERNS = [
  /^\\/(ja|zh)\\/admin(\\/|$)/,
  /^\\/(ja|zh)\\/mypage(\\/|$)/,
  /^\\/(ja|zh)\\/ai-course\\/admin(\\/|$)/,
  /^\\/(ja|zh)\\/ai-course\\/login(\\/|$)/,
  /^\\/(ja|zh)\\/ai-course\\/purchase(\\/|$)/,
  /^\\/(ja|zh)\\/login(\\/|$)/,
  /^\\/(ja|zh)\\/signup(\\/|$)/,
  /^\\/(ja|zh)\\/auth-landing(\\/|$)/,
  /^\\/(ja|zh)\\/password-reset/,
  /^\\/(ja|zh)\\/ai-lesson-demo(\\/|$)/,
  /^\\/(ja|zh)\\/tactics-board(\\/|$)/,
  /^\\/cancel(\\/|$)/,
  /^\\/internal(\\/|$)/,
  /^\\/chaoxianzu(\\/|$)/,
  /^\\/assistant(\\/|$)/,
  /^\\/admin(\\/|$)/,
];
const isPrivatePath = (pathname) => PRIVATE_PATTERNS.some((re) => re.test(pathname));

/**
 * 既知のURLの1階層目（2026-08-24）。src/App.tsx の Route と対応する。
 *
 * 【なぜ要るか】
 * 実測で /ja/this-does-not-exist-99999 が HTTP 200 でSPAシェルを返していた。
 * 存在しないURLが無限にインデックス可能＝ソフト404。React側は NotFoundPage が
 * noindex を出すが、それはJS実行後で、JSを実行しないクローラーには何も伝わらない。
 *
 * 【なぜ404ではなく noindex にしたか】
 * ステータスを404に変えると、この列挙をひとつ漏らしただけで実在ページが
 * 「見つからない」扱いになる。noindex は検索に出さないだけで画面は今までどおり動くので、
 * 万一漏らしてもユーザーへの影響が無い。列挙の網羅性は
 * src/lib/seo/workerPrerender.test.mjs が src/App.tsx の Route と突き合わせて守る。
 */
const KNOWN_LEAVES = [
  'activity', 'activity-cn', 'tournaments', 'faq', 'venues', 'international', 'contact',
  // 地域ページ（2026-08-28）
  'kawaguchi', 'toda',
  // 主催者ページ（2026-08-31）
  'about',
  'level-guide', 'cancel-policy', 'tokushoho', 'privacy', 'terms', 'admin', 'blog', 'join',
  'shuttle-roadmap', 'tactics-board', 'game', 'mypage', 'ai-lesson-demo', 'ai-course',
  'auth-landing', 'login', 'signup', 'password-reset', 'password-reset-form',
  'password-reset-success', 'results',
];

function isKnownPath(pathname) {
  if (pathname === '/' || pathname === '') return true;
  // 差し込み対象になっているURLは当然既知
  if (matchOgpRoute(pathname)) return true;
  // 限定公開の静的HTML・言語によらないページ・別グループ
  if (pathname.startsWith('/guide/')) return true;
  if (/^\\/(cancel|internal|chaoxianzu|assistant)(\\/|$)/.test(pathname)) return true;
  const seg = pathname.replace(/^\\/+|\\/+$/g, '').split('/');
  if (seg[0] === 'ja' || seg[0] === 'zh') {
    if (seg.length === 1) return true;
    return KNOWN_LEAVES.indexOf(seg[1]) !== -1;
  }
  // 旧URL（/activity・/blog/12 など。Reactが /ja/ へリダイレクトする）
  return KNOWN_LEAVES.indexOf(seg[0]) !== -1;
}

function matchOgpRoute(pathname) {
  // ルート（/）。Reactは /ja/ へリダイレクトするが、素のHTMLには canonical が無く、
  // https://kawabado.com/ と /ja/ が両方200で別メタ＝トップが2URLに割れていた（本番実測）。
  // ここで /ja/ を指す canonical を入れて1本に寄せる（hreflangは出さない＝自己参照でないため）
  if (pathname === '/') return { kind: 'static', lang: 'ja', page: '', root: true };
  let m = pathname.match(/^\\/(ja|zh)\\/tournaments\\/(\\d+)\\/?$/);
  if (m) return { kind: 'tournament', lang: m[1], id: m[2] };
  m = pathname.match(/^\\/tournaments\\/(\\d+)\\/?$/);
  if (m) return { kind: 'tournament', lang: 'ja', id: m[1] };
  // 通常活動の詳細（2026-08-24）。tournaments と blog の数字IDしか見ていなかったため、
  // 活動1件ごとのURLは素のHTMLがトップの文言のまま・本文0文字だった（sitemapには載せていた）
  m = pathname.match(/^\\/(ja|zh)\\/activity\\/([0-9a-zA-Z-]{1,64})\\/?$/);
  if (m) return { kind: 'activity', lang: m[1], id: m[2] };
  m = pathname.match(/^\\/(ja|zh)\\/blog\\/(\\d+)\\/?$/);
  if (m) return { kind: 'blog', lang: m[1], id: m[2] };
  m = pathname.match(/^\\/blog\\/(\\d+)\\/?$/);
  if (m) return { kind: 'blog', lang: 'ja', id: m[1] };
  // AI日本語コースのLP（2026-08-22）。SEOタグはreact-helmet-asyncで入るが、
  // WeChat/LINE/X のクローラーはJSを実行しないので、素のHTMLがバドミントンのまま出ていた。
  // ここで差し込まないと、コースのURLを共有するたびに「川口・蕨バドミントン交流会」と表示される
  m = pathname.match(/^\\/(ja|zh)\\/ai-course\\/?$/);
  if (m) return { kind: 'aiCourse', lang: m[1] };
  m = pathname.match(/^\\/(ja|zh)\\/ai-course\\/(shoko|yuto)\\/?$/);
  if (m) return { kind: 'aiCourse', lang: m[1], variant: m[2] };
  m = pathname.match(/^\\/(ja|zh)\\/ai-course\\/([a-z-]+)\\/?$/);
  if (m && AI_COURSE_LEGAL[m[2]]) return { kind: 'aiCourseLegal', lang: m[1], page: m[2] };
  // 静的ページ（トップ・通常活動・FAQ・クラス案内・会場・問い合わせ・特典登録・
  // キャンセルポリシー・ブログ一覧）。2026-08-23まで素のHTMLが全ページ
  // 「川口・蕨バドミントン交流会」＋ <html lang="ja"> のままで、
  // 中国語ページを微信・小紅書でシェアすると日本語のカードが出ていた
  m = pathname.match(/^\\/(ja|zh)\\/?$/);
  if (m) return { kind: 'static', lang: m[1], page: '' };
  m = pathname.match(/^\\/(ja|zh)\\/([a-z-]+)\\/?$/);
  if (m && STATIC_SEO[m[2]]) return { kind: 'static', lang: m[1], page: m[2] };
  // 2階層の静的ページ（種目別ページ tournaments/singles・大会結果 results/vol3 など・2026-08-24）。
  // 1階層しか見ていなかったため、素のHTMLがトップの文言のまま配られていた。
  // 2つめのセグメントに数字を許すのは results/vol1..3 のため（[a-z-]+ ではマッチしなかった）
  m = pathname.match(/^\\/(ja|zh)\\/([a-z-]+\\/[a-z0-9-]+)\\/?$/);
  if (m && STATIC_SEO[m[2]]) return { kind: 'static', lang: m[1], page: m[2] };
  return null;
}

/**
 * AIコースLPのSEO文言。src/pages/ai-lesson/landing/lpContent.ts の seo と**同じ内容**を持つ。
 * Workerは生成時に埋め込む独立ファイルなのでimportできない。
 * ズレたら workerAiCourseOgp.test.ts が落ちる（片方だけ直す事故を防ぐ）。
 */
const AI_COURSE_SEO = {
  shoko: {
    ja: {
      title: '翔子先生とAI日本語会話コース｜読めるのに話せないを、半年で終わらせる',
      description: '文法は分かるのに話せない中国語話者へ。AI先生との毎日の会話と、日本語コーチの個別レッスン24回で、日本で使える日本語を半年で育てます。600円のAI体験パスから始められます。',
    },
    zh: {
      title: '翔子老师 · AI日语会话陪跑课程｜用半年，告别「看得懂却说不出」',
      description: '献给「懂语法却说不出口」的中文母语者。AI老师每天陪你练习，加上真人日语教练24次一对一，用半年培养在日本真正能用的日语。可以先从600日元的AI体验通行证开始。',
    },
    ogImage: '/images/ai-course/shoko-sensei-wave.webp',
  },
  yuto: {
    ja: {
      title: '悠斗先生とAI日本語会話コース｜読めるのに話せないを、半年で終わらせる',
      description: '文法は分かるのに話せない中国語話者へ。AI先生との毎日の会話と、日本語コーチの個別レッスン24回で、日本で使える日本語を半年で育てます。600円のAI体験パスから始められます。',
    },
    zh: {
      title: '悠斗老师 · AI日语会话陪跑课程｜用半年，告别「看得懂却说不出」',
      description: '献给「懂语法却说不出口」的中文母语者。AI老师每天陪你练习，加上真人日语教练24次一对一，用半年培养在日本真正能用的日语。可以先从600日元的AI体验通行证开始。',
    },
    ogImage: '/images/ai-course/yuto-sensei-wave.webp',
  },
};

/**
 * AIコースの法務ページのタイトル。src/lib/aiLesson/course/legal/legalContent.ts と同じ。
 * sitemapに載せる以上、12ページが同じ「川口・蕨バドミントン交流会」で出てはいけない
 * （同一タイトルの重複ページとして扱われる）。ズレは workerAiCourseOgp.test.ts が見る。
 */
const AI_COURSE_LEGAL = {
  'terms':            { ja: '利用規約',                 zh: '使用条款' },
  'privacy':          { ja: 'プライバシーポリシー',     zh: '隐私政策' },
  'ai-disclosure':    { ja: 'AIの利用について',         zh: '关于AI的使用' },
  'tokushoho':        { ja: '特定商取引法に基づく表記', zh: '基于特定商业交易法的标示' },
  'cancel-policy':    { ja: 'キャンセル・返金について', zh: '关于取消与退款' },
  'data-deletion':    { ja: '学習データの削除',         zh: '学习数据的删除' },
  'account-deletion': { ja: 'アカウントの削除',         zh: '删除账号' },
  'contact':          { ja: 'お問い合わせ',             zh: '联系我们' },
};
const AI_COURSE_SUFFIX = { ja: 'AI日本語会話コース', zh: 'AI日语会话课程' };

async function fetchFirst(env, path) {
  const supabaseUrl = env.VITE_SUPABASE_URL || env.SUPABASE_URL || '';
  const key = env.VITE_SUPABASE_ANON_KEY || env.SUPABASE_ANON_KEY || '';
  if (!supabaseUrl || !key) return null;
  const res = await fetch(supabaseUrl + path, {
    headers: { apikey: key, Authorization: 'Bearer ' + key },
  });
  if (!res.ok) return null;
  const rows = await res.json();
  return Array.isArray(rows) && rows.length ? rows[0] : null;
}

function escAttr(s) {
  return String(s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function injectOgp(meta) {
  let html = INDEX_HTML
    .replace(/<title>[^<]*<\\/title>/, '<title>' + escAttr(meta.title) + '</title>')
    .replace(/(<meta name="description" content=")[^"]*(")/, '$1' + escAttr(meta.description) + '$2')
    .replace(/(<meta property="og:title" content=")[^"]*(")/, '$1' + escAttr(meta.title) + '$2')
    .replace(/(<meta property="og:description" content=")[^"]*(")/, '$1' + escAttr(meta.description) + '$2');
  if (meta.image) {
    html = html
      .replace(/(<meta property="og:image" content=")[^"]*(")/, '$1' + escAttr(meta.image) + '$2')
      .replace(/(<meta name="twitter:image" content=")[^"]*(")/, '$1' + escAttr(meta.image) + '$2');
  }
  // <html lang> と og:locale（素のHTMLは全ページ ja 固定だった）
  if (meta.lang === 'zh') {
    html = html
      .replace('<html lang="ja">', '<html lang="zh">')
      .replace(/(<meta property="og:locale" content=")[^"]*(")/, '$1zh_CN$2');
  }
  let tail = '<meta property="og:url" content="' + escAttr(meta.url) + '" />';
  // LCP画像のpreload（security側）。ブログのカバー画像など、そのページのLCPになる画像を
  // HTML段階で先読みさせる。JSON-LDやhreflangより先に置いて、発見を早める
  if (meta.imagePreload) {
    tail += '\\n    ' + meta.imagePreload;
  }
  // 販売LPだけ、本文を <noscript> で入れる（JSを実行しないクローラー向け）
  if (meta.noscriptHtml) {
    html = html.replace('</body>', meta.noscriptHtml + '\\n  </body>');
  }
  if (meta.alternates) {
    tail += '\\n    <link rel="alternate" hreflang="ja" href="' + escAttr(meta.alternates.ja) + '" />';
    tail += '\\n    <link rel="alternate" hreflang="zh" href="' + escAttr(meta.alternates.zh) + '" />';
    tail += '\\n    <link rel="alternate" hreflang="x-default" href="' + escAttr(meta.alternates.ja) + '" />';
  }
  // canonical（2026-08-22）。JS実行前のHTMLにも入れておく。
  // study.kawabado.com など別ホストから同じ内容が配られたときの重複も、これで本体へ寄る
  if (meta.canonical) {
    tail += '\\n    <link rel="canonical" href="' + escAttr(meta.canonical) + '" />';
  }
  // 構造化データ（2026-08-24）。React側は8種入れているが、素のHTMLは0個だった
  const ld = jsonLdTags(meta.jsonLd);
  if (ld) tail += '\\n    ' + ld;
  html = html.replace('</head>', function () { return tail + '\\n  </head>'; });

  // プリレンダ本文。#root には触らず、その手前に置いて React の初回描画で消す。
  // 掃除スクリプトは **#root の後ろ**に置く（前に置くと実行時点で #root がまだ存在せず、
  // MutationObserver を張る相手が null になって永久に消えなくなる）
  const lang = meta.lang === 'zh' ? 'zh' : 'ja';
  const bodyHtml = renderBodyHtml(meta.body, lang);
  if (bodyHtml) {
    const block = '<div id="kb-prerender" style="' + PRERENDER_STYLE + '">'
      + bodyHtml
      + renderNav(lang, meta.nav)
      + '</div>\\n    ';
    html = html.replace(/<div id="root">\\s*<\\/div>/, function (m) {
      return block + m + '\\n    ' + PRERENDER_CLEANUP;
    });
  }
  return html;
}

const WEEKDAYS_JA = ['日', '月', '火', '水', '木', '金', '土'];
const WEEKDAYS_ZH = ['日', '一', '二', '三', '四', '五', '六'];

async function buildOgpMeta(route, env, pageUrl) {
  if (route.kind === 'tournament') {
    const t = await fetchFirst(env,
      '/rest/v1/tournaments?id=eq.' + route.id +
      '&visibility=neq.draft&select=title,event_date,start_time,end_time,location,venue_address,entry_fee,level,event_type,status,description');
    if (!t || !t.event_date) return null;
    const [y, mo, d] = t.event_date.split('-');
    const wdIdx = new Date(t.event_date).getUTCDay();
    const time = (t.start_time || '').slice(0, 5) + '〜' + (t.end_time || '').slice(0, 5);
    const fee = Number(t.entry_fee || 0).toLocaleString('ja-JP');
    const lang = route.lang === 'zh' ? 'zh' : 'ja';
    const zh = lang === 'zh';
    const path = '/' + lang + '/tournaments/' + route.id;
    const dateLabel = zh
      ? y + '年' + Number(mo) + '月' + Number(d) + '日(周' + WEEKDAYS_ZH[wdIdx] + ')'
      : y + '年' + Number(mo) + '月' + Number(d) + '日(' + WEEKDAYS_JA[wdIdx] + ')';
    const title = zh
      ? t.title + '｜' + Number(mo) + '/' + Number(d) + '(周' + WEEKDAYS_ZH[wdIdx] + ')举办'
      : t.title + '｜' + Number(mo) + '/' + Number(d) + '(' + WEEKDAYS_JA[wdIdx] + ')開催';
    const description = zh
      ? '📅' + dateLabel + ' ' + time + '｜📍' + t.location + '｜💰报名费¥' + fee + '｜' + t.level + '·' + t.event_type + '。正在报名中！'
      : '📅' + dateLabel + ' ' + time + '｜📍' + t.location + '｜💰参加費¥' + fee + '｜' + t.level + '・' + t.event_type + '。申込受付中！';
    const venue = t.location + (t.venue_address ? '（' + t.venue_address + '）' : '');
    const facts = zh
      ? [
          { label: '日期', value: dateLabel },
          { label: '时间', value: time },
          { label: '会场', value: venue },
          { label: '参加费', value: '¥' + fee },
          { label: '级别', value: t.level },
          { label: '项目', value: t.event_type },
        ]
      : [
          { label: '開催日', value: dateLabel },
          { label: '時間', value: time },
          { label: '会場', value: venue },
          { label: '参加費', value: '¥' + fee },
          { label: 'クラス', value: t.level },
          { label: '種目', value: t.event_type },
        ];
    const paragraphs = htmlToParagraphs(t.description, 1200);
    const cancelled = t.status === 'cancelled';
    return {
      title: title,
      description: description,
      url: pageUrl,
      lang: lang,
      // 自己参照canonical（2026-08-24修正）。
      // それまで言語に関係なく常に /ja/tournaments/{id} を指していたのに、同じheadで
      // hreflang ja/zh/x-default を出し、sitemapは /zh/ も送っていた＝3者が矛盾していた。
      // 画面側（src/pages/TournamentDetailPage.tsx）も同時に自己参照へ直した
      canonical: SITE + path,
      alternates: {
        ja: SITE + '/ja/tournaments/' + route.id,
        zh: SITE + '/zh/tournaments/' + route.id,
      },
      body: { h1: t.title, lead: description, paragraphs: paragraphs, facts: facts },
      jsonLd: [
        eventJsonLd({
          name: t.title,
          startDate: t.event_date.slice(0, 10) + 'T' + t.start_time + '+09:00',
          endDate: t.event_date.slice(0, 10) + 'T' + t.end_time + '+09:00',
          eventStatus: cancelled ? 'EventCancelled' : 'EventScheduled',
          locationName: t.location,
          streetAddress: t.venue_address || undefined,
          price: Number(t.entry_fee || 0),
          // 残席の判定には entries の件数が要る＝クロールごとにもう1往復増える。
          // 正確な在庫はReact側の EventSchema が出す（描画された時点でこちらは消える）
          availability: cancelled ? 'SoldOut' : 'InStock',
          url: SITE + path,
          description: paragraphs.length ? paragraphs.join(' ') : description,
        }),
        breadcrumbJsonLd(lang, t.title, path),
      ],
    };
  }
  // 通常活動の詳細（2026-08-24 新設）。画面（ActivityPage）と同じ文言・同じ SportsEvent を出す
  if (route.kind === 'activity') {
    const a = await fetchFirst(env,
      '/rest/v1/activities?id=eq.' + route.id +
      '&status=neq.cancelled&archived_at=is.null&select=title,date,start_time,end_time,location,address,price');
    if (!a || !a.date) return null;
    const [y, mo, d] = a.date.split('-');
    const wdIdx = new Date(a.date).getUTCDay();
    const time = (a.start_time || '').slice(0, 5) + '〜' + (a.end_time || '').slice(0, 5);
    const lang = route.lang === 'zh' ? 'zh' : 'ja';
    const zh = lang === 'zh';
    const path = '/' + lang + '/activity/' + route.id;
    const dateLabel = zh
      ? y + '年' + Number(mo) + '月' + Number(d) + '日(周' + WEEKDAYS_ZH[wdIdx] + ')'
      : y + '年' + Number(mo) + '月' + Number(d) + '日(' + WEEKDAYS_JA[wdIdx] + ')';
    const price = Number(a.price || 0);
    const description = zh
      ? dateLabel + ' ' + time + ' 在' + a.location + '举办的羽毛球日常活动。参加费' + price + '日元（含羽毛球费用）。可通过本页面在线报名。'
      : dateLabel + ' ' + time + ' ' + a.location + 'で開催するバドミントン通常活動。参加費' + price + '円（シャトル代込み）。このページからそのまま申し込めます。';
    return {
      title: a.title + (zh ? ' | 川口・蕨羽毛球日常活动' : ' | 川口・蕨バドミントン通常活動'),
      description: description,
      url: pageUrl,
      lang: lang,
      canonical: SITE + path,
      alternates: {
        ja: SITE + '/ja/activity/' + route.id,
        zh: SITE + '/zh/activity/' + route.id,
      },
      body: {
        h1: a.title,
        lead: description,
        facts: zh
          ? [
              { label: '日期', value: dateLabel },
              { label: '时间', value: time },
              { label: '会场', value: a.location + (a.address ? '（' + a.address + '）' : '') },
              { label: '参加费', value: price + '日元（含羽毛球费用）' },
            ]
          : [
              { label: '開催日', value: dateLabel },
              { label: '時間', value: time },
              { label: '会場', value: a.location + (a.address ? '（' + a.address + '）' : '') },
              { label: '参加費', value: price + '円（シャトル代込み）' },
            ],
      },
      jsonLd: [
        eventJsonLd({
          name: a.title,
          startDate: a.date + 'T' + (a.start_time || '').slice(0, 5) + ':00+09:00',
          endDate: a.date + 'T' + (a.end_time || '').slice(0, 5) + ':00+09:00',
          locationName: a.location,
          streetAddress: a.address || undefined,
          price: price,
          availability: 'InStock',
          url: SITE + path,
          description: description,
        }),
        breadcrumbJsonLd(lang, a.title, path),
      ],
    };
  }
  if (route.kind === 'aiCourse') {
    // 先生別ページはその先生の文言で出す（LPと同じ）。canonicalは主ページへ集約
    const seo = AI_COURSE_SEO[route.variant || 'shoko'] || AI_COURSE_SEO.shoko;
    const t = seo[route.lang] || seo.ja;
    const lang = route.lang === 'zh' ? 'zh' : 'ja';
    return {
      title: t.title,
      description: t.description,
      image: 'https://kawabado.com' + seo.ogImage,
      url: pageUrl,
      lang: lang,
      canonical: 'https://kawabado.com/' + lang + '/ai-course',
      // 日中2言語ページが相互に結ばれていなかった（実測でhreflang 0個）。
      // 広告用variant（shoko/yuto）は noindex かつ canonical を主ページへ寄せているので出さない
      alternates: route.variant ? null : {
        ja: 'https://kawabado.com/ja/ai-course',
        zh: 'https://kawabado.com/zh/ai-course',
      },
      body: { h1: t.title, lead: t.description },
      nav: aiCourseNav(),
      // 素のHTML本文が212文字しかなかった問題への対応（2026-08-26）。
      // 上の body/nav は「Reactが描いたら消える見出し＋巡回用リンク」で、
      // こちらは **LPの本文そのもの**（lpContent.ts から生成）。役割が違うので両方出す
      noscriptHtml: lpNoscriptHtml(lang),
      // JSON-LD（Course）はLP側の src/pages/ai-lesson/landing/courseSchema.ts が持つ。
      // 素のHTMLにも出すと二重定義になるので、ここでは出さない
    };
  }
  if (route.kind === 'aiCourseLegal') {
    const L = AI_COURSE_LEGAL[route.page];
    const lang = route.lang === 'zh' ? 'zh' : 'ja';
    const seo = AI_COURSE_SEO.shoko[lang];
    return {
      title: L[lang] + '｜' + AI_COURSE_SUFFIX[lang],
      description: seo.description,
      image: 'https://kawabado.com' + AI_COURSE_SEO.shoko.ogImage,
      url: pageUrl,
      lang: lang,
      canonical: 'https://kawabado.com/' + lang + '/ai-course/' + route.page,
      alternates: {
        ja: 'https://kawabado.com/ja/ai-course/' + route.page,
        zh: 'https://kawabado.com/zh/ai-course/' + route.page,
      },
      // 法務文書は本文をここに写さない（写した瞬間に二重管理になり、必ず片方が古くなる）。
      // 見出しと同一サイト内のリンクだけ出して、本文はReactが描くものを正とする
      body: { h1: L[lang] },
      nav: aiCourseNav(),
    };
  }
  if (route.kind === 'static') {
    const e = STATIC_SEO[route.page];
    const t = e[route.lang] || e.ja;
    const suffix = route.page ? '/' + route.page : '/';
    // ブログ一覧は日本語のみ（記事本文に中国語版が無い）ので canonical を日本語版へ寄せる
    const jaOnly = route.page === 'blog';
    const lang = route.lang === 'zh' ? 'zh' : 'ja';
    const body = e.body ? (e.body[lang] || e.body.ja) : null;
    const path = '/' + (jaOnly ? 'ja' : lang) + suffix;
    const ld = [];
    if (route.page === '') {
      ld.push(ORG_JSONLD);
      ld.push(WEBSITE_JSONLD);
    } else {
      // ブログ一覧は canonical を日本語版へ寄せているので、パンクズも日本語側に揃える
      ld.push(breadcrumbJsonLd(jaOnly ? 'ja' : lang, body ? body.h1 : t.title, path));
      if (body && body.faq && body.faq.length) ld.push(faqJsonLd(body.faq));
      if (route.page === 'venues') {
        for (const v of venuesJsonLd(lang)) ld.push(v);
      }
    }
    return {
      title: t.title,
      description: t.description,
      // ページ固有のOGP画像。無ければサイト既定のまま（存在しない画像を指さない）
      image: e.image ? 'https://kawabado.com' + e.image : null,
      url: route.root ? 'https://kawabado.com/ja/' : pageUrl,
      // トップのLCPはヒーロー画像（security側の最適化）。
      // ⚠️ / ・/ja/ ・/zh/ はこの静的ルートに一致するので injectOgp を通る。
      //    下の HOME_PATH_RE のフォールバックまで落ちてこないため、preloadはここで渡す
      imagePreload: route.page === '' ? HERO_PRELOAD : '',
      lang: lang,
      canonical: 'https://kawabado.com' + path,
      // ルート（/）は canonical が /ja/ を指す＝自己参照でないので hreflang は出さない
      alternates: (jaOnly || route.root) ? null : {
        ja: 'https://kawabado.com/ja' + suffix,
        zh: 'https://kawabado.com/zh' + suffix,
      },
      body: body,
      jsonLd: ld,
    };
  }
  if (route.kind === 'blog') {
    // 【2026-08-28 統合メモ】中国語版の出し分けは両ブランチが別々に実装していた。
    // security側は title_zh/excerpt_zh の有無だけで中国語ページを名乗るため、
    // 本文が未訳の記事で「中国語のタイトルを開いたら日本語の本文」になる。
    // 本文（content_zh）を基準に判定するこちら側を残し、
    // security側にしか無かった LCP画像のpreload（imagePreload）をこちらへ移した。
    // title_zh / excerpt_zh / content_zh が無い環境（migration適用前）でも動くようにフォールバックする。
    // ここで落ちると記事ページの素のHTMLが**全記事**トップの文言に戻るので、黙って壊してはいけない
    /*
     * 【公開予定日より前の記事を素のHTMLに出さない（2026-08-31 追加）】
     * 画面側（useBlogPosts）と sitemap は published_at <= 現在 で絞っているのに、
     * ここだけ id で素直に引いていた。そのため**予約公開の記事が、
     * 公開日より前でも直リンクで全文読める**状態だった。
     * 一覧にも sitemap にも出ないので気づきにくいが、URLさえ分かれば読めてしまう。
     *
     * status では絞らない。unlisted（一覧に出さないがURLでは見せる）記事を
     * ここで落とすと、いま見えているものが見えなくなる。
     * published_at が NULL の旧データも従来どおり通す。
     */
    const nowIso = new Date().toISOString();
    const publishedFilter = '&or=(published_at.lte.' + nowIso + ',published_at.is.null)';
    let p = await fetchFirst(env,
      '/rest/v1/blog_posts?id=eq.' + route.id + publishedFilter
      + '&select=title,excerpt,image_url,content,title_zh,excerpt_zh,content_zh'
      + ',published_at,created_at,updated_at');
    if (!p) {
      p = await fetchFirst(env,
        '/rest/v1/blog_posts?id=eq.' + route.id + publishedFilter
        + '&select=title,excerpt,image_url,content,published_at,created_at,updated_at');
    }
    if (!p) return null;
    // 「中国語版があるか」の判定は本文だけを見る（src/pages/blogSeo.ts の hasZhBody と同じ）。
    // タイトルだけ訳して本文が日本語のままの記事を中国語版扱いにすると、
    // 中国語のタイトルを開いたら日本語の記事だった、という一番がっかりする状態になる
    const hasZh = typeof p.content_zh === 'string' && p.content_zh.trim() !== '';
    const wantZh = route.lang === 'zh';
    const zh = wantZh && hasZh;
    const lang = zh ? 'zh' : 'ja';
    const title = zh && p.title_zh ? p.title_zh : p.title;
    const excerpt = (zh && p.excerpt_zh ? p.excerpt_zh : p.excerpt) || '';
    const content = zh ? p.content_zh : p.content;
    // canonical は**その記事に中国語版があるか**で決まる（表示中の言語ではない）。
    //   中国語版あり → /ja も /zh もそれぞれ自己参照し、hreflang を出す
    //   まだ無い     → 従来どおり /ja へ寄せ、hreflang は出さない
    // 自己参照でない canonical と hreflang を併用すると矛盾する（src/pages/blogSeo.ts 冒頭）
    const path = '/' + (hasZh ? (wantZh ? 'zh' : 'ja') : 'ja') + '/blog/' + route.id;
    const coverUrl = p.image_url && /^https?:/.test(p.image_url) ? p.image_url : null;
    return {
      title: title + (zh ? '｜川口・蕨羽毛球交流会' : '｜川口・蕨バドミントン交流会'),
      description: excerpt || (zh
        ? '川口・蕨地区羽毛球交流会的活动博客'
        : '川口・蕨エリアのバドミントン交流会の活動ブログ'),
      image: coverUrl,
      // カバー画像＝このページのLCP。HTML段階で先読みさせる（security側から移植）
      imagePreload: coverUrl ? buildCoverPreload(coverUrl) : '',
      url: pageUrl,
      // 本文の言語を名乗る。中国語URLでも本文が日本語なら ja のまま（zhと名乗るのは嘘になる）
      lang: lang,
      canonical: 'https://kawabado.com' + path,
      alternates: hasZh ? {
        ja: 'https://kawabado.com/ja/blog/' + route.id,
        zh: 'https://kawabado.com/zh/blog/' + route.id,
      } : null,
      body: {
        h1: title,
        lead: excerpt,
        paragraphs: htmlToParagraphs(content, 2000),
      },
      jsonLd: [
        breadcrumbJsonLd(lang, title, path),
        // 素のHTMLにも「これは記事だ」と名乗らせる（2026-08-31）。
        // 画面側 BlogDetailPage.tsx の articleSchema と同じ内容にすること
        blogPostingJsonLd({
          title: title,
          description: excerpt || '',
          lang: lang,
          canonical: 'https://kawabado.com' + path,
          image: coverUrl,
          publishedAt: p.published_at,
          createdAt: p.created_at,
          updatedAt: p.updated_at,
        }),
      ],
    };
  }
  return null;
}

/** AIコース側のページに添えるリンク（バドミントン本体のナビを混ぜない） */
function aiCourseNav() {
  const list = [{ path: 'ai-course', ja: 'AI日本語会話コース', zh: 'AI日语会话课程' }];
  for (const key of Object.keys(AI_COURSE_LEGAL)) {
    list.push({ path: 'ai-course/' + key, ja: AI_COURSE_LEGAL[key].ja, zh: AI_COURSE_LEGAL[key].zh });
  }
  return list;
}

// 本番ホスト（これ以外＝staging・Previewデプロイ・localhostは検索エンジンから除外する）
const PRODUCTION_HOSTS = ['kawabado.com', 'www.kawabado.com'];

/* ══════════════════════════════════════════════════════════════════
   有料教材の門（2026-08-24）

   何が問題だったか:
     https://kawabado.com/assets/ai-course-vocab-content-*.js が
     認証なしで HTTP 200 / 2,080,346 bytes を返していた（実測）。
     読解・聴解と合わせて約3.2MB。¥600 / ¥2,980 / ¥100,000 で売っている
     商品の中身が、URLを叩くだけで誰でも全量ダウンロードできる状態だった。

   なぜこの形にしたか:
     本番は Cloudflare Pages Advanced mode で、**全リクエストがこのWorkerを通る**。
     したがって教材チャンクのパスだけを認証で塞げる。
     教材は AdvShell（AiCoursePage.tsx:85 で lazy import）からしか参照されず、
     dist/index.html に modulepreload も無い（実測）ので、
     ブラウザが要求する時点で学習者は必ず認証済みになっている。
     同一オリジンのモジュール取得には Cookie が送られるため、署名付きCookieが門として成立する。

   なぜ R2 にしなかったか:
     secure-runtime ブランチに R2 + サーバー採点の完成実装があるが、
     本番より src/supabase で 172 commit 古く、AdvShell.tsx の差が +2,744/-334 行、
     adventure 配下は 212ファイル・+39,626行の差がある。cherry-pick が成立しない。
     R2 配信（Step C）とサーバー採点（Step B）は別プロジェクトとして計画に残す。

   🚨 フェイルオープンが既定:
     AI_COURSE_ASSET_GATE が 'on' 以外、または署名鍵が未設定のときは門を完全に無効化する。
     本番には実生徒がいる。門の設定ミスで学習が止まるより、露出が続くほうがまだ戻せる。
     staging で確認してから CEO が 'on' にする。
   ══════════════════════════════════════════════════════════════════ */

/** 門の対象。ビルドごとにハッシュが変わるのでプレフィックス一致で見る（ハッシュを直書きしない） */
const GATED_ASSET_PREFIXES = [
  '/assets/ai-course-vocab-content-',
  '/assets/ai-course-reading-',
  '/assets/ai-course-listening-',
];

/** 通行証の寿命。長すぎると流出時の被害が伸び、短すぎると学習中に切れる */
const COURSE_PASS_TTL_MS = 6 * 60 * 60 * 1000;
const COURSE_PASS_COOKIE = 'kb_course_pass';

function coursePassB64url(bytes) {
  let s = '';
  for (const b of bytes) s += String.fromCharCode(b);
  return btoa(s).replace(/\\+/g, '-').replace(/\\//g, '_').replace(/=+\$/, '');
}

async function coursePassHmac(secret, msg) {
  const key = await crypto.subtle.importKey(
    'raw', new TextEncoder().encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']
  );
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(msg));
  return coursePassB64url(new Uint8Array(sig));
}

async function signCoursePass(sub, exp, secret) {
  const payload = coursePassB64url(new TextEncoder().encode(sub + '|' + exp));
  return payload + '.' + (await coursePassHmac(secret, payload));
}

/** 署名の比較は定数時間で行う（長さの違いは先に弾く。内容の差はループを最後まで回す） */
function coursePassEqual(a, b) {
  if (typeof a !== 'string' || typeof b !== 'string' || a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

async function verifyCoursePass(cookieHeader, secret, nowMs) {
  if (!secret) return false;
  const m = new RegExp('(?:^|;\\\\s*)' + COURSE_PASS_COOKIE + '=([^;]+)').exec(cookieHeader || '');
  if (!m) return false;
  const parts = m[1].split('.');
  if (parts.length !== 2) return false;
  const expected = await coursePassHmac(secret, parts[0]);
  if (!coursePassEqual(parts[1], expected)) return false;
  let decoded = '';
  try {
    decoded = atob(parts[0].replace(/-/g, '+').replace(/_/g, '/'));
  } catch (_) { return false; }
  const bar = decoded.lastIndexOf('|');
  if (bar < 0) return false;
  const exp = Number(decoded.slice(bar + 1));
  if (!Number.isFinite(exp) || (nowMs ?? Date.now()) > exp) return false;
  return true;
}

/**
 * 言語プレフィックスなしの旧URL → 正規URL の 301 マップ（統合 2026-08-28 で復帰）。
 *
 * 【なぜ要るか】
 * public/_redirects に同じ表があるが、_worker.js がある Pages（advanced mode）では
 * 拡張子なしのページURLは Worker が先に処理して200を返すため、_redirects の301は発動しない。
 * その結果:
 *   - /venues /join /privacy /tokushoho /terms /international /game /tactics-board
 *     /shuttle-roadmap は src/App.tsx に素のルートが無く、LangWrapper が lang="venues" 等と
 *     解釈して /ja/ トップへ飛ばす＝**着地内容が失われる**（src/components/LangWrapper.tsx L25-27）。
 *   - /blog/:id /faq /tournaments/:id 等は App.tsx の <Navigate> があるがクライアント側の
 *     ソフト遷移で、JSを実行しないクローラーと外部被リンク（minton.jp → 素の /blog/12）には
 *     301 が伝わらない。
 *
 * 【'/' を入れていない理由】
 * ルートだけは HEAD 側の判断（2026-08-24 の本番実測にもとづき、200＋/ja/ を指す canonical で
 * 1本に寄せる。matchOgpRoute の root:true 分岐と workerPrerender.test.mjs が固定）を優先する。
 * こちらの方が新しい決定なので上書きしない。
 *
 * GET/HEAD のみ対象（POST 等の処理リクエストは 301 しない）。クエリは呼び出し側で保持。
 * 遷移先は必ず src/App.tsx に実在するルートにすること（301ループと空振りを防ぐ）。
 */
const LEGACY_EXACT_REDIRECTS = {
  '/faq': '/ja/faq',
  '/blog': '/ja/blog',
  '/activity': '/ja/activity',
  '/activity-cn': '/zh/activity',
  '/contact': '/ja/contact',
  '/level-guide': '/ja/level-guide',
  '/cancel-policy': '/ja/cancel-policy',
  // 法務3ページ。旧ブランチは /privacy-policy だったが、HEAD の実ルートは /privacy
  '/privacy': '/ja/privacy',
  '/tokushoho': '/ja/tokushoho',
  '/terms': '/ja/terms',
  '/international': '/ja/international',
  // 地域ページ（2026-08-28）。素の /kawaguchi は App.tsx にルートが無く、
  // LangWrapper が lang="kawaguchi" と解釈してトップへ飛ばす＝着地内容が失われる
  '/kawaguchi': '/ja/kawaguchi',
  '/toda': '/ja/toda',
  '/login': '/ja/login',
  '/admin': '/ja/admin',
  '/venues': '/ja/venues',
  '/join': '/ja/join',
  '/shuttle-roadmap': '/ja/shuttle-roadmap',
  '/game': '/ja/game',
  '/tactics-board': '/ja/tactics-board',
  '/results/vol1': '/ja/results/vol1',
  '/results/vol2': '/ja/results/vol2',
  '/results/vol3': '/ja/results/vol3',
  '/chaoxianzu/activity': '/chaoxianzu/ja/activity',
  '/chaoxianzu/activity-cn': '/chaoxianzu/zh/activity',
  '/chaoxianzu/activity-kr': '/chaoxianzu/ko/activity',
  '/chaoxianzu/admin': '/chaoxianzu/ja/admin',
};

const LEGACY_ID_REDIRECTS = [
  [/^\\/blog\\/(\\d+)$/, '/ja/blog/'],
  [/^\\/tournaments\\/(\\d+)$/, '/ja/tournaments/'],
  [/^\\/activity\\/([^/]+)$/, '/ja/activity/'],
  [/^\\/activity-cn\\/([^/]+)$/, '/zh/activity/'],
  [/^\\/chaoxianzu\\/activity\\/([^/]+)$/, '/chaoxianzu/ja/activity/'],
  [/^\\/chaoxianzu\\/activity-cn\\/([^/]+)$/, '/chaoxianzu/zh/activity/'],
  [/^\\/chaoxianzu\\/activity-kr\\/([^/]+)$/, '/chaoxianzu/ko/activity/'],
];

// pathname を正規URLへ 301 する必要があれば遷移先パスを返す（不要なら null）。
function computeLegacyRedirect(pathname) {
  const p = (pathname !== '/' && pathname.endsWith('/')) ? pathname.slice(0, -1) : pathname;
  if (Object.prototype.hasOwnProperty.call(LEGACY_EXACT_REDIRECTS, p)) {
    return LEGACY_EXACT_REDIRECTS[p];
  }
  for (const [re, prefix] of LEGACY_ID_REDIRECTS) {
    const m = p.match(re);
    if (m) return prefix + m[1];
  }
  return null;
}

async function handleRequest(request, env) {
    const url = new URL(request.url);
    const pathname = url.pathname;

    // 管理画面ルートへのBasic認証ゲート（クレジット取引セキュリティ・チェックリスト対応）
    // ADMIN_GATE_USER / ADMIN_GATE_PASS が未設定の環境ではゲート無効（開発時など）
    if (/^\\/(ja\\/|zh\\/)?admin(\\/|$)/.test(pathname) && env.ADMIN_GATE_USER && env.ADMIN_GATE_PASS) {
      const auth = request.headers.get('Authorization') || '';
      const expected = 'Basic ' + btoa(env.ADMIN_GATE_USER + ':' + env.ADMIN_GATE_PASS);
      if (auth !== expected) {
        return new Response('Authentication required', {
          status: 401,
          headers: { 'WWW-Authenticate': 'Basic realm="kawabado admin"', 'Cache-Control': 'no-store' },
        });
      }
    }

    // ── 言語プレフィックスなしの旧URL → 正規URLへ 301 ─────
    // 管理ゲートの**後ろ**に置く（/admin は先に Basic 認証を通してから /ja/admin へ送る）。
    if (request.method === 'GET' || request.method === 'HEAD') {
      const legacyTarget = computeLegacyRedirect(pathname);
      if (legacyTarget) {
        return Response.redirect(url.origin + legacyTarget + url.search, 301);
      }
    }

    // /sitemap.xml → 動的生成
    if (pathname === '/sitemap.xml') {
      try {
        const xml = await generateSitemap(env);
        return new Response(xml, {
          headers: { 'Content-Type': 'application/xml; charset=utf-8' },
        });
      } catch (err) {
        return new Response(
          '<?xml version="1.0" encoding="UTF-8"?>\\n<!-- error: ' + err.message + ' -->\\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>',
          { status: 200, headers: { 'Content-Type': 'application/xml; charset=utf-8' } }
        );
      }
    }

    // /__debug エンドポイント（開発用）
    if (pathname === '/__debug') {
      const results = {};
      for (const p of ['/favicon.svg', '/assets/index-CoAYpyrw.css']) {
        try {
          const r = await env.ASSETS.fetch(new Request(url.origin + p));
          results[p] = { status: r.status };
        } catch (e) {
          results[p] = { error: e.message };
        }
      }
      return new Response(JSON.stringify(results, null, 2), {
        headers: { 'Content-Type': 'application/json' },
      });
    }

    // 学習者向けガイド（/guide/*・限定公開の静的HTML）は実ファイルをそのまま返す。
    // 拡張子なしで置いてあり（SPAフォールバック回避）、Content-Typeは _headers が付ける
    if (pathname.startsWith('/guide/')) {
      try {
        const guideRes = await env.ASSETS.fetch(request);
        if (guideRes.status < 400) return guideRes;
      } catch (_) {}
      return new Response('Not Found', { status: 404, headers: { 'Cache-Control': 'no-store' } });
    }

    /* ── 通行証の発行（学習アプリが AdvShell を開く前に1回呼ぶ）───────────
       Supabase のアクセストークンをこのWorkerが /auth/v1/user で検証し、
       通ったら署名付きCookieを返す。**JWT秘密鍵はWorkerに置かない。** */
    if (pathname === '/_course/pass') {
      if (request.method !== 'POST') {
        return new Response('Method Not Allowed', { status: 405, headers: { 'Cache-Control': 'no-store' } });
      }
      // 鍵が無い環境では門そのものが無効。呼ばれても害が無いよう素通しで終わる
      if (!env.AI_COURSE_ASSET_GATE_SECRET) {
        return new Response(JSON.stringify({ ok: true, gate: 'disabled' }), {
          status: 200, headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' },
        });
      }
      const bearer = (request.headers.get('Authorization') || '').replace(/^Bearer\\s+/i, '').trim();
      if (!bearer) return new Response('Unauthorized', { status: 401, headers: { 'Cache-Control': 'no-store' } });
      const supaUrl = env.VITE_SUPABASE_URL || env.SUPABASE_URL || '';
      const supaKey = env.VITE_SUPABASE_ANON_KEY || env.SUPABASE_ANON_KEY || '';
      if (!supaUrl || !supaKey) {
        return new Response('Service Unavailable', { status: 503, headers: { 'Cache-Control': 'no-store' } });
      }
      let sub = '';
      try {
        const who = await fetch(supaUrl + '/auth/v1/user', {
          headers: { Authorization: 'Bearer ' + bearer, apikey: supaKey },
        });
        if (!who.ok) return new Response('Unauthorized', { status: 401, headers: { 'Cache-Control': 'no-store' } });
        const body = await who.json();
        sub = String((body && body.id) || '');
      } catch (_) {
        // Supabase に届かないのは利用者の落ち度ではない。門を通せないので503（401にしない）
        return new Response('Service Unavailable', { status: 503, headers: { 'Cache-Control': 'no-store' } });
      }
      if (!sub) return new Response('Unauthorized', { status: 401, headers: { 'Cache-Control': 'no-store' } });
      const exp = Date.now() + COURSE_PASS_TTL_MS;
      const token = await signCoursePass(sub, exp, env.AI_COURSE_ASSET_GATE_SECRET);
      return new Response(JSON.stringify({ ok: true, exp: exp }), {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
          'Cache-Control': 'no-store',
          'Set-Cookie': COURSE_PASS_COOKIE + '=' + token
            + '; Path=/; Max-Age=' + Math.floor(COURSE_PASS_TTL_MS / 1000)
            + '; HttpOnly; Secure; SameSite=Lax',
        },
      });
    }

    /* ── 教材assetの門 ───────────────────────────────────────────
       既定は無効（AI_COURSE_ASSET_GATE!=='on' か 鍵未設定なら素通し）。
       対象は教材3チャンクだけで、index-*.js などサイト共通のassetは絶対に含めない。 */
    if (
      env.AI_COURSE_ASSET_GATE === 'on'
      && env.AI_COURSE_ASSET_GATE_SECRET
      && GATED_ASSET_PREFIXES.some((p) => pathname.startsWith(p))
    ) {
      const passed = await verifyCoursePass(
        request.headers.get('Cookie') || '', env.AI_COURSE_ASSET_GATE_SECRET
      );
      if (!passed) {
        return new Response('Forbidden', {
          status: 403,
          headers: { 'Cache-Control': 'no-store', 'X-Robots-Tag': 'noindex, nofollow' },
        });
      }
    }

    // 拡張子があるファイル（JS, CSS, 画像など）はenv.ASSETSで直接配信
    const hasExtension = /\\.[a-zA-Z0-9]+$/.test(pathname);
    if (hasExtension && !pathname.endsWith('.html')) {
      try {
        const assetResponse = await env.ASSETS.fetch(request);
        // _redirects のSPAフォールバックにより、存在しないアセットには index.html が
        // 200で返ってくる。それをそのまま返すと _headers の immutable ルールで
        // 「JSのURLに中身がHTML」がエッジに1年キャッシュされる事故になるため、
        // Content-Type が HTML のものはアセットとして返さない。
        const ct = (assetResponse.headers.get('Content-Type') || '');
        if (assetResponse.status < 400 && !ct.includes('text/html')) return assetResponse;
      } catch (_) {}
      // 見つからないアセットは index.html にフォールバックせず、キャッシュ不可の404を返す
      return new Response('Not Found', {
        status: 404,
        headers: { 'Cache-Control': 'no-store' },
      });
    }

    // ページ別のメタ・本文・JSON-LDを差し込んだHTMLを返す
    // （シェア時のプレビューと、JSを実行しないクローラーが読む本文のため）
    const ogpRoute = matchOgpRoute(pathname);
    let missing = false;
    if (ogpRoute) {
      try {
        const meta = await buildOgpMeta(ogpRoute, env, 'https://kawabado.com' + pathname);
        if (meta) {
          return new Response(injectOgp(meta), {
            status: 200,
            headers: {
              'Content-Type': 'text/html; charset=utf-8',
              'Cache-Control': 'no-cache, must-revalidate',
            },
          });
        }
        // 形は既知だがDBに無いURL（削除済み・下書きの大会/活動/記事）。
        // Reactは NotFound を描くがそれはJS実行後なので、ここで noindex を付ける。
        // 取得に失敗した（catchに入った）場合はDBの一時障害と区別できないので付けない
        missing = true;
      } catch (_) { /* 失敗時は共通HTMLにフォールバック */ }
    }

    // HTMLルートはWorkerに埋め込まれたindex.htmlを返す
    // HTMLは常に最新を取りに行かせる（中のJS/CSSはハッシュ付きURLなので安全に長期キャッシュできる）
    const headers = {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-cache, must-revalidate',
    };
    // ソフト404対策（2026-08-24）。既知ルートに一致しないURLは検索結果に出さない
    if (missing || !isKnownPath(pathname)) headers['X-Robots-Tag'] = 'noindex';
    // トップ系URLにはヒーロー画像のpreloadを注入してLCPを縮める（security側）。
    // 通常 / ・/ja/ ・/zh/ は上の injectOgp 側で先に返るのでここには来ないが、
    // メタ生成に失敗して素のindex.htmlへ落ちたときもLCPを落とさないよう残す
    const html = HOME_PATH_RE.test(pathname)
      ? INDEX_HTML.replace('</head>', HERO_PRELOAD + '\\n  </head>')
      : INDEX_HTML;
    return new Response(html, { status: 200, headers });
}

// セキュリティヘッダー。
// HTMLレスポンスはこのWorkerが new Response() で組み立てているため public/_headers が
// 適用されない（_headers が効くのは env.ASSETS 経由の静的ファイルのみ）。
// そのため全レスポンスにここで一括付与する。
const SECURITY_HEADERS = {
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Strict-Transport-Security': 'max-age=31536000',
  // マイクは AI講座の音声会話で自ドメインのみ使用
  'Permissions-Policy': 'geolocation=(), camera=(), payment=(), usb=(), microphone=(self)',
};

// CSPはまず Report-Only で運用し、違反レポートを確認してから強制モードへ切り替える。
// （いきなり強制すると決済・YouTube埋め込み・計測タグが黙って壊れるリスクがあるため）
const CSP_REPORT_ONLY = !SUPABASE_ORIGIN ? '' : [
  "default-src 'self'",
  "base-uri 'self'",
  "object-src 'none'",
  "frame-ancestors 'self'",
  "form-action 'self'",
  "script-src 'self' 'unsafe-inline' https://js.stripe.com https://www.googletagmanager.com https://connect.facebook.net",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob: https:",
  "font-src 'self' data:",
  "media-src 'self' blob: " + SUPABASE_ORIGIN,
  "connect-src 'self' " + SUPABASE_ORIGIN + ' ' + SUPABASE_ORIGIN.replace(/^https:/, 'wss:') +
    ' https://api.stripe.com https://www.google-analytics.com https://www.facebook.com',
  'frame-src https://js.stripe.com https://hooks.stripe.com https://www.youtube.com https://www.youtube-nocookie.com',
].join('; ');

export default {
  async fetch(request, env) {
    const response = await handleRequest(request, env);
    const out = new Response(response.body, response);

    for (const [k, v] of Object.entries(SECURITY_HEADERS)) out.headers.set(k, v);
    if (CSP_REPORT_ONLY) out.headers.set('Content-Security-Policy-Report-Only', CSP_REPORT_ONLY);

    // staging・Preview環境（本番ホスト以外）は検索エンジンにインデックスさせない。
    // 既存のステータス・ヘッダー（Cache-Control等）はそのまま維持し、
    // X-Robots-Tag だけを追加する。本番 kawabado.com には付けない。
    const url = new URL(request.url);

    // 管理画面・ログイン・受講者アプリ等は検索結果に出さない。
    // 画面側にも robots メタを入れているが、あれはJS実行後。ここはJSを実行しない
    // クローラーにも確実に効く（robots.txt は「クロールするな」であって
    // 「インデックスするな」ではないので、両方が要る）
    // ⚠️ ここで別の Response を作り直すと、上で付けたセキュリティヘッダーとCSPが
    //    管理画面・ログインだけ落ちる（統合時に一度そうなった）。out に足して out を返す
    if (isPrivatePath(url.pathname)) {
      out.headers.set('X-Robots-Tag', 'noindex, nofollow');
      return out;
    }

    const host = url.hostname;
    if (!PRODUCTION_HOSTS.includes(host)) {
      out.headers.set('X-Robots-Tag', 'noindex, nofollow');
    }
    return out;
  },
};
`;

  return workerContent;
}

// 直接実行されたときだけ dist を読み書きする（テストからは buildWorkerSource だけを使う）
if (process.argv[1] && process.argv[1].endsWith('generate-worker.mjs')) {
  const indexHtml = readFileSync('dist/index.html', 'utf8');
  writeFileSync('dist/_worker.js', buildWorkerSource(indexHtml));
  console.log('✅ Generated dist/_worker.js with embedded index.html and sitemap.xml handler');

  // 配信中のビルドを名乗る小さなファイル（2026-08-17）。
  // 開いたままのタブは古いJSを持ち続けるので、直したはずの不具合が生徒の画面では
  // 直っていない、という事故が起きる（実際に起きた）。アプリはこれを見て
  // 「新しい版があります」と知らせる。index chunkのハッシュ＝ビルドの同一性。
  const buildId = (indexHtml.match(/assets\/index-([A-Za-z0-9_-]+)\.js/) ?? [])[1] ?? 'unknown';
  writeFileSync('dist/version.json', JSON.stringify({ build: buildId }));
  console.log(`✅ Generated dist/version.json (build=${buildId})`);
}
