/**
 * ビルド後にdist/index.htmlを読み取り、
 * 正しいハッシュを埋め込んだdist/_worker.jsを自動生成するスクリプト。
 * CF Pages v3 の Clean URLs バグを回避するため index.html を Worker に埋め込む。
 */
import { readFileSync, writeFileSync } from 'fs';

const indexHtml = readFileSync('dist/index.html', 'utf8');
// バッククオートをエスケープ
const escapedHtml = indexHtml.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const workerContent = `// Auto-generated by scripts/generate-worker.mjs
// CF Pages v3 Clean URLs 500エラーを回避するためindex.htmlを直接埋め込む

const INDEX_HTML = \`${escapedHtml}\`;

// sitemap.xml 動的生成
async function generateSitemap(env) {
  const staticUrls = [
    { path: '',              priority: '1.0', freq: 'weekly' },
    { path: 'activity',      priority: '0.9', freq: 'weekly' },
    { path: 'level-guide',   priority: '0.8', freq: 'monthly' },
    { path: 'faq',           priority: '0.8', freq: 'monthly' },
    { path: 'blog',          priority: '0.7', freq: 'weekly' },
    { path: 'cancel-policy', priority: '0.5', freq: 'monthly' },
  ];

  const langs = ['ja', 'zh'];
  let urls = '';

  // Supabase REST API で公開中の大会を取得（失敗しても静的URLは返す）
  let tournaments = [];
  try {
    const supabaseUrl = env.VITE_SUPABASE_URL || env.SUPABASE_URL || '';
    const supabaseKey = env.VITE_SUPABASE_ANON_KEY || env.SUPABASE_ANON_KEY || '';
    if (supabaseUrl && supabaseKey) {
      const res = await fetch(
        supabaseUrl + '/rest/v1/tournaments?select=id,updated_at&visibility=eq.published',
        {
          headers: {
            apikey: supabaseKey,
            Authorization: 'Bearer ' + supabaseKey,
          },
        }
      );
      if (res.ok) tournaments = await res.json();
    }
  } catch (_) {}

  for (const lang of langs) {
    for (const u of staticUrls) {
      const loc = u.path === ''
        ? 'https://kawabado.com/' + lang + '/'
        : 'https://kawabado.com/' + lang + '/' + u.path;
      urls += '\\n  <url>\\n    <loc>' + loc + '</loc>\\n    <changefreq>' + u.freq + '</changefreq>\\n    <priority>' + u.priority + '</priority>\\n  </url>';
    }
    for (const t of tournaments) {
      const lastmod = t.updated_at ? t.updated_at.slice(0, 10) : '';
      urls += '\\n  <url>\\n    <loc>https://kawabado.com/' + lang + '/tournaments/' + t.id + '</loc>' + (lastmod ? '\\n    <lastmod>' + lastmod + '</lastmod>' : '') + '\\n    <changefreq>daily</changefreq>\\n    <priority>0.9</priority>\\n  </url>';
    }
  }

  return '<?xml version="1.0" encoding="UTF-8"?>\\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' + urls + '\\n</urlset>';
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const pathname = url.pathname;

    // /sitemap.xml → 動的生成
    if (pathname === '/sitemap.xml') {
      try {
        const xml = await generateSitemap(env);
        return new Response(xml, {
          headers: { 'Content-Type': 'application/xml; charset=utf-8' },
        });
      } catch (err) {
        return new Response(
          '<?xml version="1.0" encoding="UTF-8"?>\\n<!-- error: ' + err.message + ' -->\\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>',
          { status: 200, headers: { 'Content-Type': 'application/xml; charset=utf-8' } }
        );
      }
    }

    // /__debug エンドポイント（開発用）
    if (pathname === '/__debug') {
      const results = {};
      for (const p of ['/favicon.svg', '/assets/index-CoAYpyrw.css']) {
        try {
          const r = await env.ASSETS.fetch(new Request(url.origin + p));
          results[p] = { status: r.status };
        } catch (e) {
          results[p] = { error: e.message };
        }
      }
      return new Response(JSON.stringify(results, null, 2), {
        headers: { 'Content-Type': 'application/json' },
      });
    }

    // 拡張子があるファイル（JS, CSS, 画像など）はenv.ASSETSで直接配信
    const hasExtension = /\\.[a-zA-Z0-9]+$/.test(pathname);
    if (hasExtension && !pathname.endsWith('.html')) {
      try {
        const assetResponse = await env.ASSETS.fetch(request);
        if (assetResponse.status < 400) return assetResponse;
      } catch (_) {}
    }

    // HTMLルートはWorkerに埋め込まれたindex.htmlを返す
    // HTMLは常に最新を取りに行かせる（中のJS/CSSはハッシュ付きURLなので安全に長期キャッシュできる）
    return new Response(INDEX_HTML, {
      status: 200,
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Cache-Control': 'no-cache, must-revalidate',
      },
    });
  },
};
`;

writeFileSync('dist/_worker.js', workerContent);
console.log('✅ Generated dist/_worker.js with embedded index.html and sitemap.xml handler');
